### ISSUE TITLE
Bot Framework v4 Luis does't have the method QueryAsync

### ISSUE THREAD

**Issue by ciceka** [Microsoft/botbuilder-dotnet#1003]
Hello,

I am program the Bot with the new Framework v4 and want to use the method QueryAsync but there isn't the method in the new Framework v4 in Luis.

Is there any alternative for this method ? 

![image](https://user-images.githubusercontent.com/42337825/46460491-678ef000-c7bc-11e8-996f-f4e3b06eace8.png)

**Comment by cleemullins** [comment]
@ciceka, If you look at the [LUIS Sample here](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/12.nlp-with-luis), you'll see a class called [LuisBot.cs](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/12.nlp-with-luis/LuisBot.cs).

In LuisBot, you'll see this code:
```
var recognizerResult = await _services.LuisServices[LuisKey].RecognizeAsync(turnContext, cancellationToken);
var topIntent = recognizerResult?.GetTopScoringIntent();
if (topIntent != null && topIntent.HasValue && topIntent.Value.intent != "None")
{
    await turnContext.SendActivityAsync($"==>LUIS Top Scoring Intent: {topIntent.Value.intent}, Score: {topIntent.Value.score}\n");
}
```

If I understand your question correctly, this should do what you want.
