### ISSUE TITLE
MicrosoftAppCredentials returns expired token

### ISSUE THREAD

**Issue by thschuetze** [Microsoft/botbuilder-dotnet#1008]
Added the same bug in BotBuilder-v3 repo, but it does exist in v4 as well and will most likely get more attention here. See v3 bug here: https://github.com/Microsoft/BotBuilder-V3/issues/4

Summary:
MicrosoftAppCredentials.GetTokenAsync returns an expired token when the cached token and the cached auto refresh task token have expired.

[Copied from the other issue]
## Version
latest v3 (reproduced it in 3.15.3 and 3.16.1) and latest v4 (reproduced in 4.0.7)

## Describe the bug
Our bots fail to respond to the first message every morning. What we see in AppInsights is that the botframework token endpoint is successfully called, but the call to the conversations endpoint (triggered by context.PostAsync) fails with 401 Unauthorized.
After some investigation we think we have found a bug in the MicrosoftAppCredentials class.

The bot has to be talked to at least twice. First to get an initial token and 10 minutes later to kick off an auto refresh task. Then it needs to be completely idle for 60 more minutes so the cached token and the token retrieved by the auto refresh task have expired. 

In that scenario the code in MicrosoftAppCredentials.GetTokenAsync (line 197) assumes that the last cached task will return a valid token (since it completed but with a different token than the cached one) and it will use that expired token in the request (ProcessHttpRequestAsync).

## To Reproduce
Easiest way to reproduce is with a simple ConsoleApp (with the Microsoft.Bot.Builder nuget) calling MicrosoftAppCredentials.GetTokenAsync and verifying the token expiration locally. 

    class Program
    {
        private const string AppId = "valid app id";
        private const string AppSecret = "valid app secret";
        private static readonly MicrosoftAppCredentials Credentials = new MicrosoftAppCredentials(AppId, AppSecret);

        static void Main()
        {
            GetAndVerifyToken();
            while (true)
            {
                if (Console.ReadLine() == "q")
                    break;

                GetAndVerifyToken();
            }
        }

        private static async Task GetAndVerifyToken()
        {
            var tokenString = await Credentials.GetTokenAsync().ConfigureAwait(false);
            var token = new System.IdentityModel.Tokens.Jwt.JwtSecurityToken(tokenString);
            Console.WriteLine($"[{DateTime.Now}] {(DateTime.UtcNow > token.ValidTo ? "ERROR: Token expired at: " : "Token valid until: ")} {token.ValidTo.ToLocalTime()}");
        }
    }

1) start the console app -> gets a new Token that expires in 60 minutes
2) 10 minutes later hit Enter -> initiates an auto refresh token task, that gets a token that expires in 60 minutes (note: that new token is never put in the tokenCache, just the task is cached in the tokenTaskCache)
3) another 60 minutes later it Enter again -> GetTokenAsync returns an expired token

It is also possible to reproduce this issue with sending real messages via ConnectorClient.Conversations.SendToConversationWithHttpMessagesAsync, but that requires a bit more setup (activity with valid channel and conversation accounts, etc)

       private static async Task SendMessage()
        {
            var message = CreateMessage();
            MicrosoftAppCredentials.TrustServiceUrl(message.ServiceUrl);
            var client = new ConnectorClient(new Uri(message.ServiceUrl), Credentials);
            var response = await client.Conversations.SendToConversationWithHttpMessagesAsync(message.Conversation.Id, message).ConfigureAwait(false);
        }

## Expected behavior
MicrosoftAppCredentials.GetTokenAsync should not return expired tokens.
A simple fix would be to check TokenExpired(oAuthTokenTask.Result.access_token) instead of comparing to the cached token in line 197.

## Screenshots
The output of the console app
![image](https://user-images.githubusercontent.com/20794834/46613488-ad78ea80-cb13-11e8-9b7a-3e5143a735c7.png)

## Additional context
I guess for a lot of bots out there this issue does not surface because most will try to send a "Typing" activity to the user before sending the actual message and no one really notices a missing "typing.."

We have a distributed bot network where a central bot delegates intents to other completely independent bots (running in separate web apps). The central bot sends the typing, but the actual response to the user is sent by one of the "sub bots".

[bug]
[dotnet]

**Comment by jwiley84** [comment]
https://github.com/Microsoft/BotBuilder-V3/issues/4

**Comment by cleemullins** [comment]
This should be resolved by the 4.2.1 release (pending now). 
https://github.com/Microsoft/botbuilder-dotnet/releases/tag/4.2.1
