### ISSUE TITLE
Standard Bot Diagnostics Endpoint

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#1015]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Yes. It can be hard to diagnose deployment problems.

**Describe the solution you'd like**
A standard endpoint on the bot. This could be somewhat open ended - and developer extensible. The trick would be having the Azure Portal and command line tools know about this endpoint.

**Comment by benbrown** [comment]
Would this belong at the sample level or the SDK level?

The SDK doesn't set up any web endpoints by itself.  Could the SDK help to expose the right info and let developers ingest it or use it however they like? The bot knows best about all its internal dependencies.

We'll need to think about this and plan for it in the long term.

**Comment by benbrown** [comment]
@johnataylor Can you refile this on the top level Botbuilder repo? THANKS <3

**Comment by johnataylor** [comment]
opening issue at root repo https://github.com/Microsoft/BotBuilder/issues/5098
