### ISSUE TITLE
BotFrameworkAdapter is missing an interface that defines its contract with integration

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#1028]
**Is your feature request related to a problem? Please describe.**
The BotFrameworkAdapter derives from BotAdapter and its easy to see how other alternative implementations of the BotFrameworkAdapter could be created. For example, if an application wanted
to provide its own TurnContext.

However, because there is no interface modeling the interaction between the integration layer (or any alternative integration layer for that matter) it is hard to make that layer generic. As it is today, providing a new adapter means writing new integration from scratch.

**Describe the solution you'd like**
An interface that captures the relationship between integration and the adapter. Specifically the integration code creates a BotFrameworkAdapter and calls ProcessMessageRequestAsync on it. There is some abstraction with the add singleton service injection but it would be much more effective if the dependency was modeled with an interface. A design like the following would help:

```
public interface IAdapterIntegration
{
  Task<InvokeResponse> ProcessActivityAsync(
    string authHeader,
    Activity activity,
    BotCallbackHandler callback,
    CancellationToken cancellationToken);
}
```

and then...

```
public class BotFrameworkAdapter: BotAdapter, IAdapterIntegration
{
  // implementation
}
```

Many applications will undoubtedly provide their own integration with the ASP stack, for example, a base class for controllers that are also bots, or alternatively directly against some queuing infrastructure. But again its hard to make this code generic without the contract being modeled explicitly with an interface.

**Describe alternatives you've considered**
Some of the critical methods on BotFrameworkAdapter could be made virtual. This would open some doors but ultimately it would lead to more complexity that simply modeling the contract with an interface.

**Additional Context**
Providing an interface for this relationship would help with writing unit tests that inject alternative implementation.

**Comment by sgellock** [comment]
please review the console sample and the webAPI samples
