### ISSUE TITLE
The NumberPrompt<T> class should have some constraints on its generic type parameter

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#1029]
**Is your feature request related to a problem? Please describe.**
The type `T` should be number-like, such as of type IComparable, IComparable\<T>, IConvertible, IEquatable\<T>. The current implementation throws at run-time if T is not a supported type. I'd be much happier if this were caught at compile time.

**Describe the solution you'd like**
Add appropriate `where` clauses to the type definition.

**Describe alternatives you've considered**
Document what the supported types are and hope the devs discover and read that documentation.

**Additional context**
In NumberPrompt\<T>.OnRecognizeAsync, the list of "supported" types is too short, and possibly overly restrictive:
```csharp
// Try to parse value based on type
var text = results[0].Resolution["value"].ToString();
if (typeof(T) == typeof(float))...
else if (typeof(T) == typeof(int))...
else if (typeof(T) == typeof(long))...
else if (typeof(T) == typeof(double))...
else if (typeof(T) == typeof(decimal))...
else
{
    throw new NotSupportedException($"NumberPrompt: type argument T of type 'typeof(T)' is not supported");
}
```

[enhancement]

**Comment by sgellock** [comment]
Look at typescript as well please

**Comment by JonathanFingold** [comment]
Just adding `where T : struct` doesn't really seem to address the issue. For instance, if they try to use a `NumberPrompt<short>`, devs will still get a mysterious run-time exception that does not give them enough information to go on without diving into the SDK implementation code.

The "Numeric" types could be expanded to all the built-in C# number types:
byte, sbyte, short, ushort, int, uint, long, ulong, float, double, decimal.

The constraint could include:
```csharp
where T : IComparable, IComparable<T>, IEquatable<T>
```

The type checking in `OnRecognizeAsync` could be relaxed or extended to include something like:
```csharp
if (typeof(T).IsAssignableFrom(typeof(double)))...
```
