### ISSUE TITLE
Updated Recognizer-text to 1.1.2 (Just released)

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#1034]
The latest Recognizer-Text library is 1.1.2. We should consider updating this dependency to pickup the new languages, features, and bug fixes. 

Note: The [NPMJS repo](https://www.npmjs.com/package/@microsoft/recognizers-text-suite) has **NOT been updated**. I've reached out to the team to get an update on this. 

The release notes (via the Recognizer team) are:
- Choice recognizer support for French and German;
- Support for month-to-month DateTime ranges in Chinese;
- Bug fixes for corner cases in DateRange resolution in English;
- Small additions to currency units in English;
- Improved support for DateTime recognition in Traditional Chinese (partial);
- Extensions to PhoneNumber recognition;
- Bug fix in TimeZone resolution (under Preview);
- Bug fix for compound Duration timex expressions;
- Fix in TimexHelpers.ExpandDateTimeRange handling of end times;
- Improvements in URL and e-mail address extraction;
- Support for time-of-day in Chinese DateTime;
- Extensions for Dutch recognition of large numbers;
- Improved support for languages that use multiple decimal separators;
- Minor Unit fixes in English, French, and Chinese.

**Comment by johnataylor** [comment]
fixed with #1036
