### ISSUE TITLE
Add a button list style to the Choices for prompts

### ISSUE THREAD

**Issue by rosskyl** [Microsoft/botbuilder-dotnet#1057]
**Is your feature request related to a problem? Please describe.**
I am upgrading a v3 bot to v4 and am working on the prompts. I am currently using a ConfirmPrompt but would like to use buttons rather than just text.

**Describe the solution you'd like**
It would be great to have a button list style that would display the options as a card action inside a hero card attachment.

**Describe alternatives you've considered**
I have looked at creating a hero card and adding card actions to it and adding that to the prompt activity. However this displays the options "`(1) Yes or (2) No`" as text above the card still.

**Additional context**
This is what I am looking for:
![image](https://user-images.githubusercontent.com/9472151/47452613-4ce2e200-d790-11e8-8f14-e6c774e9b57e.png)
I do have some custom css styling to in the webchat.

[enhancement]

**Comment by sgellock** [comment]
Adaptive Cards should be able to address this issue for the customer

**Comment by nhadro** [comment]
I'm working with this developer on this and the primary channel we're using is Skype for Business which doesn't support many cards from what I've seen.

**Comment by yochay** [comment]
This issue was moved to Microsoft/BotBuilder#5121
