### ISSUE TITLE
HttpClient disposal anti-pattern

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#106]
There are several instances of [the `HttpClient` disposal anti-pattern](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/) within the code base. Under a sufficient amount of load this will cause socket level resource exhaustion that will result in intermittent connection failures and, ultimately, prevent bots from scaling.

The following classes are currently using this anti-pattern:

* Microsoft.Bot.Builder.Ai
   * Translator
* Microsoft.Bot.Builder.Connector
   * EndorsementsRetriever
   * MicrosoftAppCredentials
   * AttachmentsEx

**Comment by cleemullins** [comment]
I have most of these tagged for looking at. Thanks for driving home that I need to fix them sooner rather than later. 

+1

**Comment by RyanDawkins** [comment]
I've made a start at this and for #107 on my fork.

I've started on this for the QnAMaker and the Translator class.

https://github.com/RyanDawkins/botbuilder-dotnet/commit/83a51220b5bec644c30c13a2cbb98cd24c3801a3

I have implemented the changes for the Translator and the QnA maker and I'm in the process of testing.

**Comment by cleemullins** [comment]
Thanks Ryan! I was actually just reading about best practices around HttpClient and will look forward to seeing your PR.

**Comment by RyanDawkins** [comment]
Just tested the QnA version! I'm about to setup Luis to make sure that is working too.

**Comment by cleemullins** [comment]
Multiple smaller PRs are fine with me. No need for one giant one...

________________________________

**Comment by RyanDawkins** [comment]
Here you go!
 https://github.com/Microsoft/botbuilder-dotnet/pull/122

**Comment by cleemullins** [comment]
Pending PR for the remaining places this code existed: #133

**Comment by cleemullins** [comment]
Fixed. Thanks.
