### ISSUE TITLE
Add a Duration property to media card types

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#1062]
**Is your feature request related to a problem? Please describe.**
The [cards spec](https://github.com/Microsoft/BotBuilder/blob/master/specs/botframework-activity/botframework-cards.md) was [updated to include a media duration](https://github.com/Microsoft/BotBuilder/pull/5094). I can't find a corresponding member in the Microsoft.Bot.Schema namespace, or a PR containing one.

**Describe the solution you'd like**
1. Add a `Duration` property to media cards.
1. Bonus: update the **06.using-cards** samples.

**Describe alternatives you've considered**
Just pointing users to the Card schema spec.

**Additional context**
https://github.com/Microsoft/BotBuilder/pull/5094

[enhancement]

**Comment by yochay** [comment]
Need to tag botbuilder and regenerate schema lib for C# and JS (and Java , Python).

**Comment by JonathanFingold** [comment]
@yochay Do you have an ETA? I was hoping to use this issue to flag when the fix was in and I could update the docs.

**Comment by yochay** [comment]
This issue was moved to Microsoft/BotBuilder#5120

**Comment by yochay** [comment]
Moved to https://github.com/Microsoft/BotBuilder/issues/5121 to track across all SDK langauges
