### ISSUE TITLE
Display difference of choices in Prompt Options in Emulator and web Chat

### ISSUE THREAD

**Issue by RavindraVarmaa** [Microsoft/botbuilder-dotnet#1067]
I am trying to provide a set of choice to the user using PromptOptions and ChoiceFactory in Bot Framework V4. When tested on Emulator I get the choices as suggestions:

![choice_emulator](https://user-images.githubusercontent.com/43398656/47631116-8b9ae280-db6a-11e8-8d8f-0d1e5f131ea3.png)

but when testing on the Webchat I get the choice in indexed format like:
1.S
2.M
3.L
4.XL
5.XXL
6.XXXL

CODE:
step.PromptAsync("cardPrompt", new PromptOptions { Prompt = MessageFactory.Text("Please select the size of '" + userProfile.Productname + "' that you need."), Choices = ChoiceFactory.ToChoices(new List<string> { "S", "M", "L", "XL", "XXL", "XXXL" }) }, cancellationToken);

Would be helpful  if anyone can provide suggestions on how can we achieve the choices as separate suggestion box.

**Comment by yochay** [comment]
Please try 4.1 bits, as soon as they become available (later today). this should be fixed.
