### ISSUE TITLE
QnAMaker HttpClient disposal anti-pattern

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#107]
I've already filed #106 regarding some issues regarding the `HttpClient` disposal anti-pattern, but `QnAMaker` is a little more nuanced. The `QnAMaker` class at least holds onto its `HttpClient` instance in a field and will reuse it across calls to an instance, but should someone dispose of the `QnAMaker` instance it will also dispose of that underlying `HttpClient`. This could lead to developers to using the `QnAMaker` class in a **non**-singleton style and thus lead to the same resource starvation issues as mentioned in #106.

Recommend moving the `HttpClient` into a `static` field in the class and removing the `IDisposable` implementation altogether.

**Comment by cleemullins** [comment]
Thanks. I'll take a look at this shortly.

**Comment by cleemullins** [comment]
The PR to fix this is pending review. I took the simple approach of just making it static to the QnA Maker component. I Need to do this same thing for other components next...

**Comment by cleemullins** [comment]
This is closed out now.
