### ISSUE TITLE
CosmosDB : Method not found: Microsoft.Azure.Documents.Client.DocumentClient.UpsertDocumentAsync.

### ISSUE THREAD

**Issue by utkarsh24** [Microsoft/botbuilder-dotnet#1072]
Hi,

I am using cosmosDB provider for conversation state storage, and using AutoSaveStateMiddleware , with botFramework V4 4.0.8

recently i have upgraded Microsoft.Azure.DocumentDB.Core package from V 1.9.1 to V 2.1.3

I get following error when autoSaveStateMiddleware try to save state to cosmosDB

Exception :

-------------------------------
Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.Client.DocumentClient.UpsertDocumentAsync(System.String, System.Object, Microsoft.Azure.Documents.Client.RequestOptions, Boolean)'.

-----------------------------

Trace 
----------------------------------
   at Microsoft.Bot.Builder.Azure.CosmosDbStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Bot.Builder.Azure.CosmosDbStorage.WriteAsync(IDictionary`2 changes, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotState.SaveChangesAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotState.cs:line 96
   at Microsoft.Bot.Builder.BotStateSet.SaveAllChangesAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotStateSet.cs:line 73
   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\AutoSaveStateMiddleware.cs:line 61

**Comment by drub0y** [comment]
You can't upgrade across major versions like that safely as major version changes have breaking changes. So in this case you need to stay on 1.x.

**Comment by utkarsh24** [comment]
I don't this is true for bot framework V4 as bot framwork Microsoft.Bot.Builder.Core project has Microsoft.Azure.DocumentDB.Core nuget package reference of Version 2.1.2

**Comment by drub0y** [comment]
You're right, it does reference `2.1.2`. It sounds like you're somehow ending up with a mismatched version in your build though.

Can you open up NuGet Package manager at the solution level and go to the Consolidate tab and ensure that you don't somehow, somewhere have a reference to a different version of that package that could be stepping on the `2.x` version of that package?

Another, more advanced, step you can take is to go to the `\bin\Debug` directory for the bot web app project and double check the actual version of the `Microsoft.Azure.DocumentDB.Core.dll` that is ending up there as that's ultimately the version that will be loaded at runtime.

**Comment by utkarsh24** [comment]
Hi  @Drew Marsh ,

I have already checked documentDB package in Consolidate tab that all the projects are referring the same package,

I have also published the application using self contained mode and confirmed DocumentDB dll version to 2.1.2.

But still get the same error.

Interestingly while publishing the app as self contained i found following error on error list but published done successfully...

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. 
 WK.Drago.Service -> WK.Drago.Contract.Service -> Microsoft.Azure.DocumentDB.Core 2.1.2 -> System.Net.NetworkInformation 4.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0) 
 WK.Drago.Service -> WK.Drago.Contract.Service -> Microsoft.Azure.DocumentDB.Core 2.1.2 -> System.Net.NameResolution (>= 4.0.0)	WK.Drago.WebApi	projectPath\proejctName.csproj	0	

```

**Comment by sgellock** [comment]
we believe this has been addressed in the 4.1.x release of the core Bot Framework SDK.

**Comment by CoHealer** [comment]
Hi @utkarsh24. Have you been able to attempt a repro using the updated SDK?

**Comment by utkarsh24** [comment]
Thanks @sgellock and @CoHealer for your help, I have upgraded bot framework  version to 4.1.5 and it solved the issue.
