### ISSUE TITLE
Bot Framework v4, Luis returning Null for Entities 

### ISSUE THREAD

**Issue by Adityagrao** [Microsoft/botbuilder-dotnet#1073]
I am using Bot Framework v4, when I query with the endpoint URL I am getting this response

````javascript
{
  "query": "add event with aditya@gmail.com",
  "topScoringIntent": {
    "intent": "Calendar.Add",
    "score": 0.264734924
  },
  "entities": [],
  "sentimentAnalysis": {
    "label": "positive",
    "score": 0.965832
  }
}
````

I have given entity "email" for my Intent, When I test the same utterance on LUIS web, It shows me my Entity.
![image](https://user-images.githubusercontent.com/11465032/47705026-69c55c80-dc4b-11e8-8786-2f3e27b03754.png)

**Comment by Zerryth** [comment]
@Adityagrao you mention v4, but **which SDK** specifically are you using?

LMK, and I'd be happy to investigate further

**Comment by Zerryth** [comment]
Ok, looks like we will **need more of your bot code** @Adityagrao to repro what you're encountering.

Using the C# sample 51.CafeBot, was able to successfully get the entity extracted from the LUIS results

![image](https://user-images.githubusercontent.com/35248895/47877219-9f4b8080-ddd8-11e8-8e0f-fa56c5f6dfba.png)


![image](https://user-images.githubusercontent.com/35248895/47877187-8e027400-ddd8-11e8-8046-98e8d07d6e41.png)

**Comment by Zerryth** [comment]
Note: did you make sure to publish your changes to your LUIS model to make them reachable to your bot?

**Comment by Adityagrao** [comment]
Fixed, All I had to do was publish in Luis

**Comment by Zerryth** [comment]
Awesome!

(I've done that before myself)
