### ISSUE TITLE
IAdapaterIntegration availability

### ISSUE THREAD

**Issue by nimbusparis** [Microsoft/botbuilder-dotnet#1075]
I want to develop a bot targeting Telegram and I would like to create my own adapter as shown in the console bot sample but I also want to fit in the standard process defined in other samples that use `UseBotFramework` method.
After searching in code, I've seen that it get an instance of adapter that implements `IAdapterIntegration` from dependency injection.
This interface had been added 11 days ago, some days after the last release (15 days ago).
When the next release is planned in order I use this interface for my adapter?
Regards

**Comment by jwiley84** [comment]
Hi @nimbusparis!

The myget feed [here](https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily) has all the daily releases! Chances are high that if the interface was added, it will be in the daily releases there.

**Comment by johnataylor** [comment]
@nimbusparis

We hope to be getting 4.1 on the NuGet feed today. This should include this interface and the related dependency injection.
