### ISSUE TITLE
FlexObject::Clone issues

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#108]
First, `FlexObject::Clone` actually deserializes to a more specific subclass of `StoreItem` which could lead to some very strange behavior. A couple of scenarios that this would be produce unexpected results for:

* You're just cloning a "raw" `FlexObject` instance... why would you get back a `StoreItem`?
* You're cloning a subclass of `StoreItem`, maybe a `FooItem`... one would expect an instance of `FooItem` to come back, not just a `StoreItem`.

At bare minimum, the `FlexObject::Clone` implementation should produce an instance of the exact type that is being cloned (e.g. use `this.GetType()`).

Bigger picture, [implementing `ICloneable` in .NET is generally frowned upon these days for many reasons](http://codinghelmet.com/?path=howto/implement-icloneable-or-not), this being one of them. Therefore, I strongly suggest reconsidering whether the Bot Framework support any type of cloning at all. As a .NET user, I don't expect it because I am already aware of this can of worms. Guidance can always be given to those who might find a need for cloning to implement it themselves.

**Comment by cleemullins** [comment]
FlexObject is depricated in #425
