### ISSUE TITLE
User location

### ISSUE THREAD

**Issue by nimbusparis** [Microsoft/botbuilder-dotnet#1080]
Any plan to handle user location for channels (ie. Telegram) that support it? 
Can we expect to find a dedicated button on bot emulator?

**Comment by peterbozso** [comment]
I think you should take a look at this one: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Dialogs.Location
At the moment it supports Facebook Messenger's native location picker (not Telegram's), but based on this I think you could add support for Telegram as well - and submit a PR with your implementation, of course! ;)

**Comment by nimbusparis** [comment]
I will have a look but I had something more "early" in pipeline since Telegram had "live location features" that not block the dialog with the user.
I think I will intercept it in Adapter.
