### ISSUE TITLE
Not able to pass the strict filters in GetAnswerAsync using Microsoft.Bot.Builder.AI.QnA

### ISSUE THREAD

**Issue by mechaita** [Microsoft/botbuilder-dotnet#1083]
### [Github issues]
In Microsoft.Bot.Builder.AI.QnA,  Not able to pass the strict filters in GetAnswerAsync. 

I want to send different values to the metadata at different times through my bot code in GetAnswerAsync. For eg. In one scenario, I want to call GetAnswerAsync where strict filter is {metadata name = “namexyz” and metadata value = “valuexyz”} 
And in another scenario, , I want to call GetAnswerAsync where strict filter is {metadata name = “namexyz” and metadata value = “valueabc”}

As per the code here : https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs 
 strictfilters are taken at the time of initializing the QnAMaker service using QnAMaker options. Initializing in ctor will require me to create different qnaservices , since I need to use different metadata name-value pairs in different GenerateAnswer calls. There will be too many name-value combinations if I do this in ctor. I want to control strict filters from GenerateAnswer.

**Comment by stevengum** [comment]
@mechaita if you're running into issues in issuing a PR, please email me or continue emailing the thread with the SDK team and someone will assist.
