### ISSUE TITLE
Add speech support for Microsoft.Bot.Builder.TemplateManager

### ISSUE THREAD

**Issue by AlfredoMS** [Microsoft/botbuilder-dotnet#1084]
When adding Cortana support for the enterprise template (https://github.com/Microsoft/AI/tree/master/templates/Enterprise-Template), I noticed it used TemplateManager extensively, however the Activities it rendered where not suitable for voice scenarios.

**Describe the solution you'd like**
To support voice there needs to be a way to set the ssml/speak property on each message. The simples option would be given a flag, set the speak property to be equal to the text property.

To support Cortana template manger should be able to handle input hints. I propose adding an optional parameter to ReplyWith and RenderTemplate
```
public async Task ReplyWith(ITurnContext turnContext, string templateId, object data = null, string inputHint = InputHints.IgnoringInput)

public async Task<Activity> RenderTemplate(ITurnContext turnContext, string language, string templateId, object data = null, string inputHint = InputHints.IgnoringInput)
```

Cortana is very sensible to inputHints. If you want to send more than one message per turn, all messages should use inputHint.IgnoreInput and only the last one can be either AcceptingInput or ExpectingInput.
I feel IgnoringInput is a good default so people don't have to think about it, and only need to be explicit when actually expecting a reply from the user.

Another option for default value is AcceptingInput, which means user can reply anytime, however this means developers have to be careful of sending multiple messaes in a row.

**Describe alternatives you've considered**
TemplateManager already has a way to provide a function that creates a custom activity, this could work as a workaround for speach, but it would mean that all your messages need a custom renderer so it would be bettter if this is integrated into the library.

[enhancement]

**Comment by tomlm** [comment]
I don't think we need to do this.  Reasons are
1. You can already assign InputHint as part of the template that returns the activity.
2. You can modify the Activity that is returned by a template to set the input hint.
3. It is trivial to create extension method which calls normal template and sets the input hint.
4. It's actually probably a lot more effective to collect activities to be sent and then mark all of their input hint the same except for the last one.  This could easily be done via a piece of middleware.
