### ISSUE TITLE
FlexObject indexer returns dynamic which forces dynamic programming model even if developer wants to stick to strongly typed model

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#109]
Currently the indexer of the `FlexObject` class is typed as `dynamic`. The problem with this is that, as a .NET developer, if I'm choosing *not* to use the dynamic programming model of `FlexObject` and am trying to get/set values through the indexer, it is "forcing" me into the dynamic model. 

The indexer should instead be typed as `object` which would prevent developers being opted into the dynamic model when they don't want/need to be. Note that this doesn't _prevent_ them from treating the values coming out of the indexer as `dynamic` _if they want to_, it just _won't force it_ any more.

**Comment by cleemullins** [comment]
FlexObject has been fully removed in #425
