### ISSUE TITLE
dotnet new templates for bot-builder SDK

### ISSUE THREAD

**Issue by jmezach** [Microsoft/botbuilder-dotnet#1092]
**Is your feature request related to a problem? Please describe.**
Since the Bot Builder V4 SDK is supposed to work cross-platform, it would be nice if we could also get started cross-platform. Currently the documentation recommends either using Visual Studio on Windows to create a new bot, or using the Azure Portal.

**Describe the solution you'd like**
It would be nice if the templates were available as a NuGet package for installation with dotnet new. That would allow developers on all platforms to simply create a new bot using the command *dotnet new bot* or something similar.

**Describe alternatives you've considered**
The current alternatives are either Visual Studio or the Azure Portal, but neither of them are very convenient, especially if you have a Mac or Linux machine.

**Additional context**
dotnet new seems to be the way forward with respect to creating new projects and I think it was .NET developers expect to work.

[enhancement]

**Comment by cleemullins** [comment]
@sgellock added these. 

The relevant code is found here:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/dotnet-templates

**Comment by damienpontifex** [comment]
@sgellock any update on dotnet new templates being released to nuget? I saw that 4.4 is now the current release of botbuilder-dotnet so wondering if this has progressed or you might have a new timeline?

**Comment by sgellock** [comment]
we're in the middle of pushing out stuff all day today.  so yes.  will have it for you soon

**Comment by sgellock** [comment]
@damienpontifex the .NET Templates are available now.  Please refer to the following for documentation, including how to install and run them.  https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/dotnet-templates

**Comment by damienpontifex** [comment]
Thanks @sgellock just what I was looking for.
