### ISSUE TITLE
oAuth SMS Issue - Login Prompt Loop

### ISSUE THREAD

**Issue by thegoo** [Microsoft/botbuilder-dotnet#1093]
## Version
Bot Builder: 4.15
.NET Framework: .NETCore.App (2.0)

## Describe the bug
Leveraging the BotAuthenticationMSGraph sample to test oAuth capabilities with SMS.  Configured Twillio channel in Portal for my Bot App.  When logging in and providing the magic code back to the bot, the bot will respond back with "Please login" and the login URL for token.botframework.com.

## To Reproduce
1. Follow instructions to configure Azure Web App Bot and BotAuthenticationMSGraph sample from [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp).
2. Configure a Twillio channel in the Azure Portal for Web App Bot
3. Text number the value: **recent** - I am using iPhone with iOS 12
4. Click login URL provided
5. Login with credentials
6. Provide magic code back to bot
7. Observe that the bot replies with a login URL

## Expected behavior
The bot should reply with the last five emails from the inbox associated with the login.

I was able to validate that this is functioning as expected in the Emulator when I enable "Use sign-in verification code for oAuthCards".

[bug]

**Comment by nyxsys** [comment]
We were able to reproduce this on our end, going to try and dig a bit deeper and see if its an issue with the sample itself or something else (might require transferring the issue over to the samples repo if so)

**Comment by JasonSowers** [comment]
We are still investigating, this only repros with twilio.

**Comment by CoHealer** [comment]
Moving from Support back to Dev. Assigned engineers no longer available, repro established.

**Comment by BenjaminAP** [comment]
Is this Bug being worked on?

**Comment by johnataylor** [comment]
We have a major refresh of the samples. We found two very significant bugs in both auth samples: firstly the dialog _was never saved_ and secondly the waterfall steps were confused (begin on a dialog must always be the last statement executed in a step - with the result available in the next step - one of the steps didn't follow this rule and the resulting behavior would be hard to predict and possible dependent on timing.)

Both these are serious bugs. The first bug essentially meant the sample didn't work at all. When I trued it out it kept starting over - the behavior was very confusing until you notice the state was not being saved. This would explain looping behavior - and possible this looping behavior. The fixed sample is available in the samples-work-in-progress branch in the samples repo. We will be merging (and deleting) this branch in the next couple of days (at which point expect to see it in master) so if you can verify this with the updated sample that would be great. I'll close this issue but please reopen if you continue to see problems.
