### ISSUE TITLE
Include SDK version identifier in User-Agent header on all calls to LUIS APIs

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#1095]
**Is your feature request related to a problem? Please describe.**
Today, we do not have any view into LUIS traffic that are driven by botbuilder. LUIS service instruments all calls to the service and can report on User-Agent to identify the specific client.  

**Describe the solution you'd like**
On all calls to LUIS service, include User-Agent header with the following value - 
botbuilder/v4-sdk/csharp/major.minor.patch.build

[enhancement]

**Comment by johnataylor** [comment]
Added user agent for **LUIS** and **QnA**. The user-agent is additive in the case of LUIS. The format follows the standard and convention:

**PRODUCT/VERSION COMMENT**

Package name and version followed by platform details in the comment.
Specifically an example user-agent for LUIS would include something like:

**Microsoft.Bot.Builder.AI.Luis/4.7.1 (Windows NT 6.4; dotnet 2.1)**
