### ISSUE TITLE
Cortana channel does not display choice prompts

### ISSUE THREAD

**Issue by ladeak** [Microsoft/botbuilder-dotnet#1098]
Cortana channel does not display choices on choice prompts nor it waits for the user to respond.
The same prompt in FB channel and the emulator works as expected: it offers the choices and waits for user response.

## Expected behavior
Cortana channel should offer and display the choices, re-activate input listening and wait for user response.

## Sample code to repro:
```csharp
        var choices = mylist.Take(5).ToList();
        var reprompt = MessageFactory.SuggestedActions(choices, "Pls repeat");
        reprompt.AttachmentLayout = AttachmentLayoutTypes.List;
        return await step.PromptAsync(Inputs.Choice, new PromptOptions()
        {
          Choices = ChoiceFactory.ToChoices(choices),
          Prompt = MessageFactory.Text("Some Question?", "Some Question?"),
          RetryPrompt = reprompt as Activity
       }, token);
```

Cortana displays and reads the question only. In the bot response I see the suggestions though:

## Channel info:

```
"botResponse": {
    "type": "message",
    "timestamp": "2018-11-08T18:51:00.4936512Z",
    "serviceUrl": "https://CortanaBFChannelEastUs.azurewebsites.net/",
    "channelId": "cortana",
    "from": {
      "id": "xxx"
    },
    "conversation": {
      "id": "xxx"
    },
    "recipient": {
      "id": "xxx"
    },
    "text": "Some Question?",
    "speak": "Some Question?",
    "inputHint": "acceptingInput",
    "suggestedActions": {
      "actions": [
        {
          "type": "imBack",
          "title": "Zero",
          "value": "Zero"
        },
        {
          "type": "imBack",
          "title": "First",
          "value": "First"
        }
      ]
    },
    "attachments": [],
    "entities": [],
    "replyToId": "xxx"
  }
```

[bug]

**Comment by v-kydela** [comment]
While [Cortana does not support suggested actions](https://docs.botframework.com/en-us/channel-inspector/channels/Cortana?f=SuggestedActions&e=example1), it does support [choice prompts](https://docs.microsoft.com/en-us/cortana/skills/cards). Let me know if you need help implementing that as an alternative

**Comment by ladeak** [comment]
That is actually a choice prompt. Only the reprompt is suggested actions, which I can replace. Or does that cause the issue?

**Comment by ladeak** [comment]
I removed the suggested actions part, but I am still not seeing choices appearing as buttons on Cortana channel. Also, I noticed, on the referenced documentation that Choice prompt may only be supported on Node.js platform, while I am using the .net libraries.

I tried to adding HeroCard attachment to the choice prompt, but even so I have the suggested actions. It seems the built in choice prompt always generates choices into suggested actions?

**Comment by v-kydela** [comment]
I'm not sure what you mean. Are you saying Cortana is displaying suggested actions now? And not only that, but all choice prompts are displayed as suggested actions? What's the distinction between them as you understand it?

Please share your current code without the suggested actions, along with a screenshot of what you're experiencing in Cortana

**Comment by ladeak** [comment]
Sorry for confusion, I am saying that vanilla choice prompts are sent to cortana as suggested actions. I am looking for a way to use choice prompts in a way that it displays buttons on cortana channel. Do you have a suggestion?

**Comment by ladeak** [comment]
@v-kydela any updates or suggestions? This issues seems to be linked to #1162

**Comment by v-kydela** [comment]
You may actually have discovered a bug in the V4 SDK. I've had a look and it turns out V4 doesn't incorporate cards into choice prompts the way V3 did. Moreover, V4 treats Cortana as though it supports suggested actions even though it knows it doesn't. I'll see if that can be fixed. In the meantime, you can create your own card for the prompt.

First, you'll want to make sure your `ChoicePrompt` doesn't show the choices itself:
```c#
AddDialog(new ChoicePrompt(Inputs.Choice) { Style = ListStyle.None });
```
Then you'll create your card and prompt with it:
```c#
var choices = new[] { "one", "two" };

var card = new HeroCard
{
	Text = "Select the Area",
	Buttons = choices.Select(choice =>
		new CardAction(ActionTypes.ImBack, choice, value: choice)).ToList(),
};

return await stepContext.PromptAsync(CHOICEPROMPT, new PromptOptions
{
	Choices = ChoiceFactory.ToChoices(choices),
	Prompt = (Activity)MessageFactory.Attachment(card.ToAttachment()),
}, token);
```

**Comment by v-kydela** [comment]
@ladeak - Did this resolve your issue?

**Comment by ladeak** [comment]
Yes this looks good on Cortana channel. Thank you for the workaround.

**Comment by CoHealer** [comment]
Closing as mitigated

**Comment by ladeak** [comment]
Can we add one more bit: the suggested workaround only works on the Windows 10 Cortana app. I have just recently updated Cortana for android v3.0, and it shows 2 buttons, once I select one, it returns an error message, but my bot code does not seem to be hit anymore.
Could you direct this issue to the proper channel?

**Comment by KoushikGoramane** [comment]
Will it works for Microsoft teams channel also?

If it works then where these codes we have to put?
