### ISSUE TITLE
Perf - FlexObject::TryGetMember double dictionary access

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#110]
The implementation of `FlexObject::TryGetMember` uses a pattern of calling `ContainsKey` to determine if the underlying `Dictionary<K,V>` contains a key and then, if it does, uses the indexer to actually get the value. This is more costly than it needs to be as it has to hash the key twice and do two hash lookups into the dictionary:
 1. just to see if it contains the key
 2. to go get the value

A better pattern for this is to use the `Dictionary<K,V>::TryGetValue` method which will simultaneously look up the key and, if it exists, return the value via the `out` parameter while simultaneously returning a `bool` to indicate whether or not an entry with the specified key exists.

*NOTE:* this technically only impacts users that choose to use the dynamic programming model when working with `FlexBox` types.

**Comment by cleemullins** [comment]
FlexObject has been removed by #425
