### ISSUE TITLE
Remove BotFrameworkOptions.State property

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-dotnet#1100]
## Version
4.1.x

## Describe the bug
The BotFrameworkOptions.State property only seems to exist so you can add BotState instances to it in the AddBot configuration callback and then get access to them later in other registrations (e.g. bot accessor pattern). This concept doesn't exist in JS/TS because there the variable containing the BotState instance is simply closed over in other functions. The same thing should be done in the .NET case rather than having added a property.

## Additional context
The BotFrameworkOptions::State property seems like a solution to a problem that doesn't even exist. Nothing in the rest of the framework will look at this property and it is only used at start up time by the samples today and seems to be the result of someone not leveraging simple language level features to solve this problem. Instead of adding BotState instances to this property in AddBot and then looking those instances back up in other AddXXX calls later, the developer should simply hoist the variable up into the ConfigureServices scope and then close over it in the various AddXXX callbacks.

The property should be removed to simplify the surface area and all the samples/templates should be updated to use the suggested approach.

Also, what is the impact of fixing this on:
- Docs - do we need to address any doc issues>
- Samples - are there samples implications
- VSIX - anything to cover here

[bug]

**Comment by drub0y** [comment]
PR in for obsoleting the property; I'll make a separate one for the proposed `IServiceCollection` extensions.

**Comment by johnataylor** [comment]
Regarding the obsolete - yes exactly - the assumption was that the implementation of "remove" is technically to mark as "obsolete" as @cleemullins pointed out.

Regarding the overall pattern(s) for adding state to your bot. This is definitely worth more discussion.

We just added a new sample [scaleout](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/42.scaleout) that demonstrates how to implement an alternatively state solution with different locking semantics from the ground up. Actually the only thing this shares with "default" solution in the framework is the derivation of the conversation key and the fact that you need some type of Accessor implementation to pass a handle on the state into the dialogs. There has been some discussion about simplifying this last step. Anyhow we have a write up of this solution too that covers some of the concepts used eTags.

**Comment by micdah** [comment]
Maybe the documentation over at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-persist-user-inputs?view=azure-bot-service-4.0&tabs=csharp#create-storage-state-manager-and-state-property-accessor-objects should be updated with the new pattern?

It's confusing, following a guide and encountering obsolete warnings.
