### ISSUE TITLE
OnReceive() adds handler to middleware pipeline. Every time it's executed.

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#114]
In a case where a user registers their bot as a Singleton in Startup.cs like so:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(
        new Bot(new BotFrameworkAdapter(Configuration))
            .Use(new BotStateManager(new MemoryStorage())
        )
    );

    services.AddMvc();
}
```

And then adds the bot logic inside their MessagesController like so:
```csharp
public MessagesController(Bot b, BotFrameworkAdapter adapter)
{
    _bot = b;

    _bot.OnReceive(async (context, nextDelegate) =>
    {
        var userMessage = context.Request.AsMessageActivity().Text;

        var turnNumber = (int)(context.State.Conversation[@"turnNumber"] ?? 1);
        context.Reply($@"#{turnNumber++}: You said {userMessage}");

        context.State.Conversation[@"turnNumber"] = turnNumber;

        await nextDelegate();
    });
}
```

They will get n+1 messages echo'd back to them for response N.

In other words, say 'hi'
and get
~~~
you said hi
~~~
say 'hi' again and get
~~~
you said hi
you said hi
~~~

This is due to:
https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Middleware/MiddlewareSet.cs#L29

however the other methods in `MiddlewareSet` will also result in this anomaly; we're wrapping every OnReceive in a new Anonymous middleware and adding it to the pipeline.

cc @cleemullins, @cmayomsft

**Comment by cleemullins** [comment]
I have confirmed / duplicated this and am working on it now.

**Comment by cleemullins** [comment]
Fix in the PR.
