### ISSUE TITLE
SDK should offer an ICredentialProvider implementation around BotConfiguration's EndpointService

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1164]
**Is your feature request related to a problem? Please describe.**
The "problem" is the amount of boiler plate that every sample and the VSIX templates include (~40 lines in `Startup.cs`) to load the endpoint and it's credentials out of the `.bot` file using the `BotConfiguration` APIs only to transfer the string value into a `SimpleCredentialProvider`.

**Describe the solution you'd like**
It seems like there should just be an "in-the-box" `ICredentialProvider` implementation that understands how to load from the `.bot` configuration file so that everyone doesn't have to write this boiler plate themselves.

**Describe alternatives you've considered**
The alternative is what the samples/VSIX templates are doing which is repeating ~40 some odd lines of boiler plate code to directly interact with the `BotConfiguration` API to find the endpoint.

**Additional context**
I've prototyped an `BotConfigurationEndpointServiceCredentialProvider` class and will supply an implementation via a PR shortly. 

The greatest challenge is actually figuring out where that class should land in terms of the dependency chain. `Microsoft.Bot.Configuration` is completely standalone today and doesn't even reference `Microsoft.Bot.Connector` which is where `IClientCredentials` is defined. One option is to go ahead and reference `Microsoft.Bot.Connector` and then place the class into `Microsoft.Bot.Configuration`. I don't like this because the standalone nature of the library kind of makes sense. Concurrently no other library that referenced `Microsoft.Bot.Connector` references `Microsoft.Bot.Configuration` so there's not even a tie in point right now. 

We _could_ add this class to the `.Integration.XXX` libraries, but that would mean a) duplicating the class in both libraries and b) creating another dependency for the integration libs to bring in `Microsoft.Bot.Configuration` that not everyone will [want to] use. 

A 100% clean solution would be a whole new library which integrates `Microsoft.Bot.Configuration` and `Microsoft.Bot.Connector`, but that would be add a whole new dependency that people would have to know to go look for just to get this one class.

Thoughts? Opinions?

**Comment by sgellock** [comment]
some of the samples in 4.3 will help.  we have some product work to do.  consider this for 4.4

**Comment by johnataylor** [comment]
In the integration packages we have ConfigurationCredentialProvider for each flavor. That should be good.
