### ISSUE TITLE
Need simple prompting mechanism

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#117]
In keeping with the desire to be unopinionated with the core framework, we understand that simple prompting (eg: `PromptDialog...`) isn't built in.
However, bots almost *always* have a need to prompt the user for data entry so having an add-on package that provides this functionality in a very clean & concise way is highly desired.

**Comment by nrobert** [comment]
+1 for the prompt mechanism. Right now if we compare to v3 we have lost all the functionalities helping people to provide validated data.
Moreover, using the adaptive cards for form submit like in AlarmBot-Cards is impossible in most of the channels, as the card is rendered as an image (tested in Facebook Messenger, Slack, Skype, Mail, and for  Teams the attachment type not supported!).

**Comment by garypretty** [comment]
+1 totally agree with this. One major reason people are adopting the BF right now is that for simple scenarios they have a lot of help in terms of simple things like prompts.  Totally get the reasoning behind the decision to have a 'pure core', but I absolutely think we need some form of prompting similar to v3.

**Comment by cleemullins** [comment]
Prompts are in. [Found here](https://github.com/Microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.Prompts). 

Additional changes (PromptResult<T>, etc) found in PR #232
