### ISSUE TITLE
Cortana bots try to use suggested actions 

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/botbuilder-dotnet#1173]
## Version
4.1.5

## Describe the bug
It is known that Cortana does not support suggested actions, but there is logic in [`ChoiceFactory.ForChannel`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceFactory.cs#L36) that directs a Cortana bot to use suggested actions when a `ChoicePrompt` is set to the default list style of `ListStyle.Auto`. I do not know the reasoning behind this. In the line `if (!longTitles && (supportsSuggestedActions || (!hasMessageFeed && supportsCardActions)))`, Cortana satisfies that condition because even though it [doesn't support suggested actions](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L10) it [does support card actions](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L46) and also [doesn't have a message feed](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L54). At least one customer has run into [issues](https://github.com/Microsoft/botbuilder-dotnet/issues/1098) because of this.

## To Reproduce
1. Create a bot with a `ChoicePrompt` without specifying a list style so that it defaults to "auto"
2. Connect the bot to Cortana
3. Run the bot and send messages to it
4. Observe that the choices are not displayed in any form (text, buttons, or suggested actions)

## Expected behavior
The desired behavior would be for the choices to be displayed as [buttons](https://github.com/Microsoft/botbuilder-dotnet/issues/1170), but failing that they should at least be displayed as text.

## Screenshots
A screenshot of the behavior can be found [here](https://github.com/Microsoft/botbuilder-dotnet/issues/1098#issuecomment-437997427).

## Additional context
I am happy to fix this myself if that's acceptable.

[bug]

**Comment by ladeak** [comment]
@v-kydela can we add one more bit, or could you try to direct me to the right team:

The suggested [workaround](https://github.com/Microsoft/botbuilder-dotnet/issues/1098#issuecomment-438850587) only works on the Windows 10 Cortana app. I have just recently updated Cortana for android v3.0, and it shows 2 buttons, once I select one, it returns an error message, but my bot code does not seem to be hit anymore.

I think it used work with previous version of Cortana for Android.

**Comment by v-kydela** [comment]
@ladeak - It's hard to say if that's a problem with Cortana or a problem with the bot. Try to gather as much information you can about the behavior so that you can post an issue with adequate steps for how to reproduce it. If you're building the bot with the .NET V4 SDK, this repo would be a fine place to post the issue

**Comment by v-kydela** [comment]
@ladeak - I'm sorry if I was unclear, but I meant that this repo would be a fine place to post your issue as its own issue. I didn't mean that this thread would be a fine place to post your issue. Please post an issue if you'd like your problem to be looked into.

**Comment by benbrown** [comment]
@v-kydela thanks for identifying this issue so clearly. could you submit a PR with a fix for this?
