### ISSUE TITLE
Microsoft Bot Framework V4 CatchExceptionMiddleware Issue

### ISSUE THREAD

**Issue by chinnivyshnavi** [Microsoft/botbuilder-dotnet#1176]
Hello,

I'm coding on bot framework SDK V4. I have the bot builder version 4.1.5. For the addition of the catchexception for the middleware in the startup.cs file, I installed Microsoft.Bot.Builder.Core.Extensions NuGet package. 
But after installing this, my IMiddleware is getting confused with the Microsoft.Bot.Builder and the Microsoft.Bot.Builder.Core. 
Also I'm unable to add following code to my startup file 
options.Middleware.Add(new CatchExceptionMiddleware<Exception>(async (context, exception) =>
                {
                    await context.TraceActivity("Bot Exception", exception);
                    await context.SendActivity($"Sorry, it looks like something went wrong: {exception.Message}");
                }));

Can someone help me over here please

**Comment by vishwacsena** [comment]
We removed support for the catchExceptionMiddleware and replaced it with adapter.OnTurnError() where you can handle global exceptions. See any of the chsarp-dotnetcore samples in the [samples repository](https://github.com/microsoft/botbuilder-samples)
