### ISSUE TITLE
Cortana 3.0.0.2376 on Android fails when replying to hero cards

### ISSUE THREAD

**Issue by ladeak** [Microsoft/botbuilder-dotnet#1184]
A suggested [workaround](https://github.com/Microsoft/botbuilder-dotnet/issues/1098#issuecomment-438850587) for Choice prompts (to use hero cards) only works on the Windows 10 Cortana app. I have just recently updated Cortana for android v3.0.0, and it shows 2 buttons (when I add three buttons), and once I select one of the buttons, it shows a general error (Something went wrong, please try again later) message (could not get debug info). My bot code does not seem to be hit the entry breakpoint anymore.
As far as I remember when I tested the workaround on Cortana for Android v2.x it worked correctly.

## Version
4.1.5

## Expected behavior
Selecting one of the buttons should return the reply to my bot. 

## Additional context

![screenshot_20181122-000310](https://user-images.githubusercontent.com/10052368/48872806-057d5f00-edeb-11e8-90b6-c3288ffc7715.png)

[bug]

**Comment by v-kydela** [comment]
@ladeak - I've been testing this and it appears to be a bug in Cortana for Android 3.0. It looks like while `messageBack` card actions don't even show up in a card, `imBack` and `postBack` card actions do show up but produce the error you're seeing. I'll see about passing this along to the appropriate team

**Comment by ladeak** [comment]
Thanks

**Comment by ladeak** [comment]
Do you have any updates on this? It seems 3.1 still has this issue.

**Comment by v-kydela** [comment]
No updates. Please feel free to report the Cortana bug in the appropriate place

**Comment by ladeak** [comment]
Sure, please point me to the appropriate place 😊

**Comment by v-kydela** [comment]
Please try to avoid carrying on conversations in closed issues. This repo is for BotBuilder issues.

You can provide feedback through the Cortana app itself.
