### ISSUE TITLE
Can't get type of date time string through DateTimePrompt

### ISSUE THREAD

**Issue by KayMKM** [Microsoft/botbuilder-dotnet#1186]
## Version
4.1.5

## Describe the bug
The result of DateTimePrompt, DateTimeResolution only contains: Value, Start, End and TimeX. But LUIS result contains a type. I think DateTimeResolution also need add the type.

## To Reproduce
Use the DateTimePrompt to receive an input like "7pm".

## Expected behavior
The result contains Value: "19:00:00", TimeX: "T19" and type: "datetimev2.time"

[bug]

**Comment by johnataylor** [comment]
The TIMEX expression(s) in the result encapsulate all the information from LUIS. However, TIMEX expression can be a little tricky to deal with. So we have this library:

https://www.nuget.org/packages/Microsoft.Recognizers.Text.DataTypes.TimexExpression/

And here are some examples of how to use it:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/40.timex-resolution
