### ISSUE TITLE
Allow send activity to other conversation than current

### ISSUE THREAD

**Issue by nimbusparis** [Microsoft/botbuilder-dotnet#1187]
In order to send activity to other conversation, to broadcast message on conversations for instance, please modify Activity.ApplyConversationReference (in ActivityEx.cs) in order it doesn't override the value stored:

        
    public Activity ApplyConversationReference(ConversationReference reference, bool isIncoming = false)
        {
            this.ChannelId = reference.ChannelId;
            this.ServiceUrl = reference.ServiceUrl;
            if (this.Conversation == null)
                this.Conversation = reference.Conversation;

            if (isIncoming)
            {
                if (this.From == null)
                    this.From = reference.User;
                if (this.Recipient == null)
                    this.Recipient = reference.Bot;
                if (reference.ActivityId != null)
                    this.Id = reference.ActivityId;
            }
            else // Outgoing
            {
                if (this.From == null)

                    this.From = reference.Bot;
                if (this.Recipient == null)

                    this.Recipient = reference.User;
                if (reference.ActivityId != null)
                    this.ReplyToId = reference.ActivityId;
            }

            return this;
        }

**Comment by johnataylor** [comment]
This would be a breaking change. Though that's not to say there isn't merit in what you suggest, its just difficult to change it now. However, you can add your own helpers.

**Comment by nimbusparis** [comment]
Is it not possible to set the method `virtual` in order we can override it properly?
