### ISSUE TITLE
MessageFactory methods return IMessageActivity which can't be assigned to things like Prompt<T>::Prompt/RetryPrompt because those expect type Activity

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1190]
**Is your feature request related to a problem? Please describe.**
There are still sporadic cases, such as `MessageFactory`, where `IXXXActivity` interfaces are exposed vs the base `Activity` class throughout the API continually cause problems where I'm forced to cast to an explicit type to make things fit.

**Describe the solution you'd like**
It would seem that a better, less jarring experience when calling this method with no factory would be for the method to just return the natural default value for the type T (e.g. default(T)). If I didn't supply a factory, it's intuitive that I would get a default value back for that type and would need to check for that if I wanted to. As it stands now, I think most people would opt to put a factory there just to avoid the exception which is also much more costly at runtime. Additional downside of everyone always supplying a factory is an increate in code size, noise, runtime invocation costs, etc.

If anything, anywhere is requiring the Activity class then   everything might as well be typed as Activity. Having to downcast interfaces   to classes is a sign that you've modeled your type system poorly.          Developers are forced to work around this by having to downcast those   interfaces to the Activity class, but technically you can't know that what's   behind that interface is indeed that class. It just so happens to be because   that's how the framework implemented it, but it's a smell and creates a lot   of noise in the code where you have to downcast things all over the place. The problem is this is shipped and any such change would be breaking, so I'm not entirely sure what to do about it.

**Describe alternatives you've considered**
Explicit down casting wherever these APIs exist. 😢

**Comment by johnataylor** [comment]
It is unfortunate that these interfaces exist but they do. The canonical usage is to make use of MessageFactory inline, agreed this is noise but we are consistently doing that now in the samples.

The team is working on higher level abstractions that should see the light of day in the next few month, at which point this noise will be less relevant.
