### ISSUE TITLE
BotStatePropertyAccessor should return null rather than throw on the first call if no default value factory is provided.

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1191]
## Version
4.1.x

## Describe the bug

The `IStatePropertyAccessor<T>::GetAsync` API allows specifying a factory method that will provide a   default value if none exists, but if you don't supply one it will throw the first time you call the method if no value exists rather than just giving you the "natural" default value for the type you're using (e.g.   `default(T)`).

## To Reproduce
1. Define a property as `CreateProperty<int>`
2. Create a bot that takes the `IStatePropertyAccessor<int>` via the constructor
3. In the bot's `OnTurn` implementation call `GetAsync(turnContext)` (i.e. no default value factory)
4. A `MissingMemberException` is thrown saying there's no default value

## Expected behavior
I would expect the default, pit of success behavior to return the "natural", default value for the `T` which should just be `default(T)`.

**Comment by johnataylor** [comment]
@drub0y thanks for the issue, please take a look at this implementation, this capture the expected behavior and works with the Dialog stack (note thanks to @cleemullins we explicitly defined this for ref semantics - its implicit in the implementation in BotBuilder)

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/42.scaleout/RefAccessor.cs

If you think this isn't a good reference implementation then we could discuss that. Closing this here.

**Comment by drub0y** [comment]
Sorry, I'm not sure how this addresses the actual issue at hand? 🤔

This is a behavior that's shipping in the box _right now_ with the `BotStatePropertyAccessor`<sup>1</sup> implementation of `IStatePropertyAccessor<T>` so I think it should be addressed directly. Pointing at a sample that shows how someone can build their own implementation that behaves the way they want doesn't really help the typical developer who sits down with the framework and just wants to write a bot with the SDK.

If we want to say this is "by design", while I disagree w/the design, I could at least accept it because I'll be able to point developers at the response as a definitive stance on the implementation.

<em><sup>1</sup> I probably have been more specific about the behavior being related to the `BotStatePropertyAccessor` class specifically, but it's technically the only implementation in the box.</em>

**Comment by johnataylor** [comment]
OK that's a different issue then. And to be clear this isn't an issue with the current usage, specifically with Dialogs, is that correct? So the scenario you are envisaging is someone who actually decides to attenmpt to use this state model and not use Dialogs, is that correct?

Anyhow we can use this same issue - but I'll retitle it.

**Comment by johnataylor** [comment]
Note the only usage of this API in the product is Dialogs and that code does provide the factory. So this is specifically an issue for someone writing code that uses the state model directly.

**Comment by drub0y** [comment]
Correct, nothing to do with Dialogs (specifically). I should note that JavaScript/TypeScript behavior is what I'm suggesting above where it will return `undefined` (the "natural" default value there obviously) instead of throwing an error. So this would align the behavior cross-platform as well.
