### ISSUE TITLE
SendActivityAsync's overload options are painful for the most often invoked scenario

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1192]
**Is your feature request related to a problem? Please describe.**
Arguably the most common API being invoked is going to be the   SendActivity(string, [CancellationToken]) overload. Unfortunately, as   defined, the cancellationToken is optional, but this causes it to clash with   another overload forcing you to always have to name the cancellationToken   parameter if you do want to pass it.

This is because the `SendActivityAsync(string, [CancellationToken])` overload defines the `CancellationToken` as an _optional_ parameter so, when you do actually want to supply it, you must explicitly name the parameter. If you don't, the compiler can't tell the difference between that overload and the other overload of `SendActivityAsync(string, [string],  [string], [CancellationToken])`. 

This forces everyone who wants to pass the `CancellationToken` in to the first overload, which is the right thing to do and _should be_ encouraged, to have to spell it out with a verbose/repetitive parameter name like so:

```CSharp
turnContext.SendActivityAsync("Hello world!", cancellationToken: cancellationToken);
```

**Describe the solution you'd like**
Ideally this should have been defined as only one method on `ITurnContext`:          `SendActivityAsync(IActivity, CancellationToken);`  and then everything else should have been implemented as a set of extension methods for `ITurnContext` enabling convivence signatures and solving this specific problem with distinct overloads with explicit, required params: 

 * `SendActivityAsync(string);` 
 * `SendActivityAsync(string, CancellationToken);`
 * `SendActivityAsync(string, string, string, CancellationToken);`
 * etc.

**Additional Context**
Right now I'm honestly not sure how _best_ to resolve this without a breaking API change. 😢

**Comment by benbrown** [comment]
Thanks for feedback on this @drub0y, we all agree that this would be better as described but it is probably not possible to correct without breaking API changes.
