### ISSUE TITLE
TranscriptLoggerMiddleware should not use await logger.LogActivityAsync()

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-dotnet#1205]
[TranscriptLoggerMiddleware.OnTurnAsync()](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs#L42):
```cs
            // flush transcript at end of turn
            while (transcript.Count > 0)
            {
                try
                {
                    var activity = transcript.Dequeue();
                    await logger.LogActivityAsync(activity).ConfigureAwait(false);
                }
                catch (Exception err)
                {
                    System.Diagnostics.Trace.TraceError($"Transcript logActivity failed with {err}");
                }
            }
```
## Version
4.1.7

## Describe the bug
[`await logger.LogActivityAsync(activity).ConfigureAwait(false);`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs#L110) is supposed to instead be `logger.LogActivityAsync(activity).ContinueWith(...);` per @tomlm.

## Additional context
Related to Microsoft/botbuilder-js#383

[bug]

**Comment by johnataylor** [comment]
fix checked in
