### ISSUE TITLE
Update build process to handle the new application insights package

### ISSUE THREAD

**Issue by benbrown** [Microsoft/botbuilder-dotnet#1209]
Please update the c# build process to build, package and publish the new application insights client package.

**Comment by cleemullins** [comment]
I see the WebAPI Package (from the integration library) building and publishing:
https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.ApplicationInsights.WebApi

... however I don't see the .Net Core version of that package. 

Investigating.

**Comment by cleemullins** [comment]
PR #1216 should fix the .Net Core 2 packages not build built and published.

**Comment by cleemullins** [comment]
The AppInsights.Core package is now build built and signed, as seen on the [daily feed](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core). 

Confirmed (via Nuget package explorer) that the package is signed, properly versioned, and includes the code and symbol files. The Assembly library versions are also correct, as seen below. 
![image](https://user-images.githubusercontent.com/1165321/49484305-634a7780-f7eb-11e8-8a82-ff0b8cb600ee.png)

@daveta Can you validate the package is working properly? Then we can resolve this bug.

**Comment by cleemullins** [comment]
Renamed the WebAPI project (per PR #1217) and it looks to be building correctly. The resulting NuGet is:

![image](https://user-images.githubusercontent.com/1165321/49535972-4e68f500-f87a-11e8-91ad-e38fc996a23c.png)

I've delete all references to the old package from the daily feed.

**Comment by cleemullins** [comment]
I think this is good-to-go. Resolving.
