### ISSUE TITLE
Authorization Issue when I deploy my bot on Azure

### ISSUE THREAD

**Issue by waleedabuyahia** [Microsoft/botbuilder-dotnet#1223]
SDK: v4.0.30319
Endpoint: Web API
When I deployed my Bot in Azure I have the following issue appears in the web chat channel :
There was an error sending this message to your bot: HTTP status code Unauthorized 

I have check the AppID and Password everything should be fine . also below is my .bot file

{
    "name": "XXXXXX",
  "services": [
    {
      "type": "endpoint",
      "name": "development",
      "endpoint": "http://localhost:58475/api/messages",
      "appId": "",
      "appPassword": "",
      "id": "166"
    },
    {
      "type": "endpoint",
      "name": "production",
      "endpoint": "https://XXXXXXX/api/messages",
      "appId": "XXXXXX",
      "appPassword": "XXXXXXXXX",
      "id": "167"
    },
    {
      "type": "luis",
      "name": "",
      "appId": "XXXXXXX",
      "authoringKey": "XXXXXXX",
      "subscriptionKey": "XXXXXXX",
      "version": "0.1",
      "region": "westus2",
      "id": "34"
    }
  ],
    "padlock": "",
    "version": "2.0"
}

**Comment by cleemullins** [comment]
@dmvtech Can we get an update on this?

**Comment by dmvtech** [comment]
@waleedabuyahia Are you using `Microsoft.Bot.Configuration` in your startup file (as shown [here](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/03.welcome-user/Startup.cs#L67))?

Also, did you create the .bot file by using msbot or manually creating/modifying it?

You can try and creating a new bot file by using msbot:
`msbot clone services --name "<NAME>" --luisAuthoringKey "<YOUR AUTHORING KEY>" --folder "DeploymentScripts/MsbotClone" --location "westus" --verbose --appId <YOUR APP ID> --appSecret <YOUR APP SECRET PASSWORD>`

**Comment by dmvtech** [comment]
Closing as there has not been a response. Please reopen if this issue is still occuring.
