### ISSUE TITLE
API for new Activity so large a VS Tooltip can't show it

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#1229]
This API is far too overloaded.

![image](https://user-images.githubusercontent.com/20270743/49757500-658c5600-fc71-11e8-86d3-45db9c551f71.png)

All I want to do is Send a prompt with predefined responses, eg: "What would you like to do? [foo], [bar], [baz]" which I expected to be able to do with something like:
```csharp
await turnContext.SendActivityAsync(@"What would you like to do?", options: new[] { "foo", "bar", "baz" })
```

**Comment by cleemullins** [comment]
This can't be changed w/o breaking compatability.

**Comment by ryanvolum** [comment]
@cleemullins for issues like this and https://github.com/Microsoft/botbuilder-dotnet/issues/1230#issuecomment-445976434 is there anyway these can be tracked for a future version of the SDK? It makes sense that you've got to respect semantic versioning here, but it would be a shame to see the same issues crop up in an (eventual) v5 if they don't get tracked now. 

I think even just tagging these as v5 and closing them will make them easily searchable in the future.

**Comment by brandonh-msft** [comment]
Is it appropriate to mark this for v5 and leave it `Closed`???
