### ISSUE TITLE
SuggestedActions takes IEnumerable<T> for one overload, IList<T> for the other

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#1232]
Why is this??

![image](https://user-images.githubusercontent.com/20270743/49758446-d03e9100-fc73-11e8-96b1-6d9f5eeeb6be.png)

There's no discernable reason why one overload _requires both parameters_ and takes `IEnumerable<T>` while the other _requires **neither** parameter_ but takes `IList<T>`. At a minimum, these should be the same types or users are force to do unnecessary gymnastics.

**Comment by cleemullins** [comment]
@brandonh-msft - how would you suggest we fix this w/o breaking back-compat? Should we add additional overaloads?

**Comment by brandonh-msft** [comment]
changing the `IList` overload to take `IEnumerable` isn't a breaking change; `IList` inherits from `IEnumerable` so anybody passing one in today will work fine tomorrow. And by doing this, you make the `IList` one obsolete. If what you're trying to say is "either pass us both or neither, not just one" then you can enforce this with overloads instead of optional parameters. one that takes no params, and one that takes both (as `IEnumerable` please). This will only break people who are violating this constraint (rightly so)

**Comment by johnataylor** [comment]
The IList<T> constructor is generated code - we would not want to edit that.

It is perhaps unfortunate that the handcrafted extra overload that takes the IEnumerable<T> was added. However, as @cleemullins points out we need to avoid breaking changes.

If we were to removed this constructor we would break the following code:

```
        static void Func(IList<string> to, IList<string> from)
        {
        }

        static void Main(string[] args)
        {
            IEnumerable<string> a = new[] { "x", "Y" };
            IEnumerable<string> b = new[] { "z" };
            Func(a, b);  // COMPILE ERROR
        }
```
though, somewhat ironically the following would have been fine:

```
            Func(new[] { "x", "Y" }, new[] { "z" });
```

Thanks for opening the issue, however, we're leaving this as is.
