### ISSUE TITLE
Activity constructor says 'type' is optional however not using it means the message doesn't get delivered

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#1234]
The following code
```csharp
await turnContext.SendActivityAsync(@"Hey there! I'm the ASH Music Festival Bot. I'm here to guide you around the festival!");

await turnContext.SendActivityAsync(new Activity
{
    Text = @"How would you like to explore the event?",
    SuggestedActions = new SuggestedActions(actions: new[] { @"FAQs", @"Band Search", "Navigate" }.Select(i => new CardAction(ActionTypes.PostBack, i)).ToList())
});
```
Does not work. At first glance it seems it should. However what's missing is passing the message type to the Activity creation like so:
```csharp
await turnContext.SendActivityAsync(@"Hey there! I'm the ASH Music Festival Bot. I'm here to guide you around the festival!");

await turnContext.SendActivityAsync(new Activity(ActivityTypes.Message)
{
    Text = @"How would you like to explore the event?",
    SuggestedActions = new SuggestedActions(actions: new[] { @"FAQs", @"Band Search", "Navigate" }.Select(i => new CardAction(ActionTypes.PostBack, i)).ToList())
});
```
which means `type` is **clearly _not_ optional**. This should be resolved.

**Comment by cleemullins** [comment]
Consider using MessageFactory as all of the samples and docs show.

**Comment by brandonh-msft** [comment]
Why would I use `MessageFactory` if the type is called `Activity`? Furthermore if `Activity` is not supposed to be `new`'d then why is its constructor public?

**Comment by johnataylor** [comment]
Thanks for opening this issue.

Activity is generated code and we would not want to edit that. Agreed, in principle the constructor should not have been public. At it would be idea to enforce the policy you highlight.

As @cleemullins points out MessageFactory is the correct code to use - as all the samples should be illustrating.

Agreed the naming is not ideal, perhaps MessageActivityFactory would have been a more appropriate name, however, we can't change names like this without either breaking or increasing surface area.
