### ISSUE TITLE
MSTeams OAuth Card button does not work

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-dotnet#1236]
## Version
4.2.0

## Describe the bug
When an OAuth Card is rendered in Teams, nothing happens when the user clicks the button to sign in. This is because Teams doesn't support the Signin ActionType. This has been reported before in v3, but is still happening in v4 (https://github.com/Microsoft/BotBuilder/issues/4768). Hoping to have a fix in the OAuthPrompt rather than telling users to use the middleware from the original issue. 

## To Reproduce
1. Create bot with OAuthPrompt
2. Deploy to Teams
3. Try to login

## Related Issues
- https://github.com/Microsoft/AI/issues/390

[bug]

**Comment by mark-szabo** [comment]
Hey @lauren-mills have a look on this 😉: https://github.com/Microsoft/BotBuilder/issues/4768#issuecomment-437669120

**Comment by lauren-mills** [comment]
Thanks! I’ve already found the middleware and it works well, but ideally this will be taken care of in the SDK or the channel itself.

**Comment by Jeffders** [comment]
Did you use a manifest file for your bot with teams, as in this documentation?

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-oauth-card

The manifest file is required to whitelist the signin url, which allows the button to work.

**Comment by lauren-mills** [comment]
No, I didn’t. I have read through this doc before and it’s not very clear about the manifest. After digging around I see there is sample project, but is there a more informative doc somewhere I can point customers to?

**Comment by mark-szabo** [comment]
@Jeffders moreover you are not required to use a manifest to be able to chat with a bot. A direct link from the Azure portal is more than fine. 
Imagine a situation where an ISV is developing a corporate chatbot which will be used by a few companies and cannot be used by any other (eg. bot for local resources). They obviously don't want to submit it to the Teams Store as only a few hundred people will use it, but they absolutely need to log that few hundred in with SSO.

Possibility to use a bot without submitting to the store + login only works when manifest added + no meaningful error message + no clear documentation = frustrated devs 😣

**Comment by cleemullins** [comment]
Fixed by #1329
