### ISSUE TITLE
Deserialize Activity with default timestamp ("0001-01-01T00:00:00") failed on machine with Postive UTC

### ISSUE THREAD

**Issue by zongbingwang** [Microsoft/botbuilder-dotnet#1237]
## Version
4.0.7

## Describe the bug
It throws exception “Could not convert string to DateTimeOffset” when send activity to skill service with default timestamp ("0001-01-01T00:00:00")

There is a [discussion ](https://stackoverflow.com/questions/50628374/json-net-deserializing-datetimeoffset-value-fails-for-datetimeoffset-minvalue-wi)in StackOverflow about this issue and have a workaround before the bug resolved in Newtonsoft package.
Th open [bug](https://github.com/JamesNK/Newtonsoft.Json/issues/1731) for Newtonsoft.Json 

## To Reproduce

1. Send an activity with default timestamp ("0001-01-01T00:00:00") to skill service
2. You can see there the service returns 500 internal error and with error message "Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'timestamp', line 1, position 70."

> ExceptionType | Newtonsoft.Json.JsonReaderException
>        Message | Could not convert string to DateTimeOffset: 0001-01-01T00:00:00. Path 'timestamp', line 1, position 70.
>     StackTrace |    at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
>    at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadAsDateTimeOffset()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
>    at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandler.<ProcessMessageRequestAsync>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase.<HandleAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

## Expected behavior
Deserialize the timestamp information successfully

## Additional context

[bug]

**Comment by Zerryth** [comment]
Update to team: emailed @zongbingwang for some clarification, and expect the response to be slightly delayed (away on holiday).

**Comment by drub0y** [comment]
No doubt this is a bug, but, if I may ask, under what circumstances would you ever expect to receive an activity with that time in it? This just seems contrived and easily worked around by just not ever using that value since it shouldn't ever pop up in a real world scenario anyway.

Are you perhaps concerned about the fact that it's a possible issue for bots not behind the Bot Framework Service to be DoS'd by bad values being sent due to the overhead of the exception being generated???

**Comment by cleemullins** [comment]
The right answer to this seems to be, "Once Newtonsoft fixes this, we should upgrade". 

What action would you suggest we take to fix this?

**Comment by Zerryth** [comment]
Thank you for informing us of the bug on the Newtonsoft side

Closing thread here on BF side

**Comment by liamkernighan** [comment]
Maybe it will help someone
```

namespace App.Middleware
{
    /// <summary>
    /// https://github.com/Microsoft/botbuilder-dotnet/issues/1237
    /// https://github.com/JamesNK/Newtonsoft.Json/issues/1731
    /// </summary>
    public class FixNewtonsoftIssueMiddleware
    {
        private readonly RequestDelegate _next;
        public FixNewtonsoftIssueMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context, ILogger<RequestLoggingMiddleware> logger, IBot bot)
        {
            context.Request.EnableBuffering();
            using (StreamReader reader = new StreamReader(context.Request.Body, Encoding.UTF8, true, 1024, true))
            {
                var bodyAsString = await reader.ReadToEndAsync();
                var matches = new Regex(@"""timestamp"":\s+""0\d{3}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}""").Matches(bodyAsString);

                if (matches.Count > 0)
                {
                    foreach  (Match match in matches)
                    {
                        var newValue = match.Value;
                        newValue = newValue.Remove(newValue.Length - 1) + ".000Z" + @"""";
                        bodyAsString = bodyAsString.Replace(match.Value, newValue);
                    }

                    context.Request.Body = GenerateStreamFromString(bodyAsString);
                }
                         
                else
                {
                    context.Request.Body.Position = 0;
                }
            }

            await _next.Invoke(context);
        }

        private static Stream GenerateStreamFromString(string s)
        {
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            writer.Write(s);
            writer.Flush();
            stream.Position = 0;
            return stream;
        }
    }
}
```

**Comment by khurram-aziz** [comment]
While publishing bot on Skype channel; faced this issue; resolved using the @liamkernighan middleware fix
