### ISSUE TITLE
Issue with bad request using OAuth

### ISSUE THREAD

**Issue by thomasmartinsen** [Microsoft/botbuilder-dotnet#1245]
## Version
4.2.0.

## Describe the bug
Getting an error as part of the authorization flow using OAuth2, when the browser open and tries to authenticate the user. The error is "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.".

I only see the bug on one machine and in my test environment, however other see this during debug as well (see links to Stackoverflow).

## Additional context
I see several people adding issues about this on Stackoverflow:
- https://stackoverflow.com/questions/53812752/azure-adv2-token-botframework-com-resource-not-found#comment94478943_53812752
- https://stackoverflow.com/questions/53606838/bad-request-while-authenication-in-bot-sdk4-using-own-generic-oauth-2-connection#comment94479083_53606838

[bug]

**Comment by jbeltranluna** [comment]
I am also facing the same problem since last week. Nothing changed in my code but authentication stopped working.
Even performing testing directly from Azure with the same result: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
