### ISSUE TITLE
RemoveRecipientMention() in MessagesV3Controller.OnTurnAsync() is throwing Null Reference Exception for activities with activity.Type == ActivityTypes.Event

### ISSUE THREAD

**Issue by navidmolavi** [Microsoft/botbuilder-dotnet#1248]
Hi

I am trying to receive event activities in OnTurnAsync(), and activity.RemoveRecipientMention() is throwing Null Reference Exception.
Here is the payload the bot is receiving:

{
  "type": "event",
  "id": "3jUpcoUrWZq",
  "timestamp": "1970-01-18T21:12:47.627Z",
  "serviceUrl": "...",
  "channelId": "facebook",
  "channelData": {
    "field": "mention",
    "value": {
      "sender_name": "Example Name",
      "post_id": "44444444_444444444",
      "verb": "add",
      "sender_id": "44444444",
      "item": "post"
    }
  },
  "value": {
    "sender_name": "Example Name",
    "post_id": "44444444_444444444",
    "verb": "add",
    "sender_id": "44444444",
    "item": "post"
  },
  "name": "mention"
}

**Comment by cleemullins** [comment]
@navidmolavi Which version of the SDK and platform are you using? I've tagged our Support team for this issue, and they'll need that info. Hopefully we can drive to resolution pretty quickly.

**Comment by CoHealer** [comment]
ack, team will investigate this afternoon

**Comment by EricDahlvang** [comment]
This is an issue on both V3 and V4 (IF we want to consider it a bug).

V4:
https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityExtensions.cs#L56

V3:
https://github.com/Microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/ActivityEx.cs#L482

It is a simple fix: ensure the activity.Text is not null or empty before attempting to remove @mentions .  However, is this actually a bug?  Should consumers be allowed to call this when there is no .Text property?  Or, is it valid to throw an exception when attempts are made to remove @mentions with no .Text present?

@cleemullins  Do we want to consider this a bug, or a usage issue?

**Comment by CoHealer** [comment]
@cleemullins/@sgellock, do you have guidance for @navidmolavi? Should this be triage'd as a bug or is this desired behavior?

**Comment by sgellock** [comment]
This is by design.  an @ mention can happen that does not include text.
