### ISSUE TITLE
DirectLine object is not initiating the bot conversation 

### ISSUE THREAD

**Issue by DivyashriV** [Microsoft/botbuilder-dotnet#1252]
Hi Team,
 We are using Direcline channel in our bot for conversation and the directline object is not initiating the bot conversation and its throwing exception like "Authentication failed because the remote party has closed the transport stream",below is the line which throws the exception:
var conversation = await client.Conversations.StartConversationAsync();

Note:The same solution was working fine and all of a sudden it stopped working.

Thanks
Divyashri.V

**Comment by DivyashriV** [comment]
Hi Team,

Can you please help us with the issue mentioned.

Thanks
DivyashriV

**Comment by cleemullins** [comment]
Tagging our support team to help with this.

**Comment by CoHealer** [comment]
ack

**Comment by tdurnford** [comment]
@DivyashriV 

Are you still experiencing this issue? I ran through the [V3 DirectLine Sample](https://github.com/Microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/core-DirectLine) which uses the DirectLine NuGet package to try and reproduce your error, but everything seemed to work as expected. I would recommend double checking your DirectLine Secret. 

If you are still experiencing this issue, some additional information about the structure of your bot would be helpful. 

Thanks,

TJ
