### ISSUE TITLE
Channels class has incomplete list of channel identifiers

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#1255]
## Version
Daily.

## Describe the bug
The channels list is incomplete, missing channels visible in Azure: Bing and Skype for Business.

## To Reproduce
1. Go to https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Connector/Channels.cs
   - Use a non-MS-internal account.
1. Notice which channels are missing.

## Expected behavior
All channels available through Azure have identifiers defined in the Channels class.
- Bonus points for putting these constants in alpha order.

[bug]

**Comment by JonathanFingold** [comment]
Also, is Bing still an available channel?

**Comment by cleemullins** [comment]
Note that the Bing channel is no longer supported. Verify this same change in the JS codebase.

**Comment by cleemullins** [comment]
Fixed in #1328

**Comment by cleemullins** [comment]
Rather, fixed in #1319
