### ISSUE TITLE
Magic code is not exchanged for token

### ISSUE THREAD

**Issue by faithforven** [Microsoft/botbuilder-dotnet#1265]
## Version
4.2.0

## Describe the bug
With VPN on client side in Direct Line Web Chat user gets magic code after sign in with help of OAuthCard.
User pastes code back to the chat but gets 'Login to proceed'. 
https://api.botframework.com/api/usertoken/GetToken replies with Http Code 404
This is constantly reproducible when we get magic number.

Without VPN seamless login in web chat works fine.

## Additional context
Traces:
`2018-12-27 18:38:53.544 +00:00 [Debug] TcoItHelpDeskChatBot.Infrastructure.Tracing.TracingInterceptor: invocationId: 76
instance: Microsoft.Bot.Connector.OAuthClient
method: GetUserTokenAsync
parameters: {userId=dl_6c43ea21d8e646bbbf3fe47e5cc0af0b,connectionName=AzureADConnection,magicCode=635427,cancellationToken=System.Threading.CancellationToken}
2018-12-27 18:38:53.544 +00:00 [Debug] TcoItHelpDeskChatBot.Infrastructure.Tracing.TracingInterceptor: invocationId: 76
request: Method: GET, RequestUri: 'https://api.botframework.com/api/usertoken/GetToken?userId=dl_6c43ea21d8e646bbbf3fe47e5cc0af0b&connectionName=AzureADConnection&code=635427', Version: 2.0, Content: <null>, Headers:
{
  Authorization: Bearer <LONG_BEARER>
}
`

`
2018-12-27 18:38:58.968 +00:00 [Debug] TcoItHelpDeskChatBot.Infrastructure.Tracing.TracingInterceptor: invocationId: 76
response: StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Server: Microsoft-IIS/10.0
  x-ms-request-id: |f902080fba53194cb9cac6169810d77f.72476138_
  X-Content-Type-Options: nosniff
  Date: Thu, 27 Dec 2018 18:38:58 GMT
  Expires: -1
  Content-Length: 0

}

Body:
{

}
`

**Comment by Jeffders** [comment]
Thank you for reporting this. I looked into the logs and I see an issue with the bot name that is used when the OAuthCard is sent to the user. It looks like your bot is overriding the activity.From.Name (the bot's name) with a different value. You should leave this value as it is set when the Activity is received, otherwise the token will not be cached.
