### ISSUE TITLE
Is there a way  I can use V4 for create bot on VS code

### ISSUE THREAD

**Issue by anirugu** [Microsoft/botbuilder-dotnet#1268]
I have used V3 to create a bot earlier in Visual Studio 2017. I am looking for using v4 to do some work. Is this can be worked with VS code.

I means from scratch to ready app, do everything in vs code.

**Comment by drub0y** [comment]
Yes. Make sure you install [the latest .NET Core SDK](https://dotnet.microsoft.com/download) and [the C# extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) and that's all you really need to develop a .NET Core based bot with C# in VS Code. 

Note that, right now, there is no `dotnet new` template (see #1092) so you would have to bootstrap the project yourself (e.g. add in the right nuget packages). For now, the easiest way to work around that would just be to copy the `.csproj` from one of the samples such as [the Empty Bot](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/00.empty-bot/EmptyBot.csproj).

**Comment by Zerryth** [comment]
@anirugu what @drub0y is the way to go currently if you want to go about starting from scratch in VS Code.

Currently there are v4 VSIX templates that are available in Visual Studio 2017, if you're not averse to using that editor as you had done in v3.

Closing this issue, as the the item is already being tracked in #1092 to expand to `dotnet new` command that would work in VS Code

**Comment by anirugu** [comment]
@Zerryth 
Thanks, I will check and let you know.
