### ISSUE TITLE
Microsoft.Bot.Builder solution doesn't build cleanly

### ISSUE THREAD

**Issue by apulliam** [Microsoft/botbuilder-dotnet#127]
The botbuilder projects are all .NET core 2.0.  There a many NU1701 Package fallback warnings, where regular .NET projects are referenced.

**Comment by cleemullins** [comment]
+1

It's a dependant project we'll have to change, mostly from the Text-Recognizers repo which are the recognizers used by LUIS. 

I'll kick that process off on Monday.

**Comment by cleemullins** [comment]
A quick update on this:
1. I've requested access to the LUIS Recognizer repo, [found here](https://github.com/Microsoft/Cognitive-LUIS-Windows). Once I get access, I'll update the underlying code and publish new NuGet packages. 
2. I've kicked off the process to update the [Microsoft Recognizers Text](https://github.com/Microsoft/Recognizers-Text) repo to migrate to .Net Core2. That'll take a few days, as the person who would approve the PR is on vacation, and it's a possible breaking change for the teams that depend on that code.

**Comment by cleemullins** [comment]
To continue to update:
1. The PR for the Microsoft Recognizers Text repo for .Net Core 2 has been submitted. That'll take a few days to wind through the system. 
2. Still working on a plan for the LUIS Recognizer. The solutions may be more complicated than initially thought.

**Comment by lynn-orrell** [comment]
Is there a reason the EchoBot-AspNet461 project was added to samples? The addition of this project causes .Net Core build issues as well...

**Comment by cleemullins** [comment]
It was added at Brandon's request, and authored by Brandon. His thinking, which I agree with, is that it's handy to show the new SDK integrating with an older version of ASP.Net. 

I've sent an email to him asking him to cleanup the many build warnings. 

I'm open to suggestions until then.

**Comment by cleemullins** [comment]
Another update: The Recognizers-text repo has now been updated to .Net Standard 2.0. Their latest NuGet is multi-targeted, and was pulled in by #207. 

I've now gotten admin access to to the [LUIS SDK Repo](https://github.com/Microsoft/Cognitive-LUIS-Windows) and am working with the team to figure out the best path forward. 

Progress!

**Comment by cleemullins** [comment]
The [LUIS SDK Repo](https://github.com/Microsoft/Cognitive-LUIS-Windows/tree/master/CSharp) is now up-to-date with .Net Standard 2, and has a modern implementation of the C# LUIS SDK. Thanks to @emadelwany for that. 

Currently gated on updated the [Nuget package](https://www.nuget.org/packages/Microsoft.Cognitive.LUIS/), which is in-progress.

**Comment by garypretty** [comment]
@cleemullins I think this has been merged now. Is this good to be closed in that case?

**Comment by brandonh-msft** [comment]
22 warnings on a clean build today after pulling `master`:

![image](https://user-images.githubusercontent.com/20270743/37614746-c7b6ef1e-2b68-11e8-8a0f-03d07f204c6e.png)

**Comment by cleemullins** [comment]
The issues described by this thread are all resolved. 

New issues have come up regarding the BotBuilder.Classic assemblies, but they're tracked elsewhere.
