### ISSUE TITLE
Not receiving events from facebook messenger

### ISSUE THREAD

**Issue by odannyc** [Microsoft/botbuilder-dotnet#1271]
## Version
4.2

## Describe the bug
Im on the facebook messenger channel. When anything happens within the conversation that's not a message, I don't receive that event. For example, if I delete my conversation with the bot, I don't get that event/request to the bot endpoint. Another example is if I subscribe to `messaging_echoes` on facebook I don't receive any of those events either. The only things I get on my bot endpoint is actual messages (pics, audio, text, stickers.. etc). I don't receive anything else that's not considered a message. This is not an issue with the actual SDK itself but possibly of the botframework.com endpoint. I'm using this as the callback URL: `https://facebook.botframework.com/api/v1/bots/[bot id]`

**Comment by jwiley84** [comment]
Hi @odannyc! It's not so much a problem with the end point as it is the the full SDK, which at the moment doesn't support all the webhook events that facebook messenger has to offer. I don't believe that messaging_echos is supported. I'm going to cross-link this to a couple of ongoing issues that are tracking the facebook channel events feature requests.

**Comment by jwiley84** [comment]
https://github.com/Microsoft/BotBuilder/issues/4360 and https://github.com/Microsoft/BotFramework-Services/issues/5

**Comment by EricDahlvang** [comment]
Messenger messaging_echos are now supported in the Bot Framework, as are standbys and the handover protocol.
