### ISSUE TITLE
Add Refresh Token to TokenResponse

### ISSUE THREAD

**Issue by cdonke** [Microsoft/botbuilder-dotnet#1278]
OAuthPrompt helps to get the OAuth code and thr authorization token, but to request a token for a second resource, the whole authentication process must be repeated. 

If the Refresh token is deserialized to the TokenResponse object, one could manually request the token for other resources. 

On a second step, implement a GetUserTokenSilentAsync method.

**Comment by cleemullins** [comment]
@cdonke I'm not sure what the ask is here.
