### ISSUE TITLE
FlexObject is confusing and non-standard way of handling a property collection in .NET

### ISSUE THREAD

**Issue by apulliam** [Microsoft/botbuilder-dotnet#128]
FlexObject appears to try to mimic JavaScript version of botbuilder by allowing JavaScript style dynamic object properties, while also allowing DotNet strongly typed object collection handling.  Mixing dynamic and static accessors could be confusing.  DotNet developers expect a property bag/dictionary implementation for property collections.  Also if you use FlexObject as dynamic, you lose Intellisense, which is what DotNet developers use to discover class properties and methods. Even if you use the strongly typed accessors to add properties, they are returned as dynamic when they are retrieved (see #109).

**Comment by cleemullins** [comment]
FlexObject has been fully removed in #425
