### ISSUE TITLE
QnAMaker class doesn't actually pass on ScoreThreshold into request to QnA service

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-dotnet#1286]
## Version
dotnet 4.2.0

## Describe the bug
Was striving to provide more coverage on the QnA code, got an error when I tried to assert that the `QnAMakerOption.ScoreThreshold` was properly being sent into request to QnA KB.

Got `ArgumentNullException` error
![image](https://user-images.githubusercontent.com/35248895/51271036-589f0880-197b-11e9-9f27-0c89f2726d48.png)

Looks the request built never included `ScoreThreshold` in the first place
![image](https://user-images.githubusercontent.com/35248895/51270845-d1519500-197a-11e9-9ec4-58fc0667cefc.png)

## Expected behavior
For `QnAMaker` class to pass all `QnAMakerOptions` into request to KB

[bug]

**Comment by cleemullins** [comment]
Resolved by #1288
