### ISSUE TITLE
IAdapterIntegration interface needs to expose ContinueConversationAsync to enable proactive scenarios

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1287]
**Is your feature request related to a problem? Please describe.**
Unable to execute proactive callback scenarios in an abstract way because the `IAdapterIntegration` abstraction does not expose the method to trigger.

**Describe the solution you'd like**
`IAdapterIntegration` should expose `ContinueConversationAsync` so that I can trigger proactive callbacks via this abstraction.

**Describe alternatives you've considered**
Downcasting the `IAdapterIntegration` to `BotAdapter` works, but it makes a hard assumption on an the implementation detail and also makes unit testing more difficult.

**Additional context**
[This also came up recently in a discussion on another issue.](https://github.com/Microsoft/botbuilder-dotnet/issues/787#issuecomment-453551626). There is more to the discussion which I of course suggest reading, but this particular shortcoming starts at that link.

**Sample code**
Here's a sample of a proprietary backend controller that I might have that handles events from some other system and finds a related conversation reference that it will proactively continue the conversation for:

```CSharp
    [Route("some-backend")]
    public class ProactiveController
    {
        private readonly IAdapterIntegration _adapterIntegration;

        public ProactiveController(IAdapterIntegration adapterIntegration)
        {
            _adapterIntegration = adapterIntegration ?? throw new ArgumentNullException(nameof(adapterIntegration));
        }

        [Route("events")]
        [HttpPost]
        public async Task<IActionResult> TriggerEvent([FromBody]SomeCustomEvent event, CancellationToken cancellationToken)
        {
            var botAppId = GetBotAppIdFromConfig();
            var conversationReference = await GetConversationReferenceRelatedToEventAsync(event);
           
            // Here's the downcast that breaks the abstraction just to call ContinueConversationAsync
            await ((BotAdapter)_adapterIntegration)
                .ContinueConversationAsync(
                botAppId,
                conversationReference,
                (turnContext, cancellationToken) =>
                {
                    // … whatever logic ...
                },
                cancellationToken);

            return new NoContentResult();
        }
    }
```

[enhancement]

**Comment by cleemullins** [comment]
Thanks Drew. Comments in the PR.

**Comment by cleemullins** [comment]
@garypretty Gary, to take this is a breaking change as it adds an method to an interface. I suspect you've implemented this interface as part of your custom adapters. Can you take a quick look and render your opinion? 

Normally "Breaking Change" == Don't take". In this case though, I suspect we may be fine.

**Comment by garypretty** [comment]
@cleemullins @drub0y Thanks for the heads up - I am not actually using this interface at the moment. I need to take a look and see how / where it is used to see if I should be :) From the name I think what I have was done before this was introduced.  I took a copy of the bot framework adapter integration libraries and modified those to work for my adapter.  Still working at the moment.

I'll take a look at the usage and see what I need to do anyway.

**Comment by garypretty** [comment]
@drub0y @cleemullins Just taken a further look - it looks like some work has been done to simplify the use of adapters, so that I don't need my own integration libraries. Is that right?  It appears BotFrameworkAdapter implements BotAdapter and IAdapterIntegration - whereas I just implement BotAdapter.

What is the correct / recommended approach here? As I also found a SimpleAdapter, which only uses BotAdapter :)

For reference - you can see my adapter and the integration libraries derived from yours here https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Adapters.Alexa

**Comment by drub0y** [comment]
So the integration layer originally just registered the `BotFrameworkAdapter` itself with the container for its own internal use and didn't support any other types of adapters because it was not a goal of the integration at the time. @johnataylor introduced `IAdapterIntegration` to provide an abstraction which decoupled this, but when it was created it was only created to handle processing of incoming activities (i.e. `ProcessActivityAsync`) and didn't offer support for proactive (i.e. `ContinueConversationAsync`). Now people are trying to trigger proactive scenarios through their own proprietary controllers and the only thing they can really have injected into them is `IAdapterIntegration`, but they are forced to downcast this to a known implementation to access the `ContinueConversationAsync`.

The base `BotAdapter` class is still the abstraction to implement your own adapter. The `IAdapterIntegration` is really just a helpful abstraction for the `BotFrameworkAdapter` and the way it's used by the integration layer. The generic name might make it seem like more, but it's really not useful outside of the integration layer and I wouldn't expect others to implement it. I don't even think `BotFrameworkAdapter` should be implementing it directly, if anything it should have been wrapped by an integration class that delegated to `BotFrameworkAdapter`, but that ship has sailed.

I don't see you implementing it in the `BotBuilderCommunity` repo, so... this is probably a non-issue for you as I suspected. I really don't think this will hurt anyone as long as they upgrade all packages at once, but if we don't even want to risk that then here's an alternative proposal:

 1. Introduce a new `IProactiveAdapterIntegration` interface with only the `ContinueConversationAsync` method on it, leaving `IAdapterIntegration` alone.
 2. Update the `BotFrameworkAdapter` to implement this interface as well

This is non-breaking in every way and, arguably, cleaner in terms of SRP. Argument against is that it just adds another type into the universe that people have to understand, but, again, it's really only for the integration layers.
