### ISSUE TITLE
Support for CosmoDbTranscriptStore

### ISSUE THREAD

**Issue by james-novino** [Microsoft/botbuilder-dotnet#1294]
**Is your feature request related to a problem? Please describe.**
We have been using the v3 framework for some time in production and handled rolled a version of the AzureBlobTranscriptStore ourselves that used CosmoDB as a backing store so that we could take advantage of some things like the Change Feed to project data and metrics into additional datastore. It appears that only Blob Storage is supported out of the box for use as a transcript store. 

**Describe the solution you'd like**
Would like to have the same functionality and ease of use to be able to store chat transcripts into Cosmos DB instead of blob storage without having to hand roll our own chat transcript projector. 

**Describe alternatives you've considered**
The most obvious alternative would be to define and pass our own transcript provider using the CosmosDbStorage. 

[enhancement]

**Comment by benbrown** [comment]
We don't plan on doing this, however in 4.4 there will be an Azure EventHubs transcript store.  Using the stream processing pipeline, you'll be able to publish to wherever you'd like...

THAT SAID, feel free to send us a PR!
