### ISSUE TITLE
Verbose Intents from LUIS are projected in an unordered IDictionary

### ISSUE THREAD

**Issue by paulio** [Microsoft/botbuilder-dotnet#1303]
## Version
4.2

## Describe the bug
Bug is a strong word here, but the problem is that when a list of Intents is returned from LUIS they are returned in descending score order. This is very useful. However, the SDK projects them via an IDictionary. This is great when you wish to fetch a known Intent by key, but IDictionary doesn't guarantee the order so the client is forced to use Linq (or equivalent) to re-order them. It would be helpful to either explicitly use an OrderedDictionary or perhaps provide a new property array of ordered Intents. 

## To Reproduce
1. Ensure you get a list of the Intents from LUIS, e.g.
var app = new LuisApplication(luis.AppId, luis.AuthoringKey, luis.GetEndpoint());
var recognizer = new LuisRecognizer(app, new LuisPredictionOptions { IncludeAllIntents = true });
2. Make a call to LUIS and see that the Intents are exposed as an IDictionary. Whilst it appears they are correctly ordered IDictionary does not guarantee it.

## Expected behavior
Either replace IDictionary with IOrderedDictionary (or equivalent) or expose a new ordered property, e.g. OrderedIntents[]

[bug]

**Comment by sgellock** [comment]
This is a breaking change, so we can't really fix this until we do a major release.  you can use the helper method LuisRecognizer.TopIntent()

**Comment by paulio** [comment]
I don't believe it is a breaking change as the property exposes IDictionary which an OrderedDictionary can also expose. It's the underlying Dictionary vs OrderedDictionary that would change. Nor would adding a new method or property be a *breaking* change so I don't understand your point? In my pull of the code I've added orderedIntents to the Properties collections. Also how would TopIntent help?
