### ISSUE TITLE
OAuthPrompt default timeout: 15 minutes or hours?

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/botbuilder-dotnet#1307]
## Version

master branch

## Describe the bug

In [OAuthPrompt.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L55), it says the default prompt timeout is 15 minutes in milliseconds, but the value assigned to `DefaultPromptTimeout` is 15 hours and not 15 minutes:

>         // Default prompt timeout of 15 minutes (in ms)
>     private const int DefaultPromptTimeout = 54000000;

15 minutes in milliseconds would be nine-hundred thousand instead of fifty-four million. I would submit a pull request myself but I am unsure which value was intended, so I don't know if the value needs to be updated or the comment. Please advise.

[bug]

**Comment by dmvtech** [comment]
Clarified this should be 15 minutes. Comment is correct, int value is incorrect.
