### ISSUE TITLE
NuGet packages reference SourceLink as a runtime dependency rather than dev dependency

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#1310]
## Version
4.2.x

## Describe the bug
The libraries that produce NuGet packages have a reference to the `SourceLink.Create.CommandLine` package, but they lack the `PrivateAssets="All"` attribute which ultimately results in there being a transitive dependency to the package for consumers of the SDK.

## To Reproduce
1. Install any SDK package (e.g. `Microsoft.BotBuilder.Schema`) from NuGet
2. Notice that `SourceLink.Create.CommandLine` is installed as a transitive dependency to your application's project

## Expected behavior
Since SourceLink is a tool used during the development of the SDK packages, I would not expect there to be a transitive dependency to it from the published packages.

## Additional Context
One fix is to simply manually add `PrivateAssets="All"` to the `PackageReference`  for `SourceLink.Create.CommandLine` across all the projects. 

Another, simpler fix is to just update the package to 2.8.3 (latest as of right now) which will has the proper metadata to trigger `PrivateAssets` to be set automatically (along with some other properties).

[bug]

**Comment by james-novino** [comment]
As of version 4.2.2 this is still an issue. Is there an open PR to change the proejcts to use `PrivateAssets=All`?

**Comment by blrchen** [comment]
Still see this issue on 4.3.2. Why it's closed? @cleemullins 
![image](https://user-images.githubusercontent.com/1607381/55044848-cbf98080-5076-11e9-9aeb-530a75ff9c95.png)

**Comment by volthezz** [comment]
@cleemullins, this bug should be reopened, because #1324 
did not fix the bug, it only updated the version number
