### ISSUE TITLE
AlarmBot sample is overly complicated and confusing

### ISSUE THREAD

**Issue by apulliam** [Microsoft/botbuilder-dotnet#132]
AlarmBot is overly complicated.  It requires a separate middleware component to implement each topic in a conversation.  This sample implies that middleware is the recommended approach for modeling conversations.

**Comment by Stevenic** [comment]
Good feedback... We should re-factor this to not require the use of middleware.

**Comment by cleemullins** [comment]
@tomlm Tom is in-process refactoring this now to be much simpler.

**Comment by tomlm** [comment]
The first part of this has been fixed, removes the template middleware
