### ISSUE TITLE
Update the samples to remove obsolete SDK calles to BotFrameworkOptions.State property

### ISSUE THREAD

**Issue by JSWilsonX** [Microsoft/botbuilder-dotnet#1321]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
It is hard to understand how to persist state while collecting user input as the samples I have looked at have calls to BotFrameworkOptions.State property which has been removed.

**Describe the solution you'd like**
Please update the samples to work with V4 these are the ones I have found: https://github.com/Microsoft/BotBuilder-Samples

**Describe alternatives you've considered**
A better alternative is to provide templates for Visual Studio Mac. Another approach would be to provide more samples in Azure with varying degrees of complexity.

**Additional context**

[enhancement]

**Comment by jwiley84** [comment]
If I'm not mistaken, this was solved with https://github.com/Microsoft/BotBuilder-Samples/pull/1228

**Comment by jwiley84** [comment]
I actually was mistaken. 1228 fixed the JS ones, but the CSharp one are still riddle with this call. I apologize.

**Comment by johnataylor** [comment]
This is fixed with the move to an mvc model. All the new samples use this pattern.
In the samples repo, refer to samples-work-in-progress for a snapshot before we merge that into master.
