### ISSUE TITLE
Choice Prompt selection issue on MS Team channel 

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/botbuilder-dotnet#1323]
## Version
BotBuilder 4.2.0

### Web View
Choice Prompt doesn't show buttons on Teams. It works fine on Web Chat and Emulator like below.
![image](https://user-images.githubusercontent.com/118657/51872437-7486af00-236a-11e9-8962-5bfd018697b6.png)

### MS Teams View
On Teams, it shows only text selection as list options like below.
![image](https://user-images.githubusercontent.com/118657/51872502-bf082b80-236a-11e9-9960-2284a7fed1a6.png)

### Bug on MS Teams
Whenever I try with typing numbers instead of typing full text I got below error.
![image](https://user-images.githubusercontent.com/118657/51872179-97fd2a00-2369-11e9-82cd-e1daafe51aa4.png)

**Comment by garypretty** [comment]
@ikivanc This looks like it might be related to issue #1170 where your prompt is using suggested actions, but this is not supported in Team at present, hence why the Teams channel is falling back to a format that it can support.
