### ISSUE TITLE
Cortana Choice Factory Support for Card with Buttons

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#1335]
Both the JS and C# SDK should support sending a card with buttons to Cortana.

**Comment by cleemullins** [comment]
(Filed during a conversation with @stevenic)

**Comment by garypretty** [comment]
@cleemullins I submitted a PR for this on the .NET side last night :) #1339

**Comment by cleemullins** [comment]
Resolved
