### ISSUE TITLE
Bot.Connector.Tests use old version of the Azure.TestFramework

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#1338]
The version of the AzureTestFramework being used by the Connector is out of date, and emitting warnings around Newtonsoft. 

```
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.Azure.Test.HttpRecorder 1.7.0 requires Newtonsoft.Json (>= 9.0.1 && < 10.0.0) but version Newtonsoft.Json 10.0.3 was resolved.	

C:\git\botbuilder-dotnet\tests\Microsoft.Bot.Connector.Tests\Microsoft.Bot.Connector.Tests.csproj
```

I attempted to upgrade this to a later version, and came across conflicts with IdentityToken pacakges and other unexpected issues. 

That we're using Newtonsoft > 10, and this package as a constraint of < 10.0, is a problem we need to resolve.

**Comment by cleemullins** [comment]
Moving to 4.4, as this is blocked waiting on the underlying dependencies to be updated by those teams. @juanar to add detail here.

**Comment by ceciliaavila** [comment]
> Moving to 4.4, as this is blocked waiting on the underlying dependencies to be updated by those teams. @JuanAr to add detail here.

This is the current situation that causes the versions conflict:

| Project                                                | Microsoft.Bot.Connector.Tests  | Microsoft.Bot.Schema |
| ---------------------------------------  |  --------------------------------- | ------------------------ |
| Dependency                                       | Microsoft.Rest.ClientRuntime.Azure.TestFramework   1.6.0 |  
| Sub-dependency                                | Microsoft.Azure.Test.HttpRecorder   (>=   1.7.0 && < 2.0.0) |  
| Version of Newtonsoft.Json required | >= 9.0.1 && < 10.0.0 | >=10.0.3

We tried different approaches to solve this but we found new conflicts:
 
1.	Update **Microsoft.Rest.ClientRuntime.Azure.TestFramework** package to [version 1.7.6](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.TestFramework/1.7.6)
 
The resulting conflict:

| Project                                                | Microsoft.Bot.Connector.Tests  | Microsoft.Bot.Connector |
| ---------------------------------------  |  --------------------------------- | ------------------------ |
| Dependency | Microsoft.Rest.ClientRuntime.Azure.TestFramework 1.7.6 |  
| Sub-dependency | Microsoft.Rest.ClientRuntime.Azure.Authentication   (>= 2.3.7 && < 3.0.0) |  
| Version   of Microsoft.IdentityModel.Clients.ActiveDirectory    required | >= 3.14.0 && < 4.0.0 | >= 4.5.0
| Version   of Microsoft.IdentityModel.Tokens required | = 5.1.2 | >= 5.2.1

2.	Downgrade  **Newtonsoft.Json** to [version 9.0.1](https://www.nuget.org/packages/Newtonsoft.Json/9.0.1) in Microsoft.Bot.Connector.Tests and Microsoft.Bot.Schema
 
The resulting conflict:

| Project                                                | Microsoft.Bot.Connector.Tests  | Microsoft.Bot.Connector |
| ---------------------------------------  |  --------------------------------- | ------------------------ |
| Dependency | Microsoft.Rest.ClientRuntime.Azure.TestFramework   1.6.0 | Microsoft.IdentityModel.Protocols.OpenIdConnect   (5.2.1)
| Subdependency | Microsoft.Azure.Test.HttpRecorder      (>=   1.7.0 && < 2.0.0) |  
| Version   of    Newtonsoft.Json      required | >= 9.0.1 && < 10.0.0 | >= 10.0.1

**Comment by cleemullins** [comment]
@juanar It doesn't look like anything has changed, but can you take a look and sanity check my checking of your checking? :)

**Comment by cleemullins** [comment]
Closing.

**Comment by johnataylor** [comment]
We need to upgrade our Newtonsoft json dependency because the current version is holding us back from using asp 2.1 json support.

**Comment by johnataylor** [comment]
also see https://github.com/microsoft/botbuilder-dotnet/pull/3020

**Comment by EricDahlvang** [comment]
I think this was unblocked by: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.TestFramework/1.7.7

Closing the issue since https://github.com/microsoft/botbuilder-dotnet/pull/3020 has been merged.
