### ISSUE TITLE
Rename State.Conversation to ConversationState or ConversationProperties

### ISSUE THREAD

**Issue by apulliam** [Microsoft/botbuilder-dotnet#134]
The Conversation object is of type ConversationState, which is a dictionary of conversation state items added by the developer.  By convention, C# developers may expect Conversation["key"] to be an indexer into a collection of Conversations (ie: different Bot interactions).  Renaming to Conversation to ConversationState or ConversationProperties would better convey that the object is a container for conversation state objects or properties.

**Comment by Stevenic** [comment]
Good suggestion

**Comment by cleemullins** [comment]
Addressed in PR #159
