### ISSUE TITLE
TestAdapter swallows meaningful exception details in AssertReply

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#135]
The `AssertReply` method is currently swallowing meaningful, underlying exception details by throwing its own exception with nothing but the message `"failed"` when the underlying `Task` has faulted. This obscures the underlying issue from the developer and forces them to have to do something like running the test under the debugger and enable first chance exception handling (which some developers wouldn't even know how to do).

This is caused by the following logic:

https://github.com/Microsoft/botbuilder-dotnet/blob/c2020041672df0e5773f532d3dc0367c2a08604d/libraries/Microsoft.Bot.Builder/Adapters/TestAdapter.cs#L354-L357

The fix here is to pass the `Task`'s `Exception` property as the inner exception of the new exception being thrown. This will allow the full details of the original exception to flow all the way back to the test so that the developer can identify what actually went wrong. Additionally I would suggest improving the exception message from simply `"failed"` to something little more helpful like: `"An reply assertion has failed. Please check the inner exception for more details."`

**Comment by cleemullins** [comment]
This is a great find. I've been personally frustrated by the lack of exceptions here a few times, but never had a chance to dig into why things weren't propagating.

**Comment by cleemullins** [comment]
I've submitted PR #140 for review. 

Before merging, I would be very interested in seeing if you have suggestions for how to better test the new code/behavior. The inner workings of "Task" are still a bit foreign to me, and a 2nd set of eyes would be great.

**Comment by cleemullins** [comment]
Fixed. Thanks Drew!!!
