### ISSUE TITLE
De-serialization of RecognizerResult entities

### ISSUE THREAD

**Issue by joseques** [Microsoft/botbuilder-dotnet#1361]
**Is your feature request related to a problem? Please describe.**
The `RecognizerResult` entities given by the recognizer is harder to manipulate them being `JObject`.

**Describe the solution you'd like**
De-serializing the entities using generics like the `dynamic` type or even a using a `Dictionary` would help a lot in terms of data manipulation in the case when the bot heavily relies on the metadata given by the `RecognizerResult` entities.
Fairly similar to what has been done with the Intents in #731

[enhancement]

**Comment by SarangRapid** [comment]
Kudos to you @joseques to point out this issue, when RecognizerResult is exposing GetTopScoring intent, it should expose another similar function to provide list of entities, it is so hard to manipulate it as even entities JSON is also dynamic to cast into object

**Comment by SarangRapid** [comment]
Here is workaround,
 once you receive RecognizerResult value, type cast it to dictionary of string and object
```
var entitiesDictionary = luisResults.Entities.ToObject<Dictionary<string, object>>();
```
Entities first child will always be $instance, which will be empty if there are no entities else will have standard object values, while from the second child, Entities object will have desired key and value of entities, so we can just start iterating through second object and add values in custom object.

```
if (entitiesDictionary.Count > 1)
            {
                for(var i=1; i< entitiesDictionary.Count; i++)
                {
                    onTurnProperties.Entities.Add(new EntityProperty(entitiesDictionary.ElementAt(i).Key, entitiesDictionary.ElementAt(i).Value));
                }
            }
```

so values will be generalised to object type so later it can be type caste to desired type

**Comment by joseques** [comment]
Hey @SarangRapid as a workaround looks great!
But still overly complicated, as it should be simpler by design IMHO

**Comment by johnataylor** [comment]
Agreed this is a problem. It is particularly awkward with the extra levels of nesting introduced by using things like composites and along with the lack of cardinality in the model.

Some people have commented that using the generated strongly typed wrappers can help. However, the nesting and cardinality concerns are not addressed by those.

One pattern we have added to the new samples (if it's not on master yet, see samples-work-in-progress) is to put all the LUIS entity code behind a helper class specific to your application (see how the BookingDetails are built from the LUIS result in core bot, class LuisHelper.) This is not ideal but cleans the top level code up. (Note the datetime is particularly awkward.)

There is also ongoing work to raise the level of abstraction you are working with when writing Dialogs. Hopefully that will go some way to relieving this.

If there is a specific helper extension function you think would be useful please open an issue or a PR would be great.
