### ISSUE TITLE
Fix the release build settings for document XML generation

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#1364]
## Version
4.2.2

## Describe the bug
The Microsoft.Bot.Builder.Azure NuGet package contains incorrect doc XML content.

## To Reproduce
1. Download the Microsoft.Bot.Builder.Azure package, v 4.2.2.
1. Extract the contents.
1. Open **microsoft.bot.builder.azure.4.2.2\lib\netstandard2.0\Micorosoft.Bot.Builder.Azure.xml**
1. Find the entry for the **CosmosDbCustomClientOptions.DocumentCollectionRequestOptions** property.
1. Error: the summary contains a `<see>` tag with a **cref** value of `!:https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions?view=azure-dotnet`.

## Expected behavior
1. The corresponding /// comments for this property contain the tag:
`<see cref="Microsoft.Azure.Documents.Client.RequestOptions"/>`.
1. This should generate the following doc XML tag:
`<see cref="T:Microsoft.Azure.Documents.Client.RequestOptions"/>`, not one that has a value that starts with `!https://`.

## Additional context
See the ref page for the [CosmosDbCustomClientOptions.DocumentCollectionRequestOptions Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.azure.cosmosdbcustomclientoptions.documentcollectionrequestoptions?view=botbuilder-dotnet-stable) to see how this renders.

The build is currently producing about 6 such errors.

[bug]

**Comment by cleemullins** [comment]
I've tried to duplicate this on the latest 4.3 codebase ("master"). In master, I had already completly re-done all of the project files - including how documentation is generated - as part of cleaning up our build. 

That was PR #1314. 

That PR moved all of the Doc Generation settings to the Build.Directory.Props file, and standardized all of the settings across the suite. 

When I look at the Microsoft.Bot.Builder.Azure.xml file generated as part of a *Documentation* targeted build, all looks good. The XML looks like:
```
        <member name="T:Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions">
            <summary>
            CosmosDB options for custom client.
            </summary>
        </member>
```
The entire file does not have a single microsoft.com reference in it, as evidenced here:
```
C:\git\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure\bin\Documentation\netstandard2.0>dir *.xml
 Volume in drive C has no label.
 Volume Serial Number is 2A77-7BE4

 Directory of C:\git\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure\bin\Documentation\netstandard2.0

02/07/2019  11:58 AM            20,067 Microsoft.Bot.Builder.Azure.xml
02/07/2019  11:58 AM           198,461 Microsoft.Bot.Builder.xml
02/07/2019  11:58 AM           181,371 Microsoft.Bot.Connector.xml
02/07/2019  11:58 AM           198,200 Microsoft.Bot.Schema.xml
               4 File(s)        598,099 bytes
               0 Dir(s)  343,090,954,240 bytes free

C:\git\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure\bin\Documentation\netstandard2.0>grep microsoft.com *.xml
Microsoft.Bot.Connector.xml:                https://docs.microsoft.com/bot-framework/rest-api/bot-framework-rest-connector-authentication
Microsoft.Bot.Schema.xml:            See https://msdn.microsoft.com/library/hh456380.aspx for a list of valid language codes
```

I than build a local **Release** build, which generates NuGet packages and XML packages. I extracted the XML file from the Nuget, and found the same results:
```
        <member name="T:Microsoft.Bot.Builder.Azure.CosmosDbCustomClientOptions">
            <summary>
            CosmosDB options for custom client.
            </summary>
        </member>
```

Lastly, I pulled down the [most recent Nuget package](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.Azure) from our daily feed. This also didn't show any issues. 

**I cannot duplicate this on the 4.3 codebase.** 

I'm going to mark this resolved. If I missed something, please let me know and I'm happy to look again.
