### ISSUE TITLE
"The given key 'instanceId' was not present in the dictionary." when ending dialog

### ISSUE THREAD

**Issue by MattDavies** [Microsoft/botbuilder-dotnet#1368]
## Version

4.2.2

## Describe the bug

The exception listed below is thrown occasionally internally in the framework when calling the following from a waterfall dialog step:

`return await stepContext.EndDialogAsync(cancellationToken);`

I can also get this to happen sporadically by calling the following:

`dialogContext.CancelAllDialogsAsync(cancellationToken);`

## To Reproduce

I've been unable to determine exactly what causes this, as it doesn't happen with every call. This started occurring after upgrading from version 4.2.0 to 4.2.2 of the SDK, which I needed in order to pull in the fix for issue 1251.

## Expected behavior

Expecting the dialog to be ended without exception.

## Additional context

Full exception stacktrace as follows:

> Message	The given key 'instanceId' was not present in the dictionary.	
> Exception type	System.Collections.Generic.KeyNotFoundException	
> Failed method	Bot.Features.Test.TestDialog+<ThanksStep>d__7.MoveNext
> 
> System.Collections.Generic.KeyNotFoundException:
>    at System.ThrowHelper.ThrowKeyNotFoundException (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Collections.Generic.Dictionary`2.get_Item (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<OnStepAsync>d__11.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<RunStepAsync>d__12.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<ResumeDialogAsync>d__9.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.DialogContext+<EndDialogAsync>d__18.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Bot.Features.Test.TestDialog+<ThanksStep>d__7.MoveNext (Bot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Bot\Features\Test\TestDialog.csBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 142)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<OnStepAsync>d__11.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<RunStepAsync>d__12.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<ResumeDialogAsync>d__9.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallStepContext+<NextAsync>d__18.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Bot.Features.Test.TestDialog+<HandleSelection>d__6.MoveNext (Bot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Bot\Features\Test\TestDialog.csBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 79)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<OnStepAsync>d__11.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<RunStepAsync>d__12.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<ResumeDialogAsync>d__9.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallStepContext+<NextAsync>d__18.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Bot.Features.Test.TestDialog+<PromptSubmission>d__5.MoveNext (Bot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Bot\Features\Test\TestDialog.csBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 59)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<OnStepAsync>d__11.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<RunStepAsync>d__12.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<BeginDialogAsync>d__7.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.DialogContext+<BeginDialogAsync>d__15.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.DialogContext+<ReplaceDialogAsync>d__20.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Bot.Features.Test.TestDialog+<HandleSelection>d__6.MoveNext (Bot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Bot\Features\Test\TestDialog.csBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 98)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<OnStepAsync>d__11.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<RunStepAsync>d__12.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.WaterfallDialog+<ResumeDialogAsync>d__9.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.DialogContext+<EndDialogAsync>d__18.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.Prompt`1+<ContinueDialogAsync>d__5.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.Dialogs.DialogContext+<ContinueDialogAsync>d__17.MoveNext (Microsoft.Bot.Builder.Dialogs, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Bot.Bot+<OnTurnAsync>d__5.MoveNext (Bot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Bot\Bot.csBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 136)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Bot.Infrastructure.TelemetryLoggerMiddleware+<OnTurnAsync>d__13.MoveNext (Bot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\Bot\Infrastructure\TelemetryLoggerMiddleware.csBot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 144)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.MiddlewareSet+<ReceiveActivityWithStatusAsync>d__3.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Bot.Builder.BotAdapter+<RunPipelineAsync>d__13.MoveNext (Microsoft.Bot.Builder, Version=4.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)

Specific issue seems to be WaterfallDialog.cs line 158

var instanceId = stepContext.ActiveDialog.State[PersistedInstanceId] as string;

**Comment by ceciliaavila** [comment]
Hi @MattDavies, @johnataylor, 
We started reviewing this issue. We did some tests but couldn't reproduce the error. We tested a bot that uses ChoicePrompt and the **InstanceId** was created correctly in _BeginDialogAsync_ method and it was there when the _EndDialogAsync_ method was called. 

@MattDavies, could you please give us more information about the bot you are testing? Does it manage different Dialogs?
We are trying to figure out when can this be happening.

The **InstanceId** is created in _[BeginDialogAsync](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs#L64)_ method of WaterfallDialog class:
![image](https://user-images.githubusercontent.com/44245136/55030348-f56cca80-4fea-11e9-93c8-f3744a1cf223.png)

Then is used in _[EndDialogAsync](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/WaterfallDialog.cs#L131)_ method of WaterfallDialog class:
![image](https://user-images.githubusercontent.com/44245136/55030409-10d7d580-4feb-11e9-9017-e4d9f8a66997.png)

Thanks!

**Comment by MattDavies** [comment]
Hi @ceciliaavila! Sorry for the slow response. Thanks for investigating.

I went through a similar thought process as you when debugging. I landed on the theory that because we were running 4.2.0, a bunch of dialogs were created without an instanceId. When we updated to 4.2.2, and the code tries to cancel/end those legacy existing dialogs, it hits an error because the instanceId isn't set.

When a new dialog is created and then ended while fully on 4.2.2 through the whole process, there's no issue as you mentioned. I think this problem is just caused by the fact we introduced a breaking change.

I've been able to resolve by clearing out the legacy state records from storage.

**Comment by johnataylor** [comment]
Using the storage abstractions included in the SDK when you upgrade version you must clear out the conversation state. (Note conversation state should be treated something similar to cookie state on a web site. For example, it is best practice to have a leaked exception from a Dialog, delete the current conversation state with the global error handler.)

If are of course free to implement your own plugin storage solution that has stronger guarantees, however that is a non-trivial exercise.

Sample 42 demonstrates how to build a storage solution from the ground up. Though that solution does not guarantee cross version compatibility of the persisted state - it just demonstrates how to plug in alternative solutions.

**Comment by HugoPeters1024** [comment]
Should anyone else stumble across this issue, it appears that inheriting from WaterfallDialog whilst actually intending just having a generic Dialog, also causes this issue.

Package version: Microsoft.Bot.Builder.Dialogs 4.7.2
