### ISSUE TITLE
QnAMaker Middleware calling context.Reply() directly

### ISSUE THREAD

**Issue by daltskin** [Microsoft/botbuilder-dotnet#137]
QnAMaker Middleware is sending output directly to the user.  What if developer needs to format the result/use adaptive card etc..

Workaround to clone the Microsoft.Bot.Builder.Ai.QnAMaker class and store QnA response in bot state (which seems hacky) eg:

 ```cs
        public async Task ReceiveActivity(IBotContext context, MiddlewareSet.NextDelegate next)
        {
            if (context.Request.Type == ActivityTypes.Message)
            {
                var messageActivity = context.Request.AsMessageActivity();
                if (!string.IsNullOrEmpty(messageActivity.Text))
                {
                    var results = await this.GetAnswers(messageActivity.Text.Trim()).ConfigureAwait(false);
                    if (results.Any())
                    {
                        // Store results in state for handling by TemplateRenderer later
                        context.State.Conversation["QnAResult"] = results;
                    }
                }
            }

            await next().ConfigureAwait(false);
        }

**Comment by Stevenic** [comment]
So as a general rule, our goal is to make all of the built-in services usable both freestanding and as middleware.  The JS SDK has the exact opposite problem that you can only use QnA Maker in freestanding mode right now. Please continue to file issues like this and we'll have all of these lose edges sewed up soon.

**Comment by cleemullins** [comment]
For now, I think this is "By Design". As we move soon to a model where there is significantly improved stateful interactions between Middleware components, we should come back and revisit this.
