### ISSUE TITLE
Update libraries\swagger\readme.md with detailed steps for re-generating clients from swagger

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#1372]
The current readme doesn't describe the process from end-end which is what we need.  I realize that there's some hand editing that has to happen but that process should be described in detail as well.

[enhancement]

**Comment by CoHealer** [comment]
@tdurnford, can you please assist?

**Comment by CoHealer** [comment]
Removing Support with reassignment to Axel.

**Comment by axelsrz** [comment]
In 4.5 we're going to discuss the plan for moving forward with this.

**Comment by sgellock** [comment]
we've moved off of using swagger to generate the client
