### ISSUE TITLE
Why RecognizerResult doesn't contain the same JSON result from luis.ai

### ISSUE THREAD

**Issue by jolienai** [Microsoft/botbuilder-dotnet#1375]
Here is what I get from the RecognizerResultAsync method 
![screenshot 2019-02-11 at 21 03 30](https://user-images.githubusercontent.com/47538362/52587683-38ac1900-2e43-11e9-9258-ebe375276d58.png)

Why we have more then one entity e.g Service?

Which is different from what I've got from luis.ai, see below:
![screenshot 2019-02-11 at 21 03 53](https://user-images.githubusercontent.com/47538362/52587716-4cf01600-2e43-11e9-9417-2c836347f1f3.png)

**Comment by Zerryth** [comment]
Hi @jolienai. Thank you for posting. This is already a known issue, however, and fix is scheduled for 4.4 release. 

Track issue here [LuisRecognizer should expose full LUIS response](https://github.com/Microsoft/botbuilder-dotnet/issues/1348) 

Closing dupe.

**Comment by xtianus79** [comment]
@zerryth what is a 4.4 release and is there a timeline for that release? or roadmap
