### ISSUE TITLE
[SDK Parity] JS implementation of LuisRecognizer defaults endpoint to westus if endpoint is falsey

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-dotnet#1387]
## Describe the bug
Difference in implementation between JS and C#: In JavaScript, the LuisRecognizer will pass "https://westus.api.cognitive.microsoft.com" to LuisRecognizer.luisClient if no endpoint was specified.

## Expected behavior
Language parity.
[bug]

**Comment by stevkan** [comment]
Submitted PR [#1574](https://github.com/Microsoft/botbuilder-dotnet/pull/1574) - sets the LUIS default endpoint.

**Comment by daveta** [comment]
@munozemilio and I ran through the code - in both cases, if the endpoint is null/empty is should throw.  We probably should remove the default endpoint to make it clearer and add tests to make sure.

**Comment by stevengum** [comment]
@daveta we can't back out the default behavior in JS because that would be a breaking change. Our tests use this behavior in the JS repo.

**Comment by daveta** [comment]
My bad - I thought credentials were validating endpoint, they are validating endpoint key!
