### ISSUE TITLE
[OAuthPrompt]When times out, the response cannot be used to specify it's a 'timeout'

### ISSUE THREAD

**Issue by lzc850612** [Microsoft/botbuilder-dotnet#1398]
## Version
4.2

## Describe the bug
In OAuthPrompt, when the request times out, the prompt just returns the cancellationToken, instead of a proper response that contains 'timeout' indicator in any form. This gives the bot no way of knowing that the prompt failed because of timeout or some other reason, thus not able to give a proper response to the user.

## To Reproduce
1. Launch the OAuthPrompt whose timeout is very short
2. Wait until the timeout has passed and then input the magic code
3. The Result that's returned from OAuthPrompt is a cancellationToken.

## Expected behavior
The Result that's returned from OAuthPrompt is an object that has something to indicate that the operation timed out.

## Additional context

[bug]

**Comment by Jeffders** [comment]
The correct signal is that the prompt returns the expired cancellation token. When you get a result from the OAuthPrompt, simply check the type (is it a canellationToken or a TokenResponse object type). Then the bot will know what to do.
