### ISSUE TITLE
CoreBot template is a misnomer

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#1399]
The CoreBot template that ships with the v4 VSIX package leads developers to believe it's a bot comprised of only the core functionality required to ship a bot. In fact this template is loaded up with endpoints to LUIS, cognitive models, and dialogs; we should rename this VSIX to be more descriptive as to what it actually delivers.

**Comment by cleemullins** [comment]
@sgellock - My recollection is the "CoreBot" was settled on as a name after quite a bit of deliberation between our team and CSE. Changing this in the VSIX is easy enough, if we decide we want to make that decision.

**Comment by sgellock** [comment]
@brandonh-msft we've got round and round on the name of this particular sample.  The argument went something like this:  "Basic Bot?  It's not basic, there's enough stuff to learn here that it's not basic.  It really contains the core functionality of a bot.  Please call it CoreBot"
