### ISSUE TITLE
TurnContext access from a dialog isn't discoverable, affordable

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#1403]
Developers looking for an `ITurnContext` while inside a dialog are unable to easily discover that it exists on the `IStepContext` due to its naming.
`.Context` property on `IStepContext` doesn't convey this is an `ITurnContext` object; should be called `TurnContext` for discoverability and affordability.

**Comment by cleemullins** [comment]
We cannot changes names w/o breaking compatability. 

The *closest* we could come would be duplicate properties and liberal use of the "[Obsolete]" attribute. At this point, I don't believe we should do either in the v4 SDK.

**Comment by sgellock** [comment]
won't fix.
