### ISSUE TITLE
Replacing DialogSet in DialogContext with an interface

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/botbuilder-dotnet#1409]
What about replacing the `DialogSet` in `DialogContext` with an interface (e.g. IDialogProvider) that has at least a single method:
``` csharp
Task<Dialog> GetDialogAsync(string id);
```
`DialogSet` itself will implement it, e.g.:
``` csharp
public Task<Dialog> GetDialogAsync(string id) => Task.FromResult(Find(id));
```
In this way `DialogContext` could use different implementations of that interface (e.g. that dynamically create dialogs, or get them from a central repository, etc.).

Btw, I don't understand way the `DialogContext.FindDialog` is public (I beleave it should be used only in  `DialogContext` itself). This solution will introduce a breaking change if that method is used outside the `DialogContext` (after refactoring it as awaitable).

P.S.
I saw a few issues that could be linked to that and usually the proposed suggestion was to use `ComponentDialog`, so it could be considered as an alternative solutions.

**Comment by johnataylor** [comment]
Yes the suggestion is correct, application logic should always be factored into ComponentDialog.

You should not have to be concerned with DialogSet and DialogContext, rather treat them as implementation detail.

Regarding the comment abnout FindDialog method being public, it is unfortunate that most of these classes are public. For a simple and effective way to use Dialogs see the latest rev of the sample code.

In particular take a look at DialogBot class that runs any dialog as a bot. It actually makes use of an extension method Run which completely hides any notion of DialogSet. This code is currently on a branch in the samples repo. It will become master in the next few days. Note the samples use ComponentDialogs everywhere and they also introduce the strong notion of a root dialog. The following pointers will be good until the branch is merged (and deleted) at which point you can find this code in master.

https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/csharp_dotnetcore/13.basic-bot/Bots/DialogBot.cs

https://github.com/Microsoft/BotBuilder-Samples/blob/samples-work-in-progress/samples/csharp_dotnetcore/13.basic-bot/DialogExtensions.cs
