### ISSUE TITLE
Implement key rotation in LuisRecognizer

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-dotnet#1413]
For high-volume Bots the 50 RPS limitation of LUIS can prove problematic to customers. Whilst RPS can be raised on a case by case basis this is not a universal panacea therefore leveraging [Traffic Manager and Key rotation](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-traffic-manager) is a more scalable option with Containers being an option to consider if the overhead of running infrastructure is an option.

However our default Luis implementation doesn't provide the ability to handle multiple keys or provide a round-robin implementation. This will increasingly be of important for high scale customers.

**Describe the solution you'd like**
- Extend the LuisRecognizer to support multiple endpoint keys to be passed either through direct usage or via configuration
- Implement simple round robin use of the keys if multiple are provided

**Describe alternatives you've considered**
- We could consider implementing this as part of one of the Templates if preferred in the short to medium term.

[enhancement]

**Comment by mdrichardson** [comment]
I'll use this comment for progress updates. It's not a high-priority issue, so it may take some time to complete.

- [X] [Get a working implementation in Node](https://github.com/mdrichardson/QuickTypeScriptBot/blob/luisRotation/node_modules/botbuilder-ai/src/luisRecognizer.ts)
- [ ] Clean up code in Node
- [ ] Write tests for Node
- [ ] Get a working implementation in C#
- [ ] Clean up code in C#
- [ ] Write tests for C#
- [ ] Submit PR

**Comment by daveta** [comment]
@cahann : FYI

**Comment by daveta** [comment]
Hi @darrenj : thanks for the suggestion.  
I like the simplicity of the approach you describe, but from a service operations perspective, it seems like the the containers or traffic manager would be best practices.  
- Adjusting quota: If the client was managing everything, then if they need to increase the quotas then that may represent a redeploy to your application (worst case) if you are managing configuration in things like appsettings/.env.  With Traffic Manager, a live site add or remove is a pretty controlled operation.
- Availability: Seems like traffic manager would be better for availability, in case something went down.  I don't know how sophisticated the tm dispatch is, but I imagine load might be part of the equation as well.

**Comment by CoHealer** [comment]
Michael sync'd with Dave who didn't feel it was worth pursuing at this time. Removing Michael and the Support label to free up to triage.

**Comment by gabog** [comment]
> With Traffic Manager, a live site add or remove is a pretty controlled operation.

Hi @daveta, are you referring to Traffic Manager in front of the bot? or in between the bot and multiple LUIS apps?
