### ISSUE TITLE
Feature Suggestion: Embed the ability for user to grade experience & provide that feedback to designer/bot owner

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-dotnet#1418]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Bots are (still) inherently bound to fail the conversation leading to the phenomena of the user trying to bail out & escalate to humans (operator, representative, '0'...). 

**Describe the solution you'd like**
BF should provide the mechanism for developers to hook in end user feedback capabilities for specific "turn" to help dev/designers track and improve failed conversations.

**Describe alternatives you've considered**
There are at least two levels for capturing end-user sentiment:
1. A shortcut (side button) to escalate to human. Essentially a '0'/operator/representative button (or the text itself). This is the "nuclear option" leading to increased support costs. Bot developers may not want to permit that in all cases.
2. A softer feedback button ( e.g.  :) or ;(  ), In some cases the developer may desire to provide the user with the ability to grade the answer (with side UI, or during beta) & provide feedback to enable improvement on specific points in the conversation. The developer may hook additional actions to the poor experience such that a reset, or escalation (opt 1 above).

The proposal is to enable some metadata property bag in turn communications to enable hook up of grading button.

[enhancement]

**Comment by cleemullins** [comment]
This is a great feature, but it's out of scope for this SDK. This could be considered for the WebChat control, although even there this requires a SAAS service backend.
