### ISSUE TITLE
4.3.1 Microsoft.Bot.Connector package causes build warning

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#1419]
## Version
4.3.1

## Describe the bug
When updating to 4.3.1 version of Microsoft.Bot.Connector package, I get this build warning for Microsoft.Azure.KeyValue.Core:

```
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.	
```

## Expected behavior
Packages should ideally not create warnings that the user can't resolve. Obviously not a breaking issue, but it does cause confusion.

[bug]

**Comment by torynfarr** [comment]
I'm experiencing this one as well (after updating the Bot Builder SDK libraries from 4.2.2 to 4.3.1).

**Comment by EricDahlvang** [comment]
More information can be found here: https://stackoverflow.com/a/54445320/86646

The recommendation is to suppress the warning:
![image](https://user-images.githubusercontent.com/11055362/54154266-c22d1780-43fe-11e9-98ad-27ac916d509b.png)

**Comment by cleemullins** [comment]
This has been there for a long time, it's only in 4.3 and 4.4, where I cleaned up the other warnings, that this is now visible. 

This is BLOCKED waiting on the KeyVault team to release dotnet-core versions. IT's been confirmed as "OK, don't worry about it" with the Azure Storage team.

**Comment by cleemullins** [comment]
We can't fix this yet, as the relevant sub-packages aren't available. 

Pushing to 4.5

**Comment by cleemullins** [comment]
There is *still* no NetStandard20 version of the [KeyVault DLL](https://www.nuget.org/packages/Microsoft.Azure.KeyVault.Core/). 

![image](https://user-images.githubusercontent.com/1165321/59541177-fd832a80-8eb4-11e9-881f-358fc88f0423.png)


I'm closing this out, as it seems unlikely the KeyVault team will ever fix this.

**Comment by EdwinOtten** [comment]
@cleemullins I'm not sure if this means anything but with the release of [Microsoft.Azure.KeyVault.Core 3.0.4](https://www.nuget.org/packages/Microsoft.Azure.KeyVault.Core/3.0.4) it **does** have dependencies to .NETStandard 2.0:

![image](https://user-images.githubusercontent.com/5310778/63583029-77f9b600-c59a-11e9-80d4-56d450c2ee1e.png)
