### ISSUE TITLE
Treat Warnings as Errors (StyleCop issues)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#1423]
Warnings should be treated as errors for all library projects. 

This should apply to both local builds and Azure Devops CI builds.

**Comment by cleemullins** [comment]
@GasparAcevedoZainSouthworks @ceciliaavila 

We're close - what's left before we can enable this?

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi @cleemullins,

We created the PR #1512 for solving this ISSUE. As there isn't any remaining Stylecop Warning in the whole solution, we can merge that PR and close this ISSUE.

**Comment by gabog** [comment]
Merged through #1512
