### ISSUE TITLE
NuGet package for heros and cards microsoft.bot.schema issues

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#143]
see in wiki https://github.com/Microsoft/botbuilder-dotnet/wiki/Sending-Cards-and-Attachments

all of the code references Microsoft.bot.builder.schema - I've been troubleshooting it for embarrassingly long time. It should be Microsoft.Bot.Schema

on a separate note, I can't seem to get that package in VS. I've downloaded source code from ABS, updated all the packages (to the v4), but I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Bot.Schema 4.0.0-alpha201802123'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by tomlm** [comment]
I have fixed the wiki page.
The issues is that our package is .NET Standard 2.0, you need to update your project to 4.6.1 to consume a .NET Standard package.  I wish they gave you a better error message then that.
