### ISSUE TITLE
Ability to change the Prompt Styling through PromptAsync

### ISSUE THREAD

**Issue by james-novino** [Microsoft/botbuilder-dotnet#1433]
**Is your feature request related to a problem? Please describe.**
In V3, we were able to change the prompt styling at runtime based on the activity channel. However, in V4 when using the `context.PromptAsync` there is no way to set the prompt styling, the only place the styling is available for Waterfall dialogs is when the Choice Prompt is registered. 

**Describe the solution you'd like**
I would either like the ability to set the prompt styling through the PromptOptions object or a second override for the PromptAsync function to pass the Styling. 

**Describe alternatives you've considered**
We have considered creating the waterfall dialog on each turn so that we can change the styling depending on the channel, however, this is anti-pattern that we don't want to adopt. 

[enhancement]

**Comment by v-kydela** [comment]
Related: https://github.com/Microsoft/BotBuilder/issues/5263

**Comment by james-novino** [comment]
That issue is similar, but that is when initializing the Dialog Set and not when calling Prompt Async, that prompt function doesn’t expose any mechanisms to configure the style.

**Comment by v-kydela** [comment]
One of the suggestions in that DCR is to include a list style in `PromptOptions`, which is used when calling `PromptAsync`

**Comment by gabog** [comment]
Hi @james-novino, this has been added to the C# version of the SDK and will be available in the next release.

Thanks a lot for the feedback.

Gabo
