### ISSUE TITLE
Standardize StyleCop rules across projects

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#1459]
Each project in the BotBuilder today has it's own set of StyleCop rules. 

Standardize on a single ruleset across all projects, and remove the "duplicate" copies of the file. 

This should probably be done via the Directory.Build.Props file.

**Comment by JuanAr** [comment]
Is this duplicated with #1422?

**Comment by cleemullins** [comment]
Yea. This is a dupe
