### ISSUE TITLE
The json made by the CosmosDbStorage provider is bigger than the one made by AzureBlobStorage provider due to the formatting of the json

### ISSUE THREAD

**Issue by atsushina** [Microsoft/botbuilder-dotnet#1471]
When you use the azure storage provider and return the adaptive card, the json is not formatted.
So the size of the converstion data is suppressed (The size is about 6KB).

![image](https://user-images.githubusercontent.com/45960383/54341861-522cc480-467e-11e9-80b3-fdca96b1dc53.png)

![image](https://user-images.githubusercontent.com/45960383/54342653-5eb21c80-4680-11e9-9dd5-df4b847a6daf.png)

But when you use the cosmos db storage provider and return the same adaptive card, the json is formatted.
So the size of the conversation data increase by several times.

![image](https://user-images.githubusercontent.com/45960383/54356659-7fd63580-469f-11e9-8d5c-523a228f487d.png)

Because of this behavior, the user need to increase RU if multiple user talk to bot at the same time.

The json which is inserted to the cosmos db storage is made by JObject.FromObject, but it seems to make the formatted JSON.

[](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L254)

If I change the code like the following, the json in the cosmos db is not formatted and the size of it decrease considerably.

[CosmosDbStorage.cs#L197](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L197)
`var item = JObject.Parse(doc.Document).ToObject(typeof(object), _jsonSerializer);`

[CosmosDbStorage.cs#L247](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L247)
`Document = json.ToString(Formatting.None),`

[CosmosDbStorage.cs#L346](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L346)
`public string Document { get; set; }`

After changing the code
![image](https://user-images.githubusercontent.com/45960383/54356586-53221e00-469f-11e9-91f2-42e9cb3a9082.png)

But do you have any sugesstions to suppress the size of the json inserted by cosmos db storage provider?

Well when I set the JsonSerializerSettings for the JSonSerializer and the RequestOptions of the IDocumentClient, it didn't work.

[Formatting Enumeration](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Formatting.htm)

[RequestOptions Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions?view=azure-dotnet)

**Comment by cleemullins** [comment]
PR #1417 would fix this, I believe.

**Comment by atsushina** [comment]
As far as I tried the fix for PR #1417 by changing the code, but it would not help.

I passed the second parameter (Jsonserializer) to the CosmosDB Constructor with the following setting.

`jsonSerializer.TypeNameHandling = TypeNameHandling.All;`
`jsonSerializer.Formatting = Formatting.None;`
`jsonSerializer.NullValueHandling = NullValueHandling.Ignore;`
`jsonSerializer.ContractResolver = new DefaultContractResolver();`

But the inserted json to the Cosmos DB is the same (formatted).

According to the following document, the JObject.FromObject doesn't reflect the jsonserializer setting.

[JObject ignores JsonSerializerSettings during serializatio](https://github.com/JamesNK/Newtonsoft.Json/issues/1058)

[How to serialize a JObject the same way as an object with Json.NET?](https://stackoverflow.com/questions/40244395/how-to-serialize-a-jobject-the-same-way-as-an-object-with-json-net)

I can confirm that the jsonserializer setting is reflected, but the desirialized json is formatted.

![image](https://user-images.githubusercontent.com/45960383/55607554-754b1f80-57b7-11e9-88f2-d634ed455954.png)

![image](https://user-images.githubusercontent.com/45960383/55607781-fe625680-57b7-11e9-97cf-9098dce95150.png)

**Comment by cleemullins** [comment]
@atsushina I'm not sure what to do about this. It seems we have a few options:
1. Live with it. Comsos has unique JSON handling capabilities and functions, and Azure Blob storage is different. 

2. You could roll your own storage class (or copy ours) and make changes as needed. The "Creation" of the storage class is done via DI in a bot, so injecting your own instead of ours is trivial. 

To get the behavior you want, #2 seems the easiest. 

I'm open to suggestions.

**Comment by sgellock** [comment]
we've done as much investment here as I want to for now.
