### ISSUE TITLE
missing comments (remarks) for methods in ActivityHandler class 

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-dotnet#1482]
## Version
4.3.1

## Describe the bug
Most methods in Microsoft.Bot.Builder.ActivityHandler don't have remarks/ comments. The samples override methods like OnMessageActivityAsync, which is missing remarks. While most method names are self-explanatory, it would be helpful to include some description. 

for example - https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L63

[bug]

**Comment by v-kydela** [comment]
@yochay - I have written documentation comments based on my understanding of the `ActivityHandler` class and submitted a pull request
