### ISSUE TITLE
Choice.Value can't be nulll

### ISSUE THREAD

**Issue by baruchiro** [Microsoft/botbuilder-dotnet#1485]
## Describe the bug
There is no clear division of responsibility between the two `Value` fields:
 - If you only set the `ActionCard.Value`, you will receive a runtime error: `Object reference not set to an instance of an object`.
 - If you set **only** the `Choice.Value`, an ActionCard will be displayed but it will not perform a post.
 - If you set the both fields, you will not know which ones you will receive in the post.

## To Reproduce
Use `Choice` as follow:
```csharp
new Choice()
{
    Action = new CardAction(
        type:ActionTypes.PostBack, 
        title:"Select this item",
        value:1)
}
```

## Expected behavior
Use the `value` from the `CardAction` to be the `Choice.Value` if `Choice.Value` is null.

[bug]

I'm willing to help, just tell me where.

**Comment by baruchiro** [comment]
Maybe add a Compiler Warning in case there is an assignments to both fields.
But I really do not know how to do it and I'd be happy to help.

**Comment by mdrichardson** [comment]
The issue isn't so much that you can't have a null `Choice.Value` so much as when extracting `Choice`s from the `CardAction` and trying to determine the max length of the text to display for the Choice, `ChoiceFactory` was incorrectly looking at `Choice.Value` while it's null instead of looking at `Choice.Action.Title`. See PR for the fix, there.

**Comment by baruchiro** [comment]
I had a lot of wrong assumptions. I guess I did the wrong tests.
I thought `ActionCard` must be used to show cards. In one case, the options were presented as a list and not as cards (I don,t know why, it was probably a mistake in my code).

**Comment by baruchiro** [comment]
Look on [this SO Q&A](https://stackoverflow.com/questions/53841340/bot-framework-rendering-choices-changes-format). Based on [your answer](https://stackoverflow.com/a/55228187/839513), I answered this question, and you can see there are some misunderstandings on the subject.

I think there's no reason for `Choice`, and you can only use `CardAction`, when `ChoicePrompt` will takes the relevant values from it.

**Comment by mdrichardson** [comment]
Your answer is good and this is because [this line in ChoiceFactory](https://github.com/Microsoft/botbuilder-dotnet/pull/1503/files#diff-ac3fa7081e374ba67587b5c6fc962791L23) gets the length of the text from `Title`, if present (before my PR, it incorrectly gets it from Choice.Value, which is why the answer you posted works--it's looking in the wrong place).

`Choice.Value` still has a purpose because for simple Choice Prompts, writing:

```
new Choice()
{
    Value = "xyz"
}
```

is easier than writing:

```
new Choice()
{
    Action = new CardAction()
    {
        Value = "xyz"
    }
}
```

**Comment by baruchiro** [comment]
But:

```csharp
new Choice()
{
    Value = "xyz"
    Action = new CardAction()
    {
        Value = "xyz",
        Title = "Select xyz"
    }
}
```

Is more complicated then:

```csharp
new CardAction()
{
    Value = "xyz",
    Title = "Select xyz"
}
```

And we don't lose anything.

**Comment by baruchiro** [comment]
And it retains the option of setting the `Value` only.

**Comment by mdrichardson** [comment]
[PromptOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.promptoptions?view=botbuilder-dotnet-stable) doesn't accept a `CardAction` for the `Choice` property. It only accepts a `Choice`, so you still have to do both `new Choice()` and `new CardAction()`. I suppose we could allow `PromptOptions` to accept `CardAction`s, but then we're mixing up names and it could get very confusing very quickly. And then if a user accidentally uses an action like "postBack" or "call" or something, we'd have to make sure that it still completes the `ChoicePrompt`, too.

**Comment by baruchiro** [comment]
Yes, it is clear that my proposal breaks what exists.

Btw, what is `PromptOptions`? It is a dialog?

**Comment by mdrichardson** [comment]
[`PromptOptions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.promptoptions?view=botbuilder-dotnet-stable) is a set of options that you pass to [a `Prompt`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.prompt-1?view=botbuilder-dotnet-stable).

For a `ChoicePrompt`, it's the object that contains the Choices.

![image](https://user-images.githubusercontent.com/40401643/54634130-c11f6a00-4a3e-11e9-81e0-5093ea251672.png)

**Comment by baruchiro** [comment]
I was too deep and missed the base.
