### ISSUE TITLE
v4.3.1 NuGet package appears to be missing a dependency 

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#1496]
## Version
4.3.1

## Describe the bug
There appears to be a missing dependency in the 4.3.1 NuGet package that is blocking the publishing team from generating the updated C# ref topics.

## To Reproduce
See **Additional context**

## Expected behavior
See **Additional context**

## Additional context
The OPS build team sent me this information (re: work item [71587](https://ceapex.visualstudio.com/Onboarding/_workitems/edit/71587?src=WorkItemMention&src-action=artifact_link)):

> It looks like one of the recently updated NuGet packages for BotBuilder is missing a reference to a dependent dll. We are getting the following error:
##[error]mdoc: Mono.Documentation.MDocAssemblyException: Error processing Microsoft.Bot.Builder.Integration.AspNet.WebApi, Version=4.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 from D:\a\1\s\dotnet\_all\botbuilder-dotnet-stable\Microsoft.Bot.Builder.Integration.AspNet.WebApi.dll ---> Mono.Documentation.MDocException: Failed to resolve type 'System.Web.Http.HttpConfiguration' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Web.Http, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
>
> The package is: Microsoft.Bot.Builder.Integration.AspNet.Core

[bug]

**Comment by gabog** [comment]
Resolved in offline conversation with Alma, Mike and @JonathanFingold
