### ISSUE TITLE
Add InputHint as an optional parameter to BotContext.Reply method

### ISSUE THREAD

**Issue by garypretty** [Microsoft/botbuilder-dotnet#152]
On the BotContext object there is an overload for the Reply method in order to allow the developer to supply SSML as well as text. i.e.

**BotContext Reply(string text, string speak = null)**

Can we also add an optional parameter to this method for InputHint, as if the developer is providing SSML then there is a good chance they might want to indicate if they are waiting for more input or wish to end the conversation when using channels like Cortana etc. i.e.

**BotContext Reply(string text, string speak = null, InputHint inputHint = null)**

This will help avoid having the create the activity explicitly just to provide an inputHint along with SSML.

Happy to implement this and submit a PR if this is something we think we should do.

**Comment by Stevenic** [comment]
@garypretty, it's likely that the `BotContext.Reply()` and other queue based methods will be going away in favor of a `BotContext.SendActivities()` that more accurately takes an array of activities as input which it delivers immediately. Higher level abstractions like queuing responses and a simpler `Reply()` methods would need to be layered on using middleware.  

That layering opens up the possibility to create simpler methods targeted at building speech enabled bots. For instance I could see creating a piece of middleware targeted at Cortana skills that streamlines the management of `inputHint` and adds `Speak()` methods which optimizes formatting responses for Cortana.

**Comment by Stevenic** [comment]
To go along with this I do think it probably makes since to add `inputHint` as an optional argument to `MessageStyler.text()`. I just ran into a need for the same thing on the JavaScript side of things.

**Comment by garypretty** [comment]
All sounds sensible. I'll raise A PR for the change to. MessageStyler instead then. Thanks for the follow up.

**Comment by Stevenic** [comment]
Thanks @garypretty I updated all of the methods on `MessageStyler` class to take an optional `inputHint`.

**Comment by garypretty** [comment]
Closing as PR has now been merged.
