### ISSUE TITLE
[declarative-hack] [JSON] Multi-line text does not work in JSON Bot

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-dotnet#1542]
## Version
Hackathon JSON Test Bot

## Describe the bug
Multi-line text activities don't work with a JSON bot. For example, I cannot have the bot output this in a single activity:

> This is a multi-line list
> - one
> - two
> - three 

## To Reproduce

Run the [LG Bot Sample](https://github.com/Microsoft/botbuilder-dotnet/blob/ComposableDialog/samples/Microsoft.Bot.Builder.TestBot.Json/TestBotLG.cs) by (in `Startup.cs`) commenting out `return new TestBot(accessors, botResourceManager);` and un-commenting `return new TestBotLG(accessors);`. Type "multi" and you will get:

![image](https://user-images.githubusercontent.com/40401643/54851193-60926600-4ca6-11e9-9eca-8e7d5226c253.png)

[It gets this from here](https://github.com/Microsoft/botbuilder-dotnet/blob/ComposableDialog/samples/Microsoft.Bot.Builder.TestBot.Json/LG/8.LG#L51)

Now, switch back to the non-LG JSON bot by reversing the commenting/uncommenting above. Copy the mutli-line markdown from the link above into a new .lg file. Create a dialog that calls that .lg file and you will get:

![image](https://user-images.githubusercontent.com/40401643/54851377-f3330500-4ca6-11e9-9b49-d405f03585ec.png)

All spacing is exactly the same. It seems to be the way the JSON bot parses multi-line text from .lg files.

[bug]
[declarative-hack]

**Comment by vishwacsena** [comment]
@carlosscastro - possibly related to the dialog call to LG not picking up multi-line response from EvaluateTemplate?

**Comment by vishwacsena** [comment]
Verified this has been fixed in the latest bits on 4.Future. 

```json
{
    "$schema": "../../app.schema",
    "$type": "Microsoft.AdaptiveDialog",
    "generator": "test.lg",
    "steps": [
        {
            "$type": "Microsoft.SendActivity",
            "activity": "[T1]"
        },
        {
            "$type": "Microsoft.SendActivity",
            "activity": "Step 2"
        },
        {
            "$type": "Microsoft.SendActivity",
            "activity": "Step 3"
        }
    ]
}
```

Where test.lg has the following

```markdown
# T1
- ``` 
this is multi line text
- one
- two
- three
```
```
