### ISSUE TITLE
idea: consolidate 3 middleware pipes into 1

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#155]
Cross linking the idea I posted on the JavaScript side for discussion of the potential .NET implementation of this change:

https://github.com/Microsoft/botbuilder-js/issues/74

I think the idea is basically the same but instead of a single JavaScript closure, in .NET you'd provide a class that implements an `IMiddleware` interface with a single `ContextCreated()` method.

To go along with this suggestion I have a proposal for an updated `TurnContext` interface:

https://github.com/Microsoft/botbuilder-js/issues/66#issuecomment-366403012

**Comment by cleemullins** [comment]
As I've already said in the other thread, I like the idea of a single Middlware pipeline much more than our current 3 (5!) pipelines. This follows the model used by [ASP.Net Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?tabs=aspnetcore2x), Restify, Redux, and others. 

The min ASP.Net core middlware is very straightforward:
```csharp
    public void Configure(IApplicationBuilder app)
    {
        app.Run(async context =>
        {
            await context.Response.WriteAsync("Hello, World!");
        });
    }
```
We should be able get quite close to this, model-wise. 

I also quite like their .Use / .Run semantics, where .Run terminates the pipeline, and .Use extends. 
```csharp
    public void Configure(IApplicationBuilder app)
    {
        app.Use(async (context, next) =>
        {
            // Do work that doesn't write to the Response.
            await next.Invoke();
            // Do logging or other work that doesn't write to the Response.
        });

        app.Run(async context =>
        {
            await context.Response.WriteAsync("Hello from 2nd delegate.");
        });
    }
```

The predicate based Middlware we've talked about is done in ASP.Net using Map(), which branches the pipeline. 

We can lift almost their exact model, replacing HttpContext with BotContext. :)

**Comment by drub0y** [comment]
Yeah, I strongly agree this change should happen.

I also believe it would be beneficial to support a model of [factory based middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility). The biggest target benefit once again being dependency injection of transient dependencies. Additionally I think adding support for conventions based middleware should be a stretch goal.

**Comment by cleemullins** [comment]
Done.
