### ISSUE TITLE
KeyVault assembly warnings when building VA

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-dotnet#1553]
## Version
V4 / Virtual Assistant

## Describe the bug
Clean build produces KeyVault warnings due to mismatch keyvault assembly. These show up due to skills build. We suspect this is a core SDK issue though.

## To Reproduce
Enlist and build VA out of the box.

## Expected behavior
Clean build. If one needs to do any prior steps (e.g. dotnet restore, btw this didn't help in this case), it must be documented

## Additional context
Example warnings:

verity
Code
Description
Project
File
Line
Suppression State
Warning
SA1208
Using directive for 'System' should appear before directive for 'CalendarSkill.Dialogs.Shared.Resources.Strings'
CalendarSkill
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs
2
Active
Warning
SA1208
Using directive for 'System.Collections.Generic' should appear before directive for 'CalendarSkill.Dialogs.Shared.Resources.Strings'
CalendarSkill
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs
3
Active
Warning
SA1208
Using directive for 'System.IO' should appear before directive for 'CalendarSkill.Dialogs.Shared.Resources.Strings'
CalendarSkill
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs
4
Active
Warning
SA1208
Using directive for 'System.Text' should appear before directive for 'CalendarSkill.Dialogs.Shared.Resources.Strings'
CalendarSkill
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs
5
Active
Warning
SA1208
Using directive for 'System.Text.RegularExpressions' should appear before directive for 'CalendarSkill.Dialogs.Shared.Resources.Strings'
CalendarSkill
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\Models\Resources\AskParameterTemplate.cs
6
Active
Warning
SA1202
'public' members should come before 'private' members
VirtualAssistant.Tests
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\tests\virtualassistant.tests\AssistantTests.cs
174
Active
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
Microsoft.Bot.Solutions
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
Microsoft.Bot.Solutions
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
Microsoft.Bot.Solutions
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
EmailSkill (Skills\EmailSkill\EmailSkill)
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\emailskill\emailskill\EmailSkill.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
Microsoft.Bot.Solutions.Tests
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\tests\microsoft.bot.solutions.tests\Microsoft.Bot.Solutions.Tests.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
PointOfInterestSkill (Skills\PointOfInterestSkill\PointOfInterestSkill)
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\pointofinterestskill\pointofinterestskill\PointOfInterestSkill.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
AutomotiveSkill (Skills\AutomotiveSkill\AutomotiveSkill)
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskill\AutomotiveSkill.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
ToDoSkill (Skills\ToDoSkill\ToDoSkill)
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\todoskill\todoskill\ToDoSkill.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
CalendarSkill (Skills\CalendarSkill\CalendarSkill)
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskill\CalendarSkill.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
EmailSkillTest
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\emailskill\emailskilltest\EmailSkillTest.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
AutomotiveSkillTest
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\automotiveskill\automotiveskilltest\AutomotiveSkillTest.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
ToDoSkillTest
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\todoskill\todoskilltest\ToDoSkillTest.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
CalendarSkillTest
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\skills\calendarskill\calendarskilltest\CalendarSkillTest.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
VirtualAssistant
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\assistant\VirtualAssistant.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
VirtualAssistant.Tests
C:\workspace\botroot\solutions\solutions\Virtual-Assistant\src\csharp\tests\virtualassistant.tests\VirtualAssistant.Tests.csproj
1
 
Warning
NU1701
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.
PointOfInterestSkillTests

[bug]
Related bug: 
https://github.com/Microsoft/AI/issues/1000

**Comment by EricDahlvang** [comment]
Hi @scheyal 

This issue is being tracked here: https://github.com/Microsoft/botbuilder-dotnet/issues/1419

The current recommendation is to suppress 1701 and 1702.
