### ISSUE TITLE
LUISResult custom event logging the details related to Intents that come back from LUIS

### ISSUE THREAD

**Issue by smallangi** [Microsoft/botbuilder-dotnet#1565]
For a given utterance, LUIS retuns multiple intents along with their predictions scores. Top intent might not always be the "right" intent for a given utterance. It makes sense to store the intents and along with the prediction scores so that analyst can evaluate the LUIS model and identify the gaps. 

Log the Intents Json as it is, which can be parsed later on in the Telemetry Data Pipeline.

"intents": [
    {
      "intent": "intent1",
      "score": 0.9888772
    },
    {
      "intent": "intent2",
      "score": 0.874704821
    }
  ],

**Comment by benbrown** [comment]
@daveta - do you know if is this happening in the telemetry client or at LUIS?

**Comment by daveta** [comment]
@smallangi: Yes, we adopted your suggestion, we're pulling the top two now..  If you need it sooner, you can copy the files over your existing code and it should work.  Ping me know if you have any issues..

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L220
