### ISSUE TITLE
[declarative-hack] Microsoft.SaveEntity fails to save LUIS built-in entities

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-dotnet#1577]
## Version
4.5-Preview

## Describe the bug
I can use _Microsoft.SaveEntity_ to save a a custom entity defined in a LUIS app. However, LUIS built in entities (eg number) didn't seem to transfer into memory.

[bug]

**Comment by vishwacsena** [comment]
Tried and unable to repro this.
