### ISSUE TITLE
Prompt Retry Limit

### ISSUE THREAD

**Issue by james-novino** [Microsoft/botbuilder-dotnet#1581]
**Is your feature request related to a problem? Please describe.**
Currently, prompts make the assumption that the user will ultimately enter data that passes the validations. But's that's not always the desired behavior, in a number of occasions we may want to retry the prompt a set number of times and then complete the dialog rather than continually retrying the prompt. 
```
// First step of the main dialog: prompt for party size.
private async Task<DialogTurnResult> PromptForEmailAsync(
    WaterfallStepContext stepContext,
    CancellationToken cancellationToken = default(CancellationToken))
{
    // Prompt for the party size. The result of the prompt is returned to the next step of the waterfall.
    return await stepContext.PromptAsync(
        EmailPrompt,
        new PromptOptions
        {
            Prompt = MessageFactory.Text("Can you please enter your email?"),
            RetryPrompt = MessageFactory.Text("That doesn't appear to be a valid email. Can you please enter your email?"),
            Validations = ... ,
        },
        cancellationToken);
}
```

**Describe the solution you'd like**
Ideally, the ability to specify a retry limit in the prompt options and a message to send the user before ending the flow. 

**Describe alternatives you've considered**
We have considered forking the prompt ourselves and implementing similar functionality to that described above as well as creating custom prompts that use callbacks and bot state to achieve the same. 

[enhancement]

**Comment by Zerryth** [comment]
Closing, as there's already an issue open revolving around letting user know how many retry attempts have occurred, which when implemented could be used to help you write logic for a retry limit.

Track the issue here: https://github.com/Microsoft/BotBuilder-Samples/issues/1257.
Feature is currently slated for 4.4 release
