### ISSUE TITLE
[Adaptive] [DCR] We need to populate the "default" property in our schema files

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#1598]
JSON Schema has a `default` property that we can use to specify the initial value for certain properties. For instance, the `WelcomeRule.WelcomeProperty` has a default value of "conversation.welcomed" and we'd ideally want the developer to see this value in the property sheet when they add a new WelcomeRule.

[bug]

**Comment by carlosscastro** [comment]
https://github.com/microsoft/botbuilder-dotnet/pull/2003
