### ISSUE TITLE
[Adaptive] [DCR] C# missing DialogManager class

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#1603]
The C# code still has `RunAsync()` and `OnTurnAsync()` methods on the [AdaptiveDialog](https://github.com/Microsoft/botbuilder-dotnet/blob/ComposableDialog/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs). This functionality should be moved to a `DialogManager` class in the `Microsoft.Bot.Builder.Dialogs` namespace.  

[dcr]

**Comment by vishwacsena** [comment]
Not needed. Works with MVC

**Comment by vishwacsena** [comment]
We might need to reconsider this post build for all the additional functionality including session expiry policy etc.
