### ISSUE TITLE
[Adaptive] [DCR] Align EndDialog step

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#1612]
The JS version of `EndDialog` lets you pass in the resultProperty to return as part of the steps constructor.  The C# version is using `Dialog.property` to find the return value and is missing a constructor.

https://github.com/Microsoft/botbuilder-dotnet/blob/ComposableDialog/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/EndDialog.cs

We should add a `resultProperty` and then add a constructor for letting devs set it.

[dcr]

**Comment by Stevenic** [comment]
See related issue #1613

**Comment by sgellock** [comment]
address in the next "naming party (tm)"
