### ISSUE TITLE
[Adpative] [DCR] We should remove Dialog.property member from C# version of Dialog. 

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#1613]
The C# version of `Dialog` has a `property` member which the JS version is lacking. I chose not to add a `property` member to Dialog because a) it's not always relevant and b) we already have `inputProperties` and `outputProperty` members on Dialog. On top of that the current implementation isn't even correct because it only sets outputProperty.  To create a two-way binding you need to add both an inputProperties["value"] and an outputProperty.

My proposal would be to remove `property` from the Dialog level and only implement it on steps that actually support it. 

[dcr]

**Comment by tomlm** [comment]
fixed with #2092
