### ISSUE TITLE
MultipleResolutionsDateTimePrompt test breaks after upgrading to Recognizers-Text latest version 1.1.6

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/botbuilder-dotnet#1622]
## Version
4.3.2

## Describe the bug
In BotBuilder.Dialogs project we are using the version 1.1.3 of _Recognizers-Text_. We need to upgrade **Recognizers.Text.DateTime** NuGet package to the latest version 1.1.6 so _ChoicePrompts_ be able to recognize Relative Ordinals like "last one" or "next one". 
After the upgrade, the **MultipleResolutionsDateTimePrompt** test fails due to the resolution for "Wednesday 4 oclock" changed from "XXXX-WXX-3T04 XXXX-WXX-3T16" to "XXXX-WXX-3".

## To Reproduce
1. Open BotBuilder-DotNet solution.
2. Right-click on the Dependencies of **Microsoft.Bot.Builder.Dialogs** project.
3. Go to Manage NuGet packages and update **Microsoft.Recognizers.Text.DateTime** to v.1.1.6.
![image](https://user-images.githubusercontent.com/44245136/55559045-beba4280-56c3-11e9-8d76-36d13ecbedb0.png)
4. Build the solution and run all tests.
5. See the failing test.
![image](https://user-images.githubusercontent.com/44245136/55563158-c1b93100-56cb-11e9-8086-bfc89db4260e.png)
## Expected behavior
All test should run successfully.

## Screenshots
The expected value for Timex is "XXXX-WXX-3T04 XXXX-WXX-3T16".
In _ContinueDialogAsync_ of Prompt.cs:
![image](https://user-images.githubusercontent.com/44245136/55562233-e8766800-56c9-11e9-9263-133dd0dc4ddf.png)

## Additional context
This issue derives from the issue #1477.

[bug]

**Comment by johnataylor** [comment]
I've confirm this is a regression. We can't upgrade packages to 1.1.6 (or even to 1.1.6)

Opened issue in Recognizers-Text

https://github.com/Microsoft/Recognizers-Text/issues/1524

Moving this issue to 4.5. (unless we get a fix abnd we can jump to 1.1.7)

**Comment by johnataylor** [comment]
Closing this as we have another tracking issue for updating recognizer packages
