### ISSUE TITLE
Waterfall steps validator not sending SuggestedActions

### ISSUE THREAD

**Issue by paulio** [Microsoft/botbuilder-dotnet#1629]
## Version
SDK 4.3.2

## Describe the bug
Declare a text prompt with a validator function. Issue a prompt including a retryprompt activity. In the retry activity includes a few suggestedactions. When the validator fails the suggested actions are not sent (according to the emulator inspector) and are not seen (in the emulator). 

## To Reproduce
Set the prompt and retryprompt options to use identical copies of an activity that uses SuggestedActions. The original prompt will issue and honour the SuggestedActions, the retry fails to do so.

## Expected behavior
See SuggestedActions when a validator has failed. 

[bug]

**Comment by paulio** [comment]
Ok, it's not nearly as bad as I thought. The problem occurs IIF the validator itself chooses to send an activity. At that point the RetryPrompt is bulldozed out of the picture.

**Comment by mdrichardson** [comment]
I'll start looking into this. In the meantime, do you have code you can share? That would help me reproduce this.

**Comment by mdrichardson** [comment]
That's more or less intended behavior as it allows other activities to interrupt the prompt, mid-retry.

The retry prompt lives in `promptContext.Options.RetryPrompt`, so you can get around this with something like this:

```csharp
public async Task<bool> ValidatePromptAsync(PromptValidatorContext<string> promptContext, CancellationToken cancellationToken)
{
    var result = promptContext.Recognized.Value;

    await promptContext.Context.SendActivitiesAsync(
            new Activity[]
            {
                MessageFactory.Text("Message To Send First"),
                promptContext.Options.RetryPrompt
            }
        );

    if (result == "passValidation")
    {
        return true;
    }
    else
    {
        return false;
    }
}
```

You can see a similar example in the Docs, [Implement Validation Code](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-prompts?view=azure-bot-service-4.0&tabs=csharp#implement-validation-code)

**Comment by paulio** [comment]
Thanks for the workaround :)
