### ISSUE TITLE
Issue on Mac when Adding Azure Search to Bot Builder project

### ISSUE THREAD

**Issue by ChrisRisner** [Microsoft/botbuilder-dotnet#1634]
## Version
4.3

## Describe the bug
After adding the Azure Search SDK to a Bot Builder .NET project, an error is thrown when running the project on a mac (using the dotnet tool).  The error thrown is "The type initializer for 'Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase' threw an exception. ---> System.FormatException: The format of value 'Darwin18.0.0DarwinKernelVersion18.0.0WedAug22201340PDT2018rootxnu-4903.201.21/RELEASE_X86_64' is invalid.".  The solution to this issue is to add the "Microsoft.Rest.ClientRuntime" package to the same project.  You can find details on this error popping up elsewhere here: https://github.com/Azure/azure-sdk-for-net/issues/5046.

## To Reproduce
1.  Create a .NET Core bot builder project on a mac.
2.  Ensure the bot runs and responds locally.
3.  Add the Azure Search SDK to your project.
4.  Rerun the project and try to talk with your bot.
5.  The error should be thrown.

## Expected behavior
Installing the Azure Search SDK into your Bot project should install any necessary packages to not cause the bot to crash.

## Additional context
Reproduced on multiple developers Macs.

[bug]

**Comment by sgellock** [comment]
We believe we've fixed this in 4.3.2.  Support Team, will you work with the customer to see which version they are running.

**Comment by EricDahlvang** [comment]
@ChrisRisner Have you tried the 4.3.2 bits?

**Comment by ChrisRisner** [comment]
Not yet.  Will try asap and report back

**Comment by CoHealer** [comment]
@ChrisRisner, have you had a chance to try the update?

**Comment by ChrisRisner** [comment]
Apologies.  Just had a chance to try.  Updating to 4.3.2 before installing Azure Search does address the issue.  Thanks!
