### ISSUE TITLE
docs mention Microsoft.Bot.Builder.CardFactory - should it be Microsoft.Bot.Schema.CardAction?

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#166]
[Wiki](https://github.com/Microsoft/botbuilder-dotnet/wiki/Sending-Cards-and-Attachments) says "The v4 SDK includes new static Microsoft.Bot.Builder.MessageFactory and Microsoft.Bot.Builder.CardFactory" 

Microsoft.Bot.Builder.CardFactory should be Microsoft.Bot.Schema.CardAction? Can't seem to find CardFactory anywhere in the SDK.

Thanks,
Anna

**Comment by JonathanFingold** [comment]
I will update the topic.

**Comment by cleemullins** [comment]
It's so bizzare. I wrote the code. I tested the code. I checked the code in. 

... now I can't find it. 

There's a mystery afoot!

**Comment by JonathanFingold** [comment]
@cleemullins you have a bit to find the code, as I need to refactor my samples to catch up with other recent changes.

**Comment by JonathanFingold** [comment]
I've removed the reference to `CardFactory` for now and have updated the samples to use `MessageFactory`.
