### ISSUE TITLE
[Adaptive] need a way to stop the LogStep globally

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-dotnet#1660]
**Is your feature request related to a problem? Please describe.**
When using [LogStep](https://github.com/Microsoft/botbuilder-dotnet/blob/ComposableDialog/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/LogStep.cs) in a given project, I write 'LogStep' across multiple files... I need a way to stop the LogStep from logging at the global bot level. Currently, i have to comment out each line of code. 

I would like to follow .NET and define [TraceLevel](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracelevel?view=netframework-4.7.2) Trave Level model globally.   

[enhancement]

**Comment by vishwacsena** [comment]
Given the current direction and the push to using inspection middleware for broad debugging support, there are no plans to add support for this. #2323
