### ISSUE TITLE
[declarative-hack] Remove references to .bot files

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-dotnet#1664]
## Version
4.next

## Describe the bug
Remove references to .bot files as they are history.

## To Reproduce
1. scan the code for .bot pattern and replace instructions/comments accordingly

## Expected behavior
.bot references are gone with the feature.

## Additional context
Sample search:

[BF]c:\workspace\botroot\BBJS4.next\samples>findstr /sip /C:".bot file" *
01. sendActivity\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
01. sendActivity\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
FINDSTR: Cannot open 01. sendActivity\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
01. sendActivity\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
01. sendActivity\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
02. textInput\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
02. textInput\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
FINDSTR: Cannot open 02. textInput\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
02. textInput\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
02. textInput\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
03. ifCondition\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
03. ifCondition\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
FINDSTR: Cannot open 03. ifCondition\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
03. ifCondition\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
03. ifCondition\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
04. intentRule\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
04. intentRule\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
FINDSTR: Cannot open 04. intentRule\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
04. intentRule\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
04. intentRule\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
05. beginDialog\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
05. beginDialog\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
FINDSTR: Cannot open 05. beginDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
05. beginDialog\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
05. beginDialog\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
06. codeStep\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
06. codeStep\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
06. codeStep\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
06. codeStep\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
FINDSTR: Cannot open 10. sidecarDebugging\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_CreateConversation_should_return_a_valid_conversation_ID.nock.js
FINDSTR: Cannot open 10. sidecarDebugging\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetActivityMembers_should_fail_with_invalid_conversatoinId.nock.js
FINDSTR: Cannot open 10. sidecarDebugging\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
FINDSTR: Cannot open 10. sidecarDebugging\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_ReplyToActivity_should_fail_with_invalid_conversationId.nock.js
FINDSTR: Cannot open 10. sidecarDebugging\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_SendToConversation_should_fail_with_invalid_conversationId.nock.js
30. stateMachineDialog\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
30. stateMachineDialog\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_CreateConversation_should_return_a_valid_conversation_ID.nock.js
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_DeleteActivity_should_fail_with_invalid_conversationId.nock.js
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetActivityMembers_should_fail_with_invalid_conversatoinId.nock.js
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_GetConversationMembers_should_fail_with_invalid_conversationId.nock.js
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_ReplyToActivity_should_fail_with_invalid_conversationId.nock.js
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_SendToConversation_should_fail_with_invalid_conversationId.nock.js
FINDSTR: Cannot open 30. stateMachineDialog\node_modules\botbuilder-dialogs-adaptive\node_modules\botframework-connector\tests\recordings\Bot_Framework_Connector_SDK_Conversations_UpdateActivity_should_fail_with_invalid_conversationId.nock.js
30. stateMachineDialog\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
30. stateMachineDialog\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
50. todo-bot\lib\index.js:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
50. todo-bot\lib\index.js:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.
50. todo-bot\src\index.ts:    console.log(`\nTo talk to your bot, open echobot.bot file in the Emulator.`);
50. todo-bot\src\index.ts:// See https://aka.ms/about-bot-adapter to learn more about .bot file its use and bot configuration.

[bug]

**Comment by vishwacsena** [comment]
Samples in botbuidler-samples do not have any reference to .bot files.
