### ISSUE TITLE
Remove IBotContext in favor of BotContext

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#168]
The IBotContext interface doesn't seem to be adding any value. Currently it's passed into Middleware and other components, but it's not adding any value over the basic BotContext implementation. 

I don't see a scenario where it's needed. For Unit Testing, it's simple enough to Mock(BotContext), and I don't see any other classes being likely to implement the interface. 

Is there value here that I'm missing? I would love to remove it.

**Comment by RyanDawkins** [comment]
Is there a plan to make BotContext.Reply push through the pipe immediately? If not I don't think BotContext will lose it's testability. We can still check BotContext.Responses, and set the Conversation and User state members.

**Comment by cleemullins** [comment]
Yes. 

We're waiting on a bunch of changes along those lines due to an upcoming Hack. The CSE team needs something stable enough to do snippits / samples / docs against, so we decided to hold that change for this week. Once that hack is done, we have a 2-week window until the next one. 

During that window, the change to make .Reply push through (and some other similar changes) should be done. 

Steve is currently prototyping this in the JS repo, along with the switch to a Single Middleware pipeline. So far, things seem quite a bit cleaner with far less code running at unexpected times.

**Comment by RyanDawkins** [comment]
@cleemullins

Sweet. I'll look for issues with the help wanted tag.

**Comment by Stevenic** [comment]
If anyone would like to peruse the single middleware changes I've started working on for M2 they're here:

https://github.com/Microsoft/botbuilder-js/tree/m2/libraries/botbuilder-core

This is the stripped down core containing the new style `BotAdapter`, trimmed down `TurnContext`, and single middleware pipeline. There are unit tests you could look at to see how things get called and all the tests are passing. 

I'm working on the layer directly above this right now so re-shaping the ConversationState and such.

**Comment by Stevenic** [comment]
Would also like feedback on whether `TurnContext` seems like a better name then `BotContext`. This change was based off a suggestion @billba made and I think it better describes that this object lives for a single turn of conversation. I'm not tied to it though...

**Comment by garypretty** [comment]
@Stevenic I am torn on the naming of TurnContext. Whilst I totally get the premise behind the change to better describe that the context is for a single turn, I think that can be handled fairly well using documentation and initial explainers of the SDK.  BotContext feels a more natural, even if it is not the best technical description, and introducing 'Turn' into the mix feels like another term to go along with many more that we already have in the mix, that may end up making things feel more complicated (even if that is not the case). Does that make sense?

Like you I am not hugely on either side of the fence here, but my preference would be keeping it as BotContext.

**Comment by RyanDawkins** [comment]
I agree with @garypretty. I like the simplicity of IBotContext.

**Comment by billba** [comment]
I actually do not advocate (or like) the term `TurnContext`. My [middleware/context](https://github.com/Microsoft/botbuilder-js/issues/56) proposal over in the botbuilder-js repo I propose:
* renaming `Bot.onReceive` -> `Bot.onRequest`
* separating the type of the primitive, unopinionated argument to this function (I like `Turn`) from the type of the object that a bot developer can optionally create themselves to pass around their bot code, which they could name anything they want (but by convention would commonly be named `Context`).

**Comment by Stevenic** [comment]
As I said I'm not wedded to the term `TurnContext`. @billba I think we're actually renaming `Bot.onReceive()` to `Bot.porcessRequest()` and you'll call it explicitly yourself on each turn of the conversation.

**Comment by billba** [comment]
I don't understand what this means: 

> you'll call it explicitly yourself on each turn of the conversation
