### ISSUE TITLE
[declarative-hack] Text Input reprompt without validating memory

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-dotnet#1682]
## Version
4.next

## Describe the bug
TextInput that with memory property *new TextInput('dialog.product', 'What is the version of your windows?')* always reprompt (after interruption) without checking the value of the memory proprty - which in this case was filled when by the interruption. 

## To Reproduce
Code is here  https://github.com/Microsoft/botbuilder-js/blob/YK-4.next/samples/SimpleSlot/

Currently, JS (and maybe C#) has a bug that a TextInput, reprompts without checking variable (Vish DCR proposal). The following transcript (also attached) shows that clearly.  Where the bot prompts the user ([code here](https://github.com/Microsoft/botbuilder-js/blob/YK-4.next/samples/SimpleSlot/src/resetPassword/resetPassword.ts#L33)) for Windows version (fill single slot) and user reply with expected value, goes through LUIS to extract entities and place value in variable (https://github.com/Microsoft/botbuilder-js/blob/YK-4.next/samples/SimpleSlot/src/resetPassword/resetPassword.ts#L47).  While I set the memory value in the rule the text input still reprompts - ignoring the text vale. 

## Expected behavior
Expected behavior is to check property value prior to reprompting. 

## Screenshots
![image](https://user-images.githubusercontent.com/896149/56099373-cb5b4980-5ec0-11e9-9af3-4cfc4c3bbce9.png)

[bug]

**Comment by vishwacsena** [comment]
@tomlm this is related to @Stevenic re-do work. Instead of calling reprompt, we need to call continue on the input dialog. @Stevenic - do you think we will have a fix for this for //build?

**Comment by vishwacsena** [comment]
This is fixed in the latest packages.
