### ISSUE TITLE
Current v4.x framework referencing older Azure Storage libraries, causing conflicts with more updated libraries.

### ISSUE THREAD

**Issue by edboykin-insight** [microsoft/botbuilder-dotnet#1686]
## Version
Using bot builder 4.3.2, 

## Describe the bug
After updating Azure storage libraries to the most recent packages (Microsoft.Azure.Storage.Common, Microsoft.Azure.Storage.Blob, Microsoft.Azure.Cosmos.Table)
I get a compiler error on AzureBlobTranscriptStore .
`Reference to type 'CloudStorageAccount' claims it is defined in 'Microsoft.Azure.Storage.Common', but it could not be found`

It turns out Microsoft.Bot.Builder.Azure still references the older storage libraries.

Will this be updated to use the latest libraries?

**Comment by edboykin-insight** [comment]
I did a little more research. The latest code for Microsoft.Bot.Builder.Azure has the correct package references for the newer storage Nuget packages (Microsoft.Azure.Storage.Blob).  However, the problem is that AzureBlobTranscriptStore.cs & AzureblobStorage.cs are still using Microsoft.WindowsAzure.Storage and Microsoft.WindowsAzure.Storage.Blob.

**Comment by cleemullins** [comment]
Turns out we can't take these changes without breaking both code and binary compatibility. 

We'll have to stuck with what we've got for now.

**Comment by edboykin-insight** [comment]
Bummer but I get it.

**Comment by paulio** [comment]
This should not be closed. The gap between the versions of Storage is now getting far too large.

**Comment by mark-szabo** [comment]
@cleemullins How should we fix this build error till this `Microsoft.WindowsAzure.Storage` gets replaced by `Microsoft.Azure.Storage.Common`?

**Comment by Cage-e** [comment]
How should we solve this? Could you please provide a solution now that we have to stick with this problem?

**Comment by AndreyMitsyk** [comment]
The fastest workaround is to create copy of [AzureBlobTranscriptStore.cs ](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs) in your project and replace _Microsoft.WindowsAzure.Storage*_ references with a _Microsoft.Azure.Storage*_ references. After this just use your own _AzureBlobTranscriptStore.cs_.

**Comment by cleemullins** [comment]
I can provide an update on this.

In R10, @EricDahlvang is making a change to introduce new storage classes bases on the latest "Azure.*" packages, rather than the old storage drivers. That'll let us keep the old stuff, and also allow folks to consumer the newer packages if that's what they prefer. 

@EricDahlvang Can you chime in here with an update?

**Comment by EricDahlvang** [comment]
@cleemullins this was pushed out of R10, but we can pick it up again if this is a priority.

**Comment by jvanderbiest** [comment]
@EricDahlvang can you confirm these changes are in [v4.10.3](https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.10) as stated in the release notes as I'm unable to find them in my .NET Core app. 

For insance, where is BlobTranscriptStore?
![image](https://user-images.githubusercontent.com/3985995/93086869-10784200-f698-11ea-9aa3-1b57c94ac42e.png)

**Comment by EricDahlvang** [comment]
Hi @jvanderbiest 

The new classes are in new libraries:
![image](https://user-images.githubusercontent.com/11055362/93138778-62b76400-f694-11ea-8abe-af3fac23091c.png)
