### ISSUE TITLE
[Adaptive] Support regex match in common expression.

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#1692]
Here is a sample scenario:
If the bot asks the user the email recipient, the user can either type a name, or a email address.
We should support regex match in IfCondition step.

**Comment by vishwacsena** [comment]
@boydc2014 I believe we discussed adding this to prebuilt functions and we said post //build right? I'm marking this 'next iteration' but please feel free to resolve this once the prebuilt function for regex match is in and added to docs.

**Comment by vishwacsena** [comment]
Related to #1805

**Comment by carlosscastro** [comment]
@Danieladu @luhan2017 can we consider this fixed with the changes you already merged? If yes please close or let me know and I'll close this bug.

**Comment by boydc2014** [comment]
@carlosscastro fixed.
