### ISSUE TITLE
[Adaptive] Support Foreach Step

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#1694]
Foreach is needed in Email and Calendar scenario.
For examples, if bot ask the user email recipients, user can say, A, B, and C.
we need to resolve them one by one.

**Comment by Stevenic** [comment]
Here's a PR for the JS side:

https://github.com/microsoft/botbuilder-js/pull/955

**Comment by Stevenic** [comment]
I currently have two separate steps:

-  `ForEach` which enumerates the individual items of an array or collection.
-  `ForEachPage` which enumerates arrays or collections in pages.

We should decide if we wish to combine these into one step.

**Comment by carlosscastro** [comment]
Fixed in PR #1994
