### ISSUE TITLE
[Adaptive] Lg don't support count(user.emails), if the user.emails is a JArray Type

### ISSUE THREAD

**Issue by luhan2017** [Microsoft/botbuilder-dotnet#1704]
This is in the Email bot.
The LG template:
![image](https://user-images.githubusercontent.com/32191031/56182496-1736fb80-6045-11e9-8724-af02211dd142.png)

In the bot we got "You should not be here" response. which is not correct.

Here is the exception:
![image](https://user-images.githubusercontent.com/32191031/56182530-3a61ab00-6045-11e9-9305-e137bf2c60b3.png)

**Comment by Danieladu** [comment]
Fix it in #1706
