### ISSUE TITLE
OAuthPrompt Teams SSO

### ISSUE THREAD

**Issue by DavidVollmers** [Microsoft/botbuilder-dotnet#1724]
## Version
Microsoft.Bot.Builder.Dialogs 4.3.2

## Describe the bug
OAuthPrompt does not handle the MS Teams Invoke Activity like it does with a magic number Message Activity.

## To Reproduce
hasTimouted will only be true if the activity is a message:
https://github.com/Microsoft/botbuilder-dotnet/blob/54d0b2eadf2eab09841f1e099749d778929f1f4d/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L138

RetryPrompt will never be used on wrong SSO from MS Teams:
https://github.com/Microsoft/botbuilder-dotnet/blob/54d0b2eadf2eab09841f1e099749d778929f1f4d/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L169

## Expected behavior
MS Teams SSO should have the same behaviour like any other authentication on any other channel.

## Additional context
Also there is no way to change prompt texts at runtime (localization). I would like to see the following made accessable at runtime:
https://github.com/Microsoft/botbuilder-dotnet/blob/54d0b2eadf2eab09841f1e099749d778929f1f4d/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L62

[bug]

**Comment by cleemullins** [comment]
Hi David! 

This has been fixed in "master" and will ship in our 4.4 release in early May. If you need a solution sooner, you can pickup [the most recent build from our daily build server](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder). 

The PR in question is #1568. Please take a look and confirms that does what you need...

**Comment by DavidVollmers** [comment]
Hi @cleemullins 

The mentioned PR only fixes the issue with opnening the signin as a browser window. But still hasTimeouted and RetryPrompt will only be used if the activity is of type Message. But the MS Teams SignIn is of type Invoke...

Does this mean the behaviour is intended?
Also there is still no way to change prompt texts after the initialization of the OAuthPrompt...

BR
David Vollmers
