### ISSUE TITLE
Slow bot response since v4.2.2

### ISSUE THREAD

**Issue by sombe** [microsoft/botbuilder-dotnet#1741]
I noticed that in asp-mvc-bot performance of bot response decreased significatly after updating packages to v4.2.2 and higher. Using sample 30.asp-mvc-bot that references to v4.2.0 the average response time is ~100ms. Updating packages to v4.2.2 and higher time response is ~2000ms and exponentially increase for each next request. If you want to reproduce the problem use the indicated sample and update packages.
Any idea how to solve this?

**Comment by sombe** [comment]
Update: using the new version of samples (with mvc pattern) and packages v4.3.2, the issue seems to be resolved and the bot responds quickly.

**Comment by EricDahlvang** [comment]
@sombe Thank you for confirming the issue is fixed.
