### ISSUE TITLE
Improve LG validation error for multi-line variations

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#1755]
For this template, missing closing ``` for multi-line variation for HeroCard template causes an error on the subsequent template definition by name. This should instead be updated to say 'Missing end of multi-line definition for template **TemplateName**'.

Actual error seen: '[ERROR]: no such template 'HeroCard' to call in lgTemplate('HeroCard') in expression `lgTemplate("HeroCard")`'

Expected: '[ERROR]: Missing end of multi-line variation text in template 'HeroCard'. Please verify that all multi-line segments have trailing ``` to end the multi-line variation text'

``` markdown
    # HeroCard
    - ```
    [Herocard   
        title = BotFramework Hero Card
        subtitle = Microsoft Bot Framework
        text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
        image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
        buttons = Show more cards]

    # ThumbnailCard
    - ```
    [ThumbnailCard
        title = BotFramework Thumbnail Card
        subtitle = Microsoft Bot Framework
        text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
        image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
        buttons = Get Started
    ```

    # AllCards
    - ```
    @{lgTemplate("HeroCard")}
    @{lgTemplate("ThumbnailCard")}
    ```
```

**Comment by boydc2014** [comment]
Thanks @vishwacsena, this is a little bit tricky because as you can see from GitHub auto syntax highlighting that 
![image](https://user-images.githubusercontent.com/3829387/56537891-3c22f580-6594-11e9-8ead-c58668c153f7.png)

the next ``` is recognized as the end of multiline, so i'm not sure we can know about there is ``` missing, if we allow `# blabla` in multi-line mode, so, perhaps what we can do is show some errors in `[ThumbnailCard `? what do you think?
