### ISSUE TITLE
HttpClient injection appears not wired up in Microsoft.Bot.Builder.AI.Luis

### ISSUE THREAD

**Issue by nicholasamiller** [Microsoft/botbuilder-dotnet#1759]
The client for QnA maker in Microsoft.Bot.Builder.AI.QnA allows injection of an HttpClient, but the client for LUIS does not.

(I could be wrong about this. If I am, how do I inject an HttpClient?)

## Version
4.3.2

## Expected behavior
Allow injection of an HttpClient.

## Screenshots

LuisRecognizer uses contructor of LuisRuntimeClient, without passing in HttpClient:

![image](https://user-images.githubusercontent.com/20632432/56548283-0f3a0700-65c3-11e9-80ca-afa5f6d61866.png)

I notice that LuisRuntimeClient does actually have a constructor which takes an HttpClient.  It is just not used.

...so ServiceClient will new one up.
![image](https://user-images.githubusercontent.com/20632432/56548588-ccc4fa00-65c3-11e9-8616-5013911ef31b.png)

**Comment by cleemullins** [comment]
@nicholasamiller We're about to release the 4.4 branch, and I'll be cutting 4.4.0 RC1 likley in about 24 hours. Do you have time to submit a PR to fix this?

**Comment by cleemullins** [comment]
Actually, it looks like we already cleaned up this up in the 4.4 cycle:
![image](https://user-images.githubusercontent.com/1165321/56620927-749bf100-65df-11e9-9e0b-434f993085f8.png)

@Zerryth did this work in PR #1635.

**Comment by nicholasamiller** [comment]
Hi Chris, thanks for your quick response, no time personally to do a PR in
the next 24 hours sorry.
