### ISSUE TITLE
AddBotApplicationsInsights requires use of .bot file

### ISSUE THREAD

**Issue by jwiley84** [microsoft/botbuilder-dotnet#1763]
## Version
4.3

## Describe the bug
AddBotApplicationInsights() in Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/ServiceCollectionExtensions.cs has no implementation that does not require the BotConfiguration. 

Work around being tested:
```
// The following line enables Application Insights telemetry collection.
//services.AddBotApplicationInsights(services.GetRequiredService<IConfiguration>());

services.AddApplicationInsightsTelemetry();
           
services.AddSingleton<IBotTelemetryClient>(options => new BotTelemetryClient(new TelemetryClient()));
```
[bug]

**Comment by daveta** [comment]
I think this is already fixed with the new sample..

**Comment by munozemilio** [comment]
Hi @cleemullins  I already did a PR to fix this which is pending approval.
