### ISSUE TITLE
Getting Started Wiki points at wrong packages

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-dotnet#177]
I would just PR this, but I know the package names are in flux. The wiki currently indicates:

Add references to the following packages:
```
Microsoft.Bot.Builder
Microsoft.Bot.Builder.Core
Microsoft.Bot.Connector
Microsoft.Bot.Schema
```
Without specifying that one needs to hit the pre-release checkbox and download the v4.0.0 alpha packages. Without knowing this, devs accidentally install v3.

**Comment by JonathanFingold** [comment]
Updated. Will fix again as names and status change.
