### ISSUE TITLE
[Adaptive] [DCR] Add property to choice prompt that lets user control return value type - index .vs. text value

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1782]
ChoiceInput at the moment returns an object that includes value, index, score and synonym. We need to have choiceInput return either the value or index of the choice item based on user specified property on ChoiceInput.

**Comment by garypretty** [comment]
@vishwacsena @Stevenic I have submitted a PR for this.  Please let me know if you think a slightly different approach is required and I will be happy to update.  I included the 3rd option of FoundChoice (along with value / index) to provide access to the other properties if required. Cheers!

**Comment by vishwacsena** [comment]
Covered via input DCR work to be able to set choiceoutputformat. 

https://github.com/microsoft/botbuilder-dotnet/blob/47aef484e4e62a4a5f3c351549f8e079ec3698d9/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ChoiceInput.cs#L23
