### ISSUE TITLE
Template errors are swallowed and turn into a null error

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#1791]
## Version
Direct build as of 4/25/2019.

## Describe the bug
When there is a missing template error, the error is generated in TryEvaluate, but is then swallowed and turned into a null which later results in a null object exception when the null is used which is much less informative.  Here is the stack:
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine.RunStaticCheck(System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.LGTemplate> templates) Line 97
	at C:\Users\chrimc\Source\Repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.LanguageGeneration\TemplateEngine.cs(97)
Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine.Evaluate(string inlineStr, object scope, Microsoft.Bot.Builder.LanguageGeneration.IGetMethod methodBinder) Line 138
	at C:\Users\chrimc\Source\Repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.LanguageGeneration\TemplateEngine.cs(138)
Microsoft.Bot.Builder.LanguageGeneration.Renderer.dll!Microsoft.Bot.Builder.LanguageGeneration.Renderer.LGLanguageGenerator.TryEvaluate(Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine engine, string text, object data, System.Func<string, object, object> valueBinder) Line 175
	at C:\Users\chrimc\Source\Repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.LanguageGeneration.Renderer\LGLanguageGenerator.cs(175)
Microsoft.Bot.Builder.LanguageGeneration.Renderer.dll!Microsoft.Bot.Builder.LanguageGeneration.Renderer.LGLanguageGenerator.BindToTemplate(Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine engine, string inline, string id, object data, string[] types, string[] tags, System.Func<string, object, object> valueBinder) Line 120
	at C:\Users\chrimc\Source\Repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.LanguageGeneration.Renderer\LGLanguageGenerator.cs(120)
Microsoft.Bot.Builder.LanguageGeneration.Renderer.dll!Microsoft.Bot.Builder.LanguageGeneration.Renderer.LGLanguageGenerator.Generate(string targetLocale, string inlineTemplate, string id, object data, string[] types, string[] tags, System.Func<string, object, object> valueBinder) Line 86
	at C:\Users\chrimc\Source\Repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.LanguageGeneration.Renderer\LGLanguageGenerator.cs(86)
Microsoft.Bot.Builder.Dialogs.dll!Microsoft.Bot.Builder.Dialogs.TextMessageActivityGenerator.Generate(string locale, string inlineTemplate, string id, object data, string[] types, string[] tags, System.Func<string, object, object> binder) Line 49
	at C:\Users\chrimc\Source\Repos\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Dialogs\TextMessageActivityGenerator.cs(49)

## To Reproduce
1. Create a dialog that refers to a non-existent template.
2. You will see the null exception.

## Expected behavior
I would expect the template error to bubble up to the top.  Probably should not be calling TryEvaluate, but calling Evaluate.

## Additional context

[bug]

**Comment by boydc2014** [comment]
@tomlm what do you think? stop using TryEvaluate?

**Comment by Danieladu** [comment]
This issue may be fixed by @tomlm  in the new LG System. reference: https://github.com/microsoft/botbuilder-dotnet/blob/4.Future/libraries/Microsoft.Bot.Builder.LanguageGeneration.Renderer/TemplateEngineLanguageGenerator.cs
