### ISSUE TITLE
[Adaptive] Memory accessor shortcut does not resolve to an actual value

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1798]
I tried @EntityName in my C# sample.  Here's what LUIS returns.

When I use @EntityName, I get the entire list back instead of the first value. JS implementation I believe points to the first value in the list - so effectively @EntityName is turn.entities.EntityName[0], #IntentName is turn.intents[0].key == "IntentName".

@boydc2014 @chrimc62 @Stevenic 

```json
{
  "recognizerResult": {
    "alteredText": null,
    "entities": {
      "$instance": {
        "todoTitle": [
          {
            "endIndex": 20,
            "startIndex": 4,
            "text": "finish this demo",
            "type": "todoTitle"
          }
        ]
      },
      "todoTitle": [
        "finish this demo"
      ]
    },
    "intents": {
      "AddToDoDialog": {
        "score": 0.999983847
      }
    },
    "text": "add finish this demo to the list"
  }
}
```

**Comment by chrimc62** [comment]
I believe that is on purpose.  If you want the first one you can explicitly refer to it, i.e. @foo[0].  Otherwise there is no way to pick up multiple entities of the same type.

**Comment by boydc2014** [comment]
close due to dup
