### ISSUE TITLE
[Adaptive] SaveEntity step cannot use entity short hand notation

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#1799]
When I do this (which is an intended use case for the short-cuts), I see an exception. 

``` C#
new SaveEntity()
{
    Property = "turn.addTodo.title",
    Entity = "@todoTitle[0]"
}
```

**Exception**: shorthand like @todoTitle is not allowed in an accessor

**Comment by vishwacsena** [comment]
#1798

**Comment by Danieladu** [comment]
Maybe there are some problems here.

`if (dc.State.TryGetValue<object>($"turn.entities.{Entity}", out var values))`, code from class `SaveEntity` line 45

So there is no need to add @ in front of entityName

**Comment by tomlm** [comment]
should just be **entity = 'todoTitle'**

**Comment by boydc2014** [comment]
> Maybe there are some problems here.
> 
> `if (dc.State.TryGetValue<object>($"turn.entities.{Entity}", out var values))`, code from class `SaveEntity` line 45
> 
> So there is no need to add @ in front of entityName?

We can print out the expression of this exception to help clarify next time?
