### ISSUE TITLE
Timeout in Cortana channel

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-dotnet#180]
Hi, we are using a bot on the Cortana channel and we are sending a reply with InputHint = InputHints.ExpectingInput in single turn replies.

The issue is that the Cortana text box stays as "Thinking" followed by a timeout message (see attached screenshots). I tried with IgnoringInput and I have the same issue.

Also, I'm not 100% sure that it is the same problem but the WebChat shows user messages as Sending... and never changes to Sent.

Is this a known issue?
![thinking](https://user-images.githubusercontent.com/12264946/36564439-58cb8b18-17eb-11e8-9aa7-99799bc57d96.png)

![timeout](https://user-images.githubusercontent.com/12264946/36564455-602e05f2-17eb-11e8-9753-d39c1a29f348.png)

**Comment by Stevenic** [comment]
The problem is most likely that your bot logic took longer than 10 seconds to execute.  Are you performing some sort of long running query?

**Comment by gabog** [comment]
Thanks for the time Steve, as we discussed the issue is that my code seems to be sending IgnoringInput instead of AcceptingInput at the end of the flow, I will fix that.
