### ISSUE TITLE
Declarative regex should be consistent across languages

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#1805]
## Describe the bug
The RegExRecognizer needs to have a consistent regex expression across multiple computer languages.  We either need to pick a common subset or add translation of the subset we support to different regex runtimes.

## To Reproduce
Create a declarative regex recognizer with a complex regex and run on node and C#.

## Expected behavior
Declarative files should run on any runtime.

[bug]

**Comment by tomlm** [comment]
It actually is consistent across all of the languages except for javascript.  There is a non-native javascript regex library we could use, but it would be annoying to javascript developers

**Comment by boydc2014** [comment]
I guess this one can be closed @tomlm @chrimc62, in JS we now support the syntax of common regex.

**Comment by vishwacsena** [comment]
Is this also wired up in the regex recognizer?

**Comment by EricDahlvang** [comment]
@vishwacsena it will be when we merge this PR from @boydc2014 

https://github.com/microsoft/botbuilder-dotnet/pull/2130
