### ISSUE TITLE
[hackathon] LG parser doesn't allow white space between IF and :

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/botbuilder-dotnet#1806]
In the [Adaptive Dialog multi-turn prompt sample](https://github.com/Microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/csharp_dotnetcore/05.multi-turn-prompt/Dialogs/UserProfileDialog/Resources/UserProfileDialog.LG), the following code behaves incorrectly:

```
﻿# FinalUserProfileReadOut
- IF : {turn.finalConfirmation == true}
    - I have your mode of transport as {user.userProfile.Transport} and your name as {user.userProfile.Name}. [UserAgeReadBack]
- ELSE :
    - Thanks. Your profile will not be kept.
```

It only works if the white space before each colon is eliminated. As it is, it will output `IF : True` or `IF : False`. The expected behavior is that the LG parser should allow `IF:` or `IF :` when evaluating LG conditionals.

[bug]

**Comment by vishwacsena** [comment]
@boydc2014 - we should fix this for //build.

**Comment by boydc2014** [comment]
Fixed by https://github.com/Microsoft/botbuilder-dotnet/pull/1824
