### ISSUE TITLE
[Adaptive] SaveEntity step should not hard code "turn.entities."

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#1809]
Save Entity setp at the moment hard codes "turn.entities." to passed in entity name. We should instead have this be expanded by the expression system if the user said @EntityName or have the user explicitly say turn.entities.EntityName .. 

With that said, we should probably drop save entity since the @EntityName is sufficient to capture the use case to promote an entity to a property and the user could simply use `SetProperty` step instead.

**Comment by tomlm** [comment]
PR : https://github.com/Microsoft/botbuilder-dotnet/pull/1819
