### ISSUE TITLE
Add Typist Middleware to Extension Directory

### ISSUE THREAD

**Issue by RyanDawkins** [Microsoft/botbuilder-dotnet#181]
Per pull request #150, @cleemullins mentioned to create a GitHub issue to add some middleware to the wiki. 

Link to github repository: https://github.com/RyanDawkins/botframework-typist
Nuget: https://www.nuget.org/packages/RyanDawkins.Typist/1.0.0-pre

**Comment by RyanDawkins** [comment]
Due to the changes released I'm remedying my middleware. I'll reopen once I have fixed it due to the new changes.

**Comment by RyanDawkins** [comment]
Middleware now works with the latest.

**Comment by cleemullins** [comment]
@RyanDawkins What text would you like me to add to the Directory? 

If you give me a bit of Markdown, I'll add it.

**Comment by Stevenic** [comment]
added
