### ISSUE TITLE
[Adaptive] [Docs] forEach function is not documented

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#1814]
We should get this documented and add to the pre-built functions list.

**Comment by vishwacsena** [comment]
Also see this - 'forEach does not have a built-in expression evaluator.'

Is forEach not implemented yet? I thought it was.

**Comment by Danieladu** [comment]
'foreach' function is already there.

**Comment by vishwacsena** [comment]
We need to add it to docs + include a sample usage snippet.
