### ISSUE TITLE
Coveralls reporting is broken

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#1828]
The build system is no longer reporting Coveralls coverage.

**Comment by cleemullins** [comment]
I believe this is fixed now. @BruceHaley can you confirm?

**Comment by BruceHaley** [comment]
Both BotBuilder-DotNet master Functional Tests and BotBuilder-DotNet master CI-PR are publishing to coveralls.io: https://coveralls.io/repos/231490/builds
