### ISSUE TITLE
Bug: Attachment's ContentUrl Link returns 404 

### ISSUE THREAD

**Issue by ltwlf** [microsoft/botbuilder-dotnet#1834]
Hey!

I just noticed that the attachment's ContentUrl link starts to return a 404 in the MS Teams channel. For the last few month this worked like a charm. 

The ContentUrl is: https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d9-2d6e2684c00a619f481fb8d0ca1d1ff1/views/**imgo**

But the right url seems to be: https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d9-2d6e2684c00a619f481fb8d0ca1d1ff1/views/**original**

I have this issue with version 4.2.0 and 4.3.2.

Thanks and regards,
Christian

**Comment by ltwlf** [comment]
If anybody has the same issue. My temporary hot fix is just:
attachment.ContentUrl.Replace("imgo", "original");

**Comment by best0032001** [comment]
1 day ago I can't get image from ContentUrl same you.
 What is Microsoft action?

**Comment by dmvtech** [comment]
Can you clarify on how/where you are getting this ContentUrl? For me, with Teams, and using the [following sample](https://github.com/Microsoft/BotBuilder-Samples/blob/d63f981546d26ad8f56ca057db65a0088b65b988/samples/csharp_dotnetcore/15.handling-attachments/AttachmentsBot.cs#L209), I get a path to my OneDrive for Buisness file (`https://<tenant>.sharepoint.com/personal/<mysite>/Documents/Microsoft Teams Chat Files/<filename>.jpg`)

Just an FYI, Teams Channel also surfaces a ODfB shareable link:
`remoteFileUrl = ((JObject)file.Content)["downloadUrl"].ToString();`

**Comment by ltwlf** [comment]
...
`var attachment = turnContext.Activity.Attachments[i];
var contentUrl = attachment.ContentUrl`
....
`            var request = new HttpRequestMessage(HttpMethod.Get, contentUrl);

            var token = await appCredentials.GetTokenAsync();
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

            var response = await httpClient.SendAsync(request);`

**Comment by dmvtech** [comment]
Teams is looking into this. Updates when I have them.

**Comment by CoHealer** [comment]
@dmvtech , has there been any feedback from Teams?

**Comment by dmvtech** [comment]
@cohealer No, not yet. I'm still checking with them often.

**Comment by dmvtech** [comment]
This is still being investigated.

**Comment by best0032001** [comment]
> If anybody has the same issue. My temporary hot fix is just:
> attachment.ContentUrl.Replace("imgo", "original");

it to solve problems   But today  I can't get image from ContentUrl again.

**Comment by dmvtech** [comment]
No update other than being investigated still.

**Comment by dmvtech** [comment]
@ltwlf @best0032001 This should be resolved now.
