### ISSUE TITLE
Tracking issue for cherry-picks from 4.4

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#1839]
Merge / Cherrypick
1. PR #1837 into master. 
2. PR #1843 into master.
3. PR #1848 into master.
4. PR #1866 into master.
5. PR #1868 into master.

This issue is a reminder to cherrypick a last-minute change in the sidecar debugging story back into master.

**Comment by johnataylor** [comment]
these are in master now
