### ISSUE TITLE
'Brackets' middleware not nearly as trivial as node variant

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#184]
If one wanted to write a "brackets" middleware that surrounded each bot response in a starting bracket (`{`) and an ending bracket (`}`) it looks like this in the node SDK (typescript):
```typescript
public async receiveActivity(context: BotContext, next: () => Promise<void>): Promise<void> {
context.reply("{");
await next();
context.reply("}");
}
```
but in the .Net SDK, something this trivial isn't possible. You might think it'd look like this:
```csharp
public async Task ReceiveActivity(IBotContext context, MiddlewareSet.NextDelegate next)
{
    context.Reply("{");
    await next();
    context.Reply("}");
}
```
but when you execute that you get:
![image](https://user-images.githubusercontent.com/20270743/36620025-0f0c326e-18a6-11e8-9fb0-b201d38ea003.png)
So then you might start playing with TPL and try something like this:
```csharp
public async Task ReceiveActivity(IBotContext context, MiddlewareSet.NextDelegate next)
{
    context.Reply("{");
    await next().ContinueWith(t => context.Reply("}"));
}
```
but to no avail.

The only way I was able to get this to work properly was to make the middleware both a Receive **and** a Send middleware like so:
```csharp
public class Brackets : IMiddleware, IReceiveActivity, ISendActivity
{
    public async Task ReceiveActivity(IBotContext context, MiddlewareSet.NextDelegate next)
    {
        context.Reply("{");
        await next();
    }
 
    public async Task SendActivity(IBotContext context, IList<IActivity> activities, MiddlewareSet.NextDelegate next)
    {
        await next();
        context.Reply("}");
    }
}
```
which is far more complex than what we see in node.

### This leads me to believe our middleware pipeline in dotnet still isn't quite right.

cc @cleemullins @ryanvolum @tomlm

**Comment by cleemullins** [comment]
Interesting. I'll look into this.

**Comment by ryanvolum** [comment]
Not only is this an issue of complexity, but the C# workaround that Brandon wrote has different functionality. SendActivity gets called every time responses are flushed, so if a developer flushes responses mid-turn, you'd have multiple close brackets in this scenario.

**Comment by cleemullins** [comment]
I know what the bug here is. All the middleware in that pipeline is being run to completion, THEN the receive handler is called.

The receive handler should be called when the decent is completed, not when the ascent is completed.

Easy fix, fortunately.

I’ll have the fix + tests in by Monday.

________________________________

**Comment by Stevenic** [comment]
@cleemullins the single pipe middleware approach makes this a lot clearer as well. You run the leading edge for all of the middleware plugins, then execute the bots logic, and when that completes all of the trailing edges for plugins will run.

In the current multiple pipe model your left guessing a bit as to what the sequence should be. It's not intuitive for instance that you should hold open the `ContextCreated()` pipe until after `OnReceive()` completes.

**Comment by cleemullins** [comment]
@stevenic, you don't have to convince me the Single Pipeline model is cleaner. I'm there! :)

**Comment by cleemullins** [comment]
This has been fixed.
