### ISSUE TITLE
How can we send a file like image, video in bot builder 4 using waterfallstepcontext

### ISSUE THREAD

**Issue by Anu0763** [Microsoft/botbuilder-dotnet#1849]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]

**Comment by EricDahlvang** [comment]
Hi @Anu0763 

The [WaterfallStepContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.waterfallstepcontext?view=botbuilder-dotnet-stable) has a Context property that is the TurnContext.  The TurnContext has a [SendActivityAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.turncontext.sendactivityasync?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_TurnContext_SendActivityAsync_Microsoft_Bot_Schema_IActivity_System_Threading_CancellationToken_) method.  Creating an image Attachment, and adding it to the reply's attachments can be done in C# with code like this:

```cs
private async Task<DialogTurnResult> StepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
{
  var turnContext = stepContext.Context;
  var activity = turnContext.Activity;
  var reply = activity.CreateReply();
  reply.Text = "This is an attachment.";

  // Inline attached image
  var imagePath = Path.Combine(Environment.CurrentDirectory, @"Resources\architecture-resize.png");
  var imageData = Convert.ToBase64String(File.ReadAllBytes(imagePath));
  var attachment = new Attachment
  {
    Name = @"Resources\architecture-resize.png",
    ContentType = "image/png",
    ContentUrl = $"data:image/png;base64,{imageData}",
  };
  reply.Attachments = new List<Attachment>() { attachment };


  // Or, an Internet url attachment
  var urlAttachment = new Attachment
  {
    Name = @"Resources\architecture-resize.png",
    ContentType = "image/png",
    ContentUrl = "https://docs.microsoft.com/en-us/bot-framework/media/how-it-works/architecture-resize.png",
  };
  reply.Attachments = new List<Attachment>() { attachment };

  await turnContext.SendActivityAsync(reply);

```

More information can be found [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments?view=azure-bot-service-4.0&tabs=csharp)
