### ISSUE TITLE
Terminology cleanup suggestion: "Bot" --> "Adapter"

### ISSUE THREAD

**Issue by v-stbee** [Microsoft/botbuilder-dotnet#185]
BotContext.ConversationReference.**Bot** should be BotContext.ConversationReference.**Adapter**

**Comment by Stevenic** [comment]
This is actually defined at the Bot Framework protocol level and would break Skype, MS Teams, Linked In, and numerous other services if we changed it. A lot of stuff we're just stuck with until we decide to create a whole new version of the protocol.

**Comment by cleemullins** [comment]
+1 to what steve said. Your suggestion is a good one, but it would be change for change sake and drifting away from the protocol.
