### ISSUE TITLE
Inspection Middleware can fail if a message activity has no text but only attachment

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#1860]
## Version
4.4

## Describe the bug
Inspection Middleware can fail if a message activity has no text but only attachment

## To Reproduce
Attachments and no text.

This will also be in the JavaScript.

**Comment by cleemullins** [comment]
Needs to be fixed in JS and Python as well.

**Comment by johnataylor** [comment]
Fixed in C# needs fix in Node.

**Comment by johnataylor** [comment]
fixed in both repos
