### ISSUE TITLE
Properties under BotFrameworkAdapter.ConversationReference (and others) are settable

### ISSUE THREAD

**Issue by v-stbee** [Microsoft/botbuilder-dotnet#187]
Are all of these properties supposed to be settable? It seems like they (at least many of them) should be read-only.

**Comment by Stevenic** [comment]
In most cases you can both send and receive instances of types like `Activity` and `ConversationReference`. Given that just about all of the properties have to be settable otherwise we'd need a totally different schema for outgoing types versus incoming types.

**Comment by cleemullins** [comment]
We have two primary scenarios:
1. Request / Response pattern (aka: the common pattern), where the bot just responds to incoming messages. It's not 1:1, but the bot gets a message, then sends some number of outbound messages in response.

2. The Proactive case where somethign happens (timer / event / whatever) and the Bot decides it needs to send a message. 

In both cases we could: 
1. Add a ctor to the ConversationReference that took an Activity. From there it could extract the relevant properties and populate itself. This would cover the Request / Response pattern and would allow the properties to be read-only. 

2. Add a ctor that has the relevant properies and just accepts them as arguments. This would cover the Proactive scenario and let us make the properties read-only. 

I'm not really sure it matters, especially as the Conversation Reference is auto-generated from the Swagger file. Leaving it as just a pure [POCO](http://www.c-sharpcorner.com/UploadFile/5d065a/poco-classes-in-entity-framework/) seems the best choice.
