### ISSUE TITLE
Dependencies of adaptive dialog are not included in the DialogSet before calling ConsultDialogAsync

### ISSUE THREAD

**Issue by Crazedpeanut** [microsoft/botbuilder-dotnet#1882]
## Version
ComposableDialog

## Describe the bug
Dependencies of adaptive dialog are not included in the DialogSet before calling ConsultDialogAsync.

I have a multi-turn adaptive dialog, that prompts with TextInput, then on the next turn when the response is sent back I receive `DialogContext.ConsultDialogAsync(): Can't consult dialog. A dialog with an id of 'TextInput[conversation.test]:prompt' wasn't found

## To Reproduce
1. Create Adaptive Dialog
2. Call OnTurn
3. Reply to prompt
4. Create Adaptive Dialog
5. Call OnTurn

## Expected behavior
AdaptiveDialog should continue to work through the steps in the plan

## Additional context
AdaptiveDialog
```
new AdaptiveDialog
            {
                Steps = new List<IDialog>
                {
                    new TextInput
                    {
                        Prompt = new ActivityTemplate("hi!"),
                        Property = "conversation.test"
                    },
                    new SendActivity("hi {conversation.test}")
                }
            }
```

[bug]

**Comment by Crazedpeanut** [comment]
I created PR #1881 to help describe the issue I am having

**Comment by Crazedpeanut** [comment]
Deleted #1881 and created #1959 which targets 4.Future

**Comment by carlosscastro** [comment]
We already fixed this. Thanks for the PR!
