### ISSUE TITLE
[Adaptive][DCR] Expressions deal with datetime in a very awkward way.

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#1885]
**Is your feature request related to a problem? Please describe.**
The expression language deals with datetime in a very awkward way.  For example, timestamps are assumed to be strings, not numbers which makes their comparison problematic because string comparison is not numerical comparison.  

I can do time math on timestamps, but I can't easily turn a C# datetime like turn.activity.timestamp into a timestamp.  

**Describe the solution you'd like**
Switch to a model where we can tell when evaluating that a value is a datetime and all operations or comparisons operate on date times.  We might also need a way of coercing something like turn.activity.timestamp into the expression date time. This will make comparisons work and also makes it easier to convert things like C# datetime into a timestamp.  

[enhancement]

**Comment by vishwacsena** [comment]
To consolidate the various platforms we support and provide an elegant and consistent runtime platform agnostic expeirence we will do 2 things 

- Support [comparison operations](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language#operators) against date, time represented as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string
- Update [FormatDateTime](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#formatDateTime) behavior - 
    - The function can take a string or platform specific date time properties as first argument
    - (current behavior) The second argument is optional and defaults to ISO 8601 string

**Comment by boydc2014** [comment]
Close this since this is considered to be resolved
