### ISSUE TITLE
Ensure code is documented to support Microsoft Docs documentation

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#1886]
## Ensure Code decoration supports automatic documentation
In order to ensure that Microsoft Documentation is complete, the source code annotation for generated documentation must be adhered to at checkin time by policy.

We need to:
1. Scan repo for missing annotations and bring them up to documentation quality bar
2. Enforce annotation (e.g. function headers) during code reviews.

### Example
See the following: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.activityhandler.onmembersaddedasync?view=botbuilder-dotnet-stable

**Comment by cleemullins** [comment]
As written, this isn't actionable. Closing as part of 4.5.
