### ISSUE TITLE
Custom middleware sample is platform specific and overly complex

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-dotnet#189]
The sample logs to a text file in the C drive:
```
using (var writer = new StreamWriter(@"C:\Users\Public\ExampleMiddleware.txt", true))
```
Which will only work for Windows machines.

Further, while a logger is certainly a useful piece of middleware, an intro sample could be far simpler (e.g. middleware that capitalizes all bot responses, middleware that wraps all messages in an open/close bracket, etc).

**Comment by cleemullins** [comment]
That’s not right. Who wrote that? :(

Can you submit a fix?

Should be calling system.Io.File.GetTempFilname (or similar) which is platform agnostic.

________________________________

**Comment by JonathanFingold** [comment]
Changed the path to `Environment.CurrentDirectory`, which addresses the first issue, but not the second.

**Comment by cleemullins** [comment]
I've submitted a fix. In this case, the fix was to delete the sample, as it's not adding any value.
