### ISSUE TITLE
Teams: "The Sign In code was not found or expired" Microsoft.Bot.Builder.Dialogs v4.4.3

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#1893]
@jeffders can you investigate and update this issue.

Also note teh JavaScript implementation is different and doesn't have the check for msteams at all.

**Comment by gabog** [comment]
Hi @Jeffders , do you have any updates on this one?
Thanks

**Comment by Jeffders** [comment]
A few things are going on here...

1. Teams is having an issue with their client JS library. This is being tracked separately.
2. There is no good way to capture the Invoke that Teams sends back via the ActivityHandler
3. As such, the auth sample is ignoring the Invoke

Currently Teams sends back a lot of Invokes on the SignIn Button behavior (so the bot could ignore subsequent ones), but doesn't send anything on the OpenUrl Button behavior.

**Comment by Jeffders** [comment]
It turns out there is some (possibly new) requirement for how the bot is to respond to the Teams' Invoke Activity that includes the magic code. This activity is sent when the button action is 'SignIn' (which is the 4.4+ behavior). However, the OAuthPrompt does not currently return the correct response. You can add something like this to the AuthBot in the Samples #18 to make things work:

protected override async Task OnUnrecognizedActivityTypeAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    if (turnContext?.Activity.Type == ActivityTypes.Invoke)
    {
        await turnContext.SendActivityAsync(
            new Activity()
            {
                Type = ActivityTypesEx.InvokeResponse,
                Value = null
            });
        await Dialog.Run(turnContext, ConversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);           
    }
}

**Comment by garypretty** [comment]
From my testing the first time you use a Signin button on an OAuth card in Teams it is successful, but clicking it again is when you see the error about the link expiring, which I suppose makes sense.  I took a look at what @Jeffders was alluding to and I have raised PR #1963 which tries to address this issue.

The PR adds support for Invoke activities on the Activity Handler, consistent with how other activity types are handled, along with support for handling the specific invoke activity sent by teams (signin/verifyState), again consistent with the implementation that currently exists for token event activities. 

I realise this may not be the way you want to proceed, but it is working end to end, so thought I would give us something to start with.  This could also potentially resolve #1913.

**Comment by darrenj** [comment]
I am using 4.4 SDK and using the above workaround can't get to the point where Teams will allow the user to click the login button and complete authentication. I have added the `OnUnrecognizedActivityTypeAsync` handler but this isn't invoked.

I can click the button but nothing happens in Team. Note that I am testing Teams by clicking the registered Channel which then pops up Teams. I haven't used AppStudio/manifest.

![image](https://user-images.githubusercontent.com/33519520/58631940-f6b4bf00-82db-11e9-9117-661bb03bdcfa.png)

**Comment by garypretty** [comment]
@darrenj I tested this week and you appear to need the app manifest or it just won't work. The PR I submitted fixes the routing issue but doesn't get around the manifest requirement.

**Comment by darrenj** [comment]
Thanks Gary.

Urgh - I'll try with a Manifest. It would be good to unblock the Teams channel (sideloading) route as that's what most people do so we should have a story here or worst case a clear warning in the Azure portal.

**Comment by garypretty** [comment]
@darrenj Agree that unblocking the maifest requirement would be great, but I think that's going to need to come from the Teams side. In the interim I think we may need to make it very explicit in the docs that this is required.

**Comment by darrenj** [comment]
Progress - however it just "spins", any specific manifest settings I may have missed?

![image](https://user-images.githubusercontent.com/33519520/58637059-92006100-82e9-11e9-90b7-351c43ed1fc2.png)

**Comment by garypretty** [comment]
@darrenj The token domain was going to be the one I suggested.  How are you accessing the bot?  You can't go directly via the link, you need to open the 'new' bot that you just registered.  Within the app manifest there should be an 'open' link for the bot or you should be able to search by using the display name you gave the bot in the manifest.

**Comment by garypretty** [comment]
@darrenj Also, stick a breakpoint on the unrecognized activity method and see if the invoke is actually being received by the bot or not.

**Comment by garypretty** [comment]
@darrenj Is it getting here? Could be a potential place for it to get trapped. https://github.com/microsoft/botframework-solutions/blob/b2de2a733908079ae9d870a5367e18b4c8479471/templates/Enterprise-Template/src/csharp/EnterpriseBotSample/EnterpriseBotSample/Dialogs/Shared/RouterDialog.cs#L81

**Comment by darrenj** [comment]
This one is on me - we don't leverage the Unrecognizedactivity route (for valid reasons!) so of course it wasn't being invoked 🤦‍♂️

Is  now being invoked but debugging a further issue where it doesn't carry on after logging in.

**Comment by darrenj** [comment]
Thanks - do you see multiple (many) verify/State messages coming in from Teams? I respond with `InvokeResponse` but get multiple of them so wanted to check that was expected behaviour?

**Comment by garypretty** [comment]
Yes, I believe thats expected. I saw someone was looking into what they all were for in case we need to handle them differently, but for now sending the response seems to do the trick.

**Comment by darrenj** [comment]
Thanks all - fixed it. Our RouterDialog (for valid reasons until now) didn't push Invoke Messages down the dialog stack so overriding the base implementation enabled me to override this and pass it on. 

Easy fix in our nuget...

 protected async override Task<DialogTurnResult> OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken = default)
        {
            if (innerDc.Context.Activity.Type == ActivityTypes.Invoke)
            {   
....
            }
            else
            {
                // call base
                return await base.OnContinueDialogAsync(innerDc, cancellationToken);
            }
        }

**Comment by cleemullins** [comment]
The Teams OAuth changes were pushed as part of the 4.4 Hotfix, and are also rolled into the 4.5 release. We've gotten explicit sign-off from Teams (Sid, Bill, etc) that the code in place (on both sides) is "Good" and everything is now as it should be.
