### ISSUE TITLE
Alarm sample: 'add an alarm' doesn't work if the previous command was 'show alarms'

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-dotnet#190]
![image](https://user-images.githubusercontent.com/3801171/36639923-218674ec-19cb-11e8-8949-440ef17f2541.png)

**Comment by nrobert** [comment]
'add an alarm' is not a valid expression for the regex which is "add alarm(.*)"
I'm preparing a PR about those alarm-sample problems, I also noticed a crash of the Show alarms command when the user hasn't set any alarm

**Comment by garypretty** [comment]
@cleemullins @anastasiia-zolochevska I have retested this following #261 getting merged a few hours ago and this seems to be fixed, so I believe should be good to close now.
