### ISSUE TITLE
NullReferenceException in TelemetrySaveBodyASPMiddleware.cs

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botbuilder-dotnet#1902]
## Version
4.3.2

## Describe the bug
`NullReferenceException` in `request.ContentType.StartsWith` at https://github.com/microsoft/botbuilder-dotnet/blob/9752fbfaaaf93d5faf38aa5e8d4b59c1a0f20262/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs#L27

When adding MVC to a bot app and making a POST call without setting the `Content-Type` header

## To Reproduce
1. Add MVC to the bot web app
2. Add a custom API controller (e.g. to generate tokens from the directline secret)
3. Make a POST call to fetch the token from that controller, and do not set the ContentType (this is default behavior in the `fetch` call in https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle)

## Expected behavior
No exception

[bug]

**Comment by garypretty** [comment]
PR #1936 opened for this.  Just added a null check - I don't think anything else is required in the case that the content type is null, but let me know if so and I am happy to update.

**Comment by hansmbakker** [comment]
Nice! I think the null check could also be solved with the `?.` syntax but thank you for the PR!

**Comment by garypretty** [comment]
@hansmbakker No problem. I didn't think ?. would work as it won't produce a valid bool result for the if statement if it was null, so went for this approach.

**Comment by munozemilio** [comment]
Closing as PR got merged
