### ISSUE TITLE
Support QnAMaker Follow-up Prompts

### ISSUE THREAD

**Issue by jurfalino** [microsoft/botbuilder-dotnet#1906]
The QNA portal implemented a new feature to allowusers to define **follow-up questions**, those follow-up questions are returned in a 'context' property in the service response, but the QnAMaker.GetAnswersAsync method doesn´t return that property (only the answer)..

**Solution**
The Bot Framework should auntomatically generate/present dynamic cards when a QNA answer includes follow-up questions.

**Example QNA service response**
```json
{
    "answers": [
        {
            "questions": [
                "What is a Virtual Assistant"
            ],
            "answer": "We have seen significant need from our customers and partners to deliver a conversational assistant tailored to their brand, personalized to their customers and made available across a broad range of conversational canvases and devices. Continuing Microsoft open-sourced approach toward Bot Framework SDK, the open source Virtual Assistant solution provides full control over the end user experience built on a set of foundational capabilities. Additionally, the experience can be infused with intelligence about the end-user and any device/ecosystem information for a truly integrated and intelligent experience.\nFind out more [here](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/README.md).",
            "score": 100,
            "id": 141,
            "source": "custom editorial",
            "metadata": [],
            "context": {
                "isContextOnly": false,
                "prompts": [
                    {
                        "displayOrder": 0,
                        "qnaId": 182,
                        "qna": null,
                        "displayText": "what type of assistant?"
                    }
                ]
            }
        }
    ],
    "debugInfo": null
}
```

[enhancement]

**Comment by EricDahlvang** [comment]
Follow-up prompts are not supported natively by the sdk yet, but they can still be used by a bot.  An example can be found here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/qnamaker-prompting/csharp_dotnetcore

**Comment by mekinney** [comment]
Related to this, QnAMakerOptions likely needs context added to it, for passing into GetAnswersAsync.

**Comment by johnataylor** [comment]
The current plan is to support this feature through the sample repo. The next step is to update the QnA sample with features from the experimental area.

However, the Active Learning feature is being moved into the product with support for the call-train method in the client see https://github.com/microsoft/botbuilder-dotnet/pull/2124

The feature is available from the service, it just a question of how much progress we have made on incorporating this first class into the programming model. There is some discussion, for example, this "prompt" could be seen as mapping to the Dialog construct, however, a mode-less model would be easier to mix-n-match with other features like other Dialogs and LUIS.

**Comment by zeeshan40** [comment]
<img width="339" alt="follow up prompts" src="https://user-images.githubusercontent.com/31640423/61841274-c744ad80-ae59-11e9-9db9-274119937f53.PNG">

I have the same issue. I have follow up prompts set up in the QnA maker like the picture above shows. However, they just do not show up in the web chat of my Azure portal as shown in the image below. Can someone please further guide on this? Thanks

<img width="432" alt="Webchat snap" src="https://user-images.githubusercontent.com/31640423/61841371-23a7cd00-ae5a-11e9-87ca-d375ce8d4e46.PNG">

**Comment by ac14729** [comment]
Hi @johnataylor @EricDahlvang just wondering on the progress on your last comment (June 27) ?

**Comment by msekkappan** [comment]
I am using bot version 4.5.1, are the prompts available?  or do I need to create the context manually?  I do not see "context": {
                "isContextOnly": false,
                "prompts": [
                    {
                        "displayOrder": 0,
                        "qnaId": 182,
                        "qna": null,
                        "displayText": "what type of assistant?"
                    }
                ]
            } in intellisense.

**Comment by MichaelBuczek** [comment]
I don't know exactly when it became available, but it's there in 4.6.3, works great for me

**Comment by MaxMueller0815** [comment]
Hi,
In which sample?
The experimental (https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/qnamaker-prompting/csharp_dotnetcore) is with cards that cut the text of messages with promts.
<img width="379" alt="text cut" src="https://user-images.githubusercontent.com/4562396/71079679-00c0e100-218c-11ea-8253-2b82679881b7.PNG">

Can you handle the wrap of the text in heroCard?

Others in https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/
Sample 11. 48. and 49.qnamaker-all-features  has no promptst

Thanks for the info!

**Comment by MichaelBuczek** [comment]
Max,
There is a “wrap” property:
[cid:image003.jpg@01D5B59E.A110A320]

Just use that. It’s also accessible in code, if that’s what you need. Good luck!

Kind Regards,
Michael

[hel logo flerfärg]
Skype: michael.buczek@brainless.se<mailto:michael.buczek@brainless.se>
+46 790 763 261

**Comment by MaxMueller0815** [comment]
I tried sample 49.qnamaker-all-features
Maybe i made i mistake before.
now the prompts are displayed correctly!
<img width="446" alt="correct" src="https://user-images.githubusercontent.com/4562396/71082931-41bbf400-2192-11ea-9f71-4bc7149c2528.PNG">

Maybe this will help someone.

**Comment by MaxMueller0815** [comment]
@MichaelBuczek

It seems the wrap property is only available in AdaptiveCards:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format

Thanks!

**Comment by arman-g** [comment]
Why "qna": null, is always null? Is there something should be set so this property can have the follow-up pair?

**Comment by Recidvst** [comment]
Is there an up to date version of this sample?
https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/qnamaker-prompting/csharp_dotnetcore
