### ISSUE TITLE
PromptValidatorContext.AttemptCount will throw an exception when used in a validator for an OAuthPrompt or an ActivityPrompt

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#1912]
## Version
4.4.3

## Describe the bug
The introduction of `PromptValidatorContext.AttemptCount` was presumably intended only for use with prompts that derive from `Prompt<T>`, because `Prompt<T>` automatically initializes `State[AttemptCountKey]` to zero. No such initialization occurs in `OAuthPrompt` or `ActivityPrompt`, yet these classes still use validators. If you provide a validator for one of those prompts and try to access the public method `PromptValidatorContext.AttemptCount` an unfriendly exception will be thrown.

## To Reproduce
1. Create an `OAuthPrompt` or an `ActivityPrompt`
2. Give the prompt a validator
3. Try to access `PromptValidatorContext.AttemptCount` in the validator

Alternatively you can insert the following code into `ActivityPromptTests.Validator` and run the tests in that class:

```c#
Assert.IsTrue(promptContext.AttemptCount > 0);
```

## Expected behavior
There are a few options here:

1. Throw a friendlier exception that explains that `AttemptCount` is only meant to be used with prompts that derive from `Prompt<T>`
1. Handle the case when `State[AttemptCountKey]` hasn't been initialized by
a. initializing it, or
b. returning a default value

If we don't want to throw an exception, we can also decide whether or not we want to add the attempt count feature to `OAuthPrompt` and `ActivityPrompt`.

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/57888782-f1d61280-77e7-11e9-9547-9b56511f30ae.png)

[bug]

**Comment by mdrichardson** [comment]
I believe I saw something similar on the JS side, too, where it was either missing or wouldn't ++ some of the attempts in some of the prompts. Haven't investigated or tested yet, though.
