### ISSUE TITLE
OAuthPrompt does not respond to invoke activity with 200

### ISSUE THREAD

**Issue by navzam** [microsoft/botbuilder-dotnet#1913]
## Version
Microsoft.Bot.Builder.Dialogs v4.4.3

## Describe the bug
After completing the auth flow in Teams, the bot receives an `invoke` activity with the verification code. I route this activity to the currently active `OAuthPrompt` dialog, which gets the token and ends itself as expected. But my bot responds to the request with `501 Not Implemented` instead of `200`. Teams repeatedly sends the `invoke` activity (I assume because it didn't get a `200`) and my bot repeatedly responds with `501`. While this is happening, the "Sign In" button in Teams shows a spinning indicator.

This does not happen with the JS SDK. In JS, my bot responds to the request with `200`, Teams does not send multiple `invoke` activities, and the spinning indicator goes away after the auth flow is completed. I noticed that the JS `OAuthPrompt` [explicitly sends an `invokeResponse`](https://github.com/microsoft/botbuilder-js/blob/48e34acf01228c48cdd4dd9931315bd552d12a85/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L282):

```js
else if (this.isTeamsVerificationInvoke(context)) {
    const code: any = context.activity.value.state;
    await context.sendActivity({ type: 'invokeResponse', value: { status: 200 }});
    token = await this.getUserToken(context, code);
}
```

## To Reproduce
1. Start with the [C# bot authentication sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication) and register your bot, set up authentication, etc.
2. The sample does not handle the `invoke` activity for Teams, so add code to make sure those activities get to the `OAuthPrompt`. I did this somewhat crudely by just running the dialog on unrecognized activity types:
```csharp
// DialogBot.cs
protected override async Task OnUnrecognizedActivityTypeAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    await Dialog.Run(turnContext, ConversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
}
```
3. Add the bot to Teams and chat with it to go through the auth flow. Observe the outbound `501` responses.

[bug]

**Comment by garypretty** [comment]
I have raised a PR #1963 which could potentially resolve this plus a related issue, #1893, regarding Teams signin. Some comments regarding the PR are on the other issue.

**Comment by johnataylor** [comment]
There are two issues here:
1) in the SDK code we need to fix the OAuth prompt and sensitive http marshaling #1979 and #2005 
2) in the samples we should forward the Invoke activity to the Dialog if using Teams.

At some point is would be good to have (2) in the core SDK but we deferred on that because we were not sure of the set of possible Invokes Teams could send.

**Comment by johnataylor** [comment]
The JavaScript code should also not send a 200 if it didn't find the magic code.

**Comment by johnataylor** [comment]
fixed
