### ISSUE TITLE
TestAdapter Improvements for WaterfallSteps

### ISSUE THREAD

**Issue by james-novino** [microsoft/botbuilder-dotnet#1916]
**Is your feature request related to a problem? Please describe.**
Currently, we are utilizing the WaterfallSteps and WaterfallDialogs in a lot of our migration work from V3 -> V4. As part of this migration, we are looking for better ways to improve our test coverage, one of which we discovered with the TestAdapter in V4. The limitation we found with the TestAdpator it does not allow for easily testing steps that may not send a message to a user since there are no methods available to check Step Results or to intercept and mock State changes. 

**Describe the solution you'd like**
1. Allow for the interception or hooks to be exposed via the TestFlow to update or make state changes during the flow to force Dialog branching logic. 
2. Add support for TestFlow to test a single WaterfallStep with access or Assert methods for checking the step output. Would also be nice to be able to pass a specific step output into the step. 

A think a logic improvement for the test adapter would be to allow for unit testing of a single step rather than an entire dialog flow, this can be accomplished by 

**Describe alternatives you've considered**
Unit testing the specific step function is possible but it requires manually building the WaterfallStepContext which can be very tedious and time-consuming.  

[enhancement]

**Comment by sgellock** [comment]
@james-novino @gabog is driving work in this area.  It would be good for the two of you to connect

**Comment by gabog** [comment]
Hi @james-novino, I am working on a new DialogTestClient for 4.5, would you be able to send  me an example of the waterfall you are trying to test so I can see what needs to be exposed? 
The new DialogTestClient exposes a DialogResults property that can let you inspect the last result returned by the dialog but I am not sure if that will help in your case or not.
Thanks

**Comment by gabog** [comment]
Hi @james-novino, I think some of this should be addressed by the new DialogTestClient that we  are planning for 4.5 so I am closing this issue.

You can take a look at the new [CoreBot.Tests](https://github.com/microsoft/BotBuilder-Samples/tree/corebot-updates/samples/csharp_dotnetcore/13.core-bot.tests) sample project and its [readme](https://github.com/microsoft/BotBuilder-Samples/blob/corebot-updates/samples/csharp_dotnetcore/13.core-bot.tests/README.md) in the corebot-updates branch to see what's coming. 

Let us know what you think.
