### ISSUE TITLE
[Adaptive] [DCR] Provide property for consultation opt-in on all inputs

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1917]
At the moment, only TextInput participates in consultation and it is on by default. However we should formalize this and do two things - 

1. Turn consultation off by default on all inputs
2. Provide a 'consultation' property on all inputs that can be set to true/ false.

**Comment by Stevenic** [comment]
What would the input do to influence interruption? It either recognizes the input or it doesnt. Are you wanting a way to turn off "should process" behavior?

**Comment by luhan2017** [comment]
#2087
