### ISSUE TITLE
[Adaptive] Add support for all prompts for both C#

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1918]
Add support for missing prompt types to Adaptive - 
- OAuth, have a working version.
- Attachment, done
- DateTime - parity prompt, done

Future: 
- Separate Date and Time
- DateTimeRange
- Snap to DateTimeDialog

Cut: 
- ~~Activity~~

**Comment by Stevenic** [comment]
Why do we need Activity prompt?  Also... OAuth should be built into the dialog and not a prompt.

**Comment by luhan2017** [comment]
#2087

**Comment by vishwacsena** [comment]
Remaining refinements with OAuth and DateTime inputs are tracked via #2196
