### ISSUE TITLE
[Adaptive] Add QnA dialog + declarative form

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1919]
We need the QnA dialog step to include the following 

Automatically wrap basic single-turn QnA, active learning as well as multi-turn QnA models. 

Provide the following properties/ configurations -

| Property | Type | Required? | Default value | Help text |
|---------|------|-----------|--------------|----------|
|hostname|string|yes|settings.qna.hostname|Host name for your QnA Maker KB. Will be provided as editable configuration property in the UI|
|endpointkey|string|yes|settings.qna.endpointkey|endpoint key for the QnA Maker KB. This will be provided as editable configuration property in the UI |
|Kb-ID|string|yes|settings.qna.kbid|Kb ID of your QnA Maker KB. This will be provided as editable configuration property in the UI|
|threshold|float|yes|0.3|Gets or sets the minimum score threshold, used to filter returned results. This will be provided as configuration property to the user with default value set|
|Strict filter property|expression|no|dialog.qna.strictFilters|Memory property that holds strict filters to use when calling the QnA Maker KB|
|No answer|activity|yes|Sorry, I did not find an answer|Default answer to return when none found in KB|

**Comment by vishwacsena** [comment]
We are going to push this out to 4.6. Marking as such.

**Comment by vishwacsena** [comment]
We need the QnA dialog step to include the following 

Automatically wrap basic single-turn QnA, active learning as well as multi-turn QnA models. 

Provide the following properties/ configurations -

| Property | Type | Required? | Default value | Help text |
|---------|------|-----------|--------------|----------|
|hostname|string|yes|settings.qna.hostname|Host name for your QnA Maker KB|
|endpointkey|string|yes|settings.qna.endpointkey|endpoint key for the QnA Maker KB|
|Kb-ID|string|yes|settings.qna.kbid|Kb ID of your QnA Maker KB|
|top|int|no|1|Gets or sets the number of ranked results you want in the output|
|threshold|float|no|0.3|Gets or sets the minimum score threshold, used to filter returned results|
|Active learning|bool|yes|true|Enable active learning on the KB|
|Auto disambiguate|bool|yes|true|TBD|
|Auto respond |bool|no|yes|Automatically send the response to user|
|property| expression|no|dialog.qna.result|Memory property to store results returned by the QnA action|
|Strict filter property|expression|no|dialog.qna.strictFilters|Memory property that holds strict filters to use when calling the QnA Maker KB|
|Meta data boost|expression|no|dialog.qna.metadata|Memory property that holds meta data to use when calling the QnA Maker KB |

**Comment by mareekuh** [comment]
Is there a document that goes with this so I can get a better understanding of what you have in mind? From a UX perspective, I'd love to have the following:
1. Use QnA maker as a 'knowledge' base for my bot:

- When I set up my bot I can point it to predefined domains and website FAQ or document (QnA maker).
- The data from the FAQ is parced into QnA pairs 
- The data from built in Chit-chat is parsed into QnA pairs 
- The Q is marked as utterance/trigger and stored in LU
- The A is marked as Response and stored in LG
- The Q is parsed and distilled into intents

2. When creating dialogs, I can use this knowledge base to start conversations in my authoring canvas:

- I can pick from the pre-created triggers (parsed Q's from QnAMaker). A prompt (A) node already shows up in my authoring canvas.
- I can pick from the pre-created Responses (A's from QnAMaker) for my prompts and the Q is already filled out in the 'User response section.


-

**Comment by simer99** [comment]
@vishwacsena - Edited the list and removed the ones which wont be provided as part of configuration experience. Let me know if you have any comments.

**Comment by vishwacsena** [comment]
@simer99 can you add a diagram/ describe the flow we discussed yesterday including interruption?

**Comment by simer99** [comment]
> @simer99 can you add a diagram/ describe the flow we discussed yesterday including interruption?

Yep doing just that.

**Comment by simer99** [comment]
![image](https://user-images.githubusercontent.com/50911573/63973531-94c94880-cac8-11e9-9bbf-eaa9f37121ac.png)
![image](https://user-images.githubusercontent.com/50911573/63973553-9dba1a00-cac8-11e9-8a53-e1eacaa31424.png)

@Trojenguri - can you update the complete dialog steps as well?

**Comment by vishwacsena** [comment]
@simer99 - so for the initial implementation we will not participate in consultation?

**Comment by simer99** [comment]
I updated the properties based on our discussion today. Will not have autorespond. We can guide user to perfrom autorespond using HTTP action

**Comment by vishwacsena** [comment]
@simer99 @trojenguri can we close this or is there any remaining work here that needs this ticket to be active?

**Comment by simer99** [comment]
@vishwacsena  we can close this one.
