### ISSUE TITLE
[Adaptive] [LG] ActivityTemplate doesn't accept string with line break

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#1929]
## Describe the bug
when create a new ActivityTemplate(string templateStr), the templateStr can't have '\n' in that, which would cause a parsing error.

## To Reproduce
Pass any str with "\n" or "\r\n" into ActivityTemplate

## Expected behavior
Expect to work well with any string inside it.

**Comment by vishwacsena** [comment]
Closing since the related PR has been merged. Please reactivate if otherwise.
