### ISSUE TITLE
We should release a Messenger platform NuGet package

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#1931]
The Facebook Messenger platform defines JSON schemas for templates that a bot can send to the channel and also for payloads that a bot can receive from the channel. Details can be seen in the Messenger platform documentation: https://developers.facebook.com/docs/messenger-platform/send-messages

When working with C#, it often helps to define .NET types to represent these Messenger schemas. We are currently expecting each of our customers to recreate the Messenger models themselves, as explained in this blog post: https://blog.botframework.com/2017/03/28/custom-channel-data/

While it may seem sensible to rely on Facebook to release a NuGet package pertaining to their platform just as it's Microsoft's responsibility to release the Teams package, this pertains to .NET and not just Facebook, and Microsoft has already released Facebook-related NuGet packages like this: https://www.nuget.org/packages/Microsoft.AspNet.Facebook/

We should release a NuGet package for Bot Framework developers who want to build bots for the Facebook channel.

[enhancement]

**Comment by EricDahlvang** [comment]
I think this is a great idea! The sdk doesn't have a lot of channel specific code though. Maybe it could go here:
 https://github.com/BotBuilderCommunity/botbuilder-community-dotnet

**Comment by garypretty** [comment]
@v-kydela @EricDahlvang Sounds like a good idea to me.  We would gladly accept this into the community repo.

**Comment by v-kydela** [comment]
@garypretty - Currently there are 5 categories in that repo: C# Middleware, C# Dialogs & Prompts, C# Adapters, C# Recognizers, and C# Storage. Should my package go in one of those categories or a new category? The package would be comparable to the Microsoft.Bot.Connector.Teams package or the AdaptiveCards package in that it would mostly consist of models. Perhaps a new category could be "C# Models" or "C# Channels" or "C# Integration."

I think my package might be a sort of odd-one-out in that repo because the package could be for any application using the Facebook Messenger platform and would not be Bot Builder specific. I'm not entirely convinced it would belong in the Bot Builder Community repo. All the namespaces in that repo start with Bot.Builder.Community, and that could be misleading for my package if I do make it agnostic with regard to whether it's being used with the Bot Framework.

**Comment by garypretty** [comment]
Closing as part of the R10 issue triage. This is still something we can accept in the community if it exists.
