### ISSUE TITLE
RemoveRecipientMention does not remove a Skype bot mention

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#1934]
## Version
All versions (including [V3](https://github.com/microsoft/BotBuilder-V3/issues/123)) 

## Describe the bug
When a bot is @mentioned on the Skype channel, it will receive a mention.Text in the following format: 

**Skype**
`Text: "healthtest  this is just a test"`
```js
{{
  "mentioned": {
    "id": "28:2bc5b54d-5d48-4ff1-bd25-03dcbb5ce918"
  },
  "text": "<at id=\"28:2bc5b54d-5d48-4ff1-bd25-03dcbb5ce918\">healthtest</at>"
}}
```

Due to this, **ActivityExtensions.RemoveRecipientMention** does nothing on Skype.  Other channels send @mentions in this format:

**Teams**
`Text:"<at>healthtest</at> this is a test\n"`
```js
{{
  "mentioned": {
    "id": "28:2bc5b54d-5d48-4ff1-bd25-03dcbb5ce918",
    "name": "healthtest"
  },
  "text": "<at>healthtest</at>"
}}
```

## To Reproduce
1) Add a bot to a Skype group chat
2) @mention the bot
3) Call turnContext.Activity.RemoveRecipientMention();
4) Echo the text back to the user
5) Notice that the bot @mention is not removed

## Expected behavior
Either 1) the skype connector service should send @mentions in a format similar to teams or 2) the RemoveRecipientMention should handle Skype @mentions

## Screenshots
![image](https://user-images.githubusercontent.com/11055362/58212493-d06f9d80-7ca3-11e9-8b24-1e2333afa954.png)

## Additional context
Ugly workaround for Skype bots:
```cs
            foreach (var mention in turnContext.Activity.GetMentions().Where(mention => mention.Mentioned.Id == turnContext.Activity.Recipient.Id))
            {
                int index = mention.Text.IndexOf('>');
                var nextIndex = mention.Text.IndexOf('<', index);
                var mentionText = mention.Text.Substring(index + 1, nextIndex - index - 1);
                turnContext.Activity.Text = turnContext.Activity.Text.Replace(mentionText, "").Trim();
            }
```

[bug]

**Comment by garypretty** [comment]
Opened PR #1935 for this - saw it thought it would probably be a quick fix. I have changed the logic to first grab the mentioned display name using a regex and strip it, which should work for all channels. Then clean up any left over empty <at></at> tags.

Altered to....

```cs
foreach (var mention in activity.GetMentions().Where(mention => mention.Mentioned.Id == id))
            {
                var mentionNameMatch = Regex.Match(mention.Text, @"(?<=<at.*>)(.*?)(?=<\/at>)", RegexOptions.IgnoreCase);
                if (mentionNameMatch.Success)
                {
                    activity.Text = activity.Text.Replace(mentionNameMatch.Value, string.Empty);
                    activity.Text = Regex.Replace(activity.Text, "<at></at>", string.Empty, RegexOptions.IgnoreCase);
                }
            }
```
