### ISSUE TITLE
Bot time out exception - could not send "retry"

### ISSUE THREAD

**Issue by PrashantSoniHarman** [microsoft/botbuilder-dotnet#1937]
### [Github issues]
I am getting **could not send "retry"** when Bot is idle for an hour. The first query after an hour always takes a longer time and I receive the "Could not send - retry"  in the bot window. After that, it works fine.

## Version
Microsoft Bot Builder SDK 4.4.3
Project - C#.NetCore

## Describe the bug
The first query after an hour takes longer and I see "could not send -retry" error on bot window.
This was happening with the Bot Framework 3.0 and now I have migrated to 4.0 and its still happening. 

![image](https://user-images.githubusercontent.com/32177830/58236871-79c89900-7d61-11e9-84ee-489940726fd4.png)

Following is the telemetry data
![image](https://user-images.githubusercontent.com/32177830/58236742-2f471c80-7d61-11e9-85a5-0c1e65131b24.png)

![image](https://user-images.githubusercontent.com/32177830/58236788-48e86400-7d61-11e9-8156-2e61ac8b8b7f.png)

![image](https://user-images.githubusercontent.com/32177830/58236815-57368000-7d61-11e9-9024-a9b8094b301c.png)

## To Reproduce
Keep the bot idle for an hour and try the query
The "could not send "retry"" comes after few seconds

## Expected behavior
"retry" should not come.

## Additional context
We are using directline.js library for frontend as following.

`<link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js"></script>

    <script>
        var botConnection = new BotChat.DirectLine({
            token: BotAuthToken
        });

        function random_number() {
            return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
        }

        const user = {
            id: random_number(),
            name: LoggedInUserGivenName + " " + LoggedInUserSurname,
            properties: {
                'source': 'directlinewebapp',
                'user': {
                    'userDispalyName': LoggedInUserGivenName + " " + LoggedInUserSurname,
                }
            }
        };

        try {
            BotChat.App({
                botConnection: botConnection,
                user: user,
                bot: { id: 'botid', name: 'bot' }
            }, document.getElementById('botDiv'));
            botConnection
                .postActivity({
                    from: user,
                    name: 'Ping',
                    type: 'event',
                    value: 'Welcome'
                })
                .subscribe(function (id) {
                 
                });
        }
        catch (e) {
            alert(e);
        }

        function chatbox() {
        }

        function updateBotUI() {            
        }
    </script>
`
[bug]

**Comment by stevkan** [comment]
@PrashantSoniHarman, can you check that your bot's app service setting has 'Always On' enabled?

![app-service-settings](https://user-images.githubusercontent.com/18403946/58278023-ea66ba00-7d4f-11e9-8c88-cdbdc267b4e3.png)

**Comment by stevkan** [comment]
@PrashantSoniHarman, please not I circled 'Web sockets', by accident. 'Always on' is located just below it.

**Comment by stevkan** [comment]
Closing as resolved. If help is still needed on this specific issue, please feel free to re-open and update with new details.
