### ISSUE TITLE
Could not send - retry for the first query after an hour bot is idle.

### ISSUE THREAD

**Issue by PrashantSoniHarman** [microsoft/botbuilder-dotnet#1938]
[bug]
[bug]
[bug]
[bug]
### Issue
Could not send - retry for the first query after an hour bot is idle.

## Version
Microsoft Bot Builder SDK 4.4.3 (C# .NetCore)

## Describe the bug
"Could not send - retry" message appears in bot window, for the first query after an hour bot is idle. Then after it works fine. It takes longer then usual if the bot is idle for a longer time.

The similar issue was there in Bot SDK 3.0, I migrated bot to 4.4.3 SDK but still issue persist.

Current Startup.cs just connects the bot with QnA maker and LUIS and does not do anything which should take more than few ms.

The bot is connected with direlinechannel and directline javascript on frontend.
`<link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js"></script>

    <script>
        var botConnection = new BotChat.DirectLine({
            token: BotAuthToken
        });

        function random_number() {
            return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
        }

        const user = {
            id: random_number(),
            name: LoggedInUserGivenName + " " + LoggedInUserSurname,
            properties: {
                'source': 'directlinewebapp',
                'user': {
                    'userDispalyName': LoggedInUserGivenName + " " + LoggedInUserSurname,
                }
            }
        };

        try {
            BotChat.App({
                botConnection: botConnection,
                user: user,
                bot: { id: 'botid', name: 'bot' }
            }, document.getElementById('botDiv'));
            botConnection
                .postActivity({
                    from: user,
                    name: 'Ping',
                    type: 'event',
                    value: 'Welcome'
                })
                .subscribe(function (id) {
                 
                });
        }
        catch (e) {
            alert(e);
        }

        function chatbox() {
        }

        function updateBotUI() {            
        }
    </script>
`

Following is the detail capture in bot telemetry

![image](https://user-images.githubusercontent.com/32177830/58238666-50aa0780-7d65-11e9-9153-63c963645864.png)
![image](https://user-images.githubusercontent.com/32177830/58238685-5bfd3300-7d65-11e9-96c0-244a0afeda33.png)

![image](https://user-images.githubusercontent.com/32177830/58238711-65869b00-7d65-11e9-81ba-d956d90723f7.png)
![image](https://user-images.githubusercontent.com/32177830/58238731-6f100300-7d65-11e9-84a8-c57af1557a75.png)

## To Reproduce
1. Leave a bot idle for an hour
2. Post a bot query on the web chat

It takes long and throws "could not send - retry"

## 
Expected behavior
Bot query anytime should give response immediately rather than taking a long time.

**Comment by mdrichardson** [comment]
Closed. Duplicate: https://github.com/microsoft/botbuilder-dotnet/issues/1937
