### ISSUE TITLE
[LG] [DCR] Support for scope based index accessor in LG

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1941]
Today:
- I cannot use scope based property accessor in LG. E.g. this is invalid
```markdown
# T1
- You have {count(user.lists.{turn.listType})} items in your list.
```
Ask is to support expression based property accessor in LG as well. We support this on dialog side but not in LG.

**Comment by boydc2014** [comment]
maybe the proper way to do this is `getProperty(user.lists, turn.listType)` instead of `user.lists.{turn.listType}` 
i mean, the latter is against my intuitive of a expression?

**Comment by boydc2014** [comment]
we should make this  user.lists[turn.listType] works
