### ISSUE TITLE
[LG] Support case agnostic if .. elseif .. else .. switch .. case labels

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1942]
We should make all labels case insensitive. Today we expect them to be all capital case.
"If : {expression}" does not work but it should. We should make 'if', 'else', 'elseif', 'switch', 'case' be case insensitive.

**Comment by boydc2014** [comment]
Just to note, we support if and IF, but not If or iF, which is the same as many programming languages. 
I'm ok with iF and If.

**Comment by feich-ms** [comment]
Fixed in both C# and JS.
