### ISSUE TITLE
[LG] Support @ prefix in single line expressions

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1943]
Today we require @ prefix to an expression when contained within a multi-line block. We should also support @{} in a single line reference as well for consistency. 

e.g. this should work - 

```markdown
# t1 (x)
- You have @{count(x)} items in your collection.
```

**Comment by boydc2014** [comment]
@vishwacsena  do we drop just {} ? and only keep @{}
