### ISSUE TITLE
Update to latest version of Recognizer Packages

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#1945]
Update to the lastest version.

**Comment by garypretty** [comment]
PR #1964 updates recognizer packages to latest (v1.2) with unit tests that were previously failing now passing.

**Comment by johnataylor** [comment]
Also need to verify this https://github.com/microsoft/botbuilder-dotnet/issues/1622

**Comment by johnataylor** [comment]
We have a tracking issue from LUIS https://github.com/microsoft/botframework-sdk/issues/5378

**Comment by johnataylor** [comment]
Closing this issue and keeping the project wide issue in botframework-sdk
