### ISSUE TITLE
Make DialogContext public and DelegatingTurnContext protected member of ActivityHandler 

### ISSUE THREAD

**Issue by DavidVollmers** [microsoft/botbuilder-dotnet#1960]
**Describe the solution you'd like**
Make the internal constructor of DialogContext public. I understand that an internal constructor prevents misuse of the class. But as a library designer it limits you in building generic dialog classes which need to extend and manage the dialog context on their own (like WaterfallDialog using WaterfallStepContext).

**Describe alternatives you've considered**
An abstract inheritor of the class. But that's bad design in my opinion.

[enhancement]

**Comment by lischach** [comment]
Hi,

I also faced this issue where a public constructor could have helped me. I solved it by implementing the same methods and delegating to a private DialogContext field, but if the constructor was public, I wouldn't have to go through this overhead.

**Comment by johnataylor** [comment]
Making DialogContext public and DelegatingTurnContext protected member of ActivityHandler makes for improved extensibility especially with respect to inheritance.

This is C# specific.

**Comment by DavidVollmers** [comment]
I am unsure what the ActivityHandler has to do with my original issue. Can you explain that further?

**Comment by johnataylor** [comment]
It doesn't, I just lumped the issues together under a common theme of "make stuff public" and did them at the same time. This is just me not bothering to open a new separate issue.

Sorry for the confusion!

**Comment by johnataylor** [comment]
This should be in 4.5
