### ISSUE TITLE
[Adaptive] Rationalize names for built in memory properties

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-dotnet#1966]
Need to align on usage of memory for different properties and objects used in the SDK like entities.

**Comment by vishwacsena** [comment]
## turn Standard Properties 
- **turn.activity** - current activity (no change) (AdaptiveDialog only)
- **turn.recognized**  - current result of IRecognizer
    - intents
    - entities 
- **turn.stepcount** - number of executed steps (AdaptiveDialog only)
dialog Standard properties
     - **dialog**
        - **options** - the options object which is used to initialize the dialog.  NOTE: This is blend of declarative dialog properties and options set when invoking.  This allows you to data bind to configured values like MaxValue via dialog.this.options.maxValue.
        - **this** - (**NEW**) for container dialogs where child dialogs share the state (like Adaptive dialog's and steps) the this property is standard property for internal dialog book keeping
           - **step** - (**NEW**) active step property bag

## Memory Shortcuts
- $ for slot shortcut (no change)
        - $xxxx -> dialog.xxxx
- \# for intent shortcut (no change)
        - #xxxx -> turn.recognized.intents.xxxx
- @ for entity shortcut (no change)
        - @xxxx -> turn.recognized.entities.xxxx 
- ^ for options shortcut (**NEW**) - this makes it easy to databind to configured options, aka, "The maximum age we accept is {^maxValue}" <-- data bind to configured maxValue option
        - ^xxxx -> dialog.this.step.options.xxxx || dialog.this.options.xxxx 

## Data Binding
Data binding is the process of configuring the data from the memory context of the caller to the memory context of a dialog.  We spent a fair amount of time digging into this and the net result is the following recommendations.
 
There are several patterns of calling a dialog (aka function):
- 1..N input or argument bindings (aka, properties which are memory from the caller that get mapped into memory of the target)
- 1 output or result binding (aka, where the result of calling the dialog
- 2 way bindings (object is passed in and result is set as the result)

Our guidance around this is:
- Input properties should be expressed as properties which are a a string which is evaluated as an expression (either const or path to value)  (**CHANGE**)
- If there is not a 2 way binding then the result property should be called ResultProperty and expressed as a string which is evaluated as a property path (**CHANGE**)
- If there is a 2 way bindings it should also be called XXXXProperty expressed as a string which is evaluated as a property path(**CHANGE**)
Our input dialogs are about 2 way data binding to a value, and so we should standardize on the name ValueProperty 
 
Example:
```jsonc
{ 
   "$type":"Microsoft.NumberProperty",
   "minValue":"13",
   "maxValue":"{dialog.parentAge}", // data binding maxValue to caller's value of dialog.parentAge
   "valueProperty":"dialog.age";  // two-way property binding
}
```
 
The base dialog has support for data bindings, but we should change the name to reflect their role and also that they should not be probably used unless you know what they are for.  To that end we should
- Rename InputProperties and OutputProperty -> InputBindings and OutputBindings.  (**CHANGE**)
- Best practice is to not expose InputBindings and OutputBindings in our json schema, but instead have user friendly properties which get mapped to Input/OutputBindings internally.

**Comment by carlosscastro** [comment]
@tomlm and @Stevenic where are we on this?

**Comment by carlosscastro** [comment]
Just want to check if help is needed or capture what bits are missing
