### ISSUE TITLE
[Adaptive] [DCR] Fix SwitchCondition step so case values do not have to be enclosed in ''

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1975]
C# implementation of SwitchCondition step requires the value property on each case to be wrapped in ''. Most users are not going to remember to do this and we do not have any validations to suggest that they need to do this and the condition just fails silently. 

Could we update the value to always be a string and automatically wrap with '' so expression evaluation goes through correctly? 

```jsonc
{
            "$type": "Microsoft.SwitchCondition",
            "condition": "dialog.listType",
            "cases": [
                {
                    "value": "todo", // today we expect value to be explicitly wrapped like 'todo'
                    "steps": [
                    ...
                    ]
                 }
}
```

**Comment by boydc2014** [comment]
@vishwacsena I'm wondering what we are assuming this value to be? do we only support string as @chrimc62  suggested in the Teams channel? or we want a full power like

value: 21 // int
value: "21" // string
value: "string" // string
value: "{input.age}" // expression

**Comment by vishwacsena** [comment]
I believe we should start with value being string literals. We can expand on that to support types based on customer feedback/ usage scenarios.
