### ISSUE TITLE
[Adaptive] [DCR] Add '^' shorthand support

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1981]
Depends on #1980 

^ for options shortcut (**NEW**) - this makes it easy to databind to configured options, aka, "The maximum age we accept is {^maxValue}" <-- data bind to configured maxValue option
        - ^xxxx -> dialog.this.step.options.xxxx || dialog.this.options.xxxx

**Comment by boydc2014** [comment]
close as dup #1966
