### ISSUE TITLE
HttpHelper shouldn't try to serialize a null invokeresponse body

### ISSUE THREAD

**Issue by mingweiw** [microsoft/botbuilder-dotnet#1982]
## Version
4.4.3

## Describe the bug
When an invokeresponse has a null body, we are adding a ContentType header to the response plus "null" in the response body.

## Expected behavior
Don't add the ContentType header and leave the body empty.

## Additional context
Fix for aspnet.core is in this [PR](https://github.com/microsoft/botbuilder-dotnet/pull/1979/files)

**Comment by johnataylor** [comment]
fixed in 4.4.5 and in master
