### ISSUE TITLE
[Adaptive] Not able send base 64 image in adaptive dialog

### ISSUE THREAD

**Issue by vidya091209** [microsoft/botbuilder-dotnet#1989]
## Version
4.5* latest Preview version

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce

want to send a base64 image in Adaptive Dialog.
Tried using  AdaptiveCards.AdaptiveImage but it says Url is to bix in exception.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vidya091209** [comment]
@sgellock  thanks let me know if there is any work around.

**Comment by vishwacsena** [comment]
@vidya091209 can you please clarify how you need to/ trying to send base64 image? By in lining the image in a card attachment or do you need to send this directly via the SendActivity step or something else?

**Comment by vidya091209** [comment]
var img = new AdaptiveCards.AdaptiveImage(i.message)
                            {
                                Type = i.message.Split(";")[0].Substring(5)
                            };
                            dialog.Steps.Add(img);
                      
I am trying this, i think we  can not use send activity for image. i am open to any idea.

**Comment by CoHealer** [comment]
@v-kydela, please investigate.

**Comment by v-kydela** [comment]
@vidya091209 - In order to determine if this is related to adaptive dialogs, can you successfully send the base64 image outside of an adaptive dialog?

**Comment by vidya091209** [comment]
@v-kydela  yes i am able to send it outside the adaptive dialog.

**Comment by v-kydela** [comment]
@vidya091209 - Adaptive Cards are unrelated to adaptive dialogs, so naturally an adaptive image is not a valid adaptive dialog step. You can see all the types of steps available to you in the steps folder. What specific branch have you pulled in order to use adaptive dialogs?

**Comment by vidya091209** [comment]
@v-kydela I simply wanted to send a base64 image as step in adaptive dialog. i am using 4.Future branch.

**Comment by sgellock** [comment]
@v-kydela I'm moving this over to the Adaptive team to address.  Thanks for the initial help, but I'd like them to address the issue.

@tomlm @carlosscastro we should decide if we can get this fixed before the next train leaves.

**Comment by tomlm** [comment]
You need to use a **SendActivity(activity) step.  That takes a **Activity** object which can have attachments.

If all you are trying to do is send an image as an activity then it would be something like this:
```csharp
var activity = dc.TurnContext.Activity.CreateReply();
activity.Attachments.Add(new Attachment(contentType:"image/jpg", contentUrl:"base64:..."));
// this uses new CTOR that takes a raw activity, you need latest bits for this
dlg.Steps.Add(new SendActivity(activity));

// alternatively, you use a staticActivityTemplate() 
dlg.Steps.Add(new SendActivity() {  Activity = new StaticActivityTemplate(activity)});
```
If you are truly trying to send an **AdaptiveCard**, then you need to do the same thing but add an attachment with adaptive card that has an AdaptiveImage inside that.

**Comment by vidya091209** [comment]
Thanks a lot it worked.
