### ISSUE TITLE
[LG] Line number in error message is wrong when format is not correct

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#1996]
## Version
Adaptive

## Describe the bug
When adding round brackets for parameters at the end of the template(#), we should see the correct line number where the illegal behavior happens. However, the line number of the error message is incorrect. The current error message is "Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught : [ERROR]: syntax error at line 92:30 missing IDENTIFIER at ')'", which is inaccurate.

## To Reproduce
1. Add "()" after "# CreateCalendarEntryReadBack" in file "CreateCalendarEntry.lg" at line 76
2. Open the "calendar-bot-cui" project and run it
3. Open the "Bot Framework Emulator (V4)" and open your bot
4. Say "hi" in "Bot Framework Emulator (V4)" to your bot
5. Open Debug of Output in Visual Studio to see the error message

## Expected behavior
The error message should be "Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught : [ERROR]: syntax error at line 76 in CreateCalendarEntry.lg for adding redundant IDENTIFIER at ')'"

## Screenshots
![image](https://user-images.githubusercontent.com/32658030/58869913-bbf2c280-86f1-11e9-8586-3498a0dc072e.png)

**Comment by boydc2014** [comment]
The bug is related to how TemplateEngine is used today in dialog, i believe the current behavior is just merge all files as one lg file. A correct fix is to 
1. use one TemplateEngine then add multiple files (with the built-in support of multiple files in TemplateEngine). 
2. list the filename in error message

**Comment by boydc2014** [comment]
https://github.com/ZhaoqingCui/BotBuilder-Samples/tree/TestAdaptive/experimental/adaptive-dialog/csharp_dotnetcore/calendar-bot-cui 

this is code to repro @Danieladu

**Comment by vishwacsena** [comment]
@boydc2014 - is your recommendation that we should update the samples to reflect adding files explicitly? 

With the new generator change, [this is how the code would look like](https://github.com/microsoft/botbuilder-dotnet/blob/b11fddfaa8b693cbc776ee0e82b0e36035543843/samples/Code-Todo-Bot/Dialogs/AddToDoDialog/AddToDoDialog.cs#L22). Is this inline with what you are recommending above? 

If so, we should just close this issue. We will anyways have to update all our samples to reflect this pattern for the new adaptive dialog with the generator baked in.
