### ISSUE TITLE
MessageFactory Suggested Messages creates empty Text bubble

### ISSUE THREAD

**Issue by starlord-daniel** [Microsoft/botbuilder-dotnet#200]
I wrote this code to print out a message followed by suggested actions: 

`context.Reply("Get the best food here! I mean best cafeteria food... Ok let's say it's eatable. You can do the following: 'Order food', 'Add Allergies'");

            // Create the activity and add suggested actions.
            var suggestedTopics = MessageFactory.SuggestedActions(
                new CardAction[] {
                    new CardAction(type: "imBack", text: "add allergy", title: "add allergy"),
                    new CardAction(type: "imBack", text: "order food", title: "order food"),
                    new CardAction(type: "imBack", text: "help", title: "help")
                }
            );

            // Send the activity as a reply to the user.
            context.Reply(suggestedTopics);
`

As a result, I get the following response: 

![grafik](https://user-images.githubusercontent.com/24311612/36730783-ed8a88a4-1bc8-11e8-877d-0a0087e67591.png)

**Comment by anastasiia-zolochevska** [comment]
The partner I am working with faced the same issue.
The workaround we are using is to add title (which I'm not sure if documented) :
var activity = MessageFactory.SuggestedActions(new CardAction[] {
                        new CardAction(type: "imBack", text: "red", title: "red")
                  }, "Select color");

But ideally we don't want to be forced to add any title at all.

**Comment by garypretty** [comment]
@cleemullins I'll take a look at this later and see if I can see what's happening. If I can then I'll submit a fix.

**Comment by Stevenic** [comment]
@garypretty it's likely that we're always including an empty string for the text of the message when sending suggested actions. I believe you need to not include a text field at all if you just want the actions to show up without an associated message.

**Comment by garypretty** [comment]
Yes, that would be my suspicion. I’ll hopefully get a chance to take a look later.

Gary

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Stevenic** [comment]
I was looking at the code and the issue is this line [here](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Core/MessageFactory.cs#L235). We shouldn't be assigning an empty string for either this or the line below it.  We need those fields to not be filled in if they're not specified.
