### ISSUE TITLE
[Adaptive Dialog] Options are passed as object, but get as json

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2000]
## Version
Adaptive

## Describe the bug
Using BeginDialog() and pass with object as dialog option in adaptive dialog, but get the dialog option as jobject instead of strong typed object.

## To Reproduce
// Set
var skillOptions = new EmailSkillDialogOptions();
Rules = new List<IRule>()
{
                    new IntentRule("CheckMessages")
                    {
                        Steps = new List<IDialog>() { new BeginDialog(nameof(ShowEmailDialog), options: skillOptions) },
                    },
….
            
// Get
protected override async Task<DialogTurnResult> OnBeginDialogAsync(DialogContext dc, object options, CancellationToken cancellationToken = default(CancellationToken))
{
            var skillOptions = ((JObject)options).ToObject<EmailSkillDialogOptions>(); //! Expect: get object instead of Jobject

## Expected behavior
Get dialog options as object instead of json, similar with other dialog.

**Comment by vishwacsena** [comment]
#2012 will bear an impact on this issue as well.

**Comment by tomlm** [comment]
you need to do (JObject)options).ToObject<**SkillOptions**>();
