### ISSUE TITLE
"How heavy is the moon" causes an exception in out-of-the-box VA bot

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botbuilder-dotnet#2001]
## Project

**Name**: Virtual Assistant

**Language**: C#

## Description
When I ask a newly created Virtual Assistant "How heavy is the moon" it causes a exception to be thrown at line 144 of MainDialog.cs (see screen capture below).  The issue appears to be the fact that the utterance was directed to the FAQ KB and the fact that the default KB content does not have a match for that utterance.  If you ask a question that is in the KB it works fine.   

## To Reproduce
1) Open Visual Studio 2019 and turn on Exceptions Setting (Debug | Windows | Exception Settings) for C++ Exceptions and Common Language Runtime Exceptions
2) Follow directions to create a standard VA bot found [here](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/virtualassistant.md) 
3) With bot running in the VS 2019 debugger, use the bot emulator to ask "How heavy is the moon" and you should see an exception at line 144 of MainDialog.cs

## Expected behavior
No exception

## Screenshots
![image](https://user-images.githubusercontent.com/17769186/58895821-d19cc380-86c2-11e9-9ef9-37e26f2df9aa.png)

**Comment by darrenj** [comment]
I could repo, but now can't. Can you try again, could have been a transient live issue?

**Comment by darrenj** [comment]
Here was the stack trace:

t System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\r\n at Microsoft.Bot.Builder.AI.QnA.QnAMaker.FillQnAEventAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.AI.QnA.QnAMaker.OnQnaResultsAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.AI.QnA.QnAMaker.GetAnswersAsync(ITurnContext turnContext, QnAMakerOptions options, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)\r\n at djvademostart.Dialogs.MainDialog.RouteAsync(DialogContext dc, CancellationToken cancellationToken) in C:\\Users\\darrenj\\source\\repos\\demo\\djvademostart\\djvademostart\\Dialogs\\MainDialog.cs:line 166\r\n at Microsoft.Bot.Builder.Solutions.Dialogs.RouterDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)\r\n at djvademostart.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\\Users\\darrenj\\source\\repos\\demo\\djvademostart\\djvademostart\\Bots\\DialogBot.cs:line 43\r\n at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)\r\n at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)",

**Comment by managedcoder** [comment]
Is this what you are looking for?  This happens every time for me.  Here is the exception info:

System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: question
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.FillQnAEventAsync(QueryResult[] queryResults, ITurnContext turnContext, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.<OnQnaResultsAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.<GetAnswersAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyAssistantRHW.Dialogs.MainDialog.<RouteAsync>d__6.MoveNext() in C:\Source\MyAssistantRHW\MyAssistantRHW\MyAssistantRHW\Dialogs\MainDialog.cs:line 144

**Comment by garypretty** [comment]
I believe this is likely related to a known issue with telemetry and QnA, when a question is not matched.  PR is open to resolve. https://github.com/microsoft/botbuilder-dotnet/pull/1899

**Comment by managedcoder** [comment]
An update here to help expedite things... I saw that #1899 was merged to master 14 days ago so I assumed it would be part of the daily build (MyGet) and so I just tried #1899 to test what @garypretty thought might be the fix to this issue and I still get the same error.  So it would appear in the case I describe here that #1899 does not fix #2001.  The version I tied was: **4.5.0-preview-190620-1**

**Comment by gabog** [comment]
@darrenj, @lauren-mills & @managedcoder can you point me to the QnA KB that has the How Heavy is the Moon question? There's probably an issue with the framework code but I need the KB to be able to repro without having the deploy the entire VA.
Thanks

**Comment by lauren-mills** [comment]
@gabog There isn't a kb with that question. The Dispatch model thinks it should go to qna, but there isn't a match in the kb. You can use the models from the VA Template to repro.

**Comment by gabog** [comment]
k, thanks lauren, I'll try to repro outside VA and will report back to the thread.

**Comment by gabog** [comment]
This issue seems to have been fixed in 4.5 (I'm not sure what PR addresses the issue though).

I was able to repro the issue against 4.4.5 by using the following code:

    public async Task TestBug()
    {
        var qnaEndpoint = new QnAMakerEndpoint()
        {
            KnowledgeBaseId = "MyKBID",
            EndpointKey = "MyKBKey",
            Host = "https://myQnAHost-qnahost.azurewebsites.net/qnamaker",
        };
        var telemetryClient = new BotTelemetryClient(new TelemetryClient());

        var qnaMaker = new QnAMaker(qnaEndpoint, null, null, telemetryClient: telemetryClient, logPersonalInformation: true);

        var reply = await qnaMaker.GetAnswersAsync(BuildContext("how heavy is the moon"), null, null);
        reply = await qnaMaker.GetAnswersAsync(BuildContext("how heavy is the moon"), null, null);
    }

But I tried the same code against the master version of BotBuilder and couldn't repro. 

To double check, I also updated the VA Solution created from the template to point to the daily build in my get (4.5.0-preview-190628-2) and the issue doesn't repro there either.

![image](https://user-images.githubusercontent.com/12264946/60454957-39cbc000-9c03-11e9-8139-d34a68bd9646.png)
