### ISSUE TITLE
Suggested Actions don't im-ing back (Card Action's type is "imBack")

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-dotnet#201]
Tested in Emulator. The code copy-pasted from documentation and it doesn't put selected action to the conversation:

// Create the activity and add suggested actions.
var activity = MessageFactory.SuggestedActions(new CardAction[] {
    new CardAction(type: "imBack", text: "red", title: "red"),
    new CardAction(type: "imBack", text: "green", title: "green"),
    new CardAction(type: "imBack", text: "blue", title: "blue")
});

// Send the activity as a reply to the user.
context.Reply(activity);

**Comment by Stevenic** [comment]
You're not seeing the actions at all? That looks correct

**Comment by cleemullins** [comment]
I've test this code:
```
        protected override async Task OnReceiveActivity(IBotContext context)
        {

            if (context.Request.Type == ActivityTypes.Message)
            {
                if (context.Request.AsMessageActivity().Text == "foo")
                {
                    var activity = MessageFactory.SuggestedActions(new CardAction[] {
                        new CardAction(type: "imBack", text: "red", title: "red"),
                        new CardAction(type: "imBack", text: "green", title: "green"),
                        new CardAction(type: "imBack", text: "blue", title: "blue")
                        });
                    context.Reply(activity);
                }
            }

            return;
```

I get back this. 
![image](https://user-images.githubusercontent.com/1165321/36761149-a271f5dc-1bd2-11e8-9d85-e429a1beb459.png)

Now, the annoying little square is still there, but the Card Actions are properly showing up.

**Comment by cleemullins** [comment]
Note: I confirmed that ACtivity sent is correct and that this is a WebChat bug. The work-around is to send text, which is then rendered: 
```
  var activity = MessageFactory.SuggestedActions(new CardAction[] {
                        new CardAction(type: "imBack", text: "red", title: "red"),
                        new CardAction(type: "imBack", text: "green", title: "green"),
                        new CardAction(type: "imBack", text: "blue", title: "blue")
                        }, "test test test")
```

**Comment by anastasiia-zolochevska** [comment]
@cleemullins your work around doesn't work for me (sending text).

I am not saying that Card Actions are not properly showing up, I am saying that clicking on action doesn't do anything ( it doesn't put action that was selected to conversation).  And I think that the issue should still be open.

The workaround I found is to specify value (instead of text):

var activity = MessageFactory.SuggestedActions(new CardAction[] {
                        new CardAction(type: "imBack", text: "red", title: "red", value:"red"),
                        new CardAction(type: "imBack", text: "green", title: "green", value:"green"),
                        new CardAction(type: "imBack", text: "blue", title: "blue", value:"blue")
                        }, "test test test");

                    // Send the activity as a reply to the user.
                    context.Reply(activity);
