### ISSUE TITLE
[Adaptive][DCR] Changes to BeginDialog, ReplaceDialog, and RepeatDialog steps

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2012]
Here's my proposed set of changes to the BeginDialog, ReplaceDialog, and RepeatDialog steps

# BeginDialog
We need to update this step to give creators and easy way of expressing the options they'd like passed to a dialog that's being called.  Here are a list of property changes which I think help achieve that:

- `dialogId:` This property should change from a string to an expression. That will make it easy to start a dialog who's id needs to be computed.
- `options:` This property should change from a JSON object to an array of name+expression pairs.  This will let creators specify a list of named options that should be passed into the dialog being called.
- `resultProperty:`  This new property would let creators specify where they would like the output of the dialog being called to be written to.
- `valueProperty:` This would continue to be a shortcut for defining a two-way binding between a dialog and a value in memory. The incoming value would be passed in as an option named "value" and the output of the dialog would be written over the source value.

# ReplaceDialog

- `dialogId:` This property should change from a string to an expression. That will make it easy to replace the current dialog with  a dialog who's id needs to be computed.
- `options:` This property should change from a JSON object to an array of name+expression pairs.  This will let creators specify a list of named options that should be passed into the dialog being started.

# RepeatDialog

- `options:` This property should change from a JSON object to an array of name+expression pairs.  This will let creators specify a list of named options that should be passed into the dialog being started.
 
[enhancement]

**Comment by vishwacsena** [comment]
@carlosscastro was this included in the schema rev? If not, I'd vote that we take this for 4.6 and not in 4.5.

**Comment by carlosscastro** [comment]
@vishwacsena This iwas not included. We did not handshake on when we'd include it. I vote this can wait, despite being very important.

**Comment by vishwacsena** [comment]
Related to and should be cleaned up/ consolidated as part of memory property cleanup DCR
