### ISSUE TITLE
[Adaptive][DCR] Updates to EditArray step

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2016]
On the JavaScript side of things I've made a few updates to the `EditArray` step which should be applied to the C# side of things.

The main thing I did was make it so that you can now pass an expression for the value you want to either `push` onto or `remove` from an array.  This resulted in a few other property changes needing to be made:

- `value:` this new property is an expression specifying the value you'd like to push onto or remove from an array.
- `itemProperty:` this was removed is it's replaced by `value`.
- `resultProperty:` since expressions can't be used for assignment I had to add a new resultProperty field to let you specify where you'd like the result placed from a `pop`, `take`, or `clear` operation.  If this field is empty then the result is discarded.
 
[enhancement]

**Comment by vishwacsena** [comment]
We should take this change for 4.5 and prioritize schema updates first. Marking as P0 for possible impact due to schema changes.

**Comment by carlosscastro** [comment]
Fixed in #1995

**Comment by vishwacsena** [comment]
@carlosscastro, #1995 appears to be related to EditSteps step and not EditArray step. This issue is tracking work to EditArray step.

**Comment by carlosscastro** [comment]
My bad, yes, confused the steps.
