### ISSUE TITLE
LuisRecognizer doesn't return text in composite entity when child is not recognized

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/botbuilder-dotnet#2024]
Example prediction:
https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/f292bd26-91a9-4d33-b83b-15010fd7aaac?verbose=true&timezoneOffset=-360&subscription-key=4db5bf288edd4945822aeb124c59d8a5&q=travel%20from%20seattle%20to%20miami

In the response, compositeEntities has "From" and "To" detected, but there is no child entities detected (ie Airport, which is a closed list).  With this query, RecognizerResult.Entities has From and To elements but both are empty.  It shouldn't have been empty as "To" and "From" are detected.

The code in core bot sample fails getting Origin and Destination as a result (from https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot):

if (intent == "Book_flight")
                {
                    // We need to get the result from the LUIS JSON which at every level returns an array.
                    bookingDetails.Destination = recognizerResult.Entities["To"]?.FirstOrDefault()?["Airport"]?.FirstOrDefault()?.FirstOrDefault()?.ToString();
                    bookingDetails.Origin = recognizerResult.Entities["From"]?.FirstOrDefault()?["Airport"]?.FirstOrDefault()?.FirstOrDefault()?.ToString();

**Comment by johnataylor** [comment]
The structure is a little cryptic however the information is there and the application can read it.

Specifically LUIS (and therefore after some remapping) the LuisRecognizer hands the client the composite but the closed list child is missing. This means the composite matched (in a similar manner to the intent matching) but the entity didn't. The actual match text is available in the $instance metadata.

We should fix the sample code. Specifically see...

https://github.com/microsoft/BotBuilder-Samples/blob/corebot-updates/samples/csharp_dotnetcore/13.core-bot/LuisHelper.cs
