### ISSUE TITLE
If CreateReply is deprecated, please mark it as such

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#2025]
## Version
What package version of the SDK are you using: current master branch.

## Describe the bug
In #264, it is claimed that `CreateReply` was deprecated, and that people should now be using `SendActivity`. Please add an `ObsoleteAttribute` to the method to make this clear.

## To Reproduce
1. Look at the current v4.4 15.handling-attachments sample.
1. Look in Bots\AttachmentsBot.cs, [ProcessActivity](https://github.com/microsoft/BotBuilder-Samples/blob/84e3c1622a272e99e1e1bf04bbf9268d5404cf8b/samples/csharp_dotnetcore/15.handling-attachments/Bots/AttachmentsBot.cs#L82-L100).
1. See error: even developers on our own team are confused about this.

## Expected behavior
Any member that is officially deprecated should get labeled as such, to avoid this sort of confusion. Also, the samples should not use deprecated members.

## Additional context
The only reason I noticed is that it is causing confusion with our users (becasue the doc team is quoting from the samples). re: bot-docs issue [1188](https://github.com/MicrosoftDocs/bot-docs/issues/1188).

[bug]

**Comment by v-kydela** [comment]
Why would `CreateReply` be deprecated? What's replacing it?

While it's true that `SendActivity` does automatically handle the `From` and `Recipient` properties, what if they want to use `IConversations.SendToConversationAsync`? `CreateReply` is still necessary in that case.

If the solution is to use `MessageFactory`, that doesn't provide the same functionality as `CreateReply`. If they want to deprecate `CreateReply` in favor of `MessageFactory` then surely they should give `MessageFactory` equivalent functionality.

**Comment by EricDahlvang** [comment]
I'm also confused about this.  The CreateReply method is in [ActivityEx](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityEx.cs#L160) which also contains many other methods which are not present in the JavaScript sdk.  Are we deprecating all of these methods?

Due to the utility of these helper methods, it seems odd to remove them.  I would like to suggest that we leave CreateReply in the dotnet sdk, but not refer to it in the documentation or samples.  Is this an acceptable solution? @cleemullins

**Comment by v-kydela** [comment]
Surely `CreateReply` would be just as useful in the JavaScript SDK. Why not add it in for parity?

**Comment by EricDahlvang** [comment]
As discussed in standup, we are leaving CreateReply in the dotnet sdk but removing it from the samples and docs.  Closing this issue, since there is different issue in the Samples repo tracking the samples changes: https://github.com/microsoft/BotBuilder-Samples/issues/1559
