### ISSUE TITLE
Microsoft.Bot.Builder.AI.QnA GetAnswersAsync issue

### ISSUE THREAD

**Issue by vikasgoyal** [microsoft/botbuilder-dotnet#2029]
I am trying to use following library to build a basic QnABot. Microsoft.Bot.Builder.AI.QnA (v 4.4.4) . The GetAnswersAsync method returns response only if question is avaibale within Q part of QnA in KB else zero count for results. Effectively with "RankerType":"QuestionOnly".

The same query works fine through QnA Portal test console or REST APIs using curl.

[bug]

**Comment by Zerryth** [comment]
@vikasgoyal the `RankerType` property that you can send through when making a request to QnA Maker is a newer feature of the API, and has not been incorporated into the SDK (yet). In fact, your issue that you opened is the fist time that I myself have heard of it, and had to verify its newness with @diberry , senior content writer for LUIS/QnAMaker!

That being said, with how the SDK is set up currently, **you can actually still get the responses** that the QnA Maker API returns when `RankerType:QuestionOnly` is not specified (and therefore defaults to searching both answers and questions in the KB, not just questions only).
* You're saying that when you query QnA Maker directly, your bot returns responses, even if the question is not in the KB
* and that when using a bot that calls the QnA API, the bot does not send the responses

What that tells me is, is that the `ScoreThreshold` for such situations are low--the QnAMaker API is not super confident that the response that it is returning to you is the correct prediction.
* the BF SDK by default does not return a response if the `Score` of an answer is lower than `0.3F`.
* **Change the default `ScoreThreshold` in the `QnAMakerOptions` that you send with the bot, to receive the answer that QnA API returns, even if the `Score` is less than `0.3F`**

**Comment by Zerryth** [comment]
Some examples illustrating:

In my KB I created Question: "milk" and Answer: "cow". It does not have any metadata associated with it.

_Query in Postman with StrictFilters on metadata that the Q&A pair does not have_
![image](https://user-images.githubusercontent.com/35248895/59217770-8c214000-8b73-11e9-8ec7-e27fb818503c.png)
Notice above that Postman's query to QnA API returns `"No good match found in KB"` directly

_Query in Postman with no StrictFilters, but question is "cow" when only an answer in the KB actually contains the word "cow"--no questions do_
![image](https://user-images.githubusercontent.com/35248895/59217877-c8ed3700-8b73-11e9-8a78-32d4ede16d93.png)
Notice above that Postman's query to QnA API does return an answer, but it's score is less than 30.0

So if I leave Sample 11.qnamaker as is, it has the default `ScoreThreshold` of `0.3F`, it the bot will not return the answer:
![image](https://user-images.githubusercontent.com/35248895/59217956-f76b1200-8b73-11e9-8fde-88783c83e2a2.png)


But changing `QnAMakerOptions` to accept a lower `ScoreThreshold` will allow the answer to be returned in the bot:
![image](https://user-images.githubusercontent.com/35248895/59218057-2da89180-8b74-11e9-9f6e-6dcc1e4379e7.png)

![image](https://user-images.githubusercontent.com/35248895/59218098-4022cb00-8b74-11e9-9728-07c7f3028415.png)

**Comment by Zerryth** [comment]
One last comment, I will discuss offline with the BF Team how we can better coordinate with the Cognitive Services team, as admittedly it seems that we discover that they've updated and implemented a new feature only when it pops up as a bug in the BF SDK, since the SDK still remains the same

**Comment by vikasgoyal** [comment]
Thanks Ashley. Lowering Threshold worked.
