### ISSUE TITLE
Activity.cs needs to be updated

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#2039]
## Version
Master branch

## Describe the bug
The documentation comments in [Activity.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/Activity.cs) are full of typos and need to be thoroughly edited. For example:

```c#
        /// <summary>
        /// Gets or sets contains an ID that uniquely identifies the activity
        /// on the channel.
        /// </summary>
```

I cannot submit a pull request because the file is auto-generated:

```c#
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
```

It's possible that these typos have already been corrected in whatever source Activity.cs is being generated from, in which case the file should be refreshed.

## Additional context
I suspect the typos were caused by copy-pasting.

[bug]

**Comment by cleemullins** [comment]
This class is no longer auto-generated. From 4.5 forward we are HAND EDITING the class. 

At this point I would suggest you make the changes.

**Comment by EricDahlvang** [comment]
Some of these typos are also present in the swagger file on botframework-sdk, as well as botbuilder-js and botbuilder-python.
