### ISSUE TITLE
[Adaptive] [LG] [DCR] support external LG references/ import in .lg format

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2043]
This DCR introduces ability to import external LG resource in the .lg file format, in the LG library as well as in the declarative type loader. 

## File format
Reference to external content is specified via markdown link syntax. ```[link-text](link-source)```

Where
- ```link-text``` is arbitrary text user uses to identify the specific external LG resource
- ```link-source``` can be one of - 
    1. relative path to another .lg file
    2. Name of external resource to be resolved via a lambda
    3. URI to .lg file

**Note:** path based resolution (relative) only work when the LG files are loaded via ```TemplateEngine.FromFiles``` method. 

Here are some examples - 
```markdown
> here is an example of relative path based external LG resource 
[import global templates](../../global.lg)

> here is an example of a named import the content of which are provided by a delegate
[import global templates](global)

> here is an example of URI based LG resource
[import global templates](http://contoso.com/resources/lg/global.lg)
```

Updates to TemplateEngine: 
- ```FromFiles``` and ```FromText``` methods will now accept a delegate that lists external unresolved references found in loaded lg content. delegate returns ```Text``` for each unresolved reference.

TemplateEngine should: 
1. In case of a path based resource, find and use any known LG files added via FromFiles and if resource is not found, call the delegate if specified or throw.
2. In case of URI based resource, navigate to and load resource from URI and if resource not found, call the delegate if specified or throw. 
3. In case of named import, simply call the delegate if specified or throw. 

Template Engine will also throw if the expected resource cannot be resolved.

Related work on Type loader: 
- Implement delegate on all TemplateEngine.FromFiles call.

**Comment by boydc2014** [comment]
1. Priority
2. Interface

**Comment by boydc2014** [comment]
This is supported now, with some followup. i will create another DCR to track
