### ISSUE TITLE
System.ArgumentNullException has been thrown "Value cannot be null.\nParameter name: options"

### ISSUE THREAD

**Issue by AskYous** [microsoft/botbuilder-dotnet#2058]
## Version
4.4.4

## Describe the bug
When I call `dialogContext.BeginDialogAsync("sign-in")`, it errors saying parameters can't be null. I clearly provided parameters and the documentation shows this function being called without additional parameters anyways. All that's needed is the first parameter. I've been stuck on this for hours and don't know where to begin debugging because this error message is not true. See screenshot below.

## To Reproduce
1. `var dc = await this.dialogs.CreateContextAsync(turnContext, cancellationToken);`
2. `await dc.BeginDialogAsync("sign-in", new object(), cancellationToken);`
3. Run bot.
4. See error.

## Expected behavior
No error, or an accurate error message.

## Screenshots

![image](https://user-images.githubusercontent.com/791996/59370212-e5fe4300-8cf6-11e9-88ad-28f81d89fe1a.png)

## Additional context
I ran this in VS for Mac and VS Code and received the same results. It was working before. I did some code refactoring and now it breaks, but I don't remember what changes I made. Regardless, the error message is still wrong. I've also opened an issue in StackOverflow [here](https://stackoverflow.com/questions/56553043/dc-begindialogasync-value-cannot-be-null-nparameter-name-options) hoping to get a response soon as I've been stuck on this for a while now.

## Code snippet

```CS
public FlexoBot(ConversationState conversationState)
{
    this.dialogState = conversationState.CreateProperty<DialogState>("dialog-state");
    this.dialogs = new DialogSet(this.dialogState);

    // Make oauth card available to use for all handlers
    this.dialogs.Add(new OAuthPrompt("oauth", new OAuthPromptSettings() { 
        ConnectionName = "flexo-auth", 
        Title = "Please sign in." 
    }));

    dialogs.Add(new WaterfallDialog("sign-in", new WaterfallStep[] {
        PromptSignIn,
        GreetUser,
    }));
}

protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
{
    foreach (var member in membersAdded)
    {
        if (member.Id != turnContext.Activity.Recipient.Id)
        {
            var dc = await this.dialogs.CreateContextAsync(turnContext, cancellationToken);
            await dc.BeginDialogAsync("sign-in", new object(), cancellationToken);
            // Throws: System.ArgumentNullException has been thrown "Value cannot be null.\nParameter name: options"
        }
    }
}
```

[bug]

**Comment by AskYous** [comment]
I finally figured it out. It's because I was calling return step.PromptAsync("oauth", null); in one of my waterfall steps. I changed it to:

    return step.PromptAsync("oauth", new PromptOptions { });

And it works now. The error message completely tricked me. I hope there will be a fix for this misleading error message.

**Comment by cleemullins** [comment]
The existing code in [PromptAsync](https://github.com/microsoft/botbuilder-dotnet/blob/c142dc3c7a5b7c114afd27d0ab845d59370e705e/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L125) seems correct to me. The code is

```cs
        public async Task<DialogTurnResult> PromptAsync(string dialogId, PromptOptions options, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (string.IsNullOrEmpty(dialogId))
            {
                throw new ArgumentNullException(nameof(dialogId));
            }

            if (options == null)
            {
                throw new ArgumentNullException(nameof(options));
            }

            return await BeginDialogAsync(dialogId, options, cancellationToken).ConfigureAwait(false);
}
```

I don't see how we could reasonably make that more clear - the Exception call stack is there, the argument name is there, and the exception type is correct. 

The only option would be to accept null when it's passed in, which is something we try to avoid doing.

**Comment by cleemullins** [comment]
What would you suggest as a fix?

**Comment by AskYous** [comment]
Ok... I'm actually not sure if this is a Visual Studio issue or a butbuilder-dotnet issue. When running the debugger, I was hoping it would error on this part of the code: `step.PromptAsync("oauth", null);`. But instead, it encountered an error on this part of the code: `await dc.BeginDialogAsync("sign-in", new object(), cancellationToken);` Because of this, I thought the error was in another part of the code so it tricked me and put me in confusion. See the screenshots in the initial post.
