### ISSUE TITLE
/INSPECT attach command does not work in MSTeams channel conversations

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/botbuilder-dotnet#2060]
## Version
4.4.4

## Describe the bug
The `/INSPECT attach [guid]` command when issued in a MS Teams channel conversation is not processed.

## To Reproduce
1. Launch Bot Framework Emulator. Start [Bot Inspector Mode](https://github.com/Microsoft/BotFramework-Emulator/blob/master/content/CHANNELS.md)
2. Open Bot, providing the appropriate NGROK address and credentials
3. Copy the displayed `/INSPECT attach` text
4. In a Microsoft Teams channel conversation, @ mention the bot and send the `/INSPECT attach' command.

## Expected behavior
1. A response in MS Teams from the emulator stating *Attached to session...*
1. Trace entries in the emulator log

## Additional context
When the [middle inspects the activity text](https://github.com/microsoft/botbuilder-dotnet/blob/f044dd2ff6bd2795af44470054879e8706bd4274/libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs#L40), it does not [remove recipient mention](https://github.com/microsoft/botbuilder-dotnet/blob/f044dd2ff6bd2795af44470054879e8706bd4274/libraries/Microsoft.Bot.Schema/ActivityExtensions.cs#L40) text. 

[bug]

**Comment by johnataylor** [comment]
Hope to get this fixed next week, I'll set up a test with Teams and debug from there.
@pschaeflein can you provide a little more context? why is the remove recipient mention relevant?

**Comment by pschaeflein** [comment]
Because without trimming the at mention, the [if statement at line 41](https://github.com/microsoft/botbuilder-dotnet/blob/f044dd2ff6bd2795af44470054879e8706bd4274/libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs#L40) evaluates to false.
