### ISSUE TITLE
[Adaptive] [LG] [DCR] ImportResolver delegate should not only return text, but also id

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#2072]
In current implementation of file reference feature between lg files. We can pass a delegate to help the engine to resolve imports. 

But if the delegate only return text, there is no way the engine can detect duplication, like
* ```[import](b.lg)```
* ```[import](./b.lg)```
* ```[import](b) // maybe```

Because in the import discovery phase, the engine must use some kind of id\key to identify the resource been discovered. So the request here is: make sure delegate return id+text. 

The idea can be summarized as "if you want to take over resource discovery process, you should also provide a global id to identity resource".

**Comment by feich-ms** [comment]
fixed by #2065
