### ISSUE TITLE
Conversations.SendConversationHistoryWithHttpMessagesAsync should not return a ResourceResponse

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#2081]
## Version
4.5.0

## Describe the bug
While testing the REST API, I was able to successfully insert messages into Web Chat's conversation history with the "Send Conversation History" API, but I discovered that the API doesn't return a response with any content. The [`Conversations.SendConversationHistoryWithHttpMessagesAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Connector/Conversations.cs#L638) method has a return value of `Task<HttpOperationResponse<ResourceResponse>>` which means it's expecting a `ResourceResponse` from the API call. However, that doesn't make a lot of sense because what would the ID be? There could be multiple activities involved, and you already know each ID since you specified them in the call. I suspect this method may have been mistakenly based on `SendToConversationWithHttpMessagesAsync`.

Here is an example of a call to the API where you can see it doesn't return anything:

![SendConversationHistory](https://user-images.githubusercontent.com/41968495/59578785-c52f4800-907e-11e9-8274-cb562fdf5e68.jpg)

Someone might want to investigate whether `Conversations.SendConversationHistoryWithHttpMessagesAsync` should really be returning `Task<HttpOperationResponse>` instead of `Task<HttpOperationResponse<ResourceResponse>>`

[bug]

**Comment by v-kydela** [comment]
@carlosscastro - Should `Conversations.SendConversationHistoryWithHttpMessagesAsync` be returning a resource response?

**Comment by cleemullins** [comment]
Closing due to inactivty and compatibility issues.
