### ISSUE TITLE
Using ChoiceInput in Designer with SuggestedActions causes broken buttons

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#2090]
## Version
Adaptive

## Describe the bug
When using the ChoiceInput in Designer, only the first two choices will display properly when rendered as SuggestedActions.

This ChoicePrompt definition:
```
    {
      "$type": "Microsoft.ChoiceInput",
      "$designer": {
        "createdAt": "2019-06-12T19:50:23.410Z",
        "updatedAt": "2019-06-18T16:16:27.430Z",
        "id": "546453"
      },
      "property": "turn.menuchoice",
      "outputProperty": "",
      "prompt": "Here are my main functions:",
      "retryPrompt": "PLEASE PICK ONE!!",
      "style": "SuggestedAction",
      "choices": [
        {
          "value": "craft item"
        },
        {
          "action": {},
          "value": "list inventory",
          "synonyms": []
        },
        {
          "action": {},
          "value": "demo"
        },
        {
          "action": {},
          "value": "tests"
        }
      ]
    }
```

Results in this message in emulator:
![Screen Shot 2019-06-18 at 11 16 59 AM](https://user-images.githubusercontent.com/729873/59701236-c36a9f00-91ba-11e9-8b14-7936fd78bf93.png)

[bug]

**Comment by benbrown** [comment]
Additional issues with ChoicePrompt:

* When set to "Auto", the prompt fails completely and returns "Object reference not set to an instance of an object."

* When set to "Hero Card", the prompt renders as an error:

![Screen Shot 2019-06-18 at 11 20 38 AM](https://user-images.githubusercontent.com/729873/59701388-26f4cc80-91bb-11e9-9a05-c746d5bd6f71.png)

**Comment by carlosscastro** [comment]
@luhan2017 tried to reproduce and apparently this was fixed with the input rewrite. @benbrown please reopen if you experience issues after you take a snapshot of the latest changes.
