### ISSUE TITLE
[Adaptive] Enable RecognizerResult injection to reduce extra luis call

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2094]
1. Pain point
	Currently, each adaptive dialog will bind to a recognizer directly and query it per each turn. The binding is so tight, which make developer hard to manage their luis call while using adaptive SDK.
	While migrate email skill to adaptive dialog, we met the following issues due to this tight bind:
	(1)Cannot reuse luis recognize result between different adaptive dialogs
	Currently, one adaptive dialog is bind tightly with one luis model, which means every time we add a new adaptive dialog, developers could possibly add an extra luis call, which means extra money. As developers, we are seeking for a way to reduce extra luis call by sharing luis result between different adaptive dialogs.
	(2)Hard get luis result out as IRecognizerConvert object (generated by luisgen)
         Luis result now saved in turn state with separate json format:
![image](https://user-images.githubusercontent.com/16643193/59733235-bfed1b80-927f-11e9-8eea-d4e273f4a55f.png)
         If we want to save and use luis result, we need to copy them out explicitly. But in code, developers would like to have a way to copy them out and translate them to IRecognizerConvert or host by themselves then passed to adaptive dialog, simular like the following:
![image](https://user-images.githubusercontent.com/16643193/59735333-b8ca0b80-9287-11e9-8a71-b47d5adf582d.png)
2. Scenario
	Currently email skill are using the following two layer adaptive dialog model:
![image](https://user-images.githubusercontent.com/16643193/59735359-d5664380-9287-11e9-973c-eeae67101de7.png)
	Turn 1: show email (Dispatched by main dialog, Luis call*1)
	Turn 2: forward the second email (Dispatched by show email dialog, then consulted by main dialog, Luis call *2)
	Compared to email skill without adaptive dialog, the luis call time increased by two times in show email flow.

3. Proposal
	Add a new property named RecognizedResult to make recognized result can be passed from outside.
![image](https://user-images.githubusercontent.com/16643193/59735418-12323a80-9288-11e9-9526-fd1fc3366227.png)

	Change the recognize logic to the following:
![image](https://user-images.githubusercontent.com/16643193/59735428-1c543900-9288-11e9-8731-e47145aff16d.png)

	Then just inject the recognize result in OnTurnAsync() in component dialog, then luis recognizer can be managed out of Adaptive dialog.

**Comment by vishwacsena** [comment]
@luhan2017, @DingmaomaoBJTU - can we discuss this a bit more? The model we are moving to is to have one LUIS app per dialog but that does not require you to always use a LUIS recognizer for each dialog. Are you looking to have the same LUIS recognizer in two different child scenarios (both triggered via a begindialog step in a parent dialog's intent rule) or having two Level 2/ Level n children share the same LUIS app up the hierarchy chain? if it is later, you can simply have two recognizers set to the same LUIS app. Caching of the result happens at the LUIS library level and there should not be multiple calls to LUIS given same query - it is a bug if you are seeing multiple calls. 

Finally, we have the ability to return results from multiple LUIS apps in a single call so there is no metering impact to customers.

**Comment by vishwacsena** [comment]
@luhan2017; @boydc2014; @DingmaomaoBJTU - can you please help provide an update? We have this work item that will track the workflow around orchestrating multiple model results via a single LUIS call. Can you please list scenarios where you need to use the exact same LUIS app in multiple dialogs and or up the dialog chain?

**Comment by DingmaomaoBJTU** [comment]
Sure... Will give update when we are done. Sorry for the late response.

**Comment by DingmaomaoBJTU** [comment]
In my case, I still found extra luis calls. 
-- Main Dialog (luis A) -- (L1)
----Show email Dialog (luis A) -- (L2)
1) when I input "show emails", it will enter show email dialog from L1, one luis call is recorded.
2) when I input "send email" after this, it will enter send email dialog from L2, **two luis call is recorded** They are from the same luis app.

(Will list more scenarios after I'm done... Actually, there are some other issues I need to check with you...)

**Comment by DingmaomaoBJTU** [comment]
Scenario list:
Show email (L1) -> Send email (L2)
Show email (L1) -> Read email (L2)
Show email (L1) -> Delete email (L2)
....

**Comment by DingmaomaoBJTU** [comment]
And in total, I have three issues to check with you:
1) Extra luis call when use same luis app id.
2) Could not find a way to parse adaptive luis result in turn state to IRecognizerConvert object
3) In email skill, we use two luis model called general and email model to work together. In general model, we will have intents like "cancel", "help", "next page", etc, and in email model, we will handle intent like "show email", "send email". What should I do when I want to handle both set of intents in these two models in one adaptive dialog?

**Comment by DingmaomaoBJTU** [comment]
For the second one, will tracked by https://github.com/microsoft/botbuilder-dotnet/issues/2363
