### ISSUE TITLE
OnMembersAddedAsync doesn't fire when bot is added to a Teams team

### ISSUE THREAD

**Issue by paulnearney** [microsoft/botbuilder-dotnet#2095]
## Version
4.4.3

## Describe the bug
Adding the Echo Bot to a new team doesn't fire the OnMembersAddedAsync event handler, which contradicts the docs

## To Reproduce
Create a new Echo bot from the template, and deploy to Bot Service, ensure it works correctly. Then add the bot to a Teams team. 

## Expected behavior
I would expect the OnMembersAddedAsync event to fire in code.

## Additional context
I can see that the bot receives a POST containing a membersAdded activity, but the adapter does not fire the OnMembersAddedAsync event. 

OnMembersAddedAsync works fine for team members added to the conversation.

The only significant difference I can see in the activity's JSON is that the membersAdded for the bot doesn't include an aadObjectId

![image](https://user-images.githubusercontent.com/50833925/59755522-f460d780-927f-11e9-9461-1f9d3eb1f920.png)

I'm sideloading the app rather than publishing it to a store, could this be the root cause?

[bug]

**Comment by johnataylor** [comment]
The code does filter based on id before triggering that callback, here is the logic:

```
  if (turnContext.Activity.MembersAdded.Any(m => m.Id != turnContext.Activity.Recipient?.Id))
  {
    return OnMembersAddedAsync(turnContext.Activity.MembersAdded, turnContext, cancellationToken);
  }
```

Perhaps this is the problem. I'll drill into this when I have a Teams bot set up.

**Comment by mdrichardson** [comment]
@paulnearney Please see if your bot is filtering the activity as @johnataylor mentioned. Based on [my testing](https://stackoverflow.com/a/55525014/10860086), this is likely the case.

**Comment by mdrichardson** [comment]
I am closing this issue as it doesn't seem to be a blocking issue. Feel free to reopen if you have need to get this resolved.
