### ISSUE TITLE
LUIS Recognizer not working for decimal numbers

### ISSUE THREAD

**Issue by th0ger** [microsoft/botbuilder-dotnet#2097]
## Version
Using SDKv4 with current stable version:
Microsoft.Bot.Builder v4.4.5
Microsoft.Bot.Builder.AI.Luis v4.4.5

## Describe the bug
LUIS can be set up with prebuild dimension entity to recognize e.g. "3.3 kg", and extract/split the corresponding float and unit.
However, LuisRecognizer removes the decimal point from the raw LUIS reponse, returning 33.
This happens for both dot (.) and comma (,) decimal separators.

## To Reproduce
1. Use a standard LUIS/bot template (e.x. flight booking demo).
2. Configure LUIS service with a prebuilt 'dimension' entity (to recognize weight).
3. Run with Bot framework emulator, utterance "blah blah **3.3 kg**"
4. Check Luis trace in emulator:
"Raw Response" captures the value ok:
>  "luisResponse": {
> ...
>         "endIndex": 59,
>         **"entity": "3.3 kg",**
>         "resolution": {
>           "unit": "Kilogram",
>           **"value": "3.3"**
>         },

But "Recognizer Result" has removed the decimal seperator, **turning "3.3" into 33** !
>   "recognizerResult": {
>     "alteredText": null,
>     "entities": {
>       "$instance": {
>         "MyWeight": [{
>             "endIndex": 60,
>             "startIndex": 54,
>             **"text": "3.3 kg",**
>             "type": "builtin.dimension"
>           }]},
>       "MyWeight": [{
>           **"number": 33,**
>           "units": "Kilogram"
>         }],

5. Alternatively set breakpoint in Visual Studio and inspect:
```
var recognizer = new LuisRecognizer(luisApplication);
var recognizerResult = await recognizer.RecognizeAsync(turnContext, cancellationToken);
```
By investigating recognizerResult.Entities with QuickWatch
>       "MyWeight": [{
>           "number": 33.0
>           "units": "Kilogram"
>         }],

## Expected behavior
recognizerResult.Entities should be able to return a decimal number (with non-zero decimals).

[bug]

**Comment by EricDahlvang** [comment]
Please share the LUIS model you've used to reproduce this.

**Comment by th0ger** [comment]
I'm attaching the C# demo project, which also contains the extended LUIS model FlightBookingWithWeight.json
[luisdemo_issue2097_clean.zip](https://github.com/microsoft/botbuilder-dotnet/files/3355359/luisdemo_issue2097_clean.zip)


- C# project was based directly on the "Core Bot (Bot Framework v4)" template.
- FlightBooking.json was uploaded to eu.luis.ai to create a new app. Added the new dimension:weight entry, added example utterance, tested, published, retrieved keys, exported model as FlightBookingWithWeight.json.
- appseting.json was filled in with Luis & Microsoft keys (please provide your own).
- LuisHelper.cs extended with:
var weight_token = recognizerResult.Entities["$instance"]["weight"].FirstOrDefault()["text"];
var weight_number = recognizerResult.Entities["weight"]?.FirstOrDefault()?["number"];
var weight_units = recognizerResult.Entities["weight"]?.FirstOrDefault()?["units"];
await turnContext.SendActivityAsync(MessageFactory.Text($"DEBUG: weight_token = {weight_token}"), cancellationToken);
await turnContext.SendActivityAsync(MessageFactory.Text($"DEBUG: weight_number = {weight_number}"), cancellationToken);
await turnContext.SendActivityAsync(MessageFactory.Text($"DEBUG: weight_units = {weight_units}"), cancellationToken);

- Testing bot with "book flight to orlando with 4.4 kg of luggage"
- Output:
![image](https://user-images.githubusercontent.com/26322144/60597128-aaf9a780-9daa-11e9-91f7-561770e94ce6.png)

**Comment by th0ger** [comment]
As a side note, this seems related to issues like [Decimal point ignored in Convert.ToDouble](https://stackoverflow.com/questions/37461888/decimal-point-ignored-in-convert-todouble).

After LUIS, I have a waterfall dialog that can ask for supplementary information. I utilize Microsoft.Recognizers.Text.NumberWithUnit to be able to provide input such as "3.3 kg".

```
var results = NumberWithUnitRecognizer.RecognizeDimension(result, culture:"en-us", fallbackToDefaultCulture:true);
double weightValue = Convert.ToDouble(results.First().Resolution["value"], CultureInfo.InvariantCulture);
```
The `InvariantCulture` part was essential to avoid the decimal point being removed.
Maybe a similar issue exists internally in `RecognizeAsync`? I don't a way to customize culture for this.

**Comment by CoHealer** [comment]
@sgellock , what are next steps? Do you want BFSE or your team to look into this?

**Comment by chrimc62** [comment]
This is by design although it would be worth documenting.   The issue is that when we parse a number from LUIS we use double.TryParse which depends on CultureInfo.CurrentCulture for how numbers are interpreted.  In general you should set this to either invariant or the specific culture you want to use for interpreting things like numbers.  If you did CultureInfo.CurrentCulture = CultureInfo.InvariantCulture as part of your bot environment then you would get the result you expect.
