### ISSUE TITLE
[Adaptive] [Regression] New Inputs never look at grounded property value before prompting

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2119]
Inputs have a pre-built capability to skip prompt if the property already has value. Post the input DCR, this functionality has regressed. 

As an example, with this sample dialog, we will always ask the user for their name where the second time this dialog begins, we should skip it since we already have user.name set. 

```C#
var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
            {
                Generator = new TemplateEngineLanguageGenerator(),
                Steps = new List<IDialog>()
                {
                    new TextInput()
                    {
                        Prompt = new ActivityTemplate("What is your name?"),
                        Property = "user.name",
                    },
                    new SendActivity()
                    {
                        Activity = new ActivityTemplate("Hello {user.name}, nice to meet you!")
                    }
                }
            };
```

**Comment by luhan2017** [comment]
In the new InputDialog, we don't have this logic. Currently the Inputs takes two source of inputs:
1. value: a value from memory, for example entities.
2. user input. 

I will fix it.

**Comment by tomlm** [comment]
This should be working with my latest checkin. 

For example look at unit test: 
* Step_ConfirmInput
* Step_ChoiceInput
etc. these all explicitely test this scenario
