### ISSUE TITLE
DCR: Simplify model for Bot development and remove any concept of ASP.NET controllers from the developer

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#212]
# Overview
Bots should exist as a concept unto themselves and not require any sort of knowledge of middleware or things like ASP.NET controllers be developed or glued into place by the developer. In fact, a bot should know almost nothing about their host environment to remain as portable as possible across different hosts as possible. 

# High level of WIP
I'm working on a PR that I intend to submit by week's end that will do the following:

 1. Introduce an `IBot` interface that today consists of nothing but the typical `Task OnReceiveActivity(IBotContext context)` method many of the preceding refactorings have been leading to. The introduction of this concept is _very_ important. It is the target at the end of the middleware chain that ultimately contains the core logic for a bot, but is not itself middleware. Just as a controller in ASP.NET is not a piece of middleware. Implementing it shouldn't require the developer to know anything about middleware or hosting. (NOTE: ultimately, we can go further than this and go with a convention based approach that doesn't even require the developer to implement an interface, but I'll save that for another discussion.)

 2. Introduce a set of "host" integration libraries that provide a first class configuration experience for both ASP.NET Web API (i.e. NetFx 4.x) and ASP.NET Core. These will essentially be a set of configuration extensions to register the bot in an idiomatic way with those respective frameworks. Behind the scenes, the proper plumbing will be put in place to shuffle messages from some route into the underlying `IBot`, but that will be completely hidden from the developer requiring them to do nothing more than configure the bot framework integration the way they would any other service inside of those frameworks.

# Goals

## Host integration libraries
A host integration library should:
 1. Receive an `Activity` over some transport (e.g. HTTP)
 2. Establish a `BotContext` for that `Activity`
 3. Invoke the middleware to process that `Activity`

From step 3 on it becomes pure Bot Framework and the host is completely abstracted away. Additionally an integration library could optionally include some host specific middleware that might make sense when integrating specifically into that host.

## Bot lifetime and dependency injection supported
Now that `IBot` exists, the host can actually choose how it gets instantiated. From an ASP.NET (Web API or Core) perspective the host can actually resolve the `IBot` from the configured dependency container in a completely container agnostic way which keeps them from understanding lifetime of the bot or what dependencies the bot might need to do its job.

## Developer abstraction from the inner workings
The developer should be abstracted from any middleware, adapter and host details and work purely at the higher level until they _want_ to go deeper. If they're just building a bot, let them do that. They don't even need to get into thinking about middleware until they're ready, simply implement an `IBot` and configure to run in the host.

# A taste of what's to come
In the end, the developer who is creating a bot will end up doing something as simple as this:

#### `MyBot.cs`:
```C#
public class MyBot : IBot
{
    private readonly IMyService _myService;

    public MyBot(IMyService myService)
    {
        _myService = myService;
    }

    public Task OnReceiveActivity(IBotContext context)
    {
         // Bot implementation here that, for example, uses the IMyService that was injected
        ....
        
        await _myService.DoSomethingAsync();

       ....
    }
}
```
##### `App_Start\BotConfig.cs`:
```C#
public class BotConfig 
{
   public void Register(HttpConfiguration config)
   {
        config.MapBotFramework(botConfig =>
        {
            botConfig
                .UsingApplicationIdentity("myApp123", "myAppPasswordXyz")
                .UseMiddleware(new ConversationStateManagerMiddleware(new MemoryStorage()));
   }
}
```
##### `Global.asax.cs`
```C#
public class WebApiApplication : System.Web.HttpApplication
{
    protected void Application_Start()
    {
        GlobalConfiguration.Configure(config =>
        {
            WebApiConfig.Register(config);
            BotConfig.Register(config);
        });
    }
}
```
##### `Startup.cs`
```C#
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddBotFramework()
                .AddBot<MyBot>("mybot")
                    .Use(new ConversationStateManagerMiddleware(new MemoryStorage()));
        }

        public void Configure(IApplicationBuilder app)
        {
            app
                .UseBotFramework(o =>
                {
                    o.AppId = "123";
                    o.AppPassword = "Password";
                });
        }
}
```

# Final thoughts
This is of course all up for discussion and I leave to the team's discretion as to if/when to merge the forthcoming PR. IMHO, introducing these changes sooner rather than later will be a "good thing" as I believe that there is still a lot of work to be done beneath this layer (e.g. middleware, adapters, etc). So if we can get these abstractions in place now, the developers who are working purely on bots will experience much fewer breaking changes going forward and third party libraries, such as [Promptly.NET](https://github.com/cmayomsft/promptly-dotnet), can build on to this and provide even more abstractions to buffer the developers even more from change.

**Comment by drub0y** [comment]
As noted above I've pushed up my working branch and opened PR #218 for the WIP if anyone wants to start taking a look it and provide any early feedback as comments/review feedback on the PR... I'm all ears. 👂😄 

My plan for the next day or so is to spend some more time cleaning things up, making sure code is optimal (runtime and legibility) and will update all the .NET core sample projects to use the new integration libraries as only the EchoBot is updated along with the 4.61 EchoBot. Obviously I will also do my best to address any feedback that is applied to the PR in the meantime as well.

**Comment by cleemullins** [comment]
Thanks Drew! Looking forward to checking this out in detail.

________________________________

**Comment by cleemullins** [comment]
@drub0y 

Thanks! Closig this issue.
