### ISSUE TITLE
Issue with AzureBlobTranscriptStore.GetTranscriptActivitiesAsync if the blob have been created with NodeJS with AzureBlobTranscriptStore class 

### ISSUE THREAD

**Issue by didaskein** [microsoft/botbuilder-dotnet#2120]
## Version
What package version of the SDK are you using:  Latest 

## Describe the bug
Give a clear and concise description of what the bug is.
Log Transcript with AzureBlobTranscriptStore in a NodeJs Bot. Then try to consume the Transcript with a C# Bot. The issue is the name of the timestamp field with a T in C# & a t in NodeJs. And also the value in the timestamp is very strange : ex 1560759447574

## Expected behavior
Save behavior in C# & NodeJs classes write & Read

## Screenshots
![image](https://user-images.githubusercontent.com/13362276/60049720-2c787800-96cf-11e9-8c0a-fe8f5424e14e.png)

[bug]

**Comment by sgellock** [comment]
@didaskein thank you for opening the issue.  We'll take a look at it.  the earliest we'd get a fix out is our 4.6 release.

**Comment by cleemullins** [comment]
@tomlm, IIRC you wrote both side of the Transcript store and this was one of your design goals. Could you take a quick look and see if you can fix?
