### ISSUE TITLE
Publish Microsoft.Bot.Builder.Testing as a nuget

### ISSUE THREAD

**Issue by abishekreddy** [microsoft/botbuilder-dotnet#2123]
**Is your feature request related to a problem? Please describe.**
Please publish Microsoft.Bot.Builder.Testing to the nuget store so that DialogTestClient can be referenced by people writing unit tests for their bot projects.

**Describe the solution you'd like**
Microsoft.Bot.Builder.Testing should be available in the nuget store.

[enhancement]

**Comment by gabog** [comment]
Hi @abishekreddy, the testing package will be released to nuget when we release 4.5, in the meantime you can reference the nightly builds from my get https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.Testing.

Let me know if you have any feedback or comments on the DialogTestClient.

Thanks

Gabo
