### ISSUE TITLE
[Adaptive] ChoiceInput.Choices should support both List<Choices> and a memory path

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#2145]
Currently in C# implementation we have:

Choices: List<Choice> to accept user configured Choices in json.
choiceProperty: memorypath to accept list of string in memory as Choices.

We need to merge this to one property.

Choices: List<Choice>|Expression

**Comment by vishwacsena** [comment]
@luhan2017 - just checking in to see if you will be prepping a PR for this?

**Comment by vishwacsena** [comment]
Let's keep two properties
- Choices -> list<choice>
- DynamicChoices -> expression

**Comment by vishwacsena** [comment]
@luhan2017 can you help prep a fix for this?
