### ISSUE TITLE
Build fails when using Visual Studio 2017

### ISSUE THREAD

**Issue by GasparAcevedoZainSouthworks** [microsoft/botbuilder-dotnet#2148]
## Describe the bug
When running a Pipelines Build against the current _master_ branch using the _NetCore SDK v2.2.100_, we are facing some errors related to the SDK C# version.

![image](https://user-images.githubusercontent.com/43762887/60363436-ec104700-99b9-11e9-94d1-86b44e828aa1.png)

## Additional context

As you can see in the picture above, the errors remark that some changes in _LuisRecognizers.cs_ are not available for the _C# 7.0_ version and, instead of this one, the _C# 7.1_ should be used. But in our pipelines, we are using the _NetCore SDK 2.2.100_, which supports _C# 7.3_ (more information [here](https://dotnet.microsoft.com/download/dotnet-core/2.2)):

![image](https://user-images.githubusercontent.com/43762887/60363796-df402300-99ba-11e9-9b6c-0122cfeef5b0.png)

However, after doing more in-depth research, we found that there are some known issues with the _NetCore v2.2_ and _Visual Studio 2017_ ([link](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-known-issues.md#visual-studio-2017-cant-target-net-core-22)).

To fix this, we updated our pipelines for using _Visual Studio 2019_, and the Build successfully passed:

![image](https://user-images.githubusercontent.com/43762887/60364421-82456c80-99bc-11e9-95f6-32b0d1aa5165.png)

Despite this fix, we think that it would be a great idea to temporarily specify the _Language Version_ through the usage of the _**LangVersion**_ tag ([link](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#edit-the-csproj-file)) in the _Directory.Build.Props_ file, in order to avoid similar errors for those who are still using _Visual Studio 2017_

[bug]

**Comment by cleemullins** [comment]
I think Gabo (or John) did this the other day, as you're not the first person to hit this.

**Comment by gabog** [comment]
Addressed in https://github.com/microsoft/botbuilder-dotnet/pull/2158
