### ISSUE TITLE
[Adaptive] Provide confirm prompt while intent switching

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2160]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
When using adaptive dialog to switch intent, developers will either:
1. Do redispatch without confirmation (current way, less noise but may have side effect when user input with typo)
2. Prompt a confirmation first, when user said yes, switch flow.

Hope to have a way to customize option 2.

**Describe the solution you'd like**
Add a attribude like ConfirmationSteps in Adaptive Dialog SDK to define the confirmation steps.

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by vishwacsena** [comment]
@DingmaomaoBJTU, there isn't a clear way we could do this automatically. The author of the bot could choose to prompt user to confirm or perform disambiguation as they see fit to either stop consultation bubbling or continue it. 

One thing we have added recently is EditSteps which provides more fine grained control for desired consultation behavior including ability to added inputs or sending activities before or after the consultation as well as provides ability to insert the new steps anywhere in the current plan being executed.

Resolving as Won't fix.

**Comment by DingmaomaoBJTU** [comment]
@vishwacsena Yes, we can have other ways to support this configuration like add an if-condition step in every trigger rule. But my point is this could be a general request for developers (the intent switching could be a hard stop for a user, especially when user input some typo) - when I want to enable this for all trigger rules, I don't want to add the same code everywhere to make it happens. So it will be nice to have an attribute to define this confirm step (base on score would be nicer). What do you think?
