### ISSUE TITLE
IOS Teams app stopped displaying image | Teams Bot | Mobile Teams app

### ISSUE THREAD

**Issue by subhamawasthi** [microsoft/botbuilder-dotnet#2162]
Hi Team,

I have create a Bot using Botframework v3 and using the Bot in Teams channel.
Bot is working when using the Teams in Windows/PC. 
While when I use it in mobile app(IOS) the images which are present in QnA Answer are not getting displayed.

Images I have saved in azure storage(BLOB) with anonymous read.
IOS teams version : 1.0.78 

Please help me for this.

Regards
Subham Awasthi

**Comment by dmvtech** [comment]
@subhamawasthi Are you able to [debug the bot using ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/)? I'm curious to know if when using the teams mobile app on iOS if you are getting any exceptions. Also; do images that don't come from QnA answers (but from the bot) work in the iOS app?

**Comment by dmvtech** [comment]
Closing due to no action. Please reopen if the issue persists and you still need assistance.
