### ISSUE TITLE
BotState<TState> et. al. still have hard requirement on StoreItem in implementation even though constraint is only IStoreItem

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#217]
# Details
## `BotState<TState>` Middleware
`BotState<TState>` only constrains `TState` to `IStoreItem, new()`. The problem is the implementation is still casting things to `StoreItem` (the class, not the interface). Here's the offending code:

https://github.com/Microsoft/botbuilder-dotnet/blob/b08dcb406a1d30a74d09930e57c4472660c886da/libraries/Microsoft.Bot.Builder.Core/Middleware/BotState.cs#L89-L92

To make matters worse, because the codebase is still plagued by `dynamic` the code is executing in dynamic mode and you don't actually find out about this in the most obvious way. Normally this would be an `InvalidCastException`, but instead it becomes a `RuntimeBinderException` which is a whole other mess and hides the real problem. In this case the `StoreItems`, which is `FlexObject` indexer returning dynamic instead of object which was reported in issue #109.

## Storage Implementations
The `IStorage` implementations also still assume all items will be `StoreItem`. 

### FileStorage
https://github.com/Microsoft/botbuilder-dotnet/blob/b08dcb406a1d30a74d09930e57c4472660c886da/libraries/Microsoft.Bot.Builder.Core/Storage/FileStorage.cs#L117

### MemoryStorage
https://github.com/Microsoft/botbuilder-dotnet/blob/b08dcb406a1d30a74d09930e57c4472660c886da/libraries/Microsoft.Bot.Builder.Core/Storage/MemoryStorage.cs#L61-L73

For the write side of things, the fastest fix here is to just change the code to only assume `IStoreItem` and I think everything should be "ok". The read side looks like it will continue to work based on how the storage layer always work with `StoreItem` and then the `BotState<TState>` middleware uses `StoreItems::Get<TState>(key)` which ultimately calls `StoreItem::ToObject<T>` to "coerce" it into the actual `T` needed.

Longer term though I think we need to have a discussion about this. It's going to result in a lot of allocations and garbage being created all over the place which will the frequency the GC needs to run. The answer is to make `IStorage::Read` take a generic parameter of `T` so that the storage layer can work with its serializer to deserialize directly into a `T` so nothing further ever needs to happen upstream.

# Workaround
Until this issue is addressed, make sure your state objects always to inherit from the `StoreItem` class.

**Comment by cleemullins** [comment]
Fixed in #236
