### ISSUE TITLE
[LG] Refine static checker

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#2188]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Static checker in LG should be friendly to mslg tool or vscode extension or other upper layer customer.

Due to performance reason, out previous staticChecker only accept parsed lg template list, it is not friendly to user. 

So, we should expose the API that can check errors/warnings from files/file/text, not only the parsed templates.

**Describe the solution you'd like**
Add the support of accepting text\file\files in static checker. Make static checker can work as a isolated module. 

[enhancement]

**Comment by boydc2014** [comment]
Update some description, and add myself in assign list to easy track.
