### ISSUE TITLE
[Qna] How to support telemetry in Qna

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2202]
## Version
What package version of the SDK are you using.
v4.future

## Describe the bug
Give a clear and concise description of what the bug is.
Could not find a way to send telemetry in Qna maker (Microsoft.Bot.Builder.AI.QnA QnAMaker.cs). The TelemetryClient attribute has been removed

## To Reproduce
Check the code here: 
https://github.com/microsoft/botbuilder-dotnet/blob/4.Future/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs

Here is the v4.0 doc: https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.ai.qna.qnamaker?view=botbuilder-dotnet-stable
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs

## Expected behavior
Make Qna maker support telemetry

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Should be resolved via a recent FI from master. Please reactivate should you continue to see this issue.
