### ISSUE TITLE
Prompts should not always set InputHints.ExpectingInput

### ISSUE THREAD

**Issue by sgellock** [microsoft/botbuilder-dotnet#2210]
## Describe the bug
Prompts in C# always use `InputHints.ExpectingInput` and do not respect the inputHint set on activities. 

## Expected behavior
If you pass in an Activity to the PromptOptions and it has an inputHint attribute, the Prompts should use that inputHint instead of stamping on top of it with `InputHints.ExpectingInput`.

This is a complementary Issue to the following issue tracked in the JS repo:
https://github.com/microsoft/botbuilder-js/issues/1042

Python Issue tracking:
https://github.com/microsoft/botbuilder-python/issues/247

[bug]

**Comment by cleemullins** [comment]
PR #2207 against the 4.5 Branch needs to be cherrypicked to master.

**Comment by v-kydela** [comment]
I am not sure why this issue was closed since that PR only changes `OAuthPrompt` and this issue is about prompts in general. Am I understanding this incorrectly?
