### ISSUE TITLE
[Prompt/LG] Prompt still take activity not IActivity as input but things like LG can only give IMessageActivity

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2218]
## Version
What package version of the SDK are you using.
4.6.0-Daily-2019-07-05-01

## Describe the bug
When I use LG to build up a prompt, the prompt only take activity not IActivity. So I can only make a cast to make it work.

## To Reproduce
var result = _lgMultiLangEngine.Generate(sc.Context, "[ReadOut]", new { messageList = state.MessageList });
                var activity = await new TextMessageActivityGenerator().CreateActivityFromText(sc.Context, result.Result, null);
                return await sc.PromptAsync(Actions.Prompt, new PromptOptions { Prompt = **activity as Activity** });

## Expected behavior
There are two way to make this work:
1) Change Prompt to accept IActivity and support input hint
2) Add an extra function named ActivityGenerator to return Activity directly.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
@DingmaomaoBJTU - can you take a look at this proposal and comment if it addresses your core need? #2325
