### ISSUE TITLE
Expected that LuisRecognizerMiddleware would implement Microsoft.Bot.Builder.Middleware.IMiddleware

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-dotnet#222]
We could not understand how to use LuisRecognizerMiddleware. Documentation is misleading. We tried to use it the same way as RegExpRecognizerMiddleware, but it doesn't work either:

                var adapter =  new BotFrameworkAdapter(applicationId, applicationPassword)
                    .Use(new UserStateManagerMiddleware(new MemoryStorage()))
                    .Use(new ConversationStateManagerMiddleware(new MemoryStorage()))
                    .Use(new LuisRecognizerMiddleware("<appId>", "<appKey>"))
                    .Use(new RegExpRecognizerMiddleware()
                         .AddIntent("showAlarms", new Regex("show alarms(.*)", RegexOptions.IgnoreCase))
                        .AddIntent("addAlarm", new Regex("add alarm(.*)", RegexOptions.IgnoreCase))
                        .AddIntent("deleteAlarm", new Regex("delete alarm(.*)", RegexOptions.IgnoreCase))
                        .AddIntent("help", new Regex("help(.*)", RegexOptions.IgnoreCase))
                        .AddIntent("greeting", new Regex("hi(.*)", RegexOptions.IgnoreCase))
                        .AddIntent("confirmYes", new Regex("(yes|yep|yessir|^y$)", RegexOptions.IgnoreCase))
                        .AddIntent("confirmNo", new Regex("(no|nope|^n$)", RegexOptions.IgnoreCase)));

**Comment by cleemullins** [comment]
We used to have a LUIS sample for this. At CSE's urging, we deleted most samples from the Repo as we were told "Too Many Samples" were confusing. We need a have a rational n all-up Samples story, which we don't have yet.

At the more concrete level, @emadelwany has authored PR #228 which is a full-features LUIS recognizer. We are waiting on the new [LUIS SDK NuGet package ](https://www.nuget.org/packages/Microsoft.Cognitive.LUIS/)to be published, then we should be good to merge that PR.
