### ISSUE TITLE
SetProperty step lower cases the property name being assigned

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2223]
## Describe the bug
If you run a SetProperty step that basically does `dialog.fromLocale = @fromLocale` the property will end up being named `dialog.fromlocale`. This seems to only happen when a new property needs to be added to dialog.

I believe the lower casing is happening [here](https://github.com/microsoft/botbuilder-dotnet/blob/4.Future/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs#L62) and its because we end up calling `ToString()` on an expression to get the property name. Why is this even an expression?  `Property` should just be a string.

[bug]

**Comment by Danieladu** [comment]
Maybe caused by the `CamelCaseNamingStrategy` of expressionCaseSettings

**Comment by vishwacsena** [comment]
I believe this is fixed. @boydc2014 - correct?
