### ISSUE TITLE
Provide a consistent way to get/ set properties via steps/ actions tied to the life time of a specific adaptive dialog.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2224]
## Describe the bug
I spent 30 minutes trying to figure out why my LG expression for a TextInput wasn't working and it was because [InputDialog derives from Dialog](https://github.com/microsoft/botbuilder-dotnet/blob/4.Future/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Steps/SetProperty.cs#L62) and not DialogCommand.  All steps should derive from DialogCommand otherwise you'll create random sandboxes where `dialog.xxxx` isn't visible to LG or the steps expressions.

[bug]

**Comment by vishwacsena** [comment]
We discussed this and landed on $foo to support dialog property getter/ setter up to the parent container dialog level. All our docs and samples should use $foo to refer to properties that are tied to the scope of the containing adaptive dialog.

**Comment by carlosscastro** [comment]
Solved as agreed on the email thread on this.
