### ISSUE TITLE
BeginDialog step options are literal strings and not expressions

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2225]
## Describe the bug
I tried passing `@fromLocale` and `@toLocale` entities as options to a TranslateConversation dialog I was starting and what I received was the literal strings "@fromLocale" and "@toLocale". Options should be expressions so that you can pass in dynamically computed values for options.

[bug]

**Comment by carlosscastro** [comment]
@Stevenic or @vishwacsena is the best-effort binding of options implemented in javascript? Can't seem to find it. any opinions on where is the best place to implement this? Otherwise I'll find my way but allowing opportunity for folks to weigh in.

**Comment by vishwacsena** [comment]
AFAIK, we do not have it in JS.

**Comment by carlosscastro** [comment]
Fixed.
