### ISSUE TITLE
[Adaptive] BeginDialog missing ability to bind to results returned by a child dialog

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2228]
BeginDialog via options allows you to pass value in to a child dialog. Any dialog can return a value to the caller by setting a return value on the EndDialog step. 

BeginDialog in the current implementation in composer is lacking ability to recieve the returned value either via a ResultProperty or Property itself that can perform two way data binding. 

- BeginDialog step is missing ResultProperty both in code as well as in the schema (as far as I can see)
- The schema needs to be updated to reflect this as well. 

Also see [this issue](Microsoft/BotFramework-composer#531)

**Comment by carlosscastro** [comment]
Fixed, but using Property output bindings. Turns out it is not trivial do do a ResultProperty here.

**Comment by vishwacsena** [comment]
Thanks @carlosscastro - Closing this ticket since the remaining issue is tracked via #2012
