### ISSUE TITLE
Misleading Naming on Recognizers

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/botbuilder-dotnet#223]
@anastasiia-zolochevska
As with the Node SDK, you can use the LUIS recognizer and Regex recognizer as middleware or just inline: 
```          
  _luis = new LuisRecognizerMiddleware(
            this.Configuration["MICROSOFT_LUIS_APP_ID"],
            this.Configuration["MICROSOFT_LUIS_APP_PASSWORD"]);
        }
var intents = await _luis.Recognize(context);
```
In Node, this is fairly clear because the recognizer is just called ```LuisRecognizer```, and samples show it being used as middleware. In C#, calling the recognizer ```LuisRecognizerMiddleware``` implies that it's only a piece of middleware. Several developers have been under the impression that the only way to use LUIS is to call the raw endpoint.

**Comment by garypretty** [comment]
As far as I'm aware, you use the middleware for when you need middleware. If you need to use LUIS elsewhere then you can use the LuisClient which is what the middleware uses behind the scenes. This is similar to the Qnamaker middleware which also has a corresponding QnA client

**Comment by ryanvolum** [comment]
@garypretty,  the C# middleware class was based on the Node implementation, which exposes a recognizer that can also be used as middleware. See [Using LUIS](https://github.com/Microsoft/botbuilder-js/wiki/Using-LUIS-and-QnA-Maker#using-luis) doc to see examples as recognizer in middleware or in bot logic.

I'm not saying this is necessarily how it should work - it's actually kind of confusing. But if we want LuisRecognizerMiddleware to only be middleware, it shouldn't expose those other helpers. We also shouldn't expect developers to dig around our source code to find the LuisClient. The .NET SDK should either follow the Node model here and use LuisRecognizer as either middleware or just a recognizer, or it should hide the recognizer methods that hang off LuisRecognizerMiddleware and expose the LuisClient as a separate service. Ideally both SDKs should follow the same functionality, and docs/samples should reflect how you use these abstractions in middleware and in bot logic.

**Comment by garypretty** [comment]
@ryanvolum totally agree with your points. The luis middleware is actually using the luis NuGet package which is why the client isn't in our source code. I think having the middleware expose a recognizer might be too confusing and we maybe need to look to separate the two out so that the middleware simply uses a recognizer behind the scenes. Not an easy one. Maybe more feedback will come from the hacks this week.

**Comment by ryanvolum** [comment]
this is from the hack this week ;)

**Comment by garypretty** [comment]
@ryanvolum ah. All falls into place! 😂

**Comment by cleemullins** [comment]
A totally new, and feature complete, Luis recognized is coming this week.

This will have parity++ with the one on SDK v3.

Emad, from the Luis team, has been working on it this week and is nearly done.

________________________________

**Comment by cleemullins** [comment]
@emadelwany is completely reworking this. PR for review is here. #228

**Comment by cleemullins** [comment]
To close the loop on this, here's what's fixing this for LUIS:

1. @emadelwany has updated the [Official LUIS SDK repo](https://github.com/Microsoft/Cognitive-LUIS-Windows/tree/master/CSharp) here with modern code. 
2. @emadelwany is working on publishing the [NuGet to this location](https://www.nuget.org/packages/Microsoft.Cognitive.LUIS/). It's a bit more complicated than it first seemed, but we're close. 
3. @emadelwany has authored PR #228, based on the revised LUIS SDK, to bring a 1st class recognizer to this repo. He's also written a thin Middleware wrapper around that recognizer. 

Hopefully we can get that all in ASAP. And we hope to do the same for Node.

**Comment by garypretty** [comment]
@cleemullins @ryanvolum The LUIS PR has been merged now, so hopefully we can close this now? Just trying to clear up the issue list where possible.

**Comment by cleemullins** [comment]
Closing, as the LUIS PRs and other recognizer code has changed to be unrecognizable from when this was filed.
