### ISSUE TITLE
[Adaptive] Circular dialogs are not supported. it will throw an exception of StackOverFlow

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#2230]
## Version
adaptive sdk 4.6

## Describe the bug
When I try to create a bot that has any sort of circular flow of dialogs, the botruntime fails when I try to connect to the bot. 

## To Reproduce
please refer to https://github.com/microsoft/BotFramework-Composer/issues/529

**Comment by vishwacsena** [comment]
@luhan2017 is the expectation that we support this or throw a better error message? I’d assume the former but would be good if you can help clarify.

**Comment by v-kydela** [comment]
@luhan2017 - The referenced issue has been closed. Should this be closed too?

**Comment by vishwacsena** [comment]
@luhan2017 can you help get a crisp repro of this against the latest bits?

**Comment by jamiemaguiredotnet** [comment]
Hi @vishwacsena - I wondered if this can be escalated at all please?

**Comment by vishwacsena** [comment]
@luhan2017 can you help with a reduced repro please?

**Comment by jamiemaguiredotnet** [comment]
Hi all.
@vishwacsena 

Fwiw, one workaround for this issue is to use a custom event then capture this. You can then rerun the same offending dialog without this circular error occurring.

**Comment by vishwacsena** [comment]
This is an issue only with declarative. 

Root.dialog
```json
{
    "$kind": "Microsoft.AdaptiveDialog",
    "triggers": [
        {
            "$kind": "Microsoft.OnBeginDialog",
            "actions": [
                {
                    "$kind": "Microsoft.SendActivity",
                    "activity": "Hello"
                },
                {
                    "$kind": "Microsoft.BeginDialog",
                    "dialog": "child1"
                }
            ]
        }
    ]
}
```

Child1.dialog
```json
{
    "$kind": "Microsoft.AdaptiveDialog",
    "triggers": [
        {
            "$kind": "Microsoft.OnBeginDialog",
            "actions": [
                {
                    "$kind": "Microsoft.SendActivity",
                    "activity": "World"
                },
                {
                    "$kind": "Microsoft.BeginDialog",
                    "dialog": "root"
                }
            ]
        }
    ]
}
```

FWIW, this code based adaptive dialog does not repro

```C#
var rootDialog = new AdaptiveDialog("root")
{
    Generator = new TemplateEngineLanguageGenerator(_lgFile),
    Triggers = new List<OnCondition>()
    {
        new OnConversationUpdateActivity()
        {
            Actions = WelcomeUserAction()
        },
        new OnBeginDialog()
        {
            Actions = new List<Dialog>()
            {
                new SendActivity("Hello"),
                new BeginDialog()
                {
                    Dialog = "child1"
                }
            }
        }
    }
};

var childDialog = new AdaptiveDialog("child1")
{
    Triggers = new List<OnCondition>()
    {
        new OnBeginDialog()
        {
            Actions = new List<Dialog>()
            {
                new SendActivity("World!"),
                new BeginDialog()
                {
                    Dialog = "root"
                }
            }
        }
    }
};
```

**Comment by vishwacsena** [comment]
@carlosscastro can you take this one as well given you are looking into replaceDialog issue?

**Comment by cleemullins** [comment]
@vishwacsena, this is a P1 bug from July. This is another 9-month old issue that's quickly coming up on it's 1-year birthday.

**Comment by vishwacsena** [comment]
Re-assigning to @tomlm in hope of being able to address this for R9. @carlosscastro possibly related to the looping issue you are planning to address with ReplaceDialog? Also note per my repro steps above, this only repros in declarative form and not in code based adaptive dialogs.

**Comment by cleemullins** [comment]
Spoke w/ Tom, he plans to address this week.

**Comment by cleemullins** [comment]
Spoke with @tomlm. Currently being fixed by @carlosscastro
