### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by vinodkumartheking** [microsoft/botbuilder-dotnet#2234]
#Problem Statement
when i use basic ECHO bot C# sdkv 4, when checking on localhost it is working fine, after publishing to azure with proper microsoftappid and key, When i "Test in Web" . I get the following error.

## Version
C#,
Sdk v4

## Expected behavior
I should get Echo+ typed message

## Screenshots
![image](https://user-images.githubusercontent.com/18139750/61119110-c5710680-a4b7-11e9-864c-751bfceef374.png)

## Additional context
Help in solving the issue.

[bug]

**Comment by mdrichardson** [comment]
Looking into this now. What method did you use to publish/deploy?

**Comment by mdrichardson** [comment]
`InternalServerError` generally indicates there's something wrong with your bot code. Here's a couple things you can try:

1. Ensure `Portal > App Service > Configuration` has the correct `MicrosoftAppId` and `MicrosoftAppPassword`
2. Check `https://<yourEndpoint>.scm.azurewebsites.net/dev/wwwroot` and ensure all of the appropriate files are there. Should be a bunch of `.dll`s and a `wwwroot` folder
3. Open `https://<yourEndpoint>.scm.azurewebsites.net/dev/wwwroot/:vs.output` and see what errors pop up when testing

**Comment by vinodkumartheking** [comment]
For publishing i download the publishing profile from app services and used to import in VS2017 to publish it.

**Comment by mdrichardson** [comment]
@vinodkumartheking 	I'll attempt to repro and let you know how it goes. Currently, although that *should* work, that isn't the officially-recommended method of publishing. For that, [see the docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg)

**Comment by mdrichardson** [comment]
@vinodkumartheking 	Are you using the EchoBot from the samples repo, or the one from the Azure Portal > New Web App Bot?

**Comment by mdrichardson** [comment]
@vinodkumartheking 	Are you still experiencing this?

**Comment by vinodkumartheking** [comment]
It seems there was issue, while created the Microsoft AppId and Key, the autogeneration of id and key was stopped in my organization. IT team separately created by " Registration of application in azure" service and shared the ID and key. 
Later it worked don't know what the IT Admin team done to fix the issue.

**Comment by Shubham-Kr10** [comment]
Hey @mdrichardson can you help me out as same errors are coming when used both approaches posted by you for publishing  bot to azure. As bot runs fine tested locally using emulator but as published to azure it provides attached errors in web chat.
![errors](https://user-images.githubusercontent.com/54877723/76410051-4d940c80-63b5-11ea-81fb-19cc6d4b2f42.png)
