### ISSUE TITLE
[LG] need stronger error check

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botbuilder-dotnet#2235]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
When I use IF/ELSEIF, I mistakenly use "ELSE IF" instead of "ELSEIF" but there is no error message. It is hard to find the issue because LG treat the "ELSE IF" as a simple sentence. And when I run it, all the sentences under "IF" could be returned. It is very confusing. So I think LG need a stronger error check.

**Describe the solution you'd like**
Add indentation check like Python so if I use a wrong key word it won't be treated as a sentence

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by vishwacsena** [comment]
Agree, this is going to be a common issue. Once the user is in a IF block or a SWITCH block, we should add validations that help cover the following - Mistyped ‘IF’ or ‘SWITCH’ or other related label names - e.g. ‘Elae’ instead of ‘Else’, ‘else if’ instead of ‘elseif’ etc.
