### ISSUE TITLE
Needing to use AsMessageActivity() to access properties is unintuitive

### ISSUE THREAD

**Issue by starlord-daniel** [Microsoft/botbuilder-dotnet#224]
It is not intuitive to use another function on a Activity to get access to more values of it.

Instead of this code I have to write:

`context.Request.AsMessageActivity().Text` or `context.Request.AsConversationUpdateActivity().MembersAdded`

I would like to do:

`context.Request.Text` or `context.Request.MembersAdded`

**Comment by cleemullins** [comment]
@starlord-daniel I too agree. 

However, in this case we're constrained by the underlying protocol. We've been auto-generating that layer for some time, and are hesitant to change it. 

We've played with varations on this where you override virtual methods "public virtual Task OnReceiveMessage"  and the like, but the feedback was very mixed.

**Comment by cleemullins** [comment]
For now, we're planning to leave this 'as-is'. 

The code you show in the "What I would like to do" is possible now, as we're passing Activity, rather than IActivity, into all of the relevant handlers. That gives you access to .Text and the other fields you're looking for.
