### ISSUE TITLE
@entity does not handle when there are multiple entities

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2240]
If LUIS comes back with an entity like meat:[["ham"]], then @meat will produce "ham".  If it comes back with an entity like meat:[["ham", "turkey"]] then it will produce [["ham", "turkey"]] and according to the spec should produce "ham".  You have to use @@ if you want the full entity.

[bug]

**Comment by boydc2014** [comment]
I think the spec is 
for [["ham"]] => "ham"
for :[["ham", "turkey"]] => ["ham", "turkey"]
my understand is if list contains only 1 item, we remove the list, stop until it's more than 1 item

@vishwacsena can you confirm this?

**Comment by vishwacsena** [comment]
Yes. @boydc2014 we discussed this in SDK standup and the decision was to snap to @entityname always return the first value immaterial of the list depth. 

@@entityname will return the actual list.

**Comment by boydc2014** [comment]
Cool, ok, i will merge https://github.com/microsoft/botbuilder-dotnet/pull/2241
