### ISSUE TITLE
DCR: add logic to AdaptiveDialog for supporting Action.Submit from AdaptiveCards

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2243]
**Describe the solution you'd like**
Today, if you create a bot in composer that sends an AdaptiveCard with an `Action.Submit` button there's no way to process the results.  The JS version of AdaptiveDialog [has logic](https://github.com/microsoft/botbuilder-js/blob/4.future/libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts#L283) that maps the values submitted to the bot into an Intent + Entities. You can then use an IntentRule to process the cards values in the same you would if they recognized by LUIS.  We should port this logic to the C# version of AdaptiveDialog.  

[enhancement]

**Comment by vishwacsena** [comment]
@stevenic can you add the JS PR so we can bring this to C#?
