### ISSUE TITLE
[LG] Incorrect text property resolve when special character is included

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2256]
## Version
4.6.0-Daily-2019-07-13-01

## Describe the bug
When use patten "a||b" in LG and b include sth like "\n", "||", the text/speech property resolved by TextMessageActivityGenerator will be incorrect.

**Note: *this bug is a high priority bug for email and calendar display***

## To Reproduce
ReadOutMessages(emailDetails, emailDetailsWithContent)
```
The email is @{emailDetails}. || The email is @{emailDetailsWithContent}.
```
emailDetails: from Microsoft Azure recieved Today at 10:10 AM titled Your Azure AD Identity Protection Weekly Digest
emailDetailsWithContent: from Microsoft Azure recieved Today at 10:10 AM titled Your Azure AD Identity Protection Weekly Digest, content is See your report. \n [Microsoft Azure] \n Your Azure AD Identity Protection Weekly Digest...

Expected:
Text = The email is from Microsoft Azure recieved Today at 10:10 AM titled Your Azure AD Identity Protection Weekly Digest.

Actual:
Text = The email is from Microsoft Azure recieved Today at 10:10 AM titled Your Azure AD Identity Protection Weekly Digest. **[Microsoft Azure]\nYour Azure AD Identity Protection Weekly Digest...**

## Expected behavior
Text = The email is from Microsoft Azure recieved Today at 10:10 AM titled Your Azure AD Identity Protection Weekly Digest.

Speek = The email is from Microsoft Azure recieved Today at 10:10 AM titled Your Azure AD Identity Protection Weekly Digest, content is See your report.\n[Microsoft Azure]\nYour Azure AD Identity Protection Weekly Digest...

## Screenshots
![image](https://user-images.githubusercontent.com/16643193/61274496-8526c680-a7de-11e9-8526-d336ce5b3a70.png)

## Additional context

[bug]

**Comment by DingmaomaoBJTU** [comment]
As data received from msgraph for calendar & email may include *any kind character*, please ensure LG works well with all possible character and character combinations.

**Comment by vishwacsena** [comment]
We are planning to deprecate this functionality in favor of #2325
