### ISSUE TITLE
Streaming Extensions: WebSocketStreamingHttpAdapter doesn't work with AddScoped

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botbuilder-dotnet#2257]
## Version
4.5.0 Preview 1

## Describe the bug
The new streaming adapter doesn't work with AddScope and dependency injection.

## To Reproduce
The issue seems to occur when transient bot has a scoped dependency. A simple example how I was able to reproduce it:

1) In the Startup.cs, set the following lines:

services.AddScoped(ctx => Guid.NewGuid().ToString());
services.AddTransient<IBot, EchoBot>();

2)  Define the EchoBot as follows:

    public class EchoBot : ActivityHandler
    {
        private readonly string _guidString;

        public EchoBot(string guidString)
        {
            _guidString = guidString;
        }

        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(
                MessageFactory.Text($"Echo: {turnContext.Activity.Text} " + this.GetHashCode() + " " + _guidString), cancellationToken);
        }
    }

So the string sent back to the client consists of the word "Echo: ", then the client text, then bot hashcode (as a check of bot identity) and a guid provided by the IoC container.

3) Try talking to the bot via WebChat. On WebChat, I got the following results:

Echo: aaa 40687132 f82e2623-5d10-4015-9d4d-4bcf14266430
vp-echo-bot-hcwf64
aaa
You
Echo: aaa 14232079 10b00c07-817c-4c55-847f-725e775d7134
vp-echo-bot-hcwf64
aaa
You
Echo: aaa 66177964 89bc30a5-eb39-43ec-ae37-66943cfe2aa8
vp-echo-bot-hcwf64
aaa
You
Echo: aaa 59067205 38658730-86c6-42fe-9041-3a2b4815df6f

Note that both the hash code and the guid are different on each request, which is exactly what I expect. 

4) Try the same (exactly the same service, no redeployments or config changes) via the Direct Line Flex. For me, the results were:

aaa
<vp-echo-bot-hcwf64>: Echo: aaa 15949679 f7547f53-ff28-4ec9-b990-54800c65eb76
aaa
<vp-echo-bot-hcwf64>: Echo: aaa 25024597 f7547f53-ff28-4ec9-b990-54800c65eb76
aaa
<vp-echo-bot-hcwf64>: Echo: aaa 27509237 f7547f53-ff28-4ec9-b990-54800c65eb76
aaa
<vp-echo-bot-hcwf64>: Echo: aaa 39743727 f7547f53-ff28-4ec9-b990-54800c65eb76
aaa
<vp-echo-bot-hcwf64>: Echo: aaa 17760911 f7547f53-ff28-4ec9-b990-54800c65eb76
aaa
<vp-echo-bot-hcwf64>: Echo: aaa 56867592 f7547f53-ff28-4ec9-b990-54800c65eb76
aaa
<vp-echo-bot-hcwf64>: Echo: aaa 59345385 f7547f53-ff28-4ec9-b990-54800c65eb76
This time, the hashcode of the bot is different (which is what I expected - it means that each request triggers creating a new bot) but the scoped guid taken from the IoC container is the same every time, which is different than in the case of WebChat (and classic Direct Line).

**Comment by carlosscastro** [comment]
Thanks Jeff! I'll look into this as I refactor some of the streaming pieces.

**Comment by DDEfromOR** [comment]
@cleemullins is correct, there will not be a streaming adapter once the current work is complete, so there's not anything to fix here. Though to be clear, version of the adapter in master has this bug, but will be removed entirely with https://github.com/microsoft/botbuilder-dotnet/issues/2490
