### ISSUE TITLE
BotFrameworkAdapter::GetAppCredentials assumes there are some app credentials even configured

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#226]
# Details
This bug was introduced with PR #192 and has to do with the implementation of `BotFrameworkAdapter::GetCredentials`. It blindly assumes that an application identity has been configured when, in all samples, we don't bother configuring any application identity because we only hit the samples with the emulator.

Here is the offending code:

https://github.com/Microsoft/botbuilder-dotnet/blob/d28d218f78a735f6b43399844b04b3bc654fda23/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L105-L116

The problem is, when no application identity is configured, the `appId` parameter will be `null` here and since it is blindly passed to `TryGetValue` that will throw a `ArgumentNullException` because you can't pass a `null` key to it.

# Proposed Fix
The fix should be as simple as adding a check to see if `appId` is null and, if so, simply returning `null` straight away.

# Workaround
None that I'm aware of. You need to configure application identity or this will throw every time.

**Comment by brandonh-msft** [comment]
+1

# this is halting emulator development

cc @cleemullins @tomlm @cmayomsft

**Comment by drub0y** [comment]
I just noticed it's more than this as `ConnectorClient` was also updated to assume non-`null` on the `credentials` being passed in as well.

https://github.com/Microsoft/botbuilder-dotnet/blob/d28d218f78a735f6b43399844b04b3bc654fda23/libraries/Microsoft.Bot.Connector/ConnectorClient.cs#L164-L175

If I break on exceptions and step over these things I'm able to use the emulator, but that's a bit too much.

**Comment by drub0y** [comment]
I'm working on a PR for this, but I wanted to say that my last statement about `ConnectorClient` being updated was incorrect. Looking at it now in more depth as I attempt a fix, it's just that the previous version of the `BotFrameworkAdapter` code used to always initialize a `MicrosoftAppCredentials` regardless of the application identity being `null` or not and then always pass that through. So that's the simple fix I'm making here as well now.

Stand by...

**Comment by cleemullins** [comment]
@drub0y Standing by. I was about to look at this, but if you're already in-progress, I'll hold off. Ping me when you're ready!

**Comment by drub0y** [comment]
Turns out this wasn't a true fix and the manual testing I did didn't cover the scenario properly. It trades the `ArgumentNullException` for an `UnauthorizedException` now as it tries to actually get an OAuth token using the null application identity.

I'm digging back into the version before the bug was intro'd and will figure it out and submit another PR. At least now I know I can't use the EchoBot in this version of the code to validate this stuff as it completely bypasses `BotFrameworkAdapter`.

**Comment by drub0y** [comment]
Wow, ok I had to spelunk pretty deep to find the problem here and I'm still not entirely sure I'm right, but it looks like the problem stems from the changes to `BotFrameworkAdapter::ProcessActivity` which used to just call `JwtTokenValidation::AssertValidActivity`, but now calls `JwtTokenValidation::AuthenticateRequest` and the subtle bug there is that `AuthenticateRequest` which no longer checks for whether or not auth is disabled and then ends up adding the emulators URL to the list of trusted URLs with `MicrosoftAppCredentials.TrustServiceUrl`. This doesn't hurt right away and instead hurts later when the `MicrosoftAppCredentials::ShouldSetToken` method checks if the URL is trusted to determine if it should be sending a `Bearer` token to it and then tries to aquire the token which of course fails because the application identity is not set. Whew... that hurt my head. 🤕

Ok, so I now believe the fix that is needed is for `JwtTokenValidation::AuthenticateRequest` to actually consider whether or not authentication is enabled and, if not, simply return early like `JwtTokenValidation::AssertValidActivity` used to. (SIDE NOTE: `JwtTokenValidation::AssertValidActivity` is no longer called.)

I will test this out locally in my branch (with a proper test this time) and get a PR in ASAP if it seems to be working correctly.
