### ISSUE TITLE
[LG] Support evalTemplate function that can return a requested number of variations

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2266]
I’d like to be able to use the LG sub-system to not only come back with a single resolution at random but a specified list of variations. This is especially helpful in a case where I’m trying to manage all of my bot’s constituent response parts through LG. 

With this definition 
```markdown
# SuggestionsList
- [AddTodo]
- [ShowTodo]
- Help
- Cancel

# AddTodo
- Add a todo
- please add a todo

# ShowTodo
- Show my todo
- Please show my todo list

# All-Suggestion
- \n [Suggestions={join(evalTemplate(‘SuggestionsList’), ‘ | ’)}

# 2-Suggestions
- \n [Suggestions={join(evalTemplate(‘SuggestionsList’, 2), ‘|’)}
```

If I call `All-Suggestion`, I should see` [Suggestions=Add a todo | Show my todo | Help | Cancel]`

If I call `2-Suggestions`, I should see `[Suggestions=Add a todo | Show my todo]`

At the core, here’s the signature for `evalTemplate` function - 

Parameters - (templateName, numberOfItemsInList = default: all, options)

**Comment by boydc2014** [comment]
How to pass parameters to this evalTemplate? 

and a little bit in consitent of the naming of lgTemplate function,

i don't have a good suggestion yet.

**Comment by vishwacsena** [comment]
Called out the signature at the bottom of my original post - I’d expect the following behavior - 

evalTemplate(foo, options) to return all items in the foo template, fully resolved, using the options specified. 

evalTemplate(foo, 2) to return first 2 items from the list, fully resolved. 

evalTemplate(foo, 2, options) to return first 2 items from the list, fully resolved, using the options specified.

**Comment by boydc2014** [comment]
> Called out the signature at the bottom of my original post - I’d expect the following behavior -
> 
> evalTemplate(foo, options) to return all items in the foo template, fully resolved, using the options specified.
> 
> evalTemplate(foo, 2) to return first 2 items from the list, fully resolved.
> 
> evalTemplate(foo, 2, options) to return first 2 items from the list, fully resolved, using the options specified.

I see, what if my option is just a number?

**Comment by boydc2014** [comment]
Related to another topic #2272 , i was thinking how about we use templateName!() to return all evaluations, and let user do the pick, like

`{take(Hello!(), 2)} `

how about that

**Comment by vishwacsena** [comment]
Super subtle.. I didn't get it until I looked at very very closely. 

Could we do {Hello().all}? Or try a different prefix/ suffix operator?

**Comment by vishwacsena** [comment]
@boydc2014 we should close on this. Is your latest thinking that we do [foo] to get all variations and {foo()} to get one? Can you help clarify? That to me still is super subtle. I’d prefer we leave [foo] as well as {foo()} untouched and I like {takeAll(Hello, params)} where the argument to takeAll is a template name as well as any parameters you want to pass in for resolution. 

Thoughts?

**Comment by vishwacsena** [comment]
Tracked via #2325
