### ISSUE TITLE
[Adaptive] EditSteps with StepChangeTypes.InsertStepsBeforeTags is not possible

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2268]
We need to ensure that `Tags` is exposed as a configurable property on all steps. This is available on Dialog but not exposed through Adaptive steps. The following snippet of code results in the following error - `The property or indexer 'Dialog.Tags' cannot be used in this context because the set accessor is inaccessible (CS0272) [TestBed]`

We should also update the schema with this change

```C#
new TextInput() {
    Tags = new List<String>() {

    },
    Prompt = new ActivityTemplate("[Message]"),
    Property = "turn.userName",
    AllowInterruptions = true
},
```

**Comment by vishwacsena** [comment]
We need to expose the tags property on dialog to be configurable. Also bears schema impact so we should consider front loading this work as well as test to ensure that the EditSteps step with the StepChangeTypes.InsertStepsBeforeTags works E2E.

**Comment by Stevenic** [comment]
There's also a question around do we pre-define a few tags?  For instance, maybe every `InputDialog` has an "input" tag. This would make it easy to add steps before the next input.
