### ISSUE TITLE
Incorrect parameter name - Sending Cards and Attachments

### ISSUE THREAD

**Issue by joescars** [Microsoft/botbuilder-dotnet#227]
On this wiki page:
https://github.com/Microsoft/botbuilder-dotnet/wiki/Sending-Cards-and-Attachments

The parameter inside the CardAction needs to be updated to title

Currently
```c#
buttons: new CardAction[] { new CardAction(text: "buy") })
```

This needs to be updated to
```c#
buttons: new CardAction[] { new CardAction(title: "buy") })
```

**Comment by cleemullins** [comment]
Thanks This looks like a bug. Interested in submitting a PR? 

If not, I'll add it to my backlog.

**Comment by JonathanFingold** [comment]
I've updated the **Cards and attachments** page on the wiki to set the **title** property, instead of **text**.

@cleemullins , If this is not a repo issue, please close.
