### ISSUE TITLE
[LG] Use template name as function instead of `lgTemplate` function to refer template 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#2272]
**Context**
Currently if one lg template want to refer another template, two approach can be used,
1. `[templateName(args)]`, this can only be used in single line mode
2. {lgTemplate('templateName', args...)}, designed for multiple-line mode (also work in single line mode)
```
# Hi
- hi
- hello

# welcome (name)
- [Hi] {name}                                         // approach 1
- {lgTemplate('Hi')} name                               // approach 2
- ```@{lgTemplate('Hi') name```                    
```  

**Is your feature request related to a problem? Please describe.**
The problem is that `lgTemplate` is not intuitive or convenient to user.  People don't know approach 2, unless we teach them, and people always mis-typo the first argument, which need to be quoted. Overall, this requires more typing, be more tedious, more error prone, it's also less readable.  

**Describe the solution you'd like**
Instead of using `lgTemplate`, i want to able to just use template name as refence in any context. For example:
```
# Before
- {lgTemplate('Hi')}
- {lgTemplate('Welcome', name}}
- {join(foreach(alarms, x, lgTemplate('ShowSingleAlarm', x)), ","} 
# After
- {Hi()}             
- {Welcome(name)}
- {join(foreach(alarms, x, ShowSingleAlarm(x)), ","} 
```
You will see the new approach results in simpler syntax, more concise, more readable, less error-prone. requires almost no effort to learn. 

**Additional context**
One concern is the conflict with built-in functions, I prefer template override the function, and we should use Uppercase as template name will help this issue.  I do think this more natural way and more concise syntax certainly overweight this issue. 

[enhancement]

**Comment by vishwacsena** [comment]
We should do this as long as 

1. Users can continue to use [Foo] to refer to a template. We should add support for [Foo](path) and drop everything in (path) while parsing so users can use markdown link notation in renderes that support markdown rendering. 
2. In case of name collisions between template names as well as prebuilt functions, we should have template name trump prebuilt function. We should throw a warning message of this collision. Users can use prebuilt.xxxx to refer to a prebuilt function in case of collisions. 
3. Users can always use prebuilt.xxxx to refer to prebuilt templates.

**Comment by vishwacsena** [comment]
@boydc2014 isnt this done? Can this be closed?

**Comment by vishwacsena** [comment]
Tom says so.
