### ISSUE TITLE
Channel.cs tries to make Slack use suggested actions

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#2291]
## Version
master branch

## Describe the bug
Slack does not support suggested actions. Suggested actions are rendered as text, as can be seen in [this customer](https://github.com/microsoft/BotFramework-Services/issues/82)'s screenshot:
![изображение](https://user-images.githubusercontent.com/18035628/58270306-1dca3880-7d92-11e9-996e-48ed9ae36f46.png)

However, [Channel.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L36) acts as though Slack does support suggested actions:

```c#
                case Connector.Channels.Slack:
                case Connector.Channels.Telegram:
                case Connector.Channels.Emulator:
                case Connector.Channels.Directline:
                case Connector.Channels.Webchat:
                    return buttonCnt <= 100;
```

This problem is presumably in the other SDK languages as well.

## To Reproduce
1. Connect a bot to the Slack channel
2. Have the bot use a choice prompt with the list style set to "auto"
3. Observe that the choices are text instead of buttons

## Expected behavior
The SDK should acknowledge that Slack doesn't support suggested actions, or the Slack connector should convert suggested actions into Slack buttons

## Additional context
I don't think there's any need to have the Slack connector support suggested actions since buttons can already be easily implemented with hero cards

[bug]

**Comment by v-kydela** [comment]
@cleemullins - Has anyone looked at this?

**Comment by v-kydela** [comment]
@cleemullins - Who is in charge of triaging these issues?

**Comment by v-kydela** [comment]
@johnataylor - Can you comment on this?

**Comment by haacked** [comment]
I ran into [this recently too](https://github.com/microsoft/botbuilder-dotnet/issues/3974).

> The SDK should acknowledge that Slack doesn't support suggested actions, or the Slack connector should convert suggested actions into Slack buttons.

I followed the documentation on how to [implement sequential conversation flow](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp).

My expectation was that if I follow the docs, I'd get a nice interactive choice rendering in Slack. That's sort of the reason I'm choosing Microsoft Bot Framework and ABS in the first place. So I don't have to think about every platform I target in most mainline cases.

So my $0.02 would be to update the Slack connector to convert suggested actions into Slack buttons.

Or if the idea is people should not use suggested actions, add an obsolete warning on them and update the existing docs to describe how people should implement interactive choice options with the bot framework.

**Comment by haacked** [comment]
A third option is to simply update the docs I mentioned to use `ListStyle.HeroCard`. Though not sure if that causes issues for other platforms.

Might be nice if there's a way to have a fallback style. So I could have a choice that renders as `SuggestedActions` for platforms that target it, but fallback to `HeroCard` if the target platform doesn't support it.

**Comment by v-kydela** [comment]
> Might be nice if there's a way to have a fallback style. So I could have a choice that renders as `SuggestedActions` for platforms that target it, but fallback to `HeroCard` if the target platform doesn't support it.

That's what `ListStyle.Auto` already does

**Comment by haacked** [comment]
Ah, thanks! I looked at the docs for `ListStyle.Auto` and it says,

> Automatically select the appropriate style for the current channel.

In looking at the code, `ListStyle.Auto` is the default, which as my original issue points out, renders choices as text in Slack. Just to be sure, I explicitly set the `ListStyle` to `ListStyle.Auto` and I still got a text response.

So it seems to me the bug is that when you set the `ListStyle` of a `ChoicePrompt` to `ListStyle.Auto`, it should choose `ListStyle.HeroCard` for Slack. That seems to me to be a more "appropriate style" than a text response.

**Comment by v-kydela** [comment]
@haacked - Yes, that is why this bug was raised that you're commenting on now
