### ISSUE TITLE
[Adaptive] JSON Schema references are broken

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2297]
Our $schema reference does not exist which breaks schema validation.

Our .schema files refer to this:
    $schema": "https: //raw.githubusercontent.com/Microsoft/botbuilder-tools/**master**/packages/DialogSchema/src/dialogSchema.schema",
This was fine until we move DialogSchema to V.Future which means it should be:
    $schema": "https: //raw.githubusercontent.com/Microsoft/botbuilder-tools/**V.Future**/packages/DialogSchema/src/dialogSchema.schema",
That at least makes schema validation work, but V.Future is not an ideal location.  There are a couple of alternatives:
1) We could tie it to our releases--that is pretty ugly though since the meta-schema is unlikely to change most of the time and it would require updating every .schema file when we do a new release.  
2) We could pick a stable URL to put it at and add a version to the path.  I think this is the better solution.  My proposal would be https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/declarative/v1.0/dialogSchema.schema.

[bug]

**Comment by chrimc62** [comment]
Talked to @vishwacsena and we have the same issue with the SDK .schema files.  My proposal would be
that we put all schemas on botframework-sdk in the already existing schemas directory.  Since they are language independent.  This would include the meta-schema, the component .schema files and sdk.schema created by combining all of the component .schema files with dialogSchema.   This also makes changing the .schema files easier since they can use relative references to the meta-schema--it would only be composer references that would need to change for a new version.  
The challenge is versioning since the files themselves contain explicit paths to the meta-schema for .schema files and to the sdk.schema for declarative composer files.  It is also the case, that most changes are likely to be by addition, not breaking so most versions will not be incompatible.
We have a couple of choices:
1) Version with the SDKs.  I don't like this option since the schema is language independent and will frequently be stable across multiple releases.  (Especially the meta-schema.)  If we version with the SDK, then people will have to update their own composer files and .schema files.  If they don't then we are relying on cross-version compatibility anyway.
2) Give the schema their own versioning scheme using branches.  I much prefer this because it better reflects the pace of schema changes.  To develop new schema you would work in the new schema version branch and use relative paths to refer to the meta-schema.  Samples would explicitly refer to the new version branch when they are published. 
Putting this all together.
1) Create a v0.1 branch in Botframework SDK.
2) Put meta-schema in schemas\declarative\meta-schema.schema.
3) Put all component .schema files in schemas\declarative\components and update them to point to the meta-schema with a relative path.
4) The result of dialogSchema on the components would be at schemas\declarative\sdk.schema
5) Composer files would point to  https://raw.githubusercontent.com/microsoft/botframework-sdk/v0.1/schemas/declarative/sdk.schema
6) External components would point to https://raw.githubusercontent.com/microsoft/botframework-sdk/v0.1/schemas/declarative/meta-schema.schema
As long as things were non-breaking we could update that branch.  To make breaking changes we would create a new branch.
@luhan2017 @cwhitten @cleemullins  @sgellock @vishwacsena @carlosscastro  @tomlm  this make sense to you?

**Comment by chrimc62** [comment]
Vishwac and I talked some more.  And we are going to tie the schema version with the major.minor SDK version.  I will also add minimum runtime required to the sdk.schema so we can enforce that.  In addition, I will add to dialogSchema the ability to update the meta-schema pointers (and eventually translate if needed) and also add to dialogLint the ability to update the schema pointers.  
To prepare for a new release we would:
1) Create a new botframework-sdk branch for that version.
2) use dialogSchema to update the component schemas to the new version and update the minimum reqiured runtime if needed of sdk.schema.
3) Update our samples to point to the new sdk.schema.
Using branches lets us compare changes easily and this allows .dialog files to keep using the old schema as long as their runtime is beyond the mininmum.

**Comment by chrimc62** [comment]
The one thing we lose by doing this is the easy versioning packaging of code and declarative.  A much simpler thing to do is to update the tooling to allow easily updating component.schema or .dialog files and move the component.schema into the dotnet repository.   This makes it easier for now and the tools would be useful even if we revisit this when we decide to do additional languages.  Unless anyone objects, I'm going to do this.

**Comment by vishwacsena** [comment]
We should take this for 4.6 since this cleans up our entire schema story as well as enables us to continue to innovate in a clean and predictable way going forward.
