### ISSUE TITLE
Send directly to conversation does not work

### ISSUE THREAD

**Issue by ziad-akiki** [microsoft/botbuilder-dotnet#2306]
I am using the code below to forward a message from one conversation to another. Both conversations are created from the same bot. This only works if the service URL ***is not*** `http://directline.botframework.com`. For example, from the local emulator to the webchat controls it works properly, but the other way around the code fails with a `403 Forbidden` error.

```
var credentials = Configuration.GetSection("Credentials");
var account = new MicrosoftAppCredentials(credentials[MicrosoftAppCredentials.MicrosoftAppIdKey], credentials[MicrosoftAppCredentials.MicrosoftAppPasswordKey]);
var client = new ConnectorClient(new Uri(serviceUrl), account);
if (!MicrosoftAppCredentials.IsTrustedServiceUrl(serviceUrl))
    MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.Now.AddDays(7));
await connectorClient.Conversations.SendToConversationAsync(conversationIdentifier, turnContext.Activity)
```
Any idea what could be the issue?

**Comment by jwiley84** [comment]
Hi @ziad-akiki! I see you opened this issue all the way back in January. Are you still having this problem?

**Comment by ziad-akiki** [comment]
It's been a long time and I'm not working on the project anymore. Nevertheless here's how I mitigated the issue back then in case it is still present:

> var connectorClient = GetConnectorClient(serviceUrl);
>             activities.ForEach(a => a.Conversation = new ConversationAccount(id: conversationIdentifier));
>             return await connectorClient.Conversations.SendConversationHistoryAsync(conversationIdentifier, new Transcript(activities))

In a nutshell, I sent the activity as a conversation history by modifying the conversation ID before sending. I can't test the previous code currently but if needed please let me know, I'll allocate some time to test it.

**Comment by jwiley84** [comment]
I'll look into it, see if it's still an issue. My apologies for no one getting to this while you still needed the help.
