### ISSUE TITLE
The "locale" field in settings needs to be converted to lowercase

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2312]
## Version
v4

## Describe the bug
The current default value of Locale in Emulator Settings is en-US. However, it does not match the default value of adaptive dialog SDK, which is en-us.

## To Reproduce
1. Create a bot using `new ChoiceInput(){
                                Property = "dialog.FindCalendarEntry_Choice",
                                Prompt = new ActivityTemplate("[EnterYourChoice]"),
                                Choices = new List<Choice>()
                                {
                                    new Choice("First One"),
                                    new Choice("Second One"),
                                    new Choice("Third One")
                                }
                            },`
2. Run the bot with Bot Framework Emulator.
3. See the error.

## Expected behavior
Hopefully, the default value is en-us, instead of en-US.

## Screenshots
![image](https://user-images.githubusercontent.com/32658030/60698173-bb339300-9f20-11e9-9410-cda88b867b9b.png)
![image](https://user-images.githubusercontent.com/32658030/60698185-c7b7eb80-9f20-11e9-9bf1-91b7161a53b7.png)
[bug]

**Comment by ZhaoqingCui** [comment]
> @ZhaoqingCui could you please share the contents and name of the LG file you used to get this repro? So we can get an exact repro and be 100% sure we fixed this.
> 
> Also, what build are you using? Thanks

I think it is not relevant to LG file. `new ChoiceInput(){
                                Property = "turn.CreateCalendarEntry_Choice",
                                Prompt = new ActivityTemplate("[EnterYourChoice]"),
                                Choices = new List<Choice>()
                                {
                                    new Choice("Confirm The First One"),
                                    new Choice("Confirm The Second One"),
                                    new Choice("Confirm The Third One")
                                },
                                Style = ListStyle.SuggestedAction
                            },`  You can view the file below to see the sample dialog. 
[AddContactDialog - Copy.zip](https://github.com/microsoft/botbuilder-dotnet/files/3430922/AddContactDialog.-.Copy.zip)


By using ChoiceInput(), we have to change the default Locale 'en-US' to 'en-us', which is confusing and weird, to make the bot work. 
![image](https://user-images.githubusercontent.com/32658030/61864748-8c4b8400-af04-11e9-9eb5-664eb3862d04.png)

**Comment by carlosscastro** [comment]
I asked about the lg file because I created a test with a dialog just like yours and it worked. What build are you using?

**Comment by ZhaoqingCui** [comment]
> I asked about the lg file because I created a test with a dialog just like yours and it worked. What build are you using?

I guess it is fixed somehow. I am going to close this issue. Thanks a lot, guys.
