### ISSUE TITLE
[Adapative] Allow-interruption is not perform as expected

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#2314]
## Version
7/25 in 4.future

## Describe the bug
The bug is when we set allowInterruption to true, the design is to check with inputDialog first, before bubbuling it up. 

But actually, the original inputDIalog is not checked due to turnCount is still 0, which causing the inputDIalog itself is still looking for dialog.value instead of turn.acitivity.text

## To Reproduce
```c#
            var outerDialog = new AdaptiveDialog("outer")
            {
                AutoEndDialog = false,
                Recognizer = new RegexRecognizer()
                {
                    Intents = new Dictionary<string, string>()
                    {
                        { "Weather", "weather" },
                    }
                },
                Steps = new List<IDialog>()
                {
                    new NumberInput()
                    {
                        Prompt = new ActivityTemplate("age?"),
                        Property = "user.age",
                        AllowInterruptions = true,
                        OutputFormat = NumberOutputFormat.Integer,
                     }
                    new SendActivity("{user.age}"),
                },
                Rules = new List<IRule>()
                {
                    new IntentRule("Weather") {
                        Steps = new List<IDialog>() {
                            new SendActivity("In weather")
                        }
                    },
                }
            };
```

## Expected behavior
```
User: start
Bot: Age?
User: what's the weather after 2 pm?
Bot: In weather \\ not right, it should not be interrupted, because 2 is number
Bot: Age?
```
## RootCause
when allowInterruption = true, in inputDialog, we call recongizerInput first to decide whether to bubble, i  but this time, turnCount = 0, make the inputLooking for dialog.value
```C#
if (turnCount == 0)
 {
   input = dc.State.GetValue<object>(DialogContextState.DIALOG_VALUE, null);
}
```

So, note, first time **prebubble is runned, it awalys return false.** 

## Bug
If by design, we want inputDialog to process before bubble, then we should not set turnCount =0, it should becomes 1, once the initial prompt is sent. 

[bug]

**Comment by carlosscastro** [comment]
I'm not sure if I understood correctly, but FYI setting this to 1 is not the solution, at least not by itself, it would break a bunch of other things.

**Comment by Stevenic** [comment]
That's a good bug and explains an issue I was seeing... Let me think about that...
