### ISSUE TITLE
[Adaptive] Redundant single quotations around the self-defined collection in HttpRequest

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2315]
## Version
4.6.0-Daily-2019-07-17-01

## Describe the bug
Assume we want to post a meeting which has an unknown number of attendees. We will put all the information into a collection style string first, called user.finalContact, which might look like `[
    {
        'emailAddress':
        {
            'address':'x@gmail.com'
        }
    },
    {
      'emailAddress':
      {
          'address':'y@gmail.com'
      }
    },
    {
      'emailAddress':
      {
          'address':'z@gmail.com'
      }
    }
  ]
`. Note, there might be more or less than three attendees. We will use this  `new HttpRequest()
                            {
                                Property = "dialog.createResponse",
                                Method = HttpRequest.HttpMethod.POST,
                                Url = "https://graph.microsoft.com/v1.0/me/events",
                                Headers =  new Dictionary<string, string>(){
                                    ["Authorization"] = "Bearer {user.token.Token}",
                                }, 
                                Body = JObject.Parse(@"{
                                    'subject': '{dialog.CreateCalendarEntry_Subject}',
                                    'attendees': '{user.finalContact}',
                                ")
                            }` to make the API call. However, if we add ‘’ around {user.finalContact}, it disobeys the rules of JSON. The API call will fail. But without add ‘’ around {user.finalContact}, the compiler will complain. 

[bug]

**Comment by carlosscastro** [comment]
Hi! Please, more descriptive issue names will be extremely helpful in the future.

**Comment by carlosscastro** [comment]
For this one, shouldn't you be writing `'attendees': '\'{user.finalContact}\''`? Or that doesn't work?

**Comment by ZhaoqingCui** [comment]
> For this one, shouldn't you be writing `'attendees': '\'{user.finalContact}\''`? Or that doesn't work?

Sorry for not using descriptive names. I will pay attention to them in the future. Sorry.

I think you misunderstand my point: The system requires me to add unnecessary quotations while actually, I don't need them. As you know, JSON does not allow quotations around the collection (The square braces), which is **user.finalContact** in the description. But SDK does not recognize **user.finalContact** as a collection and still requires me to add single quotations around it, which will lead to redundant single quotations and API call fails.
