### ISSUE TITLE
[Adaptive] HttpRequest throws an exception when passed an empty body

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2316]
## Version
4.6.0-Daily-2019-07-17-01

## Describe the bug
Assume we want to accept a meeting using MS Graph API. The code is below `new HttpRequest()
                                    {
                                        Property = "user.acceptResponse",
                                        Method = HttpRequest.HttpMethod.POST,
                                        Url = "https://graph.microsoft.com/v1.0/me/events/{user.focusedMeeting.id}/accept",
                                        Headers =  new Dictionary<string, string>()
                                        {
                                            ["Authorization"] = "Bearer {user.token.Token}",
                                        }`. We do have anything to write in the body, so we leave it blank. Then, we run the bot and get the following error: 
![image](https://user-images.githubusercontent.com/32658030/61866329-915e0280-af07-11e9-828e-fd7419a5b846.png)

[bug]

**Comment by carlosscastro** [comment]
Hi! Please, more descriptive issue names will be extremely helpful in the future. For example: 

> Adaptive: Http step throws an exception when passed an empty body

This greatly helps triage and quick understanding ofthe bug.
