### ISSUE TITLE
[DCR] [Adaptive] Add ability to cache and use multi-model recognition results from LUIS

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2321]
We will use the ability provided by LUIS to have multiple LUIS apps results returned in a single call for composer needs. We will need to update the adaptive dialogs so a child’s LUIS recognizer results can be used by parent recognizer in case of consultation since the child’s LUIS call will include results for the parent LUIS app as well

**Comment by tomlm** [comment]
I need more information on how this should work.
