### ISSUE TITLE
[Adaptive] Update inspection middleware to work with adaptive dialogs

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2323]
Update the inspection middleware to work with new adaptive state. Add ability to return the current state of the conversation as a trace activity

Remaining work
- [ ] Update middleware to not wrap trace activity with a trace activity

**Comment by luhan2017** [comment]
I have tried that in adaptive dialog. it works well with conversationState and userState as following.

![image](https://user-images.githubusercontent.com/32191031/62109416-d5be1980-b2de-11e9-9864-ff004a6075d4.png)

**Comment by vishwacsena** [comment]
@luhan2017 - are you actively working on this?

**Comment by luhan2017** [comment]
@vishwacsena , @tomlm , I have create a pr here, could you help review on that? 
https://github.com/microsoft/botbuilder-dotnet/pull/2379
