### ISSUE TITLE
[Adaptive] Adaptive Skill Dialog in the SDK

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2324]
This should enable ability to call a remote skill as well as work with the skill protocol. Lauren and Ted will provide knobs and dials required for this step.

**Comment by Stevenic** [comment]
This should be similar to an `HttpRequest` that's sticky until it sees an `EndOfConversation` activity returned.

**Comment by vishwacsena** [comment]
@luhan2017 - are you actively working on this?

**Comment by luhan2017** [comment]
@zidaneymar (Qi Kang) is actively working on this, will keep you updated.

**Comment by vishwacsena** [comment]
@luhan2017 @zidaneymar can you add a spec of what you are implementing, specifically what properties will be configurable/ how they will be plumbed through from the environment settings (e.g. appsettings) etc? I hope we will continue to use the `settings` scope to pull required keys etc from the environment specific settings file. It would be a non starter to directly encode that in the action itself.

Also, it would be good to know if we have vetted the design with the VA team. I chatted with Lauren, Ted and they would be happy to review/ provide feedback

**Comment by vishwacsena** [comment]
@stevenic @johnataylor are looking into baking skill constructs into bot builder sdk. It will be good to drive this in a coordinated way with them.

**Comment by Kaiqb** [comment]
No porting req'd.
