### ISSUE TITLE
[Adaptive] [LG] Add support for structured LG template, enable ActivityTemplate definition through this mechanism

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2325]
# Activity template definition via Language Generation

For conversational apps (bots), we need to provide users an elegant way to express the shape of an activity that the bot sends down to the user. Although today, we have [Chatdown][1] that enables users to elegantly specify things like cards, suggested actions etc, we do not have a way to define a full blown outgoing activity in a simple text format. 

## Goals
- Provide an easy, text based way for users to define an activity 
- Provide ability for context aware composition for an activity (e.g. Speak composes with Speak on a target template etc)
- Do not bake activity as a core construct into the Language Generation sub-system. This is so we can keep the layering pure and composable across varied use cases for LG. 
- Provide a way to define sub structures (Chatdown style notations) that can compose up to an activity.

## Properties of interest
[Bot Framework activity][2] includes several fields that are of interest and might require the abilty for the user to customize or control but to start with the following are most widely used properties that should be configurable via an Activity template definition - 

| Property          | Use case                                                                                                                          |
|-------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| Text              | Display text used by the channel to render visually                                                                               |
| Speak             | Spoken text used by the channel to render audibly                                                                                 |
| Attachments       | List of attachments with their type. Used by channels to render as UI cards or other generic file attachment types                |
| SuggestedActions  | List of actions rendered as suggestions to user.                                                                                  | 
| InputHint         | Controls audio capture stream state on devices that support spoken input. Possible values can be accepting, expecting, ignoring   |

## Structured templates in LG
Today in the .lg file format, you can only do simple and conditional templates. 

Simple templates can include one-of variations and the variations can include references to other templates for composition as well as reference to expressions in the [common expression language][3].

To achieve the [goals](#goals), we will introduce a new `Structured template` concept in .lg file format. The applications of the `Structured template` include 
- activity definition
- card definition
- any [chatdown][1] style constructs

### Definition
Here's the definition of a structured template - 

```markdown
# TemplateName
> this is a comment
[Structure-name
    Property1 = <plain text> .or. <plain text with template reference> .or. <expression> 
    Property2 = list of values are denoted via '|'. e.g. a | b
> this is a comment about this specific property
    Property3 = Nested structures are achieved through composition
]
```

Here's an example of a basic Text template composition: 

```markdown
# AskForAge.prompt
[Activity
    Text = {GetAge()}
    Speak = {GetAge()}
]

# GetAge
- how old are you?
- what is your age?
```

Here's an example of text with suggested action

```markdown
# AskForAge.prompt
[Activity
    Text = {GetAge()}
    SuggestedActions = 10 | 20 | 30
]
```

Here's an example of a Hero card definition

```markdown
# HeroCard (params)
[Herocard   
    title = {params.title}
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
> {templateName()} always returns only one resolution from the template.
> all(templateName) returns a list of all resolutions from the template.(TODO)
    images = {all(HeroImages)}
    buttons = Show more cards
]

# HeroImages
- https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
- https://sec.ch9.ms/ch9/buildreactionbotframework_akajhsdi7_.jpg
```

Here is a richer example that puts them all together including a hero card can be defined as below

```markdown
# AskForAge.prompt
[Activity
    Text = {GetAge()}
    Speak = {GetAge()}
    Attachments = {HeroCard()}
    SuggestedActions = 10 | 20 | 30
    InputHint = expecting
]

# GetAge
- how old are you?
- what is your age?

# HeroCard (params)
[Herocard   
    title = {params.title}
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
    images = {all(HeroImages)}
    buttons = Show more cards
]

# HeroImages
- https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
- https://sec.ch9.ms/ch9/buildreactionbotframework_akajhsdi7_.jpg
```

By default any template reference is evaluated once during evaluation of a structured template. 

As an example, this returns the same resolution text for both `Speak` and `Text` properties. (TODO)

```markdown
# AskForAge.prompt
[Activity
    Text = {GetAge()}
    Speak = {GetAge()}
]

# GetAge
- how old are you?
- what is your age?
```

You can use the TemplateName!() (with trailing '!' after a template name) to request a new evaluation on each reference within a structured template.(TODO)

In this example, `Speak` and `Text` could come back with different resolutions because `GetAge` is re-evalauted on each instance.

```markdown
[Activity
    Text = {GetAge()}
    Speak = {GetAge!()}
]

# GetAge
- how old are you?
- what is your age?
```

Some times you might want to come back with a carousel of cards. Here's an example that achieves that - 

```markdown
# AskForAge.prompt
[Activity
> Defaults to carousel layout in case of list of cards
    Attachments = {forEach($cardValues, item, HeroCard(item)}
]

# AskForAge.prompt_2
[Activity
> Explicitly specify an attachment layout
    Attachments = {forEach($cardValues, item, HeroCard(item)}
    AttachmentLayout = list    
]

# HeroCard (title, subtitle, text)
[Herocard   
    title = {title}
    subtitle = {subtitle}
    text = {text}
    images = {all(HeroImages)}
    buttons = Show more cards
]

# HeroImages
- https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
- https://sec.ch9.ms/ch9/buildreactionbotframework_akajhsdi7_.jpg
```

Use of '|' will make a definition a list. You can use '\' as the escape character

```markdown
# AskForAge.prompt
[Activity
> With '|' you are making attachments a list. 
        Attachments = {HeroCard()} |
> You can use '\' as an escape character
        Suggestions = 10 \| cards | 20 \| cards
]
```

## Structured template composition
We will support the following composition behavior with structured template - 

1. Composition will be structure context aware, if the target template being referred is also a structured template, then 
    - the structure type must match e.g. ActivityTemplate can be referred to in another ActivityTemplate etc. 
    - the specific property under holds the template reference must exist in the target template.
2. References to simple or conditional response template can exist anywhere inside a structured template. 

As an example, reference to another structured template in `Speak` property, will result in resolution against that specific property and would result in a `property not found in template` error if the property does not exist in the target structured template. 

Here's an example: With this template definitions,  

```markdown
# T1
[Activity
    Text = {T2().text}
    Speak = foo bar {T3().speak}
]

# T2
- This is awesome

# T3
[Activity
    Speak = I can also speak!
]
```

Call to `evaluateTemplate('T1')` would result in the following internal structure: 

```markdown
[Activity
    Text = This is awesome
    Speak = I can also speak!
]
```

As another example, `evaluateTemplate('T4')` with the following definition will result in `Property 'Text' not found in structured template 'T5'`

```markdown
# T4
[Activity
    Text = {T5()}
]

# T5
[Activity
    Speak = I can also speak!
]
```

### Full reference to another structured template
You can include reference to a full structured template 
    - as a property in another structured template
    - as a reference in another simple or conditional response template

Here is an example of this style of reference in action: 

```markdown
# ST1
[MyStruct
    Text = foo
    {ST2()}
]
# ST2
[MyStruct
    Speak = bar
]
```

With this content, call to `evaluateTemplate('ST1')` will result in the following internal structure

```markdown
[MyStruct
    Text = foo
    Speak = bar
    
]
```

When the same property exists in both the calling template as well as callee, the content in caller will trump any content in the callee.

Here is an example:

```markdown
# ST1
[MyStruct
    Text = foo
    {ST2()}
]
# ST2
[MyStruct
    Speak = bar
    Text = zoo
]
```

With this content, call to `evaluateTemplate('ST1')` will result in the following internal structure 

```markdown
[MyStruct
    Text = foo
    Speak = bar
]
```
Note that this style of composition can only exists at the root level. If there is a reference to another structured template within a property, then the resolution is contextual to that property. 

## Functionality deprecated
To enable clear separation of activity composition, we will deprecate support for '||' as an ability to specify Text .vs. Speak properties. 

## Breaking change to evaluateTemplate API
evaluateTemplate will now return an object instead of a string. This is to enable the layer above to interpret any structured results returned. 

For simple template resolutions, we will continue to return a string for back-compat reasons. 

For structured templates, we will return the following
```json
{
    "$type": "structured-template-name",
    "property1": "value",
    "property2": [
        {
            "$type": "structure-name",
            "property1": ""
        }
    ]
}
```

## Chatdown style content as structured activity template
It is a natural extension to also define full chatdown style templates using the structured template definition capability. This helps eliminate the need to always define chatdown style cards in a multi-line definition

```markdown
    > Today, you would do this 

    # HeroCardTemplate
    - ```
    [Herocard   
        title = BotFramework Hero Card
        subtitle = Microsoft Bot Framework
        text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
        image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
        buttons = Show more cards
    ]
    ```
```

With this change, you can do this instead
```markdown

    # HeroCardTemplate
    [HeroCard
        title = BotFramework Hero Card
        subtitle = Microsoft Bot Framework
        text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
        image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
        buttons = Show more cards
    ]
```

## Existing chatdown style constructs supported
1. Typing
2. Suggestions
3. HeroCard
4. SigninCard
5. ThumbnailCard
6. AudioCard
7. VideoCard
8. AnimationCard
9. MediaCard
8. SigninCard
9. OAuthCard
10. Attachment
11. AttachmentLayout
12. [New] CardAction 
13. [New] AdaptiveCard
14. [New] EventActivity

### CardAction
```markdown
# CardAction (title, type, value)
[CardAction
> type can be 'openUrl', 'imBack', 'postBack', 'messageBack' 
    Type = {if(type == null, 'imBack', type)}
> description that appears on button
    Title = {title}
> payload to return as object.
    Value = {value}
]
```

### Suggestions
Suggestions can now support a full blown CardAction structure. 

```markdown
# AskForColor
[Activity
    SuggestedActions = {CardAction('red')} | {CardAction('blue') | {CardAction('See all choices', 'openUrl', 'http://contoso.com/color/choices')}}
]
```

### Adaptive card
Adaptive cards today are rendered via `[Attachment=cardpath.json adaptive]` notation.(TODO) We will continue to support this for external reference but will also support an inline definition for adaptive cards using a prebuilt function

`adaptiveCard(template-name)`

```markdown
    # GetColor.prompt
    [Activity
        Attachments = {json(GetColor.adaptive.card)
    ]

    # GetColor.adaptive.card
    - ```jsonc
    {
        // adaptive card definition
    }
    ```
```

### All card types
Buttons in any of the card types will also support full blown CardAction definition. 

Here's an example: 
```markdown
# HeroCardTemplate
[HeroCard
    title = BotFramework Hero Card
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
    image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
    buttons = {CardAction('Show more cards')} | {CardAction('See our library', 'postBack', 'http://contoso.com/cards/all')}
]
```

### Event activity
[Bot framework activity protocol][2] supports ability for bot to send a custom event activity to the client. We will add support for it via structured LG using the following definition. This should set the outgoing activities `type` property to `event` and can have a `name` property and a `value` property.

```markdown
[EventActivity
    name = some name
    value = some value
]
```

[1]:https://github.com/microsoft/botbuilder-tools/tree/master/packages/Chatdown
[2]:https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md
[3]:https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language

**Comment by DingmaomaoBJTU** [comment]
Please also ensure the following (already told dong ^_^):
1. Make activity template able to be translated correctly by MSLG tool
2. Add interface to query all possible text/speak for unit testing purposes.

**Comment by boydc2014** [comment]
Some minor issues:

1. I think a normal template should just return string instead of { type: "string", value: "value"}, so that the api is actually more easy to use and don't impact anything if people are not using structure lg. 

2. When 
```
# AskForAge.prompt
[Activity
    Text = {GetAge()}
    Speak = {GetAge()}
    Attachments = {HeroCard()}
    SuggestedActions = 10 | 20 | 30
    InputHint = expecting
]
```
I think we want to consider a case, when i want a list with only one item, probably i would suggest something like this
```
    Attachments = {HeroCard()} |                // with this "|" you are making this a list
```

3. ">" inside the markdown, looks like not syntax hightlighted right, which is definitely not a problem for this document, but that reminds me, should we allow ">" this in side structure definition.  I would prefer not in favor of the best readability

**Comment by vishwacsena** [comment]
@boydc2014 - updated spec for 1, 2. For the flexibility, let's support '>' inside a structure definition as single line comment. 

Also added a section for adaptive cards support.

**Comment by boydc2014** [comment]
> @boydc2014 - updated spec for 1, 2. For the flexibility, let's support '>' inside a structure definition as single line comment.
> 
> Also added a section for adaptive cards support.

Cool, keep comments is ok.  One thing about AdpativeCard, is that since we allow structure lg template return json(jobject), which means, not necessary to use a 'multi-line', just strcuture lg is good enough, the "$type" property will be auto-ignored by any json deserilization library. 


The other thing is some corner case i'm thinking that might be useful 
```
#T1
[MyStructure]

# T2
- {T1()}

# T3
- {T1()}   // return structure
- {T1()}   // return structure

#T4
- {T1()} hi // this will down-grade to text
```
For such case, i'm thinking it would be very convenient that we allow T2(), T3() to also return a structure, which means whether to return a structure is decided by whether you put template ref toghther with text. 

This is useful when we provide a "activity.lg" and\or "adpativeCard.lg" which means if i'm a user i would use something like

```
[import]("activity.lg")   // Activity(text) is defined here

# MyResponse
- {Activity("hello")}
```

**Comment by vishwacsena** [comment]
Addressed via #1190

**Comment by mareekuh** [comment]
- Speak/attachment/text makes sense - We'll need to be able to deal with mode-awareness as well. Speech in a car vs Mobile (phone), Kinect or desktop experience is not the same... How can we accommodate for this? Can we do this at a higher (dialog) level and if so, how would this manifest in the dialog files?

- Is it possible to have 'Speak' be populated as text? Or do 'text = speech' unless specified differently?

- how do we accommodate for the A (Answer) from QnA maker? Will this have a different type of mark-up in LG? And what about a follow-up Answer


Is my assumption correct that the structure defined in the proposal above for LG-Markdown, means it can have UX and be turned into 'GUI' for non-code users or for users new to the LG structure provided above?

Does the LG structure accommodate for incorporating /converting existing LG templates and dialogs created for/by Cortana (I am aware that our LG is similar to, but not the same as, the original LG. Are there things in the original LG that we're not yet accommodating for? What comes to mind are:
- Personality
- Modality
- Wait for input (from User)
- Partial sentence-templates (concatenated sentences)
- Description 
- Type (answer, value, slot etc)
- Condition

What would it take for Adaptive cards to be supportive natively in LG or the other way around (LG=Adaptive cards)?

**Comment by vishwacsena** [comment]
@mareekuh - answering your questions - 
> Speak/attachment/text makes sense - We'll need to be able to deal with mode-awareness as well. Speech in a car vs Mobile (phone), Kinect or desktop experience is not the same... How can we accommodate for this? Can we do this at a higher (dialog) level and if so, how would this manifest in the dialog files?

This typically is made available via activity.channelData property and is totally up to the specific channel to expose this information that either LG (via conditional responses) or dialog (branching in conversation flow) can handle. 

> Is it possible to have 'Speak' be populated as text? Or do 'text = speech' unless specified differently?

This again is controlled by the channel itself. As an example, AFAIK Cortana channel sets speak = text unless speak is explicitly specified. Given this is specific to a channel, we cannot do this automatically.

> how do we accommodate for the A (Answer) from QnA maker? Will this have a different type of mark-up in LG? And what about a follow-up Answer

QnA maker in LG, LU and dialog needs a separate spec and not addressed via this. That said, the infrastructure introduced here to have structured responses could be used by multi-turn QnA if we so design it to be. 

> Is my assumption correct that the structure defined in the proposal above for LG-Markdown, means it can have UX and be turned into 'GUI' for non-code users or for users new to the LG structure provided above?

Yes. That is correct. This only controls the underlying serialization format that is hand authorable but does not preclude us from adding UX on top. 

> Does the LG structure accommodate for incorporating /converting existing LG templates and dialogs created for/by Cortana (I am aware that our LG is similar to, but not the same as, the original LG. Are there things in the original LG that we're not yet accommodating for? What comes to mind are:

> Personality
> Modality
> Wait for input (from User)
> Partial sentence-templates (concatenated sentences)
> Description
> Type (answer, value, slot etc)
> Condition

The structured LG infrastructure enables you to define additional structures that are required. You can include all or any of these properties as needed in your definition. The ActivityGenerator layer is completely decoupled and can be adapted to Cortana specific needs.
