### ISSUE TITLE
[DCR] [Adaptive] Re-evaluate all events exposed via Adaptive dialog including protocol, dialog and adaptive events.

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2326]
Filing this ticket so we review and distill the set of events exposed via adaptive. The current set is a union of protocol level events, dialog events as well as adaptive events. we should pare back the list to only those that are backed by actual user scenarios as well as consider adding new events that help fulfill core unmet user needs.

**Adaptive events** 

| Event name         | Description/ purpose/ use case                                                      | Payload         |
|--------------------|-------------------------------------------------------------------------------------|-----------------|
| [ ] BeginDialog        | The active dialog has started.                                                      | N/A             |
| [ ] ActivityRecieved   | BF activity recieved. Use this for fine grained control of specific BF activity type | turn.activity   |
| [ ] RecognizedIntent   | The active dialog's recognizer has new information.                                 | turn.recognized |
| [ ] UnknownIntent      | The active dialog's recognizer did not detect an intent.                            | N/A             |
| [ ] CancelDialog       | The active dialog has been cancelled.                                               | N/A             |
| [ ] [REMOVE] EndDialog   | The active dialog has ended.                                                        | N/A             |
| [ ] RePromptDialog     |  Emitted when `DialogContext.repromptDialog()` is called. |  N/A               |
| [ ] [REMOVE] ResumeDialog       | ?                                                                                   | ?               |
| [ ] [REMOVE] SequenceEnded      | ?                                                                                   | ?               |
| [ ] [REMOVE] SequenceStarted    | ?                                                                                   | ?               |
| [ ] Error  | When an exception occurs it results in a call to `cancelAllDialogs()` with an "error" event   |  Exception raised| 

**Event handlers** 

| Name                                | Description                          | Base event       | Constraint                             | Use case | Keep ? |
|-------------------------------------|--------------------------------------|------------------|----------------------------------------|----------|--------|
| [ ] OnEvent                             | Generic event handler                |                  |                                        |          |        |
| [ ] OnIntent                            | Intent event handler                 | RecognizedIntent | turn.recognized.intent == 'IntentName' |          |        |
| [ ] OnUnknownIntent                     | Unknown intent event handler         | UnknownIntent    |                                        |          |        |
| [ ] OnBeginDialog                       | Begin dialog handler                 | BeginDialog      | N/A                                    |          |        |
| [ ] OnActivity                       \/ | Generic activity handler             | ActivityRecieved | N/A                                    |          |        |
| [ ] OnConversationUpdateActivity        | Conversation update activity handler | ActivityRecieved | ActivityTypes.ConversationUpdate       |          |        |
| [ ] OnEndOfConversationActivity         | End of conversation activity handler | ActivityRecieved | ActivityTypes.EndOfConversation        |          |        |
| [ ] OnEventActivity                     | Event activity handler               | ActivityRecieved | ActivityTypes.Event                    |          |        |
| [ ] OnHandoffActivity                   | Hand off activity handler            | ActivityRecieved | ActivityTypes.Handoff                  |          |        |
| [ ] OnInvokeActivity                    | Invoke activity handler              | ActivityRecieved | ActivityTypes.Invoke                   |          |        |
| [ ] OnMessageActivity                   | Message activity handler             | ActivityRecieved | ActivityTypes.Message                  |          |        |
| [ ] OnMessageDeletionActivity           | Message deletion activity handler    | ActivityRecieved | ActivityTypes.MessageDeletion          |          |        |
| [ ] OnMessageReactionActivity           | Message reaction activity handler    | ActivityRecieved | ActivityTypes.MessageReaction          |          |        |
| [ ] OnMessageUpdateActivity             | Message update activity handler      | ActivityRecieved | ActivityTypes.MessageUpdate            |          |        |
| [ ] OnTypingActivity                    | Typing activity handler              | ActivityRecieved | ActivityTypes.Typing                   |          |        |

If ActivityRecieved is added, nothing else should fire since the event loop should stop for that turn. 
CancelDialog or EndDialog cannot include actions that prolong beyond the current turn (e.g. cannot hold an input action)
If multiple events are eligible to fire, the first one will win.

**Comment by Stevenic** [comment]
We should setup a meeting to go through the current list of events.

**Comment by vishwacsena** [comment]
Also onTurn for OAuth

**Comment by Stevenic** [comment]
Also remove `StepChangeType.endSequence`. We shouldn't need this because of cancelAllDialogs()

**Comment by carlosscastro** [comment]
From a discussion with @stevenic: we should move away from using step count and mvoe towards recording in memory whether there was n interruption and act based off whether interrupted is true or false

**Comment by vishwacsena** [comment]
@tomlm is this complete with your last PR or is there any remaining work?

**Comment by vishwacsena** [comment]
Here's the final list of adaptive events and handlers for Ignite release. 

![image](https://user-images.githubusercontent.com/20918136/65174355-9d48db00-da05-11e9-963a-2a92fc8ad246.png)
