### ISSUE TITLE
Usage of FlexObject returned by LuisEntity.Resolution should be documented or changed.

### ISSUE THREAD

**Issue by dupuyjs** [Microsoft/botbuilder-dotnet#233]
Difficult to get access to the Resolution returned in LuisEntity. DotNet developers expect a property bag/dictionary implementation for property collections. Is there a simple way to access to the properties than the following code ?

```cs
            if (context.TopIntent != null)
            {
                foreach (LuisEntity item in context.TopIntent.Entities)
                {
                    //DATE
                    if (item.Type == "builtin.datetimeV2.date")
                    {
                        FlexObject resolution = item.Resolution;

                        var instance = JsonConvert.SerializeObject(resolution["values"][0]);
                        TimeEx time = JsonConvert.DeserializeObject<TimeEx>(instance);

                        this.State.Workitem.Date = DateTime.Parse(time.value);
                    }
                }
            }
```

**Comment by cleemullins** [comment]
The LUIS Middleware that's there is about to go away. If you look at PR #228, you'll see:

1. We're pulling forward a much more mature LUIS SDK codebase. 
2. That codebase is based around JObject and related constructs. 
3. The LUIS team (@emadelwany ) is doing that work, and will own it moving forward. That puts it on a much better forward looking path.

**Comment by cleemullins** [comment]
FlexObject has been totally removed by #425.
