### ISSUE TITLE
declarative OAuthInput method seem to have problems 

### ISSUE THREAD

**Issue by M-Gustuf** [microsoft/botbuilder-dotnet#2333]
## Describe the bug
The way to use oauthinput in declarative now have problems.
The JSON shows in picture will report an error that dialog.token is evaluated to be null, which means it fail to get a token.

## Screenshots
![image](https://user-images.githubusercontent.com/25506875/61939796-a9488b80-afc6-11e9-9e53-3ce19130cadd.png)

[bug]

**Comment by Stevenic** [comment]
@carlosscastro made a few comments on the PR but otherwise it looks good.
