### ISSUE TITLE
[Adaptive] TooManyRequests Exception should not happen when sending five identical cards in a short time

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2338]
## Version
4.6.0-Daily-2019-07-17-01

## Describe the bug
I am using HttpRequest to get all the meetings from my calendar by calling the API of MS graph. After getting this list, I will use a card to show the meetings to the user. However, when I send these cards frequently say, 5 times per 20 seconds, the TooManyRequests Exception will be thrown out. This exception should not happen because the above frequency should not be high enough to cause this error.

## To Reproduce
1. write a HttpRequest step. An example might be 
`new HttpRequest() {
                        Url = "https://graph.microsoft.com/v1.0/me/calendarView?startdatetime={utcNow()}&enddatetime={addDays(utcNow(), 1)}",
                        Method = HttpRequest.HttpMethod.GET,
                        Headers = new Dictionary<string, string>()
                        {
                            ["Authorization"] = "Bearer {user.token.Token}",
                        },
                        Property = "dialog.FindCalendarEntry_GraphAll"
                    }`

2. Show three of the meetings. You may decide which three to show by change user.Index. 
 `new SendActivity("[entryTemplate(dialog.ShowAllMeetingDialog_GraphAll.value[user.Index, dialog.ShowAllMeetingDialog_GraphAll.value[user.Index + 1], dialog.ShowAllMeetingDialog_GraphAll.value[user.Index + 2])]"),`

3. run these two steps several times in a not very high frequency, such as 5 times per 20 seconds. If the error is not shown, increase the frequency slightly instead of dramatically.

![image](https://user-images.githubusercontent.com/32658030/62110259-9f819980-b2e0-11e9-8160-b8aa5b5ab765.png)
The error will be thrown at line 1195 in Conversations.cs.

## Expected behavior
HttpRequest step should work fine under low frequency. 

## Screenshots
![image](https://user-images.githubusercontent.com/32658030/62021868-1db84000-b1fc-11e9-9d45-426bf3f9ade5.png)
![image](https://user-images.githubusercontent.com/32658030/62437204-db02e480-b774-11e9-9b43-691dca55932c.png)

[bug]

**Comment by tomlm** [comment]
We don't have any sort of throttling like this.  If you are getting this exception it is coming from the server that you are calling using HttpRequest.  This is not in our code.

**Comment by DingmaomaoBJTU** [comment]
![image](https://user-images.githubusercontent.com/16643193/62436485-5b741600-b772-11e9-86ad-9f34b8581730.png)
Here is the api which returns "too many requests". I don't think it is a msgraph issue because other skills calling ms graph never seen this issue before.

**Comment by tomlm** [comment]
again, this is not the SDK.  This is throttling done by the channel.  If the channel is a 3rd party channel such as facebook or slack the throttling is from them, and DirectLine has it's own throttling as well.

If you want to send 5 cards, you should send one activity with 5 attachments.
