### ISSUE TITLE
[Suggestion] Add Restart state in DialogTurnStatus

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2351]
## Version
4.4.5

## Describe the bug
Except for current dialog turn state, an extra dialog state "restart" might be helpful when we want to trigger a dialog restart/redispatch. Currently, we can only use turn result object to trigger a restart.

public enum DialogTurnStatus
    {
        Empty = 0,
        Waiting = 1,
        Complete = 2,
        Cancelled = 3,
        **Restart = 4,**
    }

**Comment by stevengum** [comment]
Per @stevenic, the DialogTurnStatus should not be a trigger, but an indicator of what occurred.
