### ISSUE TITLE
"Required entities for this event to fire" doesn't work

### ISSUE THREAD

**Issue by t-yangxi** [microsoft/botbuilder-dotnet#2354]
1. Set @food as a required entity (i.e. A list of any entities that must be found by the recognizer in order for this event to fire)
2. Expectation: when there's no @food entity found in what the user says, the intent handler shouldn't be fired. But instead, the event handler got fired and reported an error: "common.lg:Error occurs when evaluating expression ‘@food’: @food is evaluated to null"
![Screen Shot 2019-07-31 at 10 53 50 AM](https://user-images.githubusercontent.com/52472133/62235327-8e3c9980-b381-11e9-8f6b-118f3f1cebf9.png)

**Comment by tomlm** [comment]
I am 99% certain this bug isn't there any more as I have explicit unit tests for this scenario and it works.
