### ISSUE TITLE
[Adaptive] Parse luis result in turn state to a strong typed model (generate by luisgen)

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2363]
## Version
4.6.0-Daily-2019-07-17-01

## Describe the bug
Hard get luis result out as IRecognizerConvert object (generated by luisgen)
Luis result now saved in turn state with separate json format:
![image](https://user-images.githubusercontent.com/16643193/62348912-cd5d1d00-b530-11e9-8de4-53abcd57642c.png)

If we want to save and use luis result, we need to copy them out explicitly. But in code, developers would like to have a way to copy them out and translate them to IRecognizerConvert or host by themselves then passed to adaptive dialog, similar to the following:
![image](https://user-images.githubusercontent.com/16643193/62348920-d2ba6780-b530-11e9-9e24-94d46ba99288.png)

## Expected behavior
Have a API/step to translate luis result to strong typed luis model class.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
dialogStateManager.getPathValue<type>() will return a strong typed representation of the value held by the property path.
