### ISSUE TITLE
should return 400 bad request when request doesn't have an activity object

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botbuilder-dotnet#2372]
When request doesn't have an activity object, BotFrameworkHttpAdapter will throw an exception. Instead it should return 400 bad request for this case. here's the code: https://github.com/microsoft/botbuilder-dotnet/blob/f09bed819033ba4c4d52b7c04581f6347cf29d0c/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs#L63. should check if activity is null and set response code to 400 if it's null.

## Version
What package version of the SDK are you using.
4.5.1

## To Reproduce
in fiddler call the api/messages with empty payload

## Expected behavior
Give a clear and concise description of what you expected to happen.

400 bad request with message about activity not found in the payload

[bug]

**Comment by johnataylor** [comment]
fixed https://github.com/microsoft/botbuilder-dotnet/pull/2593
