### ISSUE TITLE
[Adaptive][Expressions] Sort should be supported in the next version

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2380]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Yes. I always want to output a list according to some sequence. For example, output a meeting list according to their starting times ascendingly. Find a meeting whose subject may contain "Lunch".

**Describe the solution you'd like**
The sort condition should support lambda expression.

**Additional context**
N/A

[enhancement]

**Comment by vishwacsena** [comment]
@boydc2014 can you check in with @ZhaoqingCui to see what exactly is needed here? Not sure if there is precedent here to do a sort of a collection of objects or if the ask is to have prebuilt sort function that can sort a collection.

**Comment by vishwacsena** [comment]
sort(collection, item1, item2, 'expression with item1 & item2')

**Comment by vishwacsena** [comment]
search - use existing where(list, x, x.title.contains('hello'))

**Comment by Danieladu** [comment]
> sort(collection, item1, item2, 'expression with item1 & item2')
