### ISSUE TITLE
[Adaptive] [LG] change LG, dialog systems to accept a expression engine instance

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2383]
Current LG subsystem creates its own instance of expression engine. This gets in the way of users expanding an expression library with a set of custom functions that is also available within the LG and dialog sub-systems. 

We should update LG and dialogs to be able to take and work with an expression engine instance that includes custom pre-built functions.

**Comment by Danieladu** [comment]
Template function and user-defined function wihch one should have higher priority. For example, there exists a LG file: 
```
# t1()
- hello

# t2
- {t1()}
```

And customer defines a function name: `t1`. We know template name is a runtime concept, but customized function is a pre-build concept. So when someone use `{t1()}`, which one should be called?
