### ISSUE TITLE
TurnContext.UpdateActivity does not apply a conversation reference

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#2388]
## Version
Latest

## Describe the bug
[`TurnContext.SendActivitiesAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TurnContext.cs#L209) uses `Activity.GetConversationReference` and `Activity.ApplyConversationReference` to ensure that outgoing activities have all the information the adapter and the connector client need in order to send the activities. This allows `TurnContext.SendActivityAsync` to work with activities that were generated using `MessageFactory` rather than just activities that were generated using `Activity.CreateReply` (which I have been advised to not use anymore). However, [`TurnContext.UpdateActivityAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TurnContext.cs#L288) does not apply a conversation reference to its activity, so in order to update an activity using `MessageFactory` you have to set the new activity's `Conversation` property manually. This is unintuitive.

## To Reproduce
1. Generate a new activity using a static method from the `MessageFactory` class
2. Set the new activity's `Id` property using a saved resource response ID
3. Use the new activity as the argument in `TurnContext.UpdateActivityAsync`
4. See null reference exception

## Expected behavior
`TurnContext.UpdateActivityAsync` should use the available conversation information just like `TurnContext.SendActivityAsync`.

## Screenshots
![Exception](https://user-images.githubusercontent.com/41968495/62731940-13562d00-b9d8-11e9-8468-a29fa0438a67.png)

## Additional context
I am happy to submit a PR for this myself if I am assigned to it.

[bug]

**Comment by josecarvajalrego** [comment]
Same here :(

**Comment by brunoslam** [comment]
Some problem here

**Comment by josecarvajalrego** [comment]
> Some problem here

This has worked for me on Teams:

Send card first time:
`                    IMessageActivity originActivity = MessageFactory.Attachment(_actionsCard.CreateAdaptiveCardActions("jose"));
                    userProfile.ConversationId = turnContext.Activity.Conversation.Id;
                    var response = await turnContext.SendActivityAsync(originActivity, cancellationToken);
                    userProfile.PreviousActivityId = response.Id;
`

Update card:
`  IMessageActivity responseActivity = MessageFactory.Attachment(_logTimeCard.CreateLogTimeCard2("2"));
                    responseActivity.Id = userProfile.PreviousActivityId;
                    responseActivity.Conversation = turnContext.Activity.Conversation;
                    await turnContext.UpdateActivityAsync(responseActivity, cancellationToken);`

Let me know if you need further assistance

**Comment by v-kydela** [comment]
I have noticed that in the Node.js SDK, you must not only set the updated activity's `conversation` property but also its `serviceUrl` property

**Comment by brunoslam** [comment]
I was trying to update the activity on bot framework emulator, but when i do it on Teams it works perfectly

**Comment by cleemullins** [comment]
@v-kydela, Thanks! Can you submit a PR for C#? 

(and for JS!)

**Comment by v-kydela** [comment]
I have submitted PR's for .NET and Node. I just examined the Python and Java source code and found that the problem exists in them as well, so I will attempt to fix those too.
