### ISSUE TITLE
[Adaptive] Break and Continue can be added to ForEach step

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2394]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
I think that break and continue should be added into SDK. For example, I want to iterate a list to find a specific item which meets my requirements. It would be acceptable to iterate the whole list if the item is at the end of list. However, if the item lies at the first or second position of list, it would be wasteful to iterate the whole list once. 

**Describe the solution you'd like**
Add a break and continue step to our SDK. Break if a condition is met. Continue if a condition is met.

**Describe alternatives you've considered**
We could use EditStep() to partially solve the problem. However, break and continue are the most basic feature of a SDK and should be considered. 

[enhancement]

**Comment by vishwacsena** [comment]
We will soon have jpath support in expressions. The recommendation for now is to use that to query/ filter the results prior to looping over the collection. 

Can you please close this issue if you believe that works and if not, update this with scenarios where it wouldnt?

**Comment by vishwacsena** [comment]
Implemented in latest master
