### ISSUE TITLE
[Adaptive] ConfirmPrompt zh-cn translation is not good

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2396]
## Version
What package version of the SDK are you using.

## Describe the bug
The ConfirmPrompt has some localized string hardcoded. For zh-cn version, two localization issues:
1. "是的" “不” sounds weird. Change to "是的" “不要”.
2. Looks like when “Yes” “No“ is expected, it has to be exactly “是的“， ”不“。 A variety of possible utterances for the Chinese yes or no should be supported, but right now a variation such as “不用了” does not work. 

## Expected behavior
1. Open an interface to allow hard-coded resource customization. .
2. If cannot, Change "是的" “不” to "是的" “不要”.
3. Support other Chinese yes or no.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Will be resolved via #2387
