### ISSUE TITLE
How to write unit tests for a Bot Framework v4 Dialog that requires the user to authenticate?

### ISSUE THREAD

**Issue by MilesWilde** [microsoft/botbuilder-dotnet#2404]
**Is your feature request related to a problem? Please describe.**
This is basically a continuation of this stack post because I haven't seen any pursuit by the creator:
https://stackoverflow.com/questions/53960869/how-to-write-unit-tests-for-a-bot-framework-v4-dialog-that-requires-the-user-to#comment101277202_53960869

**Describe the solution you'd like**
It would be extremely useful if I could authenticate a user in a dialog unit test because as it stands every single dialog I've made requires the user to be logged in.

**Describe alternatives you've considered**
I could test my dialogs by removing the OAuth portions but this seems like a lot of work to modify all of them/create test dialogs that model the main points and keep both of them updated.

**Comment by sgellock** [comment]
@MilesWilde the SO link you provide now has a solution for mocking.  Can you review and see if this addresses your need

**Comment by MilesWilde** [comment]
@sgellock Thanks for getting back to me. The answer is definitely good, but I'm really not sure how to implement this. 
I know the botframework SO and GitHub have different purposes so I'm not sure if I should ask my questions and paste code here. Should I ask in the SO post or is it ok to do it here?

**Comment by gabog** [comment]
Hi @MilesWilde, I am closing this one for now, feel free to reopen it if you have more questions.

Thanks
