### ISSUE TITLE
Add all public QnAMaker methods in ITelemetryQnAMaker

### ISSUE THREAD

**Issue by sachabruttin** [microsoft/botbuilder-dotnet#2405]
#### Is your feature request related to a problem? Please describe. 
In Virutal Assistant we register cognitives services like QnAMaker in the BotService and add them to a CognitiveModelSet. This class exposes QnAServices as a Dictionary<string, ITelemetryQnAMaker>. Unfortunately, this interface doesn't expose all the public methods of the QnAMaker class. 

#### What is the solution you are looking for?
Add the following method to ITelemetryQnAMaker

- [ ] ``Task<QueryResult[]> GetAnswersAsync(ITurnContext turnContext, QnAMakerOptions options = null)``
- [ ] ``QueryResult[] GetLowScoreVariation(QueryResult[] queryResult)``
- [ ] ``Task CallTrainAsync(FeedbackRecords feedbackRecords)``

#### What alternatives have you considered?
As a temporary solution, I create an extension class.

```csharp
public static class TelemetryQnaMakerExtensions
{
	public static Task<QueryResult[]> GetAnswersAsync(this ITelemetryQnAMaker qnaMaker, ITurnContext turnContext, QnAMakerOptions options = null)
	{
		return qnaMaker.GetAnswersAsync(turnContext, options, null);
	}

	public static QueryResult[] GetLowScoreVariation(this ITelemetryQnAMaker qnaMaker, QueryResult[] queryResult)
	{
		return ((QnAMaker)qnaMaker).GetLowScoreVariation(queryResult);
	}

	public static Task CallTrainAsync(this ITelemetryQnAMaker qnaMaker, FeedbackRecords feedbackRecords)
	{
		return ((QnAMaker)qnaMaker).CallTrainAsync(feedbackRecords);
	}
}
```

**Comment by cleemullins** [comment]
@sachabruttin  Thanks for the suggestion. There are a few things here to unpack:
1. The existing interface **ITelemetryQnAMaker** is designed explicitly for adding telemetry to the data plane of the services. for QnA Maker that means the GetAnswersAsync method. We've not added Training, as that's more of a control-plane event. We can't change that w/o breaking compat, as adding new methods to interfaces is a breaking change. 

2. The Solutions Team has created a [CognitiveModelSet](https://github.com/microsoft/botframework-solutions/blob/11efb3988a51c53b1012488b6b94356661d11dee/lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/CognitiveModelSet.cs) based on the Telemetry interfaces. I believe this is incorrect. 

I filed a [tracking bug](https://github.com/microsoft/botframework-solutions/issues/2110) in the solutions repo to track this.
