### ISSUE TITLE
[Adaptive] Support telemetry client in adaptive dialog

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2406]
This item tracks work to add support for telemetry client in adaptive dialog

**Comment by vishwacsena** [comment]
https://github.com/daveta/analytics/blob/master/adaptive/README.md

**Comment by vishwacsena** [comment]
Chatted with @scheyal and here is what we landed with for scoping - 

The bullet list below is the suggested instrumentation [field name][1], properties should be configured to be accessible via customdimensions
1. All new recognizers should participate and log recognition result anytime the recognizer is run. This should be similar to how the existing luisrecognizer participates in instrumentation. For all recognizers, log the recognizer configuration itself as well as the actual recognition result on recognition.
    - CrossTrainedRecognizerSet
    - MultiLanguageRecognizer
    - RecognizerSet
    - RegexRecognizer
    - ValueRecognizer
2. For adaptive dialog instrumentation, we should get to parity with waterfall dialogs and instrument the following
    - AdaptiveDialogStart
    - AdaptiveDialogCancel
    - AdaptiveDialogComplete
    - AdaptiveDialogAction
        - Include type of action in properties as `kind`
        - instance properties are all included in the property bag.
        - log this when an action begins.
        - All inputs are considered actions.
    - AdaptiveDialogTrigger

@tomlm 

[1]:https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0#schema-of-bot-analytics-instrumentation

**Comment by cleemullins** [comment]
@tomlm, this is a P0 R8 bug. Can you please update the thread?

**Comment by garypretty** [comment]
Spoke with @vishwacsena and I am happy to pick this up with the other telemetry work. Makes sense to tackle them as a group.

**Comment by tomlm** [comment]
Cool, a couple of thoughts
1.  **TelemetryLoggerMiddleware** should add  IBotTelemetryClient to **context.TurnState.Add<IBotTelemetryClient>()** so it is available to any component via **Context.TurnState.Get<IBotTelemetryClient>()**
2. We should consider instrumenting DialogContext.BeginDialog() EndDialg() etc. as that would give us telemetry for all dialogs regardless if they add additional telemetry or not.
3. I don't know if we are going to be able to log all instance properties of a declarative dialog, as they can be complex and also expressions.  Thoughts?

**Comment by garypretty** [comment]
@tomlm Thanks.
1. Sounds sensible - all being well it will be the new abstract class as opposed to IBotTelemetryClient, depending on feedback on my open PR for enabling page views (https://github.com/microsoft/botbuilder-dotnet/pull/3440)

2. I think this will make sense for some events. i.e. the new page views event we will have once we figure out the other PR. We probably still need to have tracking code in AdaptiveDialog / WaterfallDialog though as we track specific events for adaptive vs waterfall.

3. I haven't dug into the adaptive bits much yet - so I will comment on that as I get into it tomorrow.

**Comment by garypretty** [comment]
Closing as P0 functionality has now been merged.
