### ISSUE TITLE
TwilioAdapter constructor should not throw bare exceptions

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#2415]
## Version
What package version of the SDK are you using: 4.6.

## Describe the bug
The constructor code throws exceptions of type `Exception`.

## To Reproduce
1. Look at the constructor code: https://github.com/microsoft/botbuilder-dotnet/blob/a5e1a0492fffc57a80be7ddb41ca793a0a460e44/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs#L34-L47
1. See error.

## Expected behavior
These should probably throw `ArgumentException` exceptions.

## Additional context
Also, this last one should be another ArgumentNullException:https://github.com/microsoft/botbuilder-dotnet/blob/a5e1a0492fffc57a80be7ddb41ca793a0a460e44/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs#L49-L50

Also in SendActivitiesAsync:
https://github.com/microsoft/botbuilder-dotnet/blob/a5e1a0492fffc57a80be7ddb41ca793a0a460e44/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs#L82

[bug]

**Comment by cleemullins** [comment]
Fixed by PR #2420
