### ISSUE TITLE
[DCR] [Adaptive] Add a shorthand + memory path to access properties configured on an input

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2423]
Today, there is no way to access properties configured on an input (in LG) since these properties are not bound to and available via a memory scope. 

We should fix this so makers can refer to these properties in LG. 

As an example, we should have `~maxTurnCount` resolve to the value of the `maxTurnCount` property on the active input.  

| Who?  | Message                                                                   |
|------:|:--------------------------------------------------------------------------|
|User:  | Hi                                                                        |   
|Bot:   | Hello, I'm the demo bot. What is your name?                               |
|User:  | vishwac                                                                   |
|Bot:   | Hello, I have your name as 'vishwac'                                      |
|Bot:   | What is your age?                                                         |
|User:  | can you sing a song?                                                      |
|Bot:   | Sorry, I do not understand that. I'm looking for a number between 1-150   |
|User:  | tell me a joke                                                            |
|Bot:   | Sorry, I do not understand that. I'm looking for a number between 1-150   |
|User:  | blah blah blah                                                            |
|Bot:   | **Sorry, I'm not getting it. For now, I'll set your age to {~defaultValue}. You can say 'My age is \<your age>' to give me that information**   |
|Bot:   | Thank you. I have your age as 30                                          |

**Comment by tomlm** [comment]
This already exists, it's %foo -> dialog.options.foo 

Once we have path resolvers we should be able to make this look like options overlayed on top of dialog configuration. (aka, % is bound to the merged view of options and declarative options)

**Comment by vishwacsena** [comment]
@tomlm do we expose properties configured on an input dialog via dialog.options.xxx as well? E.g. if i have configured maxTurnCount property on a TextInput, will that also be available via dialog.options.maxTurnCount? 

Just making sure since the issue here is ability to access properties configured on an input.

**Comment by vishwacsena** [comment]
@tomlm @Stevenic - did we say instance properties will be available via %propertyNameXXX or turn.instance.propertyNameXXX?

**Comment by vishwacsena** [comment]
This should be fixed. 

dialog.options.xxx
this.options.xxx

%xxx is deprecated.

**Comment by vishwacsena** [comment]
In the code sample below, this.options.xxx does not work. What the is the correct way to access properties configured on Inputs? 

```C#
var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
{
    Generator = new TemplateEngineLanguageGenerator(),
                
    Triggers = new List<OnCondition>()
    {
        new OnBeginDialog() {
            Actions = new List<Dialog>() {
                new TextInput() {
                    Prompt = new ActivityTemplate("What is your name?"),
                    Property = "user.name",
                    AllowInterruptions = AllowInterruptions.Always,
                    MaxTurnCount = 3,
                    DefaultValue = "'Human'",
                    Validations = new List<string>()
                    {
                        "length(this.value) > 2",
                        "length(this.value) <= 300"
                    },
                    InvalidPrompt = new ActivityTemplate("Sorry, '{this.value}' does not work. Give me something between 2-300 character in length. What is your name?"),
                    DefaultValueResponse = new ActivityTemplate("Sorry, I'm not getting it. For now, let's set your name to '{this.options.DefaultValue}'.")
                }
            }
        }
    }
};
```

**Error**: 
```markdown
"Error occurs when evaluating expression 'this.options.DefaultValue': this.options.DefaultValue is evaluated to null"
```
