### ISSUE TITLE
[DCR] [Adaptive] Add a processInput action that indicates if user input should be processed by the active input

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2425]
Today, we use 'steps' run in a rule as part of consultation as the signal to indicate if active input should consider the user input 'consumed'. This does not work in cases where the user adds steps (e.g. logging, sending a message to user etc) but would still need the active input to reprocess user input. 

One solution is to formalize the current turn.processInput property into a step. We can review this and decide to keep the current setproperty work around as the formal solution. 

In the below scenario, when the user says `No, I'm 42`, the adaptive dialog's recognizer comes back with entity recognition for 42 which is handled via steps associated with an intent event however, there is no way for the maker to indicate the active confirm input to re-process user utterance. 

| Who?  | Message                                                   |
|------:|:----------------------------------------------------------|
|User:  | Hi                                                        |
|Bot:   | Hello, I'm the demo bot. What is your name?               |
|User:  | vishwac                                                   |
|Bot:   | Hello, I have your name as 'vishwac'                      |
|Bot:   | What is your age?                                         |
|User:  | I'm 36                                                    |
|Bot:   | I have your name as 'vishwac' and age '36'. Is that right?|
|User:  | No, I'm 42                                                |
|Bot:   | I have your name as 'vishwac' and age '42'. Is that right?|
|User:  | Yes                                                       |
|Bot:   | Thank you. You are all set.                               |

**Comment by carlosscastro** [comment]
From a discussion with @Stevenic: we should move away from using step count and mvoe towards recording in memory whether there was n interruption and act based off whether interrupted is true or false

**Comment by vishwacsena** [comment]
Add `turn.interrupted` boolean flag to indicate if the current turn is interrupted. User can set this to `false` for the active input to reprocess user utterance.

**Comment by vishwacsena** [comment]
Also tracks the work required to get away from using `this.stepCount` for re-prompting logic after consultation.

**Comment by Stevenic** [comment]
Fixed
