### ISSUE TITLE
[DCR] [Adaptive] Add a property to inputs that stops consultation

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2426]
## **Issue**
Current consultation bubbling logic does not provide for cases where user needs to stop bubbling when a specific constraint is met. We have a blanket, boolean allow interruption setting. 

However it is evident that when you use Language Understanding powered by a non-deterministic system such as LUIS, you would need the ability to short-circuit consultation bubbling when a specific constraint is met (e.g. LUIS recognizer came back with a specific intent and/ or LUIS recognizer came back with a specific entity value etc.)

## **Proposed change:**
- To all input dialogs, add a new property `DoNotInterrupt` that accepts a `an expression` as value. 
- This propoerty can only be set if `AllowInterruption` is set to true.
- The value (constraint specified as an expression) provided for `DoNotInterrup` property is evaluated **_only_** after the recognizer tied to that dialog runs for the given turn of the conversation. This is required so the expressions are always evaluated on fresh recognition results for the given turn of the conversation. 
- Upon evaluating the `DoNotInterrupt` property, if the value expression evaluates to
    - TRUE: then consultation bubbling stops and the input continues its evaluation based on properties configured on that input.
    - FALSE: then continue consultation bubbling and issue a reprompt on the input if no other rules fired on the consultation bubble.

## **Impact:**
Without this change users will have to explicitly add Rules to explicitly short circuit consultation bubbling and provide an opportunity for the leaf input dialo's recognizer to be run. With this change, users do not have to resort to handling the `RecognizedIntent` event to short-circuit consultation bubbling.

**Before this change**
```C#
var rootDialog = new AdaptiveDialog("root") {
    Rules = new List<IDialog>() {
        new EventRule() {
            Events = List<IDialog>() {
                AdaptiveEvents.BeginDialog
            },
            Steps = new List<IDialog>() {
                new NumberInput() {
                    Property = "user.profile.age",
                    Prompt = new ActivityTemplate("What is your age?"),
                    AllowInterruption = true
                },
                new SendActivity("I have your age as {user.profile.age}")
            }
        },
        new IntentRule() {
            Intent = "StopBubbling",
            Steps = new List<IDialog>() {
                // handle this intent via a rule to stop consultation bubbling.
            }
        }
    }
};
```

**After this change**
```C#
var rootDialog = new AdaptiveDialog("root") {
    Rules = new List<IDialog>() {
        new EventRule() {
            Events = List<IDialog>() {
                AdaptiveEvents.BeginDialog
            },
            Steps = new List<IDialog>() {
                new NumberInput() {
                    Property = "user.profile.age",
                    Prompt = new ActivityTemplate("What is your age?"),
                    AllowInterruption = true,
                    // New property to short circuit consultation bubbling.
                    // Having the value as an expression enables things like "#StopBubbling" 
                    // or "@number" or "#StopBubbling && @number" etc. 
                    DoNotInterrupt = "#StopBubbling"        
                },
                new SendActivity("I have your age as {user.profile.age}")
            }
        }
    }
};
```

## Implementation
- [ ] C#
- [ ] JS

**Comment by vishwacsena** [comment]
Another option is to switch `AllowInterruption` to be an expression with a different property name e.g. `InterruptWhen=<expression>` with the behavior to not consult up the parent unless the expression evaluates to true.

**Comment by Stevenic** [comment]
I agree with having one property versus two but the issue is I'm not sure how to run the expression after the recognizer is run.

**Comment by carlosscastro** [comment]
We decided to go with keeping AllowInterruptions, but making it an expression that defaults to true. You could add AllowInterrutions = "!#StopBubbling" and that would make this more sophisticated. This also requires the triggering of an event to request recognition from parents. Potential event names are RunRecognizer, OnPreActivity.
