### ISSUE TITLE
Twitter Channel

### ISSUE THREAD

**Issue by marcasmar94** [microsoft/botbuilder-dotnet#2428]
Will there be support for Twitter channel? If not what's the alternative ?

I can not see this feature anywhere or on the roadmap, we have clients demanding this channel.

Any updates?

**Comment by tdurnford** [comment]
I dont' believe the development team has any plans to add Twitter as an official BotFramework channel; however, the public BotBuilderCommunity has built a [Twitter Adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Twitter).

Also related to https://github.com/microsoft/botframework-sdk/issues/3123
