### ISSUE TITLE
Adaptive cards not rendered correctly on Facebook Messenger

### ISSUE THREAD

**Issue by mkchow5928** [microsoft/botbuilder-dotnet#2434]
## Version
4.5.1

## Describe the bug
Sending message with adaptive card activity attached does not render on Facebook Messenger

## To Reproduce
1. Register the bot with Facebook channel 
2. Send a message with adaptive cards attached.  The adaptive card includes image payload directly for the button.  

## Expected behavior
Adaptive card is converted and rendered with a Facebook equivalent UI.

## Screenshots
![image](https://user-images.githubusercontent.com/47866940/63372409-e2acb680-c33a-11e9-9c53-a1493ee9ee2b.png)

**Comment by jwiley84** [comment]
Hi @mkchow5928!

You also opened this issue [here](https://github.com/microsoft/botbuilder-dotnet/issues/2433) concerning the same behaviour, but on a different channel. I'm going to close this issue, so that we can track both over there, as they probably have the same root cause.
