### ISSUE TITLE
cannot use safe JSON deserialization for Dialog State object 

### ISSUE THREAD

**Issue by gmajian** [microsoft/botbuilder-dotnet#2437]
## Version
4.5.1

## Describe the bug
To save/load the dialog state, the bot need to serialize/deserialize the dialog states with JSON.
Currently, the dialog states contains a list of dictionaries of  objects, which is black box to the bot author programmer. To deserialize the string to the dialog state , the type information must be put into the JSON when searlizing the object ot string. For example, with Newtonsoft.Json, we need to specify `TypeNameHandling = TypeNameHandling.All` for serializer, just like the [botbuilder sample code](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/42.scaleout/DialogHost.cs#L25)

But it is not safe to put the type information into the serialized JSON string, because an attacker could modify the serialized data to include unexpected types to inject objects with malicious side effects. There are some published document about it:
 - [Do not use insecure deserializer ObjectStateFormatter](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2315-do-not-use-insecure-deserializer-objectstateformatter?view=vs-2019)
- [(MS Internal Security Requirement) Safe deserializers must be used in functions that process untrusted data](https://liquid.microsoft.com/Web/Object/Read/MS.Security/Requirements/Microsoft.Security.SystemsADM.10010#guide)

Per the above documents, when  we serialize/deserialize the dialog state, we should specify `specify TypeNameHandling = TypeNameHandling.All` for JSON serializer.  But currently it will cause exception in Bot Builder.

Bot Framework should provide a way to allow the bot to serialize/deserialize the dialog state safely.

## To Reproduce
1. download the sample code of BotBuilder: [42.scaleout](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/42.scaleout)
2. change the code in [the line](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/42.scaleout/DialogHost.cs#L25) from
```         
private static readonly JsonSerializer StateJsonSerializer = new JsonSerializer() { TypeNameHandling = TypeNameHandling.All };
```
to 
```
private static readonly JsonSerializer StateJsonSerializer = new JsonSerializer() { TypeNameHandling = TypeNameHandling.None };
```
3. Compile the project and run it
4. Use the bot emulator to talk to the bot

## Actuall behavior
Exception happens: 
```
Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Microsoft.Bot.Builder.Dialogs.DialogState'.

   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 75
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 160
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogExtensions.cs:line 18
   at Microsoft.BotBuilderSamples.DialogHost.RunTurnAsync(Dialog dialog, ITurnContext turnContext, JObject state, CancellationToken cancellationToken) in C:\src\others\BotBuilder-Samples\samples\csharp_dotnetcore\42.scaleout\DialogHost.cs:line 67
```
## Expected behavior
There is no error. 

## Screenshots
![image](https://user-images.githubusercontent.com/4533398/63395642-3d650300-c379-11e9-928b-2361d05fa4e0.png)

[bug]

**Comment by sbacha** [comment]
any updates on this ?

**Comment by EricDahlvang** [comment]
Related: https://github.com/microsoft/botbuilder-dotnet/issues/2450

**Comment by gmajian** [comment]
Hi this issue has been opened for 3 months, could someone work on them?

**Comment by EricDahlvang** [comment]
Hi @gmajian 

A Draft PR addressing this is here: https://github.com/microsoft/botbuilder-dotnet/pull/2944  This is awaiting discussion and review.

**Comment by EricDahlvang** [comment]
https://github.com/microsoft/botbuilder-dotnet/pull/3023 has been merged to master

AzureBlobStorage, MemoryStorage, and CosmosDbStorage now all provide a constructor allowing custom json serializer settings.  A few changes to BotState are also included: which enable TypeNameHandling.None  These changes are scheduled to be released with v4.7 early Dec

**Comment by kvbreddy** [comment]
@EricDahlvang , Can this issue be reopened.

The above issue is still not resolved. DialogState [serialization and deserialization](https://github.com/microsoft/BotBuilder-Samples/blob/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/csharp_dotnetcore/42.scaleout/DialogHost.cs#L61) works only if  `TypeNameHandling = TypeNameHandling.All`. `TypeNameHandling = TypeNameHandling.None` still does not work, because in most places [DialogInstance.State ](https://github.com/microsoft/botbuilder-dotnet/blob/c3b4141a56ccdd55c22da73b953bea58bef57819/libraries/Microsoft.Bot.Builder.Dialogs/DialogInstance.cs#L33) is used and directly casted to different types which requires `$type` to work.

For example, in our case :
[`var promptState = (IDictionary<string, object>)state[PersistedState];`](https://github.com/microsoft/botbuilder-dotnet/blob/c3b4141a56ccdd55c22da73b953bea58bef57819/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L196) throws an exception when using `TypeNameHandling = TypeNameHandling.None` as the `state[PersistedState]` is a JObject.

**Comment by EricDahlvang** [comment]
Good point.  The dialog stack isn't using property accessors internally. BotState works, but not the dialogs use of it.

Thank you for raising this.

**Comment by kvbreddy** [comment]
I have fixed this issue for OAuthPrompt Dialog in this [PR](https://github.com/microsoft/botbuilder-dotnet/pull/3294). May be someone can do a similar fix for other Dialogs as well.

**Comment by GustavoMoreiraPT** [comment]
Hello guys,

Any update on this?
I am experiencing the same issue when setting the JsonSerializer to TypeNameHandling.None.

Many thanks.

**Comment by okulygin** [comment]
any updates on this? it is still the issue for ComponentDialog

**Comment by cleemullins** [comment]
Per discussion, @johnataylor expects to close this out this week.

**Comment by johnataylor** [comment]
We can provide a sample in samples/experimental that shows users how they can avoid type serialization.

Issue in samples: https://github.com/microsoft/BotBuilder-Samples/issues/2870

Regarding the security documentation linked to from this issue. The stated concern here is loading types from untrusted stores. The bot state store in a normal deployment is a trusted data source.
