### ISSUE TITLE
Bot Not working with MS Teams. It is working fine in web chat

### ISSUE THREAD

**Issue by yadavsachin** [microsoft/botbuilder-dotnet#2438]
1. I have deployed bot to Azure using https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0
2. I have integrated bot with MS teams using Channels under Bot channel.
Using .Net Core 2.1

Where I can see the errors on why it is not working.

**Comment by hcyang** [comment]
@stevengum, any updayes?

**Comment by stevengum** [comment]
@yadavsachin can you provide the steps you used to contact the bot after enabling it on MS Teams? 

Are you using the [Teams App Manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload) or connecting to the bot via the link provided in the Channels?

![dotnet-issue-2438-0](https://user-images.githubusercontent.com/14935595/64190490-6088bb80-ce2b-11e9-860f-350d813547b6.png)


If you are using an App Manifest, I recommend using the Teams-integrated [App Studio](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio), which features a Manifest editor.

**Comment by stevengum** [comment]
@yadavsachin are you still running into this problem?

**Comment by yadavsachin** [comment]
Sure let me try.

**Comment by CezaryMarcjan** [comment]
@yadavsachin  we're assuming this is resolve. Please reopen if this is not the case. Thanks!
