### ISSUE TITLE
SendActivity commented out on BotContext

### ISSUE THREAD

**Issue by garypretty** [Microsoft/botbuilder-dotnet#244]
Sorry if I missed something around this over the last few days with so much change happening.  I was trying to use SendActivity on the context to send an activity immediately from middleware, rather than queuing up the activities and sending all at once.  Right now though the SendActivity method is commented out.  Is this going away? and if so what are the options for sending an activity immediately?

**Comment by drub0y** [comment]
So the problem was that the current design only allowed for fully buffered responses all the way up through the middleware pipeline. You couldn't "flush" early because the whole pipe

**Comment by Stevenic** [comment]
Not sure why this would have been commented out. It's the direction we're moving in.

**Comment by garypretty** [comment]
@cleemullins are you able to confirm the way to send activities immediately in c# at the moment? I.e. Not queueing them up in the responses list.

**Comment by cleemullins** [comment]
+1. I've been digging into this for 20 minutes now and I'm still not sure what happened. 

Either way, as @stevenic has already pointed out, this is the direction we're going. ETA on that direction is "A few days". 

To just force the issue, if you need a solution today, just call the code you see in the BotFramework Adapter:
```
MicrosoftAppCredentials appCredentials = await GetAppCredentials((context as BotFrameworkBotContext).BotAppId);
var connectorClient = new ConnectorClient(new Uri(activity.ServiceUrl), appCredentials);
await connectorClient.Conversations.SendToConversationAsync((Activity)activity).ConfigureAwait(false);

```
It might be easiest to inherit, then create a public "SendNow" method, that in turns calls the protected method.

**Comment by garypretty** [comment]
Thanks @cleemullins. Just working on middleware and this will tide me over.

**Comment by garypretty** [comment]
@cleemullins I tried to workaround the above, but to be honest it is probably just worth me waiting until we have the ability to send activities immediately in a few days.  Can we leave this open and you can let me know once this is in place?

**Comment by garypretty** [comment]
Closing this as this is handled within the M2 changes that @cleemullins has been working on.  I tested this on Chris' M2 branch over the weekend and all working as expected. @cleemullins Nice work on the M2 bits all up as well - I have built out some of the core extensions we have previously discussed based on the updated middleware pipeline and its all working great!
