### ISSUE TITLE
Inconsistency about whether resuming a prompt should count as a retry

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#2449]
## Version
master branch

## Describe the bug

In [Prompt.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L182), `ResumeDialogAsync` calls `RepromptDialogAsync` which calls `OnPromptAsync` with `isRetry` set to `false`:

```c#
public override async Task RepromptDialogAsync(ITurnContext turnContext, DialogInstance instance, CancellationToken cancellationToken = default(CancellationToken))
{
    var state = (IDictionary<string, object>)instance.State[PersistedState];
    var options = (PromptOptions)instance.State[PersistedOptions];
    await OnPromptAsync(turnContext, state, options, false, cancellationToken).ConfigureAwait(false);
}
```

However, in [ActivityPrompt.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ActivityPrompt.cs#L166), `RepromptDialogAsync` calls `OnPromptAsync` with `isRetry` set to `true`:

```c#
public override async Task RepromptDialogAsync(ITurnContext turnContext, DialogInstance instance, CancellationToken cancellationToken = default(CancellationToken))
{
    var state = (IDictionary<string, object>)instance.State[PersistedState];
    var options = (PromptOptions)instance.State[PersistedOptions];
    await OnPromptAsync(turnContext, state, options, true, cancellationToken).ConfigureAwait(false);
}
```

I know it's a rare case when a prompt would be resumed, but in such a case should the retry prompt be used or not?

[bug]

**Comment by Zerryth** [comment]
I made that change, specifically with the feedback from Gabo after he reviewed the [PR to add `isRetry` onto `ActivityPrompt.OnPromptAsync()`](https://github.com/microsoft/botbuilder-dotnet/pull/2086), which you can see in the [history here](https://github.com/microsoft/botbuilder-dotnet/pull/2086#discussion_r298375179).

It's specifically counting as a retry when **re**-prompting a user, so logically it made sense that it would go towards a retry count, and also aligned it in parity with JS (retries were completely missing from C# prior to the PR linked).

* Additionally, the `ActivityPrompt` class was just admittedly "weird" in comparison to the other "Prompts", as it is in `Microsoft.Bot.Builder.Dialogs` namespace and _does not_ derive from `Prompt` class, but instead directly from `Dialog`.
* Furthermore, deriving directly from `Dialog`, it's the only one you'll see that overrides the `Dialog.RepromptDialogAsync()` method

___
Given that it is re-prompting the user, I still agree with Gabo and think that it should in fact count as a retry (it's not simply use a "resume" on a prompt, implying it might've gone away to take care of something else first, before continuing where it had left off). That, and to remain in parity with what we had in the other language SDKS.

___

Thoughts, @gabog ?

**Comment by v-kydela** [comment]
@gabog - Have you looked at this?

**Comment by v-kydela** [comment]
It looks like `OAuthPrompt` doesn't implement its own `ResumeDialogAsync` or `RepromptDialogAsync`, so this issue only applies to `Prompt` and `ActivityPrompt`.

**Comment by v-kydela** [comment]
Here's a real-world example of a prompt being resumed: https://stackoverflow.com/questions/64765378/textprompt-reprompts-after-interruption
