### ISSUE TITLE
proposal: SendActivity should take a string or activity

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#245]
To get a little close back to the simplicity we had with `Reply()` I'd like to propose that we let `SendActivity()` take either an `Activity` or a `string`. When a string is passed a new activity of type `message` will be composed and delivered.

**Comment by cleemullins** [comment]
I’m surprised that’s not there. I added that code not long ago, and tested it.

Not clear yet how it got removed.

________________________________

**Comment by Stevenic** [comment]
I actually didn't look at the C# version of `SendActivity()`. The JS version I created doesn't support passing in a `string` yet but it feels like it should.

**Comment by Stevenic** [comment]
And to be clear I'm talking about at the `BotContext` level.  At the adapter level I think it should continue to speak raw activities because it needs to know the conversation reference info.

**Comment by garypretty** [comment]
@cleemullins do you still have the code? If not I am happy to add this and raise a PR if it helps?

**Comment by cleemullins** [comment]
The code looks like it was moved into the BotFrameworkAdapter. I need to put a plan together for how to approach the Single Middleware refactoring this week, and this seems like part of that.

**Comment by garypretty** [comment]
Just trying to do some tidying up where I can of any issues - this specific issue is handled by @cleemullins M2 branch and the ability to pass an activity or a string is present, so this will be resolved when that gets merged in.  Given that this was just a discussion point, not sure we need to keep this open?

**Comment by cleemullins** [comment]
This is done.  Current SendActivity takes either text or an IActivity. 

Current SendActivities takes an array of IActivity to support batching.
