### ISSUE TITLE
Allow customization of JsonSerializerSettings for AzureBlobStorage

### ISSUE THREAD

**Issue by nathanwinder** [microsoft/botbuilder-dotnet#2450]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

I am unable to provide custom JsonConverters for use in the AzureBlobStorage implementation.

**Describe the solution you'd like**

Accept either JsonSerializerSettings or JsonSerializer in the AzureBlobStorage constructor. A slightly better solution might be to wrap these in AzureBlobStorageOptions similar to how CosmosDbStorage does. 

**Describe alternatives you've considered**

The JsonConverterAttribute can be used as a workaround but is less desirable as it must be placed on each instance instead of global handling. It also requires a dependency on JSON.NET in assemblies that may be trying to avoid dependencies.

**Additional context**

[enhancement]

**Comment by hcyang** [comment]
hi @johnataylor, any updates? Just a reminder that this issue was assigned to you some time ago. Thanks.

**Comment by EricDahlvang** [comment]
The previous branch was deleted. Here is a new one: 

https://github.com/microsoft/botbuilder-dotnet/compare/master...eric/noTypeHandlingSerialization

@johnataylor can we take this change?

**Comment by cleemullins** [comment]
@EricDahlvang that change is bigger than I would have expected. We have this done in the CosmosDB Provider side. 

The *issue* with doing this, is the typename handling. Using a custom serializer is very fragile, and it opens up a full can of compat issues. 

@nathanwinder The easiest thing you could do it simply cut/paste the BlobStorageProvider, hack it up as needed, and call it the "NathanStorageProvider" and use it that way. Doing that would allow you to do whatever is needed.

**Comment by EricDahlvang** [comment]
@cleemullins the botstate changes are included to enable using the dialog stack while also not serializing type info.  I do not understand why the sdk allows custom json serialization for cosmosdb, yet if no type info is used (which is the recommended setting for security reasons), then it does not work with the dialog stack ootb.

**Comment by benbrown** [comment]
@ericdahlvang - hey eric, can you give us an update on this issue? It is > 90 days old now.

**Comment by EricDahlvang** [comment]
Waiting on review of https://github.com/microsoft/botbuilder-dotnet/pull/3023

**Comment by EricDahlvang** [comment]
Waiting on review of https://github.com/microsoft/botbuilder-dotnet/pull/3023

**Comment by EricDahlvang** [comment]
https://github.com/microsoft/botbuilder-dotnet/pull/3023 has been merged to master

AzureBlobStorage, MemoryStorage, and CosmosDbStorage now all provide a constructor allowing custom json serializer settings.  A few changes to BotState are also included: which enable TypeNameHandling.None  These changes are scheduled to be released with v4.7 early Dec
