### ISSUE TITLE
Incorrect Bot Content-Type

### ISSUE THREAD

**Issue by Peternator7** [Microsoft/botbuilder-dotnet#246]
When a request come through the connector from FB Messenger, the Content-Type is "application/json; charset=utf-8"

This causes the code in [ApplicationBuilderExtensions](https://github.com/Microsoft/botbuilder-dotnet/blob/f337eed828cdc77497c862a56723407a0f69556e/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/ApplicationBuilderExtensions.cs#L56) to return early.

```
if(request.ContentType != "application/json")
{
     response.StatusCode = (int)HttpStatusCode.NotAcceptable;
     return;
}
```

**Edit: This happened in webchat as well so it might be the connector version in general.**

**Comment by cleemullins** [comment]
Thanks for the bug report. 

I'll get this fixed on Monday. 

@drub0y: This looks like the code you're refactoring, as it's part of your new ASP.Net Integration code. 

Is there a standard / clean way to do this in ASP.Net?

**Comment by drub0y** [comment]
In WebAPI I'm working with the `HttpRequestMessage` where you get to work with a much nicer abstraction via [the `MediaTypeHeaderValue` class](https://msdn.microsoft.com/en-us/library/system.net.http.headers.mediatypeheadervalue(v=vs.118).aspx). 

Here in .NET Core I'm working at the raw handler level, but let me see if I can pull something in to help with parsing the header more cleanly to deal with all the wonkiness of media types.

Sit tight...

**Comment by drub0y** [comment]
@Peternator7 hey, can you let me know if this is working for you now? I tested it, of course, so it should be good, but I just want to make sure you're unblocked.

**Comment by Peternator7** [comment]
Confirming this is fixed :)
