### ISSUE TITLE
[Adaptive] [DCR] Rename addDialog, addEvent

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2471]
If you are defining an adaptive dialog you can specify a list of Actions.  If you have created a dialog, the method to add more actions is called AddDialog/AddDialogs.  I understand how that is more general, but the connection is not obvious from the naming.
Another is using Events to mean EventHandlers.  Same with AddEvent/AddEvents.

Filing this ticket to drive resolution + implementation on the right names for these.

**Comment by boydc2014** [comment]
My suggestions is to clearly distinguish event vs eventHandler, so an ideal data model to me is we pair event+handler to one group called "Reaction", then provide API to define a handler for an event, which looks like this
```C#

var dialog = new ApativeDialog();
dialog.On(new IntentEvent('IntentA')) = new IDialog() { ... } 
// if the above syntax is not avaiable in C# because of the "=", it can be the following
dialog.On('ConversationUpdate', new IDialog());

// if equals

dialog.AddReaction(new Reaction() {
  on: e,
  action: h
});
```

from a declartive perspective, the serialized format looks like this
```jsonc
{
  type: 'AdpativeDialog'
  reactions:  [
      {  
            on: { type: "IntentEvent", intent: "Hello" ...  }
            action: { type: "ListAction", actions: [...] }
      }
  ]
```

So an Reaction is On something then Do something, and a Dialog is a list of "on something do something", i feel this is very simple and clean, what do you guys think
