### ISSUE TITLE
Bot Telemetry not correctly instantiated for websocket connection

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#2474]
## Version
What package version of the SDK are you using.
4.5.1

## Describe the bug
Give a clear and concise description of what the bug is.
When connecting to a skill over websockets, the telemetry that is logged is missing the ActivityId and ConversationId that are used in Power BI to show dialog metrics. This appears to be because of the dependency on the HttpContext [here](https://github.com/microsoft/botbuilder-dotnet/blob/7f98f5a2c2cbd17010d71181a39ae3dd7378fb0d/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.WebApi/TelemetryBotIdInitializer.cs)

@lzc850612 - Please add anything I've missed.

## To Reproduce
1. Use VA with skill over websockets
2. View AppInsights data from conversations using this query:
```
customEvents
| project 
ActivityId = customDimensions.activityId,
ReplyActivityId = customDimensions.replyActivityId , 
operation_Name = operation_Name ,
ConversationId = session_Id ,
Text = customDimensions.text,
EventName = name, 
Time = timestamp, 
DialogStepName = customDimensions.StepName,
Date = timestamp,
DialogInstanceId = customDimensions.InstanceId,
DialogId = customDimensions.DialogId 
| where EventName startswith "Waterfall"
| order by Time desc
```
3. ActivityId and ConversationId are empty

## Expected behavior
Give a clear and concise description of what you expected to happen.
ActivityId and ConversationId should be logged for each activity that comes through.

## Screenshots
AppInsights Query Results:
![image](https://user-images.githubusercontent.com/27976702/64277681-c9d9fe80-ceff-11e9-8a55-b3cfdf0b7c82.png)

## Additional context
Related issues:
https://github.com/microsoft/botframework-solutions/issues/2155
https://github.com/microsoft/botframework-solutions/issues/2262

**Comment by garypretty** [comment]
Tracking PR #2580 which should fix this issue.

**Comment by lauren-mills** [comment]
Confirmed the PR fixes the issue
