### ISSUE TITLE
[Adaptive] Can't return an Array type in the ResultProperty of EndDialog

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#2475]
## Version
What package version of the SDK are you using.
4.6.0-Daily-2019-08-13-01

## Describe the bug
When trying to return an Array property as the ResultProperty of the EndDialog action, I get the following error "Can not convert Array to String". 

## To Reproduce
1. Set the ResultProperty of EndDialog to an array property.
2. Try to capture the result in the BeginDialog action.
3. Get error

## Expected behavior
Give a clear and concise description of what you expected to happen.
Should be able to return property of any type as the result of EndDialog.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
We should support string value, array as well as object in what can be passed in to a dialog via options as well as what can be returned from a dialog via EndDialog -> property.

**Comment by vishwacsena** [comment]
Try with the latest in 4.Future. This is probably fixed but if not, reactivate.
