### ISSUE TITLE
Bot Builder sporadically reports a BadRequest result from Slack API

### ISSUE THREAD

**Issue by TacticalVilius** [microsoft/botbuilder-dotnet#2479]
## Version
Microsoft.Bot.Builder - v4.5.1
Microsoft.Bot.Builder.Integration.AspNet.Core - v4.5.1
Microsoft.Bot.Configuration - v4.5.1
Microsoft.Bot.Connector - v4.5.1
Microsoft.Bot.Schema - v4.5.1

## Describe the bug
Exception thrown from Bot Builder when attempting to answer user via Slack bot. The error reported is a BadRequest response from the Slack API.

This happens every morning (Central European Time), however everything works fine after lunch and in the evening.

I don't know if the time of day has anything to do with it or if the problem occurs after a sufficiently long down time without use (which would be night time).

The same code has no problems when using an msteams bot.

## To Reproduce
Here are my steps, I have done this every morning 5 days in a row:

1. Go to your Slack bot
2. Write any input which should produce an answer from the bot
3. There is no answer, and you should see an exception in your logs

The same steps produce no error after lunch or in the evening at which time the bot answers as desired.

## Expected behavior
Slack bot integration works at all times, not sporadically.

## Additional context
Our code is running on Azure and we have a Bot Channels Registration with Slack and Microsoft Teams channels enabled. I have recreated the Slack Application from scratch using the following steps [link](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0) , but the problem persists.

When the error happens, the Azure Bot Channels Registration reports the following issue for Slack channel:

`There was an error sending this message to your bot: HTTP status code InternalServerError`

The internal server error refers to the exception thrown with stack trace:

`Operation returned an invalid status code 'BadRequest' `

> at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken)
   at ---our code line here---
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity identity, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)

The exception happens when executing the `SendActivityAsync` method:

```
private async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            string response = [we figure out the bot's response here]

            await turnContext.SendActivityAsync(response);
        }

```

`response` may contain HTML, but this same HTML works at other times, so I figure that can't be the issue.

Application Insights shows the following end-to-end transaction (our internal APIs redacted):

![image](https://user-images.githubusercontent.com/1832570/64411062-b4dea600-d08c-11e9-8388-009f96783a4c.png)

[bug]

**Comment by stevkan** [comment]
Can you check the web app configuration in Azure and verify if the "Always On" feature is enabled?

**Comment by TacticalVilius** [comment]
Hi @stevkan,

Yep, "Always On" is enabled

**Comment by stevkan** [comment]
Can you provide your bot's AppId. I would like to look at over some logs to see if any additional errors have been reported. Can you also specify the dates/times so I know where to look?

**Comment by stevkan** [comment]
The issue appears to be related to a call to this endpoint `/api/Events/Sticos_AI_Else`. I compared two instances, one that failed and one that succeeded. In both, the call is made and successfully received by the bot. A channel message is then sent from the bot back to the user which is received and processed. It is at this point the exception is made.

As you can see in these two responses, the first is missing a `message[0]` property in `customDimensions` while in the latter it is present. You're bot appears to be generating an "activity" that is missing necessary properties, namely the message. When it is received by Slack, it doesn't know what to do with it and produces the error.

I would look over your bot's logic as it relates to that API call double checking the kind of events it is generating, and why. Debugging and stepping thru will help narrow down the cause.

#### Failed response
```json
{
  "timestamp": "2019-09-10T07: 24: 18.7285426Z",
  "name": "",
  "conv_id": "",
  "cloud_RoleInstance": "RD28187897CBFF",
  "customDimensions": {
    "SerializationTimeMs": "2.3047",
    "messageActivity": "{\r\n  \"type\": \"message\",\r\n  \"timestamp\": \"2019-09-10T07:24:18.5410645Z\",\r\n  \"serviceUrl\": \"https://slack.botframework.com/\",\r\n  \"channelId\": \"slack\"\r\n}",
    "slackMessageCount": "1",
    "context": "{\r\n  \"activity\": {\r\n    \"type\": \"message\",\r\n    \"timestamp\": \"2019-09-10T07:24:18.5410645Z\",\r\n    \"serviceUrl\": \"https://slack.botframework.com/\",\r\n    \"channelId\": \"slack\"\r\n  },\r\n  \"botAccount\": {\r\n    \"id\": \"BML5WTS3C:T7XBR4SUB\"\r\n  },\r\n  \"botAccountInfo\": {\r\n    \"channelId\": \"slack\",\r\n    \"id\": \"Sticos_AI_Else\"\r\n  }\r\n}"
  },
  "customMeasurements": ""
}
```
#### Successful response
```json
{
  "timestamp": "2019-09-10T13: 15: 35.3055975Z",
  "name": "",
  "conv_id": "",
  "cloud_RoleInstance": "RD28187897CBFF",
  "customDimensions": {
    "message[0]": "{\r\n  \"message\": {\r\n    \"channel\": \"DML5WTVCJ\",\r\n    \"reply_broadcast\": false\r\n  },\r\n  \"response\": {\r\n    \"channel\": \"DML5WTVCJ\",\r\n    \"ts\": \"1568121335.001700\",\r\n    \"message\": {\r\n      \"type\": \"message\",\r\n      \"subtype\": \"bot_message\",\r\n      \"ts\": \"1568121335.001700\"\r\n    },\r\n    \"ok\": true\r\n  }\r\n}",
    "SerializationTimeMs": "0.098",
    "messageActivity": "{\r\n  \"type\": \"message\",\r\n  \"timestamp\": \"2019-09-10T13:15:35.1340312Z\",\r\n  \"serviceUrl\": \"https://slack.botframework.com/\",\r\n  \"channelId\": \"slack\"\r\n}",
    "slackMessageCount": "1",
    "context": "{\r\n  \"activity\": {\r\n    \"type\": \"message\",\r\n    \"timestamp\": \"2019-09-10T13:15:35.1340312Z\",\r\n    \"serviceUrl\": \"https://slack.botframework.com/\",\r\n    \"channelId\": \"slack\"\r\n  },\r\n  \"botAccount\": {\r\n    \"id\": \"BML5WTS3C:T7XBR4SUB\"\r\n  },\r\n  \"botAccountInfo\": {\r\n    \"channelId\": \"slack\",\r\n    \"id\": \"Sticos_AI_Else\"\r\n  }\r\n}"
  },
  "customMeasurements": ""
}
```

When the first response is received by the bot, it then generates the following:

```json
[
  {
    "timestamp": "2019-09-10T07: 24: 18.7910269Z",
    "name": "",
    "conv_id": "",
    "cloud_RoleInstance": "RD28187897CBFF",
    "customDimensions": {
      "SerializationTimeMs": "53.9625",
      "Exception": "{\r\n  \"StatusCode\": 400,\r\n  \"Response\": {\r\n    \"error\": {\r\n      \"code\": \"MissingProperty\",\r\n      \"message\": \"Slack API error\",\r\n      \"innerHttpError\": {\r\n        \"statusCode\": 200,\r\n        \"body\": {\r\n          \"ok\": false,\r\n          \"error\": \"no_text\"\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"ClassName\": \"Microsoft.Bot.Schema.APIException\",\r\n  \"Message\": \"Slack API error\",\r\n  \"Data\": null,\r\n  \"InnerException\": null,\r\n  \"HelpURL\": null,\r\n  \"StackTraceString\": \"   at SlackChannel.Slack.SlackApi.<CallSlackMethod>d__11`1.MoveNext() in D:\\\\a\\\\1\\\\s\\\\Channels\\\\SlackChannel\\\\SlackChannel\\\\Slack\\\\SlackApi.cs:line 539\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at SlackChannel.Slack.SlackApi.<SendChannelMessage>d__6.MoveNext() in D:\\\\a\\\\1\\\\s\\\\Channels\\\\SlackChannel\\\\SlackChannel\\\\Slack\\\\SlackApi.cs:line 317\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at SlackChannel.SlackConnector.<SendMessageActivityToUserAsync>d__13.MoveNext() in D:\\\\a\\\\1\\\\s\\\\Channels\\\\SlackChannel\\\\SlackChannel\\\\SlackConnector.cs:line 270\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Bot.ChannelConnector.ConnectorAPI.<SendActivityToUserAsync>d__11.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Bot.ChannelConnector.WebApiControllerExtensions.<ExecuteAndRespond>d__0`1.MoveNext()\",\r\n  \"RemoteStackTraceString\": null,\r\n  \"RemoteStackIndex\": 0,\r\n  \"ExceptionMethod\": \"8\\nMoveNext\\nSlackChannel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\\nSlackChannel.Slack.SlackApi+<CallSlackMethod>d__11`1\\nVoid MoveNext()\",\r\n  \"HResult\": -2146233088,\r\n  \"Source\": \"SlackChannel\",\r\n  \"WatsonBuckets\": null\r\n}"
    },
    "customMeasurements": ""
  },
  {
    "timestamp": "2019-09-10T07: 24: 19.0744414Z",
    "name": "Bot generated exception",
    "conv_id": "",
    "cloud_RoleInstance": "RD2818780AFB46",
    "customDimensions": {
      "SerializationTimeMs": "0.0025",
      "Bot ID": "Sticos_AI_Else",
      "Operation ID": "SendMessageToBot failed",
      "Exception": "{\r\n  \"botId\": \"Sticos_AI_Else\",\r\n  \"correlationId\": \"|d58b9e4c5113854dae7c28027eefa127.93f7d40d_93f7d411_\",\r\n  \"statusCode\": 500,\r\n  \"message\": \"POST to Sticos_AI_Else failed: POST to the bot's endpoint failed with HTTP status 500\",\r\n  \"data\": {},\r\n  \"innerException\": {\r\n    \"ClassName\": \"System.Exception\",\r\n    \"Message\": \"POST to the bot's endpoint failed with HTTP status 500\",\r\n    \"Data\": null,\r\n    \"InnerException\": null,\r\n    \"HelpURL\": null,\r\n    \"StackTraceString\": \"   at Microsoft.Bot.ChannelConnector.BotAPI.ThrowOnFailedStatusCode(Int32 statusCode)\\r\\n   at Microsoft.Bot.ChannelConnector.BotAPI.<PostActivityToBotAsync>d__31.MoveNext()\",\r\n    \"RemoteStackTraceString\": null,\r\n    \"RemoteStackIndex\": 0,\r\n    \"ExceptionMethod\": \"8\\nThrowOnFailedStatusCode\\nMicrosoft.Bot.Base.ChannelConnector, Version=3.2.3.6, Culture=neutral, PublicKeyToken=null\\nMicrosoft.Bot.ChannelConnector.BotAPI\\nVoid ThrowOnFailedStatusCode(Int32)\",\r\n    \"HResult\": -2146233088,\r\n    \"Source\": \"Microsoft.Bot.Base.ChannelConnector\",\r\n    \"WatsonBuckets\": null\r\n  },\r\n  \"hResult\": -2146233088\r\n}"
    },
    "customMeasurements": ""
  },
  {
    "timestamp": "2019-09-10T07: 24: 19.0744414Z",
    "name": "POST to bot failed",
    "conv_id": "",
    "cloud_RoleInstance": "RD2818780AFB46",
    "customDimensions": {
      "Activity ID": "13b040847eeb42e6b35e0a2de1bef3f9",
      "SerializationTimeMs": "0.1663",
      "Bot ID": "Sticos_AI_Else",
      "HTTP status code": "InternalServerError",
      "Conversation ID": "BML5WTS3C:T7XBR4SUB:DML5WTXXX",
      "Subscription ID": "6f3425fc-5959-495e-9aed-3584490a256a",
      "Exception": "{\r\n  \"botId\": \"Sticos_AI_Else\",\r\n  \"correlationId\": \"|d58b9e4c5113854dae7c28027eefa127.93f7d40d_93f7d411_\",\r\n  \"statusCode\": 500,\r\n  \"message\": \"POST to Sticos_AI_Else failed: POST to the bot's endpoint failed with HTTP status 500\",\r\n  \"data\": {},\r\n  \"innerException\": {\r\n    \"ClassName\": \"System.Exception\",\r\n    \"Message\": \"POST to the bot's endpoint failed with HTTP status 500\",\r\n    \"Data\": null,\r\n    \"InnerException\": null,\r\n    \"HelpURL\": null,\r\n    \"StackTraceString\": \"   at Microsoft.Bot.ChannelConnector.BotAPI.ThrowOnFailedStatusCode(Int32 statusCode)\\r\\n   at Microsoft.Bot.ChannelConnector.BotAPI.<PostActivityToBotAsync>d__31.MoveNext()\",\r\n    \"RemoteStackTraceString\": null,\r\n    \"RemoteStackIndex\": 0,\r\n    \"ExceptionMethod\": \"8\\nThrowOnFailedStatusCode\\nMicrosoft.Bot.Base.ChannelConnector, Version=3.2.3.6, Culture=neutral, PublicKeyToken=null\\nMicrosoft.Bot.ChannelConnector.BotAPI\\nVoid ThrowOnFailedStatusCode(Int32)\",\r\n    \"HResult\": -2146233088,\r\n    \"Source\": \"Microsoft.Bot.Base.ChannelConnector\",\r\n    \"WatsonBuckets\": null\r\n  },\r\n  \"hResult\": -2146233088\r\n}"
    },
    "customMeasurements": ""
  }
]
```

**Comment by stevkan** [comment]
Closing as the source of the issue appears to have been identified and no response has been received. If the issue persists after changes have been made to your bot, please feel free to reopen the issue.
