### ISSUE TITLE
CosmosDbStorage: read documents using the document client

### ISSUE THREAD

**Issue by munozemilio** [microsoft/botbuilder-dotnet#2487]
Remove SelfLink request. Please refer to this doc Remark section for SelfLink. https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.readdocumentasync?view=azure-dotnet .

When customer is using SelfLink request, when they are throttled, the database/collection names are not available to Cosmos DB. The recommendation is to use the ID-based link. It's also explained in the doc.

**Comment by cleemullins** [comment]
Closing in .Net, per @munozemilio .
