### ISSUE TITLE
Streaming: Telemetry should allow debuggability of streaming codepaths. 

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#2489]
How do people troubleshoot issues?

**Comment by Jeffders** [comment]
Debugging WebSocket streaming is akin to debugging HTTP in that they can take network traces and see socket traffic if they need to.

For debugging NamedPipe traffic, DL ASE has the ability to hook in App Insights to see requests sent over the streams.

There is also a longer term effort to provide a plug-in and file format to track the streaming content, but that is out of scope for 4.6.
