### ISSUE TITLE
[Adaptive] Suggestion: HttpRequest should capture response ressult and throw if not success

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2502]
## Version
What package version of the SDK are you using.

## Describe the bug
It should be nice for HttpRequest to analysis all the possible Http response result, and throw exception when the result is not 200. Otherwise all developer need to handle similar logic with status code all the time.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
consider adding a new property on HTTP request that user can configure return codes to ignore throwing an exception for - e.g. 404.

**Comment by vishwacsena** [comment]
Use a switch condition on the http status code to do what you need - e.g. emit a custom event or emit an error event etc.
