### ISSUE TITLE
[Adaptive] Choice Input's choice options should be localized

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2527]
## Version
What package version of the SDK are you using.

## Describe the bug
Check the choice input's schema:
{
              "$type": "Microsoft.ChoiceInput",
              "$designer": {
                "name": "Adjust slot dialog",
                "id": "032702",
                "updatedAt": "2019-09-17T06:56:27.993Z"
              },
              "prompt": "Sure, what would you like to adjust?",
              "maxTurnCount": 2147483647,
              "property": "turn.adjust",
              "alwaysPrompt": false,
              "allowInterruptions": "notRecognized",
              "outputFormat": "value",
              **"choices": [
                {
                  "value": "Time"
                },
                {
                  "value": "Subject"
                },
                {
                  "value": "Location"
                },
                {
                  "value": "Attendees"
                },
                {
                  "value": "Subject"
                },
                {
                  "value": "Content"
                }
              ],**
              "appendChoices": "true",
              "defaultLocale": "en-us",
              "style": "Auto",
              "choiceOptions": {
                "inlineSeparator": ", ",
                "inlineOr": " or ",
                "inlineOrMore": ", or ",
                "includeNumbers": true
              },
              "recognizerOptions": {
                "noValue": false
              }
            },
The choices are strings and cannot be localized.

## Expected behavior
Choices as expressions or lg template to make it support variables and localization.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Tracked via https://github.com/microsoft/botbuilder-dotnet/issues/2387
