### ISSUE TITLE
Inconsistency between QnaMakerMiddleware and LuisRecognizerMiddleware

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-dotnet#253]
Hi, when I use both the `QnaMakerMiddleware` and `LuisRecognizerMiddleware` I notice that they are quite different in terms of configuration. 

The `QnaMakerMiddleware` looks like this:

``` csharp
var adapter = new BotFrameworkAdapter(Configuration);

// Use the QnA maker middleware for getting responses from the knowledge base
QnAMakerMiddlewareOptions options = new QnAMakerMiddlewareOptions()
{
    SubscriptionKey = Configuration.GetSection("QnaMaker:SubscriptionKey").Value,
    KnowledgeBaseId = Configuration.GetSection("QnaMaker:KnowledgeBaseId").Value
};

adapter.Use(new QnAMakerMiddleware(options));
```

It takes a separate options object. That I have to insert in the constructor of the `QnaMakerMiddleware` class. Which is fine. Except that when I look at the `LuisRecognizerMiddleware` it is quite different.

``` csharp
var adapter = new BotFrameworkAdapter(Configuration);

// Use the LUIS middleware in the app for message enrichment
adapter.Use(new LuisRecognizerMiddleware(
    Configuration.GetSection("Luis:AppId").Value,
    Configuration.GetSection("Luis:Key").Value));
```

This time I only give it two keys and I'm done. 
It is confusing I think and I would love both middlewares to look the same.

**Comment by garypretty** [comment]
The LUIS middleware and recognizer is getting an overhaul soon (hopefully the next few days) so might be worth checking it out then.

**Comment by wmeints** [comment]
To add to this issue. I hope you can use the QnaMakerMiddlewareOptions way of working, so that I can do this:

``` csharp
var adapter = new BotFrameworkAdapter(Configuration);

// Use the QnA maker middleware for getting responses from the knowledge base
QnAMakerMiddlewareOptions options = Configuration.GetSection("QnaMaker").Get<QnAMakerMiddlewareOptions>();

adapter.Use(new QnAMakerMiddleware(options));
```

**Comment by nrobert** [comment]
The new version of LUIS Middleware has now the following signature:

`LuisRecognizerMiddleware(ILuisModel luisModel, ILuisRecognizerOptions luisRecognizerOptions = null, ILuisOptions luisOptions = null)`

So you can do:

```
var luisModel = new LuisModel("modelId", "subscriptionKey", new Uri("https://xxxxxx.api.cognitive.microsoft.com/luis/v2.0/apps/"));

adapter = new BotFrameworkAdapter(new ConfigurationCredentialProvider(configuration))
    .Use(new LuisRecognizerMiddleware(luisModel));
```

I didn't called my var `luisOptions` as it's another parameter in the signature.

@wmeints, do you think we can close this issue?

**Comment by wmeints** [comment]
Much better indeed. You can close this as solved.

**Comment by nrobert** [comment]
@wmeints I can't do it for you as I'm just a normal contributor here. But as the creator of the issue you may have the possibility to do it, don't you?

**Comment by wmeints** [comment]
Yup, I can. Sorry for the delay, out sick at the moment.
