### ISSUE TITLE
[Skype] Getting errors - Unknown attachment type for text/plain, audio/wave, audio/wav, audio/x-wav, audio/x-pn-wav, audio/webm, audio/ogg

### ISSUE THREAD

**Issue by evgeniy-glushin** [microsoft/botbuilder-dotnet#2540]
## Version
SDK 4.5.2

## Describe the bug
Given the code that works perfectly fine in local emulator but doesn't work when I publish it to skype. It returns 400 - Unknown attachment type for all the audio and text content types. 
Feel free to try the example I provided the audio file is open to the public.
```C#

var reply = MessageFactory.Text($"Echo: {turnContext.Activity.Text}");

reply.Attachments.Add(new Attachment
{
	Name = $"26563a05-5e70-4a39-8cef-7b615f5f8244.wav",
	ContentType = "audio/x-wav",
	ContentUrl = "https://s3.eu-north-1.amazonaws.com/yevhenii.ua.dev/26563a05-5e70-4a39-8cef-7b615f5f8244.wav",
});

await turnContext.SendActivityAsync(reply, cancellationToken);

```

**Comment by dmvtech** [comment]
@evgeniy-glushin Just to confirm; you are getting a 400, not a 401 or 403?

This is for adding files? Strange. I know that Skype does some strange stuff with limiting certain file types with retrieving, as you can find [here](https://stackoverflow.com/questions/55323347/retrieving-skype-attachments-when-connected-via-bot-framework/55424583#55424583). I'm not sure this is the same thing, but might be somewhat related. Do image attachments work fine for you in Skype?

I'll test and let you know what I find.

**Comment by evgeniy-glushin** [comment]
Hi,

Thank you for looking into this issue. 
Specifically I get Microsoft.Bot.Schema.ErrorResponseException (see https://s3.eu-north-1.amazonaws.com/yevhenii.ua.dev/BadArgument.png) when the bot replies to a user with an attachment.
I've just checked image/png for you and it works just fine as well as video/ogg. But I need audio/wav or any other audio format. Please let me know if you need everything from me.

**Comment by evgeniy-glushin** [comment]
@dmvtech Sorry for bothering I know you are very busy. But could you please let me know if you had a chance to look into this issue. Thanks.

**Comment by dmvtech** [comment]
I started to, but haven't been able to complete it yet. Can you please test .wma and .m4a files? Again, I [wonder ](https://stackoverflow.com/questions/55323347/retrieving-skype-attachments-when-connected-via-bot-framework/55424583#55424583)if it is related to a Skype file extension whitelist.

**Comment by evgeniy-glushin** [comment]
@dmvtech  I've just tested .wma and .m4a content types and I get the same error. I'm wondering if you can access the skype team maybe the can comment on this.

**Comment by dmvtech** [comment]
Sorry for the delay. Looks like Skype does not support audio (or text) file types as attachments from a bot. Although it will allow them as file attachments from the user/client. [This article](https://dev.skype.com/bots) shows only mentions Text (messages, not files), images and video.

Also, just wanted to make sure you knew that as of October 31, 2019 the Skype channel will no longer be accepting new Bot registrations. Current Skype bots will continue to run uninterrupted. [Learn more](https://support.skype.com/en/faq/fa12091/why-are-some-features-not-available-in-skype-anymore)
