### ISSUE TITLE
Update custom adapters and samples in prep for release

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#2542]
This task involves updating the custom adapters (twilio, webex and slack) in preparation for release. These activities involve:

- [ ] Apply consistent naming across the custom adapters (e.g.: do we use *Wrapper or *Connector for the clients?)
- [ ] Ensure all of them inherit from the same base and implement the same interfaces (BotAdapter and IHttpBotFrameworkAdapter)
- [ ] Simplify startup.cs and configuration settings
- [ ] Publish nuget packages for them
- [ ] Update samples and readmes
  - [ ] Twilio
  - [ ] Webex
  - [ ] Slack
  - [ ] Facebook

**Comment by garypretty** [comment]
Slack / Facebook adapters merged to master + feedback updates for Webex / Twilio.

**Comment by garypretty** [comment]
Preview adapters now merged into master - will be released to preview in 4.6.
Samples won't make 4.6 - tickets created for each adapter sample for R7

Slack sample - https://github.com/microsoft/BotBuilder-Samples/issues/1856
Webex sample - https://github.com/microsoft/BotBuilder-Samples/issues/1855
Facebook sample - https://github.com/microsoft/BotBuilder-Samples/issues/1854
Twilio sample - https://github.com/microsoft/BotBuilder-Samples/issues/1853
