### ISSUE TITLE
Consider moving ConfigurationCredentialProvider out of Bot.Builder into .NET Core specific integration

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#255]
Right now `ConfigurationCredentialProvider` is in the `Microsoft.Bot.Builder` project, but it has some pretty strong ties to .NET Core configuration and would not make sense to ASP.NET WebAPI based projects. I propose it be moved into the ASP.NET Core integration library where it makes more sense. ASP.NET WebAPI could get it's own version of this provider that reads from the full framework configuration style of APIs.

**Comment by cleemullins** [comment]
@drub0y - Is this still valid? I'm gong through all the open issues and closing the ones that are either completed or obsolete. This was done long enough ago, I suspect it's no longer relevant.

**Comment by drub0y** [comment]
Yeah, this is still valid IMHO. I would not include something that is tied specifically to .NET Core/Standard configuration APIs to the Core library. Honestly, with the addition of the integration library APIs, you'd want to use one approach for .NET Core/Standard and another for WebAPI.

**Comment by yochay** [comment]
@drub0y can you make this happen by end of June?

**Comment by drub0y** [comment]
Yep, consider it done! Should have it PR'd shortly.

**Comment by drub0y** [comment]
There ya go.
