### ISSUE TITLE
Functional Tests for Streaming Bots

### ISSUE THREAD

**Issue by DDEfromOR** [microsoft/botbuilder-dotnet#2559]
There are currently no end to end functional tests for the streaming extensions library integration with Bot Builder. This means if changes to Bot Builder break compatibility with streaming extensions we won't know until it's too late.

Specific test cases that came to mind while writing this:

Round trip message using streaming connections. (Named Pipe w/ DL ASE, WebSocket w/ modified DL ASE or DLS)
Round trip message using HTTP through the streaming adapter. (New adapter with classic workflow.)
Round trip message with attachments using streaming connection. (Named Pipe w/ DL ASE, WebSocket w/ modified DL ASE or DLS)

**Comment by DDEfromOR** [comment]
Depends on https://github.com/microsoft/botbuilder-dotnet/issues/2490

**Comment by DDEfromOR** [comment]
Blocked until #2490 is merged, as the functional tests need the functional code to know how to make use of the new features ;)

**Comment by sgellock** [comment]
@DDEfromOR #2490 has been merged.  Can you pick this issue back up?  thanks

**Comment by DDEfromOR** [comment]
Tests were added with https://github.com/microsoft/botbuilder-dotnet/pull/2835 but disabled with https://github.com/microsoft/botbuilder-dotnet/pull/2861 pending updates to the provisioning API and CLI tools to create bots subscribed to DirectLine Speech.

**Comment by DDEfromOR** [comment]
Bumping this to after R7. It requires changes on the service side and then having a partner team pull those changes in to their product, which isn't likely to land before R7 due to blackouts.

**Comment by DDEfromOR** [comment]
After looking over the three tickets I think this one is duplicated by the combination of https://github.com/microsoft/botbuilder-js/issues/1188 and https://github.com/microsoft/botbuilder-dotnet/issues/2863

When I originally opened this one it was meant to track the changes covered by the two linked above, so I'm closing this.
