### ISSUE TITLE
[Skype] Can't download an attachment which a user sends to the bot.

### ISSUE THREAD

**Issue by evgeniy-glushin** [microsoft/botbuilder-dotnet#2583]
## Version
SDK 4.5.2

## Description
I'm trying to download a video message the user sent to the bot and I get 500 without any error message. It happens when I call GetByteArrayAsync but GetTokenAsync works just fine and returns the token. On the other hand it works fine when I send a video file as a file attachment. Please let me know if you have any ideas on how to fix this.

I get 500 when I try to download this file for example:
https://smba.trafficmanager.net/apis/v3/attachments/0-weu-d11-a7dd2f30f52f28e7c657bbffc81be9e5/views/original

``` C#
public async Task<byte[]> LoadAttachmentAsBytes(Attachment att, string serviceUrl)
{
    var credentials = new MicrosoftAppCredentials("appId", "password");
    using (var connectorClient = new ConnectorClient(new Uri(serviceUrl), credentials))
    {
        var token = await credentials.GetTokenAsync();

        var uri = new Uri(att.ContentUrl);
        using (var httpClient = new HttpClient())
        {
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/octet-stream"));

            return await httpClient.GetByteArrayAsync(uri);
        }
    }
}
```

**Comment by dmvtech** [comment]
I'm taking a look to see if I can reproduce. Is it only with video files, or does it reproduce with other files as well?

**Comment by evgeniy-glushin** [comment]
@dmvtech It reproduces when I send a video message in skype. Looks like I'm not only one who is facing this problem https://social.msdn.microsoft.com/Forums/officeocs/en-US/cf97950f-7af6-4ed4-a053-d3453198c090/500-server-error-while-downloadning-file-from-skype?forum=AzureCognitiveService

**Comment by dmvtech** [comment]
Really strange, I am _unable_ to reproduce this issue. Have you tried [debugging using ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/)? It might not give much more, but might be worth a try.

I know you said you receive a 500 without any body, but do you have the Request and Response headers? You should be able to capture this using Fiddler (and a local repro). Also, can you share your bot handle? Feel free to email me at v-danava @ microsoft.com

**Comment by evgeniy-glushin** [comment]
I found out that it works fine for other skype users too. Do you have any idea why it fails only for me?

**Comment by dmvtech** [comment]
No idea. If you comment the Accept header line, does it behave any differently for you? I'm happy to look into it more if you want to share your bot handle or fiddler trace (again, at my email above).

**Comment by dmvtech** [comment]
Closing this. Please let us know if you still need assistance.
