### ISSUE TITLE
Update onSend/Update/Delete to prevent conversation reference form being overwritten

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#2589]
Need to update Activity communications to prevent manually addressed communications from being overwritten by the current onSend implementation.

**Comment by Virtual-Josh** [comment]
This will be done in this branch:

https://github.com/microsoft/botbuilder-dotnet/tree/johtaylo/teamsextensions

**Comment by cleemullins** [comment]
Done in the branch. Needs Unit Test / PR.

**Comment by Virtual-Josh** [comment]
PR is in. Closing.
