### ISSUE TITLE
[QnA Maker] Consume "ActiveLearningEnable" flag in QnAMaker action

### ISSUE THREAD

**Issue by trojenguri** [microsoft/botbuilder-dotnet#2595]
Configure if QnA Maker should call active learning or not based on the flag.

**Comment by vishwacsena** [comment]
@trojenguri - do we need this for 4.6? If so, backlog is not the right label.

**Comment by trojenguri** [comment]
> @trojenguri - do we need this for 4.6? If so, backlog is not the right label.

Removed Backlog.

**Comment by vishwacsena** [comment]
@trojenguri closing this as #2651 is merged.
