### ISSUE TITLE
Expressions shouldn't return an error for an invalid path

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#2609]
## Describe the bug
Looking at the C# adaptive code I noticed that we don't always raise an exception when evaluating an expression that returns error.  Talking to @tomlm, he said it's because the expression engine currently returns an error anytime an invalid path is encountered.  The issue with that is that the user has no way of knowing that their bot isn't working because of a bug in their expression.

I believe, the better approach would be to treat invalid paths internally as `null` and only return an error if the expression evaluates to something like `null + 1`. This way we can always throw errors returned from the expression engine. Yes there will still be cases of expressions with typos that don't trigger an exception but catching some/most errors is better than never catching any errors which is the way things are currently coded.

[bug]

**Comment by boydc2014** [comment]
I believe the current implementaion for an invalid path access is returning null, which is what this issue says. So @Stevenic do you have an example of the issue here?

**Comment by tomlm** [comment]
this appears to be current behavior.  Please reopen if not so.
