### ISSUE TITLE
[Adaptive] [LG] Expressions should have access to global scopes

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2612]
A called template does not have access to the global scopes like turn/dialog/settings.  This is confusing and puts a burden on all template callers to pass in the correct global information.  Much better if we look for a local parameter and if we don't find it fallback to the global scopes.  

As an example in the form stuff I wanted to do this:
# AskBread
- [askEnum('Bread')]

# askEnum(prop)
- Which {join($schema[prop].enum, ',') do you want?

With the current system, the template does not have access to $schema, I have to explicitly pass in the schema and it is confusing why I cannot do that here, but if I don't have parameters I can.

**Comment by vishwacsena** [comment]
Fixed via https://github.com/microsoft/botbuilder-dotnet/pull/2645
