### ISSUE TITLE
RetryPrompt does not work

### ISSUE THREAD

**Issue by imdat1guy** [microsoft/botbuilder-dotnet#2625]
## Version
v4

## Describe the bug
Bot does not send the retryprompt passed as an option for a promptAsync calls. All my prompts do not reprompt if response is not valid. One example is this attachment prompt:

```c#
private async Task<DialogTurnResult> AttachmentsStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
{
    bool attach = (bool)stepContext.Result;

    if (attach)
    {
        return await stepContext.PromptAsync(
            nameof(AttachmentPrompt),
            new PromptOptions
            {
                Prompt = MessageFactory.Text("Please select all the files you would like to upload"),
                RetryPrompt = MessageFactory.Text("Sorry I need an attachment")
            },
            cancellationToken);
    }
    else
    {
        return await stepContext.ContinueDialogAsync(cancellationToken);
    }
}
```

if an attachment is not sent the RetryPrompt is not sent. The bot does not respond with anything.

**Comment by imdat1guy** [comment]
this is caused by a typing activity being sent. Any workarounds?

**Comment by v-kydela** [comment]
Hello @imdat1guy - a workaround is described here: https://github.com/microsoft/botbuilder-dotnet/issues/1589

You can of course create your own prompt class and override `OnPromptAsync` as you see fit, but my recommendation is to just send the retry prompt in a validator function. I hope this helps.
