### ISSUE TITLE
DatetimePrompt NullReferenceException on a specific test case

### ISSUE THREAD

**Issue by ziad-akiki** [microsoft/botbuilder-dotnet#2629]
## Version
4.5.2

## Describe the bug
If you use a simple date time prompt within your bot, when entering an invalid date value like 'hello', 'anything', the specified `RetryPrompt` message would be send back to you.

This is not the case for this specific test case: `2019-Aug-01 to today`

In this case, the bot crashes with a `NullReferenceException` on line 109 in [DatetimePrompt.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs):
`var values = (List<Dictionary<string, string>>)results[0].Resolution["values"];`

It seems there's an issue with the Datetime recognition because it expects the day of the month at first not the year (For example if you send 29-Aug-01 it would be resolved correctly to 2001-08-01).

## To Reproduce
1. Build a bot with a simple `DatetimePrompt`.
2. Run the bot and send `2019-Aug-01 to today` when asked to.

## Expected behavior
For this specific test case it should be a valid date. If not, it should not crash but give the `RetryPrompt` message.

[bug]

**Comment by dmvtech** [comment]
I'm checking to see if I can reproduce. I'm with you; at the least it shouldn't crash.

**Comment by dmvtech** [comment]
Hi @ziad-akiki, I was able to reproduce the issue. 

Looking at the behavior (I tested with a LUIS endpoint, using a datetimev2 entity as well as the [Timex sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/40.timex-resolution)).

What is happening is that the recognizer is giving two results, one of which is a date, and the other is a date range.

```
"entities": [
{
  "entity": "from 2019-aug-01",
  "type": "builtin.datetimeV2.daterange",
  "startIndex": 28,
  "endIndex": 43
},
{
  "entity": "today",
  "type": "builtin.datetimeV2.date",
  "startIndex": 48,
  "endIndex": 52,
  "resolution": {
	"values": [
	  {
		"timex": "2019-10-01",
		"type": "date",
		"value": "2019-10-01"
	  }
	]
  }
}
```

But this does not have a valid resolution.

And to contrast, using an utterance like 

> August 1st 2019 to today

 we get one result (as we would expect) with a valid range:

```
"entities": [
{
  "entity": "from august 1st 2019 to today",
  "type": "builtin.datetimeV2.daterange",
  "startIndex": 28,
  "endIndex": 56,
  "resolution": {
	"values": [
	  {
		"timex": "(2019-08-01,2019-10-01,P61D)",
		"type": "daterange",
		"start": "2019-08-01",
		"end": "2019-10-01"
	  }
	]
  }
}
]

```

For DateTimePrompt, we can address this with a bug here. 

For the resolution aspect, please open a bug in the [Recognizers-Text ](https://github.com/microsoft/Recognizers-Text) reposiotry.

**Comment by ziad-akiki** [comment]
Hello @dmvtech, thank you. Please do proceed with opening a bug in [Recognizers-Text](https://github.com/microsoft/Recognizers-Text/). You may describe the problem and the reproduction steps there better than I would.

**Comment by dmvtech** [comment]
Will do

**Comment by tonyanziano** [comment]
Fixed via https://github.com/microsoft/Recognizers-Text/pull/1897
