### ISSUE TITLE
[Facebook] Getting System.NullReferenceException on every request

### ISSUE THREAD

**Issue by marcasmar94** [microsoft/botbuilder-dotnet#2630]
- We are getting the below **NullReferenceException** only when we get a **Facebook** Request

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()`

- This does not happen with DirectLine Channel 
- We are using the Virtual Assistant Template **V4**  **.Net Core 2.2**

Is anyone else facing this?

**Comment by darrenj** [comment]
Hi,

Thanks for letting us know. I've just tried to repro through the following steps:

- Deployed a new Virtual Assistant
- Created a new FaceBook Page and App following [these instructions](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0)
- Then in FaceBook Messenger start a conversation.

Things seem to be working OK including multi-turn conversations. Can you confirm if basic intents such as `Hello` or `Help` work for you. If so and it's a different/custom scenario perhaps you can share more so I can try and repro?

![image](https://user-images.githubusercontent.com/33519520/66055202-1a5b7080-e52d-11e9-912c-7f9980f502c7.png)

**Comment by darrenj** [comment]
Hi - any update on this issue?

**Comment by marcasmar94** [comment]
Even though we are getting the exceptions, the bot still works and we can interact with facebook messenger normally. But we keep getting these 2 Exception on every request: 

Below is a file containing the Exceptions details.
[error.json](https://drive.google.com/open?id=1ZqoEJC_R3nZlfVMHsYBv9kxH2J1BojhI)

**Comment by marcasmar94** [comment]
It seems in Microsoft.Bot.Connector.ConversationsEx.cs 

ReplyToActivityAsync is throwing an exception 

` if (activity.ReplyToId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ReplyToId");
            }`

It might be this, but if we aren't getting the ReplyToId how come the bot still works and we can reply to facebook users?

**Comment by marcasmar94** [comment]
Debugging using  Prefix, i am getting the following errors, **Only when it is from Facebook**, I have tried from emulator and directLine and we don't get those errors

 ![Error](https://bottics.com/BotFrameworkError.JPG)

**Comment by marcasmar94** [comment]
Thanks to the information i gathered from [this issue](https://github.com/microsoft/BotFramework-Services/issues/71) 

I checked the **Facebook Webhook subscription**, and saw that i was also subscribed to **message_echoes** . As soon as i Unsubscribed from this event in Facebook settings, the exceptions were gone.

**Comment by darrenj** [comment]
Thanks for letting us know.
