### ISSUE TITLE
re opening as https://github.com/microsoft/botbuilder-dotnet/issues/2597

### ISSUE THREAD

**Issue by som-nitjsr** [microsoft/botbuilder-dotnet#2636]
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
I have attached the image in original issue.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by stevengum** [comment]
Closing per the reference in microsoft/botbuilder-dotnet#2597
