### ISSUE TITLE
DialogContainer should implement TelemetryClient property

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#2638]
## Version
What package version of the SDK are you using: 4.Future (branch)

## Describe the bug
Both `AdaptiveDialog` and `ComponentDialog` derive from `DialogContainer`; however, they both override the `TelemetryClient` property with identical logic.

## To Reproduce
1. Look at the 2 versions of this property.
   - AdaptiveDialog : DialogContainer
     https://github.com/microsoft/botbuilder-dotnet/blob/80a96af7f9587611bc59e86f275802b9501b3d45/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs#L92-L105
   - ComponentDialog : DialogContainer
     https://github.com/microsoft/botbuilder-dotnet/blob/80a96af7f9587611bc59e86f275802b9501b3d45/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L41-L53
1. Error: since these have a common ancestor, why doesn't this code live there?
   - The two implementations are nigh-identical. Why do they use different modifiers: **override** vs. **new**?

## Expected behavior
If the behavior is the same, why not just implement at the base class.

## Additional context
@tomlm If this design is intentional, let me know the reasoning so I can document it correctly.

[bug]

**Comment by JonathanFingold** [comment]
Verified the issue persists in 4.9.3.

**Comment by garypretty** [comment]
@JonathanFingold The new modifier on the ComponentDialog is being used to ensure that the method on the derived class is used when setting TelemetryClient and is being called against an instance of Dialog, not necessarily ComponentDialog (e..g https://github.com/microsoft/botbuilder-dotnet/blob/71696394f8dc29533c250a359fb39c2c69e0117e/libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs#L63).

**Comment by garypretty** [comment]
This has since been altered. I changed this from 'new' to 'override' a while back to ensure the last defined implementation is called, even if the method is called on the base class. e.g. https://github.com/microsoft/botbuilder-dotnet/blob/71696394f8dc29533c250a359fb39c2c69e0117e/libraries/Microsoft.Bot.Builder.Dialogs/DialogSet.cs#L63.  I think you're right in terms of us being able to move the implementation to the DialogContainer class.
