### ISSUE TITLE
not able to pass memory scoped variable to  attachment in adaptive dialog

### ISSUE THREAD

**Issue by vidya091209** [microsoft/botbuilder-dotnet#2653]
## Version
latest version of  preview 

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
here i am creating attachment layout and passing user.id  as the url.
my requirement is show a Carousel and if user click on the link tack on that user in different third party system.
variable is working if i use simple  SendActivity("user id {user.id}")
but in this scenario it is not rendering.
   var myactivity = dc.Context.Activity.CreateReply();
                    myactivity.AttachmentLayout = AttachmentLayoutTypes.Carousel;
                
                            var h = new HeroCard()
                            {
                                Title = o.Title,
                                Text = o.Message,

                                Images = new List<CardImage> { new CardImage {
                                Url = o.ImageUrl
                                  } },
                                Buttons = o.Buttons.Select(a => new CardAction
                                {
                                    Type = "imBack",
                                    DisplayText = a.Name,
                                    Value = $"{o.Title} : {a.Name}",
                                    Text = a.Name,
                                    Title = a.Name

                                }).ToList()
                            };
                            if (!string.IsNullOrWhiteSpace(o.Url))
                            {
                                h.Buttons.Add(new CardAction
                                {
                                    Type = "openUrl",
                                    DisplayText = "Learn More",
                                    **Value = "https://abce.com/id={user.id}",**
                                    Text = "Learn More",
                                    Title = "Learn More"

                                });
                            }
                            myactivity.Attachments.Add(h.ToAttachment());
                    

                    dialog.Steps.Add(new SendActivity(myactivity));

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by stevengum** [comment]
@vidya091209 is this a preview of 4.6 or off of 4.Future?

**Comment by vidya091209** [comment]
yes this for adaptive dialog 4.Future branch

**Comment by vishwacsena** [comment]
@vidya091209 are you using language generation in your bot or just adaptive dialogs?

**Comment by vidya091209** [comment]
i am using adaptive dialog only. in my scenario these  values comes at run time  from api so i can use .lg file. i am constructing the whole flow at run time.

**Comment by vishwacsena** [comment]
We do not support data binding when you pass a custom activity. 

@tomlm - any workarounds?

**Comment by vishwacsena** [comment]
@vidya091209 - discussed this in triage and we do not support data binding when you are bringing in your own custom activity. The options are 

1. Switch to using LG 
2. Implement your own data binding logic. See [here](https://github.com/microsoft/botbuilder-dotnet/blob/196940657745ac11495e51a589f705b99288586d/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs#L47) for what SendActivity does
