### ISSUE TITLE
[Adaptive] Combining BotFramework v4 Dialogs (Waterfall) with Adaptive Dialogs Generated by Composer

### ISSUE THREAD

**Issue by sgellock** [microsoft/botbuilder-dotnet#2656]
**Describe the solution you'd like**
I want to be able to create a dialog using Composer, and reference/start it from existing BotFramework v4 Waterfall dialog.

Let's say I have a dialog where at some point I want to start "Org registration" dialog.
This org registration dialog can be designed using the Composer.
Then, I want to copy generated `.dialog` file (and probably `.lg` files) to my existing solution and do something like that:
```csharp
var resource = this._resourceExplorer.GetResources(".dialog").FirstOrDefault(r => r.Id == "RegisterCustomer.dialog");
if (resource != null)
{
  var registerCustomerDialog = DeclarativeTypeLoader.Load<AdaptiveDialog>(resource, _resourceExplorer, DebugSupport.SourceRegistry);
await registerCustomerDialog.Run(turnContext, _conversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
}
```

Currently, I did generate the `.dialog` using Composer (attached, renamed to `.txt`), and included it into the project.
I've also tried to include both `app.schema` from Declarative Dialog samples, as well as `sdk.schema` from the Composer itself.
But I still just getting an error on this line `var registerCustomerDialog = DeclarativeTypeLoader.Load<AdaptiveDialog>(resource, _resourceExplorer, DebugSupport.SourceRegistry);`:
```
DeclarativeDialogs\RegisterCustomer.dialog error: Type specified in JSON 'Microsoft.AdaptiveDialog' was not resolved. Path '$type', line 2, position 37.
```

[RegisterCustomer.txt](https://github.com/microsoft/BotFramework-Composer/files/3682817/RegisterCustomer.txt)

**Comment by tomlm** [comment]
This probably needs the declarative goo to make sure that the types are registered with the type loader system.

```
adapter
  .UseStorage(storage)
  .UseState(userState, conversationState)
  .UseResourceExplorer(resourceExplorer)
  .UseAdaptiveDialogs()
  .UseLanguageGeneration(resourceExplorer);
```

The **.UserResourceExplorer()** and **UseAdaptiveDialogs()** register the **ResourceExplorer**  and type system to fetch resources by Id, and **.UseAdaptiveDialogs()** registers all of the "Microsoft.AdaptiveDialog" => typeof(AdaptiveDialog) bookkeeping.

Can you update and try again?

**Comment by AJIXuMuK** [comment]
Was it a question to us to try or internal conversation?.. To many open-close operations. I'm a bit lost :)

**Comment by sgellock** [comment]
@AJIXuMuK was a customer issue that I logged for the customer.

**Comment by rajeshyalamarthi** [comment]
Hi,I am trying to integrate composer's adaptive dialog in bot framework V4 echo bot. I loaded all the components which are required. There are no build errors for me, but when i was debugging, at the point where DeclarativeTypeLoader is trying to load root dialog file, it is throwing the error:
**'Type specified in JSON 'Microsoft.AdaptiveDialog' was not resolved. Path '$type', line 3, position 37.**' 
![Capture](https://user-images.githubusercontent.com/31951690/70423261-29adeb80-1a93-11ea-820a-e8e42d2c3a95.PNG)

**Comment by jamiemaguiredotnet** [comment]
@tomlm - Hi, is this issue now resolved?

**Comment by vishwacsena** [comment]
Tracked via #3105
