### ISSUE TITLE
[Adaptive] The @ shortcut does not work for LUIS list entities

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2663]
The interpretation of @ was to select the first element until you got a non array value.  The current implementation interprets @ as a simple path transformation with [0] on the end to pull out the first value.  This is made more difficult since the DialogStateManager is in the core SDK so cannot use expressions.

To fix this we either need to redefine the semantics of @ or we need to come up with a way to achieve the unwrapping functionality.

@vishwacsena  you should know about this.  I also talked to @tomlm about it.
[bug]

**Comment by vishwacsena** [comment]
@xxx -> first value in the array = turn.entities.xxx[0]
If array of array, then the first value in the first array. -> turn.entities.xxx[0][0]

**Comment by chrimc62** [comment]
I'm missing how this has been resolved.  I think the path resolver needs access to the returned value.  The static resolver doesn't know which to use.  Or are you suggesting that for list entities people have to do @foo[0] and for other kinds of entities it is just @blah?
