### ISSUE TITLE
[DCR][.NET Specific] Adopt IHttpClientFactory as a mechanism to obtain HttpClients

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#2665]
Currently, we pass HttpClient instances across to different parts of the code that do Http requests. .NET is evolving towards the IHttpClientFactory pattern. 

This DCR would declare methods that pass HttpClients as obsolete, and create new mthods that pass an IHttpClientFactory.

The only risk around this was that IHttpClientFactory is used in asp.net core, but not in .net framework. However, as long as .NET framework version is greater than 4.6.1, we can consume it from the nuget package Microsoft.Extensions.Http.

**Comment by carlosscastro** [comment]
@johnataylor as FYI

**Comment by cleemullins** [comment]
@carlosscastro I suspect we won't get to this in R7. Should we push to R8?

**Comment by carlosscastro** [comment]
@cleemullins John and I visited this, and with the current tech there is not a great way to solve this right now, but we have some ideas that we could implement in R8. Pushing.

**Comment by johnataylor** [comment]
👍
