### ISSUE TITLE
Misspelled ProcessActivity in SDK

### ISSUE THREAD

**Issue by ivorb** [Microsoft/botbuilder-dotnet#267]
On home wiki page (https://github.com/Microsoft/botbuilder-dotnet/wiki) the hello world bot code references _adapter.ProcessActivity in the code provided for MessagesController.cs. There is a build error in processActivity, and the SDK has it misspelled.  Needs change in BotFrameworkAdapter

...
public Task ProcessActivty(string authHeader
...

**Comment by drub0y** [comment]
We should probably update this sample to use the newer ASP.NET integration APIs that no longer even require creating your own controller or working with the `BotFrameworkAdapter` directly.

I'm happy to do it if nobody else is already planning on it...

**Comment by JonathanFingold** [comment]
I'll take care of it. Need to coordinate with the UX people who are running a usability study off the content this week.

**Comment by JonathanFingold** [comment]
PS. Holding off on using the integration library until the corresponding NuGet package is published.

**Comment by JonathanFingold** [comment]
Part of the problem is that the published NuGet packages are now quite out of sync with the code in the repo, forcing this topic to respect one version or the other. I will make this specific to the repo bits.
