### ISSUE TITLE
[Adaptive] Recognizer and intent rule only works for parallel node not child node.

### ISSUE THREAD

**Issue by som-nitjsr** [microsoft/botbuilder-dotnet#2679]
## Version
What package version of the SDK are you using.
I am using adaptive dialog 4.6
## Describe the bug
Give a clear and concise description of what the bug is.
I have  conversion flow with multiple path where i have used ChoiceInput and switch condition.
i am able to travel to my flow paths based on my inputs  as expected there is no issues.
Now i am trying to achieve the  jump from node 2 to node 10 using Recognizer  and intent rule.
till now i can see intent rule only works at parallel nodes i have can jump between nodes.
i have applied the Recognizer  and AllowInterruptions at every node.
but still i am not able to move
## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
@som-nitjsr - can you share bit more information? 

1. Are you using preview packages off botbuilder.myget.org or building from 4.Future branch?
2. Can you share code snippet for your scenario? Is node 2 an input node and based on the user's response, you need to jump to node 10 in the flow? Is node 2 your choice input? Where does node 10 live? is that one of the branch in the switch condition or outside the entire block? 

The interruption model in adaptive dialogs enables you to model non-linear conversations. There is no support for a jump except for having the interruption provide required values required to skip through node 3...9 or we would need to re-organize the flow or your code snippet might require us to re-consider supported actions collection.

**Comment by som-nitjsr** [comment]
we are using the builds from https://botbuilder.myget.org/gallery/botbuilder-declarative
out bots are live here https://social27.com/
this is our designer
https://botdashboard.social27.com/social27/
 i wil share more info.

**Comment by som-nitjsr** [comment]
i am going with parallel node. hence closing it.
