### ISSUE TITLE
Fresh clone of sln has reference errors in EchoBot

### ISSUE THREAD

**Issue by ivorb** [Microsoft/botbuilder-dotnet#268]
Couldn't find dlls on fresh clone of this repo - likely need to update the references for first timers

Error	
Metadata file '...\botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Core\bin\Debug\netstandard2.0\Microsoft.Bot.Builder.Core.dll' could not be found	
Microsoft.Bot.Samples.EchoBot-AspNet461	

Error	 
Metadata file 'C:\Users\Ivor Berry\Documents\GitHub\botbuilder-dotnet\libraries\Microsoft.Bot.Builder\bin\Debug\netstandard2.0\Microsoft.Bot.Builder.dll' could not be found	
Microsoft.Bot.Samples.EchoBot-AspNet461	

Error	 
Metadata file '...botbuilder-dotnet\samples\EchoBot\bin\Debug\netstandard2.0\Microsoft.Bot.Samples.EchoBot.dll' could not be found	
Microsoft.Bot.Samples.EchoBot-AspNet461

**Comment by drub0y** [comment]
Hmm, that is interesting, thanks for filing this. I can repro this on a clean build dir as well. Let me check to see why the reference isn't triggering that dependent project first.
