### ISSUE TITLE
LuisRecognizer doesn't return Dispatch linked additional results (connectedServiceResult)

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-dotnet#2686]
## Version
4.5

## Describe the bug
Last year LUIS introduced a linked model capability whereby if you were invoking Dispatch and Dispatch identified the TopScoringIntent as being a LUIS model it will go ahead and invoke the LUIS model and return the `linked` result in one call saving performance/cost.

For example:
![image](https://user-images.githubusercontent.com/33519520/66502928-25c71280-eabe-11e9-85a1-01c85571fae0.png)

## To Reproduce
1. Create a Dispatch model with a linked LUIS model
2. Using the LuisRecognizer sent an utterance that should trigger the child model.
3. Observe that the resulting IRecognizerResult payload doesn't have ConnectedServiceResult

![image](https://user-images.githubusercontent.com/33519520/66502998-4abb8580-eabe-11e9-9399-29c088a408b6.png)

## Expected behavior
The ConnectedServiceResult to be returned, ideally as a discrete RecognizerResult instance that I can process as if I had called LUIS a second time.

## Additional context
- [IRecognizerResult](https://github.com/microsoft/botbuilder-dotnet/blob/b454e6134ec79440fa5681fdf0c65da5dc522686/libraries/Microsoft.Bot.Builder/RecognizerResult.cs) doesn't have this property set.
- As per Source code comments, checked that Properties on the result didn't have the required data - it's empty as you can see in watch window above.

[bug]

**Comment by darrenj** [comment]
@garypretty took a look, appears there is a `includeApiResults` option when initializing the LuisRecognizer that goes on to include additional information **including** connectedServiceResult if available.

e.g.
```
new LuisRecognizer(luisApp, luisOptions, true));
```

Now results in this with a Dispatch enabled model

![image](https://user-images.githubusercontent.com/33519520/66566593-3f6b6700-eb5d-11e9-8d3a-d58107b4b39f.png)

No mention of this in the [Dispatch Docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs) although the code example does subtlety set this to true without explaining. Would be good to transfer to the docs team to add a section on this?

Thanks @garypretty

**Comment by garypretty** [comment]
@darrenj I think we could also update our NLP sample to call this out explicitly with a comment. I will look into that.

**Comment by garypretty** [comment]
@darrenj PR raised for the comments in the samples.  I am unsure as to which repo this would need transferring to for the docs team. Are you able to transfer it?

**Comment by garypretty** [comment]
Closing this as we now have a PR open in docs to call out this parameter and the original issue is resolved.
