### ISSUE TITLE
Suggestions in Activity not working 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#2688]
This is a sample in composer which use Suggestions feature, which is not working in the last 4.Future branch.

# help
- ```
    I can show you examples on how to use actions. Enter the number next to the entity that you with to see in action.
    [Suggestions=Actions|EndTurn|IfCondition|EditArray|EndDialog|HttpRequest|SwitchCondition|RepeatDialog|TraceAndLog|Editactions|ReplaceDialog|EmitEvent]
	01 - Actions
	02 - EndTurn
	03 - IfCondiftion
	04 - EditArray, Foreach
	05 - EndDialog
	06 - HttpRequest
	07 - SwitchCondition
	08 - RepeatDialog
	09 - TraceAndLog
	10 - EditActions
	11 - ReplaceDialog
	12 - EmitEvent
    ```

![image](https://user-images.githubusercontent.com/32191031/66512632-3364a400-ea8e-11e9-9f56-520440930fea.png)

**Comment by Danieladu** [comment]
We have migrated to the structured lg, ref: #2325

**Comment by vishwacsena** [comment]
You can now do suggestions via Structured LG like this - 

```markdown
# WelcomeUser
[Activity
    Text = Hello, I'm a demo bot.
    SuggestedActions = Start | Cancel
]
```
