### ISSUE TITLE
Need to update Home sample for BotFrameworkAdapter call in Startup.cs

### ISSUE THREAD

**Issue by ivorb** [Microsoft/botbuilder-dotnet#269]
In code for hello world bot (https://github.com/Microsoft/botbuilder-dotnet/wiki) the call to BotFrameworkAdapter in provided Startup.cs code doesn't compile anymore - need to update the code to match new definition.

Workaround - use the Configuration variable (implicit cast works from IConfigurationRoot to IConfiguration).  Sample then works, but that may not be ideal.

**Comment by JonathanFingold** [comment]
Will fix this and #267 together.
