### ISSUE TITLE
RetryPrompt only displayed once

### ISSUE THREAD

**Issue by torynfarr** [microsoft/botbuilder-dotnet#2690]
## Version
4.5.1

## Describe the bug
With the Bot Framework Emulator version 4.5.1, RetryPrompts in Dialogs are no longer working as expected. Specifically, with a text prompt, the validation method is called... but if it returns false the RetryPrompt Activity is only displayed that first time. If you enter invalid input again and again after that first time, the validation method is called each time (as it should be), but when it returns false... nothing is output.

The exact same dialog (same code, no changes) running in Direct line / Web Chat functions properly. Problem appears to be specific to the Bot Framework Emulator.

## To Reproduce

1. Create a dialog which prompts the user for text input. 
2. When text is entered, the validation method will be reached.
3. Evaluate the text and (for the sake of testing) return false as it is invalid input.
4. Observe that the RetryPrompt is displayed as it should be.
5. Enter invalid input again and the validation method will be reached again.
6. Observe that the RetryPrompt is not displayed, although it should be.
[bug]

**Comment by cwhitten** [comment]
this is linked with

https://github.com/microsoft/botbuilder-dotnet/issues/2689

additional issue reports:

https://github.com/microsoft/BotFramework-Emulator/issues/1888

**Comment by EricDahlvang** [comment]
This is a quirk of the Emulator.  Other channels do not respect the ids of incoming activities, but use a generated one.  PR for emulator: https://github.com/microsoft/BotFramework-Emulator/pull/2003

Nonetheless, the [spec does state](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#id)

> Clients and bots SHOULD NOT include an id field in activities they generate.

SDKs updates to not send ids: 

[javascript](https://github.com/microsoft/botbuilder-js/commit/cdb8d6f0123175f526d935fefcac5db2b188d9aa#diff-cee27df6126434892e9a6747003fb69eR455)

[dotnet](https://github.com/microsoft/botbuilder-dotnet/pull/3012)
