### ISSUE TITLE
[Adaptive] EndDialog "property" is never used and is confusing

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#2697]
## Version
What package version of the SDK are you using.
Using latest from 4.future

## Describe the bug
The EndDialog constructor now accepts both a "property" and a "value" argument, but the value is the only one that is used for the ResultProperty. This is confusing, and ideally the property parameter would be removed. It would also be nice if the parameter were named something more clear, like "resultProperty" so it is easier to understand that it maps to the ResultProperty of BeginDialog.

[bug]

**Comment by tomlm** [comment]
agree we should remove property parameter, I think Value is worth keeping
