### ISSUE TITLE
Remove Dialogs.Flow and Dialogs.Form from master?

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-dotnet#2706]
Dialogs.Flow - https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.Dialogs.Flow
and 
Dialogs.Form - https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.Dialogs.Form

Seems empty.

They are related to the work @chrimc62  is working, but are not needed for 4.6.

Should we remove these folders?  

[bug]

**Comment by chrimc62** [comment]
Should be fine to remove.  The chrimc/map branch has my stuff.
