### ISSUE TITLE
[Teams]  OnTeamsMessagingExtensionFetchTaskAsync signature is incorrect

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#2737]
JS PR: https://github.com/microsoft/botbuilder-js/pull/1305

## Describe the bug
`TeamsActivityHandler.OnTeamsMessagingExtensionFetchTaskAsync()` needs to be updated

From:

`protected virtual Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionFetchTaskAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionQuery query, CancellationToken cancellationToken)`

to:

`protected virtual Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionFetchTaskAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionAction action, CancellationToken cancellationToken)`

## Additional context
Feedback from Hackathon.

[bug]

**Comment by EricDahlvang** [comment]
Closing, since this was completed in https://github.com/microsoft/botbuilder-dotnet/pull/2740
