### ISSUE TITLE
ConversationID on Skills may be too long for State Storage

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#2763]
This code, found in SkillConversation.cs, is problematic:
```cs
return Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new[]
            {
                ConversationId,
                ServiceUrl,
            })));
```

Both the ServiceUrl and (on some channels) the ConverstaionID, may be quite long. Teams, for example, uses a long Conversation Id. 

Our CosmosDB and Azure Blob Storage providers may have problems with this. 

Note: consider @Stevenic feedback on using UrlEncode rather than Base64 to allow the bots to work on the browser when using JS.

**Comment by gabog** [comment]
Thanks Chris, will keep an eye on this one and will get to it as soon as I wrap up my other tasks.
