### ISSUE TITLE
TeamsActivityHandler.OnTeamsMessagingExtensionCardButtonClickedAsync handler returns 'null' body

### ISSUE THREAD

**Issue by beauzeaux** [microsoft/botbuilder-dotnet#2776]
## Version
4.6.0-preview-191002-1

## Describe the bug
Pressing AdaptiveSubmitAction buttons in Teams results in an error message when `OnTeamsMessagingExtensionCardButtonClickedAsync` is registered.

## To Reproduce
1. Return an AdaptiveCard with an AdaptiveSubmitAction 
2. Press AdaptiveSubmitAction card
3. Teams shows red error message

## Expected behavior
Teams should not show error message. 

## Screenshots
![image](https://user-images.githubusercontent.com/689368/67125850-88996780-f1aa-11e9-8ffa-a864bdb4714f.png)

Invoke Response
```json
{"errorCode":1008,"message":"<BotError>Error when processing invoke response: responseType could not be parsed: Cannot access child value on Newtonsoft.Json.Linq.JValue."}
```
## Additional context
The response from the bot with the handler registered is 200/OK with a body of 'null'. The intermediate service is expecting a JSON payload. 

[bug]

**Comment by beauzeaux** [comment]
I did a little more sleuthing and I'm wondering if there is just a bug with the the integration package.
BotMessageHandlerBase.cs:76 seems to do a check if the response body is null was that supposed to be the invokeResponse?

Looking at [HttpHelper.cs:74](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs#L74) it seems this would only be affecting the BotMessageHandler and not the Adapter which uses HttpHelper.

**Comment by beauzeaux** [comment]
Sorry for the noisy issue log, I've created a new PR (#2792) to address what I believe is the root cause of the issue. 

If using the AspNetCore integration package & the .AddBot / .UseBotFramework integrations Invoke responses with an empty body would result in a failure documented above. This wouldn't have affected the Adapter + MVC route as it uses the HttpHelper serialization.

**Comment by EricDahlvang** [comment]
Thanks!  Closing,  as the fix has been merged.
