### ISSUE TITLE
[LG] support telemetry client in LG

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2783]
Had a scoping chat with @scheyal  yesterday. See how luisrecognizer does TrackEvent on recognition result. We need something similar for LG from a generator POV for adaptive dialog. Basically emit a `generatorResult` event name with properties that include the generator configuration (.lg files or any identifier we have) as well as the actual input/ output for the evaluate call. 

@boydc2014

**Comment by vishwacsena** [comment]
Had a scoping chat with @scheyal  yesterday. See how luisrecognizer does TrackEvent on recognition result. We need something similar for LG from a generator POV for adaptive dialog. Basically emit a `generatorResult` event name with properties that include the generator configuration (.lg files or any identifier we have) as well as the actual input/ output for the evaluate call. 

@boydc2014

**Comment by cleemullins** [comment]
@vishwacsena  - can you update this issue? Is this R8 and P0?
