### ISSUE TITLE
[LG] [DCR] Streamline LG, expressions, multi-line syntax

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2786]
Today we support the following - 
- Call a template: 
    - [templateName]
    - [templateName(params)]
    - {templateName()}
    - {templateName(params)}
    - {lgTemplate(templateName, params)}
- Refer to expression
    - {expression}
- Refer to expression within multi-line
    - @{expression}

This DCR proposes that we streamline the syntax to be consistent and use this everywhere - 
- Call a template
    - @{templateName()}
    - @{templateName(params)}
- Refer to expressions
    - @{expression}
- Refer to expressions within multi-line
    - @{expression}

This eliminates the need for user to learn various different ways to access expressions/ LG and streamlines all expressions (including template expansion calls) to be `@{expression | templateName (params)}` notation immaterial of their presence in single line or multi-line text.

**Comment by boydc2014** [comment]
Totally agree, we should only support @{}, I think this should happen soon. 

And @vishwacsena, even in our samples in 4.6, we should adopt this new style.
