### ISSUE TITLE
use conversation id from skill across telemetry and sdks of other languages

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#2787]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

* Conversation id is changed in skill, so one can't use conversation id to combine messages from host and skill together easily (e.g. combining telemetry for transcript)
* Conversation id depends on C# implementation of GetBytes and specific version of JsonConvert.SerializeObject, it is not likely able to be done in sdks of other languages (like Typescript)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by tomlm** [comment]
1. The SkillHost is emulating a channel and a channel gets to assign conversationIds
2. the Skill doesn't crack or know what is in the conversationId that is given it
3. The C# code base is using GetBytes(), JsonSerialize, but there is zero requirement for SkillHost's to standardize on the encoding that they choose for conversationIds (including no encoding, by assigning their own conversationId and keeping track of the meta data internally.)
4. When activities are pushed from Skill -> SkillHostby the SkillHost (aka bot) DOES receive activities that have the correct original conversationId.  Any telemetry and transcript logging that happens in the SkillHost WILL be consistent for the data that is coming from the Skill.
5. All activities that a Skill sees WILL Be consistent for the conversation with the Skill, and so all telemetry in the Skill will be consistent.
6. It is not a goal to have the conversationId be consistent between skillhost and skill.

**Comment by xieofxie** [comment]
> 1. The SkillHost is emulating a channel and a channel gets to assign conversationIds
> 2. the Skill doesn't crack or know what is in the conversationId that is given it
> 3. The C# code base is using GetBytes(), JsonSerialize, but there is zero requirement for SkillHost's to standardize on the encoding that they choose for conversationIds (including no encoding, by assigning their own conversationId and keeping track of the meta data internally.)
> 4. When activities are pushed from Skill -> SkillHostby the SkillHost (aka bot) DOES receive activities that have the correct original conversationId.  Any telemetry and transcript logging that happens in the SkillHost WILL be consistent for the data that is coming from the Skill.
> 5. All activities that a Skill sees WILL Be consistent for the conversation with the Skill, and so all telemetry in the Skill will be consistent.
> 6. It is not a goal to have the conversationId be consistent between skillhost and skill.

Thanks~ 3 really helps me
