### ISSUE TITLE
Wiki says to ref Integration.aspnet.core + Integration.aspnet.webapi for .Net Core apps; this errors out

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#279]
Should only ref `Microsoft.Bot.Builder.Integration.AspNet.Core`, not `Microsoft.Bot.Builder.Integration.AspNet.WebApi` pkg. Webapi pkg is, however, required when developing a .Net Framework WebAPI application.

offending doc: https://github.com/Microsoft/botbuilder-dotnet/wiki

**Comment by JonathanFingold** [comment]
I have some other fixes to make. I'll fix this while I'm at it. Thanks.
