### ISSUE TITLE
AlarmBot-Cards README/Wiki doesn't mention anything about using recognizers.text

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#280]
Since you're using the `recognizers.text.datetime` in AlarmBot-Cards I would call it out somewhere in the wiki or the README.

It's also not obvious where we're even using it, since we're relying on cards to input the date and time. What's the value add of including this in the sample? I'd either take it out completely (and just have the alarm title for responses be <title>,<date>,<time>), or add some more info/base around it so there's some learning/sample code available.

The only place I can find recognizers.text in the wiki is under extensions

**Comment by nrobert** [comment]
You are right, `Microsoft.Recognizers.Text.Datetime` are not used in the AlarmBot-Cards sample, only on AlarmBot. I will remove the package and unnecessary class from the sample.

**Comment by vishwacsena** [comment]
This sample will be replaced by //BUILD.
