### ISSUE TITLE
Naming collision between new Microsoft.Bot.Builder.AI.QnA.Prompt and old Microsoft.Bot.Builder.Dialogs.Prompt<T>

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#2809]
## Version
What package version of the SDK are you using. 4.6 preview

## Describe the bug
The newly introduced Microsoft.Bot.Builder.AI.QnA.Prompt conflicts with Microsoft.Bot.Builder.Dialogs.Prompt\<T>
- The JS SDK has the same problem.
- While there are ways to disambiguate these classes, it's a headache we don't need to introduce.

## To Reproduce
1. Compare
   - https://github.com/microsoft/botbuilder-dotnet/blob/6de8c937063443130197d12aae5ae3edff98933a/libraries/Microsoft.Bot.Builder.AI.QnA/Models/Prompt.cs#L9-L14
   - https://github.com/microsoft/botbuilder-dotnet/blob/2ae993714e37eb58fb8c2e8867eb03739dd05524/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L13-L28
1. **Issue**: Imagine every time time we need to explain which version of the `Prompt` class we are using in every article in which it is mentioned.

## Expected behavior
We don't introduce naming conflicts when we don't have to, especially ones within our own SDK.

[bug]

**Comment by vishwacsena** [comment]
@trojenguri; @simer99 - can you take a look and comment? 

@tomlm ; @sgellock  - we might want to consider this for 4.6.

**Comment by JonathanFingold** [comment]
PS. The casing on the two QnA ID properties is inconsistent. Probably, `QnAId` is correct for C#.
- https://github.com/microsoft/botbuilder-dotnet/blob/6de8c937063443130197d12aae5ae3edff98933a/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerOptions.cs#L58-L64
- https://github.com/microsoft/botbuilder-dotnet/blob/6de8c937063443130197d12aae5ae3edff98933a/libraries/Microsoft.Bot.Builder.AI.QnA/Models/Prompt.cs#L25-L30

**Comment by sgellock** [comment]
@JonathanFingold thanks for opening the issue.  We'll make a change and get it into master in time for the 4.6 release.  we're going to rename it to be Microsoft.Bot.Builder.AI.QnA.QnAMakerPrompt.  this aligns with the names they use for other classes
