### ISSUE TITLE
Portable PDBs need to be universally applied across CS Proj files

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#2815]
Some of our CSPROJ files have this:
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

Others do not. 

This should apply to release builds, as that's what's included in the Nuget packages.

**Comment by chrimc62** [comment]
I checked and all projects have portable set.  I think the DebugType is only necessary for the few non .net standard projects.  We could see if removing them was necessary, but that is minor clean-up so I'm leaving at this point.
