### ISSUE TITLE
[SetProperty] Property copy became shallow copy instead of deep copy

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2827]
## Version
What package version of the SDK are you using.

## Describe the bug
When using SetProperty to copy property A to property B then modify property B, you can find property A had been modified too.

## To Reproduce
1. Add a set property:
![image](https://user-images.githubusercontent.com/16643193/67368605-3097a200-f5aa-11e9-9ec1-10baae4cf414.png)
dialog.CreateCalendarEntry_FromTime is a datetime:
{
"value": "23:00:00",
"timex": "T23:00"
}

2. Modify dialog.CreateCalendarEntry_ToTime to addSeconds(formatDateTime(dialog.CreateCalendarEntry_FromTime[0].value), int(dialog.CreateCalendarEntry_Duration[0].value)) with set property
![image](https://user-images.githubusercontent.com/16643193/67368738-69377b80-f5aa-11e9-8352-4007e5ec5967.png)

3. Print dialog.CreateCalendarEntry_FromTime
4. See dialog.CreateCalendarEntry_FromTime changed also

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by DingmaomaoBJTU** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/1206

**Comment by luhan2017** [comment]
A simple way to repro this:

var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
            {
                Triggers = new List<OnCondition>()
                {
                    new OnConversationUpdateActivity()
                    {
                        //Actions = WelcomeUserAction()
                    },
                    new OnBeginDialog()
                    {
                        Actions = new List<Dialog>()
                        {
                            new DateTimeInput()
                            {
                                Prompt = new ActivityTemplate("what is your date?"),
                                Property = "dialog.date",
                                MaxTurnCount = 3,

                                //AllowInterruptions = "this.value != null"
                            },
                            new SetProperty()
                            {
                                Property = "dialog.date1",
                                Value = "dialog.date"
                            },
                            new SendActivity()
                            {
                                Activity = new ActivityTemplate("{dialog.date}, {dialog.date1}")
                            },
                            new SetProperty()
                            {
                                Property = "dialog.date[0].value",
                                Value = "'updated value'"
                            },
                            new SendActivity()
                            {
                                Activity = new ActivityTemplate("{dialog.date}, {dialog.date1}")
                            }
                        }
                    }
                }
            };

Expected behavior:
bot: what is your date?
user: tomorrow
bot: [
{
"value": "2019-10-24",
"timex": "2019-10-24"
}
], [
{
"value": "2019-10-24",
"timex": "2019-10-24"
}
]
bot:[
{
"value": "updated value",
"timex": "2019-10-24"
}
], [
{
"value": "2019-10-24",
"timex": "2019-10-24"
}
]

Actual behavior:
bot: what is your date?
user: tomorrow
bot: [
{
"value": "2019-10-24",
"timex": "2019-10-24"
}
], [
{
"value": "2019-10-24",
"timex": "2019-10-24"
}
]
bot:[
{
"value": "updated value",
"timex": "2019-10-24"
}
], [
{
"value": "updated value",
"timex": "2019-10-24"
}
]
