### ISSUE TITLE
Fix build warnings in FB Adapter

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#2845]
The following warnings show up when we build the FB adapter. Let's fix. 

Also, need to make sure the "Set Warnings as errors" is enabled for these before we take them to GA. 

##[warning]libraries\Adapters\Microsoft.Bot.Builder.Adapters.Facebook\FacebookEvents\FacebookEntry.cs(26,38): Warning CA2227: Change 'Messaging' to be read-only by removing the property setter.
##[warning]libraries\Adapters\Microsoft.Bot.Builder.Adapters.Facebook\FacebookEvents\FacebookEntry.cs(32,38): Warning CA2227: Change 'Changes' to be read-only by removing the property setter.
##[warning]libraries\Adapters\Microsoft.Bot.Builder.Adapters.Facebook\FacebookEvents\FacebookEntry.cs(38,38): Warning CA2227: Change 'Standby' to be read-only by removing the property setter.
##[warning]libraries\Adapters\Microsoft.Bot.Builder.Adapters.Facebook\FacebookEvents\FacebookResponseEvent.cs(14,36): Warning CA2227: Change 'Entry' to be read-only by removing the property setter.
##[warning]libraries\Adapters\Microsoft.Bot.Builder.Adapters.Facebook\Message.cs(31,41): Warning CA2227: Change 'Attachments' to be read-only by removing the property setter.

**Comment by garypretty** [comment]
Resolved in PR #2953
