### ISSUE TITLE
Fix WebSocket Warnings

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#2848]
Please fix these warnings, and enable "Warnings as errors" in the relevant project. 

> 55>WebSocketTransportTests.cs(30,13,30,32): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
> 55>WebSocketTransportTests.cs(25,27,25,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 55>WebSocketTransportTests.cs(35,27,35,59): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 55>WebSocketTransportTests.cs(52,27,52,56): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 55>WebSocketTransportTests.cs(94,27,94,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 55>WebSocketTransportTests.cs(107,27,107,55): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 55>WebSocketTransportTests.cs(192,64,192,76): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 55>Mocks\MockPayloadSender.cs(23,47,23,59): warning CS0067: The event 'MockPayloadSender.Disconnected' is never used
>

**Comment by cleemullins** [comment]
@carlosscastro Is this something you can get to? IF not, I can have Southworks clean this up.

**Comment by carlosscastro** [comment]
@cleemullins I'll do this before end of week.
