### ISSUE TITLE
[Adaptive] @ should not be a special character outside of ```

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2852]
Inside of ``` we use @{expr} to evaluate an expression.  Outside of ``` we just use {expr}.  It appears that the parser always treats @{ as the start of an expression--even when outside of ```.  Either we should disallow this or clarify in our documentation that {} and @{} can be used anywhere.

[bug]

**Comment by vishwacsena** [comment]
I have an update via this PR where this is clarified. In general, we should continue to push towards @{} for all expressions so you do not have to remember to do this only within multiline. 

Also the latest samples and docs do not have [TemplateName] but instead are pushing for @{templateName()} everywhere. 

https://github.com/microsoft/BotBuilder-Samples/pull/1862
