### ISSUE TITLE
[Adaptive] [LG] Support empty parametrization during template definition

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2854]
This should work - 

```markdown
# TemplateName () 
- one
- two
- three
```

**Comment by Danieladu** [comment]
Is whitespace allowed between template name and the open bracket ?

**Comment by vishwacsena** [comment]
Yes. Any concerns with supporting that?

**Comment by Danieladu** [comment]
> Yes. Any concerns with supporting that?

no, just confirm it.
