### ISSUE TITLE
Slack adapter - Revert Newtonsoft Json version to 10

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-dotnet#2858]
Currently in the Slack adapter, version 11 of Json.Net is being referenced due to a dependency being taken on a converter only available in v11.  We need to work around this and bring the Slack adapter in line with other packages to use v10.x.

**Comment by cleemullins** [comment]
I would *HOLD* the slack adapter from GA until this is fixed. We could continue to release as "-preview".

**Comment by garypretty** [comment]
@ceciliaavila / @matiasroldan6 - could someone look at this next week please? Ideally making the changes required to bring Newtonsoft Json back to v10 (in line with the version currently used by the rest of the SDK). I will be OOO for 2 weeks, but please ping @gabog / @cleemullins if you hit any blockers.

**Comment by Aliandi** [comment]
ACK, we'll be starting this issue today

**Comment by johnataylor** [comment]
To satisfy other dependencies in the asp core integration we think we need to move to 11.

**Comment by garypretty** [comment]
@matiasroldan6 / @LCarbonellRod could you confirm with @johnataylor which version of 11 we are planning to move to and then also confirm if this means we can revert the changes on the related PR? Is the feature we lost when moving to 10 available id we just roll down to 11?

**Comment by johnataylor** [comment]
We ended out moving to 12.0.3 hope that works. I'll close this now. Reopen and ping @EricDahlvang and myself if there is a problem.
