### ISSUE TITLE
Serialization of ChannelData doesn't work with Anonymous Types

### ISSUE THREAD

**Issue by Peternator7** [Microsoft/botbuilder-dotnet#286]
Hey bot team,

I'm trying to set up native Facebook notifications using `ChannelData`. When I pass an anonymously typed object (I haven't tried this with a named type yet), the object is serialized as `{}`. I see that it's a SafeJsonConvert. Is that the expected behaviour?

Thanks!

**Comment by cleemullins** [comment]
@EricDahlvang  - Eric, if you have a moment, could you investigate this? 

I suspect the answer is "By Design" as we're using Newtonsoft to do the serialization, and sticking with it's default behavior(s) is the right thing for us to be doing.

**Comment by EricDahlvang** [comment]
The documentation here https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-channeldata states:

> The value of an Activity object's ChannelData property is a JSON object. Therefore, the examples in this article show the expected format of the channelData JSON property in various scenarios. To create a JSON object using .NET, use the JObject (.NET) class.

Example:
 
> reply.ChannelData = JObject.FromObject( new  { Text = "Channel Data Text", OtherField = 1 });


There's also a little more explanation in @craigjensen answer here : https://github.com/Microsoft/BotBuilder/issues/998  

> ReadOnlyJsonContractSerialzer is the default from AutoRest generated client code and does not work with anonymous types.

**Comment by vishwacsena** [comment]
This by design with json .net
