### ISSUE TITLE
[Streaming, Engineering] Reenable functional Direct Line Speech tests

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#2863]
## Description
The Direct Line Speech functional tests that were added in 4.6 were disabled in `master` in https://github.com/microsoft/botbuilder-dotnet/pull/2861. This is due to the fact that Direct Line Speech support is not available in ARM, so the DLS tests will fail as the resources are recreated in the pipeline.

## Steps to Solution
Azure CLI or REST support for Direct Line Speech and the configuration required to enable streaming.

See **https://github.com/microsoft/botframework-sdk/issues/5655**

**Comment by cleemullins** [comment]
Currently blocked on ARM Support, which is being worked by @DDEfromOR

**Comment by DDEfromOR** [comment]
Bumping this to after R7. It requires changes on the service side and then having a partner team pull those changes in to their product, which isn't likely to land before R7 due to blackouts.
