### ISSUE TITLE
Streamline escape character in LG

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#2868]
This should be a follow up with #2786 

## Description
Because we suppose multiple kind of syntax to refer template and call functions, so it's hard to maintain an consistent escape character assumption. 

For example, today, if i don't make string evaluated, i just want to emit plain text `@{something}`

## Actual
the correct syntax today is to write `@\{something}`, because @ don't need to be escaped, but { should be, the underlying reason is we support @{} and {}. 

We should support one single way to do the evaluation, and one single way to escape to avoid evaluation. 

## Expected
Evaluate: `@{exp}`
Escape: `\@{exp}`  

Both in normal mode and in multi-line mode. 

## More context
We should revisit the escape character design, in LG body, conceptually we should think it's already be quoted. So `\` is the special character, so here is the design we need to confirm

For a given sequence `\x`, 
  if x is a supported escape character, like 'r', 'n', we should evaluate as a whole
  if x is a any other character, like "@" or "\", we should evaluate to x itself   
  if \ is not followed by any x, we should evaluate to empty

To enable use escape character to avoid evaluation, we just made escape character to be high priority than expressions.

**Comment by vishwacsena** [comment]
We should ensure the following work - 
- \@{exp}, \{exp} -> entire expression is escaped
- @{exp == "\'\'"} -> Only the character after is escaped
- @{exp == "\\r\\n"} -> Only the character after is escaped.

**Comment by boydc2014** [comment]
> We should ensure the following work -
> 
> * @{exp}, {exp} -> entire expression is escaped
> * @{exp == "''"} -> Only the character after is escaped
> * @{exp == "\r\n"} -> Only the character after is escaped.

yes, for sure.  To be more specific
here we are discussing LG escape, which should be used to avoid expression evaluation.  which is your 1st case. 

2nd is a string literal, which is not related to escape
3st is escape problem, but it's inside the expression scope. Which is supported, but not related to this issue
