### ISSUE TITLE
[Adaptive] [CEL] TIMEX prebuilt functions

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2869]
TIMEX is common representation for datetime entity recognizer both in LUIS as well as in the regex recognizer supported by Adaptive dialogs. 

Today, we are lacking ability to deal with TIMEX expressions in our prebuilt functions list available as part of the common expression language. 

To help work with TIMEX we will add the following functions to the prebuilt CEL functions under a new TIMEX section - 

1. Timex.hasFullDate(obj)

Obj must have `timex` property with a timex expression. Function returns true if a fully resolved date is found in timex property. 

| Timex | Outcome |
|--------|-----------|
| XXXX-XX-2 | false |
| 2020-02-12 | true |

```C#
new DateTimeInput()
{
    Prompt = new ActivityTemplate("Need valid full date"),
    Property = "$validDate",
    AllowInterruptions = "false",
    Validations = new List<string>()
    {
        "timex.hasFullDate(this.value)"
    }
}
```

2. Timex.hasValidHour(obj)

Obj must have `timex` property with a timex expression. Function returns true if a fully resolved time with valid hour (00-23) is found in timex property. 

| Timex | Outcome |
|--------|------------|
| T08 | true |
| PT30M | false |
| T08:30 | true |
| T20:30 | true |

```C#
new DateTimeInput()
{
    Prompt = new ActivityTemplate("Need valid full time with hour and minutes"),
    Property = "$validDate",
    Validations = new List<string>()
    {
        "timex.hasValidHour(this.value)"
    }
},
```

We can continue to add to the prebuilt functions available under timex scope but let's start with these core functions.

**Comment by cleemullins** [comment]
@vishwac, this is a P1 issue that's 6+ Months old. How (if?) do we push it forward?

**Comment by cosmicshuai** [comment]
@vishwacsena I have two question here. The first one is, when user attempt to call these two functions, 
which one of  `hasFullDate(timex)` or `timex.hasFullDate(timex)` should they use? 
Another question is hasFullDate can only take a TimexProperty object or both TimexProperty object and string should work?
I have a draft PR: https://github.com/microsoft/botbuilder-dotnet/pull/3780
Could you check this PR to see whether the implementation meets the original design.

**Comment by vishwacsena** [comment]
@cosmicshuai I was suggesting that we namespace the prebuilt functions list by their function. I think for R9, let's just have them as hasFullDate() and hasValidHour() but document this under a separate timex section in the prebuilt functions doc. 

For question 2, I believe we should support both TimexProperty object as well as string.
