### ISSUE TITLE
[LG] [CEL] Add support for suffix `?` as safe operator

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2875]
To reference null properties in an object without a runtime error, use the question mark operator. For example, to handle null outputs from a trigger, you can use these expressions:
```
userName? -> `userName = null`
$userName? -> `$userName = null`
user.name? -> `user.name = null`
user.profile.name? -> first thing which is null  - e.g `user = null` or `user.profile = null` or `user.profile.name = null`
user.lists[$listType]? -> first thing which is null - e.g. `user = null` or `user.lists = null` or `user.lists[$listType] = null`
```
If the value is null, then we will output `<property> = null` as the value

**Comment by Danieladu** [comment]
Now it is supported by default without "?".  
For example, `user.profile?.name`, if profile is null, the whole expression will be evaluated to null.

So, should be keep the current state or distinguish whether there is a question mark,(above example, with "?" will return null and without "?" will throw exception.)

**Comment by vishwacsena** [comment]
#3079

**Comment by vishwacsena** [comment]
Make the default behavior to not throw and instead return text form that shows which property/ memory scope is null.
