### ISSUE TITLE
Add type checking in ActivityFactory

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#2878]
We use ActivityFactory to turn lg result into Activity, especially structure lg result, including all kinds of cards. But it's hard to make it right once, and if i miss type something, miss a trailing "s" or use lowerCase instead of upper case, i won't get what i want, and there is no obvious clue for me to fix that. 

To help user to write a correct structure lg template more easily, we should add more checking into our acitivity factory, if any structure field (other than $type) can't be converted into Activity filed, we should emit warn or error, some thing user can see on stdout. 

We should also do that in the card conversion, especially for in adapativeCard. Do as much as we can to give user clue what happened and how to fix.

We should also update Manaco and VSCode extension to help use identify right property.

**Comment by vishwacsena** [comment]
[P0] Consider adding json schema for all structured LG templates supported out of the box. 
[P1] Consider adding support for json schema definition for custom structures defined by user.
