### ISSUE TITLE
NumberPrompt takes only int and float. By design?

### ISSUE THREAD

**Issue by v-stbee** [Microsoft/botbuilder-dotnet#288]
I tried using long, double, and decimal for the generic type in NumberPrompt. The code compiled and ran just fine, but no numbers of any sort were recognized for any of those three types, only when using int and float. I am writing up NumberPrompt in the wiki as accepting int and float, under the assumption that it's not supposed to deal with other numeric types.

**Comment by v-stbee** [comment]
I should have mentioned I tried uint as well, with the same result.

**Comment by johnataylor** [comment]
Looks to me like we should just cover all the numbers here.

**Comment by johnataylor** [comment]
added long, double, decimal with unit tests
