### ISSUE TITLE
Remove 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#2888]
In the Dir.props file, remove and/or fix the GeneratePAcakgeOnBuild attribute. 

As it sits, this prevents the Nuget attributes from properly being set on the packages. 

```
<PropertyGroup Condition="'$(GeneratePackageOnBuild)' == 'True'">
```

This change was made directly (!) in the 4.6 branch, and needs to be made on master.

**Comment by BruceHaley** [comment]
Pr is #2889 https://github.com/microsoft/botbuilder-dotnet/pull/2889/files

**Comment by cleemullins** [comment]
This has been done.
