### ISSUE TITLE
Missing UserStateManagerMiddleware and ConversationStateManagerMiddleware from AlarmBot samples, probably old and to be removed

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#289]
The READMEs for both AlarmBot and AlarmBot-Cards include the following:

The UserStateMangerMiddleware() and ConversationStateManagerMiddleware() adds automatic persistence of the **context.state.ConversationProperties** and **context.state.UserProperties** objects.  

None of the above is found in any of the files for the repo, I think it's probably old and needs to be removed?

**Comment by cleemullins** [comment]
@JonathanFingold Could you take a quick look at this and resolve? I believe we're plannning to delete the AlarmBot samples soon, so I'm not sure how much we should invest in this.

**Comment by vishwacsena** [comment]
By design. We are replacing the alarm bot sample.
