### ISSUE TITLE
Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.6.0-preview2 is missing Memory Extenstion

### ISSUE THREAD

**Issue by som-nitjsr** [microsoft/botbuilder-dotnet#2890]
## Version
Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.6.0-preview2

## Describe the bug
I have updated my updated my bot to 4.6 GA and using Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.6.0-preview2 
This package is missing **DialogContextExtensions**
https://github.com/microsoft/botbuilder-dotnet/tree/4.6/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory
The only option i see is to use Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.7.0-
but in that case whole sdk will be preview version.
from where i can get a nuget package for 4.6 which include 
https://github.com/microsoft/botbuilder-dotnet/tree/4.6/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory
 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by tomlm** [comment]
The package includes it, you need to have a using statement for 
```cs
using Microsoft.Bot.Builder.Dialogs.Memory;
```
Then you should see on dialogContext.GetState()

**Comment by som-nitjsr** [comment]
Thanks it worked.
