### ISSUE TITLE
DL Speech token refresh does a silent NRE when trying to refresh the token

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botbuilder-dotnet#2897]
## Version
4.6

## Describe the bug
There may be a bug in the token refresh thing (not customer visible except through their logger), but when I use speech with a non-standard ICredentialProvider I see this in the logs:

Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
Failed to fetch token before processing outgoing activity. Object reference not set to an instance of an object

## To Reproduce
Make your own ICredentialProvider and register it + use it with your adapter, then use DL Speech. In the logs you see this error (doesn't impact bot though).

## Expected behavior
Shouldn't report this error if we can't refresh the token, it's benign.

## Additional context
Daniel is the man.

[bug]

**Comment by DDEfromOR** [comment]
The error is benign, but if it's never logged we're back in the original boat of not having any indication the token hasn't been refreshed for weeks, leading to the bot's credentials expiring. We can workshop better ways of surfacing the lack of refreshes without spamming logs with benign errors.

**Comment by sgellock** [comment]
@carlosscastro can you drive this to closure for R7 please.

**Comment by carlosscastro** [comment]
A pull request for this is going out today :)

**Comment by carlosscastro** [comment]
Ted ended up fixing this cast during his refactor of how we get app ids. The cast to SimpleCredentialProvider is there no more, which was originally causing the null ref exception.
