### ISSUE TITLE
PartitionKey cannot be set through CosmosDbStorage.cs ctor

### ISSUE THREAD

**Issue by dawwa** [microsoft/botbuilder-dotnet#2898]
## Version
4.2, but it seems applying to all versions after reading the code.

## Describe the bug

Providing PartitionKey  through the DocumentCollectionRequestOptions of CosmosDbStorageOptions cannot property create the PartitionKey for the collection, it turns out that in the CreateDocumentCollectionIfNotExistsAsync invoked in the InitilizeAsync method, it's missing the PartitionKey property while constructing the DocumentCollection object, so it should be
`                    new DocumentCollection
                    {
                        Id = callingCollectionName,
                        PartitionKey = new PartitionKeyDefinition()
                        {
                            Paths = new Collection<string>() { partitionKey }
                        }
                    }
`
[bug]

**Comment by mdrichardson** [comment]
[4.2 was released in December, 2018](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.2.0) and we didn't [add PartitionKey support until March, 2019](https://github.com/microsoft/botbuilder-dotnet/blame/35709d5fab54d525fd0d6e478da3b1b296b2df73/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L31).

That being said, [you shouldn't use it](https://github.com/microsoft/botframework-sdk/issues/5467). Instead you should use [`CosmosDbPartitionedStorage`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs) (released in 4.6) if you want partitioning. [Here's a sample](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs)
