### ISSUE TITLE
Need guidance on when/why to use MessageFactory vs Adaptive Cards

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#290]
Our samples use both `MessageFactory` and `AdaptiveCards` but on our wiki we're missing guidance on when to use these and what differences may present themselves.

**Comment by Stevenic** [comment]
This will all be in the conceptual docs which are still 2 milestones out.

**Comment by yochay** [comment]
@Kaiqb can you please create a doc issue, copy the link to here and close this one?

**Comment by Kaiqb** [comment]
Added to internal VSTS for tracking.
