### ISSUE TITLE
[Adaptive] [DCR] Update `OutputFormat` property on inputs to be an expression

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2900]
Today we have a set of limited options for `OutputFormat` property on inputs. Given we have the full power of common expression language, we should just support expressions instead of limited set of options we support for output format. 

microsoft/BotFramework-Composer/#1402

**Comment by luhan2017** [comment]
@vishwacsena , I have investigated on this and want to understand more about the requirements.

Currently only four inputs types supports outputFormat:

TextInput, supports trim, lowercase and uppercase.
NumberInput, supports float(default) and integer.
ChoiceInput, supports index and value(default).
AttachmentInput, supports all and first(default).

what is the exact scenario we want. Should we just support TextInput output as an expression? and keep others the same? I think we should at least keep the AttachmentInput as it is.

Thoughts?

**Comment by vishwacsena** [comment]
@luhan2017 we should do the following - 

1. For text, number input, make `OutputFormat` be an expression so user can format the captured input how so ever they wish.
2. For ChoiceInput, AttachmentInput - leave OutputFormat as is.
3. Add OutputFormat property to Confirm, datetime input as an expression

**Comment by luhan2017** [comment]
I related this issue to PR 3046 by mistake, PR 3069 is the real one to fix this

**Comment by vishwacsena** [comment]
@luhan2017 pushing to R8.
