### ISSUE TITLE
Adaptive Dialogs DCR: trigger specificity

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#2906]
The way that the trigger mechanisms fire today, it's a real chance that users will configure triggers that conflict with each other. For example, if someone hooks in to a "Activity received" and also a "Message received" trigger, only one trigger gets to handle the actual event.

I'd like to discuss this design, and suggest a change to make things more intuitive for users: taking the "most specific" trigger configured, whichever is lowest in the inheritance hierarchy. Taking the example above, a Message is also an Activity so the suggested design would take the Message trigger over the Activity trigger.

This models decently with the interruption conventions.

[enhancement]

**Comment by chrimc62** [comment]
There is a mechanism in the TriggerTree stuff that would allow building in this knowledge to its most specific logic.

**Comment by vishwacsena** [comment]
We discussed this in SDK triage and the work required here is covered via the following items - 

- https://github.com/microsoft/botbuilder-dotnet/issues/3007
- https://github.com/microsoft/botbuilder-dotnet/issues/3008
- https://github.com/microsoft/BotFramework-Composer/issues/1632
- https://github.com/microsoft/BotFramework-Composer/issues/1633
