### ISSUE TITLE
JsonSerializationException - CosmosDbStorage.ReadAsync: Cannot populate JSON object onto type 'Microsoft.Graph.CallParticipantsCollectionPage'

### ISSUE THREAD

**Issue by dawwa** [microsoft/botbuilder-dotnet#2908]
## Version
4.2.

## Describe the bug
The exception throws upon the ReadAsync of [CosmosDbStorage](https://github.com/microsoft/botbuilder-dotnet/blob/4.2/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs) 
```csharp
IDictionary<string, object> items = await _storage.ReadAsync(new[] { fullStorageKey }, cancellationToken).ConfigureAwait(false);
```
Detail exception message as below:

> Exception caught: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll ("Cannot populate JSON object onto type 'Microsoft.Graph.CallParticipantsCollectionPage'. Path 'participants.$type'.") Exception caught: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll ("Cannot populate JSON object onto type 'Microsoft.Graph.CallParticipantsCollectionPage'. Path 'participants.$type'.")

After reading the following source code, seems like it gets some trouble while trying to understand the corresponding JsonContractType of the Microsoft.Graph.CallParticipantsCollectionPage, however, I'm not 100% sure it's a bug or just I need do some special setting.  

**It would be appreciated if there is any workaround can make the [CosmosDbStorage](https://github.com/microsoft/botbuilder-dotnet/blob/4.2/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs) be able to read the item I stored into cosmos DB that has property of Microsoft.Graph.CallParticipantsCollectionPage type exists.**

https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs

```csharp
public class CallParticipantsCollectionPage : CollectionPage<Participant>, ICallParticipantsCollectionPage, ICollectionPage<Participant>, IList<Participant>, ICollection<Participant>, IEnumerable<Participant>, IEnumerable
```

```json
                "participants": {
                    "$type": "Microsoft.Graph.CallParticipantsCollectionPage, Microsoft.Graph.Communications.Core.Calls",
                    "$values": [
                        {
                            "$type": "Microsoft.Graph.Participant, Microsoft.Graph.Communications.Core.Calls",
                            "info": {
                                "$type": "Microsoft.Graph.ParticipantInfo, Microsoft.Graph.Communications.Core.Calls",
                                "identity": {
                                    "$type": "Microsoft.Graph.IdentitySet, Microsoft.Graph",
                                    "application": {
                                        "$type": "Microsoft.Graph.Identity, Microsoft.Graph",
                                        "id": "37af506a-8b24-4fca-a359-f3b887500000",
                                        "tenantId": "80dfc884-160d-455b-8e52-476de0700000"
                                    }
                                },
                                "endpointType": "default"
                            },
                            "mediaStreams": {
                                "$type": "System.Collections.Generic.List`1[[Microsoft.Graph.MediaStream, Microsoft.Graph.Communications.Core.Calls]], System.Private.CoreLib",
                                "$values": [
                                    {
                                        "$type": "Microsoft.Graph.MediaStream, Microsoft.Graph.Communications.Core.Calls",
                                        "mediaType": "audio",
                                        "sourceId": "1",
                                        "direction": "sendReceive",
                                        "serverMuted": false
                                    }
                                ]
                            },
                            "isMuted": false,
                            "isInLobby": false,
                            "id": "5528d3db-8e6a-4ae2-a86b-571e6300000"
                        }
                    ]
                },
```

**Comment by mdrichardson** [comment]
@dawwa Can you include enough of your code that will allow me to repro this or a link to your repo? Is that last code block the data you're trying to store and retrieve?

I wouldn't expect any changes to be made to `CosmosDbStorage`, especially for custom usage not related to `BotState`, since it's going to be deprecated soon. You can always create your own storage class, if needed.

That being said, I'm happy to troubleshoot this and search for a workaround.

Your best bet would be to [pass in a different serializer](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs#L96)

**Comment by mdrichardson** [comment]
@dawwa Do you still need help with this?

**Comment by mdrichardson** [comment]
@dawwa I'm going to close this issue due to inactivity. Feel free to re-open if needed.
