### ISSUE TITLE
Throughout wiki, point to samples that illustrate concepts

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#291]
Our wiki and samples go together; it'd be helpful if the wiki pointed out when "you can see this concept in action in SomeFile.cs of the _____ Sample [here](http://link.to.file)

**Comment by JonathanFingold** [comment]
@brandonh-msft , after some discussion within the docs team, once the v4 doc content is available on docs.Microsoft.com, the how-tos on the wiki will come down and a link will point folks to the docs. We still need to decide whether to try to keep in sync with them, and if so, which direction that should go.
