### ISSUE TITLE
[Adaptive] Log to console generates trace with a label of 'BeginDialogAsync'

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-dotnet#2913]
When using the Log to Console Shape all trace events raised have a label of `BeginDialogAsync` which is confusing when it shows up in the Emulator as shown below

![image](https://user-images.githubusercontent.com/33519520/68084911-25920c80-fe09-11e9-929c-2fd589feb8c2.png)

![image](https://user-images.githubusercontent.com/33519520/68084826-e2379e00-fe08-11e9-8f87-995ee719bc58.png)

## To Reproduce

![image](https://user-images.githubusercontent.com/33519520/68084835-fa0f2200-fe08-11e9-89d0-8f03f15c5035.png)

## Expected behavior
- A more general name - potentially provided by the developer on the shape configuration or perhaps "Composer Trace"

**Comment by vishwacsena** [comment]
Add a property `label` to TraceActivity action and include that as the label in the trace. Default value is `Trace`.
