### ISSUE TITLE
Parameter CancellationToken not used in WaterfallStepContext.NextAsync

### ISSUE THREAD

**Issue by arman-g** [microsoft/botbuilder-dotnet#2921]
## Version
4.6.1 SDK

## Describe the bug
The cancellation token parameter that is passed to WaterfallStepContext.NextAsync function is not being used.
WaterfallStepContext class line: 101

## To Reproduce
See the screenshot

## Expected behavior
WaterfallStepContext.NextAsync function should use the passed cancellation token instead of instantiating a new instance of CancellationToken.

## Screenshots
![UML](https://user-images.githubusercontent.com/22778273/68268300-7d4b9600-000a-11ea-93af-cf6e15bf3a09.png)

[bug]

**Comment by compulim** [comment]
@arman-g thank you for the issue and the screenshot looks great. We will fix this in R7 which is slated to release around December 10th.
