### ISSUE TITLE
Work items for 4.6.2

### ISSUE THREAD

**Issue by sgellock** [microsoft/botbuilder-dotnet#2928]
Below are the works items that need to be addressed for the 4.6.2 release 
- [x] manually apply change from PR #2259 into master, cherry pick to 4.6 branch (Steve)
- [x] cherry pick PR #2926 to 4.6 branch (Colonel)
- [x] publish 4.6.2 bits (Colonel)
- [x] back out CoreBot.tests changes from dotnet samples repo (Scott)
- [x] back out CoreBot.tests changes to .NET Template (Scott)
- [x] back out CoreBot.tests changes to VSIX (Scott)
- [x] bump .NET Core Template version numbers to 4.6.2, update csproj files to use 4.6.2 assemblies (Scott)
- [x] bump VSIX version number to 4.6.2, update csproj files to use 4.6.2 assemblies (Scott)
- [x] bump csharp_dotnet samples to use 4.6.2 Bot Fx (Johnny)
- [x] publish 4.6.2 .NET Templates (EchoBot, CoreBot, EmptyBot) (Colonel)
- [x] publish 4.6.2 version of VSIX (Colonel)

**Comment by Stevenic** [comment]
PR to revert cancel is submitted. #2929

**Comment by cleemullins** [comment]
4.6.2 packages are on MyGet. 
https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder/4.6.2

**Comment by sgellock** [comment]
VSIX, .NET Templates, and C# CoreBot.tests test changes have been merged in PR #1960

**Comment by cleemullins** [comment]
VSIX, .Net Templates and packages are all on MyGet.
