### ISSUE TITLE
Default value in Prompts

### ISSUE THREAD

**Issue by mareekuh** [microsoft/botbuilder-dotnet#2934]
Issue: the default value as a label in the USer Input Prompt editor tab is confusing. There are other bugs about this that were closed.

1. The words 'default value' are confusing
2. The value is not set by default so of people dont understand what this is, the bot keeps looping when invalid input is received.
3. The tooltip is not useful to help the user undestand when and why to fill this out

![Screen Shot 2019-10-31 at 2 48 57 PM](https://user-images.githubusercontent.com/48503434/67988956-ad4fff00-fbee-11e9-8acd-9fa0eb0d9194.png)
![Screen Shot 2019-10-31 at 2 57 08 PM](https://user-images.githubusercontent.com/48503434/67988982-be007500-fbee-11e9-8a36-607a8ea1455b.png)
 

Recommendations:
Change 'Default value' to : Default User Input 
thereby matching the tab name and making it more clear what 'value' is.

Add the following copy under the text box:
The default input is updated when valid valid user input is received.

**Comment by cwhitten** [comment]
@tomlm @vishwacsena @mareekuh I've transferred this to botbuilder-dotnet for visibility/discussion

**Comment by vishwacsena** [comment]
Default value should default to `null`
@vishwacsena  to work with @mareekuh  on schema updates.

**Comment by vishwacsena** [comment]
This is tracked via SDK issue https://github.com/microsoft/botbuilder-dotnet/issues/2934

**Comment by vishwacsena** [comment]
Fix text for `Value`, `Default value`

`Default value`
Value to use when we exceed max turn count for this input.

`Value`
Expression to evaluate every time user responds to this input as the value for the property

**Comment by sangwoohaan** [comment]
Can Value be Value to recognize or Expression to evalutate value?
