### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized) - nuget package reference

### ISSUE THREAD

**Issue by Kumar3010** [microsoft/botbuilder-dotnet#2938]
we have a bot project with the nuget package referring to "https://botbuilder.myget.org/F/experimental/api/v3/index.json" and it worked fine till yesterday and from today onwards its throwing unthorized error.
could you please let us know if this url has been modified and if so what is the correct one.

appreciate your help.

**Comment by dmvtech** [comment]
@Kumar3010 Which nuget package specifically?

**Comment by Kumar3010** [comment]
Its botbuilder streaming extensions

**Comment by ppn494** [comment]
I found the Microsoft.Bot.Protocol.StreamingExtensions has been moved to Microsoft.Bot.Builder.StreamingExtensions....Modified my code to refer the new namespace and the project is building fine.

**Comment by ppn494** [comment]
fyi https://github.com/microsoft/botbuilder-dotnet/issues/2947

**Comment by sgellock** [comment]
@Kumar3010 this preview assembly was renamed.  Issue #2947 has further details, but basically Microsoft.Bot.Protocol.StreamingExtensions has been moved to Microsoft.Bot.Builder.StreamingExtensions
