### ISSUE TITLE
Need docs/guidance/example on how to create own Storage connector

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#294]
Since we ship with only Memory, File, and (if you import the right pkg) Azure Table storage connectors, we need guidance on how to roll one's own Storage connector.

**Comment by Stevenic** [comment]
Great topic to add to the conceptual docs.

**Comment by JonathanFingold** [comment]
Many topics (including this) are slated for the docs (docs.microsoft.com) but not for the wiki.

**Comment by brandonh-msft** [comment]
@JonathanFingold did this get added to the docs already? if not i feel it should remain open.

**Comment by JonathanFingold** [comment]
@brandonh-msft , The conceptual piece is drafted. Two how-to topics (**manage state** and **how to write to storage**) are stubbed in and under development. There's a third how-to that's related to state that's under discussion.
