### ISSUE TITLE
C# 8 Support

### ISSUE THREAD

**Issue by arman-g** [microsoft/botbuilder-dotnet#2940]
**Is your feature request related to a problem? Please describe.**
Currently using bot-framework SDK locks down C# version of the project to the greatest version of the package which in this case is the C# version of bot-framework.

**Describe the solution you'd like**
Support C# v8 so we can use the new C# features in a project.

**Describe alternatives you've considered**
None

**Additional context**
None

[enhancement]

**Comment by compulim** [comment]
We planned to address this in upcoming release (R7 around December 10).

**Comment by cleemullins** [comment]
I'm looking at this today, and will report back.

**Comment by cleemullins** [comment]
Our packages are built using ['latest'](https://github.com/microsoft/botbuilder-dotnet/blob/83fb03ee030497be137cc9cbfd430bcdb497f674/Directory.Build.props#L7) as the binding target for language version:
```
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
```
This is pushed across all of our packages via the [directory.build.props](https://github.com/microsoft/botbuilder-dotnet/blob/83fb03ee030497be137cc9cbfd430bcdb497f674/Directory.Build.props#L7) file. 

We cannot switch to this "8", as we target NetCore 2.1 as part of our test and regression suite. 

As I understand [this article](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) our targeting using "latest" seems the correct choice based on how we compile and test. 

To check this works, I've written the following code (note the C# 8 syntax, of a static method). This code pulls in the Bot Framework 4.6.3, and creates an Activity just to make sure it can.

```cs
    class Program
    {
        static void Main(string[] args)
        {
            Activity foo = new Activity();
            foo.Text = "test";

            int y = 5;
            int x = 7;
            Console.WriteLine(foo.Text + " " + Add(x, y));

            static int Add(int left, int right) => left + right;           
        }
    }
```

When run, this results in:
![image](https://user-images.githubusercontent.com/1165321/69671783-9238a980-104b-11ea-8efa-1929f4ea5257.png)

And confirming that the project is indeed .Net Core, here's my csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bot.Builder" Version="4.6.3" />
  </ItemGroup>

</Project>
```

Given the above, I think we're good and doing the right thing.
