### ISSUE TITLE
Unable to find package Microsoft.Bot.Protocol.StreamingExtensions.NetCore. No packages exist with this id in source(s): NuGetOrg

### ISSUE THREAD

**Issue by ppn494** [microsoft/botbuilder-dotnet#2947]
## Version
 4.4.5

## Describe the bug
I had a working DevOps pipeline with Azure DevOps and BotFramework. My build is failing as of Thursday morning due to the package Microsoft.Bot.Protocol.StreamingExtensions.NetCore with the error NU1101: Unable to find package Microsoft.Bot.Protocol.StreamingExtensions.NetCore. No packages exist with this id in source(s): NuGetOrg.

## Screenshots
Upon trying to access this url ‘https://botbuilder.myget.org/F/experimental/api/v3/index.json’ I am being prompted to give a user name and password.

Please see the error below which occurs in our build pipeline. 
/usr/share/dotnet/sdk/3.0.100/NuGet.targets(123,5): error : Unable to load the service index for source https://botbuilder.myget.org/F/experimental/api/v3/index.json---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
 

## Additional context
This had been working until end of day Wednesday. Not sure what changed on the bot framework which causes the error.

[bug]

**Comment by ppn494** [comment]
Version : 4.4.5

Bug Description:
I had a working  DevOps pipeline with Azure DevOps and BotFramework. My build is failing as of  Thursday morning due to the package Microsoft.Bot.Protocol.StreamingExtensions.NetCore with the error NU1101: Unable to find package Microsoft.Bot.Protocol.StreamingExtensions.NetCore. No packages exist with this id in source(s): NuGetOrg. 

Please see the error below which occurs in our build pipeline. Upon trying to access this url ‘https://botbuilder.myget.org/F/experimental/api/v3/index.json’  I am being prompted to give a user name and password.
 
/usr/share/dotnet/sdk/3.0.100/NuGet.targets(123,5): error : Unable to load the service index for source https://botbuilder.myget.org/F/experimental/api/v3/index.json

However this had  been working until end of day Wednesday. Not sure what changed on the bot framework which causes the error.

**Comment by ppn494** [comment]
Update: I found the Microsoft.Bot.Protocol.StreamingExtensions has been moved to Microsoft.Bot.Builder.StreamingExtensions....Modified my code to refer the new namespace and the  project is building fine.

**Comment by sgellock** [comment]
@ppn494, sorry for the disruption.  we did some clean up of old, outdated assemblies and maybe got a little to aggressive and didn't communicate this as well as we could have.  Given that you are back up and running I'm going to close this issue.  if you need further help, just reach back out.

**Comment by BillStrait** [comment]
I'm not able to find `StreamingExtensions` in Microsoft.Bot.Builder, and I don't see `WebSocketEnabledHttpAdapter` anywhere else. I am on the most recent build of Microsoft.Bot.Builder according to NuGet. Are we sure that's the right path?

**Comment by dmvtech** [comment]
@BillStrait Microsoft.Bot.Builder.StreamingExtensions is it's own package

- https://www.nuget.org/packages/Microsoft.Bot.Builder.StreamingExtensions/
- https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.StreamingExtensions
