### ISSUE TITLE
LG evaluates text in curly braces without preceding "@" as expressions

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/botbuilder-dotnet#2948]
## Version
4.6.0-preview2

## Describe the bug
LG tries to evaluate expressions that are enclosed in curly braces. Take the following card as an example:
```
# WelcomeCard
[Activity
    Attachments = @{json(AdaptiveCard.Definition())}
]

# AdaptiveCard.Definition
- ```
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Click to submit",
                    "data": {
                        "sampleInput": "{Hi}"
                    }
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```
Rendering it will fail with error 
```
Error occurs when evaluating expression WelcomeCard(): Error occurs when evaluating expression json(AdaptiveCard.Definition()): Specified argument was out of the range of valid values.
Parameter name: 'hi' does not match memory scopes:user,conversation,turn,settings,dialog,class,this
```

Trying to escape the curly braces won't help as well:
```
"sampleInput": "\{Hi\}"

Error:Error occurs when evaluating expression WelcomeCard(): Error occurs when evaluating expression json(AdaptiveCard.Definition()): Bad JSON escape sequence: {.
```

## To Reproduce
1. Define the card above in a .lg file
2. Send the card from an adaptive dialog:
```
Actions = new List<Dialog>
{
    new SendActivity("@{WelcomeCard()}")
}
``` 
## Expected behavior
The `"{Hi}"` string should be used as is. My understanding from the docs and samples is that `@{}` should be used to indicate expressions.

[bug]

**Comment by boydc2014** [comment]
Thanks @fabio-muramatsu, previously we support multiple forms to evaluate expression. I believe this is solved in master (R7 preview now), in which we streamline the syntax, by only evaluting text in `@{}`, and the only way to escape evaluating this is `\@{}`.

**Comment by vishwacsena** [comment]
@boydc2014 - what's a good workaround with 4.6.0-preview2 bits? Would `\@{}` work with those bits? If not, what will?

**Comment by Danieladu** [comment]
> @boydc2014 - what's a good workaround with 4.6.0-preview2 bits? Would `\@{}` work with those bits? If not, what will?
It is a bug in 4.6.0-preview2 version.  A workaround is to use an additional template to describe the "{Hi}" text. like this:
```
...
"sampleInput": "@{hiTemplate()}"
...
```
```
# hiTemplate
- \{Hi\}
```

But we prefer you to update the sdk to 4.7, to get a more stable SDK and with more features.

**Comment by boydc2014** [comment]
Close this due a workaround has been provided by  @Danieladu .  @fabio-muramatsu please check if it's working or not and we recommend to use the latest bits in master.
