### ISSUE TITLE
Wiki should highlight Adaptive Cards example/sample

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#295]
Currently we show Hero, Attachments, Suggested Actions, and Carousel examples for "rich" responses, but we don't highlight how to do an [Adaptive Card](http://adaptivecards.io) with the new v4 framework.

**Comment by JonathanFingold** [comment]
Putting this in my queue.

**Comment by JonathanFingold** [comment]
@brandonh-msft , Added an Adaptive Card sample.

**Comment by nrobert** [comment]
@brandonh-msft you are right for the wiki part but using Adaptive Card in projects is, at the moment, really complicated due to the lack of compatibility of most of the channels. We should add a disclaimer about that, as many people think it's magical but... it isn't

**Comment by JonathanFingold** [comment]
@nrobert , @brandonh-msft , I'll add a disclaimer. Is there a way, other than trial and error, to tell which channels support it?

**Comment by nrobert** [comment]
From my experience, no, there is no sure and valid support information, testing is Needed

**Comment by garypretty** [comment]
There is the channel inspector which will give you an idea of support and how things will be displayed in each channel https://docs.botframework.com/en-us/channel-inspector/

**Comment by nrobert** [comment]
For Adaptive Cards that's not really useful Gary

**Comment by JonathanFingold** [comment]
I've updated the lede for the sample to:

You can also send an Adaptive Card as an attachment; however, only a few channels currently support Adaptive Cards.

> **Note**: You should test this feature with the channels your bot will use to determine whether those channels support Adaptive Cards.

**Comment by brandonh-msft** [comment]
There used to be a table as to what channels supported what features of Adaptive Cards... lemme do some hunting.

**Comment by nrobert** [comment]
I think you are talking of this one? https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots

**Comment by brandonh-msft** [comment]
well that took longer than i'd have liked, but [found it](https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots#channel-status)
