### ISSUE TITLE
[Adaptive][DCR] Deep integration of QnA Maker in adaptive dialogs

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2959]
# QnA deep integration with Adaptive dialogs

[QnA Maker][1] at the moment integrates with adaptive dialog via a [QnA action][2]. While this helps cover simple use cases where we treat QnA maker call as a `fall back` on the `unrecognized intent` route, this does not help with more typical use cases users want to use QnA Maker for. 

## Primary use cases for QnA in adaptive dialog

As a user, 
- I have a bunch of FAQ pages, documents or manually authored content that serve as the knowledge base for my dialog. Any time my user says something that can be answered by my knowledge base, I want to respond with the `Answer` from my KB
- I'd like for my bot to have a personality and support [ChitChat][3] at the bot level. I'd like to add ChitChat capability to my bot and have adaptive dialogs automatically respond to general chitchat interactions.
- I have a multi-turn dialog modelled using `Intent` trigger and `Actions`. However, I would like to use a knowledge base to come back with contextually relevant `answers` to help or other contextually relevant questions. I just want to define a set of `QnA` pairs on specific input and have adaptive dialog come back with the response for a contextually relevant question.

## KB recognizer in adaptive dialog

To enable more deeper integration with QnA Maker, 
- we will add a `QnAMakerRecognizer` that implements the `IRecognizer` interface with the following behavior:
    - Call QnA maker with the configured recognizer options and include the following with every request
        - we will always set the following `meta-data` properties
            - `dialogName` = active dialog's name
            - All key value pairs found under `$qna.metaData` passed as a flat list of key value pairs. 
        - we will send context if `$qna.context` is not null
    - If there is an answer, promote it with 
        - `intents : {'QnAMatch':{Score:topanswerscore}}`
        - `entities: {'answer': [...answers...], $instance:{'answer':{....}}}`
        - `properties: {'answer': full response from QnA}`
    - If there is no answer, recognizer returns `None` intent
- Add a new `OnQnAMatch` trigger that is conditioned on `QnAMatch` intent.
- We will add ability to generate `.qna.dialog` files as well as cross-train, create kb, update kb, publish kb operations via a library + CLI wrapper in BF-CLI.
- Update `recognizer` property on adaptive dialog to accept an array of recognizers.
- Add `Id` property to recognizer.

## Handling cases when more than one recognizer is specified

When an adaptive dialog has more than one recognizer specified, we will 
- Call all recognizers in parallel
- In case where a recognizer defers its recognition to another recognizer, it must return a top scoring intent of `DeferToRecognizer_<recognizerId>`.
- If all but one recognizer has a top intent != `DeferToRecognizer_xxx` and if all other recognizers returned `DeferToRecognizer_yyy` where `yyy` is the Id of the recognizer that returned a non defer match, then
    - Emit `reconizedIntent` event with the top scoring intent from recognizer Id `yyy`. 
- Else 
    - Emit `recognizedIntent` event with `turn.recognized.intents = {'ambiguousIntent': {'recognizerId1': result from recognizer 1, 'recognizerId2': result from recognizer 2, ...}}`
- Add a new `OnAmbiguousIntent` trigger that is conditioned on `ambiguousIntent` intent.
- If any recognizer returns `None` as its top scoring intent, then it is basically eliminating itself from being a candidate. Under such circumstance, we should promote alignment among other recognizers.

## Meta data to pass when calling QnA recognizer

When calling the KbRecognizer, we will always set the following `meta-data` properties
- `dialogName` = active dialog's name
- All key value pairs found under `$kb.metaData` passed as a flat list.

e.g. with the following memory structure,

```json
{
    "dialog": {
        "kb": {
            "metaData": {
                "key1": "value1",
                "key2": "value2"
            }
        }
    }
}
```

we will pass the following as meta-data to the kb recognizer call.

```json
{
    "dialogName": "active dialog's name",
    "key1": "value1",
    "key2": "value2"
}
```

[1]:https://www.qnamaker.ai/
[2]:https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker
[3]:https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/chit-chat-knowledge-base

**Comment by xieofxie** [comment]
For multiple QnAs, will it be List<KBRecognizer> in AdaptiveDialog or introduce a MultiKBRecognizerRecognizer? Thanks~

**Comment by vishwacsena** [comment]
@tomlm @chrimc62 - Updated based on our discussion today. Please take a look.
