### ISSUE TITLE
Emulator usage docs don't call out /api/messages as endpoint for the bot

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#296]
With `IBot` implementation abstracting away the endpoint registration, it's not immediately obvious what endpoint the bot is listening on. Browser will launch (depending on Project configuration) to root location, not `/api/messages`, so a user trying to utilize the emulator won't know to add `/api/messages` on the end; this should be part of docs for using the emulator.

**Comment by drub0y** [comment]
Yeah and the `README`s and/or `default.htm` in the samples should probably call this out too.

**Comment by Kaiqb** [comment]
@brandonh-msft @drub0y - updated instructions in the getting started to include `/api/messages` part.
