### ISSUE TITLE
[Adaptive] New actions - SetProperties; InitProperties; DeleteProperties

### ISSUE THREAD

**Issue by dmvtech** [microsoft/botbuilder-dotnet#2963]
**Is your feature request related to a problem? Please describe.**
To be able to set many properties, you must use many different SetProperty.

**Describe the solution you'd like**
It would be nice to have a SetProperties, or some way to set many properties at once, instead of many individual SetProperty

**Comment by vishwacsena** [comment]
We should remove and replace our current set of actions with ones that support one or more memory operations in a single action. 

`SetProperty` -> `SetProperties`
`DeleteProperty` -> `DeleteProperties`
`InitProperty` -> `InitProperties`
