### ISSUE TITLE
[Hackathon] Variable names requirement complex and lack discoverability

### ISSUE THREAD

**Issue by RustyDes** [microsoft/botbuilder-dotnet#2964]
## Version
(N/A)

## Describe the bug
Composer will produce something that doesn't work if property naming doesn't follow some guidelines (which are not intuitive to a new user). Ideally it should be made to work with simple property names (by defaulting to a default scope), or if not feasible, it should at least yell at the user when the user enter those invalid properties.

## To Reproduce
1. In composer add a question to ask for text
2. Select the User Answer (Text) box
3. On the right, set the Property value to UserQuestion

## Expected behavior
It should warn me that this will not work and that instead I should use something like:
  $UserQuestion
or
  dialog.UserQuestion
It should likely also link to this document:
https://github.com/microsoft/BotFramework-Composer/blob/master/docs/using_memory.md

Or better yet, if the user specify something like this, a default should be used both here and in other steps where this property is being used.

## Screenshots
![image](https://user-images.githubusercontent.com/52328043/65802461-99693700-e130-11e9-9c2b-e74bb96e0e0f.png)

## Additional context

[bug]

**Comment by vishwacsena** [comment]
While we could support un-scoped properties to default to one of the available memory scopes, we should instead invest in right UA + samples that show how to get set up and use one of the available memory scopes so the user is always cognizant of what information is going where. 

Resolving as Won't fix.
