### ISSUE TITLE
Extend foreach and where to work with objects

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2966]
foreach/where currently operate over arrays only.  It would be very nice if they would also work over objects.  For example in json schema properties look like this:
{
  properties: { prop1: {...}, prop2: {..}}
}
There is no way in the current expression language to get a list of properties like ["prop1", "prop2"].  It cannot be expressed with jpath and we don't have any way to get the keys.

The proposal would be to extend foreach/where to work over objects where the iteration variable is assigned to an object { key: <key from object>, value: <value from object>}.  Then I could get the list of properties by foreach(turn.schema.properties, property, property.key) or filter them using where(turn.schema.properties, property, contains(turn.schema.required, property).
[enhancement]

**Comment by Danieladu** [comment]
thereturn result of where is list or object? for example:
```
{
properties: { prop1key1: {...},   prop1key2: {...},   prop2: {..}}
}
```

```
where(properties, property, contains(property.key, 'prop1'))
```

the result would be 
```
[
     {
         key:prop1key1, 
         value:{...}
     },
     {
         key:prop1key2,
         value:{...}
     }
]
```

or 
```
{  
      prop1key1: {...},   
      prop1key2: {...}
}
```

**Comment by Danieladu** [comment]
> the return result of where is list or object? for example:
> 
> ```
> {
> properties: { prop1key1: {...},   prop1key2: {...},   prop2: {..}}
> }
> ```
> 
> ```
> where(properties, property, contains(property.key, 'prop1'))
> ```
> 
> the result would be
> 
> ```
> [
>      {
>          key:prop1key1, 
>          value:{...}
>      },
>      {
>          key:prop1key2,
>          value:{...}
>      }
> ]
> ```
> 
> or
> 
> ```
> {  
>       prop1key1: {...},   
>       prop1key2: {...}
> }
> ```

I would evaluate it using the second solution.

**Comment by chrimc62** [comment]
Feels to me like where should be a list to be consistent. It works also be good to have a way to turn it into an object, but I would not overload where.
