### ISSUE TITLE
Add indicesAndValues function over arrays

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2967]
When iterating over an array sometimes it is useful to have access to the index into the array.  If we added a function that turned an array into an array of objects then we could access that information.  For example: foreach(indicesAndValues(someArray), elt, elt.value) would be the equivalent of foreach(someArray, elt, elt).  where(indicesAndValues(someArray), elt, elt.index > 3) would produce a new array with only elements after the fourth one.
[enhancement]

**Comment by Danieladu** [comment]
> where(indicesAndArray(someArray), elt, elt.index > 3) would produce a new array with only elements after the fourth one.
personal think, function and function should maintain a loosely coupled relationship, just use data or variable to drive the result. Obviously, `indicesAndArray` has callback attribute.

**Comment by vishwacsena** [comment]
We should just do elt.index and elt.value

**Comment by boydc2014** [comment]
yes, @vishwacsena  @Danieladu , `where` won't be smart to filter the orignal array, it will and should only filter the result of indicesAndValues,  if user want to get value, he can use select again. i guess

**Comment by Danieladu** [comment]
should add object supprt.
