### ISSUE TITLE
As part of 'Getting Started' give devs a level set on assumed minimum knowledge

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#297]
In other words, let devs know that "we assume you have base knowledge of ASP.Net Core WebAPI. If you don't, you can find great material on this [here](http://asp.net)" or something of the like.

**Comment by JonathanFingold** [comment]
Agreed. I'll try and pin this down this week and update the wiki.

**Comment by Kaiqb** [comment]
@brandonh-msft @JonathanFingold - added ASP.NET core as part of the pre-req in the getting started.
