### ISSUE TITLE
DCR: Reduce BotFrameworkAdapter constructor complexity through single, extensible BotFrameworkAdapterOptions parameter

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#2972]
Currently, the BotFrameworkAdapter and super classes have a problem where the number of parameters is ever increasing, while some of them are becoming old and unused. Because of binary backwards compatibility, each time we add a parameter, we have to add a new constructor, so the number of constructors is also linearly increasing with the number of parameters. Additionally, there are side effects on dependency injection since lots of constructors + DI are not a great match.

Further more, there are bugs in some constructors that end up creating defaults for parameters in cases where they shouldn't, so some of our samples are injecitng parameters through DI but it is not really being honored - the default from the ocnstructor is taking effect. The result of this is that developers could change DI to use another value to pass to the adapter ctor but it would not actually take effect.

The proposal is to create a class called `BotFrameworkAdapterOptions` that will have a **curated** set of parameters that we feel are **vital** to the Adapter's configurability.

With this, whenever we add a new option (after careful evaluation), we don't need new constructors polluting the adapter. This also gets us closer to the javascript implementation which is based off a BotFrameworkAdapterOptions parameter

**Comment by cleemullins** [comment]
That seems very reasonable.

**Comment by garypretty** [comment]
This seems like a really sensible change. This is how the custom adapters have been designed and it is also aligned with the changes I am making to Alexa and Google also.

**Comment by carlosscastro** [comment]
PR for this coming out today.

**Comment by carlosscastro** [comment]
John and I iterated a bit on this and decided to take some extra time to think about how to get this right.
