### ISSUE TITLE
Offer docs/guidance on IBot vs Controller/Adapter

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#298]
If we have samples showcasing both, we should offer guidance and/or pros/cons to each approach.

**Comment by Kaiqb** [comment]
@brandonh-msft @drub0y - I think we should stick with using IBot implementation. The reason we see differences is because not all samples/code snippets have been updated.

**Comment by drub0y** [comment]
I agree with `IBot`, but I'm biased. :D  Probably the only sample that _should be_ using controllers and/or adapter directly is the Connector one whose intent is to show that you can completely bypass the integration libraries and do your own thing.

FWIW, I also have an opinion that the execution of `IBot` doesn't actually belong in the integration libraries themselves, but rather in a common piece of middleware. This current version was only intended as the first step towards that with a goal of giving us the buffer we needed to go change all the underlying architecture (such as M2 pipeline/middleware changes) without impacting the developers at the edge who can just live in `IBot`-land.

**Comment by wmeints** [comment]
@drub0y well I actually think that the sample with just the connector shouldn't be using controllers at all. I'd much rather see a sample with custom middleware instead. I think that using custom middleware in ASP.NET core or even NancyFX is a much more common scenario when using just the connector.

**Comment by Kaiqb** [comment]
This is getting cleaned up with the new samples.
