### ISSUE TITLE
will lg multi lang support fallback in imported ones?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#2983]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Currently it is not supported. So when the user only wants to overwrite certain functions, the user has to copy all other functions in imported lg file.

**Describe the solution you'd like**

Also support fallback as non imported ones.

**Describe alternatives you've considered**

**Additional context**

Examples here https://github.com/microsoft/botbuilder-dotnet/pull/2982

[enhancement]

**Comment by boydc2014** [comment]
@xieofxie we don't support fine-grained language-fallback for specific template inside a particular file.  We support language-fallback at file level.

The concern around enabling such a fine-grained language fallback is not just the cost to implement, but also a more complex and more confusing model brought by this level of flexibility.   

Regarding you case, if you want to make a language variation for one specific template, my suggestion is to create new files (for each locale) to hold that template and import from the original file, rather that copy all other templates.  Will that work for you?

**Comment by xieofxie** [comment]
@boydc2014 So if I have `replies.en.lg` and it imports `helpers.en.lg`. When I need to specialize one function f for en-us, I could separate them like `helpers(without f).en.lg`, `f.en.lg` and `f.en-us.lg`. Then others do not need to be copied. Do I understand correctly? Thanks

**Comment by boydc2014** [comment]
> @boydc2014 So if I have `replies.en.lg` and it imports `helpers.en.lg`. When I need to specialize one function f for en-us, I could separate them like `helpers(without f).en.lg`, `f.en.lg` and `f.en-us.lg`. Then others do not need to be copied. Do I understand correctly? Thanks


This is the suggested hierarchy of your lg files, given the current implementations 

/-shared
 replies.lg  // in which you [import]()
 helpers.lg // in which you [import](f.lg)

/-en_us
dialogA.en_us.lg  // here is the entry, you import replies.lg if you want to share replies.lg
f.en_us.lg  //here is somethings you want to specilize

/-zh-ch
dialogA.zh_ch.lg  // here is the entry, here you import replies.lg if you want to share replies.lg
f.zh-ch.lg  // here is somethings you want to specialize

**Comment by xieofxie** [comment]
Thanks for the explanation~
So dialogA uses `"generator": "dialogA.lg"` and lg could be organized as:

/-shared
shared.lg // `[import](special.lg)`
special.lg
/-en
dialogA.en.lg // `[import](shared.lg)`
shared.en.lg // `[import](special.lg)`
special.en.lg
/-en_us
dialogA.en_us.lg // `[import](shared.lg)` 
special.en_us.lg
/-en_gb
dialogA.en_gb.lg // `[import](shared.lg)`
special.en_gb.lg
/-zh
dialogA.zh.lg // `[import](shared.lg)`
.. similar ..

Then 
1. shared in en_ca goes to dialogA.en.lg -> shared.en.lg
2. shared in en_us goes to dialogA.en_us.lg ->shared.en.lg
3. special in en_us goes to dialogA.en_us.lg ->shared.en.lg -> special.en_us.lg.
