### ISSUE TITLE
Why is HttpHelper marked "Internal" (in Microsoft.Bot.Builder.Integration.AspNet.Core)

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft/botbuilder-dotnet#2984]
I've had to create my own BotFrameworkAdapter-derived class, but in so doing I need to call HttpHelper.WriteResponse. This is annoying at the moment because the class is marked "Internal", so I've had to create my own copy of it - is there some reason it's not a Public class?

**Comment by johnataylor** [comment]
We just made this internal because it was just part of the implementation of the BotFrameworkHttpAdapter. I don't see a reason why we couldn't make this public if it was useful. We were just being a little conservative in our thinking.

However, there is always cost - we generally try to have unit test around the public service area. Obviously its tested to some significant degree because its part of the current implementation. So we could make this public in R7.

**Comment by HiltonGiesenow** [comment]
Ok great news. I'm super heads down at the moment, but if I get a chance soon I'd be most happy to help on it. If it does become "public", maybe it should change from being a "helper" to something more concrete. Possibly extension methods on HttpRequest & Response, or similar

**Comment by benbrown** [comment]
@HiltonGiesenow We certainly welcome pull requests!

**Comment by johnataylor** [comment]
this will be public in the next (minor) release - due this month

**Comment by johnataylor** [comment]
This is in master now. It will be in the latest package to be published next week.

**Comment by HiltonGiesenow** [comment]
I really appreciate your responding to this and sorting it out quickly, but to be honest I've been wondering whether this "helper" itself really should be public... While the methods _themselves_ are useless, I'm wondering if we could put them somewhere more specific than just a general "helper". What do you think? As a possible suggesting, as it's only two main methods (one one static field), perhaps we could:

- put the static BotMessageSerializer field into a static class, like a [namespace].Serialization static class
- make the remaining methods into Extenstion methods: ReadRequest, which takes in just an HttpRequest, could be made into ReadAsActvivity, for example, and WriteResponse could be WriteInvokeResponse

What do you think? I'm happy to work on this as a PR, either the design proposed or an alternative.
