### ISSUE TITLE
Code comments/docs on "black box" methods in abstractions

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#299]
With the `AddBot()` and `UseBotFramework()` methods provided in the `IBot`-using examples, we should have code comments and/or docs that talk about what happens when those methods are run so developers understand the ramifications of what's going on and why it's necessary, as well as available extensibility points.

**Comment by drub0y** [comment]
No doubt they need not only doc comments, but also some implementation comments on some of the more esoteric plumbing. I have an issue for this already under #241 so, if you don't mind, I'm gonna close this one as a duplicate.
