### ISSUE TITLE
Switch from SourceLink to Microsoft.SourceLink

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#2992]
**Is your feature request related to a problem? Please describe.**
We are currently using SourceLink.Create.CommandLine  The GitHub repository for this library [recommends ](https://github.com/ctaggart/SourceLink#quick-start) switching to [Microsoft.SourceLink.*](https://github.com/dotnet/sourcelink/)

[enhancement]

**Comment by cleemullins** [comment]
I pinged Bruce, and we should get this resolved.

**Comment by BruceHaley** [comment]
PR: Update to Microsoft.SourceLink.GitHub #3389 https://github.com/microsoft/botbuilder-dotnet/pull/3389

**Comment by BruceHaley** [comment]
Completed
