### ISSUE TITLE
Unauthorised when sending proactive messages UNTIL the bot receives a message.

### ISSUE THREAD

**Issue by jason721** [microsoft/botbuilder-dotnet#2999]
Simply put: sending proactive messages fail with 'Unauthorized' until the bot receives a message from Teams. Immediately after receiving a message, proactive messages work. I'm not sure if there's something I could be missing? 

To reproduce, do something like this immediately after creating your TeamsActivityHandler bot and BotFrameworkHttpAdapter.

The unauthorised error only occurs when using actual Teams, not the bot emulator.
```
await Adapter.ContinueConversationAsync(MicrosoftAppId, ConversationReference, async (turn, cancel) =>
{
    await turn.SendActivityAsync($"test.");
}, default(CancellationToken));
```

**Comment by mdrichardson** [comment]
This sounds like a [TrustServiceUrl issue](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#avoiding-401-unauthorized-errors). Try adding:

```js
MicrosoftAppCredentials.TrustServiceUrl(turn.Activity.ServiceUrl);
```

...just prior to `SendActivityAsync`

See [this SO answer for more context](https://stackoverflow.com/questions/57496329/proactive-messaging-bot-in-teams-without-mentioning-the-bot-beforehand/57499608#57499608)
