### ISSUE TITLE
EchoBot is a class library in the samples folder; it can't be run

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#300]
Having a reused class library in the `samples/` subfolder leads to developer confusion when they hit F5 and it attempts to run it then throws an error. Suggest putting it in a `components/` subfolder under `samples/`, or removing it completely and having those internals as part of the samples to which they're relevant.

**Comment by cleemullins** [comment]
Fixed in #322 

Added the"Echobot.cs" to each relevant sample. Delete the Echobot project. 

Simplified the echobot stuff from the sample (removed state, etc)
