### ISSUE TITLE
[Adaptive Dialogs] Allow specifying interruption conditions and retry prompts for OAuthInput

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/botbuilder-dotnet#3004]
**Is your feature request related to a problem? Please describe.**
The OAuthInput for adaptive dialogs doesn't allow setting interruption conditions for the cases when the user doesn't respond to the auth request as expected. This makes it hard to control the conversation flow, since interruptions are always enabled in this situation.

**Describe the solution you'd like**
Every input action for adaptive dialogs allow setting expressions in the `AllowInterruptions` property. The OAuthInput should accept the same property to keep it consistent with other actions. Another relevant property here would be `InvalidPrompt`, which would make the bot send a message to the user if the interruption condition is not met and they are not signing in. Right now, if the user types something that is not recognized as a valid intent, the bot stays silent.

**Describe alternatives you've considered**
As a workaround, I'm considering wrapping an OAuthPrompt in a waterfall dialog. The prompt has a retry prompt option, but it doesn't integrate well with the interruption logic from adaptive dialogs. So having support for this in OAuthInput would be the ideal solution.

[enhancement]

**Comment by benbrown** [comment]
Thanks for the request, @fabio-muramatsu.  We've assigned one of our team members to look into this.

We'll post updates here on this ticket.

**Comment by benbrown** [comment]
If you do pursue the waterfall dialog wrapper solution, please let us know how it works out and if it meets your needs.

**Comment by benbrown** [comment]
@vishwacsena Hey amigo, can you take a look at this and lend your perspective?

**Comment by vishwacsena** [comment]
@luhan2017 pushing to R8.
