### ISSUE TITLE
[Adaptive] [DCR] Action policies for Adaptive components

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3007]
Specific actions available with adaptive dialog should not be used in certain scenarios or within certain triggers. Today, there exists no mechanism in the component schema to hold a list of suggested action policies for triggers or actions. This DCR introduces support for action policy in the component schema to enable 
- UI based experiences like Bot Framework Composer to light up appropriate UI experience
- Linting and validation libraries to leverage this to provide users with appropriate errors and warnings. 

**Initial policies**
- Interactive - when applied to a trigger, indicates the specific type of actions that are permissible in that trigger. All inputs, BeginDialog action will be tagged as `Interactive`. All triggers except `OnBeginDialog` and `OnConversationUpdate` will be tagged as `Interactive`. This, or an additional policy, should also allow us to specify what type of actions a trigger's flow can end with, enabling us to keep developers 'on the rails' when responding to channel specific events, such as Teams invoke activities.
- Last action - when applied to an action, indicates that there cannot be additional actions after this action in a sequence - this action must be a leaf action. Applied to `EndDialog`, `AskAction`, `CancelAllDialogs`.

**Comment by vishwacsena** [comment]
We can revisit based on continued feedback on adaptive/ composer. Moving out of R9.

**Comment by gabog** [comment]
We believe this one should be closed or done in R10, can you confirm @vishwacsena?

**Comment by mrivera-ms** [comment]
@garypretty , please take a look and let us know if this is an R11 item. Thanks.

**Comment by cwhitten** [comment]
@mrivera-ms it would be great if we had the DCR addressed and agreed to in R11 to be implemented in R12. Thanks.

**Comment by garypretty** [comment]
Setting this as a P1 for R11 to drive progress on this.  Not a blocker for R11 to ship, but will be for R12.  This is going to be required for our Teams functionality.  If we can make progress in R11 and ship it, that would be a stretch goal.

**Comment by mrivera-ms** [comment]
This will be done in R12. Need spec to clarify how to implement.
