### ISSUE TITLE
[Adaptive] [DCR] New actions - ProcessActivity, ProcessMessageActivity

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3008]
Today, we allow developers to override the default activity processing and message activity processing pipelines baked into adaptive dialog. However this leaves users short on being able to replicate or manage the E2E event loop that is tied to each of these phases of an activities lifecycle within adaptive dialog. 

To provide developers the ability to override activity received, message activity received events and to continue to provide them with the ability to call back into the default implementation of those events in adaptive dialog, we will support two new advanced actions 

- ProcessActivity - kicks off the internal implementation of adaptive dialog to process an incoming activity

**Comment by tomlm** [comment]
To make this really concrete, I think it works like this:

We split BeginDialog() action into 2 actions
* **RouteToDialog**() - sets turn.processActivity = true and starts dialog
* **CallDialog**() - set turn.processActivity = false and starts dialog

Inside of dialog.BeginDialog()
```
   // emit initialization event for the dialog 
   // and apply non-interactive actions (since it's non-interactive, it should always fall through)
   Emit("InitDialog") event, 

   if (turn.processActivity)
   {
      // emit ActivityReceived event => triggering OnActivity/OnRecognized/OnIntent trigger definitions
      Emit("ActivityReceived") 
   }
   else 
   {  
      // emit CallDialog event=> triggering OnCallDialog trigger definitions
      Emit("CallDialog") 
   }
```

**Comment by vishwacsena** [comment]
This is same as and enabled via EmitEvent, eventType = activityRecieved (for process activity)
EmitEvent, eventType = recognizedIntent (for processMessageActivity) this will allow the triggers to be re-evaluated and internal adaptive dialog mechanics to execute.

**Comment by patatofries** [comment]
Hi @vishwacsena,

> This is same as and enabled via EmitEvent, eventType = activityRecieved (for process activity) EmitEvent, eventType = recognizedIntent (for processMessageActivity) this will allow the triggers to be re-evaluated and internal adaptive dialog mechanics to execute.

I want to override the Message Received Activity in Bot Composer.
However, I'm not able to find a way to call the base implementation, every with your quoted instructions.

Is this feature in Bot Composer still missing? Alternatively, it would be great if you could clarify the instructions!
