### ISSUE TITLE
Have the Hello World bot created by going through the wiki tutorial as a sample in the repo

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#301]
This will help users that might get stuck going through the tutorial, not have something work properly when they complete it, or those who simply prefer to see actual code while doing a walkthrough.

**Comment by nrobert** [comment]
Done.

For the HelloBot.cs file details, can you put the `using System.Threading.Tasks;` at the top of the usings in the wiki page, to match how it is ordered?

**Comment by JonathanFingold** [comment]
Updated the wiki. @nrobert , please close the issue once the PR completes.

**Comment by nrobert** [comment]
I will not be able to close it as I'm not the one requesting it

**Comment by drub0y** [comment]
I updated the PR description with a "Fixes #xxx" which should automatically close out this issue once the PR is accepted. Should work, but if it doesn't we'll circle back and close it out manually.

**Comment by cleemullins** [comment]
The full set of "Blessed" samples has been agreed upon and is part of a larger change set. This set includes tutorials, echo bot(s), and - of course - hello world. 

Closing this, as it's tracked elsewhere.
