### ISSUE TITLE
Magic code handling is not working for Teams bot

### ISSUE THREAD

**Issue by armstrong-charles** [microsoft/botbuilder-dotnet#3013]
## Version
What package version of the SDK are you using.
Bot Builder SDK v4.6

## Describe the bug
Give a clear and concise description of what the bug is.
My bot is based on enterprise bot template, migrated to v4.6 SDK, and implemented automatic magic code handling by using TeamsAuth sample, it receives "invoke" message with magic code, but OAuthPrompt was not returned, message was not routed to correct dialog implemenation.

## To Reproduce
1. Build the bot using enterprise bot template from NuGet
2. Make changes to the Bot based on the TeamsAuth sample (signin and logout text are handled)
3. Signin will display the OAuthPrompt card, once singin button is selected, bot gets OnTeamsSigninVerifyStateAsync() calls where it calls await Dialog.RunAsync(turnContext, ConversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken).
4. Call goes to SDK, finally it sends Invoke activity message to InitialStepAsync (MainDialog is a waterfall dialog with two steps, initial step and final step.) with Activity.Text is null.
5. Call never resumes from the OAuth flow

## Expected behavior
Invoke Activity with magic code is received in my bot (Bot.cs derived from DialogBot<T>) in OnTeamsSigninVerifyStateAsync, but OAuth prompt flow was never resume, it is expecting to enter the magic code. 

## Additional context

[bug]

**Comment by Virtual-Josh** [comment]
Hi @armstrong-charles,

Can you share what changes you made?

**Comment by gabog** [comment]
Closing this one due to inactivity

**Comment by armstrong-charles** [comment]
If you want I can copy the sample enterprise bot with my changes to github. 
Please let me know.
