### ISSUE TITLE
When invoking a messaging extension in Teams, the conversation Id from Activity can't be used as a chat Id parameter for Graph API

### ISSUE THREAD

**Issue by dejancg** [microsoft/botbuilder-dotnet#3019]
## Version
Using v4.6.3 Nuget packages

## Describe the bug
In Teams, when invoking a compose messaging extension from a private 1:1 conversation between two people, calling the Graph API action `https://graph.microsoft.com/beta/chats/<conversation-id>/members` with a conversation ID obtained from `ITurnContext<IInvokeActivity>` in `OnTeamsMessagingExtensionQueryAsync` causes HTTP error 400 "Bad request" with no additional description. 

## To Reproduce
1. In Teams, start a 1:1 private conversation with another person
2. Invoke an action-based messaging extension
3. In a Teams application, handle the messaging extensions via `OnTeamsMessagingExtensionQueryAsync` method
4. In that method, take the conversation Id from `turnContext.Activity.Conversation` object and after obtaining a valid access token using `botAdapter.GetAadTokensAsync`, use that token and the above Conversation Id to call the Graph API action `https://graph.microsoft.com/beta/chats/<conversation-id>/members`
5. Observe the error "Bad Request"

## Expected behavior
The expected behavior is to have `https://graph.microsoft.com/beta/chats/<conversation-id>/members` return the list of members of a Teams conversation identified by the conversation Id obtained from the activity.

## Additional context
For additional context, please take a look at the previous issue: https://github.com/microsoft/botbuilder-dotnet/issues/2976 and the StackOverflow question: https://stackoverflow.com/questions/58984349/when-invoking-a-messaging-extension-can-the-conversation-id-from-activity-be-ma

**Comment by benbrown** [comment]
Hey @Virtual-Josh, can you look into this for this customer?

**Comment by clearab** [comment]
The conversationId you're getting in this instance is encrypted, and cannot be used to make Graph calls. The messaging extension is personally scoped, so there is no guarantee your app is installed in that context and approved to access additional information.

For a messaging extension with an action command, you also should be handling either the fetch task or submit action events. You can then respond to the fetch task with a request to install your conversational bot, and use the bot APIs to get the roster once it is installed. See: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/messaging-extension-v3/create-extensions?tabs=typescript#request-to-install-your-conversational-bot

**Comment by dejancg** [comment]
Thanks @clearab, allow me to take a look at the link you provided and try the proposed solution and I'll get back with the feedback.

**Comment by dejancg** [comment]
Okay, so thanks to the input from @clearab, the information from the link he provided and [this blog post](https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/), I managed to get the bot inside my private conversation, which should now allow it to read the roster, as you guys call it. I still haven't had time to fully investigate whether this approach would suit my needs (i.e. will bot be able to obtain e-mail addresses from chat participants), but for the sake of this issue, let's say that this is a valid workaround.

I have a side question though (I'm not closing the issue because I'm not sure whether you guys will see the side question at all if I just close the issue, but you are free to close it after you see the side question, as I've got a workaround), consider the following scenario:

* On Teams, an interested party, a customer, starts a conversation with one of the support agents.
* The support agent wants to invoke the **search** messaging extension, expecting to see the previous issue reported by this customer, if any. Previous issues would be found by using the customer's e-mail address.

Now I find this scenario less likely to be possible, given the above workaround, as we can't get the bot into the conversation without using the *fetchTask* action extension, right?

**Comment by srinaath** [comment]
@clearab Can you take a look at this ticket when you get a chance

**Comment by clearab** [comment]
Hi - unfortunately no, it isn't possible to add the bot as part of the search messaging extension. You could consider using a messaging extension with an action command triggered from a message instead of a search extension. That would send the necessary information to your bot for processing, but you'd have to build your own search results screen.
