### ISSUE TITLE
Relying on case sensitivity in source

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3021]
On a fresh sync, you get warned about colliding paths which should not be there.

git clone https://github.com/microsoft/botbuilder-dotnet.git
Cloning into 'botbuilder-dotnet'...
remote: Enumerating objects: 471, done.
remote: Counting objects: 100% (471/471), done.
remote: Compressing objects: 100% (331/331), done.
remote: Total 82080 (delta 286), reused 179 (delta 138), pack-reused 81609
Receiving objects: 100% (82080/82080), 21.76 MiB | 33.75 MiB/s, done.
Resolving deltas: 100% (61873/61873), done.
Updating files: 100% (2300/2300), done.
**warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnAMaker_ReturnsAnswerWithContext.json'
  'tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnaMaker_ReturnsAnswerWithContext.json'
  'tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnAMaker_ReturnsAnswerWithoutContext.json'
  'tests/Microsoft.Bot.Builder.AI.QnA.Tests/TestData/QnaMaker_ReturnsAnswerWithoutContext.json'**

[bug]

**Comment by tomlm** [comment]
this is git /os file system behavior, what do you expect us to do about this?
