### ISSUE TITLE
ChoicePrompt takes numbers as result inside user response

### ISSUE THREAD

**Issue by cocoke** [microsoft/botbuilder-dotnet#3039]
## Version
Bot Builder 4.3.2

## Describe the bug
ChoicePrompt recognizer consider numbers as result inside user response containing multiple word

## To Reproduce
1. Create a ChoicePrompt
2. Message the bot a question with a number inside like : "What is the **first** day of the week ?"
3. It will set first choice of the list as recognized

## Expected behavior
If the user sentence contains multiple word, the recognizer should not consider the number as result

## Additional context
I'm working with the french culture, it may be different in english

[bug]

**Comment by xieofxie** [comment]
As long as https://github.com/microsoft/Recognizers-Text/tree/master/.NET#microsoftrecognizerstextnumber is used, it is an expected behavior. I am also looking for some better solutions, thanks~

**Comment by EricDahlvang** [comment]
I don't think we can exclude ordinal recognition based on word count.  Consider responses such as "the third one" or "option 2". But we could add a parameter, to not recognize ordinals in choiceprompt.

**Comment by v-kydela** [comment]
Related: https://github.com/microsoft/botbuilder-dotnet/issues/2956

**Comment by tracyboehrer** [comment]
This is a feature we'll consider for R8

**Comment by EricDahlvang** [comment]
FindChoicesOptions now has RecognizeOrdinals and RecognizeNumbers options. This will be released with 4.8
