### ISSUE TITLE
AlarmBot samples use old version of Recognizer Texts, breaks on fresh NuGet install

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#304]
This line within Models > AlarmBotContext:

`var model = DateTimeRecognizer.GetInstance().GetDateTimeModel(this.Request.Locale ?? "en-us");`

On creating from scratch, I get 1.0.1 package for Recognizer Texts which no longer includes "GetInstance()", if I revert to 1.0.0.36 it works fine

**Comment by cleemullins** [comment]
Should be good.
