### ISSUE TITLE
Typing indicator middleware might show after sending message(s)

### ISSUE THREAD

**Issue by jvanderbiest** [microsoft/botbuilder-dotnet#3047]
## Version
4.6.2

## Describe the bug
Typing indicator is showing after a message has been sent by the bot and typing indicator will timeout depending on the front-end channel that is used. This only happens if you do more work in the Turn then just sending out a single message like in the examples. In our current implementations we also save data to the database, execute some external processes and they all need to finish before the Cancellation is actually called on the [ShowTypingMiddleware](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs).

## To Reproduce
Repro repo: https://github.com/jvanderbiest/echo-bot-typing-indicator

1. Switch between `ShowTypingMiddleware` and `CustomShowTypingMiddleware`
https://github.com/jvanderbiest/echo-bot-typing-indicator/blob/master/AdapterWithErrorHandler.cs#L18

The [EchoBot ](https://github.com/jvanderbiest/echo-bot-typing-indicator/blob/master/Bots/EchoBot.cs) simulates some extra work after sending the initial message

Code snippet:
```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var activity = await CreateActivityWithTextAndSpeak($"Echo: {turnContext.Activity.Text}");
            await RunSomething();
            await turnContext.SendActivityAsync(activity, cancellationToken);
            await RunSomething();
        }

        private async Task RunSomething()
        {
            await Task.Delay(5000);
        }
```
As a temporary fix, I check if the bot has already responded:
https://github.com/jvanderbiest/echo-bot-typing-indicator/blob/master/CustomShowTypingMiddleware.cs#L90

## Expected behavior
Sending a bot message should stop the typing indicator and it should not send out any typing indicator activities

## Screenshots
How it currently works
![typing-fail](https://user-images.githubusercontent.com/3985995/69880971-c7532f00-12cb-11ea-85ee-6102e557af25.gif)

How it should work
![typing-ok](https://user-images.githubusercontent.com/3985995/69882077-4ac24f80-12cf-11ea-8b76-5ef5f3a1dc96.gif)

## Additional info
Any workaround or suggestion is appreciated

[bug]

**Comment by marcasmar94** [comment]
Facing same issue here

**Comment by dmvtech** [comment]
@jvanderbiest Is this consistent across channels other than emulator?

**Comment by marcasmar94** [comment]
@dmvtech This was happening for me on Facebook and Direct Line (webchat), that workaround solved it for both channels

**Comment by gabog** [comment]
Hi @jvanderbiest, we think this issue is solved. Closing it.

**Comment by dmvtech** [comment]
I wasn't able to reproduce just now, so seems so from my end.

**Comment by jvanderbiest** [comment]
@gabog "we think this issue is solved". Do you even care for an explanation?
@dmvtech did you use my github repro and follow the steps?

**Comment by jvanderbiest** [comment]
@dvmtech I will check if it works with the latest master version

**Comment by jvanderbiest** [comment]
I could even reproduce the issue with v4.7.0-preview-191203-1 from myget.
So it's still there...

**Comment by dmvtech** [comment]
Ok, i'll try again. I just used your repro from your repo, but am using 4.6.**3**.

**Comment by dmvtech** [comment]
I am able to reproduce this now (not sure what I was doing before 😐). I can repro on both 4.6.2 and 4.6.3.

**Comment by a-b-r-o-w-n** [comment]
@dmvtech Does this repro on `4.7`?

**Comment by dmvtech** [comment]
I will check

**Comment by dmvtech** [comment]
@a-b-r-o-w-n Confirmation reproduces in `4.7`.
