### ISSUE TITLE
support 'all' function in LG

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#3052]
### <a name="allfunction">`all` function</a>
 `all` will return a list of all resolutions from the template.

for example:
```
# HeroCard (params)
[Herocard   
    title = @{params.title}
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
> @{templateName()} always returns only one resolution from the template.
> all(templateName) returns a list of all resolutions from the template.
    images = @{all('HeroImages', 'myname')}
    buttons = Show more cards
]

# HeroImages(name)
- https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
- https://sec.ch9.ms/ch9/buildreactionbotframework_akajhsdi7_.jpg
```

[enhancement]

**Comment by vishwacsena** [comment]
@boydc2014 @Danieladu are we doing this for R7/ R8?

**Comment by Danieladu** [comment]
> @boydc2014 @Danieladu are we doing this for R7/ R8?

I think we can postpone this feature

**Comment by Danieladu** [comment]
`HeroImages()` will return a random result from template `HeroImages`, so, `all` is just a normal function, it can not change/add more info from the "single string result" from a normal template reference. So, should we use another way to apply this feature? such as "expandTemplate('HeroImages')", or "listTemplate('HeroImages')" ?

**Comment by Danieladu** [comment]
Turn it off temporarily and discuss it later as a DCR.
