### ISSUE TITLE
Using environment variables instead of appsettings for appId and appPassword

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/botbuilder-dotnet#3059]
## Version
`Microsoft.Bot.Builder.Integration.AspNet.Core` - 4.6.3

## Describe the bug
I'm using `MICROSOFT_APP_ID`|`MICROSOFT_APP_PASSWORD` as environment variables instead of using `MicrosoftAppId`|`MicrosoftAppPassword` in `appsetings.json` but while running my bot locally I got a `401 | Unauthorized` error.

## To Reproduce
.NET Core 2.2 echobot with Environment variables, just in case see my code here: https://github.com/mathieu-benoit/MyMonthlyBlogArticle.Bot/tree/dotnetcore

## Expected behavior
Environment variables should be able to be used without the `appsettings.json` file, especially with Docker container.

[bug]

**Comment by mathieu-benoit** [comment]
For example, shouldn't it be kind of implementation like this? https://github.com/microsoft/botframework-sdk/commit/cca308634c172ec65a4e550b74d21f074324a85b

**Comment by mdrichardson** [comment]
@mathieu-benoit It actually does fall back to environment variables, automatically. Take any of the samples and in Visual Studio:

1. Right-click on the Project
2. Click Properties
3. Go to Debug
4. In the Environment Variables, section, use `MicrosoftAppId` and `MicrosoftAppPassword`

![image](https://user-images.githubusercontent.com/40401643/70080025-b13eba80-15ba-11ea-8a1a-91124827af84.png)

As far as I know, there's no easy way to use `MICROSOFT_APP_ID`. You're better off just using `MicrosoftAppId`.

**Comment by mathieu-benoit** [comment]
Thanks @mdrichardson, it works indeed by using `MicrosoftAppId` and `MicrosoftAppPassword` instead of `MICROSOFT_APP_ID` and `MICROSOFT_APP_PASSWORD`. Got it, thanks!
