### ISSUE TITLE
No README for Luis and QnA (subscription id, etc) samples

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#306]
Additionally the entire wiki is out of date regarding these two samples

**Comment by JonathanFingold** [comment]
Update as of this hour.

**Comment by cleemullins** [comment]
#331 adds a basic readme for the Luis sample.

**Comment by brandonh-msft** [comment]
@JonathanFingold Doesn't look like I _can_ reopen it. :(

**Comment by JonathanFingold** [comment]
@brandonh-msft , I can reopen this for you, if that is still relevant (Chris added a readme). Sorry for the confusion.
