### ISSUE TITLE
Facebook adapter does not properly handle typing indicators

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#3071]
## Describe the bug

In order to send a typing indicator to Facebook Messenger, the developer should specify `sender_action`: `typing_on` in outgoing message.  In this case, only the sender_action and recipient fields should be set.

Our current adapter implementation does not properly handle the sender_action field.

Problem 1: sender_action is not included in the outbound message:
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs#L32

Problem 2: the message field (and message.text subfield) is always set:
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs#L34

## To Reproduce

Using the facebook adapter, attempt to send a message with {sender_action: 'typing_on'}

## Expected behavior

If {channelData: {sender_action: 'ANY VALUE'}} is present, the adapter should place it into the outgoing payload sent to Facebook AND remove the `message` field if present.

## Additional context

A related fix was made in the Javascript adapter here:
https://github.com/howdyai/botkit/pull/1871

[bug]

**Comment by garypretty** [comment]
PR merged.
