### ISSUE TITLE
[Adaptive] EmitEvent's property "bubbleEvent" has incorrect default value when load from declarative json

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#3082]
## Version
What package version of the SDK are you using.

## Describe the bug
EmitEvent's property "bubbleEvent" has incorrect default value when load from declarative json (generate from composer, for example)

## To Reproduce
1. Emit a customized event
{
          "$type": "Microsoft.EmitEvent",
          "eventName": "ConfirmSlotEvent"
}
2. Add a trigger to handle this event:
{
      "$type": "Microsoft.OnCustomEvent",
      "condition": "true",
      "actions": [
        {
          "$kind": "Microsoft.SendActivity",
          "activity": "Custom event triggerd."
        },
      ],
      "event": "ConfirmSlotEvent"
    }

You can see the event cannot catch by trigger. The root cause is the "bubbleEvent" is set to false by default, which is not align with the default value in EmitEvent class:
![image](https://user-images.githubusercontent.com/16643193/70215110-b39a4380-1777-11ea-9b30-3c835ae6cf5e.png)

[BugRepo.zip](https://github.com/microsoft/botbuilder-dotnet/files/3925600/BugRepo.zip)

## Expected behavior
The event can be captured by event trigger

## Additional context
Two questions:
1. What is the meaning to set "bubbleEvent" to false? Currently EmitEvent failed to work when bubble event set to false
2. Should we set default value to schema to avoid this issue?

[bug]

**Comment by xieofxie** [comment]
Maybe EmitEventAsync to parent in BeginDialogAsync? Currently since EmitEvent itself is a dialog, it will handle event itself when bubble is false.
