### ISSUE TITLE
InputDialog should fallback to using Activity.Value when Activity.Text is not set

### ISSUE THREAD

**Issue by abharath27** [microsoft/botbuilder-dotnet#3089]
Our bot has an adaptive card with clickable images that is configured like this:
```
{
     "type": "Image",
      "altText": "excellent",
      "url": "Url",
      "selectAction": {
          "type": "Action.Submit",
          "title": "Rate 5",
          "data": {
               "survey": "5"
           }
       }
}
```
When a user clicks this button, the bot gets `"survey" : "5"` as a JObject in the activity's `Value` property. InputDialog just ignores this data.

`InputDialog.RecognizeInput` method [looks](https://github.com/microsoft/botbuilder-dotnet/blob/4bdcaf79554e1b45a1d5d20b38b04d309799a79e/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs#L383) only at the activity's `Text` property for this input. There's special case handling for AttachmentInputs where you are reading the `Attachments` property.

Proposed fix:
Make a change [here ](https://github.com/microsoft/botbuilder-dotnet/blob/4bdcaf79554e1b45a1d5d20b38b04d309799a79e/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs#L392)to fallback to `Activity.Value` if we don't find anything in `Activity.Text`

**Comment by vishwacsena** [comment]
@Stevenic - thoughts? Seems like a good idea.

**Comment by godwin3737** [comment]
Hi, is there any movement on this ? In my opinion , as adaptive cards can be custom (with different input id's ) we should have a virtual method responsible to try and get adaptive card value .

**Comment by vishwacsena** [comment]
We should do "text": "value" in `Data` to get pulled back in value for property. This will be parallel to what we do with "intent" for `ValueRecognizer`
