### ISSUE TITLE
Revisit telemetry code pattern, embed deeper in the framework

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#3097]
Proposal: Embed AppInsights telemetry deep in the framework so that devs do not need to write boiler code, adding unnecessary clutter. There are several options to enable/disable instrumentation:
* If AppInsights key is specified --> enable telemetry   and/or
* Require an explicit flag (if we think the above is too implicit) 

The following code pattern clutters the code:

```
// The IBotTelemetryClient to the WaterfallDialog
AddDialog(new WaterfallDialog(
    nameof(WaterfallDialog),
    new WaterfallStep[]
{
    IntroStepAsync,
    ActStepAsync,
    FinalStepAsync,
})
{
    TelemetryClient = telemetryClient,
});
```

Reference: [Add telemetry to your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0)

(consider same for JS)

**Comment by bojingo** [comment]
Oh yes, please, please, please. We inevitably forget to set the telemetry client property either on custom dialog implementations or when adding prompts/dialogs. This is such an annoying detail to have to identify during a PR (if we even do...) when people forget.

**Comment by scheyal** [comment]
@garypretty - follow up on our chat.

**Comment by garypretty** [comment]
@scheyal Providing the root dialog has its TelemetryClient set, any child dialogs added to it using AddDialog will have their TelemetryClient set automatically, so you shouldn't need to set it as outlined above.
