### ISSUE TITLE
differences between alarmbot and alarmbot-cards

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#310]
I think over the evolving of this SDK, lots of differences have emerged between alarmbot and alarmbot-cards. I'm having a hard time creating AlarmBot-Cards from AlarmBot in a simple way, but I think the story to be told is "look how easily you can add cards to enhance the experience"

IMO - it might be nice to take AlarmBot and create AlarmBot-Cards directly from that, and then in the Readme for AlarmBot-Cards say **exactly what was changed to do so**. Finally, reference that in the Wiki for Cards and Attachments. I think that will bring the story all together.

**Comment by cleemullins** [comment]
@tomlm, who authored those two bots, found that the flow and implementation across the two bots was different. Using cards totally changed the flow of the bot in such a way as to make them be actually different bots. 

I don't think, long term, we'll keep AlarmBot and -Cards around as sample bots, as we want more deliberate, more real-world, samples. For now, they're good technology demonstration bots.
