### ISSUE TITLE
ActivityExtensions.RemoveRecipientMention fails to handle bot mentions if the bot name contains special characters

### ISSUE THREAD

**Issue by pappk** [microsoft/botbuilder-dotnet#3106]
## Version
4.6.3

## Describe the bug
If your bot name contains special characters that are used in Regex patterns (such as: `()*[]`), the RemoveRecipientMention function can't remove the mentions from the text.

During the bot registration process doesn't prohibit anything to use special characters in the bot name.

## To Reproduce
1. Install a teams bot in a group chat with a name: `Testbot (dev)`
2. Have the bot echo back the user message stripping out the bot name with RemoveRecipimentMention()
3. Send the bot a message

## Expected behavior
The message should be echoed back without the mentions

## Screenshots
![msteams_mentionremoving_bug_3](https://user-images.githubusercontent.com/6438434/70430849-f2801000-1a7b-11ea-8edd-ffcd722aad67.PNG)

## Additional context
The problem occurs with the Regex.Replace method in the `Microsoft.Bot.Schema.ActivityExtensions.RemoveMentionText()` function. Potentialy the `Regex.Escape()` function usage can solve the problem.

[bug]

**Comment by anusharavindrar** [comment]
@pappk I am able to repro the issue on my end. If the bot name contains a special character, the RemoveRecipientMention function is not removing the mentions from the text, but works fine with a bot name without any special characters.
![teamsMentions2_LI](https://user-images.githubusercontent.com/48731427/70576986-2122e700-1b5f-11ea-951f-8ffbc756f3a7.jpg)

**Comment by anusharavindrar** [comment]
The [PR](https://github.com/microsoft/botbuilder-dotnet/pull/3107) has been merged. Closing the issue. Feel free to reopen if this does not quite solve your scenario.
