### ISSUE TITLE
Extending Proactive Notification to a Dialog and Adding Message Queue to Promise Delivery 

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botbuilder-dotnet#3117]
**Is your feature request related to a problem? Please describe.**
In the current solution provided a Proactive Notification sends the message as an ITurnContext 

**Describe the solution you'd like**
- I want an option to use the Notification as part of a generic Dialog, which gives the user an option to either act on the notification or Ignores it.
- Message Queue to Promise Delivery of the Message to the User, to be considered if the user is Offline, this will require the notification to be stored in a Queue or CosmosDB and search the same when the user again comes online

**Comment by sgellock** [comment]
@Adityagrao thanks for opening the issue.  the team is discussing the use of CosmosDB to provide this.  we don't have a final design, and we haven't made a call as to where this would fit on our roadmap.  I've added it to our backlog.  please engage further if you'd like.

**Comment by sgellock** [comment]
@Adityagrao in looking at my roadmap for the 2020 calendar year, I don't see the team addressing this feature in my plans.  It's a cool idea, but I don't see us getting to it any time soon, unfortunately
