### ISSUE TITLE
Getting Intents from LuisRecognizerMiddleware

### ISSUE THREAD

**Issue by jamestruitt** [Microsoft/botbuilder-dotnet#313]
Problem Statement: 
Unable to get Top Intents from the LuisRecognizerMiddleware in the same manner that you do with RegExpRecognizerMiddleware.

Issue Recreation:
Register LuisRecognizerMiddleware into the Bot Adaptor
Run Bot and there is no way to get the TopIntent.

My Resolution: Not Optimal
namespace TheChurchAVBot.Context
{
    public class ChurchBotContext : BotContextWrapper
    {
        public ChurchBotContext(IBotContext context) : base(context)
        {

        }

        public Intent GetTopIntent()
        {
            var recognizedintent = RecognizedIntents.Intents;
            var recognizedEntities = RecognizedIntents.Entities;

            var resultIntent = new Intent();
            var resultEntityList = new List<Microsoft.Bot.Builder.Core.Extensions.Entity>();

            foreach (JProperty property in recognizedEntities.Properties())
            {
                var newEntity = new Microsoft.Bot.Builder.Core.Extensions.Entity()
                {
                    GroupName = property.Name,
                    Score = 1.0,
                    ["Value"] = property.Value[0]
                };

                resultIntent.Entities.Add(newEntity);

            }

            foreach (JProperty property in recognizedintent.Properties())
            {
                Console.WriteLine(property.Name + " - " + property.Value);
                resultIntent.Name = property.Name;
                resultIntent.Score = (double)property.Value;
            }

            return resultIntent;
        }
        /// <summary>\
        /// ChurchBotContext recognized Intents for the incoming request
        /// </summary>
        public RecognizerResult RecognizedIntents
        {
            get
            {
                return this.Get<RecognizerResult>("LuisRecognizerResult");
            }
        }

       

    }
}

**Comment by nrobert** [comment]
You can get the Top Intent by calling `GetTopScoringIntent`, it provides a (string, score) item

```
// Get list of itents
var results = context.Get<RecognizerResult>("LuisRecognizerResult");

// Get top Intent
var topIntent = results.GetTopScoringIntent();
```

**Comment by JonathanFingold** [comment]
PS. The [Using LUIS and QnA Maker](https://github.com/Microsoft/botbuilder-dotnet/wiki/Using-LUIS-and-QnA-Maker) page on the wiki was just updated and uses this extension method to get the top intent.

**Comment by cleemullins** [comment]
PR #331 addresses this and shows how to do it. There are several ways to do this, and I will need to update the RegEx Middleware to follow the same pattern.
