### ISSUE TITLE
AzureBlobStorage dependencies

### ISSUE THREAD

**Issue by nimbusparis** [microsoft/botbuilder-dotnet#3137]
## Version
4.7.0
## Describe the bug
The implementation of AzureBlobStorage use `Microsoft.WindowsAzure.Storage` instead of `Microsoft.Azure.Storage` that cause strange issues while inherit. I didn't find any other solution than cut-past the source to implements my own version of AzureBlobStorage

## To Reproduce
Try to inherit a class from AzureBlobStorage

## Expected behavior
Can inherit AzureBlobStorage without errors

[bug]

**Comment by mdrichardson** [comment]
@nimbusparis What issues do you experience when creating a class that inherits from `AzureBlobStorage`? Can you copy/paste your code?

**Comment by nimbusparis** [comment]
The class that inherit AzureBlobStorage:
```
    public class InheritAzureBlobStorage : AzureBlobStorage
    {
        public InheritAzureBlobStorage(Microsoft.WindowsAzure.Storage.CloudStorageAccount storageAccount, string containerName, JsonSerializer jsonSerializer) : base(storageAccount, containerName, jsonSerializer)
        {
        }

        public InheritAzureBlobStorage(string dataConnectionstring, string containerName) : base(dataConnectionstring, containerName)
        {
        }

        public InheritAzureBlobStorage(Microsoft.WindowsAzure.Storage.CloudStorageAccount storageAccount, string containerName) : base(storageAccount, containerName)
        {
        }
    }

```

`Microsoft.WindowsAzure.Storage.CloudStorageAccount` cannot be found, in package `Microsoft.Azure.Storage.Azure.Common`, the class `CloudStorageAccount` is defined in namespace `Microsoft.Azure.Storage`. Since my project is in dotnet core, I think the namespace shouldn't be anything from Windows.

**Comment by mdrichardson** [comment]
@nimbusparis I see. However, if you use `Microsoft.WindowsAzure.Storage.CloudStorageAccount` as you have above, it works, correct?

You'd just prefer that `AzureBlobStorage` switches over to the `Microsoft.Azure.Storage` packages?

**Comment by nimbusparis** [comment]
I already use Microsoft.Azure.Storage.Common package for other part of my bot and if I add `Microsoft.WindowsAzure.Storage` package, I got other errors: CS7069 while calling base constructor.

**Comment by mdrichardson** [comment]
@nimbusparis I see. The issue, then, is that the packages have duplicate assembly names so you can't use both in the same project.

In that case, your options are to:
1. Only use `Microsoft.WindowsAzure.Storage` in your project, or
2. Wait until [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/3149) is merged and released (Likely for v4.8 in January--if at all), or
4. Use the `AzureBlobStorage` provided in that PR, then inherit from it, or
5. Don't inherit from `AzureBlobStorage`

**Comment by nimbusparis** [comment]
Thank you for the PR, I can wait for next release for this, thank you for the scheduled change! 👍

**Comment by mdrichardson** [comment]
@nimbusparis You're welcome. I'm not sure if this PR will go through or not, however, I believe it would be a breaking change for anybody already inheriting from `AzureBlobStorage`. I'm not sure if there's an easy/good way to make this work backwards-compat.

**Comment by mdrichardson** [comment]
@nimbusparis I looked into this more and asked around to folks more knowledgeable than I, and that PR makes an unfixable breaking change: https://github.com/microsoft/botbuilder-dotnet/pull/1711#issuecomment-502243167

Feel free to use it yourself, but I don't believe that's something we'll fix in a release; we'd need to make an additional class for it.
