### ISSUE TITLE
DCR [Adaptive] - Providing a "disabled" indicator in Actions

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#3139]
BF Composer is beginning to scope a feature to select a series of contiguous actions intending to "skip" them in the runtime execution as a debugging feature: like "commenting-out" a series of instructions for testing purposes.

The intent of this DCR is to discuss serializing a new field into actions and triggers to encode this into the asset directly as an alternative to solving this in the application layer. If "skip" exists on the entity, simply pass over it during execution.

```json
{
  "$kind": "Microsoft.SendActivity",
  "activity": "skip me please",
  "skip": true
}
```

**Comment by tomlm** [comment]
Perhaps **disable: true**?

**Comment by tomlm** [comment]
related is $comment

**Comment by vishwacsena** [comment]
`disabled : @{expression}`. Apply this to actions
