### ISSUE TITLE
Operation returned an invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/botbuilder-dotnet#3141]
## Version
Latest v4 SDK

## Describe the bug
I am using a simple Adaptive Card to display an image using base64 encoded image value. It works fine on my local workstation with Bot Emulator. When I deploy this to Azure App Service I get an error. 

## To Reproduce
Here's my JSON with shorted base64. For full JSON and original image see attachment.

```json
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0",
  "body": [
    {
      "type": "Image",
      "url": "data:image/png;base64,iVBORw0KGgoAAAANS....ggg=="
    }
  ]
}
```

On Azure I get the following error:

```
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
  at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
  at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
  at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
```

## Expected behavior
Image is displayed

## Additional context
If I try to dispay image via URL it works just fine.

[bug]

**Comment by dkonyayev** [comment]
[card-image.txt](https://github.com/microsoft/botbuilder-dotnet/files/3965138/card-image.txt)
![rsa1](https://user-images.githubusercontent.com/15344498/70865521-a6761500-1f2c-11ea-9ba1-8167e1685e55.png)

**Comment by v-kydela** [comment]
@dkonyayev - I would like to help but I have a few questions:

1. What channel are you using?
2. Have you tried connecting that channel to a locally-running bot using a tunneling service?
3. What specific error is being reported?

This could easily be a matter of the attachment being too large.

**Comment by dkonyayev** [comment]
@v-kydela Hi, here's the answers to your questions

1. Bot is running fine in local development environment with Bot Emulator. It fails on Azure App Service with DirectLine as channel. The error on happens on backend code so I am not sure if it's really channel related.

2. I cannot use tunnelling service in our environment.

3. Here's the error. Once I replaced the URL with actual URI instead of Base64 then it started working.

2019-12-15 15:45:11.634 +00:00 [Error] 
	Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadRequest'at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()--- End of stack trace from previous location where exception was thrown

**Comment by v-kydela** [comment]
@dkonyayev - I've confirmed that the message is too big for Direct Line. The limit is 262144 bytes. If you want to embed an image in a Direct Line message, it needs to be smaller. Does this resolve your issue?

**Comment by dkonyayev** [comment]
@v-kydela It doesn't resolve my issue but it does explain it. Thanks!

**Comment by nagavamsi777** [comment]
Getting below issue when I am trying to post 24 hours weather report as courosel format means one card for one hour in teams 
Operation returned an invalid status code 'BadRequest'   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)  

Is there any limitation to display the Adaptive card in teams? Please help me.

**Comment by v-kydela** [comment]
@nagavamsi777 - You are commenting on a closed issue. Please make new posts for new issues. But for now you can see in the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#support-for-carousel-collections) that carousels have a 10-card limit in Teams.

**Comment by furkani94** [comment]
I fixed same problem with removing empty contents in my json text.

**Comment by exdunn** [comment]
I was receiving the same error as OP and fixed with @furkani94's solution.  Just to add some more context, my adaptive card was only failing for teams, when using templated cards ( `AdaptiveCardTemplate`).  I had some empty columns that I was using for spacing reasons.  Removed the columns, and _bam_, no more errrors.

**Comment by jnair7291** [comment]
@exdunn thank you so much bro...this actually saved my time debugging the entire code
