### ISSUE TITLE
Expose BotIdentityKey via BotAdapter (move from BotFrameworkAdapter)

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-dotnet#3146]
The 'BotIdentityKey' const needs to be moved from BotFrameworkAdapter to BotAdapter, to ensure it is available to the customer adapters, which inherit BotAdapter and use it as part of ContinueConversationAsync for Skills.

As well as moving the const, following a discussion with @gabog, we think it would be useful to make the const public as it could be useful for any paths which might require access to the identity. 

cc @johnataylor

**Comment by gabog** [comment]
We need to create issues in the JS, Python and Java repos so we add this constant there as well. 

@tomlm approved the C# PR so it is a bit late to change that but I would suggest we added /// documentation to the constant so user's know how to use it.

**Comment by garypretty** [comment]
Tracking issues created. Closing.

JS tracking issue - https://github.com/microsoft/botbuilder-js/issues/1523
Python tracking issue - https://github.com/microsoft/botbuilder-python/issues/548
Java tracking issue - https://github.com/microsoft/botbuilder-java/issues/166
