### ISSUE TITLE
Bots created using Azure Portal bot create flow cannot change the credentials provider

### ISSUE THREAD

**Issue by arturl** [microsoft/botbuilder-dotnet#3154]
## Version
4.7.0

## Describe the bug
If you create a bot from the template in Azure Portal, changing its credentials provider by setting the `ICredentialProvider` singleton doesn't work.

## To Reproduce
1. Go to Azure Portal and create a new web app bot
2. Download source

Define a new credentials provider, for example:

 ```
    public class DisabledAuthCredentialProvider : ICredentialProvider
    {
         public Task<string> GetAppPasswordAsync(string appId)
        {
            throw new NotImplementedException();
        }
        public Task<bool> IsAuthenticationDisabledAsync()
        {
            return Task.FromResult(true);
        }
        public Task<bool> IsValidAppIdAsync(string appId)
        {
            throw new NotImplementedException();
        }
    }
```
3. Set it as the default credential provider using the following call in startup.cs, `Startup.ConfigureServices`:

```
    services.AddSingleton<ICredentialProvider, DisabledAuthCredentialProvider>();
```
4. Run the bot. You will see that the bot continues to work as expected, you can observe that `DisabledAuthCredentialProvider` is not attached to the adapter.

## Expected behavior
The bot should reject requests. `DisabledAuthCredentialProvider.IsValidAppIdAsync` should be hit. 

## Additional context
The problem goes away if you replace the adapter type in this call:
```
< services.AddSingleton<IBotFrameworkHttpAdapter, AdapterWithErrorHandler>();

> services.AddSingleton<IBotFrameworkHttpAdapter, BotFrameworkHttpAdapter>();

```

You can also fix the issue by replacing the constructor in `AdapterWithErrorHandler` to the one that takes `ICredentialProvider`. (Note: merely adding it won't work as IoC prefers the other ctor that sets the default credentials provider). There are other ways to fix it, but it's hard to discover. This should just work out of the box.

**Comment by EricDahlvang** [comment]
This will probably be addressed by this DCR:

[DCR: Reduce BotFrameworkAdapter constructor complexity through single, extensible BotFrameworkAdapterOptions parameter](https://github.com/microsoft/botbuilder-dotnet/issues/2972)
