### ISSUE TITLE
Add CancellationToken to WebSocketClient::ConnectAsync

### ISSUE THREAD

**Issue by NickEricson** [microsoft/botbuilder-dotnet#3155]
Here

https://github.com/microsoft/botbuilder-dotnet/blob/86d67b989c331fadc8f54efccf081586fc643c9a/libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketClient.cs#L106

The cancellation token should be taken in the ConnectAsync methods and passed through to the underlying transport layer. ConnectAsync invokes code in the bot which could take a long time and should be cancel-able.

[enhancement]

**Comment by NickEricson** [comment]
Comment so it doesn't get closed.

**Comment by NickEricson** [comment]
Comment didn't work. Removing Stale tag and reopening.

**Comment by cleemullins** [comment]
@carlosscastro - are you able to pick this up? Seems like a quick change.
