### ISSUE TITLE
Declarative support for LUIS dynamic lists and external entities

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3156]
LUIS supports both dynamic lists and external entities which are not accessible through the declarative system.  In order to support this:
1) Add dynamicList as a property to the LUIS recognizer.  It should take an expression which evaluates to an object like this: { <entity>: [ {cannonicalForm: <string>, synonyms: [<string>, ...]}, ..], ...} that is passed to LUIS.
2) Add the ability to specify a child recognizer.  The child recognizer would be called and the recognizer results would be passed to LUIS as external entities.  This would allow us to use local regex recognizers or more advanced algorithmic matching using things like edit distance.
3) Create a UnionRecognizer which can union together the results of multiple child recognizers.  For intents, if the names collide pick the maximal score.  For entities, include them all.

**Comment by tomlm** [comment]
# 3 is done, RecognizerSet is the union of child recognizers.
# 1 and # 2 will be done by @chrimc62
