### ISSUE TITLE
Importance flag not working in Teams

### ISSUE THREAD

**Issue by mindncz** [microsoft/botbuilder-dotnet#3161]
Version: .NET SDK 4.7

Setting Importance flag in Activity not work in Teams. 
` var activity = turnContext.Activity.CreateReply("Test Importance"); `
` activity.Importance = "high" `
` await turnContext.SendActivityAsync(activity); `

The message was sent as normal.
![Importance](https://user-images.githubusercontent.com/46016028/71140478-3fe14780-2209-11ea-9705-23e495d3eb88.png)

**Comment by christopheranderson** [comment]
@johnataylor - is this a supported scenario in our current Teams support or a feature request?

**Comment by mindncz** [comment]
Could this support be added into Teams?

**Comment by clearab** [comment]
Setting the importance flag on a message is not currently supported in the Teams channel. I know it is a feature they are considering for the future.

**Comment by mindncz** [comment]
Do you have any plan to fix it?
