### ISSUE TITLE
path resolver like at behaves not as expected

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3165]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

`@objs.name` is expected to be expanded to `turn.recognized.entities.objs.first().name` instead of `turn.recognized.entities.objs.name.first()`.

Typical usage: `@geographyV2.location`

Example: https://github.com/microsoft/botbuilder-dotnet/pull/3164

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by boydc2014** [comment]
@tomlm @vishwacsena , `@x.y` is expected to be 'turn.reconginzed.entities.x.first().y', is that correct ?

**Comment by vishwacsena** [comment]
Not sure. @chrimc62 thoughts?

**Comment by chrimc62** [comment]
For lists we end up with two levels of arrays, i.e.
wheat rye -> bread: [[multigrainWheat, wholeGrainWheat], [rye]]  The current @ resolver unwraps only the first level, not all levels, i.e. @bread -> [multiGrainWheat, wholeGrainWheat].  In the original definition of @ it would unwrap all arrays and produce "multiGrainWheat" in this case.
