### ISSUE TITLE
[Adaptive] [LG] Fluent style expression builder for LG - samples

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3172]
In code based use of expressions, it is hard to just define all expressions as strings. We should consider adding support for and document + add samples that show fluent style construction of expressions especially in code based consumption of adaptive dialogs.

**Comment by cleemullins** [comment]
@vishwacsena, this bug is from December. Should we close it?

**Comment by boydc2014** [comment]
Taking off R10 and aded backlog as the design and intention was not clear right now, @vishwacsena can you also adding some examples of what you refered with fluent-style expression builder.

**Comment by vishwacsena** [comment]
No plans to do this
