### ISSUE TITLE
TeamsActivityHandler should not throw NotImplemented for default case of OnInvokeActivityAsync

### ISSUE THREAD

**Issue by kvbreddy** [microsoft/botbuilder-dotnet#3177]
## Version
4.7.0.

## Describe the bug

We are receiving an Activity from msteams channel of type Invoke and name not in one of the values in the switch case defined in TeamsActivityHandler.cs. In the default  case, it throws an 501(HttpStatusCode.NotImplemented).  But the activity is still forwarded to IMiddlewares and IBot and can be processed. Shouldn’t it be upto the implementation to determine which  HttpStatusCode to return in the default case? 

In our case, we receive activities from custom client canvas, using msteams channel. But as the Status code is returned by the default case even though we are able to process the request, its causing unusual behavior. Is there any work around to not send the NotImplemented as 5xx status code indicates a server error.

## Expected behavior

The default case in the switch should not throw  HttpStatusCode.NotImplemented (https://github.com/microsoft/botbuilder-dotnet/blob/3502f50f0e34a68e49c27ac1f998338f61a13780/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L110). 

## Additional context
I do know that there is a work around here like:
```

protected override async Task<InvokeResponse> OnInvokeActivityAsync(ITurnContext<IInvokeActivity> turnContext, CancellationToken cancellationToken)
{
    if (turnContext.Activity.Name == "custom" && turnContext.Activity.ChannelId == Channels.Msteams)
    {
        // Do something specific here...
        return new InvokeResponse() { Status = 200 };
    }

    return await base.OnInvokeActivityAsync(turnContext, cancellationToken);
}
But SDK fix seems to be the right approach.
```
[bug]

**Comment by johnataylor** [comment]
We resolved this issue, the behavior implemented in the TeamsActivityHandler is correct and consistent.
