### ISSUE TITLE
Microsoft.Bot.Configuration.LuisService.GetEndpoint() Throws NRE if Region is null.

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#3188]
## Version
Microsoft.Bot.Configuration, Version=4.6.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

## Describe the bug
Microsoft.Bot.Configuration.LuisService.GetEndpoint() Throws NRE if Region is null.

    /// <summary>Gets the endpoint for this LUIS service.</summary>
    /// <returns>The URL for this service.</returns>
    public string GetEndpoint()
    {
      string lower = this.Region.ToLower();

## To Reproduce
var service = new LuisService();
var endpoint = service.GetEndpoint();

## Expected behavior
Exception stating Region should be set.

**Comment by christopheranderson** [comment]
Good catch on this bug. I've assigned @tomlm to take a look.

Would a fix on 4.7.x work for you, or do you need it on 4.6.x?

**Comment by DavidStrickland0** [comment]
No rush was just writing some unit tests, hit it and had to decompile to figure it out so thought Id post. Thanks for looking into it.

**Comment by vishwacsena** [comment]
@EricDahlvang we should consider adding `deprecated` flag to this.

**Comment by EricDahlvang** [comment]
A more specific error message has been added for null region.
