### ISSUE TITLE
Testability: Lack of a contract on WaterfallStepContext

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#3201]
Can't unit test WaterfallDialog steps. I have a WaterfallDialog with multiple steps. I'd like to create Unit tests to validate the code I've written. 

**Describe the solution you'd like**
IWaterfallStepContext Interface would be preferred but exposing the constructor on the concrete would allow for the same functionality using integration tests instead of unit tests.

```
public Task<DialogTurnResult> WaterfallStep1(IWaterfallStepContext stepContext,
     CancellationToken cancellationToken)
{
      … My Code
}
```

**Describe alternatives you've considered**
Currently using an extension pattern 

```
public Task<DialogTurnResult> WaterfallStep1(WaterfallStepContext stepContext,
     CancellationToken cancellationToken)
{
     return TestableWaterfallStep1(new WaterfallStepContextFacade(stepContext),
         cancellationToken);
}

public Task<DialogTurnResult> TestableWaterfallStep1(IWaterfallStepContextFacade stepContext,
    CancellationToken cancellationToken)
{
    … My Code …. With StepContext wrapped in IWaterfallStepContextFacade  so it can be mocked for testing.
}

```
Doubling up every Step just for testability seems overly painful.

**Comment by vishwacsena** [comment]
@gabog owns our unit testing infrastructure and can recommend the best way to do this.

**Comment by gabog** [comment]
Hi @DavidStrickland0, are you using the  [DialogTestClient](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp#testing-dialogs)? 

We don't expose WaterfallStepContext there but you should be able to look at the [DialogTurnResult](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp#asserting-dialog-turn-results) object and also the activity sent by your step if you want to check some intermediate state for your step.

[CoreBot.Test](https://aka.ms/cs-core-test-sample) is a full test project that shows how to use DialogTestClient, Moq and data driven tests for CoreBot. 

Hope it helps.

**Comment by DavidStrickland0** [comment]
We use XUnit for our Unit tests with specific code coverage metrics, For any bug a unit test to duplicate that bug is required and the more specific that test can be the better. If there is a bug in the 7th Step of a waterfall it would be preferable to only have to test the 7th step and not have to navigate the dialog through all proceeding steps first. If we do Dialog level testing to valid a bug in a single step the amount of test code we will have to maintain is drastically increased. 

DialogTestClient would be fine for Dialog testing but those seem much more like Integration tests not unit tests. Testing how the Dialog works as a whole not how a single step functions.

This isn't really just isolated to the StepContext. It seems most of the BotFramework is coded in concrete instead of contract which makes what we consider a "Unit Test" hard or impossible to code.

Typically in this type of situation we abstract out the Untestable code into an Isolated Tier and keep it as thin as possible by using some kind of code generation or convention (attributes/configuration etc.) we then move all our functional code deeper into the call stack behind a set of Mockable / Injectable interfaces.

If the BotFramework team sees Dialog level testing to be sufficient and there are no plans to support more specific isolated method level testing or what I am referring to here as Unit Testing. then we'll go ahead and use an abstraction layer to isolate our code from the Botframework code. 
If this is seen as an issue but its going to be a few versions before its fixed then we'll stay with the Extension pattern we have and wait for it. 

Would like to avoid a full abstraction and Isolation if we can.

**Comment by gabog** [comment]
Hi David, thanks for the feedback, I understand your need but we don't have plans for adding additional capabilities in the upcoming release. I will keep this in for feature releases though.

Thanks again
