### ISSUE TITLE
Difference between "Unrecognized prompt" and "Invalid prompt" is not clear

### ISSUE THREAD

**Issue by seaen** [microsoft/botbuilder-dotnet#3203]
## Version
MASTER - 10/30 bug bash

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
1. Go to "Bot Asks" -> "Text input"
2. Switch to "Exceptions" tab

ISSUE: it is not clear what is the difference between "Unrecognized prompt" and "Invalid prompt".   if I ask for a city name, and the user enters "kiev" vs "foo", which of these will get triggered?

## Expected behavior
EXPECTING INSTEAD:  Some sort of clearer differentiation in naming these fields.

ALSO:  Probably "Unrecognized ANSWER" or "Invalid ANSWER" (not prompt - prompt itself is not what we're validating).

## Screenshots
![image](https://user-images.githubusercontent.com/38896146/67905790-ccd42280-fb2f-11e9-83ab-20dadf85ade9.png)

**Comment by vishwacsena** [comment]
Unrecognized Prompt:
Message to send when the recognizer does not understand the user input.

Invalid Prompt:
Message to send when the user input does not meet the validation rules.

**Comment by vishwacsena** [comment]
Tracked via https://github.com/microsoft/botbuilder-dotnet/issues/2934
