### ISSUE TITLE
How To Trace the output in Composer Generated Adaptive Dialogs

### ISSUE THREAD

**Issue by rajeshyalamarthi** [microsoft/botbuilder-dotnet#3207]
Hi, I successfully integrated composer into my V4 echo bot. And it is working pretty fine. My problem is after reading and loading the root dialog into Dialog manager, we are calling method:
**DialogManagerResult dialogresult = await this.dialogManager.OnTurnAsync(turnContext, cancellationToken: cancellationToken);**.

After Executing this method we can able to see the bot response in our chat window. but i want to log that response from composer.
But the Method mentioned above just returning Result which contains "**dialogresult.TurnResult**", which conatins just the status of the dialog.
But, how to Trace the output for logging??

**Comment by v-kydela** [comment]
@rajeshyalamarthi - I would like to help, but I have a few questions.

1. What do you mean when you say you've integrated Composer into your bot? Composer is a tool for building bots. Are you saying you had a preexisting bot that you were able to load into Composer?
2. What do you mean when you say you want to log the response and trace the output? Do you mean you want to save telemetry from your users or do you want to view some kind of output while you're talking to the bot or do you want to make the output available to the bot itself or what?
3. Can you provide screenshots that show what you're experiencing now and what your desired behavior is?

**Comment by rajeshyalamarthi** [comment]
thanks @v-kydela. Yeah what iam trying to say is with the help of composer tool we can able to generate dialogs which includes .lu, .lg, .dialog files. I loaded all those dialogs into my v4 echo bot. And i set up my echo bot in order to read all the dialogs by installing all the nudget packages required.
What i want is when i ask question to the bot, it gives response based on dilaogs and common.lg file.
i want to log the output which bot is sending to the user.
![Capture1](https://user-images.githubusercontent.com/31951690/71710202-13404900-2e21-11ea-8381-493254bf16ff.PNG)
=> In the above image after executing the dialogManager.OnTurnAsync() method we can able to see the output in chat window.
=>But  dialogManager.OnTurnAsync() method returning dialog result which contains TurnResult.status,TurnResult.Result==null,etc..
![Capture2](https://user-images.githubusercontent.com/31951690/71710341-c9a42e00-2e21-11ea-8b3d-382d6b4619de.PNG)
in the above chat window, i asked bot by typing weather. And It replied with the below responses.
**How can i log those responses in code level ??**

**Comment by v-kydela** [comment]
@rajeshyalamarthi - You've explained more about how you've set up your bot, but you still haven't answered the question of what you mean by "logging" responses.

I can sort of see that you want to access the activities that your dialog sends to the user. This can be done by providing a [`SendActivitiesHandler`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.sendactivitieshandler) delegate to your turn context's [`OnSendActivities`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.turncontext.onsendactivities#Microsoft_Bot_Builder_TurnContext_OnSendActivities_Microsoft_Bot_Builder_SendActivitiesHandler_) method. This is normally done by [middleware](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-middleware).

If you want to [log the responses to a telemetry service like Application Insights](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry), you can use [`TelemetryLoggerMiddleware`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.telemetryloggermiddleware).

Does this resolve your issue?

**Comment by rajeshyalamarthi** [comment]
@v-kydela. Not exactly. what i am trying to say is in the above chat window you can see the responses from the bot like **Let's check weather and what is your zipcode?**.
what i am asking how can i get these responses while debugging the code after exceuting the method **DialogManagerResult dialogresult = await this.dialogManager.OnTurnAsync(turnContext, cancellationToken: cancellationToken)**
=>By Logging what i mean is how to log those responses from bot in some database

**Comment by v-kydela** [comment]
@rajeshyalamarthi 

> By Logging what i mean is how to log those responses from bot in some database

Application Insights uses a Kusto database. Can you explain why the `TelemetryLoggerMiddleware` solution isn't acceptable to you?

**Comment by rajeshyalamarthi** [comment]
@v-kydela  , what i meant by db is on order to log my chat in sql db. But thanks @v-kydela , as you mentioned in above comment with the help of **send activities handler to onsendactivities** method with the help of this implementation i can able to see the activities that bot sending that to the user. Thanks a lot.

**Comment by v-kydela** [comment]
@rajeshyalamarthi - I'm glad we could get this resolved
