### ISSUE TITLE
Why does this depend on SourceLink?

### ISSUE THREAD

**Issue by ericrrichards** [microsoft/botbuilder-dotnet#3211]
Microsoft.Bot.Connector and Microsoft.Bot.Schema both depend on SourceLink.Create.CommandLine.  Installing that NuGet package junks up one's project file by adding unnecessary build targets to run SourceLink, which can break builds if your project is hosted on VSTS rather than GitHub.

Unless there's a good reason that these Bot Framework packages should pull in that dependency, it's pretty unwelcome.  I'm spending half a day going through project files and stripping out all of the gunk that the SourceLink NuGet package added.

**Comment by EricDahlvang** [comment]
Related: https://github.com/microsoft/botbuilder-dotnet/issues/2992

BotBuilder-dotnet should be using https://github.com/dotnet/sourcelink

**Comment by vishwacsena** [comment]
@BruceHaley can you take a look and comment?

**Comment by gabog** [comment]
If we don't upgrade to Microsoft.SourceLink, I think we should at least mark the dependency as `<PrivateAssets>all</PrivateAssets>` so it doesn't flow to derive projects.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by BruceHaley** [comment]
It looks like upgrading to Microsoft.SourceLink #2992 needs to be done but will take some time.

If we want a more immediate solution perhaps we should implement Gabo's suggestion now, that is mark the dependency <PrivateAssets>all</PrivateAssets>.

**Comment by BruceHaley** [comment]
PR #3259 implements the immediate solution mentioned above.

**Comment by cleemullins** [comment]
Fixed by #3259. Will release as part of R8 in March.
