### ISSUE TITLE
HttpHelper - Recompose away from "Helper"

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft/botbuilder-dotnet#3217]
I hadn't heard from anybody in a while on my [last post](https://github.com/microsoft/botbuilder-dotnet/issues/2984#event-2846939816), but perhaps because the issue was Closed it doesn't send followups? Reposting below:

I really appreciate your responding to this and sorting it out quickly, but to be honest I've been wondering whether this "helper" itself really should be public... While the methods themselves are useful, I'm wondering if we could put them somewhere more specific than just a general "helper". What do you think? As a possible suggestion, as it's only two main methods (one one static field), perhaps we could:

- put the static BotMessageSerializer field into a static class, like a [namespace].Serialization static class

- make the remaining methods into Extenstion methods: ReadRequest, which takes in just an HttpRequest, could be made into ReadAsActvivity, for example, and WriteResponse could be WriteInvokeResponse

What do you think? I'm happy to work on this as a PR, either the design proposed or an alternative.

**Comment by srinaath** [comment]
@johnataylor Could you take a look at this ticket when you get a chance.

**Comment by HiltonGiesenow** [comment]
Any news on this by any chance?

**Comment by johnataylor** [comment]
As your previous issue suggested we've made the methods public. However, once we make them public changing them can involve some significant cost. For example, we would have to mark the current  methods as deprecated in favor of the replacements etc.

That's not to say I don't like the suggested factoring, its more that I'm thinking the cost of a largely syntactic change like this is hard to justify. (Incidentally, I don't mean to sound dismissive of syntactic things like extension methods: they are a great tool to have.)

The time to have done this would have been when we first made these public. So I'm closing this now. Thanks for your comments, it is really appreciated, hopefully there are other areas in the code base (packages and samples and docs) that you have similar insights on and we would be more than happy to look at PRs and issues. Thanks.

**Comment by HiltonGiesenow** [comment]
I should have thought more about this at the time I suggested it - was hoping it was recent enough this might not have been a problem. As it's just a few weeks, I'm probably still the only person using this new public class ;-).  Thanks for the review though and let me know if it changes at any point, happy to work on it.
