### ISSUE TITLE
Skill host deployed on multiple machines, causes UnAuthorized exceptions when relaying activities back to client

### ISSUE THREAD

**Issue by sbacha** [microsoft/botbuilder-dotnet#3242]
## Version
4.7.0

## Describe the bug
We have our skill host deployed on Pod 1 and Pod 2.
Client sends activity and Pod1 recieves acitivty and relays the activity to skill
Skill sends back activity which hits a Traffic manager and requests gets sent to Pod2
Pod2 process the activity and sends to client. From Pod2 to client we get UnAuthorized Exception.

## To Reproduce
Set up 2 VA hosts, a webchat client and a skill.
Let VA 1 accept the client calls and skill reply to VA 2 by setting up the  callback url to VA2

## Expected behavior
Pod2 can successfully send activity to client.
Skill host can be deployed on multiple machines and successfully process/send any incoming skill activity.

**Comment by gabog** [comment]
Resolved in #3244
