### ISSUE TITLE
[Expression] Make Expression meet the requirement from Adaptive Card team

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#3249]
We have some requirements from AdaptiveCards team. 
- [x] ${} instead of @{} as bounding syntax.
- [x] `+` for concatenation. If either operand is a string, then `+` should do string concatenation and cast other operand to string. 
- [x] move string interpolation into expressions (bring forward Tom's work into expressions so hosts do not have to repeat this)
- [x] namespace change. Overall brand: Adaptive Expressions; NuGet: AdaptiveExpressions; NpmJS: adaptive-expressions

**Comment by vishwacsena** [comment]
@matthidinger were there other changes required? can you help summarize/ confirm the list above? We'd like to start work on this at least on the things that are PORs.

**Comment by matthidinger** [comment]
The working document is here (internal link), but it would be great if we can regroup as I think some decisions are still pending. Are you folks available Weds at 3pm to dive into it? I can send the meeting invite

https://dev.azure.com/microsoft/AdaptiveCards/_git/Explorations?path=%2Fdocs%2FExplorations%2FTemplateLanguage%2FCommonExpressionLanguage.md&version=GBmaster&_a=preview

**Comment by vishwacsena** [comment]
@boydc2014 we can start resourcing this. See list above. Let's use this ticket as a living tracking item as we find other things to do. 

@tomlm @chrimc62 @matthidinger
