### ISSUE TITLE
Test custom adapters and ensure they work with .NetCore 3.1

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#3264]
We are making updates to Integration.AspNetCore so it supports .NetCore 3.1 (see [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/3263) for details).

This issue is about testing the custom adapters (currently targeting NetStandard2.0) and making sure they work with .NetCore 3.1, and make any updates that may be necessary to make sure they work.

The custom adapters to test are:

- [x] Facebook
- [x] Slack
- [x] Twilio
- [x] Webex

**Comment by garypretty** [comment]
All 4 custom adapters tested using .Net Core 3.1 (latest master as of 30/01)
