### ISSUE TITLE
[LG] Improve LG errors and description

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3266]
# Error descriptions 

## Design
1. Start with the .lg file that contains the offending issue.
2. Include the leaf error message. e.g. `'scope.xyz' evaluated to null.`
3. Include description of the rest of the composition stack with context using the following convention - 
```markdown
[<templatename>] (Condition '<condition expression>' | Property '<Property name>' | Case '<case expression>'): Error occured when evaluating '<variation text value>'
```
4. In case of composition, include the complete failure stack.
5. In case of file import, include the complete import stack.

Here is a complete example
```markdown
test.lg: 'dialog.abc' evaluated to null. 
[structured3] Error occured when evaluating '@{structured2()}'. 
[structured2] Property 'Text': Error occured when evaluating 'I want @{conditionaltemplate1()}'. 
[conditionalTemplate1] Condition '@{dialog}': Error occured when evaluating 'I want @{template1()}'. 
[template1] Error occured when evaluating 'I want @{dialog.abc}'. 
Imports: rootdialog.lg imports test.lg.
```

## Syntax errors in .lg file
Basic syntax errors should be caught during load time. E.g. this does not fail until runtime and fails with a cryptic error

**LG file content**: 
```markdown
sendActivity("I want @{dialog.abc}")
```

**Expected**: 
Static (load time) failure with the following error - 

```
test.lg: [Error] line 1:0 - line 1:36: Unexpected content. Expecting either a comment or a template definition or an import statement.
```

**Runtime failure text**:
```
[Error] line 1:0 - line 1:36: error context.
```
## EvaluateText call

**Actual**: Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. Error occured when evaluating 'I want @{dialog.abc}'.

```C#
sendActivity("I want @{dialog.abc}")
```

## Direct reference in variation text
**Actual**: Error occurs when evaluating expression template1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [template1] Error occured when evaluating 'I want @{dialog.abc}'. 

```markdown
# template1
- I want @{dialog.abc}
```

## Refernece in a prebuilt function
**Actual**: Error occurs when evaluating expression prebuilt1(): Value cannot be null. Parameter name: o

**Expected**: test.lg: 'dialog.abc' evaluated to null. [template1] Error occured when evaluating 'I want @{foreach(dialog.abc, item, template1())}'. 

```markdown
# prebuilt1
- I want @{foreach(dialog.abc, item, template1())}
```

## Via template composition
**Actual**: Error occurs when evaluating expression template2(): Error occurs when evaluating expression template1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [template2] Error occured when evaluating 'With composition @{template1()}'. [template1] Error occured when evaluating expression 'dialog.abc' in text 'I want @{dialog.abc}'. 

```markdown
# template2
- With composition @{template1()}
```

## IF..ElSe with variation
**Actual**: Error occurs when evaluating expression conditionalTemplate1(): Error occurs when evaluating expression template1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [conditionalTemplate1] Condition '@{dialog}': Error occured when evaluating 'I want @{template1()}'. [template1] Error occured when evaluating 'I want @{dialog.abc}'. 

```markdown
# conditionalTemplate1
- IF : @{dialog}
    - I want @{template1()}
- ELSE : 
    - ok
```

## If..ElSe with failing condition
**Actual**: Error occurs when evaluating expression ‘conditionalTemplate2()’: conditionalTemplate2() is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [conditionalTemplate2] Condition '@{dialog.abc}': Error occured when evaluating 'dialog.abc'.

```markdown
# conditionalTemplate2
- IF : @{dialog.abc}
    - @{template1()}
```

## Sturcutred template direct reference
**Actual**: Error occurs when evaluating expression structured1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [structured1] Property 'Text': Error occured when evaluating 'I want @{dialog.abc}.

```markdown
# structured1
[Activity
    Text = I want @{dialog.abc}
    SuggestedActions = foo | bar
]
```

## Structured with template composition
**Actual**:Error occurs when evaluating expression structured1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [structured2] Property 'Text': Error occured when evaluating 'I want {@template1()}'. [template1] Error occured when evaluating 'I want @{dialog.abc}'.

```markdown
# structured2
[Activity
    Text = I want @{template1()}
    SuggestedActions = foo | bar
]
```

## Structured template composition

**Actual**: Error occurs when evaluating expression structured3(): Error occurs when evaluating expression structured2(): Error occurs when evaluating expression template1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [structured3] Error occured when evaluating '@{structured2()}'. [structured2] Property 'Text': Error occured when evaluating 'I want @{template1()}'. [template1] Error occured when evaluating 'I want @{dialog.abc}'. 

```markdown        
# structured3
[Activity
    @{structured2()}
    Speak = I'm so cool!
]
```

## Switch condition variation text

**Actual**: Error occurs when evaluating expression switchcase1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [switchcase1] Case '1': Error occured when evaluating 'I want @{dialog.abc}'.

```markdown
# switchcase1
- SWITCH: @{turn.testValue}
- CASE: @{1}
    - I want @{dialog.abc}
- DEFAULT:
   - final output
```

## Switch condition, reference in condition

**Actual**: Error occurs when evaluating expression switchcase1(): Error occurs when evaluating expression ‘dialog.abc’: dialog.abc is evaluated to null

**Expected**: test.lg: 'dialog.abc' evaluated to null. [switchcase1] Case 'Default': Error occured when evaluating 'I want @{dialog.abc}'.

```markdown
# switchcase2
- SWITCH: @{turn.testValue}
- CASE: @{1}
    - all good
- DEFAULT:
   - I want @{dialog.abc}
```

## Copy for error strings

```C#
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Microsoft.Bot.Builder.LanguageGeneration
{
    public class LGErrors
    {
        // Do not hit this when I load an empty LG file? 
        public const string NoTemplate = "LG file must have at least one template definition";

        // What other restrictions do we have for template name in terms of disallowed characters?
        public const string InvalidTemplateName = "Invalid template name. Name cannot include spaces.";

        public const string InvalidTemplateBody = "Invalid template body. Expecting '-' prefix.";

        // What other restrictions for structure name?
        // We should add a separate error for 'Missing structure name. Name cannot be blank, cannot include spaces.'
        public const string InvalidStrucName = "Invalid structure name. Name cannot include spaces.";

        public const string MissingStrucEnd = "Invalid structure body. Expecting ']' at the end of the body.";

        public const string EmptyStrucContent = "Invalid structure body. Body cannot be empty";

        public const string InvalidStrucBody = "Invalid structure body. Body can only include <PropertyName> = <Value> pairs.";

        public const string InvalidWhitespaceInCondition = "Invalid condition: At most 1 whitespace allowed between 'IF/ELSEIF/ELSE' and ':'.";

        // cannot repro this with 
        // # foo
        // - IF: @{dialog.abc}
        //     - abc
        // - : @{dialog.def}
        //     - def
        public const string NotStartWithIfInCondition = "Invalid condition: Conditions must start with 'IF/ELSEIF/ELSE' prefix.";

        public const string MultipleIfInCondition = "Invalid template body. There cannot be more than one 'IF' condition. Expecting 'IFELSE' or 'ELSE' statement.";

        public const string NotEndWithElseInCondition = "Conditional response template does not end with 'ELSE' condition.";

        public const string InvalidMiddleInCondition = "Invalid template body. Expecting 'ELSEIF'.";

        public const string InvalidExpressionInCondition = "Invalid condition. 'IF', 'ELSEIF' definitions must include a valid expression.";

        public const string ExtraExpressionInCondition = "Invalid condition. 'ESLE' definition cannot include an expression.";

        public const string MissingTemplateBodyInCondition = "Invalid condition body. Conditions must include a valid body.";

        public const string InvalidWhitespaceInSwitchCase = "Invalid condition: At most 1 whitespace allowed between 'SWITCH/CASE/DEFAULT' and ':'.";

        public const string NotStartWithSwitchInSwitchCase = "Invalid conditional response template. Expecting a 'SWITCH' statement?";

        public const string MultipleSwithStatementInSwitchCase = "Invalid template body. There cannot be more than one 'SWITCH' statement. Expecting 'CASE' or 'DEFAULT' statement.";

        public const string InvalidStatementInMiddlerOfSwitchCase = "Invalid template body. Expecting a 'CASE' statement.";

        public const string NotEndWithDefaultInSwitchCase = "Conditional response template does not end with 'DEFAULT' condition.";

        public const string MissingCaseInSwitchCase = "Invalid template body. Expecting at least one 'CASE' statement.";

        public const string InvalidExpressionInSwiathCase = "Invalid condition. 'SWITCH' and 'CASE' statements must include a valid expression.";

        public const string ExtraExpressionInSwitchCase = "Invalid condition. 'DEFAULT' statement cannot include an expression.";

        public const string MissingTemplateBodyInSwitchCase = "Invalid condition body. Expecing valid body inside a 'CASE' or 'DEFAULT' block.";

        public const string NoEndingInMultiline = "Expecting '```' to close the multi-line block.";

        public const string LoopDetected = "Loop detected:";

        public static string DuplicatedTemplateInSameTemplate(string templateName) => $"Duplicate definitions found for template: '{templateName}'";

        public static string DuplicatedTemplateInDiffTemplate(string templateName, string source) => $"Duplicate definitions found for template: '{templateName}' in '{source}'";

        public static string NoTemplateBody(string templateName) => $"Missing template body in template '{templateName}'";

        public static string TemplateNotExist(string templateName) => $"No such template '{templateName}'";

        public static string ErrorExpression(string refFullText, string templateName, string prefixText ) => $"[{templateName}] {prefixText} Error occured when evaluating '{refFullText}'";

        public static string NullExpression(string expression) => $"'{expression}' evaluated to null";

        public static string ArgumentMismatch(string templateName, int expectedCount, int actualCount) => $"arguments mismatch for template '{templateName}'. Expecting '{expectedCount}' arguments, actual '{actualCount}'.";

        public static string ErrorTemplateNameformat(string templateName) => $"'{templateName}' cannot be used as a template name. Template names must be avalid string.";

        public static string TemplateExist(string templateName) => $"template '{templateName}' already exists.";
    }
}
```

**Comment by Danieladu** [comment]
Several questions.

1. For the error stack, I think the bottom-most error needs to come first. 
for example
```
# t2
- @{t1()}

# t1
- @{a}
```

assume `a` is not exist, when evaluate template `t2`, I think the error should be  
```
'a' evaluated to null.  [t1] Error occured when evaluating expression 'a' in text '- @{a}'. [t2] Error occurred when evaluating '- @{t1()}'.
```

2. Currently, we do not throw exception/diagnostic in IF condition, because we would treat the error expression as a `false` result and return it.

3. In this pr, #3273, I have adapted the most error message, except for the two above, the following one.

In condition/switch/case mode, when the error occurred in the template body, but not the condition itself, for example:
```
# conditionalTemplate1
- IF : @{true}
    - I want @{a}
- ELSE : 
    - ok
```

When the library evaluate `- I want @{template1()}`, itself does not know which condition trigger it.
so, the error message current would be 
```
 'a' evaluated to null. [conditionalTemplate1] Error occured when evaluating '- I want @{a}'.
```

But not 
```
 'a' evaluated to null. [conditionalTemplate1] Condition '@{true}'. Error occured when evaluating '- I want @{a}'.
```

**Comment by vishwacsena** [comment]
In LG file if > !# @sctrict = true, then throw on all `null` evaluations.

**Comment by Danieladu** [comment]
test file and result: https://github.com/microsoft/botbuilder-dotnet/blob/cc873222103e62cc50a8109d2be38a5c38268fdf/tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/ExceptionExamples/RunTimeErrors.lg

**Comment by cleemullins** [comment]
@danieladu, This is a P0 issue in R8. Do we have an ETA for when this is done?

**Comment by Danieladu** [comment]
> @Danieladu, This is a P0 issue in R8. Do we have an ETA for when this is done?

Yes, we have close it.
