### ISSUE TITLE
Release notes for 4.7

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/botbuilder-dotnet#3271]
## Version
4.7

## Describe the bug
I wanted to see what are the new features included in 4.7 SDK but the link of **Click here to find out what's new with Bot Framework** takes me to the archived repo. 

## To Reproduce
On main README.md, click on the **Click here to find out what's new with Bot Framework**

## Expected behavior
It should take me to 4.7 Release Notes. 
[bug]

**Comment by mdrichardson** [comment]
@arafattehsin I've submitted a PR to update the link to point to [the docs](https://docs.microsoft.com/en-us/azure/bot-service/what-is-new?view=azure-bot-service-4.0). If you're looking for release notes, you can [check here](https://github.com/microsoft/botbuilder-dotnet/releases).

**Comment by arafattehsin** [comment]
Thanks @mdrichard. 👍

**Comment by arafattehsin** [comment]
Thanks @mdrichardson 👍
