### ISSUE TITLE
[Webchat][.NetCore][BotFramework] UpdateActivityAsync Method is not working in web chat

### ISSUE THREAD

**Issue by Chekrii** [microsoft/botbuilder-dotnet#3278]
## Platform 

* .NetCore
* Bot frameworkV4

## Host
* Ms Teams
* Web Chat

Hi,

We are using connector.Conversations.UpdateActivityAsync() to update the previous activity with
new activity.
This method is working fine in teams but in Web chat it is throwing error.
Is there any alternative way to update any previous activity in web chat.

Please help.
Thanks.

**Comment by xieofxie** [comment]
A quick search ends up with https://github.com/microsoft/BotFramework-WebChat/issues/2426..
Maybe you could also track this there.

**Comment by stevkan** [comment]
As @xieofxie indicates, `updateActivity` is not supported by Web Chat at this time. I would suggest you add to the conversation with your interest, following the provided link, which will help drive the need for future development.
