### ISSUE TITLE
[LG] Need a way to iterate strings

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-dotnet#3279]
**Is your feature request related to a problem? Please describe.**

Currently, there is no way to iterate over a string using Language Generation / Common Expression Language. This issue spawns from a [StackOverflow question](https://stackoverflow.com/questions/59836636/botcomposer-how-to-iterate-through-the-characters-of-a-string-using-lg-language). Basically, they want to be able to pull numbers out of strings, such that:

* "hey 1234" becomes "1234"
* "xyz1234" becomes "1234"

**Describe the solution you'd like**

Ideally, `array()` could turn a string into an array, so that it can be iterated over. 

**Describe alternatives you've considered**

Alternatively, `split(<string>, <delimiter>)` could accept a null or wildcard delimiter, which would just split every character. [It looks like that may have been considered](https://github.com/microsoft/botbuilder-dotnet/blob/c949e42abd3663e41cd7ee373c54c554d3f351a7/tests/Microsoft.Bot.Expressions.Tests/ExpressionEngineTests.cs#L357).

**Additional context**

In my own testing, with `var test = "hey, 1234"`,

* `array(test)` = `[ 'hey, 1234' ]`
* `createArray(test)` = `[ 'hey, 1234' ]`
* `split(test, null)` = `[ 'hey,' '1234']`
* `split(test, "")` = `[ 'hey,' '1234']`
* `split(test, string.Empty)` = `[ 'hey,' '1234']`

[enhancement]

**Comment by eduardmartos** [comment]
Related with this, another interesting feature will be the ability to create an array of numbers like this:
intarray([start], [end])
intarray(1, 10) => [1,2,3,4,5,6,7,8,9,10]

So we can use foreach in conjunction with this and substring to iterate on each char of the string.
And this could be useful for other scenarios too.

**Comment by vishwacsena** [comment]
We should support split(str) or split(str, '') to return an array of entire string split.
Also the prebuilt functions [doc][1] is missing details for `array` and the link is broken.

@boydc2014 

[1]:https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#array
