### ISSUE TITLE
All public code should have documentation

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3283]
## Describe the bug
Any public class, interface, method or property should have documentation.  There are many places where is it missing, for example IMemory or StackedMemory in the expression parser.  We should turn on missing documentation triggering an error.

[bug]

**Comment by johnataylor** [comment]
@Virtual-Josh  we need doc comments in this file:
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs

**Comment by garypretty** [comment]
Closing this issue. Now tracking this work with #4052.
