### ISSUE TITLE
Wiki should have instructions for VS Code and command line

### ISSUE THREAD

**Issue by GeekTrainer** [Microsoft/botbuilder-dotnet#329]
The getting started is for Visual Studio only. We should have a walk-through for those using VS Code as well.

**Comment by vishwacsena** [comment]
By design. V4 C# is Visual studio only. Happy to evaluate post //BUILD.

**Comment by GeekTrainer** [comment]
Can you please explain the technical reason for this decision? Everything can be done in VS Code.

**Comment by GeekTrainer** [comment]
@vishwacsena Can you please explain the technical reason for this decision? Everything can be done in VS Code.
