### ISSUE TITLE
[Skill] Handle EndOfConversation on Skill as part of core SDK

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botbuilder-dotnet#3307]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

The pattern to close out a ongoing skill dialog is for the parent bot to send over an activity that's type EndOfConversation. The skill has to handle it and clear out the dialog stack. Right now it's up to the skill developer to handle it, but it should be part of the core SDK.

For reference, in VA implementation, we added a component SkillMiddleware that's added for the skill's adapter to handle EndOfConversation: https://github.com/microsoft/botframework-solutions/blob/next/sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillMiddleware.cs

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by gabog** [comment]
This has been implemented in 4.8 in [this commit](https://github.com/microsoft/botbuilder-dotnet/commit/705f7fbb9d6fafd33fe9ee16ddde7c44e18094ac#diff-23d583999bd355eb18cf5b220d80214c). 
closing
