### ISSUE TITLE
Nested evaluation of LG Templates

### ISSUE THREAD

**Issue by manish-95** [microsoft/botbuilder-dotnet#3316]
**Is your feature request related to a problem? Please describe.**
Right now, I have to create a new Activity template for each response text in an lg file to explicitly set the inputHint.  As the number of responses increases, so does the number of templates required. It would be great if a single activity template could take a response text title as an input and generate the output activity based on the title given

**Describe the solution you'd like**
A method to pass the response text title to the TemplateEngine.GenerateActivityForLocale() method and be able to use a single activity template in the .lg file to generate a response activity dynamically

[enhancement]

**Comment by tonyanziano** [comment]
Hi @manish-95 , LG is still in preview and not fully supported.

We have asked our support team to take a look, but they still need to get up to speed on the product being that it is still fairly new.

**Comment by CoHealer** [comment]
We'll triage it tomorrow @manish-95 and do our best to help!

**Comment by dmvtech** [comment]
hi @manish-95 I'm taking a look at this. I'll let you know if I have any questions.

**Comment by dmvtech** [comment]
Hi @manish-95 

I'm not 100% sure if i understand the ask, but does the following accomplish what you need?
```
# singleActivityTemplate(title, inputHint)
[Activity
    Text = @{if(isTemplate(title), template(title), title)
    InputHint = @{inputHint}
]
```

**Comment by manish-95** [comment]
Hi @dmvtech , I tried implementing this but I get a response activity with the text field populated with **@{if(isTemplate(title), template(title), title)** as its value.

**Comment by Danieladu** [comment]
> Hi @dmvtech , I tried implementing this but I get a response activity with the text field populated with **@{if(isTemplate(title), template(title), title)** as its value. Are isTemplate(title) and template(title) built-in functions, or do I have to define them?

Try add a close curly bracket `}`

**Comment by manish-95** [comment]
@Danieladu Have added that as well. Now I get the following error:
 `error message: isTemplate does not have an evaluator, it's not a built-in function or a customized function in expression 'if(isTemplate(title), template(title), title)' `

**Comment by vishwacsena** [comment]
@manish-95 are you using the latest from the botbuilder myget feed or Nuget? can you try the latest nightly from the myget feed and report back? https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily

**Comment by manish-95** [comment]
@vishwacsena After updating all the packages , I now get a new error as follows:

`System.TypeLoadException: 'Could not load type 'Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine' from assembly 'Microsoft.Bot.Builder.LanguageGeneration, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'`

**Comment by Danieladu** [comment]
> @vishwacsena After updating all the packages , I now get a new error as follows:
> 
> `System.TypeLoadException: 'Could not load type 'Microsoft.Bot.Builder.LanguageGeneration.TemplateEngine' from assembly 'Microsoft.Bot.Builder.LanguageGeneration, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'`

We have updated the API in the new version. So replace `TemplateEngine` with `LGFile`, 
the classic sample is as follows:
```
var lgFile = LGParser.ParseFile('your lg file path');
var result = lgFile.EvaluateTemplate("templateName", scope);
```

**Comment by manish-95** [comment]
I am using this with the latest version of the Virtual Assistant solution, so the solution template is built to reference the TemplateManager, which internally uses the TemplateEngine. The entire structure will have to be changed to incorporate the solution provided by you ,right  @Danieladu ?

**Comment by vishwacsena** [comment]
@manish-95 yes, all references to TemplateEngine needs to be updated.

**Comment by cleemullins** [comment]
Reassigned to Vishwac. @vishwacsena, could you please triage this. I'm not sure if it's in scope for R8.

**Comment by vishwacsena** [comment]
Closing with the solution provided. @manish-95 please update your bot to use the latest nightly packages and reactivate this ticket if you need further assistance.
