### ISSUE TITLE
BOT id in the response activity changed

### ISSUE THREAD

**Issue by Sams4u** [microsoft/botbuilder-dotnet#3324]
Recently i migrated my V3 bot V4(4.5.2) with channel support Directline, Facebook, teams & Webchat. After migration from.id property of all the response activities sent by the bot to user has changed. In V3 it used to be the Bot Channel registration name/Handler name(I keep Bot channel Registration, Handler, Directline site name same). Now this property has the same name appended with some random text like `"from":{"id":"MY_BOT_ID@xYV_J4rtvL8","name":"My bot name","aadObjectId":null,"role":null}"`.

**Comment by mdrichardson** [comment]
@Sams4u That's correct. A major version change (v3.*.* -> v4.*.*) in the Bot Framework indicates that there are breaking changes. This is one of them.
