### ISSUE TITLE
Dialogs not supported - Topics instead?

### ISSUE THREAD

**Issue by waretec** [Microsoft/botbuilder-dotnet#333]
I am not sure which design principles the botbuilder will mainly support, but when I started developing my bot I thought that [dialogs ](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-manage-conversation-flow) would be a great principle to define a conversation-flow. 

I developed the bot on .NET 4.6 as well as on .NET Core 2.0. The latter I paused because I had some serialization issues [(Feature Request)](https://github.com/Microsoft/BotBuilder/issues/572). 
It was communicated that the problem should be solved with the V4 botbuilder. 
I updated my nuget packages on the first day V4 was released, wondering why all the dialogs won't compile. 
After checking the samples in this repo, I just saw the "topic"-concept. 

So, I was wondering if there is a change in the botbuilder principles or if the V4 is just missing some features (I know, it's just a prerelease...). 
At some point I only want to implement the .net core bot... Therefore, I'd like to know which principle to use for designing a more complex "conversation".

**Comment by cleemullins** [comment]
We've made some progress on this. We now have prompts, and have a PR currently outstanding for Waterfall dialogs. We have more plans here, but nothing public yet.

**Comment by cleemullins** [comment]
(Simple) Dialogs are being merged today. Hopefully, this helps provide a good start. We're looking at many more abstractions, but are not there yet.
