### ISSUE TITLE
Sending an activity inside a Prompt Validator doesn't fire the Retry Prompt message

### ISSUE THREAD

**Issue by fcapallera** [microsoft/botbuilder-dotnet#3335]
## Version
netcore 2.1, SKD 4.0

## Describe the bug
I have an imput prompt (TextPrompt, ConfirmationPrompt) with an associated promptValidator method and a `PromptOptions` object with a RetryPrompt.

If inside the PromptValidator method (that returns a `Task<bool>`) i send an activity, the `RetryPrompt` from `PromptOptions` is never sent.

## To Reproduce
1. Have a custom prompt validator method for any prompt.
2. Have a retry prompt message on said prompt.
3. Send an activity from inside the custom prompt validator method.
4. See that the activity from inside the prompt validator is sent but the retry prompt is not.

## Expected behavior
I expect to be able to send an error message from inside the prompt validator while still being able to send the retry prompt if the validation fails.

## Screenshots

```
private async Task<DialogTurnResult> AskEmailStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
{
    var promptOptions = new PromptOptions
    {
        Prompt = MessageFactory.Text("Please enter your username (email)"),
        RetryPrompt = MessageFactory.Text("This email does not exist. Please try again. You can cancel anytime.")
    };

    return await stepContext.PromptAsync("EmailValidator", promptOptions, cancellationToken);
}


private async Task<bool> ValidateEmailAsync(PromptValidatorContext<string> promptContext, CancellationToken cancellationToken)
{
    var email = promptContext.Context.Activity.Text;

    var userCollection = await PrestashopApi.GetCustomerByEmail(email);

    if(userCollection.Elements.Count == 0)
    {
        await promptContext.Context.SendActivityAsync("Send some other message");
        return await Task.FromResult(false);
    }

    return await Task.FromResult(true);
}
```

![image](https://user-images.githubusercontent.com/36483261/73727900-9f9c9f00-4732-11ea-8944-633a6ede1cda.png)

If I comment out the `SendActivityAsync` line, the RetryPrompt is sent as expected.

![image](https://user-images.githubusercontent.com/36483261/73728331-729cbc00-4733-11ea-8cd9-7e8dbf7e9181.png)

[bug]

**Comment by xieofxie** [comment]
Interesting.. I just found that in the library, they check this:
https://github.com/microsoft/botbuilder-dotnet/blob/4df966c2a1904b2f72365dbdbd0ab12f4a356a66/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L160
So it seems to be the designed behavior, but I am not sure.

**Comment by fcapallera** [comment]
I see... The obvious workaround which is setting `Responded` to false after sending the activity in the PromptContext is not possible because `Responded` is readonly.

So is the `Responded` flag set to true even if it's the bot and not the user who "responded" the previous activity? I don't get why should it be that way.

**Comment by xieofxie** [comment]
@fcapallera I think it means that when developer sends something, it suppresses the original RetryPrompt automatically.
So in your scenario, you should also send promptContext.Options.RetryPrompt after "Send some other message".

**Comment by fcapallera** [comment]
Thanks, I didn't think about that! I'll close the issue since it wasn't a bug.
