### ISSUE TITLE
LG sets a default input hint on activities which leads to issues with prompts

### ISSUE THREAD

**Issue by pavolum** [microsoft/botbuilder-dotnet#3344]
## Version
What package version of the SDK are you using.
**4.7.2**

## Describe the bug
Give a clear and concise description of what the bug is.
When LG builds an activity from text in CreateActivity() within ActivityFactory.cs it adds a default value for inputHint (acceptingInput). Since it provides a default inputHint value then the BF SDK does not override it.
 
For example, in the scenario where you are using lg to create an activity for a prompt and you pass it an unstructured lg string then it creates an activity with input hint ‘acceptinginput’. When the activity is passed to the SDK prompt class, the prompt class does not set inputhint to the desired ‘expectinginput’ because it was previously set by lg. 

## To Reproduce
1) Create an activity from an unstructured lg string using the LG ActivityFactory.CreateActivity(string lgStringResult)
2) Send that activity as part of a prompt
3) notice that the prompt will have an input hint of 'AcceptingInput' because the LG set it to that and the sdk prompt class did not override it to the usual prompt 'ExpectingInput'

## Expected behavior
I expected lg createActivity to not set a default inputHint and leave that customization to the developer. This would also enable the SDK classes such as prompt to set the correct inputHint for the activity.

## Additional context
Comments from Vishwac: I believe the fix here needs to be two fold – one in LG as well as one in our input dialog (for adaptive) that do not use the underlying prompts

[bug]

**Comment by vishwacsena** [comment]
Two part fix to this - 
1. we should not set a default for inputHint from activityFactory POV. 
2. we should update adaptive inputs to set inputHint = expectingInput whenever we are issuing a prompt or reprompt (unrecognized/ invalid prompt).

**Comment by Danieladu** [comment]
Sorry for the blocking.

The `AcceptingInput` is added by `MessageFactory.Text()` function. 

I do not know why the SDK would insert the `AcceptingInput` into the default message activity when `inputHint` property is not set.

We will make some investigation and provide the solution asap.

**Comment by vishwacsena** [comment]
@boydc2014 did we also do a fix so input dialog sets this correctly on prompt/ reprompt?

**Comment by boydc2014** [comment]
> @boydc2014 did we also do a fix so input dialog sets this correctly on prompt/ reprompt?

yes, see https://github.com/microsoft/botbuilder-dotnet/pull/3427
