### ISSUE TITLE
GetConversationMembers not surfaced through the adapter, requires application credentials

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#335]
### Issue
To get the members of a conversation from a conversation reference currently requires creating a `ConnectorClient` from your bot code, which requires the bot's application credentials.

### Expected
Should be able to get members of a conversation from a `context` or `adapter` object, without having to supply application credentials.

### Example
This is what I currently do:

In Startup.cs:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(_ => Configuration);
    services.AddBot<MyBot>(options =>
    {
        options.CredentialProvider = new ConfigurationCredentialProvider(Configuration);
        var appId = Configuration.GetSection(MicrosoftAppCredentials.MicrosoftAppIdKey)?.Value;
        var password = Configuration.GetSection(MicrosoftAppCredentials.MicrosoftAppPasswordKey)?.Value;
        var credentialProvider = new MicrosoftAppCredentials(appId, password);
        options.Middleware.Add(new MembershipListener(credentialProvider));
    });
}
```
In MembershipListener.cs:
```csharp
internal class MembershipListener : IMiddleware
{
    private ServiceClientCredentials Credentials { get; set; }

    public MembershipListener(ServiceClientCredentials credentials = null)
    {
        Credentials = credentials;
    }

    public async Task OnProcessRequest(IBotContext context, MiddlewareSet.NextDelegate next)
    {
        //...
                        var client = new ConnectorClient(new Uri(context.Request.ServiceUrl), Credentials);
                        var accounts = await client.Conversations.GetActivityMembersAsync(
                            context.Request.Conversation.Id,
                            context.Request.Id);

         // ...
        await next();
    }
```

This is what I'd like to do:
In Startup.cs:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(_ => Configuration);
    services.AddBot<MyBot>(options =>
    {
        options.CredentialProvider = new ConfigurationCredentialProvider(Configuration);
        options.Middleware.Add(new MembershipListener());
    });
}
```
In MembershipListener.cs:
```csharp
internal class MembershipListener : IMiddleware
{
    public async Task OnProcessRequest(IBotContext context, MiddlewareSet.NextDelegate next)
    {
        //...
                        var accounts = await context.GetActivityMembersAsync(
                            context.Request.Conversation.Id,
                            context.Request.Id);

         // ...
        await next();
    }
```

**Comment by cleemullins** [comment]
@JonathanFingold - This code was recently updated by @tomlm. 

Can you check and see if this issue is still relevant? I believe it's resolved.

**Comment by JonathanFingold** [comment]
@cleemullins , The issue appears to remain.

The method for getting conversation members is declared/defined in:
- IConversations.GetConversationMembersWithHttpMessagesAsync
- Conversations.GetConversationMembersWithHttpMessagesAsync

I don't see that functionality surfaced anywhere else. And so, you're stuck jumping through a bunch of hoops:
- To get a Conversations object, you need a ConnectorClient.
- To get a ConnectorClient you need credentials for the bot.

**Comment by cleemullins** [comment]
This has been added into the BotFRameworkAdapter. Found here:
https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L375

**Comment by JonathanFingold** [comment]
@cleemullins , excellent, thanks.
