### ISSUE TITLE
Loading lg throws syntax errors on template names

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3352]
## Describe the bug
When loading lg files, exceptions are thrown by the expression evaluator for .lg template names because the expression evaluator does not know the template names.

## To Reproduce
Debug with exceptions on the test: Microsoft.Bot.Builder.Dilogs.Adaptive.Tests/GeneratorTests/Generator_sandwich

## Expected behavior
We should not throw exceptions in normal operation.

## Additional context
`
>	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.BuiltInFunctions.Lookup(string type) Line 764	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.Evaluator.CustomizedEvaluatorLookup.AnonymousMethod__0(string name) Line 456	C#
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionEngine.ExpressionTransformer.MakeExpression(string type, Microsoft.Bot.Expressions.Expression[] children) Line 198	C#
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionEngine.ExpressionTransformer.VisitFuncInvokeExp(Microsoft.Bot.Expressions.ExpressionParser.FuncInvokeExpContext context) Line 105	C#
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionParser.FuncInvokeExpContext.Accept<Microsoft.Bot.Expressions.Expression>(Antlr4.Runtime.Tree.IParseTreeVisitor<Microsoft.Bot.Expressions.Expression> visitor) Line 586	C#
 	Antlr4.Runtime.dll!Antlr4.Runtime.Tree.AbstractParseTreeVisitor<Microsoft.Bot.Expressions.Expression>.VisitChildren(Antlr4.Runtime.Tree.IRuleNode node)	Unknown
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionBaseVisitor<Microsoft.Bot.Expressions.Expression>.VisitPrimaryExp(Microsoft.Bot.Expressions.ExpressionParser.PrimaryExpContext context) Line 72	C#
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionParser.PrimaryExpContext.Accept<Microsoft.Bot.Expressions.Expression>(Antlr4.Runtime.Tree.IParseTreeVisitor<Microsoft.Bot.Expressions.Expression> visitor) Line 221	C#
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionEngine.ExpressionTransformer.Transform(Antlr4.Runtime.Tree.IParseTree context) Line 76	C#
 	Microsoft.Bot.Expressions.dll!Microsoft.Bot.Expressions.ExpressionEngine.Parse(string expression) Line 51	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.StaticChecker.CheckExpression(string exp, Antlr4.Runtime.ParserRuleContext context) Line 383	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.StaticChecker.VisitNormalTemplateString(Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalTemplateStringContext context) Line 362	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalTemplateStringContext.Accept<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>>(Antlr4.Runtime.Tree.IParseTreeVisitor<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>> visitor) Line 1638	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.StaticChecker.VisitNormalTemplateBody(Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalTemplateBodyContext context) Line 140	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalTemplateBodyContext.Accept<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>>(Antlr4.Runtime.Tree.IParseTreeVisitor<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>> visitor) Line 1500	C#
 	Antlr4.Runtime.dll!Antlr4.Runtime.Tree.AbstractParseTreeVisitor<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>>.VisitChildren(Antlr4.Runtime.Tree.IRuleNode node)	Unknown
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.LGFileParserBaseVisitor<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>>.VisitNormalBody(Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalBodyContext context) Line 48	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.NormalBodyContext.Accept<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>>(Antlr4.Runtime.Tree.IParseTreeVisitor<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>> visitor) Line 742	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.StaticChecker.VisitTemplateDefinition(Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.TemplateDefinitionContext context) Line 118	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.LGFileParser.TemplateDefinitionContext.Accept<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>>(Antlr4.Runtime.Tree.IParseTreeVisitor<System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.Diagnostic>> visitor) Line 369	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.StaticChecker.Check.AnonymousMethod__0(Microsoft.Bot.Builder.LanguageGeneration.LGTemplate t) Line 71	C#
 	System.Private.CoreLib.dll!System.Collections.Generic.List<Microsoft.Bot.Builder.LanguageGeneration.LGTemplate>.ForEach(System.Action<Microsoft.Bot.Builder.LanguageGeneration.LGTemplate> action)	Unknown
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.StaticChecker.Check() Line 69	C#
 	Microsoft.Bot.Builder.LanguageGeneration.dll!Microsoft.Bot.Builder.LanguageGeneration.LGParser.ParseText(string content, string id, Microsoft.Bot.Builder.LanguageGeneration.ImportResolverDelegate importResolver) Line 59	C#
 	Microsoft.Bot.Expressions.Properties.dll!Microsoft.Bot.Expressions.Properties.Extensions.Evaluate(Microsoft.Bot.Builder.LanguageGeneration.LGFile lgFile, string inlineStr, object scope) Line 41	C#
...
`
 	
[bug]

**Comment by boydc2014** [comment]
Thanks Chris, the issue here is not exactly "throwing exceptions when loading lg files", this is somehow a by design behavior to tolerance some exception, when we do the performance tuning. Let me explain. 

* This exception is happening in evaluation time, not in loading time (otherwise we will not start the bot). 
* This is exception is happened because we didn't pass the whole text to the parser for performance reason, so the parse don't know that AskName exist. Then since we know we didn't pass the whole text to parser, so we swallow a few exceptions like this.
* This is definitely not a pretty design, we will do a fix, by passing the parser some information of the pre-parsed information, so that the parse would correctly work, and the parser don't really parse the whole text again. 

Mark this as P1 now so that people won't get panic.

**Comment by boydc2014** [comment]
Fixed in #3387. 

No more exceptions in Expression library, but i do see a few exceptions for dictionaries


> Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in System.Collections.Concurrent.dll
> Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in System.Collections.Concurrent.dll
> Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in System.Collections.Concurrent.dll
> Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in System.Collections.Concurrent.dll
> testhost Information: 0 : Executing Dialog: AdaptiveDialog Rule[26]: OnBeginDialog: ((turn.dialogEvent.name == 'beginDialog') && True)
> testhost Information: 0 : Executing Dialog: AdaptiveDialog Rule[4]: OnEndOfActions: ((turn.dialogEvent.name == 'endOfActions') && !($Name))
> testhost Information: 0 : User1 [message] hi!

Is this expected @chrimc62 ?
