### ISSUE TITLE
[LG] Best practice for mismatch Text and Speak in activity template

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3354]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Sometimes, Text and speak are mismatch. For example, speak could have decorating SSML tags or could be a summary of long text.
Then the following approach will not work:
```
# SomeResponse
[Activity
  Text = @{Text()}
  Speak = @{Text()}
]
```

**Describe the solution you'd like**
Have discussed with @Danieladu and end up with following solutions:
1 use split
```
# textAndSpeak
- good&it is good
- bad&it is bad
# template
[Activity
  text = @{first(split(textAndSpeak(), '&'))}
  speak =@{last(split(textAndSpeak(),'&'))}
]
```
2 use array
```
# textAndSpeak
- @{createArray('good','it is good')}
- @{createArray('bad','it is bad')}
# template
[Activity
  text = @{textAndSpeak()[0]}
  speak =@{textAndSpeak()[1]}
]
```
3 use another activity function
```
# ActivityOutput
[  Activity 
    @{ActivityTextSpeak()}
    SuggestedActions = yes | no
]
# ActivityTextSpeak
- @{activity('1','1')}
- @{activity('2','2')}
- @{activity('3')}
# activity(text, speak)
[Activity
 Text = @{if(text == null, text, '')}
 Speak = @{if(speak == null, speak, '')}
]
```
Could we come up with better solution? Thanks
[enhancement]

**Comment by vishwacsena** [comment]
In cases where the speak .vs. dispaly is different, user should just inline the difference or use different templates. Recommendation is to use partial activity and compose using that.

**Comment by xieofxie** [comment]
@vishwacsena So I should use this? Thanks
```
# ActivityOutput
[  Activity 
    @{ActivityTextSpeak()}
    SuggestedActions = yes | no
]

# ActivityTextSpeak
- @{ActivityTextSpeak1()}
- @{ActivityTextSpeak2()}

# ActivityTextSpeak1
[Activity
 Text = 1
 Speak = 1 is 1
]

# ActivityTextSpeak2
[Activity
 Text = 2
 Speak = 2
]
```

**Comment by vishwacsena** [comment]
@xieofxie yes. you can also do this

```
# ActivityOutput
[  Activity 
    Text = 1
    @{ActivitySpeak1()}
    SuggestedActions = yes | no
]

# ActivitySpeak1
[Activity
 Speak = 1 is 1
]
```
