### ISSUE TITLE
LG files should interpret newlines as double newlines

### ISSUE THREAD

**Issue by dandriscoll** [microsoft/botbuilder-dotnet#3364]
**Is your feature request related to a problem? Please describe.**
LG files are based on markdown, but prohibit spanning text with a single line. For example,

```
# Label
- This is valid
- This is
  not valid
```

LG renders into Markdown, and Markdown itself requires two lines to create a newline. So when I want to include newlines in output, I have to triple-quote it AND put double newlines in.

Imagine I want this output:
```
First line
Second line
Third line
```

To achieve that, I have to do:
```
# Label
- '''First line

Second line

Third line
'''
```

Having one or two of these in an LG file is ugly but an entire file full of it is unbearable. This design currently gives me the worst of both worlds: I have to live with long lines in non-quoted LG, and I have to live with double newlines in quoted LG.

**Describe the solution you'd like**
I'd like LG to turn inline newlines into double newlines in the output. The above example would become:
```
# Label
- '''First line
Second line
Third line
'''
```

[enhancement]

**Comment by vishwacsena** [comment]
We should verify this is not an issue with LG. I vaguely remember an issue with webchat 
(and hence emulator) dropping empty lines in markdown. 

@boydc2014

**Comment by dandriscoll** [comment]
I observed this behavior on SMS. Most of our channels implement the standard Markdown newline processing logic which requires two newlines to result in a single result newline. This is because Markdown allows you to use a single newline to break up long lines.

The reason I bring LG up is that it's a dialect of Markdown that prohibits newlines to break up long lines. Therefore, requiring two newlines seems like overkill.

**Comment by vishwacsena** [comment]
Thanks. We should then do this in ActivityFactory and not in LG. @boydc2014?

**Comment by vishwacsena** [comment]
Discussed in triage. Let's provide a function to put user in control so we do not inject additional line breaks where the user might not want that.

**Comment by boydc2014** [comment]
After thinking about this for a while, a functions seems to be inconvenient, bc you have to include it everywhere, my recommendation would be add an option to lg file indicate lineBreakStyle to make this happen.  See #3646

**Comment by cleemullins** [comment]
@vishwacsena, this is a P1 bug with no forward progress for 2+ months. How can we drive this forward?

**Comment by boydc2014** [comment]
tracked via #3646
