### ISSUE TITLE
Test ShowTyping_TestMiddleware_Context_Completes_Before_Typing_Interval is bad.

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-dotnet#3371]
The test ShowTyping_TestMiddleware_Context_Completes_Before_Typing_Interval is unstable and intermittently fails.

Example: In this build, the test fails in the debug build and succeeds in the release build: https://fuselabs.visualstudio.com/SDK_Public/_build/results?buildId=105006&view=results

**Comment by garypretty** [comment]
Yes, I saw this last week. I had some builds failing consistently.  I merged from master and subsequently the build passed, but I don't see any changes to anything that would affect that.

**Comment by BruceHaley** [comment]
Seems OK now. Closing the issue.
