### ISSUE TITLE
QnAMakerDialog should support passed-in text instead of only Activty.Text

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botbuilder-dotnet#3374]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
When the incoming activity into a bot does not include the text to be sent to a QnAMakerDialog, there is not a good way to pass this in as a parameter. QnAMakerDialog ONLY works with Message activities where the question is the Text property.

**Describe the solution you'd like**
I would like the text to send to QnAMakerDialog to start it to be passed in as part of the options, instead of only looking.

Also, the need for the Activity to be a Message type could also then be removed (i.e. if I wanted to call QnAMakerDialog after an OAuthPrompt, there would be an event activity in the TurnContext.

**Describe alternatives you've considered**
Currently i have to change the type of Activity and set the Text property of the Activity used by the TurnContext.

[enhancement]

**Comment by mrivera-ms** [comment]
Triaged by development team. This will, likely, need a rewrite. Reference: https://github.com/microsoft/botframework-sdk/issues/5851
