### ISSUE TITLE
Skills + OAuth + Conversation IDs: Populate RelatesTo field with root conversation reference and pass to token service

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#3377]

**Comment by cleemullins** [comment]
Note: This is alternate to the microformat. @johnatyalor is lobbying for the Microformat while listning to Band on the Run.

**Comment by cleemullins** [comment]
This is a P0 to enable SSO Auth work. Relabeling as P0.

**Comment by carlosscastro** [comment]
Done as part of #3360
