### ISSUE TITLE
ChannelServiceController can't deserialize into Activity consistently 

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#3380]
If the activity has an attachment (hero card for example) the auto-serialization that happens into the activity corrupts the Content property of the Activity. To fix you can do the following:

`string b = await (new StreamReader(Request.Body)).ReadToEndAsync();`

**Comment by gabog** [comment]
Are you seeing this in a .Net Core 2.1 or 3.1 project?

**Comment by Virtual-Josh** [comment]
It's 3.1

**Comment by gabog** [comment]
Do you have .AddNewtonsoftJson() when registering the controllers in Startup.cs? (you will need to add the Microsoft.AspNetCore.Mvc.NewtonsoftJson nuget to the solution)

![image](https://user-images.githubusercontent.com/12264946/74365086-6059f800-4d9b-11ea-972f-e6ae0ad1c92f.png)

We also fixed some other issues with 3.1 compat in R8, can you try referencing the nightly build and let me know if it still fails?

**Comment by cleemullins** [comment]
@virtual-josh, can you confirm this fixes the issue you were seeing? We believe this is a Samples issue as part of @garypretty is updating to .Net Core 3.1?

**Comment by garypretty** [comment]
You could also check the 3.1 samples branch I have open right now. They have all been updated so you should be able to test the sample straight from there if needed.

**Comment by cleemullins** [comment]
@virtual-josh, can you confirm this fixes the issue? If so, please make sure the P0 set of Sample Updates we have in flight takes this change? (@garypretty is driving that set of changes)

**Comment by cleemullins** [comment]
https://github.com/microsoft/BotBuilder-Samples/issues/2189

**Comment by Virtual-Josh** [comment]
It doesn't fix it. I still get a `Sorry, it looks like something went wrong.` message from the bot.

**Comment by garypretty** [comment]
@Virtual-Josh What version of the integration libs are you using?  They have been updated for 3.1 compatibility. 

Can you try the skill samples on the working 3.1 samples branch here -> https://github.com/microsoft/BotBuilder-Samples/tree/gary/net-core-3-1/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot

I just confirmed I was able to run the root and skill bots and send an attachment (HeroCard) from the skill bot back to the parent via the SkillController (which extends ChannelServiceController). These samples are using Microsoft.Bot.Builder.Integration.AspNet.Core v4.8.0-preview-200129-102278 (anything later than that should be good).

**Comment by garypretty** [comment]
@Virtual-Josh What version of the integration libs are you using?  They have been updated for 3.1 compatibility. 

Can you try the skill samples on the working 3.1 samples branch here -> https://github.com/microsoft/BotBuilder-Samples/tree/gary/net-core-3-1/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot

I just confirmed I was able to run the root and skill bots and send an attachment (HeroCard) from the skill bot back to the parent via the SkillController (which extends ChannelServiceController). These samples are using Microsoft.Bot.Builder.Integration.AspNet.Core v4.8.0-preview-200129-102278 (anything later than that should be good).

**Comment by Virtual-Josh** [comment]
As a small update it seems as if the core problem is in the translation between integration libraries between 4.8-preview and current. I'm able to get hero cards to come across, as intended when everything is using all 4.7 stuff (what I've been working with), or all 4.8 preview (the skill bot sample). 

While I've found a way to set serialization properties, I haven't been able to resolve the xcompat yet. I have a few other things to try before I'm out of avenues to pursue.

**Comment by Virtual-Josh** [comment]
I was able to fix the issue. A combination of adding the `.AddNewtonsoft()` in the `startup.cs` as well as updating the serialization settings parameters on the `JsonResult` callback to the bot fixed the issue.
