### ISSUE TITLE
Roll back DialogManager breaking change of stack property from "DialogState" to "_dialogs"

### ISSUE THREAD

**Issue by dandriscoll** [microsoft/botbuilder-dotnet#3393]
Issue is in DialogManager.cs#24

## Version
4.7.0

## Describe the bug
DialogManager uses a different property name for the dialog stack than the old DialogState system. DialogManager uses "_dialog" while the existing code uses "DialogState."

Preserving the existing name is important to:
1. Prevent breaking conversations when upgrading to DialogManager, which is largely a prerequisite for Adaptive
2. Handling custom-written proactive code, which may directly reference the property name
3. Not break when using multiple versions of the bot concurrently (i.e. dev box and cloud test box on same state)
4. Avoid creating a giant orphaned stack object that will never be cleaned up

[bug]

**Comment by tomlm** [comment]
Hm. the dialogmanager is preview lib, and so we know that we are making breaking changes.

**Comment by dandriscoll** [comment]
This is the issue we discussed last week -- the current preview library breaks compatibility with the existing ~v4.4 dialog system.

You're correct that this bug only needs to be fixed by the time DialogManager exits preview.
