### ISSUE TITLE
Microsoft Teams: Bot Framework + Application Insights with CreateConversationAsync causes null exception?

### ISSUE THREAD

**Issue by msftjayongg** [microsoft/botbuilder-dotnet#3395]
## Version
4.7.2

## Describe the bug
TelemetryInitializerMiddleware causes null exceptions when calling CreateConversationAsync.

## To Reproduce
Steps to reproduce the behavior (I was on MS Teams but unsure if this is necessary):
Create an AdapterWithErrorHandler inheriting from BotFrameworkHttpAdapter that "Use(middleware)" where middleware is of type TelemetryInitializerMiddleware.

call the method adapter.CreateConversationAsync()

null exception occurs.

## Expected behavior
No null exception, and logging to still occur.

## Additional context
CreateConversationAsync creates an Event activity, as per this code snippet:
![image](https://user-images.githubusercontent.com/47937276/74583812-d74fe600-4f7f-11ea-842b-d2032dd977d6.png)

This code never sets the "From" field, which is used by TelemetryLoggerMiddleware here:
![image](https://user-images.githubusercontent.com/47937276/74583816-f189c400-4f7f-11ea-8b14-8ae1bf338445.png)

This causes a null exception.

If you truly have a proactive message that fires outside of an http call, then, in OnTurnAsync, it tries to access httpContext?.Items.ContainsKey, but since httpContext is null, this also throws a null exception.

I had to work around these issues by create another middleware invoked before the TelemetryInitializerMiddleware, which ensures that those fields are non-null.

**Comment by dmvtech** [comment]
Agreed this looks like a bug. Looking into solutions.
