### ISSUE TITLE
Expressions should include flatten function

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3398]
There is currently no way in the expression language to flatten arrays into primitive values.  Union can do this for a static number of expressions, but can't do it across a computed sets of arrays.  What is needed is to be able to do flatten([[1, 2, 3], [4, [5], 6]]) -> [1, 2, 3, 4, 5, 6].

[enhancement]

**Comment by Danieladu** [comment]
fixed by #3470
