### ISSUE TITLE
Add support for "invoke" activity to adapter

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#34]
We need to support "invoke" activities which are complex because the protocol changes such that we need to send an HTTP StatusCode and Body in response to the received "invoke" activity. To do that we need to somehow get that code and body down to the connector while it holds open the response object.

The idea we've come up with is to add a new "result" or "invoke-result" activity type (we can discuss name more) that is a fake activity much like the "delay" activity. This activity will contain the StatusCode & Body the bot would like to return and when the connector receives this activity in it's post() method it will store it in a table keyed by channelId+activityId. Then when the request naturally unwinds the connector can retrieve the result from the table and complete the response.

This feature is used by payments and heavily used by Teams so we need it before //build.

**Comment by cleemullins** [comment]
Fixed in #394
