### ISSUE TITLE
Add 'role' & 'tenantId` to teamsChannelAccount

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#3405]
In the Teams channel the data returned from all get members APIs is changing to include the user role (guest, owner, user) and tenant Id. We should add this property to the appropriate objects and make sure it is assigned.

**Comment by cleemullins** [comment]
@clearab, Has teams shipped this? If so, can we assign to one of our engineers to make the enhancement? @mdrichardson is a good candidate to drive this across the platform.

**Comment by clearab** [comment]
We need to coordinate with Teams on renaming this. "role" is already taken and defined. Moving to R10.

**Comment by cleemullins** [comment]
@clearab I don't quite understand this Issue. Is it R9 or R10?
