### ISSUE TITLE
Cleanup onTeamsMembersAdded event

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#3406]
With the changes to the data returned from the get members API, we should audit/cleanup our augmentation of the onTeamsMembersAdded event. The additional call to get more information about the user who was added is probably extraneous now. At a minimum we should switch to the get single member endpoint outlined [here](https://github.com/microsoft/botframework-sdk/issues/5714)

[enhancement]

**Comment by cleemullins** [comment]
@clearab, this is a self-assigned issue from 2 months ago. How can we push this forward?

**Comment by clearab** [comment]
@cleemullins I think this makes sense as an R10 Issue.

**Comment by clearab** [comment]
Closing as duplicate
