### ISSUE TITLE
[LG] from assembly for [import], fromfile etc.

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3407]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

From assembly will help in the following:
* When I am writing an SDK, these lg files must be embedded in dll itself
* When I don't need hot update, it will be faster from assembly 

**Describe the solution you'd like**

* Add an option in SDK
* Add an option in function
* Add new grammar/function

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by boydc2014** [comment]
@xieofxie can you clarify the requirement, did you mean compile the lgfiles in dlls?

**Comment by xieofxie** [comment]
@boydc2014 Right. When I want to use lg embedded in an dll, how to handle the import fromFile etc.?

**Comment by cleemullins** [comment]
@vishwacsena This is a P1 bug that's been sitting for 2 months. How can we push this forward?

**Comment by boydc2014** [comment]
@cleemullins  this is not a bug, this is a feature requirement, and customer is asking about directly supported the interface to deal with Assembly. As a core library, I don't think it's the library's concern of where the files actually stores. And we've already provided generic approach through delegate for user to implement on there customized storage.

So I would suggest @xieofxie to read out the file from Assembly and feed into LGParser.ParseText method, in terms of import, the last parameter in LGParser.ParseText is "importResolver" you can also customize the way import is been handled.

**Comment by xieofxie** [comment]
@boydc2014 could we customize/override fromFile? Thanks

**Comment by boydc2014** [comment]
> @boydc2014 could we customize/override fromFile? Thanks

fromFile is just a function, you can create own customize function like fromMyFile, see LG tests `TestForCustomizedFunctions` for example, but it's not recommended to override existing pre-built function.

**Comment by boydc2014** [comment]
> > @boydc2014 could we customize/override fromFile? Thanks
> 
> fromFile is not a build-in mechanism, it's just a function like any other functions, we support create customize function like fromMyFile, see LG tests `TestForCustomizedFunctions` for example, but it's not recommended to override existing pre-built function (which is also doable via override Expression.Functions table).

@xieofxie will this help?

**Comment by xieofxie** [comment]
> > > @boydc2014 could we customize/override fromFile? Thanks
> > 
> > 
> > fromFile is not a build-in mechanism, it's just a function like any other functions, we support create customize function like fromMyFile, see LG tests `TestForCustomizedFunctions` for example, but it's not recommended to override existing pre-built function (which is also doable via override Expression.Functions table).
> 
> @xieofxie will this help?

Got it, thanks~
