### ISSUE TITLE
Onboard to .Net Dependency Graph Generator

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#3413]
The new [Azure .Net SDK](https://github.com/heaths/azure-sdk-for-net) uses a very nice dependency generator and graph. They have it surfaced via Build Badges. 

You can see it [in action here](https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-net/dependencies/InterdependencyGraph.html).

**Comment by EricDahlvang** [comment]
https://botbuildersdkartifacts.blob.core.windows.net/dependencies/InterdependencyGraph.html
