### ISSUE TITLE
Dialog file in .cs format

### ISSUE THREAD

**Issue by deenaMaistering** [microsoft/botbuilder-dotnet#3424]
Using Bot Framework Composer has made creating dialogs much easier. Can we get the dialog files generated by the bot framework composer in an Adaptive Dialog format in .cs file? Right now we get it in the form of .dialog and .lu files.

**Comment by vishwacsena** [comment]
Unclear what's needed here from SDK side. Pinged cwhitten for details.

**Comment by vishwacsena** [comment]
No plans right now to support this - 
1. Round tripping generated code is non trivial
2. This would require every single concept available through code based adaptive dialog also be available through UX. 

@deenaMaistering can you clarify if you are looking for an 'export to CS' option in composer .vs. 'serialize to CS' option? The later is not possible. If you are looking for a one-way export operation, it would be good to track that via a separate ticket.
