### ISSUE TITLE
CodeAction ends dialog (in 4.8-preview)

### ISSUE THREAD

**Issue by ruslanmozhaev** [microsoft/botbuilder-dotnet#3432]
Hello!
I'm currently trying out Adaptive dialog with Luis (in 4.7-preview) and was adding QnA maker so that I can use them both in dialog. I've found out that integration with it is still in progress and decided to try the latest 4.8 preview to check it out. (But maybe I've missed how it should be done in 4.7-preview version?)
After implementing required changes to recognizers and LG I've found out that CodeAction is now ending the dialog, bug description below.

### Version
4.8.0-preview-200224-108035

### Describe the bug
After CodeAction completes, the current dialog is ended (endOfActions) even though there are plenty of actions after the CodeAction. 
The CodeAction can be empty and just return DialogTurnResult. 
The DialogTurnStatus of the result does not matter - same behavior with .Complete or .Cancelled.

### To Reproduce
1 create adaptive dialog with CodeAction between other actions
2 try dialog with emulator

### Expected behavior
CodeAction returns control to the dialog and next actions are executed

I'm aware that 4.8 preview is not yet ready, but maybe this bug report will be of use.
[preview issue]

**Comment by vishwacsena** [comment]
@ruslanmozhaev, with 4.8.xx bits, you need to end the codeAction dialog from within it for the conversation to move forward. 

**Old:** 
```C# 
private async Task<DialogTurnResult> testCodeAction(DialogContext dc, System.Object options)
{
    await dc.Context.SendActivityAsync("Within code action");
    return new DialogTurnResult(DialogTurnStatus.Complete, options);
}
```

**New:** 
```C#
private async Task<DialogTurnResult> testCodeAction(DialogContext dc, System.Object options)
{
    await dc.Context.SendActivityAsync("Within code action");
    return await dc.EndDialogAsync();
}
```

This will be documented as breaking change when we ship 4.8.xxx to NuGet.

**Comment by ruslanmozhaev** [comment]
thank you!
