### ISSUE TITLE
Rename TeamsWorkaround middleware to a better name

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#3438]
Having a 'workaround' in middleware makes customers feel like they are using patched code. Please, lets rename this builtin middleware to a name that doesn't convey that.

**Comment by johnataylor** [comment]
This is purely internal cleanup.

Besides which there is little point in renaming this (agreed this is an unfortunate name, albeit an accurate name) ultimately this will be deleted.

Lowering the priority as this is strictly an internal class (in fact an internal member class of another class) and we are in the process of investigating whether it is even still required.

**Comment by clearab** [comment]
Added an item to cleanup this all-up, there's more here than just this class. https://github.com/microsoft/botframework-sdk/issues/5822
