### ISSUE TITLE
Microsoft Teams: Bot Framework + Application Insights proactive messages cause null exception

### ISSUE THREAD

**Issue by msftjayongg** [microsoft/botbuilder-dotnet#3442]
## Version
4.7.2

## Describe the bug
TelemetryInitializerMiddleware.OnTurnAsync() causes null exceptions when there is no httpContext.

## To Reproduce
1. Create an AdapterWithErrorHandler inheriting from BotFrameworkHttpAdapter that "Use(middleware)" where middleware is of type TelemetryInitializerMiddleware.
2. Send a proactive message (i.e. there is no HttpContext).

Observe there is a null exception in TelemetryInitializerMiddleware.OnTurnAsync().

## Expected behavior
No null exception, message goes through

## Screenshots
![image](https://user-images.githubusercontent.com/47937276/75302040-7d59e680-57f1-11ea-92b9-87b5541e09f7.png)

Please see the code here in TelemetryInitializerMiddleware.cs.  Note that if httpContext is null, then items is null.  You then call items.ContainsKey, which results in a null exception. Proposed fix is to use items?.ContainsKey (if that works), or do a null check for items.  The check for "items != null" is used in other parts of the repo. e.g. in TelemetryBotIdInitializer.Initialize()., so this is a pattern that exists.

## Additional context
I had to work around these issues by create another middleware invoked before the TelemetryInitializerMiddleware, which ensures that those fields are non-null.

[bug]

**Comment by msftjayongg** [comment]
This is related, but not the same, as issue 3395.

**Comment by msftjayongg** [comment]
@clearab FYI

**Comment by mdrichardson** [comment]
@msftjayongg Good catch. I caught part of this in [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/3436), but it looks like I missed one. I'll work up a PR for it, now.
