### ISSUE TITLE
API naming review for LG & Expression

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3443]
API naming revisit for LG & Expression since it's going to RC. 

Meeting notes from LG sync up:

### LG 
- [ ] rename LGFile class to LG
- [ ] rename SimpleMultipleLanguageGenerator to MultiLanguageLG
     - [ ] move MultiLanguageLG to LG package 
     - [ ] MultiLanguageLG will not implement IGenerator
     - [ ] update the interface to accept a locale instead of turnContext so that it don't depends on bot.builder package
     - [ ] implement a default fallback policy (en-us => en => "")
- [ ] move ActivityFactory into MessageFactory with a new method `FromObject`
     - [ ] Message/ActivityFactory will not depends on LG package
- [ ] rename EvaluateTemplate method to Evaluate
    - [ ] rename Evaluate method to EvaluateText
- [x] let LGParser accept an expressionEngine

### Expression
- [x] rename ExpressionEngine to ExpressionParser (hint: rename Expresion.g4 with ExpressionAntlr.g4 to avoid conflict)
- [x] (NOT VALID ANYMORE) move expression builder functions out of expression class itself

### others

**Comment by Danieladu** [comment]
name `EvaluateText` would be confused with `evaluate string content`.

**Comment by boydc2014** [comment]
> name `EvaluateText` would be confused with `evaluate LG file string content`.

I was actually very interested at options 3, we could possible do the evaluation natively in expression, by have LG evaluator only inject functions and form a customized expression engine, do you think that's possible?

**Comment by Danieladu** [comment]
> > name `EvaluateText` would be confused with `evaluate LG file string content`.
> 
> I was actually very interested at options 3, we could possible do the evaluation natively in expression, by have LG evaluator only inject functions and form a customized expression engine, do you think that's possible?

Agree with this proposal. So we can put all expression/escape recognization work into expression library.

**Comment by vishwacsena** [comment]
Tagging P0 since this will be a breaking change and require RC2 if not done for R8.

**Comment by Kaiqb** [comment]
@tomlm - this is waiting a review from you per @vishwacsena

**Comment by cleemullins** [comment]
spoke with @tomlm, and:

> yeah, we met, decided on anew names and I'm applying them right now
> probably an hour or so out, unless I run into issues
