### ISSUE TITLE
Change to ActivityHandler breaks TeamsActivityHandler

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#3446]
Either the code in ActivityHandler for invoke should be moved to TeamsActivityHandler which already at least partially covers this scenario. (i.e haandles "signin/verifyState")

Or the TeamsActivityHandler should overrride OnInvokeAsync.

Assuming the new code in ActivityHandler is actually Teams specific the new code in ActivityHandler seems unnecessary or at least should be a minor change in the TeamsActivityHandler.

(Its hard to see who made this change as its attributed to a bot. Presumably that can be resolved.)

**Comment by johnataylor** [comment]
Also need to see if the JavaScript has similar problems.

Incidentally this did cause compiler warnings which were not caught by our build system.

**Comment by Kaiqb** [comment]
@johntaylor - who should this be assigned to?

**Comment by EricDahlvang** [comment]
Is this referring to the sso changes from @Jeffders ?
