### ISSUE TITLE
Rename $role union/union(type) to interface/interface(type)

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3459]
This will make the meaning of these $role tags much clearer.  This requires changes to the SDK schema definitions and bf dialog:merge, but should be transparent to the rest of the stack since it is only used to put together the app.schema.

[enhancement]

**Comment by tomlm** [comment]
**Today**
Declaring a componentization point looks like this
**Microsoft.IDialog.schema**
```
{
    "$role": "union",
   ....
}
```
Declaring implementation of a component 
**Microsoft.Foo.schema**
```
{  
   "$role":"union(Microsoft.IDialog)"
   ...
}
```

**After DCR**
Declaring a componentization point looks like this
**Microsoft.IDialog.schema**
```
{
    "$role": "interface",
   ....
}
```
Declaring an implementation of a IDialog
**Microsoft.Foo.schema**
```
{  
   "$role":"implements(Microsoft.IDialog)"
   ...
}
```
