### ISSUE TITLE
DialogClass and Class memory scopes don't evaluate expressions

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#3460]
## Version
4.8 nighlties

## Describe the bug
When we added dialogclass and class scopes we didn't have expression properties.  Now that we have formalized expression properties, we don't have a way from the memory scope to do the evaluation of the expressions to get the actual configuration.

## Expected behavior
If I have a class with an expressionProperty on it, the memory scope shows the evaluated value for the property.
{
    BoolExpression IsVip {get;set;}
}

The memory scope for this should be able to be "class.IsVip" to get the actual value of IsVIP

[bug]

**Comment by Kaiqb** [comment]
merged
