### ISSUE TITLE
Expressions should include unique function to remove duplicates from collection

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3462]
Currently there is no easy way to get a unique collection of values.  unique would remove all duplicates from an array.

[enhancement]

**Comment by chrimc62** [comment]
This has been implemented in JS, but is still needed for node.

**Comment by chrimc62** [comment]
This is checked into js, but needs to move to c#.

**Comment by vishwacsena** [comment]
@chrimc62 can you add the JS PR so we can keep track?
