### ISSUE TITLE
Expression - improvements

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3466]
- [x] Today we have both `Array` and `CreateArray`. We should just do `CreateArray` and drop support for `Array` prebuilt function
- [ ] Support multi-line function definition. Writing long expressions as single line is hard, we should support multi-line parsing for expressions
```
<expression> ||
  <expreession2>
```

```
# template
- IF : ${<EXP> ||
                 <EXP2>}
...
```
- [x] Add prebuilt functions for type checking. isString, isArray, isObject, isInt, isDateTime, isFloat, isBool

**Comment by cosmicshuai** [comment]
For multil-line function definition. Do we need also support & and && operations? @vishwacsena

**Comment by vishwacsena** [comment]
Yes.
