### ISSUE TITLE
Namespace should be Microsoft.BotBuilder

### ISSUE THREAD

**Issue by GeekTrainer** [Microsoft/botbuilder-dotnet#348]
Maybe it's just me, but I feel it would be clearer if the namespace was BotBuilder, rather than Bot.Builder. The latter just seems clunky, and confusing.

Is there another set of objects for just Bot? Are we able to create Bots using another sub-namespace? Microsoft.Bot.Builder makes it a bit confusing.

**Comment by vishwacsena** [comment]
By design.

**Comment by GeekTrainer** [comment]
Can you please elaborate? This doesn't actually address the concern.

**Comment by GeekTrainer** [comment]
@vishwacsena Can you please elaborate? This doesn't actually answer my question.
