### ISSUE TITLE
Unclear whether IStatePropertyAccessor<T>.GetAsync should throw a MissingMemberException

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#3488]
## Version
master branch

## Describe the bug
A `MissingMemberException` is mentioned in the doc comments for [`IStatePropertyAccessor<T>.GetAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/IStatePropertyAccessor.cs#L23) and [`BotStatePropertyAccessor<T>.GetAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotState.cs#L409), but no such exception can possibly be thrown from the code. `GetAsync` simply returns the default value for the type when no default value factory is supplied, so no exception is thrown at all. This is either a documentation bug (meaning the documentation should be changed to not say it throws a `MissingMemberException`) or a bug in the code (meaning it should actually throw a `MissingMemberException`).

[bug]

**Comment by EricDahlvang** [comment]
@v-kydela said he will do some research on this, to ensure MissingMemberException is no longer thrown (which is what it looks at first glance)

**Comment by v-kydela** [comment]
@johnataylor edited `BotStatePropertyAccessor<T>.GetAsync` to not throw a `MissingMemberException` on January 29, 2019: https://github.com/microsoft/botbuilder-dotnet/pull/1330

However, the reference to `MissingMemberException` was never removed from the doc comment for `BotStatePropertyAccessor<T>.GetAsync` so @JonathanFingold edited the doc comment for `IStatePropertyAccessor<T>.GetAsync` to also include `MissingMemberException` on February 7, 2020: https://github.com/microsoft/botbuilder-dotnet/pull/3349

I believe the exception should be removed from both comments.

**Comment by JonathanFingold** [comment]
The comments for the `IStatePropertyAccessor<T>` interface methods should describe the contract. If the intent is for all implementors to throw this exception, then the `<exception>` should stay in the comments and there's an error in the implementation. Otherwise, the comments are out of sync and the `<exception>` should be removed.

**Comment by v-kydela** [comment]
If the intent was for all implementors to throw that exception, why would @johnataylor have removed the exception from the implementation?

**Comment by EricDahlvang** [comment]
It looks like the comments are out of sync.
