### ISSUE TITLE
AddBotAuthentication is gone - need info on what's required to publish to azure bot service or in general

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#349]
Because the new SDK is .NET Core, need info on how to start from the HelloWorld bot and publish it.

i.e. what are the best practices/what files to add to the bot to publish it as a Web App Bot

I see https://github.com/Microsoft/botbuilder-dotnet/pull/67 that there were some changes to how Auth happens , but now that library is gone.

Unable to repro a scenario where registering the AppId/Password with the bot works. Any help would be appreciated

**Comment by amthomas46** [comment]
I see https://github.com/Microsoft/botbuilder-dotnet/pull/67 that there were some changes to how Auth happens

**Comment by RamjotSingh** [comment]
Depending on which integration (or no integration) you have chosen the options are different 

1) ASPNetCore - BotFrameworkOptions under Microsoft.Bot.Builder.Integration.AspNet.Core has ICredentialProvider. If you have BotId and BotPassword use SimpleCredentialProvider
2) ASP.Net (Legacy WebAPI) - Similar to 1) just in Microsoft.Bot.Builder.Integration.AspNet.WebApi
3) No integration - You can pass Credential provider directly while instantiating BotFrameworkAdapter or use DependencyInjection to auto fill it.

Hope this answers your question.

**Comment by amthomas46** [comment]
Thanks so much!! I was able to publish.

I still think it the different options and an explanation in the docs would be helpful!
