### ISSUE TITLE
BotFrameworkAdapter.BuildCredentialsAsync should support CertificateAppCredentials

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#3490]
Currently, it is complicated to use CertificateAppCredentials when using BotFrameworkAdapter and BotFrameworkHttpClient, both of which have a BuildCredentialsAsync, and needs to be overriden. 

Potentially, this could roll into a general refactor of the auth layer.

https://github.com/microsoft/botbuilder-dotnet/blob/b7ea3c09703b78fb9a9cc07cce11f7b96f10d8a2/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1397-L1404

**Comment by EricDahlvang** [comment]
We also need to document how to use CertificateAppCredentials

**Comment by carlosscastro** [comment]
ETA: 7/21

**Comment by carlosscastro** [comment]
We had a discussion on this, we might repupose this bug for some deeper work in R11. Re-labelling to R11, renaming the issue and updating the description accordingly.

In the meantime, https://github.com/microsoft/botbuilder-dotnet/issues/3759 has a description on how to do this right now, which is overriding this.

**Comment by carlosscastro** [comment]
We'll triage this for R12

**Comment by EricDahlvang** [comment]
This is partly addressed here:

https://github.com/microsoft/botbuilder-dotnet/pull/4972

how to use this should probably be documented.

**Comment by gabog** [comment]
We will not address this at the moment.
