### ISSUE TITLE
Support array and json syntax in expressions

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3493]
It would be nice if you could construct an array using bracket syntax or an object using json syntax.  Today to create an array you need to do:
createArray('a', 'b', 'c') -> ['a', 'b', c']
It would be nice to just support array syntax.  While the current is OK, nesting makes it much harder to read, i.e. createArray(createArray(1, 3), createArray(4, 5)) is much less clear than [[1, 3], [4, 5]].

Similarly for objects you need to do this:
json(`{"foo": ${val}, "blah": ${woof}}`) -> { foo: <val>, blah: <woof>}
it would be nice to support doing this:
{ foo: ${val}, blah: ${woof}} which is simpler and much less fiddly since you don't have to balance quotes on properties.

[enhancement]

**Comment by cosmicshuai** [comment]
@vishwacsena I have a question here. For creating an object using { foo: ${val}, blah: ${woof}} 
the key here is an identifier. Should we also support it a string type key, like user can write { "foo": ${val}, "blah": ${woof}}? The parsed results should be identical.

**Comment by vishwacsena** [comment]
@cosmicshuai yes

**Comment by boydc2014** [comment]
@chrimc62 just so you know, this feature is supported, but with a little difference than the original spec.

the way to define a object is simply
```
{ name: "John", age: 32}  or
{ "name: "John, "age": 32} or 
{ name: user.name}   // note, there is no $ before user.name, because this is not a string interpolation env

so 
json(`{"name": ${user.name}`) will work because string interpolation, but this can be written just as 
{name: user.name}
```
