### ISSUE TITLE
Expression.ToString() is incorrect.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#3498]
## Describe the bug
Expression.ToString() is used by JsonConverter to turn an Expression back into a string.  It has a bug that it doesn't create proper strings.  For example:
```json(`{'foo': '${hello}','item': '${world}'}`).foo,hello,) ```
generates incorrect escaping of quotes
```(replace("hello'", "'", '"'),hello",)```
generates incorrect escaping of quotes, 
etc.

## To Reproduce
This unit test fails in 14 places:
```
        [DataTestMethod]
        [DynamicData(nameof(Data))]
        public void Roundtrip(string input, object expected, HashSet<string> expectedRefs)
        {
            var parsed = Expression.Parse(input);
            var newExpression = Expression.Parse(parsed.ToString());

            Assert.AreEqual(parsed.ToString(), newExpression.ToString(), $"{input} should have round tripped as string");
        }
```

## Expected behavior
Expression x = "....";
Expression y = x.ToString(); // create new expression from previous expression
// string forms are the same for 2 expressions.
x.ToString() == y.ToString();

[bug]

**Comment by boydc2014** [comment]
Offline talked with Tom, We don't have to to exactly same string,  but we need to make sure at least the toString() result is re-parseable and generate same parseTree
