### ISSUE TITLE
add error message middleware

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#35]
This could be done as a sample versus an actual piece of middleware we ship but we need a piece of middleware that you install first in your bot and it listens for an error to be thrown and then simply sends a message to the user telling the something wen't wrong. Other middleware on the stack should have already processed/logged the error so this middleware is just about telling the user something happened. 

I think the general strategy we want for all middleware error wise is to handle the error and then re-throw it so someone else can handle it.

In JS I think this middleware looks like:

```
bot.use({
    contextCreated: (context, next) => {
        return new Promise((resolve, reject) => {
            next().then(
                () => { resolve() },
                (err) => {
                    context.responses.push({ type: 'message', text: `Oops... Something went wrong.`});
                    reject(err);
                }
            );
        });
    }
});
```

**Comment by cleemullins** [comment]
@Stevenic, is this something we need to keep a tracking issue around?

**Comment by garypretty** [comment]
I have written the c# version of this middleware.  Once the wider issue of middleware not currently being able to store its own conversation state (see #248), I will finish the last couple of bits.  I am working to reproduce the various bits of middleware @Stevenic has in his toybox in C# over at https://github.com/garypretty/botbuilder-dotnet-toybox. 
@cleemullins I do have some thoughts on how to handle middleware that we don't want to include in the main repo, so let's discuss that offline.

Not sure we need an issue open here as I have this on my radar.

**Comment by cleemullins** [comment]
Thanks Gary!
