### ISSUE TITLE
[LG] Refactoring Expander

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#3523]
Expander is out of date, it should catch up with Evaluator and the lastest feature of Templates.
including:
1. Support all kinds of LG functions
2. Discard the 'builtin.' prefix
3. Achieve the correct result for `foreach` expansion. ref: #3238
4. Escape issues, including double quotation, escape character
 example: 
```
# Template
[Activity
    Text = no "double quotes" allowed
]
```

expand Template would get an invalid json `{"lgType":"Activity","text":"no "double quotes" allowed"}`

5. Reduce duplicate code of `Evaluator`

6. Others...

**Comment by cleemullins** [comment]
@vishwacsena This is a P0 bug that's not moved forward in over a month. How do we push this forward?

**Comment by feich-ms** [comment]
Sorry for the delay. I will send out a PR to resolve this by the end of this week.
