### ISSUE TITLE
[Adaptive] Classes access survey/ cleanup

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3528]
Classes should be made internal if we don't want people to use them or depend on them.
unit tests which rely on them should have trust relationship to continue to run (C# only)
Protected methods should be made private if we don't want to support them or want to change them.
Make sure there are no public/protected objects with bad names

**Comment by cleemullins** [comment]
@vishwacsena, @tomlm this will result in breaking changes, if we don't do it soon.

**Comment by cleemullins** [comment]
It's too late to change this, as the product has shipped.
