### ISSUE TITLE
CancelAllDialogs action doesn't work

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#3534]
## Version
latest master

## Describe the bug
CancelAllDialogs action doesn't work as expected. 

## To Reproduce
1. Go to Microsoft.Bot.Builder.TestBot.Json
2. Start the bot 
3. Run sample 13. EndDialog
4. See screenshot, call CancelAllDialogs will throw an exception. 

![image](https://user-images.githubusercontent.com/32191031/76379853-37be2180-638c-11ea-87df-850171d01cc7.png)

The dc.Parent.CancelAllDialogsAsync is not executed. 
![image](https://user-images.githubusercontent.com/32191031/76380018-a602e400-638c-11ea-8605-9cbfd821fcd8.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Fixed via #3536
