### ISSUE TITLE
There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by Shubham-Kr10** [microsoft/botbuilder-dotnet#3535]
Hey anyone can help me out getting errors on publishing bot to azure , while it worked fine when tested locally with the help of emulator . I 've tried different publishing steps as stated by @mdrichardson  on https://github.com/microsoft/botbuilder-dotnet/issues/2234 

Following is the snip of the errors 
![errors2](https://user-images.githubusercontent.com/54877723/76414152-c6e32d80-63bc-11ea-859b-980433057e14.png)

**Comment by stevkan** [comment]
If you are deploying via Visual Studio, be sure to select the "Remove additional files at destination" option. If you don't know, this is located in the Publish profile's settings, under "File Publish Options". Failing to do this can result in old and new files conflicting on the server. If you haven't tried this, give it a go and let me know your results.

I'm lukewarm on the above being the source of your issue, but it could be so worth testing.

I see you are running this in Web Chat. Is this the Web Chat channel "iframe" version or is this the customizable BotFramework-WebChat version?

**Comment by Shubham-Kr10** [comment]
Web chat channel is "iframe" version. Also i've selected "Remove additional files at destination" but still facing the same issue @stevkan

**Comment by Shubham-Kr10** [comment]
Thanks for response @stevkan , It worked
