### ISSUE TITLE
SlackAdapter does not parse select options

### ISSUE THREAD

**Issue by marcusbooyah** [microsoft/botbuilder-dotnet#3537]
## Version
4.7.0

## Describe the bug
The SlackAdapter does not parse dropdown selections from interactive messages.

## To Reproduce
1. Create an interactive message with multiple choice `select` option.
2. Submit response.
3. `Activity` text is null, but should contain the response value.

## Expected behavior
Response value is passed into the `text` field.

[bug]

**Comment by cleemullins** [comment]
This issue is bucketed with a few other Slack issues, and we're planning to address them all in our R10 Milestone.

**Comment by garypretty** [comment]
There is now an open PR (just awaiting some resolution of failing tests) which implements some changes to the Slack adapter, including those within this PR. @marcusbooyah , thank you very much for your contribution here.

The changes in the PR, which consolidates a number of changes, also removes the tight dependency on the Slack client that was being used.  Now, a developer can install and use any client they wish directly from NuGet.

You can see the PR at https://github.com/microsoft/botbuilder-dotnet/pull/4046.  Please let me know if you have any questions.

I am going to close out this PR, but once the consolidated PR has been merged, this will be available in the nightly builds.
