### ISSUE TITLE
Property assignment with dynamic path not working

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3545]
## Version
latest master

## Describe the bug
Our property assignment action, SetProperty, SetProperties, and EditArray are not working when the property contains dynamic values to evaluate, and the dynamic value is reference using a shortcut, for example

```
 "actions": [
                {
                  "$type": "Microsoft.SetProperties",
                  "assignments": [
                    {
                      "property": "user.lists",
                      "value": "={}"
                    },
                    {
                      "property": "user.lists.todo",
                      "value": "todo"
                    },
                    {
                      "property": "$mylist",
                      "value": "lists"
                    }

                  ]
                },
                {
                  "$kind": "Microsoft.SetProperty",
                  "property": "user[$mylist].todo",   // here will fail
                  "value": "newtodo"
                },
                {
                  "$kind": "Microsoft.SendActivity",
                  "activity": "${user[$mylist].todo}"
                }
```

## To Reproduce
Run the bot above 

## Expected behavior
Value correctly set to newtodo

## Additional context
The root cause is our path resolver assuming alias (#, $) assume this alias at begging, but didn't enforce that

before transform: user[$mylist].todo
after transform: dialog.mylist].todo  // `user[` is dropped

[bug]

**Comment by vishwacsena** [comment]
Not a R8 issue. Work around is to not use path resolvers in dynamic path and use explicit paths `dialog.xyz` instead of `$xyz`
