### ISSUE TITLE
[LG] fromFile() does not handle relative paths well

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3548]
fromFile('./foo.json') did not work. We should have relative paths work and paths must be relative to the path of the file that holds the function. 

C# and JS. reproed issue in JS.

**Comment by boydc2014** [comment]
This is an issue with js that we want the library to be run-able in browser environment, let's follow up by clarify the requirement.

**Comment by Danieladu** [comment]
it seems the code works.
