### ISSUE TITLE
[LG] improve import statement

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3550]
\[foo](foo.lg) does not work. We should consider this to be identical to \[foo](./foo.lg) where the path is relative to the file that holds the import reference.

**Comment by boydc2014** [comment]
@vishwacsena  did you have a case that this is not supported? we have tested cases that supported multiple format of this 
https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.LanguageGeneration.Tests/Examples/import.lg

**Comment by boydc2014** [comment]
Synced with Vish, that this is a reported case by Ted, maybe @Danieladu  and @cosmicshuai we should reach out to Ted since we can't repro it.

**Comment by Danieladu** [comment]
since ted can not re-pro it, we will close it temporarily
