### ISSUE TITLE
[Adaptive] Clean up global statics

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3558]
[ ] HostContext should go away
[ ] Make all extension methods base classes good names for usage with non-extension langauges

**Comment by cleemullins** [comment]
@tomlm, @vishwacsena This is a P0 bug with a very scary title and little detail that's not moved forward in 26 days. How can we push this forward?

**Comment by cwhitten** [comment]
hey there @vishwacsena @tomlm - what does this issue mean?
