### ISSUE TITLE
Auto-generate skills manifest from declaratively defined adaptive dialogs (dotnet)

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3561]
Filing a tracking ticket to evaluate and build a library that can auto-generate a skills manifest for declaratively defined adaptive dialogs.

Input from @darrenj 
The core of a manifest can be easily auto-generated and what we did with the preview bits including all the LU trigger information if your doing utterance invocation. for utterance triggering you don't need to expose discrete actions so don't need to iterate over dialogs. You could go one step further to iterate dialogs (but understanding action inputs would require manual work likely).  In short - we already provide a manifest OOB that only requires updates for appid/endpoint

**Comment by gabog** [comment]
Composer adds support for this, we won't be doing this at the SDK level
