### ISSUE TITLE
Ability to create Proactive triggers

### ISSUE THREAD

**Issue by kevmcdonk** [microsoft/botbuilder-dotnet#3566]
**Is your feature request related to a problem? Please describe.**
Firstly, I want to say how fantastic this tool is and exactly what I think people need to really get started with Bot Framework. It took me quite a while to get my head round dialogues and the flow of a Bot but this makes it so much easier to understand.

This request though is about whether you could include support for Proactive triggers, especially around getting those in to a dialogue. It's something I struggled with but I feel there are a lot of scenarios with Bots to chase people for updates that would use this.

**Describe the solution you'd like**
Similar to the ability to add intents, include the ability to create a Proactive trigger that would create a Controller with associated method in the Bot class and have the ability to link that in to a dialogue if needed as well. It could also include guidance on using Logic Apps with a schedule for starting the Proactive trigger.

**Describe alternatives you've considered**
Only alternative would be to do it yourself!

**Additional context**
I have an example of Proactive triggers connecting in to an existing dialogue at https://github.com/kevmcdonk/WhereOnEarthBot/blob/master/DailyBingChallengeChooserBot/Controllers/GetReminderController.cs but feel that the code needs tidying up before integrating. I'd be happy to investigate in a PR.

**Comment by tonyanziano** [comment]
There is currently no planned work in adaptive / composer in the R9 timeframe to support proactive triggers.

**Comment by cleemullins** [comment]
@stevenic believes this should be in R10. Triaging to there for now.

**Comment by cleemullins** [comment]
This is done in PR #4063.  

@vishwacsena is also building a sample.

**Comment by bartbilliet** [comment]
@cleemullins I understand this now gives us the ability to use proactive triggers in adaptive dialogs, correct? I believe the original issue mentioned if it would be possible to use proactive triggers in Bot Framework Composer. Am I correct that an activity trigger must still be implemented in Bot Framework Composer to expose this new adaptive dialog functionality?

**Comment by tiagonmas** [comment]
any news on a sample to acomplish this ? @vishwacsena
