### ISSUE TITLE
[Adaptive] VS code extensions

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3567]
# Adaptive tools - extension

`Adaptive tools` will ship to the [marketplace][7] as a VS code extension and provide the 
following capabilities: 

- [x] VS code
- [x] Debugging adaptive dialogs
- [x] Debugging language generation
- [x] syntax highlighting, auto-suggest, auto complete functionality
    - [x] .lu documents
    - [x] .lg documents
- [x] Expansion/ test UI for .lg documents
- [ ] C#

## User scenarios

**As a VS code or VS developer building bots**

1. Using code based or declaratively defined adaptive dialogs, I can easily set and hit breakpoints at any trigger or action within my 
adative dialogs. I can use standard debug controls to perform debug transport control operations (start, 
step over, continue, stop, restart etc).
2. Using language generation (with or without adaptive dialogs), I can easily set and hit breakpoints at any 
template or condition evaluation within my LG content. I can use standard debug controls to perform debug 
transport control operations (start, step over, continue, stop, restart etc).
3. I can easily author .lu, .lg documents with rich auto suggest, auto-complete, syntax highlighting capabilities.
Also included is static validation to capture errors, warnings as well as ability to navigate to specific error in
the document from the errors list. See [here](#lu-extension) for full reference for .lu extension and [here](#lg-extension) for .lg extension.
4. For .lg files, I can easily test expansions using an integrated extension UX. I simply select the template, 
provide test data (if required, in JSON format) and can produce one or more expansions for that template.

## **Out of scope** (post R9 backlog)

- [ ] Support for visual studio
- [ ] Support for JS bots.
- [ ] Debugging - debug console integration/ ability to evaluate expressions with snapshot of memory.
- [ ] Surface predictions (if using LUIS) into .lu document
- [ ] syntax highlighting, auto-suggest, auto complete functionality
    - [ ] .qna documents
- [ ] ability to train, test, publish .lu documents to
    - [ ] LUIS
    - [ ] Orchestrator (embeddings)
- [ ] ability to test and refine 
    - [ ] .lu documents with
        - [ ] LUIS
        - [ ] Orchestrator
    - [ ] .qna documents with QnA Maker
- [ ] ability to get custom functions working with auto-suggest, auto-complete

## lu extension

1. [Validations](#validations) - Syntax and semantic error checking (validations), errors reporting
2. [Creating entities](#creating-entities) - Auto suggest syntax for creating entities
3. [Labeling experience](#labeling-experience) - Auto suggest, auto complete experience for labeling utterances
4. [Patterns](#Patterns) - Auto suggest, auto complete experience for writing patterns
5. [Imports](#imports) - Auto suggest, auto-complete for handling imports.

### Validations
Any syntax or semantic errors should follow a similar approach as we do for LG LSP. The specific line that has the issue is highlighted with the error/ warning message.
Rely on the core parser + validation logic to identify errors/ warnings to render.

### Creating entities
We will support auto-suggest, auto complete for entity definitions using the `@` notation. 

- Auto suggest entity type as soon as user starts an entity definition/ declaration line (identified via `@` character in a new line)
    - Entity type auto-suggest/ auto-complete can be one of the following - 
        - ml, prebuilt, regex, list, composite, patternany, phraselist.
        - Given lu format also supports definitions in a separate line, this list should also include all other entity names defined (explicitly in this document or captured via an import)
    - If entity type chosen is `prebuilt` then offer prebuilt entity name suggestion - e.g. `@prebuilt number`. The prebuilt entity name suggestion should show up after `prebuilt` is typed or selected.
        - See [here][2] for a list of pre-built entity name to suggest.
- When creating a `regex` entity, auto-suggest/ auto-complete `//` after `=`. e.g. `@regex zipcode = /[0-9]{5}/`
  Another example:
  ```
    @regex zipcode
    @zipcode = /[0-9]{5}/
  ```
- When creating a `list` entity, automatically indent normalized value and synonyms. Automatically add a `-` to help with easy list addition. Note we should stop automatically adding a `-` when we detect an empty text and a line feed after a `-`. 

  Normalized value is identified via a trailing `:`. Synonyms are just a list.

  Example: 
  ```
    @list city = 
        - seattle : 
            - sea
            - seatac
            - space needle
        - new york :
            - JFK
            - EWR
            - big apple
  ```
- When creating a `composite` entity, auto-suggest, auto-complete all entity names that have already been defined. e.g. `@composite device = [number, temperature]`. We will auto-suggest all available entities after `[` and automatically add `,` when an entity is selected from the auto-suggest list.
- When creating an `ml` entity with children (identified via `=` and a new line),
    - Auto-suggest `- @` for each new line.
    - Auto-suggest either `ml` or one of the other entities defined as the type for any child.

  ```
    @ list listCity
    @ prebuilt number
    @ prebuilt geographyV2
    @ regex regexZipcode = /[0-9]{5}/
    @ ml address hasRoles fromAddress, toAddress 
    @ address =
        - @ number 'door number'
        - @ ml streetName
        - @ ml location usesFeature geographyV2
            - @ listCity city
            - @ regexZipcode zipcode
  ```

- Auto suggest, auto-complete `hasRole`, `usesFeature` in entity definition line. 
  e.g. `@ ml address hasRoles fromAddress, toAddress`
  e.g. `@ userName usesFeature personName`

### Labeling experience
- Automatically add prefix `-` when in utterance definition mode. 
- Stop inserting `-` if user hits enter with no text after `-`. remove the empty `-` line.
- Auto-suggest all defined entities when user inserts `{`. 
- Automatically close brackets `}`.
- Auto-suggest all defined roles when user inserts `:` after an entity name - e.g. `{xxx:`
- Auto-suggest all entity and roles when user types `{@`
- When user types an utterance, hits enter and hits TAB key, then 
    - replace the main utterance without entity labels
    - copy the labelled utterance as a line
    - add a new line with unlabelled utterance as text.

  ```
    > when user types this utterance, hits enter and a TAB
    # foo
    - I want {foodType = tomato}

    > The following should the outcome
    # foo
    - I want tomato
        - I want {foodType = tomato}
        - I want tomato

    > when user types this utterance, hits enter and a TAB
    # foo
    - I want tomato

    > The following should be the outcome
    # foo
    - I want tomato
        - I want tomato
  ```
- Provide an ability to select one or more characters from an utterance to label as an entity. e.g. 
  ```
    > User typed the following utterance and selected `tomato` using text selection
    # foo
    - I want tomato

    > Upon selection, offer a flyout menu with list of entities to label this as.
  ```
### Patterns
- Automatically add closing brackets - `[]`, `()`.
- Auto-suggest all defined entities when user inserts `{`. 
- Automatically close brackets `}`.
- Auto-suggest all defined roles when user inserts `:` after an entity name - e.g. `{xxx:`
- Auto-suggest all entity and roles when user types `{@`

### Imports
- Auto-suggest available .lu files when user adds `[]` in a blank line. This is for importing another .lu file.
  ```
    [a.lu](./a.lu)
  ```
- Auto-suggest available .lu files as well as available intents when user enters `[]` on a utterance line (under an intent).
  ```
    # foo
    > `bar` is an intent defined in `a.lu`
    - [a.lu](./a.lu#bar)
  ```

## lg extension

1. [Validations](#lg-validations) - Syntax and semantic error checking (validations), errors reporting
2. [Creating templates](#creating-templates) - Auto suggest syntax for template authoring
3. [Adaptive expressions](#adaptive-expressions) - Auto suggest, auto-complete for adaptive expressions
4. [Composition](#lg-composition) - Auto suggest, auto complete for template composition
5. [Imports](#imports) - Auto suggest, auto-complete for handling imports.
6. [Structured response](#structured-response) - Auto suggest, auto-complete for structured response templates.

### lg validations
Any syntax or semantic errors should follow a similar approach as we do for LU LSP. The specific line that has the issue is highlighted with the error/ warning message.
Rely on the core parser + validation logic to identify errors/ warnings to render.

### Creating templates
When creating a template, offer 
- automatic prefix of `-` when entering a new line.
- skeleton fill for If..elseif..else block
- skeleton fill for switch..case..default block
- Auto suggest for [structured response](#structured-response) the moment user types in `[` following a template name definition.

### Adaptive expressions
When user is typing an [adaptive expression][5], offer
- syntax highlighting
- auto-suggest, auto-complete for prebuilt functions including signature, parameter order and type

### Composition
When user types `{}` offer auto-suggest, auto-complete for lg templates as well. Also include paramter list if the template is parametrized.

### LG import
- Auto-suggest available .lg files when user adds `[]` in a blank line. This is for importing another .lg file.
  ```
    [a.lg](./a.lg)
  ```
- Suggest files based on other .lg files in the current directory as well as based on relative paths user specifies relative to the location of the current .lg file.

### Structured response
[Structured response][6] templates enable users to author stuctured template and its evaluation using LG. We will offer skeleton fill in, auto-suggest, auto complete based on user specified structure type. 

- offer auto suggest, auto-complete for known structure types as soon as user types `[`. This should include 
    - Activity, HeroCard, Attachment, Typing, SigninCard, ThumbnailCard, AudioCard, VideoCard, AnimationCard, MediaCard, OAuthCard, CardAction, Event
- offer skeleton fill in with top properties for each structure type based on known properties list. 
    e.g. 
    ```
        # myTemplate
        [Activity
            Text = enter display text
            Speak = enter spoken text
            SuggestedActions = enter '|' delimited actions
            AttachmentType = carousel
            Attachments = 
        ]
    ```
| Type | properties | 
|------|------------|
| Activity | Text, Speak, Attachments, SuggestedActions, AttachmentType |
| HeroCard | title, subtitle, text, image, buttons | 
| Attachment | contentType, content |
| Typing | none | 
| SigninCard | text, buttons |
| ThumbnailCard | title, subtitle, text, image, buttons | 
| AudioCard | Title, Subtitle, Text, Image, Media, Buttons, Shareable, autoloop, autostart, aspect, duration, value | 
| VideoCard | Title, subtitle, text, image, media, buttons, shareable, autoloop, autostart, aspect, duration, value | 
| AnimationCard | Title, subtitle, text, image, media, buttons, shareable, autoloop, autostart, aspect, duration, value | 
| MediaCard | Title, subtitle, text, image, media, buttons, shareable, autoloop, autostart, aspect, duration, value | 
| OAuthCard | Text, ConnectionName, TokenExchangeResource, Buttons | 
| CardAction | Type, title, image, text, displayText, value, channelData |
| Event | Name, value |

- Offer auto-suggest, auto complete for expressions within values for any property.

[1]:https://luis.ai
[2]:https://github.com/microsoft/botframework-cli/blob/master/packages/lu/docs/lu-file-format.md#prebuilt-entity
[3]:https://www.figma.com/file/xZAYxxBwZ0yxuVoP7Kx7QT/mw_LUIS-Monaco-editor?node-id=1%3A1482
[4]:https://microsoft-my.sharepoint.com/:w:/p/yiba/EeRR32-PwFNIgwROVBiqlGABJrgxWroGDkzSUTJLi4_JGw?e=E9DRGU&xsdata=MDR8MDF8dmthbm5hbkBtaWNyb3NvZnQuY29tfGI0YTIyODZlYzUwYzQzNzg0YTMwMDhkNzZhNDZhZDFmfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2MzcwOTQ3MjQwOTQxMDY4ODB8VW5rbm93bnxUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjA9fC0x&sdata=REtxV3Z6cU1KYjJPMldJQllsMVpvalAyWDR1b2VMRkM4SkxWbi9qV2J6VT0%3D
[5]:https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language
[6]:https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/structured-response-template.md
[7]:https://marketplace.visualstudio.com/

**Comment by cleemullins** [comment]
@vishwacsena, this is a P0 bug with no forward progress for 25 days. I don't believe the work described here will fit in the remaining R9 time frame. Let's discuss priorities, and consider pushing this work.

**Comment by vishwacsena** [comment]
@boydc2014 Lowering to P1. Chatted with Scott. We should continue to execute on this to get a preview solution if possible in the R9 time frame but we will not block release.

**Comment by cleemullins** [comment]
@vishwacsena, @boydc2014  Any updates on this? The deadline is upon us.

**Comment by boydc2014** [comment]
> @vishwacsena, @boydc2014 Any updates on this? The deadline is upon us.

@cleemullins i think the designed features are in, we can close this one and create an new issue for the above `out of scope` features for R10, make sense? @vishwacsena
