### ISSUE TITLE
[Adaptive] End trigger action

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3569]
We have EndTurn, EndDialog but not an EndTrigger action. Basically need to be able to use an action to end the current action plan. Without this, users will have to resort to using goto or an alternate solution.

**Comment by tomlm** [comment]
How about: **EndActions** ?

**Comment by vishwacsena** [comment]
Workaround is to use Goto action or BreakLoop action

**Comment by mrivera-ms** [comment]
@garypretty could you please look at this and tell us if it should be included in R12?

**Comment by garypretty** [comment]
@mrivera-ms Marked as a nice to have P2 for R12.  I haven't heard any demand for this and there is a workaround.

**Comment by mrivera-ms** [comment]
Since there is no customer affected by this and there is a workaround, will close this issue.
