### ISSUE TITLE
[DCR] make DialogContext a field of turnContext

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3578]
This is a requirement came from the LG debugging experience. 

Today we do debugging instrumentation in the base class `AdaptiveDialog`, where have access to the DialogContext, but we don't have access to DialogContext (do we?) when executing a specific action, for example, a SendActivity action, which have LG text to debug with. 

Ideally we want have access to DialogContext, and attach with the LG context returned in LG evalution and send them to debugger. 

Since we only have access to turnContext in executing actions, i wonder if can make DialogContext a property of turnContext?

**Comment by tomlm** [comment]
I would recommend either:
1. Pushing DialogContext as service via turnContext.TurnState.Get<DialogContext>() (this would probably require DCR #3577 to be done correctly)
2. Changing ActivityTemplate data binding method to allow passing a Dialogcontext, and plumbing that all the way into LG as optional method signature.

**Comment by tomlm** [comment]
We are going to do #3577, so this DCR is rejected.
