### ISSUE TITLE
Add a custom endpoint property to the LuisService class

### ISSUE THREAD

**Issue by WizX20** [microsoft/botbuilder-dotnet#3583]
## User Story
As a developer I want to use the SDK with docker containers; for example the new [LUIS docker container](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-container-howto?tabs=v3).

This is currently not possible with the OOTB [Microsoft.Bot.Configuration.LuisService](https://github.com/microsoft/botbuilder-dotnet/blob/50d78c5c5f77aa0569c5fe892c14873369c9f314/libraries/Microsoft.Bot.Configuration/Services/LuisService.cs#L9) class for configuration. The `Microsoft.Bot.Configuration.LuisService` class has a `GetEndpoint` method that builds the endpoint based on the configuration settings. This method makes it impossible to connect to a custom endpoint, like for example `localhost:5000`. In order to do so we need to add our own LUIS service class with, for example the property:
```
[JsonProperty("endpoint")]
public string Endpoint { get; set; }
```

We then need a custom `GetEndpoint` implementation that checks the property first:
```
if (!string.IsNullOrEmpty(this.Endpoint))
{
  return this.Endpoint;
}
```

In `MyBotSettingsBase.cs` we could use our own LUIS configuration model:
```
public class CognitiveModelConfiguration
{
  public DispatchService DispatchModel { get; set; }
  public List<OURCUSTOM_LuisService> LanguageModels { get; set; }
  public List<QnAMakerService> Knowledgebases { get; set; }
}
```

Finally we can now use the endpoint in our configuration for example:
```
"luis": {
    "appId": "aaa-aaa",
    "version": "0.1",
    "endpoint":  "http://localhost:5000",
    "region": "local",
    "authoringKey": "",
    "authoringRegion": "local"
  },
```

## Acceptance Criteria 
*List your requirements.*
- [ ] Possibility to uset (set) a custom endpoint property in the LuisService class
- [ ] Optionally, possibility to extend/override/inherit the LuisService class

## Related
* [Feature Request: Make Microsoft.Bot.Solutions.BotSettingsBase overridable](https://github.com/microsoft/botframework-solutions/issues/3186)

**Comment by CezaryMarcjan** [comment]
Thanks @WizX20 for the report.  We'll take a look at this.

**Comment by cleemullins** [comment]
This looks like a nice feature for R9.

**Comment by cleemullins** [comment]
@garypretty Can you evaluate this? It would need to be done across all of our platforms.

**Comment by cleemullins** [comment]
@garypretty, can you drive this to closure? Seems like a very nice feature to have, allowing increased flexibility with regards to containers.

**Comment by garypretty** [comment]
Absolutely. I have an open query with @tomlm. Will follow up tomorrow.

**Comment by mrivera-ms** [comment]
@garypretty, any news on this?

**Comment by cleemullins** [comment]
The PR is for C#. I've added a "Need JS" and "Need Python" label, as C# is only 1/3 of the story.

**Comment by garypretty** [comment]
PR for JS opened https://github.com/microsoft/botbuilder-js/pull/2072 (Bot Configuration classes not implemented in Python, so this is not required there).  Will close this issue once the JS PR has been approved / merged.

**Comment by garypretty** [comment]
Closing this issue now as the JS PR is awaiting merge and is tracked on https://github.com/microsoft/botbuilder-js/issues/2064 in the JS repo.
