### ISSUE TITLE
[Adaptive] ChoiceInput and ConfirmInput do no have consistent compoent schema

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3585]
ConfirmInput is missing `"$role": "expression"` for `Style` and `ChoiceOptions` property. 
ChoiceInput has the `"$role": "expression"`.

**Comment by cleemullins** [comment]
@vishwacsena, @tomlm This is a P0 bug with no forward progress for 22 days. How can we push this forward?
