### ISSUE TITLE
BotFrameworkHttpClient: Change null check on 'appId' to StringIsNullOrEmpty

### ISSUE THREAD

**Issue by WizX20** [microsoft/botbuilder-dotnet#3590]
## Issue
The _Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpClient_ [GetAppCredentialsAsync method](https://github.com/microsoft/botbuilder-dotnet/blob/373096310de1272ac1f26f2045448b3f40f4ff68/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs#L166) checks the **appId** argument for null; but a `string.IsNullOrEmpty(appId)` would be better. Or have it throw an exception when it is an empty (or whitespace) string value.

## Version
Microsoft.Bot.Builder.Integration.AspNet.Core, Version=4.7.2.0 (Runtime: v4.0.30319)

## Describe the bug
For example, I had this value (appId) fetched from configuration, which produced an empty string as value (**""**). That in it's turn produced the exception that the **clientSecret** was null or empty; which is very confusing.

## Screenshots
![image](https://user-images.githubusercontent.com/1008647/76957366-f7275080-6915-11ea-8baa-9aa7aa1fe83a.png)

[bug]

**Comment by cleemullins** [comment]
Thanks @wizX20. @carlosscastro Can you take a quick look? This seems a reasonable change, and would let us give a better error message. Seems like an R9 change.

**Comment by carlosscastro** [comment]
Thanks @WizX20. This sounds like a good idea. I'll not only check this but all other public methods in this surface to make sure we are consistent with our validations.

**Comment by cleemullins** [comment]
@carlosscastro, are you able to drive this to closure, or would you like help? @mrivera-ms will volunteer to help if you need it. :)
