### ISSUE TITLE
[LG] support adaptive cards template expansion in Activity factory

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3592]
If an attachment is an adaptive card then call adaptive cards template expansion library to support full bot side resolution of templates.

Need to figure out a way to get this working E2E while adaptive card templating is in preview.

**Comment by vishwacsena** [comment]
@matthidinger can you update this bug once you have your packages ready?

**Comment by mrivera-ms** [comment]
@boydc2014 , please prioritize this item and let us know if it will be done in R11.

**Comment by boydc2014** [comment]
> @boydc2014 , please prioritize this item and let us know if it will be done in R11.

This was originally put just for a backlog and i'm not sure the exact requirement. I saw Vishwac unassigned Matthidigner, i expect this is no longer valid. But i will talk a look at, see if i can find anything.

**Comment by boydc2014** [comment]
Closing this, since the intention wasn't clearly stated.
