### ISSUE TITLE
ShowTypingMiddleware causes BadRequest exception

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#3596]
## Version
4.7.2, 4.8.0

## Describe the bug
Starting since 16 or 17 March sending a 'ShowTyping' to the user results in the following exception:

```
Microsoft.Bot.Schema.ErrorResponseException: 'Operation returned an invalid status code 'BadGateway''

This exception was originally thrown at this call stack:
	Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(string, string, Microsoft.Bot.Schema.Activity, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>>, System.Threading.CancellationToken)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
	Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(Microsoft.Bot.Connector.IConversations, string, string, Microsoft.Bot.Schema.Activity, System.Threading.CancellationToken)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(Microsoft.Bot.Builder.ITurnContext, Microsoft.Bot.Schema.Activity[], System.Threading.CancellationToken)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]
```

The bot is successfully able to send replies to the user, it's just the 'ShowTyping' that fails. Disabling the ShowTypingMiddleware in the bot resolves the issue.
This is happening in both bots we're developing and it has been working fine before.

## To Reproduce
1. Add the ShowTypingMiddleware to the bot adapter pipeline
2. Add a delay in the response
3. Send a message to the bot

**Comment by EricDahlvang** [comment]
Hi @sschutten 

Thank you for reporting.  Which channel is this occurring on?

**Comment by sschutten** [comment]
Hi @EricDahlvang,
This is on the msteams channel. Was just thinking it may have something to do with the adjusted limits on teams. Regardless, it would be good if the middleware would not cause an unhandled exception.

**Comment by EricDahlvang** [comment]
Related: https://github.com/microsoft/BotFramework-Services/issues/194

**Comment by EricDahlvang** [comment]
Is your bot also in West Europe?

**Comment by sschutten** [comment]
Yup. Sounds very similar to the issue you added as related.

**Comment by EricDahlvang** [comment]
Okay,  I'm going to close this one as a dup. Please follow along on the linked issue for updates.
