### ISSUE TITLE
[Adaptive] DeleteProperty does not work for entity shortcut

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3600]
This does not work. Not sure if we just do not support path shortcuts in deleteproperty action .. ?
```C#
// does not work
new DeleteProperty()
{
    Property = "@geographyV2"
}
// works
new DeleteProperty()
{
    Property = "turn.recognized.entities.geographyV2"
}
```

**Comment by tomlm** [comment]
@geographyV2=> turn.recognized.entities.geographyV2.first() <-- .first()
@@geographyV2 => turn.recgonized.entities.geographyV2;

If you use DeleteProperty() with @@ it works correctly.
