### ISSUE TITLE
Handle null message.Text in DateTimePrompt

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3605]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
DateTimeRecognizer.RecognizeDateTime itself doesn't handle null query: https://github.com/microsoft/botbuilder-dotnet/blob/b08e2fb04d5f9d30554bce5cf95d437fbfaaf4db/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs#L104

It will throw 
```
System.NullReferenceException: Object reference not set to an instance of an object.
  Stack Trace: 
    QueryProcessor.Preprocess(String query, Boolean caseSensitive, Boolean recode)
    DateTimeModel.Parse(String query, DateTime refTime)
    DateTimeRecognizer.RecognizeDateTime(String query, String culture, DateTimeOptions options, Nullable`1 refTime, Boolean fallbackToDefaultCulture)
    DateTimePrompt.OnRecognizeAsync(ITurnContext turnContext, IDictionary`2 state, PromptOptions options, CancellationToken cancellationToken) line 104
```
**Describe the solution you'd like**
Handle null in DateTimePrompt

**Describe alternatives you've considered**
Handle in DateTimeRecognizer.RecognizeDateTime

**Additional context**
Easily happen in DLS

[enhancement]

**Comment by EricDahlvang** [comment]
Looks like @mdrichardson has already completed this work: https://github.com/microsoft/botbuilder-dotnet/pull/3949 

Thanks @mdrichardson !
