### ISSUE TITLE
operations contains "!" need a more clear priority

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botbuilder-dotnet#3606]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Currently, "!" will be used as "not", "forced re-execution expression" and "not equal". but there is not a clear priority among these operation.
For example when I use "!=" like "value!=xxx", it should be parsed to "not equal" because "forced re-execution expression" can't be used behind a value. But I have to use it like "value != xxx", because "forced re-execution expression" seems have a more higher priority than "not equal".
Also the error message didn't figure out that the operation is parsed to which one. So I think the error message should be more detailed too.

**Describe the solution you'd like**

It is better that the priority of "not equal" is higher than "forced re-execution expression". Or when the "!" doesn't appear after a lg template, it shouldn't be parsed as "forced re-execution expression".

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by Danieladu** [comment]
attach the re-execute issue link：#3053
