### ISSUE TITLE
DCR: ITurnContext.deleteActivity() should also take a conversation reference

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#361]
The current code only allows you to delete an activity from the same conversation as the `context.activity`. That's probably fine in the 90% case but I can imagine scenarios where the activity you want to delete is actually in another conversation.  For maximum flexibility the JS sdk lets you pass in either an Activity ID or a `ConversationReference`:

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Core/ITurnContext.cs#L36

**Comment by garypretty** [comment]
@Stevenic I've asked PR #364 to hopefully address this.

**Comment by cleemullins** [comment]
@garypretty Thanks Gary! I've merged the code branch.
