### ISSUE TITLE
Unable to Deserialize json to abstract class

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/botbuilder-dotnet#3612]
I'm trying to Serialize and Deserialize Microsoft.Bot.Builder class ( DialogManager ) . It is Serializing and while Deserializing i'm getting error like
![Error in Deserialize DialogManager class](https://user-images.githubusercontent.com/51915291/73429053-b9b83500-4360-11ea-89f5-cbde933adea9.PNG)

**Comment by vishwacsena** [comment]
Dupe of #3332
