### ISSUE TITLE
Skills + OAuth: Differentiate between regular and skill mode when receiving tokens (dotnet)

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#3617]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5789)

When doing OAuth, and a Skill gets an activity, the skill thinks it is in regular mode and not skill mode, so it uses the wrong connector client.

The fix is to have the Token Service add an additional claim and have the SDK act accordingly and know in what mode it is based on the claim.

**Comment by gabog** [comment]
Hi @carlosscastro, can you loop me in when you design this? depending in the implementation we may be able to simplify the [IsSkillClaim](https://github.com/microsoft/botbuilder-dotnet/blob/7c485e28c53c12c2733bd81d8d93a1c1325d855b/libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs#L83) method that we use to determine if we are running as a skill or if we are a parent.

**Comment by cleemullins** [comment]
@carlosscastro, this is a P0 bug that's been open for 2+ weeks. How can we drive this forward?

**Comment by cleemullins** [comment]
per @carlosscastro, this should land on Wed 4/23
