### ISSUE TITLE
CrossTrainedRecognizerSet will emit an OnChooseIntent even when the two recognizer got the same intent. 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#3623]
I want to enable the new RecognizerSets in Composer and Here is a sample default hierarchy:
Currently the yellow part are by-default enabled in Composer(a RecognizerSet with a MultiLanguageRecognizer and a ValueRecognizer), in the MultipleLanguageRecognizer, we by-default enabled a CrossTrainedReconigzerSet and under that, user can add Luis, regex or qna recognizer.

But I found there is one behavior which is not expected.
If the two recognizer under CrossTrainedRecognizerSet returns the same intent result, it will emit an OnChooseIntent result. I expect I will get a weather intent instead of “OnChooseIntent”

"recognizer": {
    "$type": "Microsoft.RecognizerSet",
    "recognizers": [
      {
        "$type": "Microsoft.MultiLanguageRecognizer",
        "recognizers": {
          "en-us": {
            "$type": "Microsoft.CrossTrainedRecognizerSet",
            "recognizers": [
              "samplerecog.lu",  // there is also a weather intent in the lu file. 
              {
                "$type": "Microsoft.RegexRecognizer",
                "id": "regex",
                "intents": [
                  {
                    "intent": "weather",
                    "pattern": "weather"
                  }
                ]
              }
            ]
          }
        }
      },
      {
        "$type": "Microsoft.ValueRecognizer",
        "id": "value"
      }
    ]
  },
@vishwacsena , is the above scenario expected?

**Comment by vishwacsena** [comment]
@luhan2017 crosstrainedrecognizer set expects the collection of recognizers specified to self-promote a winner. Each recognizer except the recognizer that is the self elected winner must return `DeferToRecognizer_<recognizerId>` as the intent. 

You would need to build a different recognizer type for what you are looking for. Even if we do build one, which recognizers result would you use given one recognizer might not return entities while other might? In your configuration, returning the regex recognizers result as the recognitionresult might not work if luis returned entities as well. Another recognizer in the collection might return other properties that might be of interest to the consumer.
