### ISSUE TITLE
[Adaptive] ReplaceDialog can cause infinite loop at load time.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#3626]
If you have an AdaptiveDialog with an ReplaceDialog Action which is declaratively bound to the parent dialog you will get an infinite loop attempting to load it.

# foo.dialog
```javascript
{
   "$kind":"Microsoft.AdaptiveDialog",
    "triggers": [
           {
                "$kind":"Microsoft.OnBeginDialog",
                 "actions":[
                         { 
                              "$kind":"Microsoft.ReplaceDialog", 
                              "dialog":"foo" 
                         }
                  ]
           }
    ]
}
```
The typeloader will attempt to look up foo, which is foo.dialog which instantiate the dialog and go into an infinite loop blowing the stack at load time.

# Proposed solution 1
We could change ReplaceDialog to only take dailogId, not Dialog, and say you can only replace with a dialog that is already in the system.  This highlights the problem that we don't really have a way of adding to the dialogset of the adaptive dialog. 

# Proposed solution 2
The typeloader could keep a dictionary of objects that it has already instantiated by id, and reuse them? 

# Other Ideas?

**Comment by carlosscastro** [comment]
this test script reproes the issue

```json
{
    "$schema": "../../../../schemas/sdk.schema",
    "$kind": "Microsoft.Test.Script",
    "dialog": {
        "$kind": "Microsoft.AdaptiveDialog",
        "id": "planningTest",
        "autoEndDialog": false,
        "triggers": [
            {
                "$kind": "Microsoft.OnBeginDialog",
                "actions": [
                    {
                        "$kind": "Microsoft.SendActivity",
                        "activity": "I'm a joke bot. To get started say 'tell me a joke'"
                    },
                    {
                        "$kind": "Microsoft.ReplaceDialog",
                        "options": {},
                        "dialog": "Action_ReplaceDialogRecursive.test"
                    }
                ]
            }
        ]
    },
    "script": [
   ]
}
```

**Comment by vishwacsena** [comment]
@tomlm @carlosscastro sounds similar to #2230 .. ? Is this an issue because dc.replaceDialogAsync removes the active dialog (which is the replaceDialog action itself) instead of the parent adaptive dialog? 
Would we not need to have repalceDialog action signal the parent adaptive dialog to perform the replace?  

https://github.com/microsoft/botbuilder-dotnet/blob/9392d65018ff31d3e0c761931ccd4de96ed8fec9/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ReplaceDialog.cs#L61

**Comment by cleemullins** [comment]
@carlosscastro, this is a P0 bug that's 2 weeks old. How can we push this forward?

**Comment by carlosscastro** [comment]
@cleemullins I will tackle this one next week, ETA 4/27. I don't expect big surprises on this one.

**Comment by vishwacsena** [comment]
@carlosscastro Likely dupe/ similar root cause? https://github.com/microsoft/botbuilder-dotnet/issues/3626

**Comment by carlosscastro** [comment]
@vishwacsena Just checked, same thing. We can keep one of them and close the other as duplicate.

**Comment by vishwacsena** [comment]
@carlosscastro had the wrong link there. Meant to link to this ticket. https://github.com/microsoft/botbuilder-dotnet/issues/3742

**Comment by carlosscastro** [comment]
Fixing as part of https://github.com/microsoft/botbuilder-dotnet/issues/2230
