### ISSUE TITLE
Bing spell check for luisRecognizerV3

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botbuilder-dotnet#3630]
**Is your feature request related to a problem? Please describe.**
When I updated my luisRecognizer from V2 to V3, I didn't find the bingspellcheck option in the LuisRecognizerOptionsV3

**Describe the solution you'd like**
provide the spellcheck option for LuisRecognizerOptionsV3 so that we can use the feature.

[enhancement]

**Comment by garypretty** [comment]
HI @xhr0804.  As noted in the LUIS documentation, the Bing spell check capability is no longer available in the V3 LUIS API. https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-tutorial-bing-spellcheck
