### ISSUE TITLE
if condition default value is empty

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botbuilder-dotnet#3634]
## Describe the bug
the default value of if condition is empty. It should be true or false at least. And I think most of users want to set an expression as condition. So it is better that the condition input box is expression as default

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. add a if condition
2. check the default condition value

## Screenshots

![image](https://user-images.githubusercontent.com/19773357/77740773-c7cbbe80-704e-11ea-9f37-04ac77c23e0e.png)

**Comment by cleemullins** [comment]
@vishwacsena, @tomlm this is a P0 that's been sitting for 12 days. How can we drive this forward?

**Comment by tomlm** [comment]
added default : "true" for conditions
