### ISSUE TITLE
display default value for certain variables

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3636]
## Is your feature request related to a problem? Please describe.

None of the ? or placeholder tell the user **what will happen if they are not set**

![image](https://user-images.githubusercontent.com/2876650/77634398-d4d3a980-6f8b-11ea-8554-4a61c1eddd73.png)

**Comment by luhan2017** [comment]
@vishwacsena, can we update the ordering of the schema definition, put all the expressions at the front of other types? Then composer user will by-default treat all field as expression. 
![image](https://user-images.githubusercontent.com/32191031/78639106-f6178c80-78df-11ea-8000-fd03a09e3cc3.png)

**Comment by cleemullins** [comment]
@vishwacsena, This is a P0 that's been open for 13 days. How best can we drive this forward?

**Comment by vishwacsena** [comment]
@cleemullins @tomlm  and I chatted this morning. @tomlm is doing a pass on all component schemas to address this and other issues. In scope for R9.
