### ISSUE TITLE
Showtyping Middleware showing that Bot is typing when is not

### ISSUE THREAD

**Issue by eduardmartos** [microsoft/botbuilder-dotnet#3638]
Using ShowTypingMiddleware() shows that the bot is typing after the user received the bot's response. From the perspective of the user experience, this is very annoying, because the User thinks that the Bot will send another message and does not.

We believed that this could be due to the order in which we define the USE in the AdapterWithErrorHandler class:

Use (new TranscriptLoggerMiddleware ())
Use (new ShowTypingMiddleware ())

But we reversed the order and got the same result.
Any ideas why this may be happening?

## Version
SDK v4
Microsoft.Bot.Builder 4.7.2
Bot.Builder.Community.Storage.EntityFramework 4.6.4
Channels: all (azure web chat, teams and directline)

## Describe the bug
Create a Bot that needs to transcript and show to user that is typing when bot is doing a long process action to get response.

## To Reproduce
1. Create a Bot
2. Add Middleware for transcript
3. Add ShowTypingMiddleware
4. See error (sometimes it shows typing before get response, but more times, it shows after)

## Expected behavior
We want that bot shows that is typing only when is truth.

## Screenshots
![E994B0E7-A553-4CF3-97B4-F413DDA7AE03](https://user-images.githubusercontent.com/54709623/77817787-06548e00-70ce-11ea-9f5b-5484aa65fa8a.jpeg)

## Additional context

[bug]

**Comment by stevkan** [comment]
Unfortunately, there are known issues with ShowTypingMiddleware(). As it is, the docs suggest [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=csharp#send-a-typing-indicator) that the following method is used for generating a typing indicator. This can be sent, as shown below, within an activity handler or as part of a waterfall or component dialog, if more specific implementation is required.

```cs
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
{
    if (string.Equals(turnContext.Activity.Text, "wait", System.StringComparison.InvariantCultureIgnoreCase))
    {
        await turnContext.SendActivitiesAsync(
            new Activity[] {
                new Activity { Type = ActivityTypes.Typing },
                new Activity { Type = "delay", Value= 3000 },
                MessageFactory.Text("Finished typing", "Finished typing"),
            },
            cancellationToken);
    }
    else
    {
        var replyText = $"Echo: {turnContext.Activity.Text}. Say 'wait' to watch me type.";
        await turnContext.SendActivityAsync(MessageFactory.Text(replyText, replyText), cancellationToken);
    }
}
```

Please be aware that the typing indicator, when used in Teams, may result in 502s as support for that feature is temporarily being scaled back. You can read more about this topic [here](https://developer.microsoft.com/en-us/microsoft-teams/blogs/outage-bots-posting-typing-indicators-will-receive-502s/).

I'm closing this issue as resolved. If you have additional (related) questions, please feel free to re-open the issue.
