### ISSUE TITLE
LG options improvements

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3646]
## Update LG options to support 
```
> !# @strict = true
> !# @replaceNull = ${path} is undefined  
> !# @lineBreakStyle = markdown
```
strict=true means throw at null (and potential other strict rules)
replaceNull works all the time. If strict=true then we throw on all conditions except for null value and we use replace text in case of null value.
lineBreakStyle = markdown means one line break will be translated to two line breaks, any other value will keep the same

If more than one strict mode qualifier is specified in an LG document, then apply the last found occurrence.

If more than one document (via import) specify the qualifier for strict mode, then apply strict mode to the entire content loaded into that template instance.

**Comment by vishwacsena** [comment]
Also needs to be documented in the LG file format.

**Comment by cleemullins** [comment]
@vishwacsena, this is a P0 Design Change. I've assigned it to you, as we need resolution here immediately ("P0").

**Comment by vishwacsena** [comment]
@cleemullins we reviewed this in the weekly LG sync last week and @boydc2014's team is on point to implement this for R9.
