### ISSUE TITLE
DCR AdaptiveAction that works in parent adaptive dialog

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3649]
**Is your feature request related to a problem? Please describe.**
Actions provide a way of declaratively writing programs.  Our current BeginDialog model puts the child adaptive dialog into its own memory context and requires the caller to handle the return results.  This can be complex if you want to use a child dialog to hide complexity and encapsulate logic.  For example, the child dialog might check on a value being in a property and if so delete some other property and otherwise add to a different property.  To use that as a child dialog I have to define a protocol for deleting or adding to a parent property and handle that explicitly in the parent.  This is complex and cumbersome enough that it does not hide complexity.

**Describe the solution you'd like**
There is also utility in being able to create a child adaptive dialog that works in the parents memory scope--I'm calling this an adaptive action.  With this mechanism, I could define child dialogs that have full access to the parents memory scope.  This would allow me to directly add/remove/test parent's memory.  In effect this is an adaptive dialog that is not a container.

[enhancement]

**Comment by vishwacsena** [comment]
Options discussed: 
- parent memory scope 
- partial class.

**Comment by vishwacsena** [comment]
@chrimc62 do you still need this? Unclear if you have a solution here..

**Comment by mrivera-ms** [comment]
Closing due to innactivity.
