### ISSUE TITLE
BotBuilder 4.8 won't work with direct reference to Cosmos DB packages (3.2.0 or 3.7.0)

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botbuilder-dotnet#3659]
## Version
4.8.0

## Describe the bug
I am using .NET Core 2.1, Bot Builder 4.8.0. If you take the project and add the Microsoft.Azure.Cosmos package 3.7.0 and deploy the project to an App Service, the app service won't run. If you try to run the site manually from kudu, you get a "can't find package Microsost.Bot.Builder.Dialog.dll" error.

## To Reproduce
1. Make bot project for 4.8.0
2. Add the Microsoft.Azure.Cosmos nuget package v 3.7.0
3. Deploy to an app service

You get this error:
An error occurred while starting the application.
.NET Core 4.6.28207.03 X86 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.1.1-rtm-30846    |    Microsoft Windows 10.0.14393    |   Need help?

I also tried adding version 3.2.0 and had the same result.

## Expected behavior
Adding a package should work.

If I add the Microsoft.Bot.Builder.Azure pacakge, that will work...but I don't understand why I can't just add the reference directly.

[bug]

**Comment by EricDahlvang** [comment]
@Jeffders are some other steps or prereqs required to reproduce this?

The exact steps I followed:

- downloaded the vsix: https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4

- created an EchoBot

- upgraded Microsoft.Bot.Builder.Integration.AspNet.Core to 4.8

- added Microsoft.Azure.Cosmos 3.7.0

- deployed to Azure from VS 2017, creating a new app service

- the app service starts without issue: https://ericechobotdeploytest.azurewebsites.net/

**Comment by EricDahlvang** [comment]
@Jeffders I cannot repeat this, so I'm going to close it.
