### ISSUE TITLE
ticks unit is not consistent with formatDateTime parameter

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botbuilder-dotnet#3677]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
The unit of ticks is count of 100 nanoseconds from 0001/1/1. And the parameter of formatDateTime is count of second from 1970/1/1.. So when I want to convert a tick to a DateTimeStamp, I need to convert its unit first.

**Describe the solution you'd like**
Unify the unit of them.

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by Danieladu** [comment]
The simplest way to convert ticks to unix timestamp in Expression is  `unixTimestamp = (ticks – 621355968000000000) / 10000000`.

I am not sure if we should add a builtin function that convert from ticks to unix timestamp and from unix timestamp to ticks too.

**Comment by Danieladu** [comment]
duplicated with #3873
