### ISSUE TITLE
Add support to SkillDialog so SSO works with expectReply (dotnet)

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#3679]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5780)

**Comment by stevengum** [comment]
@carlosscastro @swagatmishra2007, any updates on this issue? Is https://github.com/microsoft/botbuilder-dotnet/pull/3546 related to this?

**Comment by stevengum** [comment]
This has been resolved via https://github.com/microsoft/botbuilder-dotnet/pull/3818.
