### ISSUE TITLE
Use more descriptive middleware names

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#368]
We currently let you use a lot of components like `ConversationState`, `UserState`, and the `LuisRecognizer` either as middleware or free standing within your bot logic.  One issue with this approach is that when you `use()` one of these components as middleware its not abundantly clear what's being done.  An alternate approach we could take would be to wrap things like `ConversationState` with a separate class when used as middleware and then use much more descriptive names for our middleware that better describe whats being done.  For example (in JavaScript):

```JS
const storage = new MemoryStorage();
const conversationState = new ConversationState(storage);
const userState = new UserState(storage);

adapter.use(new CatchErrors((err) => console.error(err.toString())))
            .use(new ReadAndWriteBotState(conversationState, userState));
```

The `ReadAndWriteBotState` class in the example above is just our existing `BotStateSet` class renamed.  This could be generalized even further to a `ReadAndWrite` class that can work with any component that implements `ICanReadAndWrite`.

**Comment by garypretty** [comment]
@Stevenic This sounds like a similar conversation I was having with @billba and @drub0y earlier this week where I was talking specifically about BotState.  Here is a summary of my comments...

_At the moment I feel it is confusing for developers that BotState is implemented as middleware, with the option of also using it on its own (this works in JS currently and there is an open PR to address this in the immediate term for .Net).  I think this can be confusing for developers – even I who have a descent understanding of what is there at present had not understood that BotState could be used outside of middleware.  It also leaves the naming of BotState inconsistent with other middleware components, with all other components having the ‘middleware’ suffix. E.g. ShowTypingMiddleware and RegExpRecognizerMiddleware._

Clear split out BotState into its own class which handles the storage and retrieval of state objects, along with the option to key the state objects to allow N number of objects to be stored against a conversation or a user.  The BotState could be used on isolation with the appropriate Read / Write methods to store and retrieve state.  This unblocks the ability for middleware to manage it’s own state and also means that, should a developer choose to, they can explicitly choose when state is read from and written to within their bot.

_A potential solution for this could be the following....A separate middleware component, BotStateMiddleware, would be created which would use the BotState class to provide the current ability to have state read from storage and stored on the context.services property and automatically persisted on the trailing edge of the pipeline.  This also has the advantage of ensuring that the middleware component is only responsible for a specific set of activities. I.e. adding current state to the context at the start of a turn and persisting any changes at the end of a turn._

**Comment by garypretty** [comment]
I am not wedded to the idea of having a middleware suffix, but I do like the separation of things like state and middleware that takes advantage of state or, another example, luis recognizer, with middleware that uses the recognizer.

**Comment by Stevenic** [comment]
@garypretty I'm not crazy about putting the `Middleware` suffix on every class.  We discussed this internally and everyone agreed that it feels a bit redundant in most cases.  What I'm arguing for as much as anything is for naming the describes what the middleware is doing.  Another example is the `BatchOutput` class. Nothing in the class name tells you that when you add it as middleware it's going to automatically flush the batch at the end of the request but if you instead add `use(new FulshBatchOutput())`  to your bot it's a little clearer that adding that will cause any batched replies to be automatically flushed.

**Comment by garypretty** [comment]
@Stevenic Yes. Agree with this. As I say, not tied to the suffix for the naming. I definitely agree that more descriptive naming is a great idea. Your example around state maps perfectly to my thoughts (I think!). Ie. Have an object, UserState that manages state, but then middleware that can use this to read stage to the context and  persist changes, named say, ReadAndPersistUserState. I guess I'm just not a massive fan of mixing the two together into a single object (which then precludes the more descriptive naming). At the end of the day I don't think it's the end of the world or something that HAS to change either, but wanted to come in with my thoughts.

**Comment by billba** [comment]
Another idea is to use a specific named method from an object, e.g. 
```ts
.use(ConversationState.readAndPersistState)
```

**Comment by Stevenic** [comment]
So the other thing I'd say about state in particular. I'f you're managing more than one piece of state you're likely going to want to read & write them in parallel so you're down the path of a separate component that you pass your individual state objects into.  We already have that component it's called the `BotStateSet` class.

To make the changes from this proposal a bit more concrete... We would rename `BotStateSet` to something more descriptive like `ReadAndWriteBotState` as that's what it does.  We'd then change `BotState` and derived classes to not implement `Middleware`.  If you want to automatically read and write even a single piece of state you would have to use the `ReadAndWriteBotState` middleware.

I know this is actually removing functionality but I think it's potentially removing some confusion I saw our documentation writers struggling with last week.  The fact you can use BotState on it's own or as middleware seemed to confuse things for them to the point they were trying to do both in their code. They added `ConversationState` to their bot as middleware then tried manually call `write()` at the end of their code.  My hope is the separation of concerns will make everything a bit clearer and I think this applies to more than just state which is why I called the change out as philosophical change.

**Comment by billba** [comment]
This makes a lot of sense to me. It aligns with stuff @drub0y's has been working on.

**Comment by garypretty** [comment]
Just to be clear, are we suggesting that we have ReadAndWriteBotState for managing state via middleware, but we still give the user the ability to use BotState on its own if desired? If so then this is exactly what I would like to see and aligns with my proposal too.

**Comment by garypretty** [comment]
Looks like this is in line with what @drub0y is suggesting as part of his DCR / PR #375 for state overhaul. 👍
