### ISSUE TITLE
foreach nesting error

### ISSUE THREAD

**Issue by ssss141414** [microsoft/botbuilder-dotnet#3680]
## Describe the bug
When I resolve a complicated json, I put a foreach inside another foreach.
Inner foreach will cause a error(even if doing nothing, only enumerating).

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1 Let's have a test string:

{
	"value": [{
			"id": "AAMkAGRmMzk5OGVhLTVjMTUtNGYzOC1iYmE1LTE0NzcwODA4ZDBkYwBGAAAAAAA8TbBtCPDST4WJ2uegtX2RBwDjFskHKy-jSoOBzZvRKlEWAAAAAAEMAADjFskHKy-jSoOBzZvRKlEWAACQdy_MAAA=",
			"toRecipients": [{
				"emailAddress": {
					"name": "Administrator MOD",
					"address": "admin@M365x035709.OnMicrosoft.com"
				}
			}, {
				"emailAddress": {
					"name": "Administrator MOD2222",
					"address": "admin@M365x035709.OnMicrosoft.com2222"
				}
			}],
			"ccRecipients": []
		},
		{
			"id": "AAMkAGRmMzk5OGVhLTVjMTUtNGYzOC1iYmE1LTE0NzcwODA4ZDBkYwBGAAAAAAA8TbBtCPDST4WJ2uegtX2RBwDjFskHKy-jSoOBzZvRKlEWAAAAAAEMAADjFskHKy-jSoOBzZvRKlEWAACQdy_MAAA=",
			"toRecipients": [{
				"emailAddress": {
					"name": "Administrator MOD",
					"address": "admin@M365x035709.OnMicrosoft.com"
				}
			}, {
				"emailAddress": {
					"name": "Administrator MOD2222",
					"address": "admin@M365x035709.OnMicrosoft.com2222"
				}
			}],
			"ccRecipients": []
		}
	]
}

2 In composer, set and convert it to json:
![image](https://user-images.githubusercontent.com/18118994/78330088-c271f500-75b5-11ea-89e8-7ec0ef85d17d.png)

3 Add double nesting foreach:
Outer foreach enumerates 'value' list, and this works.
Inner foreach enumerates 'toRecipients', and this causes a error.
![image](https://user-images.githubusercontent.com/18118994/78330160-eb928580-75b5-11ea-8b7a-ba743f5662f2.png)

I think my 'toRecipients' is valid.
![image](https://user-images.githubusercontent.com/18118994/78330442-89865000-75b6-11ea-9110-d57bbcb69e6e.png)

![image](https://user-images.githubusercontent.com/18118994/78330285-36ac9880-75b6-11ea-949e-f261e760423b.png)

**Comment by vishwacsena** [comment]
Here is a repro

```C#
var rootDialog = new AdaptiveDialog("root")
{
    Generator = new TemplateEngineLanguageGenerator(_lgFile),
    Triggers = new List<OnCondition>()
    {
        new OnConversationUpdateActivity()
        {
            Actions = WelcomeUserAction()
        },
        new OnBeginDialog()
        {
            Actions = new List<Dialog>()
            {
                new SetProperty()
                {
                    Property = "dialog.outer",
                    Value = "=json(`{'collection':[{'recipient':['a','b','c']},{'recipient':['1','2','3']}]}`)"
                },
                new SendActivity("I have ${dialog.outer}"),
                new Foreach()
                {
                    ItemsProperty = "dialog.outer.collection",
                    Actions = new List<Dialog>()
                    {
                        new SendActivity("In outer loop. I have ${dialog.foreach.index}. ${dialog.foreach.value}"),
                        new IfCondition()
                        {
                            Condition = "isArray(dialog.foreach.value.recipient)",
                            Actions = new List<Dialog>()
                            {
                                new Foreach()
                                {
                                    ItemsProperty = "dialog.foreach.value.recipient",
                                    Actions = new List<Dialog>()
                                    {
                                        new SendActivity("In inner loop. I have ${dialog.foreach.index}. ${dialog.foreach.value}")
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
};
```

**Comment by luhan2017** [comment]
I did some investigation on this, and found this is because the outer and inner foreach loop are both using "dialog.foreach.index" and "dialog.foreach.value". the inner dialog,foreach.index is overwriting the outer one. I suggest we should support user to customize the index and value field in foreach.
