### ISSUE TITLE
Update Activity method from Virtual Assistant 

### ISSUE THREAD

**Issue by nebhagat** [microsoft/botbuilder-dotnet#3686]
**Is your feature request related to a problem? Please describe.**
I want to attach a skill which refreshes cards to Virtual Assistant. With current SDK, refreshing cards via VA is not supported. 

**Describe the solution you'd like**
`SkillHandler` class does not implement `OnUpdateActivityAsync` . Individually skill can refresh the cards but not when consumed by a Virtual Assistant. 

**Describe alternatives you've considered**
NA

[enhancement]

**Comment by clearab** [comment]
Hi - This work is planned to be completed in our next release. Please see [this issue](https://github.com/microsoft/botframework-sdk/issues/5788) for tracking.

**Comment by nebhagat** [comment]
Thanks!
