### ISSUE TITLE
Bot builder template for visual studio 2019 for mac

### ISSUE THREAD

**Issue by zap7** [microsoft/botbuilder-dotnet#3689]
Please create a bot builder template for visual studio 2019 for mac. I'd like to easily create a bot using templates for v4 of the ms bot framework. It would be great if there was nice easy way to rich multi-turn create conversational flows with a bot composer like tool as well and if this was all embedded together.

**Comment by johnataylor** [comment]
@sgellock  can you comment

**Comment by sgellock** [comment]
@zap7 Thank you for opening the issue.  At this time I don't see us creating a Visual Studio extension for the Mac version of Visual Studio.  That said, we built .NET Templates that will produce the same code that the VS for Windows extension creates.  You can install and run these templates on your Mac and open the generated code using VS for Mac.  Here is a pointer to docs on how you can do this.  https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/dotnet-templates

The docs should be enough to get you going.  If you have any further questions, let us know.
