### ISSUE TITLE
[Direct Line] Microsoft.Bot.Connector.DirectLine Local on conversationUpdate

### ISSUE THREAD

**Issue by mrmokilok** [microsoft/botbuilder-dotnet#3691]
## Version
SDK Platform: .NET
SDK Version: 3.0.2
Active Channels: Direct Line
Deployment Environment: Custom Azure Bot Service, Azure App Service

## Describe the bug
Neither Directline client nor conversations.StartConversation() allows setting language/local property, in the same way the webchat.js does. This means conversationUpdate activity doesn't have valid Locale property.

## To Reproduce
Init dlClient:
var dl = new DirectLineClient(token);
dl.SetRetryPolicy(new Microsoft.Rest.TransientFaultHandling.RetryPolicy(
           new Microsoft.Rest.TransientFaultHandling.HttpStatusCodeErrorDetectionStrategy(), 0));
.
.
Start conversation:
dl .Conversations.StartConversation();

## Expected behavior
conversationUpdate activity with Locale property, in the same way as with Emulator or webchat.js (even when using directline for communication).

## Additional context
Same custom bot is used for various different channels and using a separate init event for dl is a hackish solution.

[bug]

**Comment by cwhitten** [comment]
@mrmokilok WebChat just passes the locale along with the Activity. If you construct an Activity and include the locale, it will be sent through the client.

**Comment by mrmokilok** [comment]
Yes, of course but the conversationUpdate is sent automatically and without locale.

**Comment by cwhitten** [comment]
@p-nagpal can you comment to the Direct Line behavior with locales and conversationUpdate?

**Comment by p-nagpal** [comment]
@mrmokilok @cwhitten the DirectLine channel service does not provide locale information in the ConversationUpdate messages outside the emulator. That said, this could be a useful feature addition. @mrmokilok, could we get some additional data from you?

1. In which scenario are you hoping to use the locale provided in the ConversationUpdate message? Are you able to get this locale information via other activities? For example, the Message activity will always contain a user's locale.

2. How are you integrating DirectLine client? Are you using WebChat? If WebChat, are you using the self-hosted React package or the embed link provided by the Azure Bot Service?

**Comment by mrmokilok** [comment]
In current scenario, I'm using it in web service, which interacts as an integraation client to some live chat services. And of course I did a work around, where I ignore the conversationUpdate event for directline conversations and send in my own conversations start with the locale set. As the bot can communicate with other channels as well, I see the need to build a workaround for one channels as a bug. Especially, when you could just include StarConversation method which would take proper ties.
