### ISSUE TITLE
the behavior of operations of arithmetic are inconsistent

### ISSUE THREAD

**Issue by ssss141414** [microsoft/botbuilder-dotnet#3695]
## Describe the bug
See this picture, '+' and '*' work, but '-' results a null(even though I have define user.a, user.b as int).
![image](https://user-images.githubusercontent.com/18118994/77873450-9a645800-727c-11ea-9537-b014da4b88cc.png)
![image](https://user-images.githubusercontent.com/18118994/77873454-9f290c00-727c-11ea-809d-23c173ee5734.png)

I need to add int() to '-' to make it work.
![image](https://user-images.githubusercontent.com/18118994/77873491-b831bd00-727c-11ea-8f20-3cfc4a58fabc.png)
![image](https://user-images.githubusercontent.com/18118994/77873518-c97ac980-727c-11ea-9c74-d08034e50f0b.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
I have define user.a, user.b as int, so I think I don't need to cast again.

**Comment by cosmicshuai** [comment]
The reason user.a-user.b returns null is, in Expression, we allow user to use '-' in identifiers. Users can use '#bf-activity123' as a template name, and '-${bf-activity123()}'  to call a template name as a function.
It is ambiguous whether 'a-b' is an binary operation or an viriable name under our current token rules.
So the solution should be either we will not allow using '-' in viriable names or users have to put whitespaces in minus opeator like 'a - b'. 
@vishwacsena @boydc2014 @Danieladu

**Comment by xieofxie** [comment]
> The reason user.a-user.b returns null is, in Expression, we allow user to use '-' in identifiers. Users can use '#bf-activity123' as a template name, and '-${bf-activity123()}' to call a template name as a function.
> It is ambiguous whether 'a-b' is an binary operation or an viriable name under our current token rules.
> So the solution should be either we will not allow using '-' in viriable names or users have to put whitespaces in minus opeator like 'a - b'.
> @vishwacsena @boydc2014 @Danieladu

Yeah.. the same applies for !=. Maybe we should follow common naming rules in the first place :-)

**Comment by boydc2014** [comment]
We should not allow "-" in IDENTIFIER, @vishwacsena

**Comment by vishwacsena** [comment]
@boydc2014 you mean not have composer use bf-activity as the default template name? Not sure what you mean by identifier. 

Immaterial of the composer issue, we must have user.a-user.b work without having to cast to int()

**Comment by boydc2014** [comment]
> @boydc2014 you mean not have composer use bf-activity as the default template name? Not sure what you mean by identifier.
> 
> Immaterial of the composer issue, we must have user.a-user.b work without having to cast to int()

By "IDENIFIER", i mean tempalteName, functionName or variableName, so we are going to not allow "-" in those places, "." or "_" is a recommendation

**Comment by vishwacsena** [comment]
Prefer `_`
