### ISSUE TITLE
=addProperty({} , "a" ,dialog.a) could not be executed twice

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3696]
## Describe the bug

If we begin the following dialog twice
![image](https://user-images.githubusercontent.com/2876650/77887476-3736ed80-729d-11ea-979c-a28d77bee128.png)

It will send the following error for the second set properties

Expression evaluation resulted in an error. Expression: =addProperty({} , “a” ,dialog.a). Error: a already exists

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by vishwacsena** [comment]
@xieofxie is your expectation that in both cases, we overwrite any value that already exists for that property? I do not think that is right behavior so we do not stomp over values that you set previously. 

@boydc2014

**Comment by xieofxie** [comment]
@vishwacsena I think these bugs are caused by {} is not a new local variable.

In the first case, when using {} in AddProperty for the second time, it still refers the first {} in AddProperty, so the error occurs: 'a already exists'

In the second case, when in select, I assume it could be interpreted as
```
var result = new List<object>();
foreach(var iter in indicesAndValues(dialog.tasks)){
    var local = setProperty(setProperty(setProperty({}, "Id", iter.index),"Topic",iter.value.subject);
    result.Add(local);
}
return result;
```
And all locals refer to the same {}, so result will be an array of same last task.

**Comment by boydc2014** [comment]
This is an issue the our "{}" is only tighted to one specific instance, we are fixed that in the PR above.
