### ISSUE TITLE
settings.xx could be used Send a response not Allow interruptions

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3698]
## Is your feature request related to a problem? Please describe.

For example, I would like to set a global interrupt score in settings. But it could not be used.

**Comment by vishwacsena** [comment]
@tomlm are all property values interpreted as strings? Tagging P2 given the workaround to do `=int(settings.propertyName)`

**Comment by tomlm** [comment]
This should be fixed by #2675
