### ISSUE TITLE
endOfConversation sent when root dialog of root bot completes

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#3699]
## Version
4.8.0

## Describe the bug
I have a root bot that calls a skill, similar to the [81.skills-skilldialog](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/81.skills-skilldialog) sample. When the skill replies, The [RunAsync](https://github.com/microsoft/botbuilder-dotnet/blob/65fc09fc126bdf69786fc22b925c52d0eb0dcc8a/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L31) extension method identifies the bot is running as a skill and eventually sends an `endOfConversation` when the root dialog ends. This is and unknown activity type on the Microsoft Teams channel, resulting in a `BadRequest` exception.

The `RunAsync` extension method checks if the bot is running as a skill using the [SkillValidation.IsSkillClaim](https://github.com/microsoft/botbuilder-dotnet/blob/65fc09fc126bdf69786fc22b925c52d0eb0dcc8a/libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs#L83) method. This returns true when the following conditions are met:
- the claims contain a version
- the claims contain an audience
- the audience is not equal to https://api.botframework.com
- the values of the appId claim and audience claim are different

These conditions are also true when the root bot receives the message from the skill.

For the `BadRequest` exception to occur the root dialog also must complete or cancel. In the samples this never happens, because the dialog is always restarted with a prompt. In my bot I complete the dialog and then [this piece of code](https://github.com/microsoft/botbuilder-dotnet/blob/65fc09fc126bdf69786fc22b925c52d0eb0dcc8a/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L71) is executed which sends an endOfConversation activity.

## To Reproduce
1. Clone the [81.skills-skilldialog](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/81.skills-skilldialog) sample and set it up following the steps outlined in the readme
2. Replace [line 201 in MainDialog.cs](https://github.com/microsoft/BotBuilder-Samples/blob/27c68cd6d5652b964480278ead4c49ba036a1d13/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Dialogs/MainDialog.cs#L201) with
```csharp
return await stepContext.EndDialogAsync();
```
3. Run the bot in the Emulator and choose action # 3. GetWeather
4. Notice the trace line `Dialog MainDialog has **completed**. Sending EndOfConversation`

## Expected behavior
The endOfConversation activity should not be send when the root dialog of the root bot completes and cancels.

**Comment by johnataylor** [comment]
@gabog can you comment on this issue.

**Comment by gabog** [comment]
Hi @sschutten, just so I understand, you only see the BadRequest when running on the teams channel, not on the emulator, correct?

**Comment by gabog** [comment]
Hi @sschutten, thank you for the detailed description, I am able to repro the issue when using the teams channel. We will fix this in the next release.

**Comment by sschutten** [comment]
Hi @gabog, yes, this is only on the Teams channel, not on the emulator. For now I've come up with the following workaround in the `OnEndOfConversationAsync` override of my TeamsActivityHandler implementation. Basically I remove the appid claim so the `SkillValidation.IsSkillClaim` will return false. If you have a more elegant workaround, I'm happy to hear that.
```csharp
protected override async Task OnEndOfConversationActivityAsync(ITurnContext<IEndOfConversationActivity> turnContext, CancellationToken cancellationToken)
{
    if (turnContext.TurnState.Get<IIdentity>(BotAdapter.BotIdentityKey) is ClaimsIdentity claimIdentity && claimIdentity.HasClaim(c => c.Type == AuthenticationConstants.AppIdClaim))
    {
        claimIdentity.RemoveClaim(claimIdentity.FindFirst(AuthenticationConstants.AppIdClaim));
    }

    await _dialog.RunAsync(turnContext, _dialogStateAccessor, cancellationToken);
}
```

**Comment by gabog** [comment]
Hi @sschutten, I created a PR that I think fixes the issue you are having. Once merged it will go out in the next release. 

Your workaround seems good, but you have time, try adding a copy of [DialogExtensions](https://github.com/microsoft/botbuilder-dotnet/blob/gabog/SkillDialogFnTestsUpdates/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs) to you project, rename RunAsync as RunAsync2 and see if that works.

Thanks again for reporting this!

**Comment by sschutten** [comment]
Hi @gabog, I can confirm the code change in your PR works. I had to also copy the SkillHandler, because in 4.8.0 the ConversationReference is added to the TurnState instead of SkillConversationReference. Thanks for the much more elegant solution. I'll be looking forward to the release.

**Comment by gabog** [comment]
Great, thanks for confirming @sschutten, I'll leave this issue open until the PR is reviewed and merged into master so we can track it.

Thanks again!
