### ISSUE TITLE
Prompt output format error & enhancement

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botbuilder-dotnet#3700]
## Describe the bug
When I use _**prompt for date**_, the suggestion is "**this.value[0].Value**", but when I set it to "this.value[0].Value", the result is "**your meeting is for this.value[0].Value**"
![image](https://user-images.githubusercontent.com/44257569/78648018-f7e84c80-78ed-11ea-85c1-62ac223d5b38.png)
![image](https://user-images.githubusercontent.com/44257569/78648223-47c71380-78ee-11ea-907c-1253b55b68bb.png)

I think a "=" is missed for the hint. But I'm confused that can Output Format be any string? Is there any detection for the input?

And can we have more info about the output format? When I use the the date prompt result directly, it shows the format ```[

{

"Value": "1800",

"Start": null,

"End": null,

"Timex": "PT30M"
}

]```
Can we get the info in advance, or support something like auto-complete, so that I can choose an appropriate field that I need

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
Transferring to botbuilder-dotnet and tagging @vishwacsena

**Comment by luhan2017** [comment]
@vishwacsena, I think we need to update all the examples of the schema, there is a lot of cases missing a "=" in the examples.

**Comment by vishwacsena** [comment]
chatted with @tomlm this morning. He is going through all schema updates.
