### ISSUE TITLE
On Click of "Get Started" button in Facebook Messenger, Composer code is throwing exception

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/botbuilder-dotnet#3703]
FB messenger have "Get Started" button which helps the user to initiate the conversation with the bot. When we published the code, on click of Get Started button, we are getting exception. 

## Version
I'm using the latest version of Composer.

## To Reproduce

1. Create a messenger bot using MS Bot framework
2. Configure a get started button using the REST API to FB Graph API Explorer
3. Go to the messenger and delete the conversation if you have any existing . And try to start conversation by clicking on the error

## Additional context

**Observation: ** The channel data for normal messages and the get started button is different.
ChannelData for normal messages:
{{"sender": {"id": " "},"recipient": {"id": ""},"timestamp": 1584006792263,"message": {"mid": "m_TmBzHQTfb1dxzAncC0thLmSH6DRNDyon4k8nJX8fclpZ0OBv4nCfubgtJvAhivh_awmq9kZ7SlXfh-JPTzcdlA","seq": 0,"quick_reply": {"payload": "Analyse my skin"},"text": "Analyse my skin","is_echo": false}}}

ChannelData for GetStarted button:
{{"sender": {"id": ""},"recipient": {"id": ""},"timestamp": 1584003751592,"postback": {"payload": "Get Started","title": "Get Started"}}}

Exception message: Object serialized to String. JObject instance expected.

**Comment by DavidStrickland0** [comment]
@vidyakdil Not certain if its related or not but we had a similar situation. Bot worked fine in webchannel but failed with a serialization error in Messenger and the Issue was related to the fact that Facebook invokes authentication by default while the webchat does not. Thus the user gets serialized and deserialized.
see: https://stackoverflow.com/questions/60400935/why-does-my-azure-web-app-bot-work-fine-in-some-channels-but-not-in-facebook-or/60400936#60400936

**Comment by Danieladu** [comment]
Maybe you can just add the `message` value into channelData, So ChannelData for normal messages:
{"mid": "m_TmBzHQTfb1dxzAncC0thLmSH6DRNDyon4k8nJX8fclpZ0OBv4nCfubgtJvAhivh_awmq9kZ7SlXfh-JPTzcdlA","seq": 0,"quick_reply": {"payload": "Analyse my skin"},"text": "Analyse my skin","is_echo": false}

**Comment by vishwacsena** [comment]
@vidyakdil can you try suggestion from @Danieladu and comment here if you continue to see the issue?
