### ISSUE TITLE
[QnA Maker] Active learning lowVariationFilter function

### ISSUE THREAD

**Issue by gurvsing** [microsoft/botbuilder-dotnet#3705]
## Describe the bug
Moving the check to call for LowScoreVariation, inside the function
For more detail: https://github.com/microsoft/botbuilder-dotnet/issues/3642

**Comment by vipeketi** [comment]
Fixed with https://github.com/microsoft/botbuilder-dotnet/pull/3730

**Comment by vipeketi** [comment]
Duplicate of https://github.com/microsoft/botbuilder-dotnet/issues/3642

**Comment by vipeketi** [comment]
Duplicate of #3742
