### ISSUE TITLE
Make QnA Training Thresholds Configurable

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#3706]
**Is your feature request related to a problem? Please describe.**
We would like to actively train our QnA models more in development then in production. In production we'd like to have the standard thresholds for training. While in development we'd like very low threshholds. Practically any question that has multiple answers we'd like to train.

**Describe the solution you'd like**
Be great if we could set 
ActiveLearningUtils.MinimumScoreForLowScoreVariation
ActiveLearningUtils.MaximumScoreForLowScoreVariation
QnAMakerDialog.maximumScoreForLowScoreVariation
From AppSettings.

**Describe alternatives you've considered**
Since these are currently private Constants theres not much short of a custom implementation

[enhancement]

**Comment by pchoudhari** [comment]
Thanks for the recommendation, @DavidStrickland0 . We will put this in our backlog. Will update with an ETA.

**Comment by hcyang** [comment]
Hi @vipeketi, can you update the progress, specifically an ETA as @pchoudhari mentioned?

**Comment by vipeketi** [comment]
By end of this month, I will be able to close the issue.

**Comment by cleemullins** [comment]
Unfortunatly, this issue doesn't look like it will make the R9 train. The PR continues to have feedback cycles and issues. This should land in R10.

**Comment by vipeketi** [comment]
js changes [QnAMaker] For overloaded GetLowScoreVariation js sdk changes. #2330

**Comment by somigithub** [comment]
@cleemullins 
Based on other priorities at this moment, moving this issue to backlog. No planned ETA/sprint at this moment.
Please take it out of R10 release.
