### ISSUE TITLE
 UTF-8 BOM (Byte Order Mark) is incorrectly added to the BotFrameworkHttpAdapter.processAsync raw response

### ISSUE THREAD

**Issue by adlele** [microsoft/botbuilder-dotnet#3708]
The raw Http Response for ```BotFrameworkHttpAdapter.processAsync```  has the [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark) character added in the beginning 

it looks like ``` ï»¿ ``` in the raw http response 

https://github.com/microsoft/botbuilder-dotnet/blob/65fc09fc126bdf69786fc22b925c52d0eb0dcc8a/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/HttpHelper.cs#L77

The encoding should be ```UTF8Encoding(false, false)``` instead of ```Encoding.UTF8```
like this
```using (var writer = new StreamWriter(memoryStream, new UTF8Encoding(false, false), 1024, true)) ```

**Comment by cleemullins** [comment]
Interesting bug. 

What makes the way we're doing it wrong?

**Comment by EricDahlvang** [comment]
https://tools.ietf.org/html/rfc8259#section-8.1

> Implementations MUST NOT add a byte order mark (U+FEFF) to the
>    beginning of a networked-transmitted JSON text.  In the interests of
>    interoperability, implementations that parse JSON texts MAY ignore
>    the presence of a byte order mark rather than treating it as an
>    error.
