### ISSUE TITLE
Can not access json field in sub dialog

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botbuilder-dotnet#3710]
## Describe the bug
I have Dialog A and Dialog B. In Dialog A, when I get an oauth token, and pass the token Object to B. In Dialog A, I can access the Object as ${dialog.token}, but when I use ${dialog.token.token}, the result will be null.
In dialog B:
![image](https://user-images.githubusercontent.com/44257569/78790193-c2705b80-79e0-11ea-9664-b062c9431bc9.png)
![image](https://user-images.githubusercontent.com/44257569/78790344-fb103500-79e0-11ea-975a-9f31f360bc43.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
transferred to botbuilder-dotnet and assigned @vishwacsena to look at it

**Comment by vishwacsena** [comment]
@luhan2017 I cannot repro this as a generic issue with BeginDialog. @luhan2017 can you take a look to see if this is specific to OAuth? 

```C#
var rootDialog = new AdaptiveDialog("root")
{
    Generator = new TemplateEngineLanguageGenerator(),
    Triggers = new List<OnCondition>()
    {
        new OnBeginDialog()
        {
            Actions = new List<Dialog>()
            {
                new SendActivity("Hello"),
                new SetProperty()
                {
                    Property = "dialog.token",
                    Value = "={}"
                },
                new SetProperty()
                {
                    Property = "dialog.token.token",
                    Value = "fooBar"
                },
                new SendActivity("Dialog A : I have ${dialog.token} and ${dialog.token.token}"),
                new BeginDialog()
                {
                    Dialog = "child1",
                    Options = new {
                        token = "=dialog.token"
                    }
                }
            }
        }
    }
};

var child1 = new AdaptiveDialog("child1")
{
    Triggers = new List<OnCondition>()
    {
        new OnBeginDialog()
        {
            Actions = new List<Dialog>()
            {
                new SendActivity("Dialog B : I have ${dialog.token} and ${dialog.token.token}")
            }
        }
    }
};
```

**Comment by xhr0804** [comment]
@vishwacsena thanks for the reply. "=dialog.token" works! Previouly I used the "${dialog.token}", and it failed.

**Comment by luhan2017** [comment]
Great, thanks @xhr0804, and @vishwacsena. 
As a follow up for this, I will create a sample in Composer for passing options in BeginDialog.

**Comment by vishwacsena** [comment]
Thanks all
