### ISSUE TITLE
QnaMakerDialog Volitile call of GetLowScoreVariant causing inconsistent results.

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#3714]
## Describe the bug
https://github.com/microsoft/botbuilder-dotnet/blob/e1c3048788e024929b7b51ebf927164a3283a57f/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L319-321

If IsActiveLearning is enabled response.Answers is updated to trim out all the really low responses potentially resulting in all answers being trimmed out because they are to low and no Answer at all  may be returned.

If IsActiveLearning is not enabled this never happens.
https://github.com/microsoft/botbuilder-dotnet/blob/e1c3048788e024929b7b51ebf927164a3283a57f/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L339-342
Simply returning the top result even if it is really low.

## Expected behavior
Bot would have the same answers available when active learning is enabled as when it is not.
Either the lowballs should be trimmed out regardless or included regardless.

[bug]

**Comment by pchoudhari** [comment]
Thanks for reporting this. This seems like a dup of https://github.com/microsoft/botbuilder-dotnet/issues/3706. If the settings are configurable it would solve this, right?

**Comment by DavidStrickland0** [comment]
No, In fact it will likely just make the issue more acute. 
The settings are completely ignored when IsActiveLearning =false. So reguardless of what the setting is you can get an answer with Activelearning off that you wont get with active learning on. Easiest way to see this is crank the minimum up to 90 and ask a few ambiguous questions.
Minimizing the Current code involved and it goes something like

```
if (isActiveLearningEnabled && response.Answers.Any() && response.Answers.First().Score <= maximumScoreForLowScoreVariation)
{
       response.Answers = qnaClient.GetLowScoreVariation(response.Answers);
}
if (response.Answers.Any())
{
       result.Add(response.Answers.First());
}
```
Result may well be empty if Isactivelearning is enabled while still having values if its disabled.

**Comment by vipeketi** [comment]
@johnataylor I shall be able to work on this issue in a week.

**Comment by vipeketi** [comment]
Fixing with PR #3786
