### ISSUE TITLE
null filled in value field after add/remove the content in it.

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botbuilder-dotnet#3716]
- add the input action
- input something in value field and then remove it 
- will get following errors 
![image](https://user-images.githubusercontent.com/43408889/78128621-cd5b4700-7448-11ea-86d0-3ba7bdb348fa.png)
![image](https://user-images.githubusercontent.com/43408889/78129146-b406ca80-7449-11ea-8f20-d4ef07fa3829.png)

![image](https://user-images.githubusercontent.com/43408889/78128677-e19f4400-7448-11ea-8900-3b28513b313d.png)

**Comment by vishwacsena** [comment]
@tomlm can you look at this as part of your other schema updates? The ask here is for us to verify and have a correct set of 'required' property markings for all components.

**Comment by tomlm** [comment]
I think the right way to do this is add a pattern which defines it has to be length > 0 and non-empty
