### ISSUE TITLE
Rename QnAMakerDialog2 to something more meaningful

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#3719]
## Version
What package version of the SDK are you using: master

## Describe the bug
Having a `QnAMakerDialog2` that derives from `QnAMakerDialog` is confusing and doesn't help differentiate the two classes from each other.

## To Reproduce
1. Look at the signature: https://github.com/microsoft/botbuilder-dotnet/blob/43fd9e605009794ff78b68b38e06b360a4617ebe/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/QnAMaker/QnAMakerDialog2.cs#L12
1. Error: from the name, you would have no idea when to use one over the other.
   - QnAMakerDialog2 does not supersede QnAMakerDialog, which you'd still use in a Waterfall context.

## Expected behavior
A name more like `AdaptiveQnAMakerDialog` would be more descriptive.

## Additional context
Please see related [PR 3718](https://github.com/microsoft/botbuilder-dotnet/pull/3718), where I've updated the /// comments in this file.

[bug]

**Comment by vishwacsena** [comment]
@tomlm we have LuisAdaptiveRecognizer. Would we make this QnAMakerAdaptiveDialog? Tagging this as P0 since we need to get this change in before we announce stable release or would lose the opportunity to rename this.
