### ISSUE TITLE
Image and video cards no longer get rendered in Facebook Messenger

### ISSUE THREAD

**Issue by Tiagojaduarte** [microsoft/botbuilder-dotnet#3721]
## Version
4.8.0

## Describe the bug
I am using the new (preview) Microsoft.Bot.Builder.Adapters.Facebook.FacebookHelper and image or video cards no longer seem to be shown in Facebook messenger. I noticed the serialization of attachments is now done differently and disregards any property at the **Attachment** object level (except Content).

**Source**: Microsoft.Bot.Builder.Adapters.Facebook.FacebookHelper
**Method**: ActivityToFacebook

`if (activity.Attachments != null && activity.Attachments.Count > 0)
            {
                var payload = JsonConvert.DeserializeObject<AttachmentPayload>(JsonConvert.SerializeObject(
                    activity.Attachments[0].Content,
                    Formatting.None,
                    new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                    }));
                var facebookAttachment = new FacebookAttachment
                {
                    Type = activity.Attachments[0].ContentType,
                    Payload = payload,
                };
                facebookMessage.Message.Attachment = facebookAttachment;
          }`

It seems you only pick one attachment, and you serialize the **Content** property inside attachment which disregards all other properties that can be defined at Attachment level such as mediaUrl etc..

## Expected behavior
Images and videos should be displayed in the chat on Facebook messenger.

## Additional context
I took a look at Facebook messenger API and it seems that the assets (images and videos) cannot have any more external URLs. 

Reference: https://developers.facebook.com/docs/messenger-platform/send-messages/template/media#url

They need to be previously uploaded to Facebook or using an API to add attachments and then use the attachment ID referenced in the message.

Is this something that the bot framework will address in the future?

[bug]

**Comment by jwiley84** [comment]
@Tiagojaduarte 

My apologies on the delay. I'm looking into this today.
