### ISSUE TITLE
Slack Adapter is not including the TriggerId in the Activity

### ISSUE THREAD

**Issue by T-Roth** [microsoft/botbuilder-dotnet#3724]
## Version
Microsoft.Bot.Builder.Adapters.Slack 4.8.0-rc0

## Describe the bug
The TriggerId from the request body is not being included in the activity object, so I can not open a dialog

## To Reproduce

- In Slack click a button inside of a block_action
- If you inspect the request body you will see the "trigger_id" is in there
- Check the turnContext.Activity in OnMessageActivityAsync and notice that TriggerId can not be found

## Expected behavior
I think the problem is in 
`public static Activity PayloadToActivity(SlackPayload slackPayload)`
This should should be taking in a **SlackRequestBody** param so that the TriggerId can be retrieved and mapped on to the **Activity** object that is returned

[bug]

**Comment by garypretty** [comment]
@T-Roth Fix merged into master for next release via PR #3744.  This will be included in the nightly builds from tomorrow. Thanks for reporting.
