### ISSUE TITLE
Slack Adapter is not including the Dialogs Submission values in the Activity

### ISSUE THREAD

**Issue by T-Roth** [microsoft/botbuilder-dotnet#3726]
## Version
Microsoft.Bot.Builder.Adapters.Slack 4.8.0-rc0

## Describe the bug
Give a clear and concise description of what the bug is.  

## To Reproduce

- Update code to include TriggerId in the Activity (bug [3724](https://github.com/microsoft/botbuilder-dotnet/issues/3724))
- Click a button to show a dialog in Slack
- Fill in some input fields on the dialog
- Submit the dialog
- Notice the "submission" field in the request body (contains the values from the dialog)

## Expected behavior
Submission values would be available somewhere in the Activity object

[bug]

**Comment by axelsrz** [comment]
Hey @garypretty could you give us an update on this? Thanks.

**Comment by garypretty** [comment]
@T-Roth Fix merged into master for next release via PR #3744.  This will be included in the nightly builds from tomorrow. Thanks for reporting.
