### ISSUE TITLE
support shared recognizer from parent

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3738]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I want to group a set of elements with input for clarity and reuse.

However, I can't because input requires a new recognizer in the dialog and it can't be shared from parent.

## Describe the solution you'd like

Add an 'inherited' type for recognizer.

## Describe alternatives you've considered

Actually we could load elements from file in action like
```
"actions": [
            {
              "$kind": "Microsoft.BeginDialog",
              "$designer": {
                "id": "Iwe07c"
              },
              "dialog": "AddToListOutlook",
              "options": {
                "taskContent": "${conversation.taskContent}"
              }
            },
            "some file", // <- "some file.dialog"'s content will be put here
            {
              "$kind": "Microsoft.ReplaceDialog",
              "$designer": {
                "id": "8nNkT-"
              },
              "dialog": "ShowToDo",
              "options": {
                "fromType": "add",
                "taskContent": "${conversation.taskContent}"
              }
            }
          ]
```

Composer could group elements to file and use it as a 'dialog that shares recognizer'

**Comment by vishwacsena** [comment]
@xieofxie rather than the mechanics of how, can you share a writeup on what scenarios you are looking to achieve? Thanks!

**Comment by xieofxie** [comment]
@vishwacsena I just want to make my code more compact and reusable.

For example, a mark todo dialog would have mainly 3 parts: ask for list type, ask for task content/id, do the operation and show updated list.
Each of them may have some logic operations and thus it is not just an input element.

Then I would like to pack these 3 parts to only one element so in the mark todo dialog, there are only 3 elements called sequentially. It is more easy to understand and I could do some high order logic on these 3 elements like reordering, delete or add a part. Where these parts will still use the lu/lg in mark todo dialog. Thanks

**Comment by xieofxie** [comment]
Further thought indicates that the **alternative** way fits my requirement better.
I just want to wrap actions to make my code more compact and reusable. The wrapped one should share lu, lg, dialog variables and actually they are in the same dialog but in different files.

It might be a composer issue not a sdk one.

**Comment by vishwacsena** [comment]
Thanks @xieofxie closing this. Please respond here if you believe there is a SDK gap.
