### ISSUE TITLE
enable action RepeatDialog to be able called more than once in one turn

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3742]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't repeat more than once in one turn.

Scenario: mark todo dialog has two slots list type and task content.
* When asking for task content, the user interrupted with refilling both list type and task content.
* The mark todo dialog is **repeated** to handle the list type change to verify the task content.
* However, the task content is not matched in the list and the dialog is **repeated** again to show the list of tasks for user to select

**Describe the solution you'd like**

Remove the repeat check or provide a option to turn it off.

**Describe alternatives you've considered**

**Additional context**

Repeat check https://github.com/microsoft/botbuilder-dotnet/blob/f0599ca72800c2b145ea7faed22d9bff8f297889/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/RepeatDialog.cs#L61

[enhancement]

**Comment by vishwacsena** [comment]
@xieofxie where are you calling repeatdialog? can you share a trimmed down version of your dialog? Do you have a OnBeginDialog trigger that prompts for list type and task content, a local OnIntent that detects new entities specified and then calls repeatDialog?

**Comment by xieofxie** [comment]
@vishwacsena yes you are right. And after the local onintent, the dialog will be repeated again to prompt for certain values for the wrong ones.

the code is here: https://github.com/microsoft/botframework-skills/tree/next/skills/declarative/todoskill

See the marktodo. In GetInput intent, user could refill both list type and task content and then if it could not be marked, the mark todo dialog will repeat for new task content

**Comment by xieofxie** [comment]
Hi @carlosscastro I found this issue is not like #3626. 3626 happens when loading while this happens when running.

I created a pr to add an option to enable loop so if one needs repeating multiple times, one could turn it on. What do you think? Thanks
