### ISSUE TITLE
Comparisons to ReturnType should use bit operators

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3755]
In the recent change to adaptive expressions to support multiple types including arrays, type checking has become too aggressive.  In particular this no longer works:
\# foo(property)
- ${template(property  +'Entity')}
The reason is that + is typed as Number | string and template expects string.  This should be allowed and caught at runtime if types are incorrect.

In particular this code is wrong:
if (children0.ReturnType != ReturnType.Object && children0.ReturnType != ReturnType.String)
            {
                throw new Exception(TemplateErrors.ErrorTemplateNameformat(children0.ToString()));
            }

There may be other instances as well.  Comparisons to ReturnType should use bit operators.

[bug]

**Comment by Danieladu** [comment]
It is my fault. We have changed all Returntype of Comparisons to bit operators in `Expression` but neglected the content in LG.

Maybe, we can just change the valirdation to :
```
ExpressionFunctions.ValidateUnaryString(children0);
```

Is that make sense ?
