### ISSUE TITLE
IBotFrameworkHttpAdapter should handle AppCredentials 

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/botbuilder-dotnet#3759]
**Is your feature request related to a problem? Please describe.**
Currently we are unable to use the `BotFrameworkHttpAdapter` with AAD certificate authentication.

In release [4.5.3](https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.5.3)  support for using AppCredentials and decoupling password based authentication was introduced. However it does look like the `BotFrameworkHttpAdapter` never got updated with this. 

**Describe the solution you'd like**
Have a way to use a certificate instead of a password when using the `BotFrameworkHttpAdapter`

[enhancement]

**Comment by EricDahlvang** [comment]
Hi @timotheeguerin 

It is currently possible to use CertificateAppCredentials, by overriding BuildCredentialsAsync of BotFrameworkHttpAdapter:

```cs
public class AdapterWithErrorHandler : BotFrameworkHttpAdapter
    {
        protected override Task<AppCredentials> BuildCredentialsAsync(string appId, string oAuthScope = null)
        {
            return new CertificateAppCredentials(...);
        }
    ...
    }
```

We have an issue tracking an update to improve this: https://github.com/microsoft/botbuilder-dotnet/issues/3490  Please add any suggestions to that issue.

**Comment by timotheeguerin** [comment]
Thanks Eric, that seems to do the trick.
