### ISSUE TITLE
When I run TestBot.Json, it will throw ArgumentOutOfRangeException(range.Path)

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3769]
## Version
What package version of the SDK are you using.

https://github.com/microsoft/botbuilder-dotnet/commit/241536bbf08d198c94ad4cd52955b4b8c0b89719

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
1. clone https://github.com/microsoft/botbuilder-dotnet/commit/241536bbf08d198c94ad4cd52955b4b8c0b89719
2. start TestBot.Json
3. use emulator to connect to the bot

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

Some investigation indicates when a $kind does not have custom converter, it will create a new SourceRange here, thus no range is set:
https://github.com/microsoft/botbuilder-dotnet/blob/241536bbf08d198c94ad4cd52955b4b8c0b89719/libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs#L35

[bug]

**Comment by xieofxie** [comment]
Oh.. it happens after using an emulator to connect the bot
![image](https://user-images.githubusercontent.com/2876650/79935154-c8594880-8486-11ea-994a-8b6c44c3f061.png)

**Comment by boydc2014** [comment]
Now i can repro this in master, i must run emulator and trying to connect.

**Comment by boydc2014** [comment]
I level up this as P0, @tomlm @cleemullins
