### ISSUE TITLE
make samples use Nuget packages instead of project references

### ISSUE THREAD

**Issue by Geertvdc** [Microsoft/botbuilder-dotnet#377]
I'm building a bot based on the alarmbot sample but there is a lot of code not available yet in the nuget packages which is in the repository. 

So now the only way to experiment is doing project references which i do not prefer

is it possible to do nightly packages? now the most recent package is 2 weeks old.

**Comment by drub0y** [comment]
It's a little more nuanced than it seems obviously, but I agree with this. 

I was also meaning to write an issue suggesting a move to produce nightly packages which, since I have a minute, I'll go do now as I have a couple other NuGet related things to write up as well.

**Comment by cleemullins** [comment]
+1 to this. 

We're re-doing all the samples in the next 2 weeks as part of an actual plan rather than a bunch of haphazard samples. As part of that plan, they'll be done against the packages.

**Comment by vishwacsena** [comment]
New samples will address this.
