### ISSUE TITLE
Update AdaptiveSkillDialog to use ActivityProcessed

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#3772]
## Version
What package version of the SDK are you using.

## Describe the bug
In the AdaptiveSkillDialog, since the activity is sent explicitly, I don’t understand how activityProcessed is used. 
Could we just remove that from the code and schema? Otherwise we need to expose it in Composer, and we can’t explain to user how this value take effect. 

@gabog, @tomml, @carlosscastro, @vishwacsena  

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Seems right. @tomlm @gabog @Stevenic @clearab? If we agree, we should take this for R9 to avoid breaking changes post R9 to adaptive. Alternate is to leave the property as is - will be a no-op for users. Right?

**Comment by vishwacsena** [comment]
@clearab tagging R9 so this is triaged on skills side. Please feel free to update labels per triage outcome.

**Comment by clearab** [comment]
@gabog let's review this one for triage today

**Comment by gabog** [comment]
Hi @luhan2017, we spoke with @tomlm yesterday and we decided to keep this property. I am adding logic to use it and additional doc comments in my PR that I will merge shortly as soon as the build passes.
