### ISSUE TITLE
Improve the approach to register declarative types 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3784]
The current component registration is constructed by collecting all ComponentRegistration in `referenced` assemblies. 

The issue is, if a package is not explicitly referred, it's not going to be listed as referred assemblies. So user have to somehow use the something in the assembly in order for compiler to think it's been referred. 

For example, in https://github.com/microsoft/botbuilder-dotnet/pull/3783, in order to correctly deserialize QnaMakerDialog, we have to list QnaMaker package as a project dependency, and 
`add some extra code explicitly to refer the package` , which is very awkward. like this

```C#
// Create a non-used dialog just to make sure the target assembly is referred so that
// the target assembly's component registration can be used to deserialize declarative components
var qnaDialog = new QnAMakerDialog();
System.Diagnostics.Trace.TraceInformation($"Touch ${qnaDialog.GetType().ToString()} to make sure assembly is referred.");
```

Can we switch to looking for assembly that been copied to the same folder, instead of the current strictly referenced assembly?  or create some explicit interface like "Activate" or "Register" as a convention instead of the current implicit way?

**Comment by vishwacsena** [comment]
Fixed.
