### ISSUE TITLE
HttpRequest action supports read binary data

### ISSUE THREAD

**Issue by ssss141414** [microsoft/botbuilder-dotnet#3793]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Currently in HttpRequest action, it only supports to get responses as string.
```
object content = (object)await response.Content.ReadAsStringAsync();
```
But sometimes I need to get response as byte[]. This happens when I try to get a image, or other resources. Like this:
```
Stream streamToReadFrom = await response.Content.ReadAsStreamAsync()
// stream.toarray(), converts to byte[] 
```  
**Describe the solution you'd like**

Can you please support this? 
Maybe user can select 'get as string'/ 'get as binary'. And in HttpRequest action, do different operations according to user's choice. 
And if it is hard to save byte[] to response.Content, maybe you can encode them. So user can get original byte[] by decoding. It's better than always ReadAsStringAsync.

**Comment by cleemullins** [comment]
I removed the "Changes Required" tag on the PR, as it's ready for review again.
