### ISSUE TITLE
DCR: Relax Binary Compat Rules around Minor version changes

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#3799]
Today the C# SDK maintains binary compatibility across all minor and patch version changes. 

This DCR proposes changing this requirement to the following:
# Patch Version
Within a given minor release ("4.7.0, 4.7.1, 4.7.2") all versions would be binary compatible. 

# Minor Version 
Across minor releases, source code combability would be maintained. This means could would need to be re-compiled moving from 4.6.0 to 4.7.0.

**Comment by stevengum** [comment]
@cleemullins do you have a status update?

**Comment by mrivera-ms** [comment]
There is a parallel stream of work addressing this.
