### ISSUE TITLE
Add goodbye middleware

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#38]
Another important piece of middleware is a component that is always listening for the user to say "goodbye" or "I'd like to start over". When it detects either of these intents it should first clear the conversation sand then send a reply to the user or return them to the beginning of the conversation.

This could be done as a sample or middleware but it's another important feature that every production bot needs to help combat users getting into a stuck state.

**Comment by cleemullins** [comment]
Per discussion, this is a sample, not a change to the framework.
