### ISSUE TITLE
Null [From] on [Activity] Results in NRE during call to QnaMaker.GetAnswersRawAsync

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#3814]
Current:
QnaMaker's GetAnswersRawAsync has an unvalidated dependency on the From Property of the TurnContext.Activity. If "From" is Null OnQnaResultsAsync throws a NRE.

Expected:
ArgumentException stating that From can not be null;

https://github.com/microsoft/botbuilder-dotnet/blob/4195f66845ebbdf53492824cc03ead11427cb28e/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMaker.cs#L257

**Comment by hcyang** [comment]
Hi @DavidStrickland0, we are looking into this issue. Will update the status. Thanks for reporting.

**Comment by vishwacsena** [comment]
@garypretty this appears to be related to instrumentation. Can you comment? 

@pchoudhari can you please follow up and help drive this to closure? Thanks!

**Comment by garypretty** [comment]
There does need to be a null check here on the From property - this is what the TelemetryLoggerMiddleware does. @vishwacsena @pchoudhari I can pick this up and get a fix into PR.

**Comment by vishwacsena** [comment]
Thanks @garypretty
