### ISSUE TITLE
Re-Enable CosmosDB tests that have been disabled

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#3816]
The CosmosDB tests were disabled in PR #3815 due to timouts starting the cosmosdb emulator. 

Need to evaluate *why* we're seeing timeouts and then re-enable the tests.

**Comment by tomlm** [comment]
The build yaml file has had the powershell plugin which is supposed to install cosmosdb commented out.  It was running for 4 minutes and then timing out.  This is probably the core issue.

**Comment by mrivera-ms** [comment]
@mdrichardson please sync up with the SDK team before starting this task.

**Comment by mdrichardson** [comment]
@mrivera-ms Anybody in particular?

**Comment by mdrichardson** [comment]
Per @mrivera-ms, this one is currently blocked

**Comment by gabog** [comment]
We will not address this at the moment.
