### ISSUE TITLE
Value set form disappeared

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botbuilder-dotnet#3836]
## Describe the bug
Value set form disappeared, is this a bug or by design?
![image](https://user-images.githubusercontent.com/44257569/80561575-834d8d00-8a17-11ea-82ec-93c45b74d51d.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by vishwacsena** [comment]
@tomlm, @chrimc62  `value` property is missing from `ChoiceInput`. Need the following added. 

```json
{
    "value": {
                    "$ref": "https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/definitions.schema#/definitions/booleanExpression",
                    "title": "Value",
                    "description": "'Property' will be set to the value of this expression unless it evaluates to null.",
                    "examples": [
                        true,
                        "=user.isVip"
                    ]
                }
}
```
