### ISSUE TITLE
NumberInput - outputFormat property has no role defined, but the examples are stillexpression.

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/botbuilder-dotnet#3839]
outputFormat property in NumberInput is a string without $role:expression, but the examples are expressions.

"outputFormat": {
                    "title": "Output format",
                    "description": "Expression to format the number output.",
                    "examples": [
                        "=this.value",
                        "=int(this.text)"
                    ],
                    "type": "string",
                    "pattern": "^.*\\S.*"
                },

**Comment by cleemullins** [comment]
Our group-think settles on "Can we update the description to make this more clear?" as the various solutions all have pros/cons.

**Comment by sangwoohaan** [comment]
That goes to every single property fields we have :)

**Comment by vishwacsena** [comment]
@sangwoohaan can you comment on what you would like for the UX to be? In composer, it's not clear if you are expecting a drop down box with number and expression show up in the UI. Can you clarify?
