### ISSUE TITLE
Nightly build emits semver errors in Devops

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#3843]
Variations on this error shows up 4 times in the nightly build. 

> [error]C:\hostedtoolcache\windows\dotnet\sdk\3.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): Error NU5105: The package version '4.9.0-preview.200430-126753' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter. This message can be ignored if the package is not intended for older clients.

![image](https://user-images.githubusercontent.com/1165321/80743472-da179d00-8ad1-11ea-9178-c127192598b7.png)

**Comment by BruceHaley** [comment]
"Older clients" means "NuGet clients older than v4.3", per [this doc](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5105). Full Semver 2.0.0 description is [here](https://github.com/NuGet/Home/wiki/SemVer-2.0.0-support).

**Comment by BruceHaley** [comment]
NuGet 4.3 was released ~08/14/2017. Visual Studio 2017 15.3 RTW comes with NuGet 4.3 RTM. I read that to mean users of VS 2015 would not be compatible with Semver 2.0.0.

**Comment by mrivera-ms** [comment]
@cleemullins, I am not seeing these errors in the nightly builds. According to [this PR,](https://github.com/NuGet/NuGet.Client/pull/3226) this error has been removed from NuGet.Client. If there are still errors, could you please point me to the build?

**Comment by mrivera-ms** [comment]
@stevengum Is this still an issue? I am not able to find the build that is producing semver errors. Please see my previous comment.

**Comment by BruceHaley** [comment]
This was all fixed on 4/30. The builds fixed were:
Revert the preview version formatting containing a dot (Semver 2.0.0). In these active builds:
v	SDK_v4\builds\AI\BotBuilder-NetCoreTemplate-VASkills-daily.json
v	SDK_v4\builds\DotNet\BotBuilder-DotNet-Signed-yaml\BotBuilder-DotNet-Signed-yaml.json
v	SDK_v4\builds\DotNet\LegacyVersions\BotBuilder-DotNet-4.2-CI-PR.json
v	SDK_v4\builds\DotNet\LegacyVersions\BotBuilder-DotNet-4.5-CI-PR.json
v	SDK_v4\builds\DotNet\LegacyVersions\BotBuilder-DotNet-4.5-Signed.json
v	SDK_v4\builds\DotNet\LegacyVersions\BotBuilder-DotNet-4.7-Signed.json
