### ISSUE TITLE
[4.8.1 bot.builder] Bot with skills does not work in DL Speech channel, Skill results do not make it back to the channel.

### ISSUE THREAD

**Issue by pavolum** [microsoft/botbuilder-dotnet#3844]
## Version
4.8.1

## Describe the bug
there is a bug in 4.8 bot.builder that results in skills responses to not make it back to a DL Speech channel. I have debugged the SDK code and believe I have found the culprit. 

For some context, the skill result is correctly passed back to the VA and the VA runs SDK code to pass the skill result to the DL Speech channel. It is in this SDK code where an error arises.

In SkillHandler.ProcessActivityAsync we grab the skillConversationReference from memory and in speech scenarios the skillConversationReference.OAuthScope is always null. For some reason, this value is not stored in memory/populated in speech scenarios. When this same code is run in a non DL Speech setting (i.e. emulator) the OAuthScope value is always populated.

A null skillConversationReference.OAuthScope value leads to errors later in the pipeline (outlined later in the email) which leads to the channel not getting a response and being viewed as a server error.

When I manually set skillConversationReference.OAuthScope to AuthenticationConstants.ToChannelFromBotOAuthScope in this scenario, the problem is resolved. Not to say that this is the solution but more to confirm that the null OAuthScope in speech scenarios is in fact the culprit. 

I figured I would send over these additional findings to help you implement whatever fix is best. I would submit a PR myself but am not sure the ideal fix. Let me know if I should create a GH issue as well and I can add all these details there.

Code walk through:
1.	SkillHandler.ProcessActivityAsync we grab the skillConversationReference from memory
2.	Which we use for parameter values later in the function to call _adapter.ContinueConversationAsync, note the skillConversationReference.OAuthScope is used for the 'audience' param in ContinueConversationAsync
3.	In ContinueConversationAsync there is a null check for audience which throws an exception and leads to the skill result to never make it to the channel and appear as an internal server error

## To Reproduce
Run a bot with a connected skill in a DL Speech context using bot.builder version 4.8.1. Skill responses will not make it back to the DL Speech channel.

[bug]

**Comment by stevengum** [comment]
@gabog, @pavolum any updates? Has using `DeliveryModes.ExpectReplies` helped in addressing this situation?

___

For public note: any Skill Callers that require affinity\* should use `DeliveryModes.ExpectReplies` for `Activity.DeliveryMode` to ensure that the Skill's responses are returned to the correct Skill Caller.


\* (e.g. Skill Callers that immediately need the Skill's response, or are using WebSockets)

**Comment by gabog** [comment]
we need to research this more.
yesterday we switch to delivermode and that workaround the auth issue (which is still an issue because he is using a single server and it should work) but the directline speech channel is not receiving the message back. We need to take a closer look.
Patrick has a workaround for his demo but we still need to address this.

**Comment by gabog** [comment]
Hi @pavolum, I tried to repro the issue in my environment and it seems to work there, we need to take a closer look offline.

**Comment by pavolum** [comment]
I am closing out this issue, below is some context:

The original issue I posted is not valid as a bot with a skill in DL Speech should never run through SkillHandler.ProcessActivityAsync. When an activity is passed from the VA to a skill in a DL Speech 
the following needs to be done to ensure correct behavior: 
- The VA needs to do a deep copy of the incoming activity 
- Change deliveryMode of the copy to ExpectReplies
- Forward the copy to the skill
The original activity to the VA needs to be preserved with a null deliveryMode. 

Ideally the channel would set these fields accordingly so every bot dev does not need to add a channel conditional and change delivery mode accordingly. @gabog has reached out to the DL Speech folks to let them know about this.

**Comment by pedrocunha87** [comment]
Hi, 

This was already reported to the DL Speech team?
How can i track this issue?

Thanks.
