### ISSUE TITLE
Cleanup core C# Adapters (BF Adapter and related)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#3848]
Via @johnataylor:
> we want to rewrite/refactor/cleanup the js and C# bf adapters

**Comment by johnataylor** [comment]
The initial plan here is to make a stepwise improvement to our unit test coverage in this area before we do any refactoring.

**Comment by johnataylor** [comment]
We are working on units tests in R10. Any refactoring is R11.

**Comment by mrivera-ms** [comment]
Closing because this is being handled in other CloudAdapter work.
