### ISSUE TITLE
[Adaptive] Declarative adaptive dialogs (composer dialogs) do not work with non adaptive dialogs

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3854]
## Version
Latest master

## Describe the bug
This sample used to work but I no longer know how to get a V4 waterfall/ custom dialog based bot to work with adaptive dialogs. 

## To Reproduce
1. Run [this sample][1]
2. Connect to bot in Emulator
3. Answer first two prompts (first name, last name)
4. The sample is set up to start the adaptive dialog as step 3. This fails. 

## Expected behavior
Bot works E2E.

[bug]

[1]:https://github.com/microsoft/botbuilder-dotnet/tree/vishwac/r9-final/samples/19.integrating-composer-dialogs

**Comment by boydc2014** [comment]
Here is what i found after debugging into it. 

The bot fails at getting languageGeneratorManager from dialogContext.Services
![image](https://user-images.githubusercontent.com/3829387/80858564-869d7e80-8c8c-11ea-8d0b-2c301bf8fd85.png)

line 41 result in null after excecution. 

The reason LanguageGenratorManager is dc.Services is that in DialogContext.Child.Get
![image](https://user-images.githubusercontent.com/3829387/80858614-e09e4400-8c8c-11ea-98ee-b499bd4a1962.png)

this samples hits line 114, and this Container.CreateChildrenContext won't inherit the Services from parent dc. 

Underhood, line 114, will call CreateChildrenContext in ComponentDialog.CreateChildrenContext, inside, it will call createInnerDc, and calls new DialogContext which created a new dc with previous dc's Services.

The proper fix to me is to inherit Services in this case, either fix in CreateChildrenContext or inside CreateInnerDc will probably work.

During the debugging process, i found it's somewhat confusing how those dc are organized toghether.  Especially when i saw
1.  this Get method is creating new context objects (is this an anti-patttern)?  
2 This GetChildrenContext is called by GetActiveDialogContext, and called by SendStateSnapshotTraceAsync, this make me feels very confused about the lifecycles of dialogContext, seems like the dialogStack is already formed and run well, the dialogContext is created in a "SendingSnapshot" step, which i assume it should not create anything

cc @tomlm
