### ISSUE TITLE
UserState in AdapterExtensions.UseState should not be required

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#3859]
The [AdapterExtensions.UseState()](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/AdapterExtensions.cs) method introduced by the adaptive refactorings takes a conversation state and a user state parameters, conversation state is required for dialogs but userstate should not be required (may developers don't use user state),

This extension method and the UserStorage extension methods are new from Adaptive and I am not clear on the implications of not setting UserState.

**Comment by cleemullins** [comment]
@tomlm is working on a PR now. Closing by lunch.
