### ISSUE TITLE
Merge 4.9 into master

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#3884]
PR #3882, #3892, #3891 needs to be cherry-picked into master.

https://github.com/microsoft/botbuilder-dotnet/pull/3882
https://github.com/microsoft/botbuilder-dotnet/pull/3892
https://github.com/microsoft/botbuilder-dotnet/pull/3891
https://github.com/microsoft/botbuilder-dotnet/pull/3893

**Comment by tomlm** [comment]
don't cherry-pick, just merge 4.9 => master to pick this up.

**Comment by stevengum** [comment]
https://github.com/microsoft/botbuilder-dotnet/pull/3891 will also need to be merged into master

**Comment by stevengum** [comment]
#3890 or another PR should pick up the PR that addresses https://github.com/microsoft/botbuilder-dotnet/issues/3889
