### ISSUE TITLE
LG templates not correctly parsed in certain cases

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3885]
Input: 

![image](https://user-images.githubusercontent.com/3829387/81322637-de8e1800-90c6-11ea-95c5-a0c5ec20b4b0.png)

expected this is one template with a multiple-line mode

actually we get two templates. 

and adding \ before # won't work in multi-line case.

we could either parse this smartly, or make sure \# works in multi-line mode.

**Comment by ayenisholah** [comment]
Hi, I am interested in helping but don't know how to begin.

**Comment by boydc2014** [comment]
> Hi, I am interested in helping but don't know how to begin.

Thanks @ayenisholah. I don't know if you are familiar with botframework SDK code or not. My recommended approach is 

* Have the whole solution setup and running
* Get a sense of what's LG, maybe run some tests, and check some docs here  https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation
* Check how LG do parsing, it's in LanguageGeneration package, more specifically it should be related to problem in LGTemplateParser.g4 and LGTemplateLexer.g4
* Those files are written in Antlr, you might want to check how Antlr works
* Once you become famailar with LG and Antlr, you are good to go to solve this. 

Again thanks, and looking forward for your contribution, since we have a releasing schedule, so if you want to take it up, we are expecting to have updates in 2 or 3 weeks.

**Comment by ayenisholah** [comment]
> > Hi, I am interested in helping but don't know how to begin.
> 
> Thanks @ayenisholah. I don't know if you are familiar with botframework SDK code or not. My recommended approach is
> 
> * Have the whole solution setup and running
> * Check out what's LG, maybe run some tests, and check some docs here  https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation
> * Check how LG do parsing, it's in LanguageGeneration package, more specifically it should be related to problem in LGTemplateParser.g4 and LGTemplateLexer.g4
> * Those files are written in Antlr, you might want to check how Antlr works
> * Once you become famailar with LG and Antlr, you are good to go to solve this.
> 
> Again thanks, and looking forward for your contribution, since we have a releasing schedule, so if you want to take it up, we are expecting to have updates in 2 or 3 weeks.

Thank you @boydc2014. I would these steps and start working on it ASAP.

**Comment by boydc2014** [comment]
> > > Hi, I am interested in helping but don't know how to begin.
> > 
> > 
> > Thanks @ayenisholah. I don't know if you are familiar with botframework SDK code or not. My recommended approach is
> > 
> > * Have the whole solution setup and running
> > * Check out what's LG, maybe run some tests, and check some docs here  https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation
> > * Check how LG do parsing, it's in LanguageGeneration package, more specifically it should be related to problem in LGTemplateParser.g4 and LGTemplateLexer.g4
> > * Those files are written in Antlr, you might want to check how Antlr works
> > * Once you become famailar with LG and Antlr, you are good to go to solve this.
> > 
> > Again thanks, and looking forward for your contribution, since we have a releasing schedule, so if you want to take it up, we are expecting to have updates in 2 or 3 weeks.
> 
> Thank you @boydc2014. I would these steps and start working on it ASAP.

Thanks, @ayenisholah, i mean, no pushing, and this issue is somewhat advanced even in lg parsing, and also, we will have an engineer to start fixing this in JS side, since we have customer reported on JS side for this, maybe his solution could (if sooner) can help you with some references.

**Comment by Danieladu** [comment]
hi,  @ayenisholah We are very appreciate that you can voluntarily help us complete this feature. 

For the user has a requirement for the js version, so I firstly completed this feature on the js side and ported it to C# later. The link is here: #3944. You can take a look and give some suggestions if you are interested. 

Of course, you can continue go through your solution according to your own ideas, we will also review your solution carefully.
