### ISSUE TITLE
Don't require generating Document XML by default

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#390]
Related to #389, we shouldn't require generating document XML by default. It's not a free operation and it does slow down the inner loop for the developer who might just be trying to rapidly prototype or fix bugs and run tests.

The same options laid out in #389 are applicable for this, just that we'd be talking about the `<DocumentationFile>` build property instead.

**Comment by JonathanFingold** [comment]
PR #379 creates a separate documentation config, and removes any of the document generation flags from the debug config that I added earlier.

**Comment by cleemullins** [comment]
This is blocked on a minor merge. @JonathanFingold  - if you can fix that quickly, I can get it merged in.

**Comment by JonathanFingold** [comment]
@cleemullins working on it. ETA ~20 minutes, couldn't merge subsequent changes cleanly.
