### ISSUE TITLE
"Object reference not set to instance of object" error when creating a new text input

### ISSUE THREAD

**Issue by timoconnellaus** [microsoft/botbuilder-dotnet#3901]
## Describe the bug

"Object reference not set to instance of object" error shown in chat window in bot framework emulator when a input is added to a bot - text inputs on sample bots work without this error

## Version

a7d013b

## Browser

I'm using "BotFramework-Composer-0.0.1-windows-setup.exe" windows desktop app

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new echo bot
2. Create a text input
3. Set bot asks to "What is your name"?
4. Set property to "dialog.name"
5. Run the bot locally using the emulator
6. The bot will work as expected but following the user entering a response to "what is your name"? it will return "object reference not set to instance of object"

The issue also occurs for other input types - tested on date and multiple choice

This issue can also be replicated by creating a sample bot "AskingQuestionsSample" and adding a new text input. The questions that already exist in the bot created from the template will work as expected - but adding a new text input will trigger the error to happen.

## Expected behavior

The expected behaviour is that the error will not occur

## Screenshots

![image](https://user-images.githubusercontent.com/3151605/81492526-e2df4e80-92db-11ea-84b1-1157c12812d0.png)

![image](https://user-images.githubusercontent.com/3151605/81492530-e83c9900-92db-11ea-9244-8c5db99b08b8.png)

![image](https://user-images.githubusercontent.com/3151605/81492541-06a29480-92dc-11ea-946f-65883a773f0d.png)

![image](https://user-images.githubusercontent.com/3151605/81492480-6ea4ab00-92db-11ea-8684-e1b1f5347910.png)

![image](https://user-images.githubusercontent.com/3151605/81492478-63517f80-92db-11ea-9152-5bc494510b93.png)

**Comment by luhan2017** [comment]
@vishwac, @tomlm , I think Foreach should follow the C# foreach funtionality, which you can't update the itemList inside the loop. this is a bug that we can fix in the sdk side.

**Comment by timoconnellaus** [comment]
You're welcome. Thank you for looking into the issue so quickly

**Comment by timoconnellaus** [comment]
@luhan2017 I also get the error in other scenarios:

- When I put the text input before the for loops in the greeting (ConversationUpdate activity)
- When I put the text input in another dialog that is started in the greeting before the for loop

The reason I'm trying to set a variable is that I want to make the greeting dynamic based on the results of a HTTP request. I also tried using the begin dialog event to set the variables. This ran without an error but doing this seemed to trigger another problem - the greeting would not run at all.

**Comment by luhan2017** [comment]
@timoconnellaus , could you try this:

Add a SetProperty step at the beginning of the Greeting trigger such as dialog.MembersAdded = turn.Activity.MenbersAdded.

Then update the ForEach loop item list to dialog.membersAdded.

An example:
![image](https://user-images.githubusercontent.com/32191031/81635895-01ad2480-9445-11ea-9bb6-0144db03099d.png)

**Comment by timoconnellaus** [comment]
@luhan2017 that didn't seem to work. I tried changing the greeting dialog as suggested then did the following tests:

- added a prompt at the start of the greeting - error occurred
- added a prompt inside the loop - error occurred
- triggered a separate dialog at the start of the greeting + sent a response in the greeting - no error but the response in the greeting never appeared

Perhaps I'm doing something wrong? 

If you wanted to debug directly with me I'm happy to help. I'm a guest on the Microsoft MS Teams tenant tim@portt.com https://teams.microsoft.com/l/team/19%3a3d0c4777ce2a400c9e8092064311b1db%40thread.skype/conversations?groupId=2c99fb5d-ccdb-4258-959d-e31f9ebf4139&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by gabog** [comment]
Hi @luhan2017, what is the status of this issue?

**Comment by luhan2017** [comment]
@gabog  My PR is still open and waiting for review, would you mind to help review it?  :)

**Comment by luhan2017** [comment]
@timoconnellaus ,  I've tried to open that link you shared, but don't know how to proceed, do you still need help on this?

**Comment by timoconnellaus** [comment]
@Luhan2017 No it's OK. I have taken the logic out of the greeting for now - once the PR is merged to master I will check it again

**Comment by luhan2017** [comment]
@timoconnellaus Sorry that we decide to not fix this issue, we recommend you don't use turn memory + prompts under foreach action. You can always mitigate this by assigning the turn memory to a dialog memory and use that in the foreach action.

**Comment by mrivera-ms** [comment]
Closed as No Fix.
