### ISSUE TITLE
Clarify comparisons for null

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3902]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Since null is supported in comparisons, its behavior should be documented and tested.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by gabog** [comment]
Hi @luhan2017, can you close this issue if it is done? 

Thanks
