### ISSUE TITLE
Replace AsyncUsageAnalyzers with Microsoft.VisualStudio.Threading 

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#3905]
https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/ is the GA replacement of alpha https://www.nuget.org/packages/AsyncUsageAnalyzers/

[enhancement]

**Comment by gabog** [comment]
TODO: Check if this is not addressed by just enabling Roslyn FxCop analyzers on the solution and close it if it does.

**Comment by gabog** [comment]
This should be probably be addressed as part of #2367

**Comment by EricDahlvang** [comment]
Reopening, since this does not appear to have been done in R10.  We are still using `<PackageReference Include="AsyncUsageAnalyzers" Version="1.0.0-alpha003">` in build.props

**Comment by gabog** [comment]
Will this package throw warnings when you don't use the Async suffix? I didn't remove AsynUsageAnalyzers when I ported to FxCop analyzers because I couldn't find any other library that would help us with enforcing this naming convention.

**Comment by EricDahlvang** [comment]
@gabog   It looks like the Microsoft.VisualStudio.Threading library will help with enforcing the async suffix:
https://github.com/microsoft/vs-threading/blob/00ed5e39a70268b4a16bda6d100125e8a39bef22/src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD103UseAsyncOptionAnalyzer.cs#L105

```cs
if (methodSymbol != null && !methodSymbol.Name.EndsWith(VSTHRD200UseAsyncNamingConventionAnalyzer.MandatoryAsyncSuffix) 
```

I do not personally have experience with this library.  I had opened this issue because I noticed https://www.nuget.org/packages/AsyncUsageAnalyzers/ has not been updated since 2015 while https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/ is regularly maintained, as the documentation states this is a replacement for the alpha AsyncUsageAnalyzers.  Is there any reason we would not want to try this new library?  Have you tried it and found it to be missing something?

**Comment by gabog** [comment]
Hi Eric, AsyncUsageAnalyzers are used only during design time and the generated assemblies don't depend on it. Adding  Microsoft.VisualStudio.Threading would generate a dependency on the generated assemblies, not sure if we want to do that unless we use them extensions there. 

We could try adding Microsoft.VisualStudio.Threading.Analyzers with PrivateAssets and see if that gives us the checks we need without generating a dependency to other devs but we need to test that:

![image](https://user-images.githubusercontent.com/12264946/91873672-4c96b600-ec47-11ea-9135-1e23babd5d38.png)

**Comment by gabog** [comment]
I played with adding `Microsoft.VisualStudio.Threading.Analyzers` and I think it may be good to do this change if time permits (the AsyncUsageAnalyzers project in github states that we should use Microsoft.VisualStudio.Threading going forward).

Setting is as P2 for now.

**Comment by mrivera-ms** [comment]
Per conversation with @gabog , this is being removed from R11.

**Comment by mrivera-ms** [comment]
@JuanAr please sync up with @gabog before you start this task.
