### ISSUE TITLE
Unknown Intent handler confusion with multi-turn QnAMakerDialog

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-dotnet#3908]
## Version
4.9.0-rc4

## Describe the bug
When using `QnAMakerDialog` within a Composer dialog, the unknown intent handler is triggered when when answering a multi-turn QnA prompt.

If you ask a question that has follow-on prompts, these options are shown. The user then chooses an option (clicks the button or types) and the fallback answer (Sorry, I did not find an answer) is shown (courtesy of the unknown intent handler) before the actual QnA is then shown.

## To Reproduce
1. Create a multi-turn KB item in QnAMaker
2. Configure QnAMakerDialog inside composer
3. Configure an Unknown Intent handler that sends a "don't understand message"
3. Test a multi turn scenario and observe two responses, one from unknown intent handler and one from QnAMaker.

## Expected behavior
- Unknown intent handler doesn't fire if you are in progress with a qnamaker multi-turn dialog

### QnAMaker Editorial
![image](https://user-images.githubusercontent.com/33519520/81659325-842be900-9431-11ea-9690-ce47a9bd38f2.png)

### QnaMakerDialog experience
![image](https://user-images.githubusercontent.com/33519520/81659155-5ba3ef00-9431-11ea-81e0-1c3902582358.png)

## Additional context
- Assuming a filter on the unknown intent handler to know if QnAMakerDialog is still active might be the workaround?

[bug]

**Comment by darrenj** [comment]
Turns out a unhandled intent trigger was firing on the (second) response to a in-progress QnAMaker dialog resulting in a "unknown utterance" message being responded and **then** the QnAMAker dialog resumes hence the confusion.

**Comment by cleemullins** [comment]
@tomlm, I believe this was fixed by the PR, and that you also merged 4.9 back into master. 

Can we close this issue out?

**Comment by darrenj** [comment]
@ryanlengel validated. Thanks!
