### ISSUE TITLE
NuGet packages should all build to a common artifact directory when building locally

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#391]
## Problem
Right now the projects are all using the default option of having the `.nupkg`  dump out to the `\bin\<configuration>` folder. This is typically "ok", but the problem comes when you're doing local development within the solution and cutting a new build of the packages that you then want to import into a separate application that you're developing locally. In this solution's case we have ~10 projects that are producing packages and you would have to set up NuGet folder based package sources for each one of those ~10 `\bin\<configuration>` folders in order to consume them those packages.

## Proposal
Consider adding the `<PackageOutputPath>` property to each project and then setting that to point to something like `$(SolutionDir)\artifacts\$(Configuration)\packages\`.

> NOTE: if we do this we'd also want to make sure there is an `artifacts` entry in the `.gitignore` file to ensure its contents will not ever be considered for adding to the repo by git.

It would be remiss to not point out that `$(SolutionDir)` is problematic for automated builds and we'd probably might want to handle how packages are collected completely differently in an automated build situation anyway, so we'd probably want to add a condition to the `<PackageOutputPath>` property so it only actually applies for local builds. 

So the final property should probably end up looking something like this:

```XML
<PackageOutputPath Condition="'$(SolutionDir)' != ''">`$(SolutionDir)\artifacts\$(Configuration)\packages</PackageOutputPath>
```

Doing this will allow locally developed applications to set up a single, predictable local NuGet feed to consume all the latest versions of the packages produced during local development.

**Comment by cleemullins** [comment]
+1

**Comment by drub0y** [comment]
A separate batch file should not be needed to solve this problem and doesn't work as nicely with the inner loop of development (e.g. just building the projects/solution in VS). PR #432 was trying to solve this in a pure MSBuild sense and already worked for local builds, it's just that the VSTS build needed to be updated to override the find the packages and we didn't have time for that before build.

I would suggest reverting the separate batch file and focusing on getting the VSTS build to set the `PackageOutputPath` variable explicitly and then we can catch #432 up (e.g. `rebase` or completely redo it if easier at this point) for local builds. The only other thing I would change about #432's approach looking at it now is that it should have an additional `Condition` check to make sure `$PackageOutputPath = ''` before bothering to even do what it's currently doing so that you can override it if you wanted to.

**Comment by yochay** [comment]
@drub0y  can you please validate and close?
