### ISSUE TITLE
Build status Badges are missing 

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#3917]
![image](https://user-images.githubusercontent.com/11055362/81842143-5eb9e080-9500-11ea-8ae8-3e0a8a7f1f6d.png)

[bug]

**Comment by BruceHaley** [comment]
This should do it: PR: Add badges for Win functional tests and Linux functional tests #3950 https://github.com/microsoft/botbuilder-dotnet/pull/3950
View the results here: https://github.com/microsoft/botbuilder-dotnet/tree/BruceHaley-patch-1

**Comment by EricDahlvang** [comment]
Thanks @BruceHaley !
