### ISSUE TITLE
ActivityTypes.Suggestion, ISuggestionActivity, and Activity.AsSuggestionActivity

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#392]
Is **suggestion** a valid activity type?
- It's defined in the -dotnet repo, but it is only referenced in a couple tests.
- It's also defined in the -js repo, and is similarly elusive.
- It's defined in the [swagger file](https://github.com/Microsoft/botbuilder-dotnet/blob/f41ab1ac52ddd7c153ad63c23d9242b6f753b268/libraries/Swagger/ConnectorAPI.json#L1694), which I guess is why it's defined here.
- There's no v3 documentation for such an activity type.

If it is valid, what is its intended usage?

**Comment by cleemullins** [comment]
@JonathanFingold 

I've reached out to @dandriscoll and the Protocol folks to get this answered. Personally, I've not seen this Activity type before, but it's certainly in the Swagger file.

**Comment by vishwacsena** [comment]
Closed offline (chris w/ jonathan)
