### ISSUE TITLE
onTeamsMemberAdded throws 502 when bot is added

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#3922]
When a bot receives an onTeamsMemberAdded event where the member added was the bot, a 502 error is thrown, which results in this event never being fired.

Cause:
The event calls the getMember API, which is the source of the 502. This API cannot be passed a bot ID.

Fix:
Check to see if the member added is the bot, and if it is return a truncated TeamsChannelAccount.

**Comment by EricDahlvang** [comment]
Fixed 4.9 by https://github.com/microsoft/botbuilder-dotnet/pull/3923

Cherry-pick to master: https://github.com/microsoft/botbuilder-dotnet/pull/3924
