### ISSUE TITLE
Script component to run adaptive functions

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#3941]
## Is your feature request related to a problem? Please describe.

Sometimes you need to run a script that calculates complex data. This can contain many lines of adaptive functions. Currently I abuse Set Properties to do this, whereby each property is a 'line of code'.

This can then be something like;
this.variable = int(turn.value)
this.variable2 = int(turn.value2)
this.variable3 = sub(this.variable, this.variable2)
turn.result = this.variable3

## Describe the solution you'd like

It would be really useful if there was the possibility to run a script that lets you do this with multiple lines and then just updating turn.result or anything else. For many usecases having just adaptive functions would be enough. For tougher thing you could use C# code with the codeAction component later on.

Something like this;
var variable = int(turn.value)
var variable2 = int(turn.value2)
var variable3 = sub(this.variable, this.variable2)
turn.result = this.variable3

**Comment by vishwacsena** [comment]
Thanks @cxbuilders. With setProperties and turn scope you already can achieve this. Can you clarify if you have an unmet need with SetProperties action or is this more of a preference to be able to write a piece of script that helped? As you pointed out, you can use codeActions. Another option of-course if these are complex or rather intensive/ extensive would be to use functions.

@Stevenic may be another good use case for a JavaScriptAction?

**Comment by cxbuilders** [comment]
@vishwacsena I agree that it is possible. However I feel there is a gab between a custom action and using adaptive functions in set properties. By allowing to run an adaptive script this would be perfectly for the scenarios where a custom action is too much and set properties is too little. Using multiple set properties to mimic multiple lines of a script is really a bit of an ugly work around.

**Comment by mrivera-ms** [comment]
@garypretty , please take a look and prioritize this. Thanks.

**Comment by garypretty** [comment]
Setting milestone as R11 - this looks like a good suggestion (maybe @Stevenic already has a related path for JavaScriptAction?) - given there is a workaround, albeit using multiple set properties, I will assign this as a P2 for R11.

**Comment by boydc2014** [comment]
@cxbuilders we probably not going to introduce a new built-in action for this, but we go some open-sources extensions to do this, check https://www.nuget.org/packages?q=iciclecreek for Iciclecreek.AdaptiveExpressions.Javascript which i think can do the same thing as you proposed here, there is also a python one there.

**Comment by mrivera-ms** [comment]
@cxbuilders we will close this issue as resolved by the recommendation given by @boydc2014 . If after trying that there are still unresolved issues, please open a new issue. Thank you.
