### ISSUE TITLE
BeginSkill action won't save results in expectReplies mode

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#3953]
## Version
4.9.1

## Describe the bug
The new BeginSkill action doesn't save the result returned from a skill when the deliveryMode is "expectReplies".  The reason for this that we only do this assignment in an override of `ContinueDialog` which is looking for the EoC activity to be posted back.  This won't happen in expectReplies mode. 

[bug]

**Comment by gabog** [comment]
This seems to be a duplicate for #4139, closing it.

**Comment by gabog** [comment]
Closed the wrong one... reopen it

**Comment by gabog** [comment]
This seems stale, closing it.
