### ISSUE TITLE
Teams shows "bad request" when a skill invocation ends.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#3956]
## Version
4.9.1

## Describe the bug
When you call a skill from a bot on teams you'll get a "bad request" message when the skill ends.  I believe this is related to the issue of the post back completing on a second thread.

![image](https://user-images.githubusercontent.com/698939/82462434-6af9ec80-9a70-11ea-88c0-b2935ce5b22e.png)

[bug]

**Comment by gabog** [comment]
Closing this one, the C# changes are ready and merged in 4.9 and cherry picked on master.
JS will be addressed as part of adding support for skills in DialogManager in R10.
Pyton and Java don't have DialogManager and this will be addressed as part of porting the class and other adaptive assets to them.
