### ISSUE TITLE
NuGet.exe throws a circular reference exception when processing BotBuilder packages

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#3957]
## Action Needed
Replace Nuget.Client with Nuget.Packaging 5.x from Microsoft.Bot.Builder.Dialogs.Declarative

From Joel Martinez:

"A few more details from the nuget team, summarized here from that GH issue:

1.	This issue stems from a reorganization of types in their packages … in newer versions they have done away entirely with the Nuget.Client package, and the dependency reversal causing the circular reference is only there for the type forwarders.
2.	There are two version solvers in nuget, the one used by the nuget.exe client, and the one used when a package is restored from a project file with PackageReference. This issue doesn’t seem to exist in the PackageReference solver (which doesn’t help us since our pipeline uses nuget.exe) … they seem hesitant to make any changes/fixes to the nuget.exe solver.
3.	They recommend removing the Nuget.Client package dependency, and instead adding a reference to the newer Nuget.Packaging 5.x, which would side step the issue entirely."

## Version
4.9.1

## Describe the bug
NuGet.exe throws a circular reference exception when processing BotBuilder packages.

## Error Sample
##[error]Circular dependency detected 'Microsoft.Bot.Builder.AI.Luis 4.9.0 => Microsoft.Bot.Builder.Dialogs.Declarative 4.9.0 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0-preview4.5065 => NuGet.Packaging.Core 5.0.0-rtm.5856 => NuGet.Packaging 4.7.0-preview4.5065'.
##[error]Circular dependency detected 'Microsoft.Bot.Builder.Dialogs.Adaptive 4.9.0 => Microsoft.Bot.Builder.Dialogs.Declarative 4.9.0 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0-preview4.5065 => NuGet.Packaging.Core 5.0.0-rtm.5856 => NuGet.Packaging 4.7.0-preview4.5065'.
##[error]Circular dependency detected 'Microsoft.Bot.Builder.AI.Luis 4.9.0 => Microsoft.Bot.Builder.Dialogs.Declarative 4.9.0 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0 => NuGet.Packaging.Core 5.0.0 => NuGet.Packaging 4.7.0'.
##[error]Circular dependency detected 'Microsoft.Bot.Builder.AI.QnA 4.9.0 => Microsoft.Bot.Builder.Dialogs.Declarative 4.9.0 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0 => NuGet.Packaging.Core 5.0.0 => NuGet.Packaging 4.7.0'.
##[error]Circular dependency detected 'Microsoft.Bot.Builder.Dialogs.Adaptive 4.9.0 => Microsoft.Bot.Builder.Dialogs.Declarative 4.9.0 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0 => NuGet.Packaging.Core 5.0.0 => NuGet.Packaging 4.7.0'.
##[error]Circular dependency detected 'Microsoft.Bot.Builder.Dialogs.Declarative 4.9.0 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0 => NuGet.Packaging.Core 5.0.0 => NuGet.Packaging 4.7.0'.

## Additional context

[bug]

**Comment by joelmartinez** [comment]
For reference, this is the GH issue where the information above came from:  
https://github.com/NuGet/Home/issues/9579

**Comment by cleemullins** [comment]
PR #3964 fixes/closes this issue.
