### ISSUE TITLE
Interruptions in OAuthInput not properly consuming the user input

### ISSUE THREAD

**Issue by lucaism** [microsoft/botbuilder-dotnet#3963]
## Version
4.9.1

## Describe the bug
When specifying interruptions for an OAuthInput, the InvalidPrompt handler is still invoked after the interruption is complete.

## To Reproduce
I am using the OAuthInput below, and invoking this dialog via `BeginDialog`:
```
var authDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
{
    Recognizer = new RegexRecognizer()
    {
        Intents = new List<IntentPattern>()
        {
            new IntentPattern()
            {
                Intent = "Help",
                Pattern = "(?i)help"
            }
        },
    },
    Triggers = new List<OnCondition>()
    {
        new OnBeginDialog()
        {
            Actions = new List<Dialog>
            {
                new OAuthInput
                {
                    ConnectionName = "graph",
                    Text = "Before I can perform this operation, I need permission to validate your identity.",
                    Title = "Sign-in required",
                    Property = "$authToken",
                    InvalidPrompt = new ActivityTemplate("Sorry, I didn't understand that"),
                    AllowInterruptions = "true"
                }
            }
        },
        new OnIntent()
        {
            Intent = "Help",
            Actions = new List<Dialog>()
            {
                new SendActivity("Here's some helpful information."),
            }
        },
    }
};
```

The result of executing this dialog is as follows:
![image](https://user-images.githubusercontent.com/64159080/82498695-4704ce00-9aa5-11ea-8a35-a05e5d787186.png)

## Expected behavior
I would expect all messages except the InvalidPrompt message to be displayed. The original [pull request](https://github.com/microsoft/botbuilder-dotnet/pull/3070) seems to support this expectation, as in the first example in the PR description the input "hi" does not cause the InvalidPrompt to be displayed when AllowInterruptions is set to true. 

[bug]

**Comment by gabog** [comment]
Hi @dmvtech, can you please take a closer look at this one?

Thanks

**Comment by dmvtech** [comment]
I am looking into this. Checking to see if I can reproduce as well.

**Comment by dmvtech** [comment]
Reproduced. Confirmed bug.
