### ISSUE TITLE
Native support of LG data binding for property value

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3968]
## Context
In AdaptiveDialog, the way to do LG data binding today is via 'SendActivity' which can accept a free text that including memory reference in it, like 
```c#
var action = new SendActivity("hello ${user.name}");
```

## Issue
In QnA integration, we put the data binding text in the answer of a QA pair, then in runtime, the answer will be picked into `@answer` property in dialog state. For example
```
@answer = "hello ${user.name}"
```

The issue is if we use SendAcitivity("${@answer}") what we get is the text `hello ${user.name}`, but we  actually want is user.name is bind again. 

The only way to do this now is throw a customiedCodeAction in which evaluated it twice. 

### Solution 1: create new prebuilt function like eval
We can create a prebuilt function in LG for example eval that takes a string and result in the lg evaluation result, the example usage will be 
```c#
var action = new SendActivity("${eval(@answer)}")
```

This is pretty clean and additive change, which is why we proposed as 1st solution. The issue with this issue is perhaps we need to unify a few functions naming, we have a function called `template` which perhaps we should rename to evalTemplate, and call this new function evalText. We may consider add a evalExp for expression.  

## Solution 2: extend SendActivity
The other direction to solve this is leave LG and Expression unchanged, but extend SendActivity to have a new property let's say `value` which is an expression.  The example usage is like
```
var action = new SendActivity (value = '@answer')
```
Creating an new action like `SendActivityV2` is also  a valid solution in this direction.

**Comment by boydc2014** [comment]
Tag this with DCR, call out for triage to @vishwacsena @tomlm @chrimc62 @Stevenic

**Comment by Danieladu** [comment]
Maybe we can extend "Accessor" builtin funciton to support variable

**Comment by vishwacsena** [comment]
+1 for `eval`

**Comment by vishwacsena** [comment]
@tomlm @chrimc62 are you ok with `eval()`?

**Comment by vishwacsena** [comment]
DCR triage function makes sense. function name `expandText()`

**Comment by boydc2014** [comment]
> DCR triage function makes sense. function name `expandText()`

you mean function name called expandText()? eval or evalText feels more natural to me

**Comment by vishwacsena** [comment]
@boydc2014 the naming party is over.. :)`expandText()`
