### ISSUE TITLE
Add NonexistSubstitution in AdaptiveExpressions.Options

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3969]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't know whether a value is null because it is non exist or the value itself is null.

For example, I could use `contains` function to do this but not a global way.

**Describe the solution you'd like**
Add NonexistSubstitution like NullSubstitution but only invoked when the value is non-exist.

[enhancement]

**Comment by boydc2014** [comment]
@Danieladu can you verify first whether our IMemory interface distinguish null and not-exist ?

Take off R10 for now.

**Comment by Danieladu** [comment]
> @Danieladu can you verify first whether our IMemory interface distinguish null and not-exist ?
> 
> Take off R10 for now.

There is a `TryGetValue()` method in interface `IMemory`, the user can implement it with own memory accessor. For example, if the property does not exist, return false, if the property exists, return true.

**Comment by mrivera-ms** [comment]
@xieofxie , please see the reply from @Danieladu above. Closing as resolved.
