### ISSUE TITLE
null should not be treated as error in Expander

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3972]
## Version
What package version of the SDK are you using.

Current master

## Describe the bug
Give a clear and concise description of what the bug is.

In Expander here https://github.com/microsoft/botbuilder-dotnet/blob/112128239fa04bea3deff7e668cf659b3860881c/libraries/Microsoft.Bot.Builder.LanguageGeneration/Expander.cs#L408, when result is null and in StrictMode is true, result will be left empty causing NullReference Exception.

However, the evaluation result could be null by purpose and StrictMode should check if it accesses a non-exist variable instead of the result is null. 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by boydc2014** [comment]
Take off the R10 label, for the same reason listed in https://github.com/microsoft/botbuilder-dotnet/issues/3973#issuecomment-639998213, we will do a best effort to fix certain bugs in expander, but given the priority and the adoption of this expander feature, we are not listing the expander as a commitment in R10.
