### ISSUE TITLE
Expander can't expand certain template

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3973]
## Version
What package version of the SDK are you using.

Current master.

## Describe the bug

Expander can't expand certain template.

## To Reproduce
1. clone https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/expand_bug
2. run tests\Microsoft.Bot.Builder.LanguageGeneration.Tests\TemplatesTest.cs TestExpandFailedTemplate
3. note bad is empty while good has result:
![image](https://user-images.githubusercontent.com/2876650/82972433-9dbf5a00-a007-11ea-9f7f-ccd359c05356.png)

## Expected behavior
bad should contain result as good

## Additional context

[bug]

**Comment by vishwacsena** [comment]
@xieofxie can you add more info or close this if this has already been addressed?

**Comment by xieofxie** [comment]
@vishwacsena This bug still exists in master and I updated the reproduce steps.
@Danieladu said this should be assigned to @feich-ms

**Comment by feich-ms** [comment]
I will take a look since the expander function is maintained by me.

**Comment by boydc2014** [comment]
@xieofxie i'm taking off R10 of this, the original expander design has some limitation when it deals with list functions, and it was not going to give a complete result in all cases, especially when it evolves in functions that generate and\or manipulate list. 

We will re-design expander in the way how it works with list functions, but we don't have the commitment in R10 yet.
