### ISSUE TITLE
Add "Naughty String" testing to prompts and other input vectors

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#3976]
Consider adding automated complex string input testing to prompts and dialogs. 
This list includes many "naughty" strings, and lists them in other places as well. 
https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by Stevenic** [comment]
This would actually be a good piece of middleware. It could be configured to screen both incoming and outgoing messages.

**Comment by JonathanFingold** [comment]
JSON is in UTF-8 and C# uses UTF-16 for strings. We explicitly convert back and forth, but Wikipedia notes that there can be some issues.
