### ISSUE TITLE
use turnstate.activity.locale for multi-language generation

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3993]
**Is your feature request related to a problem? Please describe.**

Currently, multi-language generation uses turncontext.activity.locale to determine the locale.
However, when we set turn.activity.locale, it is set in turnstate instead of turncontext.
Then if we change it to another locale, the multi-language generation will remain the same.

**It blocks us from outputting responses in different languages in one turn.**

**Describe the solution you'd like**

either 1 change real  turncontext.activity.locale for turn.activity.locale
or 2 use turnstate.activity.locale for multi-language generation

[enhancement]

**Comment by vishwacsena** [comment]
We need to respect what's on the incoming activity.

**Comment by xieofxie** [comment]
Agreed. But current behavior might be a little confusing.
For example, the user knows LU/LG use locale from the incoming activity.locale. However, when the user changes turn.activity.locale, LG will not change. Yet in the bot state, the value is changed. It will cause confusion.

Further more, if we could change the real turncontext.activity.locale, we could enable developer to change locale in the same turn and enable user to set locale preference to overwrite channel's one (which still requires set activity.local before turn start).

**Comment by vishwacsena** [comment]
@xieofxie is the primary use case the one where the developer can explicitly set the locale based on user input?

**Comment by xieofxie** [comment]
@vishwacsena the use case occurs in the Multi-Language VA in Mixed Reality hackthon where the bot knows there are multiple people using different languages. Then in one turn, the bot may response '[en] ok, I have set it up. [es] what do you need?' etc.

I don't meet this in other scenarios and we could just leave it as it is.

**Comment by vishwacsena** [comment]
@tomlm @boydc2014 is this related to using the thread locale .vs. turn.activity.locale in C#? 

Dropping R10.

**Comment by boydc2014** [comment]
@cosmicshuai with our locale PR in, we should be able to enable to set turnContext.locale, right?

**Comment by cosmicshuai** [comment]
@boydc2014 @vishwacsena @xieofxie 
An locale from turn.activity.locale will be set to TurnContext.Locale property. It will change based on the incoming activities from user.
User's can get TurnContext.Locale by DialogContext.GetLocale() will retrieve the locale. 
Ref: https://github.com/microsoft/botbuilder-dotnet/pull/4276

**Comment by xieofxie** [comment]
@boydc2014 @cosmicshuai Thanks! So it seems I should use turn.locale to change the locale of LG?

I create a test for this feature here https://github.com/xieofxie/botbuilder-dotnet/commit/741492b35049da7e70224c19c54c22bc44818d0b

But I found a bug:
We should use `ObjectPath.SetPathValue` here https://github.com/microsoft/botbuilder-dotnet/blob/b17b100967eda0ed3d24bb539a0f0090e065ec7a/libraries/Microsoft.Bot.Builder/TurnContext.cs#L63
Or it will not be set to the same turn JObject. Then when I use or change it in declarative dialog, they are not the same.
However,  ObjectPath is in package Microsoft.Bot.Builder.Dialog which depends on Microsoft.Bot.Builder, so we can't reference it.
What's your idea for this?

**Comment by xieofxie** [comment]
BTW I don't feel right for using Thread.CurrentThread.CurrentCulture since we use configure await (false) everywhere. See a discussion here: https://stackoverflow.com/questions/20601578/async-webapi-thread-currentculture

**Comment by boydc2014** [comment]
@xieofxie yes, the design is we create a new property turnContext.locale to hold the locale to drive the LG processing later. So you should be able to set this value to control the locale. 

@cosmicshuai can you follow up with @xieofxie to understand this new bug?

**Comment by xieofxie** [comment]
In summary, if use Set instead of ObjectPath, turn.locale is treated as a string not separated components like this (note turn on the bottom)
![image](https://user-images.githubusercontent.com/2876650/91406009-aa588600-e874-11ea-991c-167d03c1ed32.png)

I just found another mistake: we add AI here: https://github.com/microsoft/botbuilder-dotnet/blob/b17b100967eda0ed3d24bb539a0f0090e065ec7a/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests/LGGeneratorTests.cs#L23

**Comment by mrivera-ms** [comment]
@darrenj could you please take a look here? We need a resolution. It should be prioritized or closed. Thank you.
