### ISSUE TITLE
Please add range(start, end, increment) or for loop

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3996]
**Is your feature request related to a problem? Please describe.**
In adaptive expressions there is currently no way to generate an array with N elements in it.  You can enumerate over an existing array, object or IndicesAndValues with forEach, but you cannot iterate over N values.

**Describe the solution you'd like**
I would like either a function range(start: number, end:number, increment:number=1) which generates an array of values which can be used in foreach, or a for(variable, body, start, end, increment=1) loop.  

[enhancement]

**Comment by Danieladu** [comment]
Current expression has this one [range](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#range). Maybe we can enhance it with an "increment number" option?

**Comment by vishwacsena** [comment]
Chatted offline with @chrimc62 . Closing as we believe [range][1] is sufficient for the primary use case here.

[1]:https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#range
