### ISSUE TITLE
Version change exceptions

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-dotnet#3998]
## Version
4.9.1

## Describe the bug

There have been multiple reports from customers using the latest 4.9.1 SDK whereby they are reporting sudden `Version Change` exceptions being surfaced which haven't been seen before.

From conversations with SDK there is new (undocumented) behaviour whereby an event is fired if the SDK detects a conversation is resuming when a Dialog may have changed. If this event is not handled an exception is raised to trigger state being cleared out. If the user handles the event they can make a call on whether to ignore, re-constitute state, etc.
 
I agree with the overall direction – we’ve had instances in the past for persistent channels like Teams having users that are stuck and having to have a “/reset” type command to clear out state. However I think this new behaviour change should be opt-in not enforced due to the side affects it's causing.

## To Reproduce
Two causes have been identified so far:

1. Customer deploys a Bot, users start conversations to these bots through a persistent channel (e.g. Teams). The Bot is then later updated (new dialogs added, dialogs changed, etc.). When a user resumes the conversation a version Change exception is surfaced.

2. Customer starts a conversation, dialogs are added statically at the beginning of a dialog but due to multi-locale scenarios another dialog might be registered dynamically. This then triggers the same version change exception.

## Expected behavior
Behaviour change does not impact existing bots especially those with persistent/long-running conversations or those using dynamic dialog registration scenarios

## Suggestion
- Make this behaviour opt-in so existing customers don’t run into it
- Ensure all Samples and Templates have a default implementation (currently none do)
- Update documentation with guidance about this behaviour

## Other information
With VA (due to multi-locale requirements and issues with Conversation Update not setting locale property) we have to dynamically add QnAMaker dialog when needed and this triggers the problem easily.

1.	Deploy a Virtual Assistant Sample in TypeScript
2.	Run the Virtual Assistant Sample on Bot Emulator
3.	Complete the Onboarding Dialog 
4.	Send 'What's a Virtual Assistant?' (Adds QnAMaker dialog to the stack)
5.	Wait for reply and send 'What's a Virtual Assistant?' again
6.	The bot should show an exception with the message 'Version change detected for MainDialog dialog'
 

[bug]

**Comment by cleemullins** [comment]
Fixed as part of 4.9.3
