### ISSUE TITLE
Activity message would be dropped when there is only a "ChannelData" property

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#4001]
## Version
source code

## Describe the bug
Message is dropped when the message contains only channelData property.

## To Reproduce
1. Add a SendActivity Action, and send  `${template()}`
2. LG file is 
```
# template
> only channel data property, no text and speak
[Activity
ChannelData = xxx
]
```

## Expected behavior
An empty message should be received but not be swallowed.

## Additional context
Maybe should add the channeldata into consideration in SendActivity action. Attach the original code in `SendActivity`
```
           if (activity.Type != "message" 
                || !string.IsNullOrEmpty(activity.Text)
                || activity.Attachments?.Any() == true
                || !string.IsNullOrEmpty(activity.Speak)
                || activity.SuggestedActions != null) 
            {
              // if activity only contains `channeldata`, this block would be skipped
                response = await dc.Context.SendActivityAsync(activity, cancellationToken).ConfigureAwait(false);
            }
```

[bug]

**Comment by vishwacsena** [comment]
@Danieladu can you make a fix/ pr here?

**Comment by Danieladu** [comment]
> @Danieladu can you make a fix/ pr here?
Of course.
