### ISSUE TITLE
Locale-aware pre-built functions

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#4007]
Use this to track the effort to make a set of functions to be locale aware, which contains 3 parts
1. Make adapter pick and store locale in Activity in certain place, ie Thread.CurrentThread.CurrentCulture
2. Make a set of expression functions (conversation, formating related) use the locale get in step1 as the default locale
3. Expand the interface of those functions to accept a parameter to overrride locale if default locale is not suitable

> how do I turn a number into a string?  There are ton of options there that are locale specific 
> How do I turn a date into a string? There are a ton of locale specific manifesations of that
> How do I turn a timespan into a string? This is locale specific

**Comment by xieofxie** [comment]
I think we should make locale an parameter passed in from turn.activity.locale instead of some thread storage. Since in await mechanism, there could be multiple context running on the same thread I guess?

**Comment by boydc2014** [comment]
> I think we should make locale an parameter passed in from turn.activity.locale instead of some thread storage. Since in await mechanism, there could be multiple context running on the same thread I guess?

This proposal included the adding parameter approach see no.3 in the item list, and also included an approach trying to set a good default if possible. Thread storage is just on option which is probably the convention. If thread storage don't looks promising, we will reach out for better solution.

**Comment by boydc2014** [comment]
@Danieladu @cosmicshuai two actions needs to be clarifed before we started
1. list of functions we need this support
2. the location of storing default locale

**Comment by vishwacsena** [comment]
What's the impact/ related change of this to LG?

**Comment by boydc2014** [comment]
solved by #4276

**Comment by boydc2014** [comment]
> What's the impact/ related change of this to LG?

the impact for LG is some functions leveraged in LG will peform different based on locale
