### ISSUE TITLE
Calling an event or dialog from Invalid prompt and Unrecognized prompt

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/botbuilder-dotnet#4008]
I'm trying to call an event or dialog from Invalid prompt and Unrecognized prompt I found like this feature is not yet present so I'm Requesting this feature to add

**Comment by tracyboehrer** [comment]
@vishwacsena All the Chris's ask that you look into this, plese.

**Comment by vishwacsena** [comment]
Unfortunately this is not possible with the native set of inputs available as part of adaptive dialogs. However you can extend adaptive actions with your own custom actions and you could pursue providing this capability via a custom input action. 

Keeping this in backlog so we can consider supporting this natively in a future release.

**Comment by KoradaRajesh** [comment]
Sure @vishwacsena Thank you

**Comment by mrivera-ms** [comment]
This has been replied to. @KoradaRajesh , please see the answer above. We are closing it now, but can be reopened in the future if there is a clear need.
