### ISSUE TITLE
Nested if in LG file

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/botbuilder-dotnet#4009]
Unable to create nested if in LG 

![image](https://user-images.githubusercontent.com/51915291/83329409-f1030800-a2a6-11ea-96fe-db79196de379.png)

**Comment by Danieladu** [comment]
Suggestions: 
Implement nested conditions with multi-templates, example:
```
# template
- IF:${IsMatch1()}
 - ${template1()}
- ELSEIF: ${isMatch2()}
 - ${template2()}

# template1
- IF: ${IsMatch11()}
 - looks good
- ELSEIF: ${isMatch12()}
- balabala

# template2
- IF: ${IsMatch21()}
 - looks good
- ELSEIF: ${isMatch22()}
- balabala

```

**Comment by vishwacsena** [comment]
For improved readability, nesting is only supported via composition. Please see @Danieladu's example above.

**Comment by KoradaRajesh** [comment]
Thank you! @daniel-castro and @vishwacsena
