### ISSUE TITLE
Add Expression support to BeginDialog

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4010]
## Is your feature request related to a problem? Please describe.

Currently there's no way within composer of dynamically selecting the name of the dialog or skill you want to start.  For `BeginDialog` a simple fix would be to add an "Expression" entry to the drop down list composer shows:
 
![image](https://user-images.githubusercontent.com/698939/83361742-49d2af00-a340-11ea-9234-bdf22e902c47.png)

For skills it's a little trickier as you need to give the dialog all of its host connection info. It would be nice if we could work out how to do the same with skills as well.

**Comment by vishwacsena** [comment]
@cwhitten this is a dialogExpression which can either be a dialog or an expression that resolves to an ID of a dialog to begin.

**Comment by gabog** [comment]
Let's break this one up in two, one for BeginDialog and another for BeginSkill. 
For now, I removed the skill label, so let's just use this issue to track the changes to BeginDialog. We should open a new one for BeginSkill when and if that's needed.

**Comment by boydc2014** [comment]
> Let's break this one up in two, one for BeginDialog and another for BeginSkill.
> For now, I removed the skill label, so let's just use this issue to track the changes to BeginDialog. We should open a new one for BeginSkill when and if that's needed.

Agree, we will take this soon after the P0's is done.

**Comment by boydc2014** [comment]
I'm moving this out of R11, as our investigation shows that this is not doable via current architecture. We will get a design discussion with @tomlm to address this design issue.

**Comment by mrivera-ms** [comment]
@boydc2014 what is the status of this item? Please update it and close it if needed.

**Comment by boydc2014** [comment]
> @boydc2014 what is the status of this item? Please update it and close it if needed.

I got some time with Tom and ends up with a design. Shuai is working on that. 

A PR is open for this, see the link above. I think this still needs sometime to bake, i expect the PR will be ready in the next few days.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. The associated PR needs to be reviewed again. Moving out of R12.
