### ISSUE TITLE
Adaptive Expressions: fill in obvious gaps with additional pre-built functions 

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4014]
## Issue

This issue is to track additional functions we want to add to Adaptive Expressions for R10.  Just reply with a proposed function.

[dcr]

**Comment by Danieladu** [comment]
It would be better if a sample is attached for each function

**Comment by KayMKM** [comment]
A function that can combine two list.
E.g. a=[1, 2, 3], b=[2, 3, 4], combine(a, b)=[1, 2, 3, 2, 3, 4]

**Comment by boydc2014** [comment]
@Danieladu can you propose the function signature for those functions and let us review

**Comment by Danieladu** [comment]
## indexOf/lastIndexOf
 Expression already contains these two functions, but just with the default `equals` condition.
So, should we change the original function to make it 'lambda'? The function may like:
`indexOf([1, 2, 3], x, x > 2)`
Change the original function maybe a breaking change?

## merge
`merge(json1, json2)`, should we add some more parameters? like ignore case

## Combine two list
Now expression has function `union` to combine two lists and remove the duplicated items.
So, the function's name is the biggest issue, `combine`? `addrange` ? `concatList`? (concat is exist)

**Comment by vishwacsena** [comment]
index/indexof - need to verify with @stevenic if what we have is enough
merge(json, json) makes sense. 
concat(list1, list2) makes sense.

**Comment by boydc2014** [comment]
@Stevenic can you confirm what we have now index\indexof is good enough?

**Comment by Danieladu** [comment]
Here is the workaround:
`where(indicesAndValues(user_list), x, x.value > 2)[0].index`

In the next stage, we may consider supporting some functions for lambda. like `first`, `last`, `count`, `indexOf`, `lastIndexOf` .etc.
For example:
```
first(list, x, x > 2)
last(list, x, x>2)
count(list, x, x>2)
indexOf(list, x, x > 2)
lastIndexOf(list, x, x > 2)
```

But before this feature is completed, users can also achieve these function results through the solution by other builtin functions or customize functions.

**Comment by boydc2014** [comment]
@Stevenic we are closing this now, see above the resolved issue, if you continue to have gaps, let's track them via new issues
