### ISSUE TITLE
Enable continuing conversation from an activity instead of reference.GetContinuationActivity()

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4018]
**Is your feature request related to a problem? Please describe.**

As far as I can see, this logic is almost the same as ProcessActivityAsync except for the contruction of turncontext.
https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L342

Then if we could support continuing from an activity (with conversation reference set), we could continue the bot with some custom payload proactively.

**Describe the solution you'd like**

Add a new function with activity.

**Describe alternatives you've considered**

Currently, I continue it by applying activity payloads, but I am not if it is the correct way:
```
((BotAdapter)adapter).ContinueConversationAsync(botSettings.MicrosoftAppId, reference.Reference, async (tc, ct) =>
{
    // TODO middlewares still use ContinueConversation activity
    tc.Activity.Type = activity.Type;
    tc.Activity.Text = activity.Text;
    tc.Activity.Speak = activity.Speak;
    tc.Activity.Value = activity.Value;
    tc.Activity.Attachments = activity.Attachments;
    tc.Activity.AttachmentLayout = activity.AttachmentLayout;
    await bot.OnTurnAsync(tc, ct);
}, cancellationToken).Wait();
```

[enhancement]

**Comment by stevengum** [comment]
@axelsrz the logic around ContinueConversationAsync/Proactive messaging might fall into your scope for R10 and this sounds like a reasonable ask. 

I believe @gabog and @garypretty likely have some solid feedback/perspective on using this code that could be baked into this method. They also likely have some R10 overlap as well 😉 

Lastly, @xieofxie if you are using ContinueConversationAsync in a Skills-based context, I recommend using the [overload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.botframeworkadapter.continueconversationasync?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_BotFrameworkAdapter_ContinueConversationAsync_System_Security_Claims_ClaimsIdentity_Microsoft_Bot_Schema_ConversationReference_System_String_Microsoft_Bot_Builder_BotCallbackHandler_System_Threading_CancellationToken_) with the `audience` parameter to ensure a correct auth flow:

```csharp
public override async Task ContinueConversationAsync(ClaimsIdentity claimsIdentity, ConversationReference reference, string audience, BotCallbackHandler callback, CancellationToken cancellationToken)
```

**Comment by EricDahlvang** [comment]
ContinueConversation should be reviewed all up, in conjunction with `callerId` and `oauthScope` or `authority`.  One proposal is to add callerId to ConversationReference, and derive authority from it.  This would deprecate SkillConversationReference, and simplify the surface area significantly.

**Comment by johnataylor** [comment]
This is merged for CloudAdapter - see overloads of ContinueConversation that reflect what we have with ConversationReference
