### ISSUE TITLE
Trigger Condition/Priority do not evaluate against the generator

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4019]
## Version
4.9.3

## Describe the bug
When evaluating triggers condition and priority go directly against adaptive expressions rather than through the generator.  This means they cannot use functions defined in the generator templates to simplify condition/priority.  The same issue may be found other places.

[bug]

**Comment by vishwacsena** [comment]
@tomlm says he worked through this with you offline.
