### ISSUE TITLE
Throwing Generic Exceptions

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#4022]
Problem:
In our coding standards we don't allow 

`try
{}
catch(Exception ex)
{}
`

This is because we operate under the assumption that if you can't actually do anything about an exception you shouldn't catch it and instead let it bubble up to code that can. Catching all Exceptions and handling them generically is something we assume the UI will do with a Generic Exception Handler.

The issue is that it appears the Bot framework actually throws "EXCEPTION" by convention. So we are now having to Catch "Exception" and string parse the message to figure out what went wrong. This seems contrary to what I thought was a fundamental c# rule ... "Never throw Exception" worst case throw ApplicationException but preferably throw an exception that is specific to the problem.

Did something change that altered this fundamental?

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/ActionScope.cs#L125

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder/ActivityFactory.cs#L54

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs#L55

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.LanguageGeneration/Analyzer.cs#L60

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L187

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L271

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L329

https://github.com/microsoft/botbuilder-dotnet/blob/03a51e1e09d36cd8c4e8f1dcde6263e5d62e806e/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L484

etc. etc. 
83 plus cs file have "new Exception" 1 or more time in the current master branch.

**Comment by DavidStrickland0** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types

**Comment by eddynaka** [comment]
Hi, is this issue is still available?

**Comment by gabog** [comment]
We are looking into it, just to set the proper expectations, we may not be able to address it. I will post back here on the status once we have a chance to review the options.
