### ISSUE TITLE
Using UTF-32 in Language Generation template.

### ISSUE THREAD

**Issue by khiemnvd** [microsoft/botbuilder-dotnet#4028]
I can't show emoji using UTF-32 in the template.lg in bot framework emulator.

```
# ContactBot
- Thank you. Don't hesitate to contact me anytime. \U0001F60A
```

**Comment by Danieladu** [comment]
@khiemnvd sorry for the blocking. Currently, LG does not support the \U escape, So, the "\U0001F60A" in LG is really a constant string.
The work around is just paste the UTF-8 format emoji into the lg file, it supposed to work. Snipping picture:

![image](https://user-images.githubusercontent.com/7289268/83935347-6e6cd200-a7eb-11ea-8dd3-4f4549d17682.png)

In emulator:
![image](https://user-images.githubusercontent.com/7289268/83935350-79bffd80-a7eb-11ea-8363-0a1b41e270eb.png)

Thanks

**Comment by khiemnvd** [comment]
> @khiemnvd sorry for the blocking. Currently, LG does not support the \U escape, So, the "\U0001F60A" in LG is really a constant string.
> The workaround is just paste the UTF-8 format emoji into the LG file, it supposed to work. Snipping picture:
> 
> ![image](https://user-images.githubusercontent.com/7289268/83935347-6e6cd200-a7eb-11ea-8dd3-4f4549d17682.png)
> 
> In emulator:
> ![image](https://user-images.githubusercontent.com/7289268/83935350-79bffd80-a7eb-11ea-8363-0a1b41e270eb.png)
> 
> Thanks

Thanks @Danieladu , 
I hope LG will support in the next release version.
