### ISSUE TITLE
[DCR] Expression data binding support for special character as top-level key

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#4029]
Today data binding support is basically 3 apporaches
1. a plain variable like `foo` or foo.bar
2. [], like  foo["bar"] 
3. getProperty function, getProperty(foo, "bar")

the issue is if the memory in property contains special character like ":" we won't support that in approach 1, because that's don't match will our parser rule. 

The issue with approach 2 and 3 is that it required a property to start with, ie foo must be acccessed before "bar", so if the top level key "foo" is "f:oo", it won't work. 

To solve this, the proposed solution is either 
1. We naively inject the whole memory as a special data path like $data, so that approach 2 and 3 can work as $data["a:b"] or getProperty($data, "a:b")

or 
2. we extend getProperty to support getProperty("a:b") which only have one parameter that will access the top memory. 

I will vote for 1,  @vishwacsena @chrimc62 @tomlm

**Comment by boydc2014** [comment]
related to a customer reported issue https://github.com/microsoft/AdaptiveCards/issues/4134

**Comment by chrimc62** [comment]
I prefer 2.  $data feels artificial to me.
