### ISSUE TITLE
Bug: Public Members that are not Getters/Setters Properties are not persisted between Turns.

### ISSUE THREAD

**Issue by sayar** [Microsoft/botbuilder-dotnet#403]
Only properties with getters/setters (and not public members) are being persisted in the context per turn. This should be documented or public members should be persisted. Thoughts?

This was discovered at an internal hack.

**Comment by drub0y** [comment]
Version 4 has taken an approach of serializing according to the rules of [Data Contract Serialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/serialization-guidelines). Under these rules, only public properties are candidates for serialization and only those not marked with the `[IgnoreDataMember]` attribute. 

More specifically, the framework is currently using JSON.NET under the covers for all serialization and it abides by DCS rules itself and has some additional rules/attributes of its own to control serialization. Though, the use of JSON.NET is technically an internal implementation detail, so you really shouldn't count on anything beyond raw DCS rules.

**Comment by cleemullins** [comment]
@sayar 

+1 to everything Drew said. We're using POCOs for serialization, and the general rules there mean "Properties'. As I understand it, this is how Entity Framework and other POCO / POJO serialization frameworks work.
