### ISSUE TITLE
Consider supporting TypeNameHandling.Auto

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#4033]
**Is your feature request related to a problem? Please describe.**

By default, the three storage classes in Microsoft.Bot.Builder.Azure (`AzureBlobStorage`, `CosmosDbStorage`, and `CosmosDbPartitionedStorage`) use `TypeNameHandling.All` to ensure .NET types can be round-tripped to JSON and back. This more than doubles the size of many JSON strings because they end up looking like this:

```json
{
  "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Priva
te.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
  "storageKey": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Pri
vate.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib",
    "DialogState": {
      "$type": "Microsoft.Bot.Builder.Dialogs.DialogState, Microsoft.Bot.Builder
.Dialogs",
      "dialogStack": {
        "$type": "System.Collections.Generic.List`1[[Microsoft.Bot.Builder.Dialo
gs.DialogInstance, Microsoft.Bot.Builder.Dialogs]], System.Private.CoreLib",
        "$values": []
      }
    }
  }
}
```

Newtonsoft does provide a way to mitigate this problem. When `TypeNameHandling.Auto` is used, type names are only included in the JSON as needed. That is to say, a type name is left out when it can be inferred from the containing type based on the property name. For example, the `dialogStack` property would need no type name in JSON because that information is contained in the definition for the .NET type `DialogState`.

The Bot Framework storage classes allow you to use a custom JSON serializer instead of the default one, which means you can use `TypeNameHandling.Auto` instead of `TypeNameHandling.All`. Unfortunately this causes a few problems because of the way the storage classes and `BotState` are written. `TypeNameHandling.Auto` gives you a choice about whether you want the root type to be included, because if you know what it is when you deserialize the JSON then there's no point in including it in the JSON. Since the storage classes don't include the root type when writing the JSON and also don't know what it is when reading the JSON, the JSON gets deserialized as a `JObject`. This means [state property accessors will return a copy of the cached object](https://github.com/microsoft/botbuilder-dotnet/blob/c356e857faf4f9891ec7dd351d0c9d8eab83f143/libraries/Microsoft.Bot.Builder/BotState.cs#L260), making it harder to write new values. More importantly, the bot state class doesn't know anything about the JSON serializer used by the storage class, and this will sometimes make it impossible to read values.

**Describe the solution you'd like**

In `AzureBlobStorage`, including the root type name would be as simple as changing [this line](https://github.com/microsoft/botbuilder-dotnet/blob/c356e857faf4f9891ec7dd351d0c9d8eab83f143/libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs#L200) to this:

```c#
_jsonSerializer.Serialize(streamWriter, newValue, typeof(object));
```

That third parameter represents the declared type of a property that this value might belong to. If the declared type is `object` then the serializer knows it needs to include the value's root type in the JSON in order for the object to get deserialized correctly, unless the value is just an instance of the `System.Object` class.

It would be a little more complicated in `CosmosDbStorage` and `CosmosDbPartitionedStorage` because the .NET object gets converted to a `JObject` instead of serialized into JSON directly and `JObject.FromObject` doesn't provide a parameter that lets you specify a declared type. This means the .NET object would need to be serialized into JSON and then parsed into a `JObject`.

**Describe alternatives you've considered**

The main alternative would be to specify a type when reading the JSON instead of when writing it. This would have the advantage of making the JSON even shorter still, but I don't think it will work unless we want to only allow the stored value to be deserialized as a dictionary. If we want to allow other types like `StoreItem` then we'd need to include the type in the JSON to know how to deserialize it.

**Additional context**

These changes would not have any effect on any bot that is using `TypeNameHandling.All` which is expected to be the vast majority. If a bot is using `TypeNameHandling.Auto` then these changes still wouldn't have any effect unless the bot was counting on bad behavior like `BotStatePropertyAccessor<T>.GetAsync` returning a copy of the cached value in some cases. The changes would almost certainly only have an effect on new bots that are designed to take advantage of them.

[enhancement]

**Comment by gabog** [comment]
We will not address this at the moment.
