### ISSUE TITLE
Parity issue for transcript loggers/stores

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#4034]
## Version
What package version of the SDK are you using. **4.9.3**/master

## Describe the bug
The concrete classes available in each language varies greatly:
1. TraceTranscriptLogger (C# only)
1. FileTranscriptLogger (C# only)
1. ConsoleTranscriptLogger (missing in C#)
1. MemoryTranscriptStore (**language parity**)
1. FileTranscriptStore (JavaScript only)
1. AzureBlobTranscriptStore (missing in Python)

## To Reproduce
1. In each language, track down the various implementations of the transcript logger interface/ABC.
1. Error: Notice that the various classes implemented diverge more than they match.

## Expected behavior
As much as possible, there is "feature" parity across languages.

## Additional context
I'm trying to write an article to address [work item 39190](https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/39190). I'm finding it hard to draft an article when the only concrete class where there is parity is **MemoryTranscriptStore**.

[bug]

**Comment by EricDahlvang** [comment]
FileTranscriptStore related: https://github.com/microsoft/botbuilder-dotnet/pull/1355

**Comment by mrivera-ms** [comment]
Per discussion with the R10 Pillar leads, this item does not meet the priority bar for R10. Pushing it to R11.

**Comment by mrivera-ms** [comment]
Per conversation with @gabog , this is being removed from R11.

**Comment by JonathanFingold** [comment]
Alas. Just let the doc team know whenever this finally gets addressed, and we can update the associated article.

**Comment by mrivera-ms** [comment]
@darrenj , we need prioritization. This is an item that has been around for a while and it needs specification.

**Comment by gabog** [comment]
We will not address this at the moment.
