### ISSUE TITLE
Add CosmosDb tests to nightly functional tests

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-dotnet#4038]
Ensure that CosmosDB tests are running as expected and passing on the nightly build

**Comment by mdrichardson** [comment]
I'll update this as I go through until all checkboxes are green.

# Progress:

### Dotnet

- [ ] Successfully runs locally without skipping tests
- [ ] (does not test anything) Tests exist in the nightly pipeline
- [ ] Successfully runs nightly without skipping tests

### Node

- [ ] Successfully runs locally without skipping tests
- [x] Tests exist in the nightly pipeline
- [ ] (currently skips) Successfully runs nightly without skipping tests

### Python

- [ ] Successfully runs locally without skipping tests
- [x] (currently skips) Tests exist in the nightly pipeline
- [ ] Successfully runs nightly without skipping tests

### Java

- [ ] Successfully runs locally without skipping tests
- [ ] (does not test anything) Tests exist in the nightly pipeline
- [ ] Successfully runs nightly without skipping tests

**Comment by gabog** [comment]
We will not address this at the moment.
