### ISSUE TITLE
Migrate tests to XUnit

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-dotnet#4039]
Move 100% of unit tests from MSTest to XUnit,

Once the migration of a given project is done, remove references to MSTest.TestAdapter and MSTest.TestFramework from the csproj files.

```
    <PackageReference Include="MSTest.TestAdapter" Version="1.4.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.4.0" />
```

**Comment by Virtual-Josh** [comment]
Closing this issue for now. Xunit migration has been deprioritized.
