### ISSUE TITLE
Support test code coverage calculation for declaritive

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#4042]
**Is your feature request related to a problem? Please describe.**
Hope test code coverage number can be provided for declarative bot test project so that declarative bot quality can be measured.

**Describe the solution you'd like**
For 1) declarative steps 2) expression 3) LG they both have condition branch. Is there a way to provide an api to return test coverage at least for declarative steps?

[enhancement]

**Comment by mrivera-ms** [comment]
@DingmaomaoBJTU , could you please add more detail to your request? We would like to understand exactly what you are hoping to get here.

**Comment by mrivera-ms** [comment]
@DingmaomaoBJTU thank you for opening this issue. We are not able to take this at the moment.
