### ISSUE TITLE
DCR: Add new stack inspection methods to DialogContext

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4049]
**Is your feature request related to a problem? Please describe.**
It turns out that the C# and Python versions of the SDK store their dialog stacks inverted from the JavaScript SDK.  This could lead to errors when writing code that needs to inspect the stack so we'd like to add some API's for inspecting the stack in a normalized way.  My proposal would be to add two new methods:

- **ForEachDialogInstance()** - This would walk the stack in a deterministic direction calling a delegate for each stack entry.
- **GetActiveDialogPath()** - This would return an array of strings containing the full list of dialog ID's leading up to the active dialog.

Since paths are typically presented as a segmented list from root to leaf then I believe that for both of these methods we should start from the root dialog and work our way up.  Both methods could take an `includeParent` flag which causes any parent dialog instances or path segments to be enumerated/included.

When enumerating dialog instances we should return the current DialogInstance, current DialogContext, and a flag indicating if we're on the last/active instance.  

[enhancement]

**Comment by mrivera-ms** [comment]
We will not take this for now. Closing the issue. We can open it again if there is a business need.
