### ISSUE TITLE
Variables / Expressions are not parsed in JSON object

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#4050]
When using a variable or expression in a JSON object it does not get parsed.
![image](https://user-images.githubusercontent.com/49873947/83914288-42146f80-a771-11ea-94d4-4eb975083d59.png)
![image](https://user-images.githubusercontent.com/49873947/83914298-4771ba00-a771-11ea-8127-03dbc4970852.png)
![image](https://user-images.githubusercontent.com/49873947/83914311-4c366e00-a771-11ea-8cb0-f06cc20c4a8e.png)

**Comment by cxbuilders** [comment]
@vishwacsena Am using set properties now as a step before, which is fine. Having this feature would make it a more clean approach. Thanks.

**Comment by Danieladu** [comment]
May I apply the deep data binding method (`ReplaceJTokenRecursivelyAsync` from `body` property of `HttpRequest` action) to the other three properties? (`value` property of `SetProperty`, `Assignments` of `SetProperties`, and `value` property of `EndDialog` action)

**Comment by boydc2014** [comment]
@vishwacsena as i went through again, it's hard to find a unified solution that both take care of consistency and non-breaking change. 

The best recommendation i got now, is to share out the code employed in the processing of httpBody inside httpRequest, which support arbitrary level of data binding for json. Share that to the scenarios (beginDialog, endDialog, setProperties, etc), basically anywhere json can be passed.  

That said, from user POV, the place they can pass json, they will be able to say 
```json
{
"prop": "${utcNow()}"
}
```
which is supported by the data binding solution we built on top level.

and they are also able to say `={ "prop": utcNow() }` which is our object initialization syntax in low level.

what do you think

**Comment by boydc2014** [comment]
@cxbuilders With #4291  get merged, you will be able to use deep JSON databinding in a few places
* value property in SetProperty
* PropertyAssignment (for SetProperties)
* value property in EndDialog
* body in HTTPAction

**Comment by cxbuilders** [comment]
great news, thanks!
