### ISSUE TITLE
[Engineering] Reduce CI Pipeline duration 

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#4055]
The CI pipeline takes between 25-27 minutes, there's room for improvement as the CI doesn't deploy or publish code.

The duration can improve by addressing #4047 & #4048.

___

- [ ] Disable or remove superfluous stages and steps
- [ ] Investigate "better" parallel builds

**Comment by mrivera-ms** [comment]
> The CI pipeline takes between 25-27 minutes, there's room for improvement as the CI doesn't deploy or publish code.
> 
> The duration can improve by addressing #4047 & #4048.
> 
> * [ ]  Disable or remove superfluous stages and steps
> * [ ]  Investigate "better" parallel builds

The CI Pipeline runs under 20 minutes now. Exceptions happen when there is a high volume of jobs and available build agents are not enough to cover the volume. We have done work to reduce the use of build agents by selecting the API compatibility verifications to only libraries that have been changed.

![image](https://user-images.githubusercontent.com/44449640/89604030-3ef43900-d81f-11ea-9c6d-04dddc2826cb.png)
