### ISSUE TITLE
Teams `MessageActionsPayload` class is missing `linkToMessage` property

### ISSUE THREAD

**Issue by vman** [microsoft/botbuilder-dotnet#4062]
## Version
Bot Builder .NET SDK 4.9.3

## Describe the bug
Teams `MessageActionsPayload` class is missing the `linkToMessage` property.

The Generated folder in the master branch seems to be updated 9 months ago and could be the reason why it doesn't have the linkToMessage property.

## To Reproduce
Observe the MessageActionsPayload class: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/Teams/Generated/MessageActionsPayload.cs

## Expected behavior
LinkToMessage property should be present in the MessageActionsPayload class.

## Screenshots
![image](https://user-images.githubusercontent.com/173794/84570668-db9ddb80-ad86-11ea-997d-58e1792ca3a3.png)

[bug]

**Comment by vman** [comment]
Happy to create a PR for this if everything is OK to go ahead?

**Comment by vishwacsena** [comment]
@vman please feel free to issue a PR and request review from @johnataylor

**Comment by vishwacsena** [comment]
We will review the PR later today and likely merge it in pending any review feedback.

**Comment by gabog** [comment]
Thanks again for the submission, this has been implemented as part of Implemented as part of https://github.com/microsoft/botbuilder-dotnet/issues/4120, closing this one.
