### ISSUE TITLE
Switch with number in strings as value -> Error: Arguments must either all be numbers or strings

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#4071]
When using a switch statement on a string (coming from Api JSon payload as string) that contains numbers;
![image](https://user-images.githubusercontent.com/49873947/84156438-c4e74400-aa69-11ea-8bac-2add0456fa98.png)

It throws an error:
![image](https://user-images.githubusercontent.com/49873947/84156474-d29cc980-aa69-11ea-8cfc-9027a710044d.png)

When just adding a letter after the 23 like 23A it works ok.

Somewhere the 23 does get converted into a number although I specifically set the Value Type to string.

Am currently using this as a workaround:
![image](https://user-images.githubusercontent.com/49873947/84156900-5ce52d80-aa6a-11ea-8f23-29ee5a65397a.png)

## Version

858ef680

**Comment by vishwacsena** [comment]
Not sure if this is an issue with expressions or with adaptive itself I suspect the later but @boydc2014  can you investigate and comment?

**Comment by xieofxie** [comment]
We expect a string in the case https://github.com/microsoft/botbuilder-dotnet/blob/54bad3490e0167ae5cfa08be58a3100787014fc2/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/Case.cs#L25 and parse it to number if it is https://github.com/microsoft/botbuilder-dotnet/blob/54bad3490e0167ae5cfa08be58a3100787014fc2/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SwitchCondition.cs#L122. Then when the case is a string of number, it will be type of number. I think we should update schema of Case to correct this.

**Comment by vishwacsena** [comment]
We will address this as a bug in the next release.
