### ISSUE TITLE
Allow code analysis to be disabled by a build command line argument

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-dotnet#4076]
Code analysis now runs every time a solution or project is built. That means it runs in just about all of our pipelines. CA needs to be run in only the CI-PR pipelines. In the other pipelines it just increases their running time and makes them more liable to break.

Right now there is no easy way to disable CA. Setting up CA so the build argument "-p:RunCodeAnalysis=false" could disable it would mean it could be skipped where it is not needed.

**Comment by gabog** [comment]
OK, once I finish enabling CA on all assemblies and move the analyzers to dirprops, I think I can add a condition in dirprops to exclude the analyzers from the nuget references.

**Comment by BruceHaley** [comment]
For Microsoft.Bot.Builder.sln the msbuild argument to disable CA turned out to be "-p:RunAnalyzersDuringBuild=false".

**Comment by BruceHaley** [comment]
PR #4074 resolves this issue.
