### ISSUE TITLE
Support TTL for CosmosDbPartitionedStorage in Microsoft.Bot.Builder.Azure

### ISSUE THREAD

**Issue by WalkingDisaster** [microsoft/botbuilder-dotnet#4084]
**Problem Statement**
The current implementation of `CosmosDbPartitionedStorage` does not support the declaration of a default TTL when creating a new Cosmos DB container. Supporting default TTL requires either creating the container before the code runs or updating the container at a later time to have a default TTL.

**Proposed Solution**
Add `TimeToLive` to `CosmosDbPartitionedStorageOptions` and respect the option when creating a new Cosmos DB container.

**Describe alternatives you've considered**
Considered creating a callback hook (`Action<ContainerBuilder>`) that would be called in `CreateContainerIfNotExistsAsync` before invoking `CreateIfNotExistsAsync` on the `ContainerBuilder`. This seemed a little too heavy-handed.

**Additional context**
If this is accepted, I'm prepared to submit a PR.

[enhancement]

**Comment by EricDahlvang** [comment]
Other requests for this:

https://github.com/microsoft/botbuilder-dotnet/issues/3086
https://github.com/microsoft/botframework-sdk/issues/5890

**Comment by mdrichardson** [comment]
@WalkingDisaster The SDK team has decided not to implement TTL (or additional Cosmos SDK features) so as not to duplicate the Cosmos SDK, itself.

However, [@EricDahlvang provided a GREAT programmatical workaround](https://github.com/microsoft/botframework-sdk/issues/5890#issuecomment-642810480) or you can also [set it manually](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv3%2Cjavav4#enable-time-to-live-on-a-container-using-azure-portal).
