### ISSUE TITLE
Streaming: Minimize memory footprint from connector client and other disposable objects

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#4111]
We may be hitting premature memory Pressure Conditions inside the bot builder SDK  (.net core version 4.9) when using the streaming extensions because the BotBuilder SDK is relying on the .net garbage collector to do cleanup instead of using the IDispose pattern in many places.

We are seeing a runaway amount of memory and threads being consumed in our test bot (simple echo bot) increase slightly with each connection.  Eventually this leads to us having to reset the bot it refuses any more connections. 

NOTE: we noticed this when we had to scale back our number of bot instance from 7 to three supporting 500 connections per hour.  This amounts to about 3 connections per second per instance for simple echo scenarios.

 ![image001](https://user-images.githubusercontent.com/21318528/84943409-27a79380-b099-11ea-8834-dac4e39732ad.png)

When I put a GC in the beginning of our bots OnTurnAsync

![image005](https://user-images.githubusercontent.com/21318528/84943877-e2379600-b099-11ea-9056-205e120fa175.png)

We go from incrementally increasing memory allocations with every connection:

![image002](https://user-images.githubusercontent.com/21318528/84943901-e8c60d80-b099-11ea-85ce-b7bcbe384b23.png)

To non-increasing memory allocation:

![image003](https://user-images.githubusercontent.com/21318528/84943927-f085b200-b099-11ea-8dc6-5fed8c64e3d1.png)

From running profiling I believe the some of the memory issues are happening in this path:

![image007](https://user-images.githubusercontent.com/21318528/84943963-fd0a0a80-b099-11ea-96ee-3df25cf7646c.png)

Looking at the code a bit more, there is a call here that creates a ConnectorClient that gets the client version. 

I believe this winds up initializing a ServiceClient that creates an httpclient connection to local host.  Since it does not appear that Dispose is ever called on this ServiceClient we are leaking memory under load (until GC can run).

I also don’t see where Dispose is ever called on the IConnectorClient which I think could be bad as we would wait on the GC to cleanup underlying connections.

 ![image008](https://user-images.githubusercontent.com/21318528/84944065-1743e880-b09a-11ea-9f39-d1a8b2c436a8.png)

Above is the callstack/allocations for the highlighted code, this never gets cleaned up until the .net framework runs GC which takes awhile especially during load.

**Comment by mrivera-ms** [comment]
@carlosscastro , would you please take a look at this?

**Comment by carlosscastro** [comment]
We already merged a Pr with a number of improvements in streaming memory and connection management. 

Post R10, by end of August, we plan to ship another set of improvements that should end in significant reduction of the overhead documented above.
