### ISSUE TITLE
EmitEvent action should map strings passed with "error" events to Exceptions

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4119]
**Is your feature request related to a problem? Please describe.**
So in composer you can emit an "error" event but you can only pas simple values like strings or JObjects as the `value` of an event.  The "error" event is special in that it expects and `Exception` as the value.  

**Describe the solution you'd like**
To better support "error" events raised by composer flows, the `EmitEvent` action should map string values into Exception objects when an "error" event is raised.

**Additional context**

[enhancement]

**Comment by vishwacsena** [comment]
Alternate is to add a `ThrowException` action which accepts a message and propagates up.

**Comment by boydc2014** [comment]
Note: E2E scenario is using onError trigger to catch this.
