### ISSUE TITLE
Support SSO on teams via OAuthPrompt

### ISSUE THREAD

**Issue by swagatmishra2007** [microsoft/botbuilder-dotnet#4131]
The following changes are required on oauthprompt to support SSO on teams - 
- Teams supports OAuthCards now. So remove teams from the list of channels that sends signincards instead of oauthcards.
- When SSO fails, teams expects a status code of 412 in the invoke response and not 409 (current behavior). This (breaking) change won't impact any current customers (like PVA), since the logic on clients shipped so far is to consider any non-200 status code a failure.
- Test the above changes on teams and ensure SSO works end to end

**Comment by clearab** [comment]
@johnataylor here's the Teams SSO work that needs to be done.

**Comment by carlosscastro** [comment]
4.9.3 shipped with all the pieces for this.
