### ISSUE TITLE
BeginSkill dialog doesn't save skills results

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4139]
## Version
4.9.3

## Describe the bug
When invoking a skill with `DeliveryMode = "expectReplies"` the `BeginSkill` action won't save the `EndOfConversation` results to the property configured as the `ResultProperty`. The current workaround is to add a `SetProperty` action immediately after BeginSkill and save the results using `turn.lastResult`.

[bug]

**Comment by Stevenic** [comment]
It doesn't work because we do this assignment in `ContinueConversationAsync` which doesn't happen in "expectReplies" mode.

**Comment by gabog** [comment]
This seems to be a duplicate for #3953, closing
