### ISSUE TITLE
Property sheets use inconsistent case for labels 

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4142]
## Describe the bug
Our use of case for property labels is all over the map. We should use consistent case for property labels. 

![image](https://user-images.githubusercontent.com/698939/82767751-ac76f880-9dde-11ea-9f50-dfa80e79e2be.png)

**Comment by luhan2017** [comment]
Transferring this issue to sdk, this needs the component schema update. @vishwacsena for your awareness.
