### ISSUE TITLE
MultiLanguageRecognizer‘s languagePolicy should follow the LG UseLanguagePolicy convention

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#4143]
We are enabling the MultiLanguage feature of Composer, and we want LU and LG follow the same LanguagePolicy Rule. But we found that MultipleLanguageRecognizer does not take the LanguagePolicy in DialogManager which is used by LG. (DialogManager.UseLanguagePolicy(New LanguagePolicy(defaultLanguage)))

Expected behavior:
Set the defaultLanguage in the appsettings. 
DialogManager.UseLangugaePolicy(New LanguagePolicy(defaultLanguage))
LU and LG should both follow the the fall back rule.

**Comment by EPinci** [comment]
Hello, I think I'm hitting this.
Is there a workaround while waiting for the fix?
