### ISSUE TITLE
Update all prediction options for luisrecognizer to be expression properties

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#4149]
Update `PredictionOptions` to be an expression. Given expressions can also be initialized inline and given composer does not expose this yet, I suspect this would not be a breaking change. 

Related:
- microsoft/BotFramework-Composer#3317
- microsoft/botframework-cli#805

@chrimc62 FYI

**Comment by vishwacsena** [comment]
Tagging P0 since this is an ask to light up VA/ skills

**Comment by cleemullins** [comment]
Per @tomlm, moving to backlog and removing P0 label.

**Comment by cleemullins** [comment]
@vishwacsena  Can you help us figure out it's priority, and who can do the work and when?

**Comment by tomlm** [comment]
this was already checked in 394cc22
