### ISSUE TITLE
 Remove TurnContext from LuisRecognizerOptions RecognizeAsync 

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#4157]
LuisRecognizerOptions .RecognizeAsync would be infinitely more useful if it didn't have a hard dependency on ITurnContext. With the latest changes isolating out the utterance the only use of ITurnContext is to perform TraceActivityAsync. (Without getting into the question of TurnContext having a TraceActivityAsync). Would RecognizeAsync not be better served with TraceActivityAsync being a delegate passed in from whatever source instead of mandating it be the one on the ITurnContext? This would allow Luis AI to be used outside of a TurnContext which would open the door to all kinds of use cases where you might want to take data from a third party source and analyse its intent. While also making a cleaner seperation of the UI and Data Tiers.

https://github.com/microsoft/botbuilder-dotnet/blob/ec9439e6e64b103e8305537b7549d2503139e496/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizerOptionsV3.cs#L162

**Comment by vishwacsena** [comment]
@DavidStrickland0 thanks for the suggestion. @chrimc62 @tomlm any reason why we cannot do this?

**Comment by srinaath** [comment]
@munozemilio Can you take a look at this ticket?

**Comment by munozemilio** [comment]
@DavidStrickland0 thanks for reaching out. We will evaluate your request and consider it for the next releases

**Comment by munozemilio** [comment]
Hi @DavidStrickland0 I will flag it as R11 (our next release cycle). Thanks!

**Comment by carlosscastro** [comment]
Adding to backlog for R11 consideration

**Comment by mrivera-ms** [comment]
@mdrichardson, could you please take a look at this? Also, please verify if it needs to be ported to the other languages.
