### ISSUE TITLE
Increase coverage for botbuilder package

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-dotnet#4175]
Increase unit test coverage of botbuilder package to 80%

Current Botbuilder package coverage is at 72.7%, effort to cover subpackages and files below 70% could make a big impact:

* Inspection (Subpackage) | 68.4
* Streaming (Subpackage) | 37.05
* AdapterExtensions.cs | 33.33
* BotAdapter.cs | 68.89
* BotAssert.cs | 40
* BotFrameworkAdapter.cs | 40.03
* BotFrameworkHttpStatusCodeErrorDetectionStrategy.cs | 0
* ChannelServiceHandler.cs | 30.43
* InvokeResponse.cs | 66.67
* IStorage.cs | 0
* NullBotTelemetryClient.cs | 33.33
* SkypeMentionNormalizeMiddleware.cs | 66.67
* TraceTranscriptLogger.cs | 52

**Comment by Virtual-Josh** [comment]
Closing this issue for now as unit tests have been deprioritized for R10.
