### ISSUE TITLE
Data-driven resource explorer to support component customization

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4179]
For reusable components we need a way to customize declarative assets like .lu, .lg, .qna and .dialog.  Today we also require code configuration of the resource explorer.  Our overall component story is to make use of native package systems (nuget, npm).  We want to automatically be able to discover their declarative components and to allow overriding definitions without modifying the package assets directly.  More details can be found here: https://microsoft.sharepoint.com/:p:/t/ConversationalAI785/EfipBMDcmDpLrvt-0Eh22ncBz8P0Sywj2QAubh-Sa2mw_g?e=slo91S

This proposal has two parts:
1) dialog:merge has been changed so that when it builds the app.schema it also generates an app.resources file which lists the folder order when looking for declarative assets.  We want the resource loader to be initialized from this file if present in the bot directory.
2) In order to support an inheritance override model we need to be able to find the next available version of an asset, i.e. if we have project1 which includes component1 then we would look for an asset like a.lg in project1 and then in component1.  Once we found it, that would be the asset all consumers of a.lg would use.  The issue is that we would like to be able to have the project a.lg include the hidden component1/a.lg in order to extend rather than just override it.  To do this we would add a resource explorer method to return the next version of a file given its full path.  
[enhancement]

**Comment by mrivera-ms** [comment]
@darrenj , please prioritize and assign this item. Thank you.

**Comment by mrivera-ms** [comment]
Ping @darrenj
