### ISSUE TITLE
Support inheritance for .lg

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4180]
This relies on #4179.

1) Add an inherit: resource loaded protocol which would include the next version of the file it is found in from the resource loader.   
2) Add an override decorator to indicate that a definition is an override of something found in parent versions.  This would relax the constraint that template names must be unique.

Imagine project includes component1 and component1 defines a template "foo" in a.lg that you want to override for your project.  To do this you would define project1/a.lg like below.  Because of app.resources and the resource loader, this definition would override the component1/a.lg version, but with this mechanism you can override only the pieces you want to change.  
```
component1/a.lg:
> This would be the original version of the foo template
# foo
- Original

project/a.lg:
> This would find the "next" version of this file in the resource loader, ie. component1/a.lg.  
[base](inherit:)

> This would override the template component1 version of "foo".
> The decoration indicates it is ok to have multiple versions.
> Alternatively we could allow this only if inherit is there or always.
# foo:override
- Modified
```

[enhancement]

**Comment by mrivera-ms** [comment]
@GeoffCoxMSFT is this something we will take for R12?

**Comment by boydc2014** [comment]
@chrimc62 do you think we are ready to take this and the corresponding changes to resourceExplorer and lu (maybe qna as well).

**Comment by chrimc62** [comment]
I've had on my list for a while to write-up a proposal and I would love to solve this all-up.

Being able to add "override" to be able to replace an included LG template would be useful.  We don't need the inherit thing because we need to solve the naming problem all-up.  For LU/QnA being able to add to or replace the definition would also be useful.  To solve the naming problem: 
1) Modify the resource loader so that component resources can be referred to using the package name as a namespace, i.e. MyComponent:foo inside of templates or MyComponent:a.lg in imports.
2) Including a component ensures that declarative resources can be found by the resource loader.  Would be great if this happens automatically from doing something like dialog:merge.
3) Within a component resource references do not need to be explicit for the package, i.e. in MyComponent, "foo" would mean MyComponent:foo in my project "foo" would mean the project foo.
4) We need to add 

Once we have this we would not name both files a.lg.  myOverrides.lg would look like this:
```
> This is importing an LG file from a component
[import A](component1:a.lg) 

> Override the definition of the template "component1:foo" and call the base template which came from a.lg
# component1:foo override
- modified ${base()} and call a different template ${component1:blah()}
```

Now when I make an instance of a dialog from component1 by default it includes the a.lg found inside of component1.  If I choose to override it for a particular instance with myOverrides.lg, then the lookup of "foo" inside of Component1 would look for "Component1:foo" which would be the overridden one.
