### ISSUE TITLE
FileStorage race condition prevent eTag from always being honored

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#419]
In `FileStorage.write()` we do [concurrency checks](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Core.Extensions/FileStorage.cs#L123) outside of a lock which means that it's not guaranteed to be accurate should two separate writers attempt to update the same object at the same time.  The result will be "Last Write Wins" even though the caller requested a concurrency check be made.

**Comment by sgellock** [comment]
FileStorage support has been removed,
