### ISSUE TITLE
Keep language policy consistent across platforms

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#4191]
## description
Currently, the SDK uses `var cultureCodes = CultureInfo.GetCultures(CultureTypes.AllCultures)` to get all cultures.
Here are some data from the different platform:

platform | locale number
-- | --
windows 10 | 848
ubuntu 18.04 | 723
mac | 931

This will result in different language fallbacks on different platforms.

## How to fix
1. Consistent with the locale fallback of each platform. (Maybe hard code the language fallback?)
2. Support customized language policy.

**Comment by boydc2014** [comment]
This is more of an adaptive dialog issue, I personally don't think this is an issue, we will need @tomlm's input as well.

**Comment by boydc2014** [comment]
After triage, we will leave this as "backlog" until customer runs into this and guide us have a direction.

**Comment by mrivera-ms** [comment]
Since we are not going to address this issue now, it will be closed. Reopen when there is a customer request.
