### ISSUE TITLE
update autoEndDialog in Adaptive component schema to support expressions

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4203]
Users need to be able to dynamically set this property on the dialog. For example, when operating as a Skill, `autoEndDialog` needs to be set to `true`, when _not_ operating as a skill, it needs to be set to `false`.

```json
{
  "autoEndDialog": {
    "type": "boolean",
    "title": "Auto end dialog",
    "description": "If set to true the dialog will automatically end when there are no further actions.  If set to false, remember to manually end the dialog using EndDialog action.",
    "default": true
  },
}
```

**Comment by luhan2017** [comment]
Gabo told me that we can use this expression to decide whether it is a skill mode:
```
turnContext.TurnState.Get<IIdentity>(BotAdapter.BotIdentityKey) is ClaimsIdentity claimIdentity && SkillValidation.IsSkillClaim(claimIdentity.Claims)
```
I think we need to expose this to user, so that user can create an expression to dynamic decide autoEndDialog is true or false.
