### ISSUE TITLE
Connect $kind to .lu/.lg files

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4205]
We need a way in the schema to connect a $kind property to .lu or .lg files in order to enable the UI to render the appropriate control.  For LUIS, we don't point to the corresponding .lu file.  For the generator we do point to the .lg file, but we don't know it is an .lg file.  We should either add a $role or be explicit about the semantics so composer can discover the connection through the schema.

[enhancement]

**Comment by tomlm** [comment]
I have no idea what you are talking about.

**Comment by chrimc62** [comment]
We don't need this fixed.  Composer can identify that a property uses ILanguageGenerator or IRecognizer from the schema and do the right thing.
