### ISSUE TITLE
Add a flag for skill mode in turn for adaptive dialog memory state

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4209]
**Is your feature request related to a problem? Please describe.**

I don't find a way to determine whether bot is running in skill using adaptive dialog memory state.
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-memory-states?view=azure-bot-service-4.0#turn-scope

**Describe the solution you'd like**

Add a flag in turn like turn.isSkill. This will also simplify all the codes of
`turnContext.TurnState.Get<ClaimsIdentity>(BotAdapter.BotIdentityKey) is ClaimsIdentity botIdentity && SkillValidation.IsSkillClaim(botIdentity.Claims)`.

[enhancement]

**Comment by compulim** [comment]
@vishwacsena Could you take a look at this?

**Comment by vishwacsena** [comment]
Rather than set a property, should this instead be a prebuilt function injected to expressions by adaptive? 

@Stevenic @gabog @tomlm @boydc2014

**Comment by gabog** [comment]
Hi @xieofxie, can you provide an example and how would you use this property if available? As you stated in the issue, you can find this out using code but I'm not clear on how will you use it.

PS: can you also remove the boilerplate code from the original issue and just leave the relevant parts so it is easier to read?

**Comment by xieofxie** [comment]
Hi @gabog the issue contains two parts:
1. I would like a flag in declarative's memory state like `turn.isSkill`. An example usage: when called as a skill, bot will return data sometimes while called directly, it will not. By checking this flag, I would determine if I should execute the data generation code which could be time-consuming.

2. If we have `turn.isSkill`, there should be a counterpart in C#, thus it will simplify all the usages of current skill checking code.

Thanks

**Comment by gabog** [comment]
Hi @xieofxie, can you provide a few practical examples on when would you need to know if you are running as a skill or not as a composer user?

**Comment by xieofxie** [comment]
Hi @gabog since it is not valid, I don't have a composer example now. I could find some C# examples for you https://github.com/microsoft/botframework-skills/search?l=C%23&q=IsSkill

In summary, return value, code logic like introduction, cancel, interruption would be different. Thanks~

**Comment by gabog** [comment]
Thanks for the query @xieofxie, that helps a lot to understand the need. We are currently trying to get a clear understanding one when do you need to know if something is running as a skill or not. I'll put this request in the backlog for now and will get back to it once we are done with the research. Sounds good?
