### ISSUE TITLE
Add helper for composing delay(), typing(), event(), endOfConversation(), invokeResponse(), etc.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#421]
After stripping these methods off the `TurnContext` it's now cumbersome to compose all of the non-message activity types.  We could add a new `ActivityFactory` helper class that makes it easy to compose all of these again.

**Comment by Stevenic** [comment]
That only exists for C#, the JS SDK doesn't have that.  Also, not all activities are supported. Things like "delay" and "invokeResponse" are missing.  And then it doesn't help you to know what fields should be populated.  Do you know which field you use to specify the delay interval for instance?

**Comment by JonathanFingold** [comment]
On the parity side, that makes sense, and on the missing CreateX side, too.

Since [for C#] the CreateX methods return a strongly typed object, it's easy (if an additional step) to find the associated properties.

In any case, this was not meant as an objection.

**Comment by cleemullins** [comment]
I thought these existed in c#. We must have removed the at Bill's request at some point.

**Comment by gabog** [comment]
Closing as part of R10 triage.
