### ISSUE TITLE
Store Teams Context in SQL database / Table storage to send Proactive notification to specific User 

### ISSUE THREAD

**Issue by AntonyEy** [microsoft/botbuilder-dotnet#4213]
Hello,
Currently I am working on Botframework V4 to create AD authenticated Chatbot  which works on teams. 
But i am facing some issue in Sending proactive messages to Specific User .
What is requirement to send Proactive message to specific user who had logged to my chat bot

Thanks And Regards
Anto

**Comment by v-kydela** [comment]
Thanks for the question, @AntonyEy 

You might find this document helpful: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages

Can you tell us what you've tried so far? Please include links, code samples, and screenshots when appropriate.

**Comment by AntonyEy** [comment]
@v-kydela I have used Concurrent Dictionary to save the conversation reference, And I am able to send Proactive message . But next day when i send the proactive message  to teams , User is not getting Proactive message . 
I think Concurrent Dictionary is getting erased.
Can you suggest  me some method to store conversation reference permanently
Thanks And Regards
Antony

**Comment by AntonyEy** [comment]
@v-kydela https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp I had followed above link

**Comment by v-kydela** [comment]
@AntonyEy - It sounds like you're saying you're storing information in the bot's local memory. You need to use bot state: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-state

**Comment by v-kydela** [comment]
@AntonyEy - Are you still working on this?

**Comment by AntonyEy** [comment]
@v-kydela  Thank you 
I have completed proactive messaging. I have stored tenant id and from id and service url along with user email into table storage. And created a api for sending proactive message using above data.
