### ISSUE TITLE
enable libraries to be compiled when added in another solution

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4217]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

When I added libraries in another solution for debugging purpose, it will complain `Could not find rule set file BotBuilder-DotNet.ruleset` thus not compile.

To reproduce:
- clone this project to someplace/botbuilder-dotnet
- clone https://github.com/microsoft/botframework-skills/tree/hualxie/compile_demo to someplace/botframework-skills
- open someplace/botframework-skills/skills/csharp/Skills.sln and compile Microsoft.Bot.Schema

**Describe the solution you'd like**

Could find BotBuilder-DotNet.ruleset.

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by compulim** [comment]
@cleemullins Could you take a look at this?
