### ISSUE TITLE
Add custom telemetry event

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#4234]
Add the capability to define a custom telemetry event using SDK capability.

@garypretty - can you add details?

**Comment by garypretty** [comment]
PR raised to add a new action into the SDK.  This action allows a user to specify an event name and, optionally, additional properties to be attached to the event.  The event is tracked using the registered IBotTelemetryClient and will be captured alongside the existing passive telemetry capture that is already present.
