### ISSUE TITLE
The "turn.recognized" property of an adaptive dialog does not contain the entity if the None intent hits

### ISSUE THREAD

**Issue by berhen** [microsoft/botbuilder-dotnet#4244]
## Version
4.9.3

## Describe the bug
When using a "Cross-Trained Recognizer Set" with a LuisAdaptiveRecognizer, if the "None" intent is hit, then the "turn.recognized" property does not contain the entity, even though the LUIS recognizer result contains it. 
If I connect the same entity to a different intent than "None" the "turn.recognized" property contains the entity.

## Expected behavior
The entity should be included in the "turn.recognized" property of an adaptive dialog if the "None" intent hits.

## Screenshots
![image](https://user-images.githubusercontent.com/55977816/86887477-df5c1e00-c0f8-11ea-9f27-87ace7e27d1d.png)

[bug]

**Comment by Virtual-Josh** [comment]
@stevkan @anusharavindrar can you provide an update for this issue?

**Comment by anusharavindrar** [comment]
@Virtual-Josh, I will attempt a repro on my end and update the thread.
@berhen, are you following any specific sample? Can you elaborate on the repro steps so that I can try it on my end?

**Comment by berhen** [comment]
@anusharavindrar I'm not following a specific sample, we are using parts of several examples, based on our needs.

Our RootDialog uses a CrossTrainedRecognizerSet with three recognizers, a LUIS one, and two QnA Maker:
![image](https://user-images.githubusercontent.com/55977816/87543889-d1347180-c6a5-11ea-972e-d2917ef518dd.png)

There are LUIS entities for basic tasks of our conversation flow (like logout, help, feedback..), which are not connected to a specific intent. That causes them to be recognized with the "None" intent. But when that happens, the "turn.recognized" property only contains the intent "None", not the recognized entity.

If I create a specific intent and add an utterance that hits the same entity, then both, the intent and the entity are contained in the "turn.recognized" property.

**Comment by anusharavindrar** [comment]
@berhen, thanks for the above info. I will repro on my end and update the thread with my findings.

**Comment by anusharavindrar** [comment]
@berhen, apologies for the delay. I am currently working on the repro and experiencing issues specific to my testing sample, will update the thread soon.

**Comment by berhen** [comment]
@anusharavindrar Okay thanks

**Comment by anusharavindrar** [comment]
@berhen, this looks like the expected behavior. When every recognizer in the RecognizerSet has a None intent, it just returns a default NoneIntent and not the actual None Intent from LUIS. 
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/CrossTrainedRecognizerSet.cs#L225

**Comment by berhen** [comment]
@anusharavindrar Thank you for the update on this issue. I was not aware of that behavior, thanks for the clarification. Is there any way to trigger / pick the actual LUIS intent in the case that every recognizer in the set has a None intent?

**Comment by anusharavindrar** [comment]
@berhen, as of now this is the default behavior.
@tomlm, any pointers on whether this issue should be considered a DCR or if it's going to stay this way?

**Comment by peterinnesmsft** [comment]
@tomlm are you able to take a quick look and help with @anusharavindrar's question?

**Comment by tsuwandy** [comment]
@boydc2014, @cosmicshuai, any update on this issue?

**Comment by cosmicshuai** [comment]
@tsuwandy I am still working on this issue. I w will update in this thread if there are any progress.

**Comment by cosmicshuai** [comment]
@berhen @tsuwandy @boydc2014 
I created a draft to fix this issue. Could you have a look does this resolve your concerns?
The idea is after checking all the intents and ambiguity, instead of returning a new RecognizerResult, I just do a  iteration of all results in from the recognizers and merge all existing entities. 
I have a unit test for this scenario and will try to add an E2E test with Luis recognizer.

**Comment by berhen** [comment]
@cosmicshuai Looks like a good solution to me. Thanks for your work on this issue.
