### ISSUE TITLE
Slack interactive messages not firing

### ISSUE THREAD

**Issue by UlrichBodentien** [microsoft/botbuilder-dotnet#4246]
## Version
`4.9.3`

## Describe the bug
I have followed the tutorial on setting up a Slack channel on my bot, which is using ABS
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs

I have used a Choice Prompt, to display some buttons using the HeroCard ListStyle. The choices renders correctly, however, when I click them, no requests are comming into my webserver.

## To Reproduce

1. Add a simple choice prompt with HeroCard ListStyle
2. Add the slack channel to ABS following the guide here https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs
3. Follow the optional step and enable Interactive messages
4. When clicking on the buttons in slack, no api request is firing on the bot's webserver

## Expected behavior
I would expect the buttons fires a request on the webserver

## Additional context
I have also created a SO post, where I in detail show the configurations I have made from the Slack channel tutorial. https://stackoverflow.com/questions/62790848/slack-interactive-message-not-triggering-post-request-on-my-bot

[bug]

**Comment by youyu16** [comment]
Slack deprecated some of the API methods and trigger an error in Slack Channel. The fix is on its way.

**Comment by v-kydela** [comment]
Linking: https://github.com/microsoft/BotBuilder-Samples/issues/2553

**Comment by kittu610** [comment]
This following [documentation ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs) has updated. but in document it mentioned that to add a bot user but i unable to find bot user field in slack application creation.
please find the below attached image
![image](https://user-images.githubusercontent.com/49742373/87001752-bf4e5c80-c1d5-11ea-839b-1f0a9dcfb75d.png)

i have searched in App home page also but unable to find it 
![image](https://user-images.githubusercontent.com/49742373/87001801-e573fc80-c1d5-11ea-8169-a10031415fd9.png)

**Comment by youyu16** [comment]
I think slack move the bot user from a standalone tab to the App Home. 
![image](https://user-images.githubusercontent.com/17819112/87003098-8c17c780-c1ed-11ea-9813-3d5efa66fa3b.png)

**Comment by youyu16** [comment]
@UlrichBodentien The fix is checked in please check again.

**Comment by EricDahlvang** [comment]
@UlrichBodentien can you confirm the fix please?

**Comment by UlrichBodentien** [comment]
> @UlrichBodentien can you confirm the fix please?

Yes, I can confirm it. I have tested it, and it works in the bot I am working on

**Comment by EricDahlvang** [comment]
Thank you.
