### ISSUE TITLE
Can't call skill in direct line speech channel

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4254]
## Version
What package version of the SDK are you using.

https://github.com/microsoft/botbuilder-dotnet/commit/a253e4bd020dfc900db93bdc847ce6b1ba08daf6

## Describe the bug
Give a clear and concise description of what the bug is.

When calling a skill host in direct line speech, the skill could not reply due to audience is null.

It turns out these two functions are not same yet https://github.com/microsoft/botbuilder-dotnet/blob/a253e4bd020dfc900db93bdc847ce6b1ba08daf6/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L429
https://github.com/microsoft/botbuilder-dotnet/blob/a253e4bd020dfc900db93bdc847ce6b1ba08daf6/libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs#L88

It seems we need at least add `context.TurnState.Add(OAuthScopeKey, scope);` in the second function.
We should create parity for ProcessActivityAsync & ProcessStreamingActivityAsync.

## To Reproduce
1. Deploy a skill host (VA) & a skill
2. Connect skill host through direct line speech (like via https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant)
3. Invoke skill
4. See error `Exception thrown: 'System.ArgumentNullException'`

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by compulim** [comment]
@johnataylor Could you take a look at this?

**Comment by stevengum** [comment]
I'll be opening a PR today for this, and have enlisted carlosscastro for a code review.
