### ISSUE TITLE
Missing InstallationUpdate Event handler for ActivityHandler

### ISSUE THREAD

**Issue by rbakshi2** [microsoft/botbuilder-dotnet#4287]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Trying to capture the InstallationUpdate Event is not possible through TeamsEventHandler as the handler is missing a case for InstallationUpdateEvent

**Describe the solution you'd like**
Would be awesome to have a method in TeamsEventHandler to support a method such as OnInstallationUpdateAsync to catch this event

[enhancement]

**Comment by EricDahlvang** [comment]
The InstallationUpdate event is not Teams specific, so this should be in the ActivityHandler (which TeamsActivityHandler inherits from).

ref: https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#installation-update-activity

**Comment by EricDahlvang** [comment]
This should also be updated, if Teams is sending this event: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#uncategorized

**Comment by compulim** [comment]
@EricDahlvang I am assigning this to you. Please feel free to re-assign to appropriate people if needed.

**Comment by EricDahlvang** [comment]
see parent issue: https://github.com/microsoft/botframework-sdk/issues/5959

**Comment by compulim** [comment]
@munozemilio do we add "Bot Services" and "customer-reported" for internal partner teams? Internal partner = under Microsoft org.
