### ISSUE TITLE
Solve diffs between C# and SDK swagger files

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-dotnet#4295]
Get resolution on wether port the following diffs to SDK file, open individual issue for porting the code or safe to ignore:

- [ ] 1) /v3/conversations/{conversationId}/members/{memberId} -- C# has a get endpoint that SDK does not
- [ ] 2) C# added /v3/conversations/{conversationId}/handoff
- [ ] 3) Locale description changed for Activity
- [ ] 4) C# added transcript property for Activity
- [ ] 5) C# added locale property for ConversationReference 
- [ ] 6) C# added imageAltText property for CardAction 
- [ ] 7) C# added HandOffParameters model
- [ ] 8) C# added tokenExchangeResource property for OAuthCard 
- [ ] 9) C# added TokenExchangeResource model
- [ ] 10) C# removed TokenRequest model
- [ ] 11) C# added TokenExchangeInvokeRequest, TokenExchangeInvokeResponse, Expected Replies  models
- [ ] 12) C# removed payment in ActionTypes enum
- [ ] 13) C# added ephemeral and expectReplies in DeliveryModes enum

**Comment by mrivera-ms** [comment]
Closing per @axelsrz .
