### ISSUE TITLE
Allow defining Autoscale options in CosmosDbPartitionedStorageOptions

### ISSUE THREAD

**Issue by vifani** [microsoft/botbuilder-dotnet#4310]
The current class CosmosDbPartitionedStorageOptions used to configure CosmosDbPartitionedStorage doesn't allow to define the container throughput with in auto scale mode. It's possible to consider the change of the Property ContainerThroughput from int to Nullable<int> in order to allow defining it as null. In the private method CosmosDbPartitionedStorage .CreateContainerIfNotExistsAsync this property is used to call the method ContainerBuilder.CreateIfNotExistsAsync that accepts a Nullable<int> and, if I well remember, this will put the container in auto scale mode if is created in a database with auto scale enabled.

**Comment by munozemilio** [comment]
@mdrichardson @mrivera-ms could you please triage this issue?

**Comment by EricDahlvang** [comment]
Hi @vifani 

Thank you for raising this issue.  We will consider this for a future release.  Until then, it is possible to create an IHostedService implementation to provide custom cosmosdb container creation:

this demonstrates a custom Time to Live setting for the container:

```cs
public class CosmosDbStorageInitializerHostedService : IHostedService
{
    readonly CosmosDbPartitionedStorageOptions _storageOptions;
    readonly int _cosmosDbTimeToLive;

    public CosmosDbStorageInitializerHostedService(IConfiguration config)
    {
        _storageOptions = new CosmosDbPartitionedStorageOptions()
        {
            CosmosDbEndpoint = config["CosmosDbEndpoint"],
            AuthKey = config["CosmosDbAuthKey"],
            DatabaseId = config["CosmosDbDatabaseId"],
            ContainerId = config["CosmosDbConversationStateContainerId"]
        };

        _cosmosDbTimeToLive = config.GetValue<int>("CosmosDbTimeToLive");
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        using (var client = new CosmosClient(
            _storageOptions.CosmosDbEndpoint,
            _storageOptions.AuthKey,
            _storageOptions.CosmosClientOptions ?? new CosmosClientOptions()))
        {
            // Create the contaier with the provided TTL
            var containerResponse = await client
                .GetDatabase(_storageOptions.DatabaseId)
                .DefineContainer(_storageOptions.ContainerId, "/id")
                .WithDefaultTimeToLive(_cosmosDbTimeToLive)
                .WithIndexingPolicy().WithAutomaticIndexing(false).Attach()
                .CreateIfNotExistsAsync(_storageOptions.ContainerThroughput)
                .ConfigureAwait(false);
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
```

then in startup:

```cs
// Add the Initializer as a HostedService (so it is called during the app service startup)
services.AddHostedService<CosmosDbStorageInitializerHostedService>();
```

**Comment by daveta** [comment]
Hi @vifani, let us know if that helps - we'll close this issue in a few days.
Thanks!

**Comment by vifani** [comment]
Thank you @daveta and @EricDahlvang. Yes, this helps, however is only a workaround. In my opinion, because the CosmosDbPartitionedStorage class creates the container and in the documentation (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#using-cosmos-db) is stated "skip manually creating a container since CosmosDbPartitionedStorage will create the container for you". So, if this library creates the container for me, it should support all possible scaling options in my opinion. Obviously creating it with custom code is always an option.

**Comment by peterinnesmsft** [comment]
Adding to backlog for further consideration.

**Comment by don4of4** [comment]
This is cut from the same cloth as #4934, but slightly different.
