### ISSUE TITLE
Operation was cancelled

### ISSUE THREAD

**Issue by Mrinnaal** [microsoft/botbuilder-dotnet#4323]
Getting "Operation was cancelled" issue in production. Bot was working fine all the time. Suddenly, from morning we are facing this issue.

**Comment by jwiley84** [comment]
Hi @Mrinnaal There isn't a lot of detail to go on here. Can you post your appId and a time frame this is happening, along with the SDK version you're using, your OS type and what channel this is happening on?

**Comment by Mrinnaal** [comment]
Ideally we had a call with Microsoft cloud team and realised it’s an issue from azure. They fixed it and now everything works fine. @jwiley84 thanks for the swift response 😊 appreciated!!
