### ISSUE TITLE
Validation on Max turn count

### ISSUE THREAD

**Issue by Olakhrisat** [microsoft/botbuilder-dotnet#4342]
## Is your feature request related to a problem? Please describe.
yes, because if the user enters number larger than this number 2147483647 (max integer) the bot composer will stop working

## Describe the solution you'd like
put validation on "Max turn count"

**Comment by cwhitten** [comment]
This is called out as a need to apply a max integer property that describes the language capability (JS, C#, etc)

Once defined in schema, Composer can look to validate against this field.

**Comment by EricDahlvang** [comment]
@boydc2014 would you please take a look at this.

**Comment by cwhitten** [comment]
@EricDahlvang I'll unassign @boydc2014 and ask @vishwacsena to review, accept/not-accept, and prioritize the bug.

**Comment by vishwacsena** [comment]
This is a good suggestion. Will consider this for a future release.

**Comment by mrivera-ms** [comment]
Assigning @boydc2014 . Needs clarification about which Action it refers to.

**Comment by boydc2014** [comment]
Thanks @mrivera-ms, just get back, i will clarify the proposed solution with @cwhitten soon. 

One quick question, @cwhitten can you clarify a little bit one the proposed solution? Do we want to add a new property in the runtime class or scheam or both? and how the design will work for language specific scenario (c#, js, etc)?

**Comment by chrimc62** [comment]
In InputDialog and OAuth input schema files you should add a minimum of 0 and maximum of 2147483647 to the schema for maxTurnCount.  This will allow composer to validate against that.
