### ISSUE TITLE
Feature: Add global Dialog Begin / End Triggers

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/botbuilder-dotnet#4343]
## Is your feature request related to a problem? Please describe.

There is no method currently to create a dialog to be executed when any other dialog begins or ends.

## Describe the solution you'd like

Would like the ability to add a global level trigger on dialog events so that various functionality can be implemented easily.  This will be useful for custom metrics / telemetry capture, adding collection of active feedback from users, etc.

In the trigger, getting the name of the dialog the trigger was activated on would allow the trigger to change behavior as needed.

## Describe alternatives you've considered

Right now the only alternative is to add triggers to each dialog.

**Comment by vishwacsena** [comment]
@bradrlaw one solution is to define a custom event, use EmitEvent action in each child dialog and capture it in the root dialog.

**Comment by cleemullins** [comment]
Close, as Vishwac suggested valid workaround.
