### ISSUE TITLE
Revert temporary changes to functional tests due to template validation errors

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#4356]
Functional tests started failing on June 17th due to changes to template validations in Azure:

`2020-07-22T02:17:06.3141288Z InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/***' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.`

This error happens in the templates that use nested deployments, where the dependency is evaluated in the context of the outer template by default.  [More info here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#expression-evaluation-scope-in-nested-templates) .

To change this behavior a property `"expressionEvaluationOptions": { "scope": "inner" }`, must be added.

A temporary workaround was put in place in:

- [PR 4163](https://github.com/microsoft/botbuilder-dotnet/pull/4163)
- [PR 4160](https://github.com/microsoft/botbuilder-dotnet/pull/4160)

**Action needed:**

- Revert the PRs above.
- Add the necessary property to the templates that use inner templates.
- Add new parameters to the inner template as setting the scope to "inner" prevents the inner template from seeing the outer parameters and variables.

A sample of this can be found here: [BoFramework-FunctionalTests/pull/121](https://github.com/microsoft/BotFramework-FunctionalTests/pull/121)

**Comment by BruceHaley** [comment]
Completed.
