### ISSUE TITLE
Message reaction change Activity (C#)

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#4388]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5972)

**Comment by mrivera-ms** [comment]
@clearab, is this still needed?

**Comment by clearab** [comment]
Yes, Teams implemented that payload change and we should update the Activity dispatch accordingly.

**Comment by EricDahlvang** [comment]
note: this is a breaking change to the sdk behavior, and should maybe be released with a major version update?

**Comment by clearab** [comment]
I'm not sure if it counts as a breaking change, the way the SDK would handle and activity with an add and a remove would be wrong right now - I think it would only dispatch to the reactionAdded handler. The change should just add support for dispatching correctly in the case both were sent.

However, when I wrote this one up v5 wasn't in the works yet - I'm happy to make this part of that set of changes.

**Comment by EricDahlvang** [comment]
Currently, if both are sent then both handlers will execute. First Added, then Removed:
```cs
        protected virtual async Task OnMessageReactionActivityAsync(ITurnContext<IMessageReactionActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.ReactionsAdded != null)
            {
                await OnReactionsAddedAsync(turnContext.Activity.ReactionsAdded, turnContext, cancellationToken).ConfigureAwait(false);
            }

            if (turnContext.Activity.ReactionsRemoved != null)
            {
                await OnReactionsRemovedAsync(turnContext.Activity.ReactionsRemoved, turnContext, cancellationToken).ConfigureAwait(false);
            }
        }
```

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L273

With this change, only the new handler will execute (breaking any existing bots with code in the previous two handlers).

```cs
        protected virtual async Task OnMessageReactionActivityAsync(ITurnContext<IMessageReactionActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.ReactionsRemoved != null && turnContext.Activity.ReactionsAdded != null)
            {
                await OnReactionsChangedAsync(turnContext.Activity.ReactionsAdded, turnContext.Activity.ReactionsRemoved, turnContext, cancellationToken).ConfigureAwait(false);
            }
            else
            {
                if (turnContext.Activity.ReactionsAdded != null)
                {
                    await OnReactionsAddedAsync(turnContext.Activity.ReactionsAdded, turnContext, cancellationToken).ConfigureAwait(false);
                }

                if (turnContext.Activity.ReactionsRemoved != null)
                {
                    await OnReactionsRemovedAsync(turnContext.Activity.ReactionsRemoved, turnContext, cancellationToken).ConfigureAwait(false);
                }
            }
        }
```
https://github.com/microsoft/botbuilder-dotnet/pull/6089

v5 👍

**Comment by gabog** [comment]
Merged into the v5 brach
