### ISSUE TITLE
The class scoped properties and "this.turnCount" are always "null" in input prompts of adaptive dialogs

### ISSUE THREAD

**Issue by berhen** [microsoft/botbuilder-dotnet#4409]
## Version
4.9.3

## Describe the bug
Following this example of a NumberInput (but also with other kinds of prompts):
https://docs.microsoft.com/en-us/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-inputs?view=azure-bot-service-4.0#numberinput

The property "this.value" does contain a value, but the properties "this.turnCount" and "class.defaultValue" are always "null", no matter what we do. As well as the property "class.propertyName".

Same with the examples for the "this" and "class" scopes here:
https://docs.microsoft.com/en-us/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-memory-states?view=azure-bot-service-4.0

## To Reproduce
Use this code to reproduce:

```csharp
var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
{
    Generator = new TemplateEngineLanguageGenerator(),
    Triggers = new List<OnCondition> ()
    {
        new OnUnknownIntent()
        {
            Actions = new List<Dialog>()
            {
                new NumberInput() {
                    Property = "user.favoriteNumber",
                    Prompt = new ActivityTemplate("Give me your favorite number (1-10)"),
                    // You can refer to incoming user message via turn.activity.text
                    UnrecognizedPrompt = new ActivityTemplate("Sorry, '{turn.activity.text}' did not include a valid number"),
                    // You can provide a list of validation expressions. Use turn.value to refer to any value extracted by the recognizer.
                    Validations = new List<String> () {
                        "int(this.value) >= 1",
                        "int(this.value) <= 10"
                    },
                    InvalidPrompt = new ActivityTemplate("Sorry, {this.value} does not work. Can you give me a different number that is between 1-10?"),
                    MaxTurnCount = 2,
                    DefaultValue = "9",
                    DefaultValueResponse = new ActivityTemplate("Sorry, we have tried for '${%MaxTurnCount}' number of times and I'm still not getting it. For now, I'm setting '${%property}' to '${%DefaultValue}'"),
                    AllowInterruptions = "false",
                    AlwaysPrompt = true,
                    OutputFormat = "float(this.value)"
                },
                new SendActivity("Your favorite number is {user.favoriteNumber}")
            }
        }
    }
};
```

## Expected behavior
The properties "this.turnCount" and "class.defaultValue" (as well as "class.propertyName") should contain a value, not be always "null".

**Comment by Zerryth** [comment]
@berhen, it looks like snippet that you got from the docs is incorrect (or maybe out-of-date) with regards to accessing variables--but you seemed to have gotten over that point, at least, with regard to getting the value for `this.value` by adding `$` in front to make `${this.value}`

However for the class properties, I've repro'd your issue as well.

```csharp
                new NumberInput()
                {
                    Prompt = new ActivityTemplate("Give me your favorite number (1-10)"),
                    Property = "user.favoriteNumber",
                    Validations = new List<BoolExpression>() {
                        "int(this.value) >= 1",
                        "int(this.value) <= 10"
                    },
                    InvalidPrompt = new ActivityTemplate("Sorry, '${this.value}' does not work. Can you give me a different number that is between 1-10?"),
                    UnrecognizedPrompt = new ActivityTemplate("Sorry, '${turn.activity.text}' did not include a valid number"),
                    MaxTurnCount = 2,
                    DefaultValue = "9",
                    DefaultValueResponse = new ActivityTemplate("Sorry, we have tried for '${%MaxTurnCount}' number of times and I'm still not getting it. For now, I'm setting '${%property}' to '${%DefaultValue}'"),
                    AllowInterruptions = "false",
                    AlwaysPrompt = true,
                    OutputFormat = "float(this.value)"
                }
```

![image](https://user-images.githubusercontent.com/35248895/89682327-67c21000-d8ab-11ea-97eb-5510e7479b73.png)

Going to check with teammates to see if the expression language updated at all and needs to be accessed differently or if it's something else, and get back to you.

**Comment by Zerryth** [comment]
Tried a few other things offline and also spoke with Vishwac offline from our team. Confirmed to be a bug, though we need to do a little more digging into why this is happening.

Unfortunately there is no workaround at the moment for using class scope--we just need to resolve the bug 😞 

Thanks for reporting @berhen , we'll get to the bottom of the state issue

**Comment by Zerryth** [comment]
@vishwacsena removing myself, to show up in query to assign appropriate engineer to fix

**Comment by vishwacsena** [comment]
@tomlm Looks like we are losing/ yanking out `this` and `class` memory scopes so `DefaultValueResponse` does not render.. `this` and `class` memory scopes do work for `InvalidPrompt`.

```
new TextInput()
                {
                    Prompt = new ActivityTemplate("${ModeOfTransportPrompt()}"),
                    // Set the output of the text input to this property in memory.
                    Property = "user.userProfile.Transport",
                    MaxTurnCount = 3,
                    Validations = new List<BoolExpression>()
                    {
                        "count(this.value) > 5"
                    },
                    InvalidPrompt = new ActivityTemplate("Sorry, ${this.value} does not work. Attempt: ${this.turnCount}. Setting ${class.property} to ${class.defaultValue}"),
                    DefaultValue = "human",
                    DefaultValueResponse = new ActivityTemplate("Sorry, I'm not getting it and we have tried ${this.turnCount} number of times. Setting ${class.property} to ${class.defaultValue}")
                },
```

**Comment by vishwacsena** [comment]
@boydc2014 can you take a look and help address in R11?

**Comment by cosmicshuai** [comment]
Hi @berhen 
I created a PR to fix this issue. And there is a demo to show how to access the class scope in dc.State. 
Hope this could solve your concerns.

**Comment by berhen** [comment]
Hi @cosmicshuai Thanks for your work on this issue. I'm going to check it after the release of the next SDK version.
