### ISSUE TITLE
Correct Cosmos Test

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-dotnet#4412]
There was a small test fix in [this closed PR](https://github.com/microsoft/botbuilder-dotnet/pull/4359) that still needs to be committed to the code. Cosmos changed one of their Exception responses and that needs to be accounted for when running live.

**Comment by EricDahlvang** [comment]
@mdrichardson if this gets merged: https://github.com/microsoft/botbuilder-dotnet/pull/4369  Does it address the test?

**Comment by mdrichardson** [comment]
@EricDahlvang I don't believe so. There might've been a couple of issues my closed PR addressed, though (need to dig through it as part of this issue), and that one might address them. TBD.
