### ISSUE TITLE
ITranscriptLogger to have access to ITurnContext

### ISSUE THREAD

**Issue by bojingo** [microsoft/botbuilder-dotnet#4422]
**Is your feature request related to a problem? Please describe.**
In my Bot Framework projects (2 for 2), we find ourselves needing to log contextual information as part of the transcript log. In one case we needed to log related information from Bot State accessed via `IPropertyAccessor` objects. In another case we need to log details found in the `TurnState` dictionary. In both cases, we had to abandon the `ITranscriptLogger` in favor of custom middleware. The problem is that it is non-trivial to implement a proper custom transcript logging middleware and for it being such a common scenario (I have to believe I'm not alone here!!), there should be an easier means to do this. ITranscriptLogger would be brilliant if only we had access to `ITurnContext`.

**Describe the solution you'd like**
ITranscriptLogger interface should have a method for logging that accepts the `ITurnContext` instead of just the `IActivity`. 

Alternative, because I recognize this would represent a breaking change, a means by which we can inject in some sort of dependency to our custom `ITranscriptLogger` that could retrieve the `ITurnContext` that corresponded to the `IActivity` that is being logged would also suffice. That way, if an implementer needs contextual information, they may retrieve it with the existing interface. If there is already a means to accomplish this, please document it clearly and point me toward it.

**Describe alternatives you've considered**
As mentioned, my projects end up having to implement more complex custom transcript logging middleware instead.

[enhancement]

**Comment by carlosscastro** [comment]
Thanks for filing this, sounds like a useful pattern and we understand your scenario. We've included it in the backlog that we'll use in our next planning phase. Please stay tuned on tags and milestones.
