### ISSUE TITLE
component schemas for some triggers are not correct.

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4423]
See the following:

OnEndOfConversationActivity: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnEndOfConversationActivity.schema

OnCondition: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/TriggerConditions/Microsoft.OnCondition.schema

Not all actions are functional inside OnEndOfConversationActivity, like the Input dialogs. The schema does not reflect this. Doing so results in a bot that will not accept new connections.

Ask: Scrub component schemas for a need to constrain actions to better reflect correctness and give Composer better static analysis

Repro: [OnEndOfConversationActivity.zip](https://github.com/microsoft/botbuilder-dotnet/files/5053346/OnEndOfConversationActivity.zip)

**Comment by vishwacsena** [comment]
I believe this is same ask as this DCR #3007 

@cwhitten can you comment (or close this ticket) if you believe the parent #3007 captures what you are looking for?
