### ISSUE TITLE
ArgumentNullException for none Null Argument

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#4430]
https://github.com/microsoft/botbuilder-dotnet/blob/05001a135a401212eb20c343c1699a6eb290de69/libraries/Microsoft.Bot.Builder.AI.LUIS/Generator/DateTimeSpec.cs#L29-L32

Calling 
            var obj = new DateTimeSpec(type:"",expressions: new List<string>());
Produces:
            System.ArgumentNullException : Value cannot be null. (Parameter 'type')

Expected:
             System.ArgumentException : Value must be set. (Parameter 'type')

type value is set it isnt null it shouldn't throw an ArgumentNullException

**Comment by carlosscastro** [comment]
Hello, I understand your point but this is unfortunately part of the convention that the SDK started with. At this point, if we were to change this it would result in behavior changes, thus breaking changes. thanks for reporting!
