### ISSUE TITLE
Resolve Microsoft.Bot.Builder.Dialogs.Declarative.Tests.TestDialogResourcesAreValidForSchema test failures

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#4460]
Test failing in Microsoft.Bot.Builder.Dialogs.Declarative.Tests. 
Name: TestDialogResourcesAreValidForSchema

Error message: `Assert.Fail failed. D:\a\1\s\tests\Microsoft.Bot.Builder.TestBot.Json\Samples\80 - AdaptiveSkillDialog\AdaptiveSkillDialog.main.dialog JSON is valid against no schemas from 'oneOf'. Path ''.`

The last build against master, commit c6ff4a4, run #157298, failed, and passed running against the same commit last Wednesday, #156538. That indicates no source code change of ours is responsible for the break.

Ignoring temporarily until the root cause is found. 

The test was temporarily disabled in PR#4459.

**Comment by chrimc62** [comment]
This has been resolved.
