### ISSUE TITLE
DialogStateManager.TryGetValue throws ArgumentException

### ISSUE THREAD

**Issue by jsiegmund** [microsoft/botbuilder-dotnet#4464]
## Version
4.9.4

## Describe the bug
I'm using `DialogStateManager.TryGetValue` to get a typed value from the dialog state. When attempting to cast to a wrong type, this ends in an exception being thrown.

## To Reproduce
1. Store some value in state
2. Use `dc.State.TryGetValue` to retrieve the value from cache, but supply the wrong type

## Expected behavior
I would expect the `TryGetValue` method to return false as the stored value could not be retrieved properly. The out parameter would remain null. A method with the Try prefix should never fail in an exception imho; when the Try didn't result in success it should return `false`.

**Comment by sgellock** [comment]
@tomlm sending over to you for review

**Comment by lauren-mills** [comment]
We have added this to the backlog and will look at it in an upcoming release. Thanks.

**Comment by jsiegmund** [comment]
@lauren-mills that's great, thanks!
