### ISSUE TITLE
Fix duplicate code in OAuthPrompt and OAuthInput

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#4467]
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs

and 

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs

Have many identical blocks of code.  In R10, an update was made to `OAuthPrompt` but not `OAuthInput`.  These two are now out of sync (OAuthInput's timeout will not function properly,and OAuthInput does not have EndOnInvalidMessage)

**Comment by EricDahlvang** [comment]
Investigate why the OAuthPrompt is sending the CancellationToken as the InvokeResponse:

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L518

and

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L525

**Comment by mrivera-ms** [comment]
This will fall within the refactor effort for Adaptive. We should take into consideration the adapter refactoring.

**Comment by johnataylor** [comment]
This is the first step towards fixing #4729 for the oauth prompt
