### ISSUE TITLE
404 on Composer (1.1.0) Release Notes

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/botbuilder-dotnet#4471]
Hi Team

Is it being rolled out or an actual link is different? I am not able to locate Composer Release notes as mentioned in the BF SDK 4.10 release notes. 

Cheers
Arafat

**Comment by EricDahlvang** [comment]
Hi @arafattehsin 

Thanks for opening this issue.

Yes, the release notes are in the process of being rolled out.  That link should be live within days.
