### ISSUE TITLE
Provide documentation on using Microsoft.Bot.Builder.Dialogs.Adaptive.Testing

### ISSUE THREAD

**Issue by jsiegmund** [microsoft/botbuilder-dotnet#4472]
**Is your feature request related to a problem? Please describe.**
I have seen the Microsoft.Bot.Builder.Dialogs.Adaptive.Testing preview package and perhaps due to the preview state there seems to be little documentation on this. 

I'm in the progress of building a bot using the adaptive dialog. I'm struggling with how to properly (unit)test this code. For instance, I'm using `PropertyAssigment`s to assign LUIS returned entity values to my dialog properties. Works fine for simpler assignments, but I can't seem to get it to work for an array of timex values. Apart from the fact that this in itself could be better documented, I'd also like to be able to write some tests to verify that the code is working as intended and will keep doing so in the future. 

**Describe the solution you'd like**
Whilst searching I found this package which is probably going to help, but documentation on how to use it seems to be nonexistent (or perhaps I'm looking in the wrong place!). So therefore this ticket to see if this could be sorted out. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by xieofxie** [comment]
If you are writing bot code in dialog files, you could follow the tests to build your tests https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/TestScriptTests.cs

**Comment by jsiegmund** [comment]
I took a look but I'm not sure how I would have to proceed. This all seems to be highly convention based (down to the actual test methods all being the exact same!?) which is nice if you know the convention or have documentation on it, but is very confusing and challenging to adapt when you have no clue. And I'm afraid I fall into the second category.

Also I see an `AssertReply` test, but no `AssertPropertyValue` or something similar which I could use to check whether the LUIS outcome is leading to the correct properties being set in cache. 

So yeah, _maybe_ I could get there with these samples, but without help or documentation this would take quite a while I'm afraid.

**Comment by jsiegmund** [comment]
Maybe also a more general question on the topic of testing: a scripted approach as found in these tests is a nice thing to have to test the interactions with a bot in general. But when things get more complex than just simple Hello World style solutions, the complexity of these tests would quickly increase. So I would be interested in some guidance / guidelines on how to structure a bot, dialogs and all related artifacts in more complex scenario's whilst keeping the overall thing testable. 

And lastly; when testing a bot which relies on LUIS, are there any helpful things which we can use to mock the dependency on LUIS but still have relevant test scenario's; other than recording a random response and using that as test input? Based on the definition file it might be possible to create some sort of test scenario randomizer which ensures that not always the exact same patterns are being validated by the tests? I personally like dynamic tests which can vary (within boundaries of course) their input parameters in each test run to ensure you eventually hit combinations that might not have been present in fixed test settings. From unit testing perspective you'd want to make the units as small as possible but I'd wonder how that would work for more complex / larger dialogs.

**Comment by peterinnesmsft** [comment]
@jsiegmund, thanks for the clarification! @Kaiqb can you help support from the documentation side of things? Who can we engage from the engineering team to help expand the available samples?

**Comment by lauren-mills** [comment]
We're adding this to the backlog for a future release.

**Comment by jsiegmund** [comment]
Hi @lauren-mills , so what exactly is the process involved here? From a 'customer' point of view my issue is now closed and I have nothing to go on. I still don't know how it works and I have no clue on when an item on the backlog would ever be implemented. So all I can do is wait and see? I would suggest to make this process a little bit more customer friendly when possible, so people at least get a rough idea of what they can or cannot expect.

**Comment by peterinnesmsft** [comment]
Hi @jsiegmund,

Apologies, it looks like this got closed in error. In terms of handling this work item, the appropriate owners of this area will need to internally triage and assess prioritization of this against other asks to determine when this can be done. I would expect that they update this issue accordingly.

For enhancements and feature requests from external customers, we do our best to ensure we turn them around within 90 days or less. We ask for your patience while we work to schedule this.

If there’s anything else in the meantime, do let us know.

**Comment by jsiegmund** [comment]
Thanks for the update @peterinnesmsft, much appreciated!

**Comment by tsuwandy** [comment]
@Kaiqb, could you take a look and update doc, if samples are needed, could you assign to @gabog?

**Comment by ninggao** [comment]
@Kaiqb, any update on this?

**Comment by ryanlengel** [comment]
The [`Microsoft.Bot.Builder.Dialogs.Adaptive.Testing`](https://github.com/microsoft/botbuilder-dotnet/tree/main/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests) package is still in preview, any documentation supporting this would not be provided until this is publically available. In the meantime, I would suggest keeping an eye on the project as it is in active development (since the original reference it was migrated to XUnit and continues to have new commits). Thank you!
