### ISSUE TITLE
Avoid sending typing activity when bot is invoked as skill

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#4478]
## Version
4.9.4

## Describe the bug
The ShowTypingMiddleware doesn't consider if it is running in the context of a root bot or a skill. This will cause unnecessary typing events if both the root bot and the skill are sending typing events. To avoid this the ShowTypingMiddleware should check the context using the `SkillValidation.IsSkillClaim` and only send typing events when running as a root bot.

I'll be submitting a PR with a fix for this issue.

## To Reproduce
1. Create a bot and a skill
2. Configure ShowTypingMiddleware for both the bot and the skill
3. Invoke the skill through the bot
4. Bot the bot and the skill send typing events

## Expected behavior
Only the root bot should send typing events. Skills should not unless they are invoked as a root bot.

## Additional context
Created parent issue to track this gets ported to the other languages [here](https://github.com/microsoft/botframework-sdk/issues/6049)

**Comment by peterinnesmsft** [comment]
@sschutten thank you for submitting a PR for this issue! One of our team members will look at it shortly.

**Comment by tsuwandy** [comment]
@peterinnesmsft, any update on this?
