### ISSUE TITLE
PVA DCR: DotNet classes need proper output Serialization  support

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#4489]
## Version

4.10

## Describe the issue

PvA uses dotnet for it's composer like scenarios, so it needs to write .dialog files as well as read them.  Our dotnet libraries don't have unit tests for this and don't round-trip data via the serialization paths.

## Expected behavior

When you load .dialog files into dotnet classes, you can edit them in memory and save them back out, maintaining all metadata.

*   $designer fields need to round-trip
*   string based resource references need to round-trip

**Comment by vishwacsena** [comment]
Need dev design + possible solutions.

**Comment by boydc2014** [comment]
After triaged with @tomlm, we think this is not needed anymore, we will keep it backlog.
