### ISSUE TITLE
Where is dialog.lastActivity? It's used in schema examples but doesn't appear to be real.

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4499]
See the component schema for Microsoft.DeleteActivity:

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.DeleteActivity.schema#L21

The scenarios for DeleteActivity and UpdateActivity require keeping track of certain activity id's, and dialog.lastActivity is a great example, however it doesn't appear to work.

**Comment by Danieladu** [comment]
It's `turn.lastresult.id` actually.

The `turn.lastresult` would record the previous one result. If the last action is SendActivity, the lastresult is the Activity.
So, the id of last acticity is `turn.lastresult.id`

**Comment by boydc2014** [comment]
@Danieladu  can you take the chance to update the schema to "turn.lastresult.id" and also please check if there is any test on it.

**Comment by Danieladu** [comment]
Here is the test:
https://github.com/microsoft/botbuilder-dotnet/blob/d5726a7d10ea9dc1b446ec23165353d6ed955f01/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_DeleteActivity.test.dialog#L17
So, the `dialog.lastActivity` is assigned manually.
