### ISSUE TITLE
Array handling within LG is completely broken for sub expressions...

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4501]
## Version

4.9.4 and 4.10.0

## Describe the bug

Using an array (or a prebuilt function that manipulates arrays) with an expression seems to work fine. But the moment you pass that around to/through a sub expression things get wonky. I've put together a simple set of test expressions:

```
# testExpression()
- ${string(split("demo:carousel:noNavIcon", ':'))}

# testExpression2()
- ${string(sub1(split("demo:carousel:noNavIcon", ':')))}

# testExpression3()
- ${string(sub1(createArray("demo", "carousel", ":noNavIcon")))}

# testExpression4()
- ${string(sub2(createArray("demo", "carousel", ":noNavIcon")))}

# testExpression5()
- ${string(count(sub1(createArray("demo", "carousel", ":noNavIcon"))))}

# testExpression6()
- ${string(sub3())}

# testExpression7()
- ${string(sub4())}

# sub1(a)
- ${a} 

# sub2(a)
- ${count(a)} 

# sub3()
- ${createArray("demo", "carousel", ":noNavIcon")} 

# sub4()
- ${string(createArray("demo", "carousel", ":noNavIcon"))} 
```

The output of these 7 test expressions is here:

![](https://user-images.githubusercontent.com/698939/90987063-e326f100-e53c-11ea-9097-835042c43a87.png)

The only ones that produce the expected output are tests 1 & 4.  Test 4 & 5 are particularly interesting in that it points to the issue being with the array that's returned by a sub expression. The last test is also interesting in that it shows that calling `string()` on something that's already a string causes the string to be escaped. We should have a separate function for escaping strings and calling `string()` on a string should just leave it as a string.

**Comment by boydc2014** [comment]
Closed, due to the root cause is the trailing space in the template body, the object manipulation design is expected.
