### ISSUE TITLE
Remove System.Dynamic dependency from Core.Extensions

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#451]
The (now deleted) FlexObject class had dependency on System.Dynamic. 

With the removal of FlexObject, we can now remove the Dynamic dependency.

**Comment by drub0y** [comment]
Looks like #463 took care of this and is merged in so closing out this issue.

In future, suggest including "Fixed #<issue-number>" in the commit and/or PR description to automatically link and close out issues.
