### ISSUE TITLE
Allow override for Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog

### ISSUE THREAD

**Issue by nick-romano0** [microsoft/botbuilder-dotnet#4510]
Class I'm referring to:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs

**Is your feature request related to a problem? Please describe.**
The QnAMaker Dialog is a great boilerplate template to get up and running with the QnA service and Bot Service, but it is frustrating that I cannot modify the response back to the user. Particularly the method `DisplayQnAResultAsync`. With this change, I could return adaptive cards back to the user instead of plain text.

**Describe the solution you'd like**
change:
`private async Task<DialogTurnResult> DisplayQnAResultAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)`

to:
`protected async virtual Task<DialogTurnResult> DisplayQnAResultAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)`

**Describe alternatives you've considered**
Re-implement the class from the source code. It is pretty counter-productive to have to copy 600+ lines of code to just modify a response

**Comment by vishwacsena** [comment]
@pchoudhari can you comment?

**Comment by pchoudhari** [comment]
Thanks for the suggestion, we will triage this. Assigning to @vipeketi and @DishaAgarwal

**Comment by tsuwandy** [comment]
@sahithikkss, could you address the PR comment so it could be merged?  Thanks! https://github.com/microsoft/botbuilder-dotnet/pull/4574
