### ISSUE TITLE
Add uischema for UpdateActivity & DeleteActivity

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4514]
```json
  "Microsoft.UpdateActivity": {
    "form": {
      "label": "Update an activity"
    }
  },
```
```json
  "Microsoft.DeleteActivity": {
    "form": {
      "label": "Delete activity"
    }
  },
 
```

**Comment by mrivera-ms** [comment]
@cwhitten is this issue in scope for R11?

**Comment by mrivera-ms** [comment]
Per conversation with @cwhitten , this is in scope for R11.

**Comment by mrivera-ms** [comment]
@cwhitten, is the motivation to overwrite the title fields (`"title": "Delete Activity"` and `"title": "Send an activity"`) in **Microsoft.DeleteActivity.schema** and **Microsoft.UpdateActivity.schema** or do you need to have uischemas for other changes? Would changing the title to match `"Update an activity"` and `"Delete activity"` be enough?

**Comment by cwhitten** [comment]
@mrivera-ms I'll take this one for R12. I want to add some additional items

**Comment by mrivera-ms** [comment]
@cwhitten, is this issue to be completed by R12 (2/12)?

**Comment by cwhitten** [comment]
This will be closed as part of Ze's work
