### ISSUE TITLE
Add OnDialogEnded trigger

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4519]
Salem from PVA wants this.

**Comment by vishwacsena** [comment]
@cwhitten we have [`OnEndOfActions`][1] trigger. Would it suffice for the scenarios you need this for? 

[1]:https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/OnEndOfActions.cs

**Comment by mrivera-ms** [comment]
@garypretty , can you give us an indicator of the priority of this item? Thanks.

**Comment by EricDahlvang** [comment]
Does OnEndOfActions work for this?  (as vishwacsena mentioned)

**Comment by garypretty** [comment]
@mrivera-ms let's confirm if @vishwacsena's suggestion works.  Either way, let's ensure this get's addressed as part of R11 given this is a requirement for PVA.

**Comment by mrivera-ms** [comment]
@cwhitten , could you please let us know if OnEndOfActions would work for the customer?

**Comment by cwhitten** [comment]
@sbacha What do you think?

**Comment by sbacha** [comment]
Just to understand the scope of OnEndOfActions ?  Is it global on the bot or per dialog ?
I don't see it exposed in composer yet ...

**Comment by mrivera-ms** [comment]
@cwhitten , can we expose OnEndOfActions in Composer first and see if this satisfies the requirements?

**Comment by cwhitten** [comment]
@mrivera-ms The SDK team should still be able to answer Salem’s question, right?

**Comment by boydc2014** [comment]
> Just to understand the scope of OnEndOfActions ? Is it global on the bot or per dialog ?
> I don't see it exposed in composer yet ...

Hi, @sbacha, this OnEndOfActions is trigger and it's scope is per dialog. Actually in AdaptiveDialog, all triggers must belong to a certain dialog and thus all trigger can be perceived as a per dialog level thing.

**Comment by cosmicshuai** [comment]
@sbacha 
Here is an example of using OnEndOfActions to do something at the end of per dialog. [OnEndOfActions In Dialog](https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/GeneratorTests/sandwich/sandwich.dialog)

If you have any question or concern, feel free to leave comments.

**Comment by mrivera-ms** [comment]
@sbacha and @cwhitten , is this issue still needed or the proposed solution works? Please let me know so we can close this issue.

**Comment by mrivera-ms** [comment]
Per conversation offline with @sbacha, the solution proposed seems like it meets his requirements. Closing this issue.
