### ISSUE TITLE
HTTP action possibly sending incorrect headers?

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#4524]
## Version
4.9

## Describe the bug
Give a clear and concise description of what the bug is.

I built a very simple test API using Glitch. I created this URL:

https://broken-spicy-conchoraptor.glitch.me/foo

This return JSON {bar: true}

I can retrieve this using curl.

However, when I attempt to fetch this in Composer using an HTTP action, I get a 403 error from Glitch and see no traffic hitting my server.  I believe this may be related to the http request sending incorrect or incomplete headers to the service, causing it to misidentify the destination of the request.

## To Reproduce
1. Load https://broken-spicy-conchoraptor.glitch.me/foo in your browser - make sure the service has spun up. (Glitch will sleep after inactivity)
2. In composer, set up an HTTP action with the URL `https://broken-spicy-conchoraptor.glitch.me/foo`
3. Send an activity with the resulting value, it will be a 403 error.

## Expected behavior

Composer should receive the expected JSON document.

## Screenshots
![Screen Shot 2020-08-26 at 12 52 17 PM](https://user-images.githubusercontent.com/729873/91338739-ffc06480-e79a-11ea-840e-6190f4ab8c63.png)
![Screen Shot 2020-08-26 at 12 52 37 PM](https://user-images.githubusercontent.com/729873/91338779-0bac2680-e79b-11ea-83be-6dc2b1b09be2.png)

**Comment by vishwacsena** [comment]
@boydc2014 can you help investigate/ address for R11?

**Comment by cosmicshuai** [comment]
@benbrown 
I tested this API through postman and found the header of this request need user-agent.
So I added a key-value pair in Headers:
![image](https://user-images.githubusercontent.com/17074777/93307184-4a318000-f833-11ea-9f07-87833bd606fd.png)
This will get right response code: 
![image](https://user-images.githubusercontent.com/17074777/93307274-62090400-f833-11ea-9de9-49eb6115adac.png)

**Comment by benbrown** [comment]
So our HTTP request doesn't send a user-agent header by default? It definitely should!!

**Comment by cosmicshuai** [comment]
@benbrown Yes. We should have a default user-agent in the header of HttpRequest.

**Comment by boydc2014** [comment]
> @benbrown Yes. We should have a default user-agent in the header of HttpRequest.

approved, and we should only set user-agent header if no explicit value is specified.
