### ISSUE TITLE
Feature request: introduce a special $kind for inline notes/annotations/documentation

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#4526]
**Is your feature request related to a problem? Please describe.**

As a Composer user, I would like to be able to add inline "notes" or "annotations" ala code comments.  I would like to be able to add notes at any step of the dialog and have them visible whenever I view the dialog in Composer.  Here is a mockup of how we would like to use them:

![Screen Shot 2020-08-26 at 2 55 02 PM](https://user-images.githubusercontent.com/729873/91350477-613cff00-e7ac-11ea-8bcd-db9b5083e040.png)

**Describe the solution you'd like**

I believe this should be implemented in the SDK so that the adaptive loader can be instructed to ignore these nodes instead of instantiating noop actions. 

**Describe alternatives you've considered**

It is possible for us to achieve this by bundling a custom action/schema extension with the Composer runtime, however this would require us to create a noop class to handle this which seems inelegant.

**Comment by benbrown** [comment]
See related Composer issue: https://github.com/microsoft/BotFramework-Composer/issues/3419

**Comment by mrivera-ms** [comment]
Need to find out what is the priority of this item and when should it be delivered.

**Comment by mrivera-ms** [comment]
Assigned to @boydc2014 for discussion to evaluate if this will be done.

**Comment by boydc2014** [comment]
After triaging with Tom, we should push off the decision into a dedicated review of new actions combining with a few other new actions proposal.

**Comment by mrivera-ms** [comment]
@darrenj please see the comment above and prioritize this. Thank you.
