### ISSUE TITLE
[uischema] add menu config for each component

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/botbuilder-dotnet#4527]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Composer now supports the `menu` property in the uischema. We will port Composer's configuration into the component uischemas for R11.

Current config found here: https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/ui-plugins/composer/src/defaultMenuSchema.ts#L1

**Comment by mrivera-ms** [comment]
Per conversation with @a-b-r-o-w-n this is out of scope for R11.

**Comment by mrivera-ms** [comment]
@a-b-r-o-w-n is this going to be done in R12?

**Comment by a-b-r-o-w-n** [comment]
@mrivera-ms  yes.
