### ISSUE TITLE
DCR: Separate out entity mapping logic into a replaceable component

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4539]
Adaptive dialog currently has logic that uses schema information plus expected properties and history to map entities into operations, properties and entities that are:
1) ChooseEntity if entity value is ambiguous.
2) ChooseProperty if entity can be assigned to multiple properties.
3) AssignEntity if entity can be applied to a property with a particular operation.
This is currently built into AdaptiveDialog, but this DCR would be to separate it out into its own EntityMapper component that would be replaceable in order to allow more intelligence in doing this mapping.

**Comment by mrivera-ms** [comment]
This will be split between R11 for design review and R12 for execution.

**Comment by mrivera-ms** [comment]
@boydc2014, is this on track for R12?

**Comment by boydc2014** [comment]
> @boydc2014, is this on track for R12?

No, I'm moving this out of R12 for now, I haven't quite get into the detail of this one.
