### ISSUE TITLE
FacebookClientWrapper should not silently fail on SendMessageAsync

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#4544]
#Describe the bug
If the result of the response is NOT IsSuccessStatusCode, the sdk should presumably throw an exception and not just return an empty string.  The current code makes debugging difficult, and seems to ignore errors.

```cs
                using (var client = new HttpClient())
                {
                    var res = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);

                    if (res.IsSuccessStatusCode)
                    {
                        var responseBody = await res.Content.ReadAsStringAsync().ConfigureAwait(false);
                        var stringResponse = JsonConvert.DeserializeObject<FacebookResponseOk>(responseBody);
                        return stringResponse.MessageId;
                    }

                    return string.Empty;
                }
```

## Expected behavior
An exception indicating the send operation failed.

**Comment by mrivera-ms** [comment]
@garypretty , please take a look at this and let us know if and how we should take this.

**Comment by garypretty** [comment]
@mrivera-ms yes, I think we should take this.  We should throw the error instead of returning an empty string (providing we check that no other code is relying on that return of an empty).

**Comment by mdrichardson** [comment]
@BruceHaley @EricDahlvang Did this get fixed in [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/4614)?

**Comment by EricDahlvang** [comment]
@mdrichardson it looks like it has been addressed.
