### ISSUE TITLE
Documentation should include information about the "settings." and "this." scopes

### ISSUE THREAD

**Issue by LouisEugeneMSFT** [microsoft/botbuilder-dotnet#4546]
**Is your feature request related to a problem? Please describe.**
It is hard for new users to know how BOT memory works. 

**Describe the solution you'd like**
Clear documentation on the different scopes, where they are valid and how they should be used.

**Describe alternatives you've considered**
https://docs.microsoft.com/en-us/composer/concept-memory

**Additional context**
The link above provides information about [user, conversation, dialog, turn] but not about [settings, this]

**Comment by JonathanFingold** [comment]
Documentation exists for the **Settings** and **This** scopes, among others, in the SDK docs at Reference/AdaptiveDialogs/[Memory scopes](https://docs.microsoft.com/azure/bot-service/adaptive-dialog/adaptive-dialog-prebuilt-memory-states).

**Comment by JonathanFingold** [comment]
Please reopen with comments if I have closed this prematurely.
