### ISSUE TITLE
Timeout setting on prompts

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#4555]
It would be great to have some sort of timeout setting on prompts that triggers when a user hasn't responded to the prompt within set time. It would allow for a more natural flow where the bot can remind the user to reply with an answer or cancel the dialog.

**Comment by pavolum** [comment]
We will consider this feature request and gauge whether or not it will be in future releases. Thanks!

**Comment by jintu123** [comment]
Is there a way current to identify inactive timeout in bot composer?
Using any property values or etc?

**Comment by GeoffCoxMSFT** [comment]
The challenge with a timer in a conversation is to provide a guarantee that an event will be raised when the timer is fired.  The timer scheduler has to be durable in the face of machine failure and coordinated across machines.

If you are using Composer, you could create your own timer class to invoke as a component in a custom runtime. It only works on a single machine and is not durable.  We do have some sample code if you go that route and need a starting point.

We are working on providing a durable scheduling service that could support this timer scenario as part of another project, but cannot currently provide any timeline on it.

**Comment by mrivera-ms** [comment]
@garypretty , we think this is a feature request, can you comment on it?

**Comment by garypretty** [comment]
@jintu123 This is not unique to adaptive dialogs - this is the same across the framework.  At present there is no native way within Composer that allows you to see when the user was last seen. You could store the last seen time manually into User State, which would let you know on the next turn when the user was last active.  However, if you wanted to achieve the timeout scenario, you would need to persist this data within some form of persisted storage and continuously query this yourself and send a pro-active message depending on your scenario. I have done this before with a service such as hangfire, but you would need to roll your own solution to match your scenario here.

We will log this and have it feed into future planning where relevant. Thanks.

**Comment by cwhitten** [comment]
@garypretty I believe we should leave this open as a feature-request rather than close it entirely.

**Comment by mrivera-ms** [comment]
@darrenj the SDK team reviewed this and concluded this is not something we would be implementing. Please comment and assign/close as needed.

**Comment by garypretty** [comment]
This is not something that will be address within the short - medium term and is not on any of our current roadmaps.  We have captured this requirement previously, so this will be considered again in future planning, but right now I am going to close this issue.
