### ISSUE TITLE
better document for Microsoft.MentionEntityRecognizer

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4568]
According to the [implementation](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/EntityRecognizers/MentionEntityRecognizer.cs) and [test](https://github.com/microsoft/botbuilder-dotnet/blob/f2a0b6bc9678894706ba9506bac6bcf29cc7974f/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/EntityRecognizerTests.cs#L139), this recognizer recognizes by text so it doesn't recognize [mention entity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Mention.cs).

As these names are same, we should update document to make this clear.

**Comment by mrivera-ms** [comment]
@xieofxie , please update this issue to include more detail about what you would like to see in the documents. Thanks.

**Comment by xieofxie** [comment]
@mrivera-ms I am sorry, document means comment in code here. Since we don't have document for `Microsoft.MentionEntityRecognizer` now (do we?)

**Comment by mrivera-ms** [comment]
@xieofxie are there any updates on this?

**Comment by xieofxie** [comment]
I see.. We add a https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/EntityRecognizers/ChannelMentionEntityRecognizer.cs for mention class. Close now
