### ISSUE TITLE
add a (thread safe) global scope memory

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4572]
**Is your feature request related to a problem? Please describe.**

Although it is only a global memory across one single process, it will help for some big shared information.
An example:
Server have two apis: `getBigDataVersion()`, `getBigData(string version)`
When used in bot, the bot could check `global.version` with `getBigDataVersion()` first, then determine if update `global.data`
In the worst case, it will just `getBigData(string version)` for same version with multiple threads during version update, and most of time we could save the time for get big data.
(we could even make use of `global.updatingThread` and a `compareExchange` function to avoid multiple `getBigData(string version)`)

**Comment by mrivera-ms** [comment]
@vishwacsena , could you please look at this item and let us know who should take it?

**Comment by boydc2014** [comment]
Remove the adaptiveExpression and add adaptive. 

This is an ask to add a scope in DialogStateManager of AdaptiveDialog. and @tomlm  is the right person to triage.

**Comment by mrivera-ms** [comment]
@darrenj please prioritize. Thank you.
