### ISSUE TITLE
Expression References does not include references defined by exported LG templates used as functions

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4576]
Expression.References() is supposed to return all memory references from an expression tree.  This works for all the built-in functions but does not work for exported LG template functions.  This is needed to support RunOnce functionality in triggers and I believe is also used by Composer.  Fixing the issue is a little tricky since the function is in expressions and the LG functions are in the layer above, but it looks like ReferenceWalk was setup to handle extensions but it was never plumbed through.

**Comment by mrivera-ms** [comment]
@boydc2014 are there any updates about this? Please prioritize it and add any details. Thank you.

**Comment by boydc2014** [comment]
> @boydc2014 are there any updates about this? Please prioritize it and add any details. Thank you.

This one is mostly a backlog, it's a very rare case and i think we are soon going to update this part. My judgement is there is nothing actionable at this stage. Let's close this for now. We will reopen or recreate new one, once we revisited LG-integration at R12 and this is still a issue then.

**Comment by lauren-mills** [comment]
@boydc2014 - Has support for this been added, or is it still in the backlog?
