### ISSUE TITLE
Some of the LUIS types are still in the Microsoft.Cognitive.LUIS namespace

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#458]
When the LUIS types were moved to the **Microsoft.Bot.Builder.Ai.LUIS** namespace, nearly all of the ones defined in the `Client` and `Client/Models` subdirectories were skipped and still live in the **Microsoft.Cognitive.LUIS** and **Microsoft.Cognitive.LUIS.Models** namespaces.

**Comment by garypretty** [comment]
Is assumed that as they were already in their own namespace not consistent with the project that this was intentional which is why I left them where they were. Happy to rectify if needed.

**Comment by JonathanFingold** [comment]
Interesting, I'll defer to the architects. @cleemullins ?

**Comment by cleemullins** [comment]
This is not intentional. @emadelwany , can you fix?

**Comment by cleemullins** [comment]
@garypretty - this is not intentional. The old LUIS client was called "Microsoft.Cognitive.LUIS" and we nuked it some time ago. Apparently some of the pieces escaped. Emad, on the LUIS team, should be able to clean this up asap.

**Comment by emadelwany** [comment]
This client code is just temporarily part of the Microsoft.Bot.Builder.Luis project until the identical code ships as part of the Microsoft.Cognitive.LUIS nuget. Once Microsoft.Cognitive.LUIS nuget is released by the Cognitive Services team, the whole /Client directory should be nuked, and the nuget should be a drop-in replacement (requiring 0 code changes). I can move it to the project's namespace and then we can revert all the "using" statements that uses the /client after we grab the nuget if you prefer that.

**Comment by JonathanFingold** [comment]
If changing the namespace for these will introduce a breaking change later, I think it may be better to not make the change. I can add a comment in the doc XML remarks that these will be part of a later version of the Microsoft.Cognitive.LUIS NuGet package.

**Comment by yochay** [comment]
@emadelwany can we get an ETA? 
@Kaiqb heads up we'll need to update LUIS docs in BF

**Comment by yochay** [comment]
@chrimc62  can you take this one

**Comment by chrimc62** [comment]
From Emad's comment sounds like we are waiting for CS to publish a nuget.  I've started a thread to see where that process is.

**Comment by JonathanFingold** [comment]
@cleemullins , @yochay , This looks like it was fixed at some point. The SDK doesn't appear to define any types in the Microsoft.Cognitive.LUIS namespace anymore. Please reopen if there is still an issue that needs to be resolved.
