### ISSUE TITLE
[Expression] inconsistency between doc and implementation for 'int', 'float'

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4615]
## Version
What package version of the SDK are you using.

Current main

## Describe the bug
Give a clear and concise description of what the bug is.

The document says 'Return the floating point representation of the specified string or **the string itself if conversion isn't possible**.'

https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#conversion-functions

However, if one uses `int('bad')`, `float('bad')`, it will throw an exception 'Input string was not in a correct format.'

## To Reproduce
1. See https://github.com/xieofxie/botbuilder-dotnet/commit/5084688a55c11b3749a85dbae9ca426bd33a14be

## Expected behavior
Give a clear and concise description of what you expected to happen.

If exception is the planned behavior, we still need a function to know if a string is whether in int format (from document, we could `int` and then `isInteger`

**Comment by Danieladu** [comment]
Firstly, the exception is as expected.
Let me summarize the requirements:
1. The doc of "int()" is wrong. 
2. Require a new function that can determine if a string can be converted into an integer. Maybe like:
```
tryParseToInt(param): {isInt: bool, result:number}
```
Is that right?
If so, a series of functions need to be added:
```
tryParseToJson
tryParseToFloat
tryParseToBool
tryParseToBase64
tryParseToXml
tryParseToBinary
```

hmmm, this should be considered carefully.

**Comment by xieofxie** [comment]
Yeah.. I like the way in document better

**Comment by emgrol** [comment]
@xieofxie The changes are now live.

**Comment by Danieladu** [comment]
Since the doc has been updated. Mark this issue as the new feature requirement of new prebuilt functions.

**Comment by emgrol** [comment]
The changes are live, should I close the issue @xieofxie?

**Comment by xieofxie** [comment]
@emgrol Sure, hope the new functions could be added soon.

**Comment by Danieladu** [comment]
close this one due to the duplication of #4773
