### ISSUE TITLE
[Adaptive] Add supportedContentType property to the schema for components that implement Recognizer

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#4617]
Today composer does not have any way to identify or associate a specific dialog's recognizer configuration to what build/ publishing workflows need to be run for that recognizer configuration. Composer defaults to running the LUIS and QnAMaker build and publishing workflows but this does not work when users wish to use other recognizers (e.g. PVA/ Orchestrator/ Lucene/ Spacy etc). 

In order to associate and identify the specific content type each recognizer configuration supports, we should add a `supportedContentType` property to the schema for all recognizers. This can be an enum of `Lu`, `QnA`, `LuAndQnA`, `Other`. 

This enables composer to surface UX in composer that allows the user to pick a specific recognizer tech to handle the LU, QnA workflows (build, publishing as well as recognizer configuration)

@cwhitten @boydc2014 please feel free to add more.

@tomlm @chrimc62 FYI.

**Comment by chrimc62** [comment]
Seems like this assumes that within a single bot there is a single consumer of each of the file types.  Wouldn't it make more sense to have a workflow for each $kind?  This is more open-ended and the $kind corresponds to the technology and the workflow can build in whatever reasoning it needs to do against the schema instance.

**Comment by tomlm** [comment]
We should keep it simple and just allow you to define the script for

*   PreBuild
*   Build
*   Run
*   PostBuild

Visual Studio has exactly that functionality:

![](https://user-images.githubusercontent.com/17789481/92663898-6e331580-f2b7-11ea-9a2c-ea2fff669398.png)

**Comment by vishwacsena** [comment]
@chrimc62 This would allow per dialog level flexibility. The issue with using $kind is composer does not know what specific content types you can handle.

@tomlm we could do that but not sure how that helps with associating a specific technology stack for LU and QnA content..?

**Comment by vishwacsena** [comment]
Tracked via #4651
