### ISSUE TITLE
[DCR] [LG] Support null output 

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#4620]
Currently, LG can not support `null` output. Due to the modularity of LG, `null` output is necessary for granted.

This DCR is used to discuss how to safely support the `null` output.

## Current sample
```
# template1
- ${null}

# template2
- ${a}
```

If the user evaluate `template1` or `template2` without variable `a`, the result would be a string "null" but not `null`

This would block those who want to generate `null` as the result in the middle of logic.
Example:
```
# template1
- IF: ${getName() == null}
 - hello
- ELSE:
 -  hello ${getName()}

# getName
- ${name}
```
If someone evaluates `template1` without `name` scope,  the expected result is: `hello`, but get `hello null`. It does not make sense.

Consider these factors:
- Default fallback. Originally, the `null` value would fallback to string "null" by default. If LG support `null` output, the default fallback would be an empty string or string "null"?
- [strict option](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#strict-option)  
  There is no need to use the strict mode because the `null` output is always a valid value. 
- [replaceNull option](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#strict-option)  would keep the original role.

**Comment by boydc2014** [comment]
I think we need to clarify the current behavior first, can you add some descriptions for 
* in what case null would be converted (fallback) to "null"?  please add some examples
* in what case this behavior is not appropriate? please list some examples in which the current behavior is not expected, and list the expected behaviors also

**Comment by mrivera-ms** [comment]
@vishwacsena , please assign a priority and milestone to this item?
