### ISSUE TITLE
Bots in UsGov environments stop working if you use the BotFrameworkHttpAdapter adapter

### ISSUE THREAD

**Issue by NickEricson** [microsoft/botbuilder-dotnet#4628]
## Version
C# 4.9.2 and 4.9.3

## Describe the bug
In the echo bot if you changes this line:
services.AddSingleton<IBotFrameworkHttpAdapter, **AdapterWithErrorHandler**>();
to
services.AddSingleton<IBotFrameworkHttpAdapter, **BotFrameworkHttpAdapter**>();

Bot auth will fail and the bot stops working.

## To Reproduce
1. Create a new echo bot in UsGovPrd
2. Chat with it in web chat... it works
3. Change the line in the _Describe the bug_ section and redeploy
4. Chat with it in web chat... it doesn't work

## Expected behavior
It continues to chat. Should not have to use the correct (protected) ctor to get things working.

**Comment by johnataylor** [comment]
Closing this issue as we now have a new adapter called CloudAdapter that support basic scenarios in any configured cloud environment.

The missing features are Streaming, OAuthPrompt support and Skills support. 

https://github.com/microsoft/botbuilder-dotnet/issues/4850
https://github.com/microsoft/botbuilder-dotnet/issues/4851
https://github.com/microsoft/botbuilder-dotnet/issues/4853
