### ISSUE TITLE
The SDK is over-verbose in generating TraceActivity records and it can't be turned off.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#4645]
## Version

4.10.3

## Describe the bug

When using skills there are about 5 Trace activity generated per call to the skill.  Those trace activities get logged to the transcript (Generating a lot of transcript entries) and if the emulator is the channel they all get sent to the client (generating another chunk of transcript entities).

These are not core trace messages but include overly verbose messages like:

"Starting ..."

"dialog has ended, sending end of conversation"

etc.

## To Reproduce

use skills

## Expected behavior

I think we should have a mechanism for controlling how much trace activities are created by the library. TraceActivities have performance impact, and should be controllable since they are in the SDK code itself.

I would expect to be able to have a setting or configuration or something which controls the traceactivities.

## Screenshots

This is one turn, the skill is posting back 10 TraceActivity records.

![](https://user-images.githubusercontent.com/17789481/93030688-bdd85080-f5d9-11ea-816e-687444163865.png)

**Comment by mrivera-ms** [comment]
We should look at this in the context of end-to-end skills tracing. Up for investigation.
