### ISSUE TITLE
LuisRecognizer.RecognizeAsync returns null properties

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botbuilder-dotnet#4654]
## Version
What package version of the SDK are you using.
Assembly Microsoft.Bot.Builder.AI.Luis, Version=4.9.3.0

## Describe the bug
Give a clear and concise description of what the bug is.

               Foo skillResult = await localizedServices.LuisServices["foo"]
                    .RecognizeAsync<Foo>(innerDc.Context, cancellationToken: cancellationToken);
                innerDc.Context.TurnState.Add(StateProperties.SkillLuisResult, skillResult);
                state.LuisResult = skillResult;

This is expected to return a skillResult.Properties which is not null. But it returns null. In the older version 
Microsoft.Azure.CognitiveServices.Language.LUIS.dll Version=2.0.0.0 this used to return non-null properties which look like this 
{
  "query": "some json",
  "topScoringIntent": {
    "intent": "blah.blah2",
    "score": 0.7109051
  },
  "intents": [
    {
      "intent": "blah.blah3",
      "score": 0.7109051
    },
    {
      "intent": "blah.blah4",
      "score": 0.321258
    },
... truncated
}

I used the older Luis services with the new code and hit with the same error. So it is problem with the code.

## To Reproduce
See above

## Expected behavior
Properties should be non-null. Otherwise it is a regression.

## Screenshots
![image](https://user-images.githubusercontent.com/46580784/93177807-34637400-f6e8-11ea-9524-528138c9d05c.png)
Here is the screenshot which shows the expected "Properties" from the older code. I have redacted part of code for privacy.

**Comment by tsuwandy** [comment]
@munozemilio , @gabog, is this something you could take a look at?

**Comment by ipraveenMS** [comment]
We resolved it ourselves by   IncludeAPIResults = true as below.

 luisOptions = new LuisRecognizerOptionsV3(dispatchApp)
                    {
                        TelemetryClient = telemetryClient,
                        LogPersonalInformation = true,
                        IncludeAPIResults = true
                    };
