### ISSUE TITLE
Add Locale to ITurnContext

### ISSUE THREAD

**Issue by vitaliygor** [microsoft/botbuilder-dotnet#4657]
Hello team,

We are using Adaptive Dialogs library(version 4.8) for our solution. Due to the business needs, we use our own implementation of the ITurnContext. During updated to the latest version(currently 4.10.3) we faced the issue, that we cannot overcome by ourselves.

There is a method GetLocale in [DialogContext.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs)
that returns ((TurnContext)dialogContext.Context).Locale

The explicit cast breaks all the abstraction around ITurnContext and violates Dependency Inversion.

You had a discussion regarding the soft/explicit cast in the following [PR](https://github.com/microsoft/botbuilder-dotnet/pull/4276#discussion_r465130204) by @cosmicshuai and @gabog 

That explicit cast does not allow us to update the library to the latest version because we receive InvalidCastException. Soft cast also is not a good option, because in our case we will lose information about Locale. But Soft cast does not bring any runtime errors.

Locale property should be a part of the ITurnContext interface. Basically Locale property is a facade over TurnState.
I can suggest the following option to improve the codebase:
1. Bring Locale property to ITurnContext interface. It will allow avoiding that cast.
2. Make an extension to ITurnContext to get Locale. Locale duplicates logic with TurnState accessing.

Thanks

**Comment by cosmicshuai** [comment]
Sorry for causing this trouble for your development. 
We will discuss this issue and get a solution for this as soon as possible. Personally, I prefer bring locale interface to ITurnContext.

**Comment by gabog** [comment]
Hi @vitaliygor, can you provide more details on why you had to create your own implementation of ITurnContext instead for deriving from TurnContext? 

Thanks

**Comment by vitaliygor** [comment]
Hello @gabog 

We are using decoration over ITurnContext to add some additional behavior to the TurnContext. There are several reasons why we did that:
1. The decoration is more preferable than inheritance. [Discussion](https://stackoverflow.com/questions/4842978/decorator-pattern-versus-sub-classing)
2. Microsoft.Bot.Schema infrastructure is using ITurnContext and does not know anything about the TurnContext
3. Turn context was not designed to have derived classes. It has no virtual methods and constructor that is not convenient to use(dependency on BotAdapter)
4. Inheritance does not solve our needs

Basically we have 2 implementations of ITurnContext:
1. The first one is used to inject the ITurnContext into the DI as a scoped dependency. That allows us to inject ITurnContext into constructors and do not pass ITurnContext as a method parameter. That can make our abstraction much clearer. Domain logic does not depend on Microsoft.Bot.Schema.
2. Sometimes we need to replace AdaptiveDialog output with another message. So we have a decorator that collects the responses from AdaptiveDialog and makes its logic according to the business rules. It also allows capturing trace events from AdaptiveDialog. That simplifies troubleshooting.

Thanks

**Comment by carlosscastro** [comment]
Hello @vitaliygor! I'm working on this. Note that we cannot really add anything to `ITurnContext`, since it would break backward compatibility. So we cannot really take that part of your suggestion. 

I do agree that it is not good to have the cast to `TurnContext` and that part should be addressed. I'm exploring how to remove this cast, considering folks that have custom turn context implementations.

I'll update once I have a clear direction.

**Comment by carlosscastro** [comment]
@vitaliygor For the next release, I added a fix that removes the dependency on `TurnContext`. More changes are coming this way, but I put this small fix with hopes of unblocking you. If you have a multilanguage bot, there are a few more considerations when implementing your custom `ITurnContext`, so let me know if that is the case. Multilanguage + custom turn context will become smoother later after some changes but that will not make the release that is coming in the next week.

**Comment by paulreicherdt** [comment]
Hi @vitaliygor,

would you mind sharing your ITurnContext implementation? We are working on some bots and also want to inject current ITurnContext into our application layer to access UserState/ConversationState.
