### ISSUE TITLE
Changes to "turn.activity.value" not always being persisted

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4662]
## Version

4.10.3

## Describe the bug

I'm using composer and trying to add a property to "turn.activity.value" before forwarding the activity on to another event handler in my bot for processing. Something I've done dozens of times. This is the first time I've gone from one custom event to another and my changes are being dropped.  You can see the value I added in the first trace statement:

![](https://user-images.githubusercontent.com/698939/93307886-62af8500-f7b6-11ea-9634-583c3385077a.png)

And then in the very next trace statement its gone:

![](https://user-images.githubusercontent.com/698939/93308073-a0aca900-f7b6-11ea-8662-4c475637d1fc.png)

The only step between these two actions is an `EmitEvent` action.  The interesting bits are these:

*   I added this property several steps before the trace action so it was good for the lifetime of the current scope. It just didn't survive the transition to a new scope.
*   I've modified `turn.activity.value` numerous times in the past but I'm normally replacing the entire value and not simply adding a property.

My gut says that the issue is I'm working against a cached clone of the activity and this clone is periodically overwritten. If that's the case we should try to address that as there are plenty of times you want/need to manipulate the underlying activity.

**Comment by Stevenic** [comment]
Further evidence that something is amiss.  I modified my OnSaveItem event handler to dump out everything in the turn state. The top value is the activity and the bottom is the copy of the activity value I passed as the event args.  I'll use that value to work around my bug but we should try to fix this issue.

![](https://user-images.githubusercontent.com/698939/93309915-f7b37d80-f7b8-11ea-981d-219d51bf4f21.png)

**Comment by Stevenic** [comment]
And to be clear... I'm actually fine with the activity that's in turn state being a clone of the original activity but I should be able to make any changes I want to it for routing purposes.  What I don't fully get is I know I've successfully done this before.

**Comment by Stevenic** [comment]
So the work around was to simply copy `turn.dialogEvent.value` to `turn.activity.value`.  

![](https://user-images.githubusercontent.com/698939/93311520-f5eab980-f7ba-11ea-8514-5d1219a92850.png)

For giggles I disabled that change and then put a trace action on each side of the `EmitEvent` call. The result of that was that "newItem" was there before the emit event call but not after... interesting... That leads me to believe that the issue is we're over writing the cloned activity every time we create a new DC so let me check that:  

![](https://user-images.githubusercontent.com/698939/93311729-35b1a100-f7bb-11ea-8a6b-7a53a8a9a465.png)

**Comment by Stevenic** [comment]
And as I now suspected there it is:

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L36

Ummm.... Don't so that. We should assign the activity once at the beginning of the turn and not every time  we create a new DC. We create a lot of transient DC's.

**Comment by Danieladu** [comment]
I could not reproduce the issue. Could you provide the Bot assert built by Composer? That may help a lot. Thanks.

**Comment by gabog** [comment]
Linked this issue to #4817 and closed so we can address it as part of that one.
