### ISSUE TITLE
Reference conflicts 

### ISSUE THREAD

**Issue by atifgk** [microsoft/botbuilder-dotnet#4670]
**Error CS1705 Assembly 'Microsoft.Bot.Builder.Integration.AspNet.Core' with identity 'Microsoft.Bot.Builder.Integration.AspNet.Core, Version=4.10.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.AspNetCore.Http.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Http.Abstractions' with identity 'Microsoft.AspNetCore.Http.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	Azure FunctionApp**

## Version
Microsoft.Bot.Builder.Integration.AspNet.Core, Version=4.10.3.0 with azure function

## Describe the bug
Getting version conflict

## Screenshots
![image](https://user-images.githubusercontent.com/11180268/93599793-12177200-f9d8-11ea-93b6-bd7294658fe7.png)

**Comment by EricDahlvang** [comment]
Hi @atifgk 

I believe you will need to manually add a reference to Microsoft.AspNetCore.HttpAbstractions 3.1.0 in order to overcome this.  I assume your project is targeting net core 3.1?

**Comment by atifgk** [comment]
Hi @EricDahlvang thanks for reply. yes i'm using asp.net core 3.1 version. in nuget only Microsoft.AspNetCore.HttpAbstractions 2.2.0 available. can you please guide how i can install 3.1.0? thanks

**Comment by atifgk** [comment]
please see this one
https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/

**Comment by Jawvig** [comment]
I get the same issue. Steps to reproduce:
1) Create an Azure Function app in VS 2019
2) Add the "Microsoft.Bot.Builder.Integration.AspNet.Core" 4.10.3 package
3) Replace the contents of the function class with the following:

```
    public class Function1
    {
        private readonly IBotFrameworkHttpAdapter _adapter;
        private readonly IBot _bot;

        public Function1(IBotFrameworkHttpAdapter adapter, IBot bot)
        {
            _adapter = adapter;
            _bot = bot;
        }

        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            return await _adapter.ProcessAsync(null, null, _bot);
        }
    }
```
4) Compile the project

Here's what the .NET Core 3.1 version Microsoft.Bot.Builder.Integration.AspNet.Core assembly is referencing:
![image](https://user-images.githubusercontent.com/488393/93713188-1f586c00-fb52-11ea-9be7-a08e18f4a906.png)
i.e. version 3.1.0.0, which, as @atifgk says, is not available on NuGet
This clashes with the version of the Microsoft.AspNetCore.Http.Abstractions package as referenced (indirectly) by the Microsoft.Net.Sdk.Functions 3.0.7 (and 3.0.9, at least) package, which is version 2.1.0.

I think there's a workaround as the .NET Standard 2.0 package references the following:
![image](https://user-images.githubusercontent.com/488393/93713433-c7226980-fb53-11ea-8d4d-fca8811ec62f.png)
i.e. version 2.1.0.0
Hence the workaround ought to be indirectly referencing the package through a .NET standard library.

**Comment by EricDahlvang** [comment]
I apologize for my confusion in the above response.  Looking into this more, Microsoft.AspNetCore.HttpAbstractions is actually provided for a 3.1 project via a FrameworkReference:

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

Please add this to your .csproj file, and let us know how it goes.

**Comment by atifgk** [comment]
Hi @EricDahlvang ,
  Thanks for reply. I tried your solution it solved that error but now getting other error.

`System.Private.CoreLib: Exception while executing function: BotMessagesHandler. Microsoft.Bot.Connector: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.`

I tried installing **System.IdentityModel.Tokens.Jwt, Version=5.6.0.0** but no success

**Comment by atifgk** [comment]
@EricDahlvang please find project in attachment

[SampleProject.zip](https://github.com/microsoft/botbuilder-dotnet/files/5259774/SampleProject.zip)

**Comment by atifgk** [comment]
it work fine if i use Microsoft.Bot.Builder.Integration.AspNet.Core" 4.6.0 version

`<PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.10.3" />`

**Comment by EricDahlvang** [comment]
Well, this is odd.  Adding _FunctionsSkipCleanOutput to the .csproj fixes the System.IdentityModel.Tokens.Jwt load issue:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
```

More information about this can be found here:
https://github.com/Azure/azure-functions-vs-build-sdk/issues/397
and 
https://github.com/Azure/azure-functions-host/issues/5894

**Comment by atifgk** [comment]
Thanks @EricDahlvang its working now with your trick :)
