### ISSUE TITLE
TurnContext.TurnState is missing ClaimsIdentity in streaming scenarios

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#4674]
## Version
4.10.3

## Describe the bug
The ClaimsIdentity is not populated in the TurnState for streaming scenarios.

## To Reproduce
1. Setup the [24.bot-authentication-msgraph sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/24.bot-authentication-msgraph)
2. Configure Direct Line ASE or Direct Line Speech for the bot
3. Ping the bot via Web Chat
4. Check bot's logs for error, `Unable to get the bot AppId from the audience claim.`

## Expected behavior
The bot should have the ClaimsIdentity available for normal streaming scenarios.

## Additional context
There exists a workaround for populating the ClaimsIdentity in a BotFrameworkHttpAdapterBase subclass, which adequately works for Direct Line ASE. However, this route does not support dynamic setting which means it will not work on a bot using multiple Bot Channels Registrations with Direct Line Speech. (e.g. multiple AAD AppIds)

The BotframeworkHttpAdapter should populate the ClaimsIdentity during a successful upgrade for Direct Line Speech.

### Direct Line ASE/Single AAD AppId workaround:

```cs
    public class AdapterWithErrorHandler : BotFrameworkHttpAdapter
    {
        public AdapterWithErrorHandler(IConfiguration configuration, ILogger<BotFrameworkHttpAdapter> logger, ConversationState conversationState = null)
            : base(configuration, logger)
        {

            // For OAuth + Direct Line ASE scenarios, create and store a ClaimsIdentity with the AppId of the bot.
            var appId = configuration.GetSection(MicrosoftAppCredentials.MicrosoftAppIdKey)?.Value;

            ClaimsIdentity = new ClaimsIdentity(new List<Claim>{
                new Claim(AuthenticationConstants.AudienceClaim, appId)
            });
```

**Comment by xieofxie** [comment]
See related https://github.com/microsoft/botbuilder-dotnet/issues/4254

**Comment by stevengum** [comment]
After speaking with @carlosscastro, because NamedPipe connections don't perform any auth, deriving the AppId of the active bot is undesirable from a security standpoint. Additionally, it could lead to unintended consequences if multiple bots are hosted in one .NET app.

There's no further work to be done on this issue for R11, and instead will be picked up for R12 when the CloudAdapter and BotFrameworkAuthentication induce a reexamination of the streaming implementation.

Removing R11 milestone and P0 label.

**Comment by johnataylor** [comment]
See also https://github.com/microsoft/botbuilder-dotnet/issues/4850

**Comment by mrivera-ms** [comment]
Per @johnataylor, a PR will be published today (2/9).

**Comment by stevengum** [comment]
#5178 addresses the core issue in the CloudAdapter class, but not the BotFrameworkHttpAdapterBase. As the team is shifting focus on the new CloudAdapter, we are considering this issue addressed. The recommendation at this time is to update to the CloudAdapter.

@johnataylor @carlosscastro @mrivera-ms
