### ISSUE TITLE
Test library race condition introduced from not awaiting TryLogTranscriptAsync

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#4683]
## Version
main branch

## Describe the bug
This change https://github.com/microsoft/botbuilder-dotnet/pull/4681 (not awaiting TryLogTranscriptAsync) will cause tests to randomly fail.

## To Reproduce
1. Run all tests locally
2. BlobsTranscriptStoreTests. LogDeleteActivities and LogUpdateActivities might fail
3. If they don't fail, run them again.  
4. If they do fail, try running LogDeleteActivities and LogUpdateActivities one at a time.  They succeed this way, on my machine.

## Expected behavior
Tests should consistently pass, or fail... and not rely on tasks which are not awaited, to complete

## Screenshots
While running all tests:
![image](https://user-images.githubusercontent.com/11055362/93832044-4c2b8280-fc29-11ea-85ea-9d7d849901af.png)

While running failed tests one at a time:
![image](https://user-images.githubusercontent.com/11055362/93832064-5f3e5280-fc29-11ea-99f3-fe93c03bcb62.png)

## Additional context
A race condition has been introduced into our tests.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
