### ISSUE TITLE
Investigate if custom StorageTransferOptions should be used in BlobsTranscriptStore and BlobsStorage

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#4684]
**Is your feature request related to a problem? Please describe.**
Potentially improve performance of BlobsStorage and BobsTranscriptStore

**Describe the solution you'd like**
Tom and Carlos also raise an interesting point in this issue:
https://github.com/microsoft/botbuilder-dotnet/issues/4642

We should consider what is the optimal `StorageTransferOptions` for most bots, and maybe loosely expose these:

```
        //
        // Summary:
        //     The maximum length of an transfer in bytes.
        public int? MaximumTransferLength { readonly get; set; }
        //
        // Summary:
        //     The maximum number of workers that may be used in a parallel transfer.
        public int? MaximumConcurrency { readonly get; set; }
        //
        // Summary:
        //     The size of the first range request in bytes. Blobs smaller than this limit will
        //     be downloaded in a single request. Blobs larger than this limit will continue
        //     being downloaded in chunks of size MaximumTransferLength.
        public int? InitialTransferLength { readonly get; set; }
```

**Comment by mdrichardson** [comment]
This comment is more for me tracking my thoughts.

Resources:

* [Upload Blobs Quickly](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#upload-blobs-quickly)
* [Blob Types](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs)

We might be using an inefficient blob type, as well. We use Block, which is "optimized for uploading large amounts of data efficiently". Append type might be better? Changing might cause some backwards-compat issues.

**Comment by mdrichardson** [comment]
@tomlm @gabog @carlosscastro @EricDahlvang Any quick initial thoughts on [my comment, above](https://github.com/microsoft/botbuilder-dotnet/issues/4684#issuecomment-722567907)? I don't have much experience with Blob Storage and how we use it, currently. Some insight into these comments might prevent me from spending too much time down some rabbit holes.

**Comment by EricDahlvang** [comment]
@mdrichardson  Your comments and questions seem right on to me.  We would not necessarily have to change our underlying defaults (for backwards compat reasons), but maybe we should expose some of these parameters, for enabling configuring these things. In order to provide a path towards optimization under customer determined scenarios.

**Comment by mrivera-ms** [comment]
Pushing to R13 as investigation is ongoing.
@tomlm , @gabog, @carlosscastro could you comment on @mdrichardson's questions above? Thank you.
