### ISSUE TITLE
Allow *truly* proactive messages

### ISSUE THREAD

**Issue by arturl** [microsoft/botbuilder-dotnet#4708]
**Problem:** To send a proactive message to the user, the user has to have communicated with the bot previously, which allows the bot to get the `ConversationReference` for the `ContinueConversationAsync` call. (Creating `ConversationReference` from scratch is possible but hard)

This doesn't work in scenarios where the user has never communicated with the bot before, but has consented to receive proactive messages through other way. These "other ways" are channel-specific. For example, Teams and LINE require no additional consent for PUSH messages. Facebook is introducing a concept of one-time notification that requires a special token. Other channels have different restrictions and may or may not support it.

**Request:** Add a new API `SendActivityToUser` that can send a truly proactive message to the user. The API should be able to take channel-specific parameters such as Facebook's one-time notification token. That API should be support service-based channels as well as adapter-based channels.

**Comment by lzc850612** [comment]
@clearab do I remember correct that you're working on the proactive messaging feature?

**Comment by clearab** [comment]
Currently there is nothing in the works that I'm aware of like this that works across all channels. We support this in Teams via `createConversation` but it is not support on other channels. This would be a new feature request, and maybe fits best with @scheyal efforts for standardizing across channels?

**Comment by clearab** [comment]
I will say I'm not sure how much is possible here - we rely on the channel to create the conversationId I believe, so we'd probably need to partner with the channel owners and request they implement support for the `createConversation` API before we could make any traction here.

**Comment by EricDahlvang** [comment]
SDK support for, and definition of, 'proactive messaging' could use some disambiguation.  Some channels support creating a conversation with a user who has never messaged the bot (Teams, Email, LINE?).  1:1 'createConversation' support (under certain contexts).  Other channels have certain policies regarding proactive messaging.  Simplifying SDK support for the known scenarios seems like a valid request.

**Comment by mrivera-ms** [comment]
@scheyal could you please take a look at this and prioritize?

**Comment by scheyal** [comment]
(added so this doesn't get lost)
