### ISSUE TITLE
State property is missing in MessagingExtensionAction.cs which is required for authentication

### ISSUE THREAD

**Issue by Wajeed-msft** [microsoft/botbuilder-dotnet#4709]
State property is missing in [MessagingExtensionAction.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionAction.cs). This should be similar to [MessagingExtensionQuery.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionQuery.cs#L74) State property. 

## Version
Microsoft.Bot.Builder.Integration.AspNet.Core - 4.10.3

## Describe the bug
In order to get Magic code while authenticating request in [Messaging Extension Action](https://github.com/Wajeed-msft/TeamsMessagingExtensionsActionAuthConfig/blob/master/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs#L74) we need to get the state value from the payload. It's missing in MessagingExtensionAction.cs,

## To Reproduce
Look at the sample for [authentication in Messaging Extension action](https://github.com/Wajeed-msft/TeamsMessagingExtensionsActionAuthConfig/blob/master/Bots/TeamsMessagingExtensionsSearchAuthConfigBot.cs#L62).

## Expected behavior
Add State property in [MessagingExtensionQuery.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionQuery.cs#L74).

**Comment by clearab** [comment]
Thanks for reporting, we'll get this added.

**Comment by clearab** [comment]
@EricDahlvang do you have time to pick this one up?

**Comment by EricDahlvang** [comment]
@clearab  https://github.com/microsoft/botbuilder-dotnet/pull/4718  (the build will fail because of binary compat rules, but i think we are no longer enforcing that level of compat for parameter additions???)

**Comment by clearab** [comment]
Yeah, I thought we dropped that when we pulled in the Teams stuff. @cleemullins or @mrivera-ms are we still enforcing binary compat?

**Comment by Wajeed-msft** [comment]
@cleemullins , @mrivera-ms - Could you please help here?
