### ISSUE TITLE
parity: UserAgent string for .Net contains wrong protocol version number

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#471]
The UserAgent string for .Net found here:

https://github.com/Microsoft/botbuilder-dotnet/blob/542b988d84f3ab9cfd9a6260fd39edccc2191b43/libraries/Microsoft.Bot.Connector/ConnectorClientEx.cs#L34

Translates to `Microsoft-BotFramework/4.0 (BotBuilder .Net/${package version})`.

Compare that with the JS UA string of `Microsoft-Botframework/3.1 (BotBuilder JS/${package version})`.

My understanding is that the first version number is supposed to be the protocol version which should still be "3.1" correct?

**Comment by dandriscoll** [comment]
That's right, the JS string is correct.

**Comment by cleemullins** [comment]
Fixed in #489
