### ISSUE TITLE
Declarative Adaptive Dialog issue with LUIS Recognition

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botbuilder-dotnet#4714]
Hello Team,

I am using Declarative adaptive dialog for our chatbot. I tired including the recognizer as LUIS in my .dialog file. But i am getting  Type Microsoft.LuisRecognizer not registered in factory error while execution. I am doing with the following steps in my declarative files.

Created below 4 declarative files.
Test.lu

![image](https://user-images.githubusercontent.com/17233137/94301603-7910ca00-ff88-11ea-82a0-cc3450cc0abd.png)

Created trained and publish the LUIS app in LUIS portal.

Test.lu.dialog

`{
    "$kind": "Microsoft.MultiLanguageRecognizer",
    "recognizers": {
        "en-us": "Test.en-us.lu",
        "": "Test.en-us.lu"
    },
    "$schema": "../../TestBot.schema"
}`

Test.en-us.lu.dialog

{
    "$kind": "Microsoft.LuisRecognizer",
    "applicationId": "my-app-id",
    "endpoint": "our endpoint",
    "endpointKey": "our key",
    "$schema": "../../TestBot.schema"
  }`

Test.main.dialog

`{
    "$schema": "../../TestBot.schema",
    "$kind": "Microsoft.AdaptiveDialog",
    "autoEndDialog": true,
    "defaultResultProperty": "dialog.result",
    "recognizer" : "Test.lu",
    "triggers": [
        {
            "$kind": "Microsoft.OnIntent",
            "intent": "Greeting",
            "actions": [
              {
                "$kind": "Microsoft.SendActivity",
                "activity":  "Greetings  intent!!!"
              }
            ]
        },
        {
            "$kind": "Microsoft.OnIntent",
            "intent": "Service",
            "actions": [
              {
                "$kind": "Microsoft.SendActivity",
                "activity":  "Service intent has been triggered..."
              }
           ]
        },
        {
            "$kind": "Microsoft.OnIntent",
            "intent": "Cancel",
            "actions": [
              {
                "$kind": "Microsoft.SendActivity",
                "activity":  "The cancel intent has been triggered..."
              }
            ]
        }
    ]
}

I am loading the required dialog file in my class, but still getting the above mentioned error. Kindly help me in solving the issue.

**Comment by ninggao** [comment]
@dmvtech Could you take a look at this please?

**Comment by dmvtech** [comment]
Hi @Vigneshramkumar Did you publish to your staging slot, production slot or both?

**Comment by Vigneshramkumar** [comment]
@dmvtech - Thanks for your response. I published to both staging and production slots in LUIS portal.

**Comment by Vigneshramkumar** [comment]
@dmvtech - I published to both staging and production slots in LUIS portal. In Emulator i am getting below error while running the bot.

![image](https://user-images.githubusercontent.com/17233137/94533833-52d77c80-025d-11eb-9a78-6db05423cc64.png)

And below is the logic i have written in bot for loading the dialog file through ResourceExplorer. The dialog file name is Luis.main.dialog.

![image](https://user-images.githubusercontent.com/17233137/94534030-903c0a00-025d-11eb-9d96-ab558b5e5be9.png)

**Comment by dmvtech** [comment]
Thanks. I'm looking into this more.

**Comment by Vigneshramkumar** [comment]
@dmvtech - The issue is that i missed to register the Luis component in Startup class of my project. That is the issue. It is now running fine once i included the same. Thanks for all your support.

I am calling the onTurnAsync of Dialog Manager for executing the dialog files and i am passing the DialogManager result as reply to users. But i want to manipulate the value i got from dialog manager before sending to users. Kindly let me know how can i get the result. I tried with getting the response from turn result of the DialogManager result and it is empty. But i am getting the result in emulator based on the dialog file response.

![image](https://user-images.githubusercontent.com/17233137/94595463-812e7980-02a8-11eb-800c-f21393938fa3.png)

![image](https://user-images.githubusercontent.com/17233137/94595634-b89d2600-02a8-11eb-8459-f47baba66188.png)

Thanks in advance for your response.

**Comment by dmvtech** [comment]
Hi @Vigneshramkumar Sorry for the delay.

You are wanting to modify the actual response message that gets sent to the users before being sent to them, correct? Typically, this is done with [middleware](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-middleware?view=azure-bot-service-4.0).

**Comment by dmvtech** [comment]
Hi @Vigneshramkumar Any luck? did you try using middleware to accomplish your goal?

**Comment by dmvtech** [comment]
Closing. Assuming that you resolved it. Please let us know if that is not the case.
