### ISSUE TITLE
Gov Auth Constants Need Updating

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#4729]
Various Gov Auth constants in the current code need updating. These should be updated independently of any additional configuration driven changes that we are bringing in with the new CloudAdapter.

The following is wrong:

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/EmulatorValidation.cs#L32

and mostly likely this is also wrong:

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/GovernmentAuthenticationConstants.cs#L44

@willportnoy please add relevant details.

**Comment by stevengum** [comment]
This isn't a Size: S if you count the other languages and E2E testing... I think this should be transferred to BotFramework-SDK

**Comment by willportnoy** [comment]
The GUID cab8a31a-1906-4287-a0d8-4eef66b95f6e reflects the USME.gbl tenant that contains our older bot->channel AAD resource application, which worked for Fairfax.

MicrosoftServices.onmicrosoft.us is the proper tenant that contains our newer bot->channel AAD resource application, which will transparently work for Fairfax and Arlington.

After updating these constants, the emulator will need to be validated with Fairfax and Arlington bot identity AAD applications.

**Comment by johnataylor** [comment]
This is the table used in the service code:

    "ValidIssuers": [
      "https://sts.windows.net/cab8a31a-1906-4287-a0d8-4eef66b95f6e/",
      "https://sts.windows.net/cab8a31a-1906-4287-a0d8-4eef66b95f6e/v2.0",
      "https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/",
      "https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
      "https://login.microsoftonline.us/cab8a31a-1906-4287-a0d8-4eef66b95f6e/",
      "https://login.microsoftonline.us/cab8a31a-1906-4287-a0d8-4eef66b95f6e/v2.0",
      "https://login.microsoftonline.us/f8cdef31-a31e-4b4a-93e4-5f571e91255a/",
      "https://login.microsoftonline.us/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0"
    ]

The SDK should be the same.
