### ISSUE TITLE
We should add a new CopyResponse action

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4730]
We have a powerful localization system in LG yet there's no simple way to use it for localizing things like choice set options.  We should add a new `CopyResponse` action which works the same way as `SendResponse` but lets you specify a memory variable to save the output of LG to.  We should then update SendResponse to generate the outgoing activity using a template or to pull it dynamically from memory.

This will broaden the range of uses for LG to cover anything that needs localization, not just activities. You'll be able to localize card choices, database fields, etc.

**Comment by boydc2014** [comment]
Put this to backlog

Alternatives：
* auto binding LG templates as functions to all actions, so that setProperty(ties) should work
* expose (or double check do we have) a function called template\bindToTemplate and make sure it can be used in setProperty
* create a new property in Send Activity

**Comment by mrivera-ms** [comment]
@darrenj please triage, prioritize, and add customer scenarios.

**Comment by boydc2014** [comment]
So, we had a design review with ChrisMc, Tom, Steve, ChrisW, the direction we feel good about is making LG templates\functions generally available in any actions, which will help us
* remove the necessary to use namespace + exports notions
* help localization in other actions like https://github.com/microsoft/botbuilder-dotnet/issues/2387

**Comment by sgellock** [comment]
Shiproom - moving out of R13 to R14

**Comment by cleemullins** [comment]
Removing this from R14 until PM is able to drive a scenario around localization.
