### ISSUE TITLE
Build and publish NuGet symbol/src packages

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#474]
## Overview
Officially released packages should publish src and symbols so that the debugging experience can be as flawless and rich as possible for the scenario where the developer is working with packages instead of the raw source code.

## Build Changes
First, we need to enhance the builds so they build companion symbols package for each NuGet package. This would only take adding an `<IncludeSymbols>true</IncludeSymbols>` property to the build.

Now, symbols are cool, but you know what's really cool...? Having source code so developers can step through code directly as they're debugging or just end up in the source code when an exception occurs so they can see exactly what's going on. Now, there's a couple of options for this:

 1. Add an `<IncludeSource>true</IncludeSource>` property to the build and it will embed the source code directly into the symbols package. This is a little "heavier" because it forces you to download the source files even if you're _just_ trying to get the PDBs.
 2. Employ SourceLink and generate a map file that actually just links all the files right back here to the GitHub repo. Visual Studio has native support for SourceLink baked in and provides an amazing experience for stepping through SourceLink'd packages. [Details on configuring SourceLink are available here](https://github.com/ctaggart/SourceLink).

## Publishing
Building the packages is one thing, but we need to actually publish the symbols if we want them to be available for users. Today this requires a second, manual push of the symbols package to https://nuget.smbsrc.net. This would need to be configured as a new task in the VSTS build definition.

## Further Reading
More about these topics can be found here: [Publishing and Consuming Symbols and Source for Debugging](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md). One interesting thing of note is that while this is pretty well established for the past couple of years, [it's clear there is a big change coming to NuGet.org taking symbols on natively](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements#SymServ) and so, as soon as that happens, a lot of this should be more streamlined.

**Comment by yochay** [comment]
@drub0y  please validate
