### ISSUE TITLE
The converastion State is not persistent for the proactive notification

### ISSUE THREAD

**Issue by kandy99** [microsoft/botbuilder-dotnet#4753]
I create a chatbot that is able to send a proactive notification but when I publish the bot again it loses its conversation reference  
There are not enough resources/example for the same to maintain the conversation refrence

**Comment by v-kydela** [comment]
@kandy99 - Okay so how would you like us to help you? You haven't included a question in your post, so it's unclear if you want us to fix your bot for you or if you want us to make a new sample, etc.

**Comment by kandy99** [comment]
it will be good if there is a proper sample for this problem

**Comment by ryanlengel** [comment]
Closing due to issue microsoft/BotBuilder-Samples#2825, please follow that one for updates. Thank you!
