### ISSUE TITLE
Cosmos DB storage class does not account for nesting limit

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#4755]
## Version
latest

## Describe the bug
While using `CosmosDbPartitionedStorage`, bots can throw an error message like this: "The request payload is invalid. Ensure to provide a valid request payload." Sometimes this is because of a [limit](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits) which was only recently documented: https://github.com/MicrosoftDocs/azure-docs-pr/pull/132479

We may want to account for all of the documented limits when writing to Cosmos DB, but because Bot Framework dialogs can easily create state that exceeds the nesting limit we should definitely at least account for that limit by providing an appropriate error message.

This issue has already resulted in at least one IcM, and the discussion indicates that other customers are reporting this sort of problem as well: https://portal.microsofticm.com/imp/v3/incidents/details/203892268/home

### Observe the nesting limit in Cosmos DB directly

1. Go to a Cosmos DB resource in the Azure Portal
2. Paste the contents of [nest.txt](https://github.com/microsoft/botbuilder-dotnet/files/5329776/nest.txt) into an item
3. Click the update button

### Observe the undescriptive error message in the Bot Builder SDK

Run the following code in a console app, replacing string placeholders where necessary:

```c#
var storage = new CosmosDbPartitionedStorage(
        new CosmosDbPartitionedStorageOptions
        {
            CosmosDbEndpoint = "https://{YOUR_DOMAIN}.documents.azure.com:443/",
            AuthKey = "{YOUR_AUTHKEY}",
            DatabaseId = "{YOUR_DATABASE}",
            ContainerId = "{YOUR_CONTAINER}",
            CompatibilityMode = false,
        });

// Three data-generation methods are included here to prove that the problem is caused by nested data.
// Cosmos DB can handle very large items just fine when the data contains many lines or very long lines.
// The problem is specifically caused by deep nesting.

static JObject CreateNestedData(int count) => new JObject
{
    { "data", count > 0 ? CreateNestedData(count - 1) : null },
};

static JObject CreateStackedData(int count) => new JObject
{
    { "data", new JArray(Enumerable.Range(0, count).Select(index => new JObject { { "data", null } })) },
};

static JObject CreateLongData(int count) => new JObject
{
    { "data", new string('A', count) },
};

var dict = new Dictionary<string, object>
{
    { "foo", CreateNestedData(128) }, // Throws error
    //{ "bar", CreateStackedData(11128) }, // Doesn't throw error
    //{ "baz", CreateLongData(1111128) }, // Doesn't throw error
};

var changes = new Dictionary<string, object>
{
    { "{YOUR_CONTEXTKEY}", dict },
};

Console.WriteLine("Writing...");

storage.WriteAsync(changes).Wait();
```

## Expected behavior
An error message should be thrown that lets the developer know what's wrong and how they can fix it. Just explaining that the data is nested too deeply would be good, but checking for dialog state specifically and explaining that the dialogs should be fixed would be even better.

**Comment by mrivera-ms** [comment]
@v-kydela This will need parity in the other languages. Please make sure issues are created to track them in other repos.
