### ISSUE TITLE
Bug: A zero length string in the outputFormat field of a prompt will causes the prompt to fail

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#4758]
##  Version
4.10

## Describe the bug

If the outputFormat field is set to "", the SDK interprets to mean that the value should be set to "", resulting in an unrecognized prompt error firing regardless of what the user input is.  This can occur when a user in Composer sets the outputFormat, then removes it, resulting in "" being serialized into the JSON file.

## To Reproduce
1. Create a prompt in Composer
2. Set the output format to something
3. Remove the value of the output format field.
4. Set a value for the unrecognized prompt
5. Run the bot - notice that the the prompt will never accept the value, regardless of what is provided.

## Expected behavior
I would expect this to be interpreted by the SDK to mean no output format is being applied, and the value will be left unmodified.

**Comment by Danieladu** [comment]
If the customer just wants to assign an empty string to the "outputFormat"?  Maybe add a checkbox after the block?

**Comment by benbrown** [comment]
Why would they possibly ever want to do that? It would result in the prompt never getting a value.

**Comment by Danieladu** [comment]
> n

Make sense. I will follow it.

**Comment by Danieladu** [comment]
@benbrown I have created a PR track this issue. Please take a look and see if it meet the requirement. Thanks.
