### ISSUE TITLE
Turn off binary compatibility verifications in dotnet CI pipelines

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#4759]
As discussed [here](https://github.com/microsoft/botbuilder-dotnet/pull/4718).

**Comment by EricDahlvang** [comment]
Does the library we are using have a 'compile compat' option?

**Comment by BruceHaley** [comment]
PR #4761 is merged. Compatibility verifications can now be turned off by editing in ADO BotBuilder-DotNet-CI-PR-yaml, setting the variable DisableApiCompatibityValidation to true.
