### ISSUE TITLE
Multiple Parameter Search Query Messaging Extension for Teams

### ISSUE THREAD

**Issue by MCKRUZ** [microsoft/botbuilder-dotnet#4762]
## Version
4.10.3.0

## Describe the bug
Unable to access multiple parameters when creating a Search Query Messaging Extension for Teams.  In a nutshell, I have a bot for teams that I need to have multiple parameters entered in for before I can search.  I can update my app manifest to have multiple parameters but when I go and test it, it will not allow me to enter multiple values.

**Comment by anusharavindrar** [comment]
Multi-parameter is only supported for command type set to action. You will need to specify multiple search commands, not multiple parameters (with one parameter per search command). Also, note that you can't actually trigger a search-based command from a message, so you should only include the compose and commandBox scopes for them.
