### ISSUE TITLE
Support for Bot Framework Search Protocol

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botbuilder-dotnet#4768]
This work item can be used to track supporting the bot framework search protocol (built on top of Activity Invoke) within the SDK. This allows a bot to serve as a search result provider within various search canvases, returning both text based results as well as interactive Adaptive Cards 2.0.

Needs to include the Auth Scenarios.

**Comment by mrivera-ms** [comment]
Target for R12 is investigation and definition of requirements.

**Comment by mrivera-ms** [comment]
This item is for reviewing the spec. @johnataylor  and @cleemullins will take this.

**Comment by cleemullins** [comment]
Need PM Assistance. Scenarios / Scoping / Dates are needed before engineering can move forward.

**Comment by mrivera-ms** [comment]
@Jeffders, @darrenj, please see the request above. Thank you.

**Comment by cleemullins** [comment]
Discussed with @mrivera-ms, who has the specs and has identified the components needed for implementation.

**Comment by mrivera-ms** [comment]
There is no implementation work to be done for the current milestone (R14). This issue was only tracking the specification and preliminary discussions. We will need to create child issues to track implementation work during the next milestone.
