### ISSUE TITLE
[Expression]Convert type safely

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#4773]
Currently, there is no way to parse an object into a specific type safely.
related issue: #4615

If someone wants to know if an object can be cast into int, there are several ways:
- use `isInteger(xx)`, but this one only covers the parameters whose original type is number. 
- use `int(xx)`, this one would throw exception when the object can not be converted into Integer.

The requirement is to obtain a method that can safely cast types.

There are several solutions:
### Modify the original conversion functions
`int(xxx)` would try to parse the object into int, if parse failed, return null/undefined or original value instead of throw exception.

### Add a series of new builtin functions
For example, if function `tryParseToInt` is appended into the builtin list.
```
tryParseToInt(123) -> (true, 123)
tryParseToInt('345') -> (true, 345)
tryParseToInt('abc') -> (false, 'abc')
```
or 
```
tryParseToInt(123) -> 123
tryParseToInt('345') -> 345
tryParseToInt('abc') -> null/undefined/'abc'
```

### Related functions
- int
- string
- json
- float
- bool
- base64
- xml (C# only)
- binary

[DCR]
[requirements]

**Comment by mrivera-ms** [comment]
@garypretty please prioritize and identify customer scenarios.

**Comment by Danieladu** [comment]
@microsoft/bf-adaptive any thoughts about this one?

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
