### ISSUE TITLE
OAuthUrl values are incorrect and OAuthClient.Initialize() should use AuthenticationConstants.OAuthUrl

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#4774]
Public cloud should use [https://token.botframework.com](https://github.com/microsoft/botbuilder-dotnet/blob/04204a8506e0683846621771880b9001adfd214a/libraries/Microsoft.Bot.Connector/OAuthClient.cs#L701) 
and USGov cloud should use https://token.botframework.azure.us.

`OAuthClient.Initialize()` shouldn't use a magic string for its `BaseUri`.

## Version
`main` @ 04204a8506e0683846621771880b9001adfd214a

**Comment by johnataylor** [comment]
Note this is explicit parameterized in the new UserTokenClientImpl class.

However, for completeness, as this issue highlights, the default value in the Initialize should use the constant (it can just use the _public_ cloud constant in the default.)

But what is the correct constant: in the code we have:  https://**api**.botframework.com and https://**api**.botframework.azure.us

**Comment by swagatmishra2007** [comment]
both would actually work (they point to the same service) . however, go with api as the constant in the code (which is what the sdk has today)

**Comment by johnataylor** [comment]
Thanks @swagatmishra2007  and I'll add the code to actual use the constant in the Initialize.

Do take a look at the UserTokenClient code when you get a chance - it is now the user of this lower level client. It's _much_ simpler than the 17 method IExtendedUserToken thing...
