### ISSUE TITLE
QnAMaker: Is using a hardcoded Region in the endpoint string a bug?

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#478]
Is it a problem for the Region to be hardcoded into the QnA Maker service endpoint?

We currently have

[public const string qnaMakerServiceEndpoint = "https://westus.api.cognitive.microsoft.com/qnamaker/v3.0/knowledgebases/";](https://github.com/Microsoft/botbuilder-dotnet/blob/762f76b7188b53607ea55cd05c73781af0911cc4/libraries/Microsoft.Bot.Builder.Ai.QnA/QnAMaker.cs#L14)

and then this in the constructor:
```csharp
_answerUrl = $"{qnaMakerServiceEndpoint}{options.KnowledgeBaseId}/generateanswer";
```

**Comment by cleemullins** [comment]
Every time I see this, I believe it's a bug. Then I reach out to the product team and ask, and they say "That's correct". 

So at this point, it's right. As the product goes GA shortly, that may change.
