### ISSUE TITLE
[Orchestrator] Add model version\id as a metadata to OrchestratorRecognizer 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#4787]
Base model version\id is a key metadata that is missing in current interface.

With this model version\id, user won't be able to tell and download the model if the model is missing (and it's very likely to be missed when copying\moving declarative bots).

**Comment by daveta** [comment]
@tsuwandy : Per discussion , think this manifests in bf-cli orchestrator plugin (no orchestrator API changes).  Seems like priority on this is lower.
