### ISSUE TITLE
QnA Maker: improve error checking and default value handling

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#479]
In the QnAMaker constructor we stub in default values for ScoreThreshold and Top options, but don't have any error checking. The call to `GetAnswers` include no further checks or processing on these values.
```csharp
if (_options.ScoreThreshold == 0)
{
    _options.ScoreThreshold = 0.3F;
}

if (_options.Top == 0)
{
    _options.Top = 1;
}
```
These two options jumped out at me, there may be others that should also be checked in code before sending the request.

**Note**: ScoreThreshold is used for filtering the response, so it is less of a problem, but a bounds check
with an appropriate error message would probably be helpful to developers.

**Comment by cleemullins** [comment]
@garypretty Thanks Gary!!
