### ISSUE TITLE
Unable to set MicrosoftAppPassword value in azure function V3

### ISSUE THREAD

**Issue by atifgk** [microsoft/botbuilder-dotnet#4801]
I'm trying to set MicrosoftAppPassword in azure function but no success.

I have created ConfigurationCredentialProvider class and inlcuded in Startup.cs

```
internal class ConfigurationCredentialProvider : SimpleCredentialProvider
    {        
        public ConfigurationCredentialProvider(IConfiguration configuration)
        {
            this.Password = "App password here";
        }
    }
```

```
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = new ConfigurationBuilder()
                .AddEnvironmentVariables()
                .Build();


            // Set up the dependency injection container
            var serviceCollection = builder.Services;

            serviceCollection.AddSingleton<ICredentialProvider, ConfigurationCredentialProvider>();
        }
    }
```

I always get this exception
`Exception while executing function: BotMessagesHandler <--- Value cannot be null. (Parameter 'clientSecret')`

If i add key 'MicrosoftAppPassword' in local.settings.json then Bot automatically pick app password from json

**Comment by dmvtech** [comment]
Hi @atifgk Just to clarify; you want to set the password in code and **_not_** have it pull from the configuration? (essentially overriding the built in way to pull from the settings/config)

**Comment by atifgk** [comment]
Hi @dmvtech thanks for reply. yes I want to set password from code as I have stored password in azure key vault

**Comment by atifgk** [comment]
can you please provide some example for setting using settings/config? thanks

**Comment by dmvtech** [comment]
hi @atifgk I'm working on it. I don't have much experience with functions myself, but I'll see what I can do.

With .NET/core (or even JS, etc) they will utilize the values in either the settings (`appsettings.json` or `.env`) for appid/apppassword, or it will use the App Service/Web App (or I guess even the Function's) Configuration settings. 

I don't know of any examples/samples of pulling these values from Key Vault, so let me see if I can get that working and applied to a functions bot as well.

**Comment by atifgk** [comment]
Hi @dmvtech , i know about using key vaults. if you can provide code sample that can set password from code instead of appsettings.json then that will be very helpful thanks

**Comment by atifgk** [comment]
@dmvtech , please have a look on this sample code https://stackoverflow.com/a/56548451/5064424 or this one https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp.

```
var appId = Configuration.GetSection("MicrosoftAppId").Value;
var appPassword = Configuration.GetSection("MicrosoftAppPassword").Value;
options.CredentialProvider = new SimpleCredentialProvider(appId, appPassword);
```
instead of reading password from Configuration, i want to set it from code like

```
var appId = Configuration.GetSection("MicrosoftAppId").Value;
var appPassword = "some hard coded passowrd from code here";
options.CredentialProvider = new SimpleCredentialProvider(appId, appPassword);
```

**Comment by atifgk** [comment]
i also have tried this code and registered this file in startup.cs but this function never gets triggred 

```
using Microsoft.Bot.Connector.Authentication;
using Microsoft.Extensions.Configuration;

namespace CoreBot1
{
    public class ConfigurationCredentialProvider : SimpleCredentialProvider
    {
        public ConfigurationCredentialProvider(IConfiguration configuration)
        {
          this.Password = "App password here";
        }
    }
}
```

**Comment by atifgk** [comment]
Hi @jwiley84 @stevkan @ryanlengel @dmvtech any luck on this issue?

**Comment by dmvtech** [comment]
Hi @atifgk No luck yet. I'm still working on it. Hope to have some sort of finding/answer for you in a day or two.

**Comment by atifgk** [comment]
thanks :)

**Comment by dmvtech** [comment]
Hi @atifgk Would you be able to share a sanitized (of personal/sensitive info) repo of your function code? What did you use as a starting point (did you use one of the samples, or from a visx, etc). 

Also; you mentioned V3, that is Azure Function V3, not Bot Framework V3, correct? (Assumed so, just need to make sure).

**Comment by dmvtech** [comment]
Also; I'm assuming this is .cs and not .csx, correct?

**Comment by atifgk** [comment]
@dmvtech  i have attached my code. yes its azure function v3
[FunctionApp1.zip](https://github.com/microsoft/botbuilder-dotnet/files/5504165/FunctionApp1.zip)

**Comment by dmvtech** [comment]
Hi @atifgk Sorry for the delay. I'll have an update for you by end of day.

**Comment by dmvtech** [comment]
Still working on it unfortunately. Will continue and update next week.

**Comment by atifgk** [comment]
@dmvtech thanks

**Comment by hcyang** [comment]
@dmvtech, any update?

**Comment by dmvtech** [comment]
Hi @atifgk 

Apologies for the delay. I was attempting to get something working in Azure as _well as_ with KeyVault. Unfortunately, although I have a bot running locally, I cannot get it running deployed in Azure (my lack of Function knowledge, i'm sure). 

> instead of reading password from Configuration, I want to set it from code like

Understood. I am attempting to see if I can get it working locally with KeyVault, but essentially something based off of something like this:
https://damienbod.com/2020/07/20/using-key-vault-and-managed-identities-with-azure-functions/

I'll keep at it.

**Comment by atifgk** [comment]
@dmvtech thanks

**Comment by carlosscastro** [comment]
Hello @atifgk! 

I'm looking at your issue, and I have a couple of questions / things to try first:

Bot framework already has a class called `ConfigurationCredentialProvider`, so I'd suggest using another name such as `KeyVaultCredentialProvider` for your custom class to avoid confusion. Otherwise you could be instantiating the wrong class and I want to make sure we rule that out.

Once you have that, you modify the Startup.cs of the function app to use your custom credential provider. You need to update 2 places in the code for it to be effective. Please check out the links I'm including to the original composer source code and exact line that I'm referring to.
 
First, update the [`ICredentialProvider` registration ](https://github.com/microsoft/BotFramework-Composer/blob/main/runtime/dotnet/azurefunctions/Startup.cs#L65) to use your custom provider:

```csharp
services.AddSingleton<ICredentialProvider, KeyVaultCredentialProvider>();
```

Second, update [the explicit creation of the adapter ](https://github.com/microsoft/BotFramework-Composer/blob/main/runtime/dotnet/azurefunctions/Startup.cs#L135) which receives an `ICredentialProvider` in the specific constructor that is being used.

```csharp
var adapter = new BotFrameworkHttpAdapter(new KeyVaultCredentialProvider(<your parameters>));
```
Could you please try these and let us know if that works for your scenario? Thanks!

**Comment by atifgk** [comment]
@carlosscastro @dmvtech thanks.  implenting !CredentialProvider worked

```
internal class ConfigurationCredentialProvider : ICredentialProvider
    {
        public Task<bool> IsValidAppIdAsync(string appId)
        {
            return Task.Run(() => true);
        }

        public Task<string> GetAppPasswordAsync(string appId)
        {
            return Task.Run(() => _"App passowrd"));
        }

        public Task<bool> IsAuthenticationDisabledAsync()
        {
            return Task.Run(() => false);
        }

    }
```
