### ISSUE TITLE
Static test constructors cause slow perf and unnecessary changes

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#4802]
## Version
4.10.x.

## Describe the bug
When we refactored our tests to xUnit we moved some expensive logic to static constructors (e.g.: see [SchemaMergeTests.cs](https://github.com/microsoft/botbuilder-dotnet/blob/0ccb16edcd1d69395700bbc0f1b4f8941cb99382/tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs#L31). 

VS Test Explorer executes these static constructors when attempting to enumerate the tests which recreates files and also starts the ComsbosDB emulator resulting in slow IDE performance. 

For the case of tests.schema and tests.uischema, this may also change those files and the output may be different than what we have in git if you don't have the latest CLI version.

## To Reproduce
1. Open the solution in visual studio.
2. Open the test explorer window
3. While the tests are being discovered, you'll see CosmosDB starting up and you'll notice that tests.schema and tests.uischema are being updated (sometimes with different results based on the version of the CLI you are running)

## Expected behavior
I would expect the schemas would only be updated if I am running tests related to schemas and that the CosmosDB and Azure Storage emulators would run only if I am running tests related to them.

## Screenshots
![image](https://user-images.githubusercontent.com/12264946/96132126-febcd100-0ec7-11eb-8ecb-b8854136bd89.png)

## Additional context
We should probably remove these static constructors and refactor the tests to use [Class Fixtures](https://xunit.github.io/docs/shared-context.html#class-fixture) or [Collection Fixtures](https://xunit.github.io/docs/shared-context.html#class-fixture)

See also [XUnit comparison to MS  Tests](https://xunit.net/docs/comparisons#attributes) for more info the alternative for ClassInitialize

**Comment by gabog** [comment]
I need to work on some higher priority tasks, pushing this one to R13

**Comment by mrivera-ms** [comment]
Per discussion with @gabog, this is out of scope for R13.
