### ISSUE TITLE
Proactive messaging doesn't work with emulator

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#4806]
## Version
Gabo's fork

## Describe the bug
Credential validation fails with emulator. It checks to see if the appId is the parent bot's appId instead of being on the authorized list of app IDs. This check happens in the `EmulatorValidator.cs`. 

## To Reproduce
1. Spin up the `DialogRootBot` and the `ProactiveSkill` bot. 
2. Send the parent bot a message and connect to the skill
3. Click the link the skill provides to do proactive

## Expected behavior
The flow should complete

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/96196086-617f8e00-0f03-11eb-8a55-1e6fa705afff.png)

## Additional context
This also breaks when I tested with directline. 

```
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "ReplyToActivity", controller = "Skill"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] ReplyToActivityAsync(System.String, System.String, Microsoft.Bot.Schema.Activity) on controller Microsoft.BotBuilderSamples.DialogRootBot.Controllers.SkillController (Microsoft.BotBuilderSamples.DialogRootBot).
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Bot.Connector.dll
Exception thrown: 'System.UnauthorizedAccessException' in System.Private.CoreLib.dll
```

**Comment by gabog** [comment]
Closing this one with workaround.

The proactive logic in [this project](https://github.com/microsoft/BotFramework-FunctionalTests/tree/main/Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot) shows what info needs to be stored for a skill to get proactive messages to work (I will review later with @EricDahlvang to see if there's a better way of doing this)
