### ISSUE TITLE
DebugSupport.SourceMap has undefined behavior in multithreading scenarios

### ISSUE THREAD

**Issue by babrekel** [microsoft/botbuilder-dotnet#4807]
## Version
4.10.5

## Describe the bug
`DebugSupport.SourceMap` has undefined behavior in multithreaded scenarios due to the static nature of the `Dictionary` instance. 

## Expected behavior
Expect concurrent resource managers to be able to load & validate content without affecting each other.

**Comment by carlosscastro** [comment]
This can move to R13 when we'll do some debugging improvements. There are 2 workarounds for this issue at the moment:

- By default, debugging is not enabled, so this doesn't repro
- For a temporary fix if you want debugging enabled but experience this issue, you can use the workaround in this PR: https://github.com/microsoft/botbuilder-dotnet/pull/4808

**Comment by mrivera-ms** [comment]
Per discussion with @gabog, this is not in scope for R13.

**Comment by mrivera-ms** [comment]
@gabog, @carlosscastro, please confirm if this is in scope for R14. Thank you.

**Comment by gabog** [comment]
@mrivera-ms, I don't think there's enough time to address this in R14, I would move it for R15.

**Comment by carlosscastro** [comment]
I would add it by default in R15 and we can pull it back if needed. I'll work on a nearby area, if I do I might bring it back.,

**Comment by tracyboehrer** [comment]
Already resolved elsewhere.
