### ISSUE TITLE
LUIS tracing uses obfuscated

### ISSUE THREAD

**Issue by chrimc62** [Microsoft/botbuilder-dotnet#481]
@cleemullins suggested this should be changed to be like QnA Maker where there is a specific trace record.

**Comment by cleemullins** [comment]
This looks as though it's no longer relevant:
https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Ai.LUIS/LuisTraceInfo.cs

Closing.
