### ISSUE TITLE
Enable developers to perform binary compatibility check on local machine

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#4810]
**Is your feature request related to a problem? Please describe.**
The only time to see if a dev's work passes the binary compat check is when they create a PR and wait for the appropriate job to trigger after the unit tests.

**Describe the solution you'd like**
The ability to run the binary compat check locally.

**Comment by mrivera-ms** [comment]
@JuanAr, this issue tracks the investigation in progress.
