### ISSUE TITLE
Main AdaptiveDialog dialog has an id "AdaptiveDialog" instead of resource.Id

### ISSUE THREAD

**Issue by Robulane** [microsoft/botbuilder-dotnet#4821]
## Version
4.10.0

## Describe the bug
The Id of the dialog that is loaded with LoadType method on resource explorer is "AdaptiveDialog".

## To Reproduce
1. Have some adaptive bot without the specified Id
2. Load the dialog:
var dialog =  resourceExplorer.LoadType<AdaptiveDialog>(resource)

dialog.Id equals "AdaptiveDialog"

## Expected behavior
dialog.Id should be the same as resource.Id

The behavior should be the same as in AdaptiveComponentRegistration.cs (line 171):
                var resourceId = Path.GetFileNameWithoutExtension(schema.Id);
                var resourceType = Path.GetExtension(resourceId).TrimStart('.').ToLowerInvariant();

                // load dynamic dialogs
                switch (resourceType)
                {
                    case "dialog":
                        // register foo.dialog as $kind
                        yield return new DeclarativeType<DynamicBeginDialog>(resourceId) { CustomDeserializer = new DynamicBeginDialogDeserializer(resourceExplorer, resourceId) };
                        break;
                }

**Comment by mrivera-ms** [comment]
@garypretty please triage and prioritize. Thank you.

**Comment by garypretty** [comment]
Looks like a straightforward issue to resolve.  Need to just confirm that changing the name of the loaded root dialog doesn't break anything else. Looks like a simple one to address in R12.

**Comment by feich-ms** [comment]
This `AdaptiveDialog` id only applies to the root dialog which is not referenced by other dialogs. All child dialogs are using resouce id as dialog id. So this is not a huge impact issue. We will take a fix soon.

**Comment by feich-ms** [comment]
I did more investigations and the conclusion is that when using `LoadType<Dialog>`, the root dialog id is set to resource id correctly if dialog id is not specifying in dialog file, but when using `LoadType<AdaptiveDialog>`, the root dialog id is automatically set to the dialog type `AdaptiveDialog` somehow. I can take a fix to make `LoadType<AdaptiveDialog>` return correct dialog id, but this fix will depend on the cycle detection issue fix which is tracked here https://github.com/microsoft/botbuilder-dotnet/issues/5021, so we will fix this only after https://github.com/microsoft/botbuilder-dotnet/issues/5021 is fixed.

**Comment by feich-ms** [comment]
@Robulane, currently please use `LoadType<Dialog>` rather than `LoadType<AdaptiveDialog>`. `LoadType<Dialog>` can load adaptive dialogs correctly.

**Comment by feich-ms** [comment]
Will be fixed bu this PR https://github.com/microsoft/botbuilder-dotnet/pull/5053
