### ISSUE TITLE
Surface Web Socket events and errors to clients that use bot framework sdk to manage socket connections

### ISSUE THREAD

**Issue by thehundred** [microsoft/botbuilder-dotnet#4835]
## Version
4.9.2

## Describe the bug
We have a bot that uses the bot sdk to manage the socket connections. We do that by calling the following code
await botFrameworkHttpAdapter.ProcessAsync(Request, Response, incomingBot);

When the websocket is disconnected for some reason, sending the activity over the socket should throw some exception. Currently we don't get any exception back.
This should throw exception if websocket is disconnected - await turnContext.SendActivityAsync(activity);

What would be really helpful is to allow clients to hook handlers to key websocket events like open, close, error

## To Reproduce
Try to send an activity from the bot out of turn when there is no websocket connection

## Expected behavior
SDK shold throw exception

**Comment by johnataylor** [comment]
related https://github.com/microsoft/botbuilder-dotnet/issues/4850

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. This should be addressed by the improvements @johnataylor is doing on Streaming. On track for R12.

**Comment by johnataylor** [comment]
In the latest CloudAdapter code the exception will cause the adapter's OnTurnError to be called. The socket is not part of the application programming model but the error handler can be implemented to provide logging.
