### ISSUE TITLE
RemoveRecipientMention() doesn't remove the Entity record.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#4841]
## Version

4.10.3

## Describe the bug

activity.RemoveRecipientMention() is supposed to remove a mention which targets the recipient (aka the bot). The bug is that it only removes the mention from the text, but not from the entity array.

## To Reproduce

Use Teams to send an activity to your bot using an @ mention for the bot.  You will get a payload like this:

```javascript
{
  "type": "message",
  "channelId": "msteams",
  "from": {
  	...
  },
  "conversation": {
	...
  },
  "recipient": {
    "id": "28:0047c760-1f42-4a78-b1bd-9ecd95ec3615",
    "name": "Tess"
  },
  "text": "\r\n<at>Tess</at> who created you?\r\n",
  "entities": [
    {
      "type": "mention",
      "mentioned": {
        "id": "28:0047c760-1f42-4a78-b1bd-9ecd95ec3615",
        "name": "Tess"
      },
      "text": "<at>Tess</at>"
    }
  ],
  ...
}
```

## Expected behavior

If you call activity.RemoveRecipientMention() it should

*   remove **\<at>Tess\</at>** from the activity.text
*   remove the { type:"mention"} record for that mention from the entities collection.

It currently modifies the Text, but does not remove the mention from the entities collection.

**Comment by johnataylor** [comment]
possibly related https://github.com/microsoft/botbuilder-dotnet/pull/4843

**Comment by mrivera-ms** [comment]
Reviewed with the SDK team. This was done in a prior milestone.
