### ISSUE TITLE
SkypeMentionNormalizeMiddleware only works for Skype, but Teams is built on skype and needs same support

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#4842]
## Version

4.10.3

## Describe the bug

1.  **SkypeMentionNormalizeMiddleware** attempts to normalize @ mention data structure but only does it for Skype channel. MSTeams is built on Skype and has same behavior. 
2.  **SkypeMentionNormalizeMiddleware** removes  \<at> \</at> from the entity.text, but doesn't do the same thing to the activity.text, and it should be doing both.

## To Reproduce

Send a @ mention to a bot.

The activity will look something like this:

```javascript
{
  "channelId": "msteams",
  "from": {
	...
  },
  "conversation": {
	...
  },
  "recipient": {
	...
  },
  "textFormat": "plain",
  "locale": "en-US",
  "text": "\r\n<at>Steve</at> do something\r\n",
  "entities": [
    {
      "type": "mention",
      "mentioned": {
        "id": "28:0047c760-1f42-4a78-b1bd-9ecd95ec3615",
        "name": "Steve Ickman
"
      },
      "text": "<at>Steve</at>"
    },
	...
  ],
   ...
}
```

Afterwards 

activity.text is unchanged (with _\<at>Steve\</at>_ )

entities\[0\].text is changed (with _"steve"_ )

## Expected behavior

1.  the mention data structure depends on the entity.text matching the activity.text.  The \<at> \</at> needs to be stripped from both places.
2.  It needs to do this for MSTeams channel as well as Skype

I think we should consider cloning this class to be "NormalizeMentionMiddleware" and deprecate the Skype class.

**Comment by EricDahlvang** [comment]
The SkypeMentionNormalizeMiddleware is not intended to remove the mention, but to force the pattern into what is expected by RemoveMentionText: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/ActivityExtensions.cs#L70
