### ISSUE TITLE
Add Skills Support to CloudAdapter

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#4853]
CloudAdapter and the new auth classes do not yet fully support Skills.

The current CloudAdapter does actually support proactive calls with ContinueConversation and the auth code does check for the skills audience, though this second part is not fully tested.

More specifically we need a new ChannelServiceHandler that doesn't depend on ICredentialProvider and IChannelProvider.

**Comment by mrivera-ms** [comment]
Closing as Done.
