### ISSUE TITLE
LanguageGeneratorExtensions.UseLanguageGeneration GC root / memory leak

### ISSUE THREAD

**Issue by jamesemann** [microsoft/botbuilder-dotnet#4871]
#### Background

There is an issue when using `LanguageGeneratorExtensions.UseLanguageGeneration` at scale since it uses a static dictionary to store lg managers. 

See https://github.com/microsoft/botbuilder-dotnet/blob/f55bbc3f19ca874dceebb59c3ffcb31688f141b4/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGeneratorExtensions.cs#L63

and 

https://github.com/microsoft/botbuilder-dotnet/blob/f55bbc3f19ca874dceebb59c3ffcb31688f141b4/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguageGeneratorExtensions.cs#L17

This is a GC root so this and any objects in it are never released from memory and over time in a multi tenanted environment this eventually leads to out of memory issues. 

We have worked around it by providing our own copy of the behaviour which does not cache. Would it be possible to add an additional parameter to indicate whether or not to cache the lg managers?

**Comment by boydc2014** [comment]
@tomlm how about we add a parameter for caching, and default turn it false?

**Comment by tomlm** [comment]
or use MemoryCache instead of dictionary.

**Comment by mrivera-ms** [comment]
@boydc2014 please add options for fixes and ETA. Please also add tests.

**Comment by Danieladu** [comment]
What about using [ConditionalWeakTable](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=netcore-3.1)

**Comment by boydc2014** [comment]
@mrivera-ms there are several options, like adding a parameter, or using a different data Structure.  I will get some time down next week with Tom and Hongyang to pick a good solution. 

The solution would be ready probably one week after that. The fix should be obvious (once we decided), but i suspect the tests would take some time to make a proper test against memory leak.

**Comment by jamesemann** [comment]
@boydc2014 Please feel free to tag me on this PR when ready and I can test the memory leak

**Comment by Danieladu** [comment]
@jamesemann Feel free to test the PR. Thanks.

**Comment by boydc2014** [comment]
@jamesemann  can you try the PR above https://github.com/microsoft/botbuilder-dotnet/pull/4916

**Comment by jamesemann** [comment]
Will do and report back asap

**Comment by Danieladu** [comment]
@jamesemann  Is there any update on the test?

**Comment by jamesemann** [comment]
@Danieladu not yet - will update today or tomorrow

**Comment by boydc2014** [comment]
ping @jamesemann  ~

**Comment by jamesemann** [comment]
Apologies @boydc2014 I have not been able to try the fix yet. Will prioritize and report back

**Comment by jamesemann** [comment]
Apologies for the delay - have tested my use case with solution 1 and it seems to be better. Will update the issue with some supporting data this week

**Comment by mrivera-ms** [comment]
@jamesemann, are there any updates on this? Can we close this issue as resolved?

**Comment by jamesemann** [comment]
@mrivera-ms yes I can confirm it is working and I am not seeing the same memory consumption. When I have a spare moment I will add the profiling details to this issue for reference.  Thank you all!

**Comment by mrivera-ms** [comment]
Great news. Thank you @jamesemann!
