### ISSUE TITLE
Facebook One-time Notification

### ISSUE THREAD

**Issue by sombe** [microsoft/botbuilder-dotnet#4873]
Hello,
from the recent documentation on Facebook we found out that it's allowed to send a one time notification after the 24hrs window if the user has given his permission.
https://developers.facebook.com/docs/messenger-platform/send-messages/one-time-notification

For sending such proactive message we should set in the API call the token gathered from the user, in the following way:

```json
"recipient": {
  "one_time_notif_token":"<ONE_TIME_TOKEN>"
}
```

We tried to add this value in channelData like we did for example for notification_type, but it seems that the recipient value is being ignored when sending the request to Facebook, and it returns a 400 Bad Request error ("This message is sent outside of allowed window.").
I cannot be sure that the value is being ignored though, because I didn't find a way to inspect the real JSON body sent to the Facebook API.
This is the code we tried (C#):

```c#
var reply = context.Activity.CreateReply("Notification");

reply.ChannelData = JObject.FromObject(
    new
    {
        recipient = new
        {
            one_time_notif_token = token,
        },
        notification_type = "REGULAR",
    });

await context.SendActivityAsync(reply);
```

For now we're sending the notification by calling Facebook API natively, but is there a way to achieve this with Bot Builder or is there any chance that will be added as a feature?

Thank you.

**Comment by v-kydela** [comment]
@sombe - Facebook is a third-party channel, and it's unlikely that the Bot Builder SDK will be updated to have built-in support for more Facebook Messenger features. However, the Bot Builder SDK does have a Facebook adapter. Have you tried that?

**Comment by v-kydela** [comment]
@sombe - Are you still working on this?

**Comment by sombe** [comment]
Hello @v-kydela,
yeah sorry for the delay. We've seen the Facebook adapter but One-time Notification would be the only feature that would force us to use the dedicated adapter. Given what has been done for the notification_type we thought there was a possibility for this too, but since you pointed out that this will unlikely happen, we will continue calling the API natively.

Thank you for the clarification.
