### ISSUE TITLE
OAuthInput throws when turn.activity.text is null

### ISSUE THREAD

**Issue by lucaism** [microsoft/botbuilder-dotnet#4875]
## Version
4.10.5

## Describe the bug
In msteams, when an OAuthInput dialog is active and waiting for user input, if the user submits a response that is not an auth token and has a `null` value for `turn.activity.text`, then OAuthInput will throw with the following exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Input.OAuthInput.RecognizeTokenAsync(DialogContext dc, CancellationToken cancellationToken)
```

I believe this is due to a missing null check when [checking the message input for the presence of a magic code](https://github.com/microsoft/botbuilder-dotnet/blob/3514f26dcb6fee93a86a089ec8db08da9df55ca3/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L390).
## To Reproduce
Write an AdaptiveDialog containing any OAuthInput, for example:
```
new OAuthInput
{
    ConnectionName = this.connectionName,
    Text = "Before I can perform this operation, I need permission to validate your identity.",
    Title = "Sign-in required",
    Property = "$authToken",
    InvalidPrompt = new ActivityTemplate("Sorry, please try again."),
    AllowInterruptions = "turn.recognized.intent == 'Cancel' || turn.recognized.intent == 'Help'"
},
```

Run the bot in msteams, and trigger the auth input dialog. When the "Sign-in required" button shows up in Teams, instead of clicking on it, submit a message that would result in a `null` value for `turn.activity.text`. There are several ways to do this:
- Click a button on an adaptive card (not the sign-in button) that sends an empty text value, for example:
```
{
    "type": "Action.Submit",
    "title": "Title",
    "data": {
        "msteams": {
            "type": "messageBack",
            "displayText": "nothing much",
            "text": "",
            "value": {"InputSource": "MyCard"}
        }
    }
}
```
- Send a Teams emoji with no additional text
- Use the rich text editor in Teams, select the 'quoted message' option, then send an empty quote box

## Expected behavior
The OAuthInput should display its `InvalidPrompt` message and re-prompt the user (if `MaxTurnCount` has not been reached).

As an aside, the `Validations` property inherited from `InputDialog` does not seem to be implemented in `OAuthInput`, so it is not possible to add a validation checking if `turn.activity.text` is `null`.

**Comment by Zerryth** [comment]
@lucaism looking into this. Currently I have a bot plugged into Teams that shows me the OathInput prompt, however currently it doesn't even do anything  even if I do something standard as clicking it...

![image](https://user-images.githubusercontent.com/35248895/97771979-8c6f0200-1aff-11eb-9d15-b208f17b2fff.png)
^ stays frozen there

Could you share more code with me, please, such as what action(s) you take after you prompt using the OAuthInput?

**Comment by Zerryth** [comment]
Actually, nvm, managed to get it unfrozen. For some reason when I was running the bot in VS Code rather than VS it would run the bot, but wouldn't do anything once I clicked the Sign-in button (problem to investigate later...)

**Managed to reproduce error @lucaism reported.**

![image](https://user-images.githubusercontent.com/35248895/97914228-6c5c6000-1d04-11eb-81a0-6dcbf62ea254.png)


```
Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter: Error: Exception caught : Value cannot be null. (Parameter 'input')
```

I'll discuss with the team what the next steps here should be. Thank you for raising the issue

**Comment by Zerryth** [comment]
Also yes, it does break in the place you described in your original post in `OAuthPrompt.RecognizeTokenAsync`:

![image](https://user-images.githubusercontent.com/35248895/97915031-a4b06e00-1d05-11eb-8b93-6b53e03bc921.png)
