### ISSUE TITLE
Request to add grouping information to the expression functions in the adaptive-expressions package

### ISSUE THREAD

**Issue by LouisEugeneMSFT** [microsoft/botbuilder-dotnet#4878]
When interacting with a field that supports adaptive expression functions in Composer, we would like to be able to show the list of available functions when initially placing the cursor on the field, such as this:

![image](https://user-images.githubusercontent.com/66701106/97509462-9944f780-193f-11eb-8c6e-5a3e38a73d56.png)

The functions would be grouped by category (eg: String, Collection, etc..), such as specified in the following documentation:
https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0

The request would be to add this grouping information in the adaptive-expressions package for consumption in Composer.

**Comment by cosmicshuai** [comment]
Will look into how language server protocol can provide multi-level suggestions based category. I'd like to suggest this in the Composer Language server side rather than in the Adaptive-Expressions.

**Comment by mrivera-ms** [comment]
@darrenj please prioritize and add the customer impact.

**Comment by boydc2014** [comment]
@mrivera-ms i'm not sure how this could be technically implemented, what we offer is a library containing a list of expressions, and we don't have a mechanism to expression function type as a library.  This should be a Composer issue, which use a table to store the grouping.

**Comment by LouisEugeneMSFT** [comment]
@cosmicshuai, Intellisense currently has a _**completionListOverride**_ functionality to inject any custom component in the Intellisense menu and override the default behavior. This logic is client side. The purpose of this functionality is to handle any non traditional Intellisense interaction (aka any UI that is different from a simple list of completion results). It is currently used to show "Start typing _type_ or write an expression" when you place your cursor on an empty field accepting an expression. I was planning to use this mechanism to show the nested menu displayed in the shared design.

@cosmicshuai, @boydc2014, regardless of how this data is consumed, my goal with this request is to have a single source of truth for this grouping logic. It is technically feasible to hardcode this in Composer but I want to avoid that route. For example, I see that the functions and groupings under: https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0 change somewhat frequently. Those changes should be in sync with whatever information we surface in Composer. It could be through the adaptive expression package or anything else as long as we maintain single source of truth.

**Comment by chrimc62** [comment]
This seems like a prime candidate to be expressed in .uischema.  Why isn't that the right place to have this?

**Comment by LouisEugeneMSFT** [comment]
@chrimc62, this would be about grouping the functions of the adaptive expressions language (eg: add, max, min -> Math, length, split -> String, etc..). My understanding is that the uiSchema helps with customizing the ui for the different components already present in the main sdkSchema ("Microsoft.Ask", "Microsoft.AttachmentInput", etc.. ). Could you explain a bit more how you think grouping functions in the uiSchema would work?
