### ISSUE TITLE
Component Schema for actions is overly constrained & ActionScope needs a non-list check

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4900]
Today the Adaptive component schemas that model actions are set as required when they do not need to be. This confuses authoring canvases like Composer or PVA who throw errors based on these policies. 

Additionally, ActionsScope has the potential to accept a non-list item like `null` and break the runtime.

## Description
We currently require actions to be set in schema, but the code is not robust to actions being set to null. 

## Specific Changes
- Change ActionScope to deal with null assignment as the same as empty array.
- remove required "actions" constraint on triggers, IfCondition, ForEach schema definitions.

**Comment by mrivera-ms** [comment]
@garypretty please prioritize and add any needed information.
