### ISSUE TITLE
Support multi-line expression in Object/Array definition

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#4901]
reported by @Stevenic 

## Describe the bug
Currently, the multiline expression is not supported in such format:
```
# template
- ${{
    key: "value"
}}
```

this should work

**Comment by mrivera-ms** [comment]
@Danieladu please add more details. Include specific information about what you want to be done. Please clean up the template text from the description.

**Comment by Danieladu** [comment]
Sure. Currently, I could not reproduce this issue. I would sync with the questioner to get more context.
