### ISSUE TITLE
[DCR] Further simplify the usage of expression in declarative dialogs

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#4905]
## Context

Starting from https://github.com/microsoft/botbuilder-dotnet/pull/3253, the notion of "=" is introduced to force an expression, which simplified the usage of expression in declarative dialogs. It made the parsing and validation easy, whenever a starting "=" is met, we know the content following should be parsed and validated as an expression. 

## Issue
In the case of a value starts with a "=", it's quite clear. But in the case of not starting with "=", it's still a little bit indirect and sometime can be very confusing. 

For example, in the case of boolExpression 
```
| Input           | Result        |
|-----------------|---------------|
| true            | true          |
| "true"          | true          | 
| "=true"         | true          |
| "user.age > 3"  | true          | // case 4: here is the case make things complicated
| "=user.age > 3" | true          |
| "bad"           | default(bool) | // case 6
| "bad @{bad}"    | default(bool) |
```
The support of case 4 and case 6 is what make things tricky and confusing to some extent. The treatment here is, if the value not starts with "=", we are still trying to parse and evaluate that as an expression, if it's parsed and evaluated correctly, it will still works. 

**So, as a summary, "=" is not the single way to do expression. You can use "=" or write a valid expression.** 

## Proposal

The proposal here, is to **make "=" the only way to do expression**.  More specifically, in any expression, either use "=" to start an expression, or input a literal here (with only one exception in stringExpression case, which we support string intepolation).

For example,  in boolExpression
```
| Input           | Result        |
|-----------------|---------------|
| true            | true          |    
| "true"          | true          | // this is not technically exact a "literal", but to user concept it is a literal
| "=true"         | true          |
| "user.age > 3"  | default(bool) | // sorry, not supported anymore, invalid expresion
| "=user.age > 3" | true          |
| "bad"           | default(bool) | // invalid expresion
| "bad @{bad}"    | default(bool) | // invalid expresion
``` 
in intExpression
```
| Input                | Result       |
|----------------------|--------------|
| 13                   | 13           |
| "13"                 | 13           |
| "=13"                | 13           |
| "x.y.z"              | default(int) | // sorry, not supported anymore, invalid
| "=x.y.z"             | 13           |
| "Hello world"        | default(int) | // invalid expresion
| "Hello @{user.name}" | default(int) | // invalid expresion
```

**Comment by boydc2014** [comment]
This is capturing the discussion in Composer standup, cc @GeoffCoxMSFT @cwhitten . 

@tomlm @chrimc62 @Stevenic what do you guys think?

**Comment by mrivera-ms** [comment]
@darrenj please prioritize, customer impact.

**Comment by tomlm** [comment]
I don't think this makes sense.  Are you really suggesting it's better for booleans where it is unamibious to have to put = on the front? IfCondition() and OnTrigger.Condition in partular.
```
{ 
   "$kind":"Microsoft.IfCondition",
    "condition": "=user.Age > 3 && user.age < 15 "
  ..
}
```
```
{ 
   "$kind":"Microsoft.IfCondition",
   "condition": "user.Age > 3 && user.age < 15 "
  ..
}
```
Same for all triggers?
```
{ 
   "$kind":"Microsoft.OnIntent",
    "condition": "=user.Age > 3 && user.age < 15 "
  ..
}
```
```
{ 
   "$kind":"Microsoft.OnCondition",
   "condition": "user.Age > 3 && user.age < 15 "
  ..
}
```
There is no interpretation of that string that shouldn't be a bool.
