### ISSUE TITLE
Azure Tests Fail in Fresh Clone of botbuilder-dotnet 

### ISSUE THREAD

**Issue by Zerryth** [microsoft/botbuilder-dotnet#4907]
What package version of the SDK are you using.
4.10.3

## Describe the bug
Getting a fresh clone of botbuilder-dotnet and running tests results in failing tests.
Specifically in `Microsoft.Bot.Builder.Azure.Tests`

![image](https://user-images.githubusercontent.com/35248895/97919680-0d4f1900-1d0d-11eb-88c1-8344cf03a16b.png)

## To Reproduce
- `git clone https://github.com/microsoft/botbuilder-dotnet.git` (We're on `main` branch)
- Build the repo (`Microsoft.Bot.Builder.sln`)
- Run all unit tests

## Expected behavior
For all unit tests in dotnet repo to run successfully

**Comment by mrivera-ms** [comment]
@Zerryth please add more details to this bug, including repro steps and diagnosis.

**Comment by Zerryth** [comment]
@mrivera-ms repro steps are there already, however I will take time to look into why exactly the tests are failing, and try to add more detail to the repro steps--this is off `main` branch, which I did fail to mention.

I'm not super experienced in the botbuilder Azure bits of the repo, so I don't exactly know what's wrong from a surface level from the errors given:

## Failing Tests

### **TranscriptStoreBaseTests.cs  - Microsoft.BotBuilder.Azure (netcore2.1)**

![image](https://user-images.githubusercontent.com/35248895/98020599-10ebaa00-1db8-11eb-835d-b9283bc23db1.png)

**LogUpdateActivities()**
```
 Microsoft.Bot.Builder.Azure.Tests.BlobsTranscriptStoreTests.LogUpdateActivities
   Source: TranscriptStoreBaseTests.cs line 257
   Duration: 2.9 sec

  Message: 
    System.Collections.Generic.KeyNotFoundException : The given key 'Timestamp' was not present in the dictionary.
  Stack Trace: 
    Dictionary`2.get_Item(TKey key)
    BlobsTranscriptStore.GetTranscriptActivitiesAsync(String channelId, String conversationId, String continuationToken, DateTimeOffset startDate) line 178
    BlobsTranscriptStore.GetTranscriptActivitiesAsync(String channelId, String conversationId, String continuationToken, DateTimeOffset startDate) line 174
    TranscriptStoreBaseTests.LogUpdateActivities() line 289
    --- End of stack trace from previous location where exception was thrown ---

```

**TestDateLogUpdateActivities()**
```
 Microsoft.Bot.Builder.Azure.Tests.BlobsTranscriptStoreTests.TestDateLogUpdateActivities
   Source: TranscriptStoreBaseTests.cs line 299
   Duration: 10.4 sec

  Message: 
    System.Collections.Generic.KeyNotFoundException : The given key 'Timestamp' was not present in the dictionary.
  Stack Trace: 
    Dictionary`2.get_Item(TKey key)
    BlobsTranscriptStore.GetTranscriptActivitiesAsync(String channelId, String conversationId, String continuationToken, DateTimeOffset startDate) line 178
    BlobsTranscriptStore.GetTranscriptActivitiesAsync(String channelId, String conversationId, String continuationToken, DateTimeOffset startDate) line 174
    TranscriptStoreBaseTests.TestDateLogUpdateActivities() line 334
    --- End of stack trace from previous location where exception was thrown ---

____

```
### **TranscriptStoreBaseTests.cs  - Microsoft.BotBuilder.Azure (netcore3.1)**

**LogDeleteActivities()**
```
 Microsoft.Bot.Builder.Azure.Tests.BlobsTranscriptStoreTests.LogDeleteActivities
   Source: TranscriptStoreBaseTests.cs line 355
   Duration: 1.8 sec

  Message: 
    Assert.Equal() Failure
    Expected: 3
    Actual:   0
  Stack Trace: 
    TranscriptStoreBaseTests.LogDeleteActivities() line 384
    --- End of stack trace from previous location where exception was thrown ---

```
___

I'll dig into the errors further and can update the issue once I understand what they mean

**Comment by Zerryth** [comment]
Now that I'm looking into this, it seems the breaking tests have been resolved. 🤷 
Woohoo, less work for me 😁
