### ISSUE TITLE
Audio cards don't work with on the consumer

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#4908]
Audio cards don't play on the parent when the skill returns an audio card. The audio car does play if you talk to the skill directly.

**Steps**
1. Use the card bot located [here](https://github.com/microsoft/BotFramework-FunctionalTests/tree/josh/bots/Bots/DotNet/Skills/CodeFirst/CardSkillBot) to azure
2. Update the app id and password
3. Deploy card bot to azure
4. Update the app id, password, and skill app id
5. Deploy the parent bot located [here](https://github.com/microsoft/BotFramework-FunctionalTests/tree/josh/bots/Bots/DotNet/Consumers/CodeFirst/SimpleHostBot)
6. Open the parent in the "test in webchat"
7. Send the message `skill`
8. Send the message `audio` 
9. Click the play button

**Result**
Nothing happens 

**Note**
If you open the skill in webchat, send it `audio` and click the play button it works

**Comment by mrivera-ms** [comment]
@Virtual-Josh thank you for reporting it. Please add details including analysis and clear steps for repro. Thank you.

**Comment by Virtual-Josh** [comment]
I've updated the repro steps and linked to the bots used that are now in the new file structure. Let me know if you need any additional information.

**Comment by EricDahlvang** [comment]
This is probably because the url here is hard coded to local:

https://github.com/microsoft/BotFramework-FunctionalTests/blob/josh/bots/Bots/DotNet/Skills/CodeFirst/CardSkillBot/CommandHandler.cs#L145

```cs
        private static AudioCard MakeAudiocard()
        {
            MediaUrl url = new MediaUrl(url: "http://localhost:39783/api/bell");
            return new AudioCard(title: "Audio Card", media: new[] { url }, autoloop: true);
        }
```

**Comment by Virtual-Josh** [comment]
Ahh, good point. Let me try with the deployed url.

**Comment by mrivera-ms** [comment]
@Virtual-Josh I am assigning this back to you. Please verify if the root cause is the hard coded value in the test bot and if it is, please close. If not, you can continue the investigation. Thank you.

**Comment by Virtual-Josh** [comment]
Fixing the url & publishing the files was the fix. Thanks @EricDahlvang.
