### ISSUE TITLE
Microsoft.Bot.Builder.Azure does not work with latest Microsoft.Azure.Cosmos library

### ISSUE THREAD

**Issue by yoPCix** [microsoft/botbuilder-dotnet#4909]
Currently `Microsoft.Bot.Builder.Azure` points to `Microsoft.Azure.Cosmos` package version 3.2.0, which is 1 year old. If I upgrade my project dependency for `Microsoft.Azure.Cosmos` to its latest version 3.14.0, bot framework throws an exception:

```
Method not found: ‘System.Threading.Tasks.Task1<Microsoft.Azure.Cosmos.ContainerResponse> Microsoft.Azure.Cosmos.Fluent.ContainerBuilder.CreateIfNotExistsAsync(System.Nullable1<Int32>)’.; Inner: ; 
at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.CreateContainerIfNotExistsAsync()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.CreateContainerIfNotExistsAsync()
at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.InitializeAsync()
at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.ReadAsync(String[] keys, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotState.LoadAsync(ITurnContext turnContext, Boolean force, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotState.BotStatePropertyAccessor1.GetAsync(ITurnContext turnContext, Func1 defaultValueFactory, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.Dialogs.DialogSet.CreateContextAsync(ITurnContext turnContext, CancellationToken cancellationToken)
...

```

**Comment by yoPCix** [comment]
A new parameter `CancellationToken cancellationToken = default` was added to `Microsoft.Azure.Cosmos.Fluent.ContainerBuilder.CreateIfNotExistsAsync` method in version 3.11.0

**Comment by mdrichardson** [comment]
@yoPCix What version of `Microsoft.Bot.Builder.Azure` are you running? I was able to update to `Microsoft.Azure.Cosmos` v3.14.0 just fine. If the only change to that method was adding the `CancellationToken cancellationToken = default` parameter, there shouldn't be any issues because that parameter is optional.

Can you share your `CosmosDbPartitionedStorageOptions`? (please obfuscate the keys)

**Comment by yoPCix** [comment]
I am running `Microsoft.Bot.Builder.Azure` v4.10.3

Setup is pretty straightforward.

```cs
builder.Register(ctx =>
{
    //https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0
    return new CosmosDbPartitionedStorage(
        new CosmosDbPartitionedStorageOptions
        {
            CosmosDbEndpoint = Configuration.GetValue<string>("CosmosDbUri"), // https://******.documents.azure.com:443/
            AuthKey = Configuration.GetValue<string>("CosmosDbKey"),
            DatabaseId = Configuration.GetValue<string>("CosmosBotStorageDbName"), // BotStorage
            ContainerId = Configuration.GetValue<string>("CosmosBotStorageDbCollection"), // StateDEVv4
            CompatibilityMode = false,
        });
})
.As<IStorage>()
.SingleInstance();

**Comment by mdrichardson** [comment]
@yoPCix I was only able to replicate this if I had *both* of these packages:

* Microsoft.Bot.Builder.Azure
* Microsoft.Azure.Cosmos

Is there a reason you have the `Microsoft.Azure.Cosmos` package in addition to `Microsoft.Bot.Builder.Azure`? You should only need `Microsoft.Bot.Builder.Azure`.

Again, if I actually modify the `Microsoft.Bot.Builder.Azure` package and update it's dependency to use the latest `Microsoft.Bot.Builder.Azure`, without also installing a separate `Microsoft.Bot.Builder.Azure` package, everything works just fine.

**Comment by yoPCix** [comment]
We have an internal library that is using `Microsoft.Azure.Cosmos` and we wanted to upgrade to the latest version, which caused the error. Of course for now we will downgrade that version to 3.10.1 which works OK.
I guess this issue still stands as `Microsoft.Bot.Builder.Azure` should work with the latest version.
Considered creating a pull request for this package update, but I'm getting too many test errors (probably unrelated to the actual change) that I don't feel confident enough and I can't invest time in making all tests to pass.

**Comment by mdrichardson** [comment]
@yoPCix Gotcha. I'll put in a PR to upgrade the `Microsoft.Azure.Cosmos` version within `Microsoft.Bot.Builder.Azure`. However, we're about to push a new release and I don't believe this will make it in until the next one, just FYI.
