### ISSUE TITLE
[SlackAdapter] Bot receives additional event call back when sends message/attachment to the user. 

### ISSUE THREAD

**Issue by Anshul21** [microsoft/botbuilder-dotnet#4920]
## Version
4.10
## Describe the bug
I am using SlackAdapter. Everytime bot sends a message/attachment to the user, it receives an "event_callback" which is breaking the dialog flow.  
## To Reproduce
1. use the bot sample for SlackAdapter
2. Create a dialog flow .. MainDialog >>> AskQuestion dialog. 
3. Send a blockkit card to ask user a question. 
4. Press on a button. 
5. Card rendering will send an additional event which would break the flow of dialog and bot would exit out of the dialog state
## Expected behavior
when bot sends an attachment to user. it shouldn't get an event callback.

**Comment by Anshul21** [comment]
@mrivera-ms any update on this?

**Comment by denscollo** [comment]
Hi @Anshul21 ,

We followed the steps but we couldn't reproduce this issue.
We added a dialog flow to the sample and included a block kit step in the middle, but clicking the buttons didn't interrupt the dialog, and we couldn't identify any event_callback when sending messages/attachments.

Could you share with us the code you are having the issue with? 

Another thing that might be causing this, can be the Slack APP event subscription configuration, so we could help you reviewing that as well.  

Thanks

**Comment by Anshul21** [comment]
hi @denscollo  Thanks for looking into this, i am the lead engineer at LinkedIn's employee productivity team, we can setup some time next week and i can walk you through the code and the app set-up. Feel free to ping me on teams ( ansharma <at> linkedin dot com> and we can set up a meeting

Thanks
Anshul

**Comment by denscollo** [comment]
Hi @Anshul21 , we'll be sending you an email to set up a meeting and review this. Thanks!

**Comment by joshgummersall** [comment]
@denscollo can you provide an update on this issue? Should it be closed?

**Comment by denscollo** [comment]
Hi @joshgummersall, we found a workaround for this issue and we are waiting for the user's confirmation that it works. Thanks!

**Comment by mrivera-ms** [comment]
Per offline conversation with @Anshul21 and @denscollo, this issue is resolved.
