### ISSUE TITLE
implement IExtendedUserTokenProvider for CloudAdapter 

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4922]
**Is your feature request related to a problem? Please describe.**

For current [CloudAdapter](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/CloudAdapter.cs), it doesn't implement IExtendedUserTokenProvider.

So we can't use OAuthPrompt in this adapter.

**Comment by johnataylor** [comment]
The OauthPrompt needs refactoring so it doesn't depend on IExtendedUserTokenProvider which is a design we won't be taking forward. This work, along with the adapter level logic is being tracked with https://github.com/microsoft/botbuilder-dotnet/issues/4851
