### ISSUE TITLE
Missing docs on enabling OAuth for bot in non-public azure

### ISSUE THREAD

**Issue by swagatmishra2007** [microsoft/botbuilder-dotnet#4924]
## Version
What package version of the SDK are you using.
N/A
## Describe the bug
Give a clear and concise description of what the bug is.
For a bot to use OAuthPrompt in non-public azure clouds (like gov ), the following lines of code need to be added for a c# bot, startup.cs 
string uri = "https://api.botframework.azure.us";
            MicrosoftAppCredentials.TrustServiceUrl(uri);
            OAuthClientConfig.OAuthEndpoint = uri;
However, this is not documented at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp and hence a bot developer would not know how to configure OAuth for a non-public cloud bot.

## Expected behavior
Give a clear and concise description of what you expected to happen.
The docs at the above link should be updated with these steps, so as to guide a bot developer in this scenario

**Comment by JonathanFingold** [comment]
Tracking in [bot-docs PR 1954](https://github.com/MicrosoftDocs/bot-docs/issues/1954), assigned to @mmiele.

**Comment by mrivera-ms** [comment]
@JonathanFingold is this on track for R12?

**Comment by mmiele** [comment]
These are the articles where we talk about private cloud as it applies to government cloud:

•	[Connect a bot to the Web Chat channel - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat) 
•	Compliance in Azure Bot Service - Bot Service 
•	Bot Framework Frequently Asked Questions Index - Bot Service 
•	Bot Framework Ecosystem Frequently Asked Questions - Bot Service 
•	Bot review guidelines - Bot Service

**Comment by mrivera-ms** [comment]
@JonathanFingold if the issue you linked ([bot-docs PR 1954](https://github.com/MicrosoftDocs/bot-docs/issues/1954)) is tracking this work. Do we need this issue? Should we close it as duplicate?

**Comment by mmiele** [comment]
@mrivera-ms Let's live this issue open because is linked by the  [bot-docs PR 1954](https://github.com/MicrosoftDocs/bot-docs/issues/1954) until some viable solution is found.

**Comment by mrivera-ms** [comment]
@mmiele, @JonathanFingold, is there an estimation of the time this will take to complete. Right now it is tagged as on target for R12. If it is not be done within the R12 timeframe, we need to move it out of the milestone.

**Comment by mmiele** [comment]
Related  PR https://github.com/MicrosoftDocs/bot-docs-pr/pull/2585 ready to be merged.

**Comment by JonathanFingold** [comment]
@mrivera-ms With the caveat that the publishing pipeline has been down for over a week, but [in theory] scheduled to come back up today, we are on track.

**Comment by mrivera-ms** [comment]
@JonathanFingold, is this item complete? Please update status. Thank you.

**Comment by mrivera-ms** [comment]
@JonathanFingold, please update status. Thank you.

**Comment by JonathanFingold** [comment]
The fix is in place and live in the docs.
