### ISSUE TITLE
JsonReaderException when deserializing Slack payload to the InteractionPayload model

### ISSUE THREAD

**Issue by gabemilani** [microsoft/botbuilder-dotnet#4926]
## Version
Microsoft.Bot.Builder 4.10.3
## Describe the bug
`JsonReaderException` when deserializing Slack payload to the `InteractionPayload` model.

**Problem**: `Newtonsoft.Json.JsonReaderException` at `Newtonsoft.Json.JsonTextReader.ReadStringValue`
**Message**: Unexpected character encountered while parsing value: {. Path 'state', line 1, position 4505. 

i.e. exception is thrown when a user selects an option from the Slack static select element. 

Slack sends a dictionary of objects on `state` property and the Slack adapter library is trying to deserialize to a string. 
Slack API reference: https://api.slack.com/reference/interaction-payloads/block-actions#fields
`Microsoft.Bot.Builder.Adapters.Slack.Model.InteractionPayload` class has the `State` property as a string property.

## To Reproduce
1. Create a chatbot project using the [Microsoft.Bot.Builder.Adapters.Slack.SlackAdapter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.adapters.slack.slackadapter?view=botbuilder-dotnet-stable)
2. Configure the Slack app: set the Interactivity request URL to your chatbot endpoint
3. Post a message to Slack using the `StaticSelectElement`
4. Select an option from the select element
5. See the error happening on `adapter.ProcessAsync`

## Expected behavior
Deserialize the model properly and send the activity to the `ActivityHandler`

**Comment by v-kydela** [comment]
Thank you for the report, @gabemilani 

I'm having trouble following your repro steps. Could you provide a bit more information about how to reproduce the problem? What is a `StaticSelectElement`?

**Comment by gabemilani** [comment]
Hello @v-kydela 
The `StaticSelectElement` is a class from the dependency library `SlackAPI`. Here you can find more information about it: https://api.slack.com/reference/block-kit/block-elements#static_select
Whenever I use this and select an option the `SlackAdapter` throws an exception while trying to process the request.

**Comment by v-kydela** [comment]
@gabemilani - Thank you for the link. I've found the source code [here](https://github.com/Inumedia/SlackAPI/blob/master/SlackAPI/Block.cs#L123-L132), but can you elaborate a bit more by showing a code example of an actual static select element and how you're posting it to Slack?

**Comment by gabemilani** [comment]
Here is a example:
```
var blocks = new List<IBlock>()
{
    new SectionBlock
    {
        text = new Text
        {
            type = "mrkdwn",
            text = "Select a fruit"
        }
    },
    new ActionsBlock() 
    {
        elements = new [] 
        { 
            new StaticSelectElement
            {
                placeholder = new Text { type = "plain_text", text = "Fruit" },
                action_id = "select-fruit",
                options = new [] {
                    new Option
                    {
                        text = new Text { type = "plain_text", text = "Apple" },
                        value = "select-fruit|apple"
                    },
                    new Option
                    {
                        text = new Text { type = "plain_text", text = "Orange" },
                        value = "select-fruit|orange"
                    }
                }
            }
        }
    }
};
```
Send a post request to the following API URL https://api.slack.com/methods/chat.postMessage#arg_blocks with that blocks payload

**Comment by gabemilani** [comment]
Now it's happening with `ButtonElement` too. 
A quick fix is to change the property `state` from the `InteractionPayload` class to an `object` instead of a `string`.

**Comment by v-kydela** [comment]
@gabemilani - I have reproduced the error and I'm working on a fix

**Comment by gabemilani** [comment]
That's great! Would you know a prediction of when this will be released?
Let me know if I can help with anything else. Thanks for your work @v-kydela !

**Comment by v-kydela** [comment]
@gabemilani - The PR is awaiting a code owner review
