### ISSUE TITLE
Pre & Post Activity Triggers

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#4928]
I am using Composer to built bots. Many bots that we build rely heavily upon authentication and session management. This could be like limiting the session of a user to 15mins after inactivity or checking a user database every 5 minutes etc..

In order to have a flexible solution it would be great to have a Pre Activity and Post Activity trigger that can be used in the root dialog to handle checks like these. The triggers should be called from the root or any other child dialog and after execution continue where the bot was at. Currently the only way to get this to work is using custom middleware, but that seems over the top for functionality that can be easily build in Composer itself.

The Pre and Post activity triggers should not override other triggers, but really be additional pre and post triggers.

For more information the following issue might help:
https://github.com/microsoft/BotFramework-Composer/issues/3379#issuecomment-722423896

**Comment by cwhitten** [comment]
@darrenj POR is to funnel these into PgM for discussion & prioritization, so assigning you for now.

**Comment by garypretty** [comment]
Labelled with backlog so that we can consider this in future milestone planning.

**Comment by mrivera-ms** [comment]
@boydc2014, could you please comment on this?

**Comment by boydc2014** [comment]
Yes, looks like it can be useful and also might be easy to implement a simple version. But, just so we know, there are probably more efforts than expected to have it's well implemented. The most tricky part to me is what's the impact on those two special triggers, a few questions like the following have to be answered
* should we allow any actions in this trigger without restrictions? Can you send another activity in a pre-activity trigger? 
* if so, the activity inside those two triggers, will they still have pre/post activity triggers? 
* should we allow inputs in a PostActivity trigger, which might diverge the conversation into another flow? same issue with beginDialog and some goto actions

The above is not a full list on the considerations, just to clarify the message that, we need to have a more detailed design that can help settle down those two special triggers' positioning and expectations, before moving to implementations.

**Comment by garypretty** [comment]
Thanks @boydc2014  @mrivera-ms.  I marked this as a backlog item to consider in a future milestone, especially as some work we are going in R12 (action policies) will have a direct impact on the questions posed above.

I think we should park this for now.  Please assume any items marked as backlog and not assigned into a release are going to be considered for a future milestone.  My plan is to use that label to assess the list ahead of work for R13 / R14 and so on.

**Comment by mrivera-ms** [comment]
@cxbuilders, thank you for the request. We will take this in a future release.
