### ISSUE TITLE
Bot Framework Fails to Create CosmosDb Container in Serverless Mode

### ISSUE THREAD

**Issue by don4of4** [microsoft/botbuilder-dotnet#4934]
## Version
4.10.3

## Describe the bug
This bug is straightforward -- the cosmos connector does not work on the new serverless SKU, which is unfortunate.

## To Reproduce
1.Create a serverless Cosmos DB
2. Attempt to write back state with a bot (1st time)
3. Error - Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter: Exception caught : Response status code does not indicate success: 400 Substatus: 0 Reason: (Setting offer throughput or autopilot on container is not supported for serverless accounts.ActivityId: 46f6156c-5a06-41f8-9e67-dbba5a7d2298, Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.14393 cosmos-netstandard-sdk/3.2.1).

## Expected behavior
I expect the library to successfully create containers in the cosmos DB instance.

**Comment by cwhitten** [comment]
@dmvtech can you look at this please?

**Comment by dmvtech** [comment]
Thanks @don4of4 I'm attempting to reproduce myself. Should be able to confirm tomorrow.

**Comment by don4of4** [comment]
Sounds good.  It looks like the issue is just creation, so this should be a straightforward fix.

**Comment by dmvtech** [comment]
Yeah, I'm with you on this. Reproduced and in a agreement on very similar to #4310 . I'm assuming if it was nullable, that this would no longer error. 

Obviously, you're aware of the workarounds that @EricDahlvang [has mentioned](https://github.com/microsoft/botbuilder-dotnet/issues/4310#issuecomment-662692328) in that one, so I won't go into that here. 

Thanks for bringing this to our attention.
