### ISSUE TITLE
Temp / Variable memory scope

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#4936]
I use Composer in a modular way as much as possible. This means that api calls etc are in one dialog with error handling and error messaging all within that dialog. Also regular conversation style conversations are modular and within a turn multiple dialogs could be called through events. This makes working with Composer much easier and managing dialogs becomes easier as well.

As a result of that I rather not use the turn memory scope within these dialogs as they can easily overlap with other dialogs within the same turn. When a dialog is short lived - within one turn - I tend to use the dialog memory scope for this to avoid variable overlap.

Here lies the problem, dialog variables are stored in Cosmos DB, as the Set Properties use the standard Get and Set properties for Bot State. This is no what I want, I do not want to clean up properties etc, just to ensure they are not stored in the DB uselessly.

One of the bots crashed throwing a Cosmos DB size error, since one of the api calls returned a big result, which was aggregated in the bot to just a single response back to the customer.

Within Bot Framework you can obviously just use local variables that get disposed after the function / dialog is disposed. This should be possible in Composer as well, using Set Property / Properties (not sure why Set Property exists, but that's another one... :) ) to set properties that **gets disposed after each turn and are scoped to a dialog**. This could be done maybe by having a different memory scope like **variable.xxx** or **temp.xxx** or maybe a separate Set Variables action

**Comment by cwhitten** [comment]
@cxbuilders we want to model these types of scenarios by allowing you to define custom memory scopes and behavior declaratively like we do the dialog system. assigning @darrenj

**Comment by garypretty** [comment]
@EricDahlvang @mrivera-ms Marking this one as a P2 (nice to have) for R12.  Minimally it would be good to understand what is needed to allow customers to define a custom memory scope so that we can document the process.

**Comment by EricDahlvang** [comment]
@cxbuilders  Thank you for raising this issue.

@garypretty  I think you have a sample demonstrating a custom memory scope?

**Comment by mrivera-ms** [comment]
@boydc2014, could you please comment on this?

**Comment by boydc2014** [comment]
> @boydc2014, could you please comment on this?

Sure, this is really a nice to have feature, a top-level scope can help make it more clear. But, there is some considerations if we want to implement that, given the scope in our dialog memory system is not only a prefix. It has certain implications on how it is saved to and recovered from storage.  

For example, user scope like user.xx, will be persisted with userId, convesration scope will be saved with convID, and dialog, turn scopes are more like a short-term things, which won't be even saved to storage. 

If we are to implement a customized top-level scope, we will to clarify what's the expectation of the persistence policy, and do we allow user to customized that as well, and if so, how? 

All the above considerations makes me more lean to guiding user to do what they want under our pre-defined top-level scope as a work around, like you can do conversation.temp.xxx, or dialog.temp.xxx, etc, unless it's blocking certain scenarios.

**Comment by boydc2014** [comment]
> > @boydc2014, could you please comment on this?
> 
> Sure, this is really a nice to have feature, a top-level scope can help make it more clear. But, there is some considerations have to be thought through, if we want to implement that, given the scope in our dialog memory system is not only a prefix. It has certain implications on how it is saved to and recovered from storage.
> 
> For example, user scope like user.xx, will be persisted with userId, convesration scope will be saved with convID, and dialog, turn scopes are more like a short-term thing, which won't be even saved to storage. (i'm not 100% accurate on the different treatment, just to illustrate they are treated differently because we have certain assumption on them)
> 
> If we are to implement a customized top-level scope, we will to clarify what's the expectation of the persistence policy, and do we allow user to customized that policy as well, and if so, how?
> 
> All the above considerations makes me more lean to guiding user to do what they want under our pre-defined top-level scope as a work around, like you can do conversation.temp.xxx, or dialog.temp.xxx, etc, unless it's blocking certain scenarios.

**Comment by garypretty** [comment]
Assigning this one to me.  We don't plan to undertake any work to add additional scopes such as this to the SDK at this time, however, I will be able to shortly share a sample of adding your own custom scope to achieve what you need and you will potentially be able to also add these to a Composer bot using the package capability.

**Comment by mrivera-ms** [comment]
@garypretty, since we are not taking this work for now, I am removing it from the current milestone. It can be re-assigned later when we start the work.

**Comment by martinlarosa** [comment]
Hi! Where can we see the example?
I need a place to store an API M2M token that will be used by the bot for all users. The most top level scope I have is the user level but that means I have to request a token for every user which is costly. What I need is a scope to store a token in memory that would live for as long the bot is running.
