### ISSUE TITLE
Skills can't upload attachments

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#4944]
## Version
4.10

## Describe the bug
If a skill calls Connector.Attachments().Client.Conversations.UploadAttachmentAsync it fails saying 

## To Reproduce
1. Start up the [parent bot](https://github.com/microsoft/BotFramework-FunctionalTests/tree/josh/bots/Bots/DotNet/Consumers/CodeFirst/SimpleHostBot)
2. Start the attachment [skill bot](https://github.com/microsoft/BotFramework-FunctionalTests/tree/josh/bots/Bots/DotNet/Skills/CodeFirst/AttachmentsSkillBot)
3. Connect to the parent in emulator
4. send the parent `skill` 
5. Send the parent `3` or click on the `3. Upload Attachment` option

## Expected behavior
It should upload without throwing a `NotImplemented` error

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/98734642-440dda80-2370-11eb-8e3f-c6838ed550fe.png)

## Additional info
Seems like the problem here is the endpoint isn't implemented in the skills controller

**Comment by gabog** [comment]
Closing this one as a duplicated for #4221
