### ISSUE TITLE
HealthCheck is a feature of ActivityHandler and won't necessarily work for Adaptive Dialog scenarios

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#4956]
Adaptive Dialog scenarios generally use DialogManager which is often just included in an IBot implementation. If this is the case the bot won't get the HealthCheck feature because this is implemented in ActivityHandler.

There are a few solutions here. Change the boiler plate code that invokes DialogManager to run on ActivityHandler. Move the code in ActivityHandler into the adapter (i.e. into CloudAdapter) or implement specific Health Check triggers/actions in adaptive.

Note: the way it has been done in ActivityHandler allows the application to add additional details in the response. So moving this to the adapter is not necessarily the easiest option here.

**Comment by mrivera-ms** [comment]
@johnataylor this was reviewed by the team and is being flagged as needing further discussion.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
