### ISSUE TITLE
Ability to set text properties of OAuth Login using LG

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#4960]
Since we export all language from a bot to be translated to another one in a single file (common.lg), we want to have all language used in the bot coming from that file as well. This includes the Text & Title properties of the OAuth Login. Currently it is not possible to set these properties using LG, so the bot has an English Oauth card for now. Ideally the Text & Title could just be set like the Invalid Prompt;
![image](https://user-images.githubusercontent.com/49873947/98803096-8b4da700-2414-11eb-8942-b736b6ce6c10.png)

**Comment by johnataylor** [comment]
@garypretty any update on this?

**Comment by johnataylor** [comment]
@cwhitten can you comment on this?

**Comment by cwhitten** [comment]
We should take this as a feature-request to wire up the oauth fields into the lg subsystem. The team will look to prioritize this in an upcoming release.

**Comment by garypretty** [comment]
Sorry I missed this one. I agree with @cwhitten, this would be a good one to prioritise.

**Comment by EricDahlvang** [comment]
@garypretty do you know of a way to do this without backwards compat issues?  I think StringExpression for these fields would need to be changed to ITemplate<string>, or am i not understanding the request here?

I'm not sure how to accomplish this, without a breaking change or adding new fields and deprecating the old ones.  Or, a new CloudOAuthInput?

**Comment by mrivera-ms** [comment]
@boydc2014, could you please comment on this?

**Comment by boydc2014** [comment]
> @boydc2014, could you please comment on this?

At a first glance, I suspect this should not be a breaking change, I will do my investigation and get back to you soon.

**Comment by EricDahlvang** [comment]
@boydc2014  would something such as the following potential solution?:

```cs
        private async Task SendOAuthCardAsync(DialogContext dc, IMessageActivity prompt, CancellationToken cancellationToken)
        {
            string title;
            string text;
            var languageGenerator = dc.Services.Get<LanguageGenerator>();
            if (languageGenerator != null)
            {
                var titleResult = await languageGenerator.GenerateAsync(dc, Title.ExpressionText, dc.State, cancellationToken).ConfigureAwait(false);
                var textResult = await languageGenerator.GenerateAsync(dc, Text.ExpressionText, dc.State, cancellationToken).ConfigureAwait(false);
                
                title = AdaptiveExpressions.Expression.Parse(titleResult?.ToString()).TryEvaluate<string>(dc.State).value;
                text = AdaptiveExpressions.Expression.Parse(textResult?.ToString()).TryEvaluate<string>(dc.State).value;
            }
            else
            {
                title = Title?.GetValue(dc.State);
                text = Text?.GetValue(dc.State);
            }

            var settings = new OAuthPromptSettings { ConnectionName = ConnectionName?.GetValue(dc.State), Title = title, Text = text };
            await OAuthPrompt.SendOAuthCardAsync(settings, dc.Context, prompt, cancellationToken).ConfigureAwait(false);
        }
```

This seems to work:
![image](https://user-images.githubusercontent.com/11055362/104825110-9d7d0480-580c-11eb-9938-8f3cc8ab46f1.png)

![image](https://user-images.githubusercontent.com/11055362/104825123-ae2d7a80-580c-11eb-8910-ee05ee42cea5.png)

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. On track for R12.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. @carlosscastro to review and discuss with the larger team.
