### ISSUE TITLE
Adaptive: Can't serialize an InvokeResponse using LG

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4991]
## Version

4.11.1

## Describe the bug

I'm trying to implement a Teams Messaging Extension using Composer and need to return an InvokeResponse when my extension is invoked. I'm using LG for this but get the following serialization error:

![](https://user-images.githubusercontent.com/698939/99742567-a3fb3400-2a88-11eb-805d-298748e47677.png)

The SDK isn't able to convert from the JObject composer creates to an InvokeResponse instance.  Here's the code showing the LG for my response:

![](https://user-images.githubusercontent.com/698939/99742679-e15fc180-2a88-11eb-94af-0073d3ee060c.png)

**Comment by EricDahlvang** [comment]
We could update the adapter:

from:
```cs
return (InvokeResponse)activityInvokeResponse.Value;
```

to:
```cs
    if (activityInvokeResponse.Value is InvokeResponse invokeResponse)
    {
        return invokeResponse;
    }
    else if (activityInvokeResponse.Value is JObject jObject)
    {
        return jObject.ToObject<InvokeResponse>();
    }

    return null;

```

**Comment by Stevenic** [comment]
That looks reasonable

**Comment by tomlm** [comment]
I originally thought the adapter as well, but that means every adapter has to handle this (and many don't, such as the many variations of adapters which are in our unit tests.) Instead I opted to fix this as part of the LG ActivityFactory implementation, as this is really a problem with the typeless environment of LG, and not the adapter itself.
