### ISSUE TITLE
Teams Issue:  Teams sends the same invoke activity multiple times

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5005]
## Describe the bug

I'm trying to debug a message extension and what I'm finding is that anytime I set a breakpoint during an invoke call, Teams will attempt to re-deliver the same invoke activity multiple times.  This is just plain bad...  You should NEVER send the same activity more than once as it could cause any number of duplicate storage entries to be created by the bot.  The 501's in the below screenshot are all the exact same invoke.

![](https://user-images.githubusercontent.com/698939/100308269-d7dcca80-2f5c-11eb-9ee4-664e200807d8.png)

**Comment by Stevenic** [comment]
A little more data... At looking at the requests sent the bot gets 2 invokes with the same exact timestamp & id and then it will get 2 more with a new timestamp and id.  The timestamps are about 30 seconds apart which makes me think there are two separate levels of retry going on here.  First is sends an activity then tries again after a 15 second time out. When the second send timesout it fails the request which falls back to another layer of code that retries the request yet again...

**Comment by EricDahlvang** [comment]
This seems like a bug in the Teams service itself.  Particularly, if a bot returns a 501, there should be no retries.

**Comment by EricDahlvang** [comment]
@clearab  this looks like a Teams service issue.  Unassigning myself, as there is nothing for the sdk team to do here.

**Comment by clearab** [comment]
@tacri any thoughts on this one?
