### ISSUE TITLE
[MCS-DE-GO] User Input TurnCount should not increase on Interruption

### ISSUE THREAD

**Issue by goergenj** [microsoft/botbuilder-dotnet#5008]
When a user input is requested, there should be an option to define whether an interruption will trigger the turnCount to increase or not or an option to reset the turnCount in a flow.

@joaollq @goergenj @sgellock @benbrown @Bindsi @cwhitten  @garypretty

**Comment by mrivera-ms** [comment]
@garypretty , I see you assigned this issue to `backlog`. If we are not going to take this, should we close it? We can reopen it when we are ready to take this work.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
