### ISSUE TITLE
AppInsights: PII is logged even if logPersonalInformation is false

### ISSUE THREAD

**Issue by Robulane** [microsoft/botbuilder-dotnet#5015]
## Version
4.11.0

## Describe the bug
BBF always logs the user's text.

## To Reproduce
1. Have bot with AppInsights integration. Configure the bot to not log the user's personal information as per doc https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=csharp.
2. Talk to the bot
3. Look into any event that logs the Recognizer telemetry, e.g. ValueRecognizerResult
4. Check the customDimensions, you will find "Text" property there. Example:

```json
{
    "conversationId": "0a9d58c0-3301-11eb-bf90-2102e829151f|livechat",
    "activityType": "message",
    "channelId": "emulator",
    "activityId": "2d360170-3301-11eb-98d6-891267dfc0ed",
    "TopIntentScore": "Microsoft.Bot.Builder.IntentScore",
    "Entities": {
        "instance": {
            "Ordinal": [
                {
                    "Name": "Ordinal",
                    "Value": 2,
                    "Start": 4,
                    "End": 9,
                    "Text": "second"
                }
            ]
        }
    },
    "TopIntent": "test2",
    "Intents": {
        "test2": { "score":0.989161491394043 }​
    },
    "Text": "the second test"
}
```

## Expected behavior
User's text should not be logged if logPersonalInformation == false

## Additional context
- The issue is that the `LogPersonalInformation` property is in `TelemetryLoggerMiddleware`. It should be a property in `IBotTelemetryClient` (it should be virtual on `BotTelemetryClient`). 
- `FillRecognizerResultTelemetryProperties` method should check the property on the logger and it shouldn't log text or alteredtext if `LogPersonalInformation  == false`.

- Also, we need to do additional analysis to ensure that we don't log PII in recognizerResult.Properties object.

**Comment by stevengum** [comment]
This needs to be evaluated across all language implementations to ensure the text is not logged.

**Comment by Zerryth** [comment]
Thanks for reporting! I'll start working on this next week after the weekend!

**Comment by garypretty** [comment]
@Zerryth FYI - the LUIS adaptive recognizer already does this.. We have a method for logging the result which can be overridden for this purpose. See https://github.com/microsoft/botbuilder-dotnet/blob/3af7b7b53255b9327de24dcb994dbc7a64bc1725/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisAdaptiveRecognizer.cs#L181-L230

**Comment by Zerryth** [comment]
@Robulane I'm having issues reproducing what you experienced--maybe it's specific to `ValueRecognizerResult`--is this adaptive? Maybe adaptive issue...
___

However I just grabbed sample [21.corebot-app-insights](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/21.corebot-app-insights), and didn't see any PII logged with default setup.
<details>
    <summary>LogPII False - Application Insights - customDimensions</summary>

* ![image](https://user-images.githubusercontent.com/35248895/101536619-1906ae80-394f-11eb-9182-e170aa3d5a93.png)
</details>

Compared to explicitly to log PII as `true`.
*Startup.cs*
```csharp
            services.AddSingleton<TelemetryLoggerMiddleware>(sp =>
            {
                var telemetryClient = sp.GetService<IBotTelemetryClient>();
                return new TelemetryLoggerMiddleware(telemetryClient, logPersonalInformation: true);
            });
```
<details>
    <summary>LogPII True - Application Insights - customDimensions</summary>
* ![image](https://user-images.githubusercontent.com/35248895/101536759-46535c80-394f-11eb-8c5d-7746cec74696.png)

</details>

___

I guess could you provide more information on how you set up the bot, so I can get the same buggy behavior?

**Comment by Robulane** [comment]
@Zerryth, yes, TelemetryLoggerMiddleware handles PII as expected. This bug is about the fact that there other places in BBF that log PII data. Examples that I found:

1. All recognizer results (ValueRecognizerResult, RegexRecognizerResult, RecognizerSetResult, etc.)
2. GeneratorResult can log text that may contain PII data in "text" field

**Comment by Zerryth** [comment]
Gotcha. I see what you mean now, testing out with `RegexRecognizerResult`. No bueno.
![image](https://user-images.githubusercontent.com/35248895/101694534-16c45300-3a28-11eb-8391-7402b7d47b58.png)

**Comment by Zerryth** [comment]
Update: still working on this.

I've spoken with Eric regarding best practices/design issue that arises around 
1. There being a lot of classes that derive from `Recognizer`
2. Implementing the `LogPersonalInformation`
3. `LogPersonalInformation` wanting to be a `BoolExpression` (which needs dependency on `AdaptiveExpressions`) for adaptive bits, but only a `bool` for non-adaptive

It goes deeper, however Eric said maybe we should discuss best practices with Gabo, since current solution I can think of isn't that pretty
