### ISSUE TITLE
Performance improvement: don't copy the entire Activity in JObject

### ISSUE THREAD

**Issue by Robulane** [microsoft/botbuilder-dotnet#5016]
## Version
4.11.0

## Describe the bug
TelemetryInitializerMiddleware stores the entire activity in the HttpContext. This increases memory pressure and decreases performance. We don't need to store the entire serialized activity there, we just need to store a few properties like conversationId or activityId. We should create a new class like BotTelemetryContext and copy all required properties from the activity.

**Comment by garypretty** [comment]
@Robulane do you have a clear picture of what the performance impact here?

I don't believe we can / should change this.  I think we would risk breaking people who have overridden parts of the telemetry pipeline and are existing the full object to be there.  

@Robulane I think the right approach would potentially be for you to override the appropriate parts of the pipeline and just store what you need.

**Comment by Robulane** [comment]
1. I didn't perform any benchmark but basically for each activity sent there is one Serialization-Deserialization roundtrip for no valid reason.

2. Yes, I created my own middleware to workaround this.

**Comment by gabog** [comment]
Closing this on as Roman already has a workaround.
