### ISSUE TITLE
BotBuilder 4.11.1 NullReferenceException when using .Net Framework and WebAPI

### ISSUE THREAD

**Issue by jlenon** [microsoft/botbuilder-dotnet#5026]
## Version
4.11.1

## Describe the bug
When using the WebAPI (.NET Framework) CoreBot sample with the Bot Emulator you get a null reference exception

## To Reproduce
Run the CoreBot sample with SDK 4.11.1 and then start a conversation from the emulator. The exception occurs at the following line in the CoreBot sample.

`await _adapter.ProcessAsync(Request, response, bot);`

## Expected behavior
If the SDK is downgraded to version 4.10.3 the CoreBot sample works as expected.

## Screenshots

![ss1](https://user-images.githubusercontent.com/12651248/101111006-2871b900-362a-11eb-9828-318a79fda173.png)
![ss2](https://user-images.githubusercontent.com/12651248/101111013-2dcf0380-362a-11eb-9555-3c0e3835dcb2.png)

## Additional context
ProcessAync calls ProcessActivityAsync.  The error occurs when calling the line 

`using (var connectorClient = await CreateConnectorClientAsync(activity.ServiceUrl, claimsIdentity, scope).ConfigureAwait(false))`

The actual error is in ConnectorClientEx

`        public ConnectorClient(Uri baseUri, ServiceClientCredentials credentials, HttpClient customHttpClient, bool disposeHttpClient)
#pragma warning restore CA1801 // Review unused parameters
            : base(customHttpClient, disposeHttpClient)
`

**Comment by EricDahlvang** [comment]
This looks related to https://github.com/microsoft/botbuilder-dotnet/issues/4867

If you ignore the exception, and continue execution, does the bot function as expected?

**Comment by jlenon** [comment]
Yes - ignoring the exception causes the bot to function as expected.
