### ISSUE TITLE
Null reference exception in Visual Studio 2019 16.9.0 preview 1

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5034]
Original post from customer: https://developercommunity2.visualstudio.com/t/Bot-Framework-applications-crashed-with-/1277821

Summary:
" [severity:I’m unable to use this version] [regression] [worked-in:16.8.2]
Getting “NullReferenceException” from the PostAsync action in the BotController.cs for all projects created with Bot Templates in .Net Core 3.1. This only happened right after the updates of VS 16.9.0 preview 1. "

**Comment by EricDahlvang** [comment]
This looks related to https://github.com/microsoft/botbuilder-dotnet/issues/4867

and can safely be ignored.
