### ISSUE TITLE
TranscriptLoggerMiddleware sets Activity.From role as property instead using of Role field

### ISSUE THREAD

**Issue by sibbl** [microsoft/botbuilder-dotnet#5035]
## Version
4.11.1

## Describe the bug
When sending an activity from a non-user to `IBot`, the `TranscriptLoggerMiddleware` sets a property `role` to `user` if it wasn't present before, see https://github.com/microsoft/botbuilder-dotnet/blob/4.11/libraries/Microsoft.Bot.Builder/TranscriptLoggerMiddleware.cs#L50-L53

This results in invalid JSON when the activity is serialized to JSON. See screenshots below. When sending the activity in a serialized way to another ASP.NET application for example, the last occurrence of `role` in the JSON is used without any exception or warning.

## Expected behavior
Either nothing or specifically the `Role` property of the `ChannelAccount` class should be set by i.e. `turnContext.Activity.From.Role ??= RoleTypes.User;`.

## Screenshots
![image](https://user-images.githubusercontent.com/866535/101533329-fa77d600-3995-11eb-95fb-041a69ea22d0.png)

![image](https://user-images.githubusercontent.com/866535/101533376-0b284c00-3996-11eb-9cab-d13753f707b8.png)

**Comment by EricDahlvang** [comment]
Thank you for raising this @sibbl 

Your suggestion seems valid, and we should probably move this code into CloneActivity:
```cs
                if (string.IsNullOrEmpty((string)clonedActivity.From.Properties["role"]) && string.IsNullOrEmpty(clonedActivity.From.Role))
                {
                    clonedActivity.From.Role = RoleTypes.User;
                }
```
