### ISSUE TITLE
TopicName in Teams not working after setting the value in ConversationParameters

### ISSUE THREAD

**Issue by mindncz** [microsoft/botbuilder-dotnet#5041]
## Version
Microsoft.Bot.Builder 4.11.1

## Describe the bug
Create a Teams channel-based conversation using TopicName property, the TopicName isn't displayed.

## To Reproduce
Use the following code to create a conversation with message in a Teams Channel. However, the topic is not shown.
            var param = new ConversationParameters()
            {
                Bot = bot,
                IsGroup = true,
                TopicName = "Topic",
                ChannelData = channelData,
                TenantId = channelData.Tenant.Id,
                Activity = MessageFactory.Text("Content")
            };
var conversation = await client.Conversations.CreateConversationAsync(param);

## Expected behavior
TopicName should be displayed as the following:
![Correct](https://user-images.githubusercontent.com/46016028/101735696-32e5f400-3afd-11eb-9048-d6327d7b46a0.PNG)

However, it wasn't displayed.
![Incorrect](https://user-images.githubusercontent.com/46016028/101735743-44c79700-3afd-11eb-8c25-c679c25301a0.PNG)

**Comment by stevkan** [comment]
@mindncz, there's not much info out there on using `TopicName`, however this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-a-chat), "Generating a deep link to a chat", explains that it is an optional name for a group chat.
 
I decided to open the dev console and inspect the network as I updated the different names. Chat ( `threadtype: Chat` ) contains a property called `TopicName`, while conversation ( `threadtype: topic` ) contains a `Properties` property that houses `Subject` which takes the value. The `ConversationParameters` schema doesn't seem to align to either of these.
 
![image](https://user-images.githubusercontent.com/18403946/101850944-924cff80-3b0f-11eb-9a09-ca1aef07e07e.png)

![image](https://user-images.githubusercontent.com/18403946/101850967-9c6efe00-3b0f-11eb-9ced-6102d9dd35fe.png)
 
In addition to `ConversationParameters`, there is also a `TopicName` property in `Activity`, just to keep it interesting. I updated the "TeamsStartNewThreadInTeam" sample to try sending via [Activity.TopicName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.activity.topicname?view=botbuilder-dotnet-stable#Microsoft_Bot_Schema_Activity_TopicName) and [Activity.Properties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.activity.properties?view=botbuilder-dotnet-stable) (didn't really think this would work).
 
```cs
var message = MessageFactory.Text("This will start a new thread in a channel");
message.Properties["TopicName"] = "Channel Conversation Topic";
// and
var message = MessageFactory.Text("This will start a new thread in a channel");
message.TopicName = "Channel Conversation Topic";
```

However, neither passed thru the value to populate the subject of the conversation.
 
@clearab, I was able to repro this issue. Have you played with this, at all, or know if it's possible to add in/update a conversations subject? Also, who would be best to assign this to?

**Comment by mindncz** [comment]
@stevkan Thanks for the reply. Regarding the "subject" supported in Teams channel based conversation, do you have a plan to fix or support it?

**Comment by clearab** [comment]
Both operations, setting the subject of a message in a channel or the name of a group chat, are unsupported in Teams. Setting the subject of a message is on the Teams groups backlog, but doesn't currently have an ETA. Setting the name of a group chat will not be supported.

**Comment by bandtank** [comment]
Has any of this changed? It would be extremely useful to be able to set the subject of a conversation.
