### ISSUE TITLE
NR exception when using SDK version 4.11.1

### ISSUE THREAD

**Issue by nschuessler** [microsoft/botbuilder-dotnet#5042]
## Version
4.11.1

## Describe the bug
Given the example repro code in the .zip file attached to:
https://github.com/MicrosoftDocs/bot-docs/issues/1952

Upgrade to SDK version 4.11.1

## To Reproduce
1. Unzip the repro attached to the issue: https://github.com/MicrosoftDocs/bot-docs/issues/1952
2. Upgrade the bot framework from 4.10.3 to 4.11.1
3. Press F5 to run the code
4. Using the bot emulator version 4.11.1, connect to the bot

Immediately on connection there is a NR excepton.

The exception information is:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Rest.ClientRuntime
  StackTrace:
   at Microsoft.Rest.ServiceClient`1.<>c.<AddUserAgentEntry>b__55_0(ProductInfoHeaderValue left, ProductInfoHeaderValue right) in D:\a\1\SourceDirWith49CharsLengthTestForLongPaths\sdk\mgmtcommon\ClientRuntime\ClientRuntime\ServiceClient.cs:line 568
```

The disassembled line of failure is:

```
if (!Enumerable.Contains<ProductInfoHeaderValue>((global::System.Collections.Generic.IEnumerable<ProductInfoHeaderValue>)HttpClient.get_DefaultRequestHeaders().get_UserAgent(), pInfoHeaderValue, (IEqualityComparer<ProductInfoHeaderValue>)new ObjectComparer<ProductInfoHeaderValue>((ProductInfoHeaderValue left, ProductInfoHeaderValue right) => left.get_Product().get_Name().Equals(right.get_Product().get_Name(), (StringComparison)5))))

```

And the property `left` is:

```
{(.NETCoreApp,Version=v3.1; Microsoft Windows 10.0.19042; X64)}
```

the property `right` is:
```
{FxVersion/4.700.20.47201}
```
`right.Comment` is `null` but its not clear if that is used by this statement.

## Expected behavior
Should not be NR exception as with framework 4.10.3

## Screenshots
![image](https://user-images.githubusercontent.com/54370830/101801344-0f05bc80-3ac3-11eb-9225-5519cc434bcc.png)

![image](https://user-images.githubusercontent.com/54370830/101802021-d3b7bd80-3ac3-11eb-884d-bb9f42cb6d65.png)

![image](https://user-images.githubusercontent.com/54370830/101803356-44aba500-3ac5-11eb-9791-6b3a66ea36a5.png)

## Additional context
This was found while getting a repro for:
https://github.com/MicrosoftDocs/bot-docs/issues/1952
@v-kydela  indicated he could not repro this.

bot emulator 4.11
library 4.10.3 (original before upgrade)
visual studio 16.8.2

**Comment by EricDahlvang** [comment]
This is a known issue in 4.11 explained here: https://github.com/microsoft/botbuilder-dotnet/issues/4867

The error can be safely ignored.

**Comment by mariohdez** [comment]
By the way, I am experiencing the same error on Microsoft.Azure.Management.EventGrid version 6.0.0.
![image](https://user-images.githubusercontent.com/22581660/106109984-0151d800-60ff-11eb-9ccd-9682ac517ae6.png)

When calling the DeleteAsync call on the event subscription property, the call is successful but the azure rest client is throwing a null reference exception. I was able to validate that the exception was only occurring on deubbing mode of visual studio.
