### ISSUE TITLE
Setting offer throughput or autopilot on container is not supported for serverless accounts

### ISSUE THREAD

**Issue by ankur198** [microsoft/botbuilder-dotnet#5051]
## Describe the bug
Cosmos Serverless account cannot be configured. Throughput cannot be allocated to serverless account

## To Reproduce
1. Create Serverless Cosmos Account
2. follow [this guide](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp)

## Exact error
```
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 400 Substatus: 0 Reason: (Setting offer throughput or autopilot on container is not supported for serverless accounts.ActivityId: eeb8fa4c-323d-462e-96fe-9a079750a376, Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.19042 cosmos-netstandard-sdk/3.2.1).)
```

**Comment by ankur198** [comment]
Also setting `ContainerThroughput = 0` doesnt help

**Comment by taicchoumsft** [comment]
Could you see if [ this issue](https://github.com/microsoft/botbuilder-dotnet/issues/4934) helps you?

**Comment by dmvtech** [comment]
@ankur198  You can create the CosmosDB account/db/container _manually_, beforehand and then use it. Make sure you use `/id` as partition key. As things stand currently, you cannot have it created automatically.

**Comment by shwars** [comment]
@dmvtech In 50% of the cases, I seem to be unable to create a container manually from Azure Portal with the same error message
![image](https://user-images.githubusercontent.com/2892110/108495727-30043e00-72ba-11eb-887b-fcfe741858e1.png)

**Comment by dmvtech** [comment]
@shwars This is not a bot framework issue. Please open a ticket within the Azure portal to have this addressed.
