### ISSUE TITLE
Officially support SetTestOptionsMiddleware

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#5077]
SetTestOptionsMiddleware is currently in Microsoft.Bot.Builder.Dialogs.Adaptive.Testing which is a preview package.  The next version of the emulator supports emitting the SetTestOptions event with randomValue/randomSeed to control randomness.  We need to make sure the SDK officially supports this middleware either by moving it into a release package like Microsoft.Bot.Builder.Dialogs.Adaptive or by removing preview on the testing package.  The testing package also includes support for mocking LUIS and for declarative adaptive dialog testing.

Additional notes:
TestOptions is currently being consumed in the adaptiveexpressions library ([here](https://github.com/Microsoft/botbuilder-dotnet/blob/3ea375eff52a5b57f4d8f7a02f374953a6534d32/libraries/AdaptiveExpressions/Extensions.cs#L67)).

**Comment by gabog** [comment]
Hi @chrimc62, I am try to figure out what the best place is to put SetTestOptionsMiddleware and the current package  Microsoft.Bot.Builder.Dialogs.Adaptive.Testing is the best place to have it and I think it is safe to used by users and testers. 

However, there are other classes in Microsoft.Bot.Builder.Dialogs.Adaptive.Testing that need some cleanup before we can call the entire package GA. 

We could move  SetTestOptionsMiddleware but it is in the right place right now, would it be OK to leave this where it is and have devs reference the preview package when they do testing for now? (I'd rather not have it somewhere else and then have to move it back to Microsoft.Bot.Builder.Dialogs.Adaptive.Testing.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Moving it to the next milestone.

**Comment by chrimc62** [comment]
I'm OK with that, but it is a little weird to have official support in the emulator but not the SDK.

**Comment by chrimc62** [comment]
Big rocks agreed to rename this to TestingMiddleware and put it in the same namespace and package as inspection middleware.

**Comment by tracyboehrer** [comment]
The related issue for this is how to enable in Runtime: https://github.com/microsoft/botbuilder-dotnet/issues/5202

One option is to also provide a BotComponent that could be added to Runtime (as a component) in a appsetting.development.  Though I suppose it could be baked into Runtime via the "runtimeSettings.features" node in appsettings, and it also be a development setting.

**Comment by mrivera-ms** [comment]
Assigned to @tracyboehrer per conversation with @gabog. This item is in scope for R14.

**Comment by clearab** [comment]
A Microsoft.Bot.Component.Testing package that contains both?

**Comment by cleemullins** [comment]
Note: This cannot be added until we have parity in JS. Given it's a BotBuilder change, it seems we should *also* have parity in Python and Java. @tracyboehrer Do we have a X-Plat story or concerns here?

**Comment by tracyboehrer** [comment]
@cleemullins John and I agree to not use the middleware route.  We'll add this functionality to AdaptiveDialogBot instead.  We'll still need JS parity though.
