### ISSUE TITLE
Expose all intents to triggers

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#5083]
**Is your feature request related to a problem? Please describe.**
Currently the SDK filters to the top intent from a recognizer and surfaces that.  For more complex bots it would be nice to surface all intents so that we can apply trigger conditions/priorities and selectors to them.

**Describe the solution you'd like**
Allow surfacing all intents from recognizers to the trigger system.  OnIntent would then trigger on its intent being in the surfaced intents.  Some recognizers like LUIS already support surfacing all intents, but we would also have add a flag to the regex recognizer to do the same.

**Describe alternatives you've considered**
We could put condition/priority/selectors into recognizers but this seems even more confusing.

**Additional context**
https://github.com/microsoft/BotFramework-Composer/issues/5476

**Comment by boydc2014** [comment]
@chrimc62 can you clarify a little bit more on the detailed design. 

I assume this proposal means, we will up turn.recognized an array, so that, "turn.recognized.intent" will becomes "turn.recognized[0...N].intent" and will drive the onIntent trigger?

**Comment by boydc2014** [comment]
> @chrimc62 can you clarify a little bit more on the detailed design.
> 
> I assume this proposal means, we will up turn.recognized an array, so that, "turn.recognized.intent" will becomes "turn.recognized[0...N].intent" and will drive the onIntent trigger?

The reason to ask is i'm wondering how can we make sure it's not a breaking change.  If we update turn.recognized to be an array, it's highly likely to be a breaking change, another way might be we create a new property like turn.recognizedResults[], it won't be a breaking change, but we have to maintain two set of mechanisms, what do you think

**Comment by chrimc62** [comment]
We need  to look at this E2E.  Today a single intent is surfaced and we pick the highest priority single trigger that matches the intent  and condition.  This only fires once becomes events are transient in memory.  In the composer UI it looks like you can fire on multiple different intents from a single utterance, but you cannot--this is the issue that Ben ran into.  By default surfacing a single intent seems like a good idea, so I suspect this should be opt-in.  There are a couple of different design choices:
* Change recognized.intent to be an array and change OnIntent to look for intent in the array.  Advantage is there is no new trigger, but it breaks the current contract.
* Add a new trigger OnChooseIntent which accesses the multiple intent information exposed from the recognizer.  We should make sure you have access to the full intent information, i.e. score, metadata, etc.  
I tend to prefer introducing a new trigger.
