### ISSUE TITLE
Could not resolve Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate' 

### ISSUE THREAD

**Issue by dalton5** [microsoft/botbuilder-dotnet#5085]
Hi,

I have the issue below:

![image](https://user-images.githubusercontent.com/8339768/104124051-ce61c300-534e-11eb-9aaa-01327cc2235a.png)

I can't sort it out. 

What am I missing?

Is it a bug?

Thanks,

**Comment by jwiley84** [comment]
hello @dalton5 

We're going to need some more information on this in order to repro/solve. Can you explain a bit more about your project, how you're integrating the bot framework, and what version you're using?

**Comment by dalton5** [comment]
Hi,

I updated to the last nugget version and it works.

thanks,
