### ISSUE TITLE
incorrect id is set when RegisterContainerDialogs in DialogManager

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#5086]
## Version
What package version of the SDK are you using.

Current master

## Describe the bug
Give a clear and concise description of what the bug is.

The dialog id is not set correctly, so when we begin a dialog, it is wrong.

## To Reproduce
1. Clone https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/id_bug
2. Run this test https://github.com/xieofxie/botbuilder-dotnet/blob/20dd31f6a12f4ad25c953997e4723003d7b93f7c/tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogManagerTests.cs#L348
3. It should be 'Case 1', but now it is 'Case 2'

Or
1. Run https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/adaptive-dialog/21.AdaptiveBot-declarative/AdaptiveBot.cs
2. type 1
3. it starts 2

## Expected behavior
Give a clear and concise description of what you expected to happen.

Begin the dialog correctly

## Screenshots
![image](https://user-images.githubusercontent.com/2876650/104154953-1224fd00-5421-11eb-8e14-eced657a69c5.png)

## Additional context

I created a test case for this scenario. I try to investigate the root cause and it happens here: https://github.com/microsoft/botbuilder-dotnet/blob/5160928a760e0d57830777dea05a235d52da1d68/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L92

When it calls RegisterContainerDialogs, it adds children dialogs to the parent and has name conflict, so it renames the children. Then when executes the children, it could not found the correct one. But I don't know how to fix it..

**Comment by boydc2014** [comment]
@xieofxie do you mean that we have a issue to locate the correct dialog when "multiple anonymous(inlined) dialogs are included in one dialog"?

**Comment by xieofxie** [comment]
@boydc2014 Yes.. When root dialog is anonymous, children dialog are not required to be inlined

**Comment by boydc2014** [comment]
@feich-ms  can you help follow up this with @xieofxie

**Comment by feich-ms** [comment]
Verified already fixed by this PR https://github.com/microsoft/botbuilder-dotnet/pull/5072. @xieofxie please try again with the latest main branch
