### ISSUE TITLE
ContinueConversation with a custom activity

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-dotnet#5087]
Raising issue to track this following discussion with @johnataylor.

Add an overload to continue conversation (ideally on the new cloud adapter and the existing BF adapter) that allows a custom activity to be sent to the bot.  This will be used as part of the handoff pattern where messages are received from handoff platforms (e.g. liveperson or omnichannel) onto a controller, are converted into activities and then need to be sent to the bot.

ContinueConversation today creates a continuation activity, but we require an overload that allows us to send a bespoke activity.

**Comment by xieofxie** [comment]
Also close this https://github.com/microsoft/botbuilder-dotnet/issues/4018 when done, thanks~

**Comment by johnataylor** [comment]
This is merged for CloudAdapter.
