### ISSUE TITLE
TextInput action doesn't support setting non-string property

### ISSUE THREAD

**Issue by feich-ms** [microsoft/botbuilder-dotnet#5088]
## Version
4.11.1

## Describe the bug
See a user [comment ](https://github.com/microsoft/BotFramework-Composer/issues/4875#issuecomment-753613559)here. Use TextInput to set a property with value extracted from LUIS recognized entities. If the recognized entities are an array, the TextInput action will refuse setting this array value to a property due to the string validation here https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/TextInput.cs#L51. This design seems not friendly. We think the string validation should only be applied to the raw user input rather than the property setting. Property should be able to take any valid object rather value limited to string.

## To Reproduce
1. Use TextInput action
2. Set the Property with `dialog.userInput`
3. Set the Value with an expression that returns an array, e.g. `=createArray('hello', 'world')`
4. Send a response with the `${dialog.userInput}`
5. You will see `Object reference not set to an instance of an object.`

## Expected behavior
Non-string input can be set to property

**Comment by boydc2014** [comment]
@tomlm @Stevenic can you chime in on this one, see if the restriction put on TextInput should be loosed or not. 

A short version of above proposal is
Current restriction: "The final property set must be a string"
Proposed loosed restriction: "The value get from input must be a string, but the property eventually set don't have to be a string after post processing"

**Comment by feich-ms** [comment]
I made a fix in this [commit](https://github.com/microsoft/botbuilder-dotnet/commit/a3b29e0e52e420c565458b308676d60d0ce71b28). This is just a proposal, not a final fix. This fix is to allow users to set this.property with any objects evaluated from this.value. There is no validation or formatting on the result of this.value. If this.value is left null, then it will get the input from activity and perform recognition and validations on the activity input as what we do now. Do you have any insights? @boydc2014 @tomlm

**Comment by feich-ms** [comment]
After checked current design with Dong, it should be by design that TextInput can only set text property currently, so will close this issue.
