### ISSUE TITLE
DCR: change QnA Maker component to take URL for configuration

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#509]

**Comment by cleemullins** [comment]
Should we take the full URL (Host+Segments), or just the host? 

The current default is:
`public const string qnaMakerServiceEndpoint = "https://westus.api.cognitive.microsoft.com/qnamaker/v3.0/knowledgebases/";`

I think the most flexible option is to just remove this in it's entirety, and have the developer pass in the fully URL.

**Comment by ovishesh** [comment]
At the moment, QnA Maker doesn't give an entire URL (Host+Segments) and unless the QnAMaker team has plans to change that on the portal adding an additional parameter for Host would work better. 

Something similar to [this](https://github.com/Microsoft/botbuilder-dotnet/blob/b01fe6e3de5f37b3d93875dda965fa8166c3cd28/samples/Microsoft.Bot.Samples.Ai.QnA/Startup.cs#L36) and something that is alinged with the QnAMaker portal will be nice with a default fall back to the `westus` URL.
````csharp
var qnaOptions = new QnAMakerMiddlewareOptions
{
     HostURL = "https:// ---",
     SubscriptionKey = "xxxxxx",
     KnowledgeBaseId = "xxxxxx"
};
````

This is what the QnAMaker portal looks like for deployment details:
````
POST /knowledgebases/<KBId>/generateAnswer
Host: https://westus.api.cognitive.microsoft.com/qnamaker/v2.0
Ocp-Apim-Subscription-Key: xxxxxx
Content-Type: application/json
{"question":"hi"}
````

**Comment by garypretty** [comment]
We also might need to allow developers to specify if they want to target v2 or v3 APIs.  The only difference for v3 are some additional properties so this should be straightforward. Happy to help here if needed.

**Comment by johnataylor** [comment]
should be fixed now
