### ISSUE TITLE
 SendActivity is not working as excepted , without using the “Generator”

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/botbuilder-dotnet#5102]
## Version
4.11.1

## Describe the bug
In Adaptive Dialog without using the “Generator” property, SendActivity method is not displaying the dynamic result

## To Reproduce
Example code 

 Actions = new List<Dialog>()
                    {
                        new TextInput()
                        {
                            Prompt = new StaticActivityTemplate(MessageFactory.Text("Hey enter the name")),
                            Property = "user.name"
                        },                        
                        new SendActivity("Hello , ${user.name}")
                    }

Input : Name
Result is showing as “Hello,$”

## Expected behavior
Hello , Name

## proposal changes 
Create default TemplateEngineLanguageGenerator in AdaptiveDialog ctor 
Generator = new TemplateEngineLanguageGenerator(null);

**Comment by EricDahlvang** [comment]
@rvinothrajendran I'm not sure this is a bug.  What would be the benefit to providing a new TemplateEngineLanguageGenerator with no templates?

**Comment by rvinothrajendran** [comment]
@EricDahlvang 
I think problem in languageGenerator.GenerateAsync function ( BindAsync function calling this function to generate the result) 
once I created the object for TemplateEngineLanguageGenerator , languageGenerator.GenerateAsync  return the proper result. otherwise not .
I'm not able to debug languageGenerator.GenerateAsync function to find the exact place

**Comment by EricDahlvang** [comment]
Okay, you're saying this should work ootb, without the need to supply a language generator manually:

new SendActivity("Hello , ${user.name}")

**Comment by rvinothrajendran** [comment]
@EricDahlvang yes

**Comment by Danieladu** [comment]
If you want to use the languageGeneration feature without the specific LG file, you could try to add the "UseLanguageGeneration" middleware to dialogManager.
Sample code:
```
DialogManager dm = new DialogManager(dialog)
                .UseResourceExplorer(new ResourceExplorer())
                .UseLanguageGeneration();
```

**Comment by rvinothrajendran** [comment]
but we have to use the LanguageGeneration somehow but its good adaptive-dialog refer to an empty TemplateEngine by default.

**Comment by boydc2014** [comment]
@rvinothrajendran @Danieladu i think it's good to have this work ootb, and by adding a default empty TemplateEngine, we can leverage the capbility of LG engine to do data binding (though lg file is empty). That's also kind of naturally aligned with current design, it's like creating a default value for a field in a class, that's it. 

@EricDahlvang what do you think?

**Comment by EricDahlvang** [comment]
@boydc2014 that makes sense.
