### ISSUE TITLE
Audience is null for Direct Line Extension situations

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#5110]
## Version
Current `main`

## Describe the bug
Audience is null

## To Reproduce
1. Follow https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0
2. Follow https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0
3. Say hi
4. See error 502 in webchat and in app service, we could find that audience is null.

In step 1, if one uses `app.UseNamedPipes(System.Environment.GetEnvironmentVariable("APPSETTING_WEBSITE_SITE_NAME") + ".directline", "https://api.botframework.com");`, it will work correctly.

However, if we change `"https://api.botframework.com"` to other audience, it will not work.

## Expected behavior

Work correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/2876650/105125769-20a59f80-5b18-11eb-915a-eae6b78c0926.png)
![image](https://user-images.githubusercontent.com/2876650/105125794-2f8c5200-5b18-11eb-82b4-676c64f75798.png)

## Additional context

After some investigation, I found the problem involves three parts:
1. Direct line extension (or streaming) expects custom audience to work https://github.com/microsoft/botbuilder-dotnet/blob/e90ba0b131c0e24d82e2c9ca2cb4d6fce272db33/libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs#L321
2. We require audience now https://github.com/microsoft/botbuilder-dotnet/blob/e90ba0b131c0e24d82e2c9ca2cb4d6fce272db33/libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs#L139
3. We return null for custom audience https://github.com/microsoft/botbuilder-dotnet/blob/e90ba0b131c0e24d82e2c9ca2cb4d6fce272db33/libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs#L325

One fix could be return callerId as audience when not match in function GetAudienceFromCallerId

**Comment by stevengum** [comment]
Thank you @xieofxie for filing the issue and including this very helpful information!

To avoid typing magic strings, the following constants in the **Microsoft.Bot.Connector.Authentication** can be used:

For bots in Public Azure, please use [`AuthenticationConstants.ToChannelFromBotOAuthScope`](https://github.com/microsoft/botbuilder-dotnet/blob/fd87c8fb18aa9884836c60bfb20ccec4e6bd79be/libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConstants.cs#L36).

For bots in US Government Azure, please use [`GovernmentAuthenticationConstants.ToChannelFromBotOAuthScope`](https://github.com/microsoft/botbuilder-dotnet/blob/fd87c8fb18aa9884836c60bfb20ccec4e6bd79be/libraries/Microsoft.Bot.Connector/Authentication/GovernmentAuthenticationConstants.cs#L24).

___

> In step 1, if one uses app.UseNamedPipes(System.Environment.GetEnvironmentVariable("APPSETTING_WEBSITE_SITE_NAME") + ".directline", "https://api.botframework.com");, it will work correctly.
>
> However, if we change "https://api.botframework.com" to other audience, it will not work.

@xieofxie, can you share more information about the statement where using a different audience won't work? Does "other audience" mean a `null` value?

If you're for example using `"test"` as the audience and it fails, can you share the exception and more information?

**Comment by xieofxie** [comment]
@stevengum To be honest, I don't know the function of audience here. My comment just comes from the code:
Here it states `Fallback to using the raw Audience as the CallerId`:
 https://github.com/microsoft/botbuilder-dotnet/blob/e90ba0b131c0e24d82e2c9ca2cb4d6fce272db33/libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs#L321

However when we process the activity, it will return null if it is not public, gov nor skill, so we will face the same error:
https://github.com/microsoft/botbuilder-dotnet/blob/e90ba0b131c0e24d82e2c9ca2cb4d6fce272db33/libraries/Microsoft.Bot.Builder/Streaming/BotFrameworkHttpAdapterBase.cs#L325
