### ISSUE TITLE
Copy text to speak in QnAMakerDialog

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#5112]
When using QnAMakerDialog in speech channel, the response is not spoken as LG.

**Proposed solution:**

Add a option to switch this on-off.

**Describe alternatives you've considered**

Always enable it.

**Additional context**

We always copy text to speak for LG here: https://github.com/microsoft/botbuilder-dotnet/blob/fd87c8fb18aa9884836c60bfb20ccec4e6bd79be/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Templates/ActivityTemplate.cs#L84

However, we only send text in QnA here: https://github.com/microsoft/botbuilder-dotnet/blob/fd87c8fb18aa9884836c60bfb20ccec4e6bd79be/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L552

**Comment by mrivera-ms** [comment]
This issue is being tracked here: #5980. Closing as duplicate.
