### ISSUE TITLE
Does Bot Composer work with Twilio WhatsApp Adapter?

### ISSUE THREAD

**Issue by hsachinraj** [microsoft/botbuilder-dotnet#5113]
I am using Twilio Adapter to connect to a bot designed using Bot composer. The bot works well in other channels, including Telegram, Web and DirectLine but WhatsApp. I need to make it work on WA. Can someone help?

Here are the steps to repro:
1. In Bot Composer - **project settings** - include **custom runtime**
2. added a new controller for twilio (followed the instructions given [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0#connect-a-bot-to-twilio-using-the-twilio-adapter))
3. deployed the bot to Azure App Service
4. Updated the App Service configuration with twilio information (account SID, auth token, from Number and validation URL)
5. Registered Twilio channel in the **Bot Channel Registration**
6. Update Twilio WhatsApp Sender profile to add a webhook (pointing to https://mybotapp/api/twilio)

Now when I test the bot in the **Web chat**, it works properly. However when I try it on Twilio side using WhatsApp, I am getting a 500 Error

Appreciate if someone can help

_Originally posted by @hsachinraj in https://github.com/microsoft/botbuilder-dotnet/issues/5094#issuecomment-764504802_

**Comment by stevkan** [comment]
@hsachinraj, using a service adapter (like the Twilio WhatsApp one) means you are choosing to have your bot communicate with the service directly. As such, you do not need the Twilio channel to be enabled in your Bot Channel Registration. The same is true for the reverse. If you intend to use the channel connector in your Bot Channel Registration, then you do not need the adapter. Please select and configure the one you intend to use, try again, and let me know if you still receive an error. While I don't put too much stock in this, it's _possible_ the two are conflicting.

**Comment by hsachinraj** [comment]
Thansk @stevkan. I have tried removing the channel connector yet still get the same issue - Internal Server Error 500 :(

This [repo](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/63.twilio-adapter) also seems to be supporting only SMS scenario and not WhatsApp messaging - is that correct?

**Comment by stevkan** [comment]
@hsachinraj, Yes, that is precisely the problem. Both the Twilio bot registration channel and the dotnet SDK's [Twilio adapter](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/63.twilio-adapter/Controllers/TwilioController.cs) only support Twilio and do not extend to WhatsApp. Unfortunately, while there have been discussions around extending to WhatsApp, there is no active development at this time.

Of note, while there is a [Twilio-WhatsApp adapter](https://github.com/BotBuilderCommunity/botbuilder-community-js/tree/master/libraries/botbuilder-adapter-twilio-whatsapp) available in the BotBuilder-Community JS repo, a matching one does not exist for dotnet. However, there is an [Infobip-WhatsApp adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Infobip.WhatsApp) that you may be able utilize as a workaround. As stated in the ReadMe.md file:

> Incoming WhatsApp message requests are transformed, by the adapter, into Bot Framework Activites and then when your bot sends outgoing activities, the adapter transforms the outgoing Activity into an Infobip OMNI failover messages.

Lastly, I apologize for any confusion I may have created. Initially, I mixed up in my head the community adapters with the official thinking the Twilio-WhatsApp adapter existed in both repos _and_ were official, not community.
