### ISSUE TITLE
Please fix Slack adapter configuration

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#5115]
## Version
main branch

## Describe the bug

The [Slack adapter](https://docs.microsoft.com/azure/bot-service/bot-service-channel-connect-slack?tabs=adapter) uses the following configuration settings:

```json
{
  "SlackVerificationToken": "",
  "SlackBotToken": "",
  "SlackClientSigningSecret": ""
}
```

There are a few problems with this:

1. The verification token is deprecated. According to Slack: "This deprecated Verification Token can still be used to verify that requests come from Slack, but we strongly recommend using the above, more secure, signing secret instead."
2. It's unclear whether "SlackClientSigningSecret" refers to the client secret or to the signing secret, so the name should be changed.

## Expected behavior
The Slack adapter should not use the verification token and should not have ambiguous configuration settings.

**Comment by haacked** [comment]
Please reopen this issue as it hasn't been addressed. The [docs here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?tabs=adapter&view=azure-bot-service-4.0) is outdated and looking at the `SlackAdapter` code, it looks like it still wants us to pass a deprecated SlackVerificationToken.
