### ISSUE TITLE
[Adaptive expressions] Any() function request

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#5128]
There are several occasions where I need to check if there is any value in an array that matches a condition. This is currently possible using the where() method, but would be cleaner if there were an any() method which just returned the boolean value.

Here is an example of a condition I'm using for an if/else block that is checking for the presence of any parameters in my parameters object:
```
count(where($parameters, p, exists(p))) == 0
```

It would be more readable like this:
```
not(any(where($parameters, p, exists(p))))
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrivera-ms** [comment]
@boydc2014 , could you please triage this issue? If accepted, please add milestone. Thank you.
