### ISSUE TITLE
Target .NET 5.0 for the Bot Builder .NET SDK

### ISSUE THREAD

**Issue by sebastianzolg** [microsoft/botbuilder-dotnet#5130]
Hi all, according to my question on [SO](https://stackoverflow.com/q/65885121/2715229), it would be nice to have the SDK targeting .NET 5.0, so we catch up with the latest .NET 5 GA release.

**From:**
```
<TargetFramework>netcoreapp3.1</TargetFramework>
```

**To:**
```
<TargetFramework>net5.0</TargetFramework>
```

We already see some libraries which can't be referenced since the SDK targets .NET Core 3.1. 
I've changed the target manually, and I can't see any compile or runtime error. Anything that is blocking us from switching over?

Thanks
—Sebastian

**Comment by mrivera-ms** [comment]
@sebastianzolg the team will start testing on .NET 5.0 soon. We do not have an exact date at this time, but it is in the pipeline. Thank you for your question.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. @gabo to investigate the implications and timeframe.

**Comment by mrivera-ms** [comment]
Per discussion with @gabog, this is not for R13.

**Comment by NickSpag** [comment]
Hi all, it looks like this got bumped to R15. Is there any more clarity that could be provided on when it may land or is it still a little unceratin? The team I'm on is holding on 3.1 as a result. Thanks in advance!

**Comment by mrivera-ms** [comment]
Thank you for submitting this issue @NickSpag. The team has this change in the backlog for a future release.

**Comment by Citronjack** [comment]
How about .Net6?

**Comment by gabog** [comment]
@Citronjack, we will skip net 6, the upcoming release, 4.17.x will add support for net 6 (it should be available in a few weeks from now)
