### ISSUE TITLE
Token Exchange for Virtual Assistant/Skills in Microsoft Teams returns Service Error

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/botbuilder-dotnet#5140]
## Version
4.11.1

## Describe the bug
When running in WebChat and Emulator, the token exchange between the RootBot and the SkillBot works fine. When running in Teams, the exchange call is returning: 
`System.InvalidOperationException: Unable to exchange token: (ServiceError) Consent Required`

## To Reproduce
Using the sample at BotBuilder-Samples\experimental\sso-with-skills, add the RootBot to a Microsoft Teams application. Add the domains used by the VA & Skill, and token.botframework.com, to the valid domains list in Teams.

The following commands work:
login
token
logout

The following command does not work, resulting in the above error:
skill login

## Expected behavior
The `skill login` command should display a token with the skill as the audience.

## Additional context
 
Consent for both applications has been granted.

**Comment by srinaath** [comment]
@Virtual-Josh

**Comment by Virtual-Josh** [comment]
Hi @pschaeflein,

There are many things at play here so let me try to separate them. First, you can't test the Teams specific functionality in emulator. Emulator uses the directline channel, Teams uses the Teams channel. Second, I'd caution you against using the samples in experimental. Experimental is a place where we tend to put samples that we are considering moving into the main samples repo. They aren't guaranteed to work out of the box as the documentation might not be complete, or the sample might still be under construction. Third, I would recommend you follow the documentation [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml) for adding SSO to a host + bot. Once that's working you can work on swapping in code from [this](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots) doc to handle the Teams specific events for SSO token exchange.

**Comment by pschaeflein** [comment]
@Virtual-Josh , thanks for the response.

1.) I am using the emulator only to test the VA/Skill token exchange. It is working as expected.
2.) I understand that the code is experimental. I am performing experiments. ;)
3.) I have followed the docs you referenced. As I mentioned, VA/Skill token exchange works fine. 

Do I need to implement the Teams SSO in order for the skill to get a token from the Virtual Assistant? When I run the login command, the VA shows an OAuth card. I'm find with that for now. When running the skill login command, the VA successfully intercepts the OAuth card, but the call to the ExchangeToken method fails as noted above. 

Is that a configuration issue?

**Comment by Virtual-Josh** [comment]
@pschaeflein If SSO is failing outside of teams then there's something wrong with the configuration. Based on the error you originally posted it seems as though you haven't granted access for the host to auth on behalf of the skill. I would take a second pass through [this](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-the-azure-ad-identity-for-rootbot) part of the docs for the parent and the skill to make sure everything is exactly as described. 

Have you added the step listed [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0&tabs=csharp#configure-the-emulator-for-authentication) to configure the emulator for auth? Also are you on the current version of the emulator?

**Comment by pschaeflein** [comment]
SSO works outside of Teams. It does not work inside Teams. Please refer to the issue description:
![image](https://user-images.githubusercontent.com/8008013/106655180-a6850a00-655e-11eb-84fb-9609e4053d89.png)

Again, my question:

Do I need to implement the Teams SSO in order for the skill to get a token from the Virtual Assistant?

**Comment by Virtual-Josh** [comment]
If SSO works outside of teams then the issue is either in the manifest, or in the implementation of the bot. Have you updated the `manifest.json` to have the `WebApplicationInfo` object? Here's the [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#update-your-teams-application-manifest-for-your-bot) for that. Additionally did you update the AAD app URI to match the `app://botid-MSAPPID` format?

**Comment by pschaeflein** [comment]
The AAD app URI is not in that format. The value you highlight is required to have the Teams client perform SSO to my bot. Which would be the virtual agent (root bot).

I prefer not to change that if possible, as that would be a breaking change.

Are you saying that I must make that change to get the token exchange from the root bot to the skill bot when running in the Teams client?

**Comment by Virtual-Josh** [comment]
I don't know the answer to that question since that's a Teams question not an SDK question. Let me see if I can find someone from Teams to chime in.

**Comment by Virtual-Josh** [comment]
Hey @pschaeflein I just synced up with the Teams team and the URI in the manifest does not need to match the botid. 

I'm going to ask some basic question to confirm that the fundamental pieces are as they should be. This isn't mean to be insulting. SSO has a million little steps that all have to be just so and it's difficult to know what piece is wrong. 

1. Are you using the Teams Activity Handler in both the parent and the skill?
2. Did you make the updates to the activity handler on the parent to catch the Teams SSO event?
3. Does the Azure Active Directory (AAD) app registration for the skill allow the parent's AAD app registration for auth?

**Comment by Virtual-Josh** [comment]
@pschaeflein  So I spoke with the Teams team and the Id doesn't need to match to work. However there's one thing I want to clarify. What SSO scenario are you trying to enable here? Are you trying to have the skill send an OAuth card that will be caught by SSO and won't show because the user is already logged in? Are you trying to prevent access to the skill unless the person is already logged in?  Something else? I ask since I'm wondering if you can use normal auth instead of SSO specifically.
