### ISSUE TITLE
QnAMaker Dialog Fallback action

### ISSUE THREAD

**Issue by DanieleS82** [microsoft/botbuilder-dotnet#5149]
Hi,
the origin of this request is in [this](https://github.com/microsoft/BotFramework-Composer/issues/5657) post that I opened to add a new feature in the QnAMaker Dialog component of the Bot Framework Composer.

Shortly, the QnA Maker Dialog component allows to easily connect a knowledge base. If a response score is less of a threshold set, a fallback answer is to throw, but there is no way to run a fallback action in substitution of the fallback answer. The only way is to invoke the knowledge base through the APIs and implement the flow yourself. But this requires also managing other aspects like the prompts answer ([here](https://github.com/microsoft/BotFramework-Composer/issues/4773#issuecomment-731906615) some suggestions), manage multiple versions of reply card to works properly over the web version and Teams version, etc.

**Comment by srinaath** [comment]
Can you provide your comments on whether this feature will be picked up or added to the backlog?

**Comment by kostasvl** [comment]
I'm interested in this as well. Is there some variable that this dialog sets, so that we can check what happened (eg the score, or a bool to say that the score was over the threshold)? Thanks

**Comment by mrivera-ms** [comment]
Thank you for submitting this issue @DanieleS82. We will note your request for future releases.
