### ISSUE TITLE
[Testing Skills Everywhere] Create Conversation is not implemented in the base ChannelServiceHandler

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#5153]
This is just the tracking issue to make it easier to prioritize Skills work for R13.

The CreateConversation endpoint is not implemented in the `ChannelServiceHandler`. We would need to fix that if we wanted to test the Create Conversation scenario with skills.

[link](https://github.com/microsoft/botbuilder-js/issues/3366) to issue in JS.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Currently not supported. It should be re-created as a feature request in the future.
