### ISSUE TITLE
Confusion between Prompts and Dialogs library

### ISSUE THREAD

**Issue by ivorb** [Microsoft/botbuilder-dotnet#516]
**Repo steps:**

Create basic prompt/dialog bot, using number prompt, such as the example in the wiki.

**Result:**

If you just use Dialogs library, you can't use NumberResult (necessary to get to the Value of the response). If you use just the Prompts, you can't use dialogs (DialogSet in this case). Using both complains about an ambiguous reference to NumberPrompt (you can specify the library, but is confusing why that's necessary)

**Expected:**

Adding Dialogs should contain all the prompt members, or none of them - not half way in between.

Additionally, the Prompts library still has the old prompt members in it, intentional? I was under the impression we would reduce that to where we have parity with JS.

**Comment by johnataylor** [comment]
WE are going to make the non-dialog Prompts internal - and once we've done that most likely rename or eliminate that layer.

**Comment by johnataylor** [comment]
We've removed the non-dialog prompts. The current state of the implementation is to move this prompt code into the dialogs package and make it all internal - we also changed some names to make that less confusing.
