### ISSUE TITLE
Url encoding issue with BlobStorage & Bot state

### ISSUE THREAD

**Issue by tbuquet** [microsoft/botbuilder-dotnet#5165]
## Version
4.11.1

## Describe the bug
Url encoding issue while saving a bot state using BlobStorage's implementation of IStorage.

## To Reproduce
1. Use blobstorage for the bot state
`var blobStorage = new BlobsStorage(Configuration["StorageAccountConnectionString"], Configuration["StorageAccountBlobName"]);
services.AddSingleton<IStorage>(blobStorage);
services.AddSingleton<UserState>();
services.AddSingleton<ConversationState>();`
2. When running the bot, the session gets saved with a bunch of %2f instead of creating a proper path in the storage account. For example:
`emulator%2fconversations%2f4cf19dd1-6736-11eb-b014-55dafaf9b3d1%7clivechat`

## Expected behavior
When creating a state file, the proper proper path should be:
`emulator/conversations/4cf19dd1-6736-11eb-b014-55dafaf9b3d1|livechat`

**Comment by mdrichardson** [comment]
@tbuquet This is less a bug and more [a design decision made several years ago](https://github.com/microsoft/botbuilder-dotnet/blame/a163e05c62bf387e8b5064925050d4cb11d9b1b0/libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs#L225). Blob names [have always allowed](https://github.com/Azure/azure-storage-net/blob/905e9f260b8c673988cee9903092af7c71517270/Lib/Common/NameValidator.cs#L95) `/` ([so long as the name doesn't end with `/`](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata)), however [Cosmos never has](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet). Unfortunately, it would be a breaking change to adjust this now. However, keeping the names URL-encoded allows users to migrate their data between Cosmos and Blobs, if desired, fairly easily.
