### ISSUE TITLE
Unit test coverage needed for new Cloud Adapter classes

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#5166]
The following new classes need to increase unit test coverage:
### Class Name  (current coverage)   
- Microsoft.Bot.Builder.Dialogs.CloudOAuthPrompt    (68%)
- Microsoft.Bot.Builder.Dialogs.OAuthPrompt (64%)
- Microsoft.Bot.Builder.Dialogs.OAuthHelper (74%)
- Microsoft.Bot.Connector.Authentication.UserTokenClientImpl (15%)

**Comment by ceciliaavila** [comment]
The classes `CloudOAuthPrompt` and `OAuthHelper` were removed from the repo. These are the PRs that deleted them:
https://github.com/microsoft/botbuilder-dotnet/pull/5213
https://github.com/microsoft/botbuilder-dotnet/pull/5221
