### ISSUE TITLE
[Testing Skills Everywhere] Email channel doesn't translate dialog numbers to choices accurately

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#5169]
## Version
4.11.1

## Describe the bug
Selecting a numeric option in the Email channel doesn't translate from numbers to options

## To Reproduce
1. Setup a bot in the Email channel that uses dialogs
2. Send an email to the bot
3. When the dialog option shows respond with the number, not the text 

## Expected behavior
The activity on the bot should have the value of the number instead of the number

## Screenshots
![bug](https://user-images.githubusercontent.com/50158775/107087896-feb34a80-67b0-11eb-918b-f2a22e34e143.png)
![bug2](https://user-images.githubusercontent.com/50158775/107087966-18549200-67b1-11eb-81a4-d09dd15665d7.png)
![bug3](https://user-images.githubusercontent.com/50158775/107088053-39b57e00-67b1-11eb-86a0-68a7c6b60eab.png)

## Additional context
The list of choices in the email comes through with a slightly different format than other channels. Usually choices come through with the number period (1.) format instead of the number in a set of parenthesis format that the email channel seems to use.

**Comment by xieofxie** [comment]
Hello, `context.activity.text` contains what user says, so it is '1' in this case.
To use a result from prompt, use `stepContext.Result` instead. It will be the chosen `Choice` object.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Will close it as "Won't fix".
