### ISSUE TITLE
[Testing Skills Everywhere] SSO to a skill doesn't work in the Email channel

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#5171]
## Version
4.11.1

## Describe the bug
SSO in the Email channel doesn't work as intended

## To Reproduce
1. Setup the waterfall host & skill for SSO
2. Work through the dialogs to get to the SSO scenario 

## Expected behavior
SSO should complete, however when you do the `Login` call on the skill the token exchange fails. 

## Additional context
It seems to be a performance problem. The Email channel can be Very slow to send and receive messages, it throws `Bad Gateway` errors, and sometimes requests just die for no good reason.

**Comment by xieofxie** [comment]
Although reply is slow, I could finish the SSO following this guide https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml#create-the-azure-skillbot-registration

Could you verify if everything is correct? Thanks!

**Comment by mrivera-ms** [comment]
@darrenj, could you please review and prioritize issues on the Email channel? Please let us know if we should consider it for future work.

**Comment by gabog** [comment]
We will not address this issue at the moment.
