### ISSUE TITLE
Return 202 Accepted for incoming POSTs

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#5172]
Current protocol defines that when an activity is posted to the bot there is no expected reply body other than a success status code except in 2 cases

*   **invoke** - we return the invokeResponse as content
*   **DeliveryMode=expectReplies** - we return an array of activities for the caller to process instead of HTTP POST back to the caller.

The activity protocol is designed conceptually as bi directional async delivery of activity objects. The SDK models this in a naive way...because it might have to return a body, it waits until the end of the turn to return the status code even when it knows there will be no content. This has the effect of delaying the status code for the incoming activity until the entire turn is complete and ALL of it's downstream dependencies are completed.

This is illustrated by this diagram:  

![image](https://user-images.githubusercontent.com/17789481/107156681-a1e09d00-6934-11eb-8758-968f37215624.png)

You can see that the response to step 1 only happens in step 5 after 2, 3, 4 are processed.

This leads to ill effects in the system which impacts developers and us.

*   The caller is left waiting a long time for the status code...the status code should not change regardless if you succeed processing the turn or not.
*   Clients/Channels are blamed for being slow, because the initial delivery of the activity absorbs ALL downstream costs of the bot code. (For example ABS team is constantly getting ICM tickets for performance of delivery when the perf problem is in the bot's own code.)
*   Any internal dependencies that fail get attribute back to a protocol failure for the caller, complicating the trace logs (we write "we couldn't deliver that message with 503", even though we successfully delivered the message and it was the bot logic that failed it's internal logic.  **the sender does not care if the bot understood a message and it shouldn't be an error status.**
*   It makes it hard to read the logs because the traces are spread over large area
*   with addition of new **Command** activity type, it's possible that the target channel could POST back to the bot again....If it does that synchronous, then the entire chain would have to unwind to release the initial POST.

This illustrates the command chaining that will happen if we don't make this change:

![](https://user-images.githubusercontent.com/17789481/107175478-cadb4f00-6981-11eb-80d0-1c961dd65972.png)

The initial POST(message) will block until all of the services have unwound until step 8.

The alternative is to change our SDK code to decouple the call chains by returning 202 Accepted when it receives an activity it knows does not need a response body and has been validated. This looks like this:  

![image](https://user-images.githubusercontent.com/17789481/107156703-bb81e480-6934-11eb-8ab5-fbd247c0a59b.png)

Where activity 1 is acknowledged immediately, unblocking the caller and allowing the bot's logic decides to continue to process the turn.  This allows all of the POST transactions to live the shortest life spans.

**Comment by mrivera-ms** [comment]
@tomlm, this was reviewed by the SDK team. We are pushing to R14 so we have time to do end-to-end testing.

**Comment by carlosscastro** [comment]
We ran into this in the telephony crew as well for async / await actions. Given how short R14 is, and how at the core this change is, I'm moving this to R15. We'll address it in early R15 so it has time to bake.
