### ISSUE TITLE
Home page refer the wrong twitter account

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/botbuilder-dotnet#5187]
https://github.com/microsoft/botbuilder-dotnet  (github)  page refer the wrong twitter account (@botframework) , It should be account : @msbotframework

**Comment by gabog** [comment]
Thanks for the issue and the PR @rvinothrajendran!

@darrenj / @garypretty / @cleemullins , can you please review and check if we need to change this in other repos?

Thanks

**Comment by rvinothrajendran** [comment]
@gabog 
https://github.com/microsoft/botbuilder-python and
https://github.com/Microsoft/botbuilder-js should be update the same.
Will create a PR for this.

**Comment by Virtual-Josh** [comment]
Closing this issue as the PRs are up.

**Comment by rvinothrajendran** [comment]
@Virtual-Josh sorry, not get why this PR gets closed

**Comment by Virtual-Josh** [comment]
@rvinothrajendran I'm fine to leave this one open so it can be closed on the PR is merged in.
