### ISSUE TITLE
Handle hierachial entities better

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#5193]
**Is your feature request related to a problem? Please describe.**
Adaptive does a great job of working with first level entities
Given a result like this:
```json
{
    "alteredText": null,
    "entities": {
      "$instance": {
        "bedrooms": [
          {
            "endIndex": 27,
            "startIndex": 18,
            "text": "2 bedroom",
            "type": "bedrooms"
          }
        ],
        "price": [
          {
            "endIndex": 50,
            "startIndex": 48,
            "text": "1M",
            "type": "price"
          }
        ]
      },
      "bedrooms": [
        {
          "$instance": {
            "integer": [
              {
                "endIndex": 19,
                "startIndex": 18,
                "text": "2",
                "type": "integer"
              }
            ]
          },
          "integer": [
            "2"
          ]
        }
      ],
      "price": [
        {
          "$instance": {
            "integer": [
              {
                "endIndex": 50,
                "startIndex": 48,
                "text": "1m",
                "type": "integer"
              }
            ]
          },
          "integer": [
            "1000000"
          ]
        }
      ]
    },
    "intents": {
      "Matched": {
        "score": 1.1800000667572021
      }
    }
```
With entities you can use @ to refer to first VALUE and @@ to refer to the array of values 

You can refer to the first entity of a given type by saying **@homequery**, but for nested types you have to do
**@homequery.price[0].value** 

**Describe the solution you'd like**
I would like to be able to use @ all the way through the chain, so
**@homequery.@price** --> turn.recognized.entities.homequery[0].price[0]

**Comment by cleemullins** [comment]
@boydc2014 I believe we should push this to R15. Can you review the ask, and our current status, and add your thoughts? If you agree this should be pushed, please update the milestone.

**Comment by boydc2014** [comment]
> @boydc2014 I believe we should push this to R15. Can you review the ask, and our current status, and add your thoughts? If you agree this should be pushed, please update the milestone.

Yes, i agree so, let's push this, i did some early investigation on this, this is somehow tricky to implement than it looks like because it's requiring "@" to have different meaning in different context. 

So it makes sense to push this off, on even adjust the proposal of the new syntax.
