### ISSUE TITLE
Adaptive Middleware

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#5198]
Proposed, Steve Ickman:

Just wanting to share some ideas I have for how we could add support for using Adaptive Dialogs as middleware.  It's been bugging me that you can't easily use LG or access memory scopes from within middleware.  To address that I've been thinking that we could add a new AdaptiveMiddleware class that uses an AdaptiveDialog to intercept middleware events.  The middleware class would emit OnBeforeTurn, OnAfterTurn, OnSendActivities, OnUpdateActivity, and OnDeleteActivity events which the middleware dialog could process.
 
Each middleware instance would have its own dialog stack so it could even do multi-turn interactions when `OnBeforeTurn` or OnAfterTurn.  This would let you create an OAuthPromptMiddleware for example that always ensures the user is logged in.

https://fuselabs.visualstudio.com/_git/Meeting%20Assistant?path=%2FMSMeeting-SharedActions%2FAdaptiveMiddleware.cs

**Comment by Stevenic** [comment]
I'm planning to package this up as a community package for //BUILD
