### ISSUE TITLE
Refactor the luis and qnamaker Composer-based settings extensions adapter

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botbuilder-dotnet#5199]
This method utilizes the settings file generated by bf luis:build and qna:build commands, aligning to Composer-specific settings. 

https://github.com/microsoft/botframework-core/blob/80274609e5b59c72d3d44cc79eb7de594fd3949f/src/Microsoft.Bot.Core/CognitiveSettingsExtensions.cs#L17-L27

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
