### ISSUE TITLE
Cosmos vs Storage -> State vs Transcripts

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#5205]
From cxbuilders (https://github.com/cxbuilders):
I am trying to understand what the reason is for storing the state in Cosmos and the transcripts in Storage? Why not have both in Storage? The reason I am asking is that Cosmos just takes a long time to create in the Pipeline and it would also just simplify things. Additionally the cost of Cosmos also is quite high if usage is low (for dev and acc).

**Comment by mrivera-ms** [comment]
Reviewed with the SDK team. This should probably be added in the Samples repo for a future sample.

**Comment by EricDahlvang** [comment]
Blobs storage tends to be not as performant as CosmosDb for frequent retrievals. Closing.
