### ISSUE TITLE
Auto-reload resources when file changes.

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#5210]
Per Tom:

The ResourceExplorer is set up to fire change events when the underlying resources change, only it has never worked correctly in the emitted runtime.  I finally figured out the issue.  With dotnet, all of the resources are "content", meaning they get copied to the output folder (bin/debug/....).  This is a good thing, as it means they are part of the zip file when using zip deployment etc.  
 
The issue is that the resource explorer was always being bound to executing folder, which is the bin/debug folder when running locally.  What we want is to load the resources from the root of the project when we are running locally.  Doing this then makes it that whenever composer updates a resource, the bot automatically reloads and it is immediately available without having to restart the process. 

To do that I added the following logic to startup.cs:

```
var resourceExplorer = new ResourceExplorer()
                    .AddFolder(GetDialogsFolder(config, context.ApplicationRootPath, rootDialogFolderName));
 
                resourceExplorer.Changed += (sender, e) => 
                {
                    Console.WriteLine("Resources changed, reloading...");
                    bot.RootDialog = resourceExplorer.LoadType<AdaptiveDialog>(resourceExplorer.GetResource(rootDialog));
                }; 
 
 
 
        private string GetDialogsFolder(IConfiguration config, string root, string dialogFolder) 
        {
            var hostname = config.GetValue<string>("WEBSITE_HOSTNAME"); 
            if (hostname.StartsWith("localhost"))
            {
                // we want the source dialogs folder, not the output content dialogs so we can edit and reload automatically
                for (int i = 0; i < 5; i++)
                {
                    root = Path.GetDirectoryName(root);
                    var dialogsPath = Path.Combine(root, dialogFolder);
                    if (Directory.Exists(dialogsPath))
                    {
                        return dialogsPath;
                    }
                }
            }
            return Path.Combine(root, "BondiBot");
        }
```

**Comment by tomlm** [comment]
With addition of new AdaptiveDialogBot class, this change needs to happen in here. 

Essentially.

1.  Lazy\<> initilalizer assumes it will never change (this is not true with local development)
2.  We need to listen to resourceExplorer.Changed += to reload the dialog (and all of the resources).

To fix this.

1.  change Lazy\<Dialog> to Dialog with a lock
2.  Add Changed listener to reload the dialog
3.  When local -> Change resourceExplorer folder to not be the OUTPUT folder but instead the original source files
