### ISSUE TITLE
Clean up LU Parser project

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#5212]
Project `Microsoft.Bot.Builder.Parsers.LU` is currently in preview. It needs to be cleaned up to follow the adopted standards.

Original PR: [PR 4856](https://github.com/microsoft/botbuilder-dotnet/pull/4856)

**Comment by mrivera-ms** [comment]
@munozemilio, what is the status of this? Let's discuss.

**Comment by mrivera-ms** [comment]
@munozemilio, could you please update the status of this issue?

**Comment by mrivera-ms** [comment]
Per offline conversation with @munozemilio, this will be completed in R13.

**Comment by munozemilio** [comment]
@mrivera-ms could you please provide guidance on how to see the warnings?

**Comment by mrivera-ms** [comment]
This can stay how it is while it is a preview package.
