### ISSUE TITLE
Comment in QnA Maker needs to be clarified

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#5215]
The code comment in the [QnAMaker](https://github.com/microsoft/BotBuilder-CognitiveServices/blob/58c63349521fce1500955d2c9263ba2523498b9d/CSharp/Library/QnAMaker/QnAMaker/QnAMakerService/QnAMakerAttribute.cs#L47) class needs to be clarified. There was an [ICM](https://portal.microsofticm.com/imp/v3/incidents/details/227591911/home) that was filed since a customer was confused about the comment. 

After speaking with QnA Maker they said the information listed [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbot-service%2Fbot-builder-tutorial-add-qna%3Fview%3Dazure-bot-service-4.0%26tabs%3Dcsharp%23add-knowledge-base-information-to-your-bot&data=04%7C01%7CJoshua.Ratliff%40microsoft.com%7C81f66dc66e8d410e3b6f08d8cfdf5a56%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637487905717377155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7YVe28yEL3Ttkm7CjeeV%2FmBTyN5504h705ATjLQV%2FVA%3D&reserved=0) is current so it should be used to use similar language.

**Comment by mrivera-ms** [comment]
@Virtual-Josh, could you please add status to this issue?

**Comment by Virtual-Josh** [comment]
Sorry for the slow reply, I didn't see this was assigned to me. This is actually a non-issue. The ICM linked above was for a depreciated repo.
