### ISSUE TITLE
Adaptive Expressions: Add crypto functions

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5225]
I'm trying to build a generic set of dialogs for working with cosmos DB over REST using adaptives `HttpAction`.  I can't currently generate the required [HMAC Signature](https://docs.microsoft.com/en-us/rest/api/cosmos-db/access-control-on-cosmosdb-resources?redirectedfrom=MSDN#constructkeytoken) needed for the access token due to a lack of crypto functions in the Adaptive Expressions library.  I would imagine that any sort of sophisticated REST call is going to require a similar signature so it would be great if we could get these added...

**Comment by sgellock** [comment]
Before we cut any new code here, I want to have a discussion first.

**Comment by sgellock** [comment]
Hey, before we go down this route, I'd like to have a conversation first.  Tom, Steve plus SDK leadership

**Comment by sgellock** [comment]
@Stevenic can't we create a package, and use Expression.Functions.Add() to extend Adaptive Expressions to support your scenarios?  I'm really reluctant to go down this route.

**Comment by Stevenic** [comment]
You can but they would need to be namespaced with "Crypto." and then the developer would need to tell composer to ignore anything under this namespace within their bots settings file.
