### ISSUE TITLE
SkillHttpClient should not swallow error information

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#5240]
BotFrameworkHttpClient has the following [code](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpClient.cs#L240)

```csharp
                    using (var response = await HttpClient.SendAsync(httpRequestMessage, cancellationToken).ConfigureAwait(false))
                    {
                        var content = response.Content != null ? await response.Content.ReadAsStringAsync().ConfigureAwait(false) : null;
                        return new InvokeResponse<T>
                        {
                            Status = (int)response.StatusCode,
                            Body = content?.Length > 0 ? GetBodyContent<T>(content) : default
                        };
                    }
```
Which in Skills for example has `T` as `ExpectReplies`. The problem is that when response has a *non-success* status code, the shape usually does not look like T. So we get a 500 as Status but no body. 

Alternatives could be to include error information in the invoke response or to throw exceptions on non-successful status codes. However the current way things work is very detrimental and could lead to hard debugging sessions. 

Exit criteria: 

- Unit tests: Unit tests should be possible with http client with custom delegating handler
- E2E: e2e scenario with skills, use [this ](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/) sample, remove the lines that register the BotAdapter [here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/). Skill communication should fail but skill only receives 500 without description, and no logs found on the host. We should make sure that errors in the BotFrameworkHttpClient are handled properly

**Comment by tracyboehrer** [comment]
SkillHttpClient has been deprecated.
