### ISSUE TITLE
OAuthPrompt should log diagnostics data on TokenExchange failures

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#5253]
## Version
4.12

## Describe the bug
Currently [OAuthPrompt.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L314) catches any exception that may result from trying to `UserTokenAccess.ExchangeTokenAsync()` and assumes that the failure means the user is not logged in. This may or may not be correct and it could be related to a configuration issue.

But the code explicitly discards the exception and doesn't log the root cause of the failure. 

## Expected behavior
The OAuthPrompt or the class implementing ExchangeTokenAsync should log information that would assist the developer understand the root cause of the token exchange failure.

**Comment by mrivera-ms** [comment]
Per discussion with @gabog, this is to be moved to R14.

**Comment by gabog** [comment]
We will not address this at the moment.
