### ISSUE TITLE
List Card Showing Error On Clicking On list Item During in-meeting and opening two tabs on single click.

### ISSUE THREAD

**Issue by sudoaccessdenied** [microsoft/botbuilder-dotnet#5258]
## Version
4.10.3

## Describe the bug
I am getting error "Something went wrong. Please try again."  when I click on "List card" items during in-meeting Meeting Chat.
Also it is opening two tabs on  single click.

## To Reproduce
1. Go to 'Microsoft Teams'
2. Create and event from Calender and install ```SpeakNow``` Bot to it.
3. Join the meeting .
4. Click on Chat icon during in-meeting. It will open Meeting chat.
5. Now type ```@SpeakNow Help```
6. You will get a List Card.
7. Click on the link in List card 
8. See the error.

## Expected behavior
It should open single tab and should not show the error  i.e.  "Something went wrong. Please try again." during in-meeting. else It works fine in  chat. 

### In-Meeting Screenshot
![Screenshot 2021-02-28 220645](https://user-images.githubusercontent.com/30634773/109426035-61df7800-7a11-11eb-82cf-e89021d88cbd.png)
### Opening two tabs on single click Screenshot
![Screenshot 2021-02-28 220302](https://user-images.githubusercontent.com/30634773/109426043-69068600-7a11-11eb-85ac-a56d2e2c8674.png)

### List Card ;
```
{
  "title": "Help Center",
  "items": [

    {
      "type": "resultItem",
      "icon": "https://cdn.boarddecisions.com/files/public/images/speak-now.png",
      "title": "Speak Now for Teams",
      "subtitle": "Keep virtual meeting discussions on track...",
      "tap": {
        "type": "openUrl",
        "value": "https://support.meetingdecisions.com/en/speak-now-for-teams"
      }
    }
  ]  
}
```
###  C# Code to Create Attachement of List Card in SpeakNow
```
public Attachment GetHelpCard()
        {
            // combine path for cross platform support
            var cardPath = Path.Combine(Environment.CurrentDirectory, "Resources", "ListCard.json");
            var adaptiveCardJson = File.ReadAllText(cardPath);

            var adaptiveCardAttachment = new Attachment()
            {
                ContentType = "application/vnd.microsoft.teams.card.list",
                Content = JsonConvert.DeserializeObject(adaptiveCardJson),
            };

            return adaptiveCardAttachment;
        }
```
### OnMessageAsync
```  
 await turnContext.SendActivityAsync(MessageFactory.Attachment(GetHelpCard()));
```

**Comment by clearab** [comment]
@Wajeed-msft can you please take a look at this one, and migrate to your preferred location?

**Comment by clearab** [comment]
@sudoaccessdenied these are both going to be issues with the Teams client itself, and not have much to do with the bot directly. @Wajeed-msft will hopefully get these tracked appropriately. In the future, please take a look at https://aka.ms/teamsdevfeedback for good ways to get in touch with the Teams developer support group.

**Comment by sudoaccessdenied** [comment]
@clearab  It is working fine after the yesterday New Teams Updade. Thank you.
