### ISSUE TITLE
HttpRequest dialog is mutating the singleton http client

### ISSUE THREAD

**Issue by Robulane** [microsoft/botbuilder-dotnet#5260]
## Version
4.12.0

## Describe the bug
HttpRequest dialog is retrieving the HttpClient and is mutating the default headers on it instead of building the proper HttpRequestMessage. This results in thread safety issues if the server execute multiple HttpRequests at the same time.

![image](https://user-images.githubusercontent.com/55888168/109553012-c9113100-7ad2-11eb-9c5a-0207906af94f.png)

Also, HttpRequest doesn't provide an easy way to override the logic of sending the request. This may be required to add some additional telemetry or block calls to invalid resources, etc.

## How to fix
1. Create a virtual protected method SendRequestAsync(HttpRequestMessage message) in HttpRequest.cs that will retrieve the HttpClient from the TurnState, execute the message and return Task<HttpResponseMessage> message.
2. Instead of adding the headers to the DefaultRequestHeaders, add them to the HttpRequestMessage 

## Expected behavior
HttpRequest request should not mutate the HttpClient. There should be an easy way to override the class to add a custom logic just before sending the message.

**Comment by cleemullins** [comment]
After working through this with @johnataylor and @Robulane and others from the team, this is not a blocking issue at this time.

We've filed tracking bug for R13 that arise from this and should be cleaned up. 

https://github.com/microsoft/botbuilder-dotnet/issues/5261
