### ISSUE TITLE
HttpClient injected via TurnContext needs to be removed

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#5261]
## Version
4.12.0

## Describe the bug
HttpClient is injected for testing purposes. This behavior needs to be removed, and associated tests updated. 

[HttpRequest](https://github.com/microsoft/botbuilder-dotnet/blob/8f53635a9129a5c3e4a6669820db83591edd1431/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs#L232)

**Comment by johnataylor** [comment]
What we need is a simple way for a hosting infrastructure to filter outbound http requests from the application.

A factoring we would could consider would be to split the functionality of something like the http dailog component into two halves, basically a thin dialog derivative and then a stateless "service" found on the turnstate (I know turnstate, its a very sad, but we need to work with what we've got). They could then craft the service as they saw fit. This is not a thousand miles away from finding the HttpClient or HttpClientFactory on the turnstate but it works at a much higher level, its potentially a much more locked down model. It certainly easy to test. In fact as a general pattern its probably better to write as little logic into dialog classes as possible - basically treat the dialog class as loosely analogous to a thin presentation layer.

That approach also leads to a solution that works across platforms, whereas binding to http classes directly is very c# specific.

**Comment by mrivera-ms** [comment]
@johnataylor, is this issue to be resolved in R14?

**Comment by johnataylor** [comment]
The customer for this was PVA and they are taking a different approach.
