### ISSUE TITLE
Middleware in the runtime for SSML tagging

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5266]
To support the directline speech and telephony channels, we're going to need a mechanism to ensure the appropriate SSML tags are add to Activities. Current thinking is the easiest way to support this would be a middleware in the runtime that can be enabled through settings when required. We will need to work with the Composer team to ensure proper UI support, as well as potentially automatically toggling based on channel selection.

We need two specific capabilities, which could be implemented as two pieces of middleware (but then ordering becomes a concern)  or a single middleware with associated settings.

1. A toggle to enable the fallback to the Text property for the Speak property on an activity. i.e. when enabled, if the speak property is empty on an outgoing message activity, then the value of the text property will be copied into it. 

2. If it is not already present, wrap the speak property value with a speak and a voice tag, setting the voice font (specified within settings).  If the speak and voice tags are already present, then the value is left alone, allowing a developer to override.

A simple example of this middleware (which doesn't contain the check for the speak tag - but I have a more complete version fo that code available) would look something like.

```cs
public class SpeakMiddleware : IMiddleware
    {
        public async Task OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken = default)
        {
            turnContext.OnSendActivities(async (ctx, activities, nextSend) =>
            {
                foreach (var activity in activities)
                {
                    if (activity.Type == ActivityTypes.Message)
                    {
                        activity.Speak ??= activity.Text;
                        activity.Speak =
                            $"<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='en-GB'>" +
                            $"<voice name='en-GB-LibbyNeural'>{activity.Speak}</voice>" +
                            $"</speak>";
                    }
                }

                return await nextSend().ConfigureAwait(false);
            });

            await next(cancellationToken);
        }
    }
```

**Comment by tracyboehrer** [comment]
@garypretty Is the PR with the SetSpeakMiddleware still the expected behavior?

**Comment by garypretty** [comment]
@tracyboehrer Yes, that PR reflects what we have in the current runtime, which appears to be working as expected.  Additionally we have one additional PR which ensures the middleware is added to the pipeline by default.

**Comment by tracyboehrer** [comment]
Branch:  https://github.com/microsoft/botbuilder-dotnet/tree/trboehre/setspeakmiddleware
