### ISSUE TITLE
BlobTranscriptStore stuck in infinite loop when update or delete activities can't be found in transcript store

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#5271]
## Version
4.11.1

## Describe the bug
`BlobTranscriptStore` gets stuck in an infinite loop on update and delete activities when the activity transcript can't be found in the blob store. This can occur when one activity contains multiple attachments. Each attachment ends up as a separate activity in Microsoft Teams. When one of the attachment activities is updated, the [InnerReadBlobAsync](https://github.com/microsoft/botbuilder-dotnet/blob/21ebf04eebd786ba74a5cbcbd354632fae3a8ffd/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs#L324) never exits the while loop, because it can't find the activity. The while loop only exits in case of an exception or when the activity is found.

## To Reproduce
1. Send an activity with two attachments to Microsoft Teams
2. Send an update to the activity ID of one of the activities created by the attachments
3. Application Insights continuously displays the following dependency logs:
- `ContainerClient.ListBlobsFlatSegment` of type `InProc | Microsoft.Storage`
- `GET` of type `Azure blob`

## Expected behavior
The while loop should also exit if the activity could not be found.

## Additional context
This behavior obviously leads to poor performance, but has also a significant cost impact. We found out the hard way when we discovered our storage bill to have increased over 5000% from $10 to over $500 because of the millions of list and read operations on the storage account.

**Comment by EricDahlvang** [comment]
Hi @sschutten 

Thank you for raising this issue.  I'm looking into this right now.  

How are you obtaining the activity id of one of the activities created by the attachments?

**Comment by sschutten** [comment]
Hi @EricDahlvang,

Thank you for looking into it.
We're using the turn.activity.replyToId in response to an Action.Submit action in the adaptive card in the attachment.

**Comment by sschutten** [comment]
Thanks @EricDahlvang for the quick turnaround! We've put a workaround in place where we send each attachment as a separate activity until the fix is released.
