### ISSUE TITLE
Deprecate HealthCheck activity (dotnet)

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#5284]
see [parent](https://github.com/microsoft/botframework-sdk/issues/6225)

**Comment by mrivera-ms** [comment]
@gabog, @msomanathan, is this still in scope for R13?

**Comment by msomanathan** [comment]
@mrivera-ms, it looks like composer needs the functionality of HealthCheck activity. So, we are trying to identify whether we need to keep this, but make modifications to the information it contains.
