### ISSUE TITLE
Allow package prefixes in resource ids

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#5298]
Full description of the issues and proposals is found here: https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/EdhjcHAfsDNAjaTPbHM2Oy0BS7LJRsAXu2d9ed52hOP7iQ?e=MTgM5s

The proposal is to allow .dialog, .lu and .lg files to refer to package assets using the package name as prefix.  If I had a package `MyPackage` and it had a dialog file `CoolStuff.dialog` then the only way to refer to it in your main dialog file would be to do `MyPackage#CoolStuff.dialog`.  

To refer to an LU/QNA/LG file we would extend the current resource resolver to support the same schema, i.e. `[import](MyPackage#CoolStuff.en-us.lu)`.  This is mainly to support legacy usage and would import all of the symbols in the file into the no namespace reference, i.e. if `CoolStuff.en-us.lg` defined a template `CoolStuff()` then you would refer to it in another templates as `${CoolStuff()}`.  This approach could lead to conflicts which means you are required to introduce a namespace.

To support namespaces we are replacing the markdown import with an explicit import statement to make clearer the definition.  `import MyPackage#CoolStuff.en-us.lg` would be equivalent to the legacy markdown import above, i.e. all symbols would be imported without a namespace qualification. If this causes a conflict you need to use the second form, i.e. `import myPkg=MyPackage#CoolStuff.en-us.lg` where you define a namespace to use when importing symbols.  In this case the only way to refer to the package templates would be `${myPkg.CoolStuff()}`.

The existing namespace and exports mechanism would only be for promoting LG template definitions into adaptive expressions.

From an implementation standpoint this means the bot has a unique namespace as does each package.  It is only within a namespace that filenames/template names/intents/entities must be unique. The scheme is also such that a package can refer to files in other packages.  Package asset import happens during dialog:merge and where it gets imported is up to the person calling dialog:merge.  This means we should extend the resource loader to take in a root package directory and the subdirectory would be the package name for each package.  (We should not just bake in where composer puts it.) 

In addition to the resource loader we also need to make sure that the language server and composer also work with them and we update any samples and packages.

Related work items: 
https://github.com/microsoft/BotBuilder-Samples/issues/3115
https://github.com/microsoft/BotFramework-Composer/issues/6348
https://github.com/microsoft/botframework-components/issues/723

**Comment by mrivera-ms** [comment]
@garypretty, could you please prioritize this? Is this in scope for R13 or later?

**Comment by garypretty** [comment]
Clearing the R13 milestone and adding @carlosscastro to the assignees.

**Comment by clearab** [comment]
Microsoft.Bot.Component.AdaptiveDialogs#MyDialog.Name seems like a really, really long name
