### ISSUE TITLE
Azure storage issues

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-dotnet#530]
Hi, I am trying the latest version of BF with a sample bot I wrote and I am running into several issues when trying to use AzureTableStorage or AzureBlobStorage to store conversation state.

When using AzureBlobStorage I get the following exception:
![blobexception](https://user-images.githubusercontent.com/12264946/39504620-c4cdbce8-4d9a-11e8-9c4f-ae4c15dcd0fb.png)

When using AzureTableStorage I get the following exception:
![tableexception](https://user-images.githubusercontent.com/12264946/39504768-05be0c2a-4d9c-11e8-97ec-9153df2772a0.png)

I declare the storage middleware as follows:
            IStorage storage = new AzureTableStorage(Configuration.GetSection("DataConnectionString")?.Value, "MyKey");
            or
            IStorage storage = new AzureBlobStorage(Configuration.GetSection("DataConnectionString")?.Value, "MyKey");

And then I try to read and write content using:
context.GetConversationState<StoreItem>()["MyStateKey"] = "some value";

Below is also the code I use for StoreItem (which is a copy of an object we had in previous versions that used to work fine).

MemoryStorage works fine but none of the Azure ones do. 

For Azure tables, it seems that the v9.1.1 of Azure Storage has issues serializing objects with collections (store item has a flex object in it), see this post for more details: https://github.com/Azure/azure-storage-net/issues/672 . But I don't understand what the issue could be with Blobs. Are there any steps involved in setting that up or the connection string should be enough and the framework should handle it?

Any pointers @cleemullins ?

Thanks

using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace Microsoft.Bot.Builder.Core.Extensions
{
    public delegate Task<Boolean> MiddlewareDisabler(ITurnContext context);

    public class StoreItem : FlexObject, IStoreItem
    {
        private static readonly JsonSerializerSettings _serializationSettings = new JsonSerializerSettings
        {
            // we use all so that we get typed roundtrip out of storage, but we don't use validation because we don't know what types are valid
            TypeNameHandling = TypeNameHandling.All
        };

        /// <summary>
        /// eTag for concurrency
        /// </summary>
        public string eTag { get; set; }

        public T ToObject<T>() where T : class
        {
            return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(this, _serializationSettings), _serializationSettings);
        }
    }
}

namespace Microsoft.Bot.Builder.Core.Extensions
{
    /// <summary>
    /// DynamicObject which seemlessly blends dictionary properties with real properties
    /// </summary>
    public class FlexObject : DynamicObject, ICloneable
    {
        public static JsonSerializerSettings SerializationSettings = new JsonSerializerSettings
        {
            // we use all so that we get typed roundtrip out of storage, but we don't use validation because we don't know what types are valid
            TypeNameHandling = TypeNameHandling.All
        };

        /// <remarks>
        /// If the JsonNameAttribute is used on the method name, that "revised" name is stored here
        /// so that serialization happens correctly. It's important in that case to serialize the "revised"
        /// name ("@id"), yet maintain the original name ("id") so the value can be retrieved. 
        /// 
        /// The primary scenario here is serialization to JSON. 
        /// </remarks>
        private Dictionary<string, string> _objectProperties;

        [JsonExtensionData]
        private Dictionary<string, object> dynamicProperties { get; } = new Dictionary<string, object>();

        protected IDictionary<string, string> objectProperties
        {
            get
            {
                if (_objectProperties == null)
                {
                    lock (dynamicProperties)
                    {
                        if (_objectProperties == null)
                        {
                            var temp = new Dictionary<string, string>();
                            foreach (var pi in GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance))
                            {
                                if (pi.Name == "Item")
                                {
                                    continue;
                                }

                                var customJsonAttributes = pi.GetCustomAttributes<JsonPropertyAttribute>();

                                // If there is a customJsonAttribute, then use the user
                                // specified name as the method name. This is what will be serialized
                                // out to JSON ("@id").
                                // If the Json override is not present, then the actual property
                                // name is used ("id").                                  
                                var attributeOrNull = customJsonAttributes.FirstOrDefault();
                                if (attributeOrNull != null)
                                {
                                    temp[attributeOrNull.PropertyName] = pi.Name;
                                }
                                else
                                {
                                    temp[pi.Name] = null;
                                }
                            }

                            _objectProperties = temp;
                        }
                    }
                }

                return _objectProperties;
            }
        }

        public dynamic this[string name]
        {
            get
            {
                TryGetMember(name, out var value);
                return value;
            }
            set { this.TrySetMember(name, value); }
        }

        public object Clone()
        {
            return JsonConvert.DeserializeObject(JsonConvert.SerializeObject(this, SerializationSettings), SerializationSettings);
        }

        public override IEnumerable<string> GetDynamicMemberNames()
        {
            foreach (var p in objectProperties)
            {
                yield return p.Key;
            }

            foreach (var key in dynamicProperties.Keys.Where(key => !objectProperties.ContainsKey(key)))
            {
                yield return key;
            }
        }

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            return TryGetMember(binder.Name, out result);
        }

        public override bool TryDeleteMember(DeleteMemberBinder binder)
        {
            return base.TryDeleteMember(binder);
        }

        public override bool TrySetMember(SetMemberBinder binder, object value)
        {
            return TrySetMember(binder.Name, value);
        }

        private bool TryGetMember(string name, out object result)
        {
            if (dynamicProperties.ContainsKey(name))
            {
                result = dynamicProperties[name];
                return true;
            }

            if (objectProperties.ContainsKey(name))
            {
                if (objectProperties[name] == null)
                {
                    var prop = GetType().GetTypeInfo().GetDeclaredProperty(name);
                    result = prop.GetValue(this);
                }
                else
                {
                    var actualPropertyName = objectProperties[name];
                    var prop = GetType().GetTypeInfo().GetDeclaredProperty(actualPropertyName);
                    result = prop.GetValue(this);
                }

                return true;
            }

            result = null;
            return true;
        }

        private bool TrySetMember(string name, object value)
        {
            var prop = GetType().GetTypeInfo().GetDeclaredProperty(name);
            if (prop != null)
            {
                prop.SetValue(this, value);
                return true;
            }

            dynamicProperties[name] = value;
            return true;
        }

        public void Add(string key, object value)
        {
            TrySetMember(key, value);
        }

        public bool ContainsKey(string key)
        {
            return GetDynamicMemberNames().Contains(key);
        }

        public bool Remove(string key)
        {
            var prop = GetType().GetTypeInfo().GetDeclaredProperty(key);
            if (prop != null)
            {
                prop.SetValue(this, null);
                return true;
            }

            return dynamicProperties.Remove(key);
        }

        public bool TryGetValue(string key, out object value)
        {
            return TryGetMember(key, out value);
        }

        public void Add(KeyValuePair<string, object> item)
        {
            TrySetMember(item.Key, item.Value);
        }

        public void Clear()
        {
            dynamicProperties.Clear();
        }

        public bool Contains(KeyValuePair<string, object> item)
        {
            return dynamicProperties.Contains(item);
        }

        public void CopyTo(KeyValuePair<string, object>[] array, int arrayIndex)
        {
            throw new NotImplementedException();
        }

        public bool Remove(KeyValuePair<string, object> item)
        {
            return dynamicProperties.Remove(item.Key);
        }

        public IEnumerator<KeyValuePair<string, object>> GetEnumerator()
        {
            foreach (var x in dynamicProperties)
            {
                yield return x;
            }

            foreach (var y in objectProperties.Keys)
            {
                yield return new KeyValuePair<string, object>(y, ((dynamic)this)[y]);
            }
        }

        public static T Clone<T>(object obj)
        {
            return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(obj, SerializationSettings), SerializationSettings);
        }

        public static object Clone(object obj)
        {
            return JsonConvert.DeserializeObject(JsonConvert.SerializeObject(obj, SerializationSettings), SerializationSettings);
        }
    }
}

**Comment by GhostAtom** [comment]
Hi, I have the same issue with AzureTableStorage when persisting the state.

@gabog did you managed to fix it ? Thanks

**Comment by drub0y** [comment]
So @gabog originally opened this 17d ago and while that doesn't seem like a long time, there's actually been some pretty significant changes to the storage implementations in that timeframe. For example, `StoreItem` and `FlexObject` have not existed since before the //Build conference timeframe, so if you're using the latest `4.0.1-preview` version of the packages then you shouldn't even be working with these type any more.

So, first things first, can I ask you guys to make sure you're updated to that version and then let me know if this is still an issue? You wouldn't inherit from `FlexObject` any more, you would just declare your own POCO. If you need the flexibility of a dictionary to store arbitrary key/value pairs, just put a property on your POCO of type `Dictionary<K, V>` and that _should_ work.

As for the `AzureBlobStorage` exception specifically, it looks to me like you might be debugging with "first chance" exceptions turned on??? In the scenario there it's looking for the blob, but the blob does not yet exist, so that will raise the `StorageException` which, as you can see, we are watching for with a `catch` and checking if it's a `NotFound` status code... which it should be in this case. In this scenario you should ultimately just get back new instance of your POCO.

**Comment by cleemullins** [comment]
+1 to what @drub0y has said. The Azure Storage code has had several key bug fixes this past week. There's a chance it's already fixed. 

@gabog - The removal of FlexObject from your code would be a good place to start. The serialization behavior of that is non-standard and may be conflicting with other serialization that's happening. We've removed this from the SDK, and settled on standard POCOs to make things more clear.

**Comment by GhostAtom** [comment]
@cleemullins how do you manage the the POCO initialization with _dc.ActiveDialog.State_? By passing it to the constructor? Do you have a working example with the last version of the package? Thanks

**Comment by GhostAtom** [comment]
I fixed my issue by updating the package and using each time the conversation/user state service to retrieve the POCO. And when it's not possible ie with the dialog.CreateContext() method, by adding an _explicit operator Dictionary<string, object>(UserState state)_  to cast the POCO. Hope that would help someone.

**Comment by mcinnes01** [comment]
Hi

I am also experiencing this issue, I've got the latest master branch and have just tried with the AlarmCards example, referencing the Microsoft.Bot.Build.Azure project from within the solution to ensure I am using the latest versions. This was a good test for me as I am using topics in my actual project.

I've updated the two state objects to implement a Dictionary<string, object> as below and still get the issue reported above when using AzureTableStorage:

```
    /// <summary>
    /// Object persisted as conversation state
    /// </summary>
    public class ConversationData : Dictionary<string, object>
    {
	    public const string ActiveTopicKey = "activetopic";

	    public ConversationData()
	    {
		    this[ActiveTopicKey] = null;
	    }

	    public ITopic ActiveTopic
	    {
		    get => (ITopic) this[ActiveTopicKey];
		    set => this[ActiveTopicKey] = value;
	    }
    }

    /// <summary>
    /// Object persisted as user state 
    /// </summary>
    public class UserData: Dictionary<string, object>
    {
	    public const string AlarmsKey = "alarms";

	    public UserData()
	    {
		    this[AlarmsKey] = null;
	    }

	    public IList<Alarm> Alarms
		{
		    get => (IList<Alarm>)this[AlarmsKey];
		    set => this[AlarmsKey] = value;
	    }
    }
```
Here is my startup configuration:

```
	            var connection = Configuration.GetConnectionString("StorageConnectionString");

	            IStorage conversationStore = new Microsoft.Bot.Builder.Azure.AzureTableStorage(connection, "botconversationdata");
	            middleware.Add(new ConversationState<ConversationData>(conversationStore));

	            IStorage userStore = new Microsoft.Bot.Builder.Azure.AzureTableStorage(connection, "botuserdata");
	            middleware.Add(new UserState<UserData>(userStore));
```

I had previously had this working with dialogs, but topics seem to be a problem, so not sure if I'm just missing something or if its the serialisation of ITopic that's causing the issue?

Many thanks

Andy

**Comment by drub0y** [comment]
@mcinnes01 Instead of inheriting from `Dictionary<K, V>` can you try just having a property of `Dictionary<K, V>` hang off your `ConversatioData` and `UserData` classes?

**Comment by mcinnes01** [comment]
Hi @drub0y 

Sorry for my ignorance I don't follow, please could you show me what you mean in reference to the alarms example above?

The only time I got the azure table storage to work was following this example: [here](https://github.com/Microsoft/botbuilder-dotnet/blob/master/samples-final/5.AspNetCore-MultiplePrompts-Bot/MultiplePromptsState.cs) 

I also read a few issues relating to the flattening of lists and there is an open PR: [here](https://github.com/Azure/azure-storage-net/issues/426)

Many thanks

Andy

**Comment by drub0y** [comment]
@mcinnes01 Yeah so the problem is likely that you're storing an `ITopic` in your state. It _might_ be able to persist that, but it wouldn't know what concrete time to re-instantiate when it was deserializing. 

First, to be clear, the `ITopic` stuff is only a sample and not formally fleshed out/supported. It works with `MemoryStore` (of course) and any other store that may so happen to serialize using JSON.NET and utilizes its runtime type recording feature, but `AzureTableStorage` _does not_ serialize to JSON as you know, it's doing property flattening into columns. 

The truth is `ITopic` as it is currently implemented in the sample is not a great design. The `ITopic` should really represent implementation and its state should be maintained separately either as a raw intrinsic type or a POCO.

**Comment by vishwacsena** [comment]
For V4 stable release, we plan on moving table, blob and file storage to samples. Pushing this to backlog but approved work item for now. The goal is to support table storage for persisting state by stable release.

**Comment by gabog** [comment]
OK, thanks @vishwacsena, we are using CosmosDB for now that seems to do what we need, also working on getting rid of FlexObject (we have that as a placeholder while we migrate to the new state management).
Gabo
