### ISSUE TITLE
Intermittent failures for  BotBuilder-DotNet-Functional-Tests-Linux-yaml Edit  Run pipeline

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-dotnet#5300]
## Describe the bug
This pipeline fails intermittently. I believe this is due to Azure service performance/availability degradation of some kind, but can't really tell. 

I manually triggered the pipeline twice and it passed. [1.](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=221576&view=results) [2.](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=221583&view=results)

...then re-ran a lot of the failed ones using "Rerun failed jobs" and they all failed.

Then I manually triggered it again and [it passed](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=221625&view=results).

## Troubleshooting Details

When I first began looking into this, [the errors](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=221056&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=006e6f7c-8314-5e02-a3df-483f3a1f4cfa&l=1478) were:

```
  Failed SendDirectLineMessage [25 s]
  Error Message:
   Assert.AreEqual failed. Expected:<Echo: Testing Azure Bot GUID: e55a76dd-075d-43d5-b96c-32fe3b5a1a7e>. Actual:<>. 
  Stack Trace:
     at Microsoft.Bot.Builder.FunctionalTests.DirectLineClientTests.SendDirectLineMessage() in D:\a\1\s\FunctionalTests\Microsoft.Bot.Builder.FunctionalTests\DirectLineClientTests.cs:line 35
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

After some troubleshooting, it seemed like the most likely cause for this was that the bot wasn't running, so I manually triggered the pipeline with the "Delete Resource Group" step at the end removed (so that I could manually reach out to the bot), and everything worked just fine; the tests passed *and* I could manually reach the bot.

Then, they all started failing again, many of them with [the error](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=221597&view=logs&j=6b902995-b73d-5f5c-66fd-a7f66c857d2c&t=55f72179-45d0-5cb8-1325-e2adff02e68c&l=23):

```
##[error]Details:
##[error]InternalServerError: There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 3dbeef7e-592a-42f3-b4b1-bbe732e342fd
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
```

This is what leads me to believe it was some kind of Azure/Pipelines availability/service issue. An hour or two later and I had another successful manually-triggered run.

**Comment by mrivera-ms** [comment]
@anumoluharish, this is still an issue. We need to take another look.

**Comment by anumoluharish** [comment]
Pipeline was working as expected from last few days.

![image](https://user-images.githubusercontent.com/77343388/112184369-262d6d80-8bcd-11eb-89c4-25c8759def90.png)
