### ISSUE TITLE
Trigger conditions without any actions should not fire

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5305]
## Version

4.12

## Describe the bug

When you create a new dialog in composer it **always** adds an empty `OnBeginDialog` trigger to the dialog. That's fine for 95% of dialogs that want to perform a set of actions when started but there are scenarios where you want a dialog to perform recognition immediately on start.  This will **never** happen in the current code because the empty `OnBeginDialog` trigger gets run and simply causes the dialog to do nothing. To work around the issue today the developer has to manually delete the empty trigger added by composer.

To prevent developers from having to remember to remove the empty trigger we should just update the runtime to have it ignore empty trigger conditions.

**Comment by mrivera-ms** [comment]
@tomlm, @chrimc62, could you please comment on this item?

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
