### ISSUE TITLE
Remove un-needed/wanted turn.activityProcessed logic from AdaptiveDialog class

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5306]
## Version

4.12

## Describe the bug

AdaptiveDialogs are designed to have 2 basic modes of operation. The first is dispatch mode. If your dialog has no `OnBeginDialog` trigger it will attempt to recognize the current message and dispatch the recognized intent. The second is flow mode. If you specify an OnBeginDialog trigger with a set of actions it will run those actions when the dialog is started.  Any attempt to recognize a users utterance as an interruption is deferred until turn-1.

Composer, by defaults, sets up projects to have a single root dispatch dialog and all child dialogs are considered flow dialogs. That works fine in the 95% case but there are scenarios (like forms) where you actually want a child dialog to run in dispatch mode where the users utterance is recognized on turn-0 when the dialog is started.  This is difficult to achieve in composer today for a couple of reasons.

1.   Composer always adds an empty `OnBeginDialog` trigger which the developer must manually remove. Bug #5305 would eliminate the need to do that.
2.  Because of logic that got added about a year ago [here](https://github.com/microsoft/botbuilder-dotnet/blob/c98feb7c58a5564cd8d31bedf050819af70058a3/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs#L492) and [here](https://github.com/microsoft/botbuilder-dotnet/blob/c98feb7c58a5564cd8d31bedf050819af70058a3/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialog.cs#L583) the dialog won't dispatch any incoming activities unless the developer manually sets the `ActivityProcessed` flag to false in their `BeginDilaog` call.

I know why those ActivityProcessed checks were added but I have a couple of issues with them and feel like they should be removed:

1.  If the caller fails to set the `ActivityProcessed` flag to false, starting a dispatch dialog will always result in nothing happening. When would you ever want to call a dialog that does nothing on turn-0? When there is no OnBeginDialog trigger the dialogs event processing logic wants to try and dispatch the current activity but these checks prevent that from happening so execution will stop and should the dialog developer forget to set their `AutoEnd` settings properly the dialog could end which means you now have a dialog that will never do anything as it never makes it to turn-1.
2.  Since the dialog developer can't trust the caller to set the flag properly what they need to do to work around the issues is to add an `OnBeginDialog` trigger that simply calls an `EmitEvent` actions that raises the "activityReceived" event. This essentially does what code in the if block does. @chrimc62 is currently using this as a work around to issues he was hitting with his forms stuff.
3.  My argument against this flag from day 1 was that the caller should not have to have any internal knowledge of the dialogs implementation. The dialog should be a black box to them.  Even more importantly, the dialog implementer should not have to be at the mercy of the caller needing to set a flag in order for them to even function correctly.

There's also an issue that this is a bit of an abuse of what the `turn.activityProcessed` flag was added for, That flag is intended to influence the behavior of an input that's continuing execution after an interruption.  By default, inputs will reprompt anytime there's an interruption but @vishwacsena  wanted to support scenarios where you could have an interruption and still process the users input as if there was no interruption.  Clearing this flag within your interruption achieves that behaviour.  It was never intended to have an influence on what dialogs/prompts do when they're starting.

My proposal is that we remove the 2 checks above and simply let the AdaptiveDilaog follow its normal dispatching rules based off the triggers registered for the dialog. Additionally, we should deprecate and/or remove the `ActivityProcessed` flag on the `BeginDialog` action.  It's dangerous in multiple ways and I don't think its ever going to do what you want it to do.

**Comment by tomlm** [comment]
We had a powow and came to the following conclusion:

*   We should change the default Composer **OnBeginDialog** to have constraint of **\=turn.activityprocessed == true**
*   GUIDANCE/DOCS: If you are a **dispatch dialog** and calling BeginDialog because you are **routing an activity** to a dialog you need to use set the **BeginDialog.ActivityProcessed = false**

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
