### ISSUE TITLE
[Adaptive] ForEach should be able to traverse object keys

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#5316]
## Version

4.12.x

## Describe the bug

At one point, Microsoft.Foreach used to accept iterable objects. This was removed, but provide quite a bit of utility and should come back. 

## Expected behavior

I want to be able to provide Microsoft.ForEach an object as an import and traverse its keys and have access to the key and the value for additional computation.

**Comment by mrivera-ms** [comment]
@boydc2014 to investigate.

**Comment by boydc2014** [comment]
Microsoft.Foreach doesn't support iterating on object, it was the built-in foreach function that support object. So re-label this as a feature request.

**Comment by chrimc62** [comment]
This has more details on how to do this. https://github.com/microsoft/botbuilder-dotnet/issues/5619
