### ISSUE TITLE
When receiving a slack payload, the Activity's From.Id is the BotId instead of the user's Id

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/botbuilder-dotnet#5323]
## Version
4.12

## Describe the bug

I have a bot with adaptive dialogs created with Bot Framework Composer. 
There's a ChoiceInput in the dialog.
I modified the slack adapter ActivityToSlack method to transform that to a Block Kit json so that the slack client can display it correctly and with buttons (planning on creating a PR to incorporate that to the adapter once everything is working)

Everything works fine regarding the choice input. The bot understands the click of the button, picks the correct choice out of the provided one and it's internal logic respects that choice.

The next step of the bot is to store that value in the user's memory scope and here's where the problem appears. In the emulator everything works fine, but with the slack adapter it doesn't get stored.
Debugging I realized that the value was being stored under the bot's memory scope and not the user's. Looking at the adapter code I found that [PayloadToActivity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs#L155) is assigning the botId to the From.Id property of the activity:

```
var activity = new Activity()
            {
                Timestamp = default,
                ChannelId = "slack",
                Conversation = new ConversationAccount()
                {
                    Id = slackPayload.Channel.id,
                },
                From = new ChannelAccount()
                {
                    Id = slackPayload.Message?.BotId ?? slackPayload.User.id,
                },
                Recipient = new ChannelAccount()
                {
                    Id = null,
                },
                ChannelData = slackPayload,
                Text = null,
                Type = ActivityTypes.Event,
                Value = slackPayload
            };
```

Is this because of some convention or a special reason? 

## Expected behavior
If the button was pressed by the user, then I'd expect the activity to come from the user and not the bot.

**Comment by stevkan** [comment]
@martinlarosa, I'm unable to repro the issue you are encountering. The `From.Id` property is showing as coming from the user and not the bot in my attempts. Can you share the code you are using that I can make an attempt with? Please include the modified Slack adapter you also reference.

**Comment by martinlarosa** [comment]
I was able to reproduce it with this sample code: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/60.slack-adapter

No modification of the adapter.
Run de bot, send the slash command: /block 
It will return a sample message with some restaurants and buttons at the end. 
Put a breakpoint in OnMessageActivityAsync
Press one of the buttons for the restaurants, when the breakpoint get hit inspect turnContext.Activity.From.Id, you'll see that the value is not your slack user Id but the Bot Id that starts with a B

**Comment by stevkan** [comment]
@martinlarosa, thank you for your patience. I'm still unable to repro the issue. I'm going to reach out to a colleague to see if they see the same or not.

Regarding the PR, it will be reviewed for consideration.

**Comment by stevkan** [comment]
I was finally able to reproduce the issue you are seeing. Since the contained "message" is usually the focus, I can see why the logic's preference is to take the bot's Id to be applied to the `From` property. However, I believe you are correct that it should favor the user clicking the button vs. the originator of the message (in this case, the bot).

As I mentioned, the PR will be reviewed. At the moment, we are in the midst of releasing v4.13 of the SDK. So, consideration won't be given until this process finishes.

**Comment by martinlarosa** [comment]
Thank you, let me know if I can be of any help.

**Comment by msomanathan** [comment]
@mrivera-ms Could you please take a look at this issue and let us know how to take the PR forward.
