### ISSUE TITLE
Sanitize potential PII in SetProperty Json Parse Exceptions

### ISSUE THREAD

**Issue by boberg-ms** [microsoft/botbuilder-dotnet#5328]
When executing a SetProperty event, the author can specify json extraction from another property.  When this extraction fails due to json parse exception, the thrown exception message appears to contain the entire json content.  This content will likely be considered PII, so we have to manually sanitize it right now.  If the framework could sanitize the exception message and have a separate property that contains the current message with all necessary debugging information, that would be ideal.

**Dialog Sample:**

        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "NWf97m"
          },
          "property": "dialog.JsonPayload",
          "value": "{   \"userName\": \"Charles\",   \"favoriteSandwich\": \"Ham an\\ }"
        },
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "gOOXPf"
          },
          "property": "dialog.userName",
          "value": "${json(dialog.JsonPayload).userName}"
        },

**Exception message:** 

Expression evaluation resulted in an error. Expression: =`${json(dialog.JsonPayload).userName}`. Error: Unexpected character at Path favoriteSandwich, line 1, position 58 when parsing {   "userName": "Charles",   "favoriteSandwich": "Ham an\ }.

**Comment by boydc2014** [comment]
Hi, @boberg-ms, OnError trigger is designed for situations like this, once you specify an onError trigger, the exception will be wrapped up into turn.dialogEvent property instead of poping up in the chat window. 

I assume you are using Composer, given the example you showed above. To create an onError trigger in Composer, here is the steps, 
* create trigger => dialogEvent => error
* in the trigger, create an SendActivity, or any other logic you want to specific


![image](https://user-images.githubusercontent.com/3829387/115329269-a9d67c00-a1c4-11eb-9c9f-623500f898ef.png)

![image](https://user-images.githubusercontent.com/3829387/115329299-b529a780-a1c4-11eb-851d-e55fc693530c.png)
![image](https://user-images.githubusercontent.com/3829387/115329485-f6ba5280-a1c4-11eb-8756-b7c11bd5c901.png)

**Comment by mrivera-ms** [comment]
@boberg-ms, could you please review the reply above and let us know if this works?

**Comment by boberg-ms** [comment]
Hi,

This does not solve the issue for us.

For our scenario, customers are generating their own dialogs within composer, and then we're hosting and executing them within our Power Virtual Agent bot framework.  We cannot guarantee that customers have set up an Error event to handle the exceptions.  Properties in their dialogs, particularly json properties that could be the result of a flow/http call to get account data, for example, we have to assume contain PII unless they specifically output it within a send message event.

We currently log all exception messages for diagnostic purposes, but need to sanitize these particular exception messages before doing so.  It is not easy for us to predict or handle all of these types of exceptions.  We may also send the detailed exception message to the C1 customer that authored the bot, so it is valuable to surface the full parse exception message for them to debug, so we still want the ability to get the actual full message in some cases.  This is why we suggested potentially a different property on the exception.

Let us know if we can answer any more questions or if you have any other workarounds.  Thank you.

**Comment by boberg-ms** [comment]
Actually, we may be able to specify our own ErrorHandler on the root dialog and override any handler created by the customer, just on the root dialog.  I will sync up with my team this afternoon to look into that.

**Comment by mrivera-ms** [comment]
@boberg-ms, are there any updates on this?

**Comment by boberg-ms** [comment]
We're still confirming.  Will give an update later today.

**Comment by boberg-ms** [comment]
I don't think this is going to work for us.  It let's us get the exception information, but we already have access to that.  Sorry for the late response on this, some of us were out of office last week.

**Comment by gabog** [comment]
@boydc2014 / @boberg-ms, would removing the json string (args[0]) in the line @EricDahlvang pointed out above satisfy the requirement? 

I think we are oversharing in our error message and rendering the json may not be ideal (it could also be a large object).

Looking at the native message from JsonReaderException, I think we can just return the err.Message property which will look like:

![image](https://user-images.githubusercontent.com/12264946/119871970-f6faeb80-bef0-11eb-91c3-b6e39c48f785.png)

It doesn't show up the json, it gives you info on the line and column and the path to the property that couldn't be parsed (no customer data there)

**Comment by boydc2014** [comment]
> @boydc2014 / @boberg-ms, would removing the json string (args[0]) in the line @EricDahlvang pointed out above satisfy the requirement?
> 
> I think we are oversharing in our error message and rendering the json may not be ideal (it could also be a large object).
> 
> Looking at the native message from JsonReaderException, I think we can just return the err.Message property which will look like:
> 
> ![image](https://user-images.githubusercontent.com/12264946/119871970-f6faeb80-bef0-11eb-91c3-b6e39c48f785.png)
> 
> It doesn't show up the json, it gives you info on the line and column and the path to the property that couldn't be parsed (no customer data there)
> 
> in other words the catch should look something like:
> 
> ```cs
> catch (JsonReaderException err)
> {
>      error = err.Message;
> }
> ```

This would probably satisfy the requirement of sanitizing the information, but as customer said above, in some case, they still need the full information.  I'm not sure, @boberg-ms what do you think?

**Comment by boberg-ms** [comment]
> 
> 
> @boydc2014 / @boberg-ms, would removing the json string (args[0]) in the line @EricDahlvang pointed out above satisfy the requirement?
> 
> I think we are oversharing in our error message and rendering the json may not be ideal (it could also be a large object).
> 
> Looking at the native message from JsonReaderException, I think we can just return the err.Message property which will look like:
> 
> ![image](https://user-images.githubusercontent.com/12264946/119871970-f6faeb80-bef0-11eb-91c3-b6e39c48f785.png)
> 
> It doesn't show up the json, it gives you info on the line and column and the path to the property that couldn't be parsed (no customer data there)
> 
> in other words the catch should look something like:
> 
> ```cs
> catch (JsonReaderException err)
> {
>      error = err.Message;
> }
> ```

Yes, I think this would solve the issue for us.
