### ISSUE TITLE
CoreBotAdapter is missing EoC logic (Root bot)

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#5330]
CoreAdapterBot should include the End of Conversation handling demonstrated by sample 81
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/81.skills-skilldialog

## Implementation notes
To implement this we need to have a way of knowing in the adapter.OnTurnError() if the root bot is talking to a skill (or many skills) and add logic to send EoC for the skills that are part of the current conversation.

OnTurnError only exposes TurnContext so we may need to use that to determine the status of dialog stack and see if there are skills involved at the time of the error.

**Comment by Stevenic** [comment]
The problem @johnataylor is that you need to know if there are any active dialogs in order to automatically send an EoC activity.  That sample has an assumption that you're using our dialog system and AdapterCoreBot doesn't. Correct?

How do we know when to send EoC for core bot?

**Comment by mrivera-ms** [comment]
@johnataylor is this still in scope for R13?

**Comment by tracyboehrer** [comment]
@Stevenic Via SkillConversationReferenceKey?

**Comment by mrivera-ms** [comment]
Discussed with @gabog, this is not going to be delivered in R13.

**Comment by johnataylor** [comment]
See comments in linked issue.

**Comment by johnataylor** [comment]
Perhaps we should be moving error handling like this into the bot and not attempt to do it in the adapter global OnError
