### ISSUE TITLE
Adaptive runtime should make it easy to override the ConversationState

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#5331]
There are a couple of scenarios where the developer might like to override the default ConversationState class with one of their own or as @EricDahlvang points out perhaps with something like TeamsConvesrationState.

Currently this is really hard, basically you'd have to replace the runtime. We should make this easy, so, for example, you can add a package that provides an alternative. There are a couple of ways to do this. One way (though perhaps not the best way) would be to use the ASP Dependency Injection mechanism and TryAdd it. Alterantively we could just rely on the IBot object applying the default if it isn't given one.

**Comment by johnataylor** [comment]
Perhaps we could make this P2. This is something we could add later.

**Comment by tracyboehrer** [comment]
@johnataylor Why wouldn't just 'services.AddService<ConversationState, MyConversationState>()' work?  It did for me.  What am I missing?

**Comment by Stevenic** [comment]
What you really want is a new "teams" memory scope. To do that you need to be able to update the list of memory scopes the state manager loads. Here's an example of doing that:

```c#
using AdaptiveExpressions;
using Iciclecreek.AdaptiveExpressions;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
using Microsoft.Bot.Builder.Dialogs.Debugging;
using Microsoft.Bot.Builder.Dialogs.Declarative;
using Microsoft.Bot.Builder.Dialogs.Declarative.Resources;
using Microsoft.Bot.Builder.Dialogs.Memory;
using Microsoft.Bot.Builder.Dialogs.Memory.Scopes;
using Microsoft.BotFramework.Composer.CustomAction;
using MSMeeting.SharedActions.Memory.Scopes;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MSMeeting.SharedActions
{
    public class MSMeetingComponentRegistration : ComponentRegistration, IComponentDeclarativeTypes, IComponentMemoryScopes
    {

        public IEnumerable<MemoryScope> GetMemoryScopes()
        {
            yield return new SkillMemoryScope();
            yield return new DataMemoryScope();
        }
    }
}
 
```
