### ISSUE TITLE
Circular package ref in 4.12 prevents you from being able to update from 4.11 packages

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5333]
## Version

4.12.2

## Describe the bug

I tried updating my projects packages from 4.11 to 4.12 but it fails because of a dependency error.  I tracked it down to the fact that `Bot.Builder.AI.Luis` now has a reference on `Bot.Builder.DIalogs.Adaptive.Declarative`.  The issue is that package has a reference on `Bot.Builder.Dialogs.Adaptive` which has a reference on `Bot.Builder.AI.Luis`.

I was able to work around the issue by manually updating all of the package versions in the csproj file to "4.12.2".

**Comment by EricDahlvang** [comment]
I think this is a composer runtime issue, and would be fixed with: 
https://github.com/microsoft/BotFramework-Composer/pull/6506/

**Comment by mrivera-ms** [comment]
Closing this as it is being addressed by Composer.
