### ISSUE TITLE
QnA Maker Regex is problematic and will often fail

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#534]
- Cut and paste can introduce formatting problems (extra spaces.)
- Multi-line escaped strings in code are more awkward than useful. We are expecting the programmer to format and escape this somehow?

Overall the feature seems to be more trouble than it is worth. Suggest removing feature.

**Comment by johnataylor** [comment]
and for consistency remove from JavaScript implementation as well

**Comment by yochay** [comment]
@johnataylor did you end up removing this form the code? If not do it.

**Comment by yochay** [comment]
@Stevenic verify the core was removed from JS https://github.com/Microsoft/botbuilder-js/issues/281
