### ISSUE TITLE
Allow package prefixes in LG imports and handle templates naming conflicts

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#5341]
This is a sub-ticket to #5298 which contains everything needed to enable package prefix on resource level.

This sub-ticket is to track the effort on LG side, 
* support the package prefix in LG statement, like `[import](package.name#lg.name)` 
* handle naming conflicts of LG templates, by giving an name\alias when importing, like `[import](package.name#lg.name) as foo`, this will allow calling the conflicted template inside the imported LG file, like foo.Welcome()

detailed design is in the original ticket and doc.

**Comment by mrivera-ms** [comment]
@boydc2014, per our conversation, this must be shipped in R13, therefore classifying as P0. Please change if not appropriate.
