### ISSUE TITLE
Adopt component detection in CI pipeline 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#5354]
SDK repo should adopt the "component detection" to detect high risk dependencies. Like Composer does https://github.com/microsoft/BotFramework-Composer/pull/6547/checks?check_run_id=2188768283. 

This will help SDK catch high-risk dependencies earlier and help prevent shipping it to customers including Composer.

**Comment by BruceHaley** [comment]
This issue is fixed in PR #5695. However, the PR is not merged until the 5 detected critical and high severity vulnerabilities are fixed. Those 5 issues are listed above.

**Comment by BruceHaley** [comment]
All 5 vulnerabilities listed above have been resolved. Specifically, they have been dismissed. There should now be no barriers to merging PR #5695
