### ISSUE TITLE
Profile Adaptive Dialog Stack

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#5415]
We need to run a profiler over the Adaptive stack for common scenarios. 

This tracking issue is to identify key hotspots and fix any low-hanging fruit. Larger areas identified should be separately identified.

**Comment by Stevenic** [comment]
This should be done against both C# and JS as the perf issues will likely be different for both. From my experience I see we spend the bulk of our time in Antlr for C# due to all of the expression parsing we do.

**Comment by Stevenic** [comment]
Seems like we may not be caching as much as we can

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
