### ISSUE TITLE
Update KeyVault dependency

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5417]
It looks like the package we're using has been split, and is no longer being maintained. This package also creates an annoying build warning. Can we update to whichever of the 3 new packages that replaces this one, and make the build warning go away?

https://www.nuget.org/packages/Microsoft.Azure.KeyVault.Core

**Comment by mrivera-ms** [comment]
The KeyVault dependency exists in library Microsoft.Bot.Builder.Azure and is associated with classes [AzureBlobStorage](https://github.com/microsoft/botbuilder-dotnet/blob/667e0cea22ae60c87bdf4353b876bf5b565c9a4a/libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs#L31) and [AzureBlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/667e0cea22ae60c87bdf4353b876bf5b565c9a4a/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs#L23). These classes are deprecated and may be removed from future versions of the SDK so we will not do further updates. The warnings are suppressed and do not appear at build time. They may need to be suppressed in Composer projects if they appear as well. 
Closing this issue as no further action required.
