### ISSUE TITLE
"The reader's MaxDepth of 32 has been exceeded" on nested dialogs when calling skills in EA template

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botbuilder-dotnet#5423]
## Version
4.13-rc1

## Describe the bug
When calling a skill with nesting dialogs, under certain circumstance the skill would return the following error:

"Operation returned an invalid status code ‘BadRequest’"

Debugging into the SDK, this seems to be an issue in Conversation.ReplyToActivityWithHttpMessagesAsync() where it's getting the following error from the skills endpoint of the root bot.

`{"errors":{"value.conversation.DialogState.dialogStack[0].state._adaptive.actions[0].dialogStack[0].state._adaptive.actions[0].dialogStack[0].state._adaptive.actions[0].dialogStack[0].state._adaptive.actions[0].dialogStack[0].state.options.choices.value":["The reader's MaxDepth of 32 has been exceeded. Path 'value.conversation.DialogState.dialogStack[0].state._adaptive.actions[0].dialogStack[0].state._adaptive.actions[0].dialogStack[0].state._adaptive.actions[0].dialogStack[0].state._adaptive.actions[0].dialogStack[0].state.options.choices', line 1, position 627932."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|258023c5-49ff8bf3d9391cb0.3.e5672d95_20.258023d3_"}`

Secondary, this seems to be a problem with the way errors are surfaced in the SDK that seems opaque to the end user or the developer. In this case, unless the developer enable ServiceClientTracing somehow there wouldn't be any detailed error surfaced.

A workaround is to move certain dialogs nested into the dialog above, but this would not be ideal as we don't really know what the typical end users do. 

A "fix" to this issue is to remove the limit in the Startup.cs of the bot:
From:

            `services.AddControllers().AddNewtonsoftJson();`

To:
            `services.AddControllers().AddNewtonsoftJson(options => options.SerializerSettings.MaxDepth = null);`

Where the NULL effectively removes all limit. But not sure if that's a wise thing to do either.

## To Reproduce

![image](https://user-images.githubusercontent.com/9922190/113448273-5e446580-93b0-11eb-9a88-357a49d71ab3.png)

Json from the payload to the skill endpoint on the root bot:
[ErrorJson.txt](https://github.com/microsoft/botbuilder-dotnet/files/6251015/ErrorJson.txt)

## Expected behavior
No error

## Screenshots
See above

**Comment by sgellock** [comment]
@thomas-chung, I'm assigning this back to you.  close it out if you feel you have a solution on your side.  unless of course you think it's an SDK issue, then we'll pick it up again.

**Comment by thomas-chung** [comment]
Closing for now given the solutions we have on our side.
