### ISSUE TITLE
Publish Adaptive.Teams package with correct tags

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5428]
This package needs to be republished with the new tags so that it is available in Package Manager in Composer.

Should be tagged:

- msbot-component
- msbot-action
- msbot-trigger

**Comment by carlosscastro** [comment]
I think this is already correct: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams.csproj#L18

**Comment by carlosscastro** [comment]
Csproj not reflected in nuget: https://www.nuget.org/packages/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/4.12.2-preview

**Comment by carlosscastro** [comment]
Reflected here correctly: https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.Dialogs.Adaptive.Teams/4.13.0-rc3.preview
