### ISSUE TITLE
SchemaMergeTest (350) all fail on new installation

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#5453]
There appears to be something broken with the SchemaMergeTest failing. New machine, new installation of Visual Studio, new enlistment, new build and from the top test run and all the SchemaMergeTest (350) report failure.

Is there some missing dependency?

**Comment by chrimc62** [comment]
@johnataylor are you still seeing this?  Did your machine have npm and node installed?
