### ISSUE TITLE
[OAuthCard] TokenExchangeResource property is missing JsonProperty attribute name

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/botbuilder-dotnet#5460]
## Describe the bug
When a .NET skill bot sends an OAuthCard to a JS host bot, the card is not deserialized properly because the [TokenExchangeResource](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/OAuthCard.cs#L57) property is received in uppercase.
The property is missing the _JsonProperty name_ that the other properties have.

## Expected behavior
All OAuthCard properties should be in lowercase.

## Screenshots
This image shows the OAuthCard as an activity's attachment with the _TokenExchangeResource_ with uppercase.
![image](https://user-images.githubusercontent.com/44245136/113870696-7dfcd480-9788-11eb-94b6-05ff9bbab02e.png)

**Comment by johnataylor** [comment]
@swagatmishra2007 @Jeffders @carlosscastro can you comment? thanks

**Comment by johnataylor** [comment]
@ceciliaavila thanks for find (and fixing) this, can you be specific about what is broken here, as we'd like to understand the impact and whether we need to include it in R13.

Are the following statements true?

- if I have a C# parent bot using a C# skill then everything is fine
- if I have a C# parent bot using a JS skill then everything is also fine
- if I have a JS parent with a JS skill then everything is fine
- **if I have a JS parent with a C# skill then this is an issue**

**Comment by ceciliaavila** [comment]
> @ceciliaavila thanks for find (and fixing) this, can you be specific about what is broken here, as we'd like to understand the impact and whether we need to include it in R13.
> 
> Are the following statements true?
> 
> * if I have a C# parent bot using a C# skill then everything is fine
> * if I have a C# parent bot using a JS skill then everything is also fine
> * if I have a JS parent with a JS skill then everything is fine
> * **if I have a JS parent with a C# skill then this is an issue**

Hi @johnataylor, those statements are true, we have the issue only when the parent is a JS bot and the skill is a C# bot. 
In the SSO scenario, when the parent intercepts the OAuth card sent by the skill to exchange the token, it breaks due to a property in uppercase.
