### ISSUE TITLE
TeamsActivityHandler: 429 too many requests when adding an AD group to a team

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/botbuilder-dotnet#5467]
When using this TeamsActivityHandler and then adding an Active Directory group to a Team where the bot is after around 75 calls to this line, it receives a 429 and then the bot throws an exception.

https://github.com/microsoft/botbuilder-dotnet/blob/fbb4eb8b98ccce17ebcfc8e061237def33a68305/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L516

Ideally I would like to not have an exception and that the throttling happens appropriately. But maybe there's also a workaround for my scenario? I just care about overriding OnTeamsMembersAddedAsync to detect when the bot is added to the Team, so actually this loop through all the added members is unnecessary for my goal. Is there a different way of achieving this and circumventing the bug.

**Comment by martinlarosa** [comment]
My workaround since I don't need to know anything about the new members (for now) except that my bot is one of them: Override `OnTeamsMembersAddedDispatchAsync` instead of `OnTeamsMembersAddedAsync` and do:
```
if (membersAdded.Any(m => m.Id == turnContext.Activity.Recipient.Id))
{
    await AddConversationReference(turnContext.Activity as Activity, teamInfo);
}
```

**Comment by clearab** [comment]
@Wajeed-msft  can you take a look at this one? It seems like maybe the add AAD Group path to a team is not resulting in a fully hydrated Teams Channel Account object being sent to the bot (which is what is triggering the second call to retrieve the full set of user info).

**Comment by clearab** [comment]
@martinlarosa are you seeing calls to this line when you manually add a single user through the Teams client?

**Comment by tsuwandy** [comment]
@Wajeed-msft, did you have a chance to look into this issue?

**Comment by martinlarosa** [comment]
hey @clearab sorry for the late response, I don't have a code right now deployed that could test that.

**Comment by clearab** [comment]
This is being tracked by the Teams group here: https://github.com/MicrosoftDocs/msteams-docs/issues/3250
