### ISSUE TITLE
Auth flow support for adaptive cards (1.4)

### ISSUE THREAD

**Issue by kaerm** [microsoft/botbuilder-dotnet#5468]
See [parent](https://github.com/microsoft/botframework-sdk/issues/6255)

**Comment by cleemullins** [comment]
This issue tracks with https://github.com/microsoft/botframework-sdk/issues/6255 which is being tracked by @Stevenic

**Comment by mrivera-ms** [comment]
Per conversation with @Stevenic, the investigation phase of this item is complete. We will move it to R15 to track the execution part.

**Comment by mrivera-ms** [comment]
Reviewed by the SDK team. Closing as Not Needed.
