### ISSUE TITLE
CloudAdapter - cannot call ContinueConversationAsync with an empty / null AppId

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-dotnet#5491]
## Version
4.13.0

## Describe the bug
Previously we were able to call ContinueConversationAsync with a null or empty appId, when developing locally and this worked fine.  Now though, there is an exception being thrown if the app Id is null or empty.https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs#L144

This is causing friction for the handoff packages, meaning we will need to force users to set an AppId to ensure the package does not throw an error, even if they are only working locally.

Arguably this could be classified as a backwards compat issue, given this could break existing code that is using the BotAdapter base class.

## Expected behavior
ContinueConversationAsync should work with a null or empty AppId

cc @johnataylor @carlosscastro this is the issue we were discussing.

**Comment by cleemullins** [comment]
Shipping in 4.13.1
