### ISSUE TITLE
Runtime: Expose method to do the component loading only for non-web projects

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#5494]
@tomlm ran into needing to run this method separately for console bots: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime/Extensions/ServiceCollectionExtensions.cs#L94

We should have a non-http sample of how to consume the runtime also.

**Comment by tracyboehrer** [comment]
No plans to implement this
