### ISSUE TITLE
NullReferenceException when calling CreateReply method in Activity.cs with null From property

### ISSUE THREAD

**Issue by saipraneeth888** [microsoft/botbuilder-dotnet#5499]
## Version
4.10

## Describe the bug
NullReferenceException being thrown when calling CreateReply method in Activity.cs with empty From(recipient) property
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Schema.Activity.CreateReply(String text, String locale)

## To Reproduce
1. Create an Activity class with empty or default From property 
2. Call CreateReply method on that Activity object
3. Run the testcase or sample code

## Expected behavior
No exception thrown during runtime

**Comment by GeoffCoxMSFT** [comment]
@EricDahlvang Could you kindly take a review of the PR to fix this issue?
