### ISSUE TITLE
The "Greeting" trigger isn't a greeting

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5502]
## Describe the bug

The "Greeting" label on the ConversationUpdate trigger is misleading. ConversationUpdate events are not limited to memberAdded events, they include at least the list here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=csharp#teams-conversation-update-activities

The label for this shouldn't be "Greeting"

## Version

Any

## Browser

Any

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

Any

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot
2. Add an Activity trigger
3. View the name of the ConversationUpdate trigger.

**Comment by mareekuh** [comment]
Ok let's change it to Conversation Update. 
I don't believe that at the time we named this activity all these other use cases were available, so I agree that 'greeting' is not accurate to summarize the current capabilities. Also - in searching customer feedback if we had complaints about this issue I did indeed find one customer comment.

So here's what needs to happen:
1. In the 1st dropdown 'Type of trigger', add 'Conversation update'
2. In the 2nd dropdown
- Remove 'Greeting (Conversation Update activity)
- Show the list of ConversationUpdate flavors to choose from:
- channelCreated 
- channelDeleted 
- channelRenamed 
- channelRestored
- membersAdded (MS Teams)
- membersRemoved (MS Teams)
- teamArchived (MS Teams)
- teamDeleted (MS Teams)
- teamRenamed (MS Teams)
- teamRestored (MS Teams)

If 'Teams' channel not enabled, do not show the activities for MS Teams
-

**Comment by clearab** [comment]
We can put all the channel-specific versions in the package for that channel so they aren't available by default.

**Comment by clearab** [comment]
There really are only 2 that need to be included by default I believe - members added and members removed.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
