### ISSUE TITLE
Telegram channel - method sendMediaGroup

### ISSUE THREAD

**Issue by stas-sultanov** [microsoft/botbuilder-dotnet#5505]
**Is your feature request related to a problem? Please describe.**
The problem is that I am trying to send several images as one messag via Telegram Channel.
But can not succed because bot framework does no support Telegram specfic method sendMediaGroup

**Describe the solution you'd like**
Telegram channel  start support method [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup)

**Describe alternatives you've considered**
There is no alternatives.

**Additional context**
sendMediaGroup is not listed in the bot documentation [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-channeldata?view=azure-bot-service-4.0#create-a-telegram-message)

**Comment by EricDahlvang** [comment]
Hi @stas-sultanov 

Sorry for the late response. This would require updating the Telegram bot framework backend service, and would not apply to the SDK.

If you still wish to pursue this further, please open an issue here: https://github.com/microsoft/BotFramework-Services
