### ISSUE TITLE
Skill handler only supports a single adapter

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#5513]
Skill handler has a hard dependency on a single bot adapter, making it not possible to mix multiple adapters with skills. This happens both for composer and for code-first dialogs. 

The issue is to make changes to allow multiple adapters on a root bot and skills routing to the right adapter.

**Comment by carlosscastro** [comment]
Potential approaches include 1) making skill handler take all the registered adapters or 2) create a multiplexer adapter that contains all adapters and make the runtime use that for multiple adapters. If the multiplexer adapter does the multiplexing, the skill handler can continue to receive the single (multiplexer) adapter and rely on the adapter.

**Comment by tracyboehrer** [comment]
Known limitation.
