### ISSUE TITLE
Support multiple workspaces with a single Slack Adapter

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/botbuilder-dotnet#5519]
Failing to find any example nor a way to do it with the current slack adapter code, I'm assuming that the dotnet slack adapter can only work with one slack workspace. I want to be able to install the app into multiple workspaces without having to spin up multiple backend services or instantiate multiple slack adapters

I believe the js slack adapter supports this, can this be ported over?

https://botkit.ai/docs/v4/platforms/slack.html#multi-team-support

**Comment by mdrichardson** [comment]
Thanks for the suggestion, @martinlarosa. I'll be looking into this in the next couple of weeks.

**Comment by martinlarosa** [comment]
Hi @mdrichardson !
It's great that you can dedicate a bit of time into this. I have some modifications to the adapter for validating incoming requests and sending messages to multiple workspaces,
I'll be creating a PR so you can take inspiration on it and/or give feedback. 

It doesn't include the OAuth installation process since I do that outside of the bot.

**Comment by mdrichardson** [comment]
@martinlarosa I dove into this pretty deeply and it looks like the SlackAdapter will need a fair amount of work in order to support multiple workspaces. We've got a some design changes in the pipeline for this adapter, so I'm going to put this on hold until we work those out as this may either conflict with or become part of those design changes. That said, this is still on my priority list.

**Comment by martinlarosa** [comment]
@mdrichardson I added a PR so you can take a look at what I did hoping it would help.

**Comment by mdrichardson** [comment]
@martinlarosa FYI: We're in the design stages of thinking up a new default adapter that multiplexes all the http requests to the appropriate route/adapter. It's meant to be a much broader fix to the "how do we get skills to work with multiple adapters" problem. It *probably* won't make it into this release, but it's a pretty high priority, still. Just wanted to keep you updated.

**Comment by wany23** [comment]
Hello @mdrichardson , has this been implemented?

**Comment by wany23** [comment]
thanks for the very quick response and info!
