### ISSUE TITLE
Thread starvation due to blocking thread in PayloadSender.WritePacketAsync()

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#5523]
https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Streaming/PayloadTransport/PayloadSender.cs#L151-L153

**Comment by tracyboehrer** [comment]
This version of the library was deprecated.
