### ISSUE TITLE
People template bot producing a "SignoutUser(): not supported by the current adapter" message

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#5528]
## Version
What package version of the SDK are you using: Whatever version the nightly build of Composer is using, presumably v4.13.

## Describe the bug
Give a clear and concise description of what the bug is.
This interaction seems...odd.
![image](https://user-images.githubusercontent.com/35047199/115794645-34fd7080-a383-11eb-94dd-3fe95c63db5f.png)

## To Reproduce
1. Create, configure, and publish a vanilla **People** bot, starting in Azure with an Azure Bot resource.
2. Test in web chat in Azure.
3. Republish from Composer
4. Retest in Azure in Web Chat.
5. Error: See preceding screenshot.

## Expected behavior
The default People bot should produce explicable responses.

## Screenshots
![image](https://user-images.githubusercontent.com/35047199/115794891-b1904f00-a383-11eb-90ff-c7cbb4c68e6f.png)

## Additional context
Ran into this as part of the ABS bug bash on 4/22.

**Comment by thomas-chung** [comment]
Hey @johnataylor after talking with @carlosscastro he recommend transferring this issue to you as it seems like the SignoutUser action did not handle the new CloudAdapter properly.

**Comment by carlosscastro** [comment]
Technical notes: When the cloud adapter was introduced, all the paths that casted the adapter to IUserTokenProvider were updated to do 1) if CloudAdapter -> new flow 2) if IUserTokenProvider -> old flow 3) other -throw. We need to do the same with the SignOutAction

**Comment by johnataylor** [comment]
yes its a straight forward fix, either including the same code as the OAuthPrompt or call OAuthPrompt to do the work, as the OAuthInput does.

**Comment by cleemullins** [comment]
Shipping in 4.13.1

**Comment by RamkumarManavalan** [comment]
I am using 4.14.1, but I get the same error in Bot Framework Emulator (v 4.14.1). Could someone please help? I use the "Sign out user" option in the Bot Framework Composer (version 2.1.1).
