### ISSUE TITLE
Do not include memory dump in the Emit Trace event by default

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botbuilder-dotnet#5529]
## Version
4.13GA

## Describe the bug
When emitting trace events from skills in the Emulator, the root bot would end up throwing a "Bad Request" because the emit trace events would end up stuffing too much information into the payload and cause the JSON deserialization to fail. That's already _after_ we did the optimization to reduce payload sizes from the Microsoft Graph custom actions implementation.

As a workaround for the PBX team, @lauren-mills added "=null" to the values field for all the Emit Trace event calls so it won't default to stuffing the entire memory scopes into the trace. This seemed to unblock our scenario tests.

Instead, we should by default not have everything stuffed in the emit trace event, and let developers decide which piece of information to trace.

This is also worrisome because if developers are adding skills they should probably understand where the limitations are, and how to mitigate that. Right now, none of the errors or documentations seemed to be useful in explaining the issue without serious debugging.

For the PBX team, we may want to include this in our How-To docs to ensure end users why we are doing this.

## To Reproduce
1. Remove "=null" from one of the "Authentication dialogs" in either the People or Calendar skill in EA template
2. Run in emulator

## Expected behavior
No issue.

## Screenshots
HTTP Bad Request returned

**Comment by lauren-mills** [comment]
This appears to be caused by the specifically when a trace is sent from a skill bot to a root bot and reaches a certain depth. The serialization between the skill and root cannot handle the dialog stack object when it has too many layers

**Comment by tracyboehrer** [comment]
Known limitation.
