### ISSUE TITLE
Adaptive expressions should support $ (and other chars) in property keys

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#5537]
## Version
4.13.2

## Describe the bug
You can build adaptive expressions like this `${{ $kind: 'foo'}}`, but they will not be considered valid because of the $.  You can fix this by doing `${{ '$kind': 'foo'}}`, but that is inconvenient and inconsistent with Javascript.  We should allow any characters that do not need to be in quotes or escaped in Javascript.

## Expected behavior
I should not have to quote object keys if I would not have to in javascript.

**Comment by Danieladu** [comment]
`${{ $kind: 'foo'}}` does work in my side. So, could you update your LG/Expression library to check again? Thanks.

**Comment by Danieladu** [comment]
`${{ $kind: 'foo'}}` it works in my side. Could you update LG/Expression sdk to the latest version and have a try? Thanks.

**Comment by chrimc62** [comment]
This works in the library and is related to the vs code extension for errors.

**Comment by Danieladu** [comment]
> This works in the library and is related to the vs code extension for errors.

Thanks for the feedback. We have updated the SDK version in  playground/vscode extension. Next version would works.
