### ISSUE TITLE
Teams users can not open a file in Teams which bot sends them in 1:1 chat

### ISSUE THREAD

**Issue by ahmetkocadogan** [microsoft/botbuilder-dotnet#5542]
## Version 4.13.0

I am sending Excel and PDF files from bot to user in 1:1 chat. It was working well till 22.04.2021. At this date, teams users started to have an issue about opening the file in teams with clicking on FileInfoCard, and they see a message says "this file is deleted or moved"

![image](https://user-images.githubusercontent.com/7287309/116252449-41653d00-a778-11eb-99ee-d9fa4a0e084b.png)

![image](https://user-images.githubusercontent.com/7287309/116251997-d74c9800-a777-11eb-9e30-c767e0037b6e.png)

But when we check that user's onedrive, we can see the file and  able to download and open the file. 

I am not sure if this is an issue about SDK or Teams application, i couldn't find any info about an update / changed code or behaviour for sending files in Teams channel.

Any help or direction appreciated.

Thanks.

**Comment by stevkan** [comment]
@ahmetkocadogan, thank you for your patience. This appears to be an issue with Teams. I am attempting to connect the right person / team with this so they can provide additional support.

**Comment by GeoffCoxMSFT** [comment]
@clearab - Could you add your thoughts on this one?

**Comment by clearab** [comment]
@Wajeed-msft

**Comment by Wajeed-msft** [comment]
This is a bug, we are working on fixing it. We will update this thread once it is fixed.

Internal Bug Tracker: [1744015](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1744015)

**Comment by Mamatha-MSFT** [comment]
Hi @ahmetkocadogan - The bug has been resolved could you please try now.

**Comment by ahmetkocadogan** [comment]
Hello @Mamatha-MSFT  - I tried now and works as expected.

Thank you.

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
