### ISSUE TITLE
[MCS-DE-GO] Timezone extraction does not work in 1.4.0 Bot Runtime

### ISSUE THREAD

**Issue by goergenj** [microsoft/botbuilder-dotnet#5552]
After upgrading to Composer 1.4.0. the timezone extraction does not work anymore.

Switching back to the previous runtime solves this issue.

This is one of the LG-Templates which uses this:

# TimeGreeting(scenario)
- IF: ${equals(getTimeOfDay(convertFromUTC(utcNow(), 'W. Europe Standard Time')), 'morning')}
    - Guten Morgen! ${WelcomeGreeting(scenario)}
- ELSEIF: ${equals(getTimeOfDay(convertFromUTC(utcNow(), 'W. Europe Standard Time')), 'morning')}
    - Guten Tag! ${WelcomeGreeting(scenario)}
- ELSEIF: ${equals(getTimeOfDay(convertFromUTC(utcNow(), 'W. Europe Standard Time')), 'morning')}
    - Guten Abend! ${WelcomeGreeting(scenario)}
- ELSE:
    - Guten Tag! ${WelcomeGreeting(scenario)}
    
    
 Critical issue for our customer!

@joaollq @goergenj @garypretty @benbrown @cwhitten.

**Comment by boydc2014** [comment]
@goergenj thanks for reporting, sorry for the breaking, we had a fix to correct the timezone info of the result of convertFromUTC, causing the result is not matching the input of getTimeOfDay, which we are working on a fix now, should be fixed soon. 

Meanwhile, a workaround to unblock customer is to add an extra formatDatetime after convertFromUTC , from
```
```

**Comment by goergenj** [comment]
We found the cause and fix for this:

TimeEvaluation issue is due to an misformed result of the "convertfromUTC".
![image](https://user-images.githubusercontent.com/31212469/116716050-93f06480-a9d7-11eb-9768-4060117f452c.png)


It can be easily resolved by adding the below to the prebuildfunction:

convertFromUTC(utcNow(), ‘W. Europe Standard Time’, 'yyyy-MM-ddTHH:mm:ss.fffZ')
