### ISSUE TITLE
Enable using OrchestratorRecognizer without a DialogContext 

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#5555]
Recognizers do not necessarily require a DialogContext, and cases exist where it would be useful to utilize a recognizer outside of a dialog.

**Comment by daveta** [comment]
We should coordinate with Tom - realistically, the overall Recognizer interface should support this..

**Comment by mrivera-ms** [comment]
@daveta, @tsuwandy, could you please confirm this is to be complete in R14? Thank you.

**Comment by tsuwandy** [comment]
@mrivera-ms, @EricDahlvang  this feature is nice to have for all recognizers and not just OrchestratorRecognizer.   Since R14 is a short release, can we move this to R15?

**Comment by mrivera-ms** [comment]
This is part of the work being done here: #5980. Closing this issue as duplicate.
