### ISSUE TITLE
Multiple contexts based on Card Selector

### ISSUE THREAD

**Issue by vcardins** [Microsoft/botbuilder-dotnet#557]
Hi All, 
I'm fairly new to the BOT world and I haven't found much information out there for the new SDK v4 (I haven't worked with v3 before).
What I'm trying to accomplish is simple (I'm using [AspNetCore-RichCards-Bot](https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples-final/AspNetCore-RichCards-Bot) as seed project):
Once I select one of the available options, instead of returning the information right away, I want to start a new workflow/context.

```
public async Task OnTurn(ITurnContext context)	{
	GlobalState = context.GetConversationState<GlobalState>();
	switch (context.Activity.Type)
	{
		case ActivityTypes.Message:
			var dialogContext = _dialogs.CreateContext(context, GlobalState);
			if (!context.Responded) {
				await dialogContext.Continue();
				await dialogContext.Begin(PromptStep.CardSelector);
			}
	}
}
```

Once I select the option *Update Profile*, for example, I'm replacing the context
```
	case "Update Profile":
		await dialogContext.Replace(UpdateProfilePromptStep.GatherUserProfile, GlobalState);
```
and it start prompting based on the new context, however, it skips the first question and on the 2nd, the result object is null.
![image](https://user-images.githubusercontent.com/2383329/39729290-f4aa362a-520f-11e8-9913-2048935ea91a.png)

Could you guys give me some guidance on how to accomplish this?

Thanks in advance!

**Comment by vcardins** [comment]
Hello @Stevenic, thank you very much! As I said, I'm learning through examples, I put a gist with some of the bot files  so you can have a better understanding. https://gist.github.com/vcardins/23a9f363ef1eeb7a3414790193148881.

**Comment by vcardins** [comment]
Actually, the work flow shoild start with PromptStep.CardSelector and then when I select one of the available options (Create Project or Update Profile) it switches to the other workflow and only returns to the CardSelector after being completed. Basically, select an option from the menu and start a different workflow with different state.
Hope I'm making myself clear, it'd be similar to v3 FormFlow, wondering whether it has been implemented on v4.

**Comment by Stevenic** [comment]
The code I pasted was from your Gist... So I see that you're starting `GatherUserProfile` when the user first messages not `CardSelector`. I think what you want to do will work but it looks like you're starting the wrong dialog.

**Comment by Stevenic** [comment]
To better understand what's happening in your `onTurn()` routing code... 

You're calling `dc.continue()` first to let any active dialog have a chance to run.  When that's done you need to know if anything ran and the easiest way to determine that is to see if anything responded to the user using `context.responded`. If nothing responded then most likely there wasn't an active dialog so you should either start a dialog (your card selector) or send a generic help message to the user.

This code does make an assumption that if you have an active dialog it will send some sort of message to the user so if you have code that may not reply you could extend your check after the continue call to be `if (!context.Responded && dc.ActiveDialog == null)`

**Comment by vcardins** [comment]
Hey @Stevenic, I do appreciate your help. I'll try again tonight and see how it goes. For now, I can tell that if I have:
``` 
if (!context.Responded) {
	await dialogContext.Begin(PromptStep.CardSelector); 
}
```
and then select UpdateProfile, the first UpdateProfile question/dialog is skipped and `result` is always null for the subsequente ones.
Also, is the following piece the correct way of changing the workflow? `OnTurn` will always be called anyways after the card selection and `context.Responded` will be false, which will make `await dialogContext.Begin(PromptStep.CardSelector); ` be called again and mess everything up. I might be missing a point here. (I could set up a small demo project if it's the case.)
```
switch (selectedCard) {			
	case "Update Profile":
		await dialogContext.Replace(UpdateProfilePromptStep.GatherUserProfile);
		break;
```

**Comment by vcardins** [comment]
@Stevenic, just tested, some more info
If at `onTurn` I have 
```
if (!context.Responded && activeDialog == null) {
    await dialogContext.Begin(PromptStep.CardSelector);`
}
```
then select Update Profile,
``` 
case "Update Profile":
	await dialogContext.Replace(UpdateProfilePromptStep.GatherUserProfile);
```
The `GatherUserProfile` workflow breaks cause the result object is null, see screenshot below. Again, if I start with `UpdateProfilePromptStep.GatherUserProfile` it works just fine. Ideas?
![image](https://user-images.githubusercontent.com/2383329/39794848-4eee7dde-5301-11e8-8c2b-3fc6cdc8d63e.png)

**Comment by vcardins** [comment]
Hello @Stevenic, thanks for your support. Yes, I recently figured it out. 
The issue seemed to be by calling `await dialogContext.End(); `, this issue can be closed.

Thanks again! 
`
...
private async Task ShowMenuOptions(DialogContext dialogContext, object result, SkipStepFunction next {
	var selectedCard = (result as ChoiceResult).Value.Value;
	var activity = dialogContext.Context.Activity;
	
	switch (selectedCard)
	{			
		case "Update Profile":
			//var updateProfileDialogContext = _updateProfileDialogs.CreateContext(_globalContext, GlobalState.UpdateProfile);
			//await updateProfileDialogContext.Continue();
			await dialogContext.Replace(UpdateProfilePromptStep.GatherUserProfile);
			break;
		case "Help":
			await dialogContext.Context.SendActivity(CreateResponse(activity, await HandleHelp()));
			break;
		default:
			await dialogContext.Context.SendActivity(CreateResponse(activity, await HandleHelp()));
			break;
	}
	// await dialogContext.End(); After removing this line it worked fine
}
`
