### ISSUE TITLE
SwitchCondition schema expects StringExpression, should be flexible for Int

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botbuilder-dotnet#5572]
## Version
What package version of the SDK are you using.
4.13.1

## Describe the bug
In the "duplicated intents recognized" trigger provided by Composer, there was a switch condition `=count(dialog.candidates)` that had been tested extensively and worked. A recent change in Composer enforces the SDK schema, which then broke this dialog as the [SwitchCondition.schema](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SwitchCondition.schema) expects a StringExpression. Before enforcing the  schema, the underlying code executed the condition successfully. We have resolved this now to read `=string(count(dialog.candidates))`, but perhaps the condition schema should expect a String or Int Expression.

## To Reproduce
1. Create an empty bot
2. Click on Add new trigger > Duplicated intents recognized
3. Scroll down to `Branch: Switch (multiple options)
4. Change the condition back to `=count(dialog.candidates)`, this will now throw an error that "Condition the return type does not match"

## Expected behavior
Give a clear and concise description of what you expected to happen.
Leaving the condition set to `=count(dialog.candidates))` should work as-is.

## Screenshots
**Breaks validation**
![image](https://user-images.githubusercontent.com/43043272/117715935-cc3d3300-b18d-11eb-8a12-7ee7fa7ca5e8.png)

**Passes validation**
![image](https://user-images.githubusercontent.com/43043272/117715896-c1829e00-b18d-11eb-9605-925ab5ac63f7.png)

## Additional context
cc: @lauren-mills @taicchoumsft

**Comment by tracyboehrer** [comment]
Known limitation.
