### ISSUE TITLE
Set Property not allowing Lg Template call to be evaluated as a value

### ISSUE THREAD

**Issue by sbacha** [microsoft/botbuilder-dotnet#5576]
## Version
4.12

## Describe the bug
Customer has multi language bot, and is leveraging LG templates to assign localized strings to properties to dynamically construct a string and perform operations with that string. 
SDK has a limitation today, that disallows LG Template calls to be evaluated at property setters.
The current provided approach is the export that template call as a module, the problem with that approach is now the export is tied to the namespace which is tied to the locale of the LG file. Ex:   foo.en-us.fn()
Where the customer is losing localization abilities

![image](https://user-images.githubusercontent.com/28227634/117851510-3f50b300-b23b-11eb-8060-b85c86f0e1d1.png)

## To Reproduce
Open Composer
Add a template in LG 

# getString()
- test string
- 
Go to dialog
Add a set property action
Add this : 
dialog.foo : "${getString()}

## Expected behavior
Should be able to get localized strings and assign them to properties

## Screenshots
Attached

**Comment by johnataylor** [comment]
@boydc2014 this is related to https://github.com/microsoft/botbuilder-dotnet/pull/5319
@Stevenic has a design proposal that slightly alters the approach, he can fill in the details

**Comment by Stevenic** [comment]
Our current proposal is to enable string interpolation for every `StringExpression` property within our system.  This will let developers contextually call LG templates from not only `SetProperty` but from any field that accepts a string.

**Comment by Stevenic** [comment]
Our current proposal is to enable string interpolation for every `StringExpression` property within our system.  This will let developers contextually call LG templates from not only `SetProperty` but from any field that accepts a string.

**Comment by boydc2014** [comment]
Dup to #5561

**Comment by cleemullins** [comment]
PVA is unblocked, and this issue is a dupe. Closing.
