### ISSUE TITLE
NumberInput and NumberExpression should support higher precision than float

### ISSUE THREAD

**Issue by maheshatanp** [microsoft/botbuilder-dotnet#5578]
for example if i enter this following number 8144331287 .
it is changed to 8144331300.

Why it supposed happen?

**Comment by tdurnford** [comment]
@mrivera-ms Can you triage this issue appropriately?

**Comment by ninggao** [comment]
@mrivera-ms Could you please take a look at this one?

**Comment by johnataylor** [comment]
This is presumably the NumberInput class, basically the same code as the NumberPrompt. The underlying conversion (from utterance string to number) is actually done by the NumberRecognizer.RecognizeNumber() from the Text Recognizers package. I'll investigate further and see where the problem lies.

**Comment by johnataylor** [comment]
Numbers in Composer should support double or decimal precision. C# float is very limiting.

**Comment by johnataylor** [comment]
@boydc2014 do you have any update on this?

**Comment by boydc2014** [comment]
> @boydc2014 do you have any update on this?

Sorry for the late response and thanks for the investigation above which is quite helpful.  The most straightforward fix to me is to change the default float to double, does that make sense to you?

I agree that the best treatment might be, as you said, keep it string until we really have to calculate, but the impact would be very big.
