### ISSUE TITLE
Date format is assumed to be American 

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/botbuilder-dotnet#5579]
When storing dates as properties, it seems an assumption is made that a date has been provided in the American format. If you enter a date in the format 10-20-2000, this will be converted to 2000-20-10. In cases where both the date and the month are 12 or below, the converter will assume you are using the American format. Therefore an input of 01-02-2000 will be converted to 2000-01-02. Is there a workaround to this? Can the date format be added or amended as this is causing issues in Europe.

**Comment by stevkan** [comment]
@BellaDunnett, I've checked this over several times with a colleague and the formatting of the stored value is actually correct providing the client being used is configured for the 'en-UK' locale, as well.

We tested in both Emulator (changing the locale to the above) and in Web Chat (setting the browser language to UK English). As long as the date entered conformed to the UK format (dd-MM-yyyy or dd-MM-yy), the date was always read and stored correctly. Even testing '10-20-2022' and '20-10-2022' both returned `2000-10-20` as the stored value.

When I switched back to a US locale/language, and entered the dates in the exact same format, the dates were stored according to the US format.

In other words:

- UK locale, '01-02-2022' (Feb 1, 2022) stored `2022-02-01`
- US locale, '01-02-2022' (Jan 2, 2022) stored `2022-01-02`

As you can see from the attached pics, this doesn't appear to be a bug when the locale/language of the client is taken into consideration. FYI, the `Formatted` value displayed is the interpreted month based off of the `Supplied` value.

UK vs US locale:
![image](https://user-images.githubusercontent.com/18403946/118193912-5b03b700-b3fd-11eb-8fb3-84001599ba4e.png)
![image](https://user-images.githubusercontent.com/18403946/118194229-e715de80-b3fd-11eb-9211-a749c47f80e0.png)

UK vs US locale:
![image](https://user-images.githubusercontent.com/18403946/118193956-6f47b400-b3fd-11eb-91f5-62684a44280d.png)
![image](https://user-images.githubusercontent.com/18403946/118194292-fbf27200-b3fd-11eb-9d1b-17cd13fc7dee.png)

UK vs US locale:
![image](https://user-images.githubusercontent.com/18403946/118194005-825a8400-b3fd-11eb-9759-f277adbb8917.png)
![image](https://user-images.githubusercontent.com/18403946/118194452-4116a400-b3fe-11eb-83f2-2c40a18869e5.png)

UK vs US locale:
![image](https://user-images.githubusercontent.com/18403946/118194522-58ee2800-b3fe-11eb-9d0c-f3981b3305ff.png)
![image](https://user-images.githubusercontent.com/18403946/118194534-5e4b7280-b3fe-11eb-86bd-263e9090aebb.png)

**Comment by BellaDunnett** [comment]
Hey @stevkan thanks for looking into this. It makes sense that we need to change the locale!
