### ISSUE TITLE
No way to get result value from DialogContext.End()

### ISSUE THREAD

**Issue by SamVanheer** [Microsoft/botbuilder-dotnet#558]
When creating a dialog context to run small dialogs such as `TextPrompt`, there is no way to get the result value (`TextResult`) unless you're running the prompt from inside another parent dialog.

The `DialogContext` constructor that takes a callback to get the result value is marked internal, and there is no other way to get to this object. When a prompt recognizes input the dialog prompt version of that class passes the result to `DialogContext.End()`, so unless you use the prompt directly there is no way to get that result.

Using the prompt directly would avoid the issue, but then you lose everything that the dialog version provides, such as retry support.

There should be a way to get the result from a context, and the documentation mentions a way that does not appear to be implemented: [Link](https://github.com/Microsoft/botbuilder-dotnet/wiki/Dialogs-and-Prompts#using-the-dialog-prompts)

I know that a simpler solution would be to make the code that calls the prompts into a dialog, but this doesn't work when the number of steps in a dialog is not known at creation time. A dialog that repeatedly executes the same steps can't really be defined using the Waterfall pattern.

**Comment by Stevenic** [comment]
So you can use any dialog (including prompts) on its own outside of a `DialogSet` using it's `begin()` and `continue()` methods. Here's a basic sample for calling each.  It's in JavaScript but the same basic pattern should apply in C#...

Calling begin() to start prompt:

```JavaScript
const state = {};
const completion = await dialog.begin(context, state);
if (completion.isCompleted) {
    const value = completion.result;
}
```

Save off the state object you passed in (it's a dictionary in C#) and when the user replies call continue():

```JavaScript
const completion = await dialog.continue(context, state);
if (completion.isCompleted) {
    const value = completion.result;
}
```

The prompts result will be returned as part of a completion data structure. The result is always a dictionary in C# I believe.  @johnataylor can fill in the blanks.

**Comment by johnataylor** [comment]
The C# code is modeled closely on the JavaScript and follows the pattern @stevenic describes.

One place to find usage examples (while we are waiting for other more fleshed out docs and samples) is the unit test code. For example you can take a look at the [NumberPrompt](https://github.com/Microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Dialogs.Tests/NumberPromptTests.cs) tests.
