### ISSUE TITLE
Orchestrator: Linux c# build is broken

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/botbuilder-dotnet#5586]
## Version
4.13.1

## Describe the bug
Orchestrator Recognizer does not appear to load correctly on Linux (Ubuntu 20.10 clean install). 

1)Libsentencepiece is missing
2)after resolving the above, we get api errors on the cli and bot crashes with `liboc_abi.so undefined symbol ortgetapibase`

We do not officially support 20.10 so I’ll test with 20.04 today just to be sure

## To Reproduce
1. Use Composer to create an empty c# bot 
2. Install the ‘Microsoft.botbuilder.ai.orchestrator’ package 
3. Create a simple bot and test a dialog trigger with Orchestrator 
4. Bot crashes with above message errors

**Comment by cwhitten** [comment]
https://fuselabs.visualstudio.com/APUB/_git/oc/pullrequest/15888

https://fuselabs.visualstudio.com/APUB/_git/oc/pullrequest/15884

**Comment by sgellock** [comment]
Shiproom - unbelievable
