### ISSUE TITLE
Resume a conversation on the Direct Line api with the User Id 

### ISSUE THREAD

**Issue by italoaguiar** [microsoft/botbuilder-dotnet#5589]
## Version
Bot Framework v4
DirectLine Api v3

## Describe the bug
I am trying to maintain a unique conversation id for each user of my system. Each user has their own conversation id. My bot uses proactive messages and needed to keep the history of the messages sent, so I use a single conversation id.

I currently request a token in the DirectLine api and save to database the created conversation Id.
POST https://directline.botframework.com/v3/directline/tokens/generate
{ "user":{ "id": "dl_abcdefg" }}

The generated token has the following format:

> {
  "alg": "RS256",
  "kid": "lcJ1Mqi6GJawBdL9cGbxKyKTz8M",
  "x5t": "lcJ1Mqi6GJawBdL9cGbxKyKTz8M",
  "typ": "JWT"
}.{
  "bot": "t-bot",
  "site": "fbIQwngVndIa",
  "conv": "BL6l0nhABrI0PRHflW11I-3",
  **"user": "dl_abcdefg",**
  "nbf": 1621259042,
  "exp": 1621262642,
  "iss": "https://directline.botframework.com/",
  "aud": "https://directline.botframework.com/"
}.[Signature]

However, when resuming the conversation, the token does not have the user ID and it is not possible to inform it in the request. 
GET https://directline.botframework.com/v3/directline/conversations/{conversationId}

> {
  "alg": "RS256",
  "kid": "lcJ1Mqi6GJawBdL9cGbxKyKTz8M",
  "x5t": "lcJ1Mqi6GJawBdL9cGbxKyKTz8M",
  "typ": "JWT"
}.{
  "bot": "t-bot",
  "site": "fbIQwngVndIa",
  "conv": "BL6l0nhABrI0PRHflW11I-3",
  "nbf": 1621259168,
  "exp": 1621262768,
  "iss": "https://directline.botframework.com/",
  "aud": "https://directline.botframework.com/"
}.[Signature]

Without the User Id, the bot welcome dialog is printed whenever the token is refreshed. In addition, I need the User Id to provide customized services in the bot. 

## To Reproduce
1. Generate a token (https://directline.botframework.com/v3/directline/tokens/generate)
2. Start a conversation (POST https://directline.botframework.com/v3/directline/conversations/)
3. Resume a conversation (https://directline.botframework.com/v3/directline/conversations/{conversationId})
4. Go to https://jwt.ms and compare the tokens
5. See the difference

## Expected behavior
Include the user Id in the conversation resume token

**Comment by mdrichardson** [comment]
Under "To Reproduce", how long are you waiting between steps 2 and 3? If over 30 minutes, [the token needs to be refreshed](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#secrets-and-tokens).

Regardless, I'm afraid that the User ID is only present [when creating the token](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0#tokenparameters-object). If you need the user ID mapped to a token, I'd recommend storing it within your bot using some form of persistent storage.

**Comment by mdrichardson** [comment]
@italoaguiar Do you still need assistance with this? Issues need to stay active to keep them open.

**Comment by italoaguiar** [comment]
Thank you @mdrichardson . I solved the problem by recording the user id in the cosmosDb used by the bot.

But this is a valid suggestion for improvement to token api.
