### ISSUE TITLE
ConfirmPrompt not uses Culture parameter

### ISSUE THREAD

**Issue by Arincon** [Microsoft/botbuilder-dotnet#559]
I am using ConfirmPrompt in my development, and I was passing to it the value of `Culture.Spanish` in the constructor, but it was not working. I am looking at the source code and I noticed this:

```csharp
// private IModel _model;
private Regex yes = new Regex(@"(\byes\b|\byep\b|\bok\b|\byessir\b|\bconfirm\b|^y$)", RegexOptions.IgnoreCase);
private Regex no = new Regex(@"(\bno\b|\bnope\b|\bnosir\b|\bcancel\b|^n$)", RegexOptions.IgnoreCase);

public ConfirmPrompt(string culture, PromptValidator<ConfirmResult> validator = null)
   : base(validator)
{

}
```

As you can see, the culture parameter is not being used at all, so it is the cause it does not work.
Do you know if this is fixed in another branch or release?
If not, I have done a PR (#560) with this fixed, as I think using `ChoiceRecognizer` (similar to what is used in `NumberPrompt`) will be simpler and clearer. 

Thanks in advance.

**Comment by gopal300** [comment]
i have similar problem , to be precise it´s with the localization of the Prompt Confirm.

**Comment by Arincon** [comment]
If you want to get it working until this is fixed in the repo and in the Nuget, you can copy the classes I modified in the PR, add these classes into your project, and use the modified ConfirmPrompt class instead of the class in the dll.

**Comment by cleemullins** [comment]
@johnataylor, who wrote these C# prompts, is out until next week. Can this wait until then? Ideally he would review/incorporate, just because I'm not sure I have enough context. 

Note: This change will need to be done in the Javascript SDK as well to keep them in sync, and then the docs have to be updated as well. :)

**Comment by Arincon** [comment]
Yes, It can wait, because I fixed it for my project (a workaround).
If I have to apply these changes to the Javascript SDK as well, I would to look at these more thoroughly, because I am not so familiar with it.

Regarding the documentation, I think it is not necessary to change anything, because the change is only internal, and external behaviour is not changed, but maybe I am wrong.

**Comment by johnataylor** [comment]
we have merged in the PR here
