### ISSUE TITLE
OnHandoffActivity should not be visible to Composer

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#5599]
## Version
What package version of the SDK are you using: 4.13.2+ (nightlies)

## Describe the bug
The [OnHandoffActivity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnHandoffActivity.cs) class surfaces the `handoff` _activity_, which should not be used. But, since this is surfaced in the SDK, Composer is consuming it and presenting it to the user.
- The hand-off to human scenario is supported by _event_ activities named `handoff.initiate` and `handoff.status`.

## To Reproduce
1. Error 1: Check the code for the [OnHandoffActivity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnHandoffActivity.cs) and note that it checks for the `handoff` _activity_ type, instead of for a handoff event.
2. Open Composer 2.0 and add a trigger to a dialog.
3. Error 2: Note that **Activities** > **Handover to human (Handoff activity)** is an option offered up to the user.

## Expected behavior
We don't present the user with options they should never use.

## Screenshots
![image](https://user-images.githubusercontent.com/35047199/119174869-fa3c3600-ba1d-11eb-9bd1-58c395a90609.png)

## Additional context

According to @arturl
> Handoff _activity_ type should not be used – it was included in the protocol as a “future extension” early on but was never used.  
> Only handoff _events_ should be used.

According to @garypretty 
>The handoff actions are going the right thing.

Per @cwhitten 
> The trigger in the Composer UI comes from its existence in the SDK, so if it needs to be removed then a change needs to come in from the SDK. Please open an issue with the SDK team (botbuilder-dotnet) for discussion.

Incidentally, the [OnInstallationUpdateActivity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/TriggerConditions/Activities/OnInstallationUpdateActivity.cs) class is not surfaced as an activity trigger in Composer.

**Comment by tracyboehrer** [comment]
Cannot remove from SDK for back compat.
