### ISSUE TITLE
FormBuilder equivalent in V4

### ISSUE THREAD

**Issue by SamVanheer** [Microsoft/botbuilder-dotnet#561]
Will there be a FormBuilder equivalent that enables us to define the data to be prompted for?

FormBuilder does a lot of work behind the scenes, like initializing fields with given values, allowing fields to be edited if requested, pattern matching, etc.

Such a tool would be very good to have, though it would probably be difficult to implement given the stateless nature of the new bot API.

**Comment by Stevenic** [comment]
Nothing to announce just yet but we'd love to create an updated version of FormFlow for v4.

**Comment by EricDahlvang** [comment]
Closing this as the Bot Builder Community has released a FormFlow implementation for V4: https://www.nuget.org/packages/Bot.Builder.Community.Dialogs.FormFlow/  with source here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/master/libraries/Bot.Builder.Community.Dialogs.FormFlow/README.md
