### ISSUE TITLE
PUT method in Send an HTTP request error

### ISSUE THREAD

**Issue by ghost** [microsoft/botbuilder-dotnet#5610]
## Describe the bug

After testing various settings it appears to only happen when Body is set to some value.  I can also confirm that the same bot running on 1.4.0 does not have this bug.

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution

## OS

- [ ] Windows

## To Reproduce

Here is the action used:
```json
{
    "$kind": "Microsoft.HttpRequest",
    "$designer": {
      "id": "eFG1UT"
    },
    "method": "PUT",
    "headers": {
      "testheader": "somevalue"
    },
    "responseType": "json",
    "resultProperty": "dialog.result",
    "url": "https://httpbin.org/put",
    "contentType": "application/json",
    "body": {
      "some": "value"
    }
}
```
      
Error is:  "Object reference not set to an instance of an object."

**Comment by johnataylor** [comment]
@mrivera-ms looks like there might be an issue to investigate here.
