### ISSUE TITLE
Maxturn count getting increase while interruption in composer prompts

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/botbuilder-dotnet#5611]
In side promts if we are allowing interruptions and setting maxturn count to 2 and if user message is interrupted twise in the same prompt and the maxturn count is increasing to 2 and the flow getting exit from the prompt.

So is there any way not to increase the maxturn count in promts while interrupting.

**Comment by johnataylor** [comment]
@mrivera-ms any update on this?

**Comment by johnataylor** [comment]
@Stevenic can you comment, thanks

**Comment by Stevenic** [comment]
Sounds like a bug. We should look at the ContinueAsync method and make sure that turn count is only incremented if turn.interrupted is set to false.

**Comment by johnataylor** [comment]
@KoradaRajesh thanks for reporting this bug.

@Stevenic thanks for taking a look, much appreciated. I'll assign to R14 and @mrivera-ms can see if it fits.
