### ISSUE TITLE
Microsoft.Bot.Builder.Dialogs.Debugging.SourceMap Memory Leak

### ISSUE THREAD

**Issue by karrimrabibiomni** [microsoft/botbuilder-dotnet#5614]
## Version
Botbuilder sdk 4.13.2

## Describe the bug
When using the .net bot builder sdk the dialog debugging source maps are constantly being added to Microsoft.Bot.Builder.Dialogs.Debugging.SourceMap.Instance but nothing is clearing it down.  Due to it being a static it will never get handled by GC.

## To Reproduce
Steps to reproduce the behaviour:
1. put a break point in an OnTurnAsync
2. Instantiate the bot from serval different WebChats then close the browsers and keep doing that.
3. hit your break point and look at Microsoft.Bot.Builder.Dialogs.Debugging.SourceMap.Instance in the quick debugger
4.  see it keep growing for ever

## Expected behavior
When a bot disconnects or is not used for a period of time I would want the source maps to be cleared out.

## Screenshots
![debugmemoryleak](https://user-images.githubusercontent.com/65707695/119825016-70450f00-beee-11eb-8a37-728eae736da1.jpg)

**Comment by johnataylor** [comment]
@mrivera-ms can you take a look? thanks

**Comment by mrivera-ms** [comment]
This seems to be a duplicate of #5469. @karrimrabibiomni, could you please see the referenced issue for a workaround? Thank you.

**Comment by mrivera-ms** [comment]
The fix is being tracked in #5469 and it is part of the current milestone. Closing as duplicate.
