### ISSUE TITLE
Upgrade Microsoft.Recognizers to 1.7.0

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#5620]
The sdk is on 1.2.9.  There's been many improvements and fixes since: https://github.com/microsoft/Recognizers-Text/tree/master/.NET

Testing revealed these differences, which are bug fixes:
[Microsoft.Bot.Builder.Dialogs_DateTimeModel_ResultsDateTimePrompt_Error.txt](https://github.com/microsoft/botbuilder-dotnet/files/6587587/Microsoft.Bot.Builder.Dialogs_DateTimeModel_ResultsDateTimePrompt_Error.txt)
[Microsoft.Bot.Builder.Dialogs_DateTimeModel_Results_DateTimePrompt_Words_Error.txt](https://github.com/microsoft/botbuilder-dotnet/files/6587589/Microsoft.Bot.Builder.Dialogs_DateTimeModel_Results_DateTimePrompt_Words_Error.txt)

One caveat is https://www.nuget.org/packages/Microsoft.Recognizers.Text/1.7.0 now references Microsoft.Extensions.Caching.Memory (>= 2.2.0) while our SDK supports netstandard 2.0, we have samples, generators and support for netcoreapp2.1. Microsoft.Extensions.Caching.Memory at 2.2.0 in the underlying dependency causes a downgrade issues while compiling for netcoreapp2.1. There are ways around this, but maybe we can drop support for 2.1 as it is EOL Aug2021.

**Additional context**
Note: the SDK should account for a missing Resolution in results:
![image](https://user-images.githubusercontent.com/11055362/120556790-d67bd700-c3b1-11eb-9822-2630205b7bd0.png)

**Comment by cleemullins** [comment]
Upgrading to 1.7.0 is blocked due to .NET Core versions. @JuanAr to investigate if there's a version of recognizers that we can adopt. 

Longer term @mrivera-ms to investigate dropping the .Net Core 2.0 dependency in the SDK as it's exiting support in Aug 2021.

**Comment by cleemullins** [comment]
#5688 drops support for .net core 2.0 from the SDK, which will unblock this issue. Currently targeted at R15.
