### ISSUE TITLE
Replace Dialog Action Not Working 

### ISSUE THREAD

**Issue by QaisAlkhateeb** [microsoft/botbuilder-dotnet#5624]
## Describe the bug

Replace Dialog action not working and throws the following error:
DialogContext.BeginDialogAsync(): A dialog with an id of ‘SecondDialog’ wasn’t found. The dialog must be included in the current or parent DialogSet. For example, if subclassing a ComponentDialog you can call AddDialog() within your constructor.

![image](https://user-images.githubusercontent.com/25031218/120430267-6f452f00-c37f-11eb-8502-b758030fdf26.png)

## Version

Release: 2.0.0-test
Runtime

    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.8" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.13.1" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.QnA" Version="4.13.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime" Version="4.13.1" />

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

I created simple test Bot with two dialogs, and the first dialog call replace dialog action for the second dialog 
![image](https://user-images.githubusercontent.com/25031218/120429760-9fd89900-c37e-11eb-8f12-0e48bab3435e.png)

![image](https://user-images.githubusercontent.com/25031218/120430193-4c1a7f80-c37f-11eb-8a0d-9b2e26085fac.png)

## Expected behavior

Open Second Dialog

**Comment by QaisAlkhateeb** [comment]
Hi @dmvtech  I just checked the issue and tested it and added a pull request 
please check:
#5656

**Comment by mrivera-ms** [comment]
There is a conversations associated with the PR submitted for this issue. The fix has not been approved and the team will need more time to review. Moving this issue to the next milestone.

**Comment by KunalKene1797** [comment]
Facing similar problems with our project. The project was migrated from Bot Composer 1.4.1 to 2.1.1.

![image](https://user-images.githubusercontent.com/8381101/138131773-a2965d48-97e4-42e1-9779-b0440310302c.png)

![image](https://user-images.githubusercontent.com/8381101/138131996-03d1c1fa-fc87-41b7-9c86-1d46b5bcfd73.png)

Looks like this issue is kind of sorted in #5656

Is there any workaround in the meantime or any way we could fix this bug?

_Need this for SR_
