### ISSUE TITLE
Cloud adapter + streaming + proactive is not wired up

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#5633]
Currently, proactive messages in streaming scenarios are not wired up in the CloudAdapter. Proactive messages are interpreted as http messages and when attempting to reply through http client to a url starting with `urn:...` we fail. BotFrameworkHttpAdapterBase did handle this, we could bring some logic from there.

This also breaks cloud adapter + streaming + skills (no proactive) because the bot is not able to root the skill response to the streaming transport.

**Comment by tracyboehrer** [comment]
Corrected in R15
