### ISSUE TITLE
Composer web app bots have dialog breaking/non-performant behavior on 1st interaction in Azure

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#5635]
## Describe the bug
Web app bots are slow to update/register state when talking to it in azure. It seems like a performance issue with dialogs breaking after a fresh deploy. Things work more or less as expected after you talk to the bot for a bit and restart the conversation. 

This might not be a P0, but opening user experience here is so poor it's worth looking at. 

## Version
Version:  2.0.0-nightly.240366.4a6ec2c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. create and deploy an echo skill bot as a skill
2. Create a parent bot and add the echo bot as a remote skill
3. Add a trigger to allow the parent to talk to the skill
4. deploy the parent bot to azure
5. In the azure portal go to the parent bot channel registration and test in web chat
6. Send the parent a message to connect to the skill
7. Fairly quickly send another message that would end up in the unknown intent state on the parent

## Expected behavior
I don't know what the expected lag time "should" be for this, but I never ran into this issue with code first bots so it's a disconnect for me.

## Screenshots
In the screenshot below the 2nd message I send should be in the echo dialog which is the current active dialog, but for some reason it ends up in the unknown intent trigger. The 3rd message I send ends in the active echo dialog as expected. 
![image](https://user-images.githubusercontent.com/50158775/116458876-fd2a7900-a819-11eb-9ce7-23064f73bf6c.png)

## Additional context
Also composer web app bots are painfully slow to send the opening message in azure. There is an error in the console which might be to blame:

![image](https://user-images.githubusercontent.com/50158775/116459543-cf91ff80-a81a-11eb-87fe-5f8ee9887f3c.png)

If you restart the bot after you receive the opening message response times improve greatly.

**Comment by mrivera-ms** [comment]
Per conversation with @boydc2014, this investigation will continue in the next milestone. Moving to R15.
