### ISSUE TITLE
DCR: add extra safety checks to DialogContext.continue() and begin()

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#564]
The driver code for using dialogs, while flexible, is pretty easy to get wrong.  The two primary things I see happening are people calling `dc.continue()` and then calling `dc.begin()` without checking whether the bot responded or the reverse... They call `dc.begin()` and then call `dc.continue()` which you pretty much should never do. I've done both myself so it's pretty easy to accidentally do either.

One thought I had was to add some extra checks to DialogContext which try to catch these issues and either log a warning to the console or potentially even throw an exception.  in both cases I think you should be able to disable the the checks but I think adding them would save developers some grief.

**Comment by JonathanFingold** [comment]
Can we use a different check as to whether a dialog step was processed, other than `if (context.Responded)`? There are many ways this could go wrong, such as middleware sending an activity, and it forces every dialog step to send an activity to the user. (This may be a good practice, but I could probably come up with some scenarios where it isn't relevant.)

**Comment by Stevenic** [comment]
The issue @JonathanFingold is that the alternative approaches have even bigger issues.  At one point we returned a `handled` flag back through everything. While that was technically more accurate it meant every component had to remember to either set it or pass it through. People were constantly forgetting to set it and it wasn't intuitive as to what it actually meant.

The reason I personally like using `context.responded` is that a) it sets itself so there's nothing the developer has to remember, and b) it follows the best practice that a bot should always reply when it receives a message from a user.  

While it's totally possible for middleware to send activities too, they should probably not call `next()` given that they've handled the message.  In the very rare case where a piece of middleware wants to send essentially an extra message to the user they should use the adapter directly as this will avoid setting the responded flag. I have `showTyping()` middleware that does this.

Another thing worth noting is that I believe the responded flag only gets set now when an actual "message" is sent so sending things like a "typing" indicator shouldn't trigger it.

**Comment by johnataylor** [comment]
Firstly, this is an old issue against a very old rev of this functionality and the new ContinueDialog and BeginDialog has better checks. (Note the method renames.) And secondly the solution to make things significantly easier is as @sgellock implies is to have a higher level "Run" method that encapsulates the regular Continue/Begin flow. The idea is to experiment with this method in the samples repo.

Closing this issue here.
