### ISSUE TITLE
While calling a API with content-type : "multipart/form-data",  setting content disposition in header is not working

### ISSUE THREAD

**Issue by aparnaji** [microsoft/botbuilder-dotnet#5640]
## Describe the bug

While calling a API with content-type : "mutlipart/form-data",  setting content disposition in header is not working

## Browser

- [ ] Chrome
## OS

- [ ] Windows
## To Reproduce

1. Create a Dialog ->  Trigger
2. As part  of this as for user Input as 'attachment"
3. Send this file to input as using Access External resources -> Send HTTP Request
4. The API that I used is of type content-type : "mutlipart/form-data"
5. Tried options as 
6. 1. `Content-Type: multipart/form-data;boundary="boundary"`  - this threw error, (saying Content-Type  invalid)
6.  2. Set header as key `Content-Disposition and Value as "form-data; name="file"; filename="${dialog.attachments[0].name}"` 
7. 3.  Set header as key `Content-Disposition and Value as "form-data; name="file"; filename="${dialog.attachments[0].contentUrl}"` 
6. This header itself is not being shown in emulator trace, I doubt if it is being set

Is there a fix for this issue

## Screenshots
![image](https://user-images.githubusercontent.com/26645750/117447106-977e7100-af2c-11eb-913b-d578f8941b50.png)
![image](https://user-images.githubusercontent.com/26645750/117447205-ba108a00-af2c-11eb-8405-6ccdbd93feff.png)

## Additional context
Is there any other way of calling this kind of APIs

**Comment by aparnaji** [comment]
Thanks for update, I finally added custom action to call the api.

**Comment by thomas-chung** [comment]
Thanks for reporting the issue. Since there seems to be a solution and it has been over 2 weeks. We will close this issue. If issue resurfaces, please reopen.
