### ISSUE TITLE
SetSpeakMiddleware does not honor multiple voice tags

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/botbuilder-dotnet#5657]
## Version
Used via Composer 2.0.0-nightly.250532.6b3fab5

## Describe the bug
Using multiple voice tags in the speak field in Composer does not work. Default voice tags are added creating an invalid SSML.

## To Reproduce
1. In Composer, send a new activity. Set the speak field to 
 <voice name="en-US-JennyNeural">press 1 for English.</voice><voice name="es-ES-ElviraNeural">pressione 2 para espaniol.</voice>
2. Start the bot and Test in WebChat
3. Notice that the speak field is set to 

**<voice name=\"'en-US-AriaNeural\">**<voice name=\"en-US-JennyNeural\"> press 1 for English.</voice><voice name=\"es-ES-ElviraNeural\">pressione 2 para espaniol.</voice> </voice> 

## Expected behavior
Default voice tags (**<voice name=\"'en-US-AriaNeural\">**) should not be added when one or more voice tags are specified in the speak field.

**Comment by p-nagpal** [comment]
Discussed this offline with @garypretty and @carlosscastro

**Comment by tracyboehrer** [comment]
See also: https://github.com/microsoft/botbuilder-dotnet/issues/5792

**Comment by ramfattah** [comment]
investigating
