### ISSUE TITLE
Use of ChannelServiceExceptionFilter on the ChannelServiceController is preventing custom filters to be called

### ISSUE THREAD

**Issue by nnmsft** [microsoft/botbuilder-dotnet#5670]
## Version
4.11.1

## Describe the bug
We currently have a global exception filter which we use to log unhandled exceptions that are thrown from any controller actions to our telemetry. Exceptions being thrown from the ChannelServiceController are not being logged since the use of the ChannelServiceExceptionFilter is preventing the exception from being bubbled up.

## To Reproduce
1. Add a global exception filter.
2. Trigger an exception in any actions in the ChannelServiceController
3. The custom filter won't be called.

## Expected behavior
Either a way to override the OnException method in the ChannelServiceExceptionFilter needs to be provided or the ExceptionHandled property shouldn't be set to true so other filters in the chain can get called.

**Comment by johnataylor** [comment]
We can remove the code that sets the handled to true. The status code is still set, it just allows other exception filters to execute, possible setting a different status code which would be slightly non-deterministic but in this context most likely harmless.
