### ISSUE TITLE
Channels "enumeration" is out of date

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#5678]
## Version

Parent issue https://github.com/microsoft/botframework-sdk/issues/6448

"main" (as of 6/15, 1:59 PM Pacific)

## Describe the bug

libraries/Microsoft.Bot.Connector/Channels.cs is out of sync with Intercom:
1. The new Outlook Actionable Messages channel is missing ("outlook").
2. The entry for "twilio-sms" seems like it should be marked [Obsolete], as it appears to be an incorrect duplicate of the existing entry for Twillio ("sms"). (This is also in the JavaScript SDK.)

## To Reproduce

1. Open https://github.com/microsoft/botbuilder-dotnet/blob/baf78d01d4c0b8ddae2d117a52d2a4bca1479683/libraries/Microsoft.Bot.Connector/Channels.cs
2. Error: notice that there's no entry for "outlook".
3. Error: see there are entries for "sms" and "twilio-sms".

## Expected behavior

The channels enumeration stays up to date with the channels on the Azure portal, at least for additions.

## Additional context

The Outlook Actionable Messages channel is in early preview, but visible in Azure.

Other channels enumerated in Intercom that are not in .NET:
- "enterprisechannel"
- "kaizala"
- "omnichannel"
- "searchassistant"

Note:
- "alexa" is missing from the JavaScript, Java, and Python SDKs.
- "directlinespeech" and "telephony" are missing from the Python SDK.

**Comment by sw-joelmut** [comment]
Hi @JonathanFingold, we noticed there are a few channels in the enumeration list that are not in the Azure Portal's channels anymore. Should we also mark these as obsolete?
- Console
- Cortana
- Kik
- Skype for business (There is an existing Skype channel only)
- Telephony
![image](https://user-images.githubusercontent.com/62260472/169382581-bcf14120-c64b-484d-9a1b-f2c180b1fecc.png)

Thanks.
