### ISSUE TITLE
Drop .Net Core 2.1 support to follow the officially supported versions 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#5688]
In August 2021, .Net core 2.1 is no longer supported. Maintain the SDK on supported versions of .Net. 

@mrivera-ms  Please update this issue to include the officially supported list of version and support dates. :)

**Comment by mrivera-ms** [comment]
From [.Net Core and .Net 5 Support Policy](https://dotnet.microsoft.com/platform/support/policy):

![image](https://user-images.githubusercontent.com/44449640/122314507-28058500-cecd-11eb-82ee-533a015b3979.png)

**Comment by gabog** [comment]
This has already been removed. Closing
