### ISSUE TITLE
Bot Builder Adapter for Zoom

### ISSUE THREAD

**Issue by Trinetra-MSFT** [microsoft/botbuilder-dotnet#5719]
I assume currently Bot Builder SDK .NET and .JS don't have adapter enabled for Zoom. is it possible to integrate adapter to  ZOOM API which will include support for Zoom handover protocol.

**Comment by clearab** [comment]
There's a Zoom adapter created by the community available here: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.Zoom
