### ISSUE TITLE
Add automaticDecompression for httpRequest to avoid garbled code

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#5729]
## Version
nightlies

## Describe the bug
See original issue ([MicrosoftDocs/composer-docs#128](https://github.com/MicrosoftDocs/composer-docs/issues/128))
and proposed fix ([PR 5682](https://github.com/microsoft/botbuilder-dotnet/pull/5682)).

## To Reproduce
See  [MicrosoftDocs/composer-docs#128](https://github.com/MicrosoftDocs/composer-docs/issues/128)

## Expected behavior
Bots don't produce garbled responses.

## Screenshots
See  [MicrosoftDocs/composer-docs#128](https://github.com/MicrosoftDocs/composer-docs/issues/128)

**Comment by LeeParrishMSFT** [comment]
Closed with PR: https://github.com/microsoft/botbuilder-dotnet/pull/5682
