### ISSUE TITLE
Add tests to increase the code coverage of the libraries

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-dotnet#5733]
Current total coverage reported via the BotBuilder-DotNet-CI-PR-yaml build pipeline is 77.32%. This number could be raised by increasing the number of tests run against some of the libraries. See attached report.

![image](https://user-images.githubusercontent.com/4296530/123303251-74a31e80-d4d2-11eb-80e9-e98d2f1c7ab3.png)

**Comment by mrivera-ms** [comment]
This issues is being tracked in #5167. Closing as duplicate.
