### ISSUE TITLE
Allow Skills to call other Skills within ConfigurationAdaptiveDialogBot based bots.

### ISSUE THREAD

**Issue by LeeParrishMSFT** [microsoft/botbuilder-dotnet#5738]
**Is your feature request related to a problem? Please describe.**
Today ConfigurationAdaptiveDialogBot (and it's base class AdaptiveDialogBot) only support a bot being a root bot that can call skills, or as a skill itself. This is because there is only a single AuthenticationConfiguration provided to the constructor of AdaptiveDialogBot and AuthenticationConfiguration only only has a property for a single ClaimsValidator instance. In the scenario where a skill needs to call another skill we need to have both an AllowedCallersClaimsValidator and an AllowedSkillsClaimsValidator.  We could fairly easily accommodate that by extending AuthenticationConfiguration to have two properties, one for each type of ClaimsValidator needed, or a collection of validators that we can pull from. There is also an issue in that even if we have multiple ClaimsValidators when they are called we don't have enough context to know which validator to use, i.e. we don't know if the call is a callback from a skill, or a call inbound to a skill. 

Today Composer doesn't support a skill calling another skill, so to support this scenarios we would need to makes to Composer as well as updates to the SDK/runtime to support configuring a bot as a skill that can call another skill.

**Describe the solution you'd like**
We need to extend the (Configuration)AdaptiveDialogBot to support the scenario of a bot being a skill and also being able to call other skills.

Skills that act as consumers should also support SSO

**Describe alternatives you've considered**
It would seem that the scenario of allowing skills to call other skills is desired, if not then this item can be closed as not needed.

**Additional context**
This was discussed during the fix for Issue #5285 where we discovered this scenario wasn't supported so this item was opened to track this need, while the fix for Issue #5285 was moved forward to correct a more immediate issue.

**Comment by LeeParrishMSFT** [comment]
@gabog and @johnataylor This is to track the need to support Skill to Skill calling in AdaptiveDialogBot (and ConfigurationAdaptiveDialogBot as well). While not supported by Composer today, it seems that this is a scenario that is desired, so this would be a good candidate for getting a coherent plan in place for a future release.

**Comment by gabog** [comment]
We will not address this at the moment.
