### ISSUE TITLE
LUParser doesn't support colons in the synonyms 

### ISSUE THREAD

**Issue by Robulane** [microsoft/botbuilder-dotnet#5743]
## Version
4.13

## Describe the bug
LU parser cannot parse Synonyms list if one of the synonyms contain a colon.

## To Reproduce
Execute the following test and see that it fails
```
        [Fact]
        public void LUParser_HanCandleColon()
        {
            var result = LuParser.Parse(@"
> comment
@ list listId =
    - canonical name 1 :
        - synonyme 1:
        - synonyme 1
    - canonical name 2 :
        - synonyme 2
");

            Assert.Equal(2, result.Sections[0].SynonymsList.Count);
        }

```
## Expected behavior
LU parser should handle colons and any other character in the synonymes.

**Comment by munozemilio** [comment]
This cannot be supported with LU
