### ISSUE TITLE
Make TelemetryLoggerMiddleware easier to use/extend

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#5744]
## Version
4.13.3

## Describe the bug
Adding additional properties to emit to the TelemetryLoggerMiddleware is harder than it needs to be.

## To Reproduce
1. Try to follow Gary's [instructions for adding additional properties](https://github.com/MicrosoftDocs/bot-docs/issues/2097#issuecomment-866684556).
    ```cs
    public class MyTelemetryLoggerMiddleware:TelemetryLoggerMiddleware
    {
        public MyTelemetryLoggerMiddleware(IBotTelemetryClient telemetryClient, bool logPersonalInformation = false)
            : base(telemetryClient, logPersonalInformation) { }

        protected override async Task<Dictionary<string, string>> FillSendEventPropertiesAsync(Activity activity, Dictionary<string, string> additionalProperties = null)
        {
            var props = await FillSendEventPropertiesAsync(activity, additionalProperties);

            props.Add("myCustomPropertyKey", "myCustomPropertyValue");

            return props;
        }
    }
    ```
2. Try to compile.
3. See error:
    > CS0506 'MyTelemetryLoggerMiddleware.FillSendEventPropertiesAsync(Activity, Dictionary<string, string>)': cannot override inherited member 'TelemetryLoggerMiddleware.FillSendEventPropertiesAsync(Activity, Dictionary<string, string>)' because it is not marked virtual, abstract, or override.

## Expected behavior
Options:
1. Make the various FillXxxEventProperties virtual.
2. Add an additionalProperties argument that is passed on to the FillXxx method call to the various OnXxxActivityAsync methods.

## Additional context
See bot-docs [issue 2097](https://github.com/MicrosoftDocs/bot-docs/issues/2097).

**Comment by tracyboehrer** [comment]
Known limitation.
