### ISSUE TITLE
Update Microsoft.Extensions dependencies

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#5751]
We are using most of the Microsoft.Extensions.* references from 2.1.0 (Microsoft.Extensions.Http, Microsoft.Extensions.Logging, Microsoft.Extensions.Configuration, etc, etc). The current version is 5.0. 6.0 is coming out, so we should be on 5.0. 

There are issues in updating these with the fact that we support multiple versions, so that is some work that we need to dedicate some time and get right. 

Note: There are other dependencies that need to be inventoried and updated. 

1. Key Vault
2. [Add here as more are inventoried]

Tracking this as a "Medium" work item until we've more clarity.

**Comment by BruceHaley** [comment]
Upgrading Microsoft.Extensions.* to 5.0.0 is on hold pending a decision on whether and when to stop building for TargetFramework netcoreapp2.1. netcoreapp2.1 officially reached "end of support" on August 21st.

**Comment by BruceHaley** [comment]
Related issue #5688

**Comment by gabog** [comment]
The relevant dependencies have been updated to use 3.1 as part of removing support for 2.1, closing this issue
