### ISSUE TITLE
Orchestrator recognizer: Initialize model method slows the first request

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-dotnet#5753]
Initialize model method in orchestrator recognizer is ran only once, but can take several seconds to complete, and all threads will be blocked on this and potentially leading to degraded user experiences. In voice environments such as telephony channel, time is even more important, where delays of several seconds are not a possibility.

Evaluate whether we can perform initialization on load so that we do not do all the initialization in the first call to RecognizeAsync.

**Comment by hcyang** [comment]
The latest OrchestratorRecognizer refactored (both NodeJS and DotNet versions) code in 'main' can directly be instantiated using the constructor (before, the constructor was only used for mock-up in unit tests). Therefore, this cold-start problem has a work-around: using the constructor with configuration information read from NodeJS .env file or DotNet appsettings.json.
