### ISSUE TITLE
Long user input results in 400 Bad Request

### ISSUE THREAD

**Issue by aortiz1** [microsoft/botbuilder-dotnet#5757]
## Describe the bug

On long user input the bot responds with an error "Response status code does not indicate success: 400 (Bad Request).", validations for the input length don't prevent this error to show.

## Version

Composer  1.4.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [* ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ *] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot application and add a text input.
2. On the validatation tab add the condition "length(string(this.value))<255" and as a response on invalid prompt "the text is too long".
3. Add a trigger with some some phrases ie. "the machine is broken"
4. Put the following text on the user input "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate".
5. Bot responds "Response status code does not indicate success: 400 (Bad Request)."

## Expected behavior

After giving the input the bot should respond "the text is too long"

## Screenshots

![image](https://user-images.githubusercontent.com/30127751/123707974-37bb8c80-d830-11eb-9af4-ce9b0d3ff5ab.png)
![image](https://user-images.githubusercontent.com/30127751/123708018-502ba700-d830-11eb-98e7-ca91529b411c.png)

## Additional context

The issue only affects dialogs with  LUIS recognition triggers

**Comment by dmvtech** [comment]
To clarify; 

- This happens (fails) before validation can be done.
- It fails/repros with dotnet runtime, but works with node runtime.
- Simple repro steps:

1. - Create text prompt asking for text (using dotnet runtime)
2. - Send text with > 500 characters.

**Comment by cosmicshuai** [comment]
After setting up a demo in dotnet sdk, I found the utterance with more than 500 char will get an error from luis portal.
![image](https://user-images.githubusercontent.com/17074777/125905533-d2bdfe23-e2dc-4264-ab7f-2ce1b34972ba.png)

Here is the doc for luis limits:
https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-limits

**Comment by taicchoumsft** [comment]
Thanks @cosmicshuai for the diagnosis.  @munozemilio , @mrivera-ms , how should we proceed here?  Should we validate input length in SDK before going to the LUIS service?  Or is this expected?

**Comment by gabog** [comment]
Hi @munozemilio, can you respond to @taicchoumsft's question?

Thanks

**Comment by a-b-r-o-w-n** [comment]
@mrivera-ms / @munozemilio are you able to provide an update on this?

**Comment by munozemilio** [comment]
As per conversation with @mrivera-ms given this is a Luis limitation we won't handle it in the SDK.
