### ISSUE TITLE
NullReferenceException in BotFrameworkAdapter.SendActivitiesAsync

### ISSUE THREAD

**Issue by ninilang** [microsoft/botbuilder-dotnet#5773]
## Version
What package version of the SDK are you using.
4.11.2

## Describe the bug
We are on the PVA team. In our production environment, we are intermittently seeing a `NullReferenceException `being thrown during a call to `turnContext.SendActivityAsync`.

Based on the call stack, this `NullReferenceException `seems to be originating in the `SendActivitiesAsync `method in `BotFrameworkAdapter.cs`. We don't see this happening in our internal environments and I've also failed to reproduce this locally.

Below is the call stack - 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.BotFrameworkAdapter.<SendActivitiesAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass30_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  **<Middlewares called here>**
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivityAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

However, I see that [this information trace](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L521) is logged in our telemetry, so seems like the exception is being thrown after this. We also do not use a streaming endpoint currently, so the call to [CanProcessOutgoingActivity ](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L544) should also return false. I suspect that either the `turnState` or the `connectorClient` is null somehow.

## To Reproduce
Haven't been able to reproduce this locally but keeps happening intermittently in our production environments.

## Expected behavior
The outgoing activity should be sent successfully during a call to `turnContext.SendActivityAsync` and a `NullReferenceException` shouldn't be thrown.

**Comment by EricDahlvang** [comment]
As far as I know, this should only be happening IF SendActivityAsync is used after the disposal of TurnContext: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/TurnContext.cs#L547

This is likely a bug in the project, not the sdk.  Is the consuming code sending activities out of band, after TurnContext is disposed?

The recommended method for proactive messaging is to use adapter.ContinueConversationAsync with a ConversationReference:

```cs
 await ((BotAdapter)_adapter).ContinueConversationAsync(_appId, conversationReference, BotCallback, default(CancellationToken));

        private async Task BotCallback(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync("proactive hello");
        }
```

**Comment by EricDahlvang** [comment]
Actually, this could be due to a race condition within `ShowTypingMiddleware` https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs#L130

**Comment by ninilang** [comment]
Hi Eric, we are using the the same recommended method in PVA as you mentioned above. We are also seeing this exception intermittently, so if the PVA was not implementing the recommended method of proactive messaging in the correct way, I'd assume we'd have seen this error for all outgoing activities and not just a few of them?

Also, about the race condition in the `ShowTypingMiddleware`, from the call stack we are logging, the call is originating in the PVA code where we are trying to call `SendActivityAsync `on the `TurnContext`, so I believe the `ShowTypingMiddleware `might not be the root cause of the issue.

**Comment by tracyboehrer** [comment]
Deprecated.  Use CloudAdapter.
