### ISSUE TITLE
`_checkedContainers` can become inconsistent with blob storage and further lead to unhandled exception

### ISSUE THREAD

**Issue by rmt2021** [microsoft/botbuilder-dotnet#5778]
## Version
64ecf2f3e131b05fb93aa3fa0c3abc087febf33c (latest commit in main branch till Jul 9)

## Describe the bug
`_checkedContainers` in `AzureBlobTranscriptStore`/`BlobsTranscriptStore` can become inconsistent with the actual created containers in blob storage when transient error fails `container.CreateIfNotExistsAsync()`. For example, container name in `_checkedContainers` might not be created successfully in blob storage.

More concretely, in the constructor (`botbuilder-dotnet\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs`)
```
this.Container = new Lazy<CloudBlobContainer>(
                () =>
            {
                containerName = containerName.ToLowerInvariant();
                var blobClient = storageAccount.CreateCloudBlobClient();
                NameValidator.ValidateContainerName(containerName);
                var container = blobClient.GetContainerReference(containerName);
                if (!_checkedContainers.Contains(containerName))
                {
                    _checkedContainers.Add(containerName); // add the containerName to _checkedContainers
                    container.CreateIfNotExistsAsync().Wait(); // try to create the container
                }

                return container;
            }, isThreadSafe: true);
```
The `containerName` is added before it gets created. If some transient error, like temporary 503 (server is busy), happens and fails `CreateIfNotExistsAsync`, the `containerName` will not exist in blob storage, but still appears in `_checkedContainers`.

The exception caused by the transient error will be caught by `TryLogTranscriptAsync` but it will also affect following operations and lead to unhandled exceptions. Since `_checkedContainers` is a static class variable, when the constructor is later called by another object, `_checkedContainers.Contains(containerName)` will always return true and the container will never have a second chance to be created. In methods like `GetTranscriptActivitiesAsync`, 
```
var dir = this.Container.Value.GetDirectoryReference(dirName);
...
var segment = await dir.ListBlobsSegmentedAsync(...).ConfigureAwait(false);
```
exception will happen since the container does not exist.

## To Reproduce
As shown above, one transient error that fails the `CreateIfNotExistsAsync` will lead to the inconsistency and unhandled exception.
The simplest way to reproduce is to run some existing test (like `Microsoft.Bot.Builder.Azure.Tests.AzureBlobTranscriptStoreTests.LogActivities`). If `CreateIfNotExistsAsync` fails (due to any transient error like 503), the test will fail due to unhandled container not found exception.

## Expected behavior
The `_checkedContainers` should keep consistent with the actual blob storage even when transient error happens.

## Additional context
Similar problems happens in two different places `AzureBlobTranscriptStore` and `BlobsTranscriptStore`.

We are willing to send a PR to help fix this issue. We can just change the order to
```
container.CreateIfNotExistsAsync().Wait(); // try to create the container
_checkedContainers.Add(containerName); // add the containerName to _checkedContainers
```
, so that if `CreateIfNotExistsAsync` fails, `_checkedContainers` will not contain the `containerName`. The following `_checkedContainers.Contains(containerName)` will return false so the container has a second chance to get created.

**Comment by hcyang** [comment]
Hi @carlosscastro, can you take a look of the PR. Thanks.

**Comment by carlosscastro** [comment]
@EricDahlvang  and I just synced up on this, he'll review the PR and take it from there.

**Comment by EricDahlvang** [comment]
Thanks for the PR @rmt2021 !

**Comment by carlosscastro** [comment]
+1 thanks for contributing @rmt2021
