### ISSUE TITLE
OrchestratorRecognizer: passing model + snapshot file via constructor does not work

### ISSUE THREAD

**Issue by sibbl** [microsoft/botbuilder-dotnet#5786]
## Version
4.14.0

## Describe the bug
Calling `myOrchestratorRecognizer.RecognizeAsync(dc, activity);` fails with `ArgumentNullException` for `_model` when creating the recognizer via `myOrchestratorRecognizer = new OrchestratorRecognizer(".\\model", ".\\snapshot.blu")`.

The constructor properly sets `_model` and `_snapshotFile` and then calls `InitializeModel`. So far so good, this runs without any exceptions.

However, when calling `RecognizeAsync` the `_model` and `_snapshotFile` variables are immediately overwritten with the evaluated content of `ModelFolder` and `SnapshotFile` expressions. Which by default evaluates some settings which don't exist in my `DialogContext`. Then `InitializeModel` is called and it first checks for `_model` and `_snapshotFile` to be not null - even though the `_recognizer` is already non-null at this point.

See these lines in the code: https://github.com/microsoft/botbuilder-dotnet/blob/4e77424da2392d3241628b7b9d78504cc8c7b218/libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs#L148-L151

and the check within `InitializeModel`:
https://github.com/microsoft/botbuilder-dotnet/blob/4e77424da2392d3241628b7b9d78504cc8c7b218/libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs#L369-L388

## Workaround

The following works as it overwrites the string expressions which can be evaluated properly:
```csharp
myOrchestratorRecognizer = new OrchestratorRecognizer {
   ModelFolder = ".\\model",
   SnapshotFile = ".\\snapshot.blu"
}
```

**Comment by hcyang** [comment]
Hi @sibbl, this problem has been fixed in the 'main' branch. 
Thanks for the detailed bug report. Since there is a workaround, we decided not to cherry-pick the fix and check it into the 4.14 branch. I will close the issue for now. Feel free to reopen it if you have more questions.
