### ISSUE TITLE
Metadata of blob can be missing due to transient error which leads to unhandled exception

### ISSUE THREAD

**Issue by rmt2021** [microsoft/botbuilder-dotnet#5787]
## Version
64ecf2f3e131b05fb93aa3fa0c3abc087febf33c (latest commit in main branch till Jul 9)

## Describe the bug
The metadata of the blob is set in `LogActivityAsync`
```
private static async Task LogActivityAsync(IActivity activity, CloudBlockBlob blobReference)
{
    ...
    blobReference.Metadata["Timestamp"] = activity.Timestamp.Value.ToString("O", CultureInfo.InvariantCulture);
    ...
    // write to the blob
    await blobReference.SetMetadataAsync().ConfigureAwait(false);
}
```
If `SetMetadataAsync` encounters a transient error (like 503 server is busy or 500 operation timed out), the exception will be swallowed by the catch block in `TryLogTranscriptAsync`, but the actual blob storage is left in a state that **the blob gets created but the metadata is not set**. 

Later in `GetTranscriptActivitiesAsync`, the code tries to get the metadata "Timestamp" of blob
```
if (DateTime.Parse(blob.Metadata["Timestamp"], CultureInfo.InvariantCulture).ToUniversalTime() >= startDate)
```
However, the metadata "Timestamp" can be missing if some transient error happens before and get unhandled. The missing metadata will also lead to unhandled `KeyNotFoundException` here.

## To Reproduce
As mentioned above, the `KeyNotFoundException` happens when transient error happens to the operations between blob creation and `SetMetadataAsync` (including `SetMetadataAsync`) and gets swallowed.

## Expected behavior
We cannot assume the metadata is always set well in the blob. We can either try to handle the `KeyNotFoundException` in `GetTranscriptActivitiesAsync`, or check whether "Timestamp" exists before calling `blob.Metadata["Timestamp"]`.

## Additional context
We are willing to send a PR to help fix this issue.
A simple fix is to check the existence of "Timestamp" before calling `blob.Metadata["Timestamp"]`, but I am not super sure what should be the best practice if the metadata is missing. Shall we just skip the blob and log an warning message in that case?

**Comment by hcyang** [comment]
@rmt2021, you are very welcome to submit a PR and perhaps a unit test for the PR. Thanks.

**Comment by mrivera-ms** [comment]
@rmt2021, thank you for submitting a PR. The team will review it and determine what the right approach is to handle this case.

**Comment by benbrown** [comment]
@mrivera-ms Does this PR look usable?

**Comment by EricDahlvang** [comment]
Thank you for the PR to address this. 

We recommend switching from the deprecated AzureBlobTranscriptStore to BlobsTranscriptStore in the https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure.Blobs package, which should not have this issue: 

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs#L436
