### ISSUE TITLE
BeginDialog action doesn't support expressions for Dialog Name

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5790]
I can use a string to define the name of a dialog I want to call:

![](https://user-images.githubusercontent.com/698939/126005200-24143cd6-ee12-4528-aa63-c8d7e5d174d4.png)

But if I try to use an expression I get a "Object reference not set to an instance of an object" error :(

![](https://user-images.githubusercontent.com/698939/126005357-198aa312-3dc3-42da-814b-ed3144f878e5.png)

I really need this to work for both BeginDialog and ReplaceDialog which I assume is also broken.

**Comment by Stevenic** [comment]
@LeeParrishMSFT worked out that this is actually a registration issue. If you only dynamically reference a "named dialog" it's not getting added to the underlying DialogSet and therefore can't be found. With that insight, the work around I came up with is to create a bogus "RegisterDialogs" custom event trigger off that root that will never be called, but at least forces all of the projects dynamic dialogs to be registered.

![image](https://user-images.githubusercontent.com/698939/126018329-bbf865e3-2455-43ba-9d54-253f5aa647f4.png)

It's important that this be added to the root dialog as you can only call dialogs that are registered off the current container (AdaptiveDialog) or a parent.

**Comment by cosmicshuai** [comment]
I think this PR https://github.com/microsoft/botbuilder-dotnet/pull/4880 has the feature you want here. The "RegisterDialogs" field here is corresponding to the 'dialogs' in the current solution.

**Comment by EricDahlvang** [comment]
Closing this, since the sdk now supports an array of dialogs to work around this. Composer has a backlog item to support the dialogs array.
