### ISSUE TITLE
websocket disconnected Errors while sending a message are eaten and are not thrown back

### ISSUE THREAD

**Issue by PranemMSFT** [microsoft/botbuilder-dotnet#5793]
## Version
4.13.1

## Describe the bug
when using a bot with telephony/DLS speech enabled and are having a conversation over websockets today when the send message fails due to websocket being disconnected the error is not being thrown back to the runtime. would like it to be thrown back so we can build a mechanism to resend all the messages when channel reconnects!

https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs
line 406-427

## Expected behavior
throw original exceptions back to the runtime

**Comment by carlosscastro** [comment]
We're doing a patch to fix this this week.
