### ISSUE TITLE
LUIS abstractions should provide first class support for spell check

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#5794]
@carlosscastro Spell check can be added by adding the `mkt-bing-spell-check-key` header to the http requests to LUIS and then LUIS will return the corrected version into AlteredText. The gap is that the SDK does not expose a way to control headers declaratively or a higher level property specific to spell check.

**Comment by johnataylor** [comment]
@carlosscastro
A workaround could likely be made by subclassing the recognizer, creating a new declarative type and controlling the headers internally. Not ideal or nice though, but a way out.

Regarding the long term support for spell check, seems like just by adding a property we could support this. We'd need to figure out where this lies in terms of priorities but it would be great to create an issue to track it and triage.

**Comment by sgellock** [comment]
There's been a thread on this where @darrenj an I have weighed in.  We are of 1 mind that we wouldn't do this work.  if you guys feel differently, then lets have a discussion

**Comment by tracyboehrer** [comment]
No plan to implement this.
