### ISSUE TITLE
OrchestratorRecognizer: failed to cast ReadOnlyCollection<Result> to List<Result>

### ISSUE THREAD

**Issue by sibbl** [microsoft/botbuilder-dotnet#5806]
## Version
4.14

## Describe the bug
The OrchestratorRecognizer fails with the following exception when getting a result with a low score:

```
Unable to cast object
of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[Microsoft.BotFramework.Orchestrator.Result]'
to type 'System.Collections.Generic.List`1[Microsoft.BotFramework.Orchestrator.Result]'. 
```

The following line causes it:
https://github.com/microsoft/botbuilder-dotnet/blob/4.14/libraries/Microsoft.Bot.Builder.AI.Orchestrator/OrchestratorRecognizer.cs#L178

I'd also be glad if `UnknownIntentFilterScore` wasn't private so that I could just set it to 0 for now. However there doesn't seem to be a workaround possible.

**Comment by taicchoumsft** [comment]
@sibbl , this was fixed in 4.14.1 with PR #5653, do you think you could update all your packages in `package.json` to `4.14.1` and try again? Thanks.

**Comment by taicchoumsft** [comment]
Adding @daveta for visibility

**Comment by sibbl** [comment]
@taicchoumsft thanks for the feedback. Can confirm that 4.14.1 fixes the exception.

It would still be great if it would be possible to define a custom `UnknownIntentFilterScore`. Should I open another issue for this feature request?

**Comment by taicchoumsft** [comment]
@sibbl , yes please create a new issue for this feature request. Thanks!  Closing this issue for now, please feel free to re-open if something else needs to be addressed.
