### ISSUE TITLE
Adaptive express prebuilt function empty returns false when passed with a null value

### ISSUE THREAD

**Issue by arvindkannan** [microsoft/botbuilder-dotnet#5813]
## Version
AdaptiveExpressions ~ 4.11.1

## Describe the bug
The Adaptive expression documents says "empty function" will return "TRUE" in-case of object is empty or else FALSE. But if we try pass the value as null then the function returns FALSE instead of returning TRUE.

## To Reproduce
```
var Dictionary<string, dynamic> flowData ;
new ExpressionProperty<dynamic>("${empty(null)}").GetValue(flowData) = returns FALSE
```

## Expected behavior
Expression to return TRUE as null is equivalent to empty object.

## Screenshots
As per MS-doc for adaptive expression prebuilt functions:

> ![image](https://user-images.githubusercontent.com/26468070/127786397-12fe64c8-c69d-4a33-9a66-a8d2092f480a.png)

Reference Image for the reported Issue: 

![image](https://user-images.githubusercontent.com/26468070/127786487-7f32da89-5372-4f4e-80da-89ac38071ff7.png)

## Additional context
Documentation as in here [adaptive-expressions-prebuilt-functions-empty](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#empty)

**Comment by benbrown** [comment]
@luhan2017 This looks like an issue in Adaptive Expressions. Can you help me find the right person on the team to take a look?

**Comment by Danieladu** [comment]
fixed by: https://github.com/microsoft/botbuilder-dotnet/pull/5338
