### ISSUE TITLE
Message Activity isn't updated with bot response in Middleware

### ISSUE THREAD

**Issue by ClintFrancis** [Microsoft/botbuilder-dotnet#584]
When testing out the echo bot sample, adding a piece of simple middleware never updates the text for the bot's response. When putting a break point in I can see that the emulator receives the response prior to the middleware hitting the break point.

If this isn't a bug, how do I log the bot's response??

```
public async Task OnTurn(ITurnContext context, MiddlewareSet.NextDelegate next)
{
    if (context.Activity.Type == ActivityTypes.Message)
    {
        var userUtterance = context.Activity?.AsMessageActivity()?.Text.Trim().ToLower();

        await next().ConfigureAwait(false);

        var botResponse = context.Activity?.AsMessageActivity()?.Text.Trim().ToLower();
    }
}
```

**Comment by cleemullins** [comment]
@ClintFrancis +1 to evertyhign @drub0y has said. 

This seems like more a documentation & samples issue than anything else. Any suggestions for how to better document this and make the ability more self-discoverable?

**Comment by ClintFrancis** [comment]
A point to note, but the updated sample needs amending as it doesn't return a ResourceResponse[]

```
context.OnSendActivities(async (handlerContext, activities, handlerNext) =>
{
	// Add any pre-send logic here.

	// Continue the send activities process.
	await handlerNext();

	// Add any post-send logic here.
});
```

Ending with method with this works for the moment:
`return await handlerNext.Invoke();`

**Comment by vishwacsena** [comment]
@ClintFrancis - this is documented [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-create-middleware?view=azure-bot-service-4.0&tabs=csaddmiddleware%2Ccsetagoverwrite%2Ccsmiddlewareshortcircuit%2Ccsfallback%2Ccsactivityhandler).

**Comment by abhisheknist149** [comment]
@vishwacsena  Do we have C# sample on how to invoke the SendActivities event handler. The documentation online just has class declaration.
