### ISSUE TITLE
Implement support for gathering request JWT or token claims within Middleware TurnContext.

### ISSUE THREAD

**Issue by Debro012** [microsoft/botbuilder-dotnet#5846]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
As Web Apps which serve as bots must be public facing, we need to implement the ability to only allow specific tenants to access the bot. It would be best to implement this via determining the tenant associated with the token passed in requests to the bot. Even though activities from the Teams channel include tenant info within the activity, this is not the case for other channels (DirectLine, WebChat, etc.) Therefore, we need to retrieve the tenant data based on the token claims.

**Describe the solution you'd like**
I'm seeking to implement the ability to directly read and decrypt bearer tokens (JWT) or gather all claims associated with bearer tokens (JWT) via middleware. At this time, I have not found an ability to gather the request token, or its claims, via the TurnContext passed to middleware via OnTurnAsync.

**Describe alternatives you've considered**
One workaround would be to implement this check within the controller, for all post requests, prior to the request being passed to the adapter. However, it seems better to leverage this ability via the middleware which the Bot Adapter passes requests through.

**Additional context**
N/A

**Comment by EricDahlvang** [comment]
Hi @Debro012 

Have you tried retrieving the ClaimsIdentity from TurnState?
```
var claims = turnContext.TurnState.Get<IIdentity>(BotAdapter.BotIdentityKey) as ClaimIdentity
```

**Comment by mrivera-ms** [comment]
Closing as answered. @Debro012, please re-open this issue if you have any further questions.
