### ISSUE TITLE
For a prompt, Dialog.Begin with default option causes a NullReferenceException

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#586]
**Issue**

1. Assume a turn context `context`, a Dictionary<string, object> `state`, and a Dialogs.TextPrompt `prompt`.
1. Call `prompt.Begin(context, state)`
1. **Result**: a NullReferenceException from Prompt<T>.BeginDialog, args is null.

**Expected**

Prompt<T>.BeginDialog does not throw an exception.

**Comment by johnataylor** [comment]
looking at this today - eta end of week with some other fixes around prompts and dialogs
