### ISSUE TITLE
[Streaming] Quality: Integration tests with legacy client + new server 

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#5865]
Parent issue: #5630

**Comment by carlosscastro** [comment]
First E2E test with legacy client and new server is here: https://github.com/microsoft/botbuilder-dotnet/blob/feature/streaming-pipelines/tests/Microsoft.Bot.Connector.Streaming.Tests/Integration/InteropApplicationIntegrationTests.cs

And we already found a bug thanks to it related to json reader adding quotes around json and breaking the protocol.
