### ISSUE TITLE
Dialog.Begin with optional dictionary causes InvalidCastException 

### ISSUE THREAD

**Issue by rhuebner76** [Microsoft/botbuilder-dotnet#588]
While this issue is much like #586, here providing the optional `IDictionary<string,object> dialogArgs` argument to a class implementing `Dialogs.Prompt<T>` and calling BeingDialog throws a System.InvalidCastException when using an instance of `Dictionary<string,object>`. 

**Issue** 
 1. Given: a turn context `ITurnContext context`, a state `Dictionary<string, object> state`, options ` Dictionary<string, object> options`, and Dialogs.Prompt<T> `prompt` (e.g., Dialogs.TextPrompt).

2. Call: `prompt.Begin(context, state, options);` 

3. Result: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'Microsoft.Bot.Builder.Dialogs.PromptOptions'.

**Expected**
BeginDialog does not throw an exception.

**Comment by cleemullins** [comment]
@johnataylor  - could you take a look at this? I'm guessing it's a 30 second fix.

**Comment by johnataylor** [comment]
looking at this today - eta end of week with some other fixes around prompts and dialogs
