### ISSUE TITLE
ActivityHandler->OnAdaptiveCardInvoke returns malformed response

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#5881]
## Version
4.14.1

## Describe the bug
OnAdaptiveCardInvoke() is modeled that it returns a InvokeResponse with .Body = card.
OnInvokeActivity() wraps the response with another InvokeResponse, which then is returned like this:
```json
{
   "statusCode": 200,
   "body": {
          "status": 200,
           "type":"application/vnd.microsoft.card.adaptive",
           "value": {  
                "type": "AdaptiveCard" ,
              ...
            }
   }
}
```

This does not match the definition in the docs:
* statusCode
* type (multiple format types)
* **value** - which is payload based on format types
See https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model#response-format

## Expected behavior
It should be returning this data structure.
```json
{
   "statusCode": 200,
   "type": "application/vnd.microsoft.card.adaptive", 
   "value": {
        "type": "AdaptiveCard",
        ...
   }
}
```
I think you need to:
1. Add overflow property to InvokeResponse
```Csharp
        [JsonExtensionData(ReadData = true, WriteData = true)]
        public JObject  AdditionalProperties { get; } = new JObject();
```
2. I think you need to define AdaptiveCardActionExecuteResponse as derived from InvokeResponse
```csharp
  public class AdaptiveCardExecuteResponse : InvokeResponse 
  {
     [JsonProperty("type")]
     public string Type {get;set;}

     [JsonProperty("value")]
      public object Value {get;set;}
}
```
Unit tests to validate this behavior because I think the adapter might balk trying to send an InvokeResponse with null body.

-----
BTW: You can work around this issue by overloading the OnTurnAsync method to dispatch the Action.Execute invoke yourself:
```csharp
        public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (turnContext.Activity.Type == ActivityTypes.Invoke && turnContext.Activity.Name == "adaptiveCard/action")
            {
                AdaptiveCardExecuteResponse result = ...;
                await turnContext.SendActivityAsync(new Activity { Value = result, Type = ActivityTypesEx.InvokeResponse }, cancellationToken);
                return;
            }
            await base.OnTurnAsync(turnContext, cancellationToken);
        }

```

**Comment by EricDahlvang** [comment]
The linked doc states:

> If the Bot did process an incoming adaptiveCard/action Invoke activity (i.e. if the Bot's code was involved at all in processing the request), the HTTP response's status code returned by the Bot must be equal to 200 and the body of the HTTP response must be formatted as follows:

```json
{ 
    "statusCode": <number (200 – 599)>, 
    "type": "<string>", 
    "value": "<object>"
} 
```

^ this is the BODY of the InvokeResponse, not the same level as the invoke response. The intent is to have two status. One for the invoke, and one for the execution of the invoke itself.

ActivityHandler:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L459

```cs
case "adaptiveCard/action":
    var invokeValue = GetAdaptiveCardInvokeValue(turnContext.Activity);
    return CreateInvokeResponse(await OnAdaptiveCardInvokeAsync(turnContext, invokeValue, cancellationToken).ConfigureAwait(false));
```

Sample:
https://github.com/microsoft/BotBuilder-Samples/pull/3379/files#diff-0e9b6c71aa241fd62576fee9e7d33ef34976569d8b8d49169bbfe0f1274d2ec5R57

```cs
new AdaptiveCardInvokeResponse()
{
    StatusCode = 200,
    Type = AdaptiveCard.ContentType,
    Value = new CardResource(Path.Combine(".", "Cards", "CardTwo.json")).AsJObject()
}
```

AdaptiveCards package:
https://github.com/microsoft/botframework-components/blob/main/packages/AdaptiveCards/Actions/SendActionExecuteResponse.cs#L116

```cs
            var response = new JObject()
            {
                { "statusCode", statusCode },
                { "type", mimeType },
                { "value", JToken.FromObject(value) }
            };
            var activity = new Activity(type: ActivityTypesEx.InvokeResponse, value: new InvokeResponse() { Status = 200, Body = response });
            await dc.Context.SendActivityAsync(activity, cancellationToken).ConfigureAwait(false);
```

**Comment by EricDahlvang** [comment]
Met with Tom offline. Closing as designed.
