### ISSUE TITLE
Seeing InputDialog is missing Prompt

### ISSUE THREAD

**Issue by praveenvavilla** [microsoft/botbuilder-dotnet#5888]
## Describe the bug

I am seeing below error after oAuth prompt log in and entering magic code 
![image](https://user-images.githubusercontent.com/55256942/130293577-2124c662-68f5-433d-a55c-52d49fcba01e.png)

I see the below traces in output
 Information: 0 : 1: 'conversationUpdate' ==> custom           ==> Template 
 Information: 0 : 1: 'conversationUpdate' ==> custom           ==> Template 
The thread 0x5950 has exited with code 0 (0x0).
The thread 0x5ea8 has exited with code 0 (0x0).
The thread 0x8748 has exited with code 0 (0x0).
Information: 0 : 2: 'xxxxxx' ==> activityReceived ==> OAuthInput 
Information: 0 : 1: 'xxxxxx' ==> recognizeUtterance ==> WelcomeDialog 
Information: 0 : 2: 'xxxxxx' ==> recognizeUtterance ==> CrossTrainedRecognizerSet 
Information: 0 : 2: 'xxxxxx' ==> activityReceived ==> WelcomeDialog 
Information: 0 : 4: 'xxxxxx' ==> recognizeUtterance ==> CrossTrainedRecognizerSet 
Information: 0 : 2: 'xxxxxx' ==> activityReceived ==> xxxx
'' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Web.HttpUtility.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Information: 0 : 4: 'xxxxxx' ==> recognizeUtterance ==> CrossTrainedRecognizerSet 
Information: 0 : 6: 'xxxxxx' ==> error            ==> OAuthInput 
Information: 0 : 6: 'xxxxxx' ==> error            ==> WelcomeDialog 
Information: 0 : 6: 'xxxxxx' ==> error            ==> xxx
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll

Please let me know if I am missing anything?
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by stevkan** [comment]
Thank you, @dmvtech, for your help with this issue.

@praveenvavilla, we are determining who the appropriate owner for fixing this should be and will have it re-assigned at that time.

**Comment by praveenvavilla** [comment]
sure thank you @stevkan

**Comment by lauren-mills** [comment]
@mrivera-ms - Can you help evaluate this bug against the SDK backlog?

**Comment by sw-joelmut** [comment]
Hi @praveenvavilla, @stevkan and @dmvtech.
We tried to reproduce the issue without success. Could you share the sample mentioned in previous comments, so we can have a better understanding of this specific case?

Thanks.

**Comment by gabog** [comment]
Hi @praveenvavilla, closing this one for now, feel free to re-open if you are still having issues.
