### ISSUE TITLE
When a child dialog is called from the parent dialog, and the subsequent action in the parent dialog is a custom action, the child dialog does not complete the flow until and unless the custom action completes its execution

### ISSUE THREAD

**Issue by DebdeepBurman** [microsoft/botbuilder-dotnet#5902]
We have a parent dialog that calls a child dialog. Right after the child dialog returns the flow back tot he parent dialog, a custom action is triggered. the surprising thing that we have noticed is, even if the child dialog completes the execution and returns the data back to the parent dialog, from the insights we see, the child dialog execution does not seem to be completed until the custom action in parent dialog completes the action.

![image](https://user-images.githubusercontent.com/50698495/135875071-c52aa936-946f-4d16-89a4-50cdf20d72a3.png)
![image](https://user-images.githubusercontent.com/50698495/135875352-c5f5c233-b34e-4933-a8d1-a914569e90aa.png)

**Comment by stevkan** [comment]
I am trying to repro by recreating a simplified version of the Cx's code. At this point, I am unable to repro, but I haven't completed my testing. I'll post an update when I know more.

**Comment by stevkan** [comment]
Unfortunately, I am no longer able to repro this issue. After creating the below attached bot as testable code I wanted to run it to be sure it was in working order. While running, I noticed the child dialog was now appearing to complete before the custom action ran. I then re-opened the original bot I was using for testing with and it also no longer is producing the error. With a colleague, we tried recreating the error using different approaches that worked the day before, however none were successful.

The last approach we took was to use the track event telemetry sent from within the custom action to log the time the process actually ran, as opposed to relying on the timestamp the telemetry data was sending (which is the time the track event occurred). We noticed that there was approximately an 11 sec. discrepancy between the custom action's process run time and the telemetry's timestamp (with the custom action occurring first). However, this is only an observation and isn't necessarily indicative of an issue as there isn't an apparent way to get the process run time of the dialogs, for comparison, outside of relying on the telemetry timestamp.

It should be noted that nothing was changed in the bot that would have resulted in the issue able to be repro'd one day and not the next.

Here you can see the timestamp of the telemetry track event, titled "ChildDialogEnd" which was placed at the end of the child dialog, has virtually the same timestamp as the custom action telemetry track event, titled "myEvent". The passed in property of the custom action, titled "myProp", displays the process's run time that is 11 secs. earlier.

![image](https://user-images.githubusercontent.com/18403946/136824159-0b9fde7d-e749-4cb4-b66f-a11df93e7159.png)

[customActionBot.zip](https://github.com/microsoft/botbuilder-dotnet/files/7324065/customActionBot.zip)

**Comment by EricDahlvang** [comment]
Resolved offline
