### ISSUE TITLE
Carousel rendered in full msteams width

### ISSUE THREAD

**Issue by JordyGit** [microsoft/botbuilder-dotnet#5903]
Adaptive Card property, see [Documentation here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#full-width-adaptive-card):
"msTeams": { "width": "full" },

Carousel made with:
MessageFactory.Carousel

**Is your feature request related to a problem? Please describe.**
Adaptive cards can use the msteams full witdth property to be rendered bigger in teams, alto using the same cards in a carousel or adding the property manually to a carousel, the carousel keeps being rendered smaller.

**Describe the solution you'd like**
Carousels rendered wider if the property is present or when the adaptive cards in the carousel have the property.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by mwrothbe** [comment]
Hi.  Is there an update on this issue?  It's impactful as the carousel width that is rendered is actually smaller than a normal card much less the full width that it is supposed to be.  Carousel cards in Teams used to render correctly, but at some point recently, that changed.

**Comment by v-chetsh** [comment]
@mwrothbe - We have informed the concerned team and the team is looking into it.

**Comment by Meghana-MSFT** [comment]
@JordyGit, @mwrothbe - This issue is being tracked here https://github.com/MicrosoftDocs/msteams-docs/issues/4394. Please follow this for further updates.
