### ISSUE TITLE
turnContext.Activity.Name does not support name:invoke and breaks adaptive card invoke actions from Android Clients

### ISSUE THREAD

**Issue by GauravES** [microsoft/botbuilder-dotnet#5907]
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs

switch (turnContext.Activity.Name)  does not support Name = invoke.     Starting ~Sep 2021 the Teams client on Android (but not IOS or Desktop/Web) have started to send name:invoke in the invoke activity JSON sent to the bot (Prior to this client version this JSON element name: was missing).

As a result all Adaptive Card invoke activity processing has broken when submitted from Teams Android client and  a http 501 error code is returned to the Teams Android client.

(We had to override this as a work around in our bot 

```
+        protected override async Task<InvokeResponse> OnInvokeActivityAsync(ITurnContext<IInvokeActivity> turnContext,
+            CancellationToken cancellationToken)
+        {
+            switch (turnContext.Activity.Name)
+            {
+                case "invoke":
+                    return await OnTeamsCardActionInvokeAsync(turnContext, cancellationToken).ConfigureAwait(false);
+                default:
+                    return await base.OnInvokeActivityAsync(turnContext, cancellationToken);
+            }
+        }
```
)

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by EricDahlvang** [comment]
Hi @GauravES 

Thank you for reporting this issue. Looks like a bug in Teams Android. I'm glad you've found a workaround!

The Teams team is investigating. We will get back to you soon.

**Comment by EricDahlvang** [comment]
An internal bug has been filed to fix this on Android.

Thanks again for reporting the issue.

**Comment by EricDahlvang** [comment]
Hi @GauravES 

The bug has been fixed and is in the process of rolling out. Closing this issue now.
