### ISSUE TITLE
Adaptive function sum does not work with JArray

### ISSUE THREAD

**Issue by Rich-biomni** [microsoft/botbuilder-dotnet#5909]
## Version
4.14.1

## Describe the bug
When using the Sum adaptive function, it will error on a JArray as the argument. Error 'with 1 is not a number',

Note: There will be other function that have this same issue.

## To Reproduce
1 using an adaptive dialog,
2 Set a property to an array value e.g dialog.array1 = [1.0,5.0]
3 Set another property to sum the array e.g = dialog.result = sum(dialog.array1)
  - Note this will not error as set property hides the error and you end up with null
So to see the error 
4 Send a response with template as ${sum(dialog.array1)}

Error will occur

## Expected behavior
No error the array is valid and should be summed to 6.0

## Additional context

The reasons this is going wrong: The original array will be stored in dialog state as a .net list but when accessed will be a JArray

The Sum function uses FunctionUtils.VerifyNumericList which is not handling the JArray

 return FunctionUtils.Apply(
                        args =>
                        {
                            var operands = FunctionUtils.ResolveListValue(args[0]).OfType<object>().ToList();
                            return operands.All(u => u.IsInteger()) ? operands.Sum(u => Convert.ToInt64(u, CultureInfo.InvariantCulture)) : operands.Sum(u => Convert.ToSingle(u, CultureInfo.InvariantCulture));
                        },
                        **FunctionUtils.VerifyNumericList**);

 FunctionUtils.ResolveListValue deals with JArray get getting the actual underlying value, But
 FunctionUtils.VerifyNumericList Does not handle JArray so when that code the checks the type it fails
 
On a side note Json.net uses doubleto store a number and the Bot Framewwork is littered with single conversations all over the place <eek>

**Comment by Danieladu** [comment]
@munozemilio feel free to re-assign it to me because I am familiar with the context of this issue and the source code.
