### ISSUE TITLE
Teams bot SSO is not working as expected

### ISSUE THREAD

**Issue by shashank16341** [microsoft/botbuilder-dotnet#5923]
I am trying to implement the Teams Bot SSO for our requirement. It is not giving the result as expected. I am facing multiple issues listing below.

1. In the teams web, bot is giving the consent pop up and giving the result as well by generating authorization token in the back end. Refer the below screenshot:
![ConsentWithDocuments](https://user-images.githubusercontent.com/61079487/138046725-a644862c-6340-4841-8ec2-2b62e0ac8806.png)

<img width="675" alt="ConsentPopUpInWeb" src="https://user-images.githubusercontent.com/61079487/138046758-1af0bc63-a22d-46be-bbec-4fd260f1664a.PNG">

<img width="660" alt="CorrectResponse in Desktop app" src="https://user-images.githubusercontent.com/61079487/138048236-72828389-006e-4bfa-8202-ceeb39fe4317.PNG">

2. For the admin it is working as expected but for other users it is not working at all. Token exchange is not happening in the back end. Have a look on the below screenshot.
![Not working for other users](https://user-images.githubusercontent.com/61079487/138075222-30f080e8-3249-4987-ba63-e0f7c6927dc3.png)

Referred Github solution:
https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/teams-sso/csharp_dotnetcore

Referred docs to create AAD aap:
https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/teams-sso/csharp_dotnetcore/SSOSetup.md

**Comment by shashank16341** [comment]
Hi Eric,

Thanks for your reply.

I have verified scopes and Admin & Users consent it's correct and I have replaced TokenExchangeHelper.cs class with TokenSSOTokenExchangeMiddleware.cs class.

Still, It did not work for me. I am getting response from phone teams app but from the web and desktop client I am not getting response.

Thank you in advance.

**Comment by timoleo23** [comment]
Hi @shashank16341, can you please check the Azure AD manifest of your app registration and look at parameter "accessTokenAcceptedVersion". The Expected value should be 2 (cf. screenshot)

![image](https://user-images.githubusercontent.com/17161633/140882231-8110a071-8962-4029-9dd4-e8f7a409e244.png)

**Comment by shashank16341** [comment]
Hi @EricDahlvang,
I have verified in the manifest "accessTokenAcceptedVersion" value is 2.

**Comment by timoleo23** [comment]
Thank for the confirmation @shashank16341 - Could you please confirm the following 
_"I am getting response from phone teams app but from the web and desktop client I am not getting response."_

Could you please confirm the cases when the consent prompt is displayed vs not displayed?

- Teams Mobile client / Teams Desktop client / Teams web client
- User is an admin (in Azure AD) / User is a member (in Azure AD)

Looks like you experience different behaviour based on the configuration

**Comment by EricDahlvang** [comment]
Closing this due to no response. Please let us know if you still require assistance.
