### ISSUE TITLE
DCR: add a new DialogContext.IsOnStack() method

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#593]
When crafting your bots interruption logic you may want to disable certain interruptions if a given dialog is running. The `DialogContext.IsOnStack()` method would let you pass in a list of dialog ID's and would return `true` if any of those dialogs are currently on the stack. 

Open ended text prompts like "what would you like to call the file?" are good examples where you'd want to disable listening for the user to say things like "help".  I very well could have wanted to name my file "help".

An extension to taking a list of dialog ID's as strings would be to also support wildcard matching using a regular expression.

**Comment by yochay** [comment]
@johnataylor note backlog
