### ISSUE TITLE
Suggestion to add telemetry when sending 400 response code for invalid activity

### ISSUE THREAD

**Issue by ninilang** [microsoft/botbuilder-dotnet#5934]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Currently, the SDK returns a 400 response code when the incoming activity is null or the activity type is empty. [This is the piece of code](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs#L165) being referred to. Since no trace is logged here, it's difficult to know if this piece of code actually caused the 400 result code.

**Describe the solution you'd like**
A trace indicating that we returned a 400 response here will make it easier while look at telemetry.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by mrivera-ms** [comment]
@ninilang, can you indicate what information you need added in the message?
