### ISSUE TITLE
Microsoft.Bot.Builder.Adapters.Facebook.FacebookMessage class is missing the Referral property for existing user scenario.

### ISSUE THREAD

**Issue by podgito** [microsoft/botbuilder-dotnet#5946]
## Version
4.13.2 +

## Describe the bug
Facebook describes two scenarios to the referral parameter being passed. 
1) Uses the Postback root property which is catered for but scenario 
2) uses the referral root property which can't be used. 

See here both payload scenarios here
https://developers.facebook.com/docs/messenger-platform/discovery/m-me-links/#reading_parameter

## To Reproduce
Use an m.me link with ref parameter for an existing page user scenario. Webhook sends this payload.

{
  "sender":{
    "id":"<PSID>"
  },
  "recipient":{
    "id":"<PAGE_ID>"
  },
  "timestamp":1458692752478,
  "referral": {
    "ref": "ref_data_in_m_dot_me_param",
    "source": "SHORTLINK",
    "type": "OPEN_THREAD",
  }
}

FacebookMessage class is missing the referral property in the root

## Expected behavior
The Facebook message should have the Referral parameter set if available

**Comment by lauren-mills** [comment]
@mrivera-ms - Can you help get this PR reviewed?

**Comment by ceciliaavila** [comment]
Hi @mrivera-ms, we reproduced the issue and after applying the fix in PR #5948 it was solved. Also, the PR looks good 👍

**Comment by benbrown** [comment]
This has been fixed.
