### ISSUE TITLE
OAuthInput does not work correctly when its not the first dialog, when using web chat without magic code

### ISSUE THREAD

**Issue by Rich-biomni** [microsoft/botbuilder-dotnet#5947]
## Version
4.14.1

## Describe the bug
The conversation state is not correct when the bot receives the token/response event because the channel id is directline not webchat.

When a bot has an Auth dialog that is not the first dialog and there has already been a end-of-turn the auth dialog is not continuing after the user has signed in and the bot has received the token/response event

## To Reproduce
1) In azure create a bot, along with an oauth connection to an app registration.
2) configure the bot.
     1st dialog should be a question prompt so it forces an end-of-turn 
     2nd dialog should be the oauthinput configured to the oauth connection from 1 
3) setup a web site with web chat using a token (/v3/directline/tokens/generate) including the trusted origin so that the auth wont use a magic code
4) run the bot
    sign in
    Note the question-prompt is reshown

## Expected behavior
The oauth-input should continue and receive the token/response event it should not show the first dialog. 

When the token/response event is sent to the bot controller the channelid should not be directline it should be webchat

## Additional context
So what I think is happening.
Because the oauthinput dialog is not the 1st dialog, we need conversationstate to maintain the dialog-state stack other wise ActiveDialog will not be set and the first dialog will start again incorrectly

when a user is chatting in webchat the channelid is 'webchat' and the GetStorageKey used to get the state information is based of class ConversationState : BotState  $"{channelId}/conversations/{conversationId}"

Now when the token/response event is sent after the sign in the channel is is 'directline' this means that the GetStorageKey will be different and hence the dialog-state stack will be different and therefore the ActiveDialog will be null meaning the oauthinput dialog does not continue.

Think this will be the same with the AuthPrompt dialog as well

**Comment by stevkan** [comment]
@Rich-biomni, can you clarify for me at what point in the dialog you are attempting to have the OAuth prompt display? If you could provide any code that would also be helpful to see.

In the meantime, I will attempt a repro of this. I can say that using the JS SDK, I am able to call the OAuth prompt at any point without issue (I do so in a test bot I already have set up). I haven't heard of any other reported issues.

Also, was this working in other versions and isn't in the latest? Or, is it not working in any version, if you have tried?

**Comment by Rich-biomni** [comment]
@stevkan 

Using .net C# and only know its not working in version 4.14.1 which is what we are using

Example Dialog code
-------------------


    var ad = new AdaptiveDialog("adtest");

    ad.Triggers.Add(new OnBeginDialog {
    Actions =
    {
        new CodeAction(async (dc,o) =>
        {
            await dc.Context.SendActivityAsync($"activity: type:{dc.Context.Activity?.Type}, channel:{dc.Context.Activity?.ChannelId}");
            await dc.Context.SendActivityAsync($"type signout - to sign out - or anything else to carry on");
            return new DialogTurnResult(DialogTurnStatus.Waiting);
        }),

        new CodeAction(async (dc,o) =>
        {
            if(dc.Context.Activity?.Text == "signout")
            {
                await  new OAuthInput{ MaxTurnCount = 0, Text = "SignIn", ConnectionName = "oauth", Property = "turn.accessTokenResponse" }.SignOutUserAsync(dc);
                await dc.Context.SendActivityAsync($"signed out");
            }
            return await dc.EndDialogAsync();
        }),

        new OAuthInput{ MaxTurnCount = 0, Title = "SignIn", ConnectionName = "oauth", Property = "turn.accessTokenResponse" },

        new CodeAction(async (dc,o) =>
        {
            var accessTokenReposnse = dc.State.GetValue<TokenResponse>("turn.accessTokenResponse");
            await dc.Context.SendActivityAsync($"have token: {accessTokenReposnse != null}");
            return await dc.EndDialogAsync();
        }),
    }
    });





OAuth must have **NO magic code**, so using web chat with a token from azure /v3/directline/tokens/generate

Run the adaptive dialog
 bot: activity: type:conversationUpdate, channel:webchat
 bot: type signout - to sign out - or anything else to carry on

 (user has not signed in before ever)
 user: anything

 bot: renders Auth sign in
 user: clicks SignIn - new browser tab opens and users signs in without requiring Magic Code

 bot: receives activity type event channel:directline <=== this is the oauth token event but the channel has changed

 bot: type signout - to sign out - or anything else to carry on <=== this is wrong is should be "have token True", but because the channelId has changed the activedialog state is incorrect so its gone back to the first action

Include video of it happening:

[Tenjin OAuth Issue.zip](https://github.com/microsoft/botbuilder-dotnet/files/7496456/Tenjin.OAuth.Issue.zip)

**Comment by stevkan** [comment]
@Rich-biomni, thank you for your patience. I'm having some difficulty creating a repro using only the code you have provided above inserted into a bot. Are you able to include a zipped file of your bot that I could then run and test against?

**Comment by stevkan** [comment]
Closing due to lack of response.
