### ISSUE TITLE
Facebook PostBack message cannot be deserialised.

### ISSUE THREAD

**Issue by podgito** [microsoft/botbuilder-dotnet#5951]
## Version
4.16.*

## Describe the bug
Facebook postback messages fail deserialization because the referral parameter expecting a string but is an object.
See postback payload sample here: https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_postbacks/

## To Reproduce
Created unit test with example payload - ProcessAsyncShouldSucceedWithPostBackMessages in PR attached.

## Expected behavior
Postback messages should be deserialized and an activity created

**Comment by ryanlengel** [comment]
@mrivera-ms can you assist with getting this PR reviewed? Thank you!

**Comment by gabog** [comment]
Thanks for the submission @podgito, I will review the PR and get back to you on it.

**Comment by gabog** [comment]
Hi, the custom adapters are in the process of being moved to the community repo. 

Here is the link to the PR: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/pull/461  

Can you please post your issue and PR there? 

Thanks
