### ISSUE TITLE
FileConsentCard's Descripton property has no way to escape the ampersand character.

### ISSUE THREAD

**Issue by hopsusa** [microsoft/botbuilder-dotnet#5973]
## Version
4.15.0

## Describe the bug
On a FileConsentCard, it does not appear to be possible to use an unescaped ampersand in the Description property. The same issue seems to be present on the Attachment name.

## To Reproduce
The following code is used to generate a FileConsentCard for the user to either accept or decline a file. The file name contains an ampersand which is not formatted correctly.
```
var consentContext = new Dictionary<string, string>
{
	{ "blobId", blob.BlobId },
	{ "filename", blob.FileName },
	{ "messageString", blob.Message }
};

var fileCard = new FileConsentCard
{
	Description = "P&LTest.xlsx",
	SizeInBytes = blob.FileLength,
	AcceptContext = consentContext,
	DeclineContext = consentContext
};

var asAttachment = new Attachment
{
	Content = fileCard,
	ContentType = FileConsentCard.ContentType,
	Name = "P&LTest.xlsx",
};

replyActivity.Attachments.Add(asAttachment);

await turnContext.SendActivitiesAsync(activities.ToArray(), cancellationToken);
```
The above produces the following file consent card.

![image](https://user-images.githubusercontent.com/5429923/142038631-04ff5369-2768-420d-b703-53ba24afe6fa.png)

Clicking the allow button successfully distributes the file, but the name is changed so it cannot be opened in the default app, Excel in this case.

I have tried to escape the ampersand with &amp; and with %26 without success.

## Expected behavior
File should appear with the ampersand in place as it was set on the Description for FileConsentCard and the Name for an Attachment.

**Comment by dmvtech** [comment]
I can reproduce this. I tested using sample 56 and poked around in [Attachments](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Attachment.cs), [AttachmentExtensions](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Teams/AttachmentExtensions.cs), [FileUploadInfo](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Teams/FileUploadInfo.cs)  and others, and just didn't see anything regarding changing (i.e. encoding) the name. My assumption is that this is done on the Teams side of things.

@mrivera-ms Any thoughts on this one?

**Comment by mrivera-ms** [comment]
@clearab, can you comment on this issue?

**Comment by clearab** [comment]
I've opened an issue with the Teams group, as I think this is a client-side rendering problem. I'll follow up here when I hear back.

**Comment by gabog** [comment]
Hi @clearab, did they get back to you on this one?

**Comment by clearab** [comment]
Still waiting on a response from Teams.

**Comment by Meghana-MSFT** [comment]
We are looking into this issue. We will update you soon.

**Comment by Meghana-MSFT** [comment]
We are able to repro this issue, we are raising a bug for the same. We will update you.

**Comment by tdurnford** [comment]
@Meghana-MSFT Any updates on this issue?

**Comment by Meghana-MSFT** [comment]
Currently we do not have any updates, Team is working on it.

**Comment by carlosscastro** [comment]
@clearab could you share the plan moving forward on this issue?

**Comment by clearab** [comment]
As this item is on the Teams side, @Meghana-MSFT could you provide an update on if this bug is going to be prioritized?

**Comment by mrivera-ms** [comment]
@Meghana-MSFT, @clearab, are there any updates?

**Comment by axelsrz** [comment]
@Meghana-MSFT @clearab do we have any updates on this one?

**Comment by clearab** [comment]
The bug has been filed, but currently there is no timeline for when it will be fixed.

**Comment by gabog** [comment]
Closing this one as it belongs to Teams and it is being tracked there.

**Comment by hopsusa** [comment]
@gabog Do you have a link to the Teams ticket that I can track? We have a commercial application that is currently working around this issue. I need to know when this is fixed so we can remove the workaround.

**Comment by Meghana-MSFT** [comment]
@hopsusa - This issue has been fixed, can you please verify and confirm?

**Comment by Meghana-MSFT** [comment]
@hopsusa - Did you get a chance to verify the fix?

**Comment by hopsusa** [comment]
@Meghana-MSFT - it looks like the file is displaying properly when it is delivered...

![image](https://user-images.githubusercontent.com/5429923/206280408-6e8d5889-20ae-4cfd-8a0d-e1759e80a490.png)

...but the preview seems to fail...

![image](https://user-images.githubusercontent.com/5429923/206280583-022f2829-a13e-4b35-a56e-ccf38b771dde.png)

If I download the file, it removes the ampersand and any text after in the name. However, if I rename the file locally and add the extension, I am able to open it successfully.

Thanks,

Matt
