### ISSUE TITLE
Update projects to .Net 6

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#5977]
## Summary

Update integration projects, test projects and web app projects to include .Net 6.

As part of this issue we will add and test support for Net 6 in the dotnet azure SDK.

- [ ] Add `net6.0` to the TargetFrameworks list to the following libraries:
Microsoft.Bot.Builder.Integration.AspNet.Core
Microsoft.Bot.Builder.Integration.ApplicationInsights.Core
Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime
- [ ] Add `net6.0` to the TargetFrameworks list of the unit test projects (unit tests should run on both versions)
- [ ] Update the web tests projects in the solution to target Net 6 (we don't need multi targetting for the testing projects we have in the Tests folder.
- [ ] Make required changes to the build pipelines if needed

### Reference articles

- [What's new in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-6)
- [Breaking changes in .NET 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0?toc=/dotnet/fundamentals/toc.json&bc=/dotnet/breadcrumb/toc.json)

**Comment by danmoseley** [comment]
Feel free to reach out to me (from .NET team) if you have any questions or issues we can help with.
