### ISSUE TITLE
Create action in dotnet repo for JS parity issues

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#5978]
## Summary

Whenever we merge something into v5, the action should create parity issues in JS with the proper labels (unless we tag the PR as `automation-no-partiy`.

We could probably reuse the workflow that @joshgummersall created that can be found here https://github.com/joshgummersall/dispatch-workflow

**Comment by joshgummersall** [comment]
There already is a workflow for this: https://github.com/microsoft/botbuilder-dotnet/blob/main/.github/workflows/create-botbuilder-js-parity-issue.yml
