### ISSUE TITLE
HTTPClient(s) in the Connector should be pooled

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#60]
The class EndorsementsRetriever.cs creates a new HttpClient for each request. This is wasteful of resources, and significantly increases latency. 

This should be pooled and/or static.

**Comment by RyanDawkins** [comment]
Looks like this can be closed.

**Comment by cleemullins** [comment]
Not quite yet. There is 1 left. :)

________________________________

**Comment by cleemullins** [comment]
The remaining one to fix is the ConnectorClient. It's called in [few places](https://github.com/Microsoft/botbuilder-dotnet/blob/8a47b92cad188eb400f118bab081e774038da233/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L65). 

@EricDahlvang is looking into this now. It's complex because it's down in auto-generated code and the patterns for fixing it are non-obvious.

**Comment by EricDahlvang** [comment]
In August, a constructor was introduced to **ServiceClient** that allowed consuming code to specify if **HttpClient** should be disposed https://github.com/Azure/azure-sdk-for-net/pull/3547/files .  A method was also added that ensures  **ProductInfoHeaderValue**s are not added to **UserAgent** twice.  However, this throws exceptions when a **ProductInfoHeaderValue** is provided that does not have a **Product** (i.e. constructed with comment only).  Also, the **ServiceClient** itself adds a **ProductInfoHeaderValue** every time.  These things make the HttpClient constructor on **ServiceClient** an invalid option for re-using a static HttpClient .  ( filed this issue: https://github.com/Azure/azure-sdk-for-net/issues/4086 and this PR https://github.com/Azure/azure-sdk-for-net/pull/4095 )

These things considered, the only viable option at this time is something like what @tomlm submitted here: https://github.com/Microsoft/BotBuilder/blob/d09bcc9c46e2a16d9d523f4209387fd0aaa68b29/CSharp/Library/Microsoft.Bot.Connector.Shared/ConnectorClientEx.cs

**Comment by cleemullins** [comment]
With Tom's most recent changes, #186, this is now done.
@EricDahlvang
