### ISSUE TITLE
customHttpClient for AppCredentials throws HttpClientDisposed Exception sometimes

### ISSUE THREAD

**Issue by anirudhj-msft** [microsoft/botbuilder-dotnet#6015]
We use the customHttpClient , for the AppCredentials to be created.
And this sometimes disposes the HttpClient and sends, as HttpClientDisposed... exception.
We do not have consistent scenarios on when this happens, but it does occur when a customHttpClient object is sent...
Can you verify if the customHttpClient object is being disposed explicitly ?

https://github.com/microsoft/botbuilder-dotnet/blob/a216a9b469b3ed18c8a6f6b5e47c627b70b0830b/libraries/Microsoft.Bot.Connector/Authentication/AppCredentials.cs#L43

**Comment by EricDahlvang** [comment]
Hi @anirudhj-msft 

Which version of the sdk is the bot using? 

Is this same httpclient used in other places, or only for this call? 

Are you able to provide a stack trace?

If a custom httpclient is provided to  AppCredentials, it is then used to construct a ConstantHttpClientFactory here:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs#L247 I'm not aware of this causing disposal issues.

Please provide a small repro if possible.

**Comment by gabog** [comment]
hi @anirudhj-msft, we are closing this issue, feel free to re-open if you are still experiencing problems.
