### ISSUE TITLE
Test explorer should not start Azure emulator when loading tests

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#6023]
## Summary

There is some code in the Azure tests that is causing the azure emulators to startup when opening test explorer in visual studio gets in the way when testing other things that are not related to azure.

This is probably caused by some static constructor that gets triggered when test explorer uses reflection to find tests in the target assemblies. 

As part of this issue we need to refactor the code so emulator is only started when the tests are executed and, if possible, make sure they only get started once per test run and not multiple times (right now the security window pops out at least twice).

While refactoring these test, we should analyze if we really need to run azure emulator for unit tests, it may make more sense to move the tests that depend on emulator to functional and integration tests.

**Comment by ceciliaavila** [comment]
Hi @gabog,
We analyzed how to move these tests to functional and integration and tests and found these possible options:

**Proposed options**
1- Move the tests to the [FunctionalTests project](https://github.com/microsoft/botbuilder-dotnet/tree/main/FunctionalTests/Microsoft.Bot.Builder.FunctionalTests) replacing the StorageEmulator (deprecated) with [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio). They will be run as part of the existing [FunctionalTests pipelines](https://github.com/microsoft/botbuilder-dotnet/blob/main/build/yaml/botbuilder-dotnet-functional-test-windows.yml).
	
2- Move the tests to the [FunctionalTests project](https://github.com/microsoft/botbuilder-dotnet/tree/main/FunctionalTests/Microsoft.Bot.Builder.FunctionalTests) with a different _TestCategory_ to run them in a separate pipeline that first creates the resources in Azure, removing the need for the emulators (_StorageEmulator_ and _CosmosDbEmulator_).
	
3- Move the tests to [BotFramework-FunctionalTests](https://github.com/microsoft/BotFramework-FunctionalTests) and include them in the pipelines, deploying the needed Storage resources with the rest of the shared resources.

In any case, we should probably add new unit tests mocking the resources to avoid losing coverage.

**Comment by gabog** [comment]
Hi @ceciliaavila, I am more inclined to do option #3 and also create unit tests with proper mocks in the SDK like you mention.

Let's chat about it tomorrow in our weekly call and take it from there.
