### ISSUE TITLE
Dialog changes

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#6027]
## Summary

TODO: Eric to write this down. This issue is about removing code that was added to the base classes in the Dialogs package to support adaptive (like event bubbling). 

Some candidates for removal are:
* Microsoft.Bot.Builder.Dialogs.Debugging folder and properties and methods in related classes.
* Microsoft.Bot.Builder.Dialogs.Memory folder and properties and methods in related classes.
* Microsoft.Bot.Builder.Dialogs.Obsolete folder and properties and methods in related classes.
* Microsoft.Bot.Builder.Dialogs.DialogManager.cs and related usages

Related items 
#5412

**Comment by EricDahlvang** [comment]
https://github.com/microsoft/botbuilder-dotnet/pull/6121 removes 

- Microsoft.Bot.Builder.Dialogs.Debugging folder and properties and methods in related classes.
- Microsoft.Bot.Builder.Dialogs.Memory folder and properties and methods in related classes.
- Microsoft.Bot.Builder.Dialogs.Obsolete folder and properties and methods in related classes.
- Microsoft.Bot.Builder.Dialogs.DialogManager.cs and related usages


We can address these in a separate PR:
- Microsoft.Bot.Builder.Dialogs.DialogEvent.cs and related classes. 
- ObjectPath can also be considered for removal, it is now used only by QnAMaker Recognizer.
