### ISSUE TITLE
Teams now supports an arbitrary number of card actions

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#6065]
## Version
n/a (main)

## Describe the bug
The code suggests that Teams only supports up to 3 buttons per rich card, which is no longer the case.

## To Reproduce
1. Look at [Dialogs/Choices/Channel.cs](https://github.com/microsoft/botbuilder-dotnet/blob/1539fd4f01a4041ab49bbbc1526e429a509a2485/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs#L62-L63)
1. See error. Teams should list whatever the max is, which I think is 100.

## Expected behavior
The values returned from these methods should reflect the current capabilities of each channel.

## Screenshots
n/a

## Additional context
re: Bot-docs [issue 2161](https://github.com/MicrosoftDocs/bot-docs/issues/2161).

I managed to get the following info from someone associated with Teams:
> effectively now there's no limit to the number of Card Actions supported. Each card is both Channels and Chats can support up to 6 primary actions. With the addition of Overflow menus, the 7th and subsequent primary actions will be hidden away in the overflow menu as well as any secondary actions.

**Comment by clearab** [comment]
Teams is also adding support for suggested actions in 1-1 chats, so we should add them to that case/switch at the same time. I don't think we have the right data available to check the conversation type in that switch statement?
