### ISSUE TITLE
Typos in SDK v4 vsix template

### ISSUE THREAD

**Issue by BruceHaley** [Microsoft/botbuilder-dotnet#608]
1. line 11 of default.htm was written for the old Emulator. To revise it for the new Emulator I would say something like:
 
    <p>To debug your bot using the Bot Framework Emulator, paste this URL into the **New Bot / Endpoint URL textbox**:</p>

2. there is a typo on line 11 of default.htm:
 
    <p>To debug **you** bot using the Bot Framework Emulator, paste this URL into the Emulator window:</p>
...should be:
    <p>To debug **your** bot using the Bot Framework Emulator, paste this URL into the Emulator window:</p>

3. spelling errors in Startup.cs of the SDK v4 vsix template, lines 39 and 41:
 
                // The CatchExceptionMiddleware provides a top-level exception handler for your bot. 
                // Any exceptions thrown by other Middleware, or by your OnTurn method, will be 
                // caught here. To **facillitate** debugging, the exception is sent out, via Trace, 
                // to the emulator. Trace activities are NOT displayed to users, so in addition
                // an "**Ooops**" message is sent.
 
Should be:
 
                // The CatchExceptionMiddleware provides a top-level exception handler for your bot. 
                // Any exceptions thrown by other Middleware, or by your OnTurn method, will be 
                // caught here. To **facilitate** debugging, the exception is sent out, via Trace, 
                // to the emulator. Trace activities are NOT displayed to users, so in addition
                // an "**Oops**" message is sent.

**Comment by cleemullins** [comment]
@FranciscoPonceGomez - can you take a look and fix? Thx!

**Comment by yochay** [comment]
@FranciscoPonceGomez  any updates?

**Comment by FranciscoPonceGomez** [comment]
WIP. I will upload an update today.

**Comment by FranciscoPonceGomez** [comment]
https://github.com/Microsoft/botbuilder-dotnet/pull/671
