### ISSUE TITLE
Teams is adding support for suggested actions in 1-1 chats

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#6086]
[Prompts](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/Prompt.cs#L309) and [IntputDialogs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs#L393) call `ChoiceFactory.ForChannel` by default if a `ListStyle` is not provided. 

`ForChannel` will construct a card using `SuggestedActions` if possible. This process should now also check if the conversation is Teams 1:1, in which case `SuggestedActions` ARE supported. (note: only Ring0 as of 1.3.2021)

https://github.com/microsoft/botbuilder-dotnet/issues/6065#issuecomment-1004334158

**Comment by gabog** [comment]
Flagging it as blocked since we don't have a client to test on yet

**Comment by gabog** [comment]
This is not possible in v4 without breaking changes, closing this issue.

**Comment by gabog** [comment]
Reopening for later consideration.

**Comment by ceciliaavila** [comment]
Hi @EricDahlvang, @gabog, do you know if this feature is still in validation, or is it worldwide implemented?
We couldn't get suggested actions to work on Teams.

**Comment by gykung** [comment]
Are SuggestedActions enabled on Teams? I have a bot built using SDK v4, the suggested actions work on Teams iOS, but not on Teams Desktop 1.6.00.4472 .

**Comment by gykung** [comment]
Verified that it works. Thanks!
