### ISSUE TITLE
Expression function getProperty can throw null ref exception

### ISSUE THREAD

**Issue by Rich-biomni** [microsoft/botbuilder-dotnet#6094]
## Version
4.14.1

## Describe the bug
using adaptive expression method getProperty when the 2nd argument is null then a null ref Exception is thrown.

## To Reproduce
using the following adaptive expression will throw

getProperty({prop1:123},null)

This can be seen using https://playgroundclient.azurewebsites.net/

## Expected behavior
Expected behaviour would be to return an error and not throw an exception.. The 2nd argument should be validated that it is not null or empty.

## Screenshots
![image](https://user-images.githubusercontent.com/39834624/148533798-fbb790d5-b097-4fbb-977f-e81eaa47043a.png)

**Comment by tdurnford** [comment]
@Rich-biomni Can you make sure `path` is not `null` before invoking the function.

**Comment by Rich-biomni** [comment]
@tdurnford The problem we have is the path is user entered data, and we would like to tell the user what is wrong.
So ideally we want the engine to return an error 'you cant call getProperty with a null path'. What we actually get is a NullReferenceException which tells the user nothing.

**Comment by carlosscastro** [comment]
Thanks, we'll triage this and fix according to the priority. @mrivera-ms could you drive the prioritization please? Thanks

**Comment by dmvtech** [comment]
Hi @Rich-biomni 

Your property that you should be asking to retrieve should be in quotes as a string.

So, for your example where you have:
`getProperty({pro1:23}, path)`

It should be:
`getProperty({"pro1":23}, 'path')`

The property name needs to be a string and therefore in quotes. Doing this, when you have a property that it cannot find (is null), will then result in an empty result and avoid an exception.
![image](https://user-images.githubusercontent.com/43397658/152866473-f696d130-d9cf-48ce-9779-b8a6ba734c9e.png)

You can then handle the empty result with any logic required for your bot.

**Comment by dmvtech** [comment]
> You can then handle the empty result with any logic required for your bot.

Maybe something like:
`coalesce(getProperty({"pro1":23}, 'path'),'PATH_IS_NULL')`

**Comment by Rich-biomni** [comment]
@dmvtech I get where your going unfortunately path is not always a constant string.  In our application the end user can define the expression, therefore the path can be a variable e.g dialog.XXXX

Currently when the path is null a NullReferenceException is thrown (never a good thing) which tells the user nothing and is really difficult to support. Ideally we want the engine to return an error 'you cant call getProperty with a null path'.

**Comment by johnataylor** [comment]
The design is to return the error as an exception. The code snippet illustrates one of the ways you can check for and avoid the exception in your expressions.

**Comment by Rich-biomni** [comment]
@johnataylor I disagree first of all the method contract for ExpressionEvaluator  is

private static (object value, string error) Evaluator(Expression expression, IMemory state, Options options)

it returns errors, therefore it should return error, only throw in exceptional instances. 
It is completely possible the input argument could be null and the code is missing a validation check for that case.

Perhaps you could answer this.

https://playgroundclient.azurewebsites.net/

Calling 

getProperty(null, null) 

No error, returns null

getProperty({}, null) 

Null Ref

 Why is the 2nd doing something different?
