### ISSUE TITLE
UI Issue when search extension is invoked in compose area

### ISSUE THREAD

**Issue by piyumi25** [microsoft/botbuilder-dotnet#6095]
I have developed a search extension. When it is invoked using "@search-extension-name" in compose area, following issue is occurred?
![image](https://user-images.githubusercontent.com/33615108/148541515-3b316045-59e4-496b-9a3b-a6253d899e57.png)

And when click on "Enter" the result card is selected and insert it in to the message.

But if I invoked it using the icon in compose message area, then it loads the results as expected.
![image](https://user-images.githubusercontent.com/33615108/148541197-71cb39d9-c7c7-4fa5-8bc9-858deb4f60f4.png)

Seems like it is common issue for other apps also. Can some one confirm it?

**Comment by anishprasad01** [comment]
Hi @piyumi25,

As I understand it, you're trying to run something like this [search extension sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search) and you're expecting it to work without having to manually invoke the extension by clicking on it. Is that correct?

**Comment by piyumi25** [comment]
> Hi @piyumi25,
> 
> As I understand it, you're trying to run something like this [search extension sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/50.teams-messaging-extensions-search) and you're expecting it to work without having to manually invoke the extension by clicking on it. Is that correct?

@anishprasad01 I am not saying like that. I can invoke it manually, but when it is invoking by mentioning it in compose area like @searchextencion and search some thing, it has this UI issue.

**Comment by anishprasad01** [comment]
@piyumi25

As far as I am aware, the search extension can only be invoked by using the button in the bottom row below the compose box, or by using the command box at the top of the screen. You cannot `@mention` the extension from within the compose panel itself.

**Comment by anishprasad01** [comment]
As this is expected behavior, I am going to go ahead and close this issue. If you need further help with this, feel free to comment and we can reopen the issue.
