### ISSUE TITLE
Error when trying to use LanguageServices with Microsoft.Bot.Builder.AI.QnA 4.15.0

### ISSUE THREAD

**Issue by effirmaevei** [microsoft/botbuilder-dotnet#6098]
## Version
netcoreapp3.1 + Microsoft.Bot.Builder.AI.QnA 4.15.0

## Describe the bug
Version 4.15 (latest) of Microsoft.Bot.Builder.AI.QnA breaks when trying to connect to a LanguageServices published KB. 
This does not happen if using the project library included when creating the bot from Azure or when using Azure.AI.Language.QuestionAnswering.QuestionAnsweringClient.

## To Reproduce

```
using Microsoft.Bot.Builder.AI.QnA;
using Microsoft.Extensions.Configuration;

var qnaServiceType = configuration["QnAServiceType"];
QnAMaker myQnA = new QnAMaker(new QnAMakerEndpoint
{
    KnowledgeBaseId = configuration["QnAKnowledgebaseId"],
    EndpointKey = configuration["QnAEndpointKey"],
    Host = configuration["QnAEndpointHostName"],
    QnAServiceType = qnaServiceType
});
```

![image](https://user-images.githubusercontent.com/20551019/148686115-4f4470a2-dece-4418-97a5-2a352169eeaf.png)

## Expected behavior
The project should provide up to date Microsoft.Bot.Builder.AI.QnA version that is compatible with the Language Service Questions Answering that you are promoting in Azure.

## Additional context
This piece of code was taken from the code auto-generated after creating a bot for language services. This appears to rely on a modified version of Microsoft.Bot.Builder.AI.QnA that is not available in NuGet, but rather included as some embedded SDK.

![image](https://user-images.githubusercontent.com/20551019/148685713-0e49ddd9-2822-4626-b31b-f136204825fd.png)

**Comment by tdurnford** [comment]
@mrivera-ms Can you weigh in on this issue?

**Comment by carlosscastro** [comment]
@mrivera-ms could you route this issue please? Thanks!

**Comment by jmferreirab** [comment]
Following up on this as I am still interested in seeing a response to the issue. Let me know if you need any further details.

**Comment by ramfattah** [comment]
Hello @effirmaevei, I'm looking into this issue.

**Comment by anishprasad01** [comment]
@effirmaevei,

When you say "LanguageServices", are you referring to [QnA Maker](https://www.qnamaker.ai/), or [Cognitive Service for Language](https://azure.microsoft.com/en-us/services/cognitive-services/language-service/)? The former should work, but the latter may not.

**Comment by effirmaevei** [comment]
This issue is in reference to the updated version of QnA Maker, "Question answering" that all doc articles tell users to start implementing. The parent service would be **Azure Cognitive Service for Language**, right?. See message below:

![image](https://user-images.githubusercontent.com/20551019/152888200-75e1f351-ffc5-4a6a-934f-9a453ea4338f.png)

https://azure.microsoft.com/en-us/services/cognitive-services/question-answering/#overview


It is my understanding that as long as the master branch of the dotnet SDK keeps missing the "QnaServiceType" parameter near the linked line below, the issue will remain.

https://github.com/microsoft/botbuilder-dotnet/blob/0fbba32648060b62f0d9bbd216d4d26778330d88/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerEndpoint.cs#L31

**Comment by ramfattah** [comment]
Hi @effirmaevei 

Correct, Azure Cognitive Service is the newer version. 

I was able to access "QnAServiceType" property by doing the following steps:
1) Complete this documentation [Quickstart: question answering](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/quickstart/sdk?pivots=studio) - (Select Language Studio)
2) After creating the "[question answering project](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/quickstart/sdk?pivots=studio#:~:text=created%20the%20resource.-,Create%20your%20first%20question%20answering%20project,-Sign%20in%20to)" and "[Deploy your project](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/quickstart/sdk?pivots=studio#:~:text=answer%20response%20pair.-,Deploy%20your%20project,-Select%20the%20Deploy)" in Language Studio, next step is to create the bot. Follow this doc here [Create a FAQ bot](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/tutorials/bot-service)
3) Open the newly created bot in Azure Portal and click "Download bot source code"
<img src="https://i.ibb.co/R30JNZg/Screenshot-1.png" width="800" />
4) Unzip and open the solution, there should be a "Microsoft.Bot.Builder.AI.QnA" project reference to it. 

![](https://i.ibb.co/vmhLFrr/Screenshot-2.png)


![](https://i.ibb.co/rZ2mRXg/Screenshot-3.png)


Try these steps and let me know if this worked for you.

**Comment by effirmaevei** [comment]
Yes indeed. Compatible code can be found if you follow those outlined steps. I think I mentioned that it works by using that included project reference for the QnA.AI library.

The matter here is that it does not work with the QnA.AI library published here in master. So.....

When are we getting that custom built QnA.AI library that comes fron the steps you described added to the main branch here in githu? It seems somewhat hidden deep inside Azure right now.

This is a concern for users because we cannot keep downloading the repo and recreating the bot in Azure to get the latest source code for the QnA.AI library that works for Custom Question Answering. It concerns me that the code in Azure is provisional since it has not been officially added to NuGet meaning anything I develop on top of that has a high risk of becoming obsolete real quick.

**Comment by ramfattah** [comment]
Hi @effirmaevei, looks like this is currently being worked on - [pull-request](https://github.com/microsoft/botbuilder-dotnet/pull/6179) #6179.

**Comment by ramfattah** [comment]
I am closing this one for now, feel free to re-open if you are still having issues.
