### ISSUE TITLE
OAuthPrompt: Auto sign out users if the token is expired

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#6101]
## Summary

@EricDahlvang, can you please add a summary describing this issue?

**Comment by EricDahlvang** [comment]
This has been a frustration for customers for some time: 
https://github.com/microsoft/botbuilder-dotnet/issues/1614
https://github.com/microsoft/botbuilder-dotnet/issues/764

I looked into this more today, and unfortunately the Bot Framework OAuth service does not send back the token expiration date. 

We could update our oauth samples, demonstrating how to logout the user and re-send the OAuth Card if using the token results in an error.

**Comment by gabog** [comment]
We will not address this at the moment.
