### ISSUE TITLE
Update TestAdapter to derive from CloudAdapter

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-dotnet#6107]
## Summary

- TestAdapter should derive from CloudAdapterBase
- #6075 removes `IExtendedUserTokenProvider` and `IUserTokenProvider`. As part of this PR we should mark the methods from those interfaces that were left in TestAdapter as `obsolete` to encourage users to use the new CloudAdapter and security classes.

**Comment by EricDahlvang** [comment]
note: this pr is removing IExtendedUserTokenProvider https://github.com/microsoft/botbuilder-dotnet/pull/6075

**Comment by gabog** [comment]
Thanks @EricDahlvang,  that's great, I think we should still refactor TestAdapter to derive from CloudAdapter and mark the methods that were brought in by implementing IExtendedUserTokenProvider as Obsolote to drive developers to use the CloudAdapter and new security classes, makes sense?

**Comment by gabog** [comment]
We will not address this at the moment.
