### ISSUE TITLE
Azure Bot Service V.Next

### ISSUE THREAD

**Issue by vovanb** [Microsoft/botbuilder-dotnet#611]
Will be added any GUI tool for manage conversation flow aka Azure Bot Service V.Next declared at Microsoft Build 2017 https://blog.botframework.com/2017/05/10/build/?
Will be added new channels?

**Comment by yochay** [comment]
@vovanb please file new channel request at https://feedback.azure.com/forums/562027-azure-bot-service

No current plans for a GUI tool.
