### ISSUE TITLE
Parent ComponentDialog is not resumed at the end of a child ComponentDialog

### ISSUE THREAD

**Issue by ahmadbk** [microsoft/botbuilder-dotnet#6115]
## Version
4.9.4

## Describe the bug
A (child) ComponentDialog is created by (parent) ComponentDialog. Upon ending the child ComponentDialog using the outerDc, the parent ComponentDialog is NOT resumed.

## To Reproduce
1. Create ComponentDialog A and ComponentDialog B. 
2. Start ComponentDialog A at first MessageActivity.
3. Add ComponentDialog B into ComponentDialog A's DialogSet in the BeginDialog method.
4. Send a second message which will trigger the ContinueDialog method within ComponentDialog A 
5. In the ContinueDialog method, begin ComponentDialog B using DialogContext.BeginDialog(ComponentDialog B id) method 
6. In the BeginDialog method of ComponentDialog B, End ComponentDialog B by using EndComponent(outerDc) method.
7. EndDialog method in ComponentDialog B is triggered 
8. ResumeDialog method in ComponentDialog A is NOT triggered

## Expected behavior
When a child ComponentDialog is ended, the ResumeDialog method in the parent ComponentDialog should be triggered.

## Additional context
https://github.com/microsoft/botbuilder-dotnet/blob/3428a81e3a1481615cf63a30c4c55880a908ca34/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L339-L375
EndComponent(outerDc) method eventually calls the DialogContext.EndDialogAsync() method. This method in DialogContext is the important code to consider. This method does two important things: 

1. It ends the ActiveDialog on the outerDc by removing the (child) dialog off the stack. 
2. Resume the parent dialog 

Code snippet in the EndDialogAsync method:
https://github.com/microsoft/botbuilder-dotnet/blob/3428a81e3a1481615cf63a30c4c55880a908ca34/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L348-L353

Problem occurs when retrieving the ParentDialog. It does so by using ActiveDialog property again which simply retrieves the first item on the stack. 

Code snippet of ActiveDialog property in DialogContext:
https://github.com/microsoft/botbuilder-dotnet/blob/3428a81e3a1481615cf63a30c4c55880a908ca34/libraries/Microsoft.Bot.Builder.Dialogs/DialogContext.cs#L128-L139

(Note: when working with ComponentDialogs, we do NOT expect the parent dialog to be part of it's own inner dialog stack. Only dialogs from it's own DialogSet can be within the stack)

When ending the last dialog within it's own inner dialog stack and the inner dialog stack becomes empty which means the component ends. The result of calling the ActiveDialog property now is null as there are no more items in it's inner Dialog stack. 

I believe, if the stack is null, the EndDialogAsync method should check the ParentDialog property  and if not null, resume that parent dialog to go back to the parent ComponentDialog.

**Comment by stevkan** [comment]
@ahmadbk, do you have example code that reproduces the issue that you could zip and attach for me to test with? If so, please be sure to remove any secrets/keys beforehand.

**Comment by stevkan** [comment]
Closing do to inactivity. If the issue persists, please feel free to re-open.

**Comment by ahmadbk** [comment]
Hi, please follow the following git hub repo link to access the code that reproduces the error:
https://github.com/ahmadbk/NestedDialogsBot
