### ISSUE TITLE
Trigger converstaionUpdate for all users

### ISSUE THREAD

**Issue by vitaliishandra** [microsoft/botbuilder-dotnet#6117]
We have a bot that perform proactive notifications to millions of users. Our customers add the bot application globally via Teams admin center via global policy. 
Unfortunately there are some issues with intalling the app globally via global policy:
- A lot of users didn't receive the app in MS Teams. However GraphAPI indicates it is successfully added.
- Some users received app but looks like converstaionUpdate with memberAdded  was not triggered.
As a result the bot didn't stored the converstaion reference and can't send proactive notifications to the users.

Here is what we tried:
- GraphAPI command 'Install Teams app': https://docs.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http. It works greate in case GraphAPI indicates the app is not yet installed. In most cases it indicates it is already installed.
- GraphAPI command 'Upgrade Teams app' https://docs.microsoft.com/en-us/graph/api/userteamwork-teamsappinstallation-upgrade?view=graph-rest-1.0&tabs=http. It worked in some cases and event is triggered, but not very often.
- User can write a message to the bot and we store the conversation reference from turnContext. It is ok, but in case there are thousands of missed users Organizations don't want each of their users to do that.

Are there any way to re-triger conversationUpdate.membersAdded event to store the converstaion reference for multiple users on organization level (via GraphAPI or something like that)?

**Comment by clearab** [comment]
This question will be best answered by the Teams group directly. Given the specificity, @vitaliishandra would you mind reposting your question here: https://docs.microsoft.com/en-us/answers/topics/office-teams-app-dev.html?

**Comment by carlosscastro** [comment]
Closing since @clearab suggested a better place to ask this question.
