### ISSUE TITLE
DCR: add onDialogBegin() and onDialogContinue() methods to DialogContainer 

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#612]
The `DialogContainer` class doesn't currently provide a way for a derived class to listen in on the activities as they're routed to its underlying dialogs. That means that if you create a component based off DialogContainer you can't perform any sort of interruption because you can't properly intercept the incoming activity. 

I propose that we make a small change to the DialogContainer class that adds `onDialogBegin()` and `onDialogContinue()` methods specifically designed to let components intercept incoming activities and perform interruption as needed.

I have a prototype of this in my toybox repo and it's a pretty simple change:

```JavaScript
    public dialogBegin(dc: DialogContext<C>, dialogArgs?: any): Promise<any> {
        // Start the dialogs entry point dialog.
        let result: any; 
        const cdc = new DialogContext(this.dialogs, dc.context, dc.activeDialog.state, (r) => { result = r });
        return this.onDialogBegin(cdc, this.initialDialogId, dialogArgs).then(() => {
            // End if the dialogs dialog ends.
            if (!cdc.activeDialog) {
                return dc.end(result);
            }
        });
    }

    public dialogContinue(dc: DialogContext<C>): Promise<any> {
        // Continue dialogs dialog stack.
        let result: any; 
        const cdc = new DialogContext(this.dialogs, dc.context, dc.activeDialog.state, (r) => { result = r });
        return this.onDialogContinue(cdc).then(() => {
            // End if the dialogs dialog ends.
            if (!cdc.activeDialog) {
                return dc.end(result);
            }
        });
    }

    protected onDialogBegin(dc: DialogContext<C>, dialogId: string, dialogArgs?: any): Promise<any> {
        return dc.begin(dialogId, dialogArgs);
    }

    protected onDialogContinue(dc: DialogContext<C>): Promise<any> {
        return dc.continue();
    }
```

A derived class would typically just override `onDialogContinue()` to run interruption logic anytime the component is active.  They can also override `onDialogBegin()` to dynamically decide which entry point dialog should be started.

**Comment by johnataylor** [comment]
This seems like a pretty simple and useful and consistent change.

**Comment by johnataylor** [comment]
We have these methods on ComponentDialog now.
