### ISSUE TITLE
Twilio Adapter not thread safe

### ISSUE THREAD

**Issue by podgito** [microsoft/botbuilder-dotnet#6120]
## Version
v4.13.2.0

## Describe the bug
TwilioAdapter is not thread safe. I'm trying to build a multi-tenant bot application with Twilio being used as a channel for SMS and WhatsApp. Each tenant has their own Twilio credentials to be used in the app. I want to instantiate a different TwilioAdapter depending on the incoming webhook from Twilio. I've done this with my own TwilioAdapterFactory but underpinning all this is **TwilioClient.Init()** a static function storing the Twilio credentials in static fields.

## To Reproduce
Create two instances of TwilioClientWrapper with different account settings and try send a message from the first instance.

## Expected behavior
TwilioClientWrapper should not depend on a static properties underneath. The class gives an illusion of being able to setup multiple Twilio adapters but this is not possible. Can an instance of **TwilioRestClient** be used instead?

## Additional context
To be clear I've created a factory class to create the adapter with the correct credentials. This is not part of the issue. Also of note, BotFramework or Azure Bot Services in general does not support multi-tenant bots.

**Comment by tdurnford** [comment]
@mrivera-ms Can you please assign this issue to the appropriate person?

**Comment by carlosscastro** [comment]
@mrivera-ms could you please route this to a dev who can investigate?

**Comment by padraiccloda** [comment]
@mrivera-ms @carlosscastro @tdurnford I'll have a look at this myself if needs be. But can anyone suggest some valid for this to submit with a PR and it be accepted?

**Comment by mrivera-ms** [comment]
Thank you for opening this issue, @podgito. Please note that the Bot Framework Custom Adapters are being moved to the Community repository located here: [BotBuilderCommunity: dotnet](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/pull/461). The PR is currently under review. 

This and all future issues should be opened there. 

cc @padraiccloda
