### ISSUE TITLE
Update Microsoft.Logging.Extensions dependency in bot builder package to 3.1.3

### ISSUE THREAD

**Issue by Nehaongithub** [microsoft/botbuilder-dotnet#6156]
We’re attempting to consume the package in the Substrate Search repo since we’re integrating with Message Extensions, but we’re hitting version conflicts because our repo has moved to microsoft.logging.extensions 3.1.3 and the package depends on 2.1.0. Any chance we could update the dependency in the Microsoft.Bot.Builder package to resolve the conflict?

**Comment by gabog** [comment]
Hi @Nehaongithub, if your asp.net core app is targeting dotnet 3.1, you should get microsoft.logging.extensions 3.1 automatically, if not, you can try adding an explicit reference to 3.1.3 to your project and I think that should override the request for 2.1, let us know if that's not the case.

Gabo

**Comment by tracyboehrer** [comment]
Fixed by https://github.com/microsoft/botbuilder-dotnet/pull/6341
