### ISSUE TITLE
Webex Adapter do not work with Adaptive Cards - 400 Bad Request

### ISSUE THREAD

**Issue by mocalv** [microsoft/botbuilder-dotnet#6167]
## Version
SDK 4.12.0

## Describe the bug
Using the Webex Adapter for sending messages with a adaptive card causes a 400 Bad Request response by the Webex API.

## To Reproduce
1. Open Bot Composer
2. Create new empty bot
3. Create "Send a response" Action for "unknown intent" Trigger
4. Add text and a adaptive card attachment to the action
4. Install Webex adapter under "package manager"
5. Configure Webex adapter
6. Test with ngrok to see the response by webex

## Expected behavior
Correct body send to Webex API. 

## Additional context
Tested Webex API with Postman and Adaptive Cards which works fine.

**Comment by stevkan** [comment]
@mocalv, I just want to clarify that this is a Composer bot and not a "code-first" SDK bot, yes? You list the SDK version which is why I ask. If this is, in fact, a Composer bot, could you supply the version of Composer that you are using?

**Comment by mocalv** [comment]
Correct, I am talking about a Composer bot. Version 2.1.1

**Comment by mocalv** [comment]
I analysed the traffic with mitmproxy.

My test bot:
![Bot_Framework_Composer_k1quxvJp7S](https://user-images.githubusercontent.com/30929452/152645030-133bec1e-80f3-4d2b-bb51-0131622b6a83.png)

POST adaptive card to Webex API:
![MrAMLUKvL1](https://user-images.githubusercontent.com/30929452/152645065-ea7c64de-33d4-4882-9768-52de95d1fde2.png)
![rn91eHq1f0](https://user-images.githubusercontent.com/30929452/152645070-5084cf60-7cfc-4bb9-b956-b29ff770b77e.png)

As one can see, Webex sends a 400 bad request back.

With Postman and the [Webex documentation](https://developer.webex.com/docs/api/v1/messages/create-a-message), I was able to find the syntax error. 

Not working original body:
```json
{
   "attachments":[
      {
        "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
        "body":[
            {
                "isSubtle": false,
                "text": "default text",
                "type": "TextBlock",
                "weight": "bolder"
            }
        ],
        "type":"AdaptiveCard",
        "version":"1.0"
      }
   ],
   "markdown": null,
   "roomId": "[...]",
   "text":"6",
   "toPersonEmail": null,
   "toPersonId": null
}
```

Working body:
```json
{
   "attachments":[
      {
         "contentType":"application/vnd.microsoft.card.adaptive",
         "content":{
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "body":[
               {
                  "isSubtle":false,
                  "text":"default text",
                  "type":"TextBlock",
                  "weight":"bolder"
               }
            ],
            "type":"AdaptiveCard",
            "version":"1.0"
         }
      }
   ],
   "markdown": null,
   "roomId": "[...]",
   "text":"6",
   "toPersonEmail": null,
   "toPersonId": null
}
```

So `contentType` and `content` are missing.

According to Azure live metrics, the [GeneratorResult](https://github.com/microsoft/botbuilder-dotnet/blob/2234b5035c88fc9d31783730f049b72d8b1bc118/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendActivity.cs#L101) do at least log the correct syntax. 
![2dZGTR90yO](https://user-images.githubusercontent.com/30929452/152645510-bb8a09a0-cdf3-49c9-b74f-f91c26aa5dc0.png)

**Comment by mocalv** [comment]
So the problem seems to be that the method [`CreateMessageWithAttachmentsAsync` only adds `attach.Content`](https://github.com/microsoft/botbuilder-dotnet/blob/6c1c23b90c3e3b983bd5472255a6844707eefdb7/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs#L129). 
If I look at the method [`CreateAdaptiveCardAttachment`](https://github.com/microsoft/BotBuilder-Samples/blob/901bc140f5aa300fbfa852e64afd7c65fceebff9/samples/csharp_dotnetcore/62.webex-adapter/Bots/EchoBot.cs#L74) within [a bot example](https://github.com/microsoft/BotBuilder-Samples), only the whole attachment object contains the `contentType` and `content` (which contains the adaptive card).

CreateMessageWithAttachmentsAsync
```c#
public virtual async Task<string> CreateMessageWithAttachmentsAsync(string recipient, string text, IList<Attachment> attachments, MessageTextType messageType = MessageTextType.Text, MessageTarget target = MessageTarget.PersonId, CancellationToken cancellationToken = default)
        {
            Message result;

            var attachmentsContent = new List<object>();

            foreach (var attach in attachments)
            {
                attachmentsContent.Add(attach.Content);
            }

            var request = new WebexMessageRequest
            {
                RoomId = target == MessageTarget.SpaceId ? recipient : null,
                ToPersonId = target == MessageTarget.SpaceId ? null : recipient,
                Text = text ?? string.Empty,
                Attachments = attachmentsContent.Count > 0 ? attachmentsContent : null,
            };
```

CreateAdaptiveCardAttachment
```c#
private static Attachment CreateAdaptiveCardAttachment(string filePath)
        {
            var adaptiveCardJson = File.ReadAllText(filePath);
            var adaptiveCardAttachment = new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCardJson),
            };
            return adaptiveCardAttachment;
        }
```

**Comment by mocalv** [comment]
A workaround is to install the package [Microsoft.Bot.Components.AdaptiveCards](https://github.com/microsoft/botframework-components/tree/main/packages/AdaptiveCards), which works with adaptive card templates that contain `contentType` and `content`.

Simply adding `contentType` and `content` to the standard action "send a response" (with an adaptive card as an attachment) do not work.

**Comment by mrivera-ms** [comment]
Thank you for submitting this issue @mocalv. Closing as resolved by the customer.

**Comment by mocalv** [comment]
@mrivera-ms my provided "solution" is really only a workaroud, since a douple structure is painful to maintain. So please consider reopen it. Maybe it is a Composer issue only, but somewhere this problem should be solved.
