### ISSUE TITLE
TurnContext is disposed when using TwilioAdapter on Proactive Message

### ISSUE THREAD

**Issue by miguelhughes** [microsoft/botbuilder-dotnet#6202]
## Version
4.14.1

## Describe the bug
Using TwilioAdapter, I'm unable to start a dialog in a proactive message, and save changes to the turn context. After the activity goes out, TurnContext is disposed and I can't persist the updates to the conversation.

## To Reproduce
1. Clone this repo: https://github.com/miguelhughes/ProactiveTwilioDialog
2. Initialize appsettings with credentials for twilio and a valid bot registration
3. Navigate to http://localhost:3978/api/notify
4. Object disposed exception is thrown

## Expected behavior
I would like TwilioAdapter to behave as the standard adapter and not dispose the context after sending an activity, or at least give me a way to save changes to the conversation state after a message is sent. 
Alternatively, if I must use the standard adapter on the proactive message, I need to be able to specify the sms status callback url on that message.

## Additional context
The repo is a trimmed down of my working code, showing the problem. I cobbled it together from different bot framework samples: MultiTurnPromptBot, TwilioAdapterBot and ProactiveBot.
I'm trying to get status callbacks from Twilio. I have extended TwilioAdapter and TwilioClientWrapper to include my StatusCallback url on all messages. When using the standard adapter on conversation start and twilio adapter on replies, status callbacks work fine. But I can't use the modified Twilio adapter on the first message, due to this disposing behavior.
More background of why I'm trying to do this: https://stackoverflow.com/questions/71034954/unable-to-get-twilio-sms-status-callbacks-when-sending-proactive-message

**Comment by ramfattah** [comment]
Hey @miguelhughes, I'm investigating this.

**Comment by miguelhughes** [comment]
Thanks @ramfattah . Is there anything I can do to help?

**Comment by ramfattah** [comment]
Hi @miguelhughes,

Thank you for your patience. This is my first time working with Twilio. I followed this documentation [Connect a bot to Twilio](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0) to get familiar. 

I created a free trial account on Twilio to get a phone number along with account credentials. I cloned your repo and in step 3 when navigating to `http://localhost:3978/api/notify` I get the following error `ArgumentException: HttpRequest is missing "x-twilio-signature"`

The same issue `ArgumentException: HttpRequest is missing "x-twilio-signature"` occurs in [/63.twilio-adapter/](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/63.twilio-adapter) sample and not just your repo.

<img src="https://i.gyazo.com/88db92fb4db1cf9c32d85efda187b430.png" width="600"/>


My appsettings.json
<img src="https://i.gyazo.com/d5fd851fc1a54554be220981cf3c1c12.png" width="600"/>


Not sure if I'm missing a pre-requisite step. Have you faced this problem in development before?

**Comment by eallegretta** [comment]
I'm experiencing similar issues where ITurnContext gets disposed when I launch a new thread, I was not having this issue on the -pre versions I'm currently using 4.15.2

**Comment by ramfattah** [comment]
@miguelhughes @eallegretta 

Adapters previously integrated with the SDK, like Twilio, have been transferred to the [BotBuilder-Community-dotnet](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet) repo for continued support and ownership. 

Closing this issue, you will want to file this as a new issue in that repo for additional support. Thanks.

**Comment by miguelhughes** [comment]
I found a workaround for this problem, in case anyone runs into this. I posted it on the [linked SO](https://stackoverflow.com/a/71413068/1574861) item
