### ISSUE TITLE
`dotnet new corebot -n TestBot` creates project at TestBot/CoreBot

### ISSUE THREAD

**Issue by Swimburger** [microsoft/botbuilder-dotnet#6216]
## Version
`Bot Framework Echo Bot (v4.15.0)`

## Describe the bug
When creating a new bot using `dotnet new corebot`, the `-n` argument should be used as the name of the project.
This works correctly for echobot, but not for corebot.

Instead of creating the project using the specified name, it creates a folder and then puts the project into a "CoreBot" subfolder.

## To Reproduce
1. Run `dotnet new corebot -n TestBot`

## Expected behavior
Bot project should be at `TestBot`, but is at `TestBot/CoreBot`

**Comment by Swimburger** [comment]
This also uses `CoreBot` as the root namespace which should also use the `-n` argument value

**Comment by ramfattah** [comment]
investigating this.

**Comment by Swimburger** [comment]
For anyone else running into this, here's a PowerShell script to put the project in the correct folder, rename the project, and update the namespaces:
```powershell
#!/usr/bin/env pwsh
$CorrectProjectName = "YourBotProjectName"
Push-Location "./$CorrectProjectName"
Move-Item ./CoreBot/* ./
Remove-Item ./CoreBot
Move-Item ./CoreBot.csproj "./$CorrectProjectName.csproj"
Get-ChildItem * -Recurse -File | ForEach-Object { (Get-Content $_) -replace 'CoreBot', $CorrectProjectName | Set-Content $_ }
Pop-Location
```

**Comment by johnataylor** [comment]
@ramfattah please check the readme.

https://github.com/microsoft/botbuilder-dotnet/tree/main/generators/dotnet-templates

**Comment by ramfattah** [comment]
Hey @Swimburger 

Thanks for raising this issue. I believe this is expected. The documentation needs a little clarification. 

When running `dotnet new corebot -n TestBot` only the parent folder receives the bot name. i.e. the folder output is `TestBot/CoreBot`

I opened an issue for this [Create a bot with the Bot Framework SDK doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=csharp%2Ccli) here: https://github.com/MicrosoftDocs/bot-docs/issues/2184

**Comment by Swimburger** [comment]
This is unintuitive to .NET developers as they already expect projects to be generated and use the name-argument to specify the folder and namespace.
It's also inconsistent with the other project templates which do use the name-argument correctly, and inconsistent with how the Visual Studio templates work.

I understand this is probably because of the extra argument to also generate a test project. If you'd like to keep this behavior, at least give us extra arguments to specify the project name/subfolder/namespace.
```
dotnet new corebot --name rootFolder --project-name TestBot
# rootFolder > TestBot > TestBot.csproj
```
or maybe reuse the `-o` argument to specify the folder name, and use `-n` to specify the project name:
```
dotnet new corebot -o rootFolder -n TestBot
# rootFolder > TestBot > TestBot.csproj
```
The latter is probably the most consistent with other .NET CLI project templates
