### ISSUE TITLE
Slack Adapter doesn't send item in reaction_added event 

### ISSUE THREAD

**Issue by Anshul21** [microsoft/botbuilder-dotnet#6220]
as per the documentation of slack, the reaction_added event should have information about item for which reaction is given but bot framework doesnt send it. the "item" object is empty

https://api.slack.com/apis/connections/events-api#receiving_events

**Comment by stevkan** [comment]
**Please note:** Any adapters that were previously supported by the BotFramework dotnet SDK, such as the Slack adapter, have been moved to the [botbuilder-community-dotnet](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet) repo. As such, these adapters are no longer supported by Microsoft. Any questions, bugs, or issues should be posted there according to their community posting guidelines.
