### ISSUE TITLE
Create new Schema and Connector libraries based on System.Text.Json

### ISSUE THREAD

**Issue by msomanathan** [microsoft/botbuilder-dotnet#6228]
Create 2 new libraries based on the existing `Microsoft.Bot.Schema` and `Microsoft.Bot.Connector` libraries. However, the new libraries need to make use of `System.Text.Json` instead of `Newtonsoft.Json` for serialization. For now, these new libraries will be released as `preview` for PVA to consume internally. They will GA as part of the 4.16 release.

Tentative names for the new libraries:
- Microsoft.Bot.Connector.Schema
- Microsoft.Bot.Connector.Client

**Comment by tracyboehrer** [comment]
Closing.  This is being tracked in ADO for PVA.
