### ISSUE TITLE
Add descriptions to ARM template parameters files

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#6229]
**Is your feature request related to a problem? Please describe.**

- It's difficult to understand the deployment process, even with documentation. (It's also hard to document.) Anything we can do to make it easier for users to understand (and for writers to document) would be great.
- Currently, the READMEs for the samples and bots generated from templates point to the deployment article in the docs, but that is written based on the ARM template files.

**Describe the solution you'd like**

Please add _descriptions_ to the ARM template parameters files, such as the [new-rg-parameters.json](https://github.com/microsoft/botbuilder-dotnet/blob/main/generators/dotnet-templates/Microsoft.BotFramework.CSharp.EchoBot/content/DeploymentTemplates/new-rg-parameters.json) file for the Echo bot template. See [Parameters in ARM templates](https://docs.microsoft.com/azure/azure-resource-manager/templates/parameters#description).

**Describe alternatives you've considered**

I suppose a README.md in the deployment templates folder would accomplish the same thing, but would be more work for everyone.

**Additional context**

We periodically get flurries of issues about the deployment article in the docs. As it stands, this translates to a lot of work for the support team, for the writer maintaining the article, and often a lot of back and forth with the dev team.

**Comment by JonathanFingold** [comment]
Is the parameters file even needed? I just noticed the parameters are duplicated in the ARM template itself, and the ARM template includes descriptions. If the parameters files are not used, can we please delete them?

**Comment by ceciliaavila** [comment]
Hi @JonathanFingold, adding descriptions in the parameters files is currently [not working](https://github.com/Azure/azure-cli/issues/12009). We tested it and it throws an error when trying to deploy the bot.
Instead, we added a README in each bot's _deploymentTemplates_ folder with the descriptions for the parameters.
