### ISSUE TITLE
Recogniser doesn't work in other dialogues except "Greeting".

### ISSUE THREAD

**Issue by Agodak** [microsoft/botbuilder-dotnet#6231]
## Version
What package version of the SDK are you using.
4.15.2

## Describe the bug
Give a clear and concise description of what the bug is.
Recogniser is not called for user input in other dialogues than the initial one.

## To Reproduce
Steps to reproduce the behaviour:
1. Clone this repository: https://github.com/Agodak/BFTest.git
2. Set up Language Understanding
3. Start the bot
4. When prompted for name say "Joe"
5. Bot asks for name again 

## Expected behaviour
After entering "Joe", Bot should say "Welcome Joe"

## Additional context
This happens for RegexRecogniser as well, not just the Luis one.
If you move the prompt for text from "Introduction" to "Greeting", then the bot behaves as expected.
The bot also behaves as expected if using SDK 4.15.0 or older.

**Comment by EricDahlvang** [comment]
Hi @Agodak 

Thank you for raising this issue and providing a repro. I'm looking into this and will get back to you soon.

**Comment by EricDahlvang** [comment]
This fix for this has been merged, and will be released with 4.16.0
