### ISSUE TITLE
BotFrameworkAdapter.ContinueConversation() requires an app ID

### ISSUE THREAD

**Issue by navzam** [microsoft/botbuilder-dotnet#624]
`ContinueConversation` requires you to pass the bot's ID (from [here](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Core/BotAdapter.cs#L170)):

```
public virtual Task ContinueConversation(string botId, ConversationReference reference, Func<ITurnContext, Task> callback)
```

But what should you pass when running a bot locally and using the emulator without an app ID? In `BotFrameworkAdapter`, `ContinueConversation` throws an exception if you pass null or an empty string (from [here](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L100-L101)):

```
if (string.IsNullOrWhiteSpace(botAppId))
    throw new ArgumentNullException(nameof(botAppId));
```
 It seems to work if I pass some non-empty string, but the expectation/behavior is unclear.

**Comment by gabog** [comment]
Closing as part of R10 triage.
