### ISSUE TITLE
Using SendHandoffActivity throws exception when context is null

### ISSUE THREAD

**Issue by jamesemann** [microsoft/botbuilder-dotnet#6240]
## Describe the bug

Using SendHandoffActivity throws exception when context is null

## To Reproduce
Add a `Microsoft.SendHandoffActivity` to your conversation and do not provide any values for the `context` , e.g:

```
        {
          "$kind": "Microsoft.SendHandoffActivity",
          "$designer": {
            "id": "KNC2N1"
          }
        }
```

This line throws an exception because the `value` is null

https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder/EventFactory.cs#L83

## Expected behavior

It would raise the event but with empty context.

I think it may be a case of doing a little null coalesce here:

https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/SendHandoffActivity.cs#L61-L62

So it looks like:

```
            var handoffContext = HandoffContext?.GetValue(dc.State) ?? new {};
            var transcript = Transcript?.GetValue(dc.State) ?? new Transcript();
```

Thank you!

**Comment by anishprasad01** [comment]
Hi @jamesemann,

The [handoff docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0) specify using the `EventFactory.CreateHandoffInitiation` function instead, which explicitly performs a null check and throws an exception. Thus, throwing an exception on a null context is in fact intended behavior, and disallowing empty contexts doesn't appear to be a bug.

Could you go into more detail on what you're hoping to achieve by creating a handoff with an empty context? I'm not quite sure when handing the agent a null context would be useful.

**Comment by jamesemann** [comment]
Hi @anishprasad01 . Are you referring to the validation linked below (`turnContext`)?   If so, this is not validating the `handoffContext`, which is a separate argument.

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/EventFactory.cs#L26-L29

**Comment by anishprasad01** [comment]
You're correct, my mistake. I was looking at the wrong object. I took another look at it does appear there is no check for a null handoff context. Let me check-in with the team on potential steps.

**Comment by anishprasad01** [comment]
Looks like I can confirm this is a bug. I will look into fixing this, and I will link the PR to this issue when it's ready.
