### ISSUE TITLE
OAuth Prompt not working with the Slack adapter 4.13.0

### ISSUE THREAD

**Issue by raghavsuriya** [microsoft/botbuilder-dotnet#6264]
## Version
4.13.0

## Describe the bug
I am trying to use Oauth Prompt in slack and for some reason it keeps failing and I get the following exception: 

fail: Microsoft.Bot.Builder.Adapters.Slack.SlackAdapter[0]
      Exception caught : OAuth prompt is not supported by the current adapter   at Microsoft.Bot.Builder.Dialogs.UserTokenAccess.GetUserTokenAsync(ITurnContext turnContext, OAuthPromptSettings settings, String magicCode, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.OAuthPrompt.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
         at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)

## To Reproduce
Follow the steps in the bot authentication sample . It seems to fail when working in slack.

**Comment by stevkan** [comment]
**Please note:** Any adapters that were previously supported by the BotFramework dotnet SDK, such as the Slack adapter, have been moved to the [botbuilder-community-dotnet](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet) repo. We apologize for the inconvenience, but these adapters are no longer supported by Microsoft. Any questions, bugs, or issues should be posted there according to the repo's community posting guidelines.
