### ISSUE TITLE
Bot Framework Custom Action and custom ArrayExpression property

### ISSUE THREAD

**Issue by SilvioHuckel** [microsoft/botbuilder-dotnet#6277]
### Libraries name and versions
- Microsoft.Bot.Builder 4.15.2
- Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime 4.15.2

### Environment
- .NET Core 3.1
- Windows 10 Enterprise

### The staging
I’m building a bot using **Microsoft’s Bot Framework Composer**. To extend the composer’s standard features, I also built some **Custom Actions**, including one that needs input in the form of an array of a specific type. 
Here is the schema:

    {
      "$schema": "https://schemas.botframework.com/schemas/component/v1.0/component.schema",
      "$role": "implements(Microsoft.IDialog)",
      "title": "AdvancePropertyTest",
      "description": "Test advanced properties in for custom actions.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "skillSelectors": {
          "$ref": "schema:#/definitions/arrayExpression",
          "title": "SkillSelector Items",
          "description": "SkillSelector Items.",
          "items": {
            "title": "SkillSelector Item",
            "description": "SkillSelector Item.",
            "type": "object",
            "properties": {
              "key": {
                "title": "Key",
                "description": "The skill key to query against.",
                "type": "string"
              },
              "operator": {
                "title": "Operator",
                "description": "Describes how the value of the label is compared to the value defined on the label selector.",
                "type": "string",
                "enum": [
                  "Equal",
                  "NotEqual",
                  "LessThan",
                  "LessThanEqual",
                  "GreaterThan",
                  "GreaterThanEqual"
                ],
                "default": "Equal"
              },
              "value": {
                "title": "Value",
                "description": "The value to compare against the actual label value with the given operator.",
                "type": "integer"
              }
            }
          }
        }
      }
    }

which, in the composer, results in:
[Composer action with custom properties][1]

  [1]: https://i.stack.imgur.com/8QWA1.png

So far, so good.
Now, in the dialog's code, in order to retrieve the input data, this is what I did:

    [Serializable]
    public class SkillSelector
    {
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }
    
        [JsonProperty(PropertyName = "operator")]
        public string Operator { get; set; }
    
        [JsonProperty(PropertyName = "value")]
        public int Value { get; set; }
    }
    
    
    public class AdvancedPropertyTest : Dialog
    {
        [JsonProperty("skillSelectors")]
        public ArrayExpression<SkillSelector> SkillSelectors { get; set; }
        //public ArrayExpression<Metadata> SkillSelectors { get; set; }
    
    
        public override async Task<DialogTurnResult> BeginDialogAsync(DialogContext dc, object options = null, CancellationToken cancellationToken = default)
        {
            var skillSelectors = SkillSelectors?.GetValue(dc.State);
            // some code
    
            return await dc.EndDialogAsync(cancellationToken: cancellationToken);
        }
    }

### The Issue
Unfortunately, this results in the following error message once I run it:

    AdvancedProperties.dialog error: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type ‘AdaptiveExpressions.Properties.ArrayExpression`1[SkillSelector]’ because the type requires a JSON object (e.g. {“name”:“value”}) to deserialize correctly.
    
    To fix this error either change the JSON to a JSON object (e.g. {“name”:“value”}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
    
    Path ‘skillSelectors’, line 49, position 37.

Interesting fact, using class **Microsoft.Bot.Builder.AI.QnA.MetaData** as the generic type in the **ArrayExpression** does the trick, but, of course, is not what I want.

Anyone an idea how to do this ?
Any assistance would be greatly appreciated
Cheers.

**Comment by stevkan** [comment]
@SilvioHuckel, I'd like to try repro'g this using your code, if possible. Are you able to share a copy of your Composer bot, or a slimmed down version of it that adequately demonstrates the issue?

**Comment by s1lv1o** [comment]
Hey @stevkan,
the following repo contains a slimmed down Composer project:
https://github.com/s1lv1o/bot-framework-customaction

**Comment by tdurnford** [comment]
@stevkan Any progress on this?

**Comment by stevkan** [comment]
@SilvioHuckel, thank you for your patience while I've been looking into this. I am able to repro the issue you are experiencing. I have been trying to identify if there is a possible workaround but, as of yet, I have been unable to do so. I am also trying to reach out to some of the devs who originally worked on this part of the code base. However, I'm having some difficultly with this. I'll post another update as soon as I know more.

**Comment by stevkan** [comment]
@SilvioHuckel, I'm glad you found a solution that worked!
