### ISSUE TITLE
Keep existing ClaimsIdentity when handling get request

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#6288]
## Version
Currently main branch

## Describe the bug
When in websocket, if we had already set `ClaimsIdentity` in adapter, it will be overwritten here
https://github.com/microsoft/botbuilder-dotnet/blob/57faec119171b6347ce60556f758fca5c8b536b3/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs#L320

## Expected behavior
Do not overwrite existing ClaimsIdentity. We could append new ones

**Comment by ramfattah** [comment]
BotFrameworkHttpAdapter is deprecated, and this is resolved in CloudAdapter.
