### ISSUE TITLE
Fixing issue of Improper Authentication for .Net Framework

### ISSUE THREAD

**Issue by sadviramana** [microsoft/botbuilder-dotnet#6289]
Due to the issue [https://github.com/advisories/GHSA-qxx8-292g-2w66](url) we had to upgrade the bot.connector lib above 4.9.4 which we are currently using. But this is causing the web roles to get stuck while deployment of CSES (Cloud Service).
 
Instead I wanted to try this fix which allows us to keep 4.9.4 version [https://github.com/microsoft/botbuilder-dotnet/blob/main/doc/SkillClaimsValidation.md](url). But the implementation of BotFrameworkHttpAdapter
For .Net Framework does not have a constructor which takes in AuthConfiguration setting as an argument.
The above fix seems to be for .Net Core.
 
Please help us resolve the same for .Net Framework

**Comment by anishprasad01** [comment]
Working with internal customer via another platform.

**Comment by anishprasad01** [comment]
@sadviramana,

Do you require further assistance from the bot side, or can this issue be closed?
