### ISSUE TITLE
Is CloudAdapter supported in DirectLine Extension?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#6290]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
`CloudAdapter` is the new adpater. However when I am reading the document, I found we are still using `BotFrameworkHttpAdapter` for DirectLine Extension here:

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0#troubleshooting

Could we use the new one?

**Describe the solution you'd like**
We should use the new one.

Related https://github.com/microsoft/botbuilder-dotnet/issues/6288

**Comment by tracyboehrer** [comment]
@xieofxie This is supported in 4.16.0, which is in the process of being released now.
