### ISSUE TITLE
predictionOptions.slot cannot bind to settings

### ISSUE THREAD

**Issue by kino-song** [microsoft/botbuilder-dotnet#6299]
i want to bind preditionOptions.slot to primary appsetting.config, as following:

```json
{
  "$kind": "Microsoft.LuisRecognizer",
  "id": "LUIS_IvrBot",
  "applicationId": "=settings.luis.IvrBot_en_us_lu.appId",
  "version": "=settings.luis.IvrBot_en_us_lu.version",
  "endpoint": "=settings.luis.endpoint",
  "endpointKey": "=settings.luis.endpointKey",
  "predictionOptions": {
    "includeAPIResults": true,
    "slot": "=settings.luis.slot"
  }
}
```

but it seems do not work. when i check source code, i found that slot is evaluated with dialogContext. (in LuisAdaptiveRecognizer.cs)

`options.Slot = this.Options.Slot?.GetValue(dialogContext);`

it seems it need to evaluate with dialogContext.State to make it work, as version did.

`options.Version = this.Version?.GetValue(dialogContext.State);`

**Comment by dmvtech** [comment]
Hi @kino-song 

Is this a Composer bot? If so, what version? If an SDK bot, what version of the SDK are you using? Is this based off of a [Sample](https://github.com/microsoft/BotBuilder-Samples)?

**Comment by kino-song** [comment]
I am using bot composer v2.1.2, bot sdk was 4.14.1 (generated by bot composer by default), 
then i tried to upgrade sdk to 4.15.2, still have the same issue.

> Hi @kino-song
> 
> Is this a Composer bot? If so, what version? If an SDK bot, what version of the SDK are you using? Is this based off of a [Sample](https://github.com/microsoft/BotBuilder-Samples)?

I am using bot composer v2.1.2, bot sdk was 4.14.1 (generated by bot composer by default), 
Then I tried to upgrade sdk to 4.15.2, still have the same issue.

**Comment by dmvtech** [comment]
Hi @kino-song Thank you. I was able to reproduce your findings and am currently investigating further.

**Comment by dmvtech** [comment]
Closing as PR has been submitted. If approved, it will be included in some future build. Thank you for your contribution.
