### ISSUE TITLE
Adding Bot Framework Composer Dialogs To SDK bots [Help Needed]

### ISSUE THREAD

**Issue by Rishy17** [microsoft/botbuilder-dotnet#6300]
Hi Team,

We have been using a mix of Composer and SDK dialogs in our project, with the recent updates to the packages, The Dialog Manager class was marked Obsolete. our implementation is based on this [Adding Bot Framework Composer dialogs to a Skill](https://microsoft.github.io/botframework-solutions/skills/handbook/experimental-add-composer/).

Are there any other ways to achieve similar functionality, we are looking at a way to dynamically add composer-generated '.dialog' files to SDK bot.

Regards,
R

**Comment by Rishy17** [comment]
@stevkan any update on this is appreciated

**Comment by stevkan** [comment]
@Rishy17, thank you for your patience. Unfortunately, the ability to integrate adaptive dialogs with SDK bots is no longer supported in the current version. As you can see, in the link you referenced, under the section "Add additional Nuget package references", the last officially supported version is 4.9.1 of the SDK.

If you want to continue to use a mix of adaptive dialogs and SDK dialogs, you will need to continue using the last supported version, 4.9.1. However, in doing so, you won't benefit from updates to the SDK.

If you wish to use current versions, then you will need to write custom code (ideally, based off of the previously supported classes) that will implement the functionality you need. But, as the custom code would be written in-house, it would also be supported from in-house, as well.
