### ISSUE TITLE
NamedPipe could not reconnect correctly when disconnected unexpectedly

### ISSUE THREAD

**Issue by woasishen** [microsoft/botbuilder-dotnet#6306]
## Version
4.14-4.16

## Describe the bug
I'm a dev in Microsoft for DirectLine App Service Extension. 
Some customers said their DL-ASE got disconnected once or twice per month.
I have investigated this issue, NamedPipeClient/NamedPipeServer have some bugs to do reconnect after they got an unexpected disconnected.
Both BotFrameworkHttpAdapter and CloudAdapter.

## To Reproduce
![image](https://user-images.githubusercontent.com/22291967/165212541-dda8e859-3c56-4e1f-88b3-930518109d3c.png)
I add a try catch in NamedPipeClient. And build it into my bot Site Extensions (Maybe you need the DL-ASE code to do this.)

Anyway, sometimes it gets an Exception: Access Denied.
![image](https://user-images.githubusercontent.com/22291967/165212854-f2b9f0eb-bf26-4638-af1a-19b13b5676a8.png)

I never reproduce this locally, but it happens on Azure, and if we catch this exception and do an retry, it will connect correctly.

But here the connection is not built, so the Disconnect-Event or the AutoReconnect won't call. In this way, the connection will be disconnected. And customers need manual restart the AppService to fix it.

I also do some more tests.
As NamedPipeClient/NamedPipeServer do incoming and outcoming connection in a queue. If the client succeeds the first connection but throw an exception in the second. The server will still be waiting for the second connection and never reconnect. Even though the client does reconnect, it will be waiting for the first connection. And in this way, they will never match.
And I tried, there will be some issues even if build connections parallel. As we use one-way pipe, if the client disposed, the server listener (stream reader) will notice, but if the server disposed, the client would not notice until it sends a message or checks the connection. 
In this way, if the server’s first connection succeeds and throws an exception in the second one, then the server starts reconnecting (dispose old one and reconnect).  The client’s first connection will be built with the disposed server, and the second connection will be built with the reconnect one.

Anyway, why don’t we just use two-way Pipe?
![image](https://user-images.githubusercontent.com/22291967/165219231-bc9a8bef-6301-42ec-92d5-c4eb125f1ad7.png)
I have tested this, with some easy reconnect, it will work correctly.
And I check the v4.16, in the newest code, it does not make a reconnection when disconnected unexpectedly.

But it seems there will be a version issue if we change it to a two-way pipe:
The pipe name needs to be changed, but as the DL-ASE uses the old version, this will make the bot and the DL-ASE does not match.

Share we find a way to fix this reconnect issue together?

**Comment by msomanathan** [comment]
@woasishen - From the description, you mentioned this issue happens with both BotFrameworkHttpAdapter and CloudAdapter. Is my understanding correct?

**Comment by woasishen** [comment]
> 

Yes, they all can't reconnect correctly. BotFrameworkHttpAdapter has reconnect code, but there are some bugs~
Some icm created a long time ago, I think they used BotFrameworkHttpAdapter.  But not resolved perfectly.
As the connection is between processes locally, I guess it's disconnection may not happens very often.

**Comment by tracyboehrer** [comment]
@ceciliaavila @sw-joelmut @JuanAr Muthu can provide background on this

**Comment by ceciliaavila** [comment]
Hi @msomanathan,
We've been trying to reproduce this issue without success.
Do you have the samples you used for testing named pipes? ([PR#6147](https://github.com/microsoft/botbuilder-dotnet/pull/6147))
Maybe we can adapt those to repro this issue and test the possibility of adding the reconnect logic as suggested.

**Comment by msomanathan** [comment]
@ceciliaavila - Any sample can be used to test named pipes (like, echo bot sample). You just need to follow the instructions here to set up the sample to use DirectLine ASE: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0

**Comment by ceciliaavila** [comment]
Hi @msomanathan, thanks for the quick reply.
We followed that guide to connect the bot to DL-ASE, however, we are not sure it's calling the _NamedPipeClient_ and _NamedPipeServer_ classes that we need to test.
We are trying to figure out how to simulate the connection issue between the bot and the DL extension without any success.
We thought on simplify the scenario, creating a small client that calls the _ConnectAsync_ method of the _NamedPipeClient_. We would force the error in the connection to then try adding some reconnect logic.

**Comment by msomanathan** [comment]
@ceciliaavila - Since DL-ASE requires the bot to be published, you would need to debug into the bot deployed to Azure. Below are the steps to debug DL-ASE bots, please let me know if these steps are able to unblock you:

1. I took the CloudAdapter echo bot sample to set up DL-ASE, and attached to debugger in Visual Studio from the deployed bot as per the following option:

![image](https://user-images.githubusercontent.com/41929942/175698170-93364498-519d-484d-844b-bb458262c50b.png)

2. Then, I sent a message to the bot using a DL-ASE client and hit the breakpoint in my `NamedPipeTranspot`/`StreamingTransport` code. You could create either a console client ([here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-client?view=azure-bot-service-4.0)), or a webchat client ([here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0)) to talk to the bot through DL-ASE.

![image](https://user-images.githubusercontent.com/41929942/175699382-fc3cea25-4fa6-4c8b-9a76-8d75a5afbf1a.png)

**Comment by ceciliaavila** [comment]
Hi @msomanathan, thanks for the info!
We'll use this debug option to follow the code of the bot and create a console client to test this again trying to reproduce the error.
We'll let you know how it goes.
Thanks!

**Comment by woasishen** [comment]
Hi there, I can provide two ways to reproduce this issue.
1、[ConfigBotExtension](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-net-bot?view=azure-bot-service-4.0) and [AseWebClient](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0).
Follow these two docs, create a DL-ASE Bot.
After you can talk with Bot in AseWebClient, you can visit the appservice->configuration. And change some unused application settings (such as add an unused Application Setting), and save the change. After you do this, azure will restart both appservice process and appserviceextension process. Now when you check [https://<your_app_service>.azurewebsites.net/.bot](https://%3Cyour_app_service%3E.azurewebsites.net/.bot) you will find the ib/ob are false.
If you want to debug the code, you need the permission to access https://fuselabs.visualstudio.com/DefaultCollection/Intercom/_git/Intercom.
Follow [readme.md - Repos (visualstudio.com)](https://fuselabs.visualstudio.com/_git/Intercom?path=/Microsoft.DirectLineFlex/Microsoft.DirectLineFlex/readme.md) : # Deploying a Custom Build of DL-ASE to an App Service for Testing,  you can add logs to debug.

2. You can also test reconnect locally by starting an appservice process and appserviceextension process locally.
Follow [readme.md - Repos (visualstudio.com)](https://fuselabs.visualstudio.com/_git/Intercom?path=/Microsoft.DirectLineFlex/Microsoft.DirectLineFlex/readme.md) # Local Test DL-ASE, After you config correctly, and can talk with Bot in LocalAseTest.html. Try to restart the appservice(EchoBot) or appserviceextension(DirectLineFlex.proj), the ib/ob will be false.
