### ISSUE TITLE
Nested Component Adaptive Dialog's Maximum nesting depth of 127 exceeded

### ISSUE THREAD

**Issue by karrimrabibiomni** [microsoft/botbuilder-dotnet#6307]
## Version
4.15.2

## Describe the bug
We are using ComponentDialogs to make a customise-able bot, the problem using DialogContainers like Foreach we are getting Maximim nesting depth error of 127 exceeded even when we are only 6-10 dialogs.

## To Reproduce
1. Create an adaptive bot with a DialogContainer
2. In side that container call another ComponentDialog
3. Then call another ComponentDialog 
4. Keep doing this until you get the cosmosdb exception

## Expected behavior
We want to be able to call at least 50 deep CompentDialogs 6-10 seems to allow for only simple logic

## Screenshots
![image](https://user-images.githubusercontent.com/65707695/165338101-752ca166-0a0d-4764-aea8-0d2d497bc92d.png)

Here is an example json that causes the bug.
[simplenestedbug.json.txt](https://github.com/microsoft/botbuilder-dotnet/files/8564603/simplenestedbug.json.txt)

## Additional context
1) One problem is the use of TypeNameHandling = Newtonsoft.Json.TypeNameHandling.All this seems to compound the issue. Can you update the bot code to support TypeNameHandling = Newtonsoft.Json.TypeNameHandling.None

2) Second why do you have to store Dialog state as a JObject inside cosmosDB maybe that can be changed.

3) Do you need to store the dialog state in hierarchical structure at all? will a flat Dictionary of dialogStacks against id's and a parent id work better?

**Comment by msomanathan** [comment]
@karrimrabibiomni - Deep nesting of dialogs is not a recommended scenario, and it also makes maintaining difficult. One way to work around this issue is to call your utility dialogs from [custom event](https://docs.microsoft.com/en-us/composer/how-to-define-triggers?tabs=v2x#custom-events) triggers in the root dialog rather than nesting them many levels deep. You can then emit an event from the child where you want that logic to run and set `bubbleEvent` to true which will allow the root dialog to handle that request.

**Comment by karrimrabibiomni** [comment]
Changing the singleton IStorage in the Bot's startup from the CosmosDbPartitionedStorage to the BlobsStorage fixes this issue.

What are the advantages of using CosmosDbPartitionedStorage for the Bot Framework and are the any problems or issues with using Blob storage?

**Comment by EricDahlvang** [comment]
Hi @karrimrabibiomni 

As you've determined, the 128 nesting limit is from Cosmos: https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits

Cosmos tends to have better performance than Blobs depending on usage. Particularly the transcript implementations. Other than that, I'm not aware of any issues.
