### ISSUE TITLE
Add possibility to skip Governance task in forks

### ISSUE THREAD

**Issue by sw-joelmut** [microsoft/botbuilder-dotnet#6317]
**Is your feature request related to a problem? Please describe.**
When executing the CI pipeline ([botbuilder-dotnet-ci.yml](https://github.com/microsoft/botbuilder-dotnet/blob/main/build/yaml/botbuilder-dotnet-ci.yml)) from an organization that doesn't have the `ComponentGovernanceComponentDetection@0` task installed, it fails to start.
This task doesn't seem to be publicly available, thus, it would be a good addition to let the user choose to skip it.

The following image shows the error when starting the pipeline.
![image](https://user-images.githubusercontent.com/62260472/166311494-99e9c8a8-58b0-4323-aac8-e7614b1311d0.png)

**Comment by BruceHaley** [comment]
You could put the component governance task into the yaml, then add the condition:
```
condition: and(succeeded(), ne(variables['System.PullRequest.IsFork'], 'True'))
```

**Comment by sw-joelmut** [comment]
> Our CI pipeline runs the component governance task against forks without a problem. Is it possible you are running the pipeline outside of the Microsoft organization? In which case, why not just disable or delete the task?
> 
> Here is how I skip a task in a fork. Instead of that var you could instead substitute a user-settable var like "skipComponentGovernance":
> 
> ```
> condition: and(succeeded(), ne(variables['System.PullRequest.IsFork'], 'True'))
> ```

Hi @BruceHaley, thank you for the response.
Regarding the provided solution, we've tried that and didn't work for us, since the task validation is happening at compile-time rather than run-time.
Our pipelines run on a different DevOps organization outside Microsoft's, and thus we don't have the possibility to install it.

**Comment by ceciliaavila** [comment]
Reviewed with Gabo, we'll close this issue and find an alternative on the SW side.
