### ISSUE TITLE
Add screenshots to the wiki examples

### ISSUE THREAD

**Issue by mahomedalid** [Microsoft/botbuilder-dotnet#634]
It would be very useful to see what a "Card" means or a "Suggested Action" before compiling a version of the bot with the examples code provided. This could be very useful in terms to know what kind of card do I need.

Pages: Sending Cards and Attachments, Dialogs-and-Prompts

**Comment by JonathanFingold** [comment]
@mahomedalid , More complete documentation is available on **docs.microsoft** at https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0. (We'll updating the wiki soon to point there.) However, this issue still exists there, but hopefully, we'll fix it up soon.

**Comment by JonathanFingold** [comment]
PS. Does the [Channel Inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Skype/) meet your needs? In addition, the [Adaptive Cards project](http://adaptivecards.io/) has its own documentation, along with a visualizer.
