### ISSUE TITLE
Unable to load shared library 'liboc_abi' on MacOS (DllNotFoundException)

### ISSUE THREAD

**Issue by agrubskiy** [microsoft/botbuilder-dotnet#6344]
## Version
4.16
Microsoft.Bot.Builder.AI.Orchestrator

## Describe the bug
When trying to initialize OrchestratorRecognizer object, it fails due to be unable to find liboc_abi lib in macOS environment.
This problem is specific to macOS, on Windows there's no problems whatsoever.

System.DllNotFoundException:
Unable to load shared library 'oc_abi' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liboc_abi, 0x0001): tried: 'liboc_abi' (no such file), '/usr/local/lib/liboc_abi' (no such file), '/usr/lib/liboc_abi' (no such file), '/Users/antongrubskij/Documents/ChatBot/src/client/DevRain.RevenueAI.Bot/liboc_abi' (no such file)

## To Reproduce
Fails on initialization
var orc = new OrchestratorRecognizer(modelPath, snapshotPath);

## Screenshots
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/30052548/170945567-2007bf77-c8f9-4776-b4cb-6b8b67b7ee44.png">

## Additional context
Setup:
macOS 12.4 (ARM64)
Visual Studio Mac 2022
.Net Core 6.0

**Comment by ramfattah** [comment]
Hi @agrubskiy 

Do you get the same error if using `Object initializer` to initialize the OrchestratorRecognizer class?

Example:
```cs
var orc = new OrchestratorRecognizer()
{
     ModelFolder = modelFolder,
     SnapshotFile = snapshotFile
};

```

**Comment by agrubskiy** [comment]
Ok, using this kind of initialisation works correctly both on ARM64 and x64, tried it in both envirionments

**Comment by ramfattah** [comment]
Hey @daveta, reaching out if you have any updates? Thanks.

**Comment by daveta** [comment]
Hi @agrubskiy : Unfortunately, Orchestrator only supports Mac OS on Intel x64..
