### ISSUE TITLE
HeroCard CardAction does not serialize anonymous types in Value

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#635]
Similar to #633, I was attempting to use an anonymous type for the `Value` property of a `CardAction` and while it compiles fine (of course) and runs fine at runtime, the action data from the anonymous type is not being serialized and emitted into the data property in the JSON that is returned.

**Comment by yochay** [comment]
@drub0y can you take a look and see if you can fix it?

**Comment by johnataylor** [comment]
See comments in related issue.
