### ISSUE TITLE
isMatch adaptive expression returns error when value is null or empty string

### ISSUE THREAD

**Issue by craighanson** [microsoft/botbuilder-dotnet#6354]
## Version
4.16.0

## Describe the bug
The prebuilt adaptive expression 'isMatch' returns the error message 'regular expression is empty.' when the target string is null or empty string. This makes the function hard to use and would be better if it simple returned false.

## To Reproduce
1. Go to https://playgroundclient.azurewebsites.net/
2. Enter expression --> isMatch(name, '([0-9])')
5. Enter properties --> { "name": "" }
6. Click 'Run'
7. See error

## Expected behavior
Instead of returning an error message the function should return false

**Comment by tracyboehrer** [comment]
Added to next milestone for review and analysis.
