### ISSUE TITLE
ForEachElement Performance Degradation

### ISSUE THREAD

**Issue by karrimrabibiomni** [microsoft/botbuilder-dotnet#6371]
## Version
4.16.1

## Describe the bug
After upgrading we have noticed our bots slowing down by a factor of 10.  we have pined it down to a bug in the constructor of the ForEachElement.  When you perform a linq query on a ForEachElements Actions the GetDependancies gets called several times rather than once.  For complicated dialogs this can make a 2 second turn call now be 20 seconds. 

## To Reproduce
Download and run the bot in the attached zip, you will see that GetDependancies is called 6 times to run only 4 dialog s. 

## Expected behavior
GetDependancies is only called once when performing a linq query on the actions.

## Screenshots
![image](https://user-images.githubusercontent.com/65707695/175052291-0099a129-78ff-449a-974c-384cb6a328df.png)

## Additional context
Here is our attempt at a fix

```
public ForEachElement(IEnumerable<Dialog> actions = null)
          : base(true)
        {
            _scope = new ActionScope(actions?.ToList());
        }

        public List<Dialog> Actions => this._scope.Actions;
```

## Sample Bot Showing Bug
[ForEachElementConstuctorBug.zip](https://github.com/microsoft/botbuilder-dotnet/files/8958458/ForEachElementConstuctorBug.zip)

**Comment by EricDahlvang** [comment]
Hi @karrimrabibiomni 

Thank you for raising this issue. I've added your suggestion in this pull request: https://github.com/microsoft/botbuilder-dotnet/pull/6394
