### ISSUE TITLE
[Bug, Bot.Builder.Core.Extensions] Missing CardFactory.cs

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-dotnet#638]
There is no implementation of a CardFactory in the .NET SDK (see related issues #77 and #166). As such there is also a discrepancy in the RichCards sample implementation as it uses the Card classes from the Schema library as opposed to the CardFactory from Bot.Builder.Core.Extensions.

Example: [CreateAnimationCardAttachment()](https://github.com/Microsoft/botbuilder-dotnet/blob/master/samples-final/6.AspNetCore-RichCards-Bot/RichCardsBot.cs#L182)

**Comment by johnataylor** [comment]
This is there in the JavaScript but missing from the C#. See:
https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/cardFactory.ts

**Comment by johnataylor** [comment]
The C# implementation has a set of extension functions toAttachment() defined in Schema. This is not exactly the same but give parity.
