### ISSUE TITLE
Bump Newtonsoft.Json from 12.0.3 to 13.0.1

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#6392]
Bumps [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json) from 12.0.3 to 13.0.1.

Release notes
Sourced from [Newtonsoft.Json's releases](https://github.com/JamesNK/Newtonsoft.Json/releases).

13.0.1
New feature - Add JsonSelectSettings with configuration for a regex timeout
Change - Remove portable assemblies from NuGet package
Change - JsonReader and JsonSerializer MaxDepth defaults to 64
Fix - Fixed throwing missing member error on ignored fields
Fix - Fixed various nullable annotations
Fix - Fixed annotations not being copied when tokens are cloned
Fix - Fixed naming strategy not being used when deserializing dictionary enum keys
Fix - Fixed serializing nullable struct dictionaries
Fix - Fixed JsonWriter.WriteToken to allow null with string token
Fix - Fixed missing error when deserializing JToken with a contract type mismatch
Fix - Fixed JTokenWriter when writing comment to an object

**Note:** Once addressed, this fix should be checked for PVA compat

**Comment by EricDahlvang** [comment]
For the sake of backwards compatibility, we need to ensure MaxDepth of null (or something very large) wherever json serialization/deserialization occurs.
