### ISSUE TITLE
TeamsInfo.GetMemberAsync failing with error "MethodNotAllowed"

### ISSUE THREAD

**Issue by devbynight** [microsoft/botbuilder-dotnet#6417]
## Version
4.15.2
4.16.1

## Describe the bug
When trying to get the user info when testing using teams
Exception being thrown when invoking 
member = await TeamsInfo.GetMemberAsync(stepContext.Context, activity.From.Id, cancellationToken);

Exception
Operation returned an invalid status code 'MethodNotAllowed'

Upgraded to 4.16.1
Still same error
Tried using var members = await TeamsInfo.GetPagedMembersAsync(stepContext.Context, null, null, cancellationToken);
But this gave the below error
Operation returned an invalid status code 'NotImplemented'

## To Reproduce
Exception when using the code above

## Expected behavior
This should work.

## Screenshots

App insights error
![image](https://user-images.githubusercontent.com/88477860/178924370-c7919275-3e58-4186-ae7a-c1418dcbfe83.png)

**Comment by stevkan** [comment]
@devbynight - A 500 type error in App Insights typically means there was an error in the bot, itself. So, this actually aligns with the 'MethodNotAllowed' error you are receiving in the bot. As to why you are receiving this error, can you elaborate on the details?

Did you encounter this while running one of the BotBuilder samples or are you trying to implement the functionality yourself? If a sample, which one? And did you make any changes to the code? Can you post the relevant code you are using?

**Comment by stevkan** [comment]
Also, with respect to your original post, I think we'll focus on the v4.16.1 `GetPagedMembersAsync` method since `GetMembersAsync` has a deprecated dependency and is marked as obselete.

**Comment by devbynight** [comment]
This is not from the samples. 

I am using GetMemberAsync and not GetMembersAsync

member = await TeamsInfo.GetMemberAsync(stepContext.Context, stepContext.Context.Activity.From.Id, cancellationToken);


This is a skill bot that we have. We have added this as a skill to a root bot
When I chat with the root bot, the skill bot throws exception at this line

But if I chat directly to the skill bot via teams it works.

I'm sure this was working some time back

**Comment by stevkan** [comment]
> I am using GetMemberAsync and not GetMembersAsync
>
>member = await TeamsInfo.GetMemberAsync(stepContext.Context, stepContext.Context.Activity.From.Id, cancellationToken);

If you are, in fact, trying to use `GetMembersAsync`, then I am unable to help you. As I mentioned, this method is deprecated and marked as obsolete because of a deprecated dependency. Your use of it is failing, and will continue to fail, because of this.

The solution is to use the newer `GetPagedMembersAsync` method available in the same library.

As a solution already exists to your issue and there is no alternative workaround, I am going to close this issue as resolved.

**Comment by devbynight** [comment]
@stevkan - I'm not using `GetMembersAsync`. I'm using `GetMemberAsync`

GetMemberAsync is not deprecated.
[Documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.teams.teamsinfo.getmemberasync?view=botbuilder-dotnet-stable)

**Comment by stevkan** [comment]
@devbynight - It looks like the docs were not properly updated to reflect the change in the code. I apologize for the confusion and will notify the docs team to make the appropriate changes.

As you can see in the botbuilder-dotnet Teams library, the [`GetMembersAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L119) method is, in fact, deprecated and marked as obsolete with the suggestion to use [`GetPagedMembersAsync`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L158), instead.

The same is true for the botbuilder-js Teams library (see [`getMembers`](https://github.com/microsoft/botbuilder-js/blob/b4a2a5ef5772c8ded4dece1ab291e8854e2d71df/libraries/botbuilder/src/teamsInfo.ts#L220)

**Comment by devbynight** [comment]
@stevkan - Again, I am not using GetMembersAsync

I am using [GetMemberAsync](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs#L195)

**Comment by stevkan** [comment]
Okay...so, first off, my apologies. Your initial post referenced using `GetPagedMembersAsync` and I think my brain simply glommed onto the plural version of every method after that. 😬 I'm on track now.

Our sample 57.teams-conversation-bot makes use of the same `GetMemberAsync` method (reference sample code [here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L128)) which yours appears to be structured similarly.

A primary difference I'm seeing between the two is the method in the sample lives in the activity handler (TeamsConversationBot) class. Given you're passing `stepContext.Context` as a method parameter in your code, it looks like you are perhaps trying to call the method from within a dialog...? If that is true, can you use the sample referenced above as a guide to move the call back to the activity handler and try again?

**Comment by devbynight** [comment]
@stevkan - That's alright.

This is still not working in the context of a skill bot.

Alternative solution - I replaced usage of `GetMemberAsync ` with a Graph API call to get the user details, by passing the AadObjectId obtained from the Activity context.
