### ISSUE TITLE
Need docs and samples on proactive messaging

### ISSUE THREAD

**Issue by apulliam** [Microsoft/botbuilder-dotnet#642]

**Comment by JonathanFingold** [comment]
Hi @apulliam , here's a link to our v4 topic on [How to use proactive messaging](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=cs). Let me know if that is missing information that you need.

**Comment by yochay** [comment]
We have a doc on the topic.
