### ISSUE TITLE
CreateDirectConversationAsync return “Bad format of conversation ID“”

### ISSUE THREAD

**Issue by hulin17** [microsoft/botbuilder-dotnet#6422]
## Version
What package version of the SDK are you using.
4.10.3.0

## Describe the bug
Give a clear and concise description of what the bug is.
I want to init conversation with a user via 1:1 chat in MSTeams Channel. I use the below sample to implement this.  But I got the next error. Why this? I got the Bot Channel Account & User Channel Account from "ConversationUpdate".

## To Reproduce
1.Get access_token.
2. Post the request:https://smba.trafficmanager.net/amer/v3/conversations, with `{
  "bot": {
    "id": {botId},
    "name": {botName},
  },
  "members": [
    {
      "id": {userId},
      "name": {userName},
      "aadObjectId": {userAadObjectId}
    }
  ]
}`
3. Observe the bug:

## Expected behavior
Return the conversation info.

## Screenshots
![image](https://user-images.githubusercontent.com/31561654/179964118-7c1f2fc3-2ad5-4f41-8989-03bf9af791f8.png)

**Comment by hulin17** [comment]
Updates: It's so wired when I try it again with the exactly same request, I got next error not like yesterday:
![image](https://user-images.githubusercontent.com/31561654/180116169-992f5604-40d7-41f2-a1d1-2a8465f6fb57.png)
when I add the tenantId, I got this error:
![image](https://user-images.githubusercontent.com/31561654/180116111-cd38a87c-60ad-4061-bd4f-2fe10a1a3674.png)
My botId is 96c84039-7160-48d1-a1cd-809b7e292892. You can use this to find the log. Timestamp: I just tried these two requests in last 10 minutes.

**Comment by dmvtech** [comment]
Hi @hulin17 

Can you confirm the version you are running? Is it `4.10.3` or `4.13.0` ?

**Comment by hulin17** [comment]
Hi @dmvtech, Confirmed for 4.10.3.  I also used postman to test this. You can check with the screenshots.

**Comment by dmvtech** [comment]
Thank you @hulin17. I can reproduce the original error. I'm continuing to troubleshoot.

**Comment by dmvtech** [comment]
Apologies for the delay. I am still investigating.

**Comment by tracyboehrer** [comment]
Can we try the latest SDK version, which is 4.17.1?

**Comment by dmvtech** [comment]
Closing due to lack of response.

**Comment by hulin17** [comment]
Apologies for the delay. @dmvtech @tracyboehrer. I also used Postman to test this. This is still repro. Do you guys find the root cause of this?

**Comment by antoine-chopin** [comment]
Wow great support there
