### ISSUE TITLE
Error in AdaptiveDialog.ContinueActionAsync with native dialog SDK

### ISSUE THREAD

**Issue by sbiaudet** [microsoft/botbuilder-dotnet#6433]
## Version
Version 4.17.1

## Describe the bug
I use a "SatisfactionDialog" dialog inherited from ComponentDialog. This dialog is called in an AdaptiveDialog via BeginDialog("SatisfactionDialog"). I have an error in the AdaptiveDialog.ContinueActionAsync function. 

System.ArgumentException: Could not find resource 'SatisfactionDialog.dialog' (Parameter 'SatisfactionDialog.dialog')

The problem is present since version 4.17.1 but not in version 4.16.1. the problem comes from merge #6365. The framework tries to load a SatisfactionDialog.dialog file during ContinueConversation instead of using the SatisfactionDialog instance.

` var resourceExplorer = actionDC.Context.TurnState.Get<ResourceExplorer>();
        if (resourceExplorer != null)
             {
                   dialog = resourceExplorer.LoadType<AdaptiveDialog>($"{actionDC.ActiveDialog.Id}.dialog");
                   actionDC.Dialogs.Add(dialog);
             }`

## Expected behavior
During ContinueActionAsync, the framework must support SDK native dialogs

**Comment by tdurnford** [comment]
@JuanAr Can you give us a status update on this?

**Comment by JuanAr** [comment]
> @JuanAr Can you give us a status update on this?

Hi @tdurnford, this issue is on our backlog. We'll be tackling it this week.
Thanks.

**Comment by johnataylor** [comment]
@sbiaudet we have a fix in the works for this, thanks.

**Comment by sbiaudet** [comment]
@johnataylor thanks. I've read the PR and it looks good. I will try it in a next daily build
