### ISSUE TITLE
SSL Connection failure to "login.microsoftonline.com" when we add BOT app service in VNet

### ISSUE THREAD

**Issue by Ravi-Macha** [microsoft/botbuilder-dotnet#6447]
## Version
 <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveCards" Version="2.7.3" />
    <PackageReference Include="Azure.AI.Language.QuestionAnswering" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.28.0" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.16.1" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.QnA" Version="4.16.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Azure" Version="4.16.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Azure.Blobs" Version="4.16.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.16.1" />
    <PackageReference Include="Azure.Search.Documents" Version="11.3.0" />
    <PackageReference Include="AdaptiveCards.Templating" Version="1.3.0" />
    <PackageReference Include="Antlr4.Runtime" Version="4.6.6" />
  </ItemGroup>

## Describe the bug
SSL Connection failure to "login.microsoftonline.com" when we add BOT app service in VNet

Microsoft.Bot.Builder.Integration.AspNet.Core.CloudAdapter: EXCEPTION [OnTurnError] unhandled error : Failed to acquire token for client credentials. (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.)
System.AggregateException: Failed to acquire token for client credentials. (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established,

## To Reproduce
1. Add service in VNet
2. Bot is failing to get JWT token from login.microsoftonline.com

## Expected behavior
Bot should work

**Comment by dmvtech** [comment]
Hi @Ravi-Macha 

This is not an issue with the SDK. This is a networking issue as shown in the error (The SSL connection could not be established).

**Comment by Ravi-Macha** [comment]
Well The bot framework is able to make connection but failing in acquiring the TOKEN, Bot code deployed in Azure app service is not able to LOAD and USE our company uploaded certs. Can you assist how to call URL using our CERT ?

**Comment by Ravi-Macha** [comment]
@johnataylor  - We had 3 calls with Microsoft, Networking and Bot framework teams. Case Number - 2207180010008359 . We do not allow directly to internet. The call to login.microsoftonline.com should happen through PROXY.  In order to pass PROXY we need Certs to be present in call. We dont know how to LOAD our certs in BOT framework
