### ISSUE TITLE
Error resolving type specified in JSON 'LivePersonConnector.EscalationsConversationData, LivePersonConnector'. Path 'EscalationsConversationData.$type'.Newtonsoft.Json.JsonSerializationException Could not load assembly 'LivePersonConnector'

### ISSUE THREAD

**Issue by davidimmanuel007** [microsoft/botbuilder-dotnet#6461]
Hi Experts, I'm integrating one off the handoff sample **(Live person Proxy Assistant)**  from here [to](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library/csharp_dotnetcore/samples) my bot framework solution. Im using azure cosmos db for storing the conversation states. And the Code works as expected. I have also integrated my bot with Microsoft teams. Recently I had publish my old solution (which was not integrated with live person sample). & the my bot works as expected in webchat, whereas in Microsoft teams it is not responding and when I check the logs in azure console It shows the following 

**LoggingMiddlewareCosmosDb.cs-OnTurnAsync, Message : Error resolving type specified in JSON 'LivePersonConnector.EscalationsConversationData, LivePersonConnector'. Path 'EscalationsConversationData.$type'.Newtonsoft.Json.JsonSerializationException: Could not load assembly 'LivePersonConnector'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)**

Since I have published the solution which is not integrated with live person solution It is strange that it asks for this particular assembly. Tried clearing cache for MS teams but it doesn't work.  

If i publish my solution(which is not integrated with liveperson sample) after publishing the liveperson sample integrated bot Im seeing this error - **#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.)**  

But even after deleting the dll and publishing the app to azure I;m still facing the same error for Microsoft teams. 

## Version
Bot framework SDK 3.1

## To Reproduce
1. Go to ['...'](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library/csharp_dotnetcore/samples)
2.Clonne the repository - Integrate the sample LivepersonProxyAssistant to your bot framework sample'
3. Integrate the bot to MS teams 
4. Publish the Integrated solution.
5. Publish the solution which was not integrated with Liveperson sample
6. See error in MS teams channel (The bot does not reply)

## Expected behavior
Bot should reply

**Comment by tracyboehrer** [comment]
Is SDK 3.1 correct?  If so, SDK v3 reached end-of-support on 12/31/2019.  The path forward is using the latest v4 SDK version (4.17.1 at present).
