### ISSUE TITLE
ConnectorFactoryImpl should use a named client so that an specific client can be configured accordingly

### ISSUE THREAD

**Issue by marcopelegrini** [microsoft/botbuilder-dotnet#6482]
The ConnectorFactoryImpl: 
https://github.com/microsoft/botbuilder-dotnet/blob/6cb09dce74d2725867375c4ab3679713b1fe696b/libraries/Microsoft.Bot.Connector/Authentication/ConnectorFactoryImpl.cs#L40

Uses the default name for the HttpClient, which limits the flexibility to configure the HttpClient the Bot SDK will use to communicate with smba

For instance, I can't define a timeout for this particular client

**Comment by anishprasad01** [comment]
Hi @marcopelegrini,

Thank you for your report. You're right about this, though at the moment there are no plans to modify the implementation. However, the `_httpClientFactory` is pluggable, and you could look into creating your own factory which implements `IHttpClientFactory` which can then be passed into the bot at startup via dependency injection. This approach should get you around your blocker and let you configure the HttpClient as you wish.

**Comment by marcopelegrini** [comment]
@anishprasad01 that's not really an workaround, as the factory doesn't have any information regarding where that client is being created, so there's no way to be specific in the configuration for the client of the bot sdk.

This is a very low hanging fruit and 1 line of code to change it. I'm surprised it can't be accommodated easily in your backlog

**Comment by anishprasad01** [comment]
My apologies. I can certainly communicate that sentiment, but I cannot offer any guarantees.
