### ISSUE TITLE
Microsoft.ConfirmInput doesn't show the prompt text in teams

### ISSUE THREAD

**Issue by jamesemann** [microsoft/botbuilder-dotnet#6485]
## Version
4.17.2

## Describe the bug
When using a `Microsoft.ConfirmInput` the prompt text is not shown.  

On inspection it is because the method `AppendChoices` is setting `prompt.Text` to null.

## To Reproduce
Add a `Microsoft.ConfirmInput` and test it on a teams bot:

```
{
          "$kind": "Microsoft.ConfirmInput",
          "$designer": {
            "id": "tLL1Si"
          },
          "defaultLocale": "en-us",
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "prompt": "please confirm",
          "unrecognizedPrompt": "",
          "invalidPrompt": "",
          "defaultValueResponse": "",
          "choiceOptions": {
            "includeNumbers": true
          }
}     
```
## Expected behavior
It should show the prompt text and yes/no buttons.

## Screenshots
It only shows the yes/no buttons:

![image](https://user-images.githubusercontent.com/6830648/195130790-b2890fc1-6955-4f81-81b3-f05d4e970ee2.png)

It should look like this (to workaround it I manually set the activity text value after the call to `AppendChoices` inside `ConfirmInput.OnRenderPromptAsync`):

![image](https://user-images.githubusercontent.com/6830648/195131217-b7e36661-6a90-4f5b-8d9a-04c13d6fa325.png)

## Additional context
Thanks!

**Comment by dmvtech** [comment]
Hi @jamesemann 

Is this a Composer bot? Or a code bot using adaptive/declarative?

**Comment by jamesemann** [comment]
> Hi @jamesemann
> 
> Is this a Composer bot? Or a code bot using adaptive/declarative?

Hi @dmvtech , it is a declarative bot which I made in composer. The issue is in the C# runtime.

**Comment by jamesemann** [comment]
Hi @dmvtech and team. 
Have you been able to repro this issue?

**Comment by dmvtech** [comment]
Hi @jamesemann I am unable to reproduce this yet. There are a few more things I need to try but am hitting some stumbling blocks on my end. I will update when I have more info.

**Comment by dmvtech** [comment]
Hi @jamesemann I was unable to reproduce this at all. Are you able to share a sample bot that reproduces the issue? You can share in a repository or in a zip file.

**Comment by dmvtech** [comment]
Closing due to lack of response and unable to reproduce. If you can please share a sample or exact steps on how to reproduce, we will reopen and continue.

**Comment by jamesemann** [comment]
@dmvtech I will try and carve out some time so that I can give you an exact repro of the issue.
