### ISSUE TITLE
Can’t use custom conversation state type with dialogs

### ISSUE THREAD

**Issue by twlodarc** [Microsoft/botbuilder-dotnet#650]
Is there any possibility to use custom type of conversation state and dialogs.
`_dialogs = new DialogSet();`
`var dc = _dialogs.CreateContext(turnContext, state);`
Creating dialog context requires to pass state of type IDictionary<string, object>. It means that if I want to store extra information I need to manually get them from dictionary and can’t use  `var state = ConversationState<ConversationData>.Get(turnContext);`
As a workaround I’m using something like that:
`var state = ConversationState<Dictionary<string, object>>.Get(turnContext);`
`var conversationData = ConversationData.FromDictionary(state);`

Would it be any possibility to use more than one type with ConversationState in one bot?

**Comment by yochay** [comment]
this is part of #375
