### ISSUE TITLE
BotFrameworkAdapter should return ErrorResponse for bot errors

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#651]
The C# adapter doesn't currently catch errors that happen in the bots code. The JS code does but it maps them to a 500 error. The correct behavior is to return 200 OK to the channel but return an `ErrorResponse` object with the exception that was caught.

**Comment by johnataylor** [comment]
Any leaked exception in the bots code (dialogs, middleware or wherever) will trigger the global error handler to be called.

**Comment by johnataylor** [comment]
This is an old issue. Before the 4.0 release we added a global OnTurnError on the adapter. The samples illustrate the usage.
