### ISSUE TITLE
CreateConversation() should NOT mockup a ConversationUpdate activity

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#652]
Instead, it should mockup an "event" activity with a `name` of "createConversation". Similarly, the ContinueConversation() method should mockup an "event" named "continueConversation". This recomendation is based off discussions we had with MS Teams.

**Comment by tomlm** [comment]
CR pending

**Comment by sgellock** [comment]
we believe this is done and merged.
