### ISSUE TITLE
multi-choice question with the composer

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/botbuilder-dotnet#6534]
I created a multi-choice question with the composer. This input has the type suggestedActions and contains a yes and no button. If the bot then shows this question, the suggested actions are displayed as buttons. However, if the user makes no input, the bot automatically responds with no. Can this be turned off? The max turn count setting ist set to 1 and no default response.
Regards
Andreas

**Comment by ramfattah** [comment]
Hi @andreas-sommer-engenious,

> if the user makes no input, the bot automatically responds with no.

Are you referring to if user doesn't select one of the SuggestedAction choice? 

#

I'm not able to reproduce this issue. The bot did not automatically respond with "No". 

Perhaps I'm missing something from my end, sharing the steps I took:
1. Created a new Composer Empty Bot (C#) Project
2. In Greeting trigger, I created a [multiple-choice action](https://learn.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#create-a-multiple-choice-action)
     * <strong>Bot response</strong>
          * Text: `Select Yes or No`
     * <strong>User input</strong>
          * Property: `dialog.answer`
          * List style: `SuggestedAction`
          * Array of choices: `Yes`, `No`
     * <strong>Other</strong>
          * Max turn count: `1`
          * Default value: blank
3. In the same trigger, added new `Send a response` action
     * Set the text: `You Selected ${dialog.answer}`
4. Ran the bot in Emulator
5. The bot displayed Yes and No options
6. Sent `Test`
7. Did not automatically respond with "No"



@andreas-sommer-engenious , let me know if I shall take additional steps to repro this issue. Thanks.

**Comment by ramfattah** [comment]
Hi @andreas-sommer-engenious, any updates on this?

**Comment by andreas-sommer-engenious** [comment]
Yes I’m also confused, because in the emulator it does not automatically respond. We created the web front end with nodejs and there it automatically respond after 5 minutes. I never had the effects in other bot projects.
Regards
Andreas

**Comment by ramfattah** [comment]
@andreas-sommer-engenious are you able to share a minimal reproducible bot?
