### ISSUE TITLE
applying BotMessageSerializerSettings.MaxDepth doesn't seem to work

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#6542]
Customer reports that they see "The reader’s MaxDepth of 64 has been exceeded." Using Botbuilder V4.17 with Newtonsoft.Json 13.0.1

Downgrading to Newtonsoft.Json to 12.0.3 resolved the issue. As described in https://github.com/microsoft/BotBuilder-Samples/issues/3328

However when they tried the settings as described in https://github.com/microsoft/BotFramework-Composer/issues/9387#issuecomment-1254199071

Using using Botbuilder V4.17 with Newtonsoft.Json 13.0.1 they tried to change the MaxDepth but this did not seem to work.

**Comment by tdurnford** [comment]
@JuanAr Can you investigate this issue?

**Comment by JuanAr** [comment]
> @JuanAr Can you investigate this issue?

Hi @tdurnford, we'll add this issue to our backlog. We'll let you know as soon as we start investigating it.
Thanks!

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, 
We reviewed the issue and the changes we made a few months ago, and we may have missed applying the _MaxDepth_ setting in the [OAuthClient](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/OAuthClient.cs#L728) class. Also, we need to check the [ConnectorClient](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/ConnectorClient.cs#L338) and [TeamsConnectorClient](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Teams/TeamsConnectorClient.cs#L286) classes, as we think there may be code paths that are not setting the property.
If it's ok, we'll try to include this issue in this iteration, after finishing the CodeQL fixes.

**Comment by 462sai** [comment]
Hi @ceciliaavila

Could you please confirm this fix is released? if yes please confirm the botbuilder version

Regards,
Sai.

**Comment by tracyboehrer** [comment]
@462sai This is not released.  Rather just merged into main.  The next release is currently scheduled for early January.  However, there is a periodic development release to MyGet.  Reference the "UsingMyGet.md" for details.
