### ISSUE TITLE
Sending proactive message to slack without user conversation reference

### ISSUE THREAD

**Issue by raghavsuriya** [microsoft/botbuilder-dotnet#6545]
I am looking to send a message through the bot framework to slack. However the user has not interacted with the slack bot earlier and hence no conversation reference is available. But to send a proactive message , I need a conversation reference object. How can I construct the object given that I have the botID and the userID (slack) for whom I want to send the message to. 

Also I saw the method CreateConversationsAsync . How different it is from ContinueConversationsAsync ? Can I leverage the CreateConversationAsync to create a channel between the user and bot in DM and then send the proactive message ? 

Thanks

**Comment by stevkan** [comment]
@raghavsuriya, I am looking into this and hope to have a response to you by EOD, today.

**Comment by raghavsuriya** [comment]
Hi @stevkan , thank you for the response. Did you get a chance to look at this ?

**Comment by stevkan** [comment]
@raghavsuriya - Thank you for your patience. I am still looking into this at the moment. I am able to send a proactive message to Slack using the `createConversation` method from the deprecated BotFrameworkAdapter without issue. However, I am running into some issue using the `createConvesationAsync` method from the CloudAdapter. I am continuing to investigate and will let you know what I find as I know more.

**Comment by stevkan** [comment]
@raghavsuriya - Again, thank you for your patience. I was running into some slight issues using the dotnet SDK so I switched to JS and, after some trial and error, I have been able to get it to work. I am now going back to dotnet to replicate the JS setup. I hope to have an update on that soon.

**Comment by stevkan** [comment]
@raghavsuriya - I've successfully tested this. You can find below a working example on how you can proactively start a Slack conversation with a member where no previous conversation existed. This borrows from sample [16.proactive-messages](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/16.proactive-messages) whereby the conversation is triggered by a GET call made to `http://localhost:3978/api/notify`. Of course, if you want to pass certain values as parameters in the HTTP call to be used in the new conversation (ex., a name, greeting, other data), then simply adjust the controller to accept POST calls.

_Please note: The_ `_slackBotId` _and_ `_slackMemberId` _passed into each ChannelAccount come from Slack and are defined in the appsettings.json file. Each Id will look similar to the below examples:_

> "SlackBotId": "BB5XXXNQY:T9BXXXFFS",
>  "SlackMemberId": "UFYXXX23F:T9BXXXFFS"

_The first portion (prior to the ":") is the bot / member Id. The second portion (following the ":") is the team Id. **Be sure there are no empty spaces in each Id set.**_

**NotifyController.cs:**
```c#
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System;
using System.Collections.Concurrent;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.Integration.AspNet.Core;
using Microsoft.Bot.Schema;
using Microsoft.Extensions.Configuration;

namespace Microsoft.BotBuilderSamples.Controllers
{
    [Route("api/notify")]
    [ApiController]
    public class NotifyController : ControllerBase
    {
        private readonly IBotFrameworkHttpAdapter _adapter;
        private readonly string _appId;
        private readonly string _slackBotId;
        private readonly string _slackMemberId;
        private readonly ConcurrentDictionary<string, ConversationReference> _conversationReferences;

        public NotifyController(IBotFrameworkHttpAdapter adapter, IConfiguration configuration, ConcurrentDictionary<string, ConversationReference> conversationReferences)
        {
            _adapter = adapter;
            _conversationReferences = conversationReferences;
            _appId = configuration["MicrosoftAppId"] ?? string.Empty;
            _slackBotId = configuration["SlackBotId"] ?? string.Empty;
            _slackMemberId = configuration["SlackMemberId"] ?? string.Empty;
        }

        public async Task<IActionResult> Get()
        {
            ChannelAccount bot = new Bot.Schema.ChannelAccount(_slackBotId);
            ChannelAccount members = new Bot.Schema.ChannelAccount(_slackMemberId);

            Bot.Schema.ConversationParameters ConversationParameters = new Bot.Schema.ConversationParameters();

            ConversationParameters.IsGroup = false;
            ConversationParameters.Bot = bot;
            ConversationParameters.Activity = null;
            ConversationParameters.ChannelData = null;
            ConversationParameters.Members = new ChannelAccount[] { members };
            System.Threading.CancellationToken CancellationToken = new System.Threading.CancellationToken();

            await ((BotAdapter)_adapter).CreateConversationAsync(
                _appId,
                "slack",
                "https://slack.botframework.com",
                "https://api.botframework.com",
                ConversationParameters,
                BotCallback,
                CancellationToken
            );
            
            // Let the caller know proactive messages have been sent
            return new ContentResult()
            {
                Content = "<html><body><h1>Proactive messages have been sent.</h1></body></html>",
                ContentType = "text/html",
                StatusCode = (int)HttpStatusCode.OK,
            };
        }

        private async Task BotCallback(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync("proactive hello");
        }
    }
}
```

As this should resolve your problem, I am going to close issue. If you have any additional questions regarding this, please feel free to re-open.
