### ISSUE TITLE
Handling Telegram video notes

### ISSUE THREAD

**Issue by sombe** [microsoft/botbuilder-dotnet#6547]
Hello,
I'm not sure if this is a bug or intended behaviour, I've found out that when a user sends a video note recorded within Telegram mobile app (not by using smartphone camera app but the built-in functionality) that message isn't handled like a normal file and isn't included in activity's attachments. The only place where I can find some data of that is in channel data. I think that those videos are a bit different from "normal" ones, and found out that the property in channel data is slightly different.

For reference, this is the piece of channel data of a "normal" video:
`...
"video": {
  "duration": 7,
  "width": 1280,
  "height": 720,
  "mime_type": "video/mp4",
  "thumb": {
    "file_id": "fakeIdForPrivacy",
    "file_unique_id": "fakeIdForPrivacy",
    "file_size": 16644,
    "width": 320,
    "height": 180
  },
  "file_id": "fakeIdForPrivacy",
  "file_unique_id": "fakeIdForPrivacy",
  "file_size": 3112832
  }
...`

and this is of a Telegram video note:
`...
"video_note": {
  "duration": 7,
  "length": 384,
  "thumb": {
    "file_id": "fakeIdForPrivacy",
    "file_unique_id": "fakeIdForPrivacy",
    "file_size": 8691,
    "width": 320,
    "height": 320
  },
  "file_id": "fakeIdForPrivacy",
  "file_unique_id": "fakeIdForPrivacy",
  "file_size": 1076452
  }
...`

Telegram audio notes instead are correctly handled as attachments.
This also have an impact in attachment prompt that does not recognize that type of videos as attachments. I know that I could use a custom prompt validator in order to detect this case but I was wondering if this is a known bug or if there is any planning of adding this feature in bot framewok.

Thank you!

**Comment by tdurnford** [comment]
@luhan2017 @boydc2014 Do either of you know if this a feature we support?

**Comment by johnataylor** [comment]
@boydc2014 @luhan2017 any update on this?

**Comment by boydc2014** [comment]
Sorry for the delay. I've confirmed with team that is expected behavior that we didn't handle video notes specificly. We don't have plan to do so given this feature was released at telegram side at 2017 and the decision in channel side at that time was made to leave it to as it is within in channel data.

**Comment by johnataylor** [comment]
closing this issue
