### ISSUE TITLE
SNAT Port exhaustion

### ISSUE THREAD

**Issue by Zaragor** [microsoft/botbuilder-dotnet#6553]
## Version
4.16.0

## Describe the bug
We're hosting bots created by the bot composer on a custom server in Azure, and our SNAT ports usage steadily climbs until we run out and start getting timeout errors.

## To Reproduce
1. Create a bot (I believe that makes an external HTTP call, but not 100%)
2. Create a web app that will load the AdaptiveBot and run it (using bot.ContinueConversationAsync)
3. Run the bot over the course of a few hours/days in an Azure App Service, making sure to call the endpoint
4. Observe the SNAT port exhaustion using the 'diagnose and solve errors' tab in azure

## Expected behaviour
SNAT ports should be reused

## Screenshots
![image](https://user-images.githubusercontent.com/46170709/202473692-84d837a6-2661-42a5-a8c1-12b2c12cd3ab.png)

## Additional context
I'm pretty sure that the issue isn't in the code we've written to host the bots, as the problem only appears in live and not our UAT/QAT environments. The only difference between the two are the bots that are hosted on them. I believe the problem might be in libraries/Microsoft.BotBuilder.Dialogs.Adaptive/Actions/HttpRequest.cs, where you're instantiating and disposing of a new HTTP client every time the dialog is called. 

I'm going to try verifying this by writing a custom middleware, which injects a reused HTTP client into the TurnState. I'll update this issue if that solves it. I'd rather not rely on an internal implementation detail intended for testing, so a correct fix would be preferred.

**Comment by tracyboehrer** [comment]
Adding an HttpClient to TurnState via Middleware is the recommended course.
