### ISSUE TITLE
AspNetCore-MultiplePrompts-Bot sample repeats output when age is too big a number

### ISSUE THREAD

**Issue by mishrapratyush** [Microsoft/botbuilder-dotnet#656]
Repro Steps:
1. run the sample and for name, specify abc
2. for age: enter 4324324234234234232
3. The bot prompts for name again
4. enter abc
5. for age specify 54
6. bot will display => your name and age and then it will run the "GatherInfoStep" again and this time on line #60 when converting result back to number, it fails as result is null.

Question:
Why did the flow repeat again? Shouldn't it have ended after the first successful run when it printed the name and age?

**Comment by JasonSowers** [comment]
We are in the process of reworking the samples.  We will make sure this is addressed when this sample is reworked.

**Comment by daveta** [comment]
@mishrapratyush : This might have been an old version.  
Checkout the latest 05.MultiTurn-Prompts-Bot that's in the v4 branch.
