### ISSUE TITLE
Bug while receiving Submit button action from Adaptive Card in Teams

### ISSUE THREAD

**Issue by vova-lantsov-dev** [microsoft/botbuilder-dotnet#6562]
## Version
`4.18.1`

## Describe the bug
Before (last week), when you clicked a 'submit' action button of adaptive card in order to submit some input fields, the `invoke` activity type was received in `Microsoft.Bot.Builder.ActivityHandler` class.

As for now, the `message` activity type is sent for some reason, that causes `Microsoft.Bot.Builder.Teams.TeamsActivityHandler.OnInvokeActivityAsync()` method to not be invoked.

`Microsoft.Bot.Builder.ActivityHandler.OnMessageActivityAsync()` is called at the moment. It's not implemented by the `TeamsActivityHandler` class so its overriding is not foreseen for Teams bot functionality.

## To Reproduce
1. Click on any action button that has the `submit` type
![image](https://user-images.githubusercontent.com/45858087/204310665-2ab13f25-510d-4e2e-8d09-d80aebd5de9c.png)

2.  Catch the `message` activity type
![image](https://user-images.githubusercontent.com/45858087/204311008-772b5d48-73fc-43af-aa7b-9ca26d0741b1.png)

## Expected behavior
`turnContext.activity.type` must be `invoke`

## Screenshots
![image](https://user-images.githubusercontent.com/45858087/204311438-bcf73e7e-3d73-49c0-8b59-d686053750ea.png)
![image](https://user-images.githubusercontent.com/45858087/204312544-3fb1735f-c01e-4b5a-a44f-57bc559f431c.png)

## Additional context
This is a Teams bot of `messaging extension` type.
Here is the configuration:
```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.14/MicrosoftTeams.schema.json",
  "manifestVersion": "1.14",
  "version": "1.0",
  "id": "<<YOUR-MICROSOFT-APP-ID>>",
  "packageName": "com.package.name",
  "developer": {
    "name": "Microsoft",
    "websiteUrl": "https://dev.botframework.com",
    "privacyUrl": "https://privacy.microsoft.com",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx"
  },
  "name": {
    "short": "Bot for Scheduling Interviews",
    "full": "Microsoft Teams Bot for Scheduling Interviews"
  },
  "description": {
    "short": "Bot for Scheduling Interviews",
    "full": "Bot for Scheduling Interviews built with the Bot Builder SDK"
  },
  "icons": {
    "outline": "icon-outline.png",
    "color": "icon-color.png"
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "<<YOUR-MICROSOFT-APP-ID>>",
      "scopes": [
        "team"
      ]
    }
  ],
  "composeExtensions": [
    {
      "botId": "<<YOUR-MICROSOFT-APP-ID>>",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "scheduleInterview",
          "type": "action",
          "context": [
            "compose"
          ],
          "description": "Command to run action to schedule an interview",
          "title": "Schedule an interview",
          "parameters": [
            {
              "name": "title",
              "title": "Interview title",
              "inputType": "textarea"
            },
            {
              "name": "description",
              "title": "Interview description",
              "inputType": "textarea"
            },
            {
              "name": "time",
              "title": "Interview suggested time",
              "inputType": "textarea"
            }
          ]
        }
      ]
    }
  ],
  "validDomains": [
    "<<Base_Url>>"
  ]
}
```

**Comment by anishprasad01** [comment]
Hi @vova-lantsov-dev,

- Did you make any code changes, and if so, does reverting them fix the issue?
- SDK 4.18.1 is fairly new. Does this issue occur on older versions of the SDK?
- Did you upgrade any Teams packages?

**Comment by vova-lantsov-dev** [comment]
@anishprasad01 
1) No, I didn't make any changes. It just stopped working when I tried to call this API on Monday after holidays.
2) I tried on version 4.16, the same behaviour
3) What packages I exactly have:
![image](https://user-images.githubusercontent.com/45858087/204384066-782a80e1-d3d7-4b35-8ee9-a6d8b1935b8a.png)

**Comment by anishprasad01** [comment]
I've requested someone from Teams to look into this, since you made no code changes and there were no releases on the Bot Framework side between when it worked and when it failed.

**Comment by anishprasad01** [comment]
@vova-lantsov-dev,

Teams is unable reproduce the issue. It's possible it was a transient issue. Is this issue still occurring for you?
