### ISSUE TITLE
OAuth prompt keeps showing even after the sign in was successful

### ISSUE THREAD

**Issue by thashu0424** [microsoft/botbuilder-dotnet#6574]
OAuth prompt keeps showing even after the sign in was successful . The prompt must ideal be shown only once and after it is given the permissions it should not show up again. But it keeps coming up every time I go to another chat and comeback to the bot . 
<img width="694" alt="image" src="https://user-images.githubusercontent.com/52147960/209518650-bb790f39-055c-4bd9-b684-3a610bd082a1.png">

**Comment by ramfattah** [comment]
Hi @thashu0424, we are investigating.

**Comment by thashu0424** [comment]
Hi @ramfattah any updates ?

**Comment by dmvtech** [comment]
Hi @thashu0424 

We are not able to reproduce this issue. Can you please confirm your oauth AAD application is set up correctly with all the appropriate configuration?

You can also go to your OAuth AAD app, and then go to manifest. Copy out the JSON and remove any of the sensitive/personal information, then paste it here? I'm specifically interested in the `requiredResourceAccess` section, but other parts may be important as well.

**Comment by thashu0424** [comment]
{
	"id": "6eb2e429-6145-4869-b704-d1249cb2e722",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 2,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "62e19576-7a09-4106-909c-f61e542b50d0",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2022-12-30T09:24:37Z",
	"description": null,
	"certification": null,
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://botid-62e19576-7a09-4106-909c-f61e542b50d0"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "TeamsBotSSO",
	"notes": null,
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": true,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "Allows Teams to call the app’s web APIs as the current user",
			"adminConsentDisplayName": "Teams can access the user’s profile",
			"id": "15b146e8-49f3-4d85-ac00-0b8961d2c042",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": "Enable Teams to call this app’s APIs with the same rights as you have",
			"userConsentDisplayName": "Teams can access the user profile and make requests on the user’s behalf",
			"value": "access_as_user"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2023-06-30T09:28:16.706Z",
			"keyId": "38e9a4a1-e8d6-49cb-98fa-9e1d9ecc81a2",
			"startDate": "2022-12-30T09:28:16.706Z",
			"value": null,
			"createdOn": "2022-12-30T09:25:45.7003262Z",
			"hint": ".tM",
			"displayName": "ssobot"
		},
		{
			"customKeyIdentifier": null,
			"endDate": "2027-12-30T00:00:00Z",
			"keyId": "fe831778-00af-405d-b60c-b7e624732e62",
			"startDate": "2022-12-30T09:24:39.2022563Z",
			"value": null,
			"createdOn": "2022-12-30T09:24:39.2262568Z",
			"hint": "IQP",
			"displayName": null
		}
	],
	"preAuthorizedApplications": [
		{
			"appId": "5e3ce6c0-2b1f-4285-8d4b-75ee78787342",
			"permissionIds": [
				"15b146e8-49f3-4d85-ac00-0b8961d2c045"
			]
		},
		{
			"appId": "1fec8e78-bce4-4aaf-ab1b-5451cc387262",
			"permissionIds": [
				"15b146e8-49f3-4d85-ac00-0b8961d2c045"
			]
		}
	],
	"publisherDomain": "thgmail.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "https://token.botframework.com/.auth/web/redirect",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4682d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADandPersonalMicrosoftAccount",
	"tags": [],
	"tokenEncryptionKeyId": null
}
@dmvtech

**Comment by thashu0424** [comment]
Hi @dmvtech any updates or anything wrong in the manifest?

**Comment by dmvtech** [comment]
Hi @thashu0424 Apologies for the delay. 

What API permissions are allowed? (Can be checked through the `API permissions` blade of the app registration). 

I see you only have one:
```json
      "resourceAccess": [
        {
          "id": "e1fe6dd8-ba31-4d61-89e7-88639da4682d",
          "type": "Scope"
        }
      ]
```

But I'm not familiar with what that one might be (friendly name). 

Also; from the Bot's Configuration blade and OAuth settings, does the `Test Connection` feature work correctly?

**Comment by thashu0424** [comment]
Hi @dmvtech , The API permissions are given and Test connection is working fine. Still not sure why it's having this issue

**Comment by thashu0424** [comment]
![image](https://user-images.githubusercontent.com/52147960/212828119-9310b3ab-594b-4831-a7d4-a54e1c5f47ce.png)
These are the API permissions  given

**Comment by thashu0424** [comment]
Hi @dmvtech  , I've added the manifest zip in this repo https://github.com/thashu0424/SSOBot and have given you access please accept it and check if even you are facing the issue from your end.

**Comment by thashu0424** [comment]
![image](https://user-images.githubusercontent.com/52147960/213152224-dfef4114-95a3-4edd-8719-b2df4d1d9d66.png)
In the image you can see that I have logged in . So the first time I give the permission I'm authenticated and logged in and the prompt goes away. Then when I go to another chat and come back to the bot chat the prompt shows up again and when I click on the continue again I get this message 
![image](https://user-images.githubusercontent.com/52147960/213152672-a2683242-9b83-48ab-b21d-27009bd6713b.png)

**Comment by thashu0424** [comment]
@dmvtech  any update?

**Comment by ramfattah** [comment]
@thashu0424,

* Are you able to reproduce this behavior using a fresh Teams Authentication sample [46.teams-auth](https://github.com/microsoft/BotBuilder-Samples/tree/main/archive/samples/csharp_dotnetcore/46.teams-auth)?
* Are you facing this issue in local environment or published bot? 
* Are you using SSO? 
* Did you follow any documentation to setup OAuth? If yes, could you please share links of the docs?

**Comment by thashu0424** [comment]
- Yes have tried creating 3 fresh bots all have the same issue
- In both published and local 
- Yes
- https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso

**Comment by ramfattah** [comment]
Hi @thashu0424, 

Tested Teams SSO Auth using sample [bot-conversation-sso-quickstart/csharp_dotnetcore](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore).
Followed [Build a bot with SSO authentication](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso#:~:text=Build%20a%20bot%20with%20SSO%20authentication,-Article) documentation.

I'm not able to reproduce this issue after switching to different chat and coming back. 

My Azure Bot Manifest json below looks pretty identical to yours.
<details>
  <summary>Manifest:</summary>
  
  ```json
  {
  "id": "<removed>",
  "acceptMappedClaims": null,
  "accessTokenAcceptedVersion": 2,
  "addIns": [],
  "allowPublicClient": null,
  "appId": "<bot-id>",
  "appRoles": [],
  "oauth2AllowUrlPathMatching": false,
  "createdDateTime": "2022-12-26T19:34:03Z",
  "description": null,
  "certification": null,
  "disabledByMicrosoftStatus": null,
  "groupMembershipClaims": null,
  "identifierUris": [
    "api://botid-<bot-id>"
  ],
  "informationalUrls": {
    "termsOfService": null,
    "support": null,
    "privacy": null,
    "marketing": null
  },
  "keyCredentials": [],
  "knownClientApplications": [],
  "logoUrl": null,
  "logoutUrl": null,
  "name": "RamLabBot",
  "notes": null,
  "oauth2AllowIdTokenImplicitFlow": true,
  "oauth2AllowImplicitFlow": true,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "read",
      "adminConsentDisplayName": "read",
      "id": "<removed>",
      "isEnabled": true,
      "lang": null,
      "origin": "Application",
      "type": "User",
      "userConsentDescription": "read",
      "userConsentDisplayName": "read",
      "value": "access_as_user"
    }
  ],
  "oauth2RequirePostResponse": false,
  "optionalClaims": null,
  "orgRestrictions": [],
  "parentalControlSettings": {
    "countriesBlockedForMinors": [],
    "legalAgeGroupRule": "Allow"
  },
  "passwordCredentials": [
    {
      "customKeyIdentifier": null,
      "endDate": "2023-06-26T18:36:40.568Z",
      "keyId": "<removed>",
      "startDate": "2022-12-26T19:36:40.568Z",
      "value": null,
      "createdOn": "2022-12-26T19:36:42.9308175Z",
      "hint": "<removed>",
      "displayName": "Password uploaded on Mon Dec 26 2022"
    },
    {
      "customKeyIdentifier": null,
      "endDate": "2027-12-26T00:00:00Z",
      "keyId": "<removed>",
      "startDate": "2022-12-26T19:34:04.4670407Z",
      "value": null,
      "createdOn": "2022-12-26T19:34:04.4730402Z",
      "hint": "<removed>",
      "displayName": null
    }
  ],
  "preAuthorizedApplications": [
    {
      "appId": "5e3ce6c0-2b1f-4285-8d4b-75ee78787346",
      "permissionIds": [
        "<removed>"
      ]
    },
    {
      "appId": "1fec8e78-bce4-4aaf-ab1b-5451cc387264",
      "permissionIds": [
        "<removed>"
      ]
    }
  ],
  "publisherDomain": "microsoft.onmicrosoft.com",
  "replyUrlsWithType": [
    {
      "url": "https://token.botframework.com/.auth/web/redirect",
      "type": "Web"
    }
  ],
  "requiredResourceAccess": [
    {
      "resourceAppId": "00000003-0000-0000-c000-000000000000",
      "resourceAccess": [
        {
          "id": "14dad69e-099b-42c9-810b-d002981feec1",
          "type": "Scope"
        },
        {
          "id": "b89f9189-71a5-4e70-b041-9887f0bc7e4a",
          "type": "Scope"
        },
        {
          "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
          "type": "Scope"
        },
        {
          "id": "b340eb25-3456-403f-be2f-af7a0d370277",
          "type": "Scope"
        },
        {
          "id": "06da0dbc-49e2-44d2-8312-53f166ab848a",
          "type": "Scope"
        },
        {
          "id": "ff74d97f-43af-4b68-9f2a-b77ee6968c5d",
          "type": "Scope"
        },
        {
          "id": "37f7f235-527c-4136-accd-4a02d197296e",
          "type": "Scope"
        },
        {
          "id": "ba47897c-39ec-4d83-8086-ee8256fa737d",
          "type": "Scope"
        },
        {
          "id": "df021288-bdef-4463-88db-98f22de89214",
          "type": "Role"
        }
      ]
    }
  ],
  "samlMetadataUrl": null,
  "signInUrl": null,
  "signInAudience": "AzureADandPersonalMicrosoftAccount",
  "tags": [],
  "tokenEncryptionKeyId": null
}

  ```
</details>

**Comment by ramfattah** [comment]
Asking additional questions:
1. What operating system are you using? 
2. What version of Teams are you using? 
    <img src="https://user-images.githubusercontent.com/38049078/216707273-2f13b7f8-aa8e-4411-b974-7c707e55fa6e.png" width="500"/>

**Comment by thashu0424** [comment]
OS-Windows 
Version- 1.6.00.376

**Comment by ramfattah** [comment]
Hey @thashu0424, 

To clarify: are you referring to the teams manifest or azure app registration manifest?

**Comment by ramfattah** [comment]
This is the following Teams manifest.json I used to sideload the bot app to Teams:
```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.14/MicrosoftTeams.schema.json",
  "manifestVersion": "1.14",
  "version": "1.0.0",
  "id": "<<YOUR-MICROSOFT-APP-ID>>",
  "packageName": "com.microsoft.teams.samples",
  "developer": {
    "name": "Microsoft",
    "websiteUrl": "https://example.azurewebsites.net",
    "privacyUrl": "https://example.azurewebsites.net/privacy",
    "termsOfUseUrl": "https://example.azurewebsites.net/termsofuse"
  },
  "icons": {
    "color": "icon-color.png",
    "outline": "icon-outline.png"
  },
  "name": {
    "short": "Team Auth Module",
    "full": "Simple Team Auth Module"
  },
  "description": {
    "short": "Test Team Auth Module Scenario",
    "full": "Simple Team Auth Module Scenario Test"
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "<<YOUR-MICROSOFT-APP-ID>>",
      "scopes": [
        "personal"
      ],
      "isNotificationOnly": false,
      "supportsCalling": false,
      "supportsVideo": false,
      "supportsFiles": false
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "token.botframework.com",
    "*.ngrok.io"
  ]
}
```

**Comment by ramfattah** [comment]
Hey @thashu0424, 

* To verify this behavior, are you able to provide steps to consistently reproduce this issue? 
* Are you using multiple Teams clients at the same time? (Example: Teams web and desktop clients)
* What is the bot app identity([reference](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#:~:text=As%20a%20user,multi%2Dtenant%20app.))?
    * Example: `multi-tenant`, `single-tenant` or `user-assigned managed identity`?
