### ISSUE TITLE
Document the right way to pass new contextual values to the middle of a waterfall step

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#660]
Here's what I'm trying to accomplish - 

I have a luis intent that triggers a waterfall dialog. While I’m in the waterfall dialog, I’d like to continue to pick up new luis entities. The way to pass that into the waterfall seems to be through dc.continue() but that does not take any args.

This also applies to the case when you get a card interaction based input that you need to be able to plumb through to a waterfall step. 

Need docs/ sample/ guidance on how to accomplish this.

**Comment by JonathanFingold** [comment]
If there is a way to do this that is easier than just writing a custom, non-waterfall dialog, tell us how, and the doc team will write an article around it.

**Comment by yochay** [comment]
Dup of #620
