### ISSUE TITLE
SSO not working properly in skill using sample 82.skills-sso-cloudadapter

### ISSUE THREAD

**Issue by ramfattah** [microsoft/botbuilder-dotnet#6615]
## Environment
* Operating System: **Windows 11**
* Bot channels: **WebChat, Emulator**
* Bot Framework dotnet SDK version: **4.19.3**

## Describe the bug
When using the sample [82.skills-sso-cloudadapter](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/82.skills-sso-cloudadapter) from the Bot Builder .NET SDK, the Single Sign-On (SSO) functionality is not working as expected for the skill bot. Users are required to sign in to each skill bot separately, instead of just signing in once to the root bot.

![image](https://user-images.githubusercontent.com/38049078/230225977-398c2ea2-e720-46a2-83fa-de9399ed06ee.png)

## To Reproduce
1. Set up two Azure bots, one as a root bot and the other as a skill bot.
2. Implement Single Sign-On (SSO) in both the root bot and the skill bot.
3. Use sample [82.skills-sso-cloudadapter](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/82.skills-sso-cloudadapter) from the [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) repository to test the skill bot's SSO functionality.
4. Observe that the user is required to sign in to each skill bot separately, instead of just signing in once to the root bot.

## Expected behavior
The SSO feature should enable users to sign in to the root bot, and not require signing in to each skill bot individually.

Please let me know if you have any questions.
Thanks.

**Comment by ramfattah** [comment]
Hey @ceciliaavila 

I was able to reproduce the SSO issue with the sample [82.skills-sso-cloudadapter](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/82.skills-sso-cloudadapter) for the skill bot. 
Assigning it to you for now. 

Let me know if you need any more info or if there's anything I can help with. 
Thanks.

**Comment by erquirogasw** [comment]
Hi @ramfattah, we are trying to reproduce the issue. We'll let you know if we have any doubts. Thanks!

**Comment by ramfattah** [comment]
Hi @erquirogasw, 

Looks like customer may found the root cause for this issue.


As discussed in [Add single sign-on to a bot - Bot Service | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fbot-service%2Fbot-builder-authentication-sso%3Fview%3Dazure-bot-service-4.0%26tabs%3Deml%23additional-information&data=05%7C01%7Cv-fattahram%40microsoft.com%7C2105ba8d7bfa4da2050208db3659eaf7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638163532135172981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a0GovgbGA9nHhDL0bnk7VgdMG0LlU%2B7GFU7MWh%2FVw4A%3D&reserved=0), the  [TokenExchangeSkillHandler.cs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotBuilder-Samples%2Fblob%2Fmaster%2Fexperimental%2Fsso-with-skills%2FRootBot%2FTokenExchangeSkillHandler.cs&data=05%7C01%7Cv-fattahram%40microsoft.com%7C2105ba8d7bfa4da2050208db3659eaf7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638163532135329618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U1p8gCU0I%2FqAMle6g%2BRlZuQpy2lizYWFFzzrf8zCC1E%3D&reserved=0) intercepts incoming Oauth cards and sends the token directly to skill without the intervention of user.

The problem customer found was in [InterceptOAuthCardsAsync()](https://github.com/microsoft/BotBuilder-Samples/blob/1b180f025d2c233fe496ce2bf2dcd6030cc153a6/samples/csharp_dotnetcore/82.skills-sso-cloudadapter/RootBot/TokenExchangeSkillHandler.cs#L87):

```cs
var targetSkill = GetCallingSkill(claimsIdentity);

if (targetSkill == null)
{
    return false;
}
private BotFrameworkSkill GetCallingSkill(ClaimsIdentity claimsIdentity)
{
    var botAppIdClaim = claimsIdentity.Claims?.FirstOrDefault(claim => claim.Type == AuthenticationConstants.AppIdClaim);

    var appId = botAppIdClaim?.Value;
    if (string.IsNullOrWhiteSpace(appId))
    {
        return null;
    }

    return _skillsConfig.Skills.Values.FirstOrDefault(s => string.Equals(s.AppId, appId, StringComparison.OrdinalIgnoreCase));
}
```

`InterceptOAuthCardsAsync` was returning false always as targetSkill returned null.

Checking the line:
```cs
var botAppIdClaim = claimsIdentity.Claims?.FirstOrDefault(claim => claim.Type == AuthenticationConstants.AppIdClaim);
var appId = botAppIdClaim?.Value;
```

`botAppIdClaim` was returned as null as the Claims did not include AppIdClaim (appid) claim.

Instead it returns azp claim which is documented as a replacement of appid in v2.0 tokens - [Microsoft identity platform access tokens - Microsoft Entra | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fdevelop%2Faccess-tokens%23payload-claims&data=05%7C01%7Cv-fattahram%40microsoft.com%7C2105ba8d7bfa4da2050208db3659eaf7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638163532135329618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JWNtdJg%2BlHHDvviYx7rZmqTYf52wXK%2FsEF0ZnmpnAQM%3D&reserved=0).

Changing the claim type to `AuthenticationConstants.AuthorizedParty` fixed the issue for customer. However it is important to configure the step 12 as described in [Add single sign-on to a bot - Bot Service | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fbot-service%2Fbot-builder-authentication-sso%3Fview%3Dazure-bot-service-4.0%26tabs%3Deml%23create-the-azure-ad-identity-for-skillbot&data=05%7C01%7Cv-fattahram%40microsoft.com%7C2105ba8d7bfa4da2050208db3659eaf7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638163532135329618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b6i3%2Fimt8pwxb1%2FRGVsBvHdldc0XQyN7C3LsQkd%2B8oo%3D&reserved=0) for this to work.

**Comment by erquirogasw** [comment]
Okay, thanks.
We were testing with resources that we already had configured and working and we couldn't reproduce the issue.
