### ISSUE TITLE
Inconsistent behaviour for TextPrompt on different platforms.

### ISSUE THREAD

**Issue by Deon-v** [microsoft/botbuilder-dotnet#6617]
## Version
What package version of the SDK are you using.
Microsoft.Bot.Builder.Dialogs Version="4.19.3"
Microsoft.Bot.Builder.Integration.AspNet.Core Version="4.19.3"

## Describe the bug
We have a bot that was built .net core 3.1, and have recently upgraded to .net 6.0.
With the upgrade we bumped the package version from 4.14.1 to the latest.
The app is currently in UAT.
And the .net core version is still in Production.
We have some waterfall dialogs that user textPrompts in their steps.
When the user replies to the text prompt in the windows client the response is never sent to the server.
However when doing this from an Android client the message works correctly.
We did notice that if you click on a previous button in the chat window the text from the button is recognised and sent to the server.
This issue persists through out the dialogs and is not just for the one dialog.
Everything works fine in production.

I also tested this using the Emulator and it works as expected.

I added some trace messages to the api controller to log each time a message is sent to the api from the bot, and this aligns with the described issue.

## Expected behavior
We expect text prompts to allow user to ty
pe text into the chat and reply to the bots question.

[DialogExample.txt](https://github.com/microsoft/botframework-sdk/files/11168160/DialogExample.txt)

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by anishprasad01** [comment]
Just to make it quicker while I reproduce, did you use any specific sample as a starting point?

**Comment by Deon-v** [comment]
This was originally written almost 4 years ago. So it's long past a basic sample.  

But the example I attached is one of the current waterfall dialogs, with that users need to complete go gain access to the rest if the bot

**Comment by anishprasad01** [comment]
Oh yes, I see it. I will attempt to reproduce.

**Comment by anishprasad01** [comment]
Just using some basic TextPrompts on 4.19.3 and .NET 6, I am not seeing this issue. This problem occurs no matter the content or purpose of the specific dialog? Once the hypothetical user gets past the OTP dialog and interacts with the bot through another waterfall dialog, this will happen again?

**Comment by Deon-v** [comment]
Yes, we passed the OTP dialog from a mobile client and then tried to continue on the windows client and the same happened on a different dialog.

The user has let me know, that after a day of them not touching the bot the dialogs seemed to start working again on the windows client.

So i'm guessing there is some issue on teams for windows when the underlying SDK version changes.

**Comment by anishprasad01** [comment]
Thanks for confirming.

It seems at this point that the issue in question does not seem to be within the Bot Builder SDK. Given that, I am going to go ahead and close this issue. If this problem should pop up again, I would recommend first raising it with Teams, as it seems the issues may be specific to their clients.

Of course, if you do encounter a bug or feature request in the Bot SDK in the future, please feel free to open a new issue, We're happy to help.
