### ISSUE TITLE
QnA and LUIS Emulator inspectors do not work if called from within the bot logic (only work as middleware)

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#662]
At the moment, QnA and LUIS inspectors in the Bot Framework V4 Emulator do not show any trace activities if using the QnA and LUIS recognizers in the bot logic. The trace activities only show up when using the LUIS and or QnA middleware.

**Comment by vishwacsena** [comment]
Since the middleware options are gone, this is critical to be addressed in the next iteration.

**Comment by stevengum** [comment]
Fixed via #788 for QnA Maker and #775 for LUIS
