### ISSUE TITLE
TIMEX recognizer cannot be used used to just capture date or time

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#663]
It seems impossible to use the TIMEX recognizer to just look for either date or time. It would be good to add support for being able to do just time or date resolutions.

**Comment by johnataylor** [comment]
On the current prompt model the idea is the developer writes a custom validator. In this validator the decision as to whether the text matched can be overridden. The datetime prompt calls the validator with the TIMEX. Using the TIMEX library it is easy to determine the detailed type(s) held in the TIMEX.

This might be a great thing to provide a sample of. If you agree please open an issue on the samples.
