### ISSUE TITLE
Refresh Adaptive card not posting data back to server in ms teams channel 

### ISSUE THREAD

**Issue by mukeshkushwaha06** [microsoft/botbuilder-dotnet#6646]
## Version
Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.15.2"
Adaptive card version : 1.5

## Describe the bug
 We have created teams chat bot  using universal adaptive card . We have multiples cards to complete our  product journey.
  When we invoke the bot in teams channel, card data is not posted back to server using "Action.Execute" . 
  Our product journey is working fine in one to one and group chat. we do not use any specific code for groups or channel.
  Previously it was working fine in one to one , group and channel. 
 

## To Reproduce
1. Go to  Microsoft teams channel 
2. Add chat bot to channel
3. Invoke chat bot , adaptive card will appear 
4. Type data in input textbox
5. click on next
6. inspect in function "OnInvokeActivityAsync"  and observe that data received in the card data field is empty.
  
## Expected behavior
   Adaptive card data should be posted back to server 

## Screenshots
![image](https://github.com/microsoft/botbuilder-dotnet/assets/136333905/63e8f181-8702-452b-9a15-e58a1beff477)

##  Adaptive card schema
{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.5","body":[{"type":"TextBlock","size":"Large","text":"${WorkspaceSelection_Organizer}","wrap":true},{"type":"RichTextBlock","inlines":[{"type":"TextRun","size":"medium","text":"${WorkspaceSelection_Title}"},{"type":"TextRun","size":"medium","text":"${Building}, ","weight":"bolder"},{"type":"TextRun","size":"medium","text":"${LocationName}, ","weight":"bolder"},{"type":"TextRun","size":"medium","text":"${Country}.","weight":"bolder"}]},{"type":"TextBlock","size":"medium","weight":"Bolder","text":"${SelectFloorLabel}"},{"type":"Input.ChoiceSet","id":"SelectedFloor","style":"compact","isMultiSelect":false,"choices":"${Floors}","value":"${SelectedFloor}","spacing":"default"},{"type":"TextBlock","size":"medium","weight":"Bolder","text":"${WorkspaceSelectionMessage}"},{"type":"Input.ChoiceSet","id":"SelectedWSType","isMultiSelect":false,"spacing":"default","style":"expanded","choices":"${wsTypes}","value":"${SelectedWSType}","$when":"${count(wsTypes) > 1}"},{"type":"TextBlock","wrap":true,"text":"${SelectedWSType}","$when":"${equals(count(wsTypes), 1)}"},{"type":"Input.Text","id":"SelectedWSType","isVisible":false,"value":"${SelectedWSType}","$when":"${equals(count(wsTypes), 1)}"},{"type":"Input.Toggle","id":"IsAttributeSelected","isVisible":false,"title":"${WorkspaceSelection_Attributes}"},{"type":"TextBlock","size":"medium","weight":"Bolder","text":"${WorkspaceSelection_Attendees}"},{"type":"Input.Number","id":"AttendeeCount","min":1,"max":100,"isRequired":true,"errorMessage":"${AttendeeErrorMessage}","value":"${TeamMemberCount}"}],"actions":[{"verb":"cancelledSearch","title":"${CancelledSearchLabel}","type":"Action.Execute"},{"type":"Action.Execute","verb":"workspaceSelection","title":"${Next}","data":{"TimesData":"${TimesData}","Building":"${Building}","LocationName":"${LocationName}","Floor":"${Floor}","Country":"${Country}","MasterWSType":"${MasterWSType}","WorkspaceSelectionData":"${WorkspaceSelectionData}","AttendeeSelectionData":"${AttendeeSelectionData}","RoomSelectionData":"${RoomSelectionData}","InitialTimestamp":"${InitialTimestamp}"}}]}

**Comment by mukeshkushwaha06** [comment]
> @mukeshkushwaha06,
> 
> * Have there been any code, version, or other changes between when the bot worked and when it stopped working?
        No change since last two months. 
> * Has your Teams channel changed in any way?
       We have tried with multiple channel (also tried with new channel)
> * Are there any error messages seen when debugging or in Application Insights?
      We are getting Nullpointerexception exception for card data because card data is not posted back to server

**Comment by anishprasad01** [comment]
So you are attempting to process the response from an Adaptive Card and are encountering a null pointer exception. I will attempt to reproduce the issue. In the meantime, please provide the text of the exception itself. That can sometimes help narrow down exactly where the null value is appearing.

**Comment by mukeshkushwaha06** [comment]
> So you are attempting to process the response from an Adaptive Card and are encountering a null pointer exception. I will attempt to reproduce the issue. In the meantime, please provide the text of the exception itself. That can sometimes help narrow down exactly where the null value is appearing.

**Comment by mukeshkushwaha06** [comment]
@anishprasad01  Please refer the sample code link 
  https://github.com/mukeshkushwaha06/SampleBot.git

**Comment by mukeshkushwaha06** [comment]
> So you are attempting to process the response from an Adaptive Card and are encountering a null pointer exception. I will attempt to reproduce the issue. In the meantime, please provide the text of the exception itself. That can sometimes help narrow down exactly where the null value is appearing.

@anishprasad01  We are getting null pointer exception because card data is not posted back to server

**Comment by anishprasad01** [comment]
@mukeshkushwaha06 

I can confirm the behavior you are describing. However, I do not see any reason why the bot itself might be responsible for this issue, especially if there have been no code changes. The bot does not handle sending back data from Teams, the Teams app does.

May I suggest you raise this issue with Teams support?

**Comment by anishprasad01** [comment]
This issue appears to be a Teams error. If it is confirmed that this is a bug in the bot, please feel free to reopen this issue.
