### ISSUE TITLE
Let the configuration keys be configurable

### ISSUE THREAD

**Issue by vbossica** [microsoft/botbuilder-dotnet#6669]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Configuration keys are hard-coded and are an issue when, for example, the password is stored in a Key Vault, when its name is not MicrosoftAppPassword

**Describe the solution you'd like**

Change the ConfigurationServiceClientCredentialFactory to make the configuration keys configurable.

**Describe alternatives you've considered**

Extending the class wouldn't work and it would be advantageous to keep the logic of this class intact.

**Comment by anishprasad01** [comment]
Hi @vbossica,

Thank you for the suggestion. At this time, we are not planning to make this change in the SDK. However, you are of course completely free to modify and/or extend the framework as you see fit for your implementation.
