### ISSUE TITLE
Do not bump Moq to >=4.20.0

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#6680]
FYI @tracyboehrer, @johnataylor, @LeeParrishMSFT    there's a security issue with the inclusion of an email-gathering .dll that was added to moq v4.20.0. Do not bump Moq to any version greater than or equal to 4.20.0.

The .dll runs at build-time via Moq's code analysis tool. (See below and linked issues for more details)

https://github.com/moq/moq/issues/1372

![image](https://github.com/microsoft/teams-ai/assets/14935595/504e5d6c-c625-4b44-bddc-1371d33dcf16)

Moq's maintainer is inviting discussion in https://github.com/moq/moq/issues/1374

**Comment by tracyboehrer** [comment]
@ceciliaavila Commenting for your team's visibility.
