### ISSUE TITLE
The type initializer for 'AdaptiveCardsTemplateLexer' threw an exception.

### ISSUE THREAD

**Issue by jagdish-kumawat** [microsoft/botbuilder-dotnet#6682]
On upgrading the Bot Builder SDK to 4.20.x, getting this error on Adaptive Card Templating - 
The type initializer for 'AdaptiveCardsTemplateLexer' threw an exception.

This works fine on 4.19.x. I am using C#.

**Comment by ramfattah** [comment]
Thanks @jagdish-kumawat, i'm looking into this issue.

**Comment by ramfattah** [comment]
@jagdish-kumawat, what's `AdaptiveCardsTemplateLexer`? It doesnt appear to be related to Bot Framework SDK

**Comment by ramfattah** [comment]
I found similar issue in [AdaptiveCards](https://github.com/microsoft/AdaptiveCards/issues/8615) repository. 

@jagdish-kumawat, if you're using the Adaptive Card SDK or encountering a problem related to Adaptive Card JSON templates, could you please report the issue in the appropriate [AdaptiveCards GitHub repository](https://github.com/microsoft/AdaptiveCards/issues/8615)?
