### ISSUE TITLE
Intermittent AADSTS700016 error with 4.20 and above

### ISSUE THREAD

**Issue by justin-mellor** [microsoft/botbuilder-dotnet#6691]
## Version
4.21.0

## Describe the bug
After upgrading from 4.19.3 to 4.21.0 we are getting intermittent errors
System.AggregateException : Failed to acquire token for client credentials. (AADSTS700016: Application with identifier '4bb039d2-dadb-496c-89b6-77fbe143acd7' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: bd080058-54ab-4ae4-90b5-6b862c9d0e01
Correlation ID: caf3bde3-1dcb-4358-bcb1-b2ad048a7b19
Timestamp: 2023-09-20 23:02:10Z)
Microsoft.Identity.Client.MsalServiceException : AADSTS700016: Application with identifier '4bb039d2-dadb-496c-89b6-77fbe143acd7' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: bd080058-54ab-4ae4-90b5-6b862c9d0e01
Correlation ID: caf3bde3-1dcb-4358-bcb1-b2ad048a7b19
Timestamp: 2023-09-20 23:02:10Z

This is occurring in the middle of a conversation, so the bot has definitely managed to send a message before so the App must be registered correctly.

In 4.20 the sdk changed to use MSAL so I am assuming this is related to that in some way.

## Expected behavior
I expect the bot to be able to send messages all the time.

## Additional context
Stack trace is
Microsoft.Bot.Connector.Authentication.Retry+<Run>d__0`1.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Connector.Authentication.MsalAppCredentials+<Microsoft-Bot-Connector-Authentication-IAuthenticator-GetTokenAsync>d__11.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Connector.Authentication.AppCredentials+<GetTokenAsync>d__34.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Connector.Authentication.AppCredentials+<ProcessHttpRequestAsync>d__33.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Connector.Conversations+<ReplyToActivityWithHttpMessagesAsync>d__10.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Connector.ConversationsExtensions+<ReplyToActivityAsync>d__17.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Builder.CloudAdapterBase+<SendActivitiesAsync>d__9.MoveNext
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at Microsoft.Bot.Builder.TurnContext+<>c__DisplayClass31_0+<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext

**Comment by justin-mellor** [comment]
I have been doing some research, and I think the problem is because we are using MicrosoftAppCredentials. The problem is that this creates a new ConfidentialClientApplication each time, and so should be using .WithCacheOptions(CacheOptions.EnableSharedCacheOptions)

This is according to https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/token-cache-serialization?tabs=aspnetcore#quick-summary

> If you want to use an in-memory cache and you're only using [AcquireTokenForClient](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenforclientparameterbuilder), either reuse the confidential client application instance and don't add a serializer, or create a new confidential client application and enable the [shared cache option](https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/token-cache-serialization?tabs=aspnet#no-token-cache-serialization).

I have managed to work round it by using MsalAppCredentials and creating the ConfidentialClientApplication myself and enabling the shared cache, but I think the EnableSharedCacheOptions should probably be enabled in the MicrosoftAppCredentials.BuildIAuthenticator() method

**Comment by ramfattah** [comment]
Thanks for the update @justin-mellor, I'm investigating this issue.

**Comment by ramfattah** [comment]
Hi @justin-mellor, 

What is your [bot type](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#:~:text=Emulator%2C%20or%20ngrok.-,App%20type,Support,-User%2Dassigned%20managed)? 
Ex: `MultiTenant`, `SingleTenant`, etc..

![image](https://github.com/microsoft/botbuilder-dotnet/assets/38049078/5bbb7200-0063-4086-bbd0-95aec4c9b7e5)

**Comment by ramfattah** [comment]
Hi @justin-mellor, 

What is your [bot type](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#:~:text=Emulator%2C%20or%20ngrok.-,App%20type,Support,-User%2Dassigned%20managed)? 
Ex: `MultiTenant`, `SingleTenant`, etc..

![image](https://github.com/microsoft/botbuilder-dotnet/assets/38049078/9a32022d-ed2e-4a20-bffc-fd31b114534d)

**Comment by justin-mellor** [comment]
Hi @ramfattah I don't see that screen in Azure. My bot resource is a Web App Bot not an Azure Bot so the Configuration screen doesn't have Bot Type.

**Comment by ramfattah** [comment]
Hi @justin-mellor, 

are you able to provide steps to reproduce or attach minimal reproducible .zip sample?

**Comment by justin-mellor** [comment]
Hi @ramfattah ,

As this is intermittent it is very hard to provide a consistent reproduction. We run a suite of automated tests against our bot, and we get this error in different tests each time. It is reproduceable for is purely because we run enough iterations so that we get an occurrence inside a test run.

**Comment by tracyboehrer** [comment]
The cache correction was made in 4.21.2

**Comment by justin-mellor** [comment]
> The cache correction was made in 4.21.2

Hi @tracyboehrer 
This seems to solve it.
Thanks
