### ISSUE TITLE
Send email from bot personal chat to a valid email

### ISSUE THREAD

**Issue by jsquire** [microsoft/botbuilder-dotnet#6700]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#39224>](https://github.com/Azure/azure-sdk-for-net/issues/39224).

### Library name and version

Azure Bot Service

### Query/Question

We are working on a bot framework application.

We want to implement a feature where users can send emails through their teams bot application.

From should be the teams user email address and to will be a valid email address we set.

Once the user confirms, email should be sent to the valid email address from bot.

**Comment by tracyboehrer** [comment]
This is outside the scope of the bot SDK.  Existing support for sending emails already exists in external packages.
