### ISSUE TITLE
Extensibility for Teams AI - ability to add to User Agent for Teams AI telemetry

### ISSUE THREAD

**Issue by corinagum** [microsoft/botbuilder-dotnet#6701]
Related to https://github.com/microsoft/botbuilder-js/issues/4552 

Request is from https://github.com/microsoft/teams-ai team

[ConnectorFactoryImpl](https://github.com/microsoft/botbuilder-dotnet/blob/617394d6ff834b0804cceabff2ed9d6e06342cd4/libraries/Microsoft.Bot.Connector/Authentication/ConnectorFactoryImpl.cs#L41)

We are hoping to have the ability to add Teams AI information for SMBA to parse for telemetry.

Since Teams AI is JavaScript first, we request this would be done in the JS SDK first with fast follow for C# and Python

**Comment by tracyboehrer** [comment]
This should probably be done as JS allows it, via ConfigurationBotFrameworkAuthentication. accepting a ConnectorClientOptions, on which a UserAgent value can be included.  This value is added on to our SDK UserAgent value.  For example: "TeamsAI/1.0" results in "botframework-connector/4.0.0 ms-rest-js/2.7.0 Node/v16.20.2 OS/(x64-Windows_NT-10.0.22621) TeamsAI/1.0".

There is no way to enforce this though.  That is, a customer could simply remove/change this in the bot.

Could also possible allow for the ConnectorClientOptions to read from Config, but it would need to be added to JS and Python.

**Comment by tracyboehrer** [comment]
Teams is going to subclass CloudAdapter and HttpClientFactory in order to provide appropriate requests and response headers.
