### ISSUE TITLE
Using locally built nuget packages with the C# template produces a CS0433 error.

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#672]
**Repo steps**:
1. Sync and build the repo using the Release config.
2. Create a new project using the Bot Builder Echo Bot template for v4.
3. Remove the 4.0.1-preview nuget packages from the project references.
4. Go to NuGet Package Manager settings, general options and clear the NuGet package cache.
5. Under Package Sources, add one for your local builds, i.e. …\source\repos\botbuilder-dotnet\outputpackages\.
6. Add the local packages for the ones you removed earlier:
    * Microsoft.Bot.Builder.Core
    * Microsoft.Bot.Builder.Core
    * Microsoft.Bot.Builder.Integration.AspNet.Core
7. Rebuild your project.
8. Note the compiler errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ITurnContext' exists in both 'Microsoft.Bot.Builder.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Bot.Builder, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	BuildIssureRepoSteps	C:\Users\v-jofing\source\repos\BuildIssureRepoSteps\BuildIssureRepoSteps\EchoBot.cs	19	Active
Error	CS0433	The type 'IBot' exists in both 'Microsoft.Bot.Builder.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Bot.Builder, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	BuildIssureRepoSteps	C:\Users\v-jofing\source\repos\BuildIssureRepoSteps\BuildIssureRepoSteps\EchoBot.cs	9	Active

**Comment by drub0y** [comment]
Sooo, I pulled `master` and it looks like the changes to eliminate the separate assembly for `Microsoft.Bot.Builder.Core` landed and now I only end up with `Microsoft.Bot.Builder` with everything in there. Therefore we need to make sure we remove the reference to the `Microsoft.Bot.Builder.Core` package from the projects, otherwise it's going to pull that down off NuGet still and clash with `Microsoft.Bot.Builder`.


98.38% sure that's what's happening.

**Comment by JonathanFingold** [comment]
Yes Core and Core.Extensions seem to have gone away as packages, and were just phantoms on my machine. Closing.

**Comment by JonathanFingold** [comment]
It would be nice if the build did an initial clean up the outputpackages directory though. :|

**Comment by drub0y** [comment]
💯 

I totally agree that we should add something to the Clean target to clean up `outputpackages`.
