### ISSUE TITLE
.Net 8

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#6741]
1) Test using .Net 8
2) Scope of changes

**Comment by sambathrajv** [comment]
Hi, Do you know when the projects will be upgraded to .Net 8?  Any ETA?

**Comment by gioce90** [comment]
Hi, there is any news?

**Comment by ahmed-dstny** [comment]
Hello everyone. These issues and PR are still open.. Have the .NET 8 templates been released elsewhere @ceciliaavila ?

**Comment by tracyboehrer** [comment]
@ahmed-dstny There are some changes pending.

**Comment by ahmed-dstny** [comment]
Thanks @tracyboehrer. Do you mean the warnings about the Microsoft.Identity packages?

**Comment by tracyboehrer** [comment]
@ahmed-dstny No.  There was a separate PR to update Microsoft.Identity.Client to 4.60.3 to resolve those warnings.  That has already been merged.

**Comment by ahmed-dstny** [comment]
@tracyboehrer please see my PR that merges main back into that one by @sw-joelmut:
https://github.com/microsoft/botbuilder-dotnet/pull/6788
