### ISSUE TITLE
Microsoft.Bot.Builder.AI.QnA library -> migration path from QnAMakerRecognizer to Custom Question Answering?

### ISSUE THREAD

**Issue by omon77** [microsoft/botbuilder-dotnet#6750]
I am not sure if there is a gap in migration guide or the functionality hasn't been worked on yet, but I am trying to figure out what is the path forward for the QnAMakerRecognizer and how to port code to leverage Custom Question Answering?

[Documentation](https://learn.microsoft.com/en-us/azure/ai-services/language-service/question-answering/how-to/migrate-qnamaker-to-question-answering#migration-phases) states:

> Bot SDK: For bots to use custom question answering, use the [Bot.Builder.AI.QnA](https://www.nuget.org/packages/Microsoft.Bot.Builder.AI.QnA/) SDK – We recommend customers to continue to use this for their Bot integrations.

Here is the screenshot:
![image](https://github.com/microsoft/botbuilder-dotnet/assets/37841453/0a866a6c-a13a-4d9a-a017-3598a4f24511)

Are there plans on updating the library, specifically the QnAMakerRecognizer, as it is returning instance of QnAMaker...

https://github.com/microsoft/botbuilder-dotnet/blob/07ed900bb7326e85b8a277a10dcf78db0806ab2d/libraries/Microsoft.Bot.Builder.AI.QnA/QnAMakerRecognizer.cs#L303

With the upcoming retirement of QnAMaker, it seems that the whole QnAMaker* segment of the SDK needs to be ported over to leverage Question Answering and Custom Question Answering.

**Comment by tracyboehrer** [comment]
This sample demonstrates CQA: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/12.customQABot
