### ISSUE TITLE
Dialog State Storage Issue in Bot Builder Composer: Impact on Automation and Conversations

### ISSUE THREAD

**Issue by NeethithevanR** [microsoft/botbuilder-dotnet#6751]
I'm using Bot Builder Composer (version 2.1.2) to develop my chat application, and I'm utilizing the .NET versions (netcoreapp3.1/net6.0). During bot automation testing, I encounter occasional issues where dialog states are not stored properly. Consequently, I sometimes receive previous dialogues and trigger different flows. This issue not only affects automation but also occurs during regular conversations.

**Comment by dmvtech** [comment]
Are you still experiencing this problem?
