### ISSUE TITLE
Wrong results when using OAuthPrompt from group or channel

### ISSUE THREAD

**Issue by atmoraes1** [microsoft/botbuilder-dotnet#6765]
When using OAuth2 via OAuthPrompt the user authentication flow does not work as expected. It seems some states are being shared between the turns that prevent the authentication to complete.

As race conditions might happen the scenarios may vary. The bot was built based on the sample.

Is that a bug or the OAuthPrompt is expected to only work with private chats? If that's the case how should one proceed to authenticate a conversation started from within a group or channel (Microsoft Teams).

**Comment by dmvtech** [comment]
Are you still experiencing this problem?
