### ISSUE TITLE
Migrate to System.Text.Json - remove newtonsoft

### ISSUE THREAD

**Issue by HSven1611** [microsoft/botbuilder-dotnet#6767]
As System.Text.Json is becoming more and more adapted throughout the .Net ecosystem I was wondering if you guys plan to remove Newtonsoft from the Bot Framework.

**Is your feature request related to a problem? Please describe.**
At the moment we are Integrating a bot into a solution at our customer as a web service based on .net 8 and we stumble upon multiple issues with the bot framework being dependent on newtonsoft. For example it is not possible to decide on controller level which serializier you need to use and as some other Microsoft libraries have already been updated to STJ we start having our model classes decorated with both property name attributes. Also the bot framework data models are not working when trying to deserialize with system.text.json as they seem to rely on newtonsoft attributes too. This leads to us having to use newtonsoft even in some Azure functions where we try to avoid including this.

**Describe the solution you'd like**
We'd love having newtonsoft being removed from bot framework and it's samples.

**Describe alternatives you've considered**
As mentioned, atm we have to implement and maintain certain functionalities twice. Once for system.text.json and once for newtonsoft.

**Comment by tracyboehrer** [comment]
@HSven1611 This would be desirable for us.  However, this in all likelihood will not happen in the v4 SDK.

**Comment by HSven1611** [comment]
"completed" in this case means it went from "in all likelihood " to " won't do" I guess, hmm? :-(
