### ISSUE TITLE
CosmosDBKeyEscape.TruncateKeyIfNeeded return different value after compiled 

### ISSUE THREAD

**Issue by yungfu** [microsoft/botbuilder-dotnet#6768]
## Version
4.22.2

## Describe the bug
If storage key length is larger than 255, compile program, and run it again, this method will return different value. I think this method should return same value each time.

**Comment by ceciliaavila** [comment]
Hi everyone, we reproduced the issue and found that the _[TruncateKeyIfNeeded](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/CosmosDBKeyEscape.cs#L120)_ method uses .NET's _[String.GetHashCode](https://learn.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=net-8.0&redirectedfrom=MSDN#System_Object_GetHashCode)_ method which, according to the documentation, returns the same hash code for the same string during the application execution. A different hash code could be returned if the application is rerun.

@tracyboehrer, should we replace the _GetHashCode_ method with a custom implementation to guarantee the same hash code on every run?
