### ISSUE TITLE
Updating Package Microsoft.Bot.Builder.Integration.Aspt.Core from 4.21.1 to 4.22.4 no longer finds ITeamsCommandHandler

### ISSUE THREAD

**Issue by johnyjp** [microsoft/botbuilder-dotnet#6797]
## Version
What package version of the SDK are you using.
4.22.4

## Describe the bug
Give a clear and concise description of what the bug is.
Updating Package Microsoft.Bot.Builder.Integration.Aspt.Core from 4.21.1 to 4.22.4 no longer finds ITeamsCommandHandler. Suggestion is to add a package reference to Microsoft.Bot.Builder but that does not resolve the issue.

## To Reproduce

Open example command bot project from File -> New Project MSTeams App -> CommandBot
Build - Compiles fine.   Nuget Packages -> update to 4.22 ->  Build fails with 

error CS0012: The type 'ITurnContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bot.Builder, Version=4.21.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

.net 8.0 project, No additional code other than that provided by the new project wizard.

**Comment by tracyboehrer** [comment]
@johnyjp ITeamsCommandHandler is not a Bot Framework SDK interface.  But the real problem is the CS0012 error.  Are you using Teams AI SDK and it's using 4.21.1?  Or something else using 4.21.1?

**Comment by mpec** [comment]
We have a similar issue but the error in our case is:
``` The type 'ConversationReference' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bot.Schema, Version=4.21.1.0``` 

We are running `4.22.2` and trying to upgrade to `4.22.4`.

No reference to `4.21.1.0` is present anywhere

**Comment by tracyboehrer** [comment]
@mpec Are you also a Teams app?  That is, have dependencies on any Teams package?

**Comment by mpec** [comment]
@tracyboehrer this is our dependency tree:
![image](https://github.com/microsoft/botbuilder-dotnet/assets/6253549/c0517072-9b48-493d-b1aa-8558aed43493)
So it's an Azure Function that uses AspNetCore integration.

**Comment by tracyboehrer** [comment]
<img width="665" alt="image" src="https://github.com/microsoft/botbuilder-dotnet/assets/1024902/b8f00a45-b528-4b5b-a5d4-3c38b83314c3">

**Comment by mpec** [comment]
I see, so it's an issue with TeamsFx.
How come a minor version update breaks this though?

**Comment by tracyboehrer** [comment]
@mpec All in the mysteries of DotNet package resolution.

**Comment by mpec** [comment]
Thanks for all your help @tracyboehrer, I'll probably delay the upgrade for now. :)

**Comment by tracyboehrer** [comment]
@mpec They will be forced to update at some point.  A good number of changes are dependency updates to address security alerts.  Which they will get tagged for until they do.

**Comment by johnyjp** [comment]
> @johnyjp ITeamsCommandHandler is not a Bot Framework SDK interface. But the real problem is the CS0012 error. Are you using Teams AI SDK and it's using 4.21.1? Or something else using 4.21.1?

Yes, using Teams SDK, cant see a reference to 4.21.1 anywhere.

**Comment by tracyboehrer** [comment]
Closing as this is a general issue with dependency resolution.  No corrective action possible by DotNet BF SDK.
