### ISSUE TITLE
oauth feature does not work without setting up a bot on azure on emulator

### ISSUE THREAD

**Issue by swagatmishra2007** [Microsoft/botbuilder-dotnet#680]
The node sdk has a commit, where if an appid/password is not set for a bot and the oauth feature is invoked on an emulator, then the bot returns a dummy signin url and token. 
This work needs to be ported over from the node sdk , so that we can try out oauth in c# on emulator without requiring a bot

**Comment by cleemullins** [comment]
@swagatmishra2007 Any update on this?

**Comment by daveta** [comment]
@swagatmishra2007 any update?

**Comment by swagatmishra2007** [comment]
sorry for the delay on this. Hoping to get on this tomorrow or early next week.

**Comment by swagatmishra2007** [comment]
assigned to @Jeffders who is working on this.

**Comment by Jeffders** [comment]
This is resolved now. I had added the code that was missing from the v4 SDK already.
