### ISSUE TITLE
Teams periodically fails to send messages

### ISSUE THREAD

**Issue by jamesemann** [microsoft/botbuilder-dotnet#6811]
## Version

Latest

## Describe the bug

Using the teams channel, it is intermittently not calling my endpoint with the user message.

This seems to be a recent issue. I have first noticed it today (26 Jun) , we have previously been widely using teams bots without any reported issues.

This happens with both app-reg backed bots and MSI backed bots.

## To Reproduce

1. Use ngrok to test locally

2. Create an azure bot resource and deploy the bot code, you can just use the echobot example for this.  The functionality of the bot doesn't matter as the problem occurs in the comms between teams->the bot endpoint.

3. In teams, send a set of messages in quick succession, e.g. `1`, `2`, `3`, etc. Ideally these will have different content so you can map them to the requests in ngrok.

📝 After a few messages (I can usually get it to fail within 10 messages) it will fail to send one of the messages.  You can inspect ngrok to see that the endpoint has not been called.

## Expected behavior
It should deliver all messages reliably.

The UX is negatively impacted for the end users, as they are unsure whether the messages are received or not.

## Screenshots

I can share a video of this privately if required.

## Additional context

Please reach out for any additional context needed.

**Comment by dmvtech** [comment]
I am able to reproduce. As this doesn't make it to ngrok, it's not an SDK problem, but Teams. Will attempt to get Teams to investigate.

**Comment by dmvtech** [comment]
I am no longer able to reproduce. There may have been some transient errors on the Teams side yesterday. Are you still able to reproduce?

**Comment by jamesemann** [comment]
Hi @dmvtech - this seems to be working ok now. Thank you for looking into it
