### ISSUE TITLE
The Bot Framework receives an empty activity when sending an attachment from OneDrive through MS Teams on Android

### ISSUE THREAD

**Issue by oneto20** [microsoft/botbuilder-dotnet#6812]
## Version
4.22.7

## Describe the bug
During the testing of an application using the BotFramework SDK, we detected that when sending an attachment from OneDrive through MS Teams Android to bot, it receives an empty activity.

## To Reproduce
1. Send an attachment from OneDrive through MS Teams Android.
2. Check received activity on Bot Framework
3. See error

## Expected behavior
Receive a activity with OneDrive attachment.

## Screenshots
![image](https://github.com/microsoft/botbuilder-dotnet/assets/174832572/edb89f48-d90a-4494-961d-b96731d37918)
MS Teams Android

## Additional context

Activity message
```json
{
  "type": "message",
  "timestamp": "2024-07-05T19:26:58.8963731Z",
  "localTimestamp": "2024-07-05T16:26:58.8963731-03:00",
  "id": "172020...",
  "channelId": "msteams",
  "serviceUrl": "https://smba.trafficmanager.net/amer/",
  "from": {
    "id": "29:1nS-4GF_IkhsI1n...",
    "name": "Desenv",
    "aadObjectId": "c6151835..."
  },
  "conversation": {
    "conversationType": "personal",
    "tenantId": "14f1526...",
    "id": "a:1yaXqIfZMMz..."
  },
  "recipient": {
    "id": "28:24...",
    "name": "VoxBot3"
  },
  "entities": [
    {
      "locale": "pt-BR",
      "country": "BR",
      "platform": "Android",
      "timezone": "America/Sao_Paulo",
      "type": "clientInfo"
    }
  ],
  "channelData": {
    "tenant": {
      "id": "14f1526..."
    }
  },
  "locale": "pt-BR",
  "localTimezone": "America/Sao_Paulo"
}

```

**Comment by tracyboehrer** [comment]
This isn't something Bot Framework controls.  Contact Teams support.  Either the Teams Sample repo, or Teams AI SDK.

**Comment by PGerardi** [comment]
@oneto20 Did you manage to solve the problem?
