### ISSUE TITLE
Bot teams app: After clicking send button, adaptive card showing a message at the bottom saying " 'Something went wrong. Please try again'"

### ISSUE THREAD

**Issue by Amey819** [microsoft/botbuilder-dotnet#6823]
The issue seems to be because of the lower timeout for the messages received from the user through adaptive card input.
Is there a way to increase the timeout of this input message?
image

In the screenshot as you see when we add dates, we run some diagnostics that can take longer than expected and before the results even return we get the error message as shown in the screenshot.

We would request some guidance on this issue.

**Comment by tracyboehrer** [comment]
This is a Teams question.  Reach out on the Teams Samples repo.
