### ISSUE TITLE
TeamsInfo.SendMessageToTeamsChannelAsync relies on old adapter

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#6842]
```
            await ((BotFrameworkAdapter)turnContext.Adapter).CreateConversationAsync(
```

**Comment by tracyboehrer** [comment]
@sw-joelmut This may not be a bug.  Confusing though.  I suspect that method is only called by a bot using the old adapter?

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, there are two _SendMessageToTeamsChannelAsync_ methods, one for each adapter. The only difference is that the one for _BotFrameworkAdapter_ needs the _MicrosoftAppCredentials_ parameter, while the one for _CloudAdapter_ only requires the appId.
![image](https://github.com/user-attachments/assets/ddda42c2-d8ba-45e9-b9a7-f67427e84613)

**Comment by tracyboehrer** [comment]
[like]  Tracy Boehrer reacted to your message:
________________________________

**Comment by ceciliaavila** [comment]
Hi @tracyboehrer, can we close this issue?

**Comment by tracyboehrer** [comment]
[like]  Tracy Boehrer reacted to your message:
________________________________

**Comment by ceciliaavila** [comment]
Closing as there's no issue. There are two methods, one for each adapter.
