### ISSUE TITLE
File upload to server (Azure web app) not working. Getting error "Could not find file"

### ISSUE THREAD

**Issue by Subhadwip** [microsoft/botbuilder-dotnet#6844]
## Bot framework sdk V4

I have a chatbot build with bot framework sdk V4 and hosted on Azure web app. We are using teams channel to interact with the bot. There is a strange issue we are experiencing: Whenever user uploads a file to the bot, we are uploading the file to server (C:\home\site\wwwroot). Now the issue is when we deploy the solution through Azure pipelines, and then when user upload a file to the bot, We are not able to stream the file and upload it to server. Error message "Could not find file 'C:\home\site\wwwroot\xyz.pdf'. But when we manually publish the same code through Visual studio, It works as expected, the file gets uploaded to the server."

## To Reproduce

1. Create an azure pipeline to deploy code to Azure web app.  
2. Run the pipeline.
3. Ping the bot and try to upload a file to bot
4. We get an exception saying that "Could not find file 'C:\home\site\wwwroot\xyz.pdf"
5. But same code works and file gets uploaded to server when we publish it through Visual studio

## Expected behavior

The file should get uploaded to server 

## Additional context

Below is the code to read the attachment from download url and convert it to file stream and upload it to server.

```csharp
//The attachment is of type Microsoft.Bot.Schema
var file = attachment;
  var fileDownload = JObject.FromObject(file.Content).ToObject<FileDownloadInfo>();
  var contentRoot = _config.GetValue<string>(WebHostDefaults.ContentRootKey);
  string filePath = Path.Combine(contentRoot, file.Name);
  var httpClient = _clientFactory.CreateClient();
   var httpResponse = await httpClient.GetAsync(fileDownload.DownloadUrl);
   using (var fileStream = new FileStream(filePath, FileMode.Create, FileAccess.Write, FileShare.None))
    {
            await httpResponse.Content.CopyToAsync(fileStream);
     }
```

**Comment by tracyboehrer** [comment]
None of this has anything to do with Bot Framework directly.  Assuming fileDownLoad.Url points to a valid resource I would expect it to work.  But this is all happening via HttpClient.  Is the webapp setup to require auth?
