### ISSUE TITLE
Starting at version 4.22.3 The PublicKeyToken Is Missing On Assemblies

### ISSUE THREAD

**Issue by clintwar** [microsoft/botbuilder-dotnet#6845]
## Version
4.22.3

## Describe the bug
Certain packages that have dependency either direct or transient to Microsoft.Bot.Builder and related packages at version 4.19.3 and higher will report errors because after version 4.22.2 (last version were assemblies have PublicKeyToken) you will get errors about needing to add reference to assemblies in specific versions even though higher versions should be fine. 

## To Reproduce
1. Download version 4.22.3 of Microsoft.Bot.Builder
2.  Download version 4.22.2 of Microsoft.Bot.Builder
3. Inspect both assemblies and notice 4.22.3 is not strong name signed. 4.22.2 is.

This in turn makes all of the types in 4.22.2 not the same as the types in 4.22.3.

## Expected behavior
You should not remove strong naming or change to a new public key token for released code when increasing versions. This can cause issues with dependencies and strong type resolution.

## Additional context
// Microsoft.Bot.Builder, Version=4.22.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: v4.0.30319
// This assembly is signed with a strong name key.
// This assembly was compiled using the /deterministic option.
// Hash algorithm: SHA1
// Public key: 0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9

// Microsoft.Bot.Builder, Version=4.22.3.0, Culture=neutral, PublicKeyToken=null
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: v4.0.30319
// This assembly was compiled using the /deterministic option.
// Hash algorithm: SHA1

**Comment by tracyboehrer** [comment]
Most likely due to forced migration to OneBranch and its signing.

**Comment by tracyboehrer** [comment]
This should be resolved in 4.22.8
