### ISSUE TITLE
Use of emotes in bot framework

### ISSUE THREAD

**Issue by Tyagit3** [Microsoft/botbuilder-dotnet#685]
Is there any way that we can use custom gifs/ emotes in bot framework?
Or may be using a third party dll or any other way around?

**Comment by cleemullins** [comment]
Your bot can emotes with no trouble - they're just unicode codepoints to us. :)

Even something like this, 👩🏼‍⚕️, which is really 5 codepoints (U+1F469 U+1F3FC U+200D U+2695 U+FE0E) shouldn't be an issue, although it does rely on the target system to have the relevant fonts installed.

**Comment by Tyagit3** [comment]
Simple emojis aren't required. I meant animated emojis/ animojis.

**Comment by tomlm** [comment]
You can send an AnimationCard, but not inline to text other then Unicode. BTW: Unicode endpoints do allow some level of animation.
