### ISSUE TITLE
How to set MicrosoftAppId and MicrosoftAppPassword dynamically in C# code

### ISSUE THREAD

**Issue by Danieladu** [Microsoft/botbuilder-dotnet#689]
For some reason, we map many bots to one endpoint service, so we have to assign an appid and appsecret after `Post api/messages`, but if we leave  MicrosoftAppId and MicrosoftAppPassword empty in appsettings.json, the system would response code 403 anytime. Is there any way to solve this problem?

**Comment by drub0y** [comment]
Yes, you can write your own [`ICredentialProvider`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Connector/Authentication/ICredentialProvider.cs) implementation. This will be called to validate an incoming `appId` (`IsValidAppIdAsync') and get the corresponding password for that app ('GetAppPasswordAsync').

You connect a custom credential provider up at startup time like so:

```CSharp
services.AddBot<YourBot>(options =>
{
    options.CredentialProvider = new YourCustomCredentialProvider(... your params here ...);
});
```

**Comment by Danieladu** [comment]
@drub0y  Thanks drub0y. It works.
