### ISSUE TITLE
DCR: GetConversationReference and ApplyConversationReference should be on Activity class

### ISSUE THREAD

**Issue by tomlm** [Microsoft/botbuilder-dotnet#703]
In javascript we don't have an actual "Activity" class which caused the utility methods of
* GetConversationReference() 
* ApplyConversationReference() 
to be implement as global functions off of TurnContext.

That's the wrong place for them because
a. they have nothing to do with TurnContext
b. They are operations on the activity.  (Get a Conversation reference from an activity, apply a conversationReference to an activity).

In OO languages, I propose that we have the Activity class have the helper methods for ConversationReference methods and in Javascript the helper functions should be centered around the Activity.

**Comment by cleemullins** [comment]
+1

**Comment by drub0y** [comment]
Looks like this is being addressed in #705. Just mentioning here for issue<->PR linkage since the commits/PR don't mention it themselves directly right now.

**Comment by watadarkstar** [comment]
@tomlm Dd this ever get moved in botbuilder-js? see my comment here: https://github.com/Microsoft/BotBuilder/issues/3122#issuecomment-459551474

Seems like its still `TurnContext.getConversationReference(activity)` in js?
