### ISSUE TITLE
ctor patterns

### ISSUE THREAD

**Issue by franperezlopez** [Microsoft/botbuilder-dotnet#711]
I'm seeing this pattern all around in samples:
```
ctor() {
   dialogs.Add(/* bunch of code */);
   dialogs.Add(/* bunch of code */);
}
```
In samples, the objects that you use for adding to dialogs are *simple*. Now I'm working in a real prototype, using DI, and having so much code in the ctor can cause lot of problems. I'd rather have another pattern for initializing the dialogs. I assume this is for "simplistic" reasons, but I feel having so much work done in the ctor is not right ...

In the `IBot` classes, I moved the initialization code to the `OnTurn` (for the moment, I checked a new class is created in each turn anyway). But in the `DialogContainer` classes there is no room for extension, so applying same mechanism is not possible, unless I create my own `DialogContainer` from scratch.

**Comment by franperezlopez** [comment]
can you send me an email to frankjperez|at|yahoo|dot|es ?? I can share my sample with you

**Comment by JonathanFingold** [comment]
@franperezlopez , I'm probably not understanding your issue entirely. There are two options that come to mind.

```csharp
public class MyDialog : DialogSet
{
    public MyDialog1()
    {
        Add(/* id, IDialog */);
        Add(/* id, IDialog */);
        Add(/* id, IDialog */);
        Add("main", new WaterfallStep[]
        {
            // define you mail dialog here.
        });
    }
}
```

Those IDialogs can be simple prompts, or they can be another dialog defined as a DialogContainer.

**Comment by johnataylor** [comment]
This has shipped now and the surface area is fixed other than additive changes.
One interesting area is that we have started looking at how interruption can be integrated in the dialogs e.g. Help and Cancel. This has switched the focus to ComponentDialogs which have their own internal stack. In terms of dependency injection patterns this might be a productive place to start.
