### ISSUE TITLE
Allow access to original user input and detected language when using TranslationMiddleware

### ISSUE THREAD

**Issue by n01d** [Microsoft/botbuilder-dotnet#724]
Sometimes you need access to the original (untranslated) user input or detected language in your bot while using the TranslationMiddleware. This might be the case if you want to forward untranslated text to a search engine or ask the user for specific terms that should not be translated. Currently only the translated text is available through Context.Activity.Text.

A solution could be leaving the original text in Context.Activity.Text and providing the translation in a ways similar to the LUIS middleware:

```
var result = context.Services.Get<RecognizerResult>
                    (LuisRecognizerMiddleware.LuisRecognizerResultKey);
                var topIntent = result?.GetTopScoringIntent();
```

For the translation middleware this could be something like:

```
var result = context.Services.Get<TranslationResult>
                    (TranslationMiddleware.TranslationResultKey);
var topTranslation= result?.GetTopTranslation();
var detectedLanguage= result?.GetDetectedLanguage();
```

Another way could be to still overwrite Context.Activity.Text and add the original input to another field.

**Comment by johnataylor** [comment]
TranslationMiddleware is not part of the product.
