### ISSUE TITLE
Provide a way to create a list of terms not to be translated when using TranslationMiddleware

### ISSUE THREAD

**Issue by n01d** [Microsoft/botbuilder-dotnet#725]
When using TranslationMiddleware you currently can only provide a list of patterns to detect parts of the user input not be be translated.

This works well for cases like the one described in the example (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-translation?view=azure-bot-service-4.0&tabs=cs#bypass-translation-for-specified-patterns) but I did not find a way to add a list of terms not to be translated at all, even when the user just sent this (one) term.

You frequently need this when you forward user input to a search engine or when using technical terms. For example when the bot ask the user for the kind of application the user needs help with the user might just answer "Office" or "Word". Both are words we just want to pass to the bot without translating them.

A solution could look similar to the patterns mentioned above.

**Comment by johnataylor** [comment]
TranslationMiddleware is not part of the product.
