### ISSUE TITLE
Dot Net implementation is missing validate version middleware functionality

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#727]
@stevenic says this is essential functionality and it is currently included in the JavaScript.

Refer to the JavaScript implementation for reference.

**Comment by sgellock** [comment]
consider a blog post to show customers how to version their storage

**Comment by cleemullins** [comment]
This is not in the V4.0 JS SDK. 

@stevenic removed this and [moved it to toybox](https://github.com/Stevenic/botbuilder-toybox/tree/master/packages/botbuilder-toybox-extensions/src). 

Closing.
