### ISSUE TITLE
Hide the PagedResult class

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#730]
re: [PagedResult.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/PagedResult.cs).

Per discussion with @cleemullins and @johnataylor , paging behavior should not be public.

**Comment by JonathanFingold** [comment]
@vishwacsena , What's the state of this. We're running out of time for code complete, and I don't want to add docXML for parameters and classes that are going to be hidden.

**Comment by cleemullins** [comment]
This shipped with the V4 SDK and is now part of our framework. We can't remove it w/o breaking compat, so it's in to stay.
