### ISSUE TITLE
Should the Intents and Entities properties of RecognizerResult return JObect?

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#731]
The current descriptions for these properties suggest that they return Dictionary<string, object>.

Since this class supports an interface definition, we probably want something more strongly typed than a JObject here. Implementers won't know what format they should give to these properties.

**Comment by JonathanFingold** [comment]
PS. Looks like for LUIS, this could just be Dictionary<string, double> for **Intents**.

**Comment by chrimc62** [comment]
We have defined a generic JSON payload for any recognizer (including LUIS) to return.  It looks like:
{ "intents": {"Help": {"score":0.9}, "Cancel": {"score": 0.01}}, ...}
In addition to score, any given recognizer is also free to return other information about each intent.  For example, if your recognizer supported multiple intents, it might point to the span where the intent was found.  We really should update the documentation to point to the definition of this structure which is only weakly typed which should help people understand what to generate.

Your question has to do with how we model weakly typed objects in C#.  The current interface uses a JObject which really is a dictionary that maps from a string to a value.  It also corresponds to the underlying JSON object which is common across languages.  We could make it slightly stronger by using Dictionary<string, object> but that is the same as JObject while losing the connection to the underlying JSON.  Alternatively we could type it as Dictionary<string, BaseClassWithScore> which makes it a little stronger, but at the cost of introducing another class which itself needs to have a property bag inside it for any extra properties found in the intent.

In the case of LUIS if you want a fully typed object you can use the LUISGen tool to generate a custom class for C# or Typescript which gives you intellisense.  

Please reopen if you disagree with the reasoning and have a counter-proposal.

**Comment by JonathanFingold** [comment]
@chrimc62 , RecognizerResult has a Properties property, used to capture such additional information. Would it be untoward to continue that sort of model one more level down? (I'm not sure what a RecognitionEntity class should look like, but I'll take a wild guess.)
```cs
public class RecognitionIntent
{
    public string Name { get; set; }
    public double Score { get; set; }

    [JsonExtensionData(ReadData = true, WriteData = true)]
    public IDictionary<string, object> Properties { get; set; } = new Dictionary<string, object>();
}
public class RecognitionEntity<T>
{
    public string Name { get; set; }
    public T Value { get; set; }

    [JsonExtensionData(ReadData = true, WriteData = true)]
    public IDictionary<string, object> Properties { get; set; } = new Dictionary<string, object>();
}
```
Then intents (and entities) could be defined as some sort of collection, IEnumerable, Dictionary, whatever:
```cs
[JsonProperty("intents")]
public IEnumerable<RecognitionIntent> Intents { get; set; }
```

**Comment by chrimc62** [comment]
I can push it one level down.  IDictionary<String, ScoredObject>
class ScoredObject
{
double Score;
IDictionary<string, object> Properties;
}

**Comment by johnataylor** [comment]
This has shipped now. We have an IntentScore in the product. Luis recognizer makes use of that.
