### ISSUE TITLE
Consider removing unused parameter from OAuthClient.GetUserTokenAsync

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#734]
re: [OAuthClient.GetUserTokenAsync](https://github.com/Microsoft/botbuilder-dotnet/blob/72762abcea7fea4e7b2d7bd759de8d41a81eb8f9/libraries/Microsoft.Bot.Connector/OAuthApiClient.cs#L45)

The optional **customHeaders** parameter is not used in the implementation of the method, and none of the calling methods specify a value for it.

**Comment by vishwacsena** [comment]
By design.
