### ISSUE TITLE
Sending adaptive card doesn't change ITurnContext.Responded

### ISSUE THREAD

**Issue by cocoke** [Microsoft/botbuilder-dotnet#749]
Hello, I'm facing a problem, I'm sending an adaptive card with the ``MessageFactory.Attachment`` method and the ``turnContext.SendActivity``
My project contains multiple middleware and the problem is that after sending this adaptive card ``turnContext.Responded`` doesn't set to true.
Also my custom ConversationState doesn't persist until the next 'real' message.

Is that the normal behavior ?

**Comment by daveta** [comment]
@cocoke can you please share a repro code snippet?

**Comment by johnataylor** [comment]
The dialog stack has been updated and this should all work correctly. Closing this now, if you think there is still a problem please reopen.
