### ISSUE TITLE
LanguageMap.cs class in Microsoft.Bot.Builder.Ai.Translation should be readonly and static

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#752]
The LanguageMap class is currently created frequntly, and is a high-cost-to-construct. 

The code should be refactored in 2 ways:
1. The language map should be made Readonly as the contract level. Current usage implies its immutable anyway, so enforcing that makes things cleaner. 

2. Construction should be done via a static Lazy<T>, so it's only done once. As the data is unchanging this will cleanup significant code.

**Comment by sgellock** [comment]
please pull from both node and C#

**Comment by johnataylor** [comment]
removed translation middleware from node and C#
