### ISSUE TITLE
Change Request: Remove dc.Context.Activity.Type != ActivityTypes.Message check from Prompt.cs

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-dotnet#754]
@cleemullins , @johnataylor , @Stevenic: I am working on a custom EventPrompt that can send an event and expect an event as a response, I am deriving my custom prompt from the abstract Prompt<T> class.

The issue I have is that he base class ignores activities that are not of type ActivityTypes.Message and my custom prompt never gets the response. 

Would it be possible to remove this guard from the abstract class? (I think is OK to have it in specialized prompts like TextPrompt but not on the base class).

Thanks

CC: @darrenj as an FYI.

**Comment by darrenj** [comment]
Makes sense given the scenario I think your trying to solve. Might be useful to add a high level generic scenario to help frame the need for the change.

**Comment by daveta** [comment]
@Stevenic's new dialog changes fixes this by introducing a new allActivityPrompt type. We'll wait for that change to come in before we bring this to C# as well.

**Comment by johnataylor** [comment]
This should be fixed now. As an example see the test code in ActivityPromptTests.cs
