### ISSUE TITLE
Proposal: DelayActivity no longer offers any real value and should be removed

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#768]
`DelayActivity` was invented back when outbound activities were buffered before being sent and, therefore, a bot (or middleware) needed to tell the `BotAdapter` to introduce a delay when _actually_ sending the activities out. 

Now that a call to `SendActivityAsync` results in an _immediate_ outbound activity being sent, I believe we should remove `DelayActivity` to simplify the code base both externally (one less synthetic-`Activity` type to maintain) and internally (`BotAdapter`s need to handle this specially).

People can (and likely will) just achieve this delay functionality in a way they're used to on their platform (e.g. `await Task.Delay` in .NET) before calling `SendActivityAsync`.

**Comment by cleemullins** [comment]
@drub0y That's... a great point. Your logic seems correct to me. Let me sync with Steve and verify, at which point we can accept this bug and remove it.

**Comment by sgellock** [comment]
@Stevenic can you drive to closure please.

**Comment by johnataylor** [comment]
The 4.x behavior has shipped now. Implementing a custom adapter can alter the behavior appropriately.
