### ISSUE TITLE
Issues w/nightly package versioning scheme

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#770]
The nightly packages seem to be building with a four-part version identifier and no pre-release suffix.

First, NuGet packages need to follow [semver](https://semver.org) versioning rules or else wacky things will start to happen with NuGet clients. In short: the versions need to be match the format of: `<major>.<minor>.<patch>[-<prerelease>+<build-metadata>]`

Most of the time people leverage [GitVersion](http://gitversion.readthedocs.io/en/latest/) to handle their automated package versioning. Not only will this help calculate the version number for your actual source level build to use, but it will also help generate a good package version identifier by taking on a pre-release identifier that includes the branch name and commit SHA so you can look at a package and immediately know what commit in the code this package was stamped from.

Additionally, the fact that there is no pre-release identifier on the feed right now means that if, as a developer, I add that feed to my list of feeds because I want to play with the latest bits in a test project, but I still need to develop a production release bot day-to-day, there's a possibility that when I do NuGet update that it will take the more recent version from the MyGet feed even though it's pre-release.

[Here's a nice series of blog posts](https://blogs.msdn.microsoft.com/devops/2016/05/26/versioning-nuget-packages-cd-3/) on the subject of utilizing GitVersion to deliver NuGet packages via a CD pipeline.

**Comment by cleemullins** [comment]
Thanks for the link to the blog posts. Reading today.

**Comment by cleemullins** [comment]
@drub0y You're right. Again.

**Comment by sgellock** [comment]
we will snap to semver starting with RC build candidates for v4
