### ISSUE TITLE
Components requiring state can only document scoping requirements, bot developer has configure correctly

### ISSUE THREAD

**Issue by drub0y** [microsoft/botbuilder-dotnet#773]
Under this new design a component indicates it needs one or more pieces of state by requiring `IStatePropertyAccessor<T>` parameters to its constructor. [One of the points](https://github.com/Microsoft/botbuilder-dotnet/pull/760#pullrequestreview-138043228) I was trying to make against this design is that it puts the burden on the bot developer to create these "properties" up front, hold on to them and somehow pass them into each piece of middleware during the configuration phase and eventually the bot (which still hasn't been sorted out AFAICT). 

The bigger problem that I wanted to call out in this specific issue is that there's no way, unless you go read some documentation, to know what state scope to create an accessor under for a given component. User? Conversation? Bot? You can't tell what the requirement is just from the type information.

The side effect of this is that, if the developer creates the property under the incorrect scope, the behavior of the component will likely be completely wrong. Worse, consider a scenario where the component is expecting to store its properties in Conversation scope, but the developer registers it in Bot scope. This would likely leak information from one conversation to another which would obviously be bad.

**Comment by sgellock** [comment]
Thanks for the feedback.  We agree.  Moving to backlog for consideration

**Comment by gabog** [comment]
Closing as part of R10 triage.
