### ISSUE TITLE
MemoryTranscriptStore::GetTranscriptActivitiesAsync does OrderBy on timestamp producing non-deterministic results that break tests

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#777]
`MemoryTranscriptStore` is storing the `Activity` instances it sees in a `List<Activity>`. It's `GetTranscriptActivitiesAsync` performs an `OrderBy` on this list when scanning through it to try to ensure the activities are returned in the order they were received. 

The problem is that when activities go by fast enough, such as is the case with unit tests, performing an the timestamps on the activities will be equal in terms of `DateTime` precision. Thus, if you perform an `OrderBy` on two activities that are within the same exact `DateTime` precision they will be considered equivalent and then the actual output order is undefined. This means some of the unit tests that are currently trying to validate the output are _sometimes_ broken. In fact, I've discovered that there are several tests where the author clearly must have run into this and changed the order just to get it to pass, because the order is actually _logically wrong_. For example: `Transcript_TestDateLogUpdateActivities` is coded to assert that the updated message actually comes before the message which should trigger the update.

The truth is, since we're using a `List<Activity>` as a data structure we don't need to rely on the timestamps at all because the order is naturally correct due to the append only use of the data structure.

I have removed the `OrderBy` call in `GetTransacriptActivitiesAsync` and corrected the order of assertions in some of the tests and things all work predictably. I've done this in another working branch, but we need to fix/commit this bug fix on its own. I would be happy to do the work if we all agree this is a problem and my proposed solution sounds appropriate.

**Comment by drub0y** [comment]
Thinking about this a little further, we would need to be careful about this with any transcript store implementation. For example, the `AzureBlobTranscriptStore` can fall victim to the same problem as it's relying on the `Timestamp` of the blob which could theoretically have activities within the same date/time precision.

**Comment by johnataylor** [comment]
@drub0y what you say makes sense however per @tomlm this is a test tool and we don't want to take a fix on this right now. We have some other activity record and replay experiments people have been experimenting with. We would also like to have more test unification across the various implementation languages. As part of fleshing those ideas out your point about basing logic on potentially fragile timestamp ordering is well taken.
