### ISSUE TITLE
Continuing DialogSet from information in state

### ISSUE THREAD

**Issue by JeffCordes** [Microsoft/botbuilder-dotnet#779]
All of the current samples that use dialogs or waterflows instantiate a DialogSet in the bot constructor that is called each time a new message or event is received.  This would create a lot of extra instantiation for bots with several possible dialog workflows.

When a dialog starts it stores a List<DialogInstance> in the state with the key "dialogStack".  There should be a way to attempt the continuation of any open dialogs from what is stored in the state.  Is it possible to construct a DialogSet or DialogContext from the List<DialogInstance> in the state?

So instead of initializing every dialogSet in a bot, creating a conversation context, trying to continue, then checking if a response was sent.

**Current**
```
dialogCtx1 = dialogSet1.CreateContext(cntxt, state); 
dialogCtx1.Continue();
if (dialogCtx1.Responded) { return; }
dialogCtx2 = dialogSet2.CreateContext(cntxt, state); 
dialogCtx2.Continue();
if (dialogCtx2.Responded) { return; }
dialogCtx3= dialogSet3.CreateContext(cntxt, state); 
dialogCtx3.Continue();
if (dialogCtx3.Responded) { return; }
```

We could instantiate and continue only the one we need.

**Desired**
```
if (state.TryGetValue("dialogStack", out object dialogStack))
{
	// use the info on dialogStack to continue any open Dialogs..
	DialogContext dialogContext = new DialogContext(dialogStack)
	await dialogContext.Continue();
}
```

**Comment by johnataylor** [comment]
The solution is to define your own subclass of ComponentDialog. You should then be able to create a singleton and use dependency injection to reuse this instance across different dialog instances.

Every ComponentDialog instance contain its own DialogSet instance internally so this arrangement avoids the construction of all the classes that represent the conversation model.

This new sample happens to use this approach (though it's not the main point of the sample):

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/42.scaleout/ScaleoutBot.cs

Its true that a DialogSet is created each turn, however it's only ever got one member added, that being the custom ComponentDialog (called RootDialog in this code.)
