### ISSUE TITLE
CreateDirectConversationAsync throws ArgumentNullException 

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#784]
Moved over for @michaelmsm89 from the BotBuilder repo: [#4891](https://github.com/Microsoft/BotBuilder/issues/4891)

___

## Bot Info
* SDK Platform: .NET
* SDK Version: 4.0.1-preview
* Active Channels: Slack
* Deployment Environment: Local development

## Issue Description
`IConversations.CreateDirectConversationAsync` throws a `ArgumentNullException`, but the sync version doesn't.

```
System.ArgumentNullException: Value cannot be null. Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.TrustServiceUrl(String serviceUrl, DateTime expirationTime)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.TrustServiceUrl(String serviceUrl)
   at Microsoft.Bot.Connector.ConversationsExtensions.CreateDirectConversationAsync(IConversations operations, ChannelAccount bot, ChannelAccount user, Activity activity, CancellationToken cancellationToken)
```

## Code Example
In the example below, I am picking up a message from a chat channel and then starting a conversation to reply to the message sender privately.

Throws exception:
```
public class ExampleMiddleware : IMiddleware
{
    public async Task OnTurn(ITurnContext turnContext, MiddlewareSet.NextDelegate next)
    {
        var connector = turnContext.Services.Get<IClientConnector>();
        var botAccount = new ChannelAccount(turnContext.Activity.Recipient.Id, turnContext.Activity.Recipient.Name);
        var userAccount = new ChannelAccount(turnContext.Activity.From.Id, turnContext.Activity.From.Name);
        var conversation = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount);

        // Rest of code here, but crashes on line above
    }
```

Doesn't throw exception:
```
***
var conversation = connector.Conversations.CreateDirectConversation(botAccount, userAccount);
```

**Comment by BillStrait** [comment]
I have a similar issue with both methods. The null object is customHttpClient in the method `Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials(string appId, string password, HttpClient customHttpClient)`

My code looks like this

    ChannelAccount userAccount = new ChannelAccount(_config.UncategorizedReportToEmail, _config.UncategorizedReportToEmail);
    var botAccount = new ChannelAccount(_config.BotEmail, _config.BotEmail);
    var connector = new ConnectorClient(new Uri(_config.EmailServiceUrl));
    MicrosoftAppCredentials.TrustServiceUrl(_config.EmailServiceUrl);
    // Next line is where the exception is thrown
    var conversation = connector.Conversations.CreateDirectConversation(botAccount, userAccount);
    var conversationId = conversation.Id;

**Comment by mrivera-ms** [comment]
This is a stale item.
