### ISSUE TITLE
Where is source for AzureTableStorage?

### ISSUE THREAD

**Issue by jjshuler** [Microsoft/botbuilder-dotnet#785]
I cannot find the source for AzureTableStorage IStorage implementation. I may have encountered a bug with it, but searching all of Microsoft's code for "AzureTableStorage" yielded only the example templates using the class.

**Comment by drub0y** [comment]
See [my comment](https://github.com/Microsoft/botbuilder-dotnet/issues/736#issuecomment-403628172) on #736 for more details on this.
