### ISSUE TITLE
AzureTableStorage throws 400 Bad Request when writing

### ISSUE THREAD

**Issue by JasonJShuler** [Microsoft/botbuilder-dotnet#786]
I am attempting to write to an AzureTableStorage object following the example documented here:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharpechorproperty%2Ccsetagoverwrite%2Ccsetag

When I call the Write() method, it throws a 400 Bad Request error.

Here is my code
`await _dataStore.Write(new[] { new KeyValuePair<string, object>("foo", "hello world") });`

Using Fiddler I'm noticing that the partition key is being sent as blank:
`{"":"hello world","__type":"System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"}`

And here is the error contents of the response:
`{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"An error occurred while processing this request.\nRequestId:f2f20955-c002-0058-474d-232c86000000\nTime:2018-07-24T12:51:24.2934524Z"}}}`

The bot is able to store and retrieve conversation data successfully - it is this attempt to write using the IStorage implementation directly that fails.

(Note: this is related to issue #785 - I cannot find the source for AzureTableStorage)

**Comment by drub0y** [comment]
I'm not sure what's causing this, but the `AzureTableStorage` implementation has been removed from more recent versions of the code base and, as I replied on #785, [you can read more about it here in my comment](https://github.com/Microsoft/botbuilder-dotnet/issues/736#issuecomment-403628172) on #736.

**Comment by sgellock** [comment]
@JasonJShuler per @drub0y feedback, we have decided to support Blob, CosmoDB, and MemoryStorage
