### ISSUE TITLE
DCR: change defaultValueFactory to take ITurnContext in BotState.CreateProperty()

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-dotnet#791]
@tomlm drifted from the JS BotState.CreateProperty() implementation by using a delegate to set the default value for the BotStatePropertyAccessor. 

 > - BotState.CreateProperty() default value is a little bit trickier in C#, because it isn't as easy to simply clone an object as it is in JS. If you notice I have a bit of heuristics to make a copy, but it might be a lot clearer to have a delegate to ask for a new default value. Thoughts?
> ([_source_](https://github.com/Microsoft/botbuilder-dotnet/pull/760#issue-201814413))

The delegate has this type, `Func<T>`, and is called in [BotStatePropertyAccessor.GetAsync()][GetAsync]:
```cs
public async Task<T> GetAsync(ITurnContext turnContext)
{
    try
    {
        return await _botState.GetPropertyValueAsync<T>(turnContext, Name).ConfigureAwait(false);
    }
    catch (KeyNotFoundException)
    {
        // ask for default value from factory
        var result = _defaultValueFactory();

        // save default value for any further calls
        await SetAsync(turnContext, result).ConfigureAwait(false);
        return result;
    }
}
```

Since GetAsync already requires an ITurnContext, should we also forward this context to the delegate and thus change BotState.CreateProperty() and the defaultValueFactory to look like this:

```cs
public IStatePropertyAccessor<T> CreateProperty<T>(string name,
    Func<ITurnContext, T> defaultValueFactory = null)
```

___

### Potential Use Case:
One example use case could be if a developer has two "Address" Properties, one of which is the `BillingAddress` and one of which is the `ShippingAddress`. 

In using a delegate that takes the context as an argument, the bot can dynamically populate the `ShippingAddress` property's value based off of the `BillingAddress`. The factory would check to see if the `BillingAddress` value was already created by checking the cache on the context.

@cleemullins, @vishwacsena, @daveta, @johnataylor, what do you think?

  [GetAsync]: https://github.com/Microsoft/botbuilder-dotnet/blob/3978e6b19aa34a28fa09fe84c9919e7894be4b45/libraries/Microsoft.Bot.Builder/BotState.cs#L305L320

**Comment by stevengum** [comment]
I should note that I haven't forgotten the conversations we've had for the PropertyAccessors implementation 😄 

However, I thought this mini-DCR might help flesh out prospective uses for the code we have checked in.

**Comment by drub0y** [comment]
I think your use case is a good one. The only thing I would recommend is that the API offer the ability to simply just take a `Func<T>` _as well_ since I suspect the majority of implementations will probably just return a constant and not need to deal with the `ITurnContext`. The core API can be changed to `Func<ITurnContext, T>` and then if someone just calls the overload/extension method that only wants to do  `Func<T>` you just wrap it with a `Func<ITurnContext, T>` that basically ignores the `ITurnContext` and invokes the underlying `Func<T>`.

So, to be clear, I'm suggesting `BotState::CreateProperty` be changed to:

```CSharp
public IStatePropertyAccessor<T> CreateProperty<T>(string name, Func<ITurnContext, T> defaultValueFactory = null)
{
   // … impl here ...
}
```
And then a `BotStateExtensions` class be added with:

```CSharp
public IStatePropertyAccessor<T> CreateProperty<T>(static BotState botState, string name, Func<T> defaultValueFactory) => 
    botState.CreateProperty<T>(name, tc => defaultValueFactory());
```
***NOTE:** I'm still extremely hesitant about the design of this storage API overall, so I just want to make clear that this is based on what there is today and not an approval of the overall design.*

**Comment by drub0y** [comment]
Not to muddy the waters, but another consideration that should be had is whether the factory offer support for `async` values? If so, the core signature should be changed to `Func<ITurnContext, ValueTask<T>>` and then the synchronous version should also be offered as an extension method that just auto-wraps the sync result with a `ValueTask<T>`.

**Comment by stevengum** [comment]
I think it's safe to close this DCR as now the `defaultValueFactory` is on the [`getAsync`](https://github.com/Microsoft/botbuilder-dotnet/pull/812/files#diff-82c6659b3b366b234170a2b7a16e6081R296) as opposed to the constructor. This means that when you get the property value you'll have access to the current context and can create a turn specific  `defaultValueFactory` before getting the property value.
