### ISSUE TITLE
Dialog documentation is inconsistent

### ISSUE THREAD

**Issue by WhitWaldo** [Microsoft/botbuilder-dotnet#794]
Reading through the documentation at [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp), there are a few inconsistencies that need corrections.

Each of the issues I found are within the **Using dialogs to guide the user through steps** section.

1) Under the "Create a composite dialog" section, it indicates that the following snippets are taken from the [Microsoft.Bot.Samples.Dialog.Prompts](https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples/MIcrosoft.Bot.Samples.Dialog.Prompts) sample code in the botbuilder-dotnet repo. That's the correct repo, but there is no sample given that title in there, nor is the link pointing to the correct place (it yields a 404).

2) Starting at the example preceded by "In DialogContainerBot.cs, define a class for a profile dialog." it specifies the base string value as "fillProfile" and repeats it as the key for the control two lines later. In the next example, it refers to this profile instead by "getProfile" (again, twice in the example). One of these should be updated.

**Comment by JonathanFingold** [comment]
@WhitWaldo , this article has known issues and is in the process of being rewritten. I don't have a firm date yet, as we mid-process in preparing for the next update of the NuGet packages, which will contain a number of breaking changes.

**Comment by JonathanFingold** [comment]
@WhitWaldo , the article has been updated, and has been split in two:
* [Manage simple conversation flow with dialogs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)
* [Manage complex conversation flows with dialogs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-complex-conversation-flow?view=azure-bot-service-4.0&tabs=csharp)

Please reopen if this does not fully address the issue.
