### ISSUE TITLE
DCR: Add ability to Add/View Http Headers

### ISSUE THREAD

**Issue by daveta** [microsoft/botbuilder-dotnet#799]
Currently, by-design, there isn't a way to get Http headers (both incoming from channel, or adding http headers outbound).

There have been a few cases (specifically around custom correlation id scenarios) to:
- Inspect Http Headers coming in, and be able to access in Middleware components
- Be able to add Http Headers when sending messages

For correlation/tracing, I believe this mostly goes away App Insights adopts an in-flight standard.  However, current ETA is December, which may slide.

https://w3c.github.io/distributed-tracing/report-trace-context.html
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/945

I'm filing this because I believe Stevenic mentioned this was requested before (not sure the scenario) and potential slippage in finalization of the standard.

**Comment by drub0y** [comment]
⚠️ HTTP is just one possible transport and I would highly recommend we be _very_ careful about leaking anything specific into the Bot Builder APIs that mention or expose HTTP'isms directly. ⚠️  

At most you'd maybe shove something into the `TurnContext::Services` collection at the adapter level that downstream middleware could look for _and be tolerant to not finding_ in case, somewhere down the line, we support other transports.

**Comment by gabog** [comment]
Closing as part of R10 triage.
