### ISSUE TITLE
TurnContext.SendActivityAsync Setting Responded

### ISSUE THREAD

**Issue by JeffCordes** [Microsoft/botbuilder-dotnet#800]
Should the SendActivityAsync and SendActivitiesAsync methods in TurnContext accept an optional bool as a parameter to set if the Responed flag is set after Activities are sent?

There is a lot of code that ends up using if (!context.Responded) so it is important that we can control what sets context.Responded.

SendActivitiesThroughAdapter() has logic to not set Responded = true only if the ActivityType == Trace.  However there are other types like Typing and  MessageReaction that we may not want to count as sending a Response, but also may want to.  Maybe giving the developer that calls SendActivity the ability to set responded or not is more flexible.?

**Comment by drub0y** [comment]
I agree that the current implementation is a bit flawed as the SDK just decides what it means to have responded without offering any direct control over it. I don't know if adding the `bool` to the `SendXXX` methods is the right move either, but I think this topic bears some discussion.

**Comment by JeffCordes** [comment]
What if instead of having the bool Responed, TurnContext has a property Responses that is a List<IActivity>.  This way the adapters can add all responses without having to do any filtering based on type.  The integrating developer with special logic that only wants to know responses with a certain type can use Linq on the collection to determine that.

**Comment by JeffCordes** [comment]
This is now being accomplished by using the eventhandlers.. https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-event-handlers?view=azure-bot-service-4.0&tabs=cseventhandler

And storing the sent activities in the context.Services
