### ISSUE TITLE
CosmosDbStorage partitioning option

### ISSUE THREAD

**Issue by ukphillips** [microsoft/botbuilder-dotnet#803]
It does not appear that the CosmosDbStorage for storing state allows for partitioning. Was this a conscious decision? It seems like it would make sense to naturally partition on a conversation id to allow for better long term scaling.

**Comment by drub0y** [comment]
Yes, we should probably do this. Would you be happy with a purely internal implementation of the partitioning algorithm that maybe just takes the id and runs it through a hash to arrive at a partition key or would you expect a hook that would allow you to calculate the partition key yourself? If you would want to calculate it yourself, what inputs were you thinking you'd need? 

Right now, off the top of my head, I'm imagining a simple `Func<string, string>` where the input `string` would be the key for the state and the default implementation would probably just calculate a simple hash off of that key to be the partition key.

**Comment by ukphillips** [comment]
When it comes to state my initial thought is that this should be handled internally by the framework since from the code it will be storing a DocumentStoreItem object, which the consumer would know nothing about. Or are you suggesting possibly adding a partition key property that could be extracted based on a passed in `Func<string, string>`

I'm having a hard time of thinking when that type of flexibility would be more beneficial than detrimental (someone choosing a bad partition key for looks that will happen quite frequently I would imagine), though I'm open to suggestion.

On a side note I came across this as I was trying to store the transcripts with a ConversationId partition key in a collection, and then I wanted to start putting the State in the same collection for less maintenance/cost, but I realized there was no way to get the state persistence with the partitioning property I was using (and does not have any internal partitioning approach).  I'm feeling like it might be a bad idea to keep them in the same collection, with differing partition keys being one sticking point, but interested in thoughts on that as well.

**Comment by james-novino** [comment]
This seems to be a duplicate issue. This issue should likely be closed in favor of https://github.com/Microsoft/botbuilder-dotnet/issues/1247

**Comment by CoHealer** [comment]
https://github.com/microsoft/botframework-sdk/issues/5467

**Comment by gabog** [comment]
Done as part 4.7, using https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs
