### ISSUE TITLE
BotMessageHandlerBase.SendAsync (full framework) media type problem

### ISSUE THREAD

**Issue by JasonJShuler** [Microsoft/botbuilder-dotnet#805]
Microsoft.Bot.Builder.Integration.AspNet.WebApi does not work with an actual Azure Bot Service - it throw a NotAcceptable exception.

This is because the SupportedMediaTypes list does not contain culture info, and the bot service sends it as utf-8.

I ended up grabbing the source for 4.0.1-preview and patching as follows (to only use the media type name)

I'm sure there is a better way.

I noticed that a similar issue was corrected for the .NET Core version of the WebApi integration - I'm not clear if it has been fixed in the full framework version.

```csharp
            var supportedMediaTypeNames = (from f in BotMessageMediaTypeFormatters[0].SupportedMediaTypes select f.MediaType.ToLowerInvariant());
            var mediaTypeName = requestContentHeaders.ContentType.MediaType.ToLowerInvariant();

            //if (!BotMessageMediaTypeFormatters[0].SupportedMediaTypes.Contains(requestContentHeaders.ContentType))
            if (!supportedMediaTypeNames.Contains(mediaTypeName))
            {
                return request.CreateErrorResponse(HttpStatusCode.NotAcceptable, $"Expecting Content-Type of \"{BotMessageMediaTypeFormatters[0].SupportedMediaTypes[0].MediaType}\".");
            }
```

**Comment by jjshuler** [comment]
Here is a better looking example fix:

Add the following using statement
`using System.Linq;`

At line 58 (59 after adding reference to System.Linq) in [Microsoft.Bot.Builder.Integration.AspNet.WebApi.BotMessageHandlerBase.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/ffc18910fa5c157922c9a4a11c2842ce9fe6213f/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.WebApi/BotMessageHandler.cs)

Change from this:
`            if (!BotMessageMediaTypeFormatters[0].SupportedMediaTypes.Contains(requestContentHeaders.ContentType))`

to this:

`            if (!BotMessageMediaTypeFormatters[0].SupportedMediaTypes.Select(m => m.MediaType).Contains(requestContentHeaders.ContentType.MediaType, StringComparer.InvariantCultureIgnoreCase))`

Please let me know what the correct method is to provide bug fix code.

Thanks!

**Comment by drub0y** [comment]
First, I'd probably avoid using LINQ here because of the performance implications and the fact that this is core logic that needs to be super sensitive about introducing overhead, but the point is still valid that this needs to be fixed. 

That said, I believe we can fix this much more simply by adding an entry to the `SupportedMediaTypes` to the `JsonMediaTypeFormatter` we create to include one that has the raw media type `application/json` and also sets the `CharSet` of `utf-8`. 

I will look into this as soon as I have a free moment if nobody on the team gets to it before me.

**Comment by JasonJShuler** [comment]
Thanks @drub0y,

Here is a revised patch based on your recommendations:

In the 4.0.1-preview code, insert the following after line 31 (After the closing brace for SerializerSettings on the BotMessageMediaTypeFormatters definition)

`                ,SupportedMediaTypes =
                {
                    new System.Net.Http.Headers.MediaTypeHeaderValue("application/json") { CharSet = "utf-8" },
                    new System.Net.Http.Headers.MediaTypeHeaderValue("text/json") { CharSet = "utf-8" }
                }`

I have tested and it works like a champ in both the emulator and using the Azure Bot Service.

Thanks!

**Comment by yochay** [comment]
@JasonJShuler  please create a PR with your changes.

**Comment by JasonJShuler** [comment]
@yochay seems I don't have rights to push a branch. Am I doing it wrong?
