### ISSUE TITLE
Proactive Bot message not working with Microsoft App id & password. 

### ISSUE THREAD

**Issue by chintan3100** [Microsoft/botbuilder-dotnet#806]
I am working on Proactive Bot. It is working on local simulator with below code but when we deploy to Azure it is not working.Proactive Bot message not working with Microsoft App id & password. 

Please review the attached screenshot. It looks like the authentication issue. Microsoft App id & password is available in the app setting.  It worked only once after stoped working.

  var connector = new ConnectorClient(new Uri(**ServiceUrl**));
 IMessageActivity newMessage = Activity.CreateMessageActivity();
            newMessage.Type = ActivityTypes.Message;
            newMessage.From = new ChannelAccount();
            newMessage.Conversation = new ConversationAccount(false, "MyBot");
            newMessage.Recipient = new ChannelAccount("MyBot");
            newMessage.Text = helpText;
            await connector.Conversations.SendToConversationAsync(**ConversationId**, (Activity)**newMessage**);

![image](https://user-images.githubusercontent.com/1373832/43456941-e61d9244-94e2-11e8-9cd3-b99deb82d3d4.png)

**Comment by ukphillips** [comment]
Can you provide more information about what the code is doing? It looks like you are responding to an existing conversation? Can you connect to this conversation using postman directly with the DirectLine endpoints? Is this this running in webchat, or within the azure portal web chat tester?

**Comment by yochay** [comment]
This is a great question for Bot Framework on [Stackoverflow](https://stackoverflow.com/questions/tagged/botframework).
