### ISSUE TITLE
WhatsApp channel support

### ISSUE THREAD

**Issue by franperezlopez** [Microsoft/botbuilder-dotnet#811]
WhatsApp just launched the [API for business](https://developers.facebook.com/docs/whatsapp/) in preview
do you have any plans for adding whatsapp as a channel in bot framework and support regular messaging capabilities??

**Comment by EricDahlvang** [comment]
Hi @franperezlopez 

This issue: https://github.com/Microsoft/BotBuilder/issues/2920  on the BotBuilder repository is currently tracking interest in a Bot Framework WhatsApp channel.  Please share your interest there.
