### ISSUE TITLE
BotState should not be abstract

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#814]
There are scopes other than **user** and **conversation** for which state is useful.

In particular, I'm working on a proactive sample. If the bot is managing a number of "jobs" for various users, supporting state information doesn't fit into either conversation or user state.

Do we want people to roll their own each time this comes up?

* Caching information from another service.
* Managing information for a particular location or region.
* etc.

**Comment by ukphillips** [comment]
I personally think the current approach is fine - the only thing the concrete classes currently do is implement the look up key for the IStorage implementation. Not exactly a huge lift to implement for custom state objects you might want. On any BotState you can have whatever properties of whatever type you want via `CreateProperty<T>(name)`, allowing for custom items to be stored on the ConversationState or UserState objects.

**Comment by JonathanFingold** [comment]
I'll run with whatever the team decides.

If a bot needs to route a question to another user (moderator or admin), then neither user nor conversation state will be appropriate. Same goes for any automated process not tied to a user.

**Comment by yochay** [comment]
Our state implementation is not designed to capture all state. Use other stores to save specific user data.
