### ISSUE TITLE
User-Agent proposal: Formatting requests

### ISSUE THREAD

**Issue by p-nagpal** [Microsoft/botbuilder-dotnet#825]
We would like to extract 6 fields from the user agent string if possible: 

1. BotFramework  Protocol version
2. SDK version
3. SDK Host   (Language)
4. SDK Host Version
5. OS
6. OS arch

To allow this, can we request the [User Agent Proposal ](https://github.com/Microsoft/botbuilder-dotnet/blob/d342cd66d159a023ac435aec0fdf791f93118f5f/doc/UserAgents.md 
) support the additional fields below? 

1. Could we request that Microsoft-BotFramework/<version> always be included in the user agent string? This was included in the older versions of the SDK and would be good to keep in the new proposal. 

2.  Looking at the latest code in Github, it formats the User Agent --> SDK host as 
            [SDK Host],Version=[SDK host version]
     Could we use this format in the spec too (.NETCoreApp,Version=v2.0 instead of netcore2)

Thank you.

**Comment by stevengum** [comment]
Per standup yesterday, will close this issue as the PRs to address this were merged into master. A new one should be filed to track the adding of component versions (e.g. LUIS, QnA, Storage).
