### ISSUE TITLE
Use Azure.Test.HttpRecorder to record and mock LUIS service responses

### ISSUE THREAD

**Issue by JuanAr** [microsoft/botbuilder-dotnet#826]
We found the [Azure.Test.HttpRecorder](https://www.nuget.org/packages/Microsoft.Azure.Test.HttpRecorder) used in the LUIS [Runtime.Tests](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/CognitiveServices/dataPlane/Language/LUIS/Runtime.Tests/BaseTest.cs#L26-L35) to conditionally hit the external service and store the response in file system and then use this responses to mock the service for unit tests.
Currently, this NuGet is incompatible with NETCOREAPP2.0 but they seem to be working on getting a new version with compatibility.

The purpose of this issue is to check for the compatibility status with NETCOREAPP2.0 and update those unit tests accessing external services to use the `HttpRecorder` component.

**Comment by yochay** [comment]
We can run tests on .NET 4.61, which should be enough for GA. Keep track of this items and pull in the updates as soon as they are ready.

**Comment by cleemullins** [comment]
On hold along with #1338 waiting for dependencies to be updated.

**Comment by cleemullins** [comment]
This remains blocked, as the underlying dependencies are not yet .Net Core. The MockLuisRecognizer as defined by Gabo as part of the testing infrastructure would also address this. 

Punting to 4.5.

**Comment by cleemullins** [comment]
The latest version supports both:
1. .NETCoreApp 2.0
2. Newtonsoft.Json (>= 10.0.3)

I believe we should be able to take this update in the 4.6 cycle.

**Comment by cleemullins** [comment]
Closing.
