### ISSUE TITLE
AzureBlobTranscriptStore.DeleteTranscript(channelId, conversationId) does not delete stored transcript 

### ISSUE THREAD

**Issue by DanDev33** [Microsoft/botbuilder-dotnet#828]
1. Create new AzureBlobTranscriptStore
2. Save user message activity using LogActivityAsync()
3. Retrieve Ids of stored transcripts using ListTranscriptsAsync()
4. Attempt to delete excess stored transcripts using DeleteTranscriptAsync()
    - try/catch returns no error, but transcripts are not deleted.
Example code built with Daily Build v4.0.0.37534 attached.
readme.md details the test logic.

[BlobTranscriptBot.zip](https://github.com/Microsoft/botbuilder-dotnet/files/2272539/BlobTranscriptBot.zip)

**Comment by JeffCordes** [comment]
It looks like the id gets Uri.EscapeDataString(key) as it is saved.  however when you get the transcripts you are getting its already escaped version, and the delete is escaping it again.

try..  await _myTranscripts.DeleteTranscriptAsync("emulator", Uri.UnescapeDataString(thisChannelId));

It is expecting the unescaped version of the conversationId.

@DanDev33

**Comment by DanDev33** [comment]
Thanks Jeff,

That worked great. I preferred to move the string conversion up to where the conversationIDs were initially stored, but the end result was the same.

foreach (var item in pagedResult.Items)
{
     // Make sure we store an unescaped conversationId string.
     var strConversationId = item.Id;
     storedTranscripts.Add(Uri.UnescapeDataString(strConversationId));
}

For the released product, should ListTranscriptsAsync() ensure that it  returns an UnescapedDataString for the Id?

-Dan

**Comment by JasonSowers** [comment]
I have addressed this in #869
