### ISSUE TITLE
Enable Bot.Builder.Classic (V3) dialog to run side-by-side with V4 dialogs

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-dotnet#835]
The classic namesape enables to run V3 dialogs wrapped in a V4 bot. To provide continuation from V3 to V4, we need to find a way to pass enough context (state) and control to a V4 dialog. For example. V3 root dialog has two child dialogs, order, and name. Once both dialog complete, the root dialog can call a V4 dialog (to collect address information). 

The ask is to provide the capability to have an existing V3 dialog 'get extended' with a V4 dialog and be able to pass state and context between the two dialogs systems.

**Comment by tomlm** [comment]
I think Skillls means we drop this?  Assigning to Vishwac to evaluate.

**Comment by gabog** [comment]
Closed via Skills feature.
