### ISSUE TITLE
Host V3 dialogs in a V4 bot sample

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-dotnet#836]
Add a sample, showing V3 dialogs hosted within a V4 bot, using an adapter. 

- V3 should have a root dialog, with two child dialogs that collect information.
- pass state (received information) between V3 dialogs and V4 bot.
- Create a new dialog, using V4 based on data collected with the V3 dialogs.  

related to https://github.com/Microsoft/botbuilder-dotnet/issues/835

**Comment by gabog** [comment]
Closed via the Skills feature
