### ISSUE TITLE
Issue with ChoicePrompt

### ISSUE THREAD

**Issue by rcervantes** [Microsoft/botbuilder-dotnet#837]
The issue is simple to replicate:

- Create a ChoicePrompt in C# Bot Builder V4.
- Fill the List<Choice> with the following values: 
    - "Word1, Word2 Word3 Word4"
    - "Word1 Word2, Word3 Word4"    
    - "Word1 Word2 Word3, Word4"

PD: If you see with detail is almost the same string a comma makes the difference.

- The issue is able to reproduce when you pick the Item 2 or 3 of the List, since always is returning the Item 1.

- This scenario is able to reproduce in the SDK: 4.0.1-preview and is not present if more words are different in the List<Choice> e. g. if I create a List<Choice> but with a Guid.NewGuid().ToString() values the choice prompt is working properly.

Regards,
RC

**Comment by johnataylor** [comment]
Can you clarify the issue you are having?

The default tokenizer splits the utterance based on punctuation and some emojis. Given that, I'm not sure how much sense it makes having punctuation in the choice data itself at least for the default case.

You can replace the tokenizer and still use the bulk of the choice prompt machinery.

**Comment by rcervantes** [comment]
Sure @johnataylor, sorry for the delay, I would like to clarify I'm not using LUIS, my scenario was very simple, I request the fullname in a dialog prompt and use a custom logic to get the multiple combinations to let the user pick the correct name and lastname. 

e.g.
**Fullname:** 
Chris Alexander Redfield Valentine
**Combinations:** 
Chris, Alexander Redfield Valentine
Chris Alexander, Redfield Valentine
Chris Alexander Redfield, Valentine


```
Dialogs.Add("ProfileDialog",
                new WaterfallStep[]
                {
                    AskFullnameDialog,
                    GetFullnameDialog,
                    ListCombinationsDialog,
                    DecomposeNameLastnameDialog,
                    async (dc, args, next) =>
                    {
                        //ending dialog
                        var userState = UserState<UserState>.Get(dc.Context);
                        userState.Profile.Fullname = dc.ActiveDialog.State["fullname"].ToString();
                        userState.Profile.Name = dc.ActiveDialog.State["name"].ToString();
                        userState.Profile.Lastname = dc.ActiveDialog.State["lastname"].ToString();
                        await dc.End(dc.ActiveDialog.State);
                    }
                }
            );
List<(string name, string lastname)> combinations = NameHelper.Combinations(dc.ActiveDialog.State["fullname"].ToString());

List<Choice> choices = new List<Choice>();
foreach ((string n, string l) in combinations)
{
     StringBuilder sb = new StringBuilder();
     sb.Append($"{n},{l}");
     choices.Add(new Choice { Value = $"{sb.ToString()}" });
}         
 ChoicePromptOptions choicePromptOptions = new ChoicePromptOptions { Choices = choices, RetryPromptString = $"{message}" };

var message ="Just pick a numeric option";
 await dc.Prompt("ListCombinationsDialog", $"{message}", choicePromptOptions);

private async Task DecomposeNameLastnameDialog(DialogContext dc, object result, SkipStepFunction next)
        {
            var choice = (result as ChoiceResult).Value.Value;
}
```
The issue is presented when I received the ChoiceResult in the next dialog when I pick the Item 2 or 3 of the Choices, since always is returning the Item 1.

Please let me know if this comment helps.

Thanks,
RC

**Comment by johnataylor** [comment]
@rcervantes I have been trying the following code and this appears to work correctly now. But I should be clear, I'm working on the master branch which is somewhat ahead of the published packages on NuGet. And we have slightly changed the API but its fairly minor. Anyhow here is the code I tried:

```
        private static WaterfallDialog CreateWaterfall2()
        {
            return new WaterfallDialog("test-waterfall", new WaterfallStep[] {
                WaterfallStep21,
                WaterfallStep22,
            });
        }

        private static async Task<DialogTurnResult> WaterfallStep21(DialogContext dc, WaterfallStepContext stepContext)
        {
            // we are only interested in Message activities - any other type of activity we will immediately complete teh waterfall
            if (dc.Context.Activity.Type != ActivityTypes.Message)
            {
                return await dc.EndAsync();
            }

            var choices = new List<Choice>
            {
                new Choice { Value = "Chris, Alexander Redfield Valentine" },
                new Choice { Value = "Chris Alexander, Redfield Valentine" },
                new Choice { Value = "Chris Alexander Redfield, Valentine" },
            };

            var message = "Just pick a numeric option";

            var choicePromptOptions = new PromptOptions
            {
                Choices = choices,
                Prompt = MessageFactory.Text($"{message}"),
                RetryPrompt = MessageFactory.Text($"{message}")
            };

            return await dc.PromptAsync("choice", choicePromptOptions);
        }

        private static async Task<DialogTurnResult> WaterfallStep22(DialogContext dc, WaterfallStepContext stepContext)
        {
            // step context represents values from previous (waterfall) step - in this case the first number
            if (stepContext.Values != null)
            {
                var choiceResult = (FoundChoice)stepContext.Result;
                await dc.Context.SendActivityAsync($"Thanks for '{choiceResult.Index}' {choiceResult.Value}");
            }

            return await dc.EndAsync();
        }
```

And I get the choice I would expect when I pick the number. If you are interested in trying this out you can build the main solution and drop this code into an interactive test bot called TestBot in the test tree. And then run the emulator against it.

Anyhow it seems to work as expected (at least on the latest code) and so I'm going to close this one out. If you do have problems (or you think my repo scenario is not good) please don't hesitate to comment on this (and include a mention) and then I'll drill int further.
