### ISSUE TITLE
Transcript for user and bot is not available. In bot V3.0 there is IActivityLogger  , can we have similar sample using V4.0

### ISSUE THREAD

**Issue by chintan3100** [Microsoft/botbuilder-dotnet#841]
I would like to see all conversation history, Including bot and user's responses

For Ex.

Bot : Hi,
User : Hellow
Bot : What is your location
User : some city
Bot : Please enter your current location 

..........

**Comment by sgellock** [comment]
Please refer to the TranscriptLogger middleware

**Comment by utkarsh24** [comment]
could you please add link of code sample which uses transcriptLogger middleware?
