### ISSUE TITLE
Failed to validate incoming Facebook message. Make sure your FacebookAppSecret is entered correctly.

### ISSUE THREAD

**Issue by vovanb** [Microsoft/botbuilder-dotnet#843]
Hi
Suddenly getting error in Facebook channel. Did all reconfiguration - same problem.
Thanks

**Comment by stevengum** [comment]
Cross linking with #750

**Comment by stevengum** [comment]
@vovanb I'm closing this issue as it's directly related to #750. Can you please see my comment there and provide the additional requested information.
