### ISSUE TITLE
NumberPrompt should be able to return multiple numbers

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#844]
The prompt is basically a stateful wrapper around the recognizer. The number recognizer is able to return multiple results (all the numbers found in the utterance) so the prompt should follow and be able to do the same.

DateTimePrompt is similar except slightly more complicated because there can be multiple resolutions of each result.

**Comment by Stevenic** [comment]
I think this would be a new prompt type called Multi-Number. Most bots aren't going to be prepared to accept more than a single number. A better example is choices. I'd love to see us develop a MultiChoicePrompt but i think it has different semantics then a single ChoicePrompt so needs to be a separate prompt.

**Comment by sgellock** [comment]
Let's address with a sample
