### ISSUE TITLE
Prompt results don't include all the recognizer details like Start and End

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#846]
The resolution for DateTime will include character offsets Start and End, this information is lost to the application and the validator.

If this recognizer data is useful then there should be a way for the application (at least the prompt validator) to have access to this data. 

(The DateTimeResolution structure also has Start and End but this is for date or time range start and end values.)

**Comment by sgellock** [comment]
Let's address with a sample
