### ISSUE TITLE
not able to get skype userId, or email of User using skype channel

### ISSUE THREAD

**Issue by NidhiWK** [Microsoft/botbuilder-dotnet#848]
when i tried i am getting one unique id(seems like channel id) and name(which is not username so its not unique),  I have a scenario where bot needs to ping user using skype id , is there any way in V4 version to achive this. 
In another scenario when user add bot in skype and send message then i want to get my email id or skype userid , how to achive this?

**Comment by sgellock** [comment]
Thanks for the ticket @NidhiWK.  Please ask your question over in https://stackoverflow.com/questions/tagged/botframework
