### ISSUE TITLE
OAuthPrompt missing code

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#856]
Refactor missed the following:

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L307

The current implementation in the JavaScript should be complete and correct. Here is a pointer:

https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L249

**Comment by JasonSowers** [comment]
Look into possibly adding an async bool to OAuthPrompt like "isLoggedIn"

**Comment by JasonSowers** [comment]
#864

**Comment by johnataylor** [comment]
This is fixed by #864
