### ISSUE TITLE
BotStateSet.SaveChangesAsync doesn't gracefully handle Serialization errors

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-dotnet#874]
If a developer (accidentally) adds a type to ActiveDialog.State that has a property that can't be serialized all BotState is lost and no exception is raised to help the developer understand the root cause. In this case, subsequent messages weren't being routed to an ActiveDialog because it wasn't active due to a prior serialization error.

Stepping through, it appears the exception is raised by the IsChanged/ComputeHash method on CachedBotState which BotStateSet calls as part of SaveChangesAsync

```
            public bool IsChanged()
            {
                return Hash != ComputeHash(State);
            }

            internal string ComputeHash(object obj)
            {
                return JsonConvert.SerializeObject(obj);
            }
```

This was very hard to diagnose, an exception with a clear message detailing that State had been lost due to a serialization error would be have been much appreciated.

**Comment by drub0y** [comment]
May I ask what type you were using that couldn't be serialized so that I can try to repro this? I'd be shocked if there wasn't some kind of exception occurring somewhere. I started looking at the possible call stacks that lead down this path expecting to find a try/catch that just swallows exceptions, but I'm not seeing it.

**Comment by darrenj** [comment]
I'm going to mark this as closed. There was a bug on my side that the exception management wasn't being wired up on an edge case resulting in the issue. The code does raise the exception gracefully :-)

In this case the configuration object had some undesirable contents :) "Serializing delegates is not supported on this platform"
