### ISSUE TITLE
Fix logic in welcoming users sample

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#879]
re: 2.AspNetCore-ConversationUpdate-Bot/[ConverstaitonUpdateBot.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/master/samples-final/2.AspNetCore-ConversationUpdate-Bot/ConversationUpdateBot.cs)

Shouldn't the test for greeting users be one of the following? (As the sample is now, arbitrarily checks just the first entry in the members added collection.)

```csharp
var activity = turnContext.Activity.AsConversationUpdateActivity();
if (activity.MembersAdded.Any(member => member.Id != activity.Recipient.Id))
{
    // Send a welcome message to all members in the conversation.
}
```

or

```csharp
foreach(var member in activity.MembersAdded.Where(x => x.Id != activity.Recipient.Id))
{
    // Send a direct message to each user.
}
```

**Comment by JasonSowers** [comment]
Addressed in #897
