### ISSUE TITLE
DCR: Make ConnectorClient() private and use ConnectorClient Factory

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#883]
**Background**

1. HttpClient is significantly faster if you cache and reuse an HttpClient
2. ConnectorClient is AutoRest generated subsclass of ServiceClient which manages the HttpClient
3. There is no way to make ServiceClient cache the http client, guidance from AutoRest team is that it is intended to be used as a singleton.
4. To get best perf a bot should be caching ConnectorClients
5. ConnectorClients have serviceUrl/creds associated with them so we actually need a dictionary to cache

**Issue:**

1. The generated ConnectorClient class is a simple public ctor
2. Our samples all show pattern of newing up a connector client object and using it which will lead to serious perf problems.

I have a delta which changes the BotFrameworkAdapter to do the right thing, which will mitigate our usage pattern, but it doesn't prevent developers from shooting themselves in the foot.

**Proposal**

1. change ConnectorClient from public to protected
2. Define IConnectorClientFactory interface 
3. Create a default implementation which caches based on ServiceUrl and credentials.ConnectorClient.Create() class factory which caches appropriate instances.
4. Change BotFrameworkAdapter to optionally take an IConnectorClientFactory and use the default one if not provided one.

**Benefits**
* The only way to create connectorclients would be via a caching class factory
* The policies of the class factory can be changed and evolve

**Negatives**
* this deviates from other languages which don't have this issue
* This adds more complexity

**Comment by sgellock** [comment]
Unless we feel this MUST go for our next release, I'm moving it to the backlog to consider for October

**Comment by drub0y** [comment]
IMHO this bigger architecture decision doesn't need to be made for next release so it's fine to put it on the backlog. It became even more complicated given [my latest realization](https://github.com/Microsoft/botbuilder-dotnet/pull/875#pullrequestreview-149523476) on #875. 

We should at least temporarily fix #875 either by taking @tomlm 's change as is for now or by reverting that and going with quick change to `ConnectorClient` (to expose proper constructor) and passing in the configured `HttpClient` we already set up to use.

The impact of _not_ taking any action will be resource starvation in the form of TCP connections dangling in dangling `TIME_WAIT` state under any sufficient load.

**Comment by gabog** [comment]
We can't make breaking changes and hide something that is currently public but we can look at improving HttpClients and deprecate old methods.

**Comment by johnataylor** [comment]
The issue we have is that the ideal factoring in dotnet core would be to use the new (relatively new) HttpClientFactory behavior built into ASP. However, this isn't available in the older Web Api.

The best approach is probably to focus on the new framework.

**Comment by johnataylor** [comment]
The immediate task for adapter clean up in R10 is to fill the gaps in the unit testing. Then we will look at deeper refactoring such as this.

**Comment by mrivera-ms** [comment]
Reviewed with the SDK team. This is no longer needed.
