### ISSUE TITLE
CatchException middleware

### ISSUE THREAD

**Issue by garypretty** [Microsoft/botbuilder-dotnet#887]
@cleemullins @tomlm Has the CatchException middleware component been removed from the SDK?  If so, do you have any objection to us adopting it into the Community Project?

Also planning to do the same for the AzureTableStorage as well.

**Comment by JonathanFingold** [comment]
It was removed, but there is now an `OnTurnError` property that you can specify in the BotFrameworkOptions object, and it gets set on the adapter.

**Comment by johnataylor** [comment]
@garypretty the advantage of the OnTurnError property is that it catches the exception wherever it occurs in the turn (whether in the application or the middleware).

The problem we found with using a middleware for this is that where you place it in the stack can alter whether you catch the exception and that can get confusing.

This doesn't preclude you from catching or throwing exceptions in middleware - if that's how you want your code to work - the OnTurnError is the last change catch all and comes after everything else.

**Comment by garypretty** [comment]
Thanks for the explanation of the thinking for this change. It makes sense. We might adopt the middleware approach in the community repo to show / allow people to catch particular exceptions etc. but I'll ensure we explicitly call out the OnTurnError property as part of the picture. Thanks.
