### ISSUE TITLE
OAuthPrompt & Dialog Teardown

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-dotnet#895]
I can only repro this behaviour when using OAuthPrompt, not other Prompt types. I have a custom Dialog class: `public class SkillDialog : Dialog`

In this class I override DialogBegin and DialogContinue in order to leverage a Custom Adapter. After calling ProcessActivity on the Adapter I go through responses. I listen out for an Event to be received which I want to handle as a special case.

Within this Dialog I want to use the OAuthPrompt which works perfectly but after PromptAsync completes it tears down my ActiveDialog (ActiveDialog is set to NULL). This is highly undesirable as my Skill disappears from the stack.

This happens in both OAuthPrompt scenarios (cached and signin prompt). I would expect my original Dialog to be resumed in both cases.

```
OAuthPrompt oAuth = new OAuthPrompt("SkillAuth",
new OAuthPromptSettings()
{
    ConnectionName = "yourconnectname",
    Text = "Please Sign In",
    Title = "Sign In",
    Timeout = 300000 // User has 5 minutes to login 
}, (PromptValidator<TokenResponse>)AuthPromptValidator);

DialogTurnResult dtr = await dialogContext.PromptAsync("SkillAuth", new PromptOptions());
                    
if (dtr.HasResult)
{
  // Cached token, send on to skill                        
}
```

**Comment by darrenj** [comment]
The recent checkin by @lauren-mills and John to remove the fixed VerifyTurnResult from DialogContext has enabled me to override DialogResumeAsync and return my own DialogTurnResult saying my dialog is still active rather than the fixed/default behaviour previously that tore my dialog down.

I'm now unblocked but worth double checking the logic here for the usage scenarios before closing. Removing blocker tag

**Comment by chintan3100** [comment]
I am unable to find OAuthPrompt & OAuthPromptSettings class. Can you please help me?

**Comment by sgellock** [comment]
Please clarify what the ask is here.  thanks

**Comment by lauren-mills** [comment]
This is no longer causing issues on our side.
