### ISSUE TITLE
ComponentDialog constructor should [probably] set InitialDialogId to Id

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#905]
The current implementation appears to set the InitialDialogId property to the first dialog added via `AddDialog`. If one adds the prompts first and the waterfall dialog after that, one gets strange errors unless one includes the following line in the constructor:

```csharp
public CheckInDialog(string dialogId) : base(dialogId)
{
    InitialDialogId = Id;
    // Add prompts.
    // Add main dialog (with an ID of Id) and any sub-dialogs.
```

**Comment by johnataylor** [comment]
This is by design @stevenic but we may want to make it clear in the documentation.
