### ISSUE TITLE
Make it easy to consume bot configuration when creating instances of LUIS and QnA recognizers.

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-dotnet#908]
Something like this would be much desirable - 

luisRecognizer = new LuisRecognizer(botConfig.findServiceByNameOrId(LUIS_CONFIGURATION));

without this, today, you will have to manually construct the LUIS and QnA Maker recognizer options.

**Comment by stevengum** [comment]
- [ ] **.NET:** #1011
- [ ] **JS:** #

**Comment by johnataylor** [comment]
added constructors that take configuration service
