### ISSUE TITLE
Enable OAuthPrompt settings to be controlled on a per-dialog basis

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-dotnet#911]
There may be alternative ways of resolving this but the recommended way (sample) to leverage the OAuthPrompt is as follows and is typically called once your Bot is activated to wire up the various dialogs.
```
dialogs.Add(new OAuthPrompt(AUTH_LOCALMODE,
  new OAuthPromptSettings()
  {
    ConnectionName = "adauth",
    Text = $"Authentication",
    Title = "Signin",
    Timeout = 300000 // User has 5 minutes to login 
  }, (PromptValidator<TokenResponse>)AuthPromptValidator));

```
This works fine when you have a consistent ConnectionName used for all users/scenarios. However in my scenario there is a need on a per-user basis to select the ConnectionName used for a given user - e.g. for a O365 or Google token hence there needs to be the ability to provide the ConnectionName when performing a prompt - a bit like we can do with PromptOptions perhaps?

`  return await dialogContext.PromptAsync(AUTH_SKILLMODE, myPromptOptions);`

**Comment by JasonSowers** [comment]
@darrenj are you aware of a way to work around this or need guidance?
