### ISSUE TITLE
https://aka.ms/about-bot-file routes to dev.botframework.com

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-dotnet#914]
This should go to a docs article.

**Comment by stevengum** [comment]
This link just redirects to microsoft.com: https://aka.ms/about-bot-adapter

**Comment by vishwacsena** [comment]
Also the following aka.ms links need right target URL - 
bot-framework-emulator-v4-overview
bot-framework-emulator-create-dispatch

**Comment by vishwacsena** [comment]
Fixed. 

https://aka.ms/about-bot-file -> https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/bot-file.md

https://aka.ms/about-bot-adapter -> https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=cs

https://aka.ms/bot-framework-emulator-v4-overview -> https://github.com/microsoft/botframework-emulator/wiki

https://aka.ms/bot-framework-emulator-create-dispatch -> https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch#create-bot-dispatch-using-bot-file
