### ISSUE TITLE
JS: LuisRecognizer.topIntent() returns a string, C# has RecognizerResult.GetTopScoringIntent()

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-dotnet#918]
And there is no LuisRecognizer.TopIntent() on the C# [LuisRecognizer implementation](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs).

- [x] Add TopIntent to LuisRecognizer.cs (see #1013)

**Comment by sgellock** [comment]
John and StevenG will discuss and decide a solution for Ignite

**Comment by stevengum** [comment]
Closing as we decided not to add `RecognizerResult.getTopScoringIntent()` to the JS side. [`RecognizerResult`](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/recognizerResult.ts) is an interface in JS.

C# LuisRecognizer now has [`TopIntent()`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L57-L84).
