### ISSUE TITLE
Check our Nuget package paths

### ISSUE THREAD

**Issue by daveta** [Microsoft/botbuilder-dotnet#920]
On the WebAPI sample for EchoBot, getting the following error:

`Error occurred while restoring NuGet packages: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

We have to look into this, and determine which package has a long path and fix. This issue appears to be several years old:

NuGet/Home#3324

**Comment by drub0y** [comment]
Well it's relative to the person's solution path so there's really no solving this for all people. At a certain depth this would happen for any sufficiently long enough package name.

**Comment by daveta** [comment]
Ah, let me to truncate a boatload of path..
