### ISSUE TITLE
DialogSet.Add should return a DialogSet, not a Dialog

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#924]
Current code is written this way:
```
 _dialogs = new DialogSet(this._stateAccessors.ConversationDialogState);
_dialogs.Add(OAuthHelpers.Prompt(ConnectionSettingName));
_dialogs.Add(new ChoicePrompt("choicePrompt"));
```
If the Add returned a Dialog Set, we could use fluent contstruction. 
```
 _dialogs = new DialogSet(this._stateAccessors.ConversationDialogState)
  .Add(OAuthHelpers.Prompt(ConnectionSettingName));
  .Add(new ChoicePrompt("choicePrompt"));
```

**Comment by sgellock** [comment]
If we take this for v4, then samples and docs need to be updated to reflect the change

**Comment by tomlm** [comment]
**Botbuilder-dotnet**
- [ ] PR
- [ ] Checked in
**Botbuilder-js**
- [x] PR
- [ ] Checked in

**Comment by sgellock** [comment]
ComponentDialog.addDialog() should return a ComponentDialog

**Comment by tomlm** [comment]
separate DCR
