### ISSUE TITLE
DCR: Consistency of method names across ComponentDialog and Dialog

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-dotnet#926]
ComponentDialog has methods
dialogBegin
dialogContinue
dialogResume
dialogReprompt
dialogEnd
onDialogBegin
onDialogContinue
onDialogEnd
onDialogReprompt

DialogContext
begin()
cancelAll()
continue()
end()

etc.
Shouldn’t these be the same method names?

**Comment by sgellock** [comment]
docs and samples need to be updated

**Comment by sgellock** [comment]
Can we get a final list of what the exact name changes were that went into the PR so we can optimize for the Docs Team

**Comment by carlosscastro** [comment]
PRs

- [ ] dotnet PR
- [ ] dotnet Merged
- [ ] js PR
- [ ] js Merged
- [ ] samples PR
- [ ] samples Merged

**Comment by cleemullins** [comment]
Merged in the dotNet changes.

**Comment by carlosscastro** [comment]
Closing this one because we have a node.js counterpart, and also the samples will be done next week when we do a full pass on sample.

@Kaiqb @yochay  @sgellock  This PR affects documentation. Let me know if you have questions!
