### ISSUE TITLE
Improper Caching / Disposing of ConnectorClient

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#929]
The ClientConnector is disposed on every turn as part of the end-of-turn cleanup. This interferes with the caching of HTTP Connections and other optimizations that @tomlm put in place. 

@daveta has created PR #927 which puts in a short-term fix for this, but it's ugly. 

A better solution for managing durable infrastructure resources needs to be put in place.

**Comment by tomlm** [comment]
This is exactly what DCR #883 was created to address.
