### ISSUE TITLE
Error in azure web app deployment

### ISSUE THREAD

**Issue by rcervantes** [Microsoft/botbuilder-dotnet#930]
Hello all, I'm building a demonstration bot using the most recent libraries from master branch, however, locally is working properly but after perform the docker deployment I'm receiving the following error: 

> POST to ibebot failed: POST to the bot's endpoint failed with HTTP status 500 POST to the bot's endpoint failed with HTTP status 500
> 
> Microsoft.Bot.Schema.BotException:
>    at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.3, Culture=neutral, PublicKeyToken=null)
> Inner exception System.Exception handled at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext:
>    at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__30.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.3, Culture=neutral, PublicKeyToken=null)

The source of my code is right here: 
https://github.com/rcervantes/intelligent-bot-experience
The docker file I'm using is: 
https://github.com/rcervantes/intelligent-bot-experience/blob/master/source/Dockerfile

The Bot is working fine locally, but once is published on a Web App there is an error in the endpoint, I did another publication with the same Docker config but using other EchoBot sample and is working properly using the nuget packages not the master source.

Can someone give me some hints please, I believe could be some issue in the Connector, I caught the exception using App Insights.

Thanks in advance.
RC

**Comment by sgellock** [comment]
close due to inactivity
