### ISSUE TITLE
DCR: BotStateSet should be renamed to BotStateMiddleware (or better yet BotStateSaveMiddleware)

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#935]
Our naming convention of "middlware" needs to be followed. This applies to BotState, BotStateSet, and other components that implement IMiddlware. 

This shows up, for example, here:
```
public class JobState : BotState
{
```
... where it's *far* from obvious that JobState is a Middleware component.

**Comment by tomlm** [comment]
No, BotState should NOT be middleware.
BotStateSet should be renamed to AutoSaveStateMiddleware

**Comment by tomlm** [comment]
**BotBuilder-dotnet**
- [ ]  PR
- [ ]  Checked In

**BotBuilder-js**
- [ ]  PR
- [ ]  Checked In

**Comment by sgellock** [comment]
Can we get a final list of the name changes so we can optimize for the Doc team?

**Comment by tomlm** [comment]
BotStateSet still exists and has collection of BotState with 2 methods, 
    loadAll()/LoadAllAsync()
    saveAllChanges()/SaveAllChangesAsync()

These do parallel load/save operations against the collection.

AutoSaveStateMiddleware uses the BotStateSet.SaveAllChanges() to save on the end of the turn.
