### ISSUE TITLE
Update Welcome card for Basic Bot template

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-dotnet#944]
- [x] Update image to point to a CDN
- [x] Update text - per new copy
- [x] update action items/ buttons

**Comment by mewa1024** [comment]
![welcome-card-banner](https://user-images.githubusercontent.com/39317542/45442827-f0ac7e80-b677-11e8-9678-1b7866b1f4bb.png)

**Comment by mewa1024** [comment]
JSON for card with design changes is in the comment below. Once the image is uploaded to the CDN we will need to edit the image's URL.

**Comment by mewa1024** [comment]
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Image",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtB3AwMUeNoq4gUBGe6Ocj8kyh3bXa9ZbV7u1fVKQoyKFHdkqU",
            "size": "stretch"
        },
          {
            "type": "TextBlock",
            "spacing":"medium",
            "size": "default",
            "weight":"bolder",
            "text": "Welcome to Bot Framework!",
            "wrap": true,
            "maxLines": 0
        },
        {
            "type": "TextBlock",
            "size": "default",
            "isSubtle": "yes",
            "text": "Now that you have successfully run your bot, follow the links in this Adaptive Card to expand your knowledge of Bot Framework.",
            "wrap": true,
            "maxLines": 0
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "Get an overview",
            "url": "https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0"
        },
        {
            "type": "Action.OpenUrl",
            "title": "Ask a question",
            "url": "https://stackoverflow.com/questions/tagged/botframework"
        },
        {
            "type": "Action.OpenUrl",
            "title": "Learn how to deploy",
            "url": "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0"
        }
    ]
}

**Comment by daveta** [comment]
For C#:
 https://github.com/Microsoft/BotBuilder-Samples/pull/385 is fixed.

**Comment by cleemullins** [comment]
This was merged in C#.

**Comment by yochay** [comment]
PR waiting for samples repo  - https://github.com/Microsoft/BotBuilder-Samples/pull/403
