### ISSUE TITLE
DialogState should have a default constructor

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#953]
The `DialogState` class currently has a constructor of:

```
public DialogState(List<DialogInstance> stack = null)
```

This however is not exactly the same as having a default constructor that takes no params as when one tries to define a method with a generic constraint of `new()` it will not be allowed in that case. 

Suggest removing the default `null` value from the current constructor and then just creating an actual empty constructor that delegates to that version with a `null` value:

```CSharp
public DialogState() : this(null)
{
}

public DialogState(List<DialogInstance> stack)
{
   ...existing implementation here...
}
```

FWIW I stumbled across this when I pulled the latest bits and this regressed the use of one of my generic helper methods that I have written in some code that I'm using to vet some the Dialog APIs.

**Comment by johnataylor** [comment]
@drub0y should be good now - thanks for the heads up.
