### ISSUE TITLE
LUIS LuisApplication bad error message

### ISSUE THREAD

**Issue by daveta** [Microsoft/botbuilder-dotnet#974]
Low priority! Punt to 4.1

## Version
Latest feed.
## Describe the bug

Error message complains about subscription key and prints application id.

  >>throw new ArgumentException($"\"{applicationId}\" is not a valid LUIS subscription key.")

See context below:

      /// <summary>
        /// Initializes a new instance of the <see cref="LuisApplication"/> class.
        /// </summary>
        /// <param name="applicationId">LUIS application ID.</param>
        /// <param name="endpointKey">LUIS subscription or endpoint key.</param>
        /// <param name="endpoint">LUIS endpoint to use like https://westus.api.cognitive.microsoft.com.</param>
        public LuisApplication(string applicationId, string endpointKey, string endpoint)
        {
            if (!Guid.TryParse(applicationId, out var appGuid))
            {
                throw new ArgumentException($"\"{applicationId}\" is not a valid LUIS application id.");
            }

            if (!Guid.TryParse(endpointKey, out var subscriptionGuid))
            {
                throw new ArgumentException($"\"{applicationId}\" is not a valid LUIS subscription key.");
            }

**Comment by cleemullins** [comment]
resolved
