### ISSUE TITLE
Build improperly re-packages NuGet files

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#977]
The build cracks the Nuget pacakges, signs them, then repackages. 

When it does this, it used a "/" instead of a "\". 

Replace the complicated powershell script with:
ZipFile.CreateFromDirectory(folder, nupkg);

**Comment by cleemullins** [comment]
The impact of this is that our signed NuGet packages likley don't work properly on Linux, as they're not correctly packaged.

**Comment by amthomas46** [comment]
Maybe this is related to #981

**Comment by cleemullins** [comment]
@tomlm resolved this. Root cause is an issue in the powershell script that creates the zip file for the Nuget. It uses the incorrect "/,\" and didn't work on Linux based systems.
