### ISSUE TITLE
Wiki needs better instruction on referencing locally-built nuget packages

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#98]
When building the current BotBuilder project libraries, `nupkg` files are created. Due to the workflow of VS 2017, these can't be put in a post-build step to copy to a central location (eg: `/build`).

Users aren't directed to take those nuget packages and put them in a common spot, nor how to create a nuget package source for use in their own bot.

Suggest adding direction to do relevant steps (manually copy from location x, y, z to here, then go to VS and add nuget package source to that location) or simply run the following operations from a VS 2017 command line in the bot builder repo root directory:
~~~
for /R "%cd%\libraries" %%f in (*.nupkg) do xcopy /Y "%%f" "%cd%\build"

nuget sources Remove -Name bfv4-local
nuget sources Add -Name bfv4-local -Source %__startPath%\build
~~~

Restart VS after running the above commands, and local nuget packages are available as dependencies to any bot solution

**Comment by daltskin** [comment]
+1

**Comment by tessmichi** [comment]
+1

**Comment by cleemullins** [comment]
@johnataylor @Kaiqb

**Comment by cleemullins** [comment]
To add to this, the locally build issues that folks are seeing today are a leftover from a publishing bug that @tomlm has (we think) fixed as of earlier today. Packages seem to be correctly published to the standard NuGet feed.

**Comment by JonathanFingold** [comment]
Verified that the NuGet packages are currently available from https://api.nuget.org/v3/index.json. Will update the topic this morning.

**Comment by Kaiqb** [comment]
Topic updated.
