### ISSUE TITLE
The current Microsoft.Bot.Connector.AspNetCore v2.0.1.38846 does not allow referring v4.0.7 of Microsoft.Bot.Connector library

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-dotnet#998]
## Version
4.0.7

## Describe the bug
The current Microsoft.Bot.Connector.AspNetCore with version 2.0.1.38846 does not allow referring the 4.0.7 version of Microsoft.Bot.Connector library (The ICredentialProvider’s namespace has moved).

**Comment by johnataylor** [comment]
This scenario attempts to mix V3 and V4 abstractions in the same project. There are potentially places where this will work but the intention is that the V4 packages all work together. We are working on what best practices would be for mixing existing bot logic written in V3 with v4.

**Comment by johnataylor** [comment]
@willportnoy 

It was added to support the V3 package's .NET Standard platform integration into the ASP.NET Core framework.

Could the V3 and V4 versions of the connector be merged?  That seems like the right thing to do and would probably help with issues like this one.

**Comment by johnataylor** [comment]
Note this is the V3 SDK. V3 SDK: https://github.com/Microsoft/BotBuilder/tree/3.0/CSharp/Library/Microsoft.Bot.Connector.AspNetCore

**Comment by benbrown** [comment]
This work will have to be done in the V3 repo

**Comment by johnataylor** [comment]
The V3 Connector appears to contain the appropriate SendConversationHistoryAsync call. You will need a recent version of the package:

https://www.nuget.org/packages/Microsoft.Bot.Builder/3.16.1.38846

Here is some sample code:

```
var credentials = new MicrosoftAppCredentials();
var serviceUrl = activity.ServiceUrl;
var conversationId = activity.Conversation.Id;

var client = new ConnectorClient(new Uri(serviceUrl), credentials);

var transcript = new Transcript(_activities);

var resource = await client.Conversations.SendConversationHistoryAsync(conversationId, transcript);
```
