### ISSUE TITLE
Add an option to allow bots to acquire tokens from a specified tenant

### ISSUE THREAD

**Issue by mingweiw** [microsoft/botbuilder-dotnet#999]
**Is your feature request related to a problem? Please describe.**
Some FSI (financial service industry) customers (ex. banks) have an AAD feature call [tenant restriction](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/tenant-restrictions) enabled on their network. In these cases the bot must acquire a token from a whitelisted customer tenant. We need an option in the SDK to allow the developer to specify which tenant to acquire the token from.

**Describe the solution you'd like**
Add a setting similar to "MicrosoftAppId". Maybe "ChannelTenantId"?

**Comment by Stevenic** [comment]
Can we get more details on how this should be implemented?

**Comment by benbrown** [comment]
We're going to wait to make sure that this approach works for the customer before scheduling this change (per @sgellock)

**Comment by mingweiw** [comment]
For implementation I was thinking
1. developer add an appsetting say
```xml
<add key="ChannelTenantId" value="XXX" />
```
2. If this setting is present, in the Bot.Connector, we change `JwtConfig.ToChannelFromBotLoginUrl` from its hardcoded value to `https://login.microsoftonline.com/XXX/oauth2/v2.0/token`.

I think that's all that's required.

The customer is currently using V3 SDKs. CSE said they are willing to try V4 as well. They are blocked on deploying their bot for Teams channel. We discussed this approach with the customer and it looks like it will work. At this point they need
1. An SDK drop from us to try it out.
2. Teams to update their channel to accept the new tokens on requests originating from a tenant restricted network. We've discussed this with Teams dev. Konstantin Lutskiy is looking into dates for this.

We are also evaluating additional service side work to enable this for Direct Line. Currently I think there should be no impact on SDKs from that.

**Comment by benbrown** [comment]
Let's loop in @dandriscoll on this to see if he has any comment.

**Comment by mingweiw** [comment]
Dan was looped in. We chatted about this between Dan / Artur / Jeff / Jim and I earlier.

**Comment by benbrown** [comment]
Thanks for the info @mingweiw, we just wanted to make sure he had visiblity.

**Comment by dandriscoll** [comment]
:-)

One thing we should do is specify the new behavior in our docs before we lock everything down. This will help make sure property names == terminology == concepts.

**Comment by mingweiw** [comment]
Please update the setting name from "ChannelTenantId" to "ChannelAuthTenant". The customer can specify either a guid ID or a verified domain of the tenant for this setting. So "ChannelAuthTenant" is more appropriate. Thanks.

**Comment by sgellock** [comment]
@cleemullins I talked with this team.  It's not a 4.3 issue.  There's work remaining to determine if it's a 4.4 item.

**Comment by gabog** [comment]
Closing as part of R10 triage (done in a previous release).
